# BD-KDD Kidney Disease — ANOVA + DODA Feature Selection

## Experimental objective

Evaluate conventional **ANOVA feature selection** against **ANOVA + DODA clinical-priority re-ranking** on the BD-KDD kidney-disease dataset.

### Important design rule

ANOVA scores **all 24 predictors**. DODA also receives **all 24 predictor scores** and performs the final Top-K selection after clinical-priority fusion.

This is essential: if ANOVA selected Top-K before DODA, DODA could not re-prioritize features outside that preliminary Top-K.

### Dataset

- 988 records
- 24 predictors
- Binary target: `Class`
- `Class = 0`: healthy
- `Class = 1`: kidney disease
- 0 missing values
- 80/20 stratified fixed split for the initial experiment
- 5×5 repeated stratified CV for robustness

In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("../../data/processed/BD-KDD_cleaned.csv")

if not DATA_PATH.is_file():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH.resolve()}"
    )

df = pd.read_csv(DATA_PATH)

print("=" * 70)
print("PROCESSED BD-KDD DATASET")
print("=" * 70)
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

display(df.head())

======================================================================
PROCESSED BD-KDD DATASET
======================================================================
Rows    : 988
Columns : 25

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane,Class
0,58,147,1.025,1,3,0,1,0,0,177,...,43,12342,4.3,1,0,0,1,1,0,0
1,71,142,1.025,2,3,1,0,1,0,247,...,47,7249,3.7,0,1,1,0,1,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,37,4111,3.7,0,0,0,0,0,1,0
3,34,70,1.005,1,3,1,1,0,0,215,...,44,4682,4.0,1,0,1,1,0,1,1
4,62,120,1.020,4,0,1,0,1,0,143,...,54,5161,4.7,0,0,1,0,1,0,1

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

TARGET_COLUMN = "Class"

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

print("=" * 70)
print("FEATURE / TARGET SEPARATION")
print("=" * 70)
print(f"Predictors (X) : {X.shape[1]}")
print(f"Records        : {X.shape[0]}")
print(f"Target (y)     : {TARGET_COLUMN}")
print(f"Target values  : {sorted(y.unique().tolist())}")

assert X.shape[1] == 24, "Expected 24 predictors after removing Class."
assert set(y.unique()) == {0, 1}

display(X.head())
display(y.head())

======================================================================
FEATURE / TARGET SEPARATION
======================================================================
Predictors (X) : 24
Records        : 988
Target (y)     : Class
Target values  : [0, 1]

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Hemo,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane
0,58,147,1.025,1,3,0,1,0,0,177,...,9.3,43,12342,4.3,1,0,0,1,1,0
1,71,142,1.025,2,3,1,0,1,0,247,...,16.9,47,7249,3.7,0,1,1,0,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,16.6,37,4111,3.7,0,0,0,0,0,1
3,34,70,1.005,1,3,1,1,0,0,215,...,15.4,44,4682,4.0,1,0,1,1,0,1
4,62,120,1.020,4,0,1,0,1,0,143,...,13.9,54,5161,4.7,0,0,1,0,1,0

0    0
1    1
2    0
3    1
4    1
Name: Class, dtype: int64

In [3]:
# =============================================================================
# STEP 3: TARGET DISTRIBUTION
# =============================================================================

target_distribution = pd.DataFrame({
    "Count": y.value_counts().sort_index(),
    "Percentage": (y.value_counts(normalize=True).sort_index() * 100).round(2)
})

display(target_distribution)

       Count  Percentage
Class
0        481       48.68
1        507       51.32

In [4]:
# =============================================================================
# STEP 4: DATA TYPE AND MISSING-VALUE CHECK
# =============================================================================

print("=" * 70)
print("DATA TYPES")
print("=" * 70)
display(X.dtypes.to_frame("Data Type"))

missing = pd.DataFrame({
    "Missing Count": X.isna().sum(),
    "Missing Percentage (%)": (X.isna().mean() * 100).round(2)
})

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)
display(missing)

assert X.isna().sum().sum() == 0, "Unexpected missing values detected."

print("No missing values detected. No imputation will be performed.")

======================================================================
DATA TYPES
======================================================================

      Data Type
Age       int64
Bp        int64
Sg      float64
Al        int64
Su        int64
Rbc       int64
Pc        int64
Pcc       int64
Ba        int64
Bgr       int64
Bu        int64
Sc      float64
Sod       int64
Pot     float64
Hemo    float64
Pcv       int64
Wbcc      int64
Rbcc    float64
Htn       int64
Dm        int64
Cad       int64
Appet     int64
Pe        int64
Ane       int64

======================================================================
MISSING VALUES
======================================================================

       Missing Count  Missing Percentage (%)
Age                0                     0.0
Bp                 0                     0.0
Sg                 0                     0.0
Al                 0                     0.0
Su                 0                     0.0
Rbc                0                     0.0
Pc                 0                     0.0
Pcc                0                     0.0
Ba                 0                     0.0
Bgr                0                     0.0
Bu                 0                     0.0
Sc                 0                     0.0
Sod                0                     0.0
Pot                0                     0.0
Hemo               0                     0.0
Pcv                0                     0.0
Wbcc               0                     0.0
Rbcc               0                     0.0
Htn                0                     0.0
Dm                 0                     0.0
Cad                0                     0.0
Appet              0                     0.0
Pe                 0                     0.0
Ane                0                     0.0

No missing values detected. No imputation will be performed.

## Preprocessing decision

The EDA established that BD-KDD contains **zero missing values**. Therefore, no imputation step is included in this notebook.

Feature selection is fitted only on training data/folds. Model scaling is applied only where needed and is fitted only on training data/folds.

In [5]:
# =============================================================================
# STEP 5: FIXED 80/20 STRATIFIED TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)
print(f"X_train : {X_train.shape}")
print(f"X_test  : {X_test.shape}")
print(f"y_train : {y_train.shape}")
print(f"y_test  : {y_test.shape}")

print("\nTraining class distribution:")
display((y_train.value_counts(normalize=True) * 100).round(2))

print("\nTesting class distribution:")
display((y_test.value_counts(normalize=True) * 100).round(2))

======================================================================
TRAIN-TEST SPLIT
======================================================================
X_train : (790, 24)
X_test  : (198, 24)
y_train : (790,)
y_test  : (198,)

Training class distribution:

Class
1    51.27
0    48.73
Name: proportion, dtype: float64

Testing class distribution:

Class
1    51.52
0    48.48
Name: proportion, dtype: float64

In [6]:
# =============================================================================
# STEP 6: FEATURE-SCALE CHECK
# =============================================================================
# ANOVA F-statistics are scale-invariant, so feature selection is performed
# on the original training-fold values.
#
# Scaling is applied later only for Logistic Regression.

print("ANOVA will be fitted on the original training data.")
print("Logistic Regression will be scaled after feature selection.")
print("Random Forest and XGBoost will use the selected features without scaling.")

ANOVA will be fitted on the original training data.
Logistic Regression will be scaled after feature selection.
Random Forest and XGBoost will use the selected features without scaling.

# 1. ANOVA Baseline

ANOVA is used as the statistical feature-selection baseline.

**Important:** ANOVA scores all 24 predictors first. Top-K is applied only after the complete ranking has been generated.

In [7]:
# =============================================================================
# STEP 7: ANOVA SCORES FOR ALL FEATURES
# =============================================================================

from sklearn.feature_selection import SelectKBest, f_classif

anova_selector = SelectKBest(
    score_func=f_classif,
    k="all"
)

anova_selector.fit(X_train, y_train)

anova_scores = pd.DataFrame({
    "Feature": X_train.columns,
    "ANOVA_F_Score": anova_selector.scores_,
    "ANOVA_P_Value": anova_selector.pvalues_
}).sort_values(
    "ANOVA_F_Score",
    ascending=False
).reset_index(drop=True)

anova_scores["ANOVA_Rank"] = np.arange(1, len(anova_scores) + 1)

display(anova_scores)

   Feature  ANOVA_F_Score  ANOVA_P_Value  ANOVA_Rank
0       Bp       8.902625       0.002936           1
1       Su       1.475878       0.224784           2
2       Ba       1.387509       0.239182           3
3       Bu       1.295059       0.255464           4
4      Ane       1.236786       0.266431           5
5     Rbcc       0.835335       0.361014           6
6      Pcv       0.779051       0.377701           7
7       Sc       0.770546       0.380316           8
8    Appet       0.634996       0.425769           9
9      Bgr       0.596137       0.440287          10
10      Sg       0.582353       0.445620          11
11      Dm       0.443032       0.505857          12
12     Pcc       0.432056       0.511174          13
13      Pe       0.281608       0.595799          14
14      Al       0.162929       0.686584          15
15     Pot       0.145172       0.703295          16
16    Wbcc       0.106431       0.744332          17
17     Cad       0.088220       0.766530          18
18     Rbc       0.088220       0.766530          19
19     Htn       0.085198       0.770450          20
20    Hemo       0.051148       0.821136          21
21     Age       0.015848       0.899852          22
22     Sod       0.000594       0.980559          23
23      Pc       0.000081       0.992822          24

In [8]:
# =============================================================================
# STEP 8: TOP-K ANOVA FEATURE SETS
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")

anova_results = {}

for top_k in TOP_K_VALUES:

    selected = anova_scores.head(top_k)["Feature"].tolist()

    anova_results[top_k] = {
        "features": selected,
        "X_train": X_train[selected].copy(),
        "X_test": X_test[selected].copy()
    }

    print("=" * 70)
    print(f"ANOVA TOP-{top_k}")
    print("=" * 70)
    print(selected)

Total predictors: 24
Top-K values: [5, 10, 15, 20]
======================================================================
ANOVA TOP-5
======================================================================
['Bp', 'Su', 'Ba', 'Bu', 'Ane']
======================================================================
ANOVA TOP-10
======================================================================
['Bp', 'Su', 'Ba', 'Bu', 'Ane', 'Rbcc', 'Pcv', 'Sc', 'Appet', 'Bgr']
======================================================================
ANOVA TOP-15
======================================================================
['Bp', 'Su', 'Ba', 'Bu', 'Ane', 'Rbcc', 'Pcv', 'Sc', 'Appet', 'Bgr', 'Sg', 'Dm', 'Pcc', 'Pe', 'Al']
======================================================================
ANOVA TOP-20
======================================================================
['Bp', 'Su', 'Ba', 'Bu', 'Ane', 'Rbcc', 'Pcv', 'Sc', 'Appet', 'Bgr', 'Sg', 'Dm', 'Pcc', 'Pe', 'Al', 'Pot', 'Wbcc', 'Cad', 'Rbc', 'Htn']

In [9]:
# =============================================================================
# STEP 9: DOWNSTREAM MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1
    )
}

print(list(models.keys()))

['Logistic Regression', 'Random Forest', 'XGBoost']

In [10]:
# =============================================================================
# STEP 10: ANOVA BASELINE MODEL EVALUATION
# =============================================================================

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

fixed_anova_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = anova_results[top_k]["X_train"]
    Xte_selected = anova_results[top_k]["X_test"]
    selected_features = anova_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_anova_rows.append({
            "Method": "ANOVA",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_anova_results_df = pd.DataFrame(fixed_anova_rows)
display(fixed_anova_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,ANOVA,5,Logistic Regression,"Bp, Su, Ba, Bu, Ane",0.5303,0.5391,0.6078,0.5714,0.5587
1,ANOVA,5,Random Forest,"Bp, Su, Ba, Bu, Ane",0.5303,0.5474,0.5098,0.5279,0.5600
2,ANOVA,5,XGBoost,"Bp, Su, Ba, Bu, Ane",0.5000,0.5143,0.5294,0.5217,0.5036
3,ANOVA,10,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.5606,0.5630,0.6569,0.6063,0.5895
4,ANOVA,10,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.5051,0.5208,0.4902,0.5051,0.5129
5,ANOVA,10,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.4848,0.5000,0.4804,0.4900,0.4931
6,ANOVA,15,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5556,0.5660,0.5882,0.5769,0.5684
7,ANOVA,15,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5556,0.5686,0.5686,0.5686,0.5510
8,ANOVA,15,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5051,0.5204,0.5000,0.5100,0.5314
9,ANOVA,20,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5505,0.5596,0.5980,0.5782,0.5751
10,ANOVA,20,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5303,0.5455,0.5294,0.5373,0.5436
11,ANOVA,20,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5354,0.5472,0.5686,0.5577,0.5283

In [11]:
# =============================================================================
# STEP 11: SAVE ANOVA BASELINE
# =============================================================================

baseline_dir = Path("../../../results/kidney_disease/baseline")
baseline_dir.mkdir(parents=True, exist_ok=True)

baseline_path = baseline_dir / "anova_baseline_results.csv"
fixed_anova_results_df.to_csv(baseline_path, index=False)

print(f"Saved: {baseline_path.resolve()}")

Saved: /home/claude/bd_kdd_final/results/kidney_disease/baseline/anova_baseline_results.csv

# 2. DODA Clinical Re-ranking

### Correct experimental order

```text
24 original predictors
        ↓
ANOVA scores all 24
        ↓
statistical ranking
        +
pre-specified clinical weights
        ↓
DODA rank fusion
        ↓
final Top-K
```

DODA must **not** receive an already-truncated ANOVA Top-K set. Otherwise, clinically prioritized features outside that preliminary Top-K would be impossible to recover.

In [12]:
# =============================================================================
# STEP 12: INSTALL / IMPORT DODA
# =============================================================================

# Run the following installation once if DODA is not installed:
# %pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

import doda

from doda import DODASelector
from doda.adapters import SklearnAdapter
from doda.knowledge.providers import JSONProvider
from doda.fusion import RankFusion

print("DODA:", doda.__file__)

print("Provider:", JSONProvider)
print("Fusion:", RankFusion)

DODA: /usr/local/lib/python3.12/dist-packages/doda/__init__.py
Provider: <class 'doda.knowledge.providers.json_provider.JSONProvider'>
Fusion: <class 'doda.fusion.rank.RankFusion'>

### Why a custom provider is needed here

`BD_KDD_clinical_weights.json` uses a richer schema than the package's `JSONProvider` expects — the per-feature weights live under a nested `"weights"` key, alongside `schema_version`, `sources`, `feature_tiers`, and other provenance metadata. `JSONProvider.get_weights()` only ever looks at the **top level** of the loaded JSON, so for every feature it does `self.weights.get("Age", 1.0)` — and since `"Age"` is not a top-level key in this file, **every single feature silently fell back to the default weight of 1.0**. This made the clinical layer completely flat (a tie across all 24 features), which is exactly why DODA wasn't producing any rank changes: Rank Fusion had a real statistical ranking to combine with, but a clinical ranking with no information in it at all.

This was previously masked by the validation cell below, which manually did `weights_payload["weights"]` to check coverage — that check is correct, but it validates a *different* object than the one actually passed into `DODASelector`, so it passed even though the real `provider` was broken.

**Fix**: `NestedJSONProvider`, defined below, implements the same `BaseKnowledgeProvider` interface as `JSONProvider` but reads from the nested `"weights"` key. The clinical weights file itself does not need to change — it's correctly structured for the richer schema; the loading code needed to catch up to it. If this schema becomes the standard going forward, `JSONProvider` in the actual `doda` package should be updated to check for a `"weights"` key and fall back to top-level parsing for older flat files, so every notebook doesn't need its own local copy of this class.

In [13]:
# =============================================================================
# STEP 12B: NESTED-SCHEMA CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

from doda.knowledge.providers.base import BaseKnowledgeProvider
import json as _json


class NestedJSONProvider(BaseKnowledgeProvider):
    """
    Reads clinical weights from the "weights" key of a richer JSON schema
    (schema_version, target, tier_mapping, feature_tiers, sources, etc.),
    rather than expecting the weights at the top level the way the
    package's built-in JSONProvider does.

    Same fallback behavior as JSONProvider otherwise: a feature not present
    in the weights dict gets a neutral default of 1.0, not an error --
    kept intentionally consistent so debugging behavior doesn't change,
    only where the weights are actually read from.
    """

    def __init__(self, path):
        self.path = path
        with open(path, "r", encoding="utf-8") as f:
            payload = _json.load(f)

        if "weights" not in payload:
            raise KeyError(
                f"{path} has no top-level 'weights' key -- "
                "this loader expects the nested schema. Use JSONProvider "
                "instead for a flat {feature: weight} file."
            )

        self.weights = payload["weights"]

    def get_weights(self, feature_names):
        return {
            feature: self.weights.get(feature, 1.0)
            for feature in feature_names
        }


print("NestedJSONProvider defined.")

NestedJSONProvider defined.

In [14]:
# =============================================================================
# STEP 13: LOCATE AND VALIDATE CLINICAL WEIGHTS
# =============================================================================

WEIGHTS_FILENAME = "BD_KDD_clinical_weights.json"

search_roots = [Path.cwd(), *Path.cwd().parents]
matches = []

for root in search_roots:
    try:
        matches.extend(root.rglob(WEIGHTS_FILENAME))
    except (PermissionError, OSError):
        continue

# Remove duplicates while preserving order
matches = list(dict.fromkeys(matches))

if not matches:
    raise FileNotFoundError(
        f"{WEIGHTS_FILENAME} was not found. "
        "Place it in the repository and rerun this cell."
    )

WEIGHTS_PATH = matches[0]

print(f"Using clinical weights: {WEIGHTS_PATH.resolve()}")

provider = NestedJSONProvider(str(WEIGHTS_PATH))

# Validate coverage using the JSON file directly.
import json

with open(WEIGHTS_PATH, "r", encoding="utf-8") as f:
    weights_payload = json.load(f)

clinical_weights = weights_payload["weights"]

missing_weights = sorted(set(X.columns) - set(clinical_weights))
extra_weights = sorted(set(clinical_weights) - set(X.columns))

print(f"Clinical weights: {len(clinical_weights)}")
print(f"Predictors:       {len(X.columns)}")
print(f"Missing weights:  {missing_weights}")
print(f"Extra weights:    {extra_weights}")

assert not missing_weights
assert not extra_weights

Using clinical weights: /home/claude/bd_kdd_final/notebooks/angel/kidney_disease/BD_KDD_clinical_weights.json
Clinical weights: 24
Predictors:       24
Missing weights:  []
Extra weights:    []

In [15]:
# =============================================================================
# STEP 14: DODA — SCORE ALL FEATURES, THEN APPLY TOP-K
# =============================================================================

rank_doda_results = {}

for top_k in TOP_K_VALUES:

    anova_operator = SklearnAdapter(
        SelectKBest(
            score_func=f_classif,
            k="all"     # CRITICAL: all 24 features reach DODA
        )
    )

    doda_selector = DODASelector(
        operators=[anova_operator],
        provider=provider,
        fusion=RankFusion(),
        top_k=top_k
    )

    # Fit only on training data.
    doda_selector.fit(
        X_train,
        y_train
    )

    selected_features = list(
        doda_selector.get_selected_features()
    )

    rank_doda_results[top_k] = {
        "selector": doda_selector,
        "features": selected_features,
        "X_train": X_train[selected_features].copy(),
        "X_test": X_test[selected_features].copy()
    }

    print("=" * 70)
    print(f"DODA TOP-{top_k}")
    print("=" * 70)
    print(selected_features)
    print(f"Number selected: {len(selected_features)}")

    assert len(selected_features) == top_k

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a5b0ef0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017801501103017411), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06541357475724775), 'Al': np.float64(0.018301188851955245), 'Su': np.float64(0.16578013840558292), 'Rbc': np.float64(0.009909485501440107), 'Pc': np.float64(9.097201888280592e-06), 'Pcc': np.float64(0.048531332854378655), 'Ba': np.float64(0.15585395968513205), 'Bgr': np.float64(0.0669618941521299), 'Bu': np.float64(0.14546939517569324), 'Sc': np.float64(0.08655268102314033), 'Sod': np.float64(6.673911088976461e-05), 'Pot': np.float64(0.01630663700649319), 'Hemo': np.float64(0.005745278896421053), 'Pcv': np.float64(0.08750801441459542), 'Wbcc': np.float64(0.011954978715407068), 'Rbcc': np.float64(0.093830183449561), 'Htn': np.float64(0.00957001604676683), 'Dm': np.float64(0.04976420630883494), 'Cad': np.float64(0.009909485501440107), 'Appet': np.float64(0.07132680071014873), 'Pe': np.float64(0.03163200720149144), 'Ane': np.float64(0.13892370418091674)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.029726775956284153, 'Su': 0.030834914611005692, 'Rbc': 0.027526395173453996, 'Pc': 0.026540946394272742, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.031754032258064516, 'Sc': 0.031099324975891997, 'Sod': 0.02712049508554787, 'Pot': 0.028083267871170464, 'Hemo': 0.027884615384615386, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027071520029266508, 'Rbcc': 0.029857397504456328, 'Htn': 0.028531243721117136, 'Dm': 0.029513888888888888, 'Cad': 0.027106227106227107, 'Appet': 0.028577260665441927, 'Pe': 0.028438886647841874, 'Ane': 0.030536130536130537}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Ane']
======================================================================
DODA TOP-5
======================================================================
['Bp', 'Bu', 'Sc', 'Su', 'Ane']
Number selected: 5
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a5b0ef0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017801501103017411), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06541357475724775), 'Al': np.float64(0.018301188851955245), 'Su': np.float64(0.16578013840558292), 'Rbc': np.float64(0.009909485501440107), 'Pc': np.float64(9.097201888280592e-06), 'Pcc': np.float64(0.048531332854378655), 'Ba': np.float64(0.15585395968513205), 'Bgr': np.float64(0.0669618941521299), 'Bu': np.float64(0.14546939517569324), 'Sc': np.float64(0.08655268102314033), 'Sod': np.float64(6.673911088976461e-05), 'Pot': np.float64(0.01630663700649319), 'Hemo': np.float64(0.005745278896421053), 'Pcv': np.float64(0.08750801441459542), 'Wbcc': np.float64(0.011954978715407068), 'Rbcc': np.float64(0.093830183449561), 'Htn': np.float64(0.00957001604676683), 'Dm': np.float64(0.04976420630883494), 'Cad': np.float64(0.009909485501440107), 'Appet': np.float64(0.07132680071014873), 'Pe': np.float64(0.03163200720149144), 'Ane': np.float64(0.13892370418091674)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.029726775956284153, 'Su': 0.030834914611005692, 'Rbc': 0.027526395173453996, 'Pc': 0.026540946394272742, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.031754032258064516, 'Sc': 0.031099324975891997, 'Sod': 0.02712049508554787, 'Pot': 0.028083267871170464, 'Hemo': 0.027884615384615386, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027071520029266508, 'Rbcc': 0.029857397504456328, 'Htn': 0.028531243721117136, 'Dm': 0.029513888888888888, 'Cad': 0.027106227106227107, 'Appet': 0.028577260665441927, 'Pe': 0.028438886647841874, 'Ane': 0.030536130536130537}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al']
======================================================================
DODA TOP-10
======================================================================
['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al']
Number selected: 10
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a5b0ef0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017801501103017411), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06541357475724775), 'Al': np.float64(0.018301188851955245), 'Su': np.float64(0.16578013840558292), 'Rbc': np.float64(0.009909485501440107), 'Pc': np.float64(9.097201888280592e-06), 'Pcc': np.float64(0.048531332854378655), 'Ba': np.float64(0.15585395968513205), 'Bgr': np.float64(0.0669618941521299), 'Bu': np.float64(0.14546939517569324), 'Sc': np.float64(0.08655268102314033), 'Sod': np.float64(6.673911088976461e-05), 'Pot': np.float64(0.01630663700649319), 'Hemo': np.float64(0.005745278896421053), 'Pcv': np.float64(0.08750801441459542), 'Wbcc': np.float64(0.011954978715407068), 'Rbcc': np.float64(0.093830183449561), 'Htn': np.float64(0.00957001604676683), 'Dm': np.float64(0.04976420630883494), 'Cad': np.float64(0.009909485501440107), 'Appet': np.float64(0.07132680071014873), 'Pe': np.float64(0.03163200720149144), 'Ane': np.float64(0.13892370418091674)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.029726775956284153, 'Su': 0.030834914611005692, 'Rbc': 0.027526395173453996, 'Pc': 0.026540946394272742, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.031754032258064516, 'Sc': 0.031099324975891997, 'Sod': 0.02712049508554787, 'Pot': 0.028083267871170464, 'Hemo': 0.027884615384615386, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027071520029266508, 'Rbcc': 0.029857397504456328, 'Htn': 0.028531243721117136, 'Dm': 0.029513888888888888, 'Cad': 0.027106227106227107, 'Appet': 0.028577260665441927, 'Pe': 0.028438886647841874, 'Ane': 0.030536130536130537}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al', 'Dm', 'Bgr', 'Appet', 'Htn', 'Pe']
======================================================================
DODA TOP-15
======================================================================
['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al', 'Dm', 'Bgr', 'Appet', 'Htn', 'Pe']
Number selected: 15
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a5b0ef0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.015848009107691952), 'Bp': np.float64(8.902625130307502), 'Sg': np.float64(0.5823525344971223), 'Al': np.float64(0.16292862378792028), 'Su': np.float64(1.4758784262753983), 'Rbc': np.float64(0.08822043465353854), 'Pc': np.float64(8.098897814608765e-05), 'Pcc': np.float64(0.4320562634767095), 'Ba': np.float64(1.387509378150789), 'Bgr': np.float64(0.5961366416517426), 'Bu': np.float64(1.2950594931817596), 'Sc': np.float64(0.7705460731720983), 'Sod': np.float64(0.0005941532857815975), 'Pot': np.float64(0.14517187640480858), 'Hemo': np.float64(0.05114806428390342), 'Pcv': np.float64(0.7790510482306884), 'Wbcc': np.float64(0.10643069394407427), 'Rbcc': np.float64(0.8353349491594249), 'Htn': np.float64(0.08519826535539245), 'Dm': np.float64(0.4430320736748411), 'Cad': np.float64(0.08822043465353854), 'Appet': np.float64(0.634995768466605), 'Pe': np.float64(0.28160790223406557), 'Ane': np.float64(1.2367856600364346)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017801501103017411), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06541357475724775), 'Al': np.float64(0.018301188851955245), 'Su': np.float64(0.16578013840558292), 'Rbc': np.float64(0.009909485501440107), 'Pc': np.float64(9.097201888280592e-06), 'Pcc': np.float64(0.048531332854378655), 'Ba': np.float64(0.15585395968513205), 'Bgr': np.float64(0.0669618941521299), 'Bu': np.float64(0.14546939517569324), 'Sc': np.float64(0.08655268102314033), 'Sod': np.float64(6.673911088976461e-05), 'Pot': np.float64(0.01630663700649319), 'Hemo': np.float64(0.005745278896421053), 'Pcv': np.float64(0.08750801441459542), 'Wbcc': np.float64(0.011954978715407068), 'Rbcc': np.float64(0.093830183449561), 'Htn': np.float64(0.00957001604676683), 'Dm': np.float64(0.04976420630883494), 'Cad': np.float64(0.009909485501440107), 'Appet': np.float64(0.07132680071014873), 'Pe': np.float64(0.03163200720149144), 'Ane': np.float64(0.13892370418091674)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.029726775956284153, 'Su': 0.030834914611005692, 'Rbc': 0.027526395173453996, 'Pc': 0.026540946394272742, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.031754032258064516, 'Sc': 0.031099324975891997, 'Sod': 0.02712049508554787, 'Pot': 0.028083267871170464, 'Hemo': 0.027884615384615386, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027071520029266508, 'Rbcc': 0.029857397504456328, 'Htn': 0.028531243721117136, 'Dm': 0.029513888888888888, 'Cad': 0.027106227106227107, 'Appet': 0.028577260665441927, 'Pe': 0.028438886647841874, 'Ane': 0.030536130536130537}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al', 'Dm', 'Bgr', 'Appet', 'Htn', 'Pe', 'Pot', 'Hemo', 'Pcc', 'Rbc', 'Sod']
======================================================================
DODA TOP-20
======================================================================
['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al', 'Dm', 'Bgr', 'Appet', 'Htn', 'Pe', 'Pot', 'Hemo', 'Pcc', 'Rbc', 'Sod']
Number selected: 20

In [16]:
# =============================================================================
# STEP 15: INSPECT DODA RANK CHANGES
# =============================================================================

INSPECTION_TOP_K = 10

selector = rank_doda_results[INSPECTION_TOP_K]["selector"]

print("=" * 70)
print(f"DODA RANK COMPARISON — TOP-{INSPECTION_TOP_K}")
print("=" * 70)

rank_comparison = selector.compare_scores()

display(rank_comparison)

print("\nSelected features:")
print(rank_doda_results[INSPECTION_TOP_K]["features"])

======================================================================
DODA RANK COMPARISON — TOP-10
======================================================================

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
  Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0      Bp          1              6           1            0
1      Bu          4              3           2            2
2      Sc          8              2           3            5
3      Su          2             16           4           -2
4     Ane          5             11           5            0
5     Pcv          7             10           6            1
6      Sg         11              4           7            4
7      Ba          3             22           8           -5
8    Rbcc          6             18           9           -3
9      Al         15              1          10            5

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,Bp,1,1.0000,6,0.80,1,0.0320,0
1,Bu,4,0.1455,3,0.90,2,0.0318,2
2,Sc,8,0.0866,2,1.00,3,0.0311,5
3,Su,2,0.1658,16,0.55,4,0.0308,-2
4,Ane,5,0.1389,11,0.70,5,0.0305,0
5,Pcv,7,0.0875,10,0.70,6,0.0301,1
6,Sg,11,0.0654,4,0.85,7,0.0300,4
7,Ba,3,0.1559,22,0.40,8,0.0300,-5
8,Rbcc,6,0.0938,18,0.55,9,0.0299,-3
9,Al,15,0.0183,1,1.00,10,0.0297,5
10,Dm,12,0.0498,7,0.80,11,0.0295,1
11,Bgr,10,0.0670,9,0.70,12,0.0294,-2
12,Appet,9,0.0713,24,0.40,13,0.0286,-4
13,Htn,20,0.0096,5,0.85,14,0.0285,6
14,Pe,14,0.0316,14,0.65,15,0.0284,-1
15,Pot,16,0.0163,13,0.65,16,0.0281,0
16,Hemo,21,0.0057,8,0.75,17,0.0279,4
17,Pcc,13,0.0485,21,0.40,18,0.0278,-5
18,Rbc,18,0.0099,17,0.55,19,0.0275,-1
19,Sod,23,0.0001,12,0.65,20,0.0271,3
20,Cad,19,0.0099,20,0.45,21,0.0271,-2
21,Wbcc,17,0.0120,23,0.40,22,0.0271,-5
22,Age,22,0.0018,15,0.55,23,0.0271,-1
23,Pc,24,0.0000,19,0.50,24,0.0265,0

Selected features:
['Bp', 'Bu', 'Sc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Rbcc', 'Al']

In [17]:
# =============================================================================
# STEP 15B: EXPLICIT ANOVA vs DODA RANK-SHIFT TABLE
# =============================================================================
# This table separates:
#   - statistical ANOVA rank
#   - DODA final rank
#   - clinical weight
#   - rank movement
#
# Positive Rank_Change means the feature moved upward.
# Example: ANOVA rank 10 -> DODA rank 4 = +6
#
# IMPORTANT:
# The selector is explicitly retrieved from rank_doda_results
# for the selected Top-K value. This avoids relying on a
# previously defined 'selector' variable.

# -------------------------------------------------------------------------
# Select which DODA Top-K experiment to inspect
# -------------------------------------------------------------------------

k = 10

if k not in rank_doda_results:
    raise KeyError(
        f"Top-K={k} was not found in rank_doda_results. "
        f"Available values: {list(rank_doda_results.keys())}"
    )

selector = rank_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# ANOVA / mathematical ranking
# -------------------------------------------------------------------------

math_rank = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "ANOVA_Normalized_Score"
    ]
)

math_rank["ANOVA_Rank"] = (
    math_rank["ANOVA_Normalized_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# DODA final ranking
# -------------------------------------------------------------------------

final_rank = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "DODA_Final_Score"
    ]
)

final_rank["DODA_Rank"] = (
    final_rank["DODA_Final_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# Combine rankings
# -------------------------------------------------------------------------

rank_shift_df = (
    math_rank[
        [
            "Feature",
            "ANOVA_Normalized_Score",
            "ANOVA_Rank"
        ]
    ]
    .merge(
        final_rank[
            [
                "Feature",
                "DODA_Final_Score",
                "DODA_Rank"
            ]
        ],
        on="Feature",
        how="inner"
    )
)


# -------------------------------------------------------------------------
# Add clinical weights
# -------------------------------------------------------------------------

rank_shift_df["Clinical_Weight"] = (
    rank_shift_df["Feature"]
    .map(selector.clinical_weights_)
)


# -------------------------------------------------------------------------
# Calculate rank movement
# -------------------------------------------------------------------------
# Positive value  = moved upward
# Negative value  = moved downward
# Zero             = no rank movement

rank_shift_df["Rank_Change"] = (
    rank_shift_df["ANOVA_Rank"]
    - rank_shift_df["DODA_Rank"]
)


# -------------------------------------------------------------------------
# Sort by DODA final rank
# -------------------------------------------------------------------------

rank_shift_df = (
    rank_shift_df
    .sort_values(
        by="DODA_Rank"
    )
    .reset_index(drop=True)
)


# -------------------------------------------------------------------------
# Display
# -------------------------------------------------------------------------

print("=" * 80)
print(f"ANOVA vs DODA RANK-SHIFT ANALYSIS — TOP-{k}")
print("=" * 80)

display(rank_shift_df)

================================================================================
ANOVA vs DODA RANK-SHIFT ANALYSIS — TOP-10
================================================================================

,Feature,ANOVA_Normalized_Score,ANOVA_Rank,DODA_Final_Score,DODA_Rank,Clinical_Weight,Rank_Change
0,Bp,1.000000,1,0.032018,1,0.80,0
1,Bu,0.145469,4,0.031754,2,0.90,2
2,Sc,0.086553,8,0.031099,3,1.00,5
3,Su,0.165780,2,0.030835,4,0.55,-2
4,Ane,0.138924,5,0.030536,5,0.70,0
5,Pcv,0.087508,7,0.030077,6,0.70,1
6,Sg,0.065414,11,0.029958,7,0.85,4
7,Ba,0.155854,3,0.029958,7,0.40,-4
8,Rbcc,0.093830,6,0.029857,9,0.55,-3
9,Al,0.018301,15,0.029727,10,1.00,5
10,Dm,0.049764,12,0.029514,11,0.80,1
11,Bgr,0.066962,10,0.029437,12,0.70,-2
12,Appet,0.071327,9,0.028577,13,0.40,-4
13,Htn,0.009570,20,0.028531,14,0.85,6
14,Pe,0.031632,14,0.028439,15,0.65,-1
15,Pot,0.016307,16,0.028083,16,0.65,0
16,Hemo,0.005745,21,0.027885,17,0.75,4
17,Pcc,0.048531,13,0.027783,18,0.40,-5
18,Rbc,0.009909,18,0.027526,19,0.55,-1
19,Sod,0.000067,23,0.027120,20,0.65,3
20,Cad,0.009909,18,0.027106,21,0.45,-3
21,Wbcc,0.011955,17,0.027072,22,0.40,-5
22,Age,0.001780,22,0.027052,23,0.55,-1
23,Pc,0.000009,24,0.026541,24,0.50,0

In [18]:
# =============================================================================
# STEP 16: INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weight_table = pd.DataFrame({
    "Feature": list(selector.clinical_weights_.keys()),
    "Clinical_Weight": list(selector.clinical_weights_.values())
}).sort_values(
    "Clinical_Weight",
    ascending=False
).reset_index(drop=True)

display(clinical_weight_table)

   Feature  Clinical_Weight
0       Al             1.00
1       Sc             1.00
2       Bu             0.90
3       Sg             0.85
4      Htn             0.85
5       Dm             0.80
6       Bp             0.80
7     Hemo             0.75
8      Pcv             0.70
9      Ane             0.70
10     Bgr             0.70
11     Pot             0.65
12      Pe             0.65
13     Sod             0.65
14     Age             0.55
15      Su             0.55
16     Rbc             0.55
17    Rbcc             0.55
18      Pc             0.50
19     Cad             0.45
20     Pcc             0.40
21      Ba             0.40
22    Wbcc             0.40
23   Appet             0.40

In [19]:
# =============================================================================
# STEP 17: DODA MODEL EVALUATION — FIXED SPLIT
# =============================================================================

fixed_doda_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = rank_doda_results[top_k]["X_train"]
    Xte_selected = rank_doda_results[top_k]["X_test"]
    selected_features = rank_doda_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_doda_rows.append({
            "Method": "DODA",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_doda_results_df = pd.DataFrame(fixed_doda_rows)
display(fixed_doda_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,DODA,5,Logistic Regression,"Bp, Bu, Sc, Su, Ane",0.5303,0.5378,0.6275,0.5792,0.5518
1,DODA,5,Random Forest,"Bp, Bu, Sc, Su, Ane",0.4798,0.4949,0.4804,0.4876,0.4952
2,DODA,5,XGBoost,"Bp, Bu, Sc, Su, Ane",0.4848,0.5000,0.5294,0.5143,0.5043
3,DODA,10,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5354,0.5431,0.6176,0.5780,0.5774
4,DODA,10,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5253,0.5417,0.5098,0.5253,0.5347
5,DODA,10,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5202,0.5385,0.4804,0.5078,0.5088
6,DODA,15,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5657,0.5727,0.6176,0.5943,0.5790
7,DODA,15,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5152,0.5312,0.5000,0.5152,0.5408
8,DODA,15,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5101,0.5258,0.5000,0.5126,0.5424
9,DODA,20,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5606,0.5701,0.5980,0.5837,0.5777
10,DODA,20,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5000,0.5126,0.5980,0.5520,0.5379
11,DODA,20,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5152,0.5306,0.5098,0.5200,0.5250

In [20]:
# =============================================================================
# STEP 18: FIXED-SPLIT ANOVA vs DODA COMPARISON
# =============================================================================

fixed_comparison_df = pd.concat(
    [fixed_anova_results_df, fixed_doda_results_df],
    ignore_index=True
)

display(fixed_comparison_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,ANOVA,5,Logistic Regression,"Bp, Su, Ba, Bu, Ane",0.5303,0.5391,0.6078,0.5714,0.5587
1,ANOVA,5,Random Forest,"Bp, Su, Ba, Bu, Ane",0.5303,0.5474,0.5098,0.5279,0.5600
2,ANOVA,5,XGBoost,"Bp, Su, Ba, Bu, Ane",0.5000,0.5143,0.5294,0.5217,0.5036
3,ANOVA,10,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.5606,0.5630,0.6569,0.6063,0.5895
4,ANOVA,10,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.5051,0.5208,0.4902,0.5051,0.5129
5,ANOVA,10,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr",0.4848,0.5000,0.4804,0.4900,0.4931
6,ANOVA,15,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5556,0.5660,0.5882,0.5769,0.5684
7,ANOVA,15,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5556,0.5686,0.5686,0.5686,0.5510
8,ANOVA,15,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5051,0.5204,0.5000,0.5100,0.5314
9,ANOVA,20,Logistic Regression,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5505,0.5596,0.5980,0.5782,0.5751
10,ANOVA,20,Random Forest,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5303,0.5455,0.5294,0.5373,0.5436
11,ANOVA,20,XGBoost,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...",0.5354,0.5472,0.5686,0.5577,0.5283
12,DODA,5,Logistic Regression,"Bp, Bu, Sc, Su, Ane",0.5303,0.5378,0.6275,0.5792,0.5518
13,DODA,5,Random Forest,"Bp, Bu, Sc, Su, Ane",0.4798,0.4949,0.4804,0.4876,0.4952
14,DODA,5,XGBoost,"Bp, Bu, Sc, Su, Ane",0.4848,0.5000,0.5294,0.5143,0.5043
15,DODA,10,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5354,0.5431,0.6176,0.5780,0.5774
16,DODA,10,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5253,0.5417,0.5098,0.5253,0.5347
17,DODA,10,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",0.5202,0.5385,0.4804,0.5078,0.5088
18,DODA,15,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5657,0.5727,0.6176,0.5943,0.5790
19,DODA,15,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5152,0.5312,0.5000,0.5152,0.5408
20,DODA,15,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5101,0.5258,0.5000,0.5126,0.5424
21,DODA,20,Logistic Regression,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5606,0.5701,0.5980,0.5837,0.5777
22,DODA,20,Random Forest,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5000,0.5126,0.5980,0.5520,0.5379
23,DODA,20,XGBoost,"Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",0.5152,0.5306,0.5098,0.5200,0.5250

In [21]:
# =============================================================================
# STEP 19: COMPARE FEATURE SETS ON THE FIXED SPLIT
# =============================================================================

fixed_feature_comparison = []

for top_k in TOP_K_VALUES:

    anova_set = set(anova_results[top_k]["features"])
    doda_set = set(rank_doda_results[top_k]["features"])

    intersection = anova_set & doda_set
    union = anova_set | doda_set

    jaccard = len(intersection) / len(union)

    fixed_feature_comparison.append({
        "Top_K": top_k,
        "ANOVA_Features": ", ".join(anova_results[top_k]["features"]),
        "DODA_Features": ", ".join(rank_doda_results[top_k]["features"]),
        "Same_Feature_Set": anova_set == doda_set,
        "Overlap_Count": len(intersection),
        "Jaccard": jaccard,
        "Features_Changed": top_k - len(intersection)
    })

fixed_feature_comparison_df = pd.DataFrame(fixed_feature_comparison)

display(fixed_feature_comparison_df)

,Top_K,ANOVA_Features,DODA_Features,Same_Feature_Set,Overlap_Count,Jaccard,Features_Changed
0,5,"Bp, Su, Ba, Bu, Ane","Bp, Bu, Sc, Su, Ane",False,4,0.666667,1
1,10,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr","Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al",False,8,0.666667,2
2,15,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...","Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",False,14,0.875000,1
3,20,"Bp, Su, Ba, Bu, Ane, Rbcc, Pcv, Sc, Appet, Bgr...","Bp, Bu, Sc, Su, Ane, Pcv, Sg, Ba, Rbcc, Al, Dm...",False,18,0.818182,2

In [22]:
# =============================================================================
# STEP 20: SAVE FIXED-SPLIT DODA RESULTS
# =============================================================================

doda_dir = Path("../../../results/kidney_disease/doda")
doda_dir.mkdir(parents=True, exist_ok=True)

fixed_doda_results_df.to_csv(
    doda_dir / "anova_doda_fixed_split_results.csv",
    index=False
)

fixed_feature_comparison_df.to_csv(
    doda_dir / "anova_doda_fixed_split_feature_comparison.csv",
    index=False
)

print(f"Saved results to: {doda_dir.resolve()}")

Saved results to: /home/claude/bd_kdd_final/results/kidney_disease/doda

# 3. Robustness: 5×5 Repeated Stratified Cross-Validation

The fixed split provides a reproducible initial comparison.

For robustness, feature selection is **recomputed inside every training fold**. This prevents information from the validation fold from influencing ANOVA or DODA.

There are:

- 5 folds
- 5 repeats
- 25 train/validation runs
- 4 Top-K budgets
- 2 feature-selection methods
- 3 downstream models

This produces 600 model-evaluation rows.

In [23]:
# =============================================================================
# STEP 21: REPEATED CV CONFIGURATION
# =============================================================================

from sklearn.model_selection import RepeatedStratifiedKFold

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)

print(f"Top-K values: {TOP_K_VALUES}")
print(f"CV runs: {N_SPLITS * N_REPEATS}")

Top-K values: [5, 10, 15, 20]
CV runs: 25

In [24]:
# =============================================================================
# STEP 22: 5×5 REPEATED CV — ANOVA vs DODA
# =============================================================================

cv_results = []

for run_id, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    X_train_fold = X.iloc[train_idx].copy()
    X_val_fold = X.iloc[val_idx].copy()

    y_train_fold = y.iloc[train_idx].copy()
    y_val_fold = y.iloc[val_idx].copy()

    print(f"Run {run_id:02d}/{N_SPLITS * N_REPEATS}")

    # -----------------------------------------------------------------
    # ANOVA scores ALL features inside this training fold
    # -----------------------------------------------------------------

    anova_all = SelectKBest(
        score_func=f_classif,
        k="all"
    )

    anova_all.fit(
        X_train_fold,
        y_train_fold
    )

    anova_fold_scores = pd.DataFrame({
        "Feature": X_train_fold.columns,
        "Score": anova_all.scores_
    }).sort_values(
        "Score",
        ascending=False
    )

    # -----------------------------------------------------------------
    # DODA also receives ALL features and performs final Top-K
    # -----------------------------------------------------------------

    # NOTE: previously this cell also fit a `doda_selector` once here at
    # top_k=max(TOP_K_VALUES) before the loop below -- that result was
    # never used (the loop always builds its own fold_doda per top_k),
    # so the redundant fit was removed to cut this cell's runtime.

    for top_k in TOP_K_VALUES:

        # -------------------------
        # ANOVA Top-K
        # -------------------------

        anova_features = (
            anova_fold_scores
            .head(top_k)["Feature"]
            .tolist()
        )

        # -------------------------
        # DODA Top-K
        # -------------------------

        fold_doda_operator = SklearnAdapter(
            SelectKBest(
                score_func=f_classif,
                k="all"
            )
        )

        fold_doda = DODASelector(
            operators=[fold_doda_operator],
            provider=NestedJSONProvider(str(WEIGHTS_PATH)),
            fusion=RankFusion(),
            top_k=top_k
        )

        fold_doda.fit(
            X_train_fold,
            y_train_fold
        )

        doda_features = list(
            fold_doda.get_selected_features()
        )

        # -------------------------
        # Model loop
        # -------------------------

        feature_sets = {
            "ANOVA": anova_features,
            "DODA": doda_features
        }

        for method, selected_features in feature_sets.items():

            Xtr_selected = X_train_fold[selected_features]
            Xval_selected = X_val_fold[selected_features]

            for model_name, model_template in models.items():

                model = model_template.__class__(
                    **model_template.get_params()
                )

                Xtr = Xtr_selected
                Xval = Xval_selected

                if model_name == "Logistic Regression":
                    scaler = StandardScaler()
                    Xtr = scaler.fit_transform(Xtr)
                    Xval = scaler.transform(Xval)

                model.fit(Xtr, y_train_fold)

                y_pred = model.predict(Xval)
                y_prob = model.predict_proba(Xval)[:, 1]

                cv_results.append({
                    "Run": run_id,
                    "Method": method,
                    "Top_K": top_k,
                    "Model": model_name,
                    "Accuracy": accuracy_score(y_val_fold, y_pred),
                    "Precision": precision_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "Recall": recall_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "F1": f1_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "ROC_AUC": roc_auc_score(
                        y_val_fold, y_prob
                    ),
                    "Selected_Features": ", ".join(selected_features)
                })

cv_results_df = pd.DataFrame(cv_results)

print("Completed.")
print(f"Rows generated: {len(cv_results_df)}")

assert len(cv_results_df) == 25 * 4 * 2 * 3

display(cv_results_df.head())

Run 01/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891888f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}

Normalized Mathematical Scores
{'Age': np.float64(0.06481948528961165), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4179021333136969), 'Al': np.float64(0.005204900228268476), 'Su': np.float64(0.20431187853352062), 'Rbc': np.float64(0.034347053570899296), 'Pc': np.float64(0.037884192765857895), 'Pcc': np.float64(0.0014938690028635385), 'Ba': np.float64(0.12044935560033282), 'Bgr': np.float64(0.07004649340997443), 'Bu': np.float64(9.753114918317771e-06), 'Sc': np.float64(0.09958605990846801), 'Sod': np.float64(0.07391777332350201), 'Pot': np.float64(0.11312925337087187), 'Hemo': np.float64(0.06119549802251011), 'Pcv': np.float64(0.013067462354210588), 'Wbcc': np.float64(0.11976409049331782), 'Rbcc': np.float64(0.2492016882812566), 'Htn': np.float64(0.018855225099843418), 'Dm': np.float64(0.000373110614798889), 'Cad': np.float64(0.009208818062348656), 'Appet': np.float64(0.027100947963406497), 'Pe': np.float64(0.009996625229550353), 'Ane': np.float64(0.017787611846128974)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.0287391216352965, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.02819138376017471, 'Pcc': 0.026279628993473032, 'Ba': 0.02946912242686891, 'Bgr': 0.029437229437229435, 'Bu': 0.02803379416282642, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Pot': 0.029850746268656716, 'Hemo': 0.029273504273504274, 'Pcv': 0.027972027972027972, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.03057889822595705, 'Htn': 0.029030910609857977, 'Dm': 0.027673192771084338, 'Cad': 0.026785714285714288, 'Appet': 0.027417840375586856, 'Pe': 0.027583600982429624, 'Ane': 0.02813852813852814}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Rbcc', 'Su']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889171190>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}

Normalized Mathematical Scores
{'Age': np.float64(0.06481948528961165), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4179021333136969), 'Al': np.float64(0.005204900228268476), 'Su': np.float64(0.20431187853352062), 'Rbc': np.float64(0.034347053570899296), 'Pc': np.float64(0.037884192765857895), 'Pcc': np.float64(0.0014938690028635385), 'Ba': np.float64(0.12044935560033282), 'Bgr': np.float64(0.07004649340997443), 'Bu': np.float64(9.753114918317771e-06), 'Sc': np.float64(0.09958605990846801), 'Sod': np.float64(0.07391777332350201), 'Pot': np.float64(0.11312925337087187), 'Hemo': np.float64(0.06119549802251011), 'Pcv': np.float64(0.013067462354210588), 'Wbcc': np.float64(0.11976409049331782), 'Rbcc': np.float64(0.2492016882812566), 'Htn': np.float64(0.018855225099843418), 'Dm': np.float64(0.000373110614798889), 'Cad': np.float64(0.009208818062348656), 'Appet': np.float64(0.027100947963406497), 'Pe': np.float64(0.009996625229550353), 'Ane': np.float64(0.017787611846128974)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.0287391216352965, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.02819138376017471, 'Pcc': 0.026279628993473032, 'Ba': 0.02946912242686891, 'Bgr': 0.029437229437229435, 'Bu': 0.02803379416282642, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Pot': 0.029850746268656716, 'Hemo': 0.029273504273504274, 'Pcv': 0.027972027972027972, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.03057889822595705, 'Htn': 0.029030910609857977, 'Dm': 0.027673192771084338, 'Cad': 0.026785714285714288, 'Appet': 0.027417840375586856, 'Pe': 0.027583600982429624, 'Ane': 0.02813852813852814}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Rbcc', 'Su', 'Pot', 'Ba', 'Bgr', 'Sod', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889189910>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}

Normalized Mathematical Scores
{'Age': np.float64(0.06481948528961165), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4179021333136969), 'Al': np.float64(0.005204900228268476), 'Su': np.float64(0.20431187853352062), 'Rbc': np.float64(0.034347053570899296), 'Pc': np.float64(0.037884192765857895), 'Pcc': np.float64(0.0014938690028635385), 'Ba': np.float64(0.12044935560033282), 'Bgr': np.float64(0.07004649340997443), 'Bu': np.float64(9.753114918317771e-06), 'Sc': np.float64(0.09958605990846801), 'Sod': np.float64(0.07391777332350201), 'Pot': np.float64(0.11312925337087187), 'Hemo': np.float64(0.06119549802251011), 'Pcv': np.float64(0.013067462354210588), 'Wbcc': np.float64(0.11976409049331782), 'Rbcc': np.float64(0.2492016882812566), 'Htn': np.float64(0.018855225099843418), 'Dm': np.float64(0.000373110614798889), 'Cad': np.float64(0.009208818062348656), 'Appet': np.float64(0.027100947963406497), 'Pe': np.float64(0.009996625229550353), 'Ane': np.float64(0.017787611846128974)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.0287391216352965, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.02819138376017471, 'Pcc': 0.026279628993473032, 'Ba': 0.02946912242686891, 'Bgr': 0.029437229437229435, 'Bu': 0.02803379416282642, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Pot': 0.029850746268656716, 'Hemo': 0.029273504273504274, 'Pcv': 0.027972027972027972, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.03057889822595705, 'Htn': 0.029030910609857977, 'Dm': 0.027673192771084338, 'Cad': 0.026785714285714288, 'Appet': 0.027417840375586856, 'Pe': 0.027583600982429624, 'Ane': 0.02813852813852814}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Rbcc', 'Su', 'Pot', 'Ba', 'Bgr', 'Sod', 'Hemo', 'Wbcc', 'Htn', 'Age', 'Al', 'Rbc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5892dae1b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.5692921565173608), 'Bp': np.float64(8.782731827841262), 'Sg': np.float64(3.670322367176968), 'Al': np.float64(0.0457132428955518), 'Su': np.float64(1.7944164384023895), 'Rbc': np.float64(0.3016609605897061), 'Pc': np.float64(0.3327267055767738), 'Pcc': np.float64(0.013120250838075088), 'Ba': np.float64(1.0578743890740132), 'Bgr': np.float64(0.6151995671004556), 'Bu': np.float64(8.565899281370292e-05), 'Sc': np.float64(0.8746376579674088), 'Sod': np.float64(0.6491999804114769), 'Pot': np.float64(0.9935838942402748), 'Hemo': np.float64(0.5374636482028966), 'Pcv': np.float64(0.11476801752744284), 'Wbcc': np.float64(1.0518558894081236), 'Rbcc': np.float64(2.1886715992195693), 'Htn': np.float64(0.16560038560550622), 'Dm': np.float64(0.0032769304718996235), 'Cad': np.float64(0.08087857949298904), 'Appet': np.float64(0.2380203582428801), 'Pe': np.float64(0.08779767857457285), 'Ane': np.float64(0.15622382470228321)}

Normalized Mathematical Scores
{'Age': np.float64(0.06481948528961165), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4179021333136969), 'Al': np.float64(0.005204900228268476), 'Su': np.float64(0.20431187853352062), 'Rbc': np.float64(0.034347053570899296), 'Pc': np.float64(0.037884192765857895), 'Pcc': np.float64(0.0014938690028635385), 'Ba': np.float64(0.12044935560033282), 'Bgr': np.float64(0.07004649340997443), 'Bu': np.float64(9.753114918317771e-06), 'Sc': np.float64(0.09958605990846801), 'Sod': np.float64(0.07391777332350201), 'Pot': np.float64(0.11312925337087187), 'Hemo': np.float64(0.06119549802251011), 'Pcv': np.float64(0.013067462354210588), 'Wbcc': np.float64(0.11976409049331782), 'Rbcc': np.float64(0.2492016882812566), 'Htn': np.float64(0.018855225099843418), 'Dm': np.float64(0.000373110614798889), 'Cad': np.float64(0.009208818062348656), 'Appet': np.float64(0.027100947963406497), 'Pe': np.float64(0.009996625229550353), 'Ane': np.float64(0.017787611846128974)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.0287391216352965, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.02819138376017471, 'Pcc': 0.026279628993473032, 'Ba': 0.02946912242686891, 'Bgr': 0.029437229437229435, 'Bu': 0.02803379416282642, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Pot': 0.029850746268656716, 'Hemo': 0.029273504273504274, 'Pcv': 0.027972027972027972, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.03057889822595705, 'Htn': 0.029030910609857977, 'Dm': 0.027673192771084338, 'Cad': 0.026785714285714288, 'Appet': 0.027417840375586856, 'Pe': 0.027583600982429624, 'Ane': 0.02813852813852814}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Rbcc', 'Su', 'Pot', 'Ba', 'Bgr', 'Sod', 'Hemo', 'Wbcc', 'Htn', 'Age', 'Al', 'Rbc', 'Pc', 'Ane', 'Bu', 'Pcv', 'Dm']

Run 02/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889188a10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}

Normalized Mathematical Scores
{'Age': np.float64(0.0005552474651585044), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07064830718959608), 'Al': np.float64(0.08123981409638958), 'Su': np.float64(0.03625524914560339), 'Rbc': np.float64(0.0011352184252064826), 'Pc': np.float64(0.06700636000887736), 'Pcc': np.float64(0.04192443494102272), 'Ba': np.float64(0.46919820397080164), 'Bgr': np.float64(4.362911169905294e-05), 'Bu': np.float64(0.0770692183792798), 'Sc': np.float64(0.07593826677437038), 'Sod': np.float64(0.04670012048444069), 'Pot': np.float64(0.1984533469430934), 'Hemo': np.float64(0.011615603295643021), 'Pcv': np.float64(0.382694873107447), 'Wbcc': np.float64(0.06693019003870061), 'Rbcc': np.float64(0.28922042351512717), 'Htn': np.float64(0.02319468656209716), 'Dm': np.float64(0.0004130157687605642), 'Cad': np.float64(0.02015251852893437), 'Appet': np.float64(0.07146829964634455), 'Pe': np.float64(0.19463371344897495), 'Ane': np.float64(0.0424985055345027)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03131881575727918, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028381642512077296, 'Pcc': 0.027242401779095628, 'Ba': 0.03021353930031804, 'Bgr': 0.027056277056277056, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030309988518943745, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.028693528693528692, 'Dm': 0.027673192771084338, 'Cad': 0.02694394213381555, 'Appet': 0.028370221327967807, 'Pe': 0.03007688828584351, 'Ane': 0.028484848484848488}
Top 5 Features Selected: ['Bp', 'Al', 'Pcv', 'Sc', 'Bu']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889149490>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}

Normalized Mathematical Scores
{'Age': np.float64(0.0005552474651585044), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07064830718959608), 'Al': np.float64(0.08123981409638958), 'Su': np.float64(0.03625524914560339), 'Rbc': np.float64(0.0011352184252064826), 'Pc': np.float64(0.06700636000887736), 'Pcc': np.float64(0.04192443494102272), 'Ba': np.float64(0.46919820397080164), 'Bgr': np.float64(4.362911169905294e-05), 'Bu': np.float64(0.0770692183792798), 'Sc': np.float64(0.07593826677437038), 'Sod': np.float64(0.04670012048444069), 'Pot': np.float64(0.1984533469430934), 'Hemo': np.float64(0.011615603295643021), 'Pcv': np.float64(0.382694873107447), 'Wbcc': np.float64(0.06693019003870061), 'Rbcc': np.float64(0.28922042351512717), 'Htn': np.float64(0.02319468656209716), 'Dm': np.float64(0.0004130157687605642), 'Cad': np.float64(0.02015251852893437), 'Appet': np.float64(0.07146829964634455), 'Pe': np.float64(0.19463371344897495), 'Ane': np.float64(0.0424985055345027)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03131881575727918, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028381642512077296, 'Pcc': 0.027242401779095628, 'Ba': 0.03021353930031804, 'Bgr': 0.027056277056277056, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030309988518943745, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.028693528693528692, 'Dm': 0.027673192771084338, 'Cad': 0.02694394213381555, 'Appet': 0.028370221327967807, 'Pe': 0.03007688828584351, 'Ane': 0.028484848484848488}
Top 10 Features Selected: ['Bp', 'Al', 'Pcv', 'Sc', 'Bu', 'Rbcc', 'Pot', 'Ba', 'Pe', 'Sg']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889528c20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}

Normalized Mathematical Scores
{'Age': np.float64(0.0005552474651585044), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07064830718959608), 'Al': np.float64(0.08123981409638958), 'Su': np.float64(0.03625524914560339), 'Rbc': np.float64(0.0011352184252064826), 'Pc': np.float64(0.06700636000887736), 'Pcc': np.float64(0.04192443494102272), 'Ba': np.float64(0.46919820397080164), 'Bgr': np.float64(4.362911169905294e-05), 'Bu': np.float64(0.0770692183792798), 'Sc': np.float64(0.07593826677437038), 'Sod': np.float64(0.04670012048444069), 'Pot': np.float64(0.1984533469430934), 'Hemo': np.float64(0.011615603295643021), 'Pcv': np.float64(0.382694873107447), 'Wbcc': np.float64(0.06693019003870061), 'Rbcc': np.float64(0.28922042351512717), 'Htn': np.float64(0.02319468656209716), 'Dm': np.float64(0.0004130157687605642), 'Cad': np.float64(0.02015251852893437), 'Appet': np.float64(0.07146829964634455), 'Pe': np.float64(0.19463371344897495), 'Ane': np.float64(0.0424985055345027)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03131881575727918, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028381642512077296, 'Pcc': 0.027242401779095628, 'Ba': 0.03021353930031804, 'Bgr': 0.027056277056277056, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030309988518943745, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.028693528693528692, 'Dm': 0.027673192771084338, 'Cad': 0.02694394213381555, 'Appet': 0.028370221327967807, 'Pe': 0.03007688828584351, 'Ane': 0.028484848484848488}
Top 15 Features Selected: ['Bp', 'Al', 'Pcv', 'Sc', 'Bu', 'Rbcc', 'Pot', 'Ba', 'Pe', 'Sg', 'Htn', 'Ane', 'Sod', 'Pc', 'Appet']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889d1ff20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.004887964692271122), 'Bp': np.float64(8.803218382772398), 'Sg': np.float64(0.6219324765632036), 'Al': np.float64(0.715171824866349), 'Su': np.float64(0.319162875750569), 'Rbc': np.float64(0.00999357570923964), 'Pc': np.float64(0.5898716201928145), 'Pcc': np.float64(0.36906995636015666), 'Ba': np.float64(4.130454254359554), 'Bgr': np.float64(0.0003840765981331331), 'Bu': np.float64(0.6784571599823763), 'Sc': np.float64(0.6685011460240117), 'Sod': np.float64(0.4111113591263141), 'Pot': np.float64(1.7470281519321484), 'Hemo': np.float64(0.10225469245919629), 'Pcv': np.float64(3.3689465419322278), 'Wbcc': np.float64(0.5892010793111393), 'Rbcc': np.float64(2.546070548961586), 'Htn': np.float64(0.20418789112609761), 'Dm': np.float64(0.0036358680079278723), 'Cad': np.float64(0.17740702157307642), 'Appet': np.float64(0.6291510492321863), 'Pe': np.float64(1.7134030841412715), 'Ane': np.float64(0.3741236251616886)}

Normalized Mathematical Scores
{'Age': np.float64(0.0005552474651585044), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07064830718959608), 'Al': np.float64(0.08123981409638958), 'Su': np.float64(0.03625524914560339), 'Rbc': np.float64(0.0011352184252064826), 'Pc': np.float64(0.06700636000887736), 'Pcc': np.float64(0.04192443494102272), 'Ba': np.float64(0.46919820397080164), 'Bgr': np.float64(4.362911169905294e-05), 'Bu': np.float64(0.0770692183792798), 'Sc': np.float64(0.07593826677437038), 'Sod': np.float64(0.04670012048444069), 'Pot': np.float64(0.1984533469430934), 'Hemo': np.float64(0.011615603295643021), 'Pcv': np.float64(0.382694873107447), 'Wbcc': np.float64(0.06693019003870061), 'Rbcc': np.float64(0.28922042351512717), 'Htn': np.float64(0.02319468656209716), 'Dm': np.float64(0.0004130157687605642), 'Cad': np.float64(0.02015251852893437), 'Appet': np.float64(0.07146829964634455), 'Pe': np.float64(0.19463371344897495), 'Ane': np.float64(0.0424985055345027)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03131881575727918, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028381642512077296, 'Pcc': 0.027242401779095628, 'Ba': 0.03021353930031804, 'Bgr': 0.027056277056277056, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030309988518943745, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.028693528693528692, 'Dm': 0.027673192771084338, 'Cad': 0.02694394213381555, 'Appet': 0.028370221327967807, 'Pe': 0.03007688828584351, 'Ane': 0.028484848484848488}
Top 20 Features Selected: ['Bp', 'Al', 'Pcv', 'Sc', 'Bu', 'Rbcc', 'Pot', 'Ba', 'Pe', 'Sg', 'Htn', 'Ane', 'Sod', 'Pc', 'Appet', 'Hemo', 'Wbcc', 'Su', 'Dm', 'Pcc']

Run 03/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889170aa0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}

Normalized Mathematical Scores
{'Age': np.float64(0.007423383293896278), 'Bp': np.float64(1.0), 'Sg': np.float64(0.004826789299017304), 'Al': np.float64(0.01981383806611752), 'Su': np.float64(0.16801922144812192), 'Rbc': np.float64(0.000872044032176023), 'Pc': np.float64(0.000872044032176023), 'Pcc': np.float64(9.347721761639062e-05), 'Ba': np.float64(0.21852460391383607), 'Bgr': np.float64(0.23069825897610255), 'Bu': np.float64(0.04133493541066486), 'Sc': np.float64(0.036783586010131555), 'Sod': np.float64(0.030141651019277894), 'Pot': np.float64(0.11187106994090354), 'Hemo': np.float64(9.785287148761952e-05), 'Pcv': np.float64(0.4001804013902255), 'Wbcc': np.float64(0.00629518023473806), 'Rbcc': np.float64(0.2045340838345111), 'Htn': np.float64(0.001749067071328728), 'Dm': np.float64(0.013369874155736842), 'Cad': np.float64(0.012857516312998496), 'Appet': np.float64(0.1261182614857142), 'Pe': np.float64(0.06190783554462462), 'Ane': np.float64(0.14711812652333725)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.028531243721117136, 'Al': 0.029906956136464335, 'Su': 0.029857397504456328, 'Rbc': 0.027051561365286855, 'Pc': 0.026838432635534086, 'Pcc': 0.026132699813337858, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.03021353930031804, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Pot': 0.029418126757516764, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.030090497737556562, 'Htn': 0.028373015873015873, 'Dm': 0.028958333333333336, 'Cad': 0.027443609022556388, 'Appet': 0.028790389395194696, 'Pe': 0.029211087420042643, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Bu']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889170ec0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}

Normalized Mathematical Scores
{'Age': np.float64(0.007423383293896278), 'Bp': np.float64(1.0), 'Sg': np.float64(0.004826789299017304), 'Al': np.float64(0.01981383806611752), 'Su': np.float64(0.16801922144812192), 'Rbc': np.float64(0.000872044032176023), 'Pc': np.float64(0.000872044032176023), 'Pcc': np.float64(9.347721761639062e-05), 'Ba': np.float64(0.21852460391383607), 'Bgr': np.float64(0.23069825897610255), 'Bu': np.float64(0.04133493541066486), 'Sc': np.float64(0.036783586010131555), 'Sod': np.float64(0.030141651019277894), 'Pot': np.float64(0.11187106994090354), 'Hemo': np.float64(9.785287148761952e-05), 'Pcv': np.float64(0.4001804013902255), 'Wbcc': np.float64(0.00629518023473806), 'Rbcc': np.float64(0.2045340838345111), 'Htn': np.float64(0.001749067071328728), 'Dm': np.float64(0.013369874155736842), 'Cad': np.float64(0.012857516312998496), 'Appet': np.float64(0.1261182614857142), 'Pe': np.float64(0.06190783554462462), 'Ane': np.float64(0.14711812652333725)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.028531243721117136, 'Al': 0.029906956136464335, 'Su': 0.029857397504456328, 'Rbc': 0.027051561365286855, 'Pc': 0.026838432635534086, 'Pcc': 0.026132699813337858, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.03021353930031804, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Pot': 0.029418126757516764, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.030090497737556562, 'Htn': 0.028373015873015873, 'Dm': 0.028958333333333336, 'Cad': 0.027443609022556388, 'Appet': 0.028790389395194696, 'Pe': 0.029211087420042643, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Bu', 'Rbcc', 'Ane', 'Al', 'Su', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5891b4d8b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}

Normalized Mathematical Scores
{'Age': np.float64(0.007423383293896278), 'Bp': np.float64(1.0), 'Sg': np.float64(0.004826789299017304), 'Al': np.float64(0.01981383806611752), 'Su': np.float64(0.16801922144812192), 'Rbc': np.float64(0.000872044032176023), 'Pc': np.float64(0.000872044032176023), 'Pcc': np.float64(9.347721761639062e-05), 'Ba': np.float64(0.21852460391383607), 'Bgr': np.float64(0.23069825897610255), 'Bu': np.float64(0.04133493541066486), 'Sc': np.float64(0.036783586010131555), 'Sod': np.float64(0.030141651019277894), 'Pot': np.float64(0.11187106994090354), 'Hemo': np.float64(9.785287148761952e-05), 'Pcv': np.float64(0.4001804013902255), 'Wbcc': np.float64(0.00629518023473806), 'Rbcc': np.float64(0.2045340838345111), 'Htn': np.float64(0.001749067071328728), 'Dm': np.float64(0.013369874155736842), 'Cad': np.float64(0.012857516312998496), 'Appet': np.float64(0.1261182614857142), 'Pe': np.float64(0.06190783554462462), 'Ane': np.float64(0.14711812652333725)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.028531243721117136, 'Al': 0.029906956136464335, 'Su': 0.029857397504456328, 'Rbc': 0.027051561365286855, 'Pc': 0.026838432635534086, 'Pcc': 0.026132699813337858, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.03021353930031804, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Pot': 0.029418126757516764, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.030090497737556562, 'Htn': 0.028373015873015873, 'Dm': 0.028958333333333336, 'Cad': 0.027443609022556388, 'Appet': 0.028790389395194696, 'Pe': 0.029211087420042643, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Bu', 'Rbcc', 'Ane', 'Al', 'Su', 'Ba', 'Pot', 'Pe', 'Dm', 'Appet', 'Sod']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889182c90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.07902023774231018), 'Bp': np.float64(10.644774035483648), 'Sg': np.float64(0.051380081404929716), 'Al': np.float64(0.21091382898948532), 'Su': np.float64(1.7885266459331455), 'Rbc': np.float64(0.009282711671505796), 'Pc': np.float64(0.009282711671505796), 'Pcc': np.float64(0.0009950438589922095), 'Ba': np.float64(2.3261450298563506), 'Bgr': np.float64(2.455730837180099), 'Bu': np.float64(0.4400010472178389), 'Sc': np.float64(0.39155296129262795), 'Sod': np.float64(0.32085106415661857), 'Pot': np.float64(1.1908422606287052), 'Hemo': np.float64(0.0010416217057089305), 'Pcv': np.float64(4.259829946228097), 'Wbcc': np.float64(0.06701077111142956), 'Rbcc': np.float64(2.1772191049730396), 'Htn': np.float64(0.01861842374719947), 'Dm': np.float64(0.1423192892706714), 'Cad': np.float64(0.13686535580941384), 'Appet': np.float64(1.3425003952634678), 'Pe': np.float64(0.6589949203984118), 'Ane': np.float64(1.5660392133646186)}

Normalized Mathematical Scores
{'Age': np.float64(0.007423383293896278), 'Bp': np.float64(1.0), 'Sg': np.float64(0.004826789299017304), 'Al': np.float64(0.01981383806611752), 'Su': np.float64(0.16801922144812192), 'Rbc': np.float64(0.000872044032176023), 'Pc': np.float64(0.000872044032176023), 'Pcc': np.float64(9.347721761639062e-05), 'Ba': np.float64(0.21852460391383607), 'Bgr': np.float64(0.23069825897610255), 'Bu': np.float64(0.04133493541066486), 'Sc': np.float64(0.036783586010131555), 'Sod': np.float64(0.030141651019277894), 'Pot': np.float64(0.11187106994090354), 'Hemo': np.float64(9.785287148761952e-05), 'Pcv': np.float64(0.4001804013902255), 'Wbcc': np.float64(0.00629518023473806), 'Rbcc': np.float64(0.2045340838345111), 'Htn': np.float64(0.001749067071328728), 'Dm': np.float64(0.013369874155736842), 'Cad': np.float64(0.012857516312998496), 'Appet': np.float64(0.1261182614857142), 'Pe': np.float64(0.06190783554462462), 'Ane': np.float64(0.14711812652333725)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.028531243721117136, 'Al': 0.029906956136464335, 'Su': 0.029857397504456328, 'Rbc': 0.027051561365286855, 'Pc': 0.026838432635534086, 'Pcc': 0.026132699813337858, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.03021353930031804, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Pot': 0.029418126757516764, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.030090497737556562, 'Htn': 0.028373015873015873, 'Dm': 0.028958333333333336, 'Cad': 0.027443609022556388, 'Appet': 0.028790389395194696, 'Pe': 0.029211087420042643, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Bu', 'Rbcc', 'Ane', 'Al', 'Su', 'Ba', 'Pot', 'Pe', 'Dm', 'Appet', 'Sod', 'Sg', 'Htn', 'Age', 'Hemo', 'Cad']

Run 04/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957c50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}

Normalized Mathematical Scores
{'Age': np.float64(0.04752832284825357), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06030250699348382), 'Al': np.float64(0.056108660742514846), 'Su': np.float64(0.4083349948316946), 'Rbc': np.float64(0.09722908846480315), 'Pc': np.float64(0.0022192637433987965), 'Pcc': np.float64(3.390571319253114e-07), 'Ba': np.float64(0.4862626213463846), 'Bgr': np.float64(0.1997450818651287), 'Bu': np.float64(0.3738152798687653), 'Sc': np.float64(0.1691020414675455), 'Sod': np.float64(0.14297996028299587), 'Pot': np.float64(0.47880140828859463), 'Hemo': np.float64(7.19872513695691e-05), 'Pcv': np.float64(0.10157520463766286), 'Wbcc': np.float64(0.07398844458271134), 'Rbcc': np.float64(0.2247584947361685), 'Htn': np.float64(0.001611477911972949), 'Dm': np.float64(0.015211685153563338), 'Cad': np.float64(0.04433850547570057), 'Appet': np.float64(0.17362238964473087), 'Pe': np.float64(0.51806842354042), 'Ane': np.float64(0.13367897368330217)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027526395173453996, 'Bp': 0.032018442622950824, 'Sg': 0.029030910609857977, 'Al': 0.02938045560996381, 'Su': 0.030090497737556562, 'Rbc': 0.02821939586645469, 'Pc': 0.026838432635534086, 'Pcc': 0.025989268947015427, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.03128054740957967, 'Sc': 0.030679156908665108, 'Sod': 0.02900988017658188, 'Pot': 0.03055037313432836, 'Hemo': 0.027432808155699723, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029631255487269532, 'Htn': 0.028068137824235385, 'Dm': 0.028125, 'Cad': 0.02694394213381555, 'Appet': 0.028577260665441927, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Bu', 'Pe', 'Sc', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889149490>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}

Normalized Mathematical Scores
{'Age': np.float64(0.04752832284825357), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06030250699348382), 'Al': np.float64(0.056108660742514846), 'Su': np.float64(0.4083349948316946), 'Rbc': np.float64(0.09722908846480315), 'Pc': np.float64(0.0022192637433987965), 'Pcc': np.float64(3.390571319253114e-07), 'Ba': np.float64(0.4862626213463846), 'Bgr': np.float64(0.1997450818651287), 'Bu': np.float64(0.3738152798687653), 'Sc': np.float64(0.1691020414675455), 'Sod': np.float64(0.14297996028299587), 'Pot': np.float64(0.47880140828859463), 'Hemo': np.float64(7.19872513695691e-05), 'Pcv': np.float64(0.10157520463766286), 'Wbcc': np.float64(0.07398844458271134), 'Rbcc': np.float64(0.2247584947361685), 'Htn': np.float64(0.001611477911972949), 'Dm': np.float64(0.015211685153563338), 'Cad': np.float64(0.04433850547570057), 'Appet': np.float64(0.17362238964473087), 'Pe': np.float64(0.51806842354042), 'Ane': np.float64(0.13367897368330217)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027526395173453996, 'Bp': 0.032018442622950824, 'Sg': 0.029030910609857977, 'Al': 0.02938045560996381, 'Su': 0.030090497737556562, 'Rbc': 0.02821939586645469, 'Pc': 0.026838432635534086, 'Pcc': 0.025989268947015427, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.03128054740957967, 'Sc': 0.030679156908665108, 'Sod': 0.02900988017658188, 'Pot': 0.03055037313432836, 'Hemo': 0.027432808155699723, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029631255487269532, 'Htn': 0.028068137824235385, 'Dm': 0.028125, 'Cad': 0.02694394213381555, 'Appet': 0.028577260665441927, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Bu', 'Pe', 'Sc', 'Pot', 'Su', 'Ba', 'Bgr', 'Rbcc', 'Al']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891703e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}

Normalized Mathematical Scores
{'Age': np.float64(0.04752832284825357), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06030250699348382), 'Al': np.float64(0.056108660742514846), 'Su': np.float64(0.4083349948316946), 'Rbc': np.float64(0.09722908846480315), 'Pc': np.float64(0.0022192637433987965), 'Pcc': np.float64(3.390571319253114e-07), 'Ba': np.float64(0.4862626213463846), 'Bgr': np.float64(0.1997450818651287), 'Bu': np.float64(0.3738152798687653), 'Sc': np.float64(0.1691020414675455), 'Sod': np.float64(0.14297996028299587), 'Pot': np.float64(0.47880140828859463), 'Hemo': np.float64(7.19872513695691e-05), 'Pcv': np.float64(0.10157520463766286), 'Wbcc': np.float64(0.07398844458271134), 'Rbcc': np.float64(0.2247584947361685), 'Htn': np.float64(0.001611477911972949), 'Dm': np.float64(0.015211685153563338), 'Cad': np.float64(0.04433850547570057), 'Appet': np.float64(0.17362238964473087), 'Pe': np.float64(0.51806842354042), 'Ane': np.float64(0.13367897368330217)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027526395173453996, 'Bp': 0.032018442622950824, 'Sg': 0.029030910609857977, 'Al': 0.02938045560996381, 'Su': 0.030090497737556562, 'Rbc': 0.02821939586645469, 'Pc': 0.026838432635534086, 'Pcc': 0.025989268947015427, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.03128054740957967, 'Sc': 0.030679156908665108, 'Sod': 0.02900988017658188, 'Pot': 0.03055037313432836, 'Hemo': 0.027432808155699723, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029631255487269532, 'Htn': 0.028068137824235385, 'Dm': 0.028125, 'Cad': 0.02694394213381555, 'Appet': 0.028577260665441927, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Bu', 'Pe', 'Sc', 'Pot', 'Su', 'Ba', 'Bgr', 'Rbcc', 'Al', 'Ane', 'Sg', 'Sod', 'Pcv', 'Appet']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889189760>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.22219281828673063), 'Bp': np.float64(4.674956004573073), 'Sg': np.float64(0.28191156715999693), 'Al': np.float64(0.26230552044677324), 'Su': np.float64(1.9089481359657456), 'Rbc': np.float64(0.454541710937698), 'Pc': np.float64(0.01037496036293352), 'Pcc': np.float64(1.5850771747875592e-06), 'Ba': np.float64(2.2732563614627233), 'Bgr': np.float64(0.9337994698493236), 'Bu': np.float64(1.747569987223648), 'Sc': np.float64(0.7905446041442667), 'Sod': np.float64(0.6684250238586111), 'Pot': np.float64(2.238375518676809), 'Hemo': np.float64(0.00033653723304287827), 'Pcv': np.float64(0.4748596128365806), 'Wbcc': np.float64(0.3458927232709685), 'Rbcc': np.float64(1.0507360745456564), 'Htn': np.float64(0.007533588340814816), 'Dm': np.float64(0.071113958848326), 'Cad': np.float64(0.2072805624074225), 'Appet': np.float64(0.8116770329979603), 'Pe': np.float64(2.421947087409993), 'Ane': np.float64(0.6249433207059194)}

Normalized Mathematical Scores
{'Age': np.float64(0.04752832284825357), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06030250699348382), 'Al': np.float64(0.056108660742514846), 'Su': np.float64(0.4083349948316946), 'Rbc': np.float64(0.09722908846480315), 'Pc': np.float64(0.0022192637433987965), 'Pcc': np.float64(3.390571319253114e-07), 'Ba': np.float64(0.4862626213463846), 'Bgr': np.float64(0.1997450818651287), 'Bu': np.float64(0.3738152798687653), 'Sc': np.float64(0.1691020414675455), 'Sod': np.float64(0.14297996028299587), 'Pot': np.float64(0.47880140828859463), 'Hemo': np.float64(7.19872513695691e-05), 'Pcv': np.float64(0.10157520463766286), 'Wbcc': np.float64(0.07398844458271134), 'Rbcc': np.float64(0.2247584947361685), 'Htn': np.float64(0.001611477911972949), 'Dm': np.float64(0.015211685153563338), 'Cad': np.float64(0.04433850547570057), 'Appet': np.float64(0.17362238964473087), 'Pe': np.float64(0.51806842354042), 'Ane': np.float64(0.13367897368330217)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027526395173453996, 'Bp': 0.032018442622950824, 'Sg': 0.029030910609857977, 'Al': 0.02938045560996381, 'Su': 0.030090497737556562, 'Rbc': 0.02821939586645469, 'Pc': 0.026838432635534086, 'Pcc': 0.025989268947015427, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.03128054740957967, 'Sc': 0.030679156908665108, 'Sod': 0.02900988017658188, 'Pot': 0.03055037313432836, 'Hemo': 0.027432808155699723, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029631255487269532, 'Htn': 0.028068137824235385, 'Dm': 0.028125, 'Cad': 0.02694394213381555, 'Appet': 0.028577260665441927, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Bu', 'Pe', 'Sc', 'Pot', 'Su', 'Ba', 'Bgr', 'Rbcc', 'Al', 'Ane', 'Sg', 'Sod', 'Pcv', 'Appet', 'Rbc', 'Dm', 'Htn', 'Age', 'Hemo']

Run 05/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915d160>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}

Normalized Mathematical Scores
{'Age': np.float64(1.513589006131811e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09029290427477597), 'Al': np.float64(0.020529749982642866), 'Su': np.float64(0.5588309876611757), 'Rbc': np.float64(0.0062155667339496585), 'Pc': np.float64(0.10091314907080509), 'Pcc': np.float64(0.04770579916269954), 'Ba': np.float64(0.2070551816961245), 'Bgr': np.float64(0.054516213889269936), 'Bu': np.float64(0.3870883225140087), 'Sc': np.float64(0.09897634936701673), 'Sod': np.float64(0.047963117772892236), 'Pot': np.float64(0.05564842404614212), 'Hemo': np.float64(0.004997459028407271), 'Pcv': np.float64(0.5992132160291358), 'Wbcc': np.float64(0.003207952788070596), 'Rbcc': np.float64(0.14082215963931136), 'Htn': np.float64(0.06604506984090575), 'Dm': np.float64(0.0016823115036752932), 'Cad': np.float64(0.0018004503799279711), 'Appet': np.float64(0.12819104532915615), 'Pe': np.float64(0.022626065069649034), 'Ane': np.float64(0.1658541394751749)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.027364110201042444, 'Pc': 0.028985507246376812, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.02862400327131466, 'Hemo': 0.027884615384615386, 'Pcv': 0.03128054740957967, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.029631255487269532, 'Htn': 0.02976190476190476, 'Dm': 0.027673192771084338, 'Cad': 0.0264808362369338, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.030303030303030304}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Su']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}

Normalized Mathematical Scores
{'Age': np.float64(1.513589006131811e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09029290427477597), 'Al': np.float64(0.020529749982642866), 'Su': np.float64(0.5588309876611757), 'Rbc': np.float64(0.0062155667339496585), 'Pc': np.float64(0.10091314907080509), 'Pcc': np.float64(0.04770579916269954), 'Ba': np.float64(0.2070551816961245), 'Bgr': np.float64(0.054516213889269936), 'Bu': np.float64(0.3870883225140087), 'Sc': np.float64(0.09897634936701673), 'Sod': np.float64(0.047963117772892236), 'Pot': np.float64(0.05564842404614212), 'Hemo': np.float64(0.004997459028407271), 'Pcv': np.float64(0.5992132160291358), 'Wbcc': np.float64(0.003207952788070596), 'Rbcc': np.float64(0.14082215963931136), 'Htn': np.float64(0.06604506984090575), 'Dm': np.float64(0.0016823115036752932), 'Cad': np.float64(0.0018004503799279711), 'Appet': np.float64(0.12819104532915615), 'Pe': np.float64(0.022626065069649034), 'Ane': np.float64(0.1658541394751749)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.027364110201042444, 'Pc': 0.028985507246376812, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.02862400327131466, 'Hemo': 0.027884615384615386, 'Pcv': 0.03128054740957967, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.029631255487269532, 'Htn': 0.02976190476190476, 'Dm': 0.027673192771084338, 'Cad': 0.0264808362369338, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.030303030303030304}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Su', 'Ane', 'Sg', 'Htn', 'Rbcc', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889148d40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}

Normalized Mathematical Scores
{'Age': np.float64(1.513589006131811e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09029290427477597), 'Al': np.float64(0.020529749982642866), 'Su': np.float64(0.5588309876611757), 'Rbc': np.float64(0.0062155667339496585), 'Pc': np.float64(0.10091314907080509), 'Pcc': np.float64(0.04770579916269954), 'Ba': np.float64(0.2070551816961245), 'Bgr': np.float64(0.054516213889269936), 'Bu': np.float64(0.3870883225140087), 'Sc': np.float64(0.09897634936701673), 'Sod': np.float64(0.047963117772892236), 'Pot': np.float64(0.05564842404614212), 'Hemo': np.float64(0.004997459028407271), 'Pcv': np.float64(0.5992132160291358), 'Wbcc': np.float64(0.003207952788070596), 'Rbcc': np.float64(0.14082215963931136), 'Htn': np.float64(0.06604506984090575), 'Dm': np.float64(0.0016823115036752932), 'Cad': np.float64(0.0018004503799279711), 'Appet': np.float64(0.12819104532915615), 'Pe': np.float64(0.022626065069649034), 'Ane': np.float64(0.1658541394751749)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.027364110201042444, 'Pc': 0.028985507246376812, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.02862400327131466, 'Hemo': 0.027884615384615386, 'Pcv': 0.03128054740957967, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.029631255487269532, 'Htn': 0.02976190476190476, 'Dm': 0.027673192771084338, 'Cad': 0.0264808362369338, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.030303030303030304}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Su', 'Ane', 'Sg', 'Htn', 'Rbcc', 'Ba', 'Al', 'Pc', 'Appet', 'Bgr', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891811c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00010768277396376136), 'Bp': np.float64(7.114399848804385), 'Sg': np.float64(0.642379824520575), 'Al': np.float64(0.14605685017250622), 'Su': np.float64(3.9757470941238733), 'Rbc': np.float64(0.044220027032245014), 'Pc': np.float64(0.7179364924917101), 'Pcc': np.float64(0.33939813035020194), 'Ba': np.float64(1.4730733533530724), 'Bgr': np.float64(0.38785014385120953), 'Bu': np.float64(2.7539011031676064), 'Sc': np.float64(0.7041573249719137), 'Sod': np.float64(0.34122879783165144), 'Pot': np.float64(0.3959051396200758), 'Hemo': np.float64(0.0355539217561068), 'Pcv': np.float64(4.263042413519273), 'Wbcc': np.float64(0.02282265883042105), 'Rbcc': np.float64(1.0018651512462236), 'Htn': np.float64(0.4698710348904149), 'Dm': np.float64(0.011968636707389383), 'Cad': np.float64(0.012809123910739354), 'Appet': np.float64(0.9120023535078245), 'Pe': np.float64(0.16097087391054926), 'Ane': np.float64(1.1799526648057657)}

Normalized Mathematical Scores
{'Age': np.float64(1.513589006131811e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09029290427477597), 'Al': np.float64(0.020529749982642866), 'Su': np.float64(0.5588309876611757), 'Rbc': np.float64(0.0062155667339496585), 'Pc': np.float64(0.10091314907080509), 'Pcc': np.float64(0.04770579916269954), 'Ba': np.float64(0.2070551816961245), 'Bgr': np.float64(0.054516213889269936), 'Bu': np.float64(0.3870883225140087), 'Sc': np.float64(0.09897634936701673), 'Sod': np.float64(0.047963117772892236), 'Pot': np.float64(0.05564842404614212), 'Hemo': np.float64(0.004997459028407271), 'Pcv': np.float64(0.5992132160291358), 'Wbcc': np.float64(0.003207952788070596), 'Rbcc': np.float64(0.14082215963931136), 'Htn': np.float64(0.06604506984090575), 'Dm': np.float64(0.0016823115036752932), 'Cad': np.float64(0.0018004503799279711), 'Appet': np.float64(0.12819104532915615), 'Pe': np.float64(0.022626065069649034), 'Ane': np.float64(0.1658541394751749)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.027364110201042444, 'Pc': 0.028985507246376812, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.02862400327131466, 'Hemo': 0.027884615384615386, 'Pcv': 0.03128054740957967, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.029631255487269532, 'Htn': 0.02976190476190476, 'Dm': 0.027673192771084338, 'Cad': 0.0264808362369338, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.030303030303030304}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Su', 'Ane', 'Sg', 'Htn', 'Rbcc', 'Ba', 'Al', 'Pc', 'Appet', 'Bgr', 'Pot', 'Sod', 'Pe', 'Hemo', 'Dm', 'Rbc']

Run 06/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c05f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}

Normalized Mathematical Scores
{'Age': np.float64(0.019158682687681772), 'Bp': np.float64(1.0), 'Sg': np.float64(0.3120869601278187), 'Al': np.float64(0.037079982236891504), 'Su': np.float64(0.08379549185768544), 'Rbc': np.float64(0.014869336496528442), 'Pc': np.float64(0.022751193408051793), 'Pcc': np.float64(0.062291180111995234), 'Ba': np.float64(0.3907006905546945), 'Bgr': np.float64(0.0722280300571858), 'Bu': np.float64(0.1525229755193539), 'Sc': np.float64(0.002600286960626072), 'Sod': np.float64(0.22334659484822916), 'Pot': np.float64(0.12291456408013202), 'Hemo': np.float64(0.005075204565962359), 'Pcv': np.float64(0.4330741204226484), 'Wbcc': np.float64(0.022073515610787166), 'Rbcc': np.float64(0.15498941126021554), 'Htn': np.float64(0.0008780723041911753), 'Dm': np.float64(0.0005406832954032585), 'Cad': np.float64(0.0025749200231776326), 'Appet': np.float64(0.12733833650098866), 'Pe': np.float64(0.07599960904662756), 'Ane': np.float64(0.0015086372615939665)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.029906956136464335, 'Su': 0.028991596638655463, 'Rbc': 0.027526395173453996, 'Pc': 0.02782608695652174, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.031054405392392875, 'Sc': 0.02889344262295082, 'Sod': 0.030309988518943745, 'Pot': 0.029418126757516764, 'Hemo': 0.02804284323271665, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.029857397504456328, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904, 'Cad': 0.026631393298059962, 'Appet': 0.028790389395194696, 'Pe': 0.02900988017658188, 'Ane': 0.027346637102734665}
Top 5 Features Selected: ['Bp', 'Sg', 'Pcv', 'Bu', 'Sod']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a851880>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}

Normalized Mathematical Scores
{'Age': np.float64(0.019158682687681772), 'Bp': np.float64(1.0), 'Sg': np.float64(0.3120869601278187), 'Al': np.float64(0.037079982236891504), 'Su': np.float64(0.08379549185768544), 'Rbc': np.float64(0.014869336496528442), 'Pc': np.float64(0.022751193408051793), 'Pcc': np.float64(0.062291180111995234), 'Ba': np.float64(0.3907006905546945), 'Bgr': np.float64(0.0722280300571858), 'Bu': np.float64(0.1525229755193539), 'Sc': np.float64(0.002600286960626072), 'Sod': np.float64(0.22334659484822916), 'Pot': np.float64(0.12291456408013202), 'Hemo': np.float64(0.005075204565962359), 'Pcv': np.float64(0.4330741204226484), 'Wbcc': np.float64(0.022073515610787166), 'Rbcc': np.float64(0.15498941126021554), 'Htn': np.float64(0.0008780723041911753), 'Dm': np.float64(0.0005406832954032585), 'Cad': np.float64(0.0025749200231776326), 'Appet': np.float64(0.12733833650098866), 'Pe': np.float64(0.07599960904662756), 'Ane': np.float64(0.0015086372615939665)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.029906956136464335, 'Su': 0.028991596638655463, 'Rbc': 0.027526395173453996, 'Pc': 0.02782608695652174, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.031054405392392875, 'Sc': 0.02889344262295082, 'Sod': 0.030309988518943745, 'Pot': 0.029418126757516764, 'Hemo': 0.02804284323271665, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.029857397504456328, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904, 'Cad': 0.026631393298059962, 'Appet': 0.028790389395194696, 'Pe': 0.02900988017658188, 'Ane': 0.027346637102734665}
Top 10 Features Selected: ['Bp', 'Sg', 'Pcv', 'Bu', 'Sod', 'Ba', 'Al', 'Rbcc', 'Pot', 'Bgr']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910d070>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}

Normalized Mathematical Scores
{'Age': np.float64(0.019158682687681772), 'Bp': np.float64(1.0), 'Sg': np.float64(0.3120869601278187), 'Al': np.float64(0.037079982236891504), 'Su': np.float64(0.08379549185768544), 'Rbc': np.float64(0.014869336496528442), 'Pc': np.float64(0.022751193408051793), 'Pcc': np.float64(0.062291180111995234), 'Ba': np.float64(0.3907006905546945), 'Bgr': np.float64(0.0722280300571858), 'Bu': np.float64(0.1525229755193539), 'Sc': np.float64(0.002600286960626072), 'Sod': np.float64(0.22334659484822916), 'Pot': np.float64(0.12291456408013202), 'Hemo': np.float64(0.005075204565962359), 'Pcv': np.float64(0.4330741204226484), 'Wbcc': np.float64(0.022073515610787166), 'Rbcc': np.float64(0.15498941126021554), 'Htn': np.float64(0.0008780723041911753), 'Dm': np.float64(0.0005406832954032585), 'Cad': np.float64(0.0025749200231776326), 'Appet': np.float64(0.12733833650098866), 'Pe': np.float64(0.07599960904662756), 'Ane': np.float64(0.0015086372615939665)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.029906956136464335, 'Su': 0.028991596638655463, 'Rbc': 0.027526395173453996, 'Pc': 0.02782608695652174, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.031054405392392875, 'Sc': 0.02889344262295082, 'Sod': 0.030309988518943745, 'Pot': 0.029418126757516764, 'Hemo': 0.02804284323271665, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.029857397504456328, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904, 'Cad': 0.026631393298059962, 'Appet': 0.028790389395194696, 'Pe': 0.02900988017658188, 'Ane': 0.027346637102734665}
Top 15 Features Selected: ['Bp', 'Sg', 'Pcv', 'Bu', 'Sod', 'Ba', 'Al', 'Rbcc', 'Pot', 'Bgr', 'Pe', 'Su', 'Sc', 'Appet', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915a750>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15043261110463363), 'Bp': np.float64(7.851928734189824), 'Sg': np.float64(2.4504845697935735), 'Al': np.float64(0.2911493779890966), 'Su': np.float64(0.6579562303129297), 'Rbc': np.float64(0.11675297049542911), 'Pc': np.float64(0.17864074925779197), 'Pcc': np.float64(0.4891059070079691), 'Ba': np.float64(3.067753978634212), 'Bgr': np.float64(0.5671293446199434), 'Bu': np.float64(1.197599534104546), 'Sc': np.float64(0.02041726790327898), 'Sod': np.float64(1.7537015457722633), 'Pot': np.float64(0.9651163975512049), 'Hemo': np.float64(0.03985014456337124), 'Pcv': np.float64(3.400467130180577), 'Wbcc': np.float64(0.17331967148892738), 'Rbcc': np.float64(1.2169658117692501), 'Htn': np.float64(0.006894561155974957), 'Dm': np.float64(0.0042454067032732905), 'Cad': np.float64(0.02021808851822918), 'Appet': np.float64(0.9998515433360456), 'Pe': np.float64(0.5967435140604078), 'Ane': np.float64(0.011845712263779114)}

Normalized Mathematical Scores
{'Age': np.float64(0.019158682687681772), 'Bp': np.float64(1.0), 'Sg': np.float64(0.3120869601278187), 'Al': np.float64(0.037079982236891504), 'Su': np.float64(0.08379549185768544), 'Rbc': np.float64(0.014869336496528442), 'Pc': np.float64(0.022751193408051793), 'Pcc': np.float64(0.062291180111995234), 'Ba': np.float64(0.3907006905546945), 'Bgr': np.float64(0.0722280300571858), 'Bu': np.float64(0.1525229755193539), 'Sc': np.float64(0.002600286960626072), 'Sod': np.float64(0.22334659484822916), 'Pot': np.float64(0.12291456408013202), 'Hemo': np.float64(0.005075204565962359), 'Pcv': np.float64(0.4330741204226484), 'Wbcc': np.float64(0.022073515610787166), 'Rbcc': np.float64(0.15498941126021554), 'Htn': np.float64(0.0008780723041911753), 'Dm': np.float64(0.0005406832954032585), 'Cad': np.float64(0.0025749200231776326), 'Appet': np.float64(0.12733833650098866), 'Pe': np.float64(0.07599960904662756), 'Ane': np.float64(0.0015086372615939665)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.029906956136464335, 'Su': 0.028991596638655463, 'Rbc': 0.027526395173453996, 'Pc': 0.02782608695652174, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.031054405392392875, 'Sc': 0.02889344262295082, 'Sod': 0.030309988518943745, 'Pot': 0.029418126757516764, 'Hemo': 0.02804284323271665, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.029857397504456328, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904, 'Cad': 0.026631393298059962, 'Appet': 0.028790389395194696, 'Pe': 0.02900988017658188, 'Ane': 0.027346637102734665}
Top 20 Features Selected: ['Bp', 'Sg', 'Pcv', 'Bu', 'Sod', 'Ba', 'Al', 'Rbcc', 'Pot', 'Bgr', 'Pe', 'Su', 'Sc', 'Appet', 'Hemo', 'Htn', 'Pc', 'Pcc', 'Age', 'Dm']

Run 07/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588935f890>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}

Normalized Mathematical Scores
{'Age': np.float64(0.0072142403462373975), 'Bp': np.float64(1.0), 'Sg': np.float64(0.10103893880883848), 'Al': np.float64(0.009444911515773216), 'Su': np.float64(0.5032054283744509), 'Rbc': np.float64(0.00012132297915835015), 'Pc': np.float64(0.07870306681077589), 'Pcc': np.float64(0.17814624915099325), 'Ba': np.float64(0.3948697953646531), 'Bgr': np.float64(0.01380970344715367), 'Bu': np.float64(0.506788424637601), 'Sc': np.float64(0.3707456241009536), 'Sod': np.float64(0.1391901250616206), 'Pot': np.float64(0.268119412937943), 'Hemo': np.float64(0.06902076084793006), 'Pcv': np.float64(0.32413959891710714), 'Wbcc': np.float64(0.006157004426655095), 'Rbcc': np.float64(0.5230743431986761), 'Htn': np.float64(0.044020225021212105), 'Dm': np.float64(0.0013201601562666345), 'Cad': np.float64(0.014309539222956812), 'Appet': np.float64(0.09896081249709847), 'Pe': np.float64(0.13130109692447842), 'Ane': np.float64(0.36283657733624086)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02889344262295082, 'Su': 0.030330882352941176, 'Rbc': 0.02661064425770308, 'Pc': 0.02782608695652174, 'Pcc': 0.028370221327967807, 'Ba': 0.02946912242686891, 'Bgr': 0.027809742999616416, 'Bu': 0.03200204813108039, 'Sc': 0.031544957774465976, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030834914611005692, 'Htn': 0.02886002886002886, 'Dm': 0.027673192771084338, 'Cad': 0.027106227106227107, 'Appet': 0.027598020555767037, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Rbcc', 'Su']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889529e20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}

Normalized Mathematical Scores
{'Age': np.float64(0.0072142403462373975), 'Bp': np.float64(1.0), 'Sg': np.float64(0.10103893880883848), 'Al': np.float64(0.009444911515773216), 'Su': np.float64(0.5032054283744509), 'Rbc': np.float64(0.00012132297915835015), 'Pc': np.float64(0.07870306681077589), 'Pcc': np.float64(0.17814624915099325), 'Ba': np.float64(0.3948697953646531), 'Bgr': np.float64(0.01380970344715367), 'Bu': np.float64(0.506788424637601), 'Sc': np.float64(0.3707456241009536), 'Sod': np.float64(0.1391901250616206), 'Pot': np.float64(0.268119412937943), 'Hemo': np.float64(0.06902076084793006), 'Pcv': np.float64(0.32413959891710714), 'Wbcc': np.float64(0.006157004426655095), 'Rbcc': np.float64(0.5230743431986761), 'Htn': np.float64(0.044020225021212105), 'Dm': np.float64(0.0013201601562666345), 'Cad': np.float64(0.014309539222956812), 'Appet': np.float64(0.09896081249709847), 'Pe': np.float64(0.13130109692447842), 'Ane': np.float64(0.36283657733624086)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02889344262295082, 'Su': 0.030330882352941176, 'Rbc': 0.02661064425770308, 'Pc': 0.02782608695652174, 'Pcc': 0.028370221327967807, 'Ba': 0.02946912242686891, 'Bgr': 0.027809742999616416, 'Bu': 0.03200204813108039, 'Sc': 0.031544957774465976, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030834914611005692, 'Htn': 0.02886002886002886, 'Dm': 0.027673192771084338, 'Cad': 0.027106227106227107, 'Appet': 0.027598020555767037, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Rbcc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957c50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}

Normalized Mathematical Scores
{'Age': np.float64(0.0072142403462373975), 'Bp': np.float64(1.0), 'Sg': np.float64(0.10103893880883848), 'Al': np.float64(0.009444911515773216), 'Su': np.float64(0.5032054283744509), 'Rbc': np.float64(0.00012132297915835015), 'Pc': np.float64(0.07870306681077589), 'Pcc': np.float64(0.17814624915099325), 'Ba': np.float64(0.3948697953646531), 'Bgr': np.float64(0.01380970344715367), 'Bu': np.float64(0.506788424637601), 'Sc': np.float64(0.3707456241009536), 'Sod': np.float64(0.1391901250616206), 'Pot': np.float64(0.268119412937943), 'Hemo': np.float64(0.06902076084793006), 'Pcv': np.float64(0.32413959891710714), 'Wbcc': np.float64(0.006157004426655095), 'Rbcc': np.float64(0.5230743431986761), 'Htn': np.float64(0.044020225021212105), 'Dm': np.float64(0.0013201601562666345), 'Cad': np.float64(0.014309539222956812), 'Appet': np.float64(0.09896081249709847), 'Pe': np.float64(0.13130109692447842), 'Ane': np.float64(0.36283657733624086)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02889344262295082, 'Su': 0.030330882352941176, 'Rbc': 0.02661064425770308, 'Pc': 0.02782608695652174, 'Pcc': 0.028370221327967807, 'Ba': 0.02946912242686891, 'Bgr': 0.027809742999616416, 'Bu': 0.03200204813108039, 'Sc': 0.031544957774465976, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030834914611005692, 'Htn': 0.02886002886002886, 'Dm': 0.027673192771084338, 'Cad': 0.027106227106227107, 'Appet': 0.027598020555767037, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Rbcc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Pot', 'Sod', 'Al', 'Htn', 'Pe', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a7c48c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.043398375441022825), 'Bp': np.float64(6.015654228051515), 'Sg': np.float64(0.6078153194432275), 'Al': np.float64(0.056817321893433595), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.0007298370925337349), 'Pc': np.float64(0.4734504366208649), 'Pcc': np.float64(1.0716662369166912), 'Ba': np.float64(2.375400154015212), 'Bgr': np.float64(0.08307440093000755), 'Bu': np.float64(3.048663929398751), 'Sc': np.float64(2.230277481154499), 'Sod': np.float64(0.8373196643299571), 'Pot': np.float64(1.612913680062827), 'Hemo': np.float64(0.41520503181818297), 'Pcv': np.float64(1.949911748704618), 'Wbcc': np.float64(0.037038409711339614), 'Rbcc': np.float64(3.1466343842483853), 'Htn': np.float64(0.2648104527686337), 'Dm': np.float64(0.007941627025750528), 'Cad': np.float64(0.08608124012804914), 'Appet': np.float64(0.5953140301095836), 'Pe': np.float64(0.7898619988615404), 'Ane': np.float64(2.182699390544498)}

Normalized Mathematical Scores
{'Age': np.float64(0.0072142403462373975), 'Bp': np.float64(1.0), 'Sg': np.float64(0.10103893880883848), 'Al': np.float64(0.009444911515773216), 'Su': np.float64(0.5032054283744509), 'Rbc': np.float64(0.00012132297915835015), 'Pc': np.float64(0.07870306681077589), 'Pcc': np.float64(0.17814624915099325), 'Ba': np.float64(0.3948697953646531), 'Bgr': np.float64(0.01380970344715367), 'Bu': np.float64(0.506788424637601), 'Sc': np.float64(0.3707456241009536), 'Sod': np.float64(0.1391901250616206), 'Pot': np.float64(0.268119412937943), 'Hemo': np.float64(0.06902076084793006), 'Pcv': np.float64(0.32413959891710714), 'Wbcc': np.float64(0.006157004426655095), 'Rbcc': np.float64(0.5230743431986761), 'Htn': np.float64(0.044020225021212105), 'Dm': np.float64(0.0013201601562666345), 'Cad': np.float64(0.014309539222956812), 'Appet': np.float64(0.09896081249709847), 'Pe': np.float64(0.13130109692447842), 'Ane': np.float64(0.36283657733624086)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027051561365286855, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02889344262295082, 'Su': 0.030330882352941176, 'Rbc': 0.02661064425770308, 'Pc': 0.02782608695652174, 'Pcc': 0.028370221327967807, 'Ba': 0.02946912242686891, 'Bgr': 0.027809742999616416, 'Bu': 0.03200204813108039, 'Sc': 0.031544957774465976, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030834914611005692, 'Htn': 0.02886002886002886, 'Dm': 0.027673192771084338, 'Cad': 0.027106227106227107, 'Appet': 0.027598020555767037, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Rbcc', 'Su', 'Ane', 'Pcv', 'Sg', 'Ba', 'Pot', 'Sod', 'Al', 'Htn', 'Pe', 'Hemo', 'Pcc', 'Pc', 'Bgr', 'Dm', 'Appet']

Run 08/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c05f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}

Normalized Mathematical Scores
{'Age': np.float64(0.028355286940029645), 'Bp': np.float64(1.0), 'Sg': np.float64(0.03600380122932324), 'Al': np.float64(0.0009930734544059683), 'Su': np.float64(0.3937919033341587), 'Rbc': np.float64(0.0009192304325720531), 'Pc': np.float64(0.006453854073099695), 'Pcc': np.float64(0.0022502228637772256), 'Ba': np.float64(0.5132431352785328), 'Bgr': np.float64(0.14732978276177483), 'Bu': np.float64(0.2538279859610823), 'Sc': np.float64(0.049047585366247384), 'Sod': np.float64(0.0035091695252385913), 'Pot': np.float64(0.4426490849514444), 'Hemo': np.float64(0.017172253396076913), 'Pcv': np.float64(0.2311671399221317), 'Wbcc': np.float64(0.35703984087316437), 'Rbcc': np.float64(0.37490255226785907), 'Htn': np.float64(0.002991678415922277), 'Dm': np.float64(0.020353034940444378), 'Cad': np.float64(0.008909338143942748), 'Appet': np.float64(0.3416917484207587), 'Pe': np.float64(0.7387086367936082), 'Ane': np.float64(0.15530068624513813)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029386529386529386, 'Al': 0.02844163539403516, 'Su': 0.030090497737556562, 'Rbc': 0.02661064425770308, 'Pc': 0.02715098147128967, 'Pcc': 0.026279628993473032, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03009207275993712, 'Sod': 0.027425373134328357, 'Pot': 0.03055037313432836, 'Hemo': 0.028371628371628373, 'Pcv': 0.029437229437229435, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.029857397504456328, 'Htn': 0.02821869488536155, 'Dm': 0.028782894736842105, 'Cad': 0.027106227106227107, 'Appet': 0.028790389395194696, 'Pe': 0.031054405392392875, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Sc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915e450>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}

Normalized Mathematical Scores
{'Age': np.float64(0.028355286940029645), 'Bp': np.float64(1.0), 'Sg': np.float64(0.03600380122932324), 'Al': np.float64(0.0009930734544059683), 'Su': np.float64(0.3937919033341587), 'Rbc': np.float64(0.0009192304325720531), 'Pc': np.float64(0.006453854073099695), 'Pcc': np.float64(0.0022502228637772256), 'Ba': np.float64(0.5132431352785328), 'Bgr': np.float64(0.14732978276177483), 'Bu': np.float64(0.2538279859610823), 'Sc': np.float64(0.049047585366247384), 'Sod': np.float64(0.0035091695252385913), 'Pot': np.float64(0.4426490849514444), 'Hemo': np.float64(0.017172253396076913), 'Pcv': np.float64(0.2311671399221317), 'Wbcc': np.float64(0.35703984087316437), 'Rbcc': np.float64(0.37490255226785907), 'Htn': np.float64(0.002991678415922277), 'Dm': np.float64(0.020353034940444378), 'Cad': np.float64(0.008909338143942748), 'Appet': np.float64(0.3416917484207587), 'Pe': np.float64(0.7387086367936082), 'Ane': np.float64(0.15530068624513813)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029386529386529386, 'Al': 0.02844163539403516, 'Su': 0.030090497737556562, 'Rbc': 0.02661064425770308, 'Pc': 0.02715098147128967, 'Pcc': 0.026279628993473032, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03009207275993712, 'Sod': 0.027425373134328357, 'Pot': 0.03055037313432836, 'Hemo': 0.028371628371628373, 'Pcv': 0.029437229437229435, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.029857397504456328, 'Htn': 0.02821869488536155, 'Dm': 0.028782894736842105, 'Cad': 0.027106227106227107, 'Appet': 0.028790389395194696, 'Pe': 0.031054405392392875, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Sc', 'Su', 'Ba', 'Rbcc', 'Pcv', 'Sg']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588918b650>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}

Normalized Mathematical Scores
{'Age': np.float64(0.028355286940029645), 'Bp': np.float64(1.0), 'Sg': np.float64(0.03600380122932324), 'Al': np.float64(0.0009930734544059683), 'Su': np.float64(0.3937919033341587), 'Rbc': np.float64(0.0009192304325720531), 'Pc': np.float64(0.006453854073099695), 'Pcc': np.float64(0.0022502228637772256), 'Ba': np.float64(0.5132431352785328), 'Bgr': np.float64(0.14732978276177483), 'Bu': np.float64(0.2538279859610823), 'Sc': np.float64(0.049047585366247384), 'Sod': np.float64(0.0035091695252385913), 'Pot': np.float64(0.4426490849514444), 'Hemo': np.float64(0.017172253396076913), 'Pcv': np.float64(0.2311671399221317), 'Wbcc': np.float64(0.35703984087316437), 'Rbcc': np.float64(0.37490255226785907), 'Htn': np.float64(0.002991678415922277), 'Dm': np.float64(0.020353034940444378), 'Cad': np.float64(0.008909338143942748), 'Appet': np.float64(0.3416917484207587), 'Pe': np.float64(0.7387086367936082), 'Ane': np.float64(0.15530068624513813)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029386529386529386, 'Al': 0.02844163539403516, 'Su': 0.030090497737556562, 'Rbc': 0.02661064425770308, 'Pc': 0.02715098147128967, 'Pcc': 0.026279628993473032, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03009207275993712, 'Sod': 0.027425373134328357, 'Pot': 0.03055037313432836, 'Hemo': 0.028371628371628373, 'Pcv': 0.029437229437229435, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.029857397504456328, 'Htn': 0.02821869488536155, 'Dm': 0.028782894736842105, 'Cad': 0.027106227106227107, 'Appet': 0.028790389395194696, 'Pe': 0.031054405392392875, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Sc', 'Su', 'Ba', 'Rbcc', 'Pcv', 'Sg', 'Ane', 'Bgr', 'Wbcc', 'Appet', 'Dm']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c39e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.12593006290796194), 'Bp': np.float64(4.441149305746729), 'Sg': np.float64(0.15989825683385214), 'Al': np.float64(0.004410387482590572), 'Su': np.float64(1.7488886381011817), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.028662529536137408), 'Pcc': np.float64(0.00999357570923964), 'Ba': np.float64(2.2793893939215306), 'Bgr': np.float64(0.6543135624282727), 'Bu': np.float64(1.127287983630151), 'Sc': np.float64(0.21782764969786297), 'Sod': np.float64(0.015584745800760948), 'Pot': np.float64(1.965870676321532), 'Hemo': np.float64(0.07626454124809388), 'Pcv': np.float64(1.026647782976632), 'Wbcc': np.float64(1.5856672414177764), 'Rbcc': np.float64(1.664998209727079), 'Htn': np.float64(0.013286490519890693), 'Dm': np.float64(0.09039086699559346), 'Cad': np.float64(0.03956770091263418), 'Appet': np.float64(1.5175040712782384), 'Pe': np.float64(3.2807153494450456), 'Ane': np.float64(0.6897135348995858)}

Normalized Mathematical Scores
{'Age': np.float64(0.028355286940029645), 'Bp': np.float64(1.0), 'Sg': np.float64(0.03600380122932324), 'Al': np.float64(0.0009930734544059683), 'Su': np.float64(0.3937919033341587), 'Rbc': np.float64(0.0009192304325720531), 'Pc': np.float64(0.006453854073099695), 'Pcc': np.float64(0.0022502228637772256), 'Ba': np.float64(0.5132431352785328), 'Bgr': np.float64(0.14732978276177483), 'Bu': np.float64(0.2538279859610823), 'Sc': np.float64(0.049047585366247384), 'Sod': np.float64(0.0035091695252385913), 'Pot': np.float64(0.4426490849514444), 'Hemo': np.float64(0.017172253396076913), 'Pcv': np.float64(0.2311671399221317), 'Wbcc': np.float64(0.35703984087316437), 'Rbcc': np.float64(0.37490255226785907), 'Htn': np.float64(0.002991678415922277), 'Dm': np.float64(0.020353034940444378), 'Cad': np.float64(0.008909338143942748), 'Appet': np.float64(0.3416917484207587), 'Pe': np.float64(0.7387086367936082), 'Ane': np.float64(0.15530068624513813)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029386529386529386, 'Al': 0.02844163539403516, 'Su': 0.030090497737556562, 'Rbc': 0.02661064425770308, 'Pc': 0.02715098147128967, 'Pcc': 0.026279628993473032, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03009207275993712, 'Sod': 0.027425373134328357, 'Pot': 0.03055037313432836, 'Hemo': 0.028371628371628373, 'Pcv': 0.029437229437229435, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.029857397504456328, 'Htn': 0.02821869488536155, 'Dm': 0.028782894736842105, 'Cad': 0.027106227106227107, 'Appet': 0.028790389395194696, 'Pe': 0.031054405392392875, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Sc', 'Su', 'Ba', 'Rbcc', 'Pcv', 'Sg', 'Ane', 'Bgr', 'Wbcc', 'Appet', 'Dm', 'Al', 'Hemo', 'Htn', 'Age', 'Sod']

Run 09/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915e300>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}

Normalized Mathematical Scores
{'Age': np.float64(0.01700885460583122), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11962582292667374), 'Al': np.float64(0.1317714516716716), 'Su': np.float64(0.017346655335946235), 'Rbc': np.float64(0.0325831264341166), 'Pc': np.float64(0.09296227343134601), 'Pcc': np.float64(0.0006022693930915867), 'Ba': np.float64(0.397732432760025), 'Bgr': np.float64(0.2031117099983006), 'Bu': np.float64(0.0007043585683224972), 'Sc': np.float64(0.04007060286361657), 'Sod': np.float64(0.015657375528065818), 'Pot': np.float64(0.09336059194978027), 'Hemo': np.float64(0.10355724010939366), 'Pcv': np.float64(0.03458234690972696), 'Wbcc': np.float64(0.09358753476952279), 'Rbcc': np.float64(0.13167526791854192), 'Htn': np.float64(0.032265530527759996), 'Dm': np.float64(0.014155505807289609), 'Cad': np.float64(0.0011820818137741158), 'Appet': np.float64(0.020811536396759225), 'Pe': np.float64(0.017774859353385866), 'Ane': np.float64(0.1773317785529145)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03177805800756621, 'Su': 0.027526395173453996, 'Rbc': 0.02821939586645469, 'Pc': 0.028577260665441927, 'Pcc': 0.025989268947015427, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.028177225029148854, 'Sc': 0.03028233151183971, 'Sod': 0.027425373134328357, 'Pot': 0.029211087420042643, 'Hemo': 0.030090497737556562, 'Pcv': 0.028850145288501453, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029857397504456328, 'Htn': 0.029206349206349208, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027242401779095628, 'Pe': 0.027912386121341344, 'Ane': 0.030776515151515152}
Top 5 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889182d20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}

Normalized Mathematical Scores
{'Age': np.float64(0.01700885460583122), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11962582292667374), 'Al': np.float64(0.1317714516716716), 'Su': np.float64(0.017346655335946235), 'Rbc': np.float64(0.0325831264341166), 'Pc': np.float64(0.09296227343134601), 'Pcc': np.float64(0.0006022693930915867), 'Ba': np.float64(0.397732432760025), 'Bgr': np.float64(0.2031117099983006), 'Bu': np.float64(0.0007043585683224972), 'Sc': np.float64(0.04007060286361657), 'Sod': np.float64(0.015657375528065818), 'Pot': np.float64(0.09336059194978027), 'Hemo': np.float64(0.10355724010939366), 'Pcv': np.float64(0.03458234690972696), 'Wbcc': np.float64(0.09358753476952279), 'Rbcc': np.float64(0.13167526791854192), 'Htn': np.float64(0.032265530527759996), 'Dm': np.float64(0.014155505807289609), 'Cad': np.float64(0.0011820818137741158), 'Appet': np.float64(0.020811536396759225), 'Pe': np.float64(0.017774859353385866), 'Ane': np.float64(0.1773317785529145)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03177805800756621, 'Su': 0.027526395173453996, 'Rbc': 0.02821939586645469, 'Pc': 0.028577260665441927, 'Pcc': 0.025989268947015427, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.028177225029148854, 'Sc': 0.03028233151183971, 'Sod': 0.027425373134328357, 'Pot': 0.029211087420042643, 'Hemo': 0.030090497737556562, 'Pcv': 0.028850145288501453, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029857397504456328, 'Htn': 0.029206349206349208, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027242401779095628, 'Pe': 0.027912386121341344, 'Ane': 0.030776515151515152}
Top 10 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Sc', 'Ba', 'Hemo', 'Rbcc', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588918b890>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}

Normalized Mathematical Scores
{'Age': np.float64(0.01700885460583122), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11962582292667374), 'Al': np.float64(0.1317714516716716), 'Su': np.float64(0.017346655335946235), 'Rbc': np.float64(0.0325831264341166), 'Pc': np.float64(0.09296227343134601), 'Pcc': np.float64(0.0006022693930915867), 'Ba': np.float64(0.397732432760025), 'Bgr': np.float64(0.2031117099983006), 'Bu': np.float64(0.0007043585683224972), 'Sc': np.float64(0.04007060286361657), 'Sod': np.float64(0.015657375528065818), 'Pot': np.float64(0.09336059194978027), 'Hemo': np.float64(0.10355724010939366), 'Pcv': np.float64(0.03458234690972696), 'Wbcc': np.float64(0.09358753476952279), 'Rbcc': np.float64(0.13167526791854192), 'Htn': np.float64(0.032265530527759996), 'Dm': np.float64(0.014155505807289609), 'Cad': np.float64(0.0011820818137741158), 'Appet': np.float64(0.020811536396759225), 'Pe': np.float64(0.017774859353385866), 'Ane': np.float64(0.1773317785529145)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03177805800756621, 'Su': 0.027526395173453996, 'Rbc': 0.02821939586645469, 'Pc': 0.028577260665441927, 'Pcc': 0.025989268947015427, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.028177225029148854, 'Sc': 0.03028233151183971, 'Sod': 0.027425373134328357, 'Pot': 0.029211087420042643, 'Hemo': 0.030090497737556562, 'Pcv': 0.028850145288501453, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029857397504456328, 'Htn': 0.029206349206349208, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027242401779095628, 'Pe': 0.027912386121341344, 'Ane': 0.030776515151515152}
Top 15 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Sc', 'Ba', 'Hemo', 'Rbcc', 'Pot', 'Htn', 'Pcv', 'Pc', 'Wbcc', 'Rbc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891589b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.17221549237445696), 'Bp': np.float64(10.125049356081602), 'Sg': np.float64(1.2112173613944497), 'Al': np.float64(1.3341924518981965), 'Su': np.float64(0.17563574143939192), 'Rbc': np.float64(0.32990576332087773), 'Pc': np.float64(0.9412476067459318), 'Pcc': np.float64(0.006098007330709628), 'Ba': np.float64(4.02706051220966), 'Bgr': np.float64(2.056516088530927), 'Bu': np.float64(0.007131665268644259), 'Sc': np.float64(0.4057168317220626), 'Sod': np.float64(0.15853170000837064), 'Pot': np.float64(0.94528060140452), 'Hemo': np.float64(1.048522167287204), 'Pcv': np.float64(0.35014796931012154), 'Wbcc': np.float64(0.9475784086554213), 'Rbcc': np.float64(1.3332185866505053), 'Htn': np.float64(0.3266900890937276), 'Dm': np.float64(0.14332519495910703), 'Cad': np.float64(0.011968636707389383), 'Appet': np.float64(0.2107178331930758), 'Pe': np.float64(0.1799713282504406), 'Ane': np.float64(1.795493010249992)}

Normalized Mathematical Scores
{'Age': np.float64(0.01700885460583122), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11962582292667374), 'Al': np.float64(0.1317714516716716), 'Su': np.float64(0.017346655335946235), 'Rbc': np.float64(0.0325831264341166), 'Pc': np.float64(0.09296227343134601), 'Pcc': np.float64(0.0006022693930915867), 'Ba': np.float64(0.397732432760025), 'Bgr': np.float64(0.2031117099983006), 'Bu': np.float64(0.0007043585683224972), 'Sc': np.float64(0.04007060286361657), 'Sod': np.float64(0.015657375528065818), 'Pot': np.float64(0.09336059194978027), 'Hemo': np.float64(0.10355724010939366), 'Pcv': np.float64(0.03458234690972696), 'Wbcc': np.float64(0.09358753476952279), 'Rbcc': np.float64(0.13167526791854192), 'Htn': np.float64(0.032265530527759996), 'Dm': np.float64(0.014155505807289609), 'Cad': np.float64(0.0011820818137741158), 'Appet': np.float64(0.020811536396759225), 'Pe': np.float64(0.017774859353385866), 'Ane': np.float64(0.1773317785529145)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03177805800756621, 'Su': 0.027526395173453996, 'Rbc': 0.02821939586645469, 'Pc': 0.028577260665441927, 'Pcc': 0.025989268947015427, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.028177225029148854, 'Sc': 0.03028233151183971, 'Sod': 0.027425373134328357, 'Pot': 0.029211087420042643, 'Hemo': 0.030090497737556562, 'Pcv': 0.028850145288501453, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029857397504456328, 'Htn': 0.029206349206349208, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027242401779095628, 'Pe': 0.027912386121341344, 'Ane': 0.030776515151515152}
Top 20 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Sc', 'Ba', 'Hemo', 'Rbcc', 'Pot', 'Htn', 'Pcv', 'Pc', 'Wbcc', 'Rbc', 'Bu', 'Dm', 'Pe', 'Su', 'Sod']

Run 10/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910e5d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}

Normalized Mathematical Scores
{'Age': np.float64(0.00400171687682192), 'Bp': np.float64(1.0), 'Sg': np.float64(0.01272979765826885), 'Al': np.float64(0.01593339979139913), 'Su': np.float64(0.4471047885041199), 'Rbc': np.float64(0.0005681521628561056), 'Pc': np.float64(0.00417933300022048), 'Pcc': np.float64(0.03309053377540866), 'Ba': np.float64(0.020701973266799942), 'Bgr': np.float64(0.03293058619392363), 'Bu': np.float64(0.0167891780136498), 'Sc': np.float64(0.1561257038593798), 'Sod': np.float64(0.03588640504132662), 'Pot': np.float64(0.06619619638069409), 'Hemo': np.float64(0.01961772026264442), 'Pcv': np.float64(0.37868475959616416), 'Wbcc': np.float64(0.03999393607042088), 'Rbcc': np.float64(0.12962373592147997), 'Htn': np.float64(0.003516073974697868), 'Dm': np.float64(0.039166776233022844), 'Cad': np.float64(0.09991314842605231), 'Appet': np.float64(0.05753205635030025), 'Pe': np.float64(0.018829229767696604), 'Ane': np.float64(0.02941417197488081)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.029051670471052088, 'Su': 0.030834914611005692, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.02797339593114241, 'Ba': 0.027417840375586856, 'Bgr': 0.028850145288501453, 'Bu': 0.028949545078577336, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.029850746268656716, 'Hemo': 0.02854251012145749, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.030090497737556562, 'Htn': 0.02792120864410021, 'Dm': 0.029910714285714284, 'Cad': 0.029437229437229435, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.028665028665028666}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Rbcc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915d430>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}

Normalized Mathematical Scores
{'Age': np.float64(0.00400171687682192), 'Bp': np.float64(1.0), 'Sg': np.float64(0.01272979765826885), 'Al': np.float64(0.01593339979139913), 'Su': np.float64(0.4471047885041199), 'Rbc': np.float64(0.0005681521628561056), 'Pc': np.float64(0.00417933300022048), 'Pcc': np.float64(0.03309053377540866), 'Ba': np.float64(0.020701973266799942), 'Bgr': np.float64(0.03293058619392363), 'Bu': np.float64(0.0167891780136498), 'Sc': np.float64(0.1561257038593798), 'Sod': np.float64(0.03588640504132662), 'Pot': np.float64(0.06619619638069409), 'Hemo': np.float64(0.01961772026264442), 'Pcv': np.float64(0.37868475959616416), 'Wbcc': np.float64(0.03999393607042088), 'Rbcc': np.float64(0.12962373592147997), 'Htn': np.float64(0.003516073974697868), 'Dm': np.float64(0.039166776233022844), 'Cad': np.float64(0.09991314842605231), 'Appet': np.float64(0.05753205635030025), 'Pe': np.float64(0.018829229767696604), 'Ane': np.float64(0.02941417197488081)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.029051670471052088, 'Su': 0.030834914611005692, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.02797339593114241, 'Ba': 0.027417840375586856, 'Bgr': 0.028850145288501453, 'Bu': 0.028949545078577336, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.029850746268656716, 'Hemo': 0.02854251012145749, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.030090497737556562, 'Htn': 0.02792120864410021, 'Dm': 0.029910714285714284, 'Cad': 0.029437229437229435, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.028665028665028666}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Rbcc', 'Dm', 'Pot', 'Cad', 'Al', 'Sod']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915c6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}

Normalized Mathematical Scores
{'Age': np.float64(0.00400171687682192), 'Bp': np.float64(1.0), 'Sg': np.float64(0.01272979765826885), 'Al': np.float64(0.01593339979139913), 'Su': np.float64(0.4471047885041199), 'Rbc': np.float64(0.0005681521628561056), 'Pc': np.float64(0.00417933300022048), 'Pcc': np.float64(0.03309053377540866), 'Ba': np.float64(0.020701973266799942), 'Bgr': np.float64(0.03293058619392363), 'Bu': np.float64(0.0167891780136498), 'Sc': np.float64(0.1561257038593798), 'Sod': np.float64(0.03588640504132662), 'Pot': np.float64(0.06619619638069409), 'Hemo': np.float64(0.01961772026264442), 'Pcv': np.float64(0.37868475959616416), 'Wbcc': np.float64(0.03999393607042088), 'Rbcc': np.float64(0.12962373592147997), 'Htn': np.float64(0.003516073974697868), 'Dm': np.float64(0.039166776233022844), 'Cad': np.float64(0.09991314842605231), 'Appet': np.float64(0.05753205635030025), 'Pe': np.float64(0.018829229767696604), 'Ane': np.float64(0.02941417197488081)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.029051670471052088, 'Su': 0.030834914611005692, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.02797339593114241, 'Ba': 0.027417840375586856, 'Bgr': 0.028850145288501453, 'Bu': 0.028949545078577336, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.029850746268656716, 'Hemo': 0.02854251012145749, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.030090497737556562, 'Htn': 0.02792120864410021, 'Dm': 0.029910714285714284, 'Cad': 0.029437229437229435, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.028665028665028666}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Rbcc', 'Dm', 'Pot', 'Cad', 'Al', 'Sod', 'Bu', 'Bgr', 'Appet', 'Ane', 'Wbcc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.048562467315793154), 'Bp': np.float64(12.135408078734558), 'Sg': np.float64(0.15448128934281208), 'Al': np.float64(0.19335830855025254), 'Su': np.float64(5.425799062453803), 'Rbc': np.float64(0.006894758347074496), 'Pc': np.float64(0.05071791145459756), 'Pcc': np.float64(0.401567130907733), 'Ba': np.float64(0.25122689362767087), 'Bgr': np.float64(0.3996261017352056), 'Bu': np.float64(0.20374352650215838), 'Sc': np.float64(1.894649127913237), 'Sod': np.float64(0.4354961696552556), 'Pot': np.float64(0.8033178563397744), 'Hemo': np.float64(0.2380690409616497), 'Pcv': np.float64(4.595494090896945), 'Wbcc': np.float64(0.48534273488937896), 'Rbcc': np.float64(1.5730369320972828), 'Htn': np.float64(0.04266899251797684), 'Dm': np.float64(0.4753048127162141), 'Cad': np.float64(1.2124868285813202), 'Appet': np.float64(0.6981749814196455), 'Pe': np.float64(0.2285003870392546), 'Ane': np.float64(0.3569529802132562)}

Normalized Mathematical Scores
{'Age': np.float64(0.00400171687682192), 'Bp': np.float64(1.0), 'Sg': np.float64(0.01272979765826885), 'Al': np.float64(0.01593339979139913), 'Su': np.float64(0.4471047885041199), 'Rbc': np.float64(0.0005681521628561056), 'Pc': np.float64(0.00417933300022048), 'Pcc': np.float64(0.03309053377540866), 'Ba': np.float64(0.020701973266799942), 'Bgr': np.float64(0.03293058619392363), 'Bu': np.float64(0.0167891780136498), 'Sc': np.float64(0.1561257038593798), 'Sod': np.float64(0.03588640504132662), 'Pot': np.float64(0.06619619638069409), 'Hemo': np.float64(0.01961772026264442), 'Pcv': np.float64(0.37868475959616416), 'Wbcc': np.float64(0.03999393607042088), 'Rbcc': np.float64(0.12962373592147997), 'Htn': np.float64(0.003516073974697868), 'Dm': np.float64(0.039166776233022844), 'Cad': np.float64(0.09991314842605231), 'Appet': np.float64(0.05753205635030025), 'Pe': np.float64(0.018829229767696604), 'Ane': np.float64(0.02941417197488081)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02690100430416069, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.029051670471052088, 'Su': 0.030834914611005692, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.02797339593114241, 'Ba': 0.027417840375586856, 'Bgr': 0.028850145288501453, 'Bu': 0.028949545078577336, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.029850746268656716, 'Hemo': 0.02854251012145749, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.030090497737556562, 'Htn': 0.02792120864410021, 'Dm': 0.029910714285714284, 'Cad': 0.029437229437229435, 'Appet': 0.028790389395194696, 'Pe': 0.027912386121341344, 'Ane': 0.028665028665028666}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Rbcc', 'Dm', 'Pot', 'Cad', 'Al', 'Sod', 'Bu', 'Bgr', 'Appet', 'Ane', 'Wbcc', 'Hemo', 'Sg', 'Pcc', 'Htn', 'Pe']

Run 11/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889149490>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}

Normalized Mathematical Scores
{'Age': np.float64(0.02641528236761076), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07332555867149476), 'Al': np.float64(0.00014563659241426395), 'Su': np.float64(0.35841825953030326), 'Rbc': np.float64(0.01303161927692563), 'Pc': np.float64(0.00816317527369936), 'Pcc': np.float64(0.004836679229209561), 'Ba': np.float64(0.1988943107184062), 'Bgr': np.float64(0.07620867395968574), 'Bu': np.float64(0.08776313132042335), 'Sc': np.float64(0.04651911571627551), 'Sod': np.float64(0.00835492116263911), 'Pot': np.float64(0.11884160054364705), 'Hemo': np.float64(0.0009781375686372066), 'Pcv': np.float64(0.0945764299286661), 'Wbcc': np.float64(0.048739259312639456), 'Rbcc': np.float64(0.1687151167152443), 'Htn': np.float64(0.00017687689032780694), 'Dm': np.float64(0.007952452585442728), 'Cad': np.float64(0.0003646218963678487), 'Appet': np.float64(0.04643474796621179), 'Pe': np.float64(0.09085682310854819), 'Ane': np.float64(0.07127700153862608)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.028298204527712725, 'Su': 0.030834914611005692, 'Rbc': 0.02786377708978328, 'Pc': 0.027313266443701224, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.030834914611005692, 'Sc': 0.03009207275993712, 'Sod': 0.027912386121341344, 'Pot': 0.030309988518943745, 'Hemo': 0.027730294396961064, 'Pcv': 0.030303030303030304, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.028283227848101264, 'Cad': 0.0264808362369338, 'Appet': 0.027598020555767037, 'Pe': 0.029850746268656716, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a3f3710>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}

Normalized Mathematical Scores
{'Age': np.float64(0.02641528236761076), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07332555867149476), 'Al': np.float64(0.00014563659241426395), 'Su': np.float64(0.35841825953030326), 'Rbc': np.float64(0.01303161927692563), 'Pc': np.float64(0.00816317527369936), 'Pcc': np.float64(0.004836679229209561), 'Ba': np.float64(0.1988943107184062), 'Bgr': np.float64(0.07620867395968574), 'Bu': np.float64(0.08776313132042335), 'Sc': np.float64(0.04651911571627551), 'Sod': np.float64(0.00835492116263911), 'Pot': np.float64(0.11884160054364705), 'Hemo': np.float64(0.0009781375686372066), 'Pcv': np.float64(0.0945764299286661), 'Wbcc': np.float64(0.048739259312639456), 'Rbcc': np.float64(0.1687151167152443), 'Htn': np.float64(0.00017687689032780694), 'Dm': np.float64(0.007952452585442728), 'Cad': np.float64(0.0003646218963678487), 'Appet': np.float64(0.04643474796621179), 'Pe': np.float64(0.09085682310854819), 'Ane': np.float64(0.07127700153862608)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.028298204527712725, 'Su': 0.030834914611005692, 'Rbc': 0.02786377708978328, 'Pc': 0.027313266443701224, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.030834914611005692, 'Sc': 0.03009207275993712, 'Sod': 0.027912386121341344, 'Pot': 0.030309988518943745, 'Hemo': 0.027730294396961064, 'Pcv': 0.030303030303030304, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.028283227848101264, 'Cad': 0.0264808362369338, 'Appet': 0.027598020555767037, 'Pe': 0.029850746268656716, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pot', 'Pcv', 'Sg', 'Sc', 'Ba', 'Pe']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}

Normalized Mathematical Scores
{'Age': np.float64(0.02641528236761076), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07332555867149476), 'Al': np.float64(0.00014563659241426395), 'Su': np.float64(0.35841825953030326), 'Rbc': np.float64(0.01303161927692563), 'Pc': np.float64(0.00816317527369936), 'Pcc': np.float64(0.004836679229209561), 'Ba': np.float64(0.1988943107184062), 'Bgr': np.float64(0.07620867395968574), 'Bu': np.float64(0.08776313132042335), 'Sc': np.float64(0.04651911571627551), 'Sod': np.float64(0.00835492116263911), 'Pot': np.float64(0.11884160054364705), 'Hemo': np.float64(0.0009781375686372066), 'Pcv': np.float64(0.0945764299286661), 'Wbcc': np.float64(0.048739259312639456), 'Rbcc': np.float64(0.1687151167152443), 'Htn': np.float64(0.00017687689032780694), 'Dm': np.float64(0.007952452585442728), 'Cad': np.float64(0.0003646218963678487), 'Appet': np.float64(0.04643474796621179), 'Pe': np.float64(0.09085682310854819), 'Ane': np.float64(0.07127700153862608)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.028298204527712725, 'Su': 0.030834914611005692, 'Rbc': 0.02786377708978328, 'Pc': 0.027313266443701224, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.030834914611005692, 'Sc': 0.03009207275993712, 'Sod': 0.027912386121341344, 'Pot': 0.030309988518943745, 'Hemo': 0.027730294396961064, 'Pcv': 0.030303030303030304, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.028283227848101264, 'Cad': 0.0264808362369338, 'Appet': 0.027598020555767037, 'Pe': 0.029850746268656716, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pot', 'Pcv', 'Sg', 'Sc', 'Ba', 'Pe', 'Bgr', 'Ane', 'Al', 'Dm', 'Age']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891488f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.3075613887959582), 'Bp': np.float64(11.643312553534397), 'Sg': np.float64(0.8537523977747379), 'Al': np.float64(0.0016956923647109719), 'Su': np.float64(4.173175820605129), 'Rbc': np.float64(0.15173121631990902), 'Pc': np.float64(0.09504640114096535), 'Pcc': np.float64(0.056314967986874756), 'Ba': np.float64(2.3157886248141897), 'Bgr': np.float64(0.8873214102030188), 'Bu': np.float64(1.021853568640573), 'Sc': np.float64(0.5416366039986299), 'Sod': np.float64(0.09727895845674615), 'Pot': np.float64(1.3837098994919659), 'Hemo': np.float64(0.011388761431997201), 'Pcv': np.float64(1.1011829338569044), 'Wbcc': np.float64(0.5674864298048232), 'Rbcc': np.float64(1.9644028364216248), 'Htn': np.float64(0.002059432917583881), 'Dm': np.float64(0.09259289101947239), 'Cad': np.float64(0.0042454067032732905), 'Appet': np.float64(0.5406542839151995), 'Pe': np.float64(1.0578743890740132), 'Ane': np.float64(0.8299004067929756)}

Normalized Mathematical Scores
{'Age': np.float64(0.02641528236761076), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07332555867149476), 'Al': np.float64(0.00014563659241426395), 'Su': np.float64(0.35841825953030326), 'Rbc': np.float64(0.01303161927692563), 'Pc': np.float64(0.00816317527369936), 'Pcc': np.float64(0.004836679229209561), 'Ba': np.float64(0.1988943107184062), 'Bgr': np.float64(0.07620867395968574), 'Bu': np.float64(0.08776313132042335), 'Sc': np.float64(0.04651911571627551), 'Sod': np.float64(0.00835492116263911), 'Pot': np.float64(0.11884160054364705), 'Hemo': np.float64(0.0009781375686372066), 'Pcv': np.float64(0.0945764299286661), 'Wbcc': np.float64(0.048739259312639456), 'Rbcc': np.float64(0.1687151167152443), 'Htn': np.float64(0.00017687689032780694), 'Dm': np.float64(0.007952452585442728), 'Cad': np.float64(0.0003646218963678487), 'Appet': np.float64(0.04643474796621179), 'Pe': np.float64(0.09085682310854819), 'Ane': np.float64(0.07127700153862608)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.028298204527712725, 'Su': 0.030834914611005692, 'Rbc': 0.02786377708978328, 'Pc': 0.027313266443701224, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.030834914611005692, 'Sc': 0.03009207275993712, 'Sod': 0.027912386121341344, 'Pot': 0.030309988518943745, 'Hemo': 0.027730294396961064, 'Pcv': 0.030303030303030304, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.028283227848101264, 'Cad': 0.0264808362369338, 'Appet': 0.027598020555767037, 'Pe': 0.029850746268656716, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pot', 'Pcv', 'Sg', 'Sc', 'Ba', 'Pe', 'Bgr', 'Ane', 'Al', 'Dm', 'Age', 'Wbcc', 'Htn', 'Sod', 'Rbc', 'Hemo']

Run 12/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588090fbf0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}

Normalized Mathematical Scores
{'Age': np.float64(0.014268993002322048), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11825169744863152), 'Al': np.float64(0.05983946728545228), 'Su': np.float64(0.3213444229187044), 'Rbc': np.float64(0.016798917548505113), 'Pc': np.float64(0.025917382411232433), 'Pcc': np.float64(0.006085939163971109), 'Ba': np.float64(0.4181831760594772), 'Bgr': np.float64(0.0399144283782826), 'Bu': np.float64(0.17815537086770636), 'Sc': np.float64(0.06476862158556092), 'Sod': np.float64(0.14605526899587026), 'Pot': np.float64(0.08562105295529772), 'Hemo': np.float64(0.038545083780859274), 'Pcv': np.float64(0.20161656702607345), 'Wbcc': np.float64(0.004125326197760506), 'Rbcc': np.float64(0.48890224198749144), 'Htn': np.float64(0.002016341079319537), 'Dm': np.float64(0.0035159592039087084), 'Cad': np.float64(2.4419436837895383e-05), 'Appet': np.float64(0.02870472841878442), 'Pe': np.float64(0.08058983312068302), 'Ane': np.float64(0.21118678840146127)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.027526395173453996, 'Pc': 0.027479766610201392, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.028665028665028666, 'Bu': 0.031054405392392875, 'Sc': 0.03028233151183971, 'Sod': 0.029631255487269532, 'Pot': 0.029211087420042643, 'Hemo': 0.02871794871794872, 'Pcv': 0.030303030303030304, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.030834914611005692, 'Htn': 0.02792120864410021, 'Dm': 0.027820121951219513, 'Cad': 0.026190476190476188, 'Appet': 0.027242401779095628, 'Pe': 0.02900988017658188, 'Ane': 0.030536130536130537}
Top 5 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Ane', 'Sg']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a3c8860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}

Normalized Mathematical Scores
{'Age': np.float64(0.014268993002322048), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11825169744863152), 'Al': np.float64(0.05983946728545228), 'Su': np.float64(0.3213444229187044), 'Rbc': np.float64(0.016798917548505113), 'Pc': np.float64(0.025917382411232433), 'Pcc': np.float64(0.006085939163971109), 'Ba': np.float64(0.4181831760594772), 'Bgr': np.float64(0.0399144283782826), 'Bu': np.float64(0.17815537086770636), 'Sc': np.float64(0.06476862158556092), 'Sod': np.float64(0.14605526899587026), 'Pot': np.float64(0.08562105295529772), 'Hemo': np.float64(0.038545083780859274), 'Pcv': np.float64(0.20161656702607345), 'Wbcc': np.float64(0.004125326197760506), 'Rbcc': np.float64(0.48890224198749144), 'Htn': np.float64(0.002016341079319537), 'Dm': np.float64(0.0035159592039087084), 'Cad': np.float64(2.4419436837895383e-05), 'Appet': np.float64(0.02870472841878442), 'Pe': np.float64(0.08058983312068302), 'Ane': np.float64(0.21118678840146127)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.027526395173453996, 'Pc': 0.027479766610201392, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.028665028665028666, 'Bu': 0.031054405392392875, 'Sc': 0.03028233151183971, 'Sod': 0.029631255487269532, 'Pot': 0.029211087420042643, 'Hemo': 0.02871794871794872, 'Pcv': 0.030303030303030304, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.030834914611005692, 'Htn': 0.02792120864410021, 'Dm': 0.027820121951219513, 'Cad': 0.026190476190476188, 'Appet': 0.027242401779095628, 'Pe': 0.02900988017658188, 'Ane': 0.030536130536130537}
Top 10 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Ane', 'Sg', 'Su', 'Pcv', 'Sc', 'Al', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891489b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}

Normalized Mathematical Scores
{'Age': np.float64(0.014268993002322048), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11825169744863152), 'Al': np.float64(0.05983946728545228), 'Su': np.float64(0.3213444229187044), 'Rbc': np.float64(0.016798917548505113), 'Pc': np.float64(0.025917382411232433), 'Pcc': np.float64(0.006085939163971109), 'Ba': np.float64(0.4181831760594772), 'Bgr': np.float64(0.0399144283782826), 'Bu': np.float64(0.17815537086770636), 'Sc': np.float64(0.06476862158556092), 'Sod': np.float64(0.14605526899587026), 'Pot': np.float64(0.08562105295529772), 'Hemo': np.float64(0.038545083780859274), 'Pcv': np.float64(0.20161656702607345), 'Wbcc': np.float64(0.004125326197760506), 'Rbcc': np.float64(0.48890224198749144), 'Htn': np.float64(0.002016341079319537), 'Dm': np.float64(0.0035159592039087084), 'Cad': np.float64(2.4419436837895383e-05), 'Appet': np.float64(0.02870472841878442), 'Pe': np.float64(0.08058983312068302), 'Ane': np.float64(0.21118678840146127)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.027526395173453996, 'Pc': 0.027479766610201392, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.028665028665028666, 'Bu': 0.031054405392392875, 'Sc': 0.03028233151183971, 'Sod': 0.029631255487269532, 'Pot': 0.029211087420042643, 'Hemo': 0.02871794871794872, 'Pcv': 0.030303030303030304, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.030834914611005692, 'Htn': 0.02792120864410021, 'Dm': 0.027820121951219513, 'Cad': 0.026190476190476188, 'Appet': 0.027242401779095628, 'Pe': 0.02900988017658188, 'Ane': 0.030536130536130537}
Top 15 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Ane', 'Sg', 'Su', 'Pcv', 'Sc', 'Al', 'Ba', 'Sod', 'Pot', 'Pe', 'Hemo', 'Bgr']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889b39730>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09276978166044465), 'Bp': np.float64(6.5014946496468164), 'Sg': np.float64(0.7688127782739319), 'Al': np.float64(0.3890459763940837), 'Su': np.float64(2.0892190462998004), 'Rbc': np.float64(0.109218072561464), 'Pc': np.float64(0.16850172307947817), 'Pcc': np.float64(0.03956770091263418), 'Ba': np.float64(2.7188156817230036), 'Bgr': np.float64(0.25950344254511537), 'Bu': np.float64(1.1582761905022372), 'Sc': np.float64(0.42109284670352365), 'Sod': np.float64(0.949577549929377), 'Pot': np.float64(0.5566648176859949), 'Hemo': np.float64(0.2506006559714449), 'Pcv': np.float64(1.3108090318001753), 'Wbcc': np.float64(0.026820786202787775), 'Rbcc': np.float64(3.1785953104820086), 'Htn': np.float64(0.013109230739059057), 'Dm': np.float64(0.02285898995258895), 'Cad': np.float64(0.00015876283794896522), 'Appet': np.float64(0.18662363823429182), 'Pe': np.float64(0.5239543688500504), 'Ane': np.float64(1.3730297748681948)}

Normalized Mathematical Scores
{'Age': np.float64(0.014268993002322048), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11825169744863152), 'Al': np.float64(0.05983946728545228), 'Su': np.float64(0.3213444229187044), 'Rbc': np.float64(0.016798917548505113), 'Pc': np.float64(0.025917382411232433), 'Pcc': np.float64(0.006085939163971109), 'Ba': np.float64(0.4181831760594772), 'Bgr': np.float64(0.0399144283782826), 'Bu': np.float64(0.17815537086770636), 'Sc': np.float64(0.06476862158556092), 'Sod': np.float64(0.14605526899587026), 'Pot': np.float64(0.08562105295529772), 'Hemo': np.float64(0.038545083780859274), 'Pcv': np.float64(0.20161656702607345), 'Wbcc': np.float64(0.004125326197760506), 'Rbcc': np.float64(0.48890224198749144), 'Htn': np.float64(0.002016341079319537), 'Dm': np.float64(0.0035159592039087084), 'Cad': np.float64(2.4419436837895383e-05), 'Appet': np.float64(0.02870472841878442), 'Pe': np.float64(0.08058983312068302), 'Ane': np.float64(0.21118678840146127)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.027526395173453996, 'Pc': 0.027479766610201392, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.028665028665028666, 'Bu': 0.031054405392392875, 'Sc': 0.03028233151183971, 'Sod': 0.029631255487269532, 'Pot': 0.029211087420042643, 'Hemo': 0.02871794871794872, 'Pcv': 0.030303030303030304, 'Wbcc': 0.0264301860545992, 'Rbcc': 0.030834914611005692, 'Htn': 0.02792120864410021, 'Dm': 0.027820121951219513, 'Cad': 0.026190476190476188, 'Appet': 0.027242401779095628, 'Pe': 0.02900988017658188, 'Ane': 0.030536130536130537}
Top 20 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Ane', 'Sg', 'Su', 'Pcv', 'Sc', 'Al', 'Ba', 'Sod', 'Pot', 'Pe', 'Hemo', 'Bgr', 'Htn', 'Dm', 'Rbc', 'Pc', 'Age']

Run 13/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588915e900>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}

Normalized Mathematical Scores
{'Age': np.float64(0.0003243962808640171), 'Bp': np.float64(1.0), 'Sg': np.float64(0.12105187328104614), 'Al': np.float64(0.0009710720682651271), 'Su': np.float64(0.08992835187507874), 'Rbc': np.float64(0.0023342248701164027), 'Pc': np.float64(0.000940660819910386), 'Pcc': np.float64(0.0010184976874157126), 'Ba': np.float64(0.36610770754246913), 'Bgr': np.float64(0.11264949989576467), 'Bu': np.float64(0.012152762635954875), 'Sc': np.float64(0.10591198731288823), 'Sod': np.float64(0.04420536523277991), 'Pot': np.float64(0.13957863956354097), 'Hemo': np.float64(0.030102076565446213), 'Pcv': np.float64(0.557164387712832), 'Wbcc': np.float64(0.03310901837220085), 'Rbcc': np.float64(0.2580252080653625), 'Htn': np.float64(0.08634612837177894), 'Dm': np.float64(0.023235053527669823), 'Cad': np.float64(0.0005395305265653296), 'Appet': np.float64(0.11704828838106583), 'Pe': np.float64(0.12504783841784317), 'Ane': np.float64(0.0192750814516232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.028790389395194696, 'Rbc': 0.027364110201042444, 'Pc': 0.026687875574407917, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.028949545078577336, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.028782894736842105, 'Cad': 0.026333907056798625, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.02813852813852814}
Top 5 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a3c8860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}

Normalized Mathematical Scores
{'Age': np.float64(0.0003243962808640171), 'Bp': np.float64(1.0), 'Sg': np.float64(0.12105187328104614), 'Al': np.float64(0.0009710720682651271), 'Su': np.float64(0.08992835187507874), 'Rbc': np.float64(0.0023342248701164027), 'Pc': np.float64(0.000940660819910386), 'Pcc': np.float64(0.0010184976874157126), 'Ba': np.float64(0.36610770754246913), 'Bgr': np.float64(0.11264949989576467), 'Bu': np.float64(0.012152762635954875), 'Sc': np.float64(0.10591198731288823), 'Sod': np.float64(0.04420536523277991), 'Pot': np.float64(0.13957863956354097), 'Hemo': np.float64(0.030102076565446213), 'Pcv': np.float64(0.557164387712832), 'Wbcc': np.float64(0.03310901837220085), 'Rbcc': np.float64(0.2580252080653625), 'Htn': np.float64(0.08634612837177894), 'Dm': np.float64(0.023235053527669823), 'Cad': np.float64(0.0005395305265653296), 'Appet': np.float64(0.11704828838106583), 'Pe': np.float64(0.12504783841784317), 'Ane': np.float64(0.0192750814516232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.028790389395194696, 'Rbc': 0.027364110201042444, 'Pc': 0.026687875574407917, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.028949545078577336, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.028782894736842105, 'Cad': 0.026333907056798625, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.02813852813852814}
Top 10 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Pot', 'Pe', 'Ba', 'Htn', 'Bgr']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588914a8d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}

Normalized Mathematical Scores
{'Age': np.float64(0.0003243962808640171), 'Bp': np.float64(1.0), 'Sg': np.float64(0.12105187328104614), 'Al': np.float64(0.0009710720682651271), 'Su': np.float64(0.08992835187507874), 'Rbc': np.float64(0.0023342248701164027), 'Pc': np.float64(0.000940660819910386), 'Pcc': np.float64(0.0010184976874157126), 'Ba': np.float64(0.36610770754246913), 'Bgr': np.float64(0.11264949989576467), 'Bu': np.float64(0.012152762635954875), 'Sc': np.float64(0.10591198731288823), 'Sod': np.float64(0.04420536523277991), 'Pot': np.float64(0.13957863956354097), 'Hemo': np.float64(0.030102076565446213), 'Pcv': np.float64(0.557164387712832), 'Wbcc': np.float64(0.03310901837220085), 'Rbcc': np.float64(0.2580252080653625), 'Htn': np.float64(0.08634612837177894), 'Dm': np.float64(0.023235053527669823), 'Cad': np.float64(0.0005395305265653296), 'Appet': np.float64(0.11704828838106583), 'Pe': np.float64(0.12504783841784317), 'Ane': np.float64(0.0192750814516232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.028790389395194696, 'Rbc': 0.027364110201042444, 'Pc': 0.026687875574407917, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.028949545078577336, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.028782894736842105, 'Cad': 0.026333907056798625, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.02813852813852814}
Top 15 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Pot', 'Pe', 'Ba', 'Htn', 'Bgr', 'Bu', 'Su', 'Appet', 'Dm', 'Al']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889183b90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.002738749415977661), 'Bp': np.float64(8.442604239121072), 'Sg': np.float64(1.021993058516107), 'Al': np.float64(0.008198377160027229), 'Su': np.float64(0.7592294847577111), 'Rbc': np.float64(0.019706936783506577), 'Pc': np.float64(0.007941627025750528), 'Pcc': np.float64(0.008598772893310904), 'Ba': np.float64(3.0909024836729477), 'Bgr': np.float64(0.9510551453548516), 'Bu': np.float64(0.10260096534734481), 'Sc': np.float64(0.8941729930615274), 'Sod': np.float64(0.37320840390616294), 'Pot': np.float64(1.1784072140699031), 'Hemo': np.float64(0.2541399192177833), 'Pcv': np.float64(4.703918421591653), 'Wbcc': np.float64(0.2795263388622804), 'Rbcc': np.float64(2.1784047154127264), 'Htn': np.float64(0.7289861894232732), 'Dm': np.float64(0.19616436140891028), 'Cad': np.float64(0.004555042710715676), 'Appet': np.float64(0.9881923756678521), 'Pe': np.float64(1.0557294107194097), 'Ane': np.float64(0.16273188437287797)}

Normalized Mathematical Scores
{'Age': np.float64(0.0003243962808640171), 'Bp': np.float64(1.0), 'Sg': np.float64(0.12105187328104614), 'Al': np.float64(0.0009710720682651271), 'Su': np.float64(0.08992835187507874), 'Rbc': np.float64(0.0023342248701164027), 'Pc': np.float64(0.000940660819910386), 'Pcc': np.float64(0.0010184976874157126), 'Ba': np.float64(0.36610770754246913), 'Bgr': np.float64(0.11264949989576467), 'Bu': np.float64(0.012152762635954875), 'Sc': np.float64(0.10591198731288823), 'Sod': np.float64(0.04420536523277991), 'Pot': np.float64(0.13957863956354097), 'Hemo': np.float64(0.030102076565446213), 'Pcv': np.float64(0.557164387712832), 'Wbcc': np.float64(0.03310901837220085), 'Rbcc': np.float64(0.2580252080653625), 'Htn': np.float64(0.08634612837177894), 'Dm': np.float64(0.023235053527669823), 'Cad': np.float64(0.0005395305265653296), 'Appet': np.float64(0.11704828838106583), 'Pe': np.float64(0.12504783841784317), 'Ane': np.float64(0.0192750814516232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.028790389395194696, 'Rbc': 0.027364110201042444, 'Pc': 0.026687875574407917, 'Pcc': 0.02658450704225352, 'Ba': 0.029957522915269395, 'Bgr': 0.02964426877470356, 'Bu': 0.028949545078577336, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.028782894736842105, 'Cad': 0.026333907056798625, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.02813852813852814}
Top 20 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Pot', 'Pe', 'Ba', 'Htn', 'Bgr', 'Bu', 'Su', 'Appet', 'Dm', 'Al', 'Hemo', 'Sod', 'Ane', 'Wbcc', 'Rbc']

Run 14/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c2540>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}

Normalized Mathematical Scores
{'Age': np.float64(0.00012195985572731495), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14776136390586664), 'Al': np.float64(0.003245024631754642), 'Su': np.float64(0.28189132824781243), 'Rbc': np.float64(0.00130595272182372), 'Pc': np.float64(0.019552584110135687), 'Pcc': np.float64(0.04061294281182691), 'Ba': np.float64(0.2050430634027082), 'Bgr': np.float64(0.04990788814668324), 'Bu': np.float64(0.22354486916993865), 'Sc': np.float64(0.057929369086845345), 'Sod': np.float64(0.12011989035863835), 'Pot': np.float64(0.18833426203749787), 'Hemo': np.float64(0.10507112616774789), 'Pcv': np.float64(0.08266835878677195), 'Wbcc': np.float64(0.015307749291666463), 'Rbcc': np.float64(0.0589383861575755), 'Htn': np.float64(0.013781923475138994), 'Dm': np.float64(0.003202168270336347), 'Cad': np.float64(0.010317452703437247), 'Appet': np.float64(0.23748954728864943), 'Pe': np.float64(0.12330087608842617), 'Ane': np.float64(0.06961193841223014)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.030834914611005692, 'Rbc': 0.026754075124025514, 'Pc': 0.027479766610201392, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.031754032258064516, 'Sc': 0.029906956136464335, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.028404512489927477, 'Htn': 0.028531243721117136, 'Dm': 0.027820121951219513, 'Cad': 0.026785714285714288, 'Appet': 0.029957522915269395, 'Pe': 0.029631255487269532, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891839e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}

Normalized Mathematical Scores
{'Age': np.float64(0.00012195985572731495), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14776136390586664), 'Al': np.float64(0.003245024631754642), 'Su': np.float64(0.28189132824781243), 'Rbc': np.float64(0.00130595272182372), 'Pc': np.float64(0.019552584110135687), 'Pcc': np.float64(0.04061294281182691), 'Ba': np.float64(0.2050430634027082), 'Bgr': np.float64(0.04990788814668324), 'Bu': np.float64(0.22354486916993865), 'Sc': np.float64(0.057929369086845345), 'Sod': np.float64(0.12011989035863835), 'Pot': np.float64(0.18833426203749787), 'Hemo': np.float64(0.10507112616774789), 'Pcv': np.float64(0.08266835878677195), 'Wbcc': np.float64(0.015307749291666463), 'Rbcc': np.float64(0.0589383861575755), 'Htn': np.float64(0.013781923475138994), 'Dm': np.float64(0.003202168270336347), 'Cad': np.float64(0.010317452703437247), 'Appet': np.float64(0.23748954728864943), 'Pe': np.float64(0.12330087608842617), 'Ane': np.float64(0.06961193841223014)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.030834914611005692, 'Rbc': 0.026754075124025514, 'Pc': 0.027479766610201392, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.031754032258064516, 'Sc': 0.029906956136464335, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.028404512489927477, 'Htn': 0.028531243721117136, 'Dm': 0.027820121951219513, 'Cad': 0.026785714285714288, 'Appet': 0.029957522915269395, 'Pe': 0.029631255487269532, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Pot', 'Appet', 'Sc', 'Hemo', 'Pe', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880956f60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}

Normalized Mathematical Scores
{'Age': np.float64(0.00012195985572731495), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14776136390586664), 'Al': np.float64(0.003245024631754642), 'Su': np.float64(0.28189132824781243), 'Rbc': np.float64(0.00130595272182372), 'Pc': np.float64(0.019552584110135687), 'Pcc': np.float64(0.04061294281182691), 'Ba': np.float64(0.2050430634027082), 'Bgr': np.float64(0.04990788814668324), 'Bu': np.float64(0.22354486916993865), 'Sc': np.float64(0.057929369086845345), 'Sod': np.float64(0.12011989035863835), 'Pot': np.float64(0.18833426203749787), 'Hemo': np.float64(0.10507112616774789), 'Pcv': np.float64(0.08266835878677195), 'Wbcc': np.float64(0.015307749291666463), 'Rbcc': np.float64(0.0589383861575755), 'Htn': np.float64(0.013781923475138994), 'Dm': np.float64(0.003202168270336347), 'Cad': np.float64(0.010317452703437247), 'Appet': np.float64(0.23748954728864943), 'Pe': np.float64(0.12330087608842617), 'Ane': np.float64(0.06961193841223014)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.030834914611005692, 'Rbc': 0.026754075124025514, 'Pc': 0.027479766610201392, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.031754032258064516, 'Sc': 0.029906956136464335, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.028404512489927477, 'Htn': 0.028531243721117136, 'Dm': 0.027820121951219513, 'Cad': 0.026785714285714288, 'Appet': 0.029957522915269395, 'Pe': 0.029631255487269532, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Pot', 'Appet', 'Sc', 'Hemo', 'Pe', 'Ba', 'Sod', 'Pcv', 'Ane', 'Al', 'Htn']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809552e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0007035441113608535), 'Bp': np.float64(5.768653194653485), 'Sg': np.float64(0.8523840639419337), 'Al': np.float64(0.018719421708700664), 'Su': np.float64(1.6261333112418572), 'Rbc': np.float64(0.007533588340814816), 'Pc': np.float64(0.1127920767906652), 'Pcc': np.float64(0.23428198229572458), 'Ba': np.float64(1.1828223227395698), 'Bgr': np.float64(0.28790129839577305), 'Bu': np.float64(1.289552823685562), 'Sc': np.float64(0.33417444004709124), 'Sod': np.float64(0.6929299892587855), 'Pot': np.float64(1.0864350423653186), 'Hemo': np.float64(0.6061188876334183), 'Pcv': np.float64(0.4768850920120725), 'Wbcc': np.float64(0.08830509685432636), 'Rbcc': np.float64(0.3399951095956186), 'Htn': np.float64(0.07950313688333041), 'Dm': np.float64(0.018472198222493793), 'Cad': np.float64(0.05951780649836951), 'Appet': np.float64(1.3699948356634775), 'Pe': np.float64(0.7112799927510731), 'Ane': np.float64(0.401567130907733)}

Normalized Mathematical Scores
{'Age': np.float64(0.00012195985572731495), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14776136390586664), 'Al': np.float64(0.003245024631754642), 'Su': np.float64(0.28189132824781243), 'Rbc': np.float64(0.00130595272182372), 'Pc': np.float64(0.019552584110135687), 'Pcc': np.float64(0.04061294281182691), 'Ba': np.float64(0.2050430634027082), 'Bgr': np.float64(0.04990788814668324), 'Bu': np.float64(0.22354486916993865), 'Sc': np.float64(0.057929369086845345), 'Sod': np.float64(0.12011989035863835), 'Pot': np.float64(0.18833426203749787), 'Hemo': np.float64(0.10507112616774789), 'Pcv': np.float64(0.08266835878677195), 'Wbcc': np.float64(0.015307749291666463), 'Rbcc': np.float64(0.0589383861575755), 'Htn': np.float64(0.013781923475138994), 'Dm': np.float64(0.003202168270336347), 'Cad': np.float64(0.010317452703437247), 'Appet': np.float64(0.23748954728864943), 'Pe': np.float64(0.12330087608842617), 'Ane': np.float64(0.06961193841223014)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02661064425770308, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.0287391216352965, 'Su': 0.030834914611005692, 'Rbc': 0.026754075124025514, 'Pc': 0.027479766610201392, 'Pcc': 0.027242401779095628, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.031754032258064516, 'Sc': 0.029906956136464335, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.02690501986276634, 'Rbcc': 0.028404512489927477, 'Htn': 0.028531243721117136, 'Dm': 0.027820121951219513, 'Cad': 0.026785714285714288, 'Appet': 0.029957522915269395, 'Pe': 0.029631255487269532, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Pot', 'Appet', 'Sc', 'Hemo', 'Pe', 'Ba', 'Sod', 'Pcv', 'Ane', 'Al', 'Htn', 'Bgr', 'Rbcc', 'Dm', 'Pc', 'Pcc']

Run 15/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588975e4e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}

Normalized Mathematical Scores
{'Age': np.float64(4.5146541352612095e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.035562154161397116), 'Al': np.float64(0.09199476907441152), 'Su': np.float64(0.12945134487695104), 'Rbc': np.float64(2.1008382259077592e-07), 'Pc': np.float64(0.014280127555997613), 'Pcc': np.float64(0.0666008795603799), 'Ba': np.float64(0.22099798420702346), 'Bgr': np.float64(0.12051713411561493), 'Bu': np.float64(0.10974952229659349), 'Sc': np.float64(0.18946538626500167), 'Sod': np.float64(0.062466543537021114), 'Pot': np.float64(0.28764876231561975), 'Hemo': np.float64(0.04533000596369121), 'Pcv': np.float64(0.4862862798182546), 'Wbcc': np.float64(0.02677850174449167), 'Rbcc': np.float64(0.23682104070859322), 'Htn': np.float64(0.131277899486243), 'Dm': np.float64(0.02093296021824642), 'Cad': np.float64(0.013310615794876513), 'Appet': np.float64(0.12376723864728395), 'Pe': np.float64(0.07475011884356726), 'Ane': np.float64(0.13705133634751862)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.026754075124025514, 'Bp': 0.032018442622950824, 'Sg': 0.028693528693528692, 'Al': 0.03009207275993712, 'Su': 0.02919863597612958, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.027417840375586856, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.031544957774465976, 'Sod': 0.028083267871170464, 'Pot': 0.030798389007344232, 'Hemo': 0.028371628371628373, 'Pcv': 0.03128054740957967, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.03057889822595705, 'Dm': 0.028125, 'Cad': 0.0264808362369338, 'Appet': 0.028370221327967807, 'Pe': 0.028438886647841874, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pot', 'Htn']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889138a10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}

Normalized Mathematical Scores
{'Age': np.float64(4.5146541352612095e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.035562154161397116), 'Al': np.float64(0.09199476907441152), 'Su': np.float64(0.12945134487695104), 'Rbc': np.float64(2.1008382259077592e-07), 'Pc': np.float64(0.014280127555997613), 'Pcc': np.float64(0.0666008795603799), 'Ba': np.float64(0.22099798420702346), 'Bgr': np.float64(0.12051713411561493), 'Bu': np.float64(0.10974952229659349), 'Sc': np.float64(0.18946538626500167), 'Sod': np.float64(0.062466543537021114), 'Pot': np.float64(0.28764876231561975), 'Hemo': np.float64(0.04533000596369121), 'Pcv': np.float64(0.4862862798182546), 'Wbcc': np.float64(0.02677850174449167), 'Rbcc': np.float64(0.23682104070859322), 'Htn': np.float64(0.131277899486243), 'Dm': np.float64(0.02093296021824642), 'Cad': np.float64(0.013310615794876513), 'Appet': np.float64(0.12376723864728395), 'Pe': np.float64(0.07475011884356726), 'Ane': np.float64(0.13705133634751862)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.026754075124025514, 'Bp': 0.032018442622950824, 'Sg': 0.028693528693528692, 'Al': 0.03009207275993712, 'Su': 0.02919863597612958, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.027417840375586856, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.031544957774465976, 'Sod': 0.028083267871170464, 'Pot': 0.030798389007344232, 'Hemo': 0.028371628371628373, 'Pcv': 0.03128054740957967, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.03057889822595705, 'Dm': 0.028125, 'Cad': 0.0264808362369338, 'Appet': 0.028370221327967807, 'Pe': 0.028438886647841874, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pot', 'Htn', 'Rbcc', 'Al', 'Ane', 'Bu', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910d790>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}

Normalized Mathematical Scores
{'Age': np.float64(4.5146541352612095e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.035562154161397116), 'Al': np.float64(0.09199476907441152), 'Su': np.float64(0.12945134487695104), 'Rbc': np.float64(2.1008382259077592e-07), 'Pc': np.float64(0.014280127555997613), 'Pcc': np.float64(0.0666008795603799), 'Ba': np.float64(0.22099798420702346), 'Bgr': np.float64(0.12051713411561493), 'Bu': np.float64(0.10974952229659349), 'Sc': np.float64(0.18946538626500167), 'Sod': np.float64(0.062466543537021114), 'Pot': np.float64(0.28764876231561975), 'Hemo': np.float64(0.04533000596369121), 'Pcv': np.float64(0.4862862798182546), 'Wbcc': np.float64(0.02677850174449167), 'Rbcc': np.float64(0.23682104070859322), 'Htn': np.float64(0.131277899486243), 'Dm': np.float64(0.02093296021824642), 'Cad': np.float64(0.013310615794876513), 'Appet': np.float64(0.12376723864728395), 'Pe': np.float64(0.07475011884356726), 'Ane': np.float64(0.13705133634751862)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.026754075124025514, 'Bp': 0.032018442622950824, 'Sg': 0.028693528693528692, 'Al': 0.03009207275993712, 'Su': 0.02919863597612958, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.027417840375586856, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.031544957774465976, 'Sod': 0.028083267871170464, 'Pot': 0.030798389007344232, 'Hemo': 0.028371628371628373, 'Pcv': 0.03128054740957967, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.03057889822595705, 'Dm': 0.028125, 'Cad': 0.0264808362369338, 'Appet': 0.028370221327967807, 'Pe': 0.028438886647841874, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pot', 'Htn', 'Rbcc', 'Al', 'Ane', 'Bu', 'Ba', 'Bgr', 'Su', 'Sg', 'Pe', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957c50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.00034062952271209334), 'Bp': np.float64(7.544974930673956), 'Sg': np.float64(0.2683155616285038), 'Al': np.float64(0.6940982264195747), 'Su': np.float64(0.976707151838624), 'Rbc': np.float64(1.5850771747875592e-06), 'Pc': np.float64(0.10774320441682834), 'Pcc': np.float64(0.5025019666439018), 'Ba': np.float64(1.667424250571471), 'Bgr': np.float64(0.9092987556189857), 'Bu': np.float64(0.8280573943812403), 'Sc': np.float64(1.4295115895998953), 'Sod': np.float64(0.47130850499267757), 'Pot': np.float64(2.1703027005107427), 'Hemo': np.float64(0.3420137586033511), 'Pcv': np.float64(3.669017790359432), 'Wbcc': np.float64(0.20204312434319846), 'Rbcc': np.float64(1.7868088152024524), 'Htn': np.float64(0.9904884605752389), 'Dm': np.float64(0.15793866007146448), 'Cad': np.float64(0.10042826248417609), 'Appet': np.float64(0.9338207128324982), 'Pe': np.float64(0.5639877727396139), 'Ane': np.float64(1.0340488969573924)}

Normalized Mathematical Scores
{'Age': np.float64(4.5146541352612095e-05), 'Bp': np.float64(1.0), 'Sg': np.float64(0.035562154161397116), 'Al': np.float64(0.09199476907441152), 'Su': np.float64(0.12945134487695104), 'Rbc': np.float64(2.1008382259077592e-07), 'Pc': np.float64(0.014280127555997613), 'Pcc': np.float64(0.0666008795603799), 'Ba': np.float64(0.22099798420702346), 'Bgr': np.float64(0.12051713411561493), 'Bu': np.float64(0.10974952229659349), 'Sc': np.float64(0.18946538626500167), 'Sod': np.float64(0.062466543537021114), 'Pot': np.float64(0.28764876231561975), 'Hemo': np.float64(0.04533000596369121), 'Pcv': np.float64(0.4862862798182546), 'Wbcc': np.float64(0.02677850174449167), 'Rbcc': np.float64(0.23682104070859322), 'Htn': np.float64(0.131277899486243), 'Dm': np.float64(0.02093296021824642), 'Cad': np.float64(0.013310615794876513), 'Appet': np.float64(0.12376723864728395), 'Pe': np.float64(0.07475011884356726), 'Ane': np.float64(0.13705133634751862)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.026754075124025514, 'Bp': 0.032018442622950824, 'Sg': 0.028693528693528692, 'Al': 0.03009207275993712, 'Su': 0.02919863597612958, 'Rbc': 0.02661064425770308, 'Pc': 0.026838432635534086, 'Pcc': 0.027417840375586856, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.031544957774465976, 'Sod': 0.028083267871170464, 'Pot': 0.030798389007344232, 'Hemo': 0.028371628371628373, 'Pcv': 0.03128054740957967, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.03057889822595705, 'Dm': 0.028125, 'Cad': 0.0264808362369338, 'Appet': 0.028370221327967807, 'Pe': 0.028438886647841874, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pot', 'Htn', 'Rbcc', 'Al', 'Ane', 'Bu', 'Ba', 'Bgr', 'Su', 'Sg', 'Pe', 'Hemo', 'Appet', 'Dm', 'Sod', 'Pcc', 'Pc']

Run 16/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889183f50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}

Normalized Mathematical Scores
{'Age': np.float64(0.06800832735964128), 'Bp': np.float64(1.0), 'Sg': np.float64(0.020473168221765505), 'Al': np.float64(2.7619528144968722e-05), 'Su': np.float64(0.24597291588683146), 'Rbc': np.float64(0.010700651077332432), 'Pc': np.float64(0.013415131721882918), 'Pcc': np.float64(0.10744688998589251), 'Ba': np.float64(0.0778879082322501), 'Bgr': np.float64(0.09800857895817855), 'Bu': np.float64(0.055923574081630956), 'Sc': np.float64(0.03466533423465597), 'Sod': np.float64(0.04817553339290633), 'Pot': np.float64(0.4136455009292113), 'Hemo': np.float64(0.00010433865757942859), 'Pcv': np.float64(0.2959471994467177), 'Wbcc': np.float64(0.026151722310026167), 'Rbcc': np.float64(0.06938914968204092), 'Htn': np.float64(0.015660362886617818), 'Dm': np.float64(0.0019874395756752424), 'Cad': np.float64(0.0018783335403268488), 'Appet': np.float64(0.05197933875015881), 'Pe': np.float64(0.0743289244354503), 'Ane': np.float64(0.09225926587738932)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.02886002886002886, 'Al': 0.028298204527712725, 'Su': 0.030330882352941176, 'Rbc': 0.027205882352941177, 'Pc': 0.02715098147128967, 'Pcc': 0.02946912242686891, 'Ba': 0.028790389395194696, 'Bgr': 0.030303030303030304, 'Bu': 0.030017921146953404, 'Sc': 0.029726775956284153, 'Sod': 0.028438886647841874, 'Pot': 0.031054405392392875, 'Hemo': 0.027432808155699723, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.028991596638655463, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027783137179239824, 'Pe': 0.029418126757516764, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58897bac60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}

Normalized Mathematical Scores
{'Age': np.float64(0.06800832735964128), 'Bp': np.float64(1.0), 'Sg': np.float64(0.020473168221765505), 'Al': np.float64(2.7619528144968722e-05), 'Su': np.float64(0.24597291588683146), 'Rbc': np.float64(0.010700651077332432), 'Pc': np.float64(0.013415131721882918), 'Pcc': np.float64(0.10744688998589251), 'Ba': np.float64(0.0778879082322501), 'Bgr': np.float64(0.09800857895817855), 'Bu': np.float64(0.055923574081630956), 'Sc': np.float64(0.03466533423465597), 'Sod': np.float64(0.04817553339290633), 'Pot': np.float64(0.4136455009292113), 'Hemo': np.float64(0.00010433865757942859), 'Pcv': np.float64(0.2959471994467177), 'Wbcc': np.float64(0.026151722310026167), 'Rbcc': np.float64(0.06938914968204092), 'Htn': np.float64(0.015660362886617818), 'Dm': np.float64(0.0019874395756752424), 'Cad': np.float64(0.0018783335403268488), 'Appet': np.float64(0.05197933875015881), 'Pe': np.float64(0.0743289244354503), 'Ane': np.float64(0.09225926587738932)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.02886002886002886, 'Al': 0.028298204527712725, 'Su': 0.030330882352941176, 'Rbc': 0.027205882352941177, 'Pc': 0.02715098147128967, 'Pcc': 0.02946912242686891, 'Ba': 0.028790389395194696, 'Bgr': 0.030303030303030304, 'Bu': 0.030017921146953404, 'Sc': 0.029726775956284153, 'Sod': 0.028438886647841874, 'Pot': 0.031054405392392875, 'Hemo': 0.027432808155699723, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.028991596638655463, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027783137179239824, 'Pe': 0.029418126757516764, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Ane', 'Bu', 'Sc', 'Pcc', 'Pe']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910eab0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}

Normalized Mathematical Scores
{'Age': np.float64(0.06800832735964128), 'Bp': np.float64(1.0), 'Sg': np.float64(0.020473168221765505), 'Al': np.float64(2.7619528144968722e-05), 'Su': np.float64(0.24597291588683146), 'Rbc': np.float64(0.010700651077332432), 'Pc': np.float64(0.013415131721882918), 'Pcc': np.float64(0.10744688998589251), 'Ba': np.float64(0.0778879082322501), 'Bgr': np.float64(0.09800857895817855), 'Bu': np.float64(0.055923574081630956), 'Sc': np.float64(0.03466533423465597), 'Sod': np.float64(0.04817553339290633), 'Pot': np.float64(0.4136455009292113), 'Hemo': np.float64(0.00010433865757942859), 'Pcv': np.float64(0.2959471994467177), 'Wbcc': np.float64(0.026151722310026167), 'Rbcc': np.float64(0.06938914968204092), 'Htn': np.float64(0.015660362886617818), 'Dm': np.float64(0.0019874395756752424), 'Cad': np.float64(0.0018783335403268488), 'Appet': np.float64(0.05197933875015881), 'Pe': np.float64(0.0743289244354503), 'Ane': np.float64(0.09225926587738932)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.02886002886002886, 'Al': 0.028298204527712725, 'Su': 0.030330882352941176, 'Rbc': 0.027205882352941177, 'Pc': 0.02715098147128967, 'Pcc': 0.02946912242686891, 'Ba': 0.028790389395194696, 'Bgr': 0.030303030303030304, 'Bu': 0.030017921146953404, 'Sc': 0.029726775956284153, 'Sod': 0.028438886647841874, 'Pot': 0.031054405392392875, 'Hemo': 0.027432808155699723, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.028991596638655463, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027783137179239824, 'Pe': 0.029418126757516764, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Ane', 'Bu', 'Sc', 'Pcc', 'Pe', 'Rbcc', 'Sg', 'Age', 'Ba', 'Htn']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c0fe0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.6918441191183246), 'Bp': np.float64(10.172932433108054), 'Sg': np.float64(0.20827215701167545), 'Al': np.float64(0.000280971593653093), 'Su': np.float64(2.502265853691307), 'Rbc': np.float64(0.10885700039996773), 'Pc': np.float64(0.13647122858795943), 'Pcc': np.float64(1.0930499519740788), 'Ba': np.float64(0.7923484278028008), 'Bgr': np.float64(0.9970346516064861), 'Bu': np.float64(0.5689067405503445), 'Sc': np.float64(0.3526481029402626), 'Sod': np.float64(0.4900864461349769), 'Pot': np.float64(4.207987732212001), 'Hemo': np.float64(0.0010614301137167245), 'Pcv': np.float64(3.0106508637390124), 'Wbcc': np.float64(0.26603970406930066), 'Rbcc': np.float64(0.7058911313062235), 'Htn': np.float64(0.15931181352351606), 'Dm': np.float64(0.02021808851822918), 'Cad': np.float64(0.019108160192585676), 'Appet': np.float64(0.5287823010230008), 'Pe': np.float64(0.7561431261074302), 'Ane': np.float64(0.938547278098833)}

Normalized Mathematical Scores
{'Age': np.float64(0.06800832735964128), 'Bp': np.float64(1.0), 'Sg': np.float64(0.020473168221765505), 'Al': np.float64(2.7619528144968722e-05), 'Su': np.float64(0.24597291588683146), 'Rbc': np.float64(0.010700651077332432), 'Pc': np.float64(0.013415131721882918), 'Pcc': np.float64(0.10744688998589251), 'Ba': np.float64(0.0778879082322501), 'Bgr': np.float64(0.09800857895817855), 'Bu': np.float64(0.055923574081630956), 'Sc': np.float64(0.03466533423465597), 'Sod': np.float64(0.04817553339290633), 'Pot': np.float64(0.4136455009292113), 'Hemo': np.float64(0.00010433865757942859), 'Pcv': np.float64(0.2959471994467177), 'Wbcc': np.float64(0.026151722310026167), 'Rbcc': np.float64(0.06938914968204092), 'Htn': np.float64(0.015660362886617818), 'Dm': np.float64(0.0019874395756752424), 'Cad': np.float64(0.0018783335403268488), 'Appet': np.float64(0.05197933875015881), 'Pe': np.float64(0.0743289244354503), 'Ane': np.float64(0.09225926587738932)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.02886002886002886, 'Al': 0.028298204527712725, 'Su': 0.030330882352941176, 'Rbc': 0.027205882352941177, 'Pc': 0.02715098147128967, 'Pcc': 0.02946912242686891, 'Ba': 0.028790389395194696, 'Bgr': 0.030303030303030304, 'Bu': 0.030017921146953404, 'Sc': 0.029726775956284153, 'Sod': 0.028438886647841874, 'Pot': 0.031054405392392875, 'Hemo': 0.027432808155699723, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.028991596638655463, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Appet': 0.027783137179239824, 'Pe': 0.029418126757516764, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Ane', 'Bu', 'Sc', 'Pcc', 'Pe', 'Rbcc', 'Sg', 'Age', 'Ba', 'Htn', 'Sod', 'Al', 'Dm', 'Appet', 'Hemo']

Run 17/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889183140>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017880517480327045), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0003507257088335112), 'Al': np.float64(0.0009548071772728532), 'Su': np.float64(0.2280609942190386), 'Rbc': np.float64(0.04414086628901015), 'Pc': np.float64(0.02243670756002454), 'Pcc': np.float64(0.050261134641327955), 'Ba': np.float64(0.2688255808478955), 'Bgr': np.float64(0.026947856994664024), 'Bu': np.float64(0.08029163622884501), 'Sc': np.float64(0.04427238787754912), 'Sod': np.float64(0.022814674465090785), 'Pot': np.float64(0.03782070712780431), 'Hemo': np.float64(9.334099670242801e-05), 'Pcv': np.float64(0.0028385339132425236), 'Wbcc': np.float64(0.002168496199124069), 'Rbcc': np.float64(0.1618591930531523), 'Htn': np.float64(0.00012953009763529591), 'Dm': np.float64(0.058998183666456636), 'Cad': np.float64(0.007144210610538344), 'Appet': np.float64(0.02453238872625242), 'Pe': np.float64(0.07553808584835751), 'Ane': np.float64(0.061968299059099945)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027205882352941177, 'Bp': 0.032018442622950824, 'Sg': 0.028068137824235385, 'Al': 0.0287391216352965, 'Su': 0.03057889822595705, 'Rbc': 0.028790389395194696, 'Pc': 0.027650648360030512, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.028850145288501453, 'Bu': 0.0315136476426799, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.028814262023217248, 'Hemo': 0.02728937728937729, 'Pcv': 0.027972027972027972, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.030330882352941176, 'Cad': 0.027272727272727275, 'Appet': 0.027598020555767037, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Rbcc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910ca70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017880517480327045), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0003507257088335112), 'Al': np.float64(0.0009548071772728532), 'Su': np.float64(0.2280609942190386), 'Rbc': np.float64(0.04414086628901015), 'Pc': np.float64(0.02243670756002454), 'Pcc': np.float64(0.050261134641327955), 'Ba': np.float64(0.2688255808478955), 'Bgr': np.float64(0.026947856994664024), 'Bu': np.float64(0.08029163622884501), 'Sc': np.float64(0.04427238787754912), 'Sod': np.float64(0.022814674465090785), 'Pot': np.float64(0.03782070712780431), 'Hemo': np.float64(9.334099670242801e-05), 'Pcv': np.float64(0.0028385339132425236), 'Wbcc': np.float64(0.002168496199124069), 'Rbcc': np.float64(0.1618591930531523), 'Htn': np.float64(0.00012953009763529591), 'Dm': np.float64(0.058998183666456636), 'Cad': np.float64(0.007144210610538344), 'Appet': np.float64(0.02453238872625242), 'Pe': np.float64(0.07553808584835751), 'Ane': np.float64(0.061968299059099945)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027205882352941177, 'Bp': 0.032018442622950824, 'Sg': 0.028068137824235385, 'Al': 0.0287391216352965, 'Su': 0.03057889822595705, 'Rbc': 0.028790389395194696, 'Pc': 0.027650648360030512, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.028850145288501453, 'Bu': 0.0315136476426799, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.028814262023217248, 'Hemo': 0.02728937728937729, 'Pcv': 0.027972027972027972, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.030330882352941176, 'Cad': 0.027272727272727275, 'Appet': 0.027598020555767037, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Ane', 'Bgr']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c2a80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017880517480327045), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0003507257088335112), 'Al': np.float64(0.0009548071772728532), 'Su': np.float64(0.2280609942190386), 'Rbc': np.float64(0.04414086628901015), 'Pc': np.float64(0.02243670756002454), 'Pcc': np.float64(0.050261134641327955), 'Ba': np.float64(0.2688255808478955), 'Bgr': np.float64(0.026947856994664024), 'Bu': np.float64(0.08029163622884501), 'Sc': np.float64(0.04427238787754912), 'Sod': np.float64(0.022814674465090785), 'Pot': np.float64(0.03782070712780431), 'Hemo': np.float64(9.334099670242801e-05), 'Pcv': np.float64(0.0028385339132425236), 'Wbcc': np.float64(0.002168496199124069), 'Rbcc': np.float64(0.1618591930531523), 'Htn': np.float64(0.00012953009763529591), 'Dm': np.float64(0.058998183666456636), 'Cad': np.float64(0.007144210610538344), 'Appet': np.float64(0.02453238872625242), 'Pe': np.float64(0.07553808584835751), 'Ane': np.float64(0.061968299059099945)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027205882352941177, 'Bp': 0.032018442622950824, 'Sg': 0.028068137824235385, 'Al': 0.0287391216352965, 'Su': 0.03057889822595705, 'Rbc': 0.028790389395194696, 'Pc': 0.027650648360030512, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.028850145288501453, 'Bu': 0.0315136476426799, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.028814262023217248, 'Hemo': 0.02728937728937729, 'Pcv': 0.027972027972027972, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.030330882352941176, 'Cad': 0.027272727272727275, 'Appet': 0.027598020555767037, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Ane', 'Bgr', 'Pot', 'Rbc', 'Al', 'Pcc', 'Sod']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588935f890>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.02373325215109323), 'Bp': np.float64(13.273246804632825), 'Sg': np.float64(0.004655268894076985), 'Al': np.float64(0.012673391314777386), 'Su': np.float64(3.0271098627792394), 'Rbc': np.float64(0.5858926124243288), 'Pc': np.float64(0.2978079569275769), 'Pcc': np.float64(0.6671284447752265), 'Ba': np.float64(3.568188281992892), 'Bgr': np.float64(0.35768555674612657), 'Bu': np.float64(1.0657307040132582), 'Sc': np.float64(0.5876383309291439), 'Sod': np.float64(0.30282480494250436), 'Pot': np.float64(0.5020035800330824), 'Hemo': np.float64(0.0012389380862217456), 'Pcv': np.float64(0.03767656119378823), 'Wbcc': np.float64(0.028782985245881975), 'Rbcc': np.float64(2.148397016993201), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.783097452829936), 'Cad': np.float64(0.09482687065795199), 'Appet': np.float64(0.3256244502707403), 'Pe': np.float64(1.0026356566147914), 'Ane': np.float64(0.8225205274747296)}

Normalized Mathematical Scores
{'Age': np.float64(0.0017880517480327045), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0003507257088335112), 'Al': np.float64(0.0009548071772728532), 'Su': np.float64(0.2280609942190386), 'Rbc': np.float64(0.04414086628901015), 'Pc': np.float64(0.02243670756002454), 'Pcc': np.float64(0.050261134641327955), 'Ba': np.float64(0.2688255808478955), 'Bgr': np.float64(0.026947856994664024), 'Bu': np.float64(0.08029163622884501), 'Sc': np.float64(0.04427238787754912), 'Sod': np.float64(0.022814674465090785), 'Pot': np.float64(0.03782070712780431), 'Hemo': np.float64(9.334099670242801e-05), 'Pcv': np.float64(0.0028385339132425236), 'Wbcc': np.float64(0.002168496199124069), 'Rbcc': np.float64(0.1618591930531523), 'Htn': np.float64(0.00012953009763529591), 'Dm': np.float64(0.058998183666456636), 'Cad': np.float64(0.007144210610538344), 'Appet': np.float64(0.02453238872625242), 'Pe': np.float64(0.07553808584835751), 'Ane': np.float64(0.061968299059099945)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027205882352941177, 'Bp': 0.032018442622950824, 'Sg': 0.028068137824235385, 'Al': 0.0287391216352965, 'Su': 0.03057889822595705, 'Rbc': 0.028790389395194696, 'Pc': 0.027650648360030512, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.028850145288501453, 'Bu': 0.0315136476426799, 'Sc': 0.030679156908665108, 'Sod': 0.028258706467661692, 'Pot': 0.028814262023217248, 'Hemo': 0.02728937728937729, 'Pcv': 0.027972027972027972, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030330882352941176, 'Htn': 0.02792120864410021, 'Dm': 0.030330882352941176, 'Cad': 0.027272727272727275, 'Appet': 0.027598020555767037, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Su', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Ane', 'Bgr', 'Pot', 'Rbc', 'Al', 'Pcc', 'Sod', 'Sg', 'Pcv', 'Htn', 'Pc', 'Appet']

Run 18/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588090f350>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}

Normalized Mathematical Scores
{'Age': np.float64(0.046766669722656654), 'Bp': np.float64(1.0), 'Sg': np.float64(0.2192112802969526), 'Al': np.float64(0.16719394713280256), 'Su': np.float64(0.04094236526066395), 'Rbc': np.float64(0.009040684114414627), 'Pc': np.float64(0.08951329920784225), 'Pcc': np.float64(0.017328043627652223), 'Ba': np.float64(0.18268969092908957), 'Bgr': np.float64(0.19821140525200642), 'Bu': np.float64(0.27337651255489376), 'Sc': np.float64(0.2262503665214277), 'Sod': np.float64(0.1575404133492382), 'Pot': np.float64(0.1763500409442759), 'Hemo': np.float64(0.007435139692809446), 'Pcv': np.float64(0.5735553731070908), 'Wbcc': np.float64(0.013425102445853676), 'Rbcc': np.float64(0.23032893538273483), 'Htn': np.float64(0.00029974025611697176), 'Dm': np.float64(0.0027684956040125784), 'Cad': np.float64(0.04134080324575638), 'Appet': np.float64(0.32225082550779355), 'Pe': np.float64(0.09416772175495222), 'Ane': np.float64(0.037823082626049484)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03047794966520434, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028006267136701922, 'Pcc': 0.026742734890354787, 'Ba': 0.028577260665441927, 'Bgr': 0.029857397504456328, 'Bu': 0.031754032258064516, 'Sc': 0.031544957774465976, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02658450704225352, 'Rbcc': 0.030090497737556562, 'Htn': 0.027777777777777776, 'Dm': 0.027673192771084338, 'Cad': 0.027443609022556388, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.027972027972027972}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Pcv', 'Sg']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957710>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}

Normalized Mathematical Scores
{'Age': np.float64(0.046766669722656654), 'Bp': np.float64(1.0), 'Sg': np.float64(0.2192112802969526), 'Al': np.float64(0.16719394713280256), 'Su': np.float64(0.04094236526066395), 'Rbc': np.float64(0.009040684114414627), 'Pc': np.float64(0.08951329920784225), 'Pcc': np.float64(0.017328043627652223), 'Ba': np.float64(0.18268969092908957), 'Bgr': np.float64(0.19821140525200642), 'Bu': np.float64(0.27337651255489376), 'Sc': np.float64(0.2262503665214277), 'Sod': np.float64(0.1575404133492382), 'Pot': np.float64(0.1763500409442759), 'Hemo': np.float64(0.007435139692809446), 'Pcv': np.float64(0.5735553731070908), 'Wbcc': np.float64(0.013425102445853676), 'Rbcc': np.float64(0.23032893538273483), 'Htn': np.float64(0.00029974025611697176), 'Dm': np.float64(0.0027684956040125784), 'Cad': np.float64(0.04134080324575638), 'Appet': np.float64(0.32225082550779355), 'Pe': np.float64(0.09416772175495222), 'Ane': np.float64(0.037823082626049484)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03047794966520434, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028006267136701922, 'Pcc': 0.026742734890354787, 'Ba': 0.028577260665441927, 'Bgr': 0.029857397504456328, 'Bu': 0.031754032258064516, 'Sc': 0.031544957774465976, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02658450704225352, 'Rbcc': 0.030090497737556562, 'Htn': 0.027777777777777776, 'Dm': 0.027673192771084338, 'Cad': 0.027443609022556388, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.027972027972027972}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Pcv', 'Sg', 'Al', 'Rbcc', 'Appet', 'Bgr', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889739fd0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}

Normalized Mathematical Scores
{'Age': np.float64(0.046766669722656654), 'Bp': np.float64(1.0), 'Sg': np.float64(0.2192112802969526), 'Al': np.float64(0.16719394713280256), 'Su': np.float64(0.04094236526066395), 'Rbc': np.float64(0.009040684114414627), 'Pc': np.float64(0.08951329920784225), 'Pcc': np.float64(0.017328043627652223), 'Ba': np.float64(0.18268969092908957), 'Bgr': np.float64(0.19821140525200642), 'Bu': np.float64(0.27337651255489376), 'Sc': np.float64(0.2262503665214277), 'Sod': np.float64(0.1575404133492382), 'Pot': np.float64(0.1763500409442759), 'Hemo': np.float64(0.007435139692809446), 'Pcv': np.float64(0.5735553731070908), 'Wbcc': np.float64(0.013425102445853676), 'Rbcc': np.float64(0.23032893538273483), 'Htn': np.float64(0.00029974025611697176), 'Dm': np.float64(0.0027684956040125784), 'Cad': np.float64(0.04134080324575638), 'Appet': np.float64(0.32225082550779355), 'Pe': np.float64(0.09416772175495222), 'Ane': np.float64(0.037823082626049484)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03047794966520434, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028006267136701922, 'Pcc': 0.026742734890354787, 'Ba': 0.028577260665441927, 'Bgr': 0.029857397504456328, 'Bu': 0.031754032258064516, 'Sc': 0.031544957774465976, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02658450704225352, 'Rbcc': 0.030090497737556562, 'Htn': 0.027777777777777776, 'Dm': 0.027673192771084338, 'Cad': 0.027443609022556388, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.027972027972027972}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Pcv', 'Sg', 'Al', 'Rbcc', 'Appet', 'Bgr', 'Pot', 'Sod', 'Pe', 'Ba', 'Age', 'Pc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58892ad0d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.26824969281669), 'Bp': np.float64(5.735916078855051), 'Sg': np.float64(1.257377507321692), 'Al': np.float64(0.9590104496462836), 'Su': np.float64(0.23484197120499883), 'Rbc': np.float64(0.0518566053757203), 'Pc': np.float64(0.5134407721976254), 'Pcc': np.float64(0.0993922040589522), 'Ba': np.float64(1.0478927356412246), 'Bgr': np.float64(1.136923986397438), 'Bu': np.float64(1.5680647339449347), 'Sc': np.float64(1.2977531151771056), 'Sod': np.float64(0.9036385899993663), 'Pot': np.float64(1.0115290353590187), 'Hemo': np.float64(0.04264733731251911), 'Pcv': np.float64(3.28986548671867), 'Wbcc': np.float64(0.07700526097944838), 'Rbcc': np.float64(1.3211474438873947), 'Htn': np.float64(0.0017192849545414693), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.23712737805011713), 'Appet': np.float64(1.8484036914544664), 'Pe': np.float64(0.540138149323379), 'Ane': np.float64(0.21695002778662034)}

Normalized Mathematical Scores
{'Age': np.float64(0.046766669722656654), 'Bp': np.float64(1.0), 'Sg': np.float64(0.2192112802969526), 'Al': np.float64(0.16719394713280256), 'Su': np.float64(0.04094236526066395), 'Rbc': np.float64(0.009040684114414627), 'Pc': np.float64(0.08951329920784225), 'Pcc': np.float64(0.017328043627652223), 'Ba': np.float64(0.18268969092908957), 'Bgr': np.float64(0.19821140525200642), 'Bu': np.float64(0.27337651255489376), 'Sc': np.float64(0.2262503665214277), 'Sod': np.float64(0.1575404133492382), 'Pot': np.float64(0.1763500409442759), 'Hemo': np.float64(0.007435139692809446), 'Pcv': np.float64(0.5735553731070908), 'Wbcc': np.float64(0.013425102445853676), 'Rbcc': np.float64(0.23032893538273483), 'Htn': np.float64(0.00029974025611697176), 'Dm': np.float64(0.0027684956040125784), 'Cad': np.float64(0.04134080324575638), 'Appet': np.float64(0.32225082550779355), 'Pe': np.float64(0.09416772175495222), 'Ane': np.float64(0.037823082626049484)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.03047794966520434, 'Su': 0.027692895339954164, 'Rbc': 0.027051561365286855, 'Pc': 0.028006267136701922, 'Pcc': 0.026742734890354787, 'Ba': 0.028577260665441927, 'Bgr': 0.029857397504456328, 'Bu': 0.031754032258064516, 'Sc': 0.031544957774465976, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.027579737335834898, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02658450704225352, 'Rbcc': 0.030090497737556562, 'Htn': 0.027777777777777776, 'Dm': 0.027673192771084338, 'Cad': 0.027443609022556388, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.027972027972027972}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Pcv', 'Sg', 'Al', 'Rbcc', 'Appet', 'Bgr', 'Pot', 'Sod', 'Pe', 'Ba', 'Age', 'Pc', 'Ane', 'Htn', 'Su', 'Dm', 'Hemo']

Run 19/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889181040>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}

Normalized Mathematical Scores
{'Age': np.float64(0.0700174812923458), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1231200188485292), 'Al': np.float64(0.10492327845632342), 'Su': np.float64(0.6641831823193854), 'Rbc': np.float64(0.004676746817355338), 'Pc': np.float64(0.02968255960342383), 'Pcc': np.float64(0.0032073734737171167), 'Ba': np.float64(0.5771163889695731), 'Bgr': np.float64(6.69315399965433e-05), 'Bu': np.float64(0.12521129542304751), 'Sc': np.float64(0.017051225367970078), 'Sod': np.float64(0.010172508012927725), 'Pot': np.float64(0.05266843243691984), 'Hemo': np.float64(0.0782221045560305), 'Pcv': np.float64(0.41792482817295046), 'Wbcc': np.float64(0.02807713217858267), 'Rbcc': np.float64(0.5920774030861058), 'Htn': np.float64(0.0009334386783996458), 'Dm': np.float64(0.015740874235699077), 'Cad': np.float64(0.009975924526594113), 'Appet': np.float64(0.1894787611818618), 'Pe': np.float64(0.3365788210082244), 'Ane': np.float64(0.29095152581276273)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.029709507042253523, 'Bgr': 0.027056277056277056, 'Bu': 0.030621785881252923, 'Sc': 0.02938045560996381, 'Sod': 0.027583600982429624, 'Pot': 0.028438886647841874, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.03057889822595705, 'Htn': 0.02792120864410021, 'Dm': 0.02844551282051282, 'Cad': 0.026785714285714288, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pcv']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a3c8860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}

Normalized Mathematical Scores
{'Age': np.float64(0.0700174812923458), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1231200188485292), 'Al': np.float64(0.10492327845632342), 'Su': np.float64(0.6641831823193854), 'Rbc': np.float64(0.004676746817355338), 'Pc': np.float64(0.02968255960342383), 'Pcc': np.float64(0.0032073734737171167), 'Ba': np.float64(0.5771163889695731), 'Bgr': np.float64(6.69315399965433e-05), 'Bu': np.float64(0.12521129542304751), 'Sc': np.float64(0.017051225367970078), 'Sod': np.float64(0.010172508012927725), 'Pot': np.float64(0.05266843243691984), 'Hemo': np.float64(0.0782221045560305), 'Pcv': np.float64(0.41792482817295046), 'Wbcc': np.float64(0.02807713217858267), 'Rbcc': np.float64(0.5920774030861058), 'Htn': np.float64(0.0009334386783996458), 'Dm': np.float64(0.015740874235699077), 'Cad': np.float64(0.009975924526594113), 'Appet': np.float64(0.1894787611818618), 'Pe': np.float64(0.3365788210082244), 'Ane': np.float64(0.29095152581276273)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.029709507042253523, 'Bgr': 0.027056277056277056, 'Bu': 0.030621785881252923, 'Sc': 0.02938045560996381, 'Sod': 0.027583600982429624, 'Pot': 0.028438886647841874, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.03057889822595705, 'Htn': 0.02792120864410021, 'Dm': 0.02844551282051282, 'Cad': 0.026785714285714288, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Pe', 'Ane', 'Ba']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891491c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}

Normalized Mathematical Scores
{'Age': np.float64(0.0700174812923458), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1231200188485292), 'Al': np.float64(0.10492327845632342), 'Su': np.float64(0.6641831823193854), 'Rbc': np.float64(0.004676746817355338), 'Pc': np.float64(0.02968255960342383), 'Pcc': np.float64(0.0032073734737171167), 'Ba': np.float64(0.5771163889695731), 'Bgr': np.float64(6.69315399965433e-05), 'Bu': np.float64(0.12521129542304751), 'Sc': np.float64(0.017051225367970078), 'Sod': np.float64(0.010172508012927725), 'Pot': np.float64(0.05266843243691984), 'Hemo': np.float64(0.0782221045560305), 'Pcv': np.float64(0.41792482817295046), 'Wbcc': np.float64(0.02807713217858267), 'Rbcc': np.float64(0.5920774030861058), 'Htn': np.float64(0.0009334386783996458), 'Dm': np.float64(0.015740874235699077), 'Cad': np.float64(0.009975924526594113), 'Appet': np.float64(0.1894787611818618), 'Pe': np.float64(0.3365788210082244), 'Ane': np.float64(0.29095152581276273)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.029709507042253523, 'Bgr': 0.027056277056277056, 'Bu': 0.030621785881252923, 'Sc': 0.02938045560996381, 'Sod': 0.027583600982429624, 'Pot': 0.028438886647841874, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.03057889822595705, 'Htn': 0.02792120864410021, 'Dm': 0.02844551282051282, 'Cad': 0.026785714285714288, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Pe', 'Ane', 'Ba', 'Sc', 'Hemo', 'Appet', 'Dm', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880956f60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.457413137122807), 'Bp': np.float64(6.53284192290434), 'Sg': np.float64(0.8043236206824441), 'Al': np.float64(0.6854471921880354), 'Su': np.float64(4.339003737944098), 'Rbc': np.float64(0.0305524476712284), 'Pc': np.float64(0.193911469756354), 'Pcc': np.float64(0.0209532638915105), 'Ba': np.float64(3.7702101402555948), 'Bgr': np.float64(0.0004372531704539667), 'Bu': np.float64(0.8179855999608451), 'Sc': np.float64(0.11139295992076491), 'Sod': np.float64(0.06645538680793457), 'Pot': np.float64(0.3440745434375647), 'Hemo': np.float64(0.5110126439414426), 'Pcv': np.float64(2.7302368381108435), 'Wbcc': np.float64(0.18342346617117133), 'Rbcc': np.float64(3.867948080485243), 'Htn': np.float64(0.006098007330709628), 'Dm': np.float64(0.10283264311013975), 'Cad': np.float64(0.06517113796706366), 'Appet': np.float64(1.2378347945488462), 'Pe': np.float64(2.198816232244244), 'Ane': np.float64(1.9007403253626007)}

Normalized Mathematical Scores
{'Age': np.float64(0.0700174812923458), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1231200188485292), 'Al': np.float64(0.10492327845632342), 'Su': np.float64(0.6641831823193854), 'Rbc': np.float64(0.004676746817355338), 'Pc': np.float64(0.02968255960342383), 'Pcc': np.float64(0.0032073734737171167), 'Ba': np.float64(0.5771163889695731), 'Bgr': np.float64(6.69315399965433e-05), 'Bu': np.float64(0.12521129542304751), 'Sc': np.float64(0.017051225367970078), 'Sod': np.float64(0.010172508012927725), 'Pot': np.float64(0.05266843243691984), 'Hemo': np.float64(0.0782221045560305), 'Pcv': np.float64(0.41792482817295046), 'Wbcc': np.float64(0.02807713217858267), 'Rbcc': np.float64(0.5920774030861058), 'Htn': np.float64(0.0009334386783996458), 'Dm': np.float64(0.015740874235699077), 'Cad': np.float64(0.009975924526594113), 'Appet': np.float64(0.1894787611818618), 'Pe': np.float64(0.3365788210082244), 'Ane': np.float64(0.29095152581276273)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.029709507042253523, 'Bgr': 0.027056277056277056, 'Bu': 0.030621785881252923, 'Sc': 0.02938045560996381, 'Sod': 0.027583600982429624, 'Pot': 0.028438886647841874, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.03057889822595705, 'Htn': 0.02792120864410021, 'Dm': 0.02844551282051282, 'Cad': 0.026785714285714288, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Su', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Pe', 'Ane', 'Ba', 'Sc', 'Hemo', 'Appet', 'Dm', 'Pot', 'Age', 'Htn', 'Pc', 'Sod', 'Wbcc']

Run 20/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588090f260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}

Normalized Mathematical Scores
{'Age': np.float64(0.023427091402970522), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5808805156579313), 'Al': np.float64(0.010294885910693703), 'Su': np.float64(0.10415490000804678), 'Rbc': np.float64(0.02785982564329104), 'Pc': np.float64(0.06020517975571325), 'Pcc': np.float64(0.05300285834107961), 'Ba': np.float64(0.4852971200238847), 'Bgr': np.float64(0.3015404948771574), 'Bu': np.float64(0.049264344270033), 'Sc': np.float64(0.3225083591700515), 'Sod': np.float64(0.18103866116765874), 'Pot': np.float64(0.2753247216238069), 'Hemo': np.float64(0.031445935036481576), 'Pcv': np.float64(0.5011316051907078), 'Wbcc': np.float64(0.008421557587070678), 'Rbcc': np.float64(0.2631527192024419), 'Htn': np.float64(0.31326360207300863), 'Dm': np.float64(0.018071374333998802), 'Cad': np.float64(0.002057126447678315), 'Appet': np.float64(0.055327033558080295), 'Pe': np.float64(0.01619651565288432), 'Ane': np.float64(0.03408501192889638)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.028588564574170333, 'Su': 0.028790389395194696, 'Rbc': 0.027526395173453996, 'Pc': 0.028381642512077296, 'Pcc': 0.027598020555767037, 'Ba': 0.029709507042253523, 'Bgr': 0.03007688828584351, 'Bu': 0.02946236559139785, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.029631255487269532, 'Hemo': 0.028371628371628373, 'Pcv': 0.031024531024531024, 'Wbcc': 0.026132699813337858, 'Rbcc': 0.02919863597612958, 'Htn': 0.031024531024531024, 'Dm': 0.028125, 'Cad': 0.026190476190476188, 'Appet': 0.027783137179239824, 'Pe': 0.027271052146674038, 'Ane': 0.028309409888357256}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889138b60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}

Normalized Mathematical Scores
{'Age': np.float64(0.023427091402970522), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5808805156579313), 'Al': np.float64(0.010294885910693703), 'Su': np.float64(0.10415490000804678), 'Rbc': np.float64(0.02785982564329104), 'Pc': np.float64(0.06020517975571325), 'Pcc': np.float64(0.05300285834107961), 'Ba': np.float64(0.4852971200238847), 'Bgr': np.float64(0.3015404948771574), 'Bu': np.float64(0.049264344270033), 'Sc': np.float64(0.3225083591700515), 'Sod': np.float64(0.18103866116765874), 'Pot': np.float64(0.2753247216238069), 'Hemo': np.float64(0.031445935036481576), 'Pcv': np.float64(0.5011316051907078), 'Wbcc': np.float64(0.008421557587070678), 'Rbcc': np.float64(0.2631527192024419), 'Htn': np.float64(0.31326360207300863), 'Dm': np.float64(0.018071374333998802), 'Cad': np.float64(0.002057126447678315), 'Appet': np.float64(0.055327033558080295), 'Pe': np.float64(0.01619651565288432), 'Ane': np.float64(0.03408501192889638)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.028588564574170333, 'Su': 0.028790389395194696, 'Rbc': 0.027526395173453996, 'Pc': 0.028381642512077296, 'Pcc': 0.027598020555767037, 'Ba': 0.029709507042253523, 'Bgr': 0.03007688828584351, 'Bu': 0.02946236559139785, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.029631255487269532, 'Hemo': 0.028371628371628373, 'Pcv': 0.031024531024531024, 'Wbcc': 0.026132699813337858, 'Rbcc': 0.02919863597612958, 'Htn': 0.031024531024531024, 'Dm': 0.028125, 'Cad': 0.026190476190476188, 'Appet': 0.027783137179239824, 'Pe': 0.027271052146674038, 'Ane': 0.028309409888357256}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Ba', 'Pot', 'Bu', 'Sod']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a3c8860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}

Normalized Mathematical Scores
{'Age': np.float64(0.023427091402970522), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5808805156579313), 'Al': np.float64(0.010294885910693703), 'Su': np.float64(0.10415490000804678), 'Rbc': np.float64(0.02785982564329104), 'Pc': np.float64(0.06020517975571325), 'Pcc': np.float64(0.05300285834107961), 'Ba': np.float64(0.4852971200238847), 'Bgr': np.float64(0.3015404948771574), 'Bu': np.float64(0.049264344270033), 'Sc': np.float64(0.3225083591700515), 'Sod': np.float64(0.18103866116765874), 'Pot': np.float64(0.2753247216238069), 'Hemo': np.float64(0.031445935036481576), 'Pcv': np.float64(0.5011316051907078), 'Wbcc': np.float64(0.008421557587070678), 'Rbcc': np.float64(0.2631527192024419), 'Htn': np.float64(0.31326360207300863), 'Dm': np.float64(0.018071374333998802), 'Cad': np.float64(0.002057126447678315), 'Appet': np.float64(0.055327033558080295), 'Pe': np.float64(0.01619651565288432), 'Ane': np.float64(0.03408501192889638)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.028588564574170333, 'Su': 0.028790389395194696, 'Rbc': 0.027526395173453996, 'Pc': 0.028381642512077296, 'Pcc': 0.027598020555767037, 'Ba': 0.029709507042253523, 'Bgr': 0.03007688828584351, 'Bu': 0.02946236559139785, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.029631255487269532, 'Hemo': 0.028371628371628373, 'Pcv': 0.031024531024531024, 'Wbcc': 0.026132699813337858, 'Rbcc': 0.02919863597612958, 'Htn': 0.031024531024531024, 'Dm': 0.028125, 'Cad': 0.026190476190476188, 'Appet': 0.027783137179239824, 'Pe': 0.027271052146674038, 'Ane': 0.028309409888357256}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Ba', 'Pot', 'Bu', 'Sod', 'Rbcc', 'Su', 'Al', 'Pc', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910ef60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.11815274894693678), 'Bp': np.float64(5.043423740258049), 'Sg': np.float64(2.9296265829225483), 'Al': np.float64(0.05192147200524073), 'Su': np.float64(0.5252972953647864), 'Rbc': np.float64(0.14050890604882402), 'Pc': np.float64(0.3036402328664675), 'Pcc': np.float64(0.26731587405893525), 'Ba': np.float64(2.44755901620732), 'Bgr': np.float64(1.5207964905126163), 'Bu': np.float64(0.24846096343973004), 'Sc': np.float64(1.6265463150699073), 'Sod': np.float64(0.913054681637503), 'Pot': np.float64(1.3885792373174464), 'Hemo': np.float64(0.15859517529760356), 'Pcv': np.float64(2.527419034612439), 'Wbcc': np.float64(0.04247348346458255), 'Rbcc': np.float64(1.3271906713390555), 'Htn': np.float64(1.5799210876537624), 'Dm': np.float64(0.09114159833517956), 'Cad': np.float64(0.01037496036293352), 'Appet': np.float64(0.27903767452487593), 'Pe': np.float64(0.08168589155321788), 'Ane': np.float64(0.1719051583491748)}

Normalized Mathematical Scores
{'Age': np.float64(0.023427091402970522), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5808805156579313), 'Al': np.float64(0.010294885910693703), 'Su': np.float64(0.10415490000804678), 'Rbc': np.float64(0.02785982564329104), 'Pc': np.float64(0.06020517975571325), 'Pcc': np.float64(0.05300285834107961), 'Ba': np.float64(0.4852971200238847), 'Bgr': np.float64(0.3015404948771574), 'Bu': np.float64(0.049264344270033), 'Sc': np.float64(0.3225083591700515), 'Sod': np.float64(0.18103866116765874), 'Pot': np.float64(0.2753247216238069), 'Hemo': np.float64(0.031445935036481576), 'Pcv': np.float64(0.5011316051907078), 'Wbcc': np.float64(0.008421557587070678), 'Rbcc': np.float64(0.2631527192024419), 'Htn': np.float64(0.31326360207300863), 'Dm': np.float64(0.018071374333998802), 'Cad': np.float64(0.002057126447678315), 'Appet': np.float64(0.055327033558080295), 'Pe': np.float64(0.01619651565288432), 'Ane': np.float64(0.03408501192889638)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027364110201042444, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.028588564574170333, 'Su': 0.028790389395194696, 'Rbc': 0.027526395173453996, 'Pc': 0.028381642512077296, 'Pcc': 0.027598020555767037, 'Ba': 0.029709507042253523, 'Bgr': 0.03007688828584351, 'Bu': 0.02946236559139785, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.029631255487269532, 'Hemo': 0.028371628371628373, 'Pcv': 0.031024531024531024, 'Wbcc': 0.026132699813337858, 'Rbcc': 0.02919863597612958, 'Htn': 0.031024531024531024, 'Dm': 0.028125, 'Cad': 0.026190476190476188, 'Appet': 0.027783137179239824, 'Pe': 0.027271052146674038, 'Ane': 0.028309409888357256}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Ba', 'Pot', 'Bu', 'Sod', 'Rbcc', 'Su', 'Al', 'Pc', 'Hemo', 'Ane', 'Dm', 'Appet', 'Pcc', 'Rbc']

Run 21/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891705f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}

Normalized Mathematical Scores
{'Age': np.float64(0.08180373705422836), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015429344336043678), 'Al': np.float64(0.002776434945335159), 'Su': np.float64(0.08095631163015282), 'Rbc': np.float64(0.03722102747545024), 'Pc': np.float64(0.020480327440009296), 'Pcc': np.float64(0.004502126808065258), 'Ba': np.float64(0.22137707426303943), 'Bgr': np.float64(0.03677247113237743), 'Bu': np.float64(0.032314701888347994), 'Sc': np.float64(0.1858427432268997), 'Sod': np.float64(0.09443349550143557), 'Pot': np.float64(0.23418150721965159), 'Hemo': np.float64(0.034332465402934685), 'Pcv': np.float64(0.48287380816555653), 'Wbcc': np.float64(0.04185330619881836), 'Rbcc': np.float64(0.15897562375359028), 'Htn': np.float64(0.025817690211188734), 'Dm': np.float64(0.07410721547422625), 'Cad': np.float64(0.0006570118708747849), 'Appet': np.float64(0.0033518751245444913), 'Pe': np.float64(0.30282073079074995), 'Ane': np.float64(0.047157537630454716)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.02844163539403516, 'Su': 0.028991596638655463, 'Rbc': 0.02821939586645469, 'Pc': 0.02715098147128967, 'Pcc': 0.0264301860545992, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.029116045245077504, 'Sc': 0.031544957774465976, 'Sod': 0.029631255487269532, 'Pot': 0.03055037313432836, 'Hemo': 0.02854251012145749, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029631255487269532, 'Htn': 0.028693528693528692, 'Dm': 0.029709507042253523, 'Cad': 0.026190476190476188, 'Appet': 0.026279628993473032, 'Pe': 0.030798389007344232, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pe', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889170f20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}

Normalized Mathematical Scores
{'Age': np.float64(0.08180373705422836), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015429344336043678), 'Al': np.float64(0.002776434945335159), 'Su': np.float64(0.08095631163015282), 'Rbc': np.float64(0.03722102747545024), 'Pc': np.float64(0.020480327440009296), 'Pcc': np.float64(0.004502126808065258), 'Ba': np.float64(0.22137707426303943), 'Bgr': np.float64(0.03677247113237743), 'Bu': np.float64(0.032314701888347994), 'Sc': np.float64(0.1858427432268997), 'Sod': np.float64(0.09443349550143557), 'Pot': np.float64(0.23418150721965159), 'Hemo': np.float64(0.034332465402934685), 'Pcv': np.float64(0.48287380816555653), 'Wbcc': np.float64(0.04185330619881836), 'Rbcc': np.float64(0.15897562375359028), 'Htn': np.float64(0.025817690211188734), 'Dm': np.float64(0.07410721547422625), 'Cad': np.float64(0.0006570118708747849), 'Appet': np.float64(0.0033518751245444913), 'Pe': np.float64(0.30282073079074995), 'Ane': np.float64(0.047157537630454716)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.02844163539403516, 'Su': 0.028991596638655463, 'Rbc': 0.02821939586645469, 'Pc': 0.02715098147128967, 'Pcc': 0.0264301860545992, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.029116045245077504, 'Sc': 0.031544957774465976, 'Sod': 0.029631255487269532, 'Pot': 0.03055037313432836, 'Hemo': 0.02854251012145749, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029631255487269532, 'Htn': 0.028693528693528692, 'Dm': 0.029709507042253523, 'Cad': 0.026190476190476188, 'Appet': 0.026279628993473032, 'Pe': 0.030798389007344232, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pe', 'Pot', 'Dm', 'Sod', 'Rbcc', 'Ba', 'Age']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588094b4a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}

Normalized Mathematical Scores
{'Age': np.float64(0.08180373705422836), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015429344336043678), 'Al': np.float64(0.002776434945335159), 'Su': np.float64(0.08095631163015282), 'Rbc': np.float64(0.03722102747545024), 'Pc': np.float64(0.020480327440009296), 'Pcc': np.float64(0.004502126808065258), 'Ba': np.float64(0.22137707426303943), 'Bgr': np.float64(0.03677247113237743), 'Bu': np.float64(0.032314701888347994), 'Sc': np.float64(0.1858427432268997), 'Sod': np.float64(0.09443349550143557), 'Pot': np.float64(0.23418150721965159), 'Hemo': np.float64(0.034332465402934685), 'Pcv': np.float64(0.48287380816555653), 'Wbcc': np.float64(0.04185330619881836), 'Rbcc': np.float64(0.15897562375359028), 'Htn': np.float64(0.025817690211188734), 'Dm': np.float64(0.07410721547422625), 'Cad': np.float64(0.0006570118708747849), 'Appet': np.float64(0.0033518751245444913), 'Pe': np.float64(0.30282073079074995), 'Ane': np.float64(0.047157537630454716)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.02844163539403516, 'Su': 0.028991596638655463, 'Rbc': 0.02821939586645469, 'Pc': 0.02715098147128967, 'Pcc': 0.0264301860545992, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.029116045245077504, 'Sc': 0.031544957774465976, 'Sod': 0.029631255487269532, 'Pot': 0.03055037313432836, 'Hemo': 0.02854251012145749, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029631255487269532, 'Htn': 0.028693528693528692, 'Dm': 0.029709507042253523, 'Cad': 0.026190476190476188, 'Appet': 0.026279628993473032, 'Pe': 0.030798389007344232, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pe', 'Pot', 'Dm', 'Sod', 'Rbcc', 'Ba', 'Age', 'Bu', 'Ane', 'Su', 'Htn', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889181580>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.46634163084962027), 'Bp': np.float64(5.700737492475175), 'Sg': np.float64(0.08795864174079368), 'Al': np.float64(0.015827726788290402), 'Su': np.float64(0.46151068096251624), 'Rbc': np.float64(0.21218730683774778), 'Pc': np.float64(0.11675297049542911), 'Pcc': np.float64(0.025665443090615202), 'Ba': np.float64(1.26201258722577), 'Bgr': np.float64(0.20963020487530507), 'Bu': np.float64(0.18421763261306373), 'Sc': np.float64(1.0594406940180239), 'Sod': np.float64(0.5383405683505195), 'Pot': np.float64(1.3350072982514136), 'Hemo': np.float64(0.19572037273161658), 'Pcv': np.float64(2.7527368223436532), 'Wbcc': np.float64(0.23859471183164746), 'Rbcc': np.float64(0.9062782987217191), 'Htn': np.float64(0.14717987455603293), 'Dm': np.float64(0.42246578171685795), 'Cad': np.float64(0.0037454522052971445), 'Appet': np.float64(0.019108160192585676), 'Pe': np.float64(1.7263014935175598), 'Ane': np.float64(0.2688327428227421)}

Normalized Mathematical Scores
{'Age': np.float64(0.08180373705422836), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015429344336043678), 'Al': np.float64(0.002776434945335159), 'Su': np.float64(0.08095631163015282), 'Rbc': np.float64(0.03722102747545024), 'Pc': np.float64(0.020480327440009296), 'Pcc': np.float64(0.004502126808065258), 'Ba': np.float64(0.22137707426303943), 'Bgr': np.float64(0.03677247113237743), 'Bu': np.float64(0.032314701888347994), 'Sc': np.float64(0.1858427432268997), 'Sod': np.float64(0.09443349550143557), 'Pot': np.float64(0.23418150721965159), 'Hemo': np.float64(0.034332465402934685), 'Pcv': np.float64(0.48287380816555653), 'Wbcc': np.float64(0.04185330619881836), 'Rbcc': np.float64(0.15897562375359028), 'Htn': np.float64(0.025817690211188734), 'Dm': np.float64(0.07410721547422625), 'Cad': np.float64(0.0006570118708747849), 'Appet': np.float64(0.0033518751245444913), 'Pe': np.float64(0.30282073079074995), 'Ane': np.float64(0.047157537630454716)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.028373015873015873, 'Al': 0.02844163539403516, 'Su': 0.028991596638655463, 'Rbc': 0.02821939586645469, 'Pc': 0.02715098147128967, 'Pcc': 0.0264301860545992, 'Ba': 0.02946912242686891, 'Bgr': 0.028484848484848488, 'Bu': 0.029116045245077504, 'Sc': 0.031544957774465976, 'Sod': 0.029631255487269532, 'Pot': 0.03055037313432836, 'Hemo': 0.02854251012145749, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029631255487269532, 'Htn': 0.028693528693528692, 'Dm': 0.029709507042253523, 'Cad': 0.026190476190476188, 'Appet': 0.026279628993473032, 'Pe': 0.030798389007344232, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Pe', 'Pot', 'Dm', 'Sod', 'Rbcc', 'Ba', 'Age', 'Bu', 'Ane', 'Su', 'Htn', 'Hemo', 'Bgr', 'Al', 'Sg', 'Rbc', 'Wbcc']

Run 22/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588a33f0b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}

Normalized Mathematical Scores
{'Age': np.float64(0.016449220984322565), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11501321817928077), 'Al': np.float64(0.0033885356976028846), 'Su': np.float64(0.2684823468570612), 'Rbc': np.float64(0.0006911005036768688), 'Pc': np.float64(0.009639328045270137), 'Pcc': np.float64(0.009454640238017469), 'Ba': np.float64(0.6493946169969184), 'Bgr': np.float64(0.0766125357062118), 'Bu': np.float64(0.0655961389381518), 'Sc': np.float64(0.08971657844154765), 'Sod': np.float64(0.48843780729808367), 'Pot': np.float64(0.07073169882608872), 'Hemo': np.float64(0.0003443855375670131), 'Pcv': np.float64(0.4281664644506601), 'Wbcc': np.float64(0.0005160081083650223), 'Rbcc': np.float64(0.42342512952592476), 'Htn': np.float64(0.1781083918381082), 'Dm': np.float64(0.00405680597891386), 'Cad': np.float64(0.0006911005036768688), 'Appet': np.float64(0.27855208038669776), 'Pe': np.float64(0.033758870147133614), 'Ane': np.float64(0.27239891615435635)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.02889344262295082, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Ba': 0.03021353930031804, 'Bgr': 0.02904040404040404, 'Bu': 0.02964254577157803, 'Sc': 0.03047794966520434, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.027432808155699723, 'Pcv': 0.030776515151515152, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.028283227848101264, 'Cad': 0.026631393298059962, 'Appet': 0.029236022193768675, 'Pe': 0.028258706467661692, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Sod', 'Pcv', 'Sc', 'Htn']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880957bc0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}

Normalized Mathematical Scores
{'Age': np.float64(0.016449220984322565), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11501321817928077), 'Al': np.float64(0.0033885356976028846), 'Su': np.float64(0.2684823468570612), 'Rbc': np.float64(0.0006911005036768688), 'Pc': np.float64(0.009639328045270137), 'Pcc': np.float64(0.009454640238017469), 'Ba': np.float64(0.6493946169969184), 'Bgr': np.float64(0.0766125357062118), 'Bu': np.float64(0.0655961389381518), 'Sc': np.float64(0.08971657844154765), 'Sod': np.float64(0.48843780729808367), 'Pot': np.float64(0.07073169882608872), 'Hemo': np.float64(0.0003443855375670131), 'Pcv': np.float64(0.4281664644506601), 'Wbcc': np.float64(0.0005160081083650223), 'Rbcc': np.float64(0.42342512952592476), 'Htn': np.float64(0.1781083918381082), 'Dm': np.float64(0.00405680597891386), 'Cad': np.float64(0.0006911005036768688), 'Appet': np.float64(0.27855208038669776), 'Pe': np.float64(0.033758870147133614), 'Ane': np.float64(0.27239891615435635)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.02889344262295082, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Ba': 0.03021353930031804, 'Bgr': 0.02904040404040404, 'Bu': 0.02964254577157803, 'Sc': 0.03047794966520434, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.027432808155699723, 'Pcv': 0.030776515151515152, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.028283227848101264, 'Cad': 0.026631393298059962, 'Appet': 0.029236022193768675, 'Pe': 0.028258706467661692, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Sod', 'Pcv', 'Sc', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Ane', 'Bu']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889148230>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}

Normalized Mathematical Scores
{'Age': np.float64(0.016449220984322565), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11501321817928077), 'Al': np.float64(0.0033885356976028846), 'Su': np.float64(0.2684823468570612), 'Rbc': np.float64(0.0006911005036768688), 'Pc': np.float64(0.009639328045270137), 'Pcc': np.float64(0.009454640238017469), 'Ba': np.float64(0.6493946169969184), 'Bgr': np.float64(0.0766125357062118), 'Bu': np.float64(0.0655961389381518), 'Sc': np.float64(0.08971657844154765), 'Sod': np.float64(0.48843780729808367), 'Pot': np.float64(0.07073169882608872), 'Hemo': np.float64(0.0003443855375670131), 'Pcv': np.float64(0.4281664644506601), 'Wbcc': np.float64(0.0005160081083650223), 'Rbcc': np.float64(0.42342512952592476), 'Htn': np.float64(0.1781083918381082), 'Dm': np.float64(0.00405680597891386), 'Cad': np.float64(0.0006911005036768688), 'Appet': np.float64(0.27855208038669776), 'Pe': np.float64(0.033758870147133614), 'Ane': np.float64(0.27239891615435635)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.02889344262295082, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Ba': 0.03021353930031804, 'Bgr': 0.02904040404040404, 'Bu': 0.02964254577157803, 'Sc': 0.03047794966520434, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.027432808155699723, 'Pcv': 0.030776515151515152, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.028283227848101264, 'Cad': 0.026631393298059962, 'Appet': 0.029236022193768675, 'Pe': 0.028258706467661692, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Sod', 'Pcv', 'Sc', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Ane', 'Bu', 'Su', 'Appet', 'Bgr', 'Al', 'Pot']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889149040>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.09716814086539154), 'Bp': np.float64(5.907157606916498), 'Sg': np.float64(0.6794012066636853), 'Al': np.float64(0.020016614422402983), 'Su': np.float64(1.5859675375594828), 'Rbc': np.float64(0.004082439597438639), 'Pc': np.float64(0.05694102998818103), 'Pcc': np.float64(0.0558500500026637), 'Ba': np.float64(3.836076351683972), 'Bgr': np.float64(0.4525623230821109), 'Bu': np.float64(0.3874867311128549), 'Sc': np.float64(0.5299699688075089), 'Sod': np.float64(2.8852791088864898), 'Pot': np.float64(0.4178232927706567), 'Hemo': np.float64(0.002034339647951009), 'Pcv': np.float64(2.529246787506259), 'Wbcc': np.float64(0.0030481412225590344), 'Rbcc': np.float64(2.50123897483867), 'Htn': np.float64(1.0521143417021452), 'Dm': np.float64(0.02396419229812534), 'Cad': np.float64(0.004082439597438639), 'Appet': np.float64(1.6454510405786975), 'Pe': np.float64(0.19941896659054661), 'Ane': np.float64(1.6091033296770154)}

Normalized Mathematical Scores
{'Age': np.float64(0.016449220984322565), 'Bp': np.float64(1.0), 'Sg': np.float64(0.11501321817928077), 'Al': np.float64(0.0033885356976028846), 'Su': np.float64(0.2684823468570612), 'Rbc': np.float64(0.0006911005036768688), 'Pc': np.float64(0.009639328045270137), 'Pcc': np.float64(0.009454640238017469), 'Ba': np.float64(0.6493946169969184), 'Bgr': np.float64(0.0766125357062118), 'Bu': np.float64(0.0655961389381518), 'Sc': np.float64(0.08971657844154765), 'Sod': np.float64(0.48843780729808367), 'Pot': np.float64(0.07073169882608872), 'Hemo': np.float64(0.0003443855375670131), 'Pcv': np.float64(0.4281664644506601), 'Wbcc': np.float64(0.0005160081083650223), 'Rbcc': np.float64(0.42342512952592476), 'Htn': np.float64(0.1781083918381082), 'Dm': np.float64(0.00405680597891386), 'Cad': np.float64(0.0006911005036768688), 'Appet': np.float64(0.27855208038669776), 'Pe': np.float64(0.033758870147133614), 'Ane': np.float64(0.27239891615435635)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.02889344262295082, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Ba': 0.03021353930031804, 'Bgr': 0.02904040404040404, 'Bu': 0.02964254577157803, 'Sc': 0.03047794966520434, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.027432808155699723, 'Pcv': 0.030776515151515152, 'Wbcc': 0.026279628993473032, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.028283227848101264, 'Cad': 0.026631393298059962, 'Appet': 0.029236022193768675, 'Pe': 0.028258706467661692, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Sod', 'Pcv', 'Sc', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Ane', 'Bu', 'Su', 'Appet', 'Bgr', 'Al', 'Pot', 'Dm', 'Pe', 'Age', 'Pc', 'Hemo']

Run 23/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5880948a10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}

Normalized Mathematical Scores
{'Age': np.float64(0.006886415843282214), 'Bp': np.float64(1.0), 'Sg': np.float64(0.02227879787249887), 'Al': np.float64(0.003532825427952274), 'Su': np.float64(0.256360597269538), 'Rbc': np.float64(0.03661038538450092), 'Pc': np.float64(0.00020719541916734), 'Pcc': np.float64(0.0006178482646801023), 'Ba': np.float64(0.5673171696038074), 'Bgr': np.float64(0.08336244057429941), 'Bu': np.float64(0.016172321622917082), 'Sc': np.float64(0.002011453053296673), 'Sod': np.float64(0.0030567856260745705), 'Pot': np.float64(0.05412216272340618), 'Hemo': np.float64(0.007588843215102144), 'Pcv': np.float64(0.11247622820120828), 'Wbcc': np.float64(1.2369261189006507e-05), 'Rbcc': np.float64(0.1144332872867466), 'Htn': np.float64(0.005152480975879998), 'Dm': np.float64(0.001341969841275509), 'Cad': np.float64(0.027171490485836162), 'Appet': np.float64(0.17347870063530577), 'Pe': np.float64(0.08411684120752706), 'Ane': np.float64(0.004861726983750938)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.028991596638655463, 'Pc': 0.026540946394272742, 'Pcc': 0.026279628993473032, 'Ba': 0.03021353930031804, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.02889344262295082, 'Sod': 0.027583600982429624, 'Pot': 0.029418126757516764, 'Hemo': 0.0288981288981289, 'Pcv': 0.030303030303030304, 'Wbcc': 0.025989268947015427, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.02797067901234568, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029850746268656716, 'Ane': 0.02813852813852814}
Top 5 Features Selected: ['Bp', 'Su', 'Pcv', 'Ba', 'Rbcc']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588090d910>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}

Normalized Mathematical Scores
{'Age': np.float64(0.006886415843282214), 'Bp': np.float64(1.0), 'Sg': np.float64(0.02227879787249887), 'Al': np.float64(0.003532825427952274), 'Su': np.float64(0.256360597269538), 'Rbc': np.float64(0.03661038538450092), 'Pc': np.float64(0.00020719541916734), 'Pcc': np.float64(0.0006178482646801023), 'Ba': np.float64(0.5673171696038074), 'Bgr': np.float64(0.08336244057429941), 'Bu': np.float64(0.016172321622917082), 'Sc': np.float64(0.002011453053296673), 'Sod': np.float64(0.0030567856260745705), 'Pot': np.float64(0.05412216272340618), 'Hemo': np.float64(0.007588843215102144), 'Pcv': np.float64(0.11247622820120828), 'Wbcc': np.float64(1.2369261189006507e-05), 'Rbcc': np.float64(0.1144332872867466), 'Htn': np.float64(0.005152480975879998), 'Dm': np.float64(0.001341969841275509), 'Cad': np.float64(0.027171490485836162), 'Appet': np.float64(0.17347870063530577), 'Pe': np.float64(0.08411684120752706), 'Ane': np.float64(0.004861726983750938)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.028991596638655463, 'Pc': 0.026540946394272742, 'Pcc': 0.026279628993473032, 'Ba': 0.03021353930031804, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.02889344262295082, 'Sod': 0.027583600982429624, 'Pot': 0.029418126757516764, 'Hemo': 0.0288981288981289, 'Pcv': 0.030303030303030304, 'Wbcc': 0.025989268947015427, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.02797067901234568, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029850746268656716, 'Ane': 0.02813852813852814}
Top 10 Features Selected: ['Bp', 'Su', 'Pcv', 'Ba', 'Rbcc', 'Bgr', 'Pe', 'Bu', 'Sg', 'Appet']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910d250>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}

Normalized Mathematical Scores
{'Age': np.float64(0.006886415843282214), 'Bp': np.float64(1.0), 'Sg': np.float64(0.02227879787249887), 'Al': np.float64(0.003532825427952274), 'Su': np.float64(0.256360597269538), 'Rbc': np.float64(0.03661038538450092), 'Pc': np.float64(0.00020719541916734), 'Pcc': np.float64(0.0006178482646801023), 'Ba': np.float64(0.5673171696038074), 'Bgr': np.float64(0.08336244057429941), 'Bu': np.float64(0.016172321622917082), 'Sc': np.float64(0.002011453053296673), 'Sod': np.float64(0.0030567856260745705), 'Pot': np.float64(0.05412216272340618), 'Hemo': np.float64(0.007588843215102144), 'Pcv': np.float64(0.11247622820120828), 'Wbcc': np.float64(1.2369261189006507e-05), 'Rbcc': np.float64(0.1144332872867466), 'Htn': np.float64(0.005152480975879998), 'Dm': np.float64(0.001341969841275509), 'Cad': np.float64(0.027171490485836162), 'Appet': np.float64(0.17347870063530577), 'Pe': np.float64(0.08411684120752706), 'Ane': np.float64(0.004861726983750938)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.028991596638655463, 'Pc': 0.026540946394272742, 'Pcc': 0.026279628993473032, 'Ba': 0.03021353930031804, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.02889344262295082, 'Sod': 0.027583600982429624, 'Pot': 0.029418126757516764, 'Hemo': 0.0288981288981289, 'Pcv': 0.030303030303030304, 'Wbcc': 0.025989268947015427, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.02797067901234568, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029850746268656716, 'Ane': 0.02813852813852814}
Top 15 Features Selected: ['Bp', 'Su', 'Pcv', 'Ba', 'Rbcc', 'Bgr', 'Pe', 'Bu', 'Sg', 'Appet', 'Pot', 'Al', 'Htn', 'Rbc', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809572c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.08148864859016981), 'Bp': np.float64(11.833245398571599), 'Sg': np.float64(0.263630482410454), 'Al': np.float64(0.041804790239272985), 'Su': np.float64(3.033577858014828), 'Rbc': np.float64(0.43321967439107845), 'Pc': np.float64(0.0024517942404670397), 'Pcc': np.float64(0.007311150135041268), 'Ba': np.float64(6.713203286744918), 'Bgr': np.float64(0.9864482163395268), 'Bu': np.float64(0.19137105042860353), 'Sc': np.float64(0.023802017587365647), 'Sod': np.float64(0.036171694444166715), 'Pot': np.float64(0.6404408330074894), 'Hemo': np.float64(0.08980064405558874), 'Pcv': np.float64(1.330958809810637), 'Wbcc': np.float64(0.0001463685030485415), 'Rbcc': np.float64(1.354117170229316), 'Htn': np.float64(0.060970571799059695), 'Dm': np.float64(0.015879858449295275), 'Cad': np.float64(0.32152691476385276), 'Appet': np.float64(2.0528160360429117), 'Pe': np.float64(0.9953752241613474), 'Ane': np.float64(0.057530008459582165)}

Normalized Mathematical Scores
{'Age': np.float64(0.006886415843282214), 'Bp': np.float64(1.0), 'Sg': np.float64(0.02227879787249887), 'Al': np.float64(0.003532825427952274), 'Su': np.float64(0.256360597269538), 'Rbc': np.float64(0.03661038538450092), 'Pc': np.float64(0.00020719541916734), 'Pcc': np.float64(0.0006178482646801023), 'Ba': np.float64(0.5673171696038074), 'Bgr': np.float64(0.08336244057429941), 'Bu': np.float64(0.016172321622917082), 'Sc': np.float64(0.002011453053296673), 'Sod': np.float64(0.0030567856260745705), 'Pot': np.float64(0.05412216272340618), 'Hemo': np.float64(0.007588843215102144), 'Pcv': np.float64(0.11247622820120828), 'Wbcc': np.float64(1.2369261189006507e-05), 'Rbcc': np.float64(0.1144332872867466), 'Htn': np.float64(0.005152480975879998), 'Dm': np.float64(0.001341969841275509), 'Cad': np.float64(0.027171490485836162), 'Appet': np.float64(0.17347870063530577), 'Pe': np.float64(0.08411684120752706), 'Ane': np.float64(0.004861726983750938)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.02921395544346364, 'Su': 0.03057889822595705, 'Rbc': 0.028991596638655463, 'Pc': 0.026540946394272742, 'Pcc': 0.026279628993473032, 'Ba': 0.03021353930031804, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.02889344262295082, 'Sod': 0.027583600982429624, 'Pot': 0.029418126757516764, 'Hemo': 0.0288981288981289, 'Pcv': 0.030303030303030304, 'Wbcc': 0.025989268947015427, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.02797067901234568, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029850746268656716, 'Ane': 0.02813852813852814}
Top 20 Features Selected: ['Bp', 'Su', 'Pcv', 'Ba', 'Rbcc', 'Bgr', 'Pe', 'Bu', 'Sg', 'Appet', 'Pot', 'Al', 'Htn', 'Rbc', 'Hemo', 'Sc', 'Cad', 'Ane', 'Age', 'Dm']

Run 24/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809483b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}

Normalized Mathematical Scores
{'Age': np.float64(0.019679500533092743), 'Bp': np.float64(1.0), 'Sg': np.float64(0.05993993558007728), 'Al': np.float64(0.01706159409330873), 'Su': np.float64(0.1604331293435716), 'Rbc': np.float64(0.0030347240528150023), 'Pc': np.float64(0.04738202991297126), 'Pcc': np.float64(0.00038203957386581455), 'Ba': np.float64(0.05040304966798535), 'Bgr': np.float64(0.17174997364818242), 'Bu': np.float64(0.16662097487205388), 'Sc': np.float64(0.174040489220143), 'Sod': np.float64(0.11377530284890879), 'Pot': np.float64(0.5652113982814813), 'Hemo': np.float64(0.003782228135514332), 'Pcv': np.float64(0.3058204118858228), 'Wbcc': np.float64(0.060544632827148066), 'Rbcc': np.float64(0.21756302195964794), 'Htn': np.float64(0.03489751198995834), 'Dm': np.float64(0.006972024290533084), 'Cad': np.float64(0.04738202991297126), 'Appet': np.float64(0.04738202991297126), 'Pe': np.float64(0.15763787578937333), 'Ane': np.float64(0.11196861130248739)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02921395544346364, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.027598020555767037, 'Bgr': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.029030910609857977, 'Dm': 0.028283227848101264, 'Cad': 0.02761904761904762, 'Appet': 0.027417840375586856, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Sc', 'Bu', 'Pot', 'Pcv']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f588910e3c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}

Normalized Mathematical Scores
{'Age': np.float64(0.019679500533092743), 'Bp': np.float64(1.0), 'Sg': np.float64(0.05993993558007728), 'Al': np.float64(0.01706159409330873), 'Su': np.float64(0.1604331293435716), 'Rbc': np.float64(0.0030347240528150023), 'Pc': np.float64(0.04738202991297126), 'Pcc': np.float64(0.00038203957386581455), 'Ba': np.float64(0.05040304966798535), 'Bgr': np.float64(0.17174997364818242), 'Bu': np.float64(0.16662097487205388), 'Sc': np.float64(0.174040489220143), 'Sod': np.float64(0.11377530284890879), 'Pot': np.float64(0.5652113982814813), 'Hemo': np.float64(0.003782228135514332), 'Pcv': np.float64(0.3058204118858228), 'Wbcc': np.float64(0.060544632827148066), 'Rbcc': np.float64(0.21756302195964794), 'Htn': np.float64(0.03489751198995834), 'Dm': np.float64(0.006972024290533084), 'Cad': np.float64(0.04738202991297126), 'Appet': np.float64(0.04738202991297126), 'Pe': np.float64(0.15763787578937333), 'Ane': np.float64(0.11196861130248739)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02921395544346364, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.027598020555767037, 'Bgr': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.029030910609857977, 'Dm': 0.028283227848101264, 'Cad': 0.02761904761904762, 'Appet': 0.027417840375586856, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Sc', 'Bu', 'Pot', 'Pcv', 'Rbcc', 'Bgr', 'Sg', 'Pe', 'Su']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889183740>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}

Normalized Mathematical Scores
{'Age': np.float64(0.019679500533092743), 'Bp': np.float64(1.0), 'Sg': np.float64(0.05993993558007728), 'Al': np.float64(0.01706159409330873), 'Su': np.float64(0.1604331293435716), 'Rbc': np.float64(0.0030347240528150023), 'Pc': np.float64(0.04738202991297126), 'Pcc': np.float64(0.00038203957386581455), 'Ba': np.float64(0.05040304966798535), 'Bgr': np.float64(0.17174997364818242), 'Bu': np.float64(0.16662097487205388), 'Sc': np.float64(0.174040489220143), 'Sod': np.float64(0.11377530284890879), 'Pot': np.float64(0.5652113982814813), 'Hemo': np.float64(0.003782228135514332), 'Pcv': np.float64(0.3058204118858228), 'Wbcc': np.float64(0.060544632827148066), 'Rbcc': np.float64(0.21756302195964794), 'Htn': np.float64(0.03489751198995834), 'Dm': np.float64(0.006972024290533084), 'Cad': np.float64(0.04738202991297126), 'Appet': np.float64(0.04738202991297126), 'Pe': np.float64(0.15763787578937333), 'Ane': np.float64(0.11196861130248739)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02921395544346364, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.027598020555767037, 'Bgr': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.029030910609857977, 'Dm': 0.028283227848101264, 'Cad': 0.02761904761904762, 'Appet': 0.027417840375586856, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Sc', 'Bu', 'Pot', 'Pcv', 'Rbcc', 'Bgr', 'Sg', 'Pe', 'Su', 'Ane', 'Al', 'Sod', 'Htn', 'Dm']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889181d00>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.15780193201138457), 'Bp': np.float64(8.01859436147921), 'Sg': np.float64(0.4806340294698347), 'Al': np.float64(0.13681000219445238), 'Su': np.float64(1.286448186348828), 'Rbc': np.float64(0.02433422117854771), 'Pc': np.float64(0.37993727789559056), 'Pcc': np.float64(0.0030634203728623407), 'Ba': np.float64(0.4041616098690639), 'Bgr': np.float64(1.3771933702795185), 'Bu': np.float64(1.3360660096132202), 'Sc': np.float64(1.3955600855297219), 'Sod': np.float64(0.9123180018998495), 'Pot': np.float64(4.532200931303666), 'Hemo': np.float64(0.030328153201263246), 'Pcv': np.float64(2.4522498303729083), 'Wbcc': np.float64(0.48548285140559855), 'Rbcc': np.float64(1.7445496211520104), 'Htn': np.float64(0.27982899287233304), 'Dm': np.float64(0.055905834664164676), 'Cad': np.float64(0.37993727789559056), 'Appet': np.float64(0.37993727789559056), 'Pe': np.float64(1.264034181960229), 'Ane': np.float64(0.8978308752527827)}

Normalized Mathematical Scores
{'Age': np.float64(0.019679500533092743), 'Bp': np.float64(1.0), 'Sg': np.float64(0.05993993558007728), 'Al': np.float64(0.01706159409330873), 'Su': np.float64(0.1604331293435716), 'Rbc': np.float64(0.0030347240528150023), 'Pc': np.float64(0.04738202991297126), 'Pcc': np.float64(0.00038203957386581455), 'Ba': np.float64(0.05040304966798535), 'Bgr': np.float64(0.17174997364818242), 'Bu': np.float64(0.16662097487205388), 'Sc': np.float64(0.174040489220143), 'Sod': np.float64(0.11377530284890879), 'Pot': np.float64(0.5652113982814813), 'Hemo': np.float64(0.003782228135514332), 'Pcv': np.float64(0.3058204118858228), 'Wbcc': np.float64(0.060544632827148066), 'Rbcc': np.float64(0.21756302195964794), 'Htn': np.float64(0.03489751198995834), 'Dm': np.float64(0.006972024290533084), 'Cad': np.float64(0.04738202991297126), 'Appet': np.float64(0.04738202991297126), 'Pe': np.float64(0.15763787578937333), 'Ane': np.float64(0.11196861130248739)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.027692895339954164, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.02921395544346364, 'Su': 0.029411764705882353, 'Rbc': 0.027051561365286855, 'Pc': 0.02782608695652174, 'Pcc': 0.026279628993473032, 'Ba': 0.027598020555767037, 'Bgr': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Sc': 0.03177805800756621, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.027884615384615386, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.029030910609857977, 'Dm': 0.028283227848101264, 'Cad': 0.02761904761904762, 'Appet': 0.027417840375586856, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Sc', 'Bu', 'Pot', 'Pcv', 'Rbcc', 'Bgr', 'Sg', 'Pe', 'Su', 'Ane', 'Al', 'Sod', 'Htn', 'Dm', 'Wbcc', 'Hemo', 'Pc', 'Age', 'Cad']

Run 25/25
Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889181580>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}

Normalized Mathematical Scores
{'Age': np.float64(0.03540567579353816), 'Bp': np.float64(1.0), 'Sg': np.float64(0.42962387200428076), 'Al': np.float64(0.07303601394085876), 'Su': np.float64(0.3797419108094781), 'Rbc': np.float64(0.0021459773855491424), 'Pc': np.float64(0.00402437674075237), 'Pcc': np.float64(0.0021459773855491424), 'Ba': np.float64(0.1175434062731789), 'Bgr': np.float64(0.04344792359120419), 'Bu': np.float64(0.37367196668691655), 'Sc': np.float64(0.11855652445919955), 'Sod': np.float64(0.006014983394301805), 'Pot': np.float64(0.07510598422355698), 'Hemo': np.float64(0.049352544463869524), 'Pcv': np.float64(0.11790987715711101), 'Wbcc': np.float64(0.01501801795777131), 'Rbcc': np.float64(0.2826770532331541), 'Htn': np.float64(0.01536570643284562), 'Dm': np.float64(0.0043587568611444995), 'Cad': np.float64(0.018700527732724057), 'Appet': np.float64(0.07961827446569378), 'Pe': np.float64(0.028285417037785764), 'Ane': np.float64(0.1561401318634232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.026754075124025514, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Ba': 0.028577260665441927, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.027425373134328357, 'Pot': 0.02900988017658188, 'Hemo': 0.029083245521601686, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030090497737556562, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.027272727272727275, 'Appet': 0.028370221327967807, 'Pe': 0.028083267871170464, 'Ane': 0.030303030303030304}
Top 5 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58809c1d90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}

Normalized Mathematical Scores
{'Age': np.float64(0.03540567579353816), 'Bp': np.float64(1.0), 'Sg': np.float64(0.42962387200428076), 'Al': np.float64(0.07303601394085876), 'Su': np.float64(0.3797419108094781), 'Rbc': np.float64(0.0021459773855491424), 'Pc': np.float64(0.00402437674075237), 'Pcc': np.float64(0.0021459773855491424), 'Ba': np.float64(0.1175434062731789), 'Bgr': np.float64(0.04344792359120419), 'Bu': np.float64(0.37367196668691655), 'Sc': np.float64(0.11855652445919955), 'Sod': np.float64(0.006014983394301805), 'Pot': np.float64(0.07510598422355698), 'Hemo': np.float64(0.049352544463869524), 'Pcv': np.float64(0.11790987715711101), 'Wbcc': np.float64(0.01501801795777131), 'Rbcc': np.float64(0.2826770532331541), 'Htn': np.float64(0.01536570643284562), 'Dm': np.float64(0.0043587568611444995), 'Cad': np.float64(0.018700527732724057), 'Appet': np.float64(0.07961827446569378), 'Pe': np.float64(0.028285417037785764), 'Ane': np.float64(0.1561401318634232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.026754075124025514, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Ba': 0.028577260665441927, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.027425373134328357, 'Pot': 0.02900988017658188, 'Hemo': 0.029083245521601686, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030090497737556562, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.027272727272727275, 'Appet': 0.028370221327967807, 'Pe': 0.028083267871170464, 'Ane': 0.030303030303030304}
Top 10 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Ane', 'Al', 'Rbcc', 'Pcv', 'Hemo']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f5889149040>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}

Normalized Mathematical Scores
{'Age': np.float64(0.03540567579353816), 'Bp': np.float64(1.0), 'Sg': np.float64(0.42962387200428076), 'Al': np.float64(0.07303601394085876), 'Su': np.float64(0.3797419108094781), 'Rbc': np.float64(0.0021459773855491424), 'Pc': np.float64(0.00402437674075237), 'Pcc': np.float64(0.0021459773855491424), 'Ba': np.float64(0.1175434062731789), 'Bgr': np.float64(0.04344792359120419), 'Bu': np.float64(0.37367196668691655), 'Sc': np.float64(0.11855652445919955), 'Sod': np.float64(0.006014983394301805), 'Pot': np.float64(0.07510598422355698), 'Hemo': np.float64(0.049352544463869524), 'Pcv': np.float64(0.11790987715711101), 'Wbcc': np.float64(0.01501801795777131), 'Rbcc': np.float64(0.2826770532331541), 'Htn': np.float64(0.01536570643284562), 'Dm': np.float64(0.0043587568611444995), 'Cad': np.float64(0.018700527732724057), 'Appet': np.float64(0.07961827446569378), 'Pe': np.float64(0.028285417037785764), 'Ane': np.float64(0.1561401318634232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.026754075124025514, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Ba': 0.028577260665441927, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.027425373134328357, 'Pot': 0.02900988017658188, 'Hemo': 0.029083245521601686, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030090497737556562, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.027272727272727275, 'Appet': 0.028370221327967807, 'Pe': 0.028083267871170464, 'Ane': 0.030303030303030304}
Top 15 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Ane', 'Al', 'Rbcc', 'Pcv', 'Hemo', 'Pot', 'Htn', 'Bgr', 'Ba', 'Appet']

Provider inside knowledge engine: <__main__.NestedJSONProvider object at 0x7f58891490a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.30476586839344877), 'Bp': np.float64(8.607825202112682), 'Sg': np.float64(3.6981271928676813), 'Al': np.float64(0.6286812414619772), 'Su': np.float64(3.268751990164252), 'Rbc': np.float64(0.018472198222493793), 'Pc': np.float64(0.034641131531844345), 'Pcc': np.float64(0.018472198222493793), 'Ba': np.float64(1.0117930948604392), 'Bgr': np.float64(0.37399213166783357), 'Bu': np.float64(3.216502972170651), 'Sc': np.float64(1.0205138391147865), 'Sod': np.float64(0.05177592565176037), 'Pot': np.float64(0.6464991838290113), 'Hemo': np.float64(0.42481807602448285), 'Pcv': np.float64(1.0149476121709906), 'Wbcc': np.float64(0.12927247346268472), 'Rbcc': np.float64(2.4332346628792925), 'Htn': np.float64(0.1322653150809135), 'Dm': np.float64(0.03751941715924119), 'Cad': np.float64(0.16097087391054926), 'Appet': np.float64(0.6853401894945236), 'Pe': np.float64(0.24347592563011974), 'Ane': np.float64(1.3440269621151717)}

Normalized Mathematical Scores
{'Age': np.float64(0.03540567579353816), 'Bp': np.float64(1.0), 'Sg': np.float64(0.42962387200428076), 'Al': np.float64(0.07303601394085876), 'Su': np.float64(0.3797419108094781), 'Rbc': np.float64(0.0021459773855491424), 'Pc': np.float64(0.00402437674075237), 'Pcc': np.float64(0.0021459773855491424), 'Ba': np.float64(0.1175434062731789), 'Bgr': np.float64(0.04344792359120419), 'Bu': np.float64(0.37367196668691655), 'Sc': np.float64(0.11855652445919955), 'Sod': np.float64(0.006014983394301805), 'Pot': np.float64(0.07510598422355698), 'Hemo': np.float64(0.049352544463869524), 'Pcv': np.float64(0.11790987715711101), 'Wbcc': np.float64(0.01501801795777131), 'Rbcc': np.float64(0.2826770532331541), 'Htn': np.float64(0.01536570643284562), 'Dm': np.float64(0.0043587568611444995), 'Cad': np.float64(0.018700527732724057), 'Appet': np.float64(0.07961827446569378), 'Pe': np.float64(0.028285417037785764), 'Ane': np.float64(0.1561401318634232)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.026754075124025514, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Ba': 0.028577260665441927, 'Bgr': 0.028665028665028666, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.027425373134328357, 'Pot': 0.02900988017658188, 'Hemo': 0.029083245521601686, 'Pcv': 0.029857397504456328, 'Wbcc': 0.026742734890354787, 'Rbcc': 0.030090497737556562, 'Htn': 0.028693528693528692, 'Dm': 0.02797067901234568, 'Cad': 0.027272727272727275, 'Appet': 0.028370221327967807, 'Pe': 0.028083267871170464, 'Ane': 0.030303030303030304}
Top 20 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Ane', 'Al', 'Rbcc', 'Pcv', 'Hemo', 'Pot', 'Htn', 'Bgr', 'Ba', 'Appet', 'Pe', 'Age', 'Dm', 'Sod', 'Cad']

Completed.
Rows generated: 600

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,ANOVA,5,Logistic Regression,0.525253,0.530973,0.594059,0.560748,0.524497,"Bp, Sg, Rbcc, Su, Ba"
1,1,ANOVA,5,Random Forest,0.510101,0.518868,0.544554,0.531401,0.503062,"Bp, Sg, Rbcc, Su, Ba"
2,1,ANOVA,5,XGBoost,0.515152,0.524752,0.524752,0.524752,0.499898,"Bp, Sg, Rbcc, Su, Ba"
3,1,DODA,5,Logistic Regression,0.500000,0.509615,0.524752,0.517073,0.518322,"Bp, Sg, Sc, Rbcc, Su"
4,1,DODA,5,Random Forest,0.525253,0.535354,0.524752,0.530000,0.539145,"Bp, Sg, Sc, Rbcc, Su"

In [25]:
# =============================================================================
# STEP 23: CV PERFORMANCE SUMMARY
# =============================================================================

cv_summary_df = (
    cv_results_df
    .groupby(["Method", "Top_K", "Model"])
    [["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]]
    .agg(["mean", "std"])
    .reset_index()
)

cv_summary_df.columns = [
    "Method", "Top_K", "Model",
    "Accuracy_Mean", "Accuracy_STD",
    "Precision_Mean", "Precision_STD",
    "Recall_Mean", "Recall_STD",
    "F1_Mean", "F1_STD",
    "ROC_AUC_Mean", "ROC_AUC_STD"
]

display(cv_summary_df.round(4))

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,ANOVA,5,Logistic Regression,0.5170,0.0341,0.5264,0.0294,0.5823,0.0507,0.5525,0.0360,0.5191,0.0356
1,ANOVA,5,Random Forest,0.5093,0.0293,0.5216,0.0296,0.5289,0.0503,0.5244,0.0353,0.5049,0.0368
2,ANOVA,5,XGBoost,0.5042,0.0372,0.5157,0.0366,0.5400,0.0551,0.5270,0.0433,0.4977,0.0422
3,ANOVA,10,Logistic Regression,0.5180,0.0380,0.5284,0.0345,0.5657,0.0532,0.5458,0.0399,0.5216,0.0389
4,ANOVA,10,Random Forest,0.4976,0.0307,0.5108,0.0316,0.5306,0.0409,0.5198,0.0300,0.4929,0.0460
5,ANOVA,10,XGBoost,0.5049,0.0329,0.5165,0.0317,0.5409,0.0570,0.5276,0.0403,0.4962,0.0396
6,ANOVA,15,Logistic Regression,0.5204,0.0282,0.5307,0.0262,0.5613,0.0511,0.5449,0.0345,0.5221,0.0357
7,ANOVA,15,Random Forest,0.5061,0.0365,0.5185,0.0341,0.5487,0.0458,0.5324,0.0344,0.5079,0.0402
8,ANOVA,15,XGBoost,0.5087,0.0397,0.5203,0.0367,0.5444,0.0546,0.5315,0.0421,0.5119,0.0472
9,ANOVA,20,Logistic Regression,0.5162,0.0328,0.5269,0.0306,0.5578,0.0493,0.5414,0.0363,0.5207,0.0339
10,ANOVA,20,Random Forest,0.5207,0.0346,0.5307,0.0314,0.5688,0.0525,0.5485,0.0373,0.5225,0.0344
11,ANOVA,20,XGBoost,0.5202,0.0413,0.5312,0.0378,0.5570,0.0572,0.5430,0.0426,0.5307,0.0404
12,DODA,5,Logistic Regression,0.5150,0.0311,0.5242,0.0266,0.5814,0.0575,0.5507,0.0379,0.5161,0.0321
13,DODA,5,Random Forest,0.5026,0.0404,0.5153,0.0395,0.5242,0.0537,0.5190,0.0431,0.4977,0.0456
14,DODA,5,XGBoost,0.5065,0.0398,0.5177,0.0372,0.5325,0.0649,0.5242,0.0489,0.4976,0.0452
15,DODA,10,Logistic Regression,0.5156,0.0312,0.5260,0.0282,0.5633,0.0463,0.5436,0.0339,0.5204,0.0334
16,DODA,10,Random Forest,0.4986,0.0406,0.5116,0.0392,0.5266,0.0507,0.5183,0.0409,0.4993,0.0415
17,DODA,10,XGBoost,0.5083,0.0243,0.5200,0.0226,0.5420,0.0473,0.5301,0.0310,0.5044,0.0406
18,DODA,15,Logistic Regression,0.5223,0.0308,0.5323,0.0284,0.5645,0.0460,0.5476,0.0344,0.5250,0.0353
19,DODA,15,Random Forest,0.5127,0.0324,0.5249,0.0306,0.5483,0.0388,0.5358,0.0296,0.5136,0.0405
20,DODA,15,XGBoost,0.5146,0.0385,0.5261,0.0352,0.5499,0.0534,0.5370,0.0397,0.5152,0.0461
21,DODA,20,Logistic Regression,0.5178,0.0315,0.5287,0.0300,0.5574,0.0453,0.5422,0.0340,0.5215,0.0350
22,DODA,20,Random Forest,0.5206,0.0343,0.5321,0.0323,0.5519,0.0481,0.5411,0.0352,0.5283,0.0363
23,DODA,20,XGBoost,0.5287,0.0348,0.5389,0.0310,0.5637,0.0547,0.5503,0.0388,0.5328,0.0426

In [26]:
# =============================================================================
# STEP 24: SAVE REPEATED-CV RESULTS
# =============================================================================

cv_dir = Path("../../../results/kidney_disease/cv")
cv_dir.mkdir(parents=True, exist_ok=True)

cv_results_df.to_csv(
    cv_dir / "anova_vs_doda_5x5_repeated_cv_results.csv",
    index=False
)

cv_summary_df.to_csv(
    cv_dir / "anova_vs_doda_5x5_repeated_cv_summary.csv",
    index=False
)

print(f"Saved to: {cv_dir.resolve()}")

Saved to: /home/claude/bd_kdd_final/results/kidney_disease/cv

# 4. Feature-set Stability and Rank/Set Change

Two different concepts are reported:

- **Feature-set change:** whether the Top-K membership changes.
- **Rank change:** whether feature ordering changes even when membership is retained.

Jaccard similarity evaluates set overlap, so it does not measure ordering. The fixed-split DODA rank comparison is used to inspect ordering changes.

In [27]:
# =============================================================================
# STEP 25: FEATURE-SET COMPARISON ACROSS THE 25 CV RUNS
# =============================================================================

feature_comparison_rows = []

for run_id in range(1, 26):

    for top_k in TOP_K_VALUES:

        anova_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "ANOVA") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        doda_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        anova_set = set(
            anova_row["Selected_Features"].split(", ")
        )
        doda_set = set(
            doda_row["Selected_Features"].split(", ")
        )

        overlap = len(anova_set & doda_set)
        union = len(anova_set | doda_set)

        feature_comparison_rows.append({
            "Run": run_id,
            "Top_K": top_k,
            "Same_Feature_Set": anova_set == doda_set,
            "Overlap_Count": overlap,
            "Jaccard": overlap / union,
            "Features_Changed": top_k - overlap
        })

feature_comparison_df = pd.DataFrame(
    feature_comparison_rows
)

display(
    feature_comparison_df
    .groupby("Top_K")
    [["Same_Feature_Set", "Overlap_Count", "Jaccard", "Features_Changed"]]
    .agg(["mean", "std"])
    .round(4)
)

      Same_Feature_Set         Overlap_Count         Jaccard          \
                  mean     std          mean     std    mean     std
Top_K
5                 0.04  0.2000          3.60  0.6455  0.5776  0.1577
10                0.00  0.0000          8.52  0.5859  0.7464  0.0863
15                0.16  0.3742         13.40  0.9574  0.8131  0.1069
20                0.00  0.0000         18.32  0.8021  0.8474  0.0669

      Features_Changed
                  mean     std
Top_K
5                 1.40  0.6455
10                1.48  0.5859
15                1.60  0.9574
20                1.68  0.8021

In [28]:
# =============================================================================
# STEP 26: FEATURE-SELECTION STABILITY
# =============================================================================

from itertools import combinations

stability_rows = []

for method in ["ANOVA", "DODA"]:

    for top_k in TOP_K_VALUES:

        subset = cv_results_df[
            (cv_results_df["Method"] == method) &
            (cv_results_df["Top_K"] == top_k)
        ]

        # One feature set per run; model does not affect selection.
        run_sets = {}

        for run_id in range(1, 26):
            row = subset[
                subset["Run"] == run_id
            ].iloc[0]

            run_sets[run_id] = set(
                row["Selected_Features"].split(", ")
            )

        pairwise_jaccards = []

        for a, b in combinations(range(1, 26), 2):

            set_a = run_sets[a]
            set_b = run_sets[b]

            pairwise_jaccards.append(
                len(set_a & set_b) / len(set_a | set_b)
            )

        stability_rows.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Jaccard": np.mean(pairwise_jaccards),
            "SD_Jaccard": np.std(pairwise_jaccards, ddof=1),
            "Min_Jaccard": np.min(pairwise_jaccards),
            "Max_Jaccard": np.max(pairwise_jaccards)
        })

stability_df = pd.DataFrame(stability_rows)

display(stability_df.round(4))

  Method  Top_K  Mean_Jaccard  SD_Jaccard  Min_Jaccard  Max_Jaccard
0  ANOVA      5        0.4218      0.1710       0.1111       1.0000
1  ANOVA     10        0.5030      0.1192       0.2500       0.8182
2  ANOVA     15        0.6260      0.1043       0.3636       1.0000
3  ANOVA     20        0.7676      0.0618       0.6667       0.9048
4   DODA      5        0.3910      0.1674       0.1111       1.0000
5   DODA     10        0.5177      0.1259       0.2500       1.0000
6   DODA     15        0.6534      0.1080       0.4286       0.8750
7   DODA     20        0.8245      0.0676       0.6667       1.0000

In [29]:
# =============================================================================
# STEP 27: PAIRED STATISTICAL COMPARISON OF PREDICTIVE PERFORMANCE
# =============================================================================

from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

metrics = ["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]

comparison_rows = []

for top_k in TOP_K_VALUES:

    for model_name in models.keys():

        anova = cv_results_df[
            (cv_results_df["Method"] == "ANOVA") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        doda = cv_results_df[
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        assert len(anova) == 25
        assert len(doda) == 25
        assert (anova["Run"].values == doda["Run"].values).all()

        for metric in metrics:

            anova_values = anova[metric].to_numpy()
            doda_values = doda[metric].to_numpy()

            differences = doda_values - anova_values

            mean_difference = np.mean(differences)
            sd_difference = np.std(differences, ddof=1)

            if np.allclose(differences, 0):
                statistic = 0.0
                p_value = 1.0
            else:
                statistic, p_value = wilcoxon(
                    doda_values,
                    anova_values,
                    alternative="two-sided"
                )

            paired_d = (
                mean_difference / sd_difference
                if sd_difference > 0 else 0.0
            )

            comparison_rows.append({
                "Top_K": top_k,
                "Model": model_name,
                "Metric": metric,
                "ANOVA_Mean": np.mean(anova_values),
                "DODA_Mean": np.mean(doda_values),
                "Mean_Difference_DODA_minus_ANOVA": mean_difference,
                "Paired_SD": sd_difference,
                "Paired_Cohens_d": paired_d,
                "Wilcoxon_Statistic": statistic,
                "P_Value": p_value
            })

performance_comparison_df = pd.DataFrame(comparison_rows)

reject, adjusted_p, _, _ = multipletests(
    performance_comparison_df["P_Value"],
    alpha=0.05,
    method="holm"
)

performance_comparison_df["Holm_Adjusted_P"] = adjusted_p
performance_comparison_df["Significant"] = reject

display(performance_comparison_df.round(4))

,Top_K,Model,Metric,ANOVA_Mean,DODA_Mean,Mean_Difference_DODA_minus_ANOVA,Paired_SD,Paired_Cohens_d,Wilcoxon_Statistic,P_Value,Holm_Adjusted_P,Significant
0,5,Logistic Regression,Accuracy,0.5170,0.5150,-0.0020,0.0269,-0.0754,112.0,0.6377,1.0,False
1,5,Logistic Regression,Precision,0.5264,0.5242,-0.0022,0.0236,-0.0938,130.0,0.5677,1.0,False
2,5,Logistic Regression,Recall,0.5823,0.5814,-0.0009,0.0543,-0.0158,113.0,0.6611,1.0,False
3,5,Logistic Regression,F1,0.5525,0.5507,-0.0018,0.0350,-0.0513,149.0,0.9772,1.0,False
4,5,Logistic Regression,ROC_AUC,0.5191,0.5161,-0.0030,0.0148,-0.2034,129.0,0.5485,1.0,False
5,5,Random Forest,Accuracy,0.5093,0.5026,-0.0067,0.0354,-0.1886,131.0,0.5869,1.0,False
6,5,Random Forest,Precision,0.5216,0.5153,-0.0064,0.0341,-0.1864,143.0,0.6150,1.0,False
7,5,Random Forest,Recall,0.5289,0.5242,-0.0047,0.0528,-0.0896,114.5,0.6967,1.0,False
8,5,Random Forest,F1,0.5244,0.5190,-0.0055,0.0382,-0.1429,148.0,0.7112,1.0,False
9,5,Random Forest,ROC_AUC,0.5049,0.4977,-0.0072,0.0331,-0.2189,133.0,0.4418,1.0,False
10,5,XGBoost,Accuracy,0.5042,0.5065,0.0022,0.0331,0.0674,112.0,0.6377,1.0,False
11,5,XGBoost,Precision,0.5157,0.5177,0.0020,0.0303,0.0651,127.0,0.5111,1.0,False
12,5,XGBoost,Recall,0.5400,0.5325,-0.0075,0.0544,-0.1375,123.0,0.6482,1.0,False
13,5,XGBoost,F1,0.5270,0.5242,-0.0029,0.0395,-0.0721,149.0,0.9772,1.0,False
14,5,XGBoost,ROC_AUC,0.4977,0.4976,-0.0000,0.0300,-0.0016,147.0,0.6915,1.0,False
15,10,Logistic Regression,Accuracy,0.5180,0.5156,-0.0024,0.0203,-0.1197,112.5,0.6490,1.0,False
16,10,Logistic Regression,Precision,0.5284,0.5260,-0.0023,0.0184,-0.1265,140.0,0.5602,1.0,False
17,10,Logistic Regression,Recall,0.5657,0.5633,-0.0024,0.0293,-0.0816,123.5,0.9222,1.0,False
18,10,Logistic Regression,F1,0.5458,0.5436,-0.0022,0.0207,-0.1063,162.0,1.0000,1.0,False
19,10,Logistic Regression,ROC_AUC,0.5216,0.5204,-0.0012,0.0152,-0.0770,159.0,0.9368,1.0,False
20,10,Random Forest,Accuracy,0.4976,0.4986,0.0010,0.0237,0.0425,147.5,0.6862,1.0,False
21,10,Random Forest,Precision,0.5108,0.5116,0.0008,0.0220,0.0348,151.0,0.7712,1.0,False
22,10,Random Forest,Recall,0.5306,0.5266,-0.0040,0.0507,-0.0784,109.0,0.8212,1.0,False
23,10,Random Forest,F1,0.5198,0.5183,-0.0015,0.0337,-0.0450,148.0,0.7112,1.0,False
24,10,Random Forest,ROC_AUC,0.4929,0.4993,0.0064,0.0231,0.2769,102.0,0.1073,1.0,False
25,10,XGBoost,Accuracy,0.5049,0.5083,0.0034,0.0258,0.1337,105.5,0.4953,1.0,False
26,10,XGBoost,Precision,0.5165,0.5200,0.0035,0.0256,0.1358,134.0,0.6476,1.0,False
27,10,XGBoost,Recall,0.5409,0.5420,0.0012,0.0397,0.0294,109.5,0.8347,1.0,False
28,10,XGBoost,F1,0.5276,0.5301,0.0025,0.0277,0.0913,148.0,0.9544,1.0,False
29,10,XGBoost,ROC_AUC,0.4962,0.5044,0.0082,0.0194,0.4236,98.0,0.0851,1.0,False
30,15,Logistic Regression,Accuracy,0.5204,0.5223,0.0018,0.0152,0.1196,75.0,0.9433,1.0,False
31,15,Logistic Regression,Precision,0.5307,0.5323,0.0016,0.0134,0.1186,83.0,0.9133,1.0,False
32,15,Logistic Regression,Recall,0.5613,0.5645,0.0032,0.0283,0.1124,37.5,0.5754,1.0,False
33,15,Logistic Regression,F1,0.5449,0.5476,0.0026,0.0193,0.1358,78.0,0.7439,1.0,False
34,15,Logistic Regression,ROC_AUC,0.5221,0.5250,0.0029,0.0087,0.3388,67.0,0.0918,1.0,False
35,15,Random Forest,Accuracy,0.5061,0.5127,0.0067,0.0198,0.3366,93.5,0.1756,1.0,False
36,15,Random Forest,Precision,0.5185,0.5249,0.0064,0.0206,0.3106,106.0,0.2087,1.0,False
37,15,Random Forest,Recall,0.5487,0.5483,-0.0004,0.0361,-0.0119,99.5,0.5778,1.0,False
38,15,Random Forest,F1,0.5324,0.5358,0.0033,0.0213,0.1567,130.0,0.5677,1.0,False
39,15,Random Forest,ROC_AUC,0.5079,0.5136,0.0057,0.0244,0.2342,129.0,0.3810,1.0,False
40,15,XGBoost,Accuracy,0.5087,0.5146,0.0059,0.0271,0.2172,117.5,0.2258,1.0,False
41,15,XGBoost,Precision,0.5203,0.5261,0.0058,0.0256,0.2273,122.0,0.2872,1.0,False
42,15,XGBoost,Recall,0.5444,0.5499,0.0056,0.0430,0.1290,126.0,0.4923,1.0,False
43,15,XGBoost,F1,0.5315,0.5370,0.0055,0.0298,0.1862,135.0,0.4742,1.0,False
44,15,XGBoost,ROC_AUC,0.5119,0.5152,0.0033,0.0266,0.1245,146.0,0.6571,1.0,False
45,20,Logistic Regression,Accuracy,0.5162,0.5178,0.0016,0.0128,0.1264,78.0,0.4935,1.0,False
46,20,Logistic Regression,Precision,0.5269,0.5287,0.0018,0.0115,0.1527,116.0,0.5034,1.0,False
47,20,Logistic Regression,Recall,0.5578,0.5574,-0.0004,0.0190,-0.0194,88.5,0.7930,1.0,False
48,20,Logistic Regression,F1,0.5414,0.5422,0.0008,0.0137,0.0580,137.0,0.9757,1.0,False
49,20,Logistic Regression,ROC_AUC,0.5207,0.5215,0.0008,0.0064,0.1274,113.0,0.1908,1.0,False
50,20,Random Forest,Accuracy,0.5207,0.5206,-0.0000,0.0286,-0.0010,111.5,0.6261,1.0,False
51,20,Random Forest,Precision,0.5307,0.5321,0.0014,0.0266,0.0517,154.0,0.8325,1.0,False
52,20,Random Forest,Recall,0.5688,0.5519,-0.0170,0.0353,-0.4808,55.5,0.0211,1.0,False
53,20,Random Forest,F1,0.5485,0.5411,-0.0074,0.0277,-0.2657,102.0,0.1073,1.0,False
54,20,Random Forest,ROC_AUC,0.5225,0.5283,0.0058,0.0195,0.2957,110.0,0.1645,1.0,False
55,20,XGBoost,Accuracy,0.5202,0.5287,0.0085,0.0255,0.3338,89.0,0.1360,1.0,False
56,20,XGBoost,Precision,0.5312,0.5389,0.0077,0.0246,0.3108,102.0,0.1702,1.0,False
57,20,XGBoost,Recall,0.5570,0.5637,0.0067,0.0413,0.1624,86.5,0.1939,1.0,False
58,20,XGBoost,F1,0.5430,0.5503,0.0073,0.0288,0.2534,100.0,0.1531,1.0,False
59,20,XGBoost,ROC_AUC,0.5307,0.5328,0.0021,0.0206,0.1024,139.0,0.5424,1.0,False

In [30]:
# =============================================================================
# STEP 28: SAVE STATISTICAL RESULTS
# =============================================================================

stats_dir = Path("../../../results/kidney_disease/statistics")
stats_dir.mkdir(parents=True, exist_ok=True)

feature_comparison_df.to_csv(
    stats_dir / "feature_set_comparison_5x5.csv",
    index=False
)

stability_df.to_csv(
    stats_dir / "feature_selection_stability_5x5.csv",
    index=False
)

performance_comparison_df.to_csv(
    stats_dir / "anova_vs_doda_predictive_statistics_5x5.csv",
    index=False
)

print(f"Saved statistical outputs to: {stats_dir.resolve()}")

Saved statistical outputs to: /home/claude/bd_kdd_final/results/kidney_disease/statistics

In [31]:
# =============================================================================
# STEP 29: FINAL SANITY CHECKS
# =============================================================================

print("=" * 70)
print("FINAL EXPERIMENT SANITY CHECK")
print("=" * 70)

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")
print(f"Missing values: {int(X.isna().sum().sum())}")
print(f"CV result rows: {len(cv_results_df)}")
print(f"Expected CV rows: {25 * len(TOP_K_VALUES) * 2 * len(models)}")

assert X.shape[1] == 24
assert X.isna().sum().sum() == 0
assert TOP_K_VALUES == [5, 10, 15, 20]
assert len(cv_results_df) == 25 * len(TOP_K_VALUES) * 2 * len(models)

for top_k in TOP_K_VALUES:
    assert len(anova_results[top_k]["features"]) == top_k
    assert len(rank_doda_results[top_k]["features"]) == top_k

print("All sanity checks passed.")

======================================================================
FINAL EXPERIMENT SANITY CHECK
======================================================================
Total predictors: 24
Top-K values: [5, 10, 15, 20]
Missing values: 0
CV result rows: 600
Expected CV rows: 600
All sanity checks passed.

# Methodological corrections made in this final version

### 1. Correct predictor count
BD-KDD has **25 processed columns**, but one is the binary target `Class`. Therefore the feature matrix contains **24 predictors**.

### 2. Top-K values
The experiment uses:

**Top-5, Top-10, Top-15, Top-20**

This provides approximately 20%, 40%, 60%, and 80% feature budgets over the 24 predictors. Top-24 is deliberately not used as a selection condition because retaining every feature cannot demonstrate feature-selection behavior.

### 3. Removed imputation
BD-KDD has zero missing values, so no imputation is performed.

### 4. Correct DODA architecture
ANOVA is configured with `k="all"` inside DODA. DODA receives all 24 statistical scores and performs the final Top-K selection.

### 5. No data leakage in CV
ANOVA and DODA are refit inside every training fold. Validation-fold data is never used to calculate feature-selection scores.

### 6. Model-specific scaling
Scaling is applied only to Logistic Regression and is fitted on the training data/fold. Random Forest and XGBoost use the selected features without scaling.

### 7. Consistent result paths
All outputs are stored under:

```text
results/
└── kidney_disease/
    ├── baseline/
    ├── doda/
    ├── cv/
    └── statistics/
```

### 8. Fixed split and repeated CV are separated
The fixed 80/20 experiment is an initial reproducible comparison. The 5×5 repeated stratified CV is the robustness analysis.

### 9. Feature-set change and rank change are separated
Jaccard measures feature-set overlap. DODA's rank-comparison output is retained separately because a feature can change rank without entering or leaving Top-K.

### 10. Clinical weights remain external
The clinical weights are loaded from the pre-specified JSON and are not derived from ANOVA scores, target correlations, model performance, or test-fold information.

## Interpretation rule

Do not assume that DODA must improve predictive performance.

The experiment should answer three separate questions:

1. **Does DODA change feature prioritization?**
2. **How stable are ANOVA and DODA selections across repeated folds?**
3. **What happens to predictive performance when the feature priorities are changed?**

If DODA changes the selected features while predictive performance remains similar, that is a different finding from DODA improving predictive performance.

All conclusions should be based on the generated results rather than predetermined expectations.