# BD-KDD Kidney Disease — LASSO + DODA Feature Selection

## Experimental objective

Evaluate conventional **LASSO feature selection** against **LASSO + DODA clinical-priority re-ranking** on the BD-KDD kidney-disease dataset.

### Important design rule

LASSO scores **all 24 predictors**. DODA also receives **all 24 predictor scores** and performs the final Top-K selection after clinical-priority fusion.

This is essential: if LASSO selected Top-K before DODA, DODA could not re-prioritize features outside that preliminary Top-K.

### Dataset

- 988 records
- 24 predictors
- Binary target: `Class`
- `Class = 0`: healthy
- `Class = 1`: kidney disease
- 0 missing values
- 80/20 stratified fixed split for the initial experiment
- 5×5 repeated stratified CV for robustness

In [3]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("../../data/processed/BD-KDD_cleaned.csv")

if not DATA_PATH.is_file():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH.resolve()}"
    )

df = pd.read_csv(DATA_PATH)

print("=" * 70)
print("PROCESSED BD-KDD DATASET")
print("=" * 70)
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

display(df.head())

======================================================================
PROCESSED BD-KDD DATASET
======================================================================
Rows    : 988
Columns : 25

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane,Class
0,58,147,1.025,1,3,0,1,0,0,177,...,43,12342,4.3,1,0,0,1,1,0,0
1,71,142,1.025,2,3,1,0,1,0,247,...,47,7249,3.7,0,1,1,0,1,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,37,4111,3.7,0,0,0,0,0,1,0
3,34,70,1.005,1,3,1,1,0,0,215,...,44,4682,4.0,1,0,1,1,0,1,1
4,62,120,1.020,4,0,1,0,1,0,143,...,54,5161,4.7,0,0,1,0,1,0,1

In [4]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

TARGET_COLUMN = "Class"

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

print("=" * 70)
print("FEATURE / TARGET SEPARATION")
print("=" * 70)
print(f"Predictors (X) : {X.shape[1]}")
print(f"Records        : {X.shape[0]}")
print(f"Target (y)     : {TARGET_COLUMN}")
print(f"Target values  : {sorted(y.unique().tolist())}")

assert X.shape[1] == 24, "Expected 24 predictors after removing Class."
assert set(y.unique()) == {0, 1}

display(X.head())
display(y.head())

======================================================================
FEATURE / TARGET SEPARATION
======================================================================
Predictors (X) : 24
Records        : 988
Target (y)     : Class
Target values  : [0, 1]

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Hemo,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane
0,58,147,1.025,1,3,0,1,0,0,177,...,9.3,43,12342,4.3,1,0,0,1,1,0
1,71,142,1.025,2,3,1,0,1,0,247,...,16.9,47,7249,3.7,0,1,1,0,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,16.6,37,4111,3.7,0,0,0,0,0,1
3,34,70,1.005,1,3,1,1,0,0,215,...,15.4,44,4682,4.0,1,0,1,1,0,1
4,62,120,1.020,4,0,1,0,1,0,143,...,13.9,54,5161,4.7,0,0,1,0,1,0

0    0
1    1
2    0
3    1
4    1
Name: Class, dtype: int64

In [5]:
# =============================================================================
# STEP 3: TARGET DISTRIBUTION
# =============================================================================

target_distribution = pd.DataFrame({
    "Count": y.value_counts().sort_index(),
    "Percentage": (y.value_counts(normalize=True).sort_index() * 100).round(2)
})

display(target_distribution)

       Count  Percentage
Class
0        481       48.68
1        507       51.32

In [6]:
# =============================================================================
# STEP 4: DATA TYPE AND MISSING-VALUE CHECK
# =============================================================================

print("=" * 70)
print("DATA TYPES")
print("=" * 70)
display(X.dtypes.to_frame("Data Type"))

missing = pd.DataFrame({
    "Missing Count": X.isna().sum(),
    "Missing Percentage (%)": (X.isna().mean() * 100).round(2)
})

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)
display(missing)

assert X.isna().sum().sum() == 0, "Unexpected missing values detected."

print("No missing values detected. No imputation will be performed.")

======================================================================
DATA TYPES
======================================================================

      Data Type
Age       int64
Bp        int64
Sg      float64
Al        int64
Su        int64
Rbc       int64
Pc        int64
Pcc       int64
Ba        int64
Bgr       int64
Bu        int64
Sc      float64
Sod       int64
Pot     float64
Hemo    float64
Pcv       int64
Wbcc      int64
Rbcc    float64
Htn       int64
Dm        int64
Cad       int64
Appet     int64
Pe        int64
Ane       int64

======================================================================
MISSING VALUES
======================================================================

       Missing Count  Missing Percentage (%)
Age                0                     0.0
Bp                 0                     0.0
Sg                 0                     0.0
Al                 0                     0.0
Su                 0                     0.0
Rbc                0                     0.0
Pc                 0                     0.0
Pcc                0                     0.0
Ba                 0                     0.0
Bgr                0                     0.0
Bu                 0                     0.0
Sc                 0                     0.0
Sod                0                     0.0
Pot                0                     0.0
Hemo               0                     0.0
Pcv                0                     0.0
Wbcc               0                     0.0
Rbcc               0                     0.0
Htn                0                     0.0
Dm                 0                     0.0
Cad                0                     0.0
Appet              0                     0.0
Pe                 0                     0.0
Ane                0                     0.0

No missing values detected. No imputation will be performed.

## Preprocessing decision

The EDA established that BD-KDD contains **zero missing values**. Therefore, no imputation step is included in this notebook.

Feature selection is fitted only on training data/folds. Model scaling is applied only where needed and is fitted only on training data/folds.

In [7]:
# =============================================================================
# STEP 5: FIXED 80/20 STRATIFIED TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)
print(f"X_train : {X_train.shape}")
print(f"X_test  : {X_test.shape}")
print(f"y_train : {y_train.shape}")
print(f"y_test  : {y_test.shape}")

print("\nTraining class distribution:")
display((y_train.value_counts(normalize=True) * 100).round(2))

print("\nTesting class distribution:")
display((y_test.value_counts(normalize=True) * 100).round(2))

======================================================================
TRAIN-TEST SPLIT
======================================================================
X_train : (790, 24)
X_test  : (198, 24)
y_train : (790,)
y_test  : (198,)

Training class distribution:

Class
1    51.27
0    48.73
Name: proportion, dtype: float64

Testing class distribution:

Class
1    51.52
0    48.48
Name: proportion, dtype: float64

In [8]:
# =============================================================================
# STEP 6: FEATURE-SCALE CHECK
# =============================================================================
# LASSO F-statistics are scale-invariant, so feature selection is performed
# on the original training-fold values.
#
# Scaling is applied later only for Logistic Regression.

print("LASSO will be fitted on the original training data.")
print("Logistic Regression will be scaled after feature selection.")
print("Random Forest and XGBoost will use the selected features without scaling.")

LASSO will be fitted on the original training data.
Logistic Regression will be scaled after feature selection.
Random Forest and XGBoost will use the selected features without scaling.

# 1. LASSO Baseline

LASSO is used as the statistical feature-selection baseline.

**Important:** LASSO is fitted on all 24 predictors first. Feature importance is based on the absolute L1 coefficients, and Top-K is applied only after the complete ranking has been generated.

In [9]:
# =============================================================================
# STEP 7: LASSO SCORES FOR ALL FEATURES
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

lasso_scaler = StandardScaler()

X_train_lasso_scaled = pd.DataFrame(
    lasso_scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_lasso_scaled = pd.DataFrame(
    lasso_scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

lasso_selector = LogisticRegression(
    penalty="l1",
    solver="liblinear",
    C=0.1,
    max_iter=2000,
    class_weight="balanced",
    random_state=42
)

lasso_selector.fit(
    X_train_lasso_scaled,
    y_train
)

lasso_scores = pd.DataFrame({
    "Feature": X_train.columns,
    "LASSO_Coefficient": lasso_selector.coef_[0],
    "LASSO_Absolute_Coefficient": np.abs(lasso_selector.coef_[0])
}).sort_values(
    "LASSO_Absolute_Coefficient",
    ascending=False
).reset_index(drop=True)

lasso_scores["LASSO_Rank"] = np.arange(
    1,
    len(lasso_scores) + 1
)

display(lasso_scores)

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

   Feature  LASSO_Coefficient  LASSO_Absolute_Coefficient  LASSO_Rank
0       Bp          -0.162750                    0.162750           1
1       Bu           0.038219                    0.038219           2
2       Su          -0.033818                    0.033818           3
3       Ba          -0.033182                    0.033182           4
4      Ane           0.016304                    0.016304           5
5    Appet          -0.015208                    0.015208           6
6      Pcv          -0.007970                    0.007970           7
7      Bgr           0.006839                    0.006839           8
8       Sc           0.005209                    0.005209           9
9       Dm           0.002901                    0.002901          10
10      Sg           0.002503                    0.002503          11
11    Rbcc           0.001381                    0.001381          12
12     Age           0.000000                    0.000000          13
13      Pc           0.000000                    0.000000          14
14     Rbc           0.000000                    0.000000          15
15      Al           0.000000                    0.000000          16
16     Pcc           0.000000                    0.000000          17
17    Hemo           0.000000                    0.000000          18
18     Sod           0.000000                    0.000000          19
19     Pot           0.000000                    0.000000          20
20     Htn           0.000000                    0.000000          21
21    Wbcc           0.000000                    0.000000          22
22     Cad           0.000000                    0.000000          23
23      Pe           0.000000                    0.000000          24

In [10]:
# =============================================================================
# STEP 8: TOP-K LASSO FEATURE SETS
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")

lasso_results = {}

for top_k in TOP_K_VALUES:

    selected = (
        lasso_scores
        .head(top_k)["Feature"]
        .tolist()
    )

    lasso_results[top_k] = {
        "features": selected,
        "X_train": X_train[selected].copy(),
        "X_test": X_test[selected].copy()
    }

    print("=" * 70)
    print(f"LASSO TOP-{top_k}")
    print("=" * 70)
    print(selected)

Total predictors: 24
Top-K values: [5, 10, 15, 20]
======================================================================
LASSO TOP-5
======================================================================
['Bp', 'Bu', 'Su', 'Ba', 'Ane']
======================================================================
LASSO TOP-10
======================================================================
['Bp', 'Bu', 'Su', 'Ba', 'Ane', 'Appet', 'Pcv', 'Bgr', 'Sc', 'Dm']
======================================================================
LASSO TOP-15
======================================================================
['Bp', 'Bu', 'Su', 'Ba', 'Ane', 'Appet', 'Pcv', 'Bgr', 'Sc', 'Dm', 'Sg', 'Rbcc', 'Age', 'Pc', 'Rbc']
======================================================================
LASSO TOP-20
======================================================================
['Bp', 'Bu', 'Su', 'Ba', 'Ane', 'Appet', 'Pcv', 'Bgr', 'Sc', 'Dm', 'Sg', 'Rbcc', 'Age', 'Pc', 'Rbc', 'Al', 'Pcc', 'Hemo', 'Sod', 'Pot']

In [11]:
# =============================================================================
# STEP 9: DOWNSTREAM MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1
    )
}

print(list(models.keys()))

['Logistic Regression', 'Random Forest', 'XGBoost']

In [12]:
# =============================================================================
# STEP 10: LASSO BASELINE MODEL EVALUATION
# =============================================================================

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

fixed_lasso_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = lasso_results[top_k]["X_train"]
    Xte_selected = lasso_results[top_k]["X_test"]
    selected_features = lasso_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_lasso_rows.append({
            "Method": "LASSO",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_lasso_results_df = pd.DataFrame(fixed_lasso_rows)
display(fixed_lasso_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,LASSO,5,Logistic Regression,"Bp, Bu, Su, Ba, Ane",0.5303,0.5391,0.6078,0.5714,0.5587
1,LASSO,5,Random Forest,"Bp, Bu, Su, Ba, Ane",0.5354,0.5532,0.5098,0.5306,0.5628
2,LASSO,5,XGBoost,"Bp, Bu, Su, Ba, Ane",0.5455,0.5577,0.5686,0.5631,0.5288
3,LASSO,10,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5455,0.5517,0.6275,0.5872,0.5642
4,LASSO,10,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5505,0.5644,0.5588,0.5616,0.5575
5,LASSO,10,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5253,0.5385,0.5490,0.5437,0.5239
6,LASSO,15,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5758,0.5818,0.6275,0.6038,0.5774
7,LASSO,15,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5234,0.5490,0.5359,0.5283
8,LASSO,15,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.4545,0.4722,0.5000,0.4857,0.4861
9,LASSO,20,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5657,0.5755,0.5980,0.5865,0.5751
10,LASSO,20,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5243,0.5294,0.5268,0.5518
11,LASSO,20,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5248,0.5196,0.5222,0.5137

In [13]:
# =============================================================================
# STEP 11: SAVE LASSO BASELINE
# =============================================================================

baseline_dir = Path("../../../results/kidney_disease/baseline")
baseline_dir.mkdir(parents=True, exist_ok=True)

baseline_path = baseline_dir / "lasso_baseline_results.csv"
fixed_lasso_results_df.to_csv(baseline_path, index=False)

print(f"Saved: {baseline_path.resolve()}")

Saved: C:\Users\johnm\msc_research\results\kidney_disease\baseline\lasso_baseline_results.csv

# 2. DODA Clinical Re-ranking

### Correct experimental order

```text
24 original predictors
        ↓
LASSO coefficients for all 24
        ↓
statistical ranking
        +
pre-specified clinical weights
        ↓
DODA rank fusion
        ↓
final Top-K
```

DODA must **not** receive an already-truncated LASSO Top-K set. Otherwise, clinically prioritized features outside that preliminary Top-K would be impossible to recover.

In [14]:
# =============================================================================
# STEP 12: INSTALL / IMPORT DODA
# =============================================================================

# Run the following installation once if DODA is not installed:
# %pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

import doda

from doda import DODASelector
from doda.adapters import SklearnAdapter
from doda.knowledge.providers import JSONProvider
from doda.fusion import RankFusion

print("DODA:", doda.__file__)

print("Provider:", JSONProvider)
print("Fusion:", RankFusion)

DODA: c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\__init__.py
Provider: <class 'doda.knowledge.providers.json_provider.JSONProvider'>
Fusion: <class 'doda.fusion.rank.RankFusion'>

In [15]:
# =============================================================================
# STEP 13: LOCATE AND VALIDATE CLINICAL WEIGHTS
# =============================================================================

from pathlib import Path
from doda.knowledge.providers import JSONProvider

WEIGHTS_FILENAME = "BD_KDD_clinical_weights.json"

search_roots = [Path.cwd(), *Path.cwd().parents]
matches = []

for root in search_roots:
    try:
        matches.extend(root.rglob(WEIGHTS_FILENAME))
    except (PermissionError, OSError):
        continue

# Remove duplicates while preserving order
matches = list(dict.fromkeys(matches))

if not matches:
    raise FileNotFoundError(
        f"{WEIGHTS_FILENAME} was not found. "
        "Place it in the repository and rerun this cell."
    )

WEIGHTS_PATH = matches[0]

print(f"Using clinical weights: {WEIGHTS_PATH.resolve()}")

# Use the standard DODA JSON provider
provider = JSONProvider(str(WEIGHTS_PATH))

# Validate coverage using the flat JSON directly
import json

with open(WEIGHTS_PATH, "r", encoding="utf-8") as f:
    clinical_weights = json.load(f)

missing_weights = sorted(
    set(X.columns) - set(clinical_weights)
)

extra_weights = sorted(
    set(clinical_weights) - set(X.columns)
)

print(f"Clinical weights: {len(clinical_weights)}")
print(f"Predictors:       {len(X.columns)}")
print(f"Missing weights:  {missing_weights}")
print(f"Extra weights:    {extra_weights}")

assert not missing_weights
assert not extra_weights

Using clinical weights: C:\Users\johnm\msc_research\config\clinical_weights\BD_KDD_clinical_weights.json
Clinical weights: 24
Predictors:       24
Missing weights:  []
Extra weights:    []

In [16]:
# =============================================================================
# STEP 14: DODA — SCORE ALL FEATURES, THEN APPLY TOP-K
# =============================================================================

rank_doda_results = {}

for top_k in TOP_K_VALUES:

    lasso_operator = SklearnAdapter(
        LogisticRegression(
            penalty="l1",
            solver="liblinear",
            C=0.1,
            max_iter=2000,
            class_weight="balanced",
            random_state=42
        )
    )

    doda_selector = DODASelector(
        operators=[lasso_operator],
        provider=provider,
        fusion=RankFusion(),
        top_k=top_k
    )

    # Fit on the scaled training data only.
    doda_selector.fit(
        X_train_lasso_scaled,
        y_train
    )

    selected_features = list(
        doda_selector.get_selected_features()
    )

    rank_doda_results[top_k] = {
        "selector": doda_selector,
        "features": selected_features,
        "X_train": X_train[selected_features].copy(),
        "X_test": X_test[selected_features].copy()
    }

    print("=" * 70)
    print(f"DODA TOP-{top_k}")
    print("=" * 70)
    print(selected_features)
    print(f"Number selected: {len(selected_features)}")

    assert len(selected_features) == top_k

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F98AC980>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015376910054439898), 'Al': np.float64(0.0), 'Su': np.float64(0.20778995503547254), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.20388439908360473), 'Bgr': np.float64(0.04202198145666365), 'Bu': np.float64(0.23483532087460976), 'Sc': np.float64(0.03200411887984065), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.04896944211275897), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.008487091217834803), 'Htn': np.float64(0.0), 'Dm': np.float64(0.01782508920554277), 'Cad': np.float64(0.0), 'Appet': np.float64(0.09344379201053295), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10018086829976233)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03009207275993712, 'Su': 0.03057889822595705, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.03225806451612903, 'Sc': 0.030886196246139225, 'Sod': 0.02862400327131466, 'Pot': 0.02862400327131466, 'Hemo': 0.029083245521601686, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028594771241830064, 'Htn': 0.029571646010002173, 'Dm': 0.029910714285714284, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 5 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Ane']
======================================================================
DODA TOP-5
======================================================================
['Bu', 'Bp', 'Sc', 'Su', 'Ane']
Number selected: 5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F98AC980>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015376910054439898), 'Al': np.float64(0.0), 'Su': np.float64(0.20778995503547254), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.20388439908360473), 'Bgr': np.float64(0.04202198145666365), 'Bu': np.float64(0.23483532087460976), 'Sc': np.float64(0.03200411887984065), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.04896944211275897), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.008487091217834803), 'Htn': np.float64(0.0), 'Dm': np.float64(0.01782508920554277), 'Cad': np.float64(0.0), 'Appet': np.float64(0.09344379201053295), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10018086829976233)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03009207275993712, 'Su': 0.03057889822595705, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.03225806451612903, 'Sc': 0.030886196246139225, 'Sod': 0.02862400327131466, 'Pot': 0.02862400327131466, 'Hemo': 0.029083245521601686, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028594771241830064, 'Htn': 0.029571646010002173, 'Dm': 0.029910714285714284, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 10 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr']
======================================================================
DODA TOP-10
======================================================================
['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr']
Number selected: 10
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F98AC980>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015376910054439898), 'Al': np.float64(0.0), 'Su': np.float64(0.20778995503547254), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.20388439908360473), 'Bgr': np.float64(0.04202198145666365), 'Bu': np.float64(0.23483532087460976), 'Sc': np.float64(0.03200411887984065), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.04896944211275897), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.008487091217834803), 'Htn': np.float64(0.0), 'Dm': np.float64(0.01782508920554277), 'Cad': np.float64(0.0), 'Appet': np.float64(0.09344379201053295), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10018086829976233)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03009207275993712, 'Su': 0.03057889822595705, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.03225806451612903, 'Sc': 0.030886196246139225, 'Sod': 0.02862400327131466, 'Pot': 0.02862400327131466, 'Hemo': 0.029083245521601686, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028594771241830064, 'Htn': 0.029571646010002173, 'Dm': 0.029910714285714284, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 15 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr', 'Ba', 'Htn', 'Appet', 'Hemo', 'Sod']
======================================================================
DODA TOP-15
======================================================================
['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr', 'Ba', 'Htn', 'Appet', 'Hemo', 'Sod']
Number selected: 15
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F98AC980>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16275005422941846), 'Sg': np.float64(0.0025025929452409832), 'Al': np.float64(0.0), 'Su': np.float64(0.03381782645035158), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.033182197007389065), 'Bgr': np.float64(0.006839079760899626), 'Bu': np.float64(0.038219461207325625), 'Sc': np.float64(0.005208672083258821), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.00796977935943589), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0013812745559526353), 'Htn': np.float64(0.0), 'Dm': np.float64(0.002901034234846307), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015207982217116736), 'Pe': np.float64(0.0), 'Ane': np.float64(0.016304441748536548)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.015376910054439898), 'Al': np.float64(0.0), 'Su': np.float64(0.20778995503547254), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.20388439908360473), 'Bgr': np.float64(0.04202198145666365), 'Bu': np.float64(0.23483532087460976), 'Sc': np.float64(0.03200411887984065), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.04896944211275897), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.008487091217834803), 'Htn': np.float64(0.0), 'Dm': np.float64(0.01782508920554277), 'Cad': np.float64(0.0), 'Appet': np.float64(0.09344379201053295), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10018086829976233)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03009207275993712, 'Su': 0.03057889822595705, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.03225806451612903, 'Sc': 0.030886196246139225, 'Sod': 0.02862400327131466, 'Pot': 0.02862400327131466, 'Hemo': 0.029083245521601686, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028594771241830064, 'Htn': 0.029571646010002173, 'Dm': 0.029910714285714284, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 20 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr', 'Ba', 'Htn', 'Appet', 'Hemo', 'Sod', 'Pot', 'Pe', 'Rbcc', 'Age', 'Rbc']
======================================================================
DODA TOP-20
======================================================================
['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr', 'Ba', 'Htn', 'Appet', 'Hemo', 'Sod', 'Pot', 'Pe', 'Rbcc', 'Age', 'Rbc']
Number selected: 20

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

In [17]:
# =============================================================================
# STEP 15: INSPECT DODA RANK CHANGES
# =============================================================================

INSPECTION_TOP_K = 10

selector = rank_doda_results[INSPECTION_TOP_K]["selector"]

print("=" * 70)
print(f"DODA RANK COMPARISON — TOP-{INSPECTION_TOP_K}")
print("=" * 70)

rank_comparison = selector.compare_scores()

display(rank_comparison)

print("\nSelected features:")
print(rank_doda_results[INSPECTION_TOP_K]["features"])

======================================================================
DODA RANK COMPARISON — TOP-10
======================================================================

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
  Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0      Bu          2              3           1            1
1      Bp          1              6           2           -1
2      Sc          9              2           3            6
3      Su          3             16           4           -1
4     Ane          5             11           5            0
5      Al         14              1           6            8
6     Pcv          7             10           7            0
7      Sg         11              4           8            3
8      Dm         10              7           9            1
9     Bgr          8              9          10           -2

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,Bu,2,0.2348,3,0.90,1,0.0323,1
1,Bp,1,1.0000,6,0.80,2,0.0320,-1
2,Sc,9,0.0320,2,1.00,3,0.0309,6
3,Su,3,0.2078,16,0.55,4,0.0306,-1
4,Ane,5,0.1002,11,0.70,5,0.0305,0
5,Al,14,0.0000,1,1.00,6,0.0301,8
6,Pcv,7,0.0490,10,0.70,7,0.0301,0
7,Sg,11,0.0154,4,0.85,8,0.0300,3
8,Dm,10,0.0178,7,0.80,9,0.0299,1
9,Bgr,8,0.0420,9,0.70,10,0.0299,-2
10,Ba,4,0.2039,22,0.40,11,0.0297,-7
11,Htn,22,0.0000,5,0.85,12,0.0296,10
12,Appet,6,0.0934,24,0.40,13,0.0292,-7
13,Hemo,20,0.0000,8,0.75,14,0.0291,6
14,Sod,18,0.0000,12,0.65,15,0.0286,3
15,Pot,19,0.0000,13,0.65,16,0.0286,3
16,Pe,24,0.0000,14,0.65,17,0.0286,7
17,Rbcc,12,0.0085,18,0.55,18,0.0286,-6
18,Age,13,0.0000,15,0.55,19,0.0284,-6
19,Rbc,15,0.0000,17,0.55,20,0.0284,-5
20,Pc,16,0.0000,19,0.50,21,0.0282,-5
21,Cad,23,0.0000,20,0.45,22,0.0280,1
22,Pcc,17,0.0000,21,0.40,23,0.0278,-6
23,Wbcc,21,0.0000,23,0.40,24,0.0278,-3

Selected features:
['Bu', 'Bp', 'Sc', 'Su', 'Ane', 'Al', 'Pcv', 'Sg', 'Dm', 'Bgr']

In [18]:
# =============================================================================
# STEP 15B: EXPLICIT LASSO vs DODA RANK-SHIFT TABLE
# =============================================================================
# This table separates:
#   - statistical LASSO rank
#   - DODA final rank
#   - clinical weight
#   - rank movement
#
# Positive Rank_Change means the feature moved upward.
# Example: LASSO rank 10 -> DODA rank 4 = +6
#
# IMPORTANT:
# The selector is explicitly retrieved from rank_doda_results
# for the selected Top-K value. This avoids relying on a
# previously defined 'selector' variable.

# -------------------------------------------------------------------------
# Select which DODA Top-K experiment to inspect
# -------------------------------------------------------------------------

k = 10

if k not in rank_doda_results:
    raise KeyError(
        f"Top-K={k} was not found in rank_doda_results. "
        f"Available values: {list(rank_doda_results.keys())}"
    )

selector = rank_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# LASSO / mathematical ranking
# -------------------------------------------------------------------------

math_rank = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "LASSO_Normalized_Score"
    ]
)

math_rank["LASSO_Rank"] = (
    math_rank["LASSO_Normalized_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# DODA final ranking
# -------------------------------------------------------------------------

final_rank = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "DODA_Final_Score"
    ]
)

final_rank["DODA_Rank"] = (
    final_rank["DODA_Final_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# Combine rankings
# -------------------------------------------------------------------------

rank_shift_df = (
    math_rank[
        [
            "Feature",
            "LASSO_Normalized_Score",
            "LASSO_Rank"
        ]
    ]
    .merge(
        final_rank[
            [
                "Feature",
                "DODA_Final_Score",
                "DODA_Rank"
            ]
        ],
        on="Feature",
        how="inner"
    )
)


# -------------------------------------------------------------------------
# Add clinical weights
# -------------------------------------------------------------------------

rank_shift_df["Clinical_Weight"] = (
    rank_shift_df["Feature"]
    .map(selector.clinical_weights_)
)


# -------------------------------------------------------------------------
# Calculate rank movement
# -------------------------------------------------------------------------
# Positive value  = moved upward
# Negative value  = moved downward
# Zero             = no rank movement

rank_shift_df["Rank_Change"] = (
    rank_shift_df["LASSO_Rank"]
    - rank_shift_df["DODA_Rank"]
)


# -------------------------------------------------------------------------
# Sort by DODA final rank
# -------------------------------------------------------------------------

rank_shift_df = (
    rank_shift_df
    .sort_values(
        by="DODA_Rank"
    )
    .reset_index(drop=True)
)


# -------------------------------------------------------------------------
# Display
# -------------------------------------------------------------------------

print("=" * 80)
print(f"LASSO vs DODA RANK-SHIFT ANALYSIS — TOP-{k}")
print("=" * 80)

display(rank_shift_df)

================================================================================
LASSO vs DODA RANK-SHIFT ANALYSIS — TOP-10
================================================================================

,Feature,LASSO_Normalized_Score,LASSO_Rank,DODA_Final_Score,DODA_Rank,Clinical_Weight,Rank_Change
0,Bu,0.234835,2,0.032258,1,0.90,1
1,Bp,1.000000,1,0.032018,2,0.80,-1
2,Sc,0.032004,9,0.030886,3,1.00,6
3,Su,0.207790,3,0.030579,4,0.55,-1
4,Ane,0.100181,5,0.030536,5,0.70,0
5,Al,0.000000,13,0.030092,6,1.00,7
6,Pcv,0.048969,7,0.030077,7,0.70,0
7,Sg,0.015377,11,0.029958,8,0.85,3
8,Dm,0.017825,10,0.029911,9,0.80,1
9,Bgr,0.042022,8,0.029857,10,0.70,-2
10,Ba,0.203884,4,0.029710,11,0.40,-7
11,Htn,0.000000,13,0.029572,12,0.85,1
12,Appet,0.093444,6,0.029236,13,0.40,-7
13,Hemo,0.000000,13,0.029083,14,0.75,-1
14,Pot,0.000000,13,0.028624,15,0.65,-2
15,Sod,0.000000,13,0.028624,15,0.65,-2
16,Pe,0.000000,13,0.028624,15,0.65,-2
17,Rbcc,0.008487,12,0.028595,18,0.55,-6
18,Age,0.000000,13,0.028405,19,0.55,-6
19,Rbc,0.000000,13,0.028405,19,0.55,-6
20,Pc,0.000000,13,0.028191,21,0.50,-8
21,Cad,0.000000,13,0.027984,22,0.45,-9
22,Pcc,0.000000,13,0.027783,23,0.40,-10
23,Wbcc,0.000000,13,0.027783,23,0.40,-10

In [19]:
# =============================================================================
# STEP 16: INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weight_table = pd.DataFrame({
    "Feature": list(selector.clinical_weights_.keys()),
    "Clinical_Weight": list(selector.clinical_weights_.values())
}).sort_values(
    "Clinical_Weight",
    ascending=False
).reset_index(drop=True)

display(clinical_weight_table)

   Feature  Clinical_Weight
0       Al             1.00
1       Sc             1.00
2       Bu             0.90
3       Sg             0.85
4      Htn             0.85
5       Dm             0.80
6       Bp             0.80
7     Hemo             0.75
8      Pcv             0.70
9      Ane             0.70
10     Bgr             0.70
11     Pot             0.65
12      Pe             0.65
13     Sod             0.65
14     Age             0.55
15      Su             0.55
16     Rbc             0.55
17    Rbcc             0.55
18      Pc             0.50
19     Cad             0.45
20     Pcc             0.40
21      Ba             0.40
22    Wbcc             0.40
23   Appet             0.40

In [20]:
# =============================================================================
# STEP 17: DODA MODEL EVALUATION — FIXED SPLIT
# =============================================================================

fixed_doda_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = rank_doda_results[top_k]["X_train"]
    Xte_selected = rank_doda_results[top_k]["X_test"]
    selected_features = rank_doda_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_doda_rows.append({
            "Method": "DODA",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_doda_results_df = pd.DataFrame(fixed_doda_rows)
display(fixed_doda_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,DODA,5,Logistic Regression,"Bu, Bp, Sc, Su, Ane",0.5303,0.5378,0.6275,0.5792,0.5518
1,DODA,5,Random Forest,"Bu, Bp, Sc, Su, Ane",0.4899,0.5053,0.4706,0.4873,0.4981
2,DODA,5,XGBoost,"Bu, Bp, Sc, Su, Ane",0.5101,0.5229,0.5588,0.5403,0.5008
3,DODA,10,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.5455,0.5556,0.5882,0.5714,0.5564
4,DODA,10,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.4697,0.4842,0.4510,0.4670,0.5152
5,DODA,10,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.5354,0.5510,0.5294,0.5400,0.5329
6,DODA,15,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5404,0.5495,0.5980,0.5728,0.5716
7,DODA,15,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5657,0.5800,0.5686,0.5743,0.5659
8,DODA,15,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5606,0.5789,0.5392,0.5584,0.5558
9,DODA,20,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5859,0.5943,0.6176,0.6058,0.5887
10,DODA,20,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5404,0.5524,0.5686,0.5604,0.5292
11,DODA,20,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5051,0.5189,0.5392,0.5288,0.4970

In [21]:
# =============================================================================
# STEP 18: FIXED-SPLIT LASSO vs DODA COMPARISON
# =============================================================================

fixed_comparison_df = pd.concat(
    [fixed_lasso_results_df, fixed_doda_results_df],
    ignore_index=True
)

display(fixed_comparison_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,LASSO,5,Logistic Regression,"Bp, Bu, Su, Ba, Ane",0.5303,0.5391,0.6078,0.5714,0.5587
1,LASSO,5,Random Forest,"Bp, Bu, Su, Ba, Ane",0.5354,0.5532,0.5098,0.5306,0.5628
2,LASSO,5,XGBoost,"Bp, Bu, Su, Ba, Ane",0.5455,0.5577,0.5686,0.5631,0.5288
3,LASSO,10,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5455,0.5517,0.6275,0.5872,0.5642
4,LASSO,10,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5505,0.5644,0.5588,0.5616,0.5575
5,LASSO,10,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm",0.5253,0.5385,0.5490,0.5437,0.5239
6,LASSO,15,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5758,0.5818,0.6275,0.6038,0.5774
7,LASSO,15,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5234,0.5490,0.5359,0.5283
8,LASSO,15,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.4545,0.4722,0.5000,0.4857,0.4861
9,LASSO,20,Logistic Regression,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5657,0.5755,0.5980,0.5865,0.5751
10,LASSO,20,Random Forest,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5243,0.5294,0.5268,0.5518
11,LASSO,20,XGBoost,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...",0.5101,0.5248,0.5196,0.5222,0.5137
12,DODA,5,Logistic Regression,"Bu, Bp, Sc, Su, Ane",0.5303,0.5378,0.6275,0.5792,0.5518
13,DODA,5,Random Forest,"Bu, Bp, Sc, Su, Ane",0.4899,0.5053,0.4706,0.4873,0.4981
14,DODA,5,XGBoost,"Bu, Bp, Sc, Su, Ane",0.5101,0.5229,0.5588,0.5403,0.5008
15,DODA,10,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.5455,0.5556,0.5882,0.5714,0.5564
16,DODA,10,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.4697,0.4842,0.4510,0.4670,0.5152
17,DODA,10,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",0.5354,0.5510,0.5294,0.5400,0.5329
18,DODA,15,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5404,0.5495,0.5980,0.5728,0.5716
19,DODA,15,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5657,0.5800,0.5686,0.5743,0.5659
20,DODA,15,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5606,0.5789,0.5392,0.5584,0.5558
21,DODA,20,Logistic Regression,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5859,0.5943,0.6176,0.6058,0.5887
22,DODA,20,Random Forest,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5404,0.5524,0.5686,0.5604,0.5292
23,DODA,20,XGBoost,"Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",0.5051,0.5189,0.5392,0.5288,0.4970

In [22]:
# =============================================================================
# STEP 19: COMPARE FEATURE SETS ON THE FIXED SPLIT
# =============================================================================

fixed_feature_comparison = []

for top_k in TOP_K_VALUES:

    lasso_set = set(lasso_results[top_k]["features"])
    doda_set = set(rank_doda_results[top_k]["features"])

    intersection = lasso_set & doda_set
    union = lasso_set | doda_set

    jaccard = len(intersection) / len(union)

    fixed_feature_comparison.append({
        "Top_K": top_k,
        "LASSO_Features": ", ".join(lasso_results[top_k]["features"]),
        "DODA_Features": ", ".join(rank_doda_results[top_k]["features"]),
        "Same_Feature_Set": lasso_set == doda_set,
        "Overlap_Count": len(intersection),
        "Jaccard": jaccard,
        "Features_Changed": top_k - len(intersection)
    })

fixed_feature_comparison_df = pd.DataFrame(fixed_feature_comparison)

display(fixed_feature_comparison_df)

,Top_K,LASSO_Features,DODA_Features,Same_Feature_Set,Overlap_Count,Jaccard,Features_Changed
0,5,"Bp, Bu, Su, Ba, Ane","Bu, Bp, Sc, Su, Ane",False,4,0.666667,1
1,10,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm","Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr",False,8,0.666667,2
2,15,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...","Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",False,11,0.578947,4
3,20,"Bp, Bu, Su, Ba, Ane, Appet, Pcv, Bgr, Sc, Dm, ...","Bu, Bp, Sc, Su, Ane, Al, Pcv, Sg, Dm, Bgr, Ba,...",False,18,0.818182,2

In [23]:
# =============================================================================
# STEP 20: SAVE FIXED-SPLIT DODA RESULTS
# =============================================================================

doda_dir = Path("../../../results/kidney_disease/doda")
doda_dir.mkdir(parents=True, exist_ok=True)

fixed_doda_results_df.to_csv(
    doda_dir / "lasso_doda_fixed_split_results.csv",
    index=False
)

fixed_feature_comparison_df.to_csv(
    doda_dir / "lasso_doda_fixed_split_feature_comparison.csv",
    index=False
)

print(f"Saved results to: {doda_dir.resolve()}")

Saved results to: C:\Users\johnm\msc_research\results\kidney_disease\doda

# 3.1 Five-Fold Stratified Cross-Validation

The fixed 80/20 split is followed by a separate **5-fold stratified cross-validation** experiment.

Feature selection is refit inside each training fold. DODA also receives all features and performs the final Top-K selection inside the training fold. Logistic Regression scaling is fitted only on the corresponding training fold.

The DODA fusion method remains **RankFusion**, matching the current BD-KDD pipeline.

In [24]:
# =============================================================================
# STEP 21: 5-FOLD CV CONFIGURATION
# =============================================================================
from sklearn.model_selection import StratifiedKFold

CV5_SPLITS = 5
CV5_RANDOM_STATE = 42
cv5 = StratifiedKFold(n_splits=CV5_SPLITS, shuffle=True, random_state=CV5_RANDOM_STATE)
cv5_results = []

print("5-fold CV configuration loaded.")
print("Splits:", CV5_SPLITS)
print("Top-K values:", TOP_K_VALUES)
print("Fusion: RankFusion")

5-fold CV configuration loaded.
Splits: 5
Top-K values: [5, 10, 15, 20]
Fusion: RankFusion

In [25]:
# =============================================================================
# STEP 22: 5-FOLD CV — LASSO vs DODA
# =============================================================================

# Reset results before running the CV.
# This prevents duplicate rows if the cell is executed more than once.
cv5_results = []

for fold, (train_idx, val_idx) in enumerate(
    cv5.split(X, y),
    start=1
):

    X_train_fold = X.iloc[train_idx].copy()
    X_val_fold = X.iloc[val_idx].copy()

    y_train_fold = y.iloc[train_idx].copy()
    y_val_fold = y.iloc[val_idx].copy()

    # -------------------------------------------------------------------------
    # Scale ONLY using the training-fold statistics before LASSO selection.
    # -------------------------------------------------------------------------

    fold_scaler = StandardScaler()

    X_train_fold_scaled = pd.DataFrame(
        fold_scaler.fit_transform(X_train_fold),
        columns=X_train_fold.columns,
        index=X_train_fold.index
    )

    X_val_fold_scaled = pd.DataFrame(
        fold_scaler.transform(X_val_fold),
        columns=X_val_fold.columns,
        index=X_val_fold.index
    )

    # -------------------------------------------------------------------------
    # LASSO ranking is learned ONLY from the training fold.
    # -------------------------------------------------------------------------

    lasso_fold = LogisticRegression(
        penalty="l1",
        solver="liblinear",
        C=0.1,
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    )

    lasso_fold.fit(
        X_train_fold_scaled,
        y_train_fold
    )

    lasso_fold_scores = pd.DataFrame({
        "Feature": X_train_fold.columns,
        "Score": np.abs(lasso_fold.coef_[0])
    }).sort_values(
        "Score",
        ascending=False
    )

    # -------------------------------------------------------------------------
    # Evaluate each Top-K
    # -------------------------------------------------------------------------

    for top_k in TOP_K_VALUES:

        # -------------------------
        # Baseline LASSO Top-K
        # -------------------------

        lasso_features = (
            lasso_fold_scores
            .head(top_k)["Feature"]
            .tolist()
        )

        # -------------------------
        # DODA
        # -------------------------

        fold_doda = DODASelector(
            operators=[
                SklearnAdapter(
                    LogisticRegression(
                        penalty="l1",
                        solver="liblinear",
                        C=0.1,
                        max_iter=2000,
                        class_weight="balanced",
                        random_state=42
                    )
                )
            ],
            provider=JSONProvider(
                str(WEIGHTS_PATH)
            ),
            fusion=RankFusion(),
            top_k=top_k
        )

        fold_doda.fit(
            X_train_fold_scaled,
            y_train_fold
        )

        doda_features = list(
            fold_doda.get_selected_features()
        )

        # -------------------------
        # Compare both methods
        # -------------------------

        feature_sets = {
            "LASSO": lasso_features,
            "DODA": doda_features
        }

        for method, selected_features in feature_sets.items():

            Xtr_selected = X_train_fold[selected_features]
            Xval_selected = X_val_fold[selected_features]

            # -------------------------------------------------------------
            # Downstream models
            # -------------------------------------------------------------

            for model_name, model_template in models.items():

                model = model_template.__class__(
                    **model_template.get_params()
                )

                Xtr = Xtr_selected
                Xval = Xval_selected

                # Logistic Regression is scaled using training-fold
                # statistics only.
                if model_name == "Logistic Regression":

                    scaler = StandardScaler()

                    Xtr = scaler.fit_transform(Xtr)
                    Xval = scaler.transform(Xval)

                # ---------------------------------------------------------
                # Train
                # ---------------------------------------------------------

                model.fit(
                    Xtr,
                    y_train_fold
                )

                # ---------------------------------------------------------
                # Predict
                # ---------------------------------------------------------

                y_pred = model.predict(Xval)
                y_prob = model.predict_proba(Xval)[:, 1]

                # ---------------------------------------------------------
                # Store results
                # ---------------------------------------------------------

                cv5_results.append({
                    "Fold": fold,
                    "Method": method,
                    "Top_K": top_k,
                    "Model": model_name,

                    "Accuracy": accuracy_score(
                        y_val_fold,
                        y_pred
                    ),

                    "Precision": precision_score(
                        y_val_fold,
                        y_pred,
                        zero_division=0
                    ),

                    "Recall": recall_score(
                        y_val_fold,
                        y_pred,
                        zero_division=0
                    ),

                    "F1": f1_score(
                        y_val_fold,
                        y_pred,
                        zero_division=0
                    ),

                    "ROC_AUC": roc_auc_score(
                        y_val_fold,
                        y_prob
                    ),

                    "Selected_Features": ", ".join(
                        selected_features
                    )
                })


# =============================================================================
# VALIDATION
# =============================================================================

cv5_results_df = pd.DataFrame(cv5_results)

expected_rows = (
    5
    * len(TOP_K_VALUES)
    * 2
    * len(models)
)

print("Expected rows:", expected_rows)
print("Actual rows:  ", len(cv5_results_df))

assert len(cv5_results_df) == expected_rows

print(
    "\nCompleted 5-fold CV. Rows:",
    len(cv5_results_df)
)

display(
    cv5_results_df.head()
)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97DBB10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97DBD90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F981C640>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn', 'Dm', 'Ba', 'Hemo', 'Pcv', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F981CC30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn', 'Dm', 'Ba', 'Hemo', 'Pcv', 'Ane', 'Sod', 'Wbcc', 'Age', 'Pe', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE9AE690>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 5 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97FBF00>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 10 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97FB790>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 15 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg', 'Htn', 'Sod', 'Dm', 'Pc', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F989B650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 20 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg', 'Htn', 'Sod', 'Dm', 'Pc', 'Hemo', 'Appet', 'Bgr', 'Ane', 'Age', 'Su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F9899250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 5 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97EB3E0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 10 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F97EBF20>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 15 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn', 'Ba', 'Pot', 'Dm', 'Ane', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F982E7B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 20 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn', 'Ba', 'Pot', 'Dm', 'Ane', 'Hemo', 'Appet', 'Pe', 'Sod', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F982F310>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE98E410>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F983ABD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg', 'Htn', 'Rbcc', 'Dm', 'Sod', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F9838F50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg', 'Htn', 'Rbcc', 'Dm', 'Sod', 'Hemo', 'Pcv', 'Ane', 'Rbc', 'Appet', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F9845E90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F9845860>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7C88BCAF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba', 'Rbcc', 'Dm', 'Appet', 'Hemo', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE8C5DB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba', 'Rbcc', 'Dm', 'Appet', 'Hemo', 'Bgr', 'Pot', 'Pc', 'Sod', 'Pe', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Expected rows: 120
Actual rows:   120

Completed 5-fold CV. Rows: 120

,Fold,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,LASSO,5,Logistic Regression,0.525253,0.530973,0.594059,0.560748,0.524497,"Bp, Sg, Su, Rbcc, Ba"
1,1,LASSO,5,Random Forest,0.525253,0.533333,0.554455,0.543689,0.513831,"Bp, Sg, Su, Rbcc, Ba"
2,1,LASSO,5,XGBoost,0.520202,0.526786,0.584158,0.553991,0.499898,"Bp, Sg, Su, Rbcc, Ba"
3,1,DODA,5,Logistic Regression,0.500000,0.509615,0.524752,0.517073,0.518322,"Bp, Sg, Sc, Su, Rbcc"
4,1,DODA,5,Random Forest,0.540404,0.550000,0.544554,0.547264,0.548382,"Bp, Sg, Sc, Su, Rbcc"

In [26]:
# =============================================================================
# STEP 23: 5-FOLD CV PERFORMANCE SUMMARY
# =============================================================================
cv5_summary_df = (
    cv5_results_df.groupby(["Method", "Top_K", "Model"])
    [["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]]
    .agg(["mean", "std"])
    .reset_index()
)
cv5_summary_df.columns = [
    "Method", "Top_K", "Model", "Accuracy_Mean", "Accuracy_STD",
    "Precision_Mean", "Precision_STD", "Recall_Mean", "Recall_STD",
    "F1_Mean", "F1_STD", "ROC_AUC_Mean", "ROC_AUC_STD"
]
display(cv5_summary_df.round(4))

cv5_dir = Path("../../../results/kidney_disease/cv")
cv5_dir.mkdir(parents=True, exist_ok=True)
cv5_results_df.to_csv(cv5_dir / "lasso_doda_5fold_results.csv", index=False)
cv5_summary_df.to_csv(cv5_dir / "lasso_doda_5fold_summary.csv", index=False)

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,DODA,5,Logistic Regression,0.5102,0.0302,0.5198,0.0243,0.5761,0.0597,0.5460,0.0391,0.5129,0.0231
1,DODA,5,Random Forest,0.5101,0.0389,0.5236,0.0390,0.5424,0.0164,0.5323,0.0247,0.5019,0.0413
2,DODA,5,XGBoost,0.5040,0.0188,0.5166,0.0181,0.5286,0.0287,0.5222,0.0191,0.4992,0.0325
3,DODA,10,Logistic Regression,0.5283,0.0149,0.5366,0.0110,0.5898,0.0387,0.5617,0.0217,0.5258,0.0179
4,DODA,10,Random Forest,0.4989,0.0518,0.5138,0.0498,0.5307,0.0455,0.5210,0.0400,0.4969,0.0471
5,DODA,10,XGBoost,0.5111,0.0237,0.5235,0.0216,0.5385,0.0433,0.5301,0.0261,0.5070,0.0494
6,DODA,15,Logistic Regression,0.5243,0.0077,0.5337,0.0073,0.5799,0.0153,0.5557,0.0075,0.5296,0.0187
7,DODA,15,Random Forest,0.5081,0.0249,0.5204,0.0233,0.5366,0.0483,0.5275,0.0297,0.5197,0.0391
8,DODA,15,XGBoost,0.5162,0.0403,0.5281,0.0369,0.5464,0.0351,0.5370,0.0349,0.5271,0.0531
9,DODA,20,Logistic Regression,0.5233,0.0112,0.5326,0.0100,0.5799,0.0204,0.5552,0.0125,0.5308,0.0165
10,DODA,20,Random Forest,0.5152,0.0247,0.5263,0.0214,0.5544,0.0510,0.5392,0.0311,0.5145,0.0304
11,DODA,20,XGBoost,0.5192,0.0316,0.5309,0.0279,0.5543,0.0404,0.5418,0.0284,0.5324,0.0327
12,LASSO,5,Logistic Regression,0.5101,0.0120,0.5199,0.0089,0.5898,0.0314,0.5524,0.0174,0.5169,0.0232
13,LASSO,5,Random Forest,0.5031,0.0289,0.5154,0.0262,0.5385,0.0425,0.5262,0.0296,0.4937,0.0292
14,LASSO,5,XGBoost,0.5030,0.0217,0.5144,0.0189,0.5525,0.0605,0.5318,0.0338,0.4853,0.0198
15,LASSO,10,Logistic Regression,0.5132,0.0222,0.5233,0.0185,0.5682,0.0485,0.5444,0.0306,0.5246,0.0256
16,LASSO,10,Random Forest,0.5030,0.0420,0.5170,0.0404,0.5228,0.0344,0.5193,0.0327,0.5042,0.0389
17,LASSO,10,XGBoost,0.5051,0.0468,0.5163,0.0433,0.5170,0.0721,0.5162,0.0565,0.5077,0.0518
18,LASSO,15,Logistic Regression,0.5253,0.0118,0.5348,0.0101,0.5740,0.0283,0.5535,0.0175,0.5250,0.0190
19,LASSO,15,Random Forest,0.4969,0.0443,0.5112,0.0430,0.5129,0.0412,0.5114,0.0369,0.4973,0.0517
20,LASSO,15,XGBoost,0.5020,0.0463,0.5139,0.0426,0.5149,0.0588,0.5143,0.0503,0.5120,0.0477
21,LASSO,20,Logistic Regression,0.5203,0.0123,0.5299,0.0102,0.5721,0.0296,0.5501,0.0188,0.5232,0.0128
22,LASSO,20,Random Forest,0.5111,0.0364,0.5215,0.0300,0.5603,0.0580,0.5397,0.0408,0.5143,0.0484
23,LASSO,20,XGBoost,0.5222,0.0362,0.5323,0.0317,0.5641,0.0580,0.5472,0.0410,0.5275,0.0444

# 3.2 Robustness: 5×5 Repeated Stratified Cross-Validation

The fixed split provides a reproducible initial comparison.

For robustness, feature selection is **recomputed inside every training fold**. This prevents information from the validation fold from influencing LASSO or DODA.

There are:

- 5 folds
- 5 repeats
- 25 train/validation runs
- 4 Top-K budgets
- 2 feature-selection methods
- 3 downstream models

This produces 600 model-evaluation rows.

In [27]:
# =============================================================================
# STEP 24: REPEATED CV CONFIGURATION
# =============================================================================

from sklearn.model_selection import RepeatedStratifiedKFold

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)

print(f"Top-K values: {TOP_K_VALUES}")
print(f"CV runs: {N_SPLITS * N_REPEATS}")

Top-K values: [5, 10, 15, 20]
CV runs: 25

In [28]:
# =============================================================================
# STEP 25: 5×5 REPEATED CV — LASSO vs DODA
# =============================================================================

cv_results = []

for run_id, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    X_train_fold = X.iloc[train_idx].copy()
    X_val_fold = X.iloc[val_idx].copy()

    y_train_fold = y.iloc[train_idx].copy()
    y_val_fold = y.iloc[val_idx].copy()

    print(f"Run {run_id:02d}/{N_SPLITS * N_REPEATS}")

    # -----------------------------------------------------------------
    # Scale ONLY the training partition before LASSO selection.
    # -----------------------------------------------------------------

    fold_scaler = StandardScaler()

    X_train_fold_scaled = pd.DataFrame(
        fold_scaler.fit_transform(X_train_fold),
        columns=X_train_fold.columns,
        index=X_train_fold.index
    )

    X_val_fold_scaled = pd.DataFrame(
        fold_scaler.transform(X_val_fold),
        columns=X_val_fold.columns,
        index=X_val_fold.index
    )

    # -----------------------------------------------------------------
    # LASSO scores ALL features inside this training partition.
    # -----------------------------------------------------------------

    lasso_all = LogisticRegression(
        penalty="l1",
        solver="liblinear",
        C=0.1,
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    )

    lasso_all.fit(
        X_train_fold_scaled,
        y_train_fold
    )

    lasso_fold_scores = pd.DataFrame({
        "Feature": X_train_fold.columns,
        "Score": np.abs(lasso_all.coef_[0])
    }).sort_values(
        "Score",
        ascending=False
    )

    # -----------------------------------------------------------------
    # DODA also receives ALL features and performs final Top-K.
    # -----------------------------------------------------------------

    for top_k in TOP_K_VALUES:

        # -------------------------
        # LASSO Top-K
        # -------------------------

        lasso_features = (
            lasso_fold_scores
            .head(top_k)["Feature"]
            .tolist()
        )

        # -------------------------
        # DODA Top-K
        # -------------------------

        fold_doda_operator = SklearnAdapter(
            LogisticRegression(
                penalty="l1",
                solver="liblinear",
                C=0.1,
                max_iter=2000,
                class_weight="balanced",
                random_state=42
            )
        )

        fold_doda = DODASelector(
            operators=[fold_doda_operator],
            provider=JSONProvider(str(WEIGHTS_PATH)),
            fusion=RankFusion(),
            top_k=top_k
        )

        fold_doda.fit(
            X_train_fold_scaled,
            y_train_fold
        )

        doda_features = list(
            fold_doda.get_selected_features()
        )

        # -------------------------
        # Model loop
        # -------------------------

        feature_sets = {
            "LASSO": lasso_features,
            "DODA": doda_features
        }

        for method, selected_features in feature_sets.items():

            Xtr_selected = X_train_fold[selected_features]
            Xval_selected = X_val_fold[selected_features]

            for model_name, model_template in models.items():

                model = model_template.__class__(
                    **model_template.get_params()
                )

                Xtr = Xtr_selected
                Xval = Xval_selected

                if model_name == "Logistic Regression":
                    scaler = StandardScaler()
                    Xtr = scaler.fit_transform(Xtr)
                    Xval = scaler.transform(Xval)

                model.fit(Xtr, y_train_fold)

                y_pred = model.predict(Xval)
                y_prob = model.predict_proba(Xval)[:, 1]

                cv_results.append({
                    "Run": run_id,
                    "Method": method,
                    "Top_K": top_k,
                    "Model": model_name,
                    "Accuracy": accuracy_score(
                        y_val_fold, y_pred
                    ),
                    "Precision": precision_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "Recall": recall_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "F1": f1_score(
                        y_val_fold, y_pred, zero_division=0
                    ),
                    "ROC_AUC": roc_auc_score(
                        y_val_fold, y_prob
                    ),
                    "Selected_Features": ", ".join(
                        selected_features
                    )
                })

cv_results_df = pd.DataFrame(cv_results)

print("Completed.")
print(f"Rows generated: {len(cv_results_df)}")

assert len(cv_results_df) == 25 * 4 * 2 * 3

display(cv_results_df.head())

Run 01/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F9836690>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE9205D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE99D2D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn', 'Dm', 'Ba', 'Hemo', 'Pcv', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE8DD6A0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.003865822342735337), 'Bp': np.float64(0.15778162552295807), 'Sg': np.float64(0.0831185017659493), 'Al': np.float64(0.0), 'Su': np.float64(0.042429847718452714), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026436198756198334), 'Bgr': np.float64(0.015040512081841886), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011541437819182819), 'Sod': np.float64(0.0032811826464089113), 'Pot': np.float64(0.019272522339605993), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.016593647253582967), 'Rbcc': np.float64(0.03651693953265173), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.02450109339362104), 'Bp': np.float64(1.0), 'Sg': np.float64(0.52679455855812), 'Al': np.float64(0.0), 'Su': np.float64(0.26891501198457957), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.1675492863543336), 'Bgr': np.float64(0.0953248645524533), 'Bu': np.float64(0.0), 'Sc': np.float64(0.07314817413579934), 'Sod': np.float64(0.020795720892934275), 'Pot': np.float64(0.12214681066777155), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.10516843896483055), 'Rbcc': np.float64(0.23143974725585723), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028991596638655463, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03028233151183971, 'Su': 0.03057889822595705, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02946912242686891, 'Bgr': 0.029857397504456328, 'Bu': 0.030017921146953404, 'Sc': 0.030886196246139225, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.029273504273504274, 'Pcv': 0.02904040404040404, 'Wbcc': 0.02900988017658188, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Su', 'Rbcc', 'Al', 'Pot', 'Bu', 'Bgr', 'Htn', 'Dm', 'Ba', 'Hemo', 'Pcv', 'Ane', 'Sod', 'Wbcc', 'Age', 'Pe', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 02/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7F984A200>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 5 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97FB30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 10 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDFB90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 15 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg', 'Htn', 'Sod', 'Dm', 'Pc', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97DAF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15998467011484607), 'Sg': np.float64(0.0036672042516920386), 'Al': np.float64(0.01696165106482937), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.013760919192897781), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08935539347406346), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.02257801150154013), 'Sc': np.float64(0.0008949118791052817), 'Sod': np.float64(0.008704959427459103), 'Pot': np.float64(0.039172494683421766), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07229083178197049), 'Wbcc': np.float64(0.00014825624400109248), 'Rbcc': np.float64(0.04400568949865605), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015605293699628802), 'Pe': np.float64(0.04045784511146249), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.022922222792093213), 'Al': np.float64(0.1060204771660518), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.08601398610891539), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5585247224619652), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1411260934271537), 'Sc': np.float64(0.005593735190145801), 'Sod': np.float64(0.0544112096565889), 'Pot': np.float64(0.2448515514349064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4518609922442946), 'Wbcc': np.float64(0.0009266903128572615), 'Rbcc': np.float64(0.2750619135387551), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0975424313368677), 'Pe': np.float64(0.25288576138213464), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.031099324975891997, 'Su': 0.02803921568627451, 'Rbc': 0.02803921568627451, 'Pc': 0.02877846790890269, 'Pcc': 0.027417840375586856, 'Ba': 0.03021353930031804, 'Bgr': 0.028484848484848488, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02871794871794872, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030330882352941176, 'Htn': 0.029206349206349208, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028484848484848488}
Top 20 Features Selected: ['Bp', 'Al', 'Bu', 'Pcv', 'Rbcc', 'Pe', 'Ba', 'Sc', 'Pot', 'Sg', 'Htn', 'Sod', 'Dm', 'Pc', 'Hemo', 'Appet', 'Bgr', 'Ane', 'Age', 'Su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 03/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97D610>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 5 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97F350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 10 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 15 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn', 'Ba', 'Pot', 'Dm', 'Ane', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC5F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.18266135045133275), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04631943631823336), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.052915956118520235), 'Bgr': np.float64(0.07048483712541234), 'Bu': np.float64(0.02344672794419333), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.024727901418573194), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09537687517278708), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.04664657329501615), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04334263871803412), 'Pe': np.float64(0.0029740599011285327), 'Ane': np.float64(0.020712641339215816)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.2535809365461494), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2896943222404285), 'Bgr': np.float64(0.38587712699623294), 'Bu': np.float64(0.12836173545339216), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.13537566298220025), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5221513743171342), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.25537188452706855), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.23728412502666835), 'Pe': np.float64(0.01628182367961264), 'Ane': np.float64(0.11339367243282467)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.029857397504456328, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029709507042253523, 'Bgr': 0.031024531024531024, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030090497737556562, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029437229437229435}
Top 20 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Bu', 'Al', 'Sc', 'Rbcc', 'Su', 'Sg', 'Htn', 'Ba', 'Pot', 'Dm', 'Ane', 'Hemo', 'Appet', 'Pe', 'Sod', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 04/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97D0D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97FF50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg', 'Htn', 'Rbcc', 'Dm', 'Sod', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBECF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10738009934617884), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.03864979039594924), 'Rbc': np.float64(0.006783858093534352), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06023266957607533), 'Bgr': np.float64(0.02065941081849778), 'Bu': np.float64(0.05462662163665634), 'Sc': np.float64(0.004651829322701034), 'Sod': np.float64(0.012708192887665178), 'Pot': np.float64(0.057581140164378396), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014619819380102086), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.01406827304866128), 'Pe': np.float64(0.050740649118212376), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.359934388506641), 'Rbc': np.float64(0.06317612048079893), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5609295385534464), 'Bgr': np.float64(0.19239515463563361), 'Bu': np.float64(0.5087220254895419), 'Sc': np.float64(0.04332114936590037), 'Sod': np.float64(0.11834774753463108), 'Pot': np.float64(0.5362366072948455), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13615017558299863), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.13101378313412693), 'Pe': np.float64(0.47253308040469794), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.029857397504456328, 'Rbc': 0.028790389395194696, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.03007688828584351, 'Bu': 0.031754032258064516, 'Sc': 0.03028233151183971, 'Sod': 0.029211087420042643, 'Pot': 0.030798389007344232, 'Hemo': 0.029083245521601686, 'Pcv': 0.028850145288501453, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.030309988518943745, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Pe', 'Sc', 'Ba', 'Al', 'Bgr', 'Su', 'Sg', 'Htn', 'Rbcc', 'Dm', 'Sod', 'Hemo', 'Pcv', 'Ane', 'Rbc', 'Appet', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 05/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97C590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDCE30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95B710>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba', 'Rbcc', 'Dm', 'Appet', 'Hemo', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBC650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1384746815978939), 'Sg': np.float64(0.009514100212471078), 'Al': np.float64(0.0), 'Su': np.float64(0.09234427580585562), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004109687838853666), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.037752483215554224), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.06628813906633899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0021584693694957514), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09095231740578455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.009582138739960682), 'Htn': np.float64(0.0026932345717025716), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.019540257629370377), 'Pe': np.float64(0.0), 'Ane': np.float64(0.01446661780120555)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06870642418300228), 'Al': np.float64(0.0), 'Su': np.float64(0.6668675799812066), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.029678261696874497), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2726309443713385), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.47870223134961293), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015587465842770931), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6568155012617691), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06919776690865069), 'Htn': np.float64(0.019449292395004387), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.14111068827810594), 'Pe': np.float64(0.0), 'Ane': np.float64(0.10447121187982986)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02877846790890269, 'Pcc': 0.027783137179239824, 'Ba': 0.02946912242686891, 'Bgr': 0.028850145288501453, 'Bu': 0.031754032258064516, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.028814262023217248, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029236022193768675, 'Pe': 0.02862400327131466, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sg', 'Al', 'Sc', 'Ane', 'Htn', 'Ba', 'Rbcc', 'Dm', 'Appet', 'Hemo', 'Bgr', 'Pot', 'Pc', 'Sod', 'Pe', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 06/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE97F0B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4247504694884191), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.005121578012313002), 'Ba': np.float64(0.4854814876706409), 'Bgr': np.float64(0.06136794258944339), 'Bu': np.float64(0.20704387834541327), 'Sc': np.float64(0.0), 'Sod': np.float64(0.253831668621776), 'Pot': np.float64(0.13809767363339792), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.49199104203964866), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.10071803061735508), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.20065146237490575), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.03028233151183971, 'Su': 0.028594771241830064, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.03128054740957967, 'Sc': 0.03028233151183971, 'Sod': 0.030309988518943745, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.02919863597612958, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Sg', 'Bu', 'Pcv', 'Sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBC710>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4247504694884191), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.005121578012313002), 'Ba': np.float64(0.4854814876706409), 'Bgr': np.float64(0.06136794258944339), 'Bu': np.float64(0.20704387834541327), 'Sc': np.float64(0.0), 'Sod': np.float64(0.253831668621776), 'Pot': np.float64(0.13809767363339792), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.49199104203964866), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.10071803061735508), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.20065146237490575), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.03028233151183971, 'Su': 0.028594771241830064, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.03128054740957967, 'Sc': 0.03028233151183971, 'Sod': 0.030309988518943745, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.02919863597612958, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Sg', 'Bu', 'Pcv', 'Sod', 'Al', 'Sc', 'Ba', 'Htn', 'Pot']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958050>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4247504694884191), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.005121578012313002), 'Ba': np.float64(0.4854814876706409), 'Bgr': np.float64(0.06136794258944339), 'Bu': np.float64(0.20704387834541327), 'Sc': np.float64(0.0), 'Sod': np.float64(0.253831668621776), 'Pot': np.float64(0.13809767363339792), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.49199104203964866), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.10071803061735508), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.20065146237490575), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.03028233151183971, 'Su': 0.028594771241830064, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.03128054740957967, 'Sc': 0.03028233151183971, 'Sod': 0.030309988518943745, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.02919863597612958, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Sg', 'Bu', 'Pcv', 'Sod', 'Al', 'Sc', 'Ba', 'Htn', 'Pot', 'Dm', 'Bgr', 'Hemo', 'Rbcc', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDE870>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1530921165818111), 'Sg': np.float64(0.06502594839310005), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0007840732181438625), 'Ba': np.float64(0.07432338850878485), 'Bgr': np.float64(0.009394948221288958), 'Bu': np.float64(0.03169678556120632), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03885962740480057), 'Pot': np.float64(0.021141665151561056), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07531994996514062), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.015419136485162544), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.030718157070209955), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.4247504694884191), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.005121578012313002), 'Ba': np.float64(0.4854814876706409), 'Bgr': np.float64(0.06136794258944339), 'Bu': np.float64(0.20704387834541327), 'Sc': np.float64(0.0), 'Sod': np.float64(0.253831668621776), 'Pot': np.float64(0.13809767363339792), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.49199104203964866), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.10071803061735508), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.20065146237490575), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.03149801587301587, 'Al': 0.03028233151183971, 'Su': 0.028594771241830064, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.029437229437229435, 'Bu': 0.03128054740957967, 'Sc': 0.03028233151183971, 'Sod': 0.030309988518943745, 'Pot': 0.029631255487269532, 'Hemo': 0.029273504273504274, 'Pcv': 0.03128054740957967, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.02919863597612958, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.028814262023217248, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Sg', 'Bu', 'Pcv', 'Sod', 'Al', 'Sc', 'Ba', 'Htn', 'Pot', 'Dm', 'Bgr', 'Hemo', 'Rbcc', 'Ane', 'Appet', 'Pe', 'Age', 'Su', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 07/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD190>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0013584349626462237), 'Al': np.float64(0.0), 'Su': np.float64(0.47474379965483027), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.04399232893326353), 'Pcc': np.float64(0.16856320606488218), 'Ba': np.float64(0.4802761513677171), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.6643681981599265), 'Sc': np.float64(0.3175887058906306), 'Sod': np.float64(0.1768206378366307), 'Pot': np.float64(0.3058012551408796), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.36557533689946015), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4576724665972343), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.06276528851159781), 'Pe': np.float64(0.09884227997676022), 'Ane': np.float64(0.337644789537611)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.029551337359792925, 'Su': 0.030330882352941176, 'Rbc': 0.02786377708978328, 'Pc': 0.028006267136701922, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.028309409888357256, 'Bu': 0.03225806451612903, 'Sc': 0.031099324975891997, 'Sod': 0.029211087420042643, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.028782894736842105, 'Cad': 0.027443609022556388, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959970>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0013584349626462237), 'Al': np.float64(0.0), 'Su': np.float64(0.47474379965483027), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.04399232893326353), 'Pcc': np.float64(0.16856320606488218), 'Ba': np.float64(0.4802761513677171), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.6643681981599265), 'Sc': np.float64(0.3175887058906306), 'Sod': np.float64(0.1768206378366307), 'Pot': np.float64(0.3058012551408796), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.36557533689946015), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4576724665972343), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.06276528851159781), 'Pe': np.float64(0.09884227997676022), 'Ane': np.float64(0.337644789537611)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.029551337359792925, 'Su': 0.030330882352941176, 'Rbc': 0.02786377708978328, 'Pc': 0.028006267136701922, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.028309409888357256, 'Bu': 0.03225806451612903, 'Sc': 0.031099324975891997, 'Sod': 0.029211087420042643, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.028782894736842105, 'Cad': 0.027443609022556388, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Pcv', 'Rbcc', 'Ane', 'Ba', 'Al', 'Pot']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959DF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0013584349626462237), 'Al': np.float64(0.0), 'Su': np.float64(0.47474379965483027), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.04399232893326353), 'Pcc': np.float64(0.16856320606488218), 'Ba': np.float64(0.4802761513677171), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.6643681981599265), 'Sc': np.float64(0.3175887058906306), 'Sod': np.float64(0.1768206378366307), 'Pot': np.float64(0.3058012551408796), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.36557533689946015), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4576724665972343), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.06276528851159781), 'Pe': np.float64(0.09884227997676022), 'Ane': np.float64(0.337644789537611)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.029551337359792925, 'Su': 0.030330882352941176, 'Rbc': 0.02786377708978328, 'Pc': 0.028006267136701922, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.028309409888357256, 'Bu': 0.03225806451612903, 'Sc': 0.031099324975891997, 'Sod': 0.029211087420042643, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.028782894736842105, 'Cad': 0.027443609022556388, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Pcv', 'Rbcc', 'Ane', 'Ba', 'Al', 'Pot', 'Sod', 'Sg', 'Htn', 'Pe', 'Dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95B890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12465052603224025), 'Sg': np.float64(0.00016932963267443844), 'Al': np.float64(0.0), 'Su': np.float64(0.05917706435751907), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.005483666942914642), 'Pcc': np.float64(0.021011492305668473), 'Ba': np.float64(0.059866674908725784), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.08281384537972647), 'Sc': np.float64(0.03958759925116554), 'Sod': np.float64(0.02204078551969226), 'Pot': np.float64(0.038118287314629955), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.045569158048931156), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.057049113711818165), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.007823726229535992), 'Pe': np.float64(0.01232074219332913), 'Ane': np.float64(0.04208760062790826)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0013584349626462237), 'Al': np.float64(0.0), 'Su': np.float64(0.47474379965483027), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.04399232893326353), 'Pcc': np.float64(0.16856320606488218), 'Ba': np.float64(0.4802761513677171), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.6643681981599265), 'Sc': np.float64(0.3175887058906306), 'Sod': np.float64(0.1768206378366307), 'Pot': np.float64(0.3058012551408796), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.36557533689946015), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4576724665972343), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.06276528851159781), 'Pe': np.float64(0.09884227997676022), 'Ane': np.float64(0.337644789537611)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02786377708978328, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.029551337359792925, 'Su': 0.030330882352941176, 'Rbc': 0.02786377708978328, 'Pc': 0.028006267136701922, 'Pcc': 0.028169014084507043, 'Ba': 0.029957522915269395, 'Bgr': 0.028309409888357256, 'Bu': 0.03225806451612903, 'Sc': 0.031099324975891997, 'Sod': 0.029211087420042643, 'Pot': 0.029418126757516764, 'Hemo': 0.02854251012145749, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027242401779095628, 'Rbcc': 0.030090497737556562, 'Htn': 0.029030910609857977, 'Dm': 0.028782894736842105, 'Cad': 0.027443609022556388, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bu', 'Bp', 'Sc', 'Su', 'Pcv', 'Rbcc', 'Ane', 'Ba', 'Al', 'Pot', 'Sod', 'Sg', 'Htn', 'Pe', 'Dm', 'Hemo', 'Bgr', 'Pcc', 'Pc', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 08/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDFFB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.42690625033263085), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.6057694321013894), 'Bgr': np.float64(0.03305204567076818), 'Bu': np.float64(0.32395560192257583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.4638714220071359), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.15611050043469712), 'Wbcc': np.float64(0.40240204418284076), 'Rbcc': np.float64(0.33911542670544875), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.348586217375635), 'Pe': np.float64(0.7607606713317523), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.030090497737556562, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.029236022193768675, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.03055037313432836, 'Hemo': 0.029273504273504274, 'Pcv': 0.029437229437229435, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 5 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Al']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBED50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.42690625033263085), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.6057694321013894), 'Bgr': np.float64(0.03305204567076818), 'Bu': np.float64(0.32395560192257583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.4638714220071359), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.15611050043469712), 'Wbcc': np.float64(0.40240204418284076), 'Rbcc': np.float64(0.33911542670544875), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.348586217375635), 'Pe': np.float64(0.7607606713317523), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.030090497737556562, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.029236022193768675, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.03055037313432836, 'Hemo': 0.029273504273504274, 'Pcv': 0.029437229437229435, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 10 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Al', 'Sc', 'Su', 'Ba', 'Sg', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDDBB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.42690625033263085), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.6057694321013894), 'Bgr': np.float64(0.03305204567076818), 'Bu': np.float64(0.32395560192257583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.4638714220071359), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.15611050043469712), 'Wbcc': np.float64(0.40240204418284076), 'Rbcc': np.float64(0.33911542670544875), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.348586217375635), 'Pe': np.float64(0.7607606713317523), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.030090497737556562, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.029236022193768675, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.03055037313432836, 'Hemo': 0.029273504273504274, 'Pcv': 0.029437229437229435, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 15 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Al', 'Sc', 'Su', 'Ba', 'Sg', 'Htn', 'Dm', 'Pcv', 'Rbcc', 'Hemo', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDCD70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10072086977951457), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.04299836884781376), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.061013624087094535), 'Bgr': np.float64(0.00332903078795201), 'Bu': np.float64(0.03262908999558802), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.04672153309041898), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.015723585385497982), 'Wbcc': np.float64(0.04053028389115037), 'Rbcc': np.float64(0.03415600073342402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03510990700722489), 'Pe': np.float64(0.0766244765105815), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.42690625033263085), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.6057694321013894), 'Bgr': np.float64(0.03305204567076818), 'Bu': np.float64(0.32395560192257583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.4638714220071359), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.15611050043469712), 'Wbcc': np.float64(0.40240204418284076), 'Rbcc': np.float64(0.33911542670544875), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.348586217375635), 'Pe': np.float64(0.7607606713317523), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.030090497737556562, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.029236022193768675, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.03055037313432836, 'Hemo': 0.029273504273504274, 'Pcv': 0.029437229437229435, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02900988017658188, 'Pe': 0.031054405392392875, 'Ane': 0.02904040404040404}
Top 20 Features Selected: ['Bp', 'Pe', 'Bu', 'Pot', 'Al', 'Sc', 'Su', 'Ba', 'Sg', 'Htn', 'Dm', 'Pcv', 'Rbcc', 'Hemo', 'Bgr', 'Wbcc', 'Ane', 'Appet', 'Sod', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 09/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14115222923749052), 'Al': np.float64(0.19598991111034175), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.025175476267600316), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.510777003596213), 'Bgr': np.float64(0.3606686445637868), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.08590296581290206), 'Hemo': np.float64(0.10435881310797909), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.14413936259553514), 'Rbcc': np.float64(0.11898035692239683), 'Htn': np.float64(0.02626323833254141), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.16726977237121904)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.032018442622950824, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.029827662395050816, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.029211087420042643, 'Hemo': 0.029877369007803793, 'Pcv': 0.028850145288501453, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 5 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDDD90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14115222923749052), 'Al': np.float64(0.19598991111034175), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.025175476267600316), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.510777003596213), 'Bgr': np.float64(0.3606686445637868), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.08590296581290206), 'Hemo': np.float64(0.10435881310797909), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.14413936259553514), 'Rbcc': np.float64(0.11898035692239683), 'Htn': np.float64(0.02626323833254141), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.16726977237121904)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.032018442622950824, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.029827662395050816, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.029211087420042643, 'Hemo': 0.029877369007803793, 'Pcv': 0.028850145288501453, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 10 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Ba', 'Sc', 'Htn', 'Hemo', 'Bu']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC950>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14115222923749052), 'Al': np.float64(0.19598991111034175), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.025175476267600316), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.510777003596213), 'Bgr': np.float64(0.3606686445637868), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.08590296581290206), 'Hemo': np.float64(0.10435881310797909), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.14413936259553514), 'Rbcc': np.float64(0.11898035692239683), 'Htn': np.float64(0.02626323833254141), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.16726977237121904)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.032018442622950824, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.029827662395050816, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.029211087420042643, 'Hemo': 0.029877369007803793, 'Pcv': 0.028850145288501453, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 15 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Ba', 'Sc', 'Htn', 'Hemo', 'Bu', 'Rbcc', 'Dm', 'Wbcc', 'Pot', 'Pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE9589B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.17667458247264536), 'Sg': np.float64(0.024938011165616763), 'Al': np.float64(0.03462643571427051), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.004447866758128278), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09024131384698982), 'Bgr': np.float64(0.06372098218928196), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.015176870618156401), 'Hemo': np.float64(0.018437549733193035), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.025465761704439406), 'Rbcc': np.float64(0.02102080488171078), 'Htn': np.float64(0.004640046666781328), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029552317193979556)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.14115222923749052), 'Al': np.float64(0.19598991111034175), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.025175476267600316), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.510777003596213), 'Bgr': np.float64(0.3606686445637868), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.08590296581290206), 'Hemo': np.float64(0.10435881310797909), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.14413936259553514), 'Rbcc': np.float64(0.11898035692239683), 'Htn': np.float64(0.02626323833254141), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.16726977237121904)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.032018442622950824, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.031024531024531024, 'Bu': 0.029827662395050816, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.029211087420042643, 'Hemo': 0.029877369007803793, 'Pcv': 0.028850145288501453, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.02862400327131466, 'Ane': 0.030536130536130537}
Top 20 Features Selected: ['Bp', 'Al', 'Bgr', 'Sg', 'Ane', 'Ba', 'Sc', 'Htn', 'Hemo', 'Bu', 'Rbcc', 'Dm', 'Wbcc', 'Pot', 'Pcv', 'Sod', 'Pe', 'Age', 'Su', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 10/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958470>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.5576463434465841), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.04474851380150829), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.20516706286124436), 'Sod': np.float64(0.0), 'Pot': np.float64(0.07643204615587064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.48242060841557527), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06802261822013655), 'Htn': np.float64(0.0), 'Dm': np.float64(0.032989153604144485), 'Cad': np.float64(0.15934540936753272), 'Appet': np.float64(0.07086239769437465), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028577260665441927, 'Ba': 0.028169014084507043, 'Bgr': 0.029236022193768675, 'Bu': 0.03021353930031804, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.029910714285714284, 'Cad': 0.02967032967032967, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Al']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDFC50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.5576463434465841), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.04474851380150829), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.20516706286124436), 'Sod': np.float64(0.0), 'Pot': np.float64(0.07643204615587064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.48242060841557527), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06802261822013655), 'Htn': np.float64(0.0), 'Dm': np.float64(0.032989153604144485), 'Cad': np.float64(0.15934540936753272), 'Appet': np.float64(0.07086239769437465), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028577260665441927, 'Ba': 0.028169014084507043, 'Bgr': 0.029236022193768675, 'Bu': 0.03021353930031804, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.029910714285714284, 'Cad': 0.02967032967032967, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Al', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FED34C50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.5576463434465841), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.04474851380150829), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.20516706286124436), 'Sod': np.float64(0.0), 'Pot': np.float64(0.07643204615587064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.48242060841557527), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06802261822013655), 'Htn': np.float64(0.0), 'Dm': np.float64(0.032989153604144485), 'Cad': np.float64(0.15934540936753272), 'Appet': np.float64(0.07086239769437465), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028577260665441927, 'Ba': 0.028169014084507043, 'Bgr': 0.029236022193768675, 'Bu': 0.03021353930031804, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.029910714285714284, 'Cad': 0.02967032967032967, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Al', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm', 'Cad', 'Hemo', 'Rbcc', 'Bgr', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959370>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.192624918453394), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.10741658143223161), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.00861967882192611), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.039520288752969555), 'Sod': np.float64(0.0), 'Pot': np.float64(0.014722716658000628), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0929262303562869), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.013102851287640157), 'Htn': np.float64(0.0), 'Dm': np.float64(0.00635453302284482), 'Cad': np.float64(0.030693896485343673), 'Appet': np.float64(0.01364986357729089), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.5576463434465841), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.04474851380150829), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.20516706286124436), 'Sod': np.float64(0.0), 'Pot': np.float64(0.07643204615587064), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.48242060841557527), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06802261822013655), 'Htn': np.float64(0.0), 'Dm': np.float64(0.032989153604144485), 'Cad': np.float64(0.15934540936753272), 'Appet': np.float64(0.07086239769437465), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028577260665441927, 'Ba': 0.028169014084507043, 'Bgr': 0.029236022193768675, 'Bu': 0.03021353930031804, 'Sc': 0.032018442622950824, 'Sod': 0.02900988017658188, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.029411764705882353, 'Htn': 0.029957522915269395, 'Dm': 0.029910714285714284, 'Cad': 0.02967032967032967, 'Appet': 0.02900988017658188, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Al', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm', 'Cad', 'Hemo', 'Rbcc', 'Bgr', 'Ane', 'Sod', 'Appet', 'Pe', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 11/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958A10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09533995358850705), 'Al': np.float64(0.0), 'Su': np.float64(0.46877578106941487), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.3119131879064476), 'Bgr': np.float64(0.13225643543540277), 'Bu': np.float64(0.14004051296086145), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.15337085911174778), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07606894009968058), 'Wbcc': np.float64(0.030611896913331486), 'Rbcc': np.float64(0.16677874094655545), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02313126328537505), 'Pe': np.float64(0.1109537838738393), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.03007688828584351, 'Bu': 0.03128054740957967, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.029083245521601686, 'Pcv': 0.029437229437229435, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBF890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09533995358850705), 'Al': np.float64(0.0), 'Su': np.float64(0.46877578106941487), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.3119131879064476), 'Bgr': np.float64(0.13225643543540277), 'Bu': np.float64(0.14004051296086145), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.15337085911174778), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07606894009968058), 'Wbcc': np.float64(0.030611896913331486), 'Rbcc': np.float64(0.16677874094655545), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02313126328537505), 'Pe': np.float64(0.1109537838738393), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.03007688828584351, 'Bu': 0.03128054740957967, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.029083245521601686, 'Pcv': 0.029437229437229435, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Rbcc', 'Pot', 'Al', 'Sc', 'Bgr', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95A390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09533995358850705), 'Al': np.float64(0.0), 'Su': np.float64(0.46877578106941487), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.3119131879064476), 'Bgr': np.float64(0.13225643543540277), 'Bu': np.float64(0.14004051296086145), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.15337085911174778), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07606894009968058), 'Wbcc': np.float64(0.030611896913331486), 'Rbcc': np.float64(0.16677874094655545), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02313126328537505), 'Pe': np.float64(0.1109537838738393), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.03007688828584351, 'Bu': 0.03128054740957967, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.029083245521601686, 'Pcv': 0.029437229437229435, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Rbcc', 'Pot', 'Al', 'Sc', 'Bgr', 'Ba', 'Pe', 'Htn', 'Pcv', 'Dm', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95A150>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1910950539733002), 'Sg': np.float64(0.01821899357680769), 'Al': np.float64(0.0), 'Su': np.float64(0.0895807331848358), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.05960506747796673), 'Bgr': np.float64(0.025273550667844587), 'Bu': np.float64(0.026761049382704464), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.029308412599890865), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.014536398214040201), 'Wbcc': np.float64(0.005849782092878182), 'Rbcc': np.float64(0.03187059250278107), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.004420270005989362), 'Pe': np.float64(0.021202719317913208), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.09533995358850705), 'Al': np.float64(0.0), 'Su': np.float64(0.46877578106941487), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.3119131879064476), 'Bgr': np.float64(0.13225643543540277), 'Bu': np.float64(0.14004051296086145), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.15337085911174778), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07606894009968058), 'Wbcc': np.float64(0.030611896913331486), 'Rbcc': np.float64(0.16677874094655545), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02313126328537505), 'Pe': np.float64(0.1109537838738393), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030834914611005692, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.03007688828584351, 'Bu': 0.03128054740957967, 'Sc': 0.03009207275993712, 'Sod': 0.02862400327131466, 'Pot': 0.030309988518943745, 'Hemo': 0.029083245521601686, 'Pcv': 0.029437229437229435, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Bu', 'Su', 'Sg', 'Rbcc', 'Pot', 'Al', 'Sc', 'Bgr', 'Ba', 'Pe', 'Htn', 'Pcv', 'Dm', 'Hemo', 'Ane', 'Sod', 'Age', 'Rbc', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 12/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06680636959275191), 'Al': np.float64(0.0), 'Su': np.float64(0.36858226043634096), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5539666030196482), 'Bgr': np.float64(0.01133260688932349), 'Bu': np.float64(0.26120603122291614), 'Sc': np.float64(0.0), 'Sod': np.float64(0.17546963483587438), 'Pot': np.float64(0.03799518379954242), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.19218447382724516), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4961747641366402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.008962551215451812), 'Ane': np.float64(0.14882298411806807)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03009207275993712, 'Sod': 0.029850746268656716, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.03057889822595705, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.029857397504456328}
Top 5 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Sg', 'Su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95BBF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06680636959275191), 'Al': np.float64(0.0), 'Su': np.float64(0.36858226043634096), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5539666030196482), 'Bgr': np.float64(0.01133260688932349), 'Bu': np.float64(0.26120603122291614), 'Sc': np.float64(0.0), 'Sod': np.float64(0.17546963483587438), 'Pot': np.float64(0.03799518379954242), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.19218447382724516), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4961747641366402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.008962551215451812), 'Ane': np.float64(0.14882298411806807)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03009207275993712, 'Sod': 0.029850746268656716, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.03057889822595705, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.029857397504456328}
Top 10 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Sg', 'Su', 'Pcv', 'Ba', 'Al', 'Sc', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95B650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06680636959275191), 'Al': np.float64(0.0), 'Su': np.float64(0.36858226043634096), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5539666030196482), 'Bgr': np.float64(0.01133260688932349), 'Bu': np.float64(0.26120603122291614), 'Sc': np.float64(0.0), 'Sod': np.float64(0.17546963483587438), 'Pot': np.float64(0.03799518379954242), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.19218447382724516), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4961747641366402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.008962551215451812), 'Ane': np.float64(0.14882298411806807)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03009207275993712, 'Sod': 0.029850746268656716, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.03057889822595705, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.029857397504456328}
Top 15 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Sg', 'Su', 'Pcv', 'Ba', 'Al', 'Sc', 'Ane', 'Sod', 'Htn', 'Dm', 'Bgr', 'Pot']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95AED0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.1286292490579896), 'Sg': np.float64(0.008593253153006188), 'Al': np.float64(0.0), 'Su': np.float64(0.04741045937602288), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.07125630814962278), 'Bgr': np.float64(0.0014577047140430799), 'Bu': np.float64(0.033598735645621484), 'Sc': np.float64(0.0), 'Sod': np.float64(0.022570527361418173), 'Pot': np.float64(0.004887291959955433), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0247205445490034), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06382258731242113), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0011528462324873383), 'Ane': np.float64(0.019142988689676208)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.06680636959275191), 'Al': np.float64(0.0), 'Su': np.float64(0.36858226043634096), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5539666030196482), 'Bgr': np.float64(0.01133260688932349), 'Bu': np.float64(0.26120603122291614), 'Sc': np.float64(0.0), 'Sod': np.float64(0.17546963483587438), 'Pot': np.float64(0.03799518379954242), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.19218447382724516), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.4961747641366402), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.008962551215451812), 'Ane': np.float64(0.14882298411806807)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03009207275993712, 'Sod': 0.029850746268656716, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.030303030303030304, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.03057889822595705, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.027783137179239824, 'Pe': 0.028814262023217248, 'Ane': 0.029857397504456328}
Top 20 Features Selected: ['Bp', 'Bu', 'Rbcc', 'Sg', 'Su', 'Pcv', 'Ba', 'Al', 'Sc', 'Ane', 'Sod', 'Htn', 'Dm', 'Bgr', 'Pot', 'Hemo', 'Pe', 'Age', 'Rbc', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 13/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958BF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1917538595558653), 'Al': np.float64(0.0), 'Su': np.float64(0.06890073419913043), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.4385798010296805), 'Bgr': np.float64(0.14236491552049307), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0754188830045731), 'Sod': np.float64(0.0), 'Pot': np.float64(0.17485890684348232), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6429193027789061), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2388908756856638), 'Htn': np.float64(0.008620612957174869), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.15297055440463803), 'Pe': np.float64(0.13301422486637168), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03125763125763126, 'Al': 0.03009207275993712, 'Su': 0.028790389395194696, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.03007688828584351, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02900988017658188, 'Pe': 0.029418126757516764, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95A990>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1917538595558653), 'Al': np.float64(0.0), 'Su': np.float64(0.06890073419913043), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.4385798010296805), 'Bgr': np.float64(0.14236491552049307), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0754188830045731), 'Sod': np.float64(0.0), 'Pot': np.float64(0.17485890684348232), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6429193027789061), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2388908756856638), 'Htn': np.float64(0.008620612957174869), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.15297055440463803), 'Pe': np.float64(0.13301422486637168), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03125763125763126, 'Al': 0.03009207275993712, 'Su': 0.028790389395194696, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.03007688828584351, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02900988017658188, 'Pe': 0.029418126757516764, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Al', 'Pot', 'Ba', 'Bgr', 'Bu']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95A6F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1917538595558653), 'Al': np.float64(0.0), 'Su': np.float64(0.06890073419913043), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.4385798010296805), 'Bgr': np.float64(0.14236491552049307), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0754188830045731), 'Sod': np.float64(0.0), 'Pot': np.float64(0.17485890684348232), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6429193027789061), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2388908756856638), 'Htn': np.float64(0.008620612957174869), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.15297055440463803), 'Pe': np.float64(0.13301422486637168), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03125763125763126, 'Al': 0.03009207275993712, 'Su': 0.028790389395194696, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.03007688828584351, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02900988017658188, 'Pe': 0.029418126757516764, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Al', 'Pot', 'Ba', 'Bgr', 'Bu', 'Htn', 'Pe', 'Dm', 'Hemo', 'Appet']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE9592B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.15437969416390704), 'Sg': np.float64(0.02960290219298327), 'Al': np.float64(0.0), 'Su': np.float64(0.010636874273330404), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.06770781554942928), 'Bgr': np.float64(0.02197825211772418), 'Bu': np.float64(0.0), 'Sc': np.float64(0.011643144092429482), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02699466456033191), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.09925368533507986), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.036879900326900715), 'Htn': np.float64(0.0013308475918340705), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02361554740507132), 'Pe': np.float64(0.020534695354319617), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.1917538595558653), 'Al': np.float64(0.0), 'Su': np.float64(0.06890073419913043), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.4385798010296805), 'Bgr': np.float64(0.14236491552049307), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0754188830045731), 'Sod': np.float64(0.0), 'Pot': np.float64(0.17485890684348232), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.6429193027789061), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2388908756856638), 'Htn': np.float64(0.008620612957174869), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.15297055440463803), 'Pe': np.float64(0.13301422486637168), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.03125763125763126, 'Al': 0.03009207275993712, 'Su': 0.028790389395194696, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.029957522915269395, 'Bgr': 0.029857397504456328, 'Bu': 0.029827662395050816, 'Sc': 0.030679156908665108, 'Sod': 0.02862400327131466, 'Pot': 0.03007688828584351, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.02900988017658188, 'Pe': 0.029418126757516764, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Pcv', 'Sg', 'Sc', 'Rbcc', 'Al', 'Pot', 'Ba', 'Bgr', 'Bu', 'Htn', 'Pe', 'Dm', 'Hemo', 'Appet', 'Ane', 'Su', 'Sod', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 14/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959070>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07580720333055466), 'Al': np.float64(0.0), 'Su': np.float64(0.3104009611460262), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22768499561204036), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.3148186858234383), 'Sc': np.float64(0.0), 'Sod': np.float64(0.10445093689505651), 'Pot': np.float64(0.20962781435450267), 'Hemo': np.float64(0.009881271662104063), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.3359994373672786), 'Pe': np.float64(0.05357482060149048), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03057889822595705, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.03200204813108039, 'Sc': 0.03047794966520434, 'Sod': 0.029850746268656716, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028790389395194696, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.03021353930031804, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Bu', 'Sg', 'Al', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958AD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07580720333055466), 'Al': np.float64(0.0), 'Su': np.float64(0.3104009611460262), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22768499561204036), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.3148186858234383), 'Sc': np.float64(0.0), 'Sod': np.float64(0.10445093689505651), 'Pot': np.float64(0.20962781435450267), 'Hemo': np.float64(0.009881271662104063), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.3359994373672786), 'Pe': np.float64(0.05357482060149048), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03057889822595705, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.03200204813108039, 'Sc': 0.03047794966520434, 'Sod': 0.029850746268656716, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028790389395194696, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.03021353930031804, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Bu', 'Sg', 'Al', 'Sc', 'Su', 'Appet', 'Pot', 'Htn', 'Sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07580720333055466), 'Al': np.float64(0.0), 'Su': np.float64(0.3104009611460262), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22768499561204036), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.3148186858234383), 'Sc': np.float64(0.0), 'Sod': np.float64(0.10445093689505651), 'Pot': np.float64(0.20962781435450267), 'Hemo': np.float64(0.009881271662104063), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.3359994373672786), 'Pe': np.float64(0.05357482060149048), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03057889822595705, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.03200204813108039, 'Sc': 0.03047794966520434, 'Sod': 0.029850746268656716, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028790389395194696, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.03021353930031804, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Bu', 'Sg', 'Al', 'Sc', 'Su', 'Appet', 'Pot', 'Htn', 'Sod', 'Dm', 'Hemo', 'Ba', 'Pe', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95ADB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12895399546187453), 'Sg': np.float64(0.009775641754265745), 'Al': np.float64(0.0), 'Su': np.float64(0.040027444134986156), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.029360889890891976), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.040597127382988964), 'Sc': np.float64(0.0), 'Sod': np.float64(0.01346936564235366), 'Pot': np.float64(0.027032344220953214), 'Hemo': np.float64(0.0012742294610725167), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04332846992145244), 'Pe': np.float64(0.006908687172715345), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.07580720333055466), 'Al': np.float64(0.0), 'Su': np.float64(0.3104009611460262), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22768499561204036), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.3148186858234383), 'Sc': np.float64(0.0), 'Sod': np.float64(0.10445093689505651), 'Pot': np.float64(0.20962781435450267), 'Hemo': np.float64(0.009881271662104063), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.3359994373672786), 'Pe': np.float64(0.05357482060149048), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03057889822595705, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.02946912242686891, 'Bgr': 0.029236022193768675, 'Bu': 0.03200204813108039, 'Sc': 0.03047794966520434, 'Sod': 0.029850746268656716, 'Pot': 0.03007688828584351, 'Hemo': 0.02967032967032967, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028790389395194696, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.03021353930031804, 'Pe': 0.029418126757516764, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Bu', 'Sg', 'Al', 'Sc', 'Su', 'Appet', 'Pot', 'Htn', 'Sod', 'Dm', 'Hemo', 'Ba', 'Pe', 'Bgr', 'Pcv', 'Ane', 'Age', 'Rbc', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 15/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95B350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.07134477036490218), 'Su': np.float64(0.09614355821974832), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2634900752327077), 'Bgr': np.float64(0.1882177110168292), 'Bu': np.float64(0.2220288537671308), 'Sc': np.float64(0.1646319701557792), 'Sod': np.float64(0.019784514559903772), 'Pot': np.float64(0.34477638669898947), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5463954841969012), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2065943497084811), 'Htn': np.float64(0.16247932191206826), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.204914683741895), 'Pe': np.float64(0.0), 'Ane': np.float64(0.04834741767871811)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.03028233151183971, 'Su': 0.028790389395194696, 'Rbc': 0.02803921568627451, 'Pc': 0.02782608695652174, 'Pcc': 0.027417840375586856, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.0315136476426799, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030798389007344232, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029857397504456328, 'Htn': 0.030158730158730156, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.02900988017658188, 'Pe': 0.028258706467661692, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Pot']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958110>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.07134477036490218), 'Su': np.float64(0.09614355821974832), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2634900752327077), 'Bgr': np.float64(0.1882177110168292), 'Bu': np.float64(0.2220288537671308), 'Sc': np.float64(0.1646319701557792), 'Sod': np.float64(0.019784514559903772), 'Pot': np.float64(0.34477638669898947), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5463954841969012), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2065943497084811), 'Htn': np.float64(0.16247932191206826), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.204914683741895), 'Pe': np.float64(0.0), 'Ane': np.float64(0.04834741767871811)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.03028233151183971, 'Su': 0.028790389395194696, 'Rbc': 0.02803921568627451, 'Pc': 0.02782608695652174, 'Pcc': 0.027417840375586856, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.0315136476426799, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030798389007344232, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029857397504456328, 'Htn': 0.030158730158730156, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.02900988017658188, 'Pe': 0.028258706467661692, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Pot', 'Al', 'Htn', 'Bgr', 'Rbcc', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95BEF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.07134477036490218), 'Su': np.float64(0.09614355821974832), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2634900752327077), 'Bgr': np.float64(0.1882177110168292), 'Bu': np.float64(0.2220288537671308), 'Sc': np.float64(0.1646319701557792), 'Sod': np.float64(0.019784514559903772), 'Pot': np.float64(0.34477638669898947), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5463954841969012), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2065943497084811), 'Htn': np.float64(0.16247932191206826), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.204914683741895), 'Pe': np.float64(0.0), 'Ane': np.float64(0.04834741767871811)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.03028233151183971, 'Su': 0.028790389395194696, 'Rbc': 0.02803921568627451, 'Pc': 0.02782608695652174, 'Pcc': 0.027417840375586856, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.0315136476426799, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030798389007344232, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029857397504456328, 'Htn': 0.030158730158730156, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.02900988017658188, 'Pe': 0.028258706467661692, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Pot', 'Al', 'Htn', 'Bgr', 'Rbcc', 'Ba', 'Sg', 'Appet', 'Dm', 'Ane', 'Su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958170>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14604669449130456), 'Sg': np.float64(0.0), 'Al': np.float64(0.010419667881035148), 'Su': np.float64(0.014041448874626536), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.038481854519002115), 'Bgr': np.float64(0.0274885745387275), 'Bu': np.float64(0.032426580174382685), 'Sc': np.float64(0.024043955048842658), 'Sod': np.float64(0.002889462953589033), 'Pot': np.float64(0.050353451616043196), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07979925435193326), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.03017242187550427), 'Htn': np.float64(0.02372956788844616), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.02992711221323483), 'Pe': np.float64(0.0), 'Ane': np.float64(0.007060980539167241)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.07134477036490218), 'Su': np.float64(0.09614355821974832), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.2634900752327077), 'Bgr': np.float64(0.1882177110168292), 'Bu': np.float64(0.2220288537671308), 'Sc': np.float64(0.1646319701557792), 'Sod': np.float64(0.019784514559903772), 'Pot': np.float64(0.34477638669898947), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5463954841969012), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.2065943497084811), 'Htn': np.float64(0.16247932191206826), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.204914683741895), 'Pe': np.float64(0.0), 'Ane': np.float64(0.04834741767871811)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02803921568627451, 'Bp': 0.032018442622950824, 'Sg': 0.029206349206349208, 'Al': 0.03028233151183971, 'Su': 0.028790389395194696, 'Rbc': 0.02803921568627451, 'Pc': 0.02782608695652174, 'Pcc': 0.027417840375586856, 'Ba': 0.029709507042253523, 'Bgr': 0.029857397504456328, 'Bu': 0.0315136476426799, 'Sc': 0.030886196246139225, 'Sod': 0.028438886647841874, 'Pot': 0.030798389007344232, 'Hemo': 0.02871794871794872, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027417840375586856, 'Rbcc': 0.029857397504456328, 'Htn': 0.030158730158730156, 'Dm': 0.028958333333333336, 'Cad': 0.02761904761904762, 'Appet': 0.02900988017658188, 'Pe': 0.028258706467661692, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Sc', 'Pot', 'Al', 'Htn', 'Bgr', 'Rbcc', 'Ba', 'Sg', 'Appet', 'Dm', 'Ane', 'Su', 'Hemo', 'Sod', 'Pe', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 16/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959310>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}

Normalized Mathematical Scores
{'Age': np.float64(0.05621451357128926), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.32403471623397934), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.08013583360383053), 'Ba': np.float64(0.10862582590065636), 'Bgr': np.float64(0.1656000759438183), 'Bu': np.float64(0.0970213868809636), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03260675681425043), 'Pot': np.float64(0.5646241122628519), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.3983529319321443), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.08555511953948897), 'Pe': np.float64(0.0), 'Ane': np.float64(0.08567759120078992)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.028370221327967807, 'Ba': 0.029236022193768675, 'Bgr': 0.030536130536130537, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.028814262023217248, 'Pot': 0.031054405392392875, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028404512489927477, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.02862400327131466, 'Ane': 0.029857397504456328}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Pcv', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958CB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}

Normalized Mathematical Scores
{'Age': np.float64(0.05621451357128926), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.32403471623397934), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.08013583360383053), 'Ba': np.float64(0.10862582590065636), 'Bgr': np.float64(0.1656000759438183), 'Bu': np.float64(0.0970213868809636), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03260675681425043), 'Pot': np.float64(0.5646241122628519), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.3983529319321443), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.08555511953948897), 'Pe': np.float64(0.0), 'Ane': np.float64(0.08567759120078992)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.028370221327967807, 'Ba': 0.029236022193768675, 'Bgr': 0.030536130536130537, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.028814262023217248, 'Pot': 0.031054405392392875, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028404512489927477, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.02862400327131466, 'Ane': 0.029857397504456328}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Al', 'Sc', 'Ane', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95BD10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}

Normalized Mathematical Scores
{'Age': np.float64(0.05621451357128926), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.32403471623397934), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.08013583360383053), 'Ba': np.float64(0.10862582590065636), 'Bgr': np.float64(0.1656000759438183), 'Bu': np.float64(0.0970213868809636), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03260675681425043), 'Pot': np.float64(0.5646241122628519), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.3983529319321443), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.08555511953948897), 'Pe': np.float64(0.0), 'Ane': np.float64(0.08567759120078992)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.028370221327967807, 'Ba': 0.029236022193768675, 'Bgr': 0.030536130536130537, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.028814262023217248, 'Pot': 0.031054405392392875, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028404512489927477, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.02862400327131466, 'Ane': 0.029857397504456328}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Al', 'Sc', 'Ane', 'Sg', 'Htn', 'Dm', 'Ba', 'Hemo', 'Sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959F70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.009975241995533637), 'Bp': np.float64(0.17744958306689584), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.05749982529491954), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.01422007026171787), 'Ba': np.float64(0.019275607516368688), 'Bgr': np.float64(0.029385664432076845), 'Bu': np.float64(0.01721640465059899), 'Sc': np.float64(0.0), 'Sod': np.float64(0.005786055401852405), 'Pot': np.float64(0.10019231331055926), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07068756168483455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.015181720291520751), 'Pe': np.float64(0.0), 'Ane': np.float64(0.015203452836756117)}

Normalized Mathematical Scores
{'Age': np.float64(0.05621451357128926), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.32403471623397934), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.08013583360383053), 'Ba': np.float64(0.10862582590065636), 'Bgr': np.float64(0.1656000759438183), 'Bu': np.float64(0.0970213868809636), 'Sc': np.float64(0.0), 'Sod': np.float64(0.03260675681425043), 'Pot': np.float64(0.5646241122628519), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.3983529319321443), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.08555511953948897), 'Pe': np.float64(0.0), 'Ane': np.float64(0.08567759120078992)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029571646010002173, 'Al': 0.03009207275993712, 'Su': 0.030330882352941176, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.028370221327967807, 'Ba': 0.029236022193768675, 'Bgr': 0.030536130536130537, 'Bu': 0.031054405392392875, 'Sc': 0.03009207275993712, 'Sod': 0.028814262023217248, 'Pot': 0.031054405392392875, 'Hemo': 0.029083245521601686, 'Pcv': 0.031024531024531024, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.028404512489927477, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.028577260665441927, 'Pe': 0.02862400327131466, 'Ane': 0.029857397504456328}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Al', 'Sc', 'Ane', 'Sg', 'Htn', 'Dm', 'Ba', 'Hemo', 'Sod', 'Age', 'Pe', 'Appet', 'Rbc', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 17/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95BB30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.34269484513719345), 'Rbc': np.float64(0.08446607423232809), 'Pc': np.float64(0.006541014081750207), 'Pcc': np.float64(0.03180855646119965), 'Ba': np.float64(0.42436655048226085), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.15770678191005205), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1835922379551009), 'Htn': np.float64(0.0), 'Dm': np.float64(0.06118445112066152), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.11609158093397608), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.02877846790890269, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.02900988017658188, 'Hemo': 0.02946912242686891, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029957522915269395, 'Dm': 0.030330882352941176, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.03007688828584351, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Bu', 'Su', 'Al', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE95A8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.34269484513719345), 'Rbc': np.float64(0.08446607423232809), 'Pc': np.float64(0.006541014081750207), 'Pcc': np.float64(0.03180855646119965), 'Ba': np.float64(0.42436655048226085), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.15770678191005205), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1835922379551009), 'Htn': np.float64(0.0), 'Dm': np.float64(0.06118445112066152), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.11609158093397608), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.02877846790890269, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.02900988017658188, 'Hemo': 0.02946912242686891, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029957522915269395, 'Dm': 0.030330882352941176, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.03007688828584351, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Bu', 'Su', 'Al', 'Sc', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Sg']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDE5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.34269484513719345), 'Rbc': np.float64(0.08446607423232809), 'Pc': np.float64(0.006541014081750207), 'Pcc': np.float64(0.03180855646119965), 'Ba': np.float64(0.42436655048226085), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.15770678191005205), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1835922379551009), 'Htn': np.float64(0.0), 'Dm': np.float64(0.06118445112066152), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.11609158093397608), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.02877846790890269, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.02900988017658188, 'Hemo': 0.02946912242686891, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029957522915269395, 'Dm': 0.030330882352941176, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.03007688828584351, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Bu', 'Su', 'Al', 'Sc', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Sg', 'Htn', 'Rbc', 'Hemo', 'Bgr', 'Pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDEF30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.21103048207941863), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07231905837543365), 'Rbc': np.float64(0.017824916364604156), 'Pc': np.float64(0.0013803533549600119), 'Pcc': np.float64(0.006712575004257369), 'Ba': np.float64(0.08955427772665145), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.03328093821367202), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.038743558481704285), 'Htn': np.float64(0.0), 'Dm': np.float64(0.012911784215757827), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.024498862289858817), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.34269484513719345), 'Rbc': np.float64(0.08446607423232809), 'Pc': np.float64(0.006541014081750207), 'Pcc': np.float64(0.03180855646119965), 'Ba': np.float64(0.42436655048226085), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.15770678191005205), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.0), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1835922379551009), 'Htn': np.float64(0.0), 'Dm': np.float64(0.06118445112066152), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.11609158093397608), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.02877846790890269, 'Pcc': 0.028577260665441927, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.0315136476426799, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.02900988017658188, 'Hemo': 0.02946912242686891, 'Pcv': 0.029236022193768675, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.030330882352941176, 'Htn': 0.029957522915269395, 'Dm': 0.030330882352941176, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.03007688828584351, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Bu', 'Su', 'Al', 'Sc', 'Rbcc', 'Dm', 'Ba', 'Pe', 'Sg', 'Htn', 'Rbc', 'Hemo', 'Bgr', 'Pcv', 'Ane', 'Sod', 'Pot', 'Age', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 18/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE959490>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.21166094468188917), 'Al': np.float64(0.21780456023623185), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13552356270116106), 'Bgr': np.float64(0.2216773104854038), 'Bu': np.float64(0.43017373264346603), 'Sc': np.float64(0.18445482123419518), 'Sod': np.float64(0.10097730909815587), 'Pot': np.float64(0.15399297367949735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5716673934247269), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1901875299921473), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.44570627667444523), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.031544957774465976, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.028169014084507043, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.030886196246139225, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.028850145288501453}
Top 5 Features Selected: ['Bp', 'Bu', 'Al', 'Pcv', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958E30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.21166094468188917), 'Al': np.float64(0.21780456023623185), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13552356270116106), 'Bgr': np.float64(0.2216773104854038), 'Bu': np.float64(0.43017373264346603), 'Sc': np.float64(0.18445482123419518), 'Sod': np.float64(0.10097730909815587), 'Pot': np.float64(0.15399297367949735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5716673934247269), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1901875299921473), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.44570627667444523), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.031544957774465976, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.028169014084507043, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.030886196246139225, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.028850145288501453}
Top 10 Features Selected: ['Bp', 'Bu', 'Al', 'Pcv', 'Sc', 'Sg', 'Bgr', 'Appet', 'Htn', 'Rbcc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDF8F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.21166094468188917), 'Al': np.float64(0.21780456023623185), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13552356270116106), 'Bgr': np.float64(0.2216773104854038), 'Bu': np.float64(0.43017373264346603), 'Sc': np.float64(0.18445482123419518), 'Sod': np.float64(0.10097730909815587), 'Pot': np.float64(0.15399297367949735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5716673934247269), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1901875299921473), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.44570627667444523), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.031544957774465976, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.028169014084507043, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.030886196246139225, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.028850145288501453}
Top 15 Features Selected: ['Bp', 'Bu', 'Al', 'Pcv', 'Sc', 'Sg', 'Bgr', 'Appet', 'Htn', 'Rbcc', 'Dm', 'Pot', 'Hemo', 'Ane', 'Sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBE450>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12568212595358128), 'Sg': np.float64(0.026601997508963193), 'Al': np.float64(0.02737414017287447), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.017032889477085394), 'Bgr': np.float64(0.027860875657477663), 'Bu': np.float64(0.05406514924801829), 'Sc': np.float64(0.023182674075101436), 'Sod': np.float64(0.012691042880528134), 'Pot': np.float64(0.019354164313953114), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07184837334396203), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.023903173099273575), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05601731240329937), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.21166094468188917), 'Al': np.float64(0.21780456023623185), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13552356270116106), 'Bgr': np.float64(0.2216773104854038), 'Bu': np.float64(0.43017373264346603), 'Sc': np.float64(0.18445482123419518), 'Sod': np.float64(0.10097730909815587), 'Pot': np.float64(0.15399297367949735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5716673934247269), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1901875299921473), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.44570627667444523), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028404512489927477, 'Bp': 0.032018442622950824, 'Sg': 0.030798389007344232, 'Al': 0.031544957774465976, 'Su': 0.028404512489927477, 'Rbc': 0.028404512489927477, 'Pc': 0.02819138376017471, 'Pcc': 0.027783137179239824, 'Ba': 0.028169014084507043, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.030886196246139225, 'Sod': 0.028814262023217248, 'Pot': 0.029211087420042643, 'Hemo': 0.029083245521601686, 'Pcv': 0.03128054740957967, 'Wbcc': 0.027783137179239824, 'Rbcc': 0.029411764705882353, 'Htn': 0.029571646010002173, 'Dm': 0.0293236301369863, 'Cad': 0.027984344422700584, 'Appet': 0.029957522915269395, 'Pe': 0.02862400327131466, 'Ane': 0.028850145288501453}
Top 20 Features Selected: ['Bp', 'Bu', 'Al', 'Pcv', 'Sc', 'Sg', 'Bgr', 'Appet', 'Htn', 'Rbcc', 'Dm', 'Pot', 'Hemo', 'Ane', 'Sod', 'Pe', 'Age', 'Su', 'Rbc', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 19/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE9585F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.15089636905318496), 'Al': np.float64(0.02395440881174475), 'Su': np.float64(0.7482214906901892), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7076981434762203), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1729609147108325), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4311715791579268), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.5862626511911391), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.25445903098391875), 'Pe': np.float64(0.43028407225171067), 'Ane': np.float64(0.28251825388015395)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.028814262023217248, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 5 Features Selected: ['Bp', 'Su', 'Bu', 'Pcv', 'Al']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBC1D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.15089636905318496), 'Al': np.float64(0.02395440881174475), 'Su': np.float64(0.7482214906901892), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7076981434762203), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1729609147108325), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4311715791579268), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.5862626511911391), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.25445903098391875), 'Pe': np.float64(0.43028407225171067), 'Ane': np.float64(0.28251825388015395)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.028814262023217248, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 10 Features Selected: ['Bp', 'Su', 'Bu', 'Pcv', 'Al', 'Rbcc', 'Sc', 'Sg', 'Pe', 'Ane']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC7D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.15089636905318496), 'Al': np.float64(0.02395440881174475), 'Su': np.float64(0.7482214906901892), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7076981434762203), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1729609147108325), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4311715791579268), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.5862626511911391), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.25445903098391875), 'Pe': np.float64(0.43028407225171067), 'Ane': np.float64(0.28251825388015395)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.028814262023217248, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 15 Features Selected: ['Bp', 'Su', 'Bu', 'Pcv', 'Al', 'Rbcc', 'Sc', 'Sg', 'Pe', 'Ane', 'Ba', 'Htn', 'Dm', 'Hemo', 'Bgr']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECBC2F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12663077026554587), 'Sg': np.float64(0.01910812344347889), 'Al': np.float64(0.0030333652390870172), 'Su': np.float64(0.09474786369533361), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.08961636102389056), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0219021738556661), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.054599589185380056), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.07423889109825497), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.03222234309451803), 'Pe': np.float64(0.054487203502229915), 'Ane': np.float64(0.035775504102920935)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.15089636905318496), 'Al': np.float64(0.02395440881174475), 'Su': np.float64(0.7482214906901892), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7076981434762203), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.1729609147108325), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.0), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4311715791579268), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.5862626511911391), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.25445903098391875), 'Pe': np.float64(0.43028407225171067), 'Ane': np.float64(0.28251825388015395)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.03047794966520434, 'Su': 0.030834914611005692, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.029957522915269395, 'Bgr': 0.02904040404040404, 'Bu': 0.030621785881252923, 'Sc': 0.03028233151183971, 'Sod': 0.028814262023217248, 'Pot': 0.028814262023217248, 'Hemo': 0.029273504273504274, 'Pcv': 0.030536130536130537, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.030330882352941176, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.028790389395194696, 'Pe': 0.03007688828584351, 'Ane': 0.03007688828584351}
Top 20 Features Selected: ['Bp', 'Su', 'Bu', 'Pcv', 'Al', 'Rbcc', 'Sc', 'Sg', 'Pe', 'Ane', 'Ba', 'Htn', 'Dm', 'Hemo', 'Bgr', 'Sod', 'Pot', 'Appet', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 20/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FE958C50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.6286300787825484), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5464826873861023), 'Bgr': np.float64(0.3639191199541212), 'Bu': np.float64(0.0), 'Sc': np.float64(0.3048559633588544), 'Sod': np.float64(0.21869253919382733), 'Pot': np.float64(0.3213020112916438), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5690779908616455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13016788048297037), 'Htn': np.float64(0.2936250954204642), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03047794966520434, 'Su': 0.028790389395194696, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03131881575727918, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.03057889822595705, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC2F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.6286300787825484), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5464826873861023), 'Bgr': np.float64(0.3639191199541212), 'Bu': np.float64(0.0), 'Sc': np.float64(0.3048559633588544), 'Sod': np.float64(0.21869253919382733), 'Pot': np.float64(0.3213020112916438), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5690779908616455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13016788048297037), 'Htn': np.float64(0.2936250954204642), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03047794966520434, 'Su': 0.028790389395194696, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03131881575727918, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.03057889822595705, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Al', 'Bu', 'Pot', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD3D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.6286300787825484), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5464826873861023), 'Bgr': np.float64(0.3639191199541212), 'Bu': np.float64(0.0), 'Sc': np.float64(0.3048559633588544), 'Sod': np.float64(0.21869253919382733), 'Pot': np.float64(0.3213020112916438), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5690779908616455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13016788048297037), 'Htn': np.float64(0.2936250954204642), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03047794966520434, 'Su': 0.028790389395194696, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03131881575727918, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.03057889822595705, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Al', 'Bu', 'Pot', 'Ba', 'Dm', 'Hemo', 'Sod', 'Ane', 'Pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD9D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.10951729417158454), 'Sg': np.float64(0.06884586526313471), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.059849305234141836), 'Bgr': np.float64(0.03985543731467965), 'Bu': np.float64(0.0), 'Sc': np.float64(0.033387000219133454), 'Sod': np.float64(0.02395061514802117), 'Pot': np.float64(0.035188126888548735), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.06232388173176912), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.014255634058545125), 'Htn': np.float64(0.03215702595132256), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.6286300787825484), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.5464826873861023), 'Bgr': np.float64(0.3639191199541212), 'Bu': np.float64(0.0), 'Sc': np.float64(0.3048559633588544), 'Sod': np.float64(0.21869253919382733), 'Pot': np.float64(0.3213020112916438), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5690779908616455), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.13016788048297037), 'Htn': np.float64(0.2936250954204642), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.0), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.03200204813108039, 'Al': 0.03047794966520434, 'Su': 0.028790389395194696, 'Rbc': 0.028790389395194696, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03131881575727918, 'Sod': 0.029418126757516764, 'Pot': 0.03007688828584351, 'Hemo': 0.02946912242686891, 'Pcv': 0.031024531024531024, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.03057889822595705, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.028169014084507043, 'Pe': 0.02900988017658188, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Pcv', 'Htn', 'Bgr', 'Al', 'Bu', 'Pot', 'Ba', 'Dm', 'Hemo', 'Sod', 'Ane', 'Pe', 'Rbcc', 'Age', 'Su', 'Rbc', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 21/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDF2F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22588693731605514), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.1525565686740702), 'Sod': np.float64(0.07260103995882397), 'Pot': np.float64(0.27014551302314077), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5045389699822597), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06146303446200639), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.385428445138594), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.030886196246139225, 'Su': 0.02919863597612958, 'Rbc': 0.02919863597612958, 'Pc': 0.028985507246376812, 'Pcc': 0.028577260665441927, 'Ba': 0.02946912242686891, 'Bgr': 0.02964426877470356, 'Bu': 0.030621785881252923, 'Sc': 0.031544957774465976, 'Sod': 0.029850746268656716, 'Pot': 0.03055037313432836, 'Hemo': 0.029877369007803793, 'Pcv': 0.03128054740957967, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029411764705882353, 'Htn': 0.03036576949620428, 'Dm': 0.030117753623188408, 'Cad': 0.02877846790890269, 'Appet': 0.028577260665441927, 'Pe': 0.030798389007344232, 'Ane': 0.02964426877470356}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Al', 'Pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDF6B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22588693731605514), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.1525565686740702), 'Sod': np.float64(0.07260103995882397), 'Pot': np.float64(0.27014551302314077), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5045389699822597), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06146303446200639), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.385428445138594), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.030886196246139225, 'Su': 0.02919863597612958, 'Rbc': 0.02919863597612958, 'Pc': 0.028985507246376812, 'Pcc': 0.028577260665441927, 'Ba': 0.02946912242686891, 'Bgr': 0.02964426877470356, 'Bu': 0.030621785881252923, 'Sc': 0.031544957774465976, 'Sod': 0.029850746268656716, 'Pot': 0.03055037313432836, 'Hemo': 0.029877369007803793, 'Pcv': 0.03128054740957967, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029411764705882353, 'Htn': 0.03036576949620428, 'Dm': 0.030117753623188408, 'Cad': 0.02877846790890269, 'Appet': 0.028577260665441927, 'Pe': 0.030798389007344232, 'Ane': 0.02964426877470356}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Al', 'Pe', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDE030>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22588693731605514), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.1525565686740702), 'Sod': np.float64(0.07260103995882397), 'Pot': np.float64(0.27014551302314077), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5045389699822597), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06146303446200639), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.385428445138594), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.030886196246139225, 'Su': 0.02919863597612958, 'Rbc': 0.02919863597612958, 'Pc': 0.028985507246376812, 'Pcc': 0.028577260665441927, 'Ba': 0.02946912242686891, 'Bgr': 0.02964426877470356, 'Bu': 0.030621785881252923, 'Sc': 0.031544957774465976, 'Sod': 0.029850746268656716, 'Pot': 0.03055037313432836, 'Hemo': 0.029877369007803793, 'Pcv': 0.03128054740957967, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029411764705882353, 'Htn': 0.03036576949620428, 'Dm': 0.030117753623188408, 'Cad': 0.02877846790890269, 'Appet': 0.028577260665441927, 'Pe': 0.030798389007344232, 'Ane': 0.02964426877470356}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Al', 'Pe', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm', 'Hemo', 'Sod', 'Bgr', 'Ane', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDF830>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.11852781729568664), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.026773885635679603), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.018082197099057062), 'Sod': np.float64(0.008605242799716332), 'Pot': np.float64(0.03201975801085637), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.059801902852611194), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.0072850793191511845), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.045683992325947845), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.0), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.22588693731605514), 'Bgr': np.float64(0.0), 'Bu': np.float64(0.0), 'Sc': np.float64(0.1525565686740702), 'Sod': np.float64(0.07260103995882397), 'Pot': np.float64(0.27014551302314077), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.5045389699822597), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.06146303446200639), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.385428445138594), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02919863597612958, 'Bp': 0.032018442622950824, 'Sg': 0.03036576949620428, 'Al': 0.030886196246139225, 'Su': 0.02919863597612958, 'Rbc': 0.02919863597612958, 'Pc': 0.028985507246376812, 'Pcc': 0.028577260665441927, 'Ba': 0.02946912242686891, 'Bgr': 0.02964426877470356, 'Bu': 0.030621785881252923, 'Sc': 0.031544957774465976, 'Sod': 0.029850746268656716, 'Pot': 0.03055037313432836, 'Hemo': 0.029877369007803793, 'Pcv': 0.03128054740957967, 'Wbcc': 0.028577260665441927, 'Rbcc': 0.029411764705882353, 'Htn': 0.03036576949620428, 'Dm': 0.030117753623188408, 'Cad': 0.02877846790890269, 'Appet': 0.028577260665441927, 'Pe': 0.030798389007344232, 'Ane': 0.02964426877470356}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Al', 'Pe', 'Bu', 'Pot', 'Sg', 'Htn', 'Dm', 'Hemo', 'Sod', 'Bgr', 'Ane', 'Ba', 'Rbcc', 'Age', 'Su', 'Rbc', 'Pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 22/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD2B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.057714094127003276), 'Al': np.float64(0.0), 'Su': np.float64(0.24689137946409373), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7154092036002883), 'Bgr': np.float64(0.043825625465038945), 'Bu': np.float64(0.005122387833368701), 'Sc': np.float64(0.0), 'Sod': np.float64(0.5738695982848182), 'Pot': np.float64(0.0009739989055682384), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4568409275748139), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.44688519461242593), 'Htn': np.float64(0.17542679251455762), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.35393401312777506), 'Pe': np.float64(0.0), 'Ane': np.float64(0.23255427144806542)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.029906956136464335, 'Su': 0.029631255487269532, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.029906956136464335, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.030776515151515152, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.029857397504456328}
Top 5 Features Selected: ['Bp', 'Sod', 'Pcv', 'Htn', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDC5F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.057714094127003276), 'Al': np.float64(0.0), 'Su': np.float64(0.24689137946409373), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7154092036002883), 'Bgr': np.float64(0.043825625465038945), 'Bu': np.float64(0.005122387833368701), 'Sc': np.float64(0.0), 'Sod': np.float64(0.5738695982848182), 'Pot': np.float64(0.0009739989055682384), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4568409275748139), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.44688519461242593), 'Htn': np.float64(0.17542679251455762), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.35393401312777506), 'Pe': np.float64(0.0), 'Ane': np.float64(0.23255427144806542)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.029906956136464335, 'Su': 0.029631255487269532, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.029906956136464335, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.030776515151515152, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.029857397504456328}
Top 10 Features Selected: ['Bp', 'Sod', 'Pcv', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Bu', 'Al', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDCDD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.057714094127003276), 'Al': np.float64(0.0), 'Su': np.float64(0.24689137946409373), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7154092036002883), 'Bgr': np.float64(0.043825625465038945), 'Bu': np.float64(0.005122387833368701), 'Sc': np.float64(0.0), 'Sod': np.float64(0.5738695982848182), 'Pot': np.float64(0.0009739989055682384), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4568409275748139), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.44688519461242593), 'Htn': np.float64(0.17542679251455762), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.35393401312777506), 'Pe': np.float64(0.0), 'Ane': np.float64(0.23255427144806542)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.029906956136464335, 'Su': 0.029631255487269532, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.029906956136464335, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.030776515151515152, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.029857397504456328}
Top 15 Features Selected: ['Bp', 'Sod', 'Pcv', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Bu', 'Al', 'Sc', 'Ane', 'Su', 'Bgr', 'Appet', 'Dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDDCD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.12615817951187694), 'Sg': np.float64(0.007281105047239842), 'Al': np.float64(0.0), 'Su': np.float64(0.031147366970366065), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.09025472273225409), 'Bgr': np.float64(0.005528961124638668), 'Bu': np.float64(0.000646231123811583), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0723983437968248), 'Pot': np.float64(0.00012287792877304949), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.057634219749355745), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.056378222603114495), 'Htn': np.float64(0.02213152478124435), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.04465167076353285), 'Pe': np.float64(0.0), 'Ane': np.float64(0.029338623523598794)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.057714094127003276), 'Al': np.float64(0.0), 'Su': np.float64(0.24689137946409373), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7154092036002883), 'Bgr': np.float64(0.043825625465038945), 'Bu': np.float64(0.005122387833368701), 'Sc': np.float64(0.0), 'Sod': np.float64(0.5738695982848182), 'Pot': np.float64(0.0009739989055682384), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.4568409275748139), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.44688519461242593), 'Htn': np.float64(0.17542679251455762), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.35393401312777506), 'Pe': np.float64(0.0), 'Ane': np.float64(0.23255427144806542)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.030158730158730156, 'Al': 0.029906956136464335, 'Su': 0.029631255487269532, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.03021353930031804, 'Bgr': 0.029236022193768675, 'Bu': 0.030017921146953404, 'Sc': 0.029906956136464335, 'Sod': 0.030798389007344232, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.030776515151515152, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.03036576949620428, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.029857397504456328}
Top 20 Features Selected: ['Bp', 'Sod', 'Pcv', 'Htn', 'Ba', 'Sg', 'Rbcc', 'Bu', 'Al', 'Sc', 'Ane', 'Su', 'Bgr', 'Appet', 'Dm', 'Hemo', 'Pot', 'Pe', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 23/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDF170>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.35912313262497586), 'Rbc': np.float64(0.05516611590173663), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7082986130055181), 'Bgr': np.float64(0.12729242384986028), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02937721567409849), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07994916602454165), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.027113726071967225), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.29299900764659004), 'Pe': np.float64(0.051672447366759904), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.03021353930031804, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02946912242686891, 'Pcv': 0.030303030303030304, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Su', 'Bgr', 'Al', 'Sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDEAB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.35912313262497586), 'Rbc': np.float64(0.05516611590173663), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7082986130055181), 'Bgr': np.float64(0.12729242384986028), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02937721567409849), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07994916602454165), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.027113726071967225), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.29299900764659004), 'Pe': np.float64(0.051672447366759904), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.03021353930031804, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02946912242686891, 'Pcv': 0.030303030303030304, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Su', 'Bgr', 'Al', 'Sc', 'Pcv', 'Ba', 'Bu', 'Sg', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDEDB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.35912313262497586), 'Rbc': np.float64(0.05516611590173663), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7082986130055181), 'Bgr': np.float64(0.12729242384986028), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02937721567409849), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07994916602454165), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.027113726071967225), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.29299900764659004), 'Pe': np.float64(0.051672447366759904), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.03021353930031804, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02946912242686891, 'Pcv': 0.030303030303030304, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Su', 'Bgr', 'Al', 'Sc', 'Pcv', 'Ba', 'Bu', 'Sg', 'Htn', 'Dm', 'Appet', 'Rbc', 'Pe', 'Hemo']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD3D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.2009686100049258), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.07217247678425602), 'Rbc': np.float64(0.011086657632142645), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.14234578772413584), 'Bgr': np.float64(0.025581781485264285), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.005903898199838493), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.016067272767005175), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.00544900784073757), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.05888360329955782), 'Pe': np.float64(0.010384539922850426), 'Ane': np.float64(0.0)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.35912313262497586), 'Rbc': np.float64(0.05516611590173663), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.7082986130055181), 'Bgr': np.float64(0.12729242384986028), 'Bu': np.float64(0.0), 'Sc': np.float64(0.0), 'Sod': np.float64(0.0), 'Pot': np.float64(0.02937721567409849), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.07994916602454165), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.027113726071967225), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.29299900764659004), 'Pe': np.float64(0.051672447366759904), 'Ane': np.float64(0.0)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028790389395194696, 'Bp': 0.032018442622950824, 'Sg': 0.029957522915269395, 'Al': 0.03047794966520434, 'Su': 0.03057889822595705, 'Rbc': 0.029631255487269532, 'Pc': 0.028577260665441927, 'Pcc': 0.028169014084507043, 'Ba': 0.03021353930031804, 'Bgr': 0.030536130536130537, 'Bu': 0.03021353930031804, 'Sc': 0.03047794966520434, 'Sod': 0.02900988017658188, 'Pot': 0.029418126757516764, 'Hemo': 0.02946912242686891, 'Pcv': 0.030303030303030304, 'Wbcc': 0.028169014084507043, 'Rbcc': 0.028991596638655463, 'Htn': 0.029957522915269395, 'Dm': 0.029709507042253523, 'Cad': 0.028370221327967807, 'Appet': 0.029709507042253523, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Su', 'Bgr', 'Al', 'Sc', 'Pcv', 'Ba', 'Bu', 'Sg', 'Htn', 'Dm', 'Appet', 'Rbc', 'Pe', 'Hemo', 'Pot', 'Ane', 'Sod', 'Rbcc', 'Age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 24/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDD970>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.14181649915610517), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.27826403759257384), 'Bu': np.float64(0.3011442188611579), 'Sc': np.float64(0.17308094735197674), 'Sod': np.float64(0.12555758817729323), 'Pot': np.float64(0.6383006323888494), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.37321989405210193), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1966810056066172), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.15880572840811708), 'Ane': np.float64(0.053118143369392475)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.02919863597612958, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02797339593114241, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.029273504273504274, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.029857397504456328, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Pot', 'Pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDEC30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.14181649915610517), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.27826403759257384), 'Bu': np.float64(0.3011442188611579), 'Sc': np.float64(0.17308094735197674), 'Sod': np.float64(0.12555758817729323), 'Pot': np.float64(0.6383006323888494), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.37321989405210193), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1966810056066172), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.15880572840811708), 'Ane': np.float64(0.053118143369392475)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.02919863597612958, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02797339593114241, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.029273504273504274, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.029857397504456328, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Pot', 'Pcv', 'Bgr', 'Al', 'Rbcc', 'Sg', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDE5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.14181649915610517), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.27826403759257384), 'Bu': np.float64(0.3011442188611579), 'Sc': np.float64(0.17308094735197674), 'Sod': np.float64(0.12555758817729323), 'Pot': np.float64(0.6383006323888494), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.37321989405210193), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1966810056066172), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.15880572840811708), 'Ane': np.float64(0.053118143369392475)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.02919863597612958, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02797339593114241, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.029273504273504274, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.029857397504456328, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Pot', 'Pcv', 'Bgr', 'Al', 'Rbcc', 'Sg', 'Htn', 'Pe', 'Dm', 'Hemo', 'Ane', 'Sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDFD10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.14687193333865592), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.02082886341037703), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.04086917717984175), 'Bu': np.float64(0.044229633637897586), 'Sc': np.float64(0.02542073336167094), 'Sod': np.float64(0.018440885720937824), 'Pot': np.float64(0.093748447930237), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.05481552739988054), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.02888691954443489), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.023324104356553667), 'Ane': np.float64(0.00780156441202258)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.0), 'Al': np.float64(0.0), 'Su': np.float64(0.14181649915610517), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.0), 'Bgr': np.float64(0.27826403759257384), 'Bu': np.float64(0.3011442188611579), 'Sc': np.float64(0.17308094735197674), 'Sod': np.float64(0.12555758817729323), 'Pot': np.float64(0.6383006323888494), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.37321989405210193), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.1966810056066172), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.0), 'Pe': np.float64(0.15880572840811708), 'Ane': np.float64(0.053118143369392475)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.028594771241830064, 'Bp': 0.032018442622950824, 'Sg': 0.02976190476190476, 'Al': 0.03028233151183971, 'Su': 0.02919863597612958, 'Rbc': 0.028594771241830064, 'Pc': 0.028381642512077296, 'Pcc': 0.02797339593114241, 'Ba': 0.02797339593114241, 'Bgr': 0.030536130536130537, 'Bu': 0.031754032258064516, 'Sc': 0.03131881575727918, 'Sod': 0.029211087420042643, 'Pot': 0.031054405392392875, 'Hemo': 0.029273504273504274, 'Pcv': 0.031024531024531024, 'Wbcc': 0.02797339593114241, 'Rbcc': 0.029857397504456328, 'Htn': 0.02976190476190476, 'Dm': 0.029513888888888888, 'Cad': 0.02817460317460317, 'Appet': 0.02797339593114241, 'Pe': 0.029631255487269532, 'Ane': 0.029236022193768675}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Pot', 'Pcv', 'Bgr', 'Al', 'Rbcc', 'Sg', 'Htn', 'Pe', 'Dm', 'Hemo', 'Ane', 'Sod', 'Su', 'Age', 'Rbc', 'Pc', 'Cad']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Run 25/25
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDEBD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5142381040171355), 'Al': np.float64(0.08390097020113624), 'Su': np.float64(0.47175477232948393), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13593597067723462), 'Bgr': np.float64(0.03923982973018475), 'Bu': np.float64(0.5447617275819571), 'Sc': np.float64(0.08670187435313755), 'Sod': np.float64(0.0), 'Pot': np.float64(0.030217852304441725), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.14579178653506378), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.28346467357536553), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.16196616048426604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.11661034673460423)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.031746031746031744, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.028790389395194696, 'Bgr': 0.02904040404040404, 'Bu': 0.03225806451612903, 'Sc': 0.030679156908665108, 'Sod': 0.028438886647841874, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.029386529386529386, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.02964426877470356}
Top 5 Features Selected: ['Bu', 'Bp', 'Sg', 'Sc', 'Al']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FECDDB50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5142381040171355), 'Al': np.float64(0.08390097020113624), 'Su': np.float64(0.47175477232948393), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13593597067723462), 'Bgr': np.float64(0.03923982973018475), 'Bu': np.float64(0.5447617275819571), 'Sc': np.float64(0.08670187435313755), 'Sod': np.float64(0.0), 'Pot': np.float64(0.030217852304441725), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.14579178653506378), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.28346467357536553), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.16196616048426604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.11661034673460423)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.031746031746031744, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.028790389395194696, 'Bgr': 0.02904040404040404, 'Bu': 0.03225806451612903, 'Sc': 0.030679156908665108, 'Sod': 0.028438886647841874, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.029386529386529386, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.02964426877470356}
Top 10 Features Selected: ['Bu', 'Bp', 'Sg', 'Sc', 'Al', 'Su', 'Rbcc', 'Pcv', 'Ane', 'Htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FED22D50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5142381040171355), 'Al': np.float64(0.08390097020113624), 'Su': np.float64(0.47175477232948393), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13593597067723462), 'Bgr': np.float64(0.03923982973018475), 'Bu': np.float64(0.5447617275819571), 'Sc': np.float64(0.08670187435313755), 'Sod': np.float64(0.0), 'Pot': np.float64(0.030217852304441725), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.14579178653506378), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.28346467357536553), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.16196616048426604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.11661034673460423)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.031746031746031744, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.028790389395194696, 'Bgr': 0.02904040404040404, 'Bu': 0.03225806451612903, 'Sc': 0.030679156908665108, 'Sod': 0.028438886647841874, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.029386529386529386, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.02964426877470356}
Top 15 Features Selected: ['Bu', 'Bp', 'Sg', 'Sc', 'Al', 'Su', 'Rbcc', 'Pcv', 'Ane', 'Htn', 'Appet', 'Dm', 'Bgr', 'Hemo', 'Ba']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F7FED221B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['Age', 'Bp', 'Sg', 'Al', 'Su', 'Rbc', 'Pc', 'Pcc', 'Ba', 'Bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(0.16267731301501193), 'Sg': np.float64(0.08365487301144182), 'Al': np.float64(0.013648784391673427), 'Su': np.float64(0.07674379876456915), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.022113698451859978), 'Bgr': np.float64(0.006383430063673035), 'Bu': np.float64(0.08862037407644868), 'Sc': np.float64(0.01410442795313359), 'Sod': np.float64(0.0), 'Pot': np.float64(0.004915759017971066), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.023717016093182372), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.046113271431917915), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.026348219786938604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.018969857876534286)}

Normalized Mathematical Scores
{'Age': np.float64(0.0), 'Bp': np.float64(1.0), 'Sg': np.float64(0.5142381040171355), 'Al': np.float64(0.08390097020113624), 'Su': np.float64(0.47175477232948393), 'Rbc': np.float64(0.0), 'Pc': np.float64(0.0), 'Pcc': np.float64(0.0), 'Ba': np.float64(0.13593597067723462), 'Bgr': np.float64(0.03923982973018475), 'Bu': np.float64(0.5447617275819571), 'Sc': np.float64(0.08670187435313755), 'Sod': np.float64(0.0), 'Pot': np.float64(0.030217852304441725), 'Hemo': np.float64(0.0), 'Pcv': np.float64(0.14579178653506378), 'Wbcc': np.float64(0.0), 'Rbcc': np.float64(0.28346467357536553), 'Htn': np.float64(0.0), 'Dm': np.float64(0.0), 'Cad': np.float64(0.0), 'Appet': np.float64(0.16196616048426604), 'Pe': np.float64(0.0), 'Ane': np.float64(0.11661034673460423)}

Clinical Weights
{'Age': 0.55, 'Bp': 0.8, 'Sg': 0.85, 'Al': 1.0, 'Su': 0.55, 'Rbc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Ba': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Sod': 0.65, 'Pot': 0.65, 'Hemo': 0.75, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Htn': 0.85, 'Dm': 0.8, 'Cad': 0.45, 'Appet': 0.4, 'Pe': 0.65, 'Ane': 0.7}

Final DODA Scores
{'Age': 0.02821939586645469, 'Bp': 0.032018442622950824, 'Sg': 0.031746031746031744, 'Al': 0.03047794966520434, 'Su': 0.030330882352941176, 'Rbc': 0.02821939586645469, 'Pc': 0.028006267136701922, 'Pcc': 0.027598020555767037, 'Ba': 0.028790389395194696, 'Bgr': 0.02904040404040404, 'Bu': 0.03225806451612903, 'Sc': 0.030679156908665108, 'Sod': 0.028438886647841874, 'Pot': 0.02862400327131466, 'Hemo': 0.0288981288981289, 'Pcv': 0.03007688828584351, 'Wbcc': 0.027598020555767037, 'Rbcc': 0.030090497737556562, 'Htn': 0.029386529386529386, 'Dm': 0.029138513513513514, 'Cad': 0.027799227799227798, 'Appet': 0.029236022193768675, 'Pe': 0.028438886647841874, 'Ane': 0.02964426877470356}
Top 20 Features Selected: ['Bu', 'Bp', 'Sg', 'Sc', 'Al', 'Su', 'Rbcc', 'Pcv', 'Ane', 'Htn', 'Appet', 'Dm', 'Bgr', 'Hemo', 'Ba', 'Pot', 'Sod', 'Pe', 'Age', 'Rbc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Completed.
Rows generated: 600

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,LASSO,5,Logistic Regression,0.525253,0.530973,0.594059,0.560748,0.524497,"Bp, Sg, Su, Rbcc, Ba"
1,1,LASSO,5,Random Forest,0.525253,0.533333,0.554455,0.543689,0.513831,"Bp, Sg, Su, Rbcc, Ba"
2,1,LASSO,5,XGBoost,0.520202,0.526786,0.584158,0.553991,0.499898,"Bp, Sg, Su, Rbcc, Ba"
3,1,DODA,5,Logistic Regression,0.500000,0.509615,0.524752,0.517073,0.518322,"Bp, Sg, Sc, Su, Rbcc"
4,1,DODA,5,Random Forest,0.540404,0.550000,0.544554,0.547264,0.548382,"Bp, Sg, Sc, Su, Rbcc"

In [29]:
# =============================================================================
# STEP 26: CV PERFORMANCE SUMMARY
# =============================================================================

cv_summary_df = (
    cv_results_df
    .groupby(["Method", "Top_K", "Model"])
    [["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]]
    .agg(["mean", "std"])
    .reset_index()
)

cv_summary_df.columns = [
    "Method", "Top_K", "Model",
    "Accuracy_Mean", "Accuracy_STD",
    "Precision_Mean", "Precision_STD",
    "Recall_Mean", "Recall_STD",
    "F1_Mean", "F1_STD",
    "ROC_AUC_Mean", "ROC_AUC_STD"
]

display(cv_summary_df.round(4))

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,DODA,5,Logistic Regression,0.5095,0.0336,0.5193,0.0285,0.5724,0.0611,0.5439,0.0411,0.5142,0.0338
1,DODA,5,Random Forest,0.5107,0.0345,0.5229,0.0328,0.5384,0.0473,0.5299,0.0355,0.5087,0.0445
2,DODA,5,XGBoost,0.5067,0.0347,0.5176,0.0322,0.5348,0.0664,0.5252,0.0467,0.5060,0.0408
3,DODA,10,Logistic Regression,0.5170,0.0252,0.5273,0.0229,0.5712,0.0410,0.5478,0.0271,0.5173,0.0308
4,DODA,10,Random Forest,0.5109,0.0419,0.5234,0.0396,0.5416,0.0536,0.5315,0.0413,0.5100,0.0396
5,DODA,10,XGBoost,0.5079,0.0364,0.5198,0.0343,0.5381,0.0513,0.5282,0.0399,0.5106,0.0462
6,DODA,15,Logistic Regression,0.5178,0.0265,0.5283,0.0251,0.5673,0.0385,0.5467,0.0275,0.5209,0.0353
7,DODA,15,Random Forest,0.5115,0.0296,0.5234,0.0276,0.5389,0.0443,0.5305,0.0327,0.5187,0.0373
8,DODA,15,XGBoost,0.5180,0.0324,0.5294,0.0303,0.5487,0.0489,0.5383,0.0352,0.5243,0.0403
9,DODA,20,Logistic Regression,0.5168,0.0305,0.5276,0.0291,0.5626,0.0454,0.5439,0.0326,0.5236,0.0327
10,DODA,20,Random Forest,0.5269,0.0294,0.5364,0.0256,0.5692,0.0532,0.5517,0.0355,0.5308,0.0318
11,DODA,20,XGBoost,0.5318,0.0345,0.5418,0.0310,0.5657,0.0561,0.5527,0.0391,0.5457,0.0351
12,LASSO,5,Logistic Regression,0.5125,0.0334,0.5225,0.0289,0.5720,0.0545,0.5456,0.0377,0.5163,0.0379
13,LASSO,5,Random Forest,0.5081,0.0406,0.5207,0.0404,0.5290,0.0551,0.5240,0.0433,0.5022,0.0440
14,LASSO,5,XGBoost,0.5069,0.0338,0.5183,0.0328,0.5365,0.0552,0.5266,0.0410,0.4976,0.0448
15,LASSO,10,Logistic Regression,0.5144,0.0334,0.5252,0.0306,0.5610,0.0493,0.5419,0.0355,0.5185,0.0374
16,LASSO,10,Random Forest,0.5016,0.0329,0.5144,0.0313,0.5314,0.0480,0.5219,0.0344,0.5018,0.0372
17,LASSO,10,XGBoost,0.5055,0.0330,0.5170,0.0316,0.5318,0.0571,0.5236,0.0417,0.5028,0.0426
18,LASSO,15,Logistic Regression,0.5166,0.0297,0.5271,0.0272,0.5602,0.0465,0.5427,0.0337,0.5178,0.0373
19,LASSO,15,Random Forest,0.5095,0.0360,0.5216,0.0346,0.5444,0.0471,0.5321,0.0361,0.5130,0.0422
20,LASSO,15,XGBoost,0.5049,0.0390,0.5165,0.0377,0.5313,0.0585,0.5232,0.0453,0.5180,0.0404
21,LASSO,20,Logistic Regression,0.5211,0.0280,0.5313,0.0262,0.5630,0.0481,0.5461,0.0334,0.5208,0.0338
22,LASSO,20,Random Forest,0.5176,0.0291,0.5279,0.0257,0.5613,0.0480,0.5436,0.0333,0.5264,0.0297
23,LASSO,20,XGBoost,0.5371,0.0306,0.5472,0.0289,0.5705,0.0462,0.5579,0.0325,0.5436,0.0328

In [30]:
# =============================================================================
# STEP 24: SAVE REPEATED-CV RESULTS
# =============================================================================

cv_dir = Path("../../../results/kidney_disease/cv")
cv_dir.mkdir(parents=True, exist_ok=True)

cv_results_df.to_csv(
    cv_dir / "lasso_vs_doda_5x5_repeated_cv_results.csv",
    index=False
)

cv_summary_df.to_csv(
    cv_dir / "lasso_vs_doda_5x5_repeated_cv_summary.csv",
    index=False
)

print(f"Saved to: {cv_dir.resolve()}")

Saved to: C:\Users\johnm\msc_research\results\kidney_disease\cv

# 4. Feature-Selection Stability, Rank/Set Change, and Statistical Comparison

Two different concepts are reported:

- **Feature-set change:** whether the Top-K membership changes.
- **Rank change:** whether feature ordering changes even when membership is retained.

Jaccard similarity evaluates set overlap, so it does not measure ordering. The fixed-split DODA rank comparison is used to inspect ordering changes.

In [31]:
# =============================================================================
# STEP 28: FEATURE-SET COMPARISON ACROSS THE 25 CV RUNS
# =============================================================================

feature_comparison_rows = []

for run_id in range(1, 26):

    for top_k in TOP_K_VALUES:

        lasso_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "LASSO") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        doda_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        lasso_set = set(
            lasso_row["Selected_Features"].split(", ")
        )
        doda_set = set(
            doda_row["Selected_Features"].split(", ")
        )

        overlap = len(lasso_set & doda_set)
        union = len(lasso_set | doda_set)

        feature_comparison_rows.append({
            "Run": run_id,
            "Top_K": top_k,
            "Same_Feature_Set": lasso_set == doda_set,
            "Overlap_Count": overlap,
            "Jaccard": overlap / union,
            "Features_Changed": top_k - overlap
        })

feature_comparison_df = pd.DataFrame(
    feature_comparison_rows
)

display(
    feature_comparison_df
    .groupby("Top_K")
    [["Same_Feature_Set", "Overlap_Count", "Jaccard", "Features_Changed"]]
    .agg(["mean", "std"])
    .round(4)
)

      Same_Feature_Set      Overlap_Count         Jaccard          \
                  mean  std          mean     std    mean     std
Top_K
5                  0.0  0.0          3.44  0.5831  0.5357  0.1331
10                 0.0  0.0          7.24  1.0909  0.5783  0.1339
15                 0.0  0.0         10.64  1.0360  0.5539  0.0850
20                 0.0  0.0         17.52  0.5099  0.7802  0.0403

      Features_Changed
                  mean     std
Top_K
5                 1.56  0.5831
10                2.76  1.0909
15                4.36  1.0360
20                2.48  0.5099

In [32]:
# =============================================================================
# STEP 29: FEATURE-SELECTION STABILITY
# =============================================================================

from itertools import combinations

stability_rows = []

for method in ["LASSO", "DODA"]:

    for top_k in TOP_K_VALUES:

        subset = cv_results_df[
            (cv_results_df["Method"] == method) &
            (cv_results_df["Top_K"] == top_k)
        ]

        # One feature set per run; model does not affect selection.
        run_sets = {}

        for run_id in range(1, 26):
            row = subset[
                subset["Run"] == run_id
            ].iloc[0]

            run_sets[run_id] = set(
                row["Selected_Features"].split(", ")
            )

        pairwise_jaccards = []

        for a, b in combinations(range(1, 26), 2):

            set_a = run_sets[a]
            set_b = run_sets[b]

            pairwise_jaccards.append(
                len(set_a & set_b) / len(set_a | set_b)
            )

        stability_rows.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Jaccard": np.mean(pairwise_jaccards),
            "SD_Jaccard": np.std(pairwise_jaccards, ddof=1),
            "Min_Jaccard": np.min(pairwise_jaccards),
            "Max_Jaccard": np.max(pairwise_jaccards)
        })

stability_df = pd.DataFrame(stability_rows)

display(stability_df.round(4))

  Method  Top_K  Mean_Jaccard  SD_Jaccard  Min_Jaccard  Max_Jaccard
0  LASSO      5        0.3951      0.1662       0.1111       1.0000
1  LASSO     10        0.4770      0.1266       0.1765       0.8182
2  LASSO     15        0.6222      0.1002       0.4286       1.0000
3  LASSO     20        0.8729      0.0614       0.7391       1.0000
4   DODA      5        0.3884      0.1645       0.1111       1.0000
5   DODA     10        0.6029      0.1050       0.4286       0.8182
6   DODA     15        0.7527      0.0852       0.5789       1.0000
7   DODA     20        0.9096      0.0593       0.7391       1.0000

## 4.1 Additional Feature-Selection Stability Analyses

The 25 repeated-CV runs are used to quantify selection frequency, chance-adjusted stability, and direct LASSO–DODA feature-set agreement.

In [33]:
# =============================================================================
# STEP 30: FEATURE SELECTION FREQUENCY
# =============================================================================
frequency_rows = []
for method in ["LASSO", "DODA"]:
    for top_k in TOP_K_VALUES:
        subset = cv_results_df[(cv_results_df["Method"] == method) & (cv_results_df["Top_K"] == top_k)]
        counts = {feature: 0 for feature in X.columns}
        for run_id in sorted(subset["Run"].unique()):
            row = subset[subset["Run"] == run_id].iloc[0]
            for feature in row["Selected_Features"].split(", "):
                counts[feature] += 1
        for feature, count in counts.items():
            frequency_rows.append({
                "Method": method, "Top_K": top_k, "Feature": feature,
                "Selection_Count": count,
                "Selection_Frequency": count / (N_SPLITS * N_REPEATS)
            })
feature_frequency_df = pd.DataFrame(frequency_rows)

display(
    feature_frequency_df.sort_values(
        ["Method", "Top_K", "Selection_Frequency", "Feature"],
        ascending=[True, True, False, True]
    ).groupby(["Method", "Top_K"], group_keys=False).head(10).round(4)
)

    Method  Top_K Feature  Selection_Count  Selection_Frequency
97    DODA      5      Bp               25                 1.00
106   DODA      5      Bu               17                 0.68
111   DODA      5     Pcv               15                 0.60
107   DODA      5      Sc               14                 0.56
99    DODA      5      Al               12                 0.48
..     ...    ...     ...              ...                  ...
82   LASSO     20      Bu               25                 1.00
86   LASSO     20    Hemo               25                 1.00
78   LASSO     20      Pc               25                 1.00
79   LASSO     20     Pcc               25                 1.00
87   LASSO     20     Pcv               25                 1.00

[80 rows x 5 columns]

In [34]:
# =============================================================================
# STEP 31: KUNCHEVA INDEX
# =============================================================================
from itertools import combinations
N_FEATURES = X.shape[1]
kuncheva_rows = []

for method in ["LASSO", "DODA"]:
    for top_k in TOP_K_VALUES:
        subset = cv_results_df[(cv_results_df["Method"] == method) & (cv_results_df["Top_K"] == top_k)]
        run_sets = {}
        for run_id in sorted(subset["Run"].unique()):
            row = subset[subset["Run"] == run_id].iloc[0]
            run_sets[run_id] = set(row["Selected_Features"].split(", "))

        for run_a, run_b in combinations(sorted(run_sets), 2):
            intersection = len(run_sets[run_a] & run_sets[run_b])
            denominator = top_k * (N_FEATURES - top_k)
            value = np.nan if denominator == 0 else ((intersection * N_FEATURES) - (top_k ** 2)) / denominator
            kuncheva_rows.append({
                "Method": method, "Top_K": top_k, "Run_A": run_a, "Run_B": run_b,
                "Intersection": intersection, "Kuncheva_Index": value
            })

kuncheva_df = pd.DataFrame(kuncheva_rows)
kuncheva_summary_df = (
    kuncheva_df.groupby(["Method", "Top_K"])["Kuncheva_Index"]
    .agg(Mean_Kuncheva="mean", Std_Kuncheva="std", Min_Kuncheva="min", Max_Kuncheva="max")
    .reset_index()
)
display(kuncheva_summary_df.round(4))

  Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0   DODA      5         0.4189        0.2112       -0.0105        1.0000
1   DODA     10         0.5663        0.1391        0.3143        0.8286
2   DODA     15         0.6166        0.1481        0.2889        1.0000
3   DODA     20         0.7100        0.1960        0.1000        1.0000
4  LASSO      5         0.4282        0.2046       -0.0105        1.0000
5  LASSO     10         0.3760        0.2000       -0.2000        0.8286
6  LASSO     15         0.3665        0.2025       -0.0667        1.0000
7  LASSO     20         0.5860        0.2101        0.1000        1.0000

In [35]:
# =============================================================================
# STEP 32: LASSO–DODA FEATURE-SET AGREEMENT SUMMARY
# =============================================================================
agreement_summary_df = (
    feature_comparison_df.groupby("Top_K")
    .agg(
        Same_Feature_Set_Rate=("Same_Feature_Set", "mean"),
        Mean_Overlap=("Overlap_Count", "mean"),
        SD_Overlap=("Overlap_Count", "std"),
        Mean_Jaccard=("Jaccard", "mean"),
        SD_Jaccard=("Jaccard", "std"),
        Mean_Features_Changed=("Features_Changed", "mean"),
        SD_Features_Changed=("Features_Changed", "std")
    ).reset_index()
)
display(agreement_summary_df.round(4))

,Top_K,Same_Feature_Set_Rate,Mean_Overlap,SD_Overlap,Mean_Jaccard,SD_Jaccard,Mean_Features_Changed,SD_Features_Changed
0,5,0.0,3.44,0.5831,0.5357,0.1331,1.56,0.5831
1,10,0.0,7.24,1.0909,0.5783,0.1339,2.76,1.0909
2,15,0.0,10.64,1.0360,0.5539,0.0850,4.36,1.0360
3,20,0.0,17.52,0.5099,0.7802,0.0403,2.48,0.5099

In [36]:
# =============================================================================
# STEP 33: PAIRED STATISTICAL COMPARISON OF PREDICTIVE PERFORMANCE
# =============================================================================

from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

metrics = ["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]

comparison_rows = []

for top_k in TOP_K_VALUES:

    for model_name in models.keys():

        lasso = cv_results_df[
            (cv_results_df["Method"] == "LASSO") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        doda = cv_results_df[
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        assert len(lasso) == 25
        assert len(doda) == 25
        assert (lasso["Run"].values == doda["Run"].values).all()

        for metric in metrics:

            lasso_values = lasso[metric].to_numpy()
            doda_values = doda[metric].to_numpy()

            differences = doda_values - lasso_values

            mean_difference = np.mean(differences)
            sd_difference = np.std(differences, ddof=1)

            if np.allclose(differences, 0):
                statistic = 0.0
                p_value = 1.0
            else:
                statistic, p_value = wilcoxon(
                    doda_values,
                    lasso_values,
                    alternative="two-sided"
                )

            paired_d = (
                mean_difference / sd_difference
                if sd_difference > 0 else 0.0
            )

            comparison_rows.append({
                "Top_K": top_k,
                "Model": model_name,
                "Metric": metric,
                "LASSO_Mean": np.mean(lasso_values),
                "DODA_Mean": np.mean(doda_values),
                "Mean_Difference_DODA_minus_LASSO": mean_difference,
                "Paired_SD": sd_difference,
                "Paired_Cohens_d": paired_d,
                "Wilcoxon_Statistic": statistic,
                "P_Value": p_value
            })

performance_comparison_df = pd.DataFrame(comparison_rows)

reject, adjusted_p, _, _ = multipletests(
    performance_comparison_df["P_Value"],
    alpha=0.05,
    method="holm"
)

performance_comparison_df["Holm_Adjusted_P"] = adjusted_p
performance_comparison_df["Significant"] = reject

display(performance_comparison_df.round(4))

,Top_K,Model,Metric,LASSO_Mean,DODA_Mean,Mean_Difference_DODA_minus_LASSO,Paired_SD,Paired_Cohens_d,Wilcoxon_Statistic,P_Value,Holm_Adjusted_P,Significant
0,5,Logistic Regression,Accuracy,0.5125,0.5095,-0.0030,0.0252,-0.1198,119.0,0.5632,1.0,False
1,5,Logistic Regression,Precision,0.5225,0.5193,-0.0031,0.0221,-0.1428,129.0,0.5485,1.0,False
2,5,Logistic Regression,Recall,0.5720,0.5724,0.0004,0.0508,0.0075,131.0,0.5870,1.0,False
3,5,Logistic Regression,F1,0.5456,0.5439,-0.0017,0.0332,-0.0512,130.0,0.5677,1.0,False
4,5,Logistic Regression,ROC_AUC,0.5163,0.5142,-0.0021,0.0135,-0.1577,142.0,0.5965,1.0,False
5,5,Random Forest,Accuracy,0.5081,0.5107,0.0026,0.0375,0.0693,157.5,0.8930,1.0,False
6,5,Random Forest,Precision,0.5207,0.5229,0.0022,0.0368,0.0611,160.0,0.9578,1.0,False
7,5,Random Forest,Recall,0.5290,0.5384,0.0093,0.0511,0.1830,118.0,0.3604,1.0,False
8,5,Random Forest,F1,0.5240,0.5299,0.0059,0.0352,0.1664,144.0,0.6338,1.0,False
9,5,Random Forest,ROC_AUC,0.5022,0.5087,0.0065,0.0385,0.1676,135.0,0.4742,1.0,False
10,5,XGBoost,Accuracy,0.5069,0.5067,-0.0002,0.0268,-0.0076,158.5,0.9143,1.0,False
11,5,XGBoost,Precision,0.5183,0.5176,-0.0008,0.0250,-0.0301,162.0,1.0000,1.0,False
12,5,XGBoost,Recall,0.5365,0.5348,-0.0017,0.0444,-0.0374,115.5,0.7208,1.0,False
13,5,XGBoost,F1,0.5266,0.5252,-0.0015,0.0302,-0.0492,147.0,0.6915,1.0,False
14,5,XGBoost,ROC_AUC,0.4976,0.5060,0.0084,0.0264,0.3180,110.0,0.1645,1.0,False
15,10,Logistic Regression,Accuracy,0.5144,0.5170,0.0026,0.0204,0.1292,113.0,0.6610,1.0,False
16,10,Logistic Regression,Precision,0.5252,0.5273,0.0021,0.0185,0.1140,149.0,0.7310,1.0,False
17,10,Logistic Regression,Recall,0.5610,0.5712,0.0102,0.0292,0.3496,92.5,0.0994,1.0,False
18,10,Logistic Regression,F1,0.5419,0.5478,0.0060,0.0208,0.2866,117.0,0.2304,1.0,False
19,10,Logistic Regression,ROC_AUC,0.5185,0.5173,-0.0012,0.0135,-0.0915,149.0,0.7310,1.0,False
20,10,Random Forest,Accuracy,0.5016,0.5109,0.0093,0.0355,0.2620,98.5,0.2294,1.0,False
21,10,Random Forest,Precision,0.5144,0.5234,0.0089,0.0332,0.2686,113.0,0.1908,1.0,False
22,10,Random Forest,Recall,0.5314,0.5416,0.0103,0.0453,0.2264,109.5,0.2468,1.0,False
23,10,Random Forest,F1,0.5219,0.5315,0.0095,0.0355,0.2681,111.0,0.1730,1.0,False
24,10,Random Forest,ROC_AUC,0.5018,0.5100,0.0082,0.0328,0.2502,91.0,0.0551,1.0,False
25,10,XGBoost,Accuracy,0.5055,0.5079,0.0024,0.0354,0.0686,146.5,0.6668,1.0,False
26,10,XGBoost,Precision,0.5170,0.5198,0.0028,0.0331,0.0840,145.0,0.6377,1.0,False
27,10,XGBoost,Recall,0.5318,0.5381,0.0063,0.0485,0.1300,96.5,0.5086,1.0,False
28,10,XGBoost,F1,0.5236,0.5282,0.0045,0.0377,0.1206,131.0,0.4108,1.0,False
29,10,XGBoost,ROC_AUC,0.5028,0.5106,0.0078,0.0315,0.2482,119.0,0.2521,1.0,False
30,15,Logistic Regression,Accuracy,0.5166,0.5178,0.0012,0.0174,0.0697,136.0,0.6887,1.0,False
31,15,Logistic Regression,Precision,0.5271,0.5283,0.0013,0.0161,0.0779,146.0,0.6721,1.0,False
32,15,Logistic Regression,Recall,0.5602,0.5673,0.0071,0.0218,0.3241,94.5,0.1845,1.0,False
33,15,Logistic Regression,F1,0.5427,0.5467,0.0040,0.0174,0.2273,122.0,0.2872,1.0,False
34,15,Logistic Regression,ROC_AUC,0.5178,0.5209,0.0031,0.0117,0.2658,121.0,0.2752,1.0,False
35,15,Random Forest,Accuracy,0.5095,0.5115,0.0020,0.0262,0.0774,128.0,0.7610,1.0,False
36,15,Random Forest,Precision,0.5216,0.5234,0.0018,0.0242,0.0732,158.0,0.9158,1.0,False
37,15,Random Forest,Recall,0.5444,0.5389,-0.0054,0.0463,-0.1177,156.5,0.8717,1.0,False
38,15,Random Forest,F1,0.5321,0.5305,-0.0016,0.0308,-0.0508,150.0,0.7510,1.0,False
39,15,Random Forest,ROC_AUC,0.5130,0.5187,0.0056,0.0310,0.1817,130.0,0.3957,1.0,False
40,15,XGBoost,Accuracy,0.5049,0.5180,0.0132,0.0287,0.4591,84.5,0.0358,1.0,False
41,15,XGBoost,Precision,0.5165,0.5294,0.0130,0.0291,0.4451,91.0,0.0551,1.0,False
42,15,XGBoost,Recall,0.5313,0.5487,0.0174,0.0428,0.4057,44.5,0.0420,1.0,False
43,15,XGBoost,F1,0.5232,0.5383,0.0150,0.0328,0.4576,79.0,0.0236,1.0,False
44,15,XGBoost,ROC_AUC,0.5180,0.5243,0.0063,0.0292,0.2162,119.0,0.2521,1.0,False
45,20,Logistic Regression,Accuracy,0.5211,0.5168,-0.0043,0.0168,-0.2531,109.0,0.2412,1.0,False
46,20,Logistic Regression,Precision,0.5313,0.5276,-0.0037,0.0154,-0.2428,115.0,0.3173,1.0,False
47,20,Logistic Regression,Recall,0.5630,0.5626,-0.0004,0.0264,-0.0153,109.5,0.8344,1.0,False
48,20,Logistic Regression,F1,0.5461,0.5439,-0.0022,0.0183,-0.1195,142.0,0.8192,1.0,False
49,20,Logistic Regression,ROC_AUC,0.5208,0.5236,0.0027,0.0082,0.3296,91.5,0.0561,1.0,False
50,20,Random Forest,Accuracy,0.5176,0.5269,0.0094,0.0313,0.2993,91.5,0.0945,1.0,False
51,20,Random Forest,Precision,0.5279,0.5364,0.0085,0.0280,0.3037,106.0,0.1336,1.0,False
52,20,Random Forest,Recall,0.5613,0.5692,0.0079,0.0420,0.1880,110.5,0.2587,1.0,False
53,20,Random Forest,F1,0.5436,0.5517,0.0081,0.0321,0.2521,105.0,0.1266,1.0,False
54,20,Random Forest,ROC_AUC,0.5264,0.5308,0.0044,0.0206,0.2128,123.0,0.2996,1.0,False
55,20,XGBoost,Accuracy,0.5371,0.5318,-0.0053,0.0233,-0.2261,106.5,0.3378,1.0,False
56,20,XGBoost,Precision,0.5472,0.5418,-0.0055,0.0227,-0.2405,122.0,0.4237,1.0,False
57,20,XGBoost,Recall,0.5705,0.5657,-0.0048,0.0289,-0.1648,87.5,0.5130,1.0,False
58,20,XGBoost,F1,0.5579,0.5527,-0.0052,0.0228,-0.2286,111.0,0.2652,1.0,False
59,20,XGBoost,ROC_AUC,0.5436,0.5457,0.0021,0.0193,0.1085,143.0,0.6150,1.0,False

In [37]:
# =============================================================================
# STEP 34: SAVE STATISTICAL RESULTS
# =============================================================================

stats_dir = Path("../../../results/kidney_disease/statistics")
stats_dir.mkdir(parents=True, exist_ok=True)

feature_comparison_df.to_csv(
    stats_dir / "feature_set_comparison_5x5.csv",
    index=False
)

stability_df.to_csv(
    stats_dir / "feature_selection_stability_5x5.csv",
    index=False
)

performance_comparison_df.to_csv(
    stats_dir / "lasso_vs_doda_predictive_statistics_5x5.csv",
    index=False
)

print(f"Saved statistical outputs to: {stats_dir.resolve()}")

feature_frequency_df.to_csv(
    stats_dir / "feature_selection_frequency_5x5.csv",
    index=False
)

kuncheva_df.to_csv(
    stats_dir / "kuncheva_pairwise_5x5.csv",
    index=False
)

kuncheva_summary_df.to_csv(
    stats_dir / "kuncheva_summary_5x5.csv",
    index=False
)

agreement_summary_df.to_csv(
    stats_dir / "lasso_doda_agreement_summary_5x5.csv",
    index=False
)

Saved statistical outputs to: C:\Users\johnm\msc_research\results\kidney_disease\statistics

In [38]:
# =============================================================================
# STEP 36: FINAL SANITY CHECKS
# =============================================================================

print("=" * 70)
print("FINAL EXPERIMENT SANITY CHECK")
print("=" * 70)

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")
print(f"Missing values: {int(X.isna().sum().sum())}")
print(f"5-fold CV result rows: {len(cv5_results_df)}")
print(f"Repeated CV result rows: {len(cv_results_df)}")
print(f"Expected 5-fold rows: {5 * len(TOP_K_VALUES) * 2 * len(models)}")
print(f"Expected repeated CV rows: {25 * len(TOP_K_VALUES) * 2 * len(models)}")

assert X.shape[1] == 24
assert X.isna().sum().sum() == 0
assert TOP_K_VALUES == [5, 10, 15, 20]
assert len(cv5_results_df) == 5 * len(TOP_K_VALUES) * 2 * len(models)
assert len(cv_results_df) == 25 * len(TOP_K_VALUES) * 2 * len(models)
assert len(feature_frequency_df) == 2 * len(TOP_K_VALUES) * X.shape[1]
assert len(kuncheva_summary_df) == 2 * len(TOP_K_VALUES)
assert len(agreement_summary_df) == len(TOP_K_VALUES)

for top_k in TOP_K_VALUES:
    assert len(lasso_results[top_k]["features"]) == top_k
    assert len(rank_doda_results[top_k]["features"]) == top_k

print("All sanity checks passed.")

======================================================================
FINAL EXPERIMENT SANITY CHECK
======================================================================
Total predictors: 24
Top-K values: [5, 10, 15, 20]
Missing values: 0
5-fold CV result rows: 120
Repeated CV result rows: 600
Expected 5-fold rows: 120
Expected repeated CV rows: 600
All sanity checks passed.

# Methodological design notes for the BD-KDD experiment

### 1. Correct predictor count
BD-KDD has **25 processed columns**, but one is the binary target `Class`. Therefore the feature matrix contains **24 predictors**.

### 2. Top-K values
The experiment uses:

**Top-5, Top-10, Top-15, Top-20**

This provides approximately 20%, 40%, 60%, and 80% feature budgets over the 24 predictors. Top-24 is deliberately not used as a selection condition because retaining every feature cannot demonstrate feature-selection behavior.

### 3. Removed imputation
BD-KDD has zero missing values, so no imputation is performed.

### 4. Correct DODA architecture
LASSO is fitted on all 24 standardized predictors inside DODA. DODA receives all 24 statistical scores and performs the final Top-K selection.

### 5. No data leakage in CV
LASSO and DODA are refit inside every training fold. Validation-fold data is never used to calculate feature-selection scores.

### 6. Model-specific scaling
Scaling is applied only to Logistic Regression and is fitted on the training data/fold. Random Forest and XGBoost use the selected features without scaling.

### 7. Consistent result paths
All outputs are stored under:

```text
results/
└── kidney_disease/
    ├── baseline/
    ├── doda/
    ├── cv/
    └── statistics/
```

### 8. Fixed split and repeated CV are separated
The fixed 80/20 experiment is an initial reproducible comparison. The 5×5 repeated stratified CV is the robustness analysis.

### 9. Feature-set change and rank change are separated
Jaccard measures feature-set overlap. DODA's rank-comparison output is retained separately because a feature can change rank without entering or leaving Top-K.

### 10. Clinical weights remain external
The clinical weights are loaded from the pre-specified JSON and are not derived from LASSO scores, target correlations, model performance, or test-fold information.