# BD-KDD Kidney Disease — mRMR + DODA Feature Selection

## Experimental objective

Evaluate conventional **mRMR feature selection** against **mRMR + DODA clinical-priority re-ranking** on the BD-KDD kidney-disease dataset.

### Important design rule

mRMR ranks **all 24 predictors**. DODA also receives **all 24 predictor scores** and performs the final Top-K selection after clinical-priority fusion.

This is essential: if mRMR selected Top-K before DODA, DODA could not re-prioritize features outside that preliminary Top-K.

### Dataset

- 988 records
- 24 predictors
- Binary target: `Class`
- `Class = 0`: healthy
- `Class = 1`: kidney disease
- 0 missing values
- 80/20 stratified fixed split for the initial experiment
- 5×5 repeated stratified CV for robustness

In [3]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("../../data/processed/BD-KDD_cleaned.csv")

if not DATA_PATH.is_file():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH.resolve()}"
    )

df = pd.read_csv(DATA_PATH)

print("=" * 70)
print("PROCESSED BD-KDD DATASET")
print("=" * 70)
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

display(df.head())

======================================================================
PROCESSED BD-KDD DATASET
======================================================================
Rows    : 988
Columns : 25

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane,Class
0,58,147,1.025,1,3,0,1,0,0,177,...,43,12342,4.3,1,0,0,1,1,0,0
1,71,142,1.025,2,3,1,0,1,0,247,...,47,7249,3.7,0,1,1,0,1,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,37,4111,3.7,0,0,0,0,0,1,0
3,34,70,1.005,1,3,1,1,0,0,215,...,44,4682,4.0,1,0,1,1,0,1,1
4,62,120,1.020,4,0,1,0,1,0,143,...,54,5161,4.7,0,0,1,0,1,0,1

In [4]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

TARGET_COLUMN = "Class"

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

print("=" * 70)
print("FEATURE / TARGET SEPARATION")
print("=" * 70)
print(f"Predictors (X) : {X.shape[1]}")
print(f"Records        : {X.shape[0]}")
print(f"Target (y)     : {TARGET_COLUMN}")
print(f"Target values  : {sorted(y.unique().tolist())}")

assert X.shape[1] == 24, "Expected 24 predictors after removing Class."
assert set(y.unique()) == {0, 1}

display(X.head())
display(y.head())

======================================================================
FEATURE / TARGET SEPARATION
======================================================================
Predictors (X) : 24
Records        : 988
Target (y)     : Class
Target values  : [0, 1]

,Age,Bp,Sg,Al,Su,Rbc,Pc,Pcc,Ba,Bgr,...,Hemo,Pcv,Wbcc,Rbcc,Htn,Dm,Cad,Appet,Pe,Ane
0,58,147,1.025,1,3,0,1,0,0,177,...,9.3,43,12342,4.3,1,0,0,1,1,0
1,71,142,1.025,2,3,1,0,1,0,247,...,16.9,47,7249,3.7,0,1,1,0,1,1
2,48,179,1.005,0,4,1,1,0,1,367,...,16.6,37,4111,3.7,0,0,0,0,0,1
3,34,70,1.005,1,3,1,1,0,0,215,...,15.4,44,4682,4.0,1,0,1,1,0,1
4,62,120,1.020,4,0,1,0,1,0,143,...,13.9,54,5161,4.7,0,0,1,0,1,0

0    0
1    1
2    0
3    1
4    1
Name: Class, dtype: int64

In [5]:
# =============================================================================
# STEP 3: TARGET DISTRIBUTION
# =============================================================================

target_distribution = pd.DataFrame({
    "Count": y.value_counts().sort_index(),
    "Percentage": (y.value_counts(normalize=True).sort_index() * 100).round(2)
})

display(target_distribution)

       Count  Percentage
Class
0        481       48.68
1        507       51.32

In [6]:
# =============================================================================
# STEP 4: DATA TYPE AND MISSING-VALUE CHECK
# =============================================================================

print("=" * 70)
print("DATA TYPES")
print("=" * 70)
display(X.dtypes.to_frame("Data Type"))

missing = pd.DataFrame({
    "Missing Count": X.isna().sum(),
    "Missing Percentage (%)": (X.isna().mean() * 100).round(2)
})

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)
display(missing)

assert X.isna().sum().sum() == 0, "Unexpected missing values detected."

print("No missing values detected. No imputation will be performed.")

======================================================================
DATA TYPES
======================================================================

      Data Type
Age       int64
Bp        int64
Sg      float64
Al        int64
Su        int64
Rbc       int64
Pc        int64
Pcc       int64
Ba        int64
Bgr       int64
Bu        int64
Sc      float64
Sod       int64
Pot     float64
Hemo    float64
Pcv       int64
Wbcc      int64
Rbcc    float64
Htn       int64
Dm        int64
Cad       int64
Appet     int64
Pe        int64
Ane       int64

======================================================================
MISSING VALUES
======================================================================

       Missing Count  Missing Percentage (%)
Age                0                     0.0
Bp                 0                     0.0
Sg                 0                     0.0
Al                 0                     0.0
Su                 0                     0.0
Rbc                0                     0.0
Pc                 0                     0.0
Pcc                0                     0.0
Ba                 0                     0.0
Bgr                0                     0.0
Bu                 0                     0.0
Sc                 0                     0.0
Sod                0                     0.0
Pot                0                     0.0
Hemo               0                     0.0
Pcv                0                     0.0
Wbcc               0                     0.0
Rbcc               0                     0.0
Htn                0                     0.0
Dm                 0                     0.0
Cad                0                     0.0
Appet              0                     0.0
Pe                 0                     0.0
Ane                0                     0.0

No missing values detected. No imputation will be performed.

## Preprocessing decision

The EDA established that BD-KDD contains **zero missing values**. Therefore, no imputation step is included in this notebook.

Feature selection is fitted only on training data/folds. Model scaling is applied only where needed and is fitted only on training data/folds.

In [7]:
# =============================================================================
# STEP 5: FIXED 80/20 STRATIFIED TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)
print(f"X_train : {X_train.shape}")
print(f"X_test  : {X_test.shape}")
print(f"y_train : {y_train.shape}")
print(f"y_test  : {y_test.shape}")

print("\nTraining class distribution:")
display((y_train.value_counts(normalize=True) * 100).round(2))

print("\nTesting class distribution:")
display((y_test.value_counts(normalize=True) * 100).round(2))

======================================================================
TRAIN-TEST SPLIT
======================================================================
X_train : (790, 24)
X_test  : (198, 24)
y_train : (790,)
y_test  : (198,)

Training class distribution:

Class
1    51.27
0    48.73
Name: proportion, dtype: float64

Testing class distribution:

Class
1    51.52
0    48.48
Name: proportion, dtype: float64

In [8]:
# =============================================================================
# STEP 6: FEATURE-SCALE CHECK
# =============================================================================
# mRMR is applied to the training data after fold-specific preprocessing.
# Scaling is fitted only on the corresponding training partition.
#
# Logistic Regression is scaled again after feature selection.
# Random Forest and XGBoost use the selected features without downstream scaling.

print("mRMR will be fitted using training data only.")
print("Logistic Regression will be scaled after feature selection.")
print("Random Forest and XGBoost will use the selected features without scaling.")

mRMR will be fitted using training data only.
Logistic Regression will be scaled after feature selection.
Random Forest and XGBoost will use the selected features without scaling.

# 1. mRMR Baseline

mRMR is used as the statistical feature-selection baseline.

**Important:** mRMR is fitted on all 24 predictors first. The complete mRMR ranking is generated before Top-K is applied.

In [9]:
# =============================================================================
# STEP 7: mRMR RANKING FOR ALL FEATURES
# =============================================================================

from mrmr import mrmr_classif
from sklearn.preprocessing import StandardScaler

mrmr_scaler = StandardScaler()

X_train_mrmr_scaled = pd.DataFrame(
    mrmr_scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_mrmr_scaled = pd.DataFrame(
    mrmr_scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

# mRMR expects clean, aligned pandas objects.
X_mrmr_train = X_train_mrmr_scaled.reset_index(drop=True)
y_mrmr_train = y_train.reset_index(drop=True)

mrmr_ranked_features = mrmr_classif(
    X=X_mrmr_train,
    y=y_mrmr_train,
    K=X_mrmr_train.shape[1]
)

# Convert the complete mRMR ordering into decreasing normalized scores.
# Rank 1 = 1.0; rank 24 = 1/24.
n_features = len(mrmr_ranked_features)

mrmr_scores = pd.DataFrame({
    "Feature": mrmr_ranked_features,
    "mRMR_Score": [
        (n_features - rank) / n_features
        for rank in range(n_features)
    ]
})

mrmr_scores["mRMR_Rank"] = np.arange(
    1,
    len(mrmr_scores) + 1
)

display(mrmr_scores)

100%|██████████| 24/24 [00:07<00:00,  3.29it/s]

   Feature  mRMR_Score  mRMR_Rank
0       Bp    1.000000          1
1       Su    0.958333          2
2       Sg    0.916667          3
3       Ba    0.875000          4
4      Bgr    0.833333          5
5      Ane    0.791667          6
6       Bu    0.750000          7
7      Pcv    0.708333          8
8       Sc    0.666667          9
9     Rbcc    0.625000         10
10      Dm    0.583333         11
11   Appet    0.541667         12
12     Pcc    0.500000         13
13      Pe    0.458333         14
14      Al    0.416667         15
15     Pot    0.375000         16
16    Wbcc    0.333333         17
17     Htn    0.291667         18
18     Cad    0.250000         19
19     Rbc    0.208333         20
20    Hemo    0.166667         21
21     Age    0.125000         22
22     Sod    0.083333         23
23      Pc    0.041667         24

In [10]:
# =============================================================================
# STEP 8: TOP-K mRMR FEATURE SETS
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")

mrmr_results = {}

for top_k in TOP_K_VALUES:

    selected = (
        mrmr_scores
        .head(top_k)["Feature"]
        .tolist()
    )

    mrmr_results[top_k] = {
        "features": selected,
        "X_train": X_train[selected].copy(),
        "X_test": X_test[selected].copy()
    }

    print("=" * 70)
    print(f"mRMR TOP-{top_k}")
    print("=" * 70)
    print(selected)

Total predictors: 24
Top-K values: [5, 10, 15, 20]
======================================================================
mRMR TOP-5
======================================================================
['Bp', 'Su', 'Sg', 'Ba', 'Bgr']
======================================================================
mRMR TOP-10
======================================================================
['Bp', 'Su', 'Sg', 'Ba', 'Bgr', 'Ane', 'Bu', 'Pcv', 'Sc', 'Rbcc']
======================================================================
mRMR TOP-15
======================================================================
['Bp', 'Su', 'Sg', 'Ba', 'Bgr', 'Ane', 'Bu', 'Pcv', 'Sc', 'Rbcc', 'Dm', 'Appet', 'Pcc', 'Pe', 'Al']
======================================================================
mRMR TOP-20
======================================================================
['Bp', 'Su', 'Sg', 'Ba', 'Bgr', 'Ane', 'Bu', 'Pcv', 'Sc', 'Rbcc', 'Dm', 'Appet', 'Pcc', 'Pe', 'Al', 'Pot', 'Wbcc', 'Htn', 'Cad', 'Rbc']

In [11]:
# =============================================================================
# STEP 9: DOWNSTREAM MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1
    )
}

print(list(models.keys()))

['Logistic Regression', 'Random Forest', 'XGBoost']

In [12]:
# =============================================================================
# STEP 10: mRMR BASELINE MODEL EVALUATION
# =============================================================================

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

fixed_mrmr_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = mrmr_results[top_k]["X_train"]
    Xte_selected = mrmr_results[top_k]["X_test"]
    selected_features = mrmr_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_mrmr_rows.append({
            "Method": "mRMR",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_mrmr_results_df = pd.DataFrame(fixed_mrmr_rows)
display(fixed_mrmr_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,mRMR,5,Logistic Regression,"Bp, Su, Sg, Ba, Bgr",0.5404,0.5455,0.6471,0.5919,0.5828
1,mRMR,5,Random Forest,"Bp, Su, Sg, Ba, Bgr",0.5505,0.5730,0.5000,0.5340,0.5805
2,mRMR,5,XGBoost,"Bp, Su, Sg, Ba, Bgr",0.5657,0.5800,0.5686,0.5743,0.5416
3,mRMR,10,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.5556,0.5625,0.6176,0.5888,0.5901
4,mRMR,10,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.4899,0.5053,0.4706,0.4873,0.5075
5,mRMR,10,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.5152,0.5312,0.5000,0.5152,0.5066
6,mRMR,15,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5556,0.5660,0.5882,0.5769,0.5684
7,mRMR,15,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5303,0.5474,0.5098,0.5279,0.5233
8,mRMR,15,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5253,0.5392,0.5392,0.5392,0.5413
9,mRMR,20,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5505,0.5596,0.5980,0.5782,0.5751
10,mRMR,20,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5101,0.5253,0.5098,0.5174,0.5290
11,mRMR,20,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5354,0.5455,0.5882,0.5660,0.5167

In [13]:
# =============================================================================
# STEP 11: SAVE mRMR BASELINE
# =============================================================================

baseline_dir = Path("../../../results/kidney_disease/baseline")
baseline_dir.mkdir(parents=True, exist_ok=True)

baseline_path = baseline_dir / "mrmr_baseline_results.csv"
fixed_mrmr_results_df.to_csv(baseline_path, index=False)

print(f"Saved: {baseline_path.resolve()}")

Saved: C:\Users\johnm\msc_research\results\kidney_disease\baseline\mrmr_baseline_results.csv

# 2. DODA Clinical Re-ranking

### Correct experimental order

```text
24 original predictors
        ↓
mRMR ranking for all 24
        ↓
statistical ranking
        +
pre-specified clinical weights
        ↓
DODA RankFusion
        ↓
final Top-K
```

DODA must **not** receive an already-truncated mRMR Top-K set. Otherwise, clinically prioritized features outside that preliminary Top-K would be impossible to recover.

In [14]:
# =============================================================================
# STEP 12: INSTALL / IMPORT DODA
# =============================================================================

# Run the following installation once if DODA is not installed:
# %pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

import doda

from doda import DODASelector
from doda.adapters import SklearnAdapter
from doda.knowledge.providers import JSONProvider
from doda.fusion import RankFusion

print("DODA:", doda.__file__)

print("Provider:", JSONProvider)
print("Fusion:", RankFusion)

DODA: c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\__init__.py
Provider: <class 'doda.knowledge.providers.json_provider.JSONProvider'>
Fusion: <class 'doda.fusion.rank.RankFusion'>

In [15]:
# =============================================================================
# STEP 13: LOCATE AND VALIDATE CLINICAL WEIGHTS
# =============================================================================

from pathlib import Path
from doda.knowledge.providers import JSONProvider

WEIGHTS_FILENAME = "BD_KDD_clinical_weights.json"

search_roots = [Path.cwd(), *Path.cwd().parents]
matches = []

for root in search_roots:
    try:
        matches.extend(root.rglob(WEIGHTS_FILENAME))
    except (PermissionError, OSError):
        continue

# Remove duplicates while preserving order
matches = list(dict.fromkeys(matches))

if not matches:
    raise FileNotFoundError(
        f"{WEIGHTS_FILENAME} was not found. "
        "Place it in the repository and rerun this cell."
    )

WEIGHTS_PATH = matches[0]

print(f"Using clinical weights: {WEIGHTS_PATH.resolve()}")

# Use the standard DODA JSON provider
provider = JSONProvider(str(WEIGHTS_PATH))

# Validate coverage using the flat JSON directly
import json

with open(WEIGHTS_PATH, "r", encoding="utf-8") as f:
    clinical_weights = json.load(f)

missing_weights = sorted(
    set(X.columns) - set(clinical_weights)
)

extra_weights = sorted(
    set(clinical_weights) - set(X.columns)
)

print(f"Clinical weights: {len(clinical_weights)}")
print(f"Predictors:       {len(X.columns)}")
print(f"Missing weights:  {missing_weights}")
print(f"Extra weights:    {extra_weights}")

assert not missing_weights
assert not extra_weights

Using clinical weights: C:\Users\johnm\msc_research\config\clinical_weights\BD_KDD_clinical_weights.json
Clinical weights: 24
Predictors:       24
Missing weights:  []
Extra weights:    []

In [16]:
# =============================================================================
# STEP 14: DODA — mRMR SCORE ALL FEATURES, THEN APPLY TOP-K
# =============================================================================

class MRMRAdapter:
    """
    Adapter that runs mRMR on all available features and exposes the
    complete ranking as normalized operator importance scores.
    """

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):
        X_local = pd.DataFrame(X).copy()
        X_local.columns = list(X.columns)
        X_local = X_local.reset_index(drop=True)
        y_local = pd.Series(y).reset_index(drop=True)

        ranked_features = mrmr_classif(
            X=X_local,
            y=y_local,
            K=X_local.shape[1]
        )

        n_features = len(ranked_features)

        self.importance = {
            feature: (n_features - rank) / n_features
            for rank, feature in enumerate(ranked_features)
        }

        return self

    def get_importance(self):
        return self.importance

    def get_name(self):
        return "mRMR"


rank_doda_results = {}

for top_k in TOP_K_VALUES:

    mrmr_operator = MRMRAdapter()

    doda_selector = DODASelector(
        operators=[mrmr_operator],
        provider=provider,
        fusion=RankFusion(),
        top_k=top_k
    )

    # Fit on the scaled training data only.
    doda_selector.fit(
        X_train_mrmr_scaled,
        y_train
    )

    selected_features = list(
        doda_selector.get_selected_features()
    )

    rank_doda_results[top_k] = {
        "selector": doda_selector,
        "features": selected_features,
        "X_train": X_train[selected_features].copy(),
        "X_test": X_test[selected_features].copy()
    }

    print("=" * 70)
    print(f"DODA TOP-{top_k}")
    print("=" * 70)
    print(selected_features)
    print(f"Number selected: {len(selected_features)}")

    assert len(selected_features) == top_k

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D6DBA10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.34it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ane': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Pcv': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Dm': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Al': np.float64(0.4166666666666667), 'Pot': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Sod': np.float64(0.08333333333333333), 'Pc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Ba': 0.4, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcv': 0.7, 'Sc': 1.0, 'Rbcc': 0.55, 'Dm': 0.8, 'Appet': 0.4, 'Pcc': 0.4, 'Pe': 0.65, 'Al': 1.0, 'Pot': 0.65, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Rbc': 0.55, 'Hemo': 0.75, 'Age': 0.55, 'Sod': 0.65, 'Pc': 0.5}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Ane': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Pcv': 0.029857397504456328, 'Sc': 0.030886196246139225, 'Rbcc': 0.028991596638655463, 'Dm': 0.029709507042253523, 'Appet': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Pe': 0.028438886647841874, 'Al': 0.029726775956284153, 'Pot': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Rbc': 0.027205882352941177, 'Hemo': 0.027730294396961064, 'Age': 0.02690100430416069, 'Sod': 0.026973565905412694, 'Pc': 0.026397515527950312}
Top 5 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su']
======================================================================
DODA TOP-5
======================================================================
['Bp', 'Sg', 'Bu', 'Sc', 'Su']
Number selected: 5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D6DBA10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ane': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Pcv': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Dm': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Al': np.float64(0.4166666666666667), 'Pot': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Sod': np.float64(0.08333333333333333), 'Pc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Ba': 0.4, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcv': 0.7, 'Sc': 1.0, 'Rbcc': 0.55, 'Dm': 0.8, 'Appet': 0.4, 'Pcc': 0.4, 'Pe': 0.65, 'Al': 1.0, 'Pot': 0.65, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Rbc': 0.55, 'Hemo': 0.75, 'Age': 0.55, 'Sod': 0.65, 'Pc': 0.5}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Ane': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Pcv': 0.029857397504456328, 'Sc': 0.030886196246139225, 'Rbcc': 0.028991596638655463, 'Dm': 0.029709507042253523, 'Appet': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Pe': 0.028438886647841874, 'Al': 0.029726775956284153, 'Pot': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Rbc': 0.027205882352941177, 'Hemo': 0.027730294396961064, 'Age': 0.02690100430416069, 'Sod': 0.026973565905412694, 'Pc': 0.026397515527950312}
Top 10 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba']
======================================================================
DODA TOP-10
======================================================================
['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba']
Number selected: 10
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D6DBA10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.37it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ane': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Pcv': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Dm': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Al': np.float64(0.4166666666666667), 'Pot': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Sod': np.float64(0.08333333333333333), 'Pc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Ba': 0.4, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcv': 0.7, 'Sc': 1.0, 'Rbcc': 0.55, 'Dm': 0.8, 'Appet': 0.4, 'Pcc': 0.4, 'Pe': 0.65, 'Al': 1.0, 'Pot': 0.65, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Rbc': 0.55, 'Hemo': 0.75, 'Age': 0.55, 'Sod': 0.65, 'Pc': 0.5}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Ane': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Pcv': 0.029857397504456328, 'Sc': 0.030886196246139225, 'Rbcc': 0.028991596638655463, 'Dm': 0.029709507042253523, 'Appet': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Pe': 0.028438886647841874, 'Al': 0.029726775956284153, 'Pot': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Rbc': 0.027205882352941177, 'Hemo': 0.027730294396961064, 'Age': 0.02690100430416069, 'Sod': 0.026973565905412694, 'Pc': 0.026397515527950312}
Top 15 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba', 'Dm', 'Rbcc', 'Htn', 'Pe', 'Pot']
======================================================================
DODA TOP-15
======================================================================
['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba', 'Dm', 'Rbcc', 'Htn', 'Pe', 'Pot']
Number selected: 15
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D6DBA10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.47it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Ane': 0.7916666666666666, 'Bu': 0.75, 'Pcv': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Rbcc': 0.625, 'Dm': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Pcc': 0.5, 'Pe': 0.4583333333333333, 'Al': 0.4166666666666667, 'Pot': 0.375, 'Wbcc': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Rbc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Age': 0.125, 'Sod': 0.08333333333333333, 'Pc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ane': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Pcv': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Dm': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Al': np.float64(0.4166666666666667), 'Pot': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Sod': np.float64(0.08333333333333333), 'Pc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Ba': 0.4, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcv': 0.7, 'Sc': 1.0, 'Rbcc': 0.55, 'Dm': 0.8, 'Appet': 0.4, 'Pcc': 0.4, 'Pe': 0.65, 'Al': 1.0, 'Pot': 0.65, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Rbc': 0.55, 'Hemo': 0.75, 'Age': 0.55, 'Sod': 0.65, 'Pc': 0.5}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Ane': 0.030303030303030304, 'Bu': 0.031054405392392875, 'Pcv': 0.029857397504456328, 'Sc': 0.030886196246139225, 'Rbcc': 0.028991596638655463, 'Dm': 0.029709507042253523, 'Appet': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Pe': 0.028438886647841874, 'Al': 0.029726775956284153, 'Pot': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Rbc': 0.027205882352941177, 'Hemo': 0.027730294396961064, 'Age': 0.02690100430416069, 'Sod': 0.026973565905412694, 'Pc': 0.026397515527950312}
Top 20 Features Selected: ['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba', 'Dm', 'Rbcc', 'Htn', 'Pe', 'Pot', 'Appet', 'Pcc', 'Hemo', 'Rbc', 'Wbcc']
======================================================================
DODA TOP-20
======================================================================
['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba', 'Dm', 'Rbcc', 'Htn', 'Pe', 'Pot', 'Appet', 'Pcc', 'Hemo', 'Rbc', 'Wbcc']
Number selected: 20

In [17]:
# =============================================================================
# STEP 15: INSPECT DODA RANK CHANGES
# =============================================================================

INSPECTION_TOP_K = 10

selector = rank_doda_results[INSPECTION_TOP_K]["selector"]

print("=" * 70)
print(f"DODA RANK COMPARISON — TOP-{INSPECTION_TOP_K}")
print("=" * 70)

rank_comparison = selector.compare_scores()

display(rank_comparison)

print("\nSelected features:")
print(rank_doda_results[INSPECTION_TOP_K]["features"])

======================================================================
DODA RANK COMPARISON — TOP-10
======================================================================

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
  Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0      Bp          1              6           1            0
1      Sg          3              4           2            1
2      Bu          7              3           3            4
3      Sc          9              1           4            5
4      Su          2             15           5           -3
5     Bgr          5              9           6           -1
6     Ane          6             10           7           -1
7     Pcv          8             11           8            0
8      Al         15              2           9            6
9      Ba          4             21          10           -6

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,Bp,1,1.0000,6,0.80,1,0.0320,0
1,Sg,3,0.9167,4,0.85,2,0.0317,1
2,Bu,7,0.7500,3,0.90,3,0.0311,4
3,Sc,9,0.6667,1,1.00,4,0.0309,5
4,Su,2,0.9583,15,0.55,5,0.0308,-3
5,Bgr,5,0.8333,9,0.70,6,0.0305,-1
6,Ane,6,0.7917,10,0.70,7,0.0303,-1
7,Pcv,8,0.7083,11,0.70,8,0.0299,0
8,Al,15,0.4167,2,1.00,9,0.0297,6
9,Ba,4,0.8750,21,0.40,10,0.0297,-6
10,Dm,11,0.5833,7,0.80,11,0.0297,0
11,Rbcc,10,0.6250,16,0.55,12,0.0290,-2
12,Htn,18,0.2917,5,0.85,13,0.0287,5
13,Pe,14,0.4583,12,0.65,14,0.0284,0
14,Pot,16,0.3750,13,0.65,15,0.0281,1
15,Appet,12,0.5417,22,0.40,16,0.0280,-4
16,Pcc,13,0.5000,23,0.40,17,0.0278,-4
17,Hemo,21,0.1667,8,0.75,18,0.0277,3
18,Rbc,20,0.2083,17,0.55,19,0.0272,1
19,Wbcc,17,0.3333,24,0.40,20,0.0271,-3
20,Sod,23,0.0833,14,0.65,21,0.0270,2
21,Cad,19,0.2500,20,0.45,22,0.0269,-3
22,Age,22,0.1250,18,0.55,23,0.0269,-1
23,Pc,24,0.0417,19,0.50,24,0.0264,0

Selected features:
['Bp', 'Sg', 'Bu', 'Sc', 'Su', 'Bgr', 'Ane', 'Pcv', 'Al', 'Ba']

In [18]:
# =============================================================================
# STEP 15B: EXPLICIT mRMR vs DODA RANK-SHIFT TABLE
# =============================================================================
# This table separates:
#   - statistical mRMR rank
#   - DODA final rank
#   - clinical weight
#   - rank movement
#
# Positive Rank_Change means the feature moved upward.
# Example: mRMR rank 10 -> DODA rank 4 = +6
#
# IMPORTANT:
# The selector is explicitly retrieved from rank_doda_results
# for the selected Top-K value. This avoids relying on a
# previously defined 'selector' variable.

# -------------------------------------------------------------------------
# Select which DODA Top-K experiment to inspect
# -------------------------------------------------------------------------

k = 10

if k not in rank_doda_results:
    raise KeyError(
        f"Top-K={k} was not found in rank_doda_results. "
        f"Available values: {list(rank_doda_results.keys())}"
    )

selector = rank_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# mRMR / mathematical ranking
# -------------------------------------------------------------------------

math_rank = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "mRMR_Normalized_Score"
    ]
)

math_rank["mRMR_Rank"] = (
    math_rank["mRMR_Normalized_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# DODA final ranking
# -------------------------------------------------------------------------

final_rank = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "DODA_Final_Score"
    ]
)

final_rank["DODA_Rank"] = (
    final_rank["DODA_Final_Score"]
    .rank(
        method="min",
        ascending=False
    )
    .astype(int)
)


# -------------------------------------------------------------------------
# Combine rankings
# -------------------------------------------------------------------------

rank_shift_df = (
    math_rank[
        [
            "Feature",
            "mRMR_Normalized_Score",
            "mRMR_Rank"
        ]
    ]
    .merge(
        final_rank[
            [
                "Feature",
                "DODA_Final_Score",
                "DODA_Rank"
            ]
        ],
        on="Feature",
        how="inner"
    )
)


# -------------------------------------------------------------------------
# Add clinical weights
# -------------------------------------------------------------------------

rank_shift_df["Clinical_Weight"] = (
    rank_shift_df["Feature"]
    .map(selector.clinical_weights_)
)


# -------------------------------------------------------------------------
# Calculate rank movement
# -------------------------------------------------------------------------
# Positive value  = moved upward
# Negative value  = moved downward
# Zero             = no rank movement

rank_shift_df["Rank_Change"] = (
    rank_shift_df["mRMR_Rank"]
    - rank_shift_df["DODA_Rank"]
)


# -------------------------------------------------------------------------
# Sort by DODA final rank
# -------------------------------------------------------------------------

rank_shift_df = (
    rank_shift_df
    .sort_values(
        by="DODA_Rank"
    )
    .reset_index(drop=True)
)


# -------------------------------------------------------------------------
# Display
# -------------------------------------------------------------------------

print("=" * 80)
print(f"mRMR vs DODA RANK-SHIFT ANALYSIS — TOP-{k}")
print("=" * 80)

display(rank_shift_df)

================================================================================
mRMR vs DODA RANK-SHIFT ANALYSIS — TOP-10
================================================================================

,Feature,mRMR_Normalized_Score,mRMR_Rank,DODA_Final_Score,DODA_Rank,Clinical_Weight,Rank_Change
0,Bp,1.000000,1,0.032018,1,0.80,0
1,Sg,0.916667,3,0.031746,2,0.85,1
2,Bu,0.750000,7,0.031054,3,0.90,4
3,Sc,0.666667,9,0.030886,4,1.00,5
4,Su,0.958333,2,0.030835,5,0.55,-3
5,Bgr,0.833333,5,0.030536,6,0.70,-1
6,Ane,0.791667,6,0.030303,7,0.70,-1
7,Pcv,0.708333,8,0.029857,8,0.70,0
8,Al,0.416667,15,0.029727,9,1.00,6
9,Ba,0.875000,4,0.029710,10,0.40,-6
10,Dm,0.583333,11,0.029710,10,0.80,1
11,Rbcc,0.625000,10,0.028992,12,0.55,-2
12,Htn,0.291667,18,0.028694,13,0.85,5
13,Pe,0.458333,14,0.028439,14,0.65,0
14,Pot,0.375000,16,0.028083,15,0.65,1
15,Appet,0.541667,12,0.027973,16,0.40,-4
16,Pcc,0.500000,13,0.027783,17,0.40,-4
17,Hemo,0.166667,21,0.027730,18,0.75,3
18,Rbc,0.208333,20,0.027206,19,0.55,1
19,Wbcc,0.333333,17,0.027072,20,0.40,-3
20,Sod,0.083333,23,0.026974,21,0.65,2
21,Cad,0.250000,19,0.026944,22,0.45,-3
22,Age,0.125000,22,0.026901,23,0.55,-1
23,Pc,0.041667,24,0.026398,24,0.50,0

In [19]:
# =============================================================================
# STEP 16: INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weight_table = pd.DataFrame({
    "Feature": list(selector.clinical_weights_.keys()),
    "Clinical_Weight": list(selector.clinical_weights_.values())
}).sort_values(
    "Clinical_Weight",
    ascending=False
).reset_index(drop=True)

display(clinical_weight_table)

   Feature  Clinical_Weight
0       Al             1.00
1       Sc             1.00
2       Bu             0.90
3       Sg             0.85
4      Htn             0.85
5       Dm             0.80
6       Bp             0.80
7     Hemo             0.75
8      Bgr             0.70
9      Ane             0.70
10     Pcv             0.70
11     Sod             0.65
12     Pot             0.65
13      Pe             0.65
14     Age             0.55
15      Su             0.55
16    Rbcc             0.55
17     Rbc             0.55
18      Pc             0.50
19     Cad             0.45
20      Ba             0.40
21   Appet             0.40
22     Pcc             0.40
23    Wbcc             0.40

In [20]:
# =============================================================================
# STEP 17: DODA MODEL EVALUATION — FIXED SPLIT
# =============================================================================

fixed_doda_rows = []

for top_k in TOP_K_VALUES:

    Xtr_selected = rank_doda_results[top_k]["X_train"]
    Xte_selected = rank_doda_results[top_k]["X_test"]
    selected_features = rank_doda_results[top_k]["features"]

    for model_name, model_template in models.items():

        model = model_template.__class__(
            **model_template.get_params()
        )

        Xtr = Xtr_selected
        Xte = Xte_selected

        if model_name == "Logistic Regression":
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xte = scaler.transform(Xte)

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xte)
        y_prob = model.predict_proba(Xte)[:, 1]

        fixed_doda_rows.append({
            "Method": "DODA",
            "Top_K": top_k,
            "Model": model_name,
            "Selected_Features": ", ".join(selected_features),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, zero_division=0),
            "Recall": recall_score(y_test, y_pred, zero_division=0),
            "F1": f1_score(y_test, y_pred, zero_division=0),
            "ROC_AUC": roc_auc_score(y_test, y_prob)
        })

fixed_doda_results_df = pd.DataFrame(fixed_doda_rows)
display(fixed_doda_results_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,DODA,5,Logistic Regression,"Bp, Sg, Bu, Sc, Su",0.5505,0.5575,0.6176,0.5860,0.5524
1,DODA,5,Random Forest,"Bp, Sg, Bu, Sc, Su",0.4697,0.4848,0.4706,0.4776,0.4526
2,DODA,5,XGBoost,"Bp, Sg, Bu, Sc, Su",0.5000,0.5146,0.5196,0.5171,0.4922
3,DODA,10,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5354,0.5446,0.5980,0.5701,0.5797
4,DODA,10,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5253,0.5392,0.5392,0.5392,0.5447
5,DODA,10,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5303,0.5437,0.5490,0.5463,0.5350
6,DODA,15,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5657,0.5727,0.6176,0.5943,0.5856
7,DODA,15,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.4949,0.5104,0.4804,0.4949,0.5362
8,DODA,15,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.4697,0.4865,0.5294,0.5070,0.4970
9,DODA,20,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5707,0.5794,0.6078,0.5933,0.5763
10,DODA,20,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5152,0.5306,0.5098,0.5200,0.5481
11,DODA,20,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5051,0.5192,0.5294,0.5243,0.5156

In [21]:
# =============================================================================
# STEP 18: FIXED-SPLIT mRMR vs DODA COMPARISON
# =============================================================================

fixed_comparison_df = pd.concat(
    [fixed_mrmr_results_df, fixed_doda_results_df],
    ignore_index=True
)

display(fixed_comparison_df.round(4))

,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,mRMR,5,Logistic Regression,"Bp, Su, Sg, Ba, Bgr",0.5404,0.5455,0.6471,0.5919,0.5828
1,mRMR,5,Random Forest,"Bp, Su, Sg, Ba, Bgr",0.5505,0.5730,0.5000,0.5340,0.5805
2,mRMR,5,XGBoost,"Bp, Su, Sg, Ba, Bgr",0.5657,0.5800,0.5686,0.5743,0.5416
3,mRMR,10,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.5556,0.5625,0.6176,0.5888,0.5901
4,mRMR,10,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.4899,0.5053,0.4706,0.4873,0.5075
5,mRMR,10,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc",0.5152,0.5312,0.5000,0.5152,0.5066
6,mRMR,15,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5556,0.5660,0.5882,0.5769,0.5684
7,mRMR,15,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5303,0.5474,0.5098,0.5279,0.5233
8,mRMR,15,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5253,0.5392,0.5392,0.5392,0.5413
9,mRMR,20,Logistic Regression,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5505,0.5596,0.5980,0.5782,0.5751
10,mRMR,20,Random Forest,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5101,0.5253,0.5098,0.5174,0.5290
11,mRMR,20,XGBoost,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...",0.5354,0.5455,0.5882,0.5660,0.5167
12,DODA,5,Logistic Regression,"Bp, Sg, Bu, Sc, Su",0.5505,0.5575,0.6176,0.5860,0.5524
13,DODA,5,Random Forest,"Bp, Sg, Bu, Sc, Su",0.4697,0.4848,0.4706,0.4776,0.4526
14,DODA,5,XGBoost,"Bp, Sg, Bu, Sc, Su",0.5000,0.5146,0.5196,0.5171,0.4922
15,DODA,10,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5354,0.5446,0.5980,0.5701,0.5797
16,DODA,10,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5253,0.5392,0.5392,0.5392,0.5447
17,DODA,10,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",0.5303,0.5437,0.5490,0.5463,0.5350
18,DODA,15,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5657,0.5727,0.6176,0.5943,0.5856
19,DODA,15,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.4949,0.5104,0.4804,0.4949,0.5362
20,DODA,15,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.4697,0.4865,0.5294,0.5070,0.4970
21,DODA,20,Logistic Regression,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5707,0.5794,0.6078,0.5933,0.5763
22,DODA,20,Random Forest,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5152,0.5306,0.5098,0.5200,0.5481
23,DODA,20,XGBoost,"Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",0.5051,0.5192,0.5294,0.5243,0.5156

In [22]:
# =============================================================================
# STEP 19: COMPARE FEATURE SETS ON THE FIXED SPLIT
# =============================================================================

fixed_feature_comparison = []

for top_k in TOP_K_VALUES:

    mrmr_set = set(mrmr_results[top_k]["features"])
    doda_set = set(rank_doda_results[top_k]["features"])

    intersection = mrmr_set & doda_set
    union = mrmr_set | doda_set

    jaccard = len(intersection) / len(union)

    fixed_feature_comparison.append({
        "Top_K": top_k,
        "mRMR_Features": ", ".join(mrmr_results[top_k]["features"]),
        "DODA_Features": ", ".join(rank_doda_results[top_k]["features"]),
        "Same_Feature_Set": mrmr_set == doda_set,
        "Overlap_Count": len(intersection),
        "Jaccard": jaccard,
        "Features_Changed": top_k - len(intersection)
    })

fixed_feature_comparison_df = pd.DataFrame(fixed_feature_comparison)

display(fixed_feature_comparison_df)

,Top_K,mRMR_Features,DODA_Features,Same_Feature_Set,Overlap_Count,Jaccard,Features_Changed
0,5,"Bp, Su, Sg, Ba, Bgr","Bp, Sg, Bu, Sc, Su",False,3,0.428571,2
1,10,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc","Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba",False,9,0.818182,1
2,15,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...","Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",False,13,0.764706,2
3,20,"Bp, Su, Sg, Ba, Bgr, Ane, Bu, Pcv, Sc, Rbcc, D...","Bp, Sg, Bu, Sc, Su, Bgr, Ane, Pcv, Al, Ba, Dm,...",False,19,0.904762,1

In [23]:
# =============================================================================
# STEP 20: SAVE FIXED-SPLIT DODA RESULTS
# =============================================================================

doda_dir = Path("../../../results/kidney_disease/doda")
doda_dir.mkdir(parents=True, exist_ok=True)

fixed_doda_results_df.to_csv(
    doda_dir / "mrmr_doda_fixed_split_results.csv",
    index=False
)

fixed_feature_comparison_df.to_csv(
    doda_dir / "mrmr_doda_fixed_split_feature_comparison.csv",
    index=False
)

print(f"Saved results to: {doda_dir.resolve()}")

Saved results to: C:\Users\johnm\msc_research\results\kidney_disease\doda

# 3.1 Five-Fold Stratified Cross-Validation

The fixed 80/20 split is followed by a separate **5-fold stratified cross-validation** experiment.

Feature selection is refit inside each training fold. DODA also receives all features and performs the final Top-K selection inside the training fold. Logistic Regression scaling is fitted only on the corresponding training fold.

The DODA fusion method remains **RankFusion**, matching the current BD-KDD pipeline.

In [24]:
# =============================================================================
# STEP 21: 5-FOLD CV CONFIGURATION
# =============================================================================
from sklearn.model_selection import StratifiedKFold

CV5_SPLITS = 5
CV5_RANDOM_STATE = 42
cv5 = StratifiedKFold(n_splits=CV5_SPLITS, shuffle=True, random_state=CV5_RANDOM_STATE)
cv5_results = []

print("5-fold CV configuration loaded.")
print("Splits:", CV5_SPLITS)
print("Top-K values:", TOP_K_VALUES)
print("Fusion: RankFusion")

5-fold CV configuration loaded.
Splits: 5
Top-K values: [5, 10, 15, 20]
Fusion: RankFusion

In [25]:
# =============================================================================
# STEP 22: 5-FOLD CV — mRMR vs DODA
# =============================================================================

# Reset results before running the CV.
# This prevents duplicate rows if the cell is executed more than once.
cv5_results = []

for fold, (train_idx, val_idx) in enumerate(
    cv5.split(X, y),
    start=1
):

    X_train_fold = X.iloc[train_idx].copy()
    X_val_fold = X.iloc[val_idx].copy()

    y_train_fold = y.iloc[train_idx].copy()
    y_val_fold = y.iloc[val_idx].copy()

    # -------------------------------------------------------------------------
    # Scale ONLY using the training-fold statistics before mRMR selection.
    # -------------------------------------------------------------------------

    fold_scaler = StandardScaler()

    X_train_fold_scaled = pd.DataFrame(
        fold_scaler.fit_transform(X_train_fold),
        columns=X_train_fold.columns,
        index=X_train_fold.index
    )

    X_val_fold_scaled = pd.DataFrame(
        fold_scaler.transform(X_val_fold),
        columns=X_val_fold.columns,
        index=X_val_fold.index
    )

    # -------------------------------------------------------------------------
    # mRMR ranking is learned ONLY from the training fold.
    # -------------------------------------------------------------------------

    X_mrmr_fold = X_train_fold_scaled.reset_index(drop=True)
    y_mrmr_fold = y_train_fold.reset_index(drop=True)

    mrmr_fold_ranked = mrmr_classif(
        X=X_mrmr_fold,
        y=y_mrmr_fold,
        K=X_mrmr_fold.shape[1]
    )

    # -------------------------------------------------------------------------
    # Evaluate each Top-K
    # -------------------------------------------------------------------------

    for top_k in TOP_K_VALUES:

        mrmr_features = mrmr_fold_ranked[:top_k]

        fold_doda = DODASelector(
            operators=[MRMRAdapter()],
            provider=JSONProvider(str(WEIGHTS_PATH)),
            fusion=RankFusion(),
            top_k=top_k
        )

        fold_doda.fit(
            X_train_fold_scaled,
            y_train_fold
        )

        doda_features = list(
            fold_doda.get_selected_features()
        )

        feature_sets = {
            "mRMR": mrmr_features,
            "DODA": doda_features
        }

        for method, selected_features in feature_sets.items():

            Xtr_selected = X_train_fold[selected_features]
            Xval_selected = X_val_fold[selected_features]

            for model_name, model_template in models.items():

                model = model_template.__class__(
                    **model_template.get_params()
                )

                Xtr = Xtr_selected
                Xval = Xval_selected

                if model_name == "Logistic Regression":
                    scaler = StandardScaler()
                    Xtr = scaler.fit_transform(Xtr)
                    Xval = scaler.transform(Xval)

                model.fit(Xtr, y_train_fold)

                y_pred = model.predict(Xval)
                y_prob = model.predict_proba(Xval)[:, 1]

                cv5_results.append({
                    "Fold": fold,
                    "Method": method,
                    "Top_K": top_k,
                    "Model": model_name,
                    "Selected_Features": ", ".join(selected_features),
                    "Accuracy": accuracy_score(y_val_fold, y_pred),
                    "Precision": precision_score(y_val_fold, y_pred, zero_division=0),
                    "Recall": recall_score(y_val_fold, y_pred, zero_division=0),
                    "F1": f1_score(y_val_fold, y_pred, zero_division=0),
                    "ROC_AUC": roc_auc_score(y_val_fold, y_prob)
                })

cv5_results_df = pd.DataFrame(cv5_results)

expected_rows = CV5_SPLITS * len(TOP_K_VALUES) * 2 * len(models)

print(f"Expected rows: {expected_rows}")
print(f"Actual rows:   {len(cv5_results_df)}")

assert len(cv5_results_df) == expected_rows

display(cv5_results_df.round(4))

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D73A490>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.65it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 5 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D73AAD0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.64it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 10 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D6B5350>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:08<00:00,  2.81it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 15 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc', 'Age', 'Htn', 'Sod', 'Al', 'Pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F8F0C30>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.22it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 20 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc', 'Age', 'Htn', 'Sod', 'Al', 'Pc', 'Ane', 'Rbc', 'Bu', 'Pcv', 'Dm']

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA77890>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.70it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 5 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D70F460>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.68it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 10 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F905480>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.72it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 15 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc', 'Htn', 'Ane', 'Wbcc', 'Pc', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F8FF150>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.44it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 20 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc', 'Htn', 'Ane', 'Wbcc', 'Pc', 'Sod', 'Hemo', 'Appet', 'Su', 'Dm', 'Pcc']

100%|██████████| 24/24 [00:06<00:00,  3.49it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F8FEC50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D702C60>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.65it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D703E30>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane', 'Rbcc', 'Pe', 'Sod', 'Appet', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F95B5B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane', 'Rbcc', 'Pe', 'Sod', 'Appet', 'Dm', 'Sg', 'Htn', 'Age', 'Cad', 'Hemo']

100%|██████████| 24/24 [00:06<00:00,  3.62it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F9583D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.59it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03430600>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.24it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7D51AC90>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:08<00:00,  2.83it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc', 'Pcv', 'Sod', 'Sg', 'Ane', 'Rbc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F953110>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.45it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc', 'Pcv', 'Sod', 'Sg', 'Ane', 'Rbc', 'Dm', 'Htn', 'Appet', 'Age', 'Hemo']

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0348DF40>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.43it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03496BA0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.36it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0341F390>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.42it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba', 'Rbcc', 'Al', 'Bgr', 'Pot', 'Appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0349DB30>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba', 'Rbcc', 'Al', 'Bgr', 'Pot', 'Appet', 'Sod', 'Hemo', 'Dm', 'Pe', 'Pcc']
Expected rows: 120
Actual rows:   120

,Fold,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,1,mRMR,5,Logistic Regression,"Bp, Ba, Sg, Pot, Hemo",0.4899,0.5000,0.5347,0.5167,0.5135
1,1,mRMR,5,Random Forest,"Bp, Ba, Sg, Pot, Hemo",0.4798,0.4907,0.5248,0.5072,0.5059
2,1,mRMR,5,XGBoost,"Bp, Ba, Sg, Pot, Hemo",0.5505,0.5556,0.5941,0.5742,0.5326
3,1,DODA,5,Logistic Regression,"Bp, Sg, Hemo, Pot, Sc",0.5051,0.5146,0.5248,0.5196,0.5076
4,1,DODA,5,Random Forest,"Bp, Sg, Hemo, Pot, Sc",0.5354,0.5455,0.5347,0.5400,0.5405
...,...,...,...,...,...,...,...,...,...,...
115,5,mRMR,20,Random Forest,"Bp, Su, Pcv, Bu, Ba, Pc, Ane, Rbcc, Appet, Htn...",0.5228,0.5310,0.5941,0.5607,0.5179
116,5,mRMR,20,XGBoost,"Bp, Su, Pcv, Bu, Ba, Pc, Ane, Rbcc, Appet, Htn...",0.5127,0.5225,0.5743,0.5472,0.4830
117,5,DODA,20,Logistic Regression,"Bp, Bu, Pcv, Su, Sc, Htn, Ane, Sg, Pc, Ba, Rbc...",0.5178,0.5263,0.5941,0.5581,0.5259
118,5,DODA,20,Random Forest,"Bp, Bu, Pcv, Su, Sc, Htn, Ane, Sg, Pc, Ba, Rbc...",0.5076,0.5175,0.5842,0.5488,0.4818
119,5,DODA,20,XGBoost,"Bp, Bu, Pcv, Su, Sc, Htn, Ane, Sg, Pc, Ba, Rbc...",0.4975,0.5091,0.5545,0.5308,0.4968

In [26]:
# =============================================================================
# STEP 23: 5-FOLD CV PERFORMANCE SUMMARY
# =============================================================================
cv5_summary_df = (
    cv5_results_df.groupby(["Method", "Top_K", "Model"])
    [["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]]
    .agg(["mean", "std"])
    .reset_index()
)
cv5_summary_df.columns = [
    "Method", "Top_K", "Model", "Accuracy_Mean", "Accuracy_STD",
    "Precision_Mean", "Precision_STD", "Recall_Mean", "Recall_STD",
    "F1_Mean", "F1_STD", "ROC_AUC_Mean", "ROC_AUC_STD"
]
display(cv5_summary_df.round(4))

cv5_dir = Path("../../../results/kidney_disease/cv")
cv5_dir.mkdir(parents=True, exist_ok=True)
cv5_results_df.to_csv(cv5_dir / "mrmr_doda_5fold_results.csv", index=False)
cv5_summary_df.to_csv(cv5_dir / "mrmr_doda_5fold_summary.csv", index=False)

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,DODA,5,Logistic Regression,0.5182,0.0261,0.5272,0.0213,0.5859,0.0599,0.5542,0.0353,0.5141,0.0208
1,DODA,5,Random Forest,0.5121,0.0245,0.5257,0.0244,0.5307,0.0265,0.5274,0.0142,0.4961,0.0340
2,DODA,5,XGBoost,0.5151,0.0342,0.5280,0.0332,0.5346,0.0524,0.5303,0.0361,0.5107,0.0547
3,DODA,10,Logistic Regression,0.5304,0.0121,0.5392,0.0084,0.5800,0.0344,0.5586,0.0201,0.5231,0.0192
4,DODA,10,Random Forest,0.5009,0.0486,0.5168,0.0523,0.5306,0.0319,0.5223,0.0315,0.5048,0.0515
5,DODA,10,XGBoost,0.5111,0.0396,0.5229,0.0362,0.5464,0.0362,0.5343,0.0354,0.5032,0.0478
6,DODA,15,Logistic Regression,0.5243,0.0092,0.5343,0.0069,0.5681,0.0130,0.5507,0.0094,0.5239,0.0176
7,DODA,15,Random Forest,0.5162,0.0285,0.5279,0.0264,0.5484,0.0366,0.5376,0.0271,0.5142,0.0407
8,DODA,15,XGBoost,0.5020,0.0597,0.5136,0.0540,0.5268,0.0757,0.5196,0.0631,0.5112,0.0646
9,DODA,20,Logistic Regression,0.5202,0.0093,0.5302,0.0080,0.5740,0.0284,0.5509,0.0137,0.5250,0.0177
10,DODA,20,Random Forest,0.5242,0.0331,0.5344,0.0283,0.5662,0.0506,0.5493,0.0354,0.5237,0.0346
11,DODA,20,XGBoost,0.5232,0.0366,0.5337,0.0316,0.5542,0.0601,0.5431,0.0436,0.5336,0.0424
12,mRMR,5,Logistic Regression,0.5051,0.0220,0.5153,0.0178,0.5741,0.0547,0.5426,0.0335,0.5199,0.0280
13,mRMR,5,Random Forest,0.5091,0.0188,0.5215,0.0200,0.5404,0.0195,0.5305,0.0137,0.5036,0.0103
14,mRMR,5,XGBoost,0.5172,0.0224,0.5284,0.0204,0.5583,0.0504,0.5420,0.0271,0.4943,0.0286
15,mRMR,10,Logistic Regression,0.5213,0.0140,0.5308,0.0129,0.5780,0.0276,0.5532,0.0176,0.5222,0.0213
16,mRMR,10,Random Forest,0.4919,0.0396,0.5041,0.0353,0.5110,0.0601,0.5071,0.0455,0.4980,0.0523
17,mRMR,10,XGBoost,0.5060,0.0439,0.5178,0.0392,0.5228,0.0604,0.5200,0.0484,0.5032,0.0436
18,mRMR,15,Logistic Regression,0.5172,0.0225,0.5278,0.0206,0.5641,0.0302,0.5451,0.0223,0.5221,0.0144
19,mRMR,15,Random Forest,0.4939,0.0429,0.5066,0.0385,0.5209,0.0562,0.5131,0.0448,0.5019,0.0484
20,mRMR,15,XGBoost,0.5061,0.0359,0.5190,0.0324,0.5247,0.0366,0.5216,0.0318,0.5100,0.0461
21,mRMR,20,Logistic Regression,0.5243,0.0153,0.5335,0.0128,0.5760,0.0438,0.5535,0.0256,0.5239,0.0161
22,mRMR,20,Random Forest,0.5050,0.0268,0.5164,0.0246,0.5444,0.0498,0.5296,0.0347,0.5143,0.0301
23,mRMR,20,XGBoost,0.5273,0.0500,0.5387,0.0455,0.5583,0.0492,0.5479,0.0451,0.5240,0.0532

# 3.2 Robustness: 5×5 Repeated Stratified Cross-Validation

The fixed split provides a reproducible initial comparison.

For robustness, feature selection is **recomputed inside every training fold**. This prevents information from the validation fold from influencing mRMR or DODA.

There are:

- 5 folds
- 5 repeats
- 25 train/validation runs
- 4 Top-K budgets
- 2 feature-selection methods
- 3 downstream models

This produces 600 model-evaluation rows.

In [27]:
from mrmr import mrmr_classif

# =============================================================================
# STEP 24: REPEATED CV CONFIGURATION
# =============================================================================

from sklearn.model_selection import RepeatedStratifiedKFold

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)

print(f"Top-K values: {TOP_K_VALUES}")
print(f"CV runs: {N_SPLITS * N_REPEATS}")

Top-K values: [5, 10, 15, 20]
CV runs: 25

In [28]:
# =============================================================================
# STEP 25: 5×5 REPEATED CV — mRMR vs DODA
# =============================================================================

cv_results = []

for run_id, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    X_train_fold = X.iloc[train_idx].copy()
    X_val_fold = X.iloc[val_idx].copy()

    y_train_fold = y.iloc[train_idx].copy()
    y_val_fold = y.iloc[val_idx].copy()

    print(f"Run {run_id:02d}/{N_SPLITS * N_REPEATS}")

    fold_scaler = StandardScaler()

    X_train_fold_scaled = pd.DataFrame(
        fold_scaler.fit_transform(X_train_fold),
        columns=X_train_fold.columns,
        index=X_train_fold.index
    )

    X_val_fold_scaled = pd.DataFrame(
        fold_scaler.transform(X_val_fold),
        columns=X_val_fold.columns,
        index=X_val_fold.index
    )

    X_mrmr_fold = X_train_fold_scaled.reset_index(drop=True)
    y_mrmr_fold = y_train_fold.reset_index(drop=True)

    mrmr_fold_ranked = mrmr_classif(
        X=X_mrmr_fold,
        y=y_mrmr_fold,
        K=X_mrmr_fold.shape[1]
    )

    for top_k in TOP_K_VALUES:

        mrmr_features = mrmr_fold_ranked[:top_k]

        fold_doda = DODASelector(
            operators=[MRMRAdapter()],
            provider=JSONProvider(str(WEIGHTS_PATH)),
            fusion=RankFusion(),
            top_k=top_k
        )

        fold_doda.fit(
            X_train_fold_scaled,
            y_train_fold
        )

        doda_features = list(
            fold_doda.get_selected_features()
        )

        feature_sets = {
            "mRMR": mrmr_features,
            "DODA": doda_features
        }

        for method, selected_features in feature_sets.items():

            Xtr_selected = X_train_fold[selected_features]
            Xval_selected = X_val_fold[selected_features]

            for model_name, model_template in models.items():

                model = model_template.__class__(
                    **model_template.get_params()
                )

                Xtr = Xtr_selected
                Xval = Xval_selected

                if model_name == "Logistic Regression":
                    scaler = StandardScaler()
                    Xtr = scaler.fit_transform(Xtr)
                    Xval = scaler.transform(Xval)

                model.fit(Xtr, y_train_fold)

                y_pred = model.predict(Xval)
                y_prob = model.predict_proba(Xval)[:, 1]

                cv_results.append({
                    "Run": run_id,
                    "Method": method,
                    "Top_K": top_k,
                    "Model": model_name,
                    "Selected_Features": ", ".join(selected_features),
                    "Accuracy": accuracy_score(y_val_fold, y_pred),
                    "Precision": precision_score(y_val_fold, y_pred, zero_division=0),
                    "Recall": recall_score(y_val_fold, y_pred, zero_division=0),
                    "F1": f1_score(y_val_fold, y_pred, zero_division=0),
                    "ROC_AUC": roc_auc_score(y_val_fold, y_prob)
                })

cv_results_df = pd.DataFrame(cv_results)

expected_rows = N_SPLITS * N_REPEATS * len(TOP_K_VALUES) * 2 * len(models)

print(f"Expected repeated-CV rows: {expected_rows}")
print(f"Actual repeated-CV rows:   {len(cv_results_df)}")

assert len(cv_results_df) == expected_rows

display(cv_results_df.round(4))

Run 01/25

100%|██████████| 24/24 [00:06<00:00,  3.49it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA01EB0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.59it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 5 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA96A50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.56it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 10 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F930350>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 15 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc', 'Age', 'Htn', 'Sod', 'Al', 'Pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA3F460>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.62it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Hemo': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Su': 0.75, 'Rbcc': 0.7083333333333334, 'Age': 0.6666666666666666, 'Bgr': 0.625, 'Sc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Appet': 0.4583333333333333, 'Rbc': 0.4166666666666667, 'Htn': 0.375, 'Ane': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Cad': 0.25, 'Pe': 0.20833333333333334, 'Al': 0.16666666666666666, 'Pcc': 0.125, 'Dm': 0.08333333333333333, 'Bu': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Hemo': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Age': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Rbc': np.float64(0.4166666666666667), 'Htn': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bu': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Hemo': 0.75, 'Wbcc': 0.4, 'Su': 0.55, 'Rbcc': 0.55, 'Age': 0.55, 'Bgr': 0.7, 'Sc': 1.0, 'Sod': 0.65, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Htn': 0.85, 'Ane': 0.7, 'Pcv': 0.7, 'Cad': 0.45, 'Pe': 0.65, 'Al': 1.0, 'Pcc': 0.4, 'Dm': 0.8, 'Bu': 0.9}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Hemo': 0.03076923076923077, 'Wbcc': 0.029236022193768675, 'Su': 0.029631255487269532, 'Rbcc': 0.029411764705882353, 'Age': 0.02919863597612958, 'Bgr': 0.029437229437229435, 'Sc': 0.03047794966520434, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Appet': 0.027598020555767037, 'Rbc': 0.02803921568627451, 'Htn': 0.029030910609857977, 'Ane': 0.02813852813852814, 'Pcv': 0.027972027972027972, 'Cad': 0.02694394213381555, 'Pe': 0.027425373134328357, 'Al': 0.0287391216352965, 'Pcc': 0.026279628993473032, 'Dm': 0.027673192771084338, 'Bu': 0.02803379416282642}
Top 20 Features Selected: ['Bp', 'Sg', 'Hemo', 'Pot', 'Sc', 'Ba', 'Su', 'Bgr', 'Rbcc', 'Wbcc', 'Age', 'Htn', 'Sod', 'Al', 'Pc', 'Ane', 'Rbc', 'Bu', 'Pcv', 'Dm']
Run 02/25

100%|██████████| 24/24 [00:06<00:00,  3.66it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F9F2510>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.05it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 5 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA8A2D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.38it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 10 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA88710>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 15 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc', 'Htn', 'Ane', 'Wbcc', 'Pc', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F965370>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Pe': 0.8333333333333334, 'Rbcc': 0.7916666666666666, 'Sg': 0.75, 'Al': 0.7083333333333334, 'Wbcc': 0.6666666666666666, 'Bu': 0.625, 'Sc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Appet': 0.5, 'Ane': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pcc': 0.375, 'Su': 0.3333333333333333, 'Htn': 0.2916666666666667, 'Cad': 0.25, 'Hemo': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Pe': np.float64(0.8333333333333334), 'Rbcc': np.float64(0.7916666666666666), 'Sg': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Wbcc': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Htn': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pcv': 0.7, 'Pe': 0.65, 'Rbcc': 0.55, 'Sg': 0.85, 'Al': 1.0, 'Wbcc': 0.4, 'Bu': 0.9, 'Sc': 1.0, 'Pc': 0.5, 'Appet': 0.4, 'Ane': 0.7, 'Sod': 0.65, 'Pcc': 0.4, 'Su': 0.55, 'Htn': 0.85, 'Cad': 0.45, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Pe': 0.030309988518943745, 'Rbcc': 0.029857397504456328, 'Sg': 0.030798389007344232, 'Al': 0.031099324975891997, 'Wbcc': 0.028577260665441927, 'Bu': 0.0304147465437788, 'Sc': 0.03047794966520434, 'Pc': 0.028381642512077296, 'Appet': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Sod': 0.028258706467661692, 'Pcc': 0.027242401779095628, 'Su': 0.027692895339954164, 'Htn': 0.028693528693528692, 'Cad': 0.02694394213381555, 'Hemo': 0.027884615384615386, 'Rbc': 0.027051561365286855, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Bgr': 0.027056277056277056}
Top 20 Features Selected: ['Bp', 'Al', 'Pot', 'Sg', 'Pcv', 'Sc', 'Bu', 'Pe', 'Ba', 'Rbcc', 'Htn', 'Ane', 'Wbcc', 'Pc', 'Sod', 'Hemo', 'Appet', 'Su', 'Dm', 'Pcc']
Run 03/25

100%|██████████| 24/24 [00:06<00:00,  3.64it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAAED0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.65it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA8B350>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.62it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F965D90>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.49it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane', 'Rbcc', 'Pe', 'Sod', 'Appet', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAB290>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.62it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pcv': 0.9583333333333334, 'Bgr': 0.9166666666666666, 'Ba': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Bu': 0.5416666666666666, 'Sc': 0.5, 'Al': 0.4583333333333333, 'Cad': 0.4166666666666667, 'Dm': 0.375, 'Age': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Sg': 0.25, 'Htn': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Rbc': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pcv': np.float64(0.9583333333333334), 'Bgr': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Bu': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Cad': np.float64(0.4166666666666667), 'Dm': np.float64(0.375), 'Age': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Sg': np.float64(0.25), 'Htn': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Su': 0.55, 'Pot': 0.65, 'Rbcc': 0.55, 'Appet': 0.4, 'Ane': 0.7, 'Pe': 0.65, 'Sod': 0.65, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Cad': 0.45, 'Dm': 0.8, 'Age': 0.55, 'Wbcc': 0.4, 'Sg': 0.85, 'Htn': 0.85, 'Pc': 0.5, 'Rbc': 0.55, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pcv': 0.03128054740957967, 'Bgr': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Ane': 0.02964426877470356, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Bu': 0.030017921146953404, 'Sc': 0.03009207275993712, 'Al': 0.029906956136464335, 'Cad': 0.02761904761904762, 'Dm': 0.028782894736842105, 'Age': 0.027692895339954164, 'Wbcc': 0.02690501986276634, 'Sg': 0.028531243721117136, 'Htn': 0.028373015873015873, 'Pc': 0.026838432635534086, 'Rbc': 0.02690100430416069, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Pcv', 'Bgr', 'Sc', 'Su', 'Pot', 'Bu', 'Al', 'Ba', 'Ane', 'Rbcc', 'Pe', 'Sod', 'Appet', 'Dm', 'Sg', 'Htn', 'Age', 'Cad', 'Hemo']
Run 04/25

100%|██████████| 24/24 [00:06<00:00,  3.58it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAB4D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7F90B5F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.67it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAAED0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc', 'Pcv', 'Sod', 'Sg', 'Ane', 'Rbc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA33470>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.64it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Su': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Bgr': 0.75, 'Rbcc': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Pcv': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Al': 0.375, 'Sg': 0.3333333333333333, 'Age': 0.2916666666666667, 'Cad': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Htn': 0.125, 'Hemo': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Pcv': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Al': np.float64(0.375), 'Sg': np.float64(0.3333333333333333), 'Age': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Htn': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Pe': 0.65, 'Su': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Age': 0.55, 'Cad': 0.45, 'Dm': 0.8, 'Pc': 0.5, 'Htn': 0.85, 'Hemo': 0.75, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Su': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Bgr': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Pcv': 0.029236022193768675, 'Appet': 0.02797339593114241, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Al': 0.029551337359792925, 'Sg': 0.02886002886002886, 'Age': 0.027526395173453996, 'Cad': 0.02694394213381555, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Htn': 0.028068137824235385, 'Hemo': 0.027432808155699723, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Sc', 'Pe', 'Su', 'Bgr', 'Ba', 'Al', 'Rbcc', 'Pcv', 'Sod', 'Sg', 'Ane', 'Rbc', 'Dm', 'Htn', 'Appet', 'Age', 'Hemo']
Run 05/25

100%|██████████| 24/24 [00:06<00:00,  3.63it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA9190>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B22EA1190>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.05it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03111490>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba', 'Rbcc', 'Al', 'Bgr', 'Pot', 'Appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAB410>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Bu': 0.875, 'Ba': 0.8333333333333334, 'Pc': 0.7916666666666666, 'Ane': 0.75, 'Rbcc': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Htn': 0.625, 'Sc': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Pot': 0.5, 'Bgr': 0.4583333333333333, 'Pcc': 0.4166666666666667, 'Sod': 0.375, 'Al': 0.3333333333333333, 'Pe': 0.2916666666666667, 'Rbc': 0.25, 'Hemo': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Dm': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Ba': np.float64(0.8333333333333334), 'Pc': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Htn': np.float64(0.625), 'Sc': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Pot': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pcc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Al': np.float64(0.3333333333333333), 'Pe': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Hemo': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Pc': 0.5, 'Ane': 0.7, 'Rbcc': 0.55, 'Appet': 0.4, 'Htn': 0.85, 'Sc': 1.0, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Pcc': 0.4, 'Sod': 0.65, 'Al': 1.0, 'Pe': 0.65, 'Rbc': 0.55, 'Hemo': 0.75, 'Wbcc': 0.4, 'Dm': 0.8, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Bu': 0.031754032258064516, 'Ba': 0.02946912242686891, 'Pc': 0.02964426877470356, 'Ane': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Appet': 0.028577260665441927, 'Htn': 0.030158730158730156, 'Sc': 0.03047794966520434, 'Sg': 0.02976190476190476, 'Pot': 0.02862400327131466, 'Bgr': 0.028665028665028666, 'Pcc': 0.027417840375586856, 'Sod': 0.028083267871170464, 'Al': 0.02938045560996381, 'Pe': 0.027745885954841176, 'Rbc': 0.027364110201042444, 'Hemo': 0.027884615384615386, 'Wbcc': 0.0264301860545992, 'Dm': 0.027820121951219513, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Bu', 'Pcv', 'Su', 'Sc', 'Htn', 'Ane', 'Sg', 'Pc', 'Ba', 'Rbcc', 'Al', 'Bgr', 'Pot', 'Appet', 'Sod', 'Hemo', 'Dm', 'Pe', 'Pcc']
Run 06/25

100%|██████████| 24/24 [00:07<00:00,  3.42it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA32510>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.56it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Sod': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Sg': np.float64(0.7916666666666666), 'Pe': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Bu': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Appet': np.float64(0.5833333333333334), 'Pcc': np.float64(0.5416666666666666), 'Su': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Hemo': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Sc': np.float64(0.16666666666666666), 'Ane': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Dm': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Sod': 0.65, 'Pcv': 0.7, 'Sg': 0.85, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Appet': 0.4, 'Pcc': 0.4, 'Su': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Age': 0.55, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Cad': 0.45, 'Sc': 1.0, 'Ane': 0.7, 'Htn': 0.85, 'Dm': 0.8}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Sod': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Sg': 0.031024531024531024, 'Pe': 0.029850746268656716, 'Rbcc': 0.029411764705882353, 'Bu': 0.030621785881252923, 'Bgr': 0.029437229437229435, 'Appet': 0.028169014084507043, 'Pcc': 0.02797339593114241, 'Su': 0.028404512489927477, 'Al': 0.029906956136464335, 'Pc': 0.02782608695652174, 'Age': 0.02786377708978328, 'Wbcc': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Hemo': 0.02804284323271665, 'Cad': 0.026785714285714288, 'Sc': 0.0287391216352965, 'Ane': 0.027346637102734665, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904}
Top 5 Features Selected: ['Bp', 'Sg', 'Pot', 'Bu', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA30DD0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Sod': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Sg': np.float64(0.7916666666666666), 'Pe': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Bu': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Appet': np.float64(0.5833333333333334), 'Pcc': np.float64(0.5416666666666666), 'Su': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Hemo': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Sc': np.float64(0.16666666666666666), 'Ane': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Dm': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Sod': 0.65, 'Pcv': 0.7, 'Sg': 0.85, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Appet': 0.4, 'Pcc': 0.4, 'Su': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Age': 0.55, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Cad': 0.45, 'Sc': 1.0, 'Ane': 0.7, 'Htn': 0.85, 'Dm': 0.8}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Sod': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Sg': 0.031024531024531024, 'Pe': 0.029850746268656716, 'Rbcc': 0.029411764705882353, 'Bu': 0.030621785881252923, 'Bgr': 0.029437229437229435, 'Appet': 0.028169014084507043, 'Pcc': 0.02797339593114241, 'Su': 0.028404512489927477, 'Al': 0.029906956136464335, 'Pc': 0.02782608695652174, 'Age': 0.02786377708978328, 'Wbcc': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Hemo': 0.02804284323271665, 'Cad': 0.026785714285714288, 'Sc': 0.0287391216352965, 'Ane': 0.027346637102734665, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904}
Top 10 Features Selected: ['Bp', 'Sg', 'Pot', 'Bu', 'Sod', 'Pcv', 'Ba', 'Al', 'Pe', 'Bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031103B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Sod': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Sg': np.float64(0.7916666666666666), 'Pe': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Bu': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Appet': np.float64(0.5833333333333334), 'Pcc': np.float64(0.5416666666666666), 'Su': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Hemo': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Sc': np.float64(0.16666666666666666), 'Ane': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Dm': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Sod': 0.65, 'Pcv': 0.7, 'Sg': 0.85, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Appet': 0.4, 'Pcc': 0.4, 'Su': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Age': 0.55, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Cad': 0.45, 'Sc': 1.0, 'Ane': 0.7, 'Htn': 0.85, 'Dm': 0.8}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Sod': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Sg': 0.031024531024531024, 'Pe': 0.029850746268656716, 'Rbcc': 0.029411764705882353, 'Bu': 0.030621785881252923, 'Bgr': 0.029437229437229435, 'Appet': 0.028169014084507043, 'Pcc': 0.02797339593114241, 'Su': 0.028404512489927477, 'Al': 0.029906956136464335, 'Pc': 0.02782608695652174, 'Age': 0.02786377708978328, 'Wbcc': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Hemo': 0.02804284323271665, 'Cad': 0.026785714285714288, 'Sc': 0.0287391216352965, 'Ane': 0.027346637102734665, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904}
Top 15 Features Selected: ['Bp', 'Sg', 'Pot', 'Bu', 'Sod', 'Pcv', 'Ba', 'Al', 'Pe', 'Bgr', 'Rbcc', 'Sc', 'Su', 'Appet', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA82F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.51it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Sod': 0.875, 'Pcv': 0.8333333333333334, 'Sg': 0.7916666666666666, 'Pe': 0.75, 'Rbcc': 0.7083333333333334, 'Bu': 0.6666666666666666, 'Bgr': 0.625, 'Appet': 0.5833333333333334, 'Pcc': 0.5416666666666666, 'Su': 0.5, 'Al': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Age': 0.375, 'Wbcc': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Hemo': 0.25, 'Cad': 0.20833333333333334, 'Sc': 0.16666666666666666, 'Ane': 0.125, 'Htn': 0.08333333333333333, 'Dm': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Sod': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Sg': np.float64(0.7916666666666666), 'Pe': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Bu': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Appet': np.float64(0.5833333333333334), 'Pcc': np.float64(0.5416666666666666), 'Su': np.float64(0.5), 'Al': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Hemo': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Sc': np.float64(0.16666666666666666), 'Ane': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Dm': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Sod': 0.65, 'Pcv': 0.7, 'Sg': 0.85, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Bgr': 0.7, 'Appet': 0.4, 'Pcc': 0.4, 'Su': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Age': 0.55, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Cad': 0.45, 'Sc': 1.0, 'Ane': 0.7, 'Htn': 0.85, 'Dm': 0.8}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Sod': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Sg': 0.031024531024531024, 'Pe': 0.029850746268656716, 'Rbcc': 0.029411764705882353, 'Bu': 0.030621785881252923, 'Bgr': 0.029437229437229435, 'Appet': 0.028169014084507043, 'Pcc': 0.02797339593114241, 'Su': 0.028404512489927477, 'Al': 0.029906956136464335, 'Pc': 0.02782608695652174, 'Age': 0.02786377708978328, 'Wbcc': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Hemo': 0.02804284323271665, 'Cad': 0.026785714285714288, 'Sc': 0.0287391216352965, 'Ane': 0.027346637102734665, 'Htn': 0.02792120864410021, 'Dm': 0.027529761904761904}
Top 20 Features Selected: ['Bp', 'Sg', 'Pot', 'Bu', 'Sod', 'Pcv', 'Ba', 'Al', 'Pe', 'Bgr', 'Rbcc', 'Sc', 'Su', 'Appet', 'Hemo', 'Pcc', 'Htn', 'Age', 'Pc', 'Dm']
Run 07/25

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA30FB0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Pcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sg': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Bgr': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Bu': 0.9, 'Su': 0.55, 'Pot': 0.65, 'Pcv': 0.7, 'Sc': 1.0, 'Ane': 0.7, 'Rbcc': 0.55, 'Pcc': 0.4, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Cad': 0.45, 'Bgr': 0.7, 'Al': 1.0, 'Wbcc': 0.4, 'Age': 0.55, 'Dm': 0.8, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Bu': 0.031754032258064516, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Sc': 0.031099324975891997, 'Ane': 0.02964426877470356, 'Rbcc': 0.028991596638655463, 'Pcc': 0.028169014084507043, 'Sod': 0.028814262023217248, 'Appet': 0.027783137179239824, 'Sg': 0.029386529386529386, 'Hemo': 0.02871794871794872, 'Pc': 0.027650648360030512, 'Htn': 0.02886002886002886, 'Cad': 0.027106227106227107, 'Bgr': 0.027809742999616416, 'Al': 0.02889344262295082, 'Wbcc': 0.0264301860545992, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Rbc': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Bu', 'Sc', 'Pe', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA30530>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Pcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sg': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Bgr': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Bu': 0.9, 'Su': 0.55, 'Pot': 0.65, 'Pcv': 0.7, 'Sc': 1.0, 'Ane': 0.7, 'Rbcc': 0.55, 'Pcc': 0.4, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Cad': 0.45, 'Bgr': 0.7, 'Al': 1.0, 'Wbcc': 0.4, 'Age': 0.55, 'Dm': 0.8, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Bu': 0.031754032258064516, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Sc': 0.031099324975891997, 'Ane': 0.02964426877470356, 'Rbcc': 0.028991596638655463, 'Pcc': 0.028169014084507043, 'Sod': 0.028814262023217248, 'Appet': 0.027783137179239824, 'Sg': 0.029386529386529386, 'Hemo': 0.02871794871794872, 'Pc': 0.027650648360030512, 'Htn': 0.02886002886002886, 'Cad': 0.027106227106227107, 'Bgr': 0.027809742999616416, 'Al': 0.02889344262295082, 'Wbcc': 0.0264301860545992, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Rbc': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Bu', 'Sc', 'Pe', 'Su', 'Pot', 'Pcv', 'Ba', 'Ane', 'Sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113D10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Pcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sg': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Bgr': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Bu': 0.9, 'Su': 0.55, 'Pot': 0.65, 'Pcv': 0.7, 'Sc': 1.0, 'Ane': 0.7, 'Rbcc': 0.55, 'Pcc': 0.4, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Cad': 0.45, 'Bgr': 0.7, 'Al': 1.0, 'Wbcc': 0.4, 'Age': 0.55, 'Dm': 0.8, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Bu': 0.031754032258064516, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Sc': 0.031099324975891997, 'Ane': 0.02964426877470356, 'Rbcc': 0.028991596638655463, 'Pcc': 0.028169014084507043, 'Sod': 0.028814262023217248, 'Appet': 0.027783137179239824, 'Sg': 0.029386529386529386, 'Hemo': 0.02871794871794872, 'Pc': 0.027650648360030512, 'Htn': 0.02886002886002886, 'Cad': 0.027106227106227107, 'Bgr': 0.027809742999616416, 'Al': 0.02889344262295082, 'Wbcc': 0.0264301860545992, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Rbc': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Bu', 'Sc', 'Pe', 'Su', 'Pot', 'Pcv', 'Ba', 'Ane', 'Sg', 'Rbcc', 'Al', 'Htn', 'Sod', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAAED0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Bu': 0.875, 'Su': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Sc': 0.7083333333333334, 'Ane': 0.6666666666666666, 'Rbcc': 0.625, 'Pcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Appet': 0.5, 'Sg': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Pc': 0.375, 'Htn': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Bgr': 0.25, 'Al': 0.20833333333333334, 'Wbcc': 0.16666666666666666, 'Age': 0.125, 'Dm': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Ane': np.float64(0.6666666666666666), 'Rbcc': np.float64(0.625), 'Pcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sg': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Bgr': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Wbcc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Bu': 0.9, 'Su': 0.55, 'Pot': 0.65, 'Pcv': 0.7, 'Sc': 1.0, 'Ane': 0.7, 'Rbcc': 0.55, 'Pcc': 0.4, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Cad': 0.45, 'Bgr': 0.7, 'Al': 1.0, 'Wbcc': 0.4, 'Age': 0.55, 'Dm': 0.8, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Bu': 0.031754032258064516, 'Su': 0.030090497737556562, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Sc': 0.031099324975891997, 'Ane': 0.02964426877470356, 'Rbcc': 0.028991596638655463, 'Pcc': 0.028169014084507043, 'Sod': 0.028814262023217248, 'Appet': 0.027783137179239824, 'Sg': 0.029386529386529386, 'Hemo': 0.02871794871794872, 'Pc': 0.027650648360030512, 'Htn': 0.02886002886002886, 'Cad': 0.027106227106227107, 'Bgr': 0.027809742999616416, 'Al': 0.02889344262295082, 'Wbcc': 0.0264301860545992, 'Age': 0.02690100430416069, 'Dm': 0.027673192771084338, 'Rbc': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Bu', 'Sc', 'Pe', 'Su', 'Pot', 'Pcv', 'Ba', 'Ane', 'Sg', 'Rbcc', 'Al', 'Htn', 'Sod', 'Hemo', 'Pcc', 'Bgr', 'Appet', 'Dm', 'Pc']
Run 08/25

100%|██████████| 24/24 [00:06<00:00,  3.43it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA81D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pe': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sg': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Pc': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Htn': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Al': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pe': 0.65, 'Pot': 0.65, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Appet': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Ane': 0.7, 'Bgr': 0.7, 'Sg': 0.85, 'Age': 0.55, 'Sc': 1.0, 'Hemo': 0.75, 'Dm': 0.8, 'Cad': 0.45, 'Pc': 0.5, 'Sod': 0.65, 'Htn': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pe': 0.030798389007344232, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Su': 0.02919863597612958, 'Bu': 0.0304147465437788, 'Ane': 0.029236022193768675, 'Bgr': 0.02904040404040404, 'Sg': 0.029571646010002173, 'Age': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Hemo': 0.02854251012145749, 'Dm': 0.028612012987012988, 'Cad': 0.027106227106227107, 'Pc': 0.02715098147128967, 'Sod': 0.027425373134328357, 'Htn': 0.02821869488536155, 'Pcc': 0.026279628993473032, 'Al': 0.02844163539403516, 'Rbc': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Pe', 'Pot', 'Pcv', 'Bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8410>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pe': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sg': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Pc': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Htn': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Al': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pe': 0.65, 'Pot': 0.65, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Appet': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Ane': 0.7, 'Bgr': 0.7, 'Sg': 0.85, 'Age': 0.55, 'Sc': 1.0, 'Hemo': 0.75, 'Dm': 0.8, 'Cad': 0.45, 'Pc': 0.5, 'Sod': 0.65, 'Htn': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pe': 0.030798389007344232, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Su': 0.02919863597612958, 'Bu': 0.0304147465437788, 'Ane': 0.029236022193768675, 'Bgr': 0.02904040404040404, 'Sg': 0.029571646010002173, 'Age': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Hemo': 0.02854251012145749, 'Dm': 0.028612012987012988, 'Cad': 0.027106227106227107, 'Pc': 0.02715098147128967, 'Sod': 0.027425373134328357, 'Htn': 0.02821869488536155, 'Pcc': 0.026279628993473032, 'Al': 0.02844163539403516, 'Rbc': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Pe', 'Pot', 'Pcv', 'Bu', 'Ba', 'Sc', 'Rbcc', 'Sg', 'Wbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345E210>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pe': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sg': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Pc': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Htn': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Al': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pe': 0.65, 'Pot': 0.65, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Appet': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Ane': 0.7, 'Bgr': 0.7, 'Sg': 0.85, 'Age': 0.55, 'Sc': 1.0, 'Hemo': 0.75, 'Dm': 0.8, 'Cad': 0.45, 'Pc': 0.5, 'Sod': 0.65, 'Htn': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pe': 0.030798389007344232, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Su': 0.02919863597612958, 'Bu': 0.0304147465437788, 'Ane': 0.029236022193768675, 'Bgr': 0.02904040404040404, 'Sg': 0.029571646010002173, 'Age': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Hemo': 0.02854251012145749, 'Dm': 0.028612012987012988, 'Cad': 0.027106227106227107, 'Pc': 0.02715098147128967, 'Sod': 0.027425373134328357, 'Htn': 0.02821869488536155, 'Pcc': 0.026279628993473032, 'Al': 0.02844163539403516, 'Rbc': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Pe', 'Pot', 'Pcv', 'Bu', 'Ba', 'Sc', 'Rbcc', 'Sg', 'Wbcc', 'Ane', 'Su', 'Bgr', 'Appet', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8BF0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.56it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pe': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Wbcc': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Su': 0.6666666666666666, 'Bu': 0.625, 'Ane': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sg': 0.5, 'Age': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Hemo': 0.375, 'Dm': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Pc': 0.25, 'Sod': 0.20833333333333334, 'Htn': 0.16666666666666666, 'Pcc': 0.125, 'Al': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pe': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Wbcc': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Bu': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sg': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Pc': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Htn': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Al': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pe': 0.65, 'Pot': 0.65, 'Pcv': 0.7, 'Wbcc': 0.4, 'Rbcc': 0.55, 'Appet': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Ane': 0.7, 'Bgr': 0.7, 'Sg': 0.85, 'Age': 0.55, 'Sc': 1.0, 'Hemo': 0.75, 'Dm': 0.8, 'Cad': 0.45, 'Pc': 0.5, 'Sod': 0.65, 'Htn': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pe': 0.030798389007344232, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Wbcc': 0.029236022193768675, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Su': 0.02919863597612958, 'Bu': 0.0304147465437788, 'Ane': 0.029236022193768675, 'Bgr': 0.02904040404040404, 'Sg': 0.029571646010002173, 'Age': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Hemo': 0.02854251012145749, 'Dm': 0.028612012987012988, 'Cad': 0.027106227106227107, 'Pc': 0.02715098147128967, 'Sod': 0.027425373134328357, 'Htn': 0.02821869488536155, 'Pcc': 0.026279628993473032, 'Al': 0.02844163539403516, 'Rbc': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Pe', 'Pot', 'Pcv', 'Bu', 'Ba', 'Sc', 'Rbcc', 'Sg', 'Wbcc', 'Ane', 'Su', 'Bgr', 'Appet', 'Dm', 'Hemo', 'Al', 'Age', 'Htn', 'Sod']
Run 09/25

100%|██████████| 24/24 [00:06<00:00,  3.45it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8C50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.56it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Wbcc': np.float64(0.9166666666666666), 'Sg': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Hemo': np.float64(0.625), 'Pc': np.float64(0.5833333333333334), 'Pcv': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Htn': np.float64(0.4583333333333333), 'Appet': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Dm': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Bu': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Wbcc': 0.4, 'Sg': 0.85, 'Bgr': 0.7, 'Pot': 0.65, 'Ane': 0.7, 'Al': 1.0, 'Rbcc': 0.55, 'Hemo': 0.75, 'Pc': 0.5, 'Pcv': 0.7, 'Sc': 1.0, 'Htn': 0.85, 'Appet': 0.4, 'Rbc': 0.55, 'Su': 0.55, 'Dm': 0.8, 'Age': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Cad': 0.45, 'Bu': 0.9, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Wbcc': 0.029957522915269395, 'Sg': 0.03149801587301587, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Ane': 0.03007688828584351, 'Al': 0.031099324975891997, 'Rbcc': 0.02919863597612958, 'Hemo': 0.02967032967032967, 'Pc': 0.028577260665441927, 'Pcv': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Htn': 0.029386529386529386, 'Appet': 0.027417840375586856, 'Rbc': 0.02786377708978328, 'Su': 0.027692895339954164, 'Dm': 0.02844551282051282, 'Age': 0.027364110201042444, 'Pe': 0.027425373134328357, 'Sod': 0.027271052146674038, 'Cad': 0.0264808362369338, 'Bu': 0.028177225029148854, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Sg', 'Al', 'Bgr', 'Ba']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA33A10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Wbcc': np.float64(0.9166666666666666), 'Sg': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Hemo': np.float64(0.625), 'Pc': np.float64(0.5833333333333334), 'Pcv': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Htn': np.float64(0.4583333333333333), 'Appet': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Dm': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Bu': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Wbcc': 0.4, 'Sg': 0.85, 'Bgr': 0.7, 'Pot': 0.65, 'Ane': 0.7, 'Al': 1.0, 'Rbcc': 0.55, 'Hemo': 0.75, 'Pc': 0.5, 'Pcv': 0.7, 'Sc': 1.0, 'Htn': 0.85, 'Appet': 0.4, 'Rbc': 0.55, 'Su': 0.55, 'Dm': 0.8, 'Age': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Cad': 0.45, 'Bu': 0.9, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Wbcc': 0.029957522915269395, 'Sg': 0.03149801587301587, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Ane': 0.03007688828584351, 'Al': 0.031099324975891997, 'Rbcc': 0.02919863597612958, 'Hemo': 0.02967032967032967, 'Pc': 0.028577260665441927, 'Pcv': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Htn': 0.029386529386529386, 'Appet': 0.027417840375586856, 'Rbc': 0.02786377708978328, 'Su': 0.027692895339954164, 'Dm': 0.02844551282051282, 'Age': 0.027364110201042444, 'Pe': 0.027425373134328357, 'Sod': 0.027271052146674038, 'Cad': 0.0264808362369338, 'Bu': 0.028177225029148854, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Sg', 'Al', 'Bgr', 'Ba', 'Sc', 'Pot', 'Ane', 'Wbcc', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321E810>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.40it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Wbcc': np.float64(0.9166666666666666), 'Sg': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Hemo': np.float64(0.625), 'Pc': np.float64(0.5833333333333334), 'Pcv': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Htn': np.float64(0.4583333333333333), 'Appet': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Dm': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Bu': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Wbcc': 0.4, 'Sg': 0.85, 'Bgr': 0.7, 'Pot': 0.65, 'Ane': 0.7, 'Al': 1.0, 'Rbcc': 0.55, 'Hemo': 0.75, 'Pc': 0.5, 'Pcv': 0.7, 'Sc': 1.0, 'Htn': 0.85, 'Appet': 0.4, 'Rbc': 0.55, 'Su': 0.55, 'Dm': 0.8, 'Age': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Cad': 0.45, 'Bu': 0.9, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Wbcc': 0.029957522915269395, 'Sg': 0.03149801587301587, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Ane': 0.03007688828584351, 'Al': 0.031099324975891997, 'Rbcc': 0.02919863597612958, 'Hemo': 0.02967032967032967, 'Pc': 0.028577260665441927, 'Pcv': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Htn': 0.029386529386529386, 'Appet': 0.027417840375586856, 'Rbc': 0.02786377708978328, 'Su': 0.027692895339954164, 'Dm': 0.02844551282051282, 'Age': 0.027364110201042444, 'Pe': 0.027425373134328357, 'Sod': 0.027271052146674038, 'Cad': 0.0264808362369338, 'Bu': 0.028177225029148854, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Sg', 'Al', 'Bgr', 'Ba', 'Sc', 'Pot', 'Ane', 'Wbcc', 'Hemo', 'Htn', 'Rbcc', 'Pcv', 'Pc', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA9070>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Wbcc': 0.9166666666666666, 'Sg': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Ane': 0.75, 'Al': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Hemo': 0.625, 'Pc': 0.5833333333333334, 'Pcv': 0.5416666666666666, 'Sc': 0.5, 'Htn': 0.4583333333333333, 'Appet': 0.4166666666666667, 'Rbc': 0.375, 'Su': 0.3333333333333333, 'Dm': 0.2916666666666667, 'Age': 0.25, 'Pe': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Cad': 0.125, 'Bu': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Wbcc': np.float64(0.9166666666666666), 'Sg': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Al': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Hemo': np.float64(0.625), 'Pc': np.float64(0.5833333333333334), 'Pcv': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Htn': np.float64(0.4583333333333333), 'Appet': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Su': np.float64(0.3333333333333333), 'Dm': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Bu': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Wbcc': 0.4, 'Sg': 0.85, 'Bgr': 0.7, 'Pot': 0.65, 'Ane': 0.7, 'Al': 1.0, 'Rbcc': 0.55, 'Hemo': 0.75, 'Pc': 0.5, 'Pcv': 0.7, 'Sc': 1.0, 'Htn': 0.85, 'Appet': 0.4, 'Rbc': 0.55, 'Su': 0.55, 'Dm': 0.8, 'Age': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Cad': 0.45, 'Bu': 0.9, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Wbcc': 0.029957522915269395, 'Sg': 0.03149801587301587, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Ane': 0.03007688828584351, 'Al': 0.031099324975891997, 'Rbcc': 0.02919863597612958, 'Hemo': 0.02967032967032967, 'Pc': 0.028577260665441927, 'Pcv': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Htn': 0.029386529386529386, 'Appet': 0.027417840375586856, 'Rbc': 0.02786377708978328, 'Su': 0.027692895339954164, 'Dm': 0.02844551282051282, 'Age': 0.027364110201042444, 'Pe': 0.027425373134328357, 'Sod': 0.027271052146674038, 'Cad': 0.0264808362369338, 'Bu': 0.028177225029148854, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Sg', 'Al', 'Bgr', 'Ba', 'Sc', 'Pot', 'Ane', 'Wbcc', 'Hemo', 'Htn', 'Rbcc', 'Pcv', 'Pc', 'Dm', 'Bu', 'Rbc', 'Su', 'Pe', 'Appet']
Run 10/25

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA31010>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Sc': np.float64(0.875), 'Cad': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Bgr': np.float64(0.7083333333333334), 'Dm': np.float64(0.6666666666666666), 'Appet': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Al': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Sc': 1.0, 'Cad': 0.45, 'Pot': 0.65, 'Rbcc': 0.55, 'Bgr': 0.7, 'Dm': 0.8, 'Appet': 0.4, 'Sod': 0.65, 'Wbcc': 0.4, 'Pcc': 0.4, 'Ane': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Hemo': 0.75, 'Sg': 0.85, 'Al': 1.0, 'Pe': 0.65, 'Pc': 0.5, 'Age': 0.55, 'Htn': 0.85, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Sc': 0.032018442622950824, 'Cad': 0.02967032967032967, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Bgr': 0.029857397504456328, 'Dm': 0.030117753623188408, 'Appet': 0.028370221327967807, 'Sod': 0.02900988017658188, 'Wbcc': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Bu': 0.02946236559139785, 'Ba': 0.027242401779095628, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Al': 0.029051670471052088, 'Pe': 0.027425373134328357, 'Pc': 0.026838432635534086, 'Age': 0.02690100430416069, 'Htn': 0.02792120864410021, 'Rbc': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112E70>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Sc': np.float64(0.875), 'Cad': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Bgr': np.float64(0.7083333333333334), 'Dm': np.float64(0.6666666666666666), 'Appet': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Al': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Sc': 1.0, 'Cad': 0.45, 'Pot': 0.65, 'Rbcc': 0.55, 'Bgr': 0.7, 'Dm': 0.8, 'Appet': 0.4, 'Sod': 0.65, 'Wbcc': 0.4, 'Pcc': 0.4, 'Ane': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Hemo': 0.75, 'Sg': 0.85, 'Al': 1.0, 'Pe': 0.65, 'Pc': 0.5, 'Age': 0.55, 'Htn': 0.85, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Sc': 0.032018442622950824, 'Cad': 0.02967032967032967, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Bgr': 0.029857397504456328, 'Dm': 0.030117753623188408, 'Appet': 0.028370221327967807, 'Sod': 0.02900988017658188, 'Wbcc': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Bu': 0.02946236559139785, 'Ba': 0.027242401779095628, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Al': 0.029051670471052088, 'Pe': 0.027425373134328357, 'Pc': 0.026838432635534086, 'Age': 0.02690100430416069, 'Htn': 0.02792120864410021, 'Rbc': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Dm', 'Pot', 'Bgr', 'Cad', 'Rbcc', 'Bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8290>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Sc': np.float64(0.875), 'Cad': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Bgr': np.float64(0.7083333333333334), 'Dm': np.float64(0.6666666666666666), 'Appet': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Al': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Sc': 1.0, 'Cad': 0.45, 'Pot': 0.65, 'Rbcc': 0.55, 'Bgr': 0.7, 'Dm': 0.8, 'Appet': 0.4, 'Sod': 0.65, 'Wbcc': 0.4, 'Pcc': 0.4, 'Ane': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Hemo': 0.75, 'Sg': 0.85, 'Al': 1.0, 'Pe': 0.65, 'Pc': 0.5, 'Age': 0.55, 'Htn': 0.85, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Sc': 0.032018442622950824, 'Cad': 0.02967032967032967, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Bgr': 0.029857397504456328, 'Dm': 0.030117753623188408, 'Appet': 0.028370221327967807, 'Sod': 0.02900988017658188, 'Wbcc': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Bu': 0.02946236559139785, 'Ba': 0.027242401779095628, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Al': 0.029051670471052088, 'Pe': 0.027425373134328357, 'Pc': 0.026838432635534086, 'Age': 0.02690100430416069, 'Htn': 0.02792120864410021, 'Rbc': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Dm', 'Pot', 'Bgr', 'Cad', 'Rbcc', 'Bu', 'Al', 'Sod', 'Sg', 'Ane', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA9310>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.49it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Sc': 0.875, 'Cad': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Rbcc': 0.75, 'Bgr': 0.7083333333333334, 'Dm': 0.6666666666666666, 'Appet': 0.625, 'Sod': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Pcc': 0.5, 'Ane': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ba': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Al': 0.25, 'Pe': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Age': 0.125, 'Htn': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Sc': np.float64(0.875), 'Cad': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Bgr': np.float64(0.7083333333333334), 'Dm': np.float64(0.6666666666666666), 'Appet': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Al': np.float64(0.25), 'Pe': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Age': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Sc': 1.0, 'Cad': 0.45, 'Pot': 0.65, 'Rbcc': 0.55, 'Bgr': 0.7, 'Dm': 0.8, 'Appet': 0.4, 'Sod': 0.65, 'Wbcc': 0.4, 'Pcc': 0.4, 'Ane': 0.7, 'Bu': 0.9, 'Ba': 0.4, 'Hemo': 0.75, 'Sg': 0.85, 'Al': 1.0, 'Pe': 0.65, 'Pc': 0.5, 'Age': 0.55, 'Htn': 0.85, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Sc': 0.032018442622950824, 'Cad': 0.02967032967032967, 'Pot': 0.03007688828584351, 'Rbcc': 0.029631255487269532, 'Bgr': 0.029857397504456328, 'Dm': 0.030117753623188408, 'Appet': 0.028370221327967807, 'Sod': 0.02900988017658188, 'Wbcc': 0.02797339593114241, 'Pcc': 0.027783137179239824, 'Ane': 0.028665028665028666, 'Bu': 0.02946236559139785, 'Ba': 0.027242401779095628, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Al': 0.029051670471052088, 'Pe': 0.027425373134328357, 'Pc': 0.026838432635534086, 'Age': 0.02690100430416069, 'Htn': 0.02792120864410021, 'Rbc': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Sc', 'Pcv', 'Su', 'Dm', 'Pot', 'Bgr', 'Cad', 'Rbcc', 'Bu', 'Al', 'Sod', 'Sg', 'Ane', 'Hemo', 'Appet', 'Wbcc', 'Htn', 'Pcc', 'Pe']
Run 11/25

100%|██████████| 24/24 [00:07<00:00,  3.41it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA8B350>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Bu': np.float64(0.8333333333333334), 'Pe': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sc': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Pe': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Sg': 0.85, 'Bgr': 0.7, 'Ane': 0.7, 'Wbcc': 0.4, 'Appet': 0.4, 'Sc': 1.0, 'Age': 0.55, 'Rbc': 0.55, 'Dm': 0.8, 'Pc': 0.5, 'Sod': 0.65, 'Pcc': 0.4, 'Hemo': 0.75, 'Cad': 0.45, 'Htn': 0.85, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Su': 0.030330882352941176, 'Bu': 0.0315136476426799, 'Pe': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sg': 0.03036576949620428, 'Bgr': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Wbcc': 0.02797339593114241, 'Appet': 0.027783137179239824, 'Sc': 0.029906956136464335, 'Age': 0.02803921568627451, 'Rbc': 0.02786377708978328, 'Dm': 0.028612012987012988, 'Pc': 0.027313266443701224, 'Sod': 0.027583600982429624, 'Pcc': 0.02658450704225352, 'Hemo': 0.027730294396961064, 'Cad': 0.0264808362369338, 'Htn': 0.02792120864410021, 'Al': 0.028298204527712725}
Top 5 Features Selected: ['Bp', 'Bu', 'Pot', 'Sg', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA9190>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Bu': np.float64(0.8333333333333334), 'Pe': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sc': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Pe': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Sg': 0.85, 'Bgr': 0.7, 'Ane': 0.7, 'Wbcc': 0.4, 'Appet': 0.4, 'Sc': 1.0, 'Age': 0.55, 'Rbc': 0.55, 'Dm': 0.8, 'Pc': 0.5, 'Sod': 0.65, 'Pcc': 0.4, 'Hemo': 0.75, 'Cad': 0.45, 'Htn': 0.85, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Su': 0.030330882352941176, 'Bu': 0.0315136476426799, 'Pe': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sg': 0.03036576949620428, 'Bgr': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Wbcc': 0.02797339593114241, 'Appet': 0.027783137179239824, 'Sc': 0.029906956136464335, 'Age': 0.02803921568627451, 'Rbc': 0.02786377708978328, 'Dm': 0.028612012987012988, 'Pc': 0.027313266443701224, 'Sod': 0.027583600982429624, 'Pcc': 0.02658450704225352, 'Hemo': 0.027730294396961064, 'Cad': 0.0264808362369338, 'Htn': 0.02792120864410021, 'Al': 0.028298204527712725}
Top 10 Features Selected: ['Bp', 'Bu', 'Pot', 'Sg', 'Su', 'Pe', 'Pcv', 'Ba', 'Sc', 'Bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345F4D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Bu': np.float64(0.8333333333333334), 'Pe': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sc': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Pe': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Sg': 0.85, 'Bgr': 0.7, 'Ane': 0.7, 'Wbcc': 0.4, 'Appet': 0.4, 'Sc': 1.0, 'Age': 0.55, 'Rbc': 0.55, 'Dm': 0.8, 'Pc': 0.5, 'Sod': 0.65, 'Pcc': 0.4, 'Hemo': 0.75, 'Cad': 0.45, 'Htn': 0.85, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Su': 0.030330882352941176, 'Bu': 0.0315136476426799, 'Pe': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sg': 0.03036576949620428, 'Bgr': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Wbcc': 0.02797339593114241, 'Appet': 0.027783137179239824, 'Sc': 0.029906956136464335, 'Age': 0.02803921568627451, 'Rbc': 0.02786377708978328, 'Dm': 0.028612012987012988, 'Pc': 0.027313266443701224, 'Sod': 0.027583600982429624, 'Pcc': 0.02658450704225352, 'Hemo': 0.027730294396961064, 'Cad': 0.0264808362369338, 'Htn': 0.02792120864410021, 'Al': 0.028298204527712725}
Top 15 Features Selected: ['Bp', 'Bu', 'Pot', 'Sg', 'Su', 'Pe', 'Pcv', 'Ba', 'Sc', 'Bgr', 'Rbcc', 'Ane', 'Dm', 'Al', 'Age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8170>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.44it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Su': 0.875, 'Bu': 0.8333333333333334, 'Pe': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Bgr': 0.625, 'Ane': 0.5833333333333334, 'Wbcc': 0.5416666666666666, 'Appet': 0.5, 'Sc': 0.4583333333333333, 'Age': 0.4166666666666667, 'Rbc': 0.375, 'Dm': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Sod': 0.25, 'Pcc': 0.20833333333333334, 'Hemo': 0.16666666666666666, 'Cad': 0.125, 'Htn': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Bu': np.float64(0.8333333333333334), 'Pe': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Bgr': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Wbcc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Sc': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Rbc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Hemo': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Ba': 0.4, 'Su': 0.55, 'Bu': 0.9, 'Pe': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Sg': 0.85, 'Bgr': 0.7, 'Ane': 0.7, 'Wbcc': 0.4, 'Appet': 0.4, 'Sc': 1.0, 'Age': 0.55, 'Rbc': 0.55, 'Dm': 0.8, 'Pc': 0.5, 'Sod': 0.65, 'Pcc': 0.4, 'Hemo': 0.75, 'Cad': 0.45, 'Htn': 0.85, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Su': 0.030330882352941176, 'Bu': 0.0315136476426799, 'Pe': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Sg': 0.03036576949620428, 'Bgr': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Wbcc': 0.02797339593114241, 'Appet': 0.027783137179239824, 'Sc': 0.029906956136464335, 'Age': 0.02803921568627451, 'Rbc': 0.02786377708978328, 'Dm': 0.028612012987012988, 'Pc': 0.027313266443701224, 'Sod': 0.027583600982429624, 'Pcc': 0.02658450704225352, 'Hemo': 0.027730294396961064, 'Cad': 0.0264808362369338, 'Htn': 0.02792120864410021, 'Al': 0.028298204527712725}
Top 20 Features Selected: ['Bp', 'Bu', 'Pot', 'Sg', 'Su', 'Pe', 'Pcv', 'Ba', 'Sc', 'Bgr', 'Rbcc', 'Ane', 'Dm', 'Al', 'Age', 'Wbcc', 'Htn', 'Rbc', 'Appet', 'Hemo']
Run 12/25

100%|██████████| 24/24 [00:07<00:00,  3.34it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA99D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Rbcc': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Al': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Bgr': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Appet': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Wbcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Rbcc': 0.55, 'Su': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Sod': 0.65, 'Sg': 0.85, 'Pot': 0.65, 'Al': 1.0, 'Sc': 1.0, 'Hemo': 0.75, 'Bgr': 0.7, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Age': 0.55, 'Pcc': 0.4, 'Dm': 0.8, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Rbcc': 0.030330882352941176, 'Su': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sod': 0.029418126757516764, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Al': 0.03028233151183971, 'Sc': 0.03009207275993712, 'Hemo': 0.0288981288981289, 'Bgr': 0.028484848484848488, 'Pc': 0.027650648360030512, 'Appet': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Pcc': 0.02658450704225352, 'Dm': 0.02797067901234568, 'Wbcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Cad': 0.026190476190476188}
Top 5 Features Selected: ['Bp', 'Pe', 'Bu', 'Rbcc', 'Pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAA630>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Rbcc': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Al': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Bgr': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Appet': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Wbcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Rbcc': 0.55, 'Su': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Sod': 0.65, 'Sg': 0.85, 'Pot': 0.65, 'Al': 1.0, 'Sc': 1.0, 'Hemo': 0.75, 'Bgr': 0.7, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Age': 0.55, 'Pcc': 0.4, 'Dm': 0.8, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Rbcc': 0.030330882352941176, 'Su': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sod': 0.029418126757516764, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Al': 0.03028233151183971, 'Sc': 0.03009207275993712, 'Hemo': 0.0288981288981289, 'Bgr': 0.028484848484848488, 'Pc': 0.027650648360030512, 'Appet': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Pcc': 0.02658450704225352, 'Dm': 0.02797067901234568, 'Wbcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Cad': 0.026190476190476188}
Top 10 Features Selected: ['Bp', 'Pe', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Sc', 'Su', 'Ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345ECF0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Rbcc': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Al': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Bgr': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Appet': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Wbcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Rbcc': 0.55, 'Su': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Sod': 0.65, 'Sg': 0.85, 'Pot': 0.65, 'Al': 1.0, 'Sc': 1.0, 'Hemo': 0.75, 'Bgr': 0.7, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Age': 0.55, 'Pcc': 0.4, 'Dm': 0.8, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Rbcc': 0.030330882352941176, 'Su': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sod': 0.029418126757516764, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Al': 0.03028233151183971, 'Sc': 0.03009207275993712, 'Hemo': 0.0288981288981289, 'Bgr': 0.028484848484848488, 'Pc': 0.027650648360030512, 'Appet': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Pcc': 0.02658450704225352, 'Dm': 0.02797067901234568, 'Wbcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Cad': 0.026190476190476188}
Top 15 Features Selected: ['Bp', 'Pe', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Sc', 'Su', 'Ane', 'Ba', 'Sod', 'Pot', 'Hemo', 'Bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03111430>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pe': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Rbcc': 0.875, 'Su': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Al': 0.5416666666666666, 'Sc': 0.5, 'Hemo': 0.4583333333333333, 'Bgr': 0.4166666666666667, 'Pc': 0.375, 'Appet': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Pcc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Wbcc': 0.125, 'Htn': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pe': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Rbcc': np.float64(0.875), 'Su': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Al': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Bgr': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Appet': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Pcc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Wbcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pe': 0.65, 'Ba': 0.4, 'Rbcc': 0.55, 'Su': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Sod': 0.65, 'Sg': 0.85, 'Pot': 0.65, 'Al': 1.0, 'Sc': 1.0, 'Hemo': 0.75, 'Bgr': 0.7, 'Pc': 0.5, 'Appet': 0.4, 'Rbc': 0.55, 'Age': 0.55, 'Pcc': 0.4, 'Dm': 0.8, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pe': 0.031054405392392875, 'Ba': 0.029957522915269395, 'Rbcc': 0.030330882352941176, 'Su': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sod': 0.029418126757516764, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Al': 0.03028233151183971, 'Sc': 0.03009207275993712, 'Hemo': 0.0288981288981289, 'Bgr': 0.028484848484848488, 'Pc': 0.027650648360030512, 'Appet': 0.027071520029266508, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Pcc': 0.02658450704225352, 'Dm': 0.02797067901234568, 'Wbcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Cad': 0.026190476190476188}
Top 20 Features Selected: ['Bp', 'Pe', 'Bu', 'Rbcc', 'Pcv', 'Al', 'Sg', 'Sc', 'Su', 'Ane', 'Ba', 'Sod', 'Pot', 'Hemo', 'Bgr', 'Dm', 'Htn', 'Pc', 'Rbc', 'Age']
Run 13/25

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA9970>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.55it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Htn': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Dm': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Bu': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Pcv': 0.7, 'Ba': 0.4, 'Bgr': 0.7, 'Su': 0.55, 'Rbcc': 0.55, 'Appet': 0.4, 'Sg': 0.85, 'Pe': 0.65, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Wbcc': 0.4, 'Dm': 0.8, 'Hemo': 0.75, 'Ane': 0.7, 'Bu': 0.9, 'Rbc': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Pcc': 0.4, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Sg': 0.03036576949620428, 'Pe': 0.029211087420042643, 'Htn': 0.029957522915269395, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Wbcc': 0.027598020555767037, 'Dm': 0.028958333333333336, 'Hemo': 0.02854251012145749, 'Ane': 0.02813852813852814, 'Bu': 0.028949545078577336, 'Rbc': 0.027364110201042444, 'Al': 0.02889344262295082, 'Pc': 0.026838432635534086, 'Pcc': 0.026279628993473032, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Pot', 'Pcv', 'Bgr', 'Sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D6510>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.59it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Htn': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Dm': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Bu': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Pcv': 0.7, 'Ba': 0.4, 'Bgr': 0.7, 'Su': 0.55, 'Rbcc': 0.55, 'Appet': 0.4, 'Sg': 0.85, 'Pe': 0.65, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Wbcc': 0.4, 'Dm': 0.8, 'Hemo': 0.75, 'Ane': 0.7, 'Bu': 0.9, 'Rbc': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Pcc': 0.4, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Sg': 0.03036576949620428, 'Pe': 0.029211087420042643, 'Htn': 0.029957522915269395, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Wbcc': 0.027598020555767037, 'Dm': 0.028958333333333336, 'Hemo': 0.02854251012145749, 'Ane': 0.02813852813852814, 'Bu': 0.028949545078577336, 'Rbc': 0.027364110201042444, 'Al': 0.02889344262295082, 'Pc': 0.026838432635534086, 'Pcc': 0.026279628993473032, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Pot', 'Pcv', 'Bgr', 'Sg', 'Sc', 'Htn', 'Su', 'Ba', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D5430>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.35it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Htn': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Dm': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Bu': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Pcv': 0.7, 'Ba': 0.4, 'Bgr': 0.7, 'Su': 0.55, 'Rbcc': 0.55, 'Appet': 0.4, 'Sg': 0.85, 'Pe': 0.65, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Wbcc': 0.4, 'Dm': 0.8, 'Hemo': 0.75, 'Ane': 0.7, 'Bu': 0.9, 'Rbc': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Pcc': 0.4, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Sg': 0.03036576949620428, 'Pe': 0.029211087420042643, 'Htn': 0.029957522915269395, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Wbcc': 0.027598020555767037, 'Dm': 0.028958333333333336, 'Hemo': 0.02854251012145749, 'Ane': 0.02813852813852814, 'Bu': 0.028949545078577336, 'Rbc': 0.027364110201042444, 'Al': 0.02889344262295082, 'Pc': 0.026838432635534086, 'Pcc': 0.026279628993473032, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Pot', 'Pcv', 'Bgr', 'Sg', 'Sc', 'Htn', 'Su', 'Ba', 'Rbcc', 'Pe', 'Dm', 'Bu', 'Al', 'Appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321CC50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Rbcc': 0.75, 'Appet': 0.7083333333333334, 'Sg': 0.6666666666666666, 'Pe': 0.625, 'Htn': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Sod': 0.5, 'Wbcc': 0.4583333333333333, 'Dm': 0.4166666666666667, 'Hemo': 0.375, 'Ane': 0.3333333333333333, 'Bu': 0.2916666666666667, 'Rbc': 0.25, 'Al': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Pcc': 0.125, 'Cad': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Sg': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Htn': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Dm': np.float64(0.4166666666666667), 'Hemo': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Bu': np.float64(0.2916666666666667), 'Rbc': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Cad': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Pcv': 0.7, 'Ba': 0.4, 'Bgr': 0.7, 'Su': 0.55, 'Rbcc': 0.55, 'Appet': 0.4, 'Sg': 0.85, 'Pe': 0.65, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Wbcc': 0.4, 'Dm': 0.8, 'Hemo': 0.75, 'Ane': 0.7, 'Bu': 0.9, 'Rbc': 0.55, 'Al': 1.0, 'Pc': 0.5, 'Pcc': 0.4, 'Cad': 0.45, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Sg': 0.03036576949620428, 'Pe': 0.029211087420042643, 'Htn': 0.029957522915269395, 'Sc': 0.03028233151183971, 'Sod': 0.02862400327131466, 'Wbcc': 0.027598020555767037, 'Dm': 0.028958333333333336, 'Hemo': 0.02854251012145749, 'Ane': 0.02813852813852814, 'Bu': 0.028949545078577336, 'Rbc': 0.027364110201042444, 'Al': 0.02889344262295082, 'Pc': 0.026838432635534086, 'Pcc': 0.026279628993473032, 'Cad': 0.026333907056798625, 'Age': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Pot', 'Pcv', 'Bgr', 'Sg', 'Sc', 'Htn', 'Su', 'Ba', 'Rbcc', 'Pe', 'Dm', 'Bu', 'Al', 'Appet', 'Sod', 'Hemo', 'Ane', 'Wbcc', 'Rbc']
Run 14/25

100%|██████████| 24/24 [00:06<00:00,  3.61it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAA8B30>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.35it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Hemo': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Pcv': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Rbcc': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Su': 0.55, 'Sg': 0.85, 'Appet': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pe': 0.65, 'Pcv': 0.7, 'Ane': 0.7, 'Sod': 0.65, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Al': 1.0, 'Dm': 0.8, 'Rbc': 0.55, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Su': 0.030330882352941176, 'Sg': 0.03125763125763126, 'Appet': 0.029236022193768675, 'Bu': 0.031054405392392875, 'Hemo': 0.030090497737556562, 'Pe': 0.029418126757516764, 'Pcv': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Sod': 0.028814262023217248, 'Bgr': 0.028850145288501453, 'Rbcc': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Pcc': 0.027242401779095628, 'Pc': 0.027479766610201392, 'Wbcc': 0.02690501986276634, 'Htn': 0.028531243721117136, 'Cad': 0.026785714285714288, 'Al': 0.0287391216352965, 'Dm': 0.027820121951219513, 'Rbc': 0.026754075124025514, 'Age': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Sg', 'Bu', 'Pot', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321D550>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.45it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Hemo': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Pcv': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Rbcc': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Su': 0.55, 'Sg': 0.85, 'Appet': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pe': 0.65, 'Pcv': 0.7, 'Ane': 0.7, 'Sod': 0.65, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Al': 1.0, 'Dm': 0.8, 'Rbc': 0.55, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Su': 0.030330882352941176, 'Sg': 0.03125763125763126, 'Appet': 0.029236022193768675, 'Bu': 0.031054405392392875, 'Hemo': 0.030090497737556562, 'Pe': 0.029418126757516764, 'Pcv': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Sod': 0.028814262023217248, 'Bgr': 0.028850145288501453, 'Rbcc': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Pcc': 0.027242401779095628, 'Pc': 0.027479766610201392, 'Wbcc': 0.02690501986276634, 'Htn': 0.028531243721117136, 'Cad': 0.026785714285714288, 'Al': 0.0287391216352965, 'Dm': 0.027820121951219513, 'Rbc': 0.026754075124025514, 'Age': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Sg', 'Bu', 'Pot', 'Su', 'Ba', 'Hemo', 'Sc', 'Pcv', 'Pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D4EF0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.59it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Hemo': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Pcv': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Rbcc': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Su': 0.55, 'Sg': 0.85, 'Appet': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pe': 0.65, 'Pcv': 0.7, 'Ane': 0.7, 'Sod': 0.65, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Al': 1.0, 'Dm': 0.8, 'Rbc': 0.55, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Su': 0.030330882352941176, 'Sg': 0.03125763125763126, 'Appet': 0.029236022193768675, 'Bu': 0.031054405392392875, 'Hemo': 0.030090497737556562, 'Pe': 0.029418126757516764, 'Pcv': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Sod': 0.028814262023217248, 'Bgr': 0.028850145288501453, 'Rbcc': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Pcc': 0.027242401779095628, 'Pc': 0.027479766610201392, 'Wbcc': 0.02690501986276634, 'Htn': 0.028531243721117136, 'Cad': 0.026785714285714288, 'Al': 0.0287391216352965, 'Dm': 0.027820121951219513, 'Rbc': 0.026754075124025514, 'Age': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Sg', 'Bu', 'Pot', 'Su', 'Ba', 'Hemo', 'Sc', 'Pcv', 'Pe', 'Appet', 'Ane', 'Bgr', 'Sod', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D5B50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Su': 0.875, 'Sg': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bu': 0.75, 'Hemo': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Pcv': 0.625, 'Ane': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Bgr': 0.5, 'Rbcc': 0.4583333333333333, 'Sc': 0.4166666666666667, 'Pcc': 0.375, 'Pc': 0.3333333333333333, 'Wbcc': 0.2916666666666667, 'Htn': 0.25, 'Cad': 0.20833333333333334, 'Al': 0.16666666666666666, 'Dm': 0.125, 'Rbc': 0.08333333333333333, 'Age': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Su': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Hemo': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Pcv': np.float64(0.625), 'Ane': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Rbcc': np.float64(0.4583333333333333), 'Sc': np.float64(0.4166666666666667), 'Pcc': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Wbcc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Cad': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Dm': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Age': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Su': 0.55, 'Sg': 0.85, 'Appet': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pe': 0.65, 'Pcv': 0.7, 'Ane': 0.7, 'Sod': 0.65, 'Bgr': 0.7, 'Rbcc': 0.55, 'Sc': 1.0, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4, 'Htn': 0.85, 'Cad': 0.45, 'Al': 1.0, 'Dm': 0.8, 'Rbc': 0.55, 'Age': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Su': 0.030330882352941176, 'Sg': 0.03125763125763126, 'Appet': 0.029236022193768675, 'Bu': 0.031054405392392875, 'Hemo': 0.030090497737556562, 'Pe': 0.029418126757516764, 'Pcv': 0.029437229437229435, 'Ane': 0.029236022193768675, 'Sod': 0.028814262023217248, 'Bgr': 0.028850145288501453, 'Rbcc': 0.02821939586645469, 'Sc': 0.029726775956284153, 'Pcc': 0.027242401779095628, 'Pc': 0.027479766610201392, 'Wbcc': 0.02690501986276634, 'Htn': 0.028531243721117136, 'Cad': 0.026785714285714288, 'Al': 0.0287391216352965, 'Dm': 0.027820121951219513, 'Rbc': 0.026754075124025514, 'Age': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Sg', 'Bu', 'Pot', 'Su', 'Ba', 'Hemo', 'Sc', 'Pcv', 'Pe', 'Appet', 'Ane', 'Bgr', 'Sod', 'Al', 'Htn', 'Rbcc', 'Dm', 'Pc', 'Pcc']
Run 15/25

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAB530>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.41it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Htn': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Pcc': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Wbcc': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Age': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pcv': 0.7, 'Pot': 0.65, 'Htn': 0.85, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Rbcc': 0.55, 'Al': 1.0, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcc': 0.4, 'Sod': 0.65, 'Pe': 0.65, 'Hemo': 0.75, 'Sg': 0.85, 'Wbcc': 0.4, 'Dm': 0.8, 'Pc': 0.5, 'Cad': 0.45, 'Age': 0.55, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pcv': 0.031024531024531024, 'Pot': 0.03055037313432836, 'Htn': 0.03125763125763126, 'Ba': 0.029236022193768675, 'Su': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Rbcc': 0.02919863597612958, 'Al': 0.030679156908665108, 'Bgr': 0.029236022193768675, 'Ane': 0.02904040404040404, 'Bu': 0.029827662395050816, 'Pcc': 0.027598020555767037, 'Sod': 0.028258706467661692, 'Pe': 0.028083267871170464, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Wbcc': 0.026742734890354787, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Cad': 0.0264808362369338, 'Age': 0.026754075124025514, 'Rbc': 0.02661064425770308}
Top 5 Features Selected: ['Sc', 'Bp', 'Htn', 'Pcv', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345D9D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.47it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Htn': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Pcc': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Wbcc': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Age': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pcv': 0.7, 'Pot': 0.65, 'Htn': 0.85, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Rbcc': 0.55, 'Al': 1.0, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcc': 0.4, 'Sod': 0.65, 'Pe': 0.65, 'Hemo': 0.75, 'Sg': 0.85, 'Wbcc': 0.4, 'Dm': 0.8, 'Pc': 0.5, 'Cad': 0.45, 'Age': 0.55, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pcv': 0.031024531024531024, 'Pot': 0.03055037313432836, 'Htn': 0.03125763125763126, 'Ba': 0.029236022193768675, 'Su': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Rbcc': 0.02919863597612958, 'Al': 0.030679156908665108, 'Bgr': 0.029236022193768675, 'Ane': 0.02904040404040404, 'Bu': 0.029827662395050816, 'Pcc': 0.027598020555767037, 'Sod': 0.028258706467661692, 'Pe': 0.028083267871170464, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Wbcc': 0.026742734890354787, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Cad': 0.0264808362369338, 'Age': 0.026754075124025514, 'Rbc': 0.02661064425770308}
Top 10 Features Selected: ['Sc', 'Bp', 'Htn', 'Pcv', 'Al', 'Pot', 'Bu', 'Su', 'Ba', 'Bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113A70>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.47it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Htn': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Pcc': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Wbcc': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Age': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pcv': 0.7, 'Pot': 0.65, 'Htn': 0.85, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Rbcc': 0.55, 'Al': 1.0, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcc': 0.4, 'Sod': 0.65, 'Pe': 0.65, 'Hemo': 0.75, 'Sg': 0.85, 'Wbcc': 0.4, 'Dm': 0.8, 'Pc': 0.5, 'Cad': 0.45, 'Age': 0.55, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pcv': 0.031024531024531024, 'Pot': 0.03055037313432836, 'Htn': 0.03125763125763126, 'Ba': 0.029236022193768675, 'Su': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Rbcc': 0.02919863597612958, 'Al': 0.030679156908665108, 'Bgr': 0.029236022193768675, 'Ane': 0.02904040404040404, 'Bu': 0.029827662395050816, 'Pcc': 0.027598020555767037, 'Sod': 0.028258706467661692, 'Pe': 0.028083267871170464, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Wbcc': 0.026742734890354787, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Cad': 0.0264808362369338, 'Age': 0.026754075124025514, 'Rbc': 0.02661064425770308}
Top 15 Features Selected: ['Sc', 'Bp', 'Htn', 'Pcv', 'Al', 'Pot', 'Bu', 'Su', 'Ba', 'Bgr', 'Rbcc', 'Ane', 'Appet', 'Sg', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345C470>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.39it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Pot': 0.875, 'Htn': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Su': 0.75, 'Appet': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Al': 0.625, 'Bgr': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Bu': 0.5, 'Pcc': 0.4583333333333333, 'Sod': 0.4166666666666667, 'Pe': 0.375, 'Hemo': 0.3333333333333333, 'Sg': 0.2916666666666667, 'Wbcc': 0.25, 'Dm': 0.20833333333333334, 'Pc': 0.16666666666666666, 'Cad': 0.125, 'Age': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Htn': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Su': np.float64(0.75), 'Appet': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Pcc': np.float64(0.4583333333333333), 'Sod': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Sg': np.float64(0.2916666666666667), 'Wbcc': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pc': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Age': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pcv': 0.7, 'Pot': 0.65, 'Htn': 0.85, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Rbcc': 0.55, 'Al': 1.0, 'Bgr': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Pcc': 0.4, 'Sod': 0.65, 'Pe': 0.65, 'Hemo': 0.75, 'Sg': 0.85, 'Wbcc': 0.4, 'Dm': 0.8, 'Pc': 0.5, 'Cad': 0.45, 'Age': 0.55, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pcv': 0.031024531024531024, 'Pot': 0.03055037313432836, 'Htn': 0.03125763125763126, 'Ba': 0.029236022193768675, 'Su': 0.029631255487269532, 'Appet': 0.028790389395194696, 'Rbcc': 0.02919863597612958, 'Al': 0.030679156908665108, 'Bgr': 0.029236022193768675, 'Ane': 0.02904040404040404, 'Bu': 0.029827662395050816, 'Pcc': 0.027598020555767037, 'Sod': 0.028258706467661692, 'Pe': 0.028083267871170464, 'Hemo': 0.028371628371628373, 'Sg': 0.028693528693528692, 'Wbcc': 0.026742734890354787, 'Dm': 0.028125, 'Pc': 0.026838432635534086, 'Cad': 0.0264808362369338, 'Age': 0.026754075124025514, 'Rbc': 0.02661064425770308}
Top 20 Features Selected: ['Sc', 'Bp', 'Htn', 'Pcv', 'Al', 'Pot', 'Bu', 'Su', 'Ba', 'Bgr', 'Rbcc', 'Ane', 'Appet', 'Sg', 'Hemo', 'Sod', 'Dm', 'Pe', 'Pcc', 'Pc']
Run 16/25

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FA8AB70>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Pcc': np.float64(0.75), 'Age': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Bu': np.float64(0.5833333333333334), 'Rbcc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Sc': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Su': 0.55, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Pcc': 0.4, 'Age': 0.55, 'Pe': 0.65, 'Ane': 0.7, 'Bu': 0.9, 'Rbcc': 0.55, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Sc': 1.0, 'Wbcc': 0.4, 'Pc': 0.5, 'Htn': 0.85, 'Rbc': 0.55, 'Dm': 0.8, 'Cad': 0.45, 'Hemo': 0.75, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Su': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Ba': 0.029236022193768675, 'Pcc': 0.02900988017658188, 'Age': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Ane': 0.029437229437229435, 'Bu': 0.03021353930031804, 'Rbcc': 0.028594771241830064, 'Sod': 0.02862400327131466, 'Appet': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Sc': 0.029551337359792925, 'Wbcc': 0.027071520029266508, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Rbc': 0.027205882352941177, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Hemo': 0.027432808155699723, 'Al': 0.028298204527712725}
Top 5 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112870>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.46it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Pcc': np.float64(0.75), 'Age': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Bu': np.float64(0.5833333333333334), 'Rbcc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Sc': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Su': 0.55, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Pcc': 0.4, 'Age': 0.55, 'Pe': 0.65, 'Ane': 0.7, 'Bu': 0.9, 'Rbcc': 0.55, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Sc': 1.0, 'Wbcc': 0.4, 'Pc': 0.5, 'Htn': 0.85, 'Rbc': 0.55, 'Dm': 0.8, 'Cad': 0.45, 'Hemo': 0.75, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Su': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Ba': 0.029236022193768675, 'Pcc': 0.02900988017658188, 'Age': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Ane': 0.029437229437229435, 'Bu': 0.03021353930031804, 'Rbcc': 0.028594771241830064, 'Sod': 0.02862400327131466, 'Appet': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Sc': 0.029551337359792925, 'Wbcc': 0.027071520029266508, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Rbc': 0.027205882352941177, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Hemo': 0.027432808155699723, 'Al': 0.028298204527712725}
Top 10 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Bu', 'Sc', 'Ane', 'Pe', 'Age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113DD0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.43it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Pcc': np.float64(0.75), 'Age': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Bu': np.float64(0.5833333333333334), 'Rbcc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Sc': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Su': 0.55, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Pcc': 0.4, 'Age': 0.55, 'Pe': 0.65, 'Ane': 0.7, 'Bu': 0.9, 'Rbcc': 0.55, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Sc': 1.0, 'Wbcc': 0.4, 'Pc': 0.5, 'Htn': 0.85, 'Rbc': 0.55, 'Dm': 0.8, 'Cad': 0.45, 'Hemo': 0.75, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Su': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Ba': 0.029236022193768675, 'Pcc': 0.02900988017658188, 'Age': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Ane': 0.029437229437229435, 'Bu': 0.03021353930031804, 'Rbcc': 0.028594771241830064, 'Sod': 0.02862400327131466, 'Appet': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Sc': 0.029551337359792925, 'Wbcc': 0.027071520029266508, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Rbc': 0.027205882352941177, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Hemo': 0.027432808155699723, 'Al': 0.028298204527712725}
Top 15 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Bu', 'Sc', 'Ane', 'Pe', 'Age', 'Ba', 'Sg', 'Pcc', 'Sod', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321F710>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.42it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Pot': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Ba': 0.7916666666666666, 'Pcc': 0.75, 'Age': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Ane': 0.625, 'Bu': 0.5833333333333334, 'Rbcc': 0.5416666666666666, 'Sod': 0.5, 'Appet': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Sc': 0.375, 'Wbcc': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Rbc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Cad': 0.125, 'Hemo': 0.08333333333333333, 'Al': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Pot': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Ba': np.float64(0.7916666666666666), 'Pcc': np.float64(0.75), 'Age': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Bu': np.float64(0.5833333333333334), 'Rbcc': np.float64(0.5416666666666666), 'Sod': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Sc': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Rbc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Cad': np.float64(0.125), 'Hemo': np.float64(0.08333333333333333), 'Al': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Pot': 0.65, 'Su': 0.55, 'Pcv': 0.7, 'Bgr': 0.7, 'Ba': 0.4, 'Pcc': 0.4, 'Age': 0.55, 'Pe': 0.65, 'Ane': 0.7, 'Bu': 0.9, 'Rbcc': 0.55, 'Sod': 0.65, 'Appet': 0.4, 'Sg': 0.85, 'Sc': 1.0, 'Wbcc': 0.4, 'Pc': 0.5, 'Htn': 0.85, 'Rbc': 0.55, 'Dm': 0.8, 'Cad': 0.45, 'Hemo': 0.75, 'Al': 1.0}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Pot': 0.031054405392392875, 'Su': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Ba': 0.029236022193768675, 'Pcc': 0.02900988017658188, 'Age': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Ane': 0.029437229437229435, 'Bu': 0.03021353930031804, 'Rbcc': 0.028594771241830064, 'Sod': 0.02862400327131466, 'Appet': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Sc': 0.029551337359792925, 'Wbcc': 0.027071520029266508, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Rbc': 0.027205882352941177, 'Dm': 0.02797067901234568, 'Cad': 0.0264808362369338, 'Hemo': 0.027432808155699723, 'Al': 0.028298204527712725}
Top 20 Features Selected: ['Bp', 'Pot', 'Pcv', 'Su', 'Bgr', 'Bu', 'Sc', 'Ane', 'Pe', 'Age', 'Ba', 'Sg', 'Pcc', 'Sod', 'Rbcc', 'Htn', 'Al', 'Dm', 'Appet', 'Hemo']
Run 17/25

100%|██████████| 24/24 [00:06<00:00,  3.59it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031124B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.54it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Pot': np.float64(0.75), 'Dm': np.float64(0.7083333333333334), 'Pcc': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Rbc': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Cad': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Sg': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Ba': 0.4, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Pot': 0.65, 'Dm': 0.8, 'Pcc': 0.4, 'Ane': 0.7, 'Rbc': 0.55, 'Sc': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Pc': 0.5, 'Sod': 0.65, 'Cad': 0.45, 'Pcv': 0.7, 'Age': 0.55, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Htn': 0.85, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Pot': 0.029850746268656716, 'Dm': 0.030330882352941176, 'Pcc': 0.028577260665441927, 'Ane': 0.029437229437229435, 'Rbc': 0.028790389395194696, 'Sc': 0.03028233151183971, 'Appet': 0.027783137179239824, 'Bgr': 0.028665028665028666, 'Pc': 0.02782608695652174, 'Sod': 0.028083267871170464, 'Cad': 0.027272727272727275, 'Pcv': 0.027972027972027972, 'Age': 0.027364110201042444, 'Wbcc': 0.02658450704225352, 'Al': 0.0287391216352965, 'Sg': 0.028068137824235385, 'Htn': 0.02792120864410021, 'Hemo': 0.02728937728937729}
Top 5 Features Selected: ['Bp', 'Bu', 'Su', 'Pe', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345D430>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.56it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Pot': np.float64(0.75), 'Dm': np.float64(0.7083333333333334), 'Pcc': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Rbc': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Cad': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Sg': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Ba': 0.4, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Pot': 0.65, 'Dm': 0.8, 'Pcc': 0.4, 'Ane': 0.7, 'Rbc': 0.55, 'Sc': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Pc': 0.5, 'Sod': 0.65, 'Cad': 0.45, 'Pcv': 0.7, 'Age': 0.55, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Htn': 0.85, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Pot': 0.029850746268656716, 'Dm': 0.030330882352941176, 'Pcc': 0.028577260665441927, 'Ane': 0.029437229437229435, 'Rbc': 0.028790389395194696, 'Sc': 0.03028233151183971, 'Appet': 0.027783137179239824, 'Bgr': 0.028665028665028666, 'Pc': 0.02782608695652174, 'Sod': 0.028083267871170464, 'Cad': 0.027272727272727275, 'Pcv': 0.027972027972027972, 'Age': 0.027364110201042444, 'Wbcc': 0.02658450704225352, 'Al': 0.0287391216352965, 'Sg': 0.028068137824235385, 'Htn': 0.02792120864410021, 'Hemo': 0.02728937728937729}
Top 10 Features Selected: ['Bp', 'Bu', 'Su', 'Pe', 'Dm', 'Sc', 'Rbcc', 'Ba', 'Pot', 'Ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031123F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Pot': np.float64(0.75), 'Dm': np.float64(0.7083333333333334), 'Pcc': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Rbc': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Cad': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Sg': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Ba': 0.4, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Pot': 0.65, 'Dm': 0.8, 'Pcc': 0.4, 'Ane': 0.7, 'Rbc': 0.55, 'Sc': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Pc': 0.5, 'Sod': 0.65, 'Cad': 0.45, 'Pcv': 0.7, 'Age': 0.55, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Htn': 0.85, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Pot': 0.029850746268656716, 'Dm': 0.030330882352941176, 'Pcc': 0.028577260665441927, 'Ane': 0.029437229437229435, 'Rbc': 0.028790389395194696, 'Sc': 0.03028233151183971, 'Appet': 0.027783137179239824, 'Bgr': 0.028665028665028666, 'Pc': 0.02782608695652174, 'Sod': 0.028083267871170464, 'Cad': 0.027272727272727275, 'Pcv': 0.027972027972027972, 'Age': 0.027364110201042444, 'Wbcc': 0.02658450704225352, 'Al': 0.0287391216352965, 'Sg': 0.028068137824235385, 'Htn': 0.02792120864410021, 'Hemo': 0.02728937728937729}
Top 15 Features Selected: ['Bp', 'Bu', 'Su', 'Pe', 'Dm', 'Sc', 'Rbcc', 'Ba', 'Pot', 'Ane', 'Rbc', 'Al', 'Bgr', 'Pcc', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D4BF0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.35it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Ba': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Bu': 0.7916666666666666, 'Pot': 0.75, 'Dm': 0.7083333333333334, 'Pcc': 0.6666666666666666, 'Ane': 0.625, 'Rbc': 0.5833333333333334, 'Sc': 0.5416666666666666, 'Appet': 0.5, 'Bgr': 0.4583333333333333, 'Pc': 0.4166666666666667, 'Sod': 0.375, 'Cad': 0.3333333333333333, 'Pcv': 0.2916666666666667, 'Age': 0.25, 'Wbcc': 0.20833333333333334, 'Al': 0.16666666666666666, 'Sg': 0.125, 'Htn': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Ba': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Bu': np.float64(0.7916666666666666), 'Pot': np.float64(0.75), 'Dm': np.float64(0.7083333333333334), 'Pcc': np.float64(0.6666666666666666), 'Ane': np.float64(0.625), 'Rbc': np.float64(0.5833333333333334), 'Sc': np.float64(0.5416666666666666), 'Appet': np.float64(0.5), 'Bgr': np.float64(0.4583333333333333), 'Pc': np.float64(0.4166666666666667), 'Sod': np.float64(0.375), 'Cad': np.float64(0.3333333333333333), 'Pcv': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Al': np.float64(0.16666666666666666), 'Sg': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Ba': 0.4, 'Pe': 0.65, 'Rbcc': 0.55, 'Bu': 0.9, 'Pot': 0.65, 'Dm': 0.8, 'Pcc': 0.4, 'Ane': 0.7, 'Rbc': 0.55, 'Sc': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Pc': 0.5, 'Sod': 0.65, 'Cad': 0.45, 'Pcv': 0.7, 'Age': 0.55, 'Wbcc': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Htn': 0.85, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Ba': 0.029957522915269395, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Bu': 0.03128054740957967, 'Pot': 0.029850746268656716, 'Dm': 0.030330882352941176, 'Pcc': 0.028577260665441927, 'Ane': 0.029437229437229435, 'Rbc': 0.028790389395194696, 'Sc': 0.03028233151183971, 'Appet': 0.027783137179239824, 'Bgr': 0.028665028665028666, 'Pc': 0.02782608695652174, 'Sod': 0.028083267871170464, 'Cad': 0.027272727272727275, 'Pcv': 0.027972027972027972, 'Age': 0.027364110201042444, 'Wbcc': 0.02658450704225352, 'Al': 0.0287391216352965, 'Sg': 0.028068137824235385, 'Htn': 0.02792120864410021, 'Hemo': 0.02728937728937729}
Top 20 Features Selected: ['Bp', 'Bu', 'Su', 'Pe', 'Dm', 'Sc', 'Rbcc', 'Ba', 'Pot', 'Ane', 'Rbc', 'Al', 'Bgr', 'Pcc', 'Sod', 'Sg', 'Pcv', 'Htn', 'Pc', 'Appet']
Run 18/25

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345F9B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.57it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Cad': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Su': np.float64(0.2916666666666667), 'Pcc': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Htn': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Rbcc': 0.55, 'Sod': 0.65, 'Pc': 0.5, 'Pe': 0.65, 'Age': 0.55, 'Cad': 0.45, 'Ane': 0.7, 'Su': 0.55, 'Pcc': 0.4, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Dm': 0.8, 'Htn': 0.85}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Appet': 0.029236022193768675, 'Bgr': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Al': 0.030679156908665108, 'Rbcc': 0.028790389395194696, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Pe': 0.028438886647841874, 'Age': 0.02803921568627451, 'Cad': 0.027443609022556388, 'Ane': 0.02813852813852814, 'Su': 0.027526395173453996, 'Pcc': 0.026742734890354787, 'Wbcc': 0.02658450704225352, 'Rbc': 0.027051561365286855, 'Hemo': 0.027579737335834898, 'Dm': 0.027673192771084338, 'Htn': 0.027777777777777776}
Top 5 Features Selected: ['Bp', 'Sg', 'Sc', 'Bu', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031138F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.14it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Cad': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Su': np.float64(0.2916666666666667), 'Pcc': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Htn': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Rbcc': 0.55, 'Sod': 0.65, 'Pc': 0.5, 'Pe': 0.65, 'Age': 0.55, 'Cad': 0.45, 'Ane': 0.7, 'Su': 0.55, 'Pcc': 0.4, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Dm': 0.8, 'Htn': 0.85}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Appet': 0.029236022193768675, 'Bgr': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Al': 0.030679156908665108, 'Rbcc': 0.028790389395194696, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Pe': 0.028438886647841874, 'Age': 0.02803921568627451, 'Cad': 0.027443609022556388, 'Ane': 0.02813852813852814, 'Su': 0.027526395173453996, 'Pcc': 0.026742734890354787, 'Wbcc': 0.02658450704225352, 'Rbc': 0.027051561365286855, 'Hemo': 0.027579737335834898, 'Dm': 0.027673192771084338, 'Htn': 0.027777777777777776}
Top 10 Features Selected: ['Bp', 'Sg', 'Sc', 'Bu', 'Al', 'Pot', 'Pcv', 'Ba', 'Bgr', 'Appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031123F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Cad': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Su': np.float64(0.2916666666666667), 'Pcc': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Htn': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Rbcc': 0.55, 'Sod': 0.65, 'Pc': 0.5, 'Pe': 0.65, 'Age': 0.55, 'Cad': 0.45, 'Ane': 0.7, 'Su': 0.55, 'Pcc': 0.4, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Dm': 0.8, 'Htn': 0.85}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Appet': 0.029236022193768675, 'Bgr': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Al': 0.030679156908665108, 'Rbcc': 0.028790389395194696, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Pe': 0.028438886647841874, 'Age': 0.02803921568627451, 'Cad': 0.027443609022556388, 'Ane': 0.02813852813852814, 'Su': 0.027526395173453996, 'Pcc': 0.026742734890354787, 'Wbcc': 0.02658450704225352, 'Rbc': 0.027051561365286855, 'Hemo': 0.027579737335834898, 'Dm': 0.027673192771084338, 'Htn': 0.027777777777777776}
Top 15 Features Selected: ['Bp', 'Sg', 'Sc', 'Bu', 'Al', 'Pot', 'Pcv', 'Ba', 'Bgr', 'Appet', 'Sod', 'Rbcc', 'Pe', 'Pc', 'Ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345C9B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.46it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Pot': 0.875, 'Pcv': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Bgr': 0.75, 'Bu': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Al': 0.625, 'Rbcc': 0.5833333333333334, 'Sod': 0.5416666666666666, 'Pc': 0.5, 'Pe': 0.4583333333333333, 'Age': 0.4166666666666667, 'Cad': 0.375, 'Ane': 0.3333333333333333, 'Su': 0.2916666666666667, 'Pcc': 0.25, 'Wbcc': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Hemo': 0.125, 'Dm': 0.08333333333333333, 'Htn': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Pot': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Sod': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Pe': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Cad': np.float64(0.375), 'Ane': np.float64(0.3333333333333333), 'Su': np.float64(0.2916666666666667), 'Pcc': np.float64(0.25), 'Wbcc': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Dm': np.float64(0.08333333333333333), 'Htn': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Pcv': 0.7, 'Appet': 0.4, 'Bgr': 0.7, 'Bu': 0.9, 'Sc': 1.0, 'Al': 1.0, 'Rbcc': 0.55, 'Sod': 0.65, 'Pc': 0.5, 'Pe': 0.65, 'Age': 0.55, 'Cad': 0.45, 'Ane': 0.7, 'Su': 0.55, 'Pcc': 0.4, 'Wbcc': 0.4, 'Rbc': 0.55, 'Hemo': 0.75, 'Dm': 0.8, 'Htn': 0.85}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Sg': 0.031746031746031744, 'Pot': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Appet': 0.029236022193768675, 'Bgr': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Sc': 0.030886196246139225, 'Al': 0.030679156908665108, 'Rbcc': 0.028790389395194696, 'Sod': 0.028814262023217248, 'Pc': 0.02819138376017471, 'Pe': 0.028438886647841874, 'Age': 0.02803921568627451, 'Cad': 0.027443609022556388, 'Ane': 0.02813852813852814, 'Su': 0.027526395173453996, 'Pcc': 0.026742734890354787, 'Wbcc': 0.02658450704225352, 'Rbc': 0.027051561365286855, 'Hemo': 0.027579737335834898, 'Dm': 0.027673192771084338, 'Htn': 0.027777777777777776}
Top 20 Features Selected: ['Bp', 'Sg', 'Sc', 'Bu', 'Al', 'Pot', 'Pcv', 'Ba', 'Bgr', 'Appet', 'Sod', 'Rbcc', 'Pe', 'Pc', 'Ane', 'Age', 'Htn', 'Dm', 'Hemo', 'Su']
Run 19/25

100%|██████████| 24/24 [00:06<00:00,  3.43it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113A10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.44it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Sg': np.float64(0.5833333333333334), 'Hemo': np.float64(0.5416666666666666), 'Age': np.float64(0.5), 'Pot': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Sc': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Pe': 0.65, 'Rbcc': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Appet': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Hemo': 0.75, 'Age': 0.55, 'Pot': 0.65, 'Wbcc': 0.4, 'Pc': 0.5, 'Dm': 0.8, 'Sc': 1.0, 'Cad': 0.45, 'Sod': 0.65, 'Rbc': 0.55, 'Pcc': 0.4, 'Htn': 0.85, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Appet': 0.028577260665441927, 'Al': 0.030679156908665108, 'Sg': 0.029957522915269395, 'Hemo': 0.029273504273504274, 'Age': 0.028404512489927477, 'Pot': 0.028438886647841874, 'Wbcc': 0.027417840375586856, 'Pc': 0.027650648360030512, 'Dm': 0.028612012987012988, 'Sc': 0.02921395544346364, 'Cad': 0.02694394213381555, 'Sod': 0.027425373134328357, 'Rbc': 0.027051561365286855, 'Pcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Bgr': 0.027056277056277056}
Top 5 Features Selected: ['Bp', 'Bu', 'Al', 'Su', 'Pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321F710>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.39it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Sg': np.float64(0.5833333333333334), 'Hemo': np.float64(0.5416666666666666), 'Age': np.float64(0.5), 'Pot': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Sc': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Pe': 0.65, 'Rbcc': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Appet': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Hemo': 0.75, 'Age': 0.55, 'Pot': 0.65, 'Wbcc': 0.4, 'Pc': 0.5, 'Dm': 0.8, 'Sc': 1.0, 'Cad': 0.45, 'Sod': 0.65, 'Rbc': 0.55, 'Pcc': 0.4, 'Htn': 0.85, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Appet': 0.028577260665441927, 'Al': 0.030679156908665108, 'Sg': 0.029957522915269395, 'Hemo': 0.029273504273504274, 'Age': 0.028404512489927477, 'Pot': 0.028438886647841874, 'Wbcc': 0.027417840375586856, 'Pc': 0.027650648360030512, 'Dm': 0.028612012987012988, 'Sc': 0.02921395544346364, 'Cad': 0.02694394213381555, 'Sod': 0.027425373134328357, 'Rbc': 0.027051561365286855, 'Pcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Bgr': 0.027056277056277056}
Top 10 Features Selected: ['Bp', 'Bu', 'Al', 'Su', 'Pe', 'Pcv', 'Ba', 'Rbcc', 'Ane', 'Sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345D910>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.37it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Sg': np.float64(0.5833333333333334), 'Hemo': np.float64(0.5416666666666666), 'Age': np.float64(0.5), 'Pot': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Sc': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Pe': 0.65, 'Rbcc': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Appet': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Hemo': 0.75, 'Age': 0.55, 'Pot': 0.65, 'Wbcc': 0.4, 'Pc': 0.5, 'Dm': 0.8, 'Sc': 1.0, 'Cad': 0.45, 'Sod': 0.65, 'Rbc': 0.55, 'Pcc': 0.4, 'Htn': 0.85, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Appet': 0.028577260665441927, 'Al': 0.030679156908665108, 'Sg': 0.029957522915269395, 'Hemo': 0.029273504273504274, 'Age': 0.028404512489927477, 'Pot': 0.028438886647841874, 'Wbcc': 0.027417840375586856, 'Pc': 0.027650648360030512, 'Dm': 0.028612012987012988, 'Sc': 0.02921395544346364, 'Cad': 0.02694394213381555, 'Sod': 0.027425373134328357, 'Rbc': 0.027051561365286855, 'Pcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Bgr': 0.027056277056277056}
Top 15 Features Selected: ['Bp', 'Bu', 'Al', 'Su', 'Pe', 'Pcv', 'Ba', 'Rbcc', 'Ane', 'Sg', 'Hemo', 'Sc', 'Dm', 'Appet', 'Pot']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D7230>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.48it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Pe': 0.875, 'Rbcc': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Ane': 0.75, 'Bu': 0.7083333333333334, 'Appet': 0.6666666666666666, 'Al': 0.625, 'Sg': 0.5833333333333334, 'Hemo': 0.5416666666666666, 'Age': 0.5, 'Pot': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Pc': 0.375, 'Dm': 0.3333333333333333, 'Sc': 0.2916666666666667, 'Cad': 0.25, 'Sod': 0.20833333333333334, 'Rbc': 0.16666666666666666, 'Pcc': 0.125, 'Htn': 0.08333333333333333, 'Bgr': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Rbcc': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Ane': np.float64(0.75), 'Bu': np.float64(0.7083333333333334), 'Appet': np.float64(0.6666666666666666), 'Al': np.float64(0.625), 'Sg': np.float64(0.5833333333333334), 'Hemo': np.float64(0.5416666666666666), 'Age': np.float64(0.5), 'Pot': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Pc': np.float64(0.375), 'Dm': np.float64(0.3333333333333333), 'Sc': np.float64(0.2916666666666667), 'Cad': np.float64(0.25), 'Sod': np.float64(0.20833333333333334), 'Rbc': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Htn': np.float64(0.08333333333333333), 'Bgr': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Pe': 0.65, 'Rbcc': 0.55, 'Pcv': 0.7, 'Ane': 0.7, 'Bu': 0.9, 'Appet': 0.4, 'Al': 1.0, 'Sg': 0.85, 'Hemo': 0.75, 'Age': 0.55, 'Pot': 0.65, 'Wbcc': 0.4, 'Pc': 0.5, 'Dm': 0.8, 'Sc': 1.0, 'Cad': 0.45, 'Sod': 0.65, 'Rbc': 0.55, 'Pcc': 0.4, 'Htn': 0.85, 'Bgr': 0.7}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Pe': 0.03055037313432836, 'Rbcc': 0.030090497737556562, 'Pcv': 0.030303030303030304, 'Ane': 0.03007688828584351, 'Bu': 0.030834914611005692, 'Appet': 0.028577260665441927, 'Al': 0.030679156908665108, 'Sg': 0.029957522915269395, 'Hemo': 0.029273504273504274, 'Age': 0.028404512489927477, 'Pot': 0.028438886647841874, 'Wbcc': 0.027417840375586856, 'Pc': 0.027650648360030512, 'Dm': 0.028612012987012988, 'Sc': 0.02921395544346364, 'Cad': 0.02694394213381555, 'Sod': 0.027425373134328357, 'Rbc': 0.027051561365286855, 'Pcc': 0.026279628993473032, 'Htn': 0.02792120864410021, 'Bgr': 0.027056277056277056}
Top 20 Features Selected: ['Bp', 'Bu', 'Al', 'Su', 'Pe', 'Pcv', 'Ba', 'Rbcc', 'Ane', 'Sg', 'Hemo', 'Sc', 'Dm', 'Appet', 'Pot', 'Age', 'Htn', 'Pc', 'Sod', 'Wbcc']
Run 20/25

100%|██████████| 24/24 [00:07<00:00,  3.40it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345EFF0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Htn': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pe': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Rbcc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Appet': 0.4, 'Bu': 0.9, 'Ane': 0.7, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Pe': 0.65, 'Al': 1.0, 'Wbcc': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Sg': 0.03125763125763126, 'Pot': 0.03007688828584351, 'Bgr': 0.03007688828584351, 'Htn': 0.03057889822595705, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Rbcc': 0.028790389395194696, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Appet': 0.027598020555767037, 'Bu': 0.02946236559139785, 'Ane': 0.028309409888357256, 'Hemo': 0.028371628371628373, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Dm': 0.028125, 'Pe': 0.027271052146674038, 'Al': 0.028588564574170333, 'Wbcc': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 5 Features Selected: ['Bp', 'Sg', 'Pcv', 'Sc', 'Su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112150>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.32it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Htn': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pe': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Rbcc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Appet': 0.4, 'Bu': 0.9, 'Ane': 0.7, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Pe': 0.65, 'Al': 1.0, 'Wbcc': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Sg': 0.03125763125763126, 'Pot': 0.03007688828584351, 'Bgr': 0.03007688828584351, 'Htn': 0.03057889822595705, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Rbcc': 0.028790389395194696, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Appet': 0.027598020555767037, 'Bu': 0.02946236559139785, 'Ane': 0.028309409888357256, 'Hemo': 0.028371628371628373, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Dm': 0.028125, 'Pe': 0.027271052146674038, 'Al': 0.028588564574170333, 'Wbcc': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 10 Features Selected: ['Bp', 'Sg', 'Pcv', 'Sc', 'Su', 'Htn', 'Pot', 'Bgr', 'Ba', 'Bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345E8D0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:08<00:00,  2.92it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Htn': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pe': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Rbcc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Appet': 0.4, 'Bu': 0.9, 'Ane': 0.7, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Pe': 0.65, 'Al': 1.0, 'Wbcc': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Sg': 0.03125763125763126, 'Pot': 0.03007688828584351, 'Bgr': 0.03007688828584351, 'Htn': 0.03057889822595705, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Rbcc': 0.028790389395194696, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Appet': 0.027598020555767037, 'Bu': 0.02946236559139785, 'Ane': 0.028309409888357256, 'Hemo': 0.028371628371628373, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Dm': 0.028125, 'Pe': 0.027271052146674038, 'Al': 0.028588564574170333, 'Wbcc': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 15 Features Selected: ['Bp', 'Sg', 'Pcv', 'Sc', 'Su', 'Htn', 'Pot', 'Bgr', 'Ba', 'Bu', 'Sod', 'Rbcc', 'Al', 'Pc', 'Hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113170>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.47it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Pcv': 0.9166666666666666, 'Ba': 0.875, 'Sg': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Bgr': 0.75, 'Htn': 0.7083333333333334, 'Sc': 0.6666666666666666, 'Sod': 0.625, 'Rbcc': 0.5833333333333334, 'Pc': 0.5416666666666666, 'Pcc': 0.5, 'Appet': 0.4583333333333333, 'Bu': 0.4166666666666667, 'Ane': 0.375, 'Hemo': 0.3333333333333333, 'Rbc': 0.2916666666666667, 'Age': 0.25, 'Dm': 0.20833333333333334, 'Pe': 0.16666666666666666, 'Al': 0.125, 'Wbcc': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Pcv': np.float64(0.9166666666666666), 'Ba': np.float64(0.875), 'Sg': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Bgr': np.float64(0.75), 'Htn': np.float64(0.7083333333333334), 'Sc': np.float64(0.6666666666666666), 'Sod': np.float64(0.625), 'Rbcc': np.float64(0.5833333333333334), 'Pc': np.float64(0.5416666666666666), 'Pcc': np.float64(0.5), 'Appet': np.float64(0.4583333333333333), 'Bu': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Rbc': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Pe': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Pcv': 0.7, 'Ba': 0.4, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Htn': 0.85, 'Sc': 1.0, 'Sod': 0.65, 'Rbcc': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Appet': 0.4, 'Bu': 0.9, 'Ane': 0.7, 'Hemo': 0.75, 'Rbc': 0.55, 'Age': 0.55, 'Dm': 0.8, 'Pe': 0.65, 'Al': 1.0, 'Wbcc': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Pcv': 0.031024531024531024, 'Ba': 0.029709507042253523, 'Sg': 0.03125763125763126, 'Pot': 0.03007688828584351, 'Bgr': 0.03007688828584351, 'Htn': 0.03057889822595705, 'Sc': 0.030886196246139225, 'Sod': 0.029211087420042643, 'Rbcc': 0.028790389395194696, 'Pc': 0.028381642512077296, 'Pcc': 0.027783137179239824, 'Appet': 0.027598020555767037, 'Bu': 0.02946236559139785, 'Ane': 0.028309409888357256, 'Hemo': 0.028371628371628373, 'Rbc': 0.027526395173453996, 'Age': 0.027364110201042444, 'Dm': 0.028125, 'Pe': 0.027271052146674038, 'Al': 0.028588564574170333, 'Wbcc': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 20 Features Selected: ['Bp', 'Sg', 'Pcv', 'Sc', 'Su', 'Htn', 'Pot', 'Bgr', 'Ba', 'Bu', 'Sod', 'Rbcc', 'Al', 'Pc', 'Hemo', 'Ane', 'Dm', 'Pcc', 'Appet', 'Rbc']
Run 21/25

100%|██████████| 24/24 [00:07<00:00,  3.37it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112AB0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.49it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Age': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Dm': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Su': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Bu': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Sg': np.float64(0.20833333333333334), 'Pcc': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Appet': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pe': 0.65, 'Pcv': 0.7, 'Age': 0.55, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Dm': 0.8, 'Bgr': 0.7, 'Su': 0.55, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Sg': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Appet': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pe': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Age': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Dm': 0.029910714285714284, 'Bgr': 0.029236022193768675, 'Su': 0.028594771241830064, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Bu': 0.02928692699490662, 'Hemo': 0.028371628371628373, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Sg': 0.028373015873015873, 'Pcc': 0.0264301860545992, 'Al': 0.028588564574170333, 'Appet': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 5 Features Selected: ['Bp', 'Sc', 'Pot', 'Pe', 'Pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112D50>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.53it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Age': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Dm': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Su': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Bu': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Sg': np.float64(0.20833333333333334), 'Pcc': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Appet': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pe': 0.65, 'Pcv': 0.7, 'Age': 0.55, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Dm': 0.8, 'Bgr': 0.7, 'Su': 0.55, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Sg': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Appet': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pe': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Age': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Dm': 0.029910714285714284, 'Bgr': 0.029236022193768675, 'Su': 0.028594771241830064, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Bu': 0.02928692699490662, 'Hemo': 0.028371628371628373, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Sg': 0.028373015873015873, 'Pcc': 0.0264301860545992, 'Al': 0.028588564574170333, 'Appet': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 10 Features Selected: ['Bp', 'Sc', 'Pot', 'Pe', 'Pcv', 'Ba', 'Dm', 'Age', 'Rbcc', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031124B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Age': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Dm': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Su': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Bu': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Sg': np.float64(0.20833333333333334), 'Pcc': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Appet': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pe': 0.65, 'Pcv': 0.7, 'Age': 0.55, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Dm': 0.8, 'Bgr': 0.7, 'Su': 0.55, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Sg': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Appet': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pe': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Age': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Dm': 0.029910714285714284, 'Bgr': 0.029236022193768675, 'Su': 0.028594771241830064, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Bu': 0.02928692699490662, 'Hemo': 0.028371628371628373, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Sg': 0.028373015873015873, 'Pcc': 0.0264301860545992, 'Al': 0.028588564574170333, 'Appet': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 15 Features Selected: ['Bp', 'Sc', 'Pot', 'Pe', 'Pcv', 'Ba', 'Dm', 'Age', 'Rbcc', 'Sod', 'Bu', 'Bgr', 'Ane', 'Su', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031139B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.47it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pe': 0.875, 'Pcv': 0.8333333333333334, 'Age': 0.7916666666666666, 'Rbcc': 0.75, 'Sc': 0.7083333333333334, 'Sod': 0.6666666666666666, 'Dm': 0.625, 'Bgr': 0.5833333333333334, 'Su': 0.5416666666666666, 'Rbc': 0.5, 'Ane': 0.4583333333333333, 'Wbcc': 0.4166666666666667, 'Bu': 0.375, 'Hemo': 0.3333333333333333, 'Pc': 0.2916666666666667, 'Htn': 0.25, 'Sg': 0.20833333333333334, 'Pcc': 0.16666666666666666, 'Al': 0.125, 'Appet': 0.08333333333333333, 'Cad': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pe': np.float64(0.875), 'Pcv': np.float64(0.8333333333333334), 'Age': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Sc': np.float64(0.7083333333333334), 'Sod': np.float64(0.6666666666666666), 'Dm': np.float64(0.625), 'Bgr': np.float64(0.5833333333333334), 'Su': np.float64(0.5416666666666666), 'Rbc': np.float64(0.5), 'Ane': np.float64(0.4583333333333333), 'Wbcc': np.float64(0.4166666666666667), 'Bu': np.float64(0.375), 'Hemo': np.float64(0.3333333333333333), 'Pc': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Sg': np.float64(0.20833333333333334), 'Pcc': np.float64(0.16666666666666666), 'Al': np.float64(0.125), 'Appet': np.float64(0.08333333333333333), 'Cad': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Pot': 0.65, 'Pe': 0.65, 'Pcv': 0.7, 'Age': 0.55, 'Rbcc': 0.55, 'Sc': 1.0, 'Sod': 0.65, 'Dm': 0.8, 'Bgr': 0.7, 'Su': 0.55, 'Rbc': 0.55, 'Ane': 0.7, 'Wbcc': 0.4, 'Bu': 0.9, 'Hemo': 0.75, 'Pc': 0.5, 'Htn': 0.85, 'Sg': 0.85, 'Pcc': 0.4, 'Al': 1.0, 'Appet': 0.4, 'Cad': 0.45}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Pot': 0.030798389007344232, 'Pe': 0.03055037313432836, 'Pcv': 0.030536130536130537, 'Age': 0.029857397504456328, 'Rbcc': 0.029631255487269532, 'Sc': 0.031099324975891997, 'Sod': 0.029418126757516764, 'Dm': 0.029910714285714284, 'Bgr': 0.029236022193768675, 'Su': 0.028594771241830064, 'Rbc': 0.028404512489927477, 'Ane': 0.028665028665028666, 'Wbcc': 0.027417840375586856, 'Bu': 0.02928692699490662, 'Hemo': 0.028371628371628373, 'Pc': 0.027313266443701224, 'Htn': 0.028531243721117136, 'Sg': 0.028373015873015873, 'Pcc': 0.0264301860545992, 'Al': 0.028588564574170333, 'Appet': 0.026132699813337858, 'Cad': 0.026190476190476188}
Top 20 Features Selected: ['Bp', 'Sc', 'Pot', 'Pe', 'Pcv', 'Ba', 'Dm', 'Age', 'Rbcc', 'Sod', 'Bu', 'Bgr', 'Ane', 'Su', 'Al', 'Htn', 'Rbc', 'Sg', 'Hemo', 'Wbcc']
Run 22/25

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113530>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.40it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Rbcc': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Sod': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Htn': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Bu': np.float64(0.4583333333333333), 'Pe': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Pcc': np.float64(0.2916666666666667), 'Dm': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Cad': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Rbcc': 0.55, 'Pcv': 0.7, 'Sod': 0.65, 'Appet': 0.4, 'Htn': 0.85, 'Ane': 0.7, 'Su': 0.55, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Sc': 1.0, 'Bu': 0.9, 'Pe': 0.65, 'Age': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Dm': 0.8, 'Al': 1.0, 'Cad': 0.45, 'Rbc': 0.55, 'Wbcc': 0.4, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Rbcc': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Sod': 0.030309988518943745, 'Appet': 0.029236022193768675, 'Htn': 0.030798389007344232, 'Ane': 0.029857397504456328, 'Su': 0.02919863597612958, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Bgr': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Bu': 0.02964254577157803, 'Pe': 0.028258706467661692, 'Age': 0.02786377708978328, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Dm': 0.028283227848101264, 'Al': 0.02889344262295082, 'Cad': 0.026631393298059962, 'Rbc': 0.02690100430416069, 'Wbcc': 0.026132699813337858, 'Hemo': 0.02728937728937729}
Top 5 Features Selected: ['Bp', 'Htn', 'Pcv', 'Rbcc', 'Sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B7FAAB0B0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Rbcc': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Sod': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Htn': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Bu': np.float64(0.4583333333333333), 'Pe': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Pcc': np.float64(0.2916666666666667), 'Dm': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Cad': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Rbcc': 0.55, 'Pcv': 0.7, 'Sod': 0.65, 'Appet': 0.4, 'Htn': 0.85, 'Ane': 0.7, 'Su': 0.55, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Sc': 1.0, 'Bu': 0.9, 'Pe': 0.65, 'Age': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Dm': 0.8, 'Al': 1.0, 'Cad': 0.45, 'Rbc': 0.55, 'Wbcc': 0.4, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Rbcc': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Sod': 0.030309988518943745, 'Appet': 0.029236022193768675, 'Htn': 0.030798389007344232, 'Ane': 0.029857397504456328, 'Su': 0.02919863597612958, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Bgr': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Bu': 0.02964254577157803, 'Pe': 0.028258706467661692, 'Age': 0.02786377708978328, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Dm': 0.028283227848101264, 'Al': 0.02889344262295082, 'Cad': 0.026631393298059962, 'Rbc': 0.02690100430416069, 'Wbcc': 0.026132699813337858, 'Hemo': 0.02728937728937729}
Top 10 Features Selected: ['Bp', 'Htn', 'Pcv', 'Rbcc', 'Sod', 'Ba', 'Sg', 'Sc', 'Ane', 'Bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0321FAD0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.34it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Rbcc': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Sod': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Htn': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Bu': np.float64(0.4583333333333333), 'Pe': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Pcc': np.float64(0.2916666666666667), 'Dm': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Cad': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Rbcc': 0.55, 'Pcv': 0.7, 'Sod': 0.65, 'Appet': 0.4, 'Htn': 0.85, 'Ane': 0.7, 'Su': 0.55, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Sc': 1.0, 'Bu': 0.9, 'Pe': 0.65, 'Age': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Dm': 0.8, 'Al': 1.0, 'Cad': 0.45, 'Rbc': 0.55, 'Wbcc': 0.4, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Rbcc': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Sod': 0.030309988518943745, 'Appet': 0.029236022193768675, 'Htn': 0.030798389007344232, 'Ane': 0.029857397504456328, 'Su': 0.02919863597612958, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Bgr': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Bu': 0.02964254577157803, 'Pe': 0.028258706467661692, 'Age': 0.02786377708978328, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Dm': 0.028283227848101264, 'Al': 0.02889344262295082, 'Cad': 0.026631393298059962, 'Rbc': 0.02690100430416069, 'Wbcc': 0.026132699813337858, 'Hemo': 0.02728937728937729}
Top 15 Features Selected: ['Bp', 'Htn', 'Pcv', 'Rbcc', 'Sod', 'Ba', 'Sg', 'Sc', 'Ane', 'Bu', 'Appet', 'Su', 'Bgr', 'Pot', 'Al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03110FB0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.33it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Rbcc': 0.9166666666666666, 'Pcv': 0.875, 'Sod': 0.8333333333333334, 'Appet': 0.7916666666666666, 'Htn': 0.75, 'Ane': 0.7083333333333334, 'Su': 0.6666666666666666, 'Sg': 0.625, 'Pot': 0.5833333333333334, 'Bgr': 0.5416666666666666, 'Sc': 0.5, 'Bu': 0.4583333333333333, 'Pe': 0.4166666666666667, 'Age': 0.375, 'Pc': 0.3333333333333333, 'Pcc': 0.2916666666666667, 'Dm': 0.25, 'Al': 0.20833333333333334, 'Cad': 0.16666666666666666, 'Rbc': 0.125, 'Wbcc': 0.08333333333333333, 'Hemo': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Rbcc': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Sod': np.float64(0.8333333333333334), 'Appet': np.float64(0.7916666666666666), 'Htn': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Su': np.float64(0.6666666666666666), 'Sg': np.float64(0.625), 'Pot': np.float64(0.5833333333333334), 'Bgr': np.float64(0.5416666666666666), 'Sc': np.float64(0.5), 'Bu': np.float64(0.4583333333333333), 'Pe': np.float64(0.4166666666666667), 'Age': np.float64(0.375), 'Pc': np.float64(0.3333333333333333), 'Pcc': np.float64(0.2916666666666667), 'Dm': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Cad': np.float64(0.16666666666666666), 'Rbc': np.float64(0.125), 'Wbcc': np.float64(0.08333333333333333), 'Hemo': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Rbcc': 0.55, 'Pcv': 0.7, 'Sod': 0.65, 'Appet': 0.4, 'Htn': 0.85, 'Ane': 0.7, 'Su': 0.55, 'Sg': 0.85, 'Pot': 0.65, 'Bgr': 0.7, 'Sc': 1.0, 'Bu': 0.9, 'Pe': 0.65, 'Age': 0.55, 'Pc': 0.5, 'Pcc': 0.4, 'Dm': 0.8, 'Al': 1.0, 'Cad': 0.45, 'Rbc': 0.55, 'Wbcc': 0.4, 'Hemo': 0.75}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Rbcc': 0.03057889822595705, 'Pcv': 0.030776515151515152, 'Sod': 0.030309988518943745, 'Appet': 0.029236022193768675, 'Htn': 0.030798389007344232, 'Ane': 0.029857397504456328, 'Su': 0.02919863597612958, 'Sg': 0.030158730158730156, 'Pot': 0.02900988017658188, 'Bgr': 0.02904040404040404, 'Sc': 0.03009207275993712, 'Bu': 0.02964254577157803, 'Pe': 0.028258706467661692, 'Age': 0.02786377708978328, 'Pc': 0.027479766610201392, 'Pcc': 0.02690501986276634, 'Dm': 0.028283227848101264, 'Al': 0.02889344262295082, 'Cad': 0.026631393298059962, 'Rbc': 0.02690100430416069, 'Wbcc': 0.026132699813337858, 'Hemo': 0.02728937728937729}
Top 20 Features Selected: ['Bp', 'Htn', 'Pcv', 'Rbcc', 'Sod', 'Ba', 'Sg', 'Sc', 'Ane', 'Bu', 'Appet', 'Su', 'Bgr', 'Pot', 'Al', 'Dm', 'Pe', 'Age', 'Pc', 'Hemo']
Run 23/25

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03110710>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.45it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Appet': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Rbc': np.float64(0.625), 'Cad': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Al': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Sc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Pc': np.float64(0.08333333333333333), 'Wbcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Bgr': 0.7, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Pe': 0.65, 'Rbc': 0.55, 'Cad': 0.45, 'Sg': 0.85, 'Bu': 0.9, 'Age': 0.55, 'Hemo': 0.75, 'Ane': 0.7, 'Htn': 0.85, 'Al': 1.0, 'Sod': 0.65, 'Sc': 1.0, 'Dm': 0.8, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Appet': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Rbc': 0.028991596638655463, 'Cad': 0.028370221327967807, 'Sg': 0.02976190476190476, 'Bu': 0.029827662395050816, 'Age': 0.02821939586645469, 'Hemo': 0.02871794871794872, 'Ane': 0.028309409888357256, 'Htn': 0.02886002886002886, 'Al': 0.02921395544346364, 'Sod': 0.027583600982429624, 'Sc': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Pcc': 0.026279628993473032, 'Pc': 0.026540946394272742, 'Wbcc': 0.025989268947015427}
Top 5 Features Selected: ['Bp', 'Su', 'Bgr', 'Ba', 'Pot']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03111550>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.52it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Appet': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Rbc': np.float64(0.625), 'Cad': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Al': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Sc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Pc': np.float64(0.08333333333333333), 'Wbcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Bgr': 0.7, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Pe': 0.65, 'Rbc': 0.55, 'Cad': 0.45, 'Sg': 0.85, 'Bu': 0.9, 'Age': 0.55, 'Hemo': 0.75, 'Ane': 0.7, 'Htn': 0.85, 'Al': 1.0, 'Sod': 0.65, 'Sc': 1.0, 'Dm': 0.8, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Appet': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Rbc': 0.028991596638655463, 'Cad': 0.028370221327967807, 'Sg': 0.02976190476190476, 'Bu': 0.029827662395050816, 'Age': 0.02821939586645469, 'Hemo': 0.02871794871794872, 'Ane': 0.028309409888357256, 'Htn': 0.02886002886002886, 'Al': 0.02921395544346364, 'Sod': 0.027583600982429624, 'Sc': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Pcc': 0.026279628993473032, 'Pc': 0.026540946394272742, 'Wbcc': 0.025989268947015427}
Top 10 Features Selected: ['Bp', 'Su', 'Bgr', 'Ba', 'Pot', 'Pcv', 'Bu', 'Sg', 'Appet', 'Pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113110>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Appet': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Rbc': np.float64(0.625), 'Cad': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Al': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Sc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Pc': np.float64(0.08333333333333333), 'Wbcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Bgr': 0.7, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Pe': 0.65, 'Rbc': 0.55, 'Cad': 0.45, 'Sg': 0.85, 'Bu': 0.9, 'Age': 0.55, 'Hemo': 0.75, 'Ane': 0.7, 'Htn': 0.85, 'Al': 1.0, 'Sod': 0.65, 'Sc': 1.0, 'Dm': 0.8, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Appet': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Rbc': 0.028991596638655463, 'Cad': 0.028370221327967807, 'Sg': 0.02976190476190476, 'Bu': 0.029827662395050816, 'Age': 0.02821939586645469, 'Hemo': 0.02871794871794872, 'Ane': 0.028309409888357256, 'Htn': 0.02886002886002886, 'Al': 0.02921395544346364, 'Sod': 0.027583600982429624, 'Sc': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Pcc': 0.026279628993473032, 'Pc': 0.026540946394272742, 'Wbcc': 0.025989268947015427}
Top 15 Features Selected: ['Bp', 'Su', 'Bgr', 'Ba', 'Pot', 'Pcv', 'Bu', 'Sg', 'Appet', 'Pe', 'Rbcc', 'Al', 'Rbc', 'Sc', 'Htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B0345D610>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.50it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Ba': 0.9583333333333334, 'Su': 0.9166666666666666, 'Appet': 0.875, 'Bgr': 0.8333333333333334, 'Pot': 0.7916666666666666, 'Pcv': 0.75, 'Rbcc': 0.7083333333333334, 'Pe': 0.6666666666666666, 'Rbc': 0.625, 'Cad': 0.5833333333333334, 'Sg': 0.5416666666666666, 'Bu': 0.5, 'Age': 0.4583333333333333, 'Hemo': 0.4166666666666667, 'Ane': 0.375, 'Htn': 0.3333333333333333, 'Al': 0.2916666666666667, 'Sod': 0.25, 'Sc': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Pcc': 0.125, 'Pc': 0.08333333333333333, 'Wbcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Ba': np.float64(0.9583333333333334), 'Su': np.float64(0.9166666666666666), 'Appet': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Pot': np.float64(0.7916666666666666), 'Pcv': np.float64(0.75), 'Rbcc': np.float64(0.7083333333333334), 'Pe': np.float64(0.6666666666666666), 'Rbc': np.float64(0.625), 'Cad': np.float64(0.5833333333333334), 'Sg': np.float64(0.5416666666666666), 'Bu': np.float64(0.5), 'Age': np.float64(0.4583333333333333), 'Hemo': np.float64(0.4166666666666667), 'Ane': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Al': np.float64(0.2916666666666667), 'Sod': np.float64(0.25), 'Sc': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Pcc': np.float64(0.125), 'Pc': np.float64(0.08333333333333333), 'Wbcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Ba': 0.4, 'Su': 0.55, 'Appet': 0.4, 'Bgr': 0.7, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Pe': 0.65, 'Rbc': 0.55, 'Cad': 0.45, 'Sg': 0.85, 'Bu': 0.9, 'Age': 0.55, 'Hemo': 0.75, 'Ane': 0.7, 'Htn': 0.85, 'Al': 1.0, 'Sod': 0.65, 'Sc': 1.0, 'Dm': 0.8, 'Pcc': 0.4, 'Pc': 0.5, 'Wbcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Ba': 0.03021353930031804, 'Su': 0.03057889822595705, 'Appet': 0.029709507042253523, 'Bgr': 0.030536130536130537, 'Pot': 0.03007688828584351, 'Pcv': 0.03007688828584351, 'Rbcc': 0.029411764705882353, 'Pe': 0.029418126757516764, 'Rbc': 0.028991596638655463, 'Cad': 0.028370221327967807, 'Sg': 0.02976190476190476, 'Bu': 0.029827662395050816, 'Age': 0.02821939586645469, 'Hemo': 0.02871794871794872, 'Ane': 0.028309409888357256, 'Htn': 0.02886002886002886, 'Al': 0.02921395544346364, 'Sod': 0.027583600982429624, 'Sc': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Pcc': 0.026279628993473032, 'Pc': 0.026540946394272742, 'Wbcc': 0.025989268947015427}
Top 20 Features Selected: ['Bp', 'Su', 'Bgr', 'Ba', 'Pot', 'Pcv', 'Bu', 'Sg', 'Appet', 'Pe', 'Rbcc', 'Al', 'Rbc', 'Sc', 'Htn', 'Hemo', 'Cad', 'Ane', 'Age', 'Dm']
Run 24/25

100%|██████████| 24/24 [00:06<00:00,  3.43it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113A70>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.46it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Cad': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Appet': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pot': 0.65, 'Pcv': 0.7, 'Bgr': 0.7, 'Su': 0.55, 'Bu': 0.9, 'Cad': 0.45, 'Rbcc': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Ane': 0.7, 'Pc': 0.5, 'Wbcc': 0.4, 'Sg': 0.85, 'Ba': 0.4, 'Htn': 0.85, 'Appet': 0.4, 'Age': 0.55, 'Al': 1.0, 'Dm': 0.8, 'Hemo': 0.75, 'Rbc': 0.55, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Bu': 0.031054405392392875, 'Cad': 0.028991596638655463, 'Rbcc': 0.02919863597612958, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Ane': 0.02904040404040404, 'Pc': 0.02819138376017471, 'Wbcc': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Ba': 0.027242401779095628, 'Htn': 0.02886002886002886, 'Appet': 0.02690501986276634, 'Age': 0.027364110201042444, 'Al': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Hemo': 0.027579737335834898, 'Rbc': 0.026754075124025514, 'Pcc': 0.025989268947015427}
Top 5 Features Selected: ['Sc', 'Bp', 'Bu', 'Pot', 'Pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B031102F0>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.46it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Cad': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Appet': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pot': 0.65, 'Pcv': 0.7, 'Bgr': 0.7, 'Su': 0.55, 'Bu': 0.9, 'Cad': 0.45, 'Rbcc': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Ane': 0.7, 'Pc': 0.5, 'Wbcc': 0.4, 'Sg': 0.85, 'Ba': 0.4, 'Htn': 0.85, 'Appet': 0.4, 'Age': 0.55, 'Al': 1.0, 'Dm': 0.8, 'Hemo': 0.75, 'Rbc': 0.55, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Bu': 0.031054405392392875, 'Cad': 0.028991596638655463, 'Rbcc': 0.02919863597612958, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Ane': 0.02904040404040404, 'Pc': 0.02819138376017471, 'Wbcc': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Ba': 0.027242401779095628, 'Htn': 0.02886002886002886, 'Appet': 0.02690501986276634, 'Age': 0.027364110201042444, 'Al': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Hemo': 0.027579737335834898, 'Rbc': 0.026754075124025514, 'Pcc': 0.025989268947015427}
Top 10 Features Selected: ['Sc', 'Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Pe', 'Sg', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03113290>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.42it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Cad': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Appet': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pot': 0.65, 'Pcv': 0.7, 'Bgr': 0.7, 'Su': 0.55, 'Bu': 0.9, 'Cad': 0.45, 'Rbcc': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Ane': 0.7, 'Pc': 0.5, 'Wbcc': 0.4, 'Sg': 0.85, 'Ba': 0.4, 'Htn': 0.85, 'Appet': 0.4, 'Age': 0.55, 'Al': 1.0, 'Dm': 0.8, 'Hemo': 0.75, 'Rbc': 0.55, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Bu': 0.031054405392392875, 'Cad': 0.028991596638655463, 'Rbcc': 0.02919863597612958, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Ane': 0.02904040404040404, 'Pc': 0.02819138376017471, 'Wbcc': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Ba': 0.027242401779095628, 'Htn': 0.02886002886002886, 'Appet': 0.02690501986276634, 'Age': 0.027364110201042444, 'Al': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Hemo': 0.027579737335834898, 'Rbc': 0.026754075124025514, 'Pcc': 0.025989268947015427}
Top 15 Features Selected: ['Sc', 'Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Pe', 'Sg', 'Rbcc', 'Ane', 'Sod', 'Cad', 'Al', 'Htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03112F30>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.24it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Sc': 0.9583333333333334, 'Pot': 0.9166666666666666, 'Pcv': 0.875, 'Bgr': 0.8333333333333334, 'Su': 0.7916666666666666, 'Bu': 0.75, 'Cad': 0.7083333333333334, 'Rbcc': 0.6666666666666666, 'Pe': 0.625, 'Sod': 0.5833333333333334, 'Ane': 0.5416666666666666, 'Pc': 0.5, 'Wbcc': 0.4583333333333333, 'Sg': 0.4166666666666667, 'Ba': 0.375, 'Htn': 0.3333333333333333, 'Appet': 0.2916666666666667, 'Age': 0.25, 'Al': 0.20833333333333334, 'Dm': 0.16666666666666666, 'Hemo': 0.125, 'Rbc': 0.08333333333333333, 'Pcc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Sc': np.float64(0.9583333333333334), 'Pot': np.float64(0.9166666666666666), 'Pcv': np.float64(0.875), 'Bgr': np.float64(0.8333333333333334), 'Su': np.float64(0.7916666666666666), 'Bu': np.float64(0.75), 'Cad': np.float64(0.7083333333333334), 'Rbcc': np.float64(0.6666666666666666), 'Pe': np.float64(0.625), 'Sod': np.float64(0.5833333333333334), 'Ane': np.float64(0.5416666666666666), 'Pc': np.float64(0.5), 'Wbcc': np.float64(0.4583333333333333), 'Sg': np.float64(0.4166666666666667), 'Ba': np.float64(0.375), 'Htn': np.float64(0.3333333333333333), 'Appet': np.float64(0.2916666666666667), 'Age': np.float64(0.25), 'Al': np.float64(0.20833333333333334), 'Dm': np.float64(0.16666666666666666), 'Hemo': np.float64(0.125), 'Rbc': np.float64(0.08333333333333333), 'Pcc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Sc': 1.0, 'Pot': 0.65, 'Pcv': 0.7, 'Bgr': 0.7, 'Su': 0.55, 'Bu': 0.9, 'Cad': 0.45, 'Rbcc': 0.55, 'Pe': 0.65, 'Sod': 0.65, 'Ane': 0.7, 'Pc': 0.5, 'Wbcc': 0.4, 'Sg': 0.85, 'Ba': 0.4, 'Htn': 0.85, 'Appet': 0.4, 'Age': 0.55, 'Al': 1.0, 'Dm': 0.8, 'Hemo': 0.75, 'Rbc': 0.55, 'Pcc': 0.4}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Sc': 0.03252247488101534, 'Pot': 0.030798389007344232, 'Pcv': 0.030776515151515152, 'Bgr': 0.030536130536130537, 'Su': 0.029857397504456328, 'Bu': 0.031054405392392875, 'Cad': 0.028991596638655463, 'Rbcc': 0.02919863597612958, 'Pe': 0.029211087420042643, 'Sod': 0.02900988017658188, 'Ane': 0.02904040404040404, 'Pc': 0.02819138376017471, 'Wbcc': 0.027598020555767037, 'Sg': 0.029206349206349208, 'Ba': 0.027242401779095628, 'Htn': 0.02886002886002886, 'Appet': 0.02690501986276634, 'Age': 0.027364110201042444, 'Al': 0.02889344262295082, 'Dm': 0.02797067901234568, 'Hemo': 0.027579737335834898, 'Rbc': 0.026754075124025514, 'Pcc': 0.025989268947015427}
Top 20 Features Selected: ['Sc', 'Bp', 'Bu', 'Pot', 'Pcv', 'Bgr', 'Su', 'Pe', 'Sg', 'Rbcc', 'Ane', 'Sod', 'Cad', 'Al', 'Htn', 'Pc', 'Dm', 'Wbcc', 'Hemo', 'Age']
Run 25/25

100%|██████████| 24/24 [00:08<00:00,  2.89it/s]

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03111790>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:08<00:00,  2.70it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Pot': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Ba': np.float64(0.6666666666666666), 'Sc': np.float64(0.625), 'Al': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Pc': np.float64(0.125), 'Pcc': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Bu': 0.9, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Ane': 0.7, 'Ba': 0.4, 'Sc': 1.0, 'Al': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Hemo': 0.75, 'Age': 0.55, 'Pe': 0.65, 'Wbcc': 0.4, 'Cad': 0.45, 'Htn': 0.85, 'Dm': 0.8, 'Sod': 0.65, 'Pc': 0.5, 'Pcc': 0.4, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Bu': 0.031754032258064516, 'Pot': 0.030309988518943745, 'Pcv': 0.030303030303030304, 'Rbcc': 0.029631255487269532, 'Ane': 0.029857397504456328, 'Ba': 0.028577260665441927, 'Sc': 0.030679156908665108, 'Al': 0.03047794966520434, 'Appet': 0.02797339593114241, 'Bgr': 0.028850145288501453, 'Hemo': 0.0288981288981289, 'Age': 0.02803921568627451, 'Pe': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Cad': 0.027106227106227107, 'Htn': 0.028531243721117136, 'Dm': 0.028125, 'Sod': 0.027271052146674038, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Rbc': 0.02661064425770308}
Top 5 Features Selected: ['Bp', 'Bu', 'Sg', 'Su', 'Sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03111F10>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:08<00:00,  2.71it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Pot': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Ba': np.float64(0.6666666666666666), 'Sc': np.float64(0.625), 'Al': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Pc': np.float64(0.125), 'Pcc': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Bu': 0.9, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Ane': 0.7, 'Ba': 0.4, 'Sc': 1.0, 'Al': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Hemo': 0.75, 'Age': 0.55, 'Pe': 0.65, 'Wbcc': 0.4, 'Cad': 0.45, 'Htn': 0.85, 'Dm': 0.8, 'Sod': 0.65, 'Pc': 0.5, 'Pcc': 0.4, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Bu': 0.031754032258064516, 'Pot': 0.030309988518943745, 'Pcv': 0.030303030303030304, 'Rbcc': 0.029631255487269532, 'Ane': 0.029857397504456328, 'Ba': 0.028577260665441927, 'Sc': 0.030679156908665108, 'Al': 0.03047794966520434, 'Appet': 0.02797339593114241, 'Bgr': 0.028850145288501453, 'Hemo': 0.0288981288981289, 'Age': 0.02803921568627451, 'Pe': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Cad': 0.027106227106227107, 'Htn': 0.028531243721117136, 'Dm': 0.028125, 'Sod': 0.027271052146674038, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Rbc': 0.02661064425770308}
Top 10 Features Selected: ['Bp', 'Bu', 'Sg', 'Su', 'Sc', 'Al', 'Pot', 'Pcv', 'Ane', 'Rbcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B032D6150>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:07<00:00,  3.28it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Pot': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Ba': np.float64(0.6666666666666666), 'Sc': np.float64(0.625), 'Al': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Pc': np.float64(0.125), 'Pcc': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Bu': 0.9, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Ane': 0.7, 'Ba': 0.4, 'Sc': 1.0, 'Al': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Hemo': 0.75, 'Age': 0.55, 'Pe': 0.65, 'Wbcc': 0.4, 'Cad': 0.45, 'Htn': 0.85, 'Dm': 0.8, 'Sod': 0.65, 'Pc': 0.5, 'Pcc': 0.4, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Bu': 0.031754032258064516, 'Pot': 0.030309988518943745, 'Pcv': 0.030303030303030304, 'Rbcc': 0.029631255487269532, 'Ane': 0.029857397504456328, 'Ba': 0.028577260665441927, 'Sc': 0.030679156908665108, 'Al': 0.03047794966520434, 'Appet': 0.02797339593114241, 'Bgr': 0.028850145288501453, 'Hemo': 0.0288981288981289, 'Age': 0.02803921568627451, 'Pe': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Cad': 0.027106227106227107, 'Htn': 0.028531243721117136, 'Dm': 0.028125, 'Sod': 0.027271052146674038, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Rbc': 0.02661064425770308}
Top 15 Features Selected: ['Bp', 'Bu', 'Sg', 'Su', 'Sc', 'Al', 'Pot', 'Pcv', 'Ane', 'Rbcc', 'Hemo', 'Bgr', 'Ba', 'Htn', 'Dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019B03110890>
DODA Pipeline Started
Running: mRMR

100%|██████████| 24/24 [00:06<00:00,  3.51it/s]

Operator Scores:
{'mRMR_1': {'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'Bp': 1.0, 'Su': 0.9583333333333334, 'Sg': 0.9166666666666666, 'Bu': 0.875, 'Pot': 0.8333333333333334, 'Pcv': 0.7916666666666666, 'Rbcc': 0.75, 'Ane': 0.7083333333333334, 'Ba': 0.6666666666666666, 'Sc': 0.625, 'Al': 0.5833333333333334, 'Appet': 0.5416666666666666, 'Bgr': 0.5, 'Hemo': 0.4583333333333333, 'Age': 0.4166666666666667, 'Pe': 0.375, 'Wbcc': 0.3333333333333333, 'Cad': 0.2916666666666667, 'Htn': 0.25, 'Dm': 0.20833333333333334, 'Sod': 0.16666666666666666, 'Pc': 0.125, 'Pcc': 0.08333333333333333, 'Rbc': 0.041666666666666664}

Normalized Mathematical Scores
{'Bp': np.float64(1.0), 'Su': np.float64(0.9583333333333334), 'Sg': np.float64(0.9166666666666666), 'Bu': np.float64(0.875), 'Pot': np.float64(0.8333333333333334), 'Pcv': np.float64(0.7916666666666666), 'Rbcc': np.float64(0.75), 'Ane': np.float64(0.7083333333333334), 'Ba': np.float64(0.6666666666666666), 'Sc': np.float64(0.625), 'Al': np.float64(0.5833333333333334), 'Appet': np.float64(0.5416666666666666), 'Bgr': np.float64(0.5), 'Hemo': np.float64(0.4583333333333333), 'Age': np.float64(0.4166666666666667), 'Pe': np.float64(0.375), 'Wbcc': np.float64(0.3333333333333333), 'Cad': np.float64(0.2916666666666667), 'Htn': np.float64(0.25), 'Dm': np.float64(0.20833333333333334), 'Sod': np.float64(0.16666666666666666), 'Pc': np.float64(0.125), 'Pcc': np.float64(0.08333333333333333), 'Rbc': np.float64(0.041666666666666664)}

Clinical Weights
{'Bp': 0.8, 'Su': 0.55, 'Sg': 0.85, 'Bu': 0.9, 'Pot': 0.65, 'Pcv': 0.7, 'Rbcc': 0.55, 'Ane': 0.7, 'Ba': 0.4, 'Sc': 1.0, 'Al': 1.0, 'Appet': 0.4, 'Bgr': 0.7, 'Hemo': 0.75, 'Age': 0.55, 'Pe': 0.65, 'Wbcc': 0.4, 'Cad': 0.45, 'Htn': 0.85, 'Dm': 0.8, 'Sod': 0.65, 'Pc': 0.5, 'Pcc': 0.4, 'Rbc': 0.55}

Final DODA Scores
{'Bp': 0.032018442622950824, 'Su': 0.030834914611005692, 'Sg': 0.031746031746031744, 'Bu': 0.031754032258064516, 'Pot': 0.030309988518943745, 'Pcv': 0.030303030303030304, 'Rbcc': 0.029631255487269532, 'Ane': 0.029857397504456328, 'Ba': 0.028577260665441927, 'Sc': 0.030679156908665108, 'Al': 0.03047794966520434, 'Appet': 0.02797339593114241, 'Bgr': 0.028850145288501453, 'Hemo': 0.0288981288981289, 'Age': 0.02803921568627451, 'Pe': 0.028083267871170464, 'Wbcc': 0.027071520029266508, 'Cad': 0.027106227106227107, 'Htn': 0.028531243721117136, 'Dm': 0.028125, 'Sod': 0.027271052146674038, 'Pc': 0.026687875574407917, 'Pcc': 0.026132699813337858, 'Rbc': 0.02661064425770308}
Top 20 Features Selected: ['Bp', 'Bu', 'Sg', 'Su', 'Sc', 'Al', 'Pot', 'Pcv', 'Ane', 'Rbcc', 'Hemo', 'Bgr', 'Ba', 'Htn', 'Dm', 'Pe', 'Age', 'Appet', 'Sod', 'Cad']
Expected repeated-CV rows: 600
Actual repeated-CV rows:   600

,Run,Method,Top_K,Model,Selected_Features,Accuracy,Precision,Recall,F1,ROC_AUC
0,1,mRMR,5,Logistic Regression,"Bp, Ba, Sg, Pot, Hemo",0.4899,0.5000,0.5347,0.5167,0.5135
1,1,mRMR,5,Random Forest,"Bp, Ba, Sg, Pot, Hemo",0.4798,0.4907,0.5248,0.5072,0.5059
2,1,mRMR,5,XGBoost,"Bp, Ba, Sg, Pot, Hemo",0.5505,0.5556,0.5941,0.5742,0.5326
3,1,DODA,5,Logistic Regression,"Bp, Sg, Hemo, Pot, Sc",0.5051,0.5146,0.5248,0.5196,0.5076
4,1,DODA,5,Random Forest,"Bp, Sg, Hemo, Pot, Sc",0.5354,0.5455,0.5347,0.5400,0.5405
...,...,...,...,...,...,...,...,...,...,...
595,25,mRMR,20,Random Forest,"Bp, Su, Sg, Bu, Pot, Pcv, Rbcc, Ane, Ba, Sc, A...",0.5025,0.5133,0.5743,0.5421,0.5016
596,25,mRMR,20,XGBoost,"Bp, Su, Sg, Bu, Pot, Pcv, Rbcc, Ane, Ba, Sc, A...",0.5127,0.5225,0.5743,0.5472,0.5132
597,25,DODA,20,Logistic Regression,"Bp, Bu, Sg, Su, Sc, Al, Pot, Pcv, Ane, Rbcc, H...",0.5381,0.5424,0.6337,0.5845,0.5154
598,25,DODA,20,Random Forest,"Bp, Bu, Sg, Su, Sc, Al, Pot, Pcv, Ane, Rbcc, H...",0.5381,0.5463,0.5842,0.5646,0.5283
599,25,DODA,20,XGBoost,"Bp, Bu, Sg, Su, Sc, Al, Pot, Pcv, Ane, Rbcc, H...",0.5178,0.5300,0.5248,0.5274,0.5383

In [29]:
# =============================================================================
# STEP 26: CV PERFORMANCE SUMMARY
# =============================================================================

cv_summary_df = (
    cv_results_df
    .groupby(["Method", "Top_K", "Model"])
    [["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]]
    .agg(["mean", "std"])
    .reset_index()
)

cv_summary_df.columns = [
    "Method", "Top_K", "Model",
    "Accuracy_Mean", "Accuracy_STD",
    "Precision_Mean", "Precision_STD",
    "Recall_Mean", "Recall_STD",
    "F1_Mean", "F1_STD",
    "ROC_AUC_Mean", "ROC_AUC_STD"
]

display(cv_summary_df.round(4))

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,DODA,5,Logistic Regression,0.5129,0.0362,0.5228,0.0319,0.5768,0.0559,0.5478,0.0397,0.5156,0.0376
1,DODA,5,Random Forest,0.5091,0.0365,0.5207,0.0367,0.5333,0.0612,0.5260,0.0449,0.4965,0.0442
2,DODA,5,XGBoost,0.5044,0.0362,0.5160,0.0347,0.5301,0.0595,0.5223,0.0445,0.5036,0.0433
3,DODA,10,Logistic Regression,0.5180,0.0292,0.5280,0.0260,0.5708,0.0450,0.5481,0.0318,0.5203,0.0359
4,DODA,10,Random Forest,0.4970,0.0378,0.5104,0.0368,0.5278,0.0441,0.5182,0.0352,0.4963,0.0426
5,DODA,10,XGBoost,0.5012,0.0347,0.5133,0.0333,0.5302,0.0499,0.5211,0.0390,0.5011,0.0413
6,DODA,15,Logistic Regression,0.5206,0.0332,0.5309,0.0303,0.5633,0.0455,0.5463,0.0351,0.5239,0.0363
7,DODA,15,Random Forest,0.5045,0.0283,0.5173,0.0269,0.5357,0.0345,0.5258,0.0255,0.5108,0.0378
8,DODA,15,XGBoost,0.5126,0.0390,0.5242,0.0354,0.5393,0.0519,0.5312,0.0413,0.5158,0.0460
9,DODA,20,Logistic Regression,0.5180,0.0311,0.5287,0.0296,0.5598,0.0468,0.5433,0.0342,0.5217,0.0346
10,DODA,20,Random Forest,0.5287,0.0362,0.5381,0.0312,0.5661,0.0601,0.5511,0.0427,0.5311,0.0365
11,DODA,20,XGBoost,0.5291,0.0325,0.5396,0.0292,0.5577,0.0537,0.5479,0.0374,0.5369,0.0396
12,mRMR,5,Logistic Regression,0.5170,0.0335,0.5261,0.0294,0.5799,0.0560,0.5512,0.0393,0.5203,0.0426
13,mRMR,5,Random Forest,0.5020,0.0447,0.5144,0.0438,0.5242,0.0560,0.5187,0.0474,0.5045,0.0490
14,mRMR,5,XGBoost,0.5099,0.0376,0.5211,0.0357,0.5428,0.0612,0.5309,0.0450,0.4995,0.0488
15,mRMR,10,Logistic Regression,0.5119,0.0309,0.5226,0.0279,0.5602,0.0468,0.5403,0.0341,0.5184,0.0343
16,mRMR,10,Random Forest,0.4972,0.0339,0.5097,0.0319,0.5203,0.0497,0.5144,0.0379,0.4919,0.0432
17,mRMR,10,XGBoost,0.4964,0.0373,0.5089,0.0353,0.5251,0.0506,0.5163,0.0401,0.4974,0.0433
18,mRMR,15,Logistic Regression,0.5156,0.0286,0.5261,0.0261,0.5586,0.0477,0.5414,0.0337,0.5214,0.0352
19,mRMR,15,Random Forest,0.4964,0.0300,0.5087,0.0279,0.5294,0.0491,0.5182,0.0356,0.5032,0.0397
20,mRMR,15,XGBoost,0.5045,0.0346,0.5170,0.0327,0.5325,0.0443,0.5241,0.0344,0.5100,0.0427
21,mRMR,20,Logistic Regression,0.5168,0.0327,0.5274,0.0305,0.5586,0.0499,0.5420,0.0365,0.5208,0.0340
22,mRMR,20,Random Forest,0.5140,0.0318,0.5249,0.0283,0.5542,0.0520,0.5385,0.0356,0.5251,0.0316
23,mRMR,20,XGBoost,0.5249,0.0373,0.5359,0.0351,0.5610,0.0472,0.5475,0.0363,0.5334,0.0421

In [30]:
# =============================================================================
# STEP 24: SAVE REPEATED-CV RESULTS
# =============================================================================

cv_dir = Path("../../../results/kidney_disease/cv")
cv_dir.mkdir(parents=True, exist_ok=True)

cv_results_df.to_csv(
    cv_dir / "mrmr_vs_doda_5x5_repeated_cv_results.csv",
    index=False
)

cv_summary_df.to_csv(
    cv_dir / "mrmr_vs_doda_5x5_repeated_cv_summary.csv",
    index=False
)

print(f"Saved to: {cv_dir.resolve()}")

Saved to: C:\Users\johnm\msc_research\results\kidney_disease\cv

# 4. Feature-Selection Stability, Rank/Set Change, and Statistical Comparison

Two different concepts are reported:

- **Feature-set change:** whether the Top-K membership changes.
- **Rank change:** whether feature ordering changes even when membership is retained.

Jaccard similarity evaluates set overlap, so it does not measure ordering. The fixed-split DODA rank comparison is used to inspect ordering changes.

In [31]:
# =============================================================================
# STEP 28: FEATURE-SET COMPARISON ACROSS THE 25 CV RUNS
# =============================================================================

feature_comparison_rows = []

for run_id in range(1, 26):

    for top_k in TOP_K_VALUES:

        mrmr_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "mRMR") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        doda_row = cv_results_df[
            (cv_results_df["Run"] == run_id) &
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k)
        ].iloc[0]

        mrmr_set = set(
            mrmr_row["Selected_Features"].split(", ")
        )
        doda_set = set(
            doda_row["Selected_Features"].split(", ")
        )

        overlap = len(mrmr_set & doda_set)
        union = len(mrmr_set | doda_set)

        feature_comparison_rows.append({
            "Run": run_id,
            "Top_K": top_k,
            "Same_Feature_Set": mrmr_set == doda_set,
            "Overlap_Count": overlap,
            "Jaccard": overlap / union,
            "Features_Changed": top_k - overlap
        })

feature_comparison_df = pd.DataFrame(
    feature_comparison_rows
)

display(
    feature_comparison_df
    .groupby("Top_K")
    [["Same_Feature_Set", "Overlap_Count", "Jaccard", "Features_Changed"]]
    .agg(["mean", "std"])
    .round(4)
)

      Same_Feature_Set         Overlap_Count         Jaccard          \
                  mean     std          mean     std    mean     std
Top_K
5                 0.04  0.2000          3.72  0.6137  0.6062  0.1491
10                0.08  0.2769          8.68  0.6904  0.7731  0.1075
15                0.04  0.2000         13.36  0.7000  0.8060  0.0768
20                0.04  0.2000         18.36  0.9074  0.8515  0.0764

      Features_Changed
                  mean     std
Top_K
5                 1.28  0.6137
10                1.32  0.6904
15                1.64  0.7000
20                1.64  0.9074

In [32]:
# =============================================================================
# STEP 29: FEATURE-SELECTION STABILITY
# =============================================================================

from itertools import combinations

stability_rows = []

for method in ["mRMR", "DODA"]:

    for top_k in TOP_K_VALUES:

        subset = cv_results_df[
            (cv_results_df["Method"] == method) &
            (cv_results_df["Top_K"] == top_k)
        ]

        # One feature set per run; model does not affect selection.
        run_sets = {}

        for run_id in range(1, 26):
            row = subset[
                subset["Run"] == run_id
            ].iloc[0]

            run_sets[run_id] = set(
                row["Selected_Features"].split(", ")
            )

        pairwise_jaccards = []

        for a, b in combinations(range(1, 26), 2):

            set_a = run_sets[a]
            set_b = run_sets[b]

            pairwise_jaccards.append(
                len(set_a & set_b) / len(set_a | set_b)
            )

        stability_rows.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Jaccard": np.mean(pairwise_jaccards),
            "SD_Jaccard": np.std(pairwise_jaccards, ddof=1),
            "Min_Jaccard": np.min(pairwise_jaccards),
            "Max_Jaccard": np.max(pairwise_jaccards)
        })

stability_df = pd.DataFrame(stability_rows)

display(stability_df.round(4))

  Method  Top_K  Mean_Jaccard  SD_Jaccard  Min_Jaccard  Max_Jaccard
0   mRMR      5        0.4062      0.1711       0.1111       1.0000
1   mRMR     10        0.4775      0.1215       0.2500       0.8182
2   mRMR     15        0.6147      0.0981       0.4286       1.0000
3   mRMR     20        0.7599      0.0622       0.6667       0.9048
4   DODA      5        0.3482      0.1589       0.1111       1.0000
5   DODA     10        0.5214      0.1222       0.2500       0.8182
6   DODA     15        0.6663      0.0976       0.4286       0.8750
7   DODA     20        0.8227      0.0687       0.6667       1.0000

## 4.1 Additional Feature-Selection Stability Analyses

The 25 repeated-CV runs are used to quantify selection frequency, chance-adjusted stability, and direct mRMR–DODA feature-set agreement.

In [33]:
# =============================================================================
# STEP 30: FEATURE SELECTION FREQUENCY
# =============================================================================
frequency_rows = []
for method in ["mRMR", "DODA"]:
    for top_k in TOP_K_VALUES:
        subset = cv_results_df[(cv_results_df["Method"] == method) & (cv_results_df["Top_K"] == top_k)]
        counts = {feature: 0 for feature in X.columns}
        for run_id in sorted(subset["Run"].unique()):
            row = subset[subset["Run"] == run_id].iloc[0]
            for feature in row["Selected_Features"].split(", "):
                counts[feature] += 1
        for feature, count in counts.items():
            frequency_rows.append({
                "Method": method, "Top_K": top_k, "Feature": feature,
                "Selection_Count": count,
                "Selection_Frequency": count / (N_SPLITS * N_REPEATS)
            })
feature_frequency_df = pd.DataFrame(frequency_rows)

display(
    feature_frequency_df.sort_values(
        ["Method", "Top_K", "Selection_Frequency", "Feature"],
        ascending=[True, True, False, True]
    ).groupby(["Method", "Top_K"], group_keys=False).head(10).round(4)
)

    Method  Top_K Feature  Selection_Count  Selection_Frequency
97    DODA      5      Bp               25                 1.00
106   DODA      5      Bu               13                 0.52
111   DODA      5     Pcv               13                 0.52
109   DODA      5     Pot               12                 0.48
107   DODA      5      Sc               12                 0.48
..     ...    ...     ...              ...                  ...
76    mRMR     20      Su               25                 1.00
95    mRMR     20     Ane               24                 0.96
93    mRMR     20   Appet               24                 0.96
94    mRMR     20      Pe               24                 0.96
83    mRMR     20      Sc               24                 0.96

[80 rows x 5 columns]

In [34]:
# =============================================================================
# STEP 31: KUNCHEVA INDEX
# =============================================================================
from itertools import combinations
N_FEATURES = X.shape[1]
kuncheva_rows = []

for method in ["mRMR", "DODA"]:
    for top_k in TOP_K_VALUES:
        subset = cv_results_df[(cv_results_df["Method"] == method) & (cv_results_df["Top_K"] == top_k)]
        run_sets = {}
        for run_id in sorted(subset["Run"].unique()):
            row = subset[subset["Run"] == run_id].iloc[0]
            run_sets[run_id] = set(row["Selected_Features"].split(", "))

        for run_a, run_b in combinations(sorted(run_sets), 2):
            intersection = len(run_sets[run_a] & run_sets[run_b])
            denominator = top_k * (N_FEATURES - top_k)
            value = np.nan if denominator == 0 else ((intersection * N_FEATURES) - (top_k ** 2)) / denominator
            kuncheva_rows.append({
                "Method": method, "Top_K": top_k, "Run_A": run_a, "Run_B": run_b,
                "Intersection": intersection, "Kuncheva_Index": value
            })

kuncheva_df = pd.DataFrame(kuncheva_rows)
kuncheva_summary_df = (
    kuncheva_df.groupby(["Method", "Top_K"])["Kuncheva_Index"]
    .agg(Mean_Kuncheva="mean", Std_Kuncheva="std", Min_Kuncheva="min", Max_Kuncheva="max")
    .reset_index()
)
display(kuncheva_summary_df.round(4))

  Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0   DODA      5         0.3642        0.2162       -0.0105        1.0000
1   DODA     10         0.4463        0.1809       -0.0286        0.8286
2   DODA     15         0.4548        0.1914       -0.0667        0.8222
3   DODA     20         0.4070        0.2471       -0.2000        1.0000
4   mRMR      5         0.4417        0.2086       -0.0105        1.0000
5   mRMR     10         0.3783        0.1897       -0.0286        0.8286
6   mRMR     15         0.3517        0.2000       -0.0667        1.0000
7   mRMR     20         0.1730        0.2399       -0.2000        0.7000

In [35]:
# =============================================================================
# STEP 32: mRMR–DODA FEATURE-SET AGREEMENT SUMMARY
# =============================================================================
agreement_summary_df = (
    feature_comparison_df.groupby("Top_K")
    .agg(
        Same_Feature_Set_Rate=("Same_Feature_Set", "mean"),
        Mean_Overlap=("Overlap_Count", "mean"),
        SD_Overlap=("Overlap_Count", "std"),
        Mean_Jaccard=("Jaccard", "mean"),
        SD_Jaccard=("Jaccard", "std"),
        Mean_Features_Changed=("Features_Changed", "mean"),
        SD_Features_Changed=("Features_Changed", "std")
    ).reset_index()
)
display(agreement_summary_df.round(4))

,Top_K,Same_Feature_Set_Rate,Mean_Overlap,SD_Overlap,Mean_Jaccard,SD_Jaccard,Mean_Features_Changed,SD_Features_Changed
0,5,0.04,3.72,0.6137,0.6062,0.1491,1.28,0.6137
1,10,0.08,8.68,0.6904,0.7731,0.1075,1.32,0.6904
2,15,0.04,13.36,0.7000,0.8060,0.0768,1.64,0.7000
3,20,0.04,18.36,0.9074,0.8515,0.0764,1.64,0.9074

In [36]:
# =============================================================================
# STEP 33: PAIRED STATISTICAL COMPARISON OF PREDICTIVE PERFORMANCE
# =============================================================================

from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

metrics = ["Accuracy", "Precision", "Recall", "F1", "ROC_AUC"]

comparison_rows = []

for top_k in TOP_K_VALUES:

    for model_name in models.keys():

        mrmr = cv_results_df[
            (cv_results_df["Method"] == "mRMR") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        doda = cv_results_df[
            (cv_results_df["Method"] == "DODA") &
            (cv_results_df["Top_K"] == top_k) &
            (cv_results_df["Model"] == model_name)
        ].sort_values("Run")

        assert len(mrmr) == 25
        assert len(doda) == 25
        assert (mrmr["Run"].values == doda["Run"].values).all()

        for metric in metrics:

            mrmr_values = mrmr[metric].to_numpy()
            doda_values = doda[metric].to_numpy()

            differences = doda_values - mrmr_values

            mean_difference = np.mean(differences)
            sd_difference = np.std(differences, ddof=1)

            if np.allclose(differences, 0):
                statistic = 0.0
                p_value = 1.0
            else:
                statistic, p_value = wilcoxon(
                    doda_values,
                    mrmr_values,
                    alternative="two-sided"
                )

            paired_d = (
                mean_difference / sd_difference
                if sd_difference > 0 else 0.0
            )

            comparison_rows.append({
                "Top_K": top_k,
                "Model": model_name,
                "Metric": metric,
                "mRMR_Mean": np.mean(mrmr_values),
                "DODA_Mean": np.mean(doda_values),
                "Mean_Difference_DODA_minus_mRMR": mean_difference,
                "Paired_SD": sd_difference,
                "Paired_Cohens_d": paired_d,
                "Wilcoxon_Statistic": statistic,
                "P_Value": p_value
            })

performance_comparison_df = pd.DataFrame(comparison_rows)

reject, adjusted_p, _, _ = multipletests(
    performance_comparison_df["P_Value"],
    alpha=0.05,
    method="holm"
)

performance_comparison_df["Holm_Adjusted_P"] = adjusted_p
performance_comparison_df["Significant"] = reject

display(performance_comparison_df.round(4))

,Top_K,Model,Metric,mRMR_Mean,DODA_Mean,Mean_Difference_DODA_minus_mRMR,Paired_SD,Paired_Cohens_d,Wilcoxon_Statistic,P_Value,Holm_Adjusted_P,Significant
0,5,Logistic Regression,Accuracy,0.5170,0.5129,-0.0041,0.0220,-0.1847,91.5,0.4041,1.0000,False
1,5,Logistic Regression,Precision,0.5261,0.5228,-0.0032,0.0195,-0.1656,115.0,0.4842,1.0000,False
2,5,Logistic Regression,Recall,0.5799,0.5768,-0.0031,0.0325,-0.0961,121.0,0.8580,1.0000,False
3,5,Logistic Regression,F1,0.5512,0.5478,-0.0033,0.0232,-0.1435,133.0,0.8791,1.0000,False
4,5,Logistic Regression,ROC_AUC,0.5203,0.5156,-0.0047,0.0164,-0.2844,95.0,0.1909,1.0000,False
5,5,Random Forest,Accuracy,0.5020,0.5091,0.0071,0.0436,0.1627,113.5,0.2970,1.0000,False
6,5,Random Forest,Precision,0.5144,0.5207,0.0063,0.0406,0.1546,112.0,0.2776,1.0000,False
7,5,Random Forest,Recall,0.5242,0.5333,0.0091,0.0637,0.1431,114.5,0.4745,1.0000,False
8,5,Random Forest,F1,0.5187,0.5260,0.0074,0.0466,0.1579,114.0,0.3037,1.0000,False
9,5,Random Forest,ROC_AUC,0.5045,0.4965,-0.0080,0.0369,-0.2168,140.0,0.5602,1.0000,False
10,5,XGBoost,Accuracy,0.5099,0.5044,-0.0055,0.0305,-0.1788,100.0,0.2476,1.0000,False
11,5,XGBoost,Precision,0.5211,0.5160,-0.0051,0.0297,-0.1709,108.0,0.2301,1.0000,False
12,5,XGBoost,Recall,0.5428,0.5301,-0.0126,0.0443,-0.2846,96.0,0.1226,1.0000,False
13,5,XGBoost,F1,0.5309,0.5223,-0.0086,0.0325,-0.2645,105.0,0.1985,1.0000,False
14,5,XGBoost,ROC_AUC,0.4995,0.5036,0.0041,0.0280,0.1460,139.0,0.5424,1.0000,False
15,10,Logistic Regression,Accuracy,0.5119,0.5180,0.0061,0.0226,0.2689,83.0,0.4110,1.0000,False
16,10,Logistic Regression,Precision,0.5226,0.5280,0.0054,0.0213,0.2515,115.5,0.4937,1.0000,False
17,10,Logistic Regression,Recall,0.5602,0.5708,0.0107,0.0286,0.3728,36.5,0.0582,1.0000,False
18,10,Logistic Regression,F1,0.5403,0.5481,0.0078,0.0227,0.3452,77.5,0.0657,1.0000,False
19,10,Logistic Regression,ROC_AUC,0.5184,0.5203,0.0018,0.0095,0.1957,105.0,0.3155,1.0000,False
20,10,Random Forest,Accuracy,0.4972,0.4970,-0.0002,0.0438,-0.0050,131.5,0.8433,1.0000,False
21,10,Random Forest,Precision,0.5097,0.5104,0.0007,0.0424,0.0162,141.0,0.7971,1.0000,False
22,10,Random Forest,Recall,0.5203,0.5278,0.0074,0.0435,0.1712,114.0,0.4651,1.0000,False
23,10,Random Forest,F1,0.5144,0.5182,0.0038,0.0388,0.0987,128.0,0.5296,1.0000,False
24,10,Random Forest,ROC_AUC,0.4919,0.4963,0.0044,0.0311,0.1426,133.0,0.4418,1.0000,False
25,10,XGBoost,Accuracy,0.4964,0.5012,0.0049,0.0227,0.2142,101.0,0.2602,1.0000,False
26,10,XGBoost,Precision,0.5089,0.5133,0.0044,0.0213,0.2072,121.0,0.2752,1.0000,False
27,10,XGBoost,Recall,0.5251,0.5302,0.0051,0.0325,0.1584,136.0,0.6889,1.0000,False
28,10,XGBoost,F1,0.5163,0.5211,0.0048,0.0242,0.1984,129.0,0.3810,1.0000,False
29,10,XGBoost,ROC_AUC,0.4974,0.5011,0.0037,0.0177,0.2084,141.5,0.5720,1.0000,False
30,15,Logistic Regression,Accuracy,0.5156,0.5206,0.0050,0.0203,0.2487,82.5,0.2511,1.0000,False
31,15,Logistic Regression,Precision,0.5261,0.5309,0.0048,0.0187,0.2585,87.0,0.1997,1.0000,False
32,15,Logistic Regression,Recall,0.5586,0.5633,0.0047,0.0235,0.2008,73.5,0.3864,1.0000,False
33,15,Logistic Regression,F1,0.5414,0.5463,0.0049,0.0191,0.2564,87.0,0.1997,1.0000,False
34,15,Logistic Regression,ROC_AUC,0.5214,0.5239,0.0025,0.0059,0.4247,85.0,0.0633,1.0000,False
35,15,Random Forest,Accuracy,0.4964,0.5045,0.0081,0.0334,0.2431,95.0,0.1907,1.0000,False
36,15,Random Forest,Precision,0.5087,0.5173,0.0086,0.0311,0.2760,109.0,0.1500,1.0000,False
37,15,Random Forest,Recall,0.5294,0.5357,0.0063,0.0522,0.1203,122.0,0.6264,1.0000,False
38,15,Random Forest,F1,0.5182,0.5258,0.0075,0.0387,0.1951,135.0,0.4593,1.0000,False
39,15,Random Forest,ROC_AUC,0.5032,0.5108,0.0077,0.0257,0.2987,103.0,0.1793,1.0000,False
40,15,XGBoost,Accuracy,0.5045,0.5126,0.0081,0.0270,0.2998,100.0,0.1530,1.0000,False
41,15,XGBoost,Precision,0.5170,0.5242,0.0072,0.0257,0.2796,103.0,0.1793,1.0000,False
42,15,XGBoost,Recall,0.5325,0.5393,0.0067,0.0368,0.1834,112.5,0.4377,1.0000,False
43,15,XGBoost,F1,0.5241,0.5312,0.0070,0.0281,0.2499,115.0,0.2099,1.0000,False
44,15,XGBoost,ROC_AUC,0.5100,0.5158,0.0058,0.0228,0.2548,130.0,0.3957,1.0000,False
45,20,Logistic Regression,Accuracy,0.5168,0.5180,0.0012,0.0121,0.1002,83.0,0.6288,1.0000,False
46,20,Logistic Regression,Precision,0.5274,0.5287,0.0013,0.0108,0.1183,126.0,0.7151,1.0000,False
47,20,Logistic Regression,Recall,0.5586,0.5598,0.0012,0.0188,0.0648,62.5,0.5065,1.0000,False
48,20,Logistic Regression,F1,0.5420,0.5433,0.0013,0.0134,0.0933,127.0,0.7380,1.0000,False
49,20,Logistic Regression,ROC_AUC,0.5208,0.5217,0.0009,0.0065,0.1405,107.0,0.2192,1.0000,False
50,20,Random Forest,Accuracy,0.5140,0.5287,0.0148,0.0251,0.5887,64.5,0.0145,0.8576,False
51,20,Random Forest,Precision,0.5249,0.5381,0.0132,0.0229,0.5764,62.0,0.0056,0.3347,False
52,20,Random Forest,Recall,0.5542,0.5661,0.0120,0.0470,0.2544,94.0,0.2910,1.0000,False
53,20,Random Forest,F1,0.5385,0.5511,0.0126,0.0313,0.4037,89.0,0.0483,1.0000,False
54,20,Random Forest,ROC_AUC,0.5251,0.5311,0.0059,0.0229,0.2585,119.0,0.2418,1.0000,False
55,20,XGBoost,Accuracy,0.5249,0.5291,0.0042,0.0302,0.1400,112.5,0.4378,1.0000,False
56,20,XGBoost,Precision,0.5359,0.5396,0.0037,0.0277,0.1334,134.0,0.4578,1.0000,False
57,20,XGBoost,Recall,0.5610,0.5577,-0.0032,0.0402,-0.0799,107.0,0.5265,1.0000,False
58,20,XGBoost,F1,0.5475,0.5479,0.0003,0.0316,0.0108,154.0,0.8325,1.0000,False
59,20,XGBoost,ROC_AUC,0.5334,0.5369,0.0034,0.0195,0.1766,118.0,0.2311,1.0000,False

In [37]:
# =============================================================================
# STEP 34: SAVE STATISTICAL RESULTS
# =============================================================================

stats_dir = Path("../../../results/kidney_disease/statistics")
stats_dir.mkdir(parents=True, exist_ok=True)

feature_comparison_df.to_csv(
    stats_dir / "feature_set_comparison_5x5.csv",
    index=False
)

stability_df.to_csv(
    stats_dir / "feature_selection_stability_5x5.csv",
    index=False
)

performance_comparison_df.to_csv(
    stats_dir / "mrmr_vs_doda_predictive_statistics_5x5.csv",
    index=False
)

print(f"Saved statistical outputs to: {stats_dir.resolve()}")

feature_frequency_df.to_csv(
    stats_dir / "feature_selection_frequency_5x5.csv",
    index=False
)

kuncheva_df.to_csv(
    stats_dir / "kuncheva_pairwise_5x5.csv",
    index=False
)

kuncheva_summary_df.to_csv(
    stats_dir / "kuncheva_summary_5x5.csv",
    index=False
)

agreement_summary_df.to_csv(
    stats_dir / "mrmr_doda_agreement_summary_5x5.csv",
    index=False
)

Saved statistical outputs to: C:\Users\johnm\msc_research\results\kidney_disease\statistics

In [38]:
# =============================================================================
# STEP 36: FINAL SANITY CHECKS
# =============================================================================

print("=" * 70)
print("FINAL EXPERIMENT SANITY CHECK")
print("=" * 70)

print(f"Total predictors: {X.shape[1]}")
print(f"Top-K values: {TOP_K_VALUES}")
print(f"Missing values: {int(X.isna().sum().sum())}")
print(f"5-fold CV result rows: {len(cv5_results_df)}")
print(f"Repeated CV result rows: {len(cv_results_df)}")
print(f"Expected 5-fold rows: {5 * len(TOP_K_VALUES) * 2 * len(models)}")
print(f"Expected repeated CV rows: {25 * len(TOP_K_VALUES) * 2 * len(models)}")

assert X.shape[1] == 24
assert X.isna().sum().sum() == 0
assert TOP_K_VALUES == [5, 10, 15, 20]
assert len(cv5_results_df) == 5 * len(TOP_K_VALUES) * 2 * len(models)
assert len(cv_results_df) == 25 * len(TOP_K_VALUES) * 2 * len(models)
assert len(feature_frequency_df) == 2 * len(TOP_K_VALUES) * X.shape[1]
assert len(kuncheva_summary_df) == 2 * len(TOP_K_VALUES)
assert len(agreement_summary_df) == len(TOP_K_VALUES)

for top_k in TOP_K_VALUES:
    assert len(mrmr_results[top_k]["features"]) == top_k
    assert len(rank_doda_results[top_k]["features"]) == top_k

print("All sanity checks passed.")

======================================================================
FINAL EXPERIMENT SANITY CHECK
======================================================================
Total predictors: 24
Top-K values: [5, 10, 15, 20]
Missing values: 0
5-fold CV result rows: 120
Repeated CV result rows: 600
Expected 5-fold rows: 120
Expected repeated CV rows: 600
All sanity checks passed.