In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# Random Forest

# 1. Baseline

In [10]:
# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION
# TOP-K = 5, 10, 15, 20
# =============================================================================

from sklearn.ensemble import RandomForestClassifier
import pandas as pd


# =============================================================================
# FIT RANDOM FOREST ON ALL TRAINING FEATURES
# =============================================================================

rf_selector = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


rf_selector.fit(
    X_train_scaled,
    y_train
)


# =============================================================================
# CREATE FEATURE IMPORTANCE DATAFRAME
# =============================================================================

rf_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "RF Importance": rf_selector.feature_importances_

})


# =============================================================================
# SORT FEATURES BY IMPORTANCE
# =============================================================================

rf_scores = rf_scores.sort_values(
    by="RF Importance",
    ascending=False
).reset_index(drop=True)


# =============================================================================
# TOP-K VALUES
# =============================================================================

k_values = [5, 10, 15, 20]

rf_results = {}


# =============================================================================
# SELECT TOP-K FEATURES
# =============================================================================

for k in k_values:

    top_features = (
        rf_scores
        .head(k)["Feature"]
        .tolist()
    )


    # -------------------------------------------------------------------------
    # Boolean mask for selecting columns
    # -------------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # -------------------------------------------------------------------------
    # Store results
    # -------------------------------------------------------------------------

    rf_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": rf_scores.head(k)

    }


    # -------------------------------------------------------------------------
    # Display results
    # -------------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} RANDOM FOREST FEATURES")
    print("=" * 70)

    print("\nSelected Features:")
    print(top_features)

    print("\nFeature Importance:")
    print(rf_scores.head(k))


# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION COMPLETED
# =============================================================================

======================================================================
TOP 5 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth']

Feature Importance:
    Feature  RF Importance
0       BMI       0.173505
1       Age       0.130559
2   GenHlth       0.090235
3    Income       0.088408
4  PhysHlth       0.073413
======================================================================
TOP 10 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker']

Feature Importance:
     Feature  RF Importance
0        BMI       0.173505
1        Age       0.130559
2    GenHlth       0.090235
3     Income       0.088408
4   PhysHlth       0.073413
5     HighBP       0.072852
6  Education       0.062088
7   MentHlth       0.055019
8   HighChol       0.036720
9     Smoker       0.029588
======================================================================
TOP 15 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk']

Feature Importance:
         Feature  RF Importance
0            BMI       0.173505
1            Age       0.130559
2        GenHlth       0.090235
3         Income       0.088408
4       PhysHlth       0.073413
5         HighBP       0.072852
6      Education       0.062088
7       MentHlth       0.055019
8       HighChol       0.036720
9         Smoker       0.029588
10        Fruits       0.029558
11           Sex       0.025366
12  PhysActivity       0.023618
13       Veggies       0.023308
14      DiffWalk       0.021686
======================================================================
TOP 20 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare']

Feature Importance:
                 Feature  RF Importance
0                    BMI       0.173505
1                    Age       0.130559
2                GenHlth       0.090235
3                 Income       0.088408
4               PhysHlth       0.073413
5                 HighBP       0.072852
6              Education       0.062088
7               MentHlth       0.055019
8               HighChol       0.036720
9                 Smoker       0.029588
10                Fruits       0.029558
11                   Sex       0.025366
12          PhysActivity       0.023618
13               Veggies       0.023308
14              DiffWalk       0.021686
15  HeartDiseaseorAttack       0.017280
16           NoDocbcCost       0.012788
17                Stroke       0.010267
18     HvyAlcoholConsump       0.009578
19         AnyHealthcare       0.007810

In [12]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [13]:
# =============================================================================
# RANDOM FOREST FEATURE SELECTION — MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_model_results = []


for k in k_values:

    Xtr = rf_results[k]["X_train"]

    Xts = rf_results[k]["X_test"]

    features = ", ".join(
        rf_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_model_results.append({

            "Method": "Random Forest",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_results_df = pd.DataFrame(
    rf_model_results
)


display(rf_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth",0.701057,0.303039,0.734435,0.429047,0.785012
1,Random Forest,5,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth",0.744547,0.287354,0.452914,0.351620,0.694036
2,Random Forest,5,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth",0.689116,0.297977,0.761647,0.428365,0.789155
3,Random Forest,10,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708661,0.312426,0.753669,0.441735,0.804624
4,Random Forest,10,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.817802,0.354117,0.232227,0.280502,0.745475
5,Random Forest,10,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708726,0.314128,0.764354,0.445265,0.806214
6,Random Forest,15,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710513,0.314553,0.757230,0.444472,0.806440
7,Random Forest,15,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.839416,0.428571,0.150021,0.222246,0.770186
8,Random Forest,15,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710426,0.315613,0.764639,0.446803,0.807885
9,Random Forest,20,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.714304,0.317629,0.755948,0.447311,0.809080
10,Random Forest,20,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.842837,0.456658,0.145605,0.220806,0.777013
11,Random Forest,20,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.712169,0.317665,0.768343,0.449492,0.810260

In [14]:
rf_results_df.to_csv(
    "../../../results/diabetes/baseline/rf_baseline_results.csv",
    index=False
)

## 2. DODA

In [15]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--upgrade",
    "--force-reinstall",
    "--no-cache-dir",
    "git+https://github.com/anandha-3679/DODA.git"
])

0

In [16]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [17]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [18]:
# =============================================================================
# RANDOM FOREST + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

rf_doda_results = {}


# =============================================================================
# RUN DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"RANDOM FOREST + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest operator
    # ---------------------------------------------------------------------

    rf = SklearnAdapter(
        RandomForestClassifier(
            n_estimators=100,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        )
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[rf],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    rf_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("RANDOM FOREST + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
RANDOM FOREST + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001BB8AD50C20>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 5 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth']

======================================================================
RANDOM FOREST + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001BB8AD50C20>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 10 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education']

======================================================================
RANDOM FOREST + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001BB8AD50C20>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 15 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits']

======================================================================
RANDOM FOREST + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001BB8AD50C20>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores

In [20]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = rf_doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
3                    BMI        0.173505               1.000000
18                   Age        0.130559               0.752482
13               GenHlth        0.090235               0.520070
20                Income        0.088408               0.509541
15              PhysHlth        0.073413               0.423119
0                 HighBP        0.072852               0.419884
19             Education        0.062088               0.357843
14              MentHlth        0.055019               0.317106
1               HighChol        0.036720               0.211638
4                 Smoker        0.029588               0.170531
8                 Fruits        0.029558               0.170359
17                   Sex        0.025366               0.146198
7           PhysActivity        0.023618               0.136126
9                Veggies        0.023308               0.134336
16              DiffWalk        0.021686               0.124985
6   HeartDiseaseorAttack        0.017280               0.099592
12           NoDocbcCost        0.012788               0.073704
5                 Stroke        0.010267               0.059173
10     HvyAlcoholConsump        0.009578               0.055203
11         AnyHealthcare        0.007810               0.045014
2              CholCheck        0.006355               0.036625

In [21]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                 HighBP              1.0
3                    BMI              1.0
13               GenHlth              1.0
6   HeartDiseaseorAttack              1.0
5                 Stroke              1.0
18                   Age              0.9
16              DiffWalk              0.9
1               HighChol              0.9
15              PhysHlth              0.8
4                 Smoker              0.6
14              MentHlth              0.5
2              CholCheck              0.4
7           PhysActivity              0.4
20                Income              0.3
19             Education              0.3
12           NoDocbcCost              0.2
9                Veggies              0.2
8                 Fruits              0.2
11         AnyHealthcare              0.2
10     HvyAlcoholConsump              0.2
17                   Sex              0.2

In [22]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
3                    BMI          1.000000
18                   Age          0.677234
13               GenHlth          0.520070
0                 HighBP          0.419884
15              PhysHlth          0.338495
1               HighChol          0.190474
14              MentHlth          0.158553
20                Income          0.152862
16              DiffWalk          0.112487
19             Education          0.107353
4                 Smoker          0.102319
6   HeartDiseaseorAttack          0.099592
5                 Stroke          0.059173
7           PhysActivity          0.054450
8                 Fruits          0.034072
17                   Sex          0.029240
9                Veggies          0.026867
12           NoDocbcCost          0.014741
2              CholCheck          0.014650
10     HvyAlcoholConsump          0.011041
11         AnyHealthcare          0.009003

In [23]:
selector.get_selected_features()

['BMI',
 'Age',
 'GenHlth',
 'HighBP',
 'PhysHlth',
 'HighChol',
 'MentHlth',
 'Income',
 'DiffWalk',
 'Education']

In [24]:
comparison = selector.compare_scores()

comparison

,Feature,Math Rank,Normalized Math Score,Clinical Weight,DODA Rank,Final Score,Rank Change
0,BMI,1,1.0000,1.0,1,1.0000,0
1,Age,2,0.7525,0.9,2,0.6772,0
2,GenHlth,3,0.5201,1.0,3,0.5201,0
3,HighBP,6,0.4199,1.0,4,0.4199,2
4,PhysHlth,5,0.4231,0.8,5,0.3385,0
5,HighChol,9,0.2116,0.9,6,0.1905,3
6,MentHlth,8,0.3171,0.5,7,0.1586,1
7,Income,4,0.5095,0.3,8,0.1529,-4
8,DiffWalk,15,0.1250,0.9,9,0.1125,6
9,Education,7,0.3578,0.3,10,0.1074,-3
10,Smoker,10,0.1705,0.6,11,0.1023,-1
11,HeartDiseaseorAttack,16,0.0996,1.0,12,0.0996,4
12,Stroke,18,0.0592,1.0,13,0.0592,5
13,PhysActivity,13,0.1361,0.4,14,0.0545,-1
14,Fruits,11,0.1704,0.2,15,0.0341,-4
15,Sex,12,0.1462,0.2,16,0.0292,-4
16,Veggies,14,0.1343,0.2,17,0.0269,-3
17,NoDocbcCost,17,0.0737,0.2,18,0.0147,-1
18,CholCheck,21,0.0366,0.4,19,0.0146,2
19,HvyAlcoholConsump,19,0.0552,0.2,20,0.0110,-1
20,AnyHealthcare,20,0.0450,0.2,21,0.0090,-1

In [25]:
# =============================================================================
# RANDOM FOREST + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_doda_model_results = []


for k in k_values:

    Xtr = rf_doda_results[k]["X_train"]

    Xts = rf_doda_results[k]["X_test"]

    features = ", ".join(
        rf_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_doda_model_results.append({

            "Method": "RF + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_doda_results_df = pd.DataFrame(
    rf_doda_model_results
)


display(rf_doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,RF + DODA,5,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
1,RF + DODA,5,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth",0.728816,0.303298,0.596096,0.402037,0.735567
2,RF + DODA,5,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
3,RF + DODA,10,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.709533,0.313077,0.753099,0.442288,0.804871
4,RF + DODA,10,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.812420,0.342011,0.245192,0.285619,0.740782
5,RF + DODA,10,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.706765,0.313157,0.768770,0.445031,0.805572
6,RF + DODA,15,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.713585,0.316543,0.752956,0.445709,0.805998
7,RF + DODA,15,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.834078,0.396312,0.162274,0.230264,0.762869
8,RF + DODA,15,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.711123,0.316035,0.763499,0.447030,0.806484
9,RF + DODA,20,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
10,RF + DODA,20,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.843273,0.461056,0.146745,0.222630,0.778232
11,RF + DODA,20,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [26]:
rf_doda_results_df.to_csv(
    "../../../results/diabetes/doda/rf_doda_results.csv",
    index=False
)

In [28]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        rf_results_df,
        rf_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth",0.701057,0.303039,0.734435,0.429047,0.785012
1,Random Forest,5,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth",0.744547,0.287354,0.452914,0.351620,0.694036
2,Random Forest,5,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth",0.689116,0.297977,0.761647,0.428365,0.789155
3,Random Forest,10,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708661,0.312426,0.753669,0.441735,0.804624
4,Random Forest,10,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.817802,0.354117,0.232227,0.280502,0.745475
5,Random Forest,10,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708726,0.314128,0.764354,0.445265,0.806214
6,Random Forest,15,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710513,0.314553,0.757230,0.444472,0.806440
7,Random Forest,15,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.839416,0.428571,0.150021,0.222246,0.770186
8,Random Forest,15,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710426,0.315613,0.764639,0.446803,0.807885
9,Random Forest,20,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.714304,0.317629,0.755948,0.447311,0.809080
10,Random Forest,20,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.842837,0.456658,0.145605,0.220806,0.777013
11,Random Forest,20,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.712169,0.317665,0.768343,0.449492,0.810260
12,RF + DODA,5,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
13,RF + DODA,5,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth",0.728816,0.303298,0.596096,0.402037,0.735567
14,RF + DODA,5,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
15,RF + DODA,10,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.709533,0.313077,0.753099,0.442288,0.804871
16,RF + DODA,10,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.812420,0.342011,0.245192,0.285619,0.740782
17,RF + DODA,10,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.706765,0.313157,0.768770,0.445031,0.805572
18,RF + DODA,15,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.713585,0.316543,0.752956,0.445709,0.805998
19,RF + DODA,15,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.834078,0.396312,0.162274,0.230264,0.762869
20,RF + DODA,15,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.711123,0.316035,0.763499,0.447030,0.806484
21,RF + DODA,20,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
22,RF + DODA,20,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.843273,0.461056,0.146745,0.222630,0.778232
23,RF + DODA,20,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [29]:
for k in k_values:

    selector = rf_doda_results[k]["selector"]

    raw_rank = [
        x[0]
        for x in sorted(
            selector.raw_math_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    doda_rank = [
        x[0]
        for x in sorted(
            selector.final_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    print("\n" + "=" * 70)
    print(f"TOP {k}")
    print("=" * 70)

    print("Raw Math Ranking:")
    print(raw_rank)

    print("\nDODA Ranking:")
    print(doda_rank)

    print("\nTop-K Same:",
          raw_rank[:k] == doda_rank[:k])

======================================================================
TOP 5
======================================================================
Raw Math Ranking:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare', 'CholCheck']

DODA Ranking:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'NoDocbcCost', 'CholCheck', 'HvyAlcoholConsump', 'AnyHealthcare']

Top-K Same: False

======================================================================
TOP 10
======================================================================
Raw Math Ranking:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare', 'CholCheck']

DODA Ranking:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'NoDocbcCost', 'CholCheck', 'HvyAlcoholConsump', 'AnyHealthcare']

Top-K Same: False

======================================================================
TOP 15
======================================================================
Raw Math Ranking:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare', 'CholCheck']

DODA Ranking:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'NoDocbcCost', 'CholCheck', 'HvyAlcoholConsump', 'AnyHealthcare']

Top-K Same: False

======================================================================
TOP 20
======================================================================
Raw Math Ranking:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare', 'CholCheck']

DODA Ranking:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'NoDocbcCost', 'CholCheck', 'HvyAlcoholConsump', 'AnyHealthcare']

Top-K Same: False

# RF + DODA — Experiment Interpretation

## 1. Overall Observation

The Random Forest + DODA experiment evaluates whether incorporating clinical knowledge into a Random Forest-based feature-selection process can modify feature rankings while maintaining or improving downstream predictive performance.

The results show that DODA changes the feature ranking produced by the Random Forest operator at every evaluated Top-K value:

- Top-5: `Top-K Same = False`
- Top-10: `Top-K Same = False`
- Top-15: `Top-K Same = False`
- Top-20: `Top-K Same = False`

Therefore, the clinical knowledge layer is actively influencing the feature-selection process rather than simply reproducing the original Random Forest ranking.

---

## 2. Change in Feature Ranking

The Random Forest baseline produced the following ranking:

1. BMI
2. Age
3. GenHlth
4. Income
5. PhysHlth
6. HighBP
7. Education
8. MentHlth
9. HighChol
10. Smoker
11. Fruits
12. Sex
13. PhysActivity
14. Veggies
15. DiffWalk
16. HeartDiseaseorAttack
17. NoDocbcCost
18. Stroke
19. HvyAlcoholConsump
20. AnyHealthcare
21. CholCheck

After applying DODA, the ranking became:

1. BMI
2. Age
3. GenHlth
4. HighBP
5. PhysHlth
6. HighChol
7. MentHlth
8. Income
9. DiffWalk
10. Education
11. Smoker
12. HeartDiseaseorAttack
13. Stroke
14. PhysActivity
15. Fruits
16. Sex
17. Veggies
18. NoDocbcCost
19. CholCheck
20. HvyAlcoholConsump
21. AnyHealthcare

The comparison shows that important data-driven features such as **BMI, Age, and GenHlth** remain highly ranked after applying DODA. However, several clinically relevant features receive higher priority.

For example:

- `HighBP` moves from rank 6 to rank 4.
- `HighChol` moves from rank 9 to rank 6.
- `DiffWalk` moves from rank 15 to rank 9.
- `HeartDiseaseorAttack` moves from rank 16 to rank 12.
- `Stroke` moves from rank 18 to rank 13.
- `CholCheck` moves from rank 21 to rank 19.

This demonstrates that the clinical knowledge layer changes the ranking while retaining important statistical signals.

---

## 3. Top-K Feature Selection

The selected Top-K features also change after applying DODA.

### Top-5

**Random Forest:**

```text
BMI
Age
GenHlth
Income
PhysHlth
````

**RF + DODA:**

```text
BMI
Age
GenHlth
HighBP
PhysHlth
```

DODA replaces `Income` with `HighBP`, resulting in a more clinically relevant Top-5 subset.

---

### Top-10

The Random Forest baseline includes features such as `Income`, `Education`, and `MentHlth` relatively early in the ranking.

After DODA, clinically relevant variables such as `HighBP` and `HighChol` receive higher priority.

This indicates that the knowledge-guided ranking is changing the composition of the selected feature subset.

---

### Top-15 and Top-20

The same general pattern continues at larger feature subsets.

DODA promotes clinically relevant variables such as:

* HighBP
* HighChol
* DiffWalk
* HeartDiseaseorAttack
* Stroke

while some lower-priority variables are pushed further down the ranking.

Therefore, the effect of DODA is not restricted to the Top-5 subset. The ranking changes persist across all evaluated values of K.

---

## 4. Top-K Stability Between RF and RF + DODA

The comparison between the original Random Forest ranking and the DODA-adjusted ranking produced:

```text
Top-5  → Top-K Same: False
Top-10 → Top-K Same: False
Top-15 → Top-K Same: False
Top-20 → Top-K Same: False
```

This is an important result for the proposed framework.

If the Top-K subsets had remained identical, it would suggest that the clinical knowledge layer had little or no practical influence on feature selection.

Instead, the fact that all four comparisons are `False` demonstrates that DODA is effectively modifying the feature-selection outcome.

---

# 5. Predictive Performance Comparison

The selected features were evaluated using:

* Logistic Regression
* Random Forest
* XGBoost

The evaluation metrics were:

* Accuracy
* Precision
* Recall
* F1 Score
* ROC-AUC

Because the dataset is highly imbalanced, accuracy should not be interpreted independently. Recall, F1-score, and ROC-AUC are particularly important for evaluating the models.

---

## 6. Logistic Regression Results

The ROC-AUC comparison between Random Forest feature selection and RF + DODA feature selection is:

| Top-K |     RF | RF + DODA |  Change |
| ----: | -----: | --------: | ------: |
|     5 | 0.7850 |    0.7970 | +0.0120 |
|    10 | 0.8046 |    0.8049 | +0.0003 |
|    15 | 0.8064 |    0.8060 | -0.0004 |
|    20 | 0.8091 |    0.8105 | +0.0015 |

The largest improvement occurs at Top-5, where ROC-AUC increases from approximately `0.7850` to `0.7970`.

At Top-10 and Top-20, the performance remains very similar, while Top-15 shows only a negligible decrease.

This indicates that DODA can modify the feature subset while largely preserving the predictive information required by Logistic Regression.

The best Logistic Regression configuration is:

```text
Method   : RF + DODA
Top-K    : 20
ROC-AUC  : 0.8105
Recall   : 0.7597
F1 Score : 0.4484
```

---

## 7. Random Forest Results

The ROC-AUC comparison is:

| Top-K |     RF | RF + DODA |  Change |
| ----: | -----: | --------: | ------: |
|     5 | 0.6940 |    0.7356 | +0.0415 |
|    10 | 0.7455 |    0.7408 | -0.0047 |
|    15 | 0.7702 |    0.7629 | -0.0073 |
|    20 | 0.7770 |    0.7782 | +0.0012 |

The largest improvement occurs at Top-5.

ROC-AUC increases from:

```text
0.6940 → 0.7356
```

This represents an improvement of approximately `0.0415`.

However, the improvement is not consistent across all K values. At Top-10 and Top-15, the RF + DODA configuration produces slightly lower ROC-AUC than the Random Forest baseline.

This indicates that the effect of clinical knowledge depends on the number of features retained.

---

## 8. XGBoost Results

The ROC-AUC comparison is:

| Top-K |     RF | RF + DODA |  Change |
| ----: | -----: | --------: | ------: |
|     5 | 0.7892 |    0.8002 | +0.0110 |
|    10 | 0.8062 |    0.8056 | -0.0006 |
|    15 | 0.8079 |    0.8065 | -0.0014 |
|    20 | 0.8103 |    0.8116 | +0.0014 |

The largest improvement occurs at Top-5:

```text
0.7892 → 0.8002
```

At Top-10 and Top-15, the differences are very small.

At Top-20, RF + DODA achieves the highest ROC-AUC observed in the RF-based experiment:

```text
ROC-AUC = 0.8116
```

The corresponding recall and F1-score are:

```text
Recall   = 0.7688
F1 Score = 0.4500
```

Therefore, **XGBoost + RF + DODA with Top-20 features** provides the strongest overall discriminative performance in this experiment.

---

# 9. Best Performing Configurations

### Best Logistic Regression

```text
Method   : RF + DODA
Top-K    : 20
Accuracy : 0.7142
Precision: 0.3181
Recall   : 0.7597
F1 Score : 0.4484
ROC-AUC  : 0.8105
```

### Best Random Forest

```text
Method   : RF + DODA
Top-K    : 20
Accuracy : 0.8433
Precision: 0.4611
Recall   : 0.1467
F1 Score : 0.2226
ROC-AUC  : 0.7782
```

### Best XGBoost

```text
Method   : RF + DODA
Top-K    : 20
Accuracy : 0.7126
Precision: 0.3181
Recall   : 0.7688
F1 Score : 0.4500
ROC-AUC  : 0.8116
```

---

# 10. Importance of Recall and F1-Score

The Random Forest models achieve relatively high accuracy at larger K values. For example:

```text
RF + DODA, Top-20

Accuracy  = 0.8433
Precision = 0.4611
Recall    = 0.1467
F1 Score  = 0.2226
ROC-AUC   = 0.7782
```

Although the accuracy is high, the recall is only `0.1467`.

This indicates that the model correctly identifies only a relatively small proportion of the positive cases.

Therefore, accuracy alone is not an appropriate metric for selecting the best model in this imbalanced clinical prediction problem.

Metrics such as **Recall, F1-score, and ROC-AUC** provide a more meaningful assessment of model performance.

In particular, the XGBoost + RF + DODA Top-20 configuration provides a better balance between recall and precision than the corresponding Random Forest model.

---

# 11. Effect of Clinical Knowledge

The primary purpose of DODA is not simply to maximize predictive performance.

Instead, DODA aims to combine:

1. **Data-driven mathematical importance**
2. **Clinical knowledge**
3. **Feature ranking and selection**

The experiment demonstrates that this combination produces a different ranking from the purely data-driven Random Forest ranking.

For example:

```text
Random Forest:
BMI → Age → GenHlth → Income → PhysHlth → HighBP ...

RF + DODA:
BMI → Age → GenHlth → HighBP → PhysHlth → HighChol ...
```

The change demonstrates that clinical knowledge is being incorporated into the feature-selection process.

At the same time, the strongest statistical features remain highly ranked.

This suggests that DODA does not completely override the data-driven evidence. Instead, it **adjusts the ranking according to clinical relevance**.

---

# 12. Main Finding

The main finding from this experiment is:

> **RF + DODA successfully modifies Random Forest-based feature rankings by incorporating clinical knowledge while preserving important data-driven features.**

The `Top-K Same = False` result for all four K values confirms that the DODA layer has a measurable influence on feature selection.

However, the predictive-performance improvements are not uniform across every model and Top-K value.

This is an expected result because changing the feature subset can affect different predictive models differently.

---

# 13. Research Interpretation

The results provide evidence supporting the proposed concept of a **clinically guided feature-selection framework**.

The Random Forest operator identifies features based on data-driven predictive importance. DODA then incorporates clinical weights to modify these rankings.

The resulting feature rankings demonstrate that clinically meaningful variables such as:

* `HighBP`
* `HighChol`
* `DiffWalk`
* `HeartDiseaseorAttack`
* `Stroke`

can be promoted even when their original Random Forest importance is lower.

Importantly, this adjustment does not result in a substantial loss of predictive performance.

In several configurations, RF + DODA produces equal or better ROC-AUC than the Random Forest baseline.

Therefore, the experiment supports the argument that DODA can introduce **clinical interpretability and domain knowledge into conventional feature-selection methods while maintaining competitive predictive performance**.

---

# 14. Conclusion

The RF + DODA experiment demonstrates that the proposed DODA framework effectively integrates clinical knowledge with Random Forest-based feature selection.

The key observations are:

* DODA changes the feature ranking at **every Top-K level**.
* Important data-driven features such as `BMI`, `Age`, and `GenHlth` remain highly ranked.
* Clinically relevant features such as `HighBP`, `HighChol`, `DiffWalk`, `HeartDiseaseorAttack`, and `Stroke` are promoted.
* The Top-K feature sets differ between Random Forest and RF + DODA for all evaluated K values.
* Predictive performance is generally maintained and improves in several configurations.
* The largest Random Forest improvement occurs at **Top-5**, with ROC-AUC increasing from `0.6940` to `0.7356`.
* The best overall ROC-AUC is obtained by **XGBoost + RF + DODA with Top-20 features (`0.8116`)**.
* Accuracy should not be considered independently because of the class imbalance.
* Recall, F1-score, and ROC-AUC provide more meaningful evaluation of the clinical prediction task.

Overall, these findings indicate that **DODA can alter data-driven feature rankings in a clinically meaningful way without substantially compromising predictive performance**, supporting its use as a knowledge-guided feature-selection framework.

```
```