In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# MRMR

## 1. Baseline

In [10]:
!pip install mrmr-selection

Requirement already satisfied: mrmr-selection in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (0.2.8)
Requirement already satisfied: category-encoders in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (2.9.0)
Requirement already satisfied: jinja2 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (3.1.6)
Requirement already satisfied: tqdm in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (4.67.1)
Requirement already satisfied: joblib in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (1.4.2)
Requirement already satisfied: pandas>=1.0.3 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (2.2.3)
Requirement already satisfied: numpy>=1.18.1 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (2.1.3)
Requirement already satisfied: scikit-learn in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (1.6.1)
Requirement already satisfied: scipy in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (1.15.3)
Requirement already satisfied: polars>=0.12.5 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from mrmr-selection) (1.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from pandas>=1.0.3->mrmr-selection) (2025.2)
Requirement already satisfied: polars-runtime-32==1.43.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from polars>=0.12.5->mrmr-selection) (1.43.0)
Requirement already satisfied: six>=1.5 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.3->mrmr-selection) (1.17.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from category-encoders->mrmr-selection) (1.0.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from category-encoders->mrmr-selection) (0.14.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from scikit-learn->mrmr-selection) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from statsmodels>=0.9.0->category-encoders->mrmr-selection) (24.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from jinja2->mrmr-selection) (3.0.2)
Requirement already satisfied: colorama in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from tqdm->mrmr-selection) (0.4.6)

In [11]:
# =============================================================================
# MRMR BASELINE FEATURE SELECTION
# TOP-K = 5, 10, 15, 20
# =============================================================================

from mrmr import mrmr_classif
import pandas as pd


# -------------------------------------------------------------------------
# Align indices
# -------------------------------------------------------------------------

X_train_mrmr = X_train_scaled.copy()
y_train_mrmr = y_train.copy()

X_train_mrmr = X_train_mrmr.reset_index(drop=True)
y_train_mrmr = y_train_mrmr.reset_index(drop=True)


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Store MRMR results
# -------------------------------------------------------------------------

mrmr_results = {}


# =============================================================================
# RUN MRMR
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"TOP {k} MRMR FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # MRMR feature selection
    # ---------------------------------------------------------------------

    selected_features = mrmr_classif(
        X=X_train_mrmr,
        y=y_train_mrmr,
        K=k
    )


    # ---------------------------------------------------------------------
    # Select features
    # ---------------------------------------------------------------------

    X_train_selected = X_train_scaled[
        selected_features
    ]

    X_test_selected = X_test_scaled[
        selected_features
    ]


    # ---------------------------------------------------------------------
    # Store results
    # ---------------------------------------------------------------------

    mrmr_results[k] = {

        "features": selected_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected
    }


    # ---------------------------------------------------------------------
    # Display
    # ---------------------------------------------------------------------

    print("\nSelected Features:")

    print(selected_features)


print("\n" + "=" * 70)
print("MRMR FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
TOP 5 MRMR FEATURES
======================================================================

100%|██████████| 5/5 [00:01<00:00,  3.30it/s]

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']

======================================================================
TOP 10 MRMR FEATURES
======================================================================

100%|██████████| 10/10 [00:03<00:00,  3.24it/s]

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']

======================================================================
TOP 15 MRMR FEATURES
======================================================================

100%|██████████| 15/15 [00:05<00:00,  2.99it/s]

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']

======================================================================
TOP 20 MRMR FEATURES
======================================================================

100%|██████████| 20/20 [00:11<00:00,  1.82it/s]

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']

======================================================================
MRMR FEATURE SELECTION COMPLETED
======================================================================

In [12]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [13]:
# =============================================================================
# MRMR MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


mrmr_model_results = []


for k in k_values:

    Xtr = mrmr_results[k]["X_train"]

    Xts = mrmr_results[k]["X_test"]

    features = ", ".join(
        mrmr_results[k]["features"]
    )


    for model_name, model in models.items():

        # -------------------------------------------------------------
        # Train
        # -------------------------------------------------------------

        model.fit(
            Xtr,
            y_train
        )


        # -------------------------------------------------------------
        # Predictions
        # -------------------------------------------------------------

        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        # -------------------------------------------------------------
        # Store metrics
        # -------------------------------------------------------------

        mrmr_model_results.append({

            "Method": "MRMR",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


# =============================================================================
# CREATE RESULTS DATAFRAME
# =============================================================================

mrmr_results_df = pd.DataFrame(
    mrmr_model_results
)


display(mrmr_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,MRMR,5,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.708552,0.308374,0.728736,0.433364,0.791913
1,MRMR,5,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.703366,0.305629,0.738709,0.432372,0.786967
2,MRMR,5,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.691077,0.299927,0.764496,0.430831,0.794595
3,MRMR,10,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714631,0.317631,0.754096,0.446987,0.807581
4,MRMR,10,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.794161,0.325825,0.323550,0.324684,0.723269
5,MRMR,10,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.709228,0.315137,0.768201,0.446931,0.808270
6,MRMR,15,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714806,0.318198,0.756803,0.448024,0.809239
7,MRMR,15,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.822290,0.362515,0.213563,0.268782,0.751129
8,MRMR,15,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.710818,0.316767,0.770053,0.448883,0.810332
9,MRMR,20,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714304,0.318260,0.760080,0.448659,0.810583
10,MRMR,20,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.843621,0.466582,0.157145,0.235106,0.776711
11,MRMR,20,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.712997,0.319040,0.772760,0.451624,0.811831

In [14]:
mrmr_results_df.to_csv(
    "../../../results/diabetes/baseline/mrmr_baseline_results.csv",
    index=False
)

## 2. DODA

In [15]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [17]:
# =============================================================================
# MRMR ADAPTER FOR DODA
# =============================================================================

import numpy as np


class MRMRAdapter:

    def __init__(self, K):
        self.K = K
        self.importance = {}

    def fit(self, X, y):

        # Run MRMR
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=self.K
        )

        # -------------------------------------------------------------
        # Convert MRMR ranking into importance scores
        # First feature = highest score
        # -------------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # -------------------------------------------------------------
        # Store importance
        # -------------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"

In [18]:
# ============================================================
# FIX INDEX ALIGNMENT FOR MRMR
# ============================================================

# Convert X and y to pandas objects
X_mrmr = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
).reset_index(drop=True)

y_mrmr = pd.Series(
    y_train
).reset_index(drop=True)


print("X shape:", X_mrmr.shape)
print("y shape:", y_mrmr.shape)

print("X index:", X_mrmr.index[:5])
print("y index:", y_mrmr.index[:5])

X shape: (183579, 21)
y shape: (183579,)
X index: RangeIndex(start=0, stop=5, step=1)
y index: RangeIndex(start=0, stop=5, step=1)

In [19]:
from mrmr import mrmr_classif

mrmr_ranked_features = mrmr_classif(
    X=X_mrmr,
    y=y_mrmr,
    K=X_mrmr.shape[1]
)

print("Full MRMR ranking:")
print(mrmr_ranked_features)

print("Number of features:", len(mrmr_ranked_features))

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Full MRMR ranking:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits', 'NoDocbcCost']
Number of features: 21

In [20]:
# =============================================================================
# MRMR + DODA FEATURE SELECTION
# =============================================================================

import numpy as np
import pandas as pd


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# MRMR Adapter
# -------------------------------------------------------------------------

class MRMRAdapter:

    def __init__(self, ranked_features):

        self.ranked_features = ranked_features
        self.importance = {}


    def fit(self, X, y):

        n_features = len(self.ranked_features)

        # Convert MRMR ranking into decreasing scores
        # Rank 1 = highest score
        # Rank n = lowest score

        for rank, feature in enumerate(
            self.ranked_features,
            start=1
        ):

            self.importance[feature] = (
                n_features - rank + 1
            ) / n_features

        return self


    def get_importance(self):

        return self.importance


    def get_name(self):

        return "MRMR"


# -------------------------------------------------------------------------
# Store results
# -------------------------------------------------------------------------

mrmr_doda_results = {}


# =============================================================================
# RUN MRMR + DODA
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"MRMR + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Create MRMR adapter
    # ---------------------------------------------------------------------

    mrmr_adapter = MRMRAdapter(
        mrmr_ranked_features
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(

        operators=[
            mrmr_adapter
        ],

        provider=provider,

        fusion=fusion,

        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on training data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform test data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = (
        selector.get_selected_features()
    )


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store results
    # ---------------------------------------------------------------------

    mrmr_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores":
            selector.raw_math_scores_,

        "math_scores":
            selector.math_scores_,

        "clinical_weights":
            selector.clinical_weights_,

        "final_scores":
            selector.final_scores_
    }


print("\n" + "=" * 70)
print("MRMR + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
MRMR + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D01E510>
DODA Pipeline Started
Running: MRMR
Operator Scores:
{'MRMR_1': {'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}

Normalized Mathematical Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.8571428571428571), 'DiffWalk': np.float64(0.8095238095238095), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.7142857142857143), 'Income': np.float64(0.6666666666666666), 'PhysHlth': np.float64(0.6190476190476191), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'CholCheck': np.float64(0.5238095238095238), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.42857142857142855), 'Education': np.float64(0.38095238095238093), 'Veggies': np.float64(0.3333333333333333), 'Smoker': np.float64(0.2857142857142857), 'MentHlth': np.float64(0.23809523809523808), 'Sex': np.float64(0.19047619047619047), 'AnyHealthcare': np.float64(0.14285714285714285), 'Fruits': np.float64(0.09523809523809523), 'NoDocbcCost': np.float64(0.047619047619047616)}

Clinical Weights
{'GenHlth': 1.0, 'HighBP': 1.0, 'BMI': 1.0, 'HighChol': 0.9, 'DiffWalk': 0.9, 'HeartDiseaseorAttack': 1.0, 'Age': 0.9, 'Income': 0.3, 'PhysHlth': 0.8, 'HvyAlcoholConsump': 0.2, 'CholCheck': 0.4, 'Stroke': 1.0, 'PhysActivity': 0.4, 'Education': 0.3, 'Veggies': 0.2, 'Smoker': 0.6, 'MentHlth': 0.5, 'Sex': 0.2, 'AnyHealthcare': 0.2, 'Fruits': 0.2, 'NoDocbcCost': 0.2}

Final DODA Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.7714285714285714), 'DiffWalk': np.float64(0.7285714285714286), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.6428571428571429), 'Income': np.float64(0.19999999999999998), 'PhysHlth': np.float64(0.49523809523809526), 'HvyAlcoholConsump': np.float64(0.11428571428571428), 'CholCheck': np.float64(0.20952380952380956), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.17142857142857143), 'Education': np.float64(0.11428571428571427), 'Veggies': np.float64(0.06666666666666667), 'Smoker': np.float64(0.1714285714285714), 'MentHlth': np.float64(0.11904761904761904), 'Sex': np.float64(0.0380952380952381), 'AnyHealthcare': np.float64(0.02857142857142857), 'Fruits': np.float64(0.01904761904761905), 'NoDocbcCost': np.float64(0.009523809523809525)}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

======================================================================
MRMR + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D01E510>
DODA Pipeline Started
Running: MRMR
Operator Scores:
{'MRMR_1': {'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}

Normalized Mathematical Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.8571428571428571), 'DiffWalk': np.float64(0.8095238095238095), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.7142857142857143), 'Income': np.float64(0.6666666666666666), 'PhysHlth': np.float64(0.6190476190476191), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'CholCheck': np.float64(0.5238095238095238), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.42857142857142855), 'Education': np.float64(0.38095238095238093), 'Veggies': np.float64(0.3333333333333333), 'Smoker': np.float64(0.2857142857142857), 'MentHlth': np.float64(0.23809523809523808), 'Sex': np.float64(0.19047619047619047), 'AnyHealthcare': np.float64(0.14285714285714285), 'Fruits': np.float64(0.09523809523809523), 'NoDocbcCost': np.float64(0.047619047619047616)}

Clinical Weights
{'GenHlth': 1.0, 'HighBP': 1.0, 'BMI': 1.0, 'HighChol': 0.9, 'DiffWalk': 0.9, 'HeartDiseaseorAttack': 1.0, 'Age': 0.9, 'Income': 0.3, 'PhysHlth': 0.8, 'HvyAlcoholConsump': 0.2, 'CholCheck': 0.4, 'Stroke': 1.0, 'PhysActivity': 0.4, 'Education': 0.3, 'Veggies': 0.2, 'Smoker': 0.6, 'MentHlth': 0.5, 'Sex': 0.2, 'AnyHealthcare': 0.2, 'Fruits': 0.2, 'NoDocbcCost': 0.2}

Final DODA Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.7714285714285714), 'DiffWalk': np.float64(0.7285714285714286), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.6428571428571429), 'Income': np.float64(0.19999999999999998), 'PhysHlth': np.float64(0.49523809523809526), 'HvyAlcoholConsump': np.float64(0.11428571428571428), 'CholCheck': np.float64(0.20952380952380956), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.17142857142857143), 'Education': np.float64(0.11428571428571427), 'Veggies': np.float64(0.06666666666666667), 'Smoker': np.float64(0.1714285714285714), 'MentHlth': np.float64(0.11904761904761904), 'Sex': np.float64(0.0380952380952381), 'AnyHealthcare': np.float64(0.02857142857142857), 'Fruits': np.float64(0.01904761904761905), 'NoDocbcCost': np.float64(0.009523809523809525)}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck']

======================================================================
MRMR + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D01E510>
DODA Pipeline Started
Running: MRMR
Operator Scores:
{'MRMR_1': {'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}

Normalized Mathematical Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.8571428571428571), 'DiffWalk': np.float64(0.8095238095238095), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.7142857142857143), 'Income': np.float64(0.6666666666666666), 'PhysHlth': np.float64(0.6190476190476191), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'CholCheck': np.float64(0.5238095238095238), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.42857142857142855), 'Education': np.float64(0.38095238095238093), 'Veggies': np.float64(0.3333333333333333), 'Smoker': np.float64(0.2857142857142857), 'MentHlth': np.float64(0.23809523809523808), 'Sex': np.float64(0.19047619047619047), 'AnyHealthcare': np.float64(0.14285714285714285), 'Fruits': np.float64(0.09523809523809523), 'NoDocbcCost': np.float64(0.047619047619047616)}

Clinical Weights
{'GenHlth': 1.0, 'HighBP': 1.0, 'BMI': 1.0, 'HighChol': 0.9, 'DiffWalk': 0.9, 'HeartDiseaseorAttack': 1.0, 'Age': 0.9, 'Income': 0.3, 'PhysHlth': 0.8, 'HvyAlcoholConsump': 0.2, 'CholCheck': 0.4, 'Stroke': 1.0, 'PhysActivity': 0.4, 'Education': 0.3, 'Veggies': 0.2, 'Smoker': 0.6, 'MentHlth': 0.5, 'Sex': 0.2, 'AnyHealthcare': 0.2, 'Fruits': 0.2, 'NoDocbcCost': 0.2}

Final DODA Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.7714285714285714), 'DiffWalk': np.float64(0.7285714285714286), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.6428571428571429), 'Income': np.float64(0.19999999999999998), 'PhysHlth': np.float64(0.49523809523809526), 'HvyAlcoholConsump': np.float64(0.11428571428571428), 'CholCheck': np.float64(0.20952380952380956), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.17142857142857143), 'Education': np.float64(0.11428571428571427), 'Veggies': np.float64(0.06666666666666667), 'Smoker': np.float64(0.1714285714285714), 'MentHlth': np.float64(0.11904761904761904), 'Sex': np.float64(0.0380952380952381), 'AnyHealthcare': np.float64(0.02857142857142857), 'Fruits': np.float64(0.01904761904761905), 'NoDocbcCost': np.float64(0.009523809523809525)}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck', 'Income', 'PhysActivity', 'Smoker', 'MentHlth', 'HvyAlcoholConsump']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck', 'Income', 'PhysActivity', 'Smoker', 'MentHlth', 'HvyAlcoholConsump']

======================================================================
MRMR + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D01E510>
DODA Pipeline Started
Running: MRMR
Operator Scores:
{'MRMR_1': {'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'GenHlth': 1.0, 'HighBP': 0.9523809523809523, 'BMI': 0.9047619047619048, 'HighChol': 0.8571428571428571, 'DiffWalk': 0.8095238095238095, 'HeartDiseaseorAttack': 0.7619047619047619, 'Age': 0.7142857142857143, 'Income': 0.6666666666666666, 'PhysHlth': 0.6190476190476191, 'HvyAlcoholConsump': 0.5714285714285714, 'CholCheck': 0.5238095238095238, 'Stroke': 0.47619047619047616, 'PhysActivity': 0.42857142857142855, 'Education': 0.38095238095238093, 'Veggies': 0.3333333333333333, 'Smoker': 0.2857142857142857, 'MentHlth': 0.23809523809523808, 'Sex': 0.19047619047619047, 'AnyHealthcare': 0.14285714285714285, 'Fruits': 0.09523809523809523, 'NoDocbcCost': 0.047619047619047616}

Normalized Mathematical Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.8571428571428571), 'DiffWalk': np.float64(0.8095238095238095), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.7142857142857143), 'Income': np.float64(0.6666666666666666), 'PhysHlth': np.float64(0.6190476190476191), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'CholCheck': np.float64(0.5238095238095238), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.42857142857142855), 'Education': np.float64(0.38095238095238093), 'Veggies': np.float64(0.3333333333333333), 'Smoker': np.float64(0.2857142857142857), 'MentHlth': np.float64(0.23809523809523808), 'Sex': np.float64(0.19047619047619047), 'AnyHealthcare': np.float64(0.14285714285714285), 'Fruits': np.float64(0.09523809523809523), 'NoDocbcCost': np.float64(0.047619047619047616)}

Clinical Weights
{'GenHlth': 1.0, 'HighBP': 1.0, 'BMI': 1.0, 'HighChol': 0.9, 'DiffWalk': 0.9, 'HeartDiseaseorAttack': 1.0, 'Age': 0.9, 'Income': 0.3, 'PhysHlth': 0.8, 'HvyAlcoholConsump': 0.2, 'CholCheck': 0.4, 'Stroke': 1.0, 'PhysActivity': 0.4, 'Education': 0.3, 'Veggies': 0.2, 'Smoker': 0.6, 'MentHlth': 0.5, 'Sex': 0.2, 'AnyHealthcare': 0.2, 'Fruits': 0.2, 'NoDocbcCost': 0.2}

Final DODA Scores
{'GenHlth': np.float64(1.0), 'HighBP': np.float64(0.9523809523809523), 'BMI': np.float64(0.9047619047619048), 'HighChol': np.float64(0.7714285714285714), 'DiffWalk': np.float64(0.7285714285714286), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'Age': np.float64(0.6428571428571429), 'Income': np.float64(0.19999999999999998), 'PhysHlth': np.float64(0.49523809523809526), 'HvyAlcoholConsump': np.float64(0.11428571428571428), 'CholCheck': np.float64(0.20952380952380956), 'Stroke': np.float64(0.47619047619047616), 'PhysActivity': np.float64(0.17142857142857143), 'Education': np.float64(0.11428571428571427), 'Veggies': np.float64(0.06666666666666667), 'Smoker': np.float64(0.1714285714285714), 'MentHlth': np.float64(0.11904761904761904), 'Sex': np.float64(0.0380952380952381), 'AnyHealthcare': np.float64(0.02857142857142857), 'Fruits': np.float64(0.01904761904761905), 'NoDocbcCost': np.float64(0.009523809523809525)}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck', 'Income', 'PhysActivity', 'Smoker', 'MentHlth', 'HvyAlcoholConsump', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'CholCheck', 'Income', 'PhysActivity', 'Smoker', 'MentHlth', 'HvyAlcoholConsump', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

======================================================================
MRMR + DODA FEATURE SELECTION COMPLETED
======================================================================

In [21]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = mrmr_doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
0                GenHlth        1.000000               1.000000
1                 HighBP        0.952381               0.952381
2                    BMI        0.904762               0.904762
3               HighChol        0.857143               0.857143
4               DiffWalk        0.809524               0.809524
5   HeartDiseaseorAttack        0.761905               0.761905
6                    Age        0.714286               0.714286
7                 Income        0.666667               0.666667
8               PhysHlth        0.619048               0.619048
9      HvyAlcoholConsump        0.571429               0.571429
10             CholCheck        0.523810               0.523810
11                Stroke        0.476190               0.476190
12          PhysActivity        0.428571               0.428571
13             Education        0.380952               0.380952
14               Veggies        0.333333               0.333333
15                Smoker        0.285714               0.285714
16              MentHlth        0.238095               0.238095
17                   Sex        0.190476               0.190476
18         AnyHealthcare        0.142857               0.142857
19                Fruits        0.095238               0.095238
20           NoDocbcCost        0.047619               0.047619

In [22]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                GenHlth              1.0
1                 HighBP              1.0
2                    BMI              1.0
11                Stroke              1.0
5   HeartDiseaseorAttack              1.0
4               DiffWalk              0.9
3               HighChol              0.9
6                    Age              0.9
8               PhysHlth              0.8
15                Smoker              0.6
16              MentHlth              0.5
12          PhysActivity              0.4
10             CholCheck              0.4
13             Education              0.3
7                 Income              0.3
9      HvyAlcoholConsump              0.2
14               Veggies              0.2
17                   Sex              0.2
18         AnyHealthcare              0.2
19                Fruits              0.2
20           NoDocbcCost              0.2

In [23]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
0                GenHlth          1.000000
1                 HighBP          0.952381
2                    BMI          0.904762
3               HighChol          0.771429
5   HeartDiseaseorAttack          0.761905
4               DiffWalk          0.728571
6                    Age          0.642857
8               PhysHlth          0.495238
11                Stroke          0.476190
10             CholCheck          0.209524
7                 Income          0.200000
12          PhysActivity          0.171429
15                Smoker          0.171429
16              MentHlth          0.119048
9      HvyAlcoholConsump          0.114286
13             Education          0.114286
14               Veggies          0.066667
17                   Sex          0.038095
18         AnyHealthcare          0.028571
19                Fruits          0.019048
20           NoDocbcCost          0.009524

In [24]:
selector.get_selected_features()

['GenHlth',
 'HighBP',
 'BMI',
 'HighChol',
 'HeartDiseaseorAttack',
 'DiffWalk',
 'Age',
 'PhysHlth',
 'Stroke',
 'CholCheck']

In [25]:
comparison = selector.compare_scores()

comparison

======================================================================
MATHEMATICAL vs CLINICAL vs HADAMARDFUSION
======================================================================

Fusion Method: HadamardFusion

Top Features After Fusion:
                Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0               GenHlth          1              1           1            0
1                HighBP          2              2           2            0
2                   BMI          3              3           3            0
3              HighChol          4              6           4            0
4  HeartDiseaseorAttack          6              4           5            1
5              DiffWalk          5              7           6           -1
6                   Age          7              8           7            0
7              PhysHlth          9              9           8            1
8                Stroke         12              5           9            3
9             CholCheck         11             12          10            1

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,GenHlth,1,1.0000,1,1.0,1,1.0000,0
1,HighBP,2,0.9524,2,1.0,2,0.9524,0
2,BMI,3,0.9048,3,1.0,3,0.9048,0
3,HighChol,4,0.8571,6,0.9,4,0.7714,0
4,HeartDiseaseorAttack,6,0.7619,4,1.0,5,0.7619,1
5,DiffWalk,5,0.8095,7,0.9,6,0.7286,-1
6,Age,7,0.7143,8,0.9,7,0.6429,0
7,PhysHlth,9,0.6190,9,0.8,8,0.4952,1
8,Stroke,12,0.4762,5,1.0,9,0.4762,3
9,CholCheck,11,0.5238,12,0.4,10,0.2095,1
10,Income,8,0.6667,14,0.3,11,0.2000,-3
11,PhysActivity,13,0.4286,13,0.4,12,0.1714,1
12,Smoker,16,0.2857,10,0.6,13,0.1714,3
13,MentHlth,17,0.2381,11,0.5,14,0.1190,3
14,HvyAlcoholConsump,10,0.5714,16,0.2,15,0.1143,-5
15,Education,14,0.3810,15,0.3,16,0.1143,-2
16,Veggies,15,0.3333,17,0.2,17,0.0667,-2
17,Sex,18,0.1905,18,0.2,18,0.0381,0
18,AnyHealthcare,19,0.1429,19,0.2,19,0.0286,0
19,Fruits,20,0.0952,20,0.2,20,0.0190,0
20,NoDocbcCost,21,0.0476,21,0.2,21,0.0095,0

In [26]:
# =============================================================================
# MRMR + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


mrmr_doda_model_results = []


# =============================================================================
# EVALUATE EACH TOP-K
# =============================================================================

for k in k_values:

    Xtr = mrmr_doda_results[k]["X_train"]

    Xts = mrmr_doda_results[k]["X_test"]

    features = ", ".join(
        mrmr_doda_results[k]["features"]
    )


    # -------------------------------------------------------------------------
    # Evaluate each ML model
    # -------------------------------------------------------------------------

    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        # Predictions
        y_pred = model.predict(
            Xts
        )


        # Probability predictions
        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        # ---------------------------------------------------------------------
        # Store results
        # ---------------------------------------------------------------------

        mrmr_doda_model_results.append({

            "Method": "MRMR + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


# =============================================================================
# CREATE RESULTS DATAFRAME
# =============================================================================

mrmr_doda_results_df = pd.DataFrame(
    mrmr_doda_model_results
)


display(mrmr_doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,MRMR + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714261,0.313140,0.727597,0.437843,0.793300
1,MRMR + DODA,5,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.715786,0.313986,0.724462,0.438098,0.790212
2,MRMR + DODA,5,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.703955,0.308133,0.751389,0.437042,0.796183
3,MRMR + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.712975,0.316954,0.759082,0.447186,0.806608
4,MRMR + DODA,10,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.767905,0.315901,0.444080,0.369182,0.715571
5,MRMR + DODA,10,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.706286,0.312909,0.769768,0.444948,0.809073
6,MRMR + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714304,0.317476,0.754951,0.446984,0.809135
7,MRMR + DODA,15,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.821440,0.362873,0.221684,0.275228,0.748295
8,MRMR + DODA,15,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.709445,0.315235,0.767631,0.446933,0.810423
9,MRMR + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714304,0.318260,0.760080,0.448659,0.810583
10,MRMR + DODA,20,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.842292,0.453185,0.151019,0.226544,0.776487
11,MRMR + DODA,20,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.712997,0.319040,0.772760,0.451624,0.811831

In [27]:
mrmr_doda_results_df.to_csv(
    "../../../results/diabetes/doda/mrmr_doda_results.csv",
    index=False
)

In [28]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        mrmr_results_df,
        mrmr_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,MRMR,5,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.708552,0.308374,0.728736,0.433364,0.791913
1,MRMR,5,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.703366,0.305629,0.738709,0.432372,0.786967
2,MRMR,5,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk",0.691077,0.299927,0.764496,0.430831,0.794595
3,MRMR,10,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714631,0.317631,0.754096,0.446987,0.807581
4,MRMR,10,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.794161,0.325825,0.323550,0.324684,0.723269
5,MRMR,10,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.709228,0.315137,0.768201,0.446931,0.808270
6,MRMR,15,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714806,0.318198,0.756803,0.448024,0.809239
7,MRMR,15,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.822290,0.362515,0.213563,0.268782,0.751129
8,MRMR,15,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.710818,0.316767,0.770053,0.448883,0.810332
9,MRMR,20,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.714304,0.318260,0.760080,0.448659,0.810583
10,MRMR,20,Random Forest,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.843621,0.466582,0.157145,0.235106,0.776711
11,MRMR,20,XGBoost,"GenHlth, HighBP, BMI, HighChol, DiffWalk, Hear...",0.712997,0.319040,0.772760,0.451624,0.811831
12,MRMR + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714261,0.313140,0.727597,0.437843,0.793300
13,MRMR + DODA,5,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.715786,0.313986,0.724462,0.438098,0.790212
14,MRMR + DODA,5,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.703955,0.308133,0.751389,0.437042,0.796183
15,MRMR + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.712975,0.316954,0.759082,0.447186,0.806608
16,MRMR + DODA,10,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.767905,0.315901,0.444080,0.369182,0.715571
17,MRMR + DODA,10,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.706286,0.312909,0.769768,0.444948,0.809073
18,MRMR + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714304,0.317476,0.754951,0.446984,0.809135
19,MRMR + DODA,15,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.821440,0.362873,0.221684,0.275228,0.748295
20,MRMR + DODA,15,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.709445,0.315235,0.767631,0.446933,0.810423
21,MRMR + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.714304,0.318260,0.760080,0.448659,0.810583
22,MRMR + DODA,20,Random Forest,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.842292,0.453185,0.151019,0.226544,0.776487
23,MRMR + DODA,20,XGBoost,"GenHlth, HighBP, BMI, HighChol, HeartDiseaseor...",0.712997,0.319040,0.772760,0.451624,0.811831

In [29]:
# ============================================================
# mRMR + DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer

from doda import DODASelector
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# MRMR ADAPTER
# ============================================================

from mrmr import mrmr_classif


class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # --------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # --------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # --------------------------------------------------------
        # Store importance
        # --------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "clinical_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should contain the ORIGINAL Heart Disease data
# before imputation/scaling.
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"mRMR + DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0


    # ========================================================
    # 25 REPEATED CV RUNS
    # ========================================================

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()


        # ----------------------------------------------------
        # IMPUTATION
        # ----------------------------------------------------

        imputer = SimpleImputer(
            strategy="median"
        )

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )


        # ----------------------------------------------------
        # mRMR OPERATOR
        # ----------------------------------------------------

        mrmr_operator = MRMRAdapter()


        # ----------------------------------------------------
        # CLINICAL KNOWLEDGE PROVIDER
        # ----------------------------------------------------

        provider = JSONProvider(
            WEIGHTS_FILE
        )


        # ----------------------------------------------------
        # DODA SELECTOR
        # ----------------------------------------------------

        doda_selector = DODASelector(

            operators=[mrmr_operator],

            provider=provider,

            fusion=RankFusion(),

            top_k=TOP_K

        )


        # ----------------------------------------------------
        # FIT ONLY ON TRAINING FOLD
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )


        # ----------------------------------------------------
        # SELECTED FEATURES
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )


        selected_feature_sets.append(
            set(selected_features)
        )


        all_runs.append({

            "Top_K": TOP_K,

            "Run": run_number,

            "Selected_Features": selected_features

        })


        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []


    for i in range(
        len(selected_feature_sets)
    ):

        for j in range(
            i + 1,
            len(selected_feature_sets)
        ):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]


            intersection = len(
                set_a.intersection(set_b)
            )

            union = len(
                set_a.union(set_b)
            )


            jaccard = (
                intersection / union
            )


            jaccard_scores.append(
                jaccard
            )


            all_jaccard.append({

                "Top_K": TOP_K,

                "Run_A": i + 1,

                "Run_B": j + 1,

                "Jaccard_Similarity": jaccard

            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(
        jaccard_scores
    )

    std_jaccard = np.std(
        jaccard_scores
    )

    min_jaccard = np.min(
        jaccard_scores
    )

    max_jaccard = np.max(
        jaccard_scores
    )


    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(
        f"Number of runs:          "
        f"{len(selected_feature_sets)}"
    )

    print(
        f"Number of comparisons:   "
        f"{len(jaccard_scores)}"
    )

    print(
        f"Mean Jaccard Similarity: "
        f"{mean_jaccard:.4f}"
    )

    print(
        f"Standard Deviation:      "
        f"{std_jaccard:.4f}"
    )

    print(
        f"Minimum Jaccard:         "
        f"{min_jaccard:.4f}"
    )

    print(
        f"Maximum Jaccard:         "
        f"{max_jaccard:.4f}"
    )


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}


    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )


    for feature, count in feature_counts.items():

        all_frequency.append({

            "Top_K": TOP_K,

            "Feature": feature,

            "Selection_Count": count,

            "Selection_Frequency":
                count / len(selected_feature_sets)

        })


    frequency_df_topk = pd.DataFrame(

        [

            {

                "Feature": feature,

                "Selection_Count": count,

                "Selection_Frequency":
                    count / len(selected_feature_sets)

            }

            for feature, count
            in feature_counts.items()

        ]

    ).sort_values(

        "Selection_Frequency",

        ascending=False

    )


    print(
        "\nFEATURE SELECTION FREQUENCY"
    )

    print(
        frequency_df_topk.to_string(
            index=False
        )
    )


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(
    all_runs
)

jaccard_df = pd.DataFrame(
    all_jaccard
)

frequency_df = pd.DataFrame(
    all_frequency
)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []


for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]


    summary_rows.append({

        "Top_K": TOP_K,

        "Mean_Jaccard":
            subset.mean(),

        "Std_Jaccard":
            subset.std(),

        "Min_Jaccard":
            subset.min(),

        "Max_Jaccard":
            subset.max()

    })


summary_df = pd.DataFrame(
    summary_rows
)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("mRMR + DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(

    summary_df.to_string(

        index=False,

        float_format=lambda x:
            f"{x:.4f}"

    )

)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/diabetes/"
    "mrmr_doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/diabetes/"
    "mrmr_doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/diabetes/"
    "mrmr_doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/diabetes/"
    "mrmr_doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")

print(
    "1. mrmr_doda_stability_all_topk_runs.csv"
)

print(
    "2. mrmr_doda_stability_all_topk_jaccard.csv"
)

print(
    "3. mrmr_doda_stability_all_topk_frequency.csv"
)

print(
    "4. mrmr_doda_stability_all_topk_summary.csv"
)

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D05D810>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.44it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 01: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001924087D1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.65it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 02: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EE67230>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.62it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 03: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EE675C0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.65it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 04: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264B1CA70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.62it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 05: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EE6B350>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.63it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 06: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EE6B130>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.63it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 07: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D008C50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.65it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 08: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EEAE650>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.69it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 09: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001924088AD50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.67it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 10: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240878230>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.66it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 11: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EEA5D30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.63it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 12: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400F8670>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.33it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 13: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400EB790>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.34it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 14: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D024950>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.35it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 15: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001924006D0D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 16: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240863CD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 17: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192408D68E0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 18: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192408C8730>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 19: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192408BF9D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.35it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 20: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EE63D10>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.33it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 21: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400F2CD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol']
Run 22: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400F2F50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 23: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926D06D860>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.32it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 24: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240859080>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Run 25: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

----------------------------------------------------------------------
TOP-5 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 1.0000
Standard Deviation:      0.0000
Minimum Jaccard:         1.0000
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
             Feature  Selection_Count  Selection_Frequency
                 BMI               25                  1.0
HeartDiseaseorAttack               25                  1.0
              HighBP               25                  1.0
            HighChol               25                  1.0
             GenHlth               25                  1.0

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-10
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF879B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 01: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.33it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 02: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBDD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 03: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 04: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB050>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.32it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 05: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE5F70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 06: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 07: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6330>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.34it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 08: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 09: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 10: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB770>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 11: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 12: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 13: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE5FD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 14: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE61B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 15: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 16: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6150>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.35it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 17: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.34it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 18: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE5F70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.35it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 19: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE61B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.46it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 20: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 21: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.65it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 22: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.69it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 23: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6150>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.70it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 24: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6090>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.72it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
Run 25: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

----------------------------------------------------------------------
TOP-10 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 1.0000
Standard Deviation:      0.0000
Minimum Jaccard:         1.0000
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
             Feature  Selection_Count  Selection_Frequency
                 BMI               25                  1.0
              Income               25                  1.0
HeartDiseaseorAttack               25                  1.0
              HighBP               25                  1.0
            DiffWalk               25                  1.0
              Stroke               25                  1.0
            HighChol               25                  1.0
                 Age               25                  1.0
            PhysHlth               25                  1.0
             GenHlth               25                  1.0

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-15
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.69it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 01: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.68it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 02: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.68it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 03: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6150>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.67it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 04: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6090>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.69it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 05: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.69it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']
Run 06: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB6B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.70it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 07: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 08: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.84it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 09: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB230>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 10: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB590>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.94it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 11: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 12: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 13: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBBF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 14: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB5F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education']
Run 15: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 16: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.94it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 17: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 18: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.95it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 19: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 20: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBF50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Run 21: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.91it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 22: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Run 23: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB770>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education']
Run 24: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']
Run 25: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']

----------------------------------------------------------------------
TOP-15 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 0.9375
Standard Deviation:      0.0625
Minimum Jaccard:         0.8750
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
             Feature  Selection_Count  Selection_Frequency
                 BMI               25                  1.0
        PhysActivity               25                  1.0
           CholCheck               25                  1.0
              Income               25                  1.0
              HighBP               25                  1.0
HeartDiseaseorAttack               25                  1.0
              Smoker               25                  1.0
   HvyAlcoholConsump               25                  1.0
                 Age               25                  1.0
            DiffWalk               25                  1.0
              Stroke               25                  1.0
            HighChol               25                  1.0
             GenHlth               25                  1.0
            PhysHlth               25                  1.0
           Education               15                  0.6
            MentHlth               10                  0.4

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-20
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 01: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 02: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 03: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400270B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.31it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 04: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB950>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 05: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 06: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 07: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6210>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 08: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 09: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBBF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 10: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE5FD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 11: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 12: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE5F70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 13: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 14: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB950>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 15: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB590>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 16: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019240071970>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 17: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6330>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 18: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BAF90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 19: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB3B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 20: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BB230>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 21: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001925DF87890>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 22: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000019264AE6150>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 23: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400BBE90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 24: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000192400271D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.37it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
Run 25: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

----------------------------------------------------------------------
TOP-20 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 1.0000
Standard Deviation:      0.0000
Minimum Jaccard:         1.0000
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
             Feature  Selection_Count  Selection_Frequency
           Education               25                  1.0
           CholCheck               25                  1.0
              Income               25                  1.0
             Veggies               25                  1.0
   HvyAlcoholConsump               25                  1.0
             GenHlth               25                  1.0
       AnyHealthcare               25                  1.0
              Stroke               25                  1.0
            HighChol               25                  1.0
                 Age               25                  1.0
            MentHlth               25                  1.0
                 Sex               25                  1.0
            DiffWalk               25                  1.0
            PhysHlth               25                  1.0
                 BMI               25                  1.0
        PhysActivity               25                  1.0
HeartDiseaseorAttack               25                  1.0
              HighBP               25                  1.0
              Fruits               25                  1.0
              Smoker               25                  1.0

======================================================================
mRMR + DODA STABILITY — ALL TOP-K VALUES
======================================================================
 Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
     5        1.0000       0.0000       1.0000       1.0000
    10        1.0000       0.0000       1.0000       1.0000
    15        0.9375       0.0626       0.8750       1.0000
    20        1.0000       0.0000       1.0000       1.0000

Files saved:
1. mrmr_doda_stability_all_topk_runs.csv
2. mrmr_doda_stability_all_topk_jaccard.csv
3. mrmr_doda_stability_all_topk_frequency.csv
4. mrmr_doda_stability_all_topk_summary.csv

In [30]:
# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from mrmr import mrmr_classif

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# =============================================================================
# MRMR ADAPTER
# =============================================================================

class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # ---------------------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # ---------------------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # ---------------------------------------------------------------------
        # Store importance
        # ---------------------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"


# =============================================================================
# CONFIGURATION
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

target_column = "Diabetes_binary"

X = df.drop(columns=[target_column])
y = df[target_column]

feature_names = X.columns.tolist()


# =============================================================================
# MODELS
# =============================================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# =============================================================================
# CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

provider = JSONProvider(
    "clinical_weights.json"
)


# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# =============================================================================
# RESULTS STORAGE
# =============================================================================

results = []


# =============================================================================
# CROSS-VALIDATION LOOP
# =============================================================================

for run_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    print("\n" + "=" * 80)
    print(f"REPEATED STRATIFIED CV RUN {run_number}")
    print("=" * 80)

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # =========================================================================
    # IMPUTATION
    # =========================================================================

    imputer = SimpleImputer(
        strategy="median"
    )

    X_train_imp_array = imputer.fit_transform(
        X_train
    )

    X_test_imp_array = imputer.transform(
        X_test
    )

    X_train_imp = pd.DataFrame(
        X_train_imp_array,
        columns=feature_names,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        X_test_imp_array,
        columns=feature_names,
        index=X_test.index
    )


    # =========================================================================
    # FEATURE SELECTION FOR EACH TOP-K VALUE
    # =========================================================================

    for top_k in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"TOP-K = {top_k}")
        print("-" * 80)


        # =====================================================================
        # BASELINE mRMR FEATURE SELECTION
        # =====================================================================

        mrmr_selected_features = mrmr_classif(
            X=X_train_imp,
            y=y_train,
            K=top_k
        )

        mrmr_features = list(
            mrmr_selected_features
        )

        print("mRMR-selected features:")
        print(mrmr_features)


        # =====================================================================
        # DODA-mRMR FEATURE SELECTION
        # =====================================================================

        mrmr_operator = MRMRAdapter()

        doda_selector = DODASelector(
            operators=[mrmr_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        doda_features = list(
            doda_selector.get_selected_features()
        )

        print("DODA-selected features:")
        print(doda_features)


        # =====================================================================
        # PREPARE SELECTED FEATURE MATRICES
        # =====================================================================

        X_train_mrmr_selected = (
            X_train_imp[mrmr_features]
        )

        X_test_mrmr_selected = (
            X_test_imp[mrmr_features]
        )

        X_train_doda_selected = (
            X_train_imp[doda_features]
        )

        X_test_doda_selected = (
            X_test_imp[doda_features]
        )


        # =====================================================================
        # MODEL EVALUATION
        # =====================================================================

        selected_feature_sets = {

            "mRMR": (
                X_train_mrmr_selected,
                X_test_mrmr_selected,
                mrmr_features
            ),

            "DODA": (
                X_train_doda_selected,
                X_test_doda_selected,
                doda_features
            )

        }


        for method, (
            X_train_selected,
            X_test_selected,
            selected_features
        ) in selected_feature_sets.items():

            for model_name, model_template in models.items():

                model = clone(
                    model_template
                )

                X_train_model = (
                    X_train_selected.copy()
                )

                X_test_model = (
                    X_test_selected.copy()
                )


                # -------------------------------------------------------------
                # Scale only Logistic Regression
                # -------------------------------------------------------------

                if model_name == "Logistic Regression":

                    model_scaler = StandardScaler()

                    X_train_model = (
                        model_scaler.fit_transform(
                            X_train_model
                        )
                    )

                    X_test_model = (
                        model_scaler.transform(
                            X_test_model
                        )
                    )


                # -------------------------------------------------------------
                # Train model
                # -------------------------------------------------------------

                model.fit(
                    X_train_model,
                    y_train
                )

                y_pred = model.predict(
                    X_test_model
                )

                y_prob = model.predict_proba(
                    X_test_model
                )[:, 1]


                # -------------------------------------------------------------
                # Calculate metrics
                # -------------------------------------------------------------

                accuracy = accuracy_score(
                    y_test,
                    y_pred
                )

                precision = precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                roc_auc = roc_auc_score(
                    y_test,
                    y_prob
                )


                # -------------------------------------------------------------
                # Store results
                # -------------------------------------------------------------

                results.append({

                    "Run": run_number,

                    "Method": method,

                    "Top_K": top_k,

                    "Model": model_name,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": roc_auc,

                    "Selected_Features": selected_features

                })


# =============================================================================
# RESULTS DATAFRAME
# =============================================================================

results_df = pd.DataFrame(
    results
)


# =============================================================================
# DISPLAY RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("REPEATED STRATIFIED CV RESULTS — mRMR VS DODA-mRMR")
print("=" * 80)

display(
    results_df.head()
)

print(
    "Total evaluation rows:",
    len(results_df)
)

================================================================================
REPEATED STRATIFIED CV RUN 1
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.70it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.47it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.40it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:06<00:00,  2.35it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.29it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:14<00:00,  1.35it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 2
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.74it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.42it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.54it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.41it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:06<00:00,  2.36it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:17<00:00,  1.23it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:14<00:00,  1.34it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.41it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 3
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.87it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.81it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.60it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.83it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.80it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.92it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 4
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.07it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.88it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.84it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.91it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.65it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.80it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.92it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 5
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.67it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.49it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:06<00:00,  2.33it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.29it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:15<00:00,  1.32it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.36it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 6
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.59it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.48it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.63it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.76it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.82it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.89it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 7
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.11it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.47it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.39it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:06<00:00,  2.30it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.30it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:12<00:00,  1.56it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:13<00:00,  1.61it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 8
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.98it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.88it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.99it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.63it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.74it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.84it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.82it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.84it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 9
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.97it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.92it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.81it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.81it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:04<00:00,  3.44it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:15<00:00,  1.35it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.72it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.73it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 10
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.96it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.64it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.40it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.61it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.77it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.77it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.84it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 11
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.13it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.80it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.65it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.74it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.80it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.86it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 12
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.11it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.89it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.89it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.65it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.78it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:12<00:00,  1.67it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.72it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 13
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.20it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.83it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.79it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.86it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.58it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.73it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 14
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.10it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.80it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.83it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.51it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.78it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 15
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.16it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.83it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.65it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.80it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.79it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'Smoker', 'PhysActivity', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 16
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.97it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.82it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.88it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.70it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:10<00:00,  1.82it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 17
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.13it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.86it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.94it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.89it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.60it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.79it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.77it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.73it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 18
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:02<00:00,  2.44it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.45it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.90it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:12<00:00,  1.66it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.91it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  2.00it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:12<00:00,  1.59it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.90it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 19
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.10it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.84it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.96it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.83it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.60it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.82it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.81it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.96it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 20
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.28it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.94it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.83it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.86it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.67it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.86it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:11<00:00,  1.71it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.83it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 21
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.27it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.91it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:02<00:00,  3.36it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:09<00:00,  2.12it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.68it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:13<00:00,  1.58it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:09<00:00,  2.14it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  2.00it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 22
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.77it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:13<00:00,  1.59it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.86it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:14<00:00,  1.49it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:07<00:00,  2.14it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.80it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:09<00:00,  2.05it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:09<00:00,  2.11it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.8095238095238095), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.7619047619047619), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03177805800756621, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.03128054740957967, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HeartDiseaseorAttack', 'HighChol', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 23
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.13it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  2.09it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.15it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  2.07it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:05<00:00,  2.69it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.82it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:10<00:00,  1.82it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'PhysActivity', 'Education', 'Veggies', 'MentHlth', 'Smoker', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.89it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.23809523809523808), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.42857142857142855), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.2857142857142857), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028612012987012988, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02854251012145749, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Smoker', 'MentHlth', 'Education', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 24
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  2.53it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.25it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:05<00:00,  1.88it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:17<00:00,  1.21it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:09<00:00,  1.64it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'PhysActivity', 'Stroke', 'Education', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:16<00:00,  1.31it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:14<00:00,  1.40it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'PhysActivity', 'Stroke', 'Education', 'Veggies', 'Smoker', 'MentHlth', 'Sex', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:13<00:00,  1.52it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.2857142857142857), 'Stroke': np.float64(0.42857142857142855), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.47619047619047616), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.19047619047619047), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.38095238095238093), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03009207275993712, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.027526395173453996, 'Age': 0.031054405392392875, 'Education': 0.028438886647841874, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'PhysActivity', 'HvyAlcoholConsump', 'Smoker', 'Education', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RUN 25
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:01<00:00,  3.83it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:09<00:00,  2.14it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.89it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  2.06it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------

100%|██████████| 15/15 [00:06<00:00,  2.33it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:11<00:00,  1.81it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------

100%|██████████| 20/20 [00:10<00:00,  1.88it/s]

mRMR-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Age', 'Income', 'PhysHlth', 'HvyAlcoholConsump', 'CholCheck', 'Stroke', 'Education', 'PhysActivity', 'Veggies', 'Sex', 'MentHlth', 'Smoker', 'AnyHealthcare', 'Fruits']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001926EF1B1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 21/21 [00:10<00:00,  1.97it/s]

Operator Scores:
{'MRMR_1': {'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.9523809523809523), 'HighChol': np.float64(0.8571428571428571), 'CholCheck': np.float64(0.5238095238095238), 'BMI': np.float64(0.9047619047619048), 'Smoker': np.float64(0.19047619047619047), 'Stroke': np.float64(0.47619047619047616), 'HeartDiseaseorAttack': np.float64(0.7619047619047619), 'PhysActivity': np.float64(0.38095238095238093), 'Fruits': np.float64(0.09523809523809523), 'Veggies': np.float64(0.3333333333333333), 'HvyAlcoholConsump': np.float64(0.5714285714285714), 'AnyHealthcare': np.float64(0.14285714285714285), 'NoDocbcCost': np.float64(0.047619047619047616), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.23809523809523808), 'PhysHlth': np.float64(0.6190476190476191), 'DiffWalk': np.float64(0.8095238095238095), 'Sex': np.float64(0.2857142857142857), 'Age': np.float64(0.7142857142857143), 'Education': np.float64(0.42857142857142855), 'Income': np.float64(0.6666666666666666)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.031754032258064516, 'CholCheck': 0.029236022193768675, 'BMI': 0.032266458495966696, 'Smoker': 0.02844551282051282, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.031544957774465976, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.027205882352941177, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.028991596638655463, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.028371628371628373, 'PhysHlth': 0.03036576949620428, 'DiffWalk': 0.0315136476426799, 'Sex': 0.02786377708978328, 'Age': 0.031054405392392875, 'Education': 0.02862400327131466, 'Income': 0.029631255487269532}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']
DODA-selected features:
['GenHlth', 'HighBP', 'BMI', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Age', 'PhysHlth', 'Stroke', 'Income', 'CholCheck', 'HvyAlcoholConsump', 'PhysActivity', 'Education', 'Smoker', 'MentHlth', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

================================================================================
REPEATED STRATIFIED CV RESULTS — mRMR VS DODA-mRMR
================================================================================

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,mRMR,5,Logistic Regression,0.850202,0.543849,0.127226,0.206212,0.788804,"[GenHlth, HighBP, BMI, HighChol, DiffWalk]"
1,1,mRMR,5,Random Forest,0.851313,0.559127,0.131358,0.212737,0.787067,"[GenHlth, HighBP, BMI, HighChol, DiffWalk]"
2,1,mRMR,5,XGBoost,0.852402,0.579805,0.126799,0.208090,0.793961,"[GenHlth, HighBP, BMI, HighChol, DiffWalk]"
3,1,DODA,5,Logistic Regression,0.851138,0.556564,0.131073,0.212177,0.790357,"[GenHlth, HighBP, BMI, HighChol, HeartDiseaseo..."
4,1,DODA,5,Random Forest,0.852184,0.574320,0.129363,0.211163,0.789398,"[GenHlth, HighBP, BMI, HighChol, HeartDiseaseo..."

Total evaluation rows: 600

In [31]:
# =============================================================================
# PREPARE FEATURE SETS FOR STABILITY ANALYSIS
# mRMR VS DODA-mRMR
# =============================================================================

import ast
import numpy as np
import pandas as pd


# =============================================================================
# CONVERT SELECTED FEATURES TO SET
# =============================================================================

def convert_to_set(features):
    """
    Convert Selected_Features into a Python set.
    Handles lists, tuples, NumPy arrays, and strings.
    """

    if isinstance(features, str):

        # Handle string representation of a list
        if features.startswith("[") and features.endswith("]"):

            try:
                features = ast.literal_eval(features)

            except Exception:
                features = features.split(",")

        else:
            features = features.split(",")


    return {
        str(feature).strip().strip("'").strip('"')
        for feature in features
        if str(feature).strip()
    }


# =============================================================================
# USE ONLY ONE MODEL
# =============================================================================

# Feature selection is independent of the predictive model.
# Therefore, Logistic Regression rows are sufficient.

stability_df = results_df[
    results_df["Model"] == "Logistic Regression"
].copy()


# =============================================================================
# CONVERT FEATURE LISTS TO SETS
# =============================================================================

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(convert_to_set)
)


# =============================================================================
# CHECK RESULTS
# =============================================================================

print("=" * 80)
print("FEATURE SETS PREPARED FOR STABILITY ANALYSIS")
print("=" * 80)

print(
    "Rows used for stability analysis:",
    len(stability_df)
)


# =============================================================================
# DISPLAY SAMPLE
# =============================================================================

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head(10)
)


# =============================================================================
# CHECK FEATURE COUNT
# =============================================================================

stability_df["Feature_Count"] = (
    stability_df["Feature_Set"]
    .apply(len)
)


print("\nFeature count check:")

display(
    stability_df[
        [
            "Method",
            "Top_K",
            "Feature_Count"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Method", "Top_K"]
    )
)


# =============================================================================
# VERIFY EXPECTED TOP-K
# =============================================================================

invalid_rows = stability_df[
    stability_df["Feature_Count"] != stability_df["Top_K"]
]


if len(invalid_rows) == 0:

    print(
        "\n✓ All feature sets contain the expected number of features."
    )

else:

    print(
        "\n⚠ WARNING: Some feature sets do not match their Top-K value."
    )

    display(
        invalid_rows[
            [
                "Run",
                "Method",
                "Top_K",
                "Feature_Count",
                "Feature_Set"
            ]
        ]
    )

================================================================================
FEATURE SETS PREPARED FOR STABILITY ANALYSIS
================================================================================
Rows used for stability analysis: 200

    Run Method  Top_K                                        Feature_Set
0     1   mRMR      5         {BMI, HighBP, DiffWalk, HighChol, GenHlth}
3     1   DODA      5  {BMI, HeartDiseaseorAttack, HighBP, HighChol, ...
6     1   mRMR     10  {BMI, Income, HeartDiseaseorAttack, HighBP, Hv...
9     1   DODA     10  {BMI, Income, HeartDiseaseorAttack, HighBP, Di...
12    1   mRMR     15  {BMI, Education, PhysActivity, CholCheck, Inco...
15    1   DODA     15  {BMI, Education, PhysActivity, CholCheck, Inco...
18    1   mRMR     20  {Education, CholCheck, Income, Veggies, HvyAlc...
21    1   DODA     20  {Education, CholCheck, Income, Veggies, HvyAlc...
24    2   mRMR      5         {BMI, HighBP, DiffWalk, HighChol, GenHlth}
27    2   DODA      5  {BMI, HeartDiseaseorAttack, HighBP, HighChol, ...

Feature count check:

   Method  Top_K  Feature_Count
3    DODA      5              5
9    DODA     10             10
15   DODA     15             15
21   DODA     20             20
0    mRMR      5              5
6    mRMR     10             10
12   mRMR     15             15
18   mRMR     20             20

✓ All feature sets contain the expected number of features.

In [32]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# mRMR VS DODA-mRMR
# =============================================================================

selection_frequency = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]


        # -------------------------------------------------------------
        # Number of CV runs
        # -------------------------------------------------------------

        total_runs = len(subset)


        # -------------------------------------------------------------
        # All features appearing across the 25 runs
        # -------------------------------------------------------------

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )


        # -------------------------------------------------------------
        # Calculate selection frequency
        # -------------------------------------------------------------

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set
                in subset["Feature_Set"]
            )


            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100

            })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

selection_frequency_df = pd.DataFrame(
    selection_frequency
)


# =============================================================================
# SORT RESULTS
# =============================================================================

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


# =============================================================================
# DISPLAY
# =============================================================================

print("=" * 80)
print("FEATURE SELECTION FREQUENCY")
print("=" * 80)

display(
    selection_frequency_df
)

================================================================================
FEATURE SELECTION FREQUENCY
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,DODA,5,BMI,25,25,100.0
1,DODA,5,GenHlth,25,25,100.0
2,DODA,5,HeartDiseaseorAttack,25,25,100.0
3,DODA,5,HighBP,25,25,100.0
4,DODA,5,HighChol,25,25,100.0
...,...,...,...,...,...,...
97,mRMR,20,PhysHlth,25,25,100.0
98,mRMR,20,Sex,25,25,100.0
99,mRMR,20,Smoker,25,25,100.0
100,mRMR,20,Stroke,25,25,100.0
101,mRMR,20,Veggies,25,25,100.0

In [33]:
# =============================================================================
# TEST 2: JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Jaccard comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )

                union = len(
                    set_a.union(set_b)
                )


                if union == 0:
                    jaccard = 0.0

                else:
                    jaccard = (
                        intersection / union
                    )


                jaccard_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Union": union,

                    "Jaccard_Similarity": jaccard

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

jaccard_df = pd.DataFrame(
    jaccard_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("JACCARD SIMILARITY — PAIRWISE RESULTS")
print("=" * 80)

display(
    jaccard_df
)


# =============================================================================
# JACCARD SUMMARY
# =============================================================================

jaccard_summary = (
    jaccard_df
    .groupby(
        ["Method", "Top_K"]
    )["Jaccard_Similarity"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("JACCARD SIMILARITY SUMMARY")
print("=" * 80)

display(
    jaccard_summary
)

================================================================================
JACCARD SIMILARITY — PAIRWISE RESULTS
================================================================================

     Method  Top_K  Run_A  Run_B  Intersection  Union  Jaccard_Similarity
0      mRMR      5      1      2             5      5                 1.0
1      mRMR      5      1      3             5      5                 1.0
2      mRMR      5      1      4             5      5                 1.0
3      mRMR      5      1      5             5      5                 1.0
4      mRMR      5      1      6             5      5                 1.0
...     ...    ...    ...    ...           ...    ...                 ...
2395   DODA     20     22     24            20     20                 1.0
2396   DODA     20     22     25            20     20                 1.0
2397   DODA     20     23     24            20     20                 1.0
2398   DODA     20     23     25            20     20                 1.0
2399   DODA     20     24     25            20     20                 1.0

[2400 rows x 7 columns]

================================================================================
JACCARD SIMILARITY SUMMARY
================================================================================

  Method  Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0   DODA      5      1.000000     0.000000     1.000000          1.0
1   DODA     10      1.000000     0.000000     1.000000          1.0
2   DODA     15      0.937500     0.062604     0.875000          1.0
3   DODA     20      1.000000     0.000000     1.000000          1.0
4   mRMR      5      0.973333     0.090582     0.666667          1.0
5   mRMR     10      1.000000     0.000000     1.000000          1.0
6   mRMR     15      1.000000     0.000000     1.000000          1.0
7   mRMR     20      1.000000     0.000000     1.000000          1.0

In [34]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

Total number of features: 21
================================================================================
KUNCHEVA INDEX — PAIRWISE RESULTS
================================================================================

     Method  Top_K  Run_A  Run_B  Intersection  Kuncheva_Index
0      mRMR      5      1      2             5             1.0
1      mRMR      5      1      3             5             1.0
2      mRMR      5      1      4             5             1.0
3      mRMR      5      1      5             5             1.0
4      mRMR      5      1      6             5             1.0
...     ...    ...    ...    ...           ...             ...
2395   DODA     20     22     24            20             1.0
2396   DODA     20     22     25            20             1.0
2397   DODA     20     23     24            20             1.0
2398   DODA     20     23     25            20             1.0
2399   DODA     20     24     25            20             1.0

[2400 rows x 6 columns]

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

  Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0   DODA      5       1.000000      0.000000      1.000000           1.0
1   DODA     10       1.000000      0.000000      1.000000           1.0
2   DODA     15       0.883333      0.116862      0.766667           1.0
3   DODA     20       1.000000      0.000000      1.000000           1.0
4   mRMR      5       0.979000      0.071333      0.737500           1.0
5   mRMR     10       1.000000      0.000000      1.000000           1.0
6   mRMR     15       1.000000      0.000000      1.000000           1.0
7   mRMR     20       1.000000      0.000000      1.000000           1.0

In [35]:
# =============================================================================
# TEST 4: mRMR VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for top_k in sorted(stability_df["Top_K"].unique()):

    mrmr_subset = stability_df[
        (stability_df["Method"] == "mRMR") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    doda_subset = stability_df[
        (stability_df["Method"] == "DODA") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    # Match mRMR and DODA feature sets from the same CV run
    merged = pd.merge(
        mrmr_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "mRMR_Feature_Set"}
        ),
        doda_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "DODA_Feature_Set"}
        ),
        on="Run",
        how="inner"
    )

    for _, row in merged.iterrows():

        mrmr_set = row["mRMR_Feature_Set"]
        doda_set = row["DODA_Feature_Set"]

        # Common features
        intersection = len(
            mrmr_set.intersection(doda_set)
        )

        # Total unique features
        union = len(
            mrmr_set.union(doda_set)
        )

        # Jaccard agreement
        if union == 0:
            jaccard_agreement = 0.0
        else:
            jaccard_agreement = intersection / union

        agreement_results.append({
            "Top_K": top_k,
            "Run": row["Run"],
            "mRMR_Features": sorted(mrmr_set),
            "DODA_Features": sorted(doda_set),
            "Common_Features": sorted(
                mrmr_set.intersection(doda_set)
            ),
            "Common_Feature_Count": intersection,
            "Jaccard_Agreement": jaccard_agreement
        })


# Convert to DataFrame
agreement_df = pd.DataFrame(agreement_results)

display(agreement_df)

,Top_K,Run,mRMR_Features,DODA_Features,Common_Features,Common_Feature_Count,Jaccard_Agreement
0,5,1,"[BMI, DiffWalk, GenHlth, HighBP, HighChol]","[BMI, GenHlth, HeartDiseaseorAttack, HighBP, H...","[BMI, GenHlth, HighBP, HighChol]",4,0.666667
1,5,2,"[BMI, DiffWalk, GenHlth, HighBP, HighChol]","[BMI, GenHlth, HeartDiseaseorAttack, HighBP, H...","[BMI, GenHlth, HighBP, HighChol]",4,0.666667
2,5,3,"[BMI, DiffWalk, GenHlth, HighBP, HighChol]","[BMI, GenHlth, HeartDiseaseorAttack, HighBP, H...","[BMI, GenHlth, HighBP, HighChol]",4,0.666667
3,5,4,"[BMI, DiffWalk, GenHlth, HighBP, HighChol]","[BMI, GenHlth, HeartDiseaseorAttack, HighBP, H...","[BMI, GenHlth, HighBP, HighChol]",4,0.666667
4,5,5,"[BMI, DiffWalk, GenHlth, HighBP, HighChol]","[BMI, GenHlth, HeartDiseaseorAttack, HighBP, H...","[BMI, GenHlth, HighBP, HighChol]",4,0.666667
...,...,...,...,...,...,...,...
95,20,21,"[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...",20,1.000000
96,20,22,"[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...",20,1.000000
97,20,23,"[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...",20,1.000000
98,20,24,"[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...",20,1.000000
99,20,25,"[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...",20,1.000000

In [36]:
# =============================================================================
# mRMR VS DODA AGREEMENT SUMMARY
# =============================================================================

agreement_summary = (
    agreement_df
    .groupby("Top_K")["Jaccard_Agreement"]
    .agg(
        Mean_Agreement="mean",
        Std_Agreement="std",
        Min_Agreement="min",
        Max_Agreement="max"
    )
    .reset_index()
)

display(agreement_summary)

   Top_K  Mean_Agreement  Std_Agreement  Min_Agreement  Max_Agreement
0      5        0.680000       0.066667       0.666667       1.000000
1     10        0.818182       0.000000       0.818182       0.818182
2     15        0.830882       0.055147       0.764706       0.875000
3     20        1.000000       0.000000       1.000000       1.000000