In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# Random Forest

# 1. Baseline

In [10]:
# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION
# TOP-K = 5, 10, 15, 20
# =============================================================================

from sklearn.ensemble import RandomForestClassifier
import pandas as pd


# =============================================================================
# FIT RANDOM FOREST ON ALL TRAINING FEATURES
# =============================================================================

rf_selector = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


rf_selector.fit(
    X_train_scaled,
    y_train
)


# =============================================================================
# CREATE FEATURE IMPORTANCE DATAFRAME
# =============================================================================

rf_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "RF Importance": rf_selector.feature_importances_

})


# =============================================================================
# SORT FEATURES BY IMPORTANCE
# =============================================================================

rf_scores = rf_scores.sort_values(
    by="RF Importance",
    ascending=False
).reset_index(drop=True)


# =============================================================================
# TOP-K VALUES
# =============================================================================

k_values = [5, 10, 15, 20]

rf_results = {}


# =============================================================================
# SELECT TOP-K FEATURES
# =============================================================================

for k in k_values:

    top_features = (
        rf_scores
        .head(k)["Feature"]
        .tolist()
    )


    # -------------------------------------------------------------------------
    # Boolean mask for selecting columns
    # -------------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # -------------------------------------------------------------------------
    # Store results
    # -------------------------------------------------------------------------

    rf_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": rf_scores.head(k)

    }


    # -------------------------------------------------------------------------
    # Display results
    # -------------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} RANDOM FOREST FEATURES")
    print("=" * 70)

    print("\nSelected Features:")
    print(top_features)

    print("\nFeature Importance:")
    print(rf_scores.head(k))


# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION COMPLETED
# =============================================================================

======================================================================
TOP 5 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth']

Feature Importance:
    Feature  RF Importance
0       BMI       0.173505
1       Age       0.130559
2   GenHlth       0.090235
3    Income       0.088408
4  PhysHlth       0.073413
======================================================================
TOP 10 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker']

Feature Importance:
     Feature  RF Importance
0        BMI       0.173505
1        Age       0.130559
2    GenHlth       0.090235
3     Income       0.088408
4   PhysHlth       0.073413
5     HighBP       0.072852
6  Education       0.062088
7   MentHlth       0.055019
8   HighChol       0.036720
9     Smoker       0.029588
======================================================================
TOP 15 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk']

Feature Importance:
         Feature  RF Importance
0            BMI       0.173505
1            Age       0.130559
2        GenHlth       0.090235
3         Income       0.088408
4       PhysHlth       0.073413
5         HighBP       0.072852
6      Education       0.062088
7       MentHlth       0.055019
8       HighChol       0.036720
9         Smoker       0.029588
10        Fruits       0.029558
11           Sex       0.025366
12  PhysActivity       0.023618
13       Veggies       0.023308
14      DiffWalk       0.021686
======================================================================
TOP 20 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['BMI', 'Age', 'GenHlth', 'Income', 'PhysHlth', 'HighBP', 'Education', 'MentHlth', 'HighChol', 'Smoker', 'Fruits', 'Sex', 'PhysActivity', 'Veggies', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'HvyAlcoholConsump', 'AnyHealthcare']

Feature Importance:
                 Feature  RF Importance
0                    BMI       0.173505
1                    Age       0.130559
2                GenHlth       0.090235
3                 Income       0.088408
4               PhysHlth       0.073413
5                 HighBP       0.072852
6              Education       0.062088
7               MentHlth       0.055019
8               HighChol       0.036720
9                 Smoker       0.029588
10                Fruits       0.029558
11                   Sex       0.025366
12          PhysActivity       0.023618
13               Veggies       0.023308
14              DiffWalk       0.021686
15  HeartDiseaseorAttack       0.017280
16           NoDocbcCost       0.012788
17                Stroke       0.010267
18     HvyAlcoholConsump       0.009578
19         AnyHealthcare       0.007810

In [11]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [12]:
# =============================================================================
# RANDOM FOREST FEATURE SELECTION — MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_model_results = []


for k in k_values:

    Xtr = rf_results[k]["X_train"]

    Xts = rf_results[k]["X_test"]

    features = ", ".join(
        rf_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_model_results.append({

            "Method": "Random Forest",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_results_df = pd.DataFrame(
    rf_model_results
)


display(rf_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth",0.701057,0.303039,0.734435,0.429047,0.785012
1,Random Forest,5,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth",0.744547,0.287354,0.452914,0.351620,0.694036
2,Random Forest,5,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth",0.689116,0.297977,0.761647,0.428365,0.789155
3,Random Forest,10,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708661,0.312426,0.753669,0.441735,0.804624
4,Random Forest,10,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.817802,0.354117,0.232227,0.280502,0.745475
5,Random Forest,10,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708726,0.314128,0.764354,0.445265,0.806214
6,Random Forest,15,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710513,0.314553,0.757230,0.444472,0.806440
7,Random Forest,15,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.839416,0.428571,0.150021,0.222246,0.770186
8,Random Forest,15,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710426,0.315613,0.764639,0.446803,0.807885
9,Random Forest,20,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.714304,0.317629,0.755948,0.447311,0.809080
10,Random Forest,20,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.842837,0.456658,0.145605,0.220806,0.777013
11,Random Forest,20,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.712169,0.317665,0.768343,0.449492,0.810260

In [13]:
rf_results_df.to_csv(
    "../../../results/diabetes/baseline/rf_baseline_results.csv",
    index=False
)

## 2. DODA

In [14]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [15]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [16]:
# =============================================================================
# RANDOM FOREST + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

rf_doda_results = {}


# =============================================================================
# RUN DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"RANDOM FOREST + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest operator
    # ---------------------------------------------------------------------

    rf = SklearnAdapter(
        RandomForestClassifier(
            n_estimators=100,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        )
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[rf],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    rf_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("RANDOM FOREST + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
RANDOM FOREST + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017FE6187620>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 5 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth']

======================================================================
RANDOM FOREST + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017FE6187620>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 10 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education']

======================================================================
RANDOM FOREST + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017FE6187620>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.19047443454449758), 'CholCheck': np.float64(0.01464991076420835), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.10231855423577833), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.054450213390780614), 'Fruits': np.float64(0.03407171751189637), 'Veggies': np.float64(0.026867166593553878), 'HvyAlcoholConsump': np.float64(0.011040569822240514), 'AnyHealthcare': np.float64(0.009002848444599082), 'NoDocbcCost': np.float64(0.014740759541341592), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.15855275405685007), 'PhysHlth': np.float64(0.33849503791311364), 'DiffWalk': np.float64(0.11248651603679159), 'Sex': np.float64(0.02923959658462287), 'Age': np.float64(0.677233827642279), 'Education': np.float64(0.10735301075605118), 'Income': np.float64(0.15286236892179236)}
Top 15 Features Selected: ['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits']

Selected Features:
['BMI', 'Age', 'GenHlth', 'HighBP', 'PhysHlth', 'HighChol', 'MentHlth', 'Income', 'DiffWalk', 'Education', 'Smoker', 'HeartDiseaseorAttack', 'Stroke', 'PhysActivity', 'Fruits']

======================================================================
RANDOM FOREST + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017FE6187620>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07285193478836292), 'HighChol': np.float64(0.03672026566347378), 'CholCheck': np.float64(0.006354576597706317), 'BMI': np.float64(0.17350485473894844), 'Smoker': np.float64(0.029587943149629894), 'Stroke': np.float64(0.010266744845272133), 'HeartDiseaseorAttack': np.float64(0.017279638922368307), 'PhysActivity': np.float64(0.02361844091218034), 'Fruits': np.float64(0.029558041988040323), 'Veggies': np.float64(0.02330791918530847), 'HvyAlcoholConsump': np.float64(0.00957796231621529), 'AnyHealthcare': np.float64(0.007810189558084658), 'NoDocbcCost': np.float64(0.012787966714811206), 'GenHlth': np.float64(0.09023471859520318), 'MentHlth': np.float64(0.05501934512218798), 'PhysHlth': np.float64(0.07341316547871203), 'DiffWalk': np.float64(0.021685507361171023), 'Sex': np.float64(0.02536605979020222), 'Age': np.float64(0.13055928543263962), 'Education': np.float64(0.0620875617900581), 'Income': np.float64(0.08840787704942378)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4198841288791275), 'HighChol': np.float64(0.21163826060499732), 'CholCheck': np.float64(0.03662477691052087), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17053092372629722), 'Stroke': np.float64(0.05917266615230594), 'HeartDiseaseorAttack': np.float64(0.09959167395267912), 'PhysActivity': np.float64(0.13612553347695153), 'Fruits': np.float64(0.17035858755948183), 'Veggies': np.float64(0.13433583296776938), 'HvyAlcoholConsump': np.float64(0.055202849111202566), 'AnyHealthcare': np.float64(0.04501424222299541), 'NoDocbcCost': np.float64(0.07370379770670796), 'GenHlth': np.float64(0.5200702812089514), 'MentHlth': np.float64(0.31710550811370014), 'PhysHlth': np.float64(0.423118797391392), 'DiffWalk': np.float64(0.12498501781865733), 'Sex': np.float64(0.14619798292311434), 'Age': np.float64(0.7524820307136433), 'Education': np.float64(0.3578433691868373), 'Income': np.float64(0.5095412297393079)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores

In [17]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = rf_doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
3                    BMI        0.173505               1.000000
18                   Age        0.130559               0.752482
13               GenHlth        0.090235               0.520070
20                Income        0.088408               0.509541
15              PhysHlth        0.073413               0.423119
0                 HighBP        0.072852               0.419884
19             Education        0.062088               0.357843
14              MentHlth        0.055019               0.317106
1               HighChol        0.036720               0.211638
4                 Smoker        0.029588               0.170531
8                 Fruits        0.029558               0.170359
17                   Sex        0.025366               0.146198
7           PhysActivity        0.023618               0.136126
9                Veggies        0.023308               0.134336
16              DiffWalk        0.021686               0.124985
6   HeartDiseaseorAttack        0.017280               0.099592
12           NoDocbcCost        0.012788               0.073704
5                 Stroke        0.010267               0.059173
10     HvyAlcoholConsump        0.009578               0.055203
11         AnyHealthcare        0.007810               0.045014
2              CholCheck        0.006355               0.036625

In [18]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                 HighBP              1.0
3                    BMI              1.0
13               GenHlth              1.0
6   HeartDiseaseorAttack              1.0
5                 Stroke              1.0
18                   Age              0.9
16              DiffWalk              0.9
1               HighChol              0.9
15              PhysHlth              0.8
4                 Smoker              0.6
14              MentHlth              0.5
2              CholCheck              0.4
7           PhysActivity              0.4
20                Income              0.3
19             Education              0.3
12           NoDocbcCost              0.2
9                Veggies              0.2
8                 Fruits              0.2
11         AnyHealthcare              0.2
10     HvyAlcoholConsump              0.2
17                   Sex              0.2

In [19]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
3                    BMI          1.000000
18                   Age          0.677234
13               GenHlth          0.520070
0                 HighBP          0.419884
15              PhysHlth          0.338495
1               HighChol          0.190474
14              MentHlth          0.158553
20                Income          0.152862
16              DiffWalk          0.112487
19             Education          0.107353
4                 Smoker          0.102319
6   HeartDiseaseorAttack          0.099592
5                 Stroke          0.059173
7           PhysActivity          0.054450
8                 Fruits          0.034072
17                   Sex          0.029240
9                Veggies          0.026867
12           NoDocbcCost          0.014741
2              CholCheck          0.014650
10     HvyAlcoholConsump          0.011041
11         AnyHealthcare          0.009003

In [20]:
selector.get_selected_features()

['BMI',
 'Age',
 'GenHlth',
 'HighBP',
 'PhysHlth',
 'HighChol',
 'MentHlth',
 'Income',
 'DiffWalk',
 'Education']

In [21]:
comparison = selector.compare_scores()

comparison

======================================================================
MATHEMATICAL vs CLINICAL vs HADAMARDFUSION
======================================================================

Fusion Method: HadamardFusion

Top Features After Fusion:
     Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0        BMI          1              2           1            0
1        Age          2              8           2            0
2    GenHlth          3              5           3            0
3     HighBP          6              1           4            2
4   PhysHlth          5              9           5            0
5   HighChol          9              6           6            3
6   MentHlth          8             11           7            1
7     Income          4             15           8           -4
8   DiffWalk         15              7           9            6
9  Education          7             14          10           -3

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,BMI,1,1.0000,2,1.0,1,1.0000,0
1,Age,2,0.7525,8,0.9,2,0.6772,0
2,GenHlth,3,0.5201,5,1.0,3,0.5201,0
3,HighBP,6,0.4199,1,1.0,4,0.4199,2
4,PhysHlth,5,0.4231,9,0.8,5,0.3385,0
5,HighChol,9,0.2116,6,0.9,6,0.1905,3
6,MentHlth,8,0.3171,11,0.5,7,0.1586,1
7,Income,4,0.5095,15,0.3,8,0.1529,-4
8,DiffWalk,15,0.1250,7,0.9,9,0.1125,6
9,Education,7,0.3578,14,0.3,10,0.1074,-3
10,Smoker,10,0.1705,10,0.6,11,0.1023,-1
11,HeartDiseaseorAttack,16,0.0996,4,1.0,12,0.0996,4
12,Stroke,18,0.0592,3,1.0,13,0.0592,5
13,PhysActivity,13,0.1361,13,0.4,14,0.0545,-1
14,Fruits,11,0.1704,16,0.2,15,0.0341,-4
15,Sex,12,0.1462,21,0.2,16,0.0292,-4
16,Veggies,14,0.1343,17,0.2,17,0.0269,-3
17,NoDocbcCost,17,0.0737,20,0.2,18,0.0147,-1
18,CholCheck,21,0.0366,12,0.4,19,0.0146,2
19,HvyAlcoholConsump,19,0.0552,18,0.2,20,0.0110,-1
20,AnyHealthcare,20,0.0450,19,0.2,21,0.0090,-1

In [22]:
# =============================================================================
# RANDOM FOREST + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_doda_model_results = []


for k in k_values:

    Xtr = rf_doda_results[k]["X_train"]

    Xts = rf_doda_results[k]["X_test"]

    features = ", ".join(
        rf_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_doda_model_results.append({

            "Method": "RF + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_doda_results_df = pd.DataFrame(
    rf_doda_model_results
)


display(rf_doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,RF + DODA,5,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
1,RF + DODA,5,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth",0.728816,0.303298,0.596096,0.402037,0.735567
2,RF + DODA,5,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
3,RF + DODA,10,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.709533,0.313077,0.753099,0.442288,0.804871
4,RF + DODA,10,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.812420,0.342011,0.245192,0.285619,0.740782
5,RF + DODA,10,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.706765,0.313157,0.768770,0.445031,0.805572
6,RF + DODA,15,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.713585,0.316543,0.752956,0.445709,0.805998
7,RF + DODA,15,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.834078,0.396312,0.162274,0.230264,0.762869
8,RF + DODA,15,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.711123,0.316035,0.763499,0.447030,0.806484
9,RF + DODA,20,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
10,RF + DODA,20,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.843273,0.461056,0.146745,0.222630,0.778232
11,RF + DODA,20,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [23]:
rf_doda_results_df.to_csv(
    "../../../results/diabetes/doda/rf_doda_results.csv",
    index=False
)

In [24]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        rf_results_df,
        rf_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth",0.701057,0.303039,0.734435,0.429047,0.785012
1,Random Forest,5,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth",0.744547,0.287354,0.452914,0.351620,0.694036
2,Random Forest,5,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth",0.689116,0.297977,0.761647,0.428365,0.789155
3,Random Forest,10,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708661,0.312426,0.753669,0.441735,0.804624
4,Random Forest,10,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.817802,0.354117,0.232227,0.280502,0.745475
5,Random Forest,10,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.708726,0.314128,0.764354,0.445265,0.806214
6,Random Forest,15,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710513,0.314553,0.757230,0.444472,0.806440
7,Random Forest,15,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.839416,0.428571,0.150021,0.222246,0.770186
8,Random Forest,15,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.710426,0.315613,0.764639,0.446803,0.807885
9,Random Forest,20,Logistic Regression,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.714304,0.317629,0.755948,0.447311,0.809080
10,Random Forest,20,Random Forest,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.842837,0.456658,0.145605,0.220806,0.777013
11,Random Forest,20,XGBoost,"BMI, Age, GenHlth, Income, PhysHlth, HighBP, E...",0.712169,0.317665,0.768343,0.449492,0.810260
12,RF + DODA,5,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
13,RF + DODA,5,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth",0.728816,0.303298,0.596096,0.402037,0.735567
14,RF + DODA,5,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
15,RF + DODA,10,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.709533,0.313077,0.753099,0.442288,0.804871
16,RF + DODA,10,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.812420,0.342011,0.245192,0.285619,0.740782
17,RF + DODA,10,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.706765,0.313157,0.768770,0.445031,0.805572
18,RF + DODA,15,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.713585,0.316543,0.752956,0.445709,0.805998
19,RF + DODA,15,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.834078,0.396312,0.162274,0.230264,0.762869
20,RF + DODA,15,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.711123,0.316035,0.763499,0.447030,0.806484
21,RF + DODA,20,Logistic Regression,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
22,RF + DODA,20,Random Forest,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.843273,0.461056,0.146745,0.222630,0.778232
23,RF + DODA,20,XGBoost,"BMI, Age, GenHlth, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [26]:
# ============================================================
# RANDOM FOREST + DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# Heart Disease Dataset
# ============================================================


import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from doda import DODASelector
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion
from doda.adapters.sklearn_adapter import SklearnAdapter


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "clinical_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should contain the ORIGINAL Heart Disease data
# before imputation/scaling.
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"RANDOM FOREST + DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0


    # ========================================================
    # 25 REPEATED CV RUNS
    # ========================================================

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()


        # ----------------------------------------------------
        # IMPUTATION
        # ----------------------------------------------------

        imputer = SimpleImputer(
            strategy="median"
        )

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )


        # ----------------------------------------------------
        # RANDOM FOREST OPERATOR
        # ----------------------------------------------------

        rf_operator = SklearnAdapter(
            RandomForestClassifier(
                n_estimators=200,
                random_state=RANDOM_STATE,
                class_weight="balanced"
            )
        )


        # ----------------------------------------------------
        # CLINICAL KNOWLEDGE PROVIDER
        # ----------------------------------------------------

        provider = JSONProvider(
            WEIGHTS_FILE
        )


        # ----------------------------------------------------
        # DODA SELECTOR
        # ----------------------------------------------------

        doda_selector = DODASelector(

            operators=[rf_operator],

            provider=provider,

            fusion=RankFusion(),

            top_k=TOP_K

        )


        # ----------------------------------------------------
        # FIT ONLY ON TRAINING FOLD
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )


        # ----------------------------------------------------
        # SELECTED FEATURES
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )


        selected_feature_sets.append(
            set(selected_features)
        )


        all_runs.append({

            "Top_K": TOP_K,

            "Run": run_number,

            "Selected_Features": selected_features

        })


        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []


    for i in range(
        len(selected_feature_sets)
    ):

        for j in range(
            i + 1,
            len(selected_feature_sets)
        ):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]


            intersection = len(
                set_a.intersection(set_b)
            )

            union = len(
                set_a.union(set_b)
            )


            jaccard = (
                intersection / union
            )


            jaccard_scores.append(
                jaccard
            )


            all_jaccard.append({

                "Top_K": TOP_K,

                "Run_A": i + 1,

                "Run_B": j + 1,

                "Jaccard_Similarity": jaccard

            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(
        jaccard_scores
    )

    std_jaccard = np.std(
        jaccard_scores
    )

    min_jaccard = np.min(
        jaccard_scores
    )

    max_jaccard = np.max(
        jaccard_scores
    )


    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(
        f"Number of runs:          "
        f"{len(selected_feature_sets)}"
    )

    print(
        f"Number of comparisons:   "
        f"{len(jaccard_scores)}"
    )

    print(
        f"Mean Jaccard Similarity: "
        f"{mean_jaccard:.4f}"
    )

    print(
        f"Standard Deviation:      "
        f"{std_jaccard:.4f}"
    )

    print(
        f"Minimum Jaccard:         "
        f"{min_jaccard:.4f}"
    )

    print(
        f"Maximum Jaccard:         "
        f"{max_jaccard:.4f}"
    )


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}


    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )


    for feature, count in feature_counts.items():

        all_frequency.append({

            "Top_K": TOP_K,

            "Feature": feature,

            "Selection_Count": count,

            "Selection_Frequency":
                count / len(selected_feature_sets)

        })


    frequency_df_topk = pd.DataFrame(

        [

            {

                "Feature": feature,

                "Selection_Count": count,

                "Selection_Frequency":
                    count / len(selected_feature_sets)

            }

            for feature, count
            in feature_counts.items()

        ]

    ).sort_values(

        "Selection_Frequency",

        ascending=False

    )


    print(
        "\nFEATURE SELECTION FREQUENCY"
    )

    print(
        frequency_df_topk.to_string(
            index=False
        )
    )


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(
    all_runs
)

jaccard_df = pd.DataFrame(
    all_jaccard
)

frequency_df = pd.DataFrame(
    all_frequency
)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []


for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]


    summary_rows.append({

        "Top_K": TOP_K,

        "Mean_Jaccard":
            subset.mean(),

        "Std_Jaccard":
            subset.std(),

        "Min_Jaccard":
            subset.min(),

        "Max_Jaccard":
            subset.max()

    })


summary_df = pd.DataFrame(
    summary_rows
)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("RANDOM FOREST + DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(

    summary_df.to_string(

        index=False,

        float_format=lambda x:
            f"{x:.4f}"

    )

)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/diabetes/"
    "rf_doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/diabetes/"
    "rf_doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/diabetes/"
    "rf_doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/diabetes/"
    "rf_doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")

print(
    "1. rf_doda_stability_all_topk_runs.csv"
)

print(
    "2. rf_doda_stability_all_topk_jaccard.csv"
)

print(
    "3. rf_doda_stability_all_topk_frequency.csv"
)

print(
    "4. rf_doda_stability_all_topk_summary.csv"
)

======================================================================
RANDOM FOREST + DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F8306D310>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07169008258921687), 'HighChol': np.float64(0.03672063491265991), 'CholCheck': np.float64(0.006293833183565951), 'BMI': np.float64(0.1732083208153204), 'Smoker': np.float64(0.029778234391548333), 'Stroke': np.float64(0.009954076768751416), 'HeartDiseaseorAttack': np.float64(0.0171539414789473), 'PhysActivity': np.float64(0.024042599206274374), 'Fruits': np.float64(0.029256951502913502), 'Veggies': np.float64(0.02328545147334804), 'HvyAlcoholConsump': np.float64(0.009595485759355524), 'AnyHealthcare': np.float64(0.007791271659484316), 'NoDocbcCost': np.float64(0.012586430338942554), 'GenHlth': np.float64(0.09258476306689613), 'MentHlth': np.float64(0.05519648918708631), 'PhysHlth': np.float64(0.07312802894960965), 'DiffWalk': np.float64(0.023176412536512352), 'Sex': np.float64(0.02486012717376853), 'Age': np.float64(0.1299623158309074), 'Education': np.float64(0.061383260186873796), 'Income': np.float64(0.08835128898801738)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07169008258921687), 'HighChol': np.float64(0.03672063491265991), 'CholCheck': np.float64(0.006293833183565951), 'BMI': np.float64(0.1732083208153204), 'Smoker': np.float64(0.029778234391548333), 'Stroke': np.float64(0.009954076768751416), 'HeartDiseaseorAttack': np.float64(0.0171539414789473), 'PhysActivity': np.float64(0.024042599206274374), 'Fruits': np.float64(0.029256951502913502), 'Veggies': np.float64(0.02328545147334804), 'HvyAlcoholConsump': np.float64(0.009595485759355524), 'AnyHealthcare': np.float64(0.007791271659484316), 'NoDocbcCost': np.float64(0.012586430338942554), 'GenHlth': np.float64(0.09258476306689613), 'MentHlth': np.float64(0.05519648918708631), 'PhysHlth': np.float64(0.07312802894960965), 'DiffWalk': np.float64(0.023176412536512352), 'Sex': np.float64(0.02486012717376853), 'Age': np.float64(0.1299623158309074), 'Education': np.float64(0.061383260186873796), 'Income': np.float64(0.08835128898801738)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.41389514228738966), 'HighChol': np.float64(0.21200271869047496), 'CholCheck': np.float64(0.036336783094136765), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17192150037236795), 'Stroke': np.float64(0.057468813980159385), 'HeartDiseaseorAttack': np.float64(0.0990364746808978), 'PhysActivity': np.float64(0.1388074146386378), 'Fruits': np.float64(0.16891192851010947), 'Veggies': np.float64(0.1344361019363247), 'HvyAlcoholConsump': np.float64(0.0553985265499254), 'AnyHealthcare': np.float64(0.044982086442553706), 'NoDocbcCost': np.float64(0.07266643010968601), 'GenHlth': np.float64(0.5345283796476072), 'MentHlth': np.float64(0.31867111768803746), 'PhysHlth': np.float64(0.42219697417181723), 'DiffWalk': np.float64(0.1338065771171796), 'Sex': np.float64(0.14352732626670459), 'Age': np.float64(0.7503237443741336), 'Education': np.float64(0.354389788538637), 'Income': np.float64(0.5100868628720211)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031544957774465976, 'HighChol': 0.030621785881252923, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.028790389395194696, 'Veggies': 0.02821939586645469, 'HvyAlcoholConsump': 0.027364110201042444, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.032266458495966696, 'MentHlth': 0.030090497737556562, 'PhysHlth': 0.03125763125763126, 'DiffWalk': 0.02946236559139785, 'Sex': 0.028594771241830064, 'Age': 0.03225806451612903, 'Education': 0.029850746268656716, 'Income': 0.03055037313432836}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Run 01: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F82FFB6F0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.0713852790897221), 'HighChol': np.float64(0.03720324386463491), 'CholCheck': np.float64(0.006261592433023906), 'BMI': np.float64(0.17117187356050448), 'Smoker': np.float64(0.029486624952115677), 'Stroke': np.float64(0.010160305308171679), 'HeartDiseaseorAttack': np.float64(0.017762626348618086), 'PhysActivity': np.float64(0.023387273761188803), 'Fruits': np.float64(0.029264489607823133), 'Veggies': np.float64(0.023492595173733324), 'HvyAlcoholConsump': np.float64(0.009476195662398353), 'AnyHealthcare': np.float64(0.007819331013311477), 'NoDocbcCost': np.float64(0.012759338325706287), 'GenHlth': np.float64(0.09297914411517035), 'MentHlth': np.float64(0.0550119064688254), 'PhysHlth': np.float64(0.07312135089168499), 'DiffWalk': np.float64(0.02445471690052037), 'Sex': np.float64(0.0249580841726556), 'Age': np.float64(0.12994669895133254), 'Education': np.float64(0.06236990440239358), 'Income': np.float64(0.08752742499646507)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.0713852790897221), 'HighChol': np.float64(0.03720324386463491), 'CholCheck': np.float64(0.006261592433023906), 'BMI': np.float64(0.17117187356050448), 'Smoker': np.float64(0.029486624952115677), 'Stroke': np.float64(0.010160305308171679), 'HeartDiseaseorAttack': np.float64(0.017762626348618086), 'PhysActivity': np.float64(0.023387273761188803), 'Fruits': np.float64(0.029264489607823133), 'Veggies': np.float64(0.023492595173733324), 'HvyAlcoholConsump': np.float64(0.009476195662398353), 'AnyHealthcare': np.float64(0.007819331013311477), 'NoDocbcCost': np.float64(0.012759338325706287), 'GenHlth': np.float64(0.09297914411517035), 'MentHlth': np.float64(0.0550119064688254), 'PhysHlth': np.float64(0.07312135089168499), 'DiffWalk': np.float64(0.02445471690052037), 'Sex': np.float64(0.0249580841726556), 'Age': np.float64(0.12994669895133254), 'Education': np.float64(0.06236990440239358), 'Income': np.float64(0.08752742499646507)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.4170386033923348), 'HighChol': np.float64(0.21734437493017567), 'CholCheck': np.float64(0.03658073200215693), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17226325995487207), 'Stroke': np.float64(0.05935732954737038), 'HeartDiseaseorAttack': np.float64(0.10377070706268511), 'PhysActivity': np.float64(0.1366303544777294), 'Fruits': np.float64(0.1709655272160058), 'Veggies': np.float64(0.13724565073145237), 'HvyAlcoholConsump': np.float64(0.05536070538509811), 'AnyHealthcare': np.float64(0.045681167417657334), 'NoDocbcCost': np.float64(0.07454109171268851), 'GenHlth': np.float64(0.5431917182486456), 'MentHlth': np.float64(0.3213840295402283), 'PhysHlth': np.float64(0.427180875985672), 'DiffWalk': np.float64(0.14286644407076793), 'Sex': np.float64(0.14580715659359547), 'Age': np.float64(0.7591591787151878), 'Education': np.float64(0.3643700516039953), 'Income': np.float64(0.5113423319838032)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031544957774465976, 'HighChol': 0.030621785881252923, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028484848484848488, 'Fruits': 0.028790389395194696, 'Veggies': 0.02821939586645469, 'HvyAlcoholConsump': 0.027364110201042444, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.032266458495966696, 'MentHlth': 0.030090497737556562, 'PhysHlth': 0.03125763125763126, 'DiffWalk': 0.029827662395050816, 'Sex': 0.028594771241830064, 'Age': 0.03225806451612903, 'Education': 0.029850746268656716, 'Income': 0.03055037313432836}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Run 02: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F82FFB950>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07321187543005116), 'HighChol': np.float64(0.03673263656848847), 'CholCheck': np.float64(0.006244800924086202), 'BMI': np.float64(0.17322698740654585), 'Smoker': np.float64(0.029652978651686444), 'Stroke': np.float64(0.010049170326387089), 'HeartDiseaseorAttack': np.float64(0.01717569487587209), 'PhysActivity': np.float64(0.023775042315768158), 'Fruits': np.float64(0.02914549649382846), 'Veggies': np.float64(0.023332306183377203), 'HvyAlcoholConsump': np.float64(0.009675258320281198), 'AnyHealthcare': np.float64(0.007810331312296877), 'NoDocbcCost': np.float64(0.012774609457302754), 'GenHlth': np.float64(0.09181069692822214), 'MentHlth': np.float64(0.05495708246004574), 'PhysHlth': np.float64(0.07259776198012187), 'DiffWalk': np.float64(0.02303041603509928), 'Sex': np.float64(0.025292393829513055), 'Age': np.float64(0.12963948674790385), 'Education': np.float64(0.06201044438679026), 'Income': np.float64(0.08785452936633179)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07321187543005116), 'HighChol': np.float64(0.03673263656848847), 'CholCheck': np.float64(0.006244800924086202), 'BMI': np.float64(0.17322698740654585), 'Smoker': np.float64(0.029652978651686444), 'Stroke': np.float64(0.010049170326387089), 'HeartDiseaseorAttack': np.float64(0.01717569487587209), 'PhysActivity': np.float64(0.023775042315768158), 'Fruits': np.float64(0.02914549649382846), 'Veggies': np.float64(0.023332306183377203), 'HvyAlcoholConsump': np.float64(0.009675258320281198), 'AnyHealthcare': np.float64(0.007810331312296877), 'NoDocbcCost': np.float64(0.012774609457302754), 'GenHlth': np.float64(0.09181069692822214), 'MentHlth': np.float64(0.05495708246004574), 'PhysHlth': np.float64(0.07259776198012187), 'DiffWalk': np.float64(0.02303041603509928), 'Sex': np.float64(0.025292393829513055), 'Age': np.float64(0.12963948674790385), 'Education': np.float64(0.06201044438679026), 'Income': np.float64(0.08785452936633179)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.42263550573808945), 'HighChol': np.float64(0.21204915653402645), 'CholCheck': np.float64(0.03604981543337874), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.17117990155941445), 'Stroke': np.float64(0.05801157473692436), 'HeartDiseaseorAttack': np.float64(0.09915138012278944), 'PhysActivity': np.float64(0.137247911954796), 'Fruits': np.float64(0.16825032248252975), 'Veggies': np.float64(0.1346920969572639), 'HvyAlcoholConsump': np.float64(0.05585306576725465), 'AnyHealthcare': np.float64(0.045087266304336494), 'NoDocbcCost': np.float64(0.07374491497287351), 'GenHlth': np.float64(0.5300022721791722), 'MentHlth': np.float64(0.3172547377451479), 'PhysHlth': np.float64(0.4190903684640224), 'DiffWalk': np.float64(0.13294935379236997), 'Sex': np.float64(0.1460072371411414), 'Age': np.float64(0.7483792721260768), 'Education': np.float64(0.35797219194984986), 'Income': np.float64(0.5071642166248973)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03177805800756621, 'HighChol': 0.030621785881252923, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.028790389395194696, 'Veggies': 0.02821939586645469, 'HvyAlcoholConsump': 0.027364110201042444, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.032266458495966696, 'MentHlth': 0.030090497737556562, 'PhysHlth': 0.031024531024531024, 'DiffWalk': 0.02946236559139785, 'Sex': 0.028594771241830064, 'Age': 0.03225806451612903, 'Education': 0.029850746268656716, 'Income': 0.03055037313432836}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Run 03: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F830CDC70>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.07033563427661513), 'HighChol': np.float64(0.03718879782045982), 'CholCheck': np.float64(0.00641066462991634), 'BMI': np.float64(0.17302677835056904), 'Smoker': np.float64(0.029273778085461513), 'Stroke': np.float64(0.010098618326546481), 'HeartDiseaseorAttack': np.float64(0.01719468806981135), 'PhysActivity': np.float64(0.023146873070969392), 'Fruits': np.float64(0.02923917474383381), 'Veggies': np.float64(0.023019571114023866), 'HvyAlcoholConsump': np.float64(0.009482796341040448), 'AnyHealthcare': np.float64(0.007864241737771614), 'NoDocbcCost': np.float64(0.012773423681648365), 'GenHlth': np.float64(0.09243852719805251), 'MentHlth': np.float64(0.05550844144141091), 'PhysHlth': np.float64(0.0730054221496312), 'DiffWalk': np.float64(0.023267599199313677), 'Sex': np.float64(0.02518880760753186), 'Age': np.float64(0.13047915853514344), 'Education': np.float64(0.06189597171107728), 'Income': np.float64(0.08916103190917196)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.07033563427661513), 'HighChol': np.float64(0.03718879782045982), 'CholCheck': np.float64(0.00641066462991634), 'BMI': np.float64(0.17302677835056904), 'Smoker': np.float64(0.029273778085461513), 'Stroke': np.float64(0.010098618326546481), 'HeartDiseaseorAttack': np.float64(0.01719468806981135), 'PhysActivity': np.float64(0.023146873070969392), 'Fruits': np.float64(0.02923917474383381), 'Veggies': np.float64(0.023019571114023866), 'HvyAlcoholConsump': np.float64(0.009482796341040448), 'AnyHealthcare': np.float64(0.007864241737771614), 'NoDocbcCost': np.float64(0.012773423681648365), 'GenHlth': np.float64(0.09243852719805251), 'MentHlth': np.float64(0.05550844144141091), 'PhysHlth': np.float64(0.0730054221496312), 'DiffWalk': np.float64(0.023267599199313677), 'Sex': np.float64(0.02518880760753186), 'Age': np.float64(0.13047915853514344), 'Education': np.float64(0.06189597171107728), 'Income': np.float64(0.08916103190917196)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.40650143837336156), 'HighChol': np.float64(0.21493088049707373), 'CholCheck': np.float64(0.037050129991599984), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1691864020385908), 'Stroke': np.float64(0.05836448220798344), 'HeartDiseaseorAttack': np.float64(0.09937587831042687), 'PhysActivity': np.float64(0.1337762471891581), 'Fruits': np.float64(0.16898641367865272), 'Veggies': np.float64(0.133040511610197), 'HvyAlcoholConsump': np.float64(0.05480536846052454), 'AnyHealthcare': np.float64(0.045451009449172644), 'NoDocbcCost': np.float64(0.07382339198252984), 'GenHlth': np.float64(0.5342440521591582), 'MentHlth': np.float64(0.3208083856762647), 'PhysHlth': np.float64(0.42193134984987773), 'DiffWalk': np.float64(0.13447397808084516), 'Sex': np.float64(0.1455775103001507), 'Age': np.float64(0.7540980637735739), 'Education': np.float64(0.3577248117379267), 'Income': np.float64(0.515301924702794)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031544957774465976, 'HighChol': 0.030621785881252923, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028665028665028666, 'Fruits': 0.028790389395194696, 'Veggies': 0.02803921568627451, 'HvyAlcoholConsump': 0.027364110201042444, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.032266458495966696, 'MentHlth': 0.030090497737556562, 'PhysHlth': 0.03125763125763126, 'DiffWalk': 0.029827662395050816, 'Sex': 0.028594771241830064, 'Age': 0.03225806451612903, 'Education': 0.029850746268656716, 'Income': 0.03055037313432836}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Run 04: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F812267A0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:

In [27]:
# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# =============================================================================
# CONFIGURATION
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

target_column = "Diabetes_binary"

X = df.drop(columns=[target_column])
y = df[target_column]

feature_names = X.columns.tolist()


# =============================================================================
# MODELS
# =============================================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# =============================================================================
# CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

provider = JSONProvider(
    "clinical_weights.json"
)


# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# =============================================================================
# RESULTS STORAGE
# =============================================================================

results = []


# =============================================================================
# CROSS-VALIDATION LOOP
# =============================================================================

for run_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    print("\n" + "=" * 80)
    print(f"REPEATED STRATIFIED CV RUN {run_number}")
    print("=" * 80)

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # =========================================================================
    # IMPUTATION
    # =========================================================================

    imputer = SimpleImputer(
        strategy="median"
    )

    X_train_imp_array = imputer.fit_transform(
        X_train
    )

    X_test_imp_array = imputer.transform(
        X_test
    )

    X_train_imp = pd.DataFrame(
        X_train_imp_array,
        columns=feature_names,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        X_test_imp_array,
        columns=feature_names,
        index=X_test.index
    )


    # =========================================================================
    # FEATURE SELECTION FOR EACH TOP-K VALUE
    # =========================================================================

    for top_k in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"TOP-K = {top_k}")
        print("-" * 80)


        # =====================================================================
        # BASELINE RANDOM FOREST FEATURE SELECTION
        # =====================================================================

        rf_operator_baseline = RandomForestClassifier(
            n_estimators=300,
            random_state=RANDOM_STATE,
            n_jobs=-1
        )

        rf_operator_baseline.fit(
            X_train_imp,
            y_train
        )

        rf_importance = pd.Series(
            rf_operator_baseline.feature_importances_,
            index=X_train_imp.columns
        )

        rf_features = (
            rf_importance
            .sort_values(
                ascending=False
            )
            .head(top_k)
            .index
            .tolist()
        )

        print("Random Forest-selected features:")
        print(rf_features)


        # =====================================================================
        # DODA-RANDOM FOREST FEATURE SELECTION
        # =====================================================================

        rf_operator = SklearnAdapter(
            RandomForestClassifier(
                n_estimators=300,
                random_state=RANDOM_STATE,
                n_jobs=-1
            )
        )

        doda_selector = DODASelector(
            operators=[rf_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        doda_features = list(
            doda_selector.get_selected_features()
        )

        print("DODA-selected features:")
        print(doda_features)


        # =====================================================================
        # PREPARE SELECTED FEATURE MATRICES
        # =====================================================================

        X_train_rf_selected = (
            X_train_imp[rf_features]
        )

        X_test_rf_selected = (
            X_test_imp[rf_features]
        )

        X_train_doda_selected = (
            X_train_imp[doda_features]
        )

        X_test_doda_selected = (
            X_test_imp[doda_features]
        )


        # =====================================================================
        # MODEL EVALUATION
        # =====================================================================

        selected_feature_sets = {

            "Random Forest": (
                X_train_rf_selected,
                X_test_rf_selected,
                rf_features
            ),

            "DODA": (
                X_train_doda_selected,
                X_test_doda_selected,
                doda_features
            )

        }


        for method, (
            X_train_selected,
            X_test_selected,
            selected_features
        ) in selected_feature_sets.items():

            for model_name, model_template in models.items():

                model = clone(
                    model_template
                )

                X_train_model = (
                    X_train_selected.copy()
                )

                X_test_model = (
                    X_test_selected.copy()
                )


                # -------------------------------------------------------------
                # Scale only Logistic Regression
                # -------------------------------------------------------------

                if model_name == "Logistic Regression":

                    model_scaler = StandardScaler()

                    X_train_model = (
                        model_scaler.fit_transform(
                            X_train_model
                        )
                    )

                    X_test_model = (
                        model_scaler.transform(
                            X_test_model
                        )
                    )


                # -------------------------------------------------------------
                # Train model
                # -------------------------------------------------------------

                model.fit(
                    X_train_model,
                    y_train
                )

                y_pred = model.predict(
                    X_test_model
                )

                y_prob = model.predict_proba(
                    X_test_model
                )[:, 1]


                # -------------------------------------------------------------
                # Calculate metrics
                # -------------------------------------------------------------

                accuracy = accuracy_score(
                    y_test,
                    y_pred
                )

                precision = precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                roc_auc = roc_auc_score(
                    y_test,
                    y_prob
                )


                # -------------------------------------------------------------
                # Store results
                # -------------------------------------------------------------

                results.append({

                    "Run": run_number,

                    "Method": method,

                    "Top_K": top_k,

                    "Model": model_name,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": roc_auc,

                    "Selected_Features": selected_features

                })


# =============================================================================
# RESULTS DATAFRAME
# =============================================================================

results_df = pd.DataFrame(
    results
)


# =============================================================================
# DISPLAY RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("REPEATED STRATIFIED CV RESULTS — RANDOM FOREST VS DODA-RANDOM FOREST")
print("=" * 80)

display(
    results_df.head()
)

print(
    "Total evaluation rows:",
    len(results_df)
)

================================================================================
REPEATED STRATIFIED CV RUN 1
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------
Random Forest-selected features:
['BMI', 'Age', 'Income', 'PhysHlth', 'Education']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F81247B30>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.22210130265282252), 'HighChol': np.float64(0.14204835015624648), 'CholCheck': np.float64(0.019917738082838636), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.18302239555910452), 'Stroke': np.float64(0.06685686982024362), 'HeartDiseaseorAttack': np.float64(0.09991700775081991), 'PhysActivity': np.float64(0.14488834401787404), 'Fruits': np.float64(0.1832278661988042), 'Veggies': np.float64(0.14683007901058928), 'HvyAlcoholConsump': np.float64(0.041677492457772955), 'AnyHealthcare': np.float64(0.047591256656548835), 'NoDocbcCost': np.float64(0.08298366322493161), 'GenHlth': np.float64(0.3609408969382924), 'MentHlth': np.float64(0.342971717097658), 'PhysHlth': np.float64(0.45880520369078415), 'DiffWalk': np.float64(0.12334957948336141), 'Sex': np.float64(0.1482462695955422), 'Age': np.float64(0.6675049750936912), 'Education': np.float64(0.39411788439816253), 'Income': np.float64(0.542983184928331)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031099324975891997, 'HighChol': 0.02964254577157803, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.02919863597612958, 'Veggies': 0.028594771241830064, 'HvyAlcoholConsump': 0.027205882352941177, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.031544957774465976, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.02946236559139785, 'Sex': 0.028790389395194696, 'Age': 0.03225806451612903, 'Education': 0.030309988518943745, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP']
DODA-selected features:
['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------
Random Forest-selected features:
['BMI', 'Age', 'Income', 'PhysHlth', 'Education', 'GenHlth', 'MentHlth', 'HighBP', 'Fruits', 'Smoker']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F81247B30>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.22210130265282252), 'HighChol': np.float64(0.14204835015624648), 'CholCheck': np.float64(0.019917738082838636), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.18302239555910452), 'Stroke': np.float64(0.06685686982024362), 'HeartDiseaseorAttack': np.float64(0.09991700775081991), 'PhysActivity': np.float64(0.14488834401787404), 'Fruits': np.float64(0.1832278661988042), 'Veggies': np.float64(0.14683007901058928), 'HvyAlcoholConsump': np.float64(0.041677492457772955), 'AnyHealthcare': np.float64(0.047591256656548835), 'NoDocbcCost': np.float64(0.08298366322493161), 'GenHlth': np.float64(0.3609408969382924), 'MentHlth': np.float64(0.342971717097658), 'PhysHlth': np.float64(0.45880520369078415), 'DiffWalk': np.float64(0.12334957948336141), 'Sex': np.float64(0.1482462695955422), 'Age': np.float64(0.6675049750936912), 'Education': np.float64(0.39411788439816253), 'Income': np.float64(0.542983184928331)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031099324975891997, 'HighChol': 0.02964254577157803, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.02919863597612958, 'Veggies': 0.028594771241830064, 'HvyAlcoholConsump': 0.027205882352941177, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.031544957774465976, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.02946236559139785, 'Sex': 0.028790389395194696, 'Age': 0.03225806451612903, 'Education': 0.030309988518943745, 'Income': 0.030798389007344232}
Top 10 Features Selected: ['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP', 'Income', 'MentHlth', 'Education', 'Smoker', 'HighChol']
DODA-selected features:
['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP', 'Income', 'MentHlth', 'Education', 'Smoker', 'HighChol']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------
Random Forest-selected features:
['BMI', 'Age', 'Income', 'PhysHlth', 'Education', 'GenHlth', 'MentHlth', 'HighBP', 'Fruits', 'Smoker', 'Sex', 'Veggies', 'PhysActivity', 'HighChol', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F81247B30>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.22210130265282252), 'HighChol': np.float64(0.14204835015624648), 'CholCheck': np.float64(0.019917738082838636), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.18302239555910452), 'Stroke': np.float64(0.06685686982024362), 'HeartDiseaseorAttack': np.float64(0.09991700775081991), 'PhysActivity': np.float64(0.14488834401787404), 'Fruits': np.float64(0.1832278661988042), 'Veggies': np.float64(0.14683007901058928), 'HvyAlcoholConsump': np.float64(0.041677492457772955), 'AnyHealthcare': np.float64(0.047591256656548835), 'NoDocbcCost': np.float64(0.08298366322493161), 'GenHlth': np.float64(0.3609408969382924), 'MentHlth': np.float64(0.342971717097658), 'PhysHlth': np.float64(0.45880520369078415), 'DiffWalk': np.float64(0.12334957948336141), 'Sex': np.float64(0.1482462695955422), 'Age': np.float64(0.6675049750936912), 'Education': np.float64(0.39411788439816253), 'Income': np.float64(0.542983184928331)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.031099324975891997, 'HighChol': 0.02964254577157803, 'CholCheck': 0.02749719416386083, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02921395544346364, 'HeartDiseaseorAttack': 0.029551337359792925, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.02919863597612958, 'Veggies': 0.028594771241830064, 'HvyAlcoholConsump': 0.027205882352941177, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027692895339954164, 'GenHlth': 0.031544957774465976, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.02946236559139785, 'Sex': 0.028790389395194696, 'Age': 0.03225806451612903, 'Education': 0.030309988518943745, 'Income': 0.030798389007344232}
Top 15 Features Selected: ['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP', 'Income', 'MentHlth', 'Education', 'Smoker', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Stroke', 'Fruits', 'PhysActivity']
DODA-selected features:
['BMI', 'Age', 'GenHlth', 'PhysHlth', 'HighBP', 'Income', 'MentHlth', 'Education', 'Smoker', 'HighChol', 'HeartDiseaseorAttack', 'DiffWalk', 'Stroke', 'Fruits', 'PhysActivity']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------
Random Forest-selected features:
['BMI', 'Age', 'Income', 'PhysHlth', 'Education', 'GenHlth', 'MentHlth', 'HighBP', 'Fruits', 'Smoker', 'Sex', 'Veggies', 'PhysActivity', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'NoDocbcCost', 'Stroke', 'AnyHealthcare', 'HvyAlcoholConsump']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000017F81247B30>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of feature importances: 21
Operator Scores:
{'RandomForestClassifier_1': {'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.04097823562976836), 'HighChol': np.float64(0.02620826935275311), 'CholCheck': np.float64(0.003674871577166771), 'BMI': np.float64(0.18450245514238814), 'Smoker': np.float64(0.0337680813266961), 'Stroke': np.float64(0.012335256624969983), 'HeartDiseaseorAttack': np.float64(0.0184349332405073), 'PhysActivity': np.float64(0.026732255192812707), 'Fruits': np.float64(0.03380599116418037), 'Veggies': np.float64(0.027090510066204557), 'HvyAlcoholConsump': np.float64(0.007689599682637474), 'AnyHealthcare': np.float64(0.008780703696444783), 'NoDocbcCost': np.float64(0.015310689601708989), 'GenHlth': np.float64(0.06659448164641063), 'MentHlth': np.float64(0.06327912384891848), 'PhysHlth': np.float64(0.08465068651305316), 'DiffWalk': np.float64(0.022758300255461328), 'Sex': np.float64(0.027351800706077907), 'Age': np.float64(0.12315630672454468), 'Education': np.float64(0.0727157172869849), 'Income': np.float64(0.10018173072031043)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.22210130265282252), 'HighChol': np.float64(0.14204835015624648), 'CholCheck': np.float64(0.019917738082838636), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.18302239555910452), 'Stroke': np.float64(0.06685686982024362), 'HeartDiseaseorAttack': np.float64(0.09991700775081991), 'PhysActivity': np.float64(0.14488834401787404), 'Fruits': np.float64(0.1832278661988042), 'Veggies': np.float64(0.14683007901058928), 'HvyAlcoholConsump': np.float64(0.041677492457772955), 'AnyHealthcare': np.float64(0.047591256656548835), 'NoDocbcCost': np.float64(0.08298366322493161), 'GenHlth': np.float64(0.3609408969382924), 'MentHlth': np.float64(0.342971717097658), 'PhysHlth': np.float64(0.45880520369078415), 'DiffWalk': np.float64(0.12334957948336141), 'Sex': np.float64(0.1482462695955422), 'Age': np.float64(0.6675049750936912), 'Education': np.float64(0.39411788439816253), 'Income': np.float64(0.542983184928331)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,Random Forest,5,Logistic Regression,0.845975,0.471264,0.058413,0.103942,0.750501,"[BMI, Age, Income, PhysHlth, Education]"
1,1,Random Forest,5,Random Forest,0.828478,0.355375,0.149309,0.210273,0.689766,"[BMI, Age, Income, PhysHlth, Education]"
2,1,Random Forest,5,XGBoost,0.848567,0.542022,0.063399,0.113520,0.761783,"[BMI, Age, Income, PhysHlth, Education]"
3,1,DODA,5,Logistic Regression,0.849003,0.529142,0.115116,0.189094,0.794154,"[BMI, Age, GenHlth, PhysHlth, HighBP]"
4,1,DODA,5,Random Forest,0.838043,0.429012,0.178231,0.251837,0.752617,"[BMI, Age, GenHlth, PhysHlth, HighBP]"

Total evaluation rows: 600

In [28]:
# =============================================================================
# PREPARE FEATURE SETS FOR STABILITY ANALYSIS
# mRMR VS DODA-mRMR
# =============================================================================

import ast
import numpy as np
import pandas as pd


# =============================================================================
# CONVERT SELECTED FEATURES TO SET
# =============================================================================

def convert_to_set(features):
    """
    Convert Selected_Features into a Python set.
    Handles lists, tuples, NumPy arrays, and strings.
    """

    if isinstance(features, str):

        # Handle string representation of a list
        if features.startswith("[") and features.endswith("]"):

            try:
                features = ast.literal_eval(features)

            except Exception:
                features = features.split(",")

        else:
            features = features.split(",")


    return {
        str(feature).strip().strip("'").strip('"')
        for feature in features
        if str(feature).strip()
    }


# =============================================================================
# USE ONLY ONE MODEL
# =============================================================================

# Feature selection is independent of the predictive model.
# Therefore, Logistic Regression rows are sufficient.

stability_df = results_df[
    results_df["Model"] == "Logistic Regression"
].copy()


# =============================================================================
# CONVERT FEATURE LISTS TO SETS
# =============================================================================

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(convert_to_set)
)


# =============================================================================
# CHECK RESULTS
# =============================================================================

print("=" * 80)
print("FEATURE SETS PREPARED FOR STABILITY ANALYSIS")
print("=" * 80)

print(
    "Rows used for stability analysis:",
    len(stability_df)
)


# =============================================================================
# DISPLAY SAMPLE
# =============================================================================

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head(10)
)


# =============================================================================
# CHECK FEATURE COUNT
# =============================================================================

stability_df["Feature_Count"] = (
    stability_df["Feature_Set"]
    .apply(len)
)


print("\nFeature count check:")

display(
    stability_df[
        [
            "Method",
            "Top_K",
            "Feature_Count"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Method", "Top_K"]
    )
)


# =============================================================================
# VERIFY EXPECTED TOP-K
# =============================================================================

invalid_rows = stability_df[
    stability_df["Feature_Count"] != stability_df["Top_K"]
]


if len(invalid_rows) == 0:

    print(
        "\n✓ All feature sets contain the expected number of features."
    )

else:

    print(
        "\n⚠ WARNING: Some feature sets do not match their Top-K value."
    )

    display(
        invalid_rows[
            [
                "Run",
                "Method",
                "Top_K",
                "Feature_Count",
                "Feature_Set"
            ]
        ]
    )

================================================================================
FEATURE SETS PREPARED FOR STABILITY ANALYSIS
================================================================================
Rows used for stability analysis: 200

,Run,Method,Top_K,Feature_Set
0,1,Random Forest,5,"{Education, Age, Income, BMI, PhysHlth}"
3,1,DODA,5,"{GenHlth, HighBP, Age, BMI, PhysHlth}"
6,1,Random Forest,10,"{Fruits, Smoker, Education, GenHlth, HighBP, A..."
9,1,DODA,10,"{Income, Smoker, GenHlth, HighBP, Education, H..."
12,1,Random Forest,15,"{Veggies, PhysActivity, Fruits, DiffWalk, Smok..."
15,1,DODA,15,"{Stroke, HeartDiseaseorAttack, Income, PhysAct..."
18,1,Random Forest,20,"{Fruits, HighChol, AnyHealthcare, Age, Stroke,..."
21,1,DODA,20,"{Fruits, HighChol, AnyHealthcare, Age, Stroke,..."
24,2,Random Forest,5,"{Education, Age, Income, BMI, PhysHlth}"
27,2,DODA,5,"{GenHlth, HighBP, Age, BMI, PhysHlth}"

Feature count check:

           Method  Top_K  Feature_Count
3            DODA      5              5
9            DODA     10             10
15           DODA     15             15
21           DODA     20             20
0   Random Forest      5              5
6   Random Forest     10             10
12  Random Forest     15             15
18  Random Forest     20             20

✓ All feature sets contain the expected number of features.

In [29]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# RF VS DODA-RF
# =============================================================================

selection_frequency = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]


        # -------------------------------------------------------------
        # Number of CV runs
        # -------------------------------------------------------------

        total_runs = len(subset)


        # -------------------------------------------------------------
        # All features appearing across the 25 runs
        # -------------------------------------------------------------

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )


        # -------------------------------------------------------------
        # Calculate selection frequency
        # -------------------------------------------------------------

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set
                in subset["Feature_Set"]
            )


            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100

            })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

selection_frequency_df = pd.DataFrame(
    selection_frequency
)


# =============================================================================
# SORT RESULTS
# =============================================================================

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


# =============================================================================
# DISPLAY
# =============================================================================

print("=" * 80)
print("FEATURE SELECTION FREQUENCY")
print("=" * 80)

display(
    selection_frequency_df
)

================================================================================
FEATURE SELECTION FREQUENCY
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,DODA,5,Age,25,25,100.0
1,DODA,5,BMI,25,25,100.0
2,DODA,5,GenHlth,25,25,100.0
3,DODA,5,HighBP,25,25,100.0
4,DODA,5,PhysHlth,25,25,100.0
...,...,...,...,...,...,...
97,Random Forest,20,PhysHlth,25,25,100.0
98,Random Forest,20,Sex,25,25,100.0
99,Random Forest,20,Smoker,25,25,100.0
100,Random Forest,20,Stroke,25,25,100.0
101,Random Forest,20,Veggies,25,25,100.0

In [30]:
# =============================================================================
# TEST 2: JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Jaccard comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )

                union = len(
                    set_a.union(set_b)
                )


                if union == 0:
                    jaccard = 0.0

                else:
                    jaccard = (
                        intersection / union
                    )


                jaccard_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Union": union,

                    "Jaccard_Similarity": jaccard

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

jaccard_df = pd.DataFrame(
    jaccard_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("JACCARD SIMILARITY — PAIRWISE RESULTS")
print("=" * 80)

display(
    jaccard_df
)


# =============================================================================
# JACCARD SUMMARY
# =============================================================================

jaccard_summary = (
    jaccard_df
    .groupby(
        ["Method", "Top_K"]
    )["Jaccard_Similarity"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("JACCARD SIMILARITY SUMMARY")
print("=" * 80)

display(
    jaccard_summary
)

================================================================================
JACCARD SIMILARITY — PAIRWISE RESULTS
================================================================================

,Method,Top_K,Run_A,Run_B,Intersection,Union,Jaccard_Similarity
0,Random Forest,5,1,2,5,5,1.0
1,Random Forest,5,1,3,5,5,1.0
2,Random Forest,5,1,4,5,5,1.0
3,Random Forest,5,1,5,5,5,1.0
4,Random Forest,5,1,6,5,5,1.0
...,...,...,...,...,...,...,...
2395,DODA,20,22,24,20,20,1.0
2396,DODA,20,22,25,20,20,1.0
2397,DODA,20,23,24,20,20,1.0
2398,DODA,20,23,25,20,20,1.0
2399,DODA,20,24,25,20,20,1.0

================================================================================
JACCARD SIMILARITY SUMMARY
================================================================================

          Method  Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0           DODA      5      1.000000      0.00000        1.000          1.0
1           DODA     10      1.000000      0.00000        1.000          1.0
2           DODA     15      0.955833      0.05985        0.875          1.0
3           DODA     20      1.000000      0.00000        1.000          1.0
4  Random Forest      5      1.000000      0.00000        1.000          1.0
5  Random Forest     10      1.000000      0.00000        1.000          1.0
6  Random Forest     15      1.000000      0.00000        1.000          1.0
7  Random Forest     20      1.000000      0.00000        1.000          1.0

In [31]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

Total number of features: 21
================================================================================
KUNCHEVA INDEX — PAIRWISE RESULTS
================================================================================

             Method  Top_K  Run_A  Run_B  Intersection  Kuncheva_Index
0     Random Forest      5      1      2             5             1.0
1     Random Forest      5      1      3             5             1.0
2     Random Forest      5      1      4             5             1.0
3     Random Forest      5      1      5             5             1.0
4     Random Forest      5      1      6             5             1.0
...             ...    ...    ...    ...           ...             ...
2395           DODA     20     22     24            20             1.0
2396           DODA     20     22     25            20             1.0
2397           DODA     20     23     24            20             1.0
2398           DODA     20     23     25            20             1.0
2399           DODA     20     24     25            20             1.0

[2400 rows x 6 columns]

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

,Method,Top_K,Mean_Kuncheva,Std_Kuncheva,Min_Kuncheva,Max_Kuncheva
0,DODA,5,1.000000,0.000000,1.000000,1.0
1,DODA,10,1.000000,0.000000,1.000000,1.0
2,DODA,15,0.917556,0.111721,0.766667,1.0
3,DODA,20,1.000000,0.000000,1.000000,1.0
4,Random Forest,5,1.000000,0.000000,1.000000,1.0
5,Random Forest,10,1.000000,0.000000,1.000000,1.0
6,Random Forest,15,1.000000,0.000000,1.000000,1.0
7,Random Forest,20,1.000000,0.000000,1.000000,1.0

In [32]:
# =============================================================================
# TEST 4: RANDOM FOREST VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for top_k in sorted(stability_df["Top_K"].unique()):

    rf_subset = stability_df[
        (stability_df["Method"] == "Random Forest") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    doda_subset = stability_df[
        (stability_df["Method"] == "DODA") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    # Match Random Forest and DODA feature sets from the same CV run
    merged = pd.merge(
        rf_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "RF_Feature_Set"}
        ),
        doda_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "DODA_Feature_Set"}
        ),
        on="Run",
        how="inner"
    )

    for _, row in merged.iterrows():

        rf_set = row["RF_Feature_Set"]
        doda_set = row["DODA_Feature_Set"]

        # Common features
        intersection = len(
            rf_set.intersection(doda_set)
        )

        # Total unique features
        union = len(
            rf_set.union(doda_set)
        )

        # Jaccard agreement
        if union == 0:
            jaccard_agreement = 0.0
        else:
            jaccard_agreement = intersection / union

        agreement_results.append({
            "Top_K": top_k,
            "Run": row["Run"],
            "RF_Features": sorted(rf_set),
            "DODA_Features": sorted(doda_set),
            "Common_Features": sorted(
                rf_set.intersection(doda_set)
            ),
            "Common_Feature_Count": intersection,
            "Jaccard_Agreement": jaccard_agreement
        })


# Convert to DataFrame
agreement_df = pd.DataFrame(agreement_results)

display(agreement_df)

,Top_K,Run,RF_Features,DODA_Features,Common_Features,Common_Feature_Count,Jaccard_Agreement
0,5,1,"[Age, BMI, Education, Income, PhysHlth]","[Age, BMI, GenHlth, HighBP, PhysHlth]","[Age, BMI, PhysHlth]",3,0.428571
1,5,2,"[Age, BMI, Education, Income, PhysHlth]","[Age, BMI, GenHlth, HighBP, PhysHlth]","[Age, BMI, PhysHlth]",3,0.428571
2,5,3,"[Age, BMI, Education, Income, PhysHlth]","[Age, BMI, GenHlth, HighBP, PhysHlth]","[Age, BMI, PhysHlth]",3,0.428571
3,5,4,"[Age, BMI, Education, Income, PhysHlth]","[Age, BMI, GenHlth, HighBP, PhysHlth]","[Age, BMI, PhysHlth]",3,0.428571
4,5,5,"[Age, BMI, Education, Income, PhysHlth]","[Age, BMI, GenHlth, HighBP, PhysHlth]","[Age, BMI, PhysHlth]",3,0.428571
...,...,...,...,...,...,...,...
95,20,21,"[Age, AnyHealthcare, BMI, DiffWalk, Education,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, DiffWalk, Education,...",19,0.904762
96,20,22,"[Age, AnyHealthcare, BMI, DiffWalk, Education,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, DiffWalk, Education,...",19,0.904762
97,20,23,"[Age, AnyHealthcare, BMI, DiffWalk, Education,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, DiffWalk, Education,...",19,0.904762
98,20,24,"[Age, AnyHealthcare, BMI, DiffWalk, Education,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, DiffWalk, Education,...",19,0.904762
99,20,25,"[Age, AnyHealthcare, BMI, DiffWalk, Education,...","[Age, AnyHealthcare, BMI, CholCheck, DiffWalk,...","[Age, AnyHealthcare, BMI, DiffWalk, Education,...",19,0.904762

In [33]:
# =============================================================================
# RF VS DODA AGREEMENT SUMMARY
# =============================================================================

agreement_summary = (
    agreement_df
    .groupby("Top_K")["Jaccard_Agreement"]
    .agg(
        Mean_Agreement="mean",
        Std_Agreement="std",
        Min_Agreement="min",
        Max_Agreement="max"
    )
    .reset_index()
)

display(agreement_summary)

   Top_K  Mean_Agreement  Std_Agreement  Min_Agreement  Max_Agreement
0      5        0.428571            0.0       0.428571       0.428571
1     10        0.818182            0.0       0.818182       0.818182
2     15        0.764706            0.0       0.764706       0.764706
3     20        0.904762            0.0       0.904762       0.904762