In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# BORUTA

## 1. Baseline

In [10]:
!pip install boruta

Requirement already satisfied: boruta in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (0.4.3)
Requirement already satisfied: numpy>=1.10.4 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (2.1.3)
Requirement already satisfied: scikit-learn>=0.17.1 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (1.6.1)
Requirement already satisfied: scipy>=0.17.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from boruta) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from scikit-learn>=0.17.1->boruta) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anandha lakshmi\downloads\anaconda\lib\site-packages (from scikit-learn>=0.17.1->boruta) (3.5.0)

In [11]:
# =============================================================================
# BORUTA BASELINE FEATURE SELECTION (TOP-K = 5,10,15,20)
# =============================================================================

from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np


# =============================================================================
# BORUTA FEATURE SELECTION
# =============================================================================

# Random Forest used internally by Boruta
rf_boruta = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


# Initialize Boruta
boruta_selector = BorutaPy(
    estimator=rf_boruta,

    n_estimators="auto",

    verbose=0,

    random_state=42,

    max_iter=100,

    perc=100
)


# -------------------------------------------------------------------------
# Fit Boruta ONLY on training data
# -------------------------------------------------------------------------

boruta_selector.fit(
    X_train_scaled.values,
    y_train.values
)


# =============================================================================
# CREATE BORUTA RANKING
# =============================================================================

boruta_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "Boruta Rank": boruta_selector.ranking_,

    "Confirmed": boruta_selector.support_,

    "Tentative": boruta_selector.support_weak_

})


# -------------------------------------------------------------------------
# Sort by Boruta rank
# -------------------------------------------------------------------------

boruta_scores = boruta_scores.sort_values(
    by=["Boruta Rank", "Feature"]
).reset_index(drop=True)


print("=" * 70)
print("BORUTA FEATURE RANKING")
print("=" * 70)

print(boruta_scores)


# =============================================================================
# TOP-K FEATURE SELECTION
# =============================================================================

k_values = [5, 10, 15, 20]

boruta_results = {}


for k in k_values:

    # ---------------------------------------------------------------------
    # Select top-k features according to Boruta ranking
    # ---------------------------------------------------------------------

    top_features = (
        boruta_scores
        .head(k)["Feature"]
        .tolist()
    )


    # ---------------------------------------------------------------------
    # Boolean mask for selecting columns
    # ---------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    # ---------------------------------------------------------------------
    # Select training and testing features
    # ---------------------------------------------------------------------

    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # ---------------------------------------------------------------------
    # Store results
    # ---------------------------------------------------------------------

    boruta_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": boruta_scores.head(k)

    }


    # ---------------------------------------------------------------------
    # Display
    # ---------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} BORUTA FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nBoruta Ranking:")
    print(
        boruta_scores.head(k)
    )

======================================================================
BORUTA FEATURE RANKING
======================================================================
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
15               Veggies           14      False      False
16     HvyAlcoholConsump           15      False      False
17           NoDocbcCost           16      False      False
18                Stroke           17      False      False
19             CholCheck           18      False      False
20         AnyHealthcare           19      False      False
======================================================================
TOP 5 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income']

Boruta Ranking:
   Feature  Boruta Rank  Confirmed  Tentative
0      Age            1       True      False
1      BMI            1       True      False
2  GenHlth            1       True      False
3   HighBP            2      False      False
4   Income            3      False      False
======================================================================
TOP 10 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk']

Boruta Ranking:
     Feature  Boruta Rank  Confirmed  Tentative
0        Age            1       True      False
1        BMI            1       True      False
2    GenHlth            1       True      False
3     HighBP            2      False      False
4     Income            3      False      False
5   PhysHlth            4      False      False
6   HighChol            5      False      False
7  Education            6      False      False
8   MentHlth            7      False      False
9   DiffWalk            8      False      False
======================================================================
TOP 15 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Sex', 'Smoker', 'Fruits', 'PhysActivity']

Boruta Ranking:
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
======================================================================
TOP 20 BORUTA FEATURES
======================================================================
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Sex', 'Smoker', 'Fruits', 'PhysActivity', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost', 'Stroke', 'CholCheck']

Boruta Ranking:
                 Feature  Boruta Rank  Confirmed  Tentative
0                    Age            1       True      False
1                    BMI            1       True      False
2                GenHlth            1       True      False
3                 HighBP            2      False      False
4                 Income            3      False      False
5               PhysHlth            4      False      False
6               HighChol            5      False      False
7              Education            6      False      False
8               MentHlth            7      False      False
9               DiffWalk            8      False      False
10  HeartDiseaseorAttack            9      False      False
11                   Sex           10      False      False
12                Smoker           11      False      False
13                Fruits           12      False      False
14          PhysActivity           13      False      False
15               Veggies           14      False      False
16     HvyAlcoholConsump           15      False      False
17           NoDocbcCost           16      False      False
18                Stroke           17      False      False
19             CholCheck           18      False      False

In [12]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,

        eval_metric="logloss",
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()
    )
}

In [13]:
# =============================================================================
# MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


results = []


for k in k_values:

    Xtr = boruta_results[k]["X_train"]

    Xts = boruta_results[k]["X_test"]

    features = ", ".join(
        boruta_results[k]["features"]
    )


    # ---------------------------------------------------------------------
    # Evaluate every model
    # ---------------------------------------------------------------------

    for model_name, model in models.items():

        # Fit model
        model.fit(
            Xtr,
            y_train
        )


        # Predictions
        y_pred = model.predict(
            Xts
        )


        # Probability predictions
        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        # Store metrics
        results.append({

            "Method": "Boruta",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


# =============================================================================
# FINAL BORUTA RESULTS TABLE
# =============================================================================

boruta_results_df = pd.DataFrame(
    results
)


display(
    boruta_results_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta,5,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income",0.704347,0.308659,0.752671,0.437787,0.797671
1,Boruta,5,Random Forest,"Age, BMI, GenHlth, HighBP, Income",0.723172,0.300155,0.608349,0.401977,0.736248
2,Boruta,5,XGBoost,"Age, BMI, GenHlth, HighBP, Income",0.695784,0.304544,0.770623,0.436562,0.800745
3,Boruta,10,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.709533,0.313077,0.753099,0.442288,0.804871
4,Boruta,10,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.812136,0.340370,0.243482,0.283887,0.740769
5,Boruta,10,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.706765,0.313157,0.768770,0.445031,0.805572
6,Boruta,15,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.713150,0.316450,0.754808,0.445941,0.807144
7,Boruta,15,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.837063,0.410317,0.149594,0.219252,0.767797
8,Boruta,15,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.710056,0.315947,0.768913,0.447865,0.808701
9,Boruta,20,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.714195,0.318100,0.759652,0.448425,0.810549
10,Boruta,20,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.842358,0.453247,0.149167,0.224461,0.776700
11,Boruta,20,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.712627,0.318123,0.768770,0.450023,0.811615

In [14]:
boruta_results_df.to_csv(
    "../../../results/diabetes/baseline/boruta_baseline_results.csv",
    index=False
)

## 2. DODA

In [15]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [17]:
# =============================================================================
# BORUTA + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

doda_results = {}


# =============================================================================
# RUN BORUTA + DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"BORUTA + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest estimator used by Boruta
    # ---------------------------------------------------------------------

    rf_boruta = RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )


    # ---------------------------------------------------------------------
    # Boruta operator
    # ---------------------------------------------------------------------

    boruta = BorutaPy(
        estimator=rf_boruta,
        n_estimators="auto",
        max_iter=100,
        perc=100,
        random_state=42,
        verbose=0
    )


    # ---------------------------------------------------------------------
    # Wrap Boruta as a DODA operator
    # ---------------------------------------------------------------------

    boruta_operator = SklearnAdapter(
        boruta
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[boruta_operator],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("BORUTA + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
BORUTA + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D19870B770>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 5 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth']

======================================================================
BORUTA + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D19870B770>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 10 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth']

======================================================================
BORUTA + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D19870B770>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 15 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck']

======================================================================
BORUTA + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D19870B770>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.18000000000000002), 'CholCheck': np.float64(0.022222222222222223), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.05454545454545454), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.03076923076923077), 'Fruits': np.float64(0.016666666666666666), 'Veggies': np.float64(0.014285714285714285), 'HvyAlcoholConsump': np.float64(0.013333333333333334), 'AnyHealthcare': np.float64(0.010526315789473684), 'NoDocbcCost': np.float64(0.0125), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07142857142857142), 'PhysHlth': np.float64(0.2), 'DiffWalk': np.float64(0.1125), 'Sex': np.float64(0.020000000000000004), 'Age': np.float64(0.9), 'Education': np.float64(0.049999999999999996), 'Income': np.float64(0.09999999999999999)}
Top 20 Features Selected: ['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck', 'Sex', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost']

Selected Features:
['BMI', 'GenHlth', 'Age', 'HighBP', 'PhysHlth', 'HighChol', 'DiffWalk', 'HeartDiseaseorAttack', 'Income', 'MentHlth', 'Stroke', 'Smoker', 'Education', 'PhysActivity', 'CholCheck', 'Sex', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost']

======================================================================
BORUTA + DODA FEATURE SELECTION COMPLETED
======================================================================

In [18]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
3                    BMI        1.000000               1.000000
13               GenHlth        1.000000               1.000000
18                   Age        1.000000               1.000000
0                 HighBP        0.500000               0.500000
20                Income        0.333333               0.333333
15              PhysHlth        0.250000               0.250000
1               HighChol        0.200000               0.200000
19             Education        0.166667               0.166667
14              MentHlth        0.142857               0.142857
16              DiffWalk        0.125000               0.125000
6   HeartDiseaseorAttack        0.111111               0.111111
17                   Sex        0.100000               0.100000
4                 Smoker        0.090909               0.090909
8                 Fruits        0.083333               0.083333
7           PhysActivity        0.076923               0.076923
9                Veggies        0.071429               0.071429
10     HvyAlcoholConsump        0.066667               0.066667
12           NoDocbcCost        0.062500               0.062500
5                 Stroke        0.058824               0.058824
2              CholCheck        0.055556               0.055556
11         AnyHealthcare        0.052632               0.052632

In [19]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                 HighBP              1.0
3                    BMI              1.0
13               GenHlth              1.0
6   HeartDiseaseorAttack              1.0
5                 Stroke              1.0
18                   Age              0.9
16              DiffWalk              0.9
1               HighChol              0.9
15              PhysHlth              0.8
4                 Smoker              0.6
14              MentHlth              0.5
2              CholCheck              0.4
7           PhysActivity              0.4
20                Income              0.3
19             Education              0.3
12           NoDocbcCost              0.2
9                Veggies              0.2
8                 Fruits              0.2
11         AnyHealthcare              0.2
10     HvyAlcoholConsump              0.2
17                   Sex              0.2

In [20]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
3                    BMI          1.000000
13               GenHlth          1.000000
18                   Age          0.900000
0                 HighBP          0.500000
15              PhysHlth          0.200000
1               HighChol          0.180000
16              DiffWalk          0.112500
6   HeartDiseaseorAttack          0.111111
20                Income          0.100000
14              MentHlth          0.071429
5                 Stroke          0.058824
4                 Smoker          0.054545
19             Education          0.050000
7           PhysActivity          0.030769
2              CholCheck          0.022222
17                   Sex          0.020000
8                 Fruits          0.016667
9                Veggies          0.014286
10     HvyAlcoholConsump          0.013333
12           NoDocbcCost          0.012500
11         AnyHealthcare          0.010526

In [21]:
selector.get_selected_features()

['BMI',
 'GenHlth',
 'Age',
 'HighBP',
 'PhysHlth',
 'HighChol',
 'DiffWalk',
 'HeartDiseaseorAttack',
 'Income',
 'MentHlth']

In [22]:
comparison = selector.compare_scores()

comparison

======================================================================
MATHEMATICAL vs CLINICAL vs HADAMARDFUSION
======================================================================

Fusion Method: HadamardFusion

Top Features After Fusion:
                Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0                   BMI          1              2           1            0
1               GenHlth          2              5           2            0
2                   Age          3              8           3            0
3                HighBP          4              1           4            0
4              PhysHlth          6              9           5            1
5              HighChol          7              6           6            1
6              DiffWalk         10              7           7            3
7  HeartDiseaseorAttack         11              4           8            3
8                Income          5             15           9           -4
9              MentHlth          9             11          10           -1

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,BMI,1,1.0000,2,1.0,1,1.0000,0
1,GenHlth,2,1.0000,5,1.0,2,1.0000,0
2,Age,3,1.0000,8,0.9,3,0.9000,0
3,HighBP,4,0.5000,1,1.0,4,0.5000,0
4,PhysHlth,6,0.2500,9,0.8,5,0.2000,1
5,HighChol,7,0.2000,6,0.9,6,0.1800,1
6,DiffWalk,10,0.1250,7,0.9,7,0.1125,3
7,HeartDiseaseorAttack,11,0.1111,4,1.0,8,0.1111,3
8,Income,5,0.3333,15,0.3,9,0.1000,-4
9,MentHlth,9,0.1429,11,0.5,10,0.0714,-1
10,Stroke,19,0.0588,3,1.0,11,0.0588,8
11,Smoker,13,0.0909,10,0.6,12,0.0545,1
12,Education,8,0.1667,14,0.3,13,0.0500,-5
13,PhysActivity,15,0.0769,13,0.4,14,0.0308,1
14,CholCheck,20,0.0556,12,0.4,15,0.0222,5
15,Sex,12,0.1000,21,0.2,16,0.0200,-4
16,Fruits,14,0.0833,16,0.2,17,0.0167,-3
17,Veggies,16,0.0714,17,0.2,18,0.0143,-2
18,HvyAlcoholConsump,17,0.0667,18,0.2,19,0.0133,-2
19,NoDocbcCost,18,0.0625,20,0.2,20,0.0125,-2
20,AnyHealthcare,21,0.0526,19,0.2,21,0.0105,0

In [23]:
# =============================================================================
# BORUTA + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


doda_model_results = []


for k in k_values:

    Xtr = doda_results[k]["X_train"]

    Xts = doda_results[k]["X_test"]

    features = ", ".join(
        doda_results[k]["features"]
    )


    # ---------------------------------------------------------------------
    # Evaluate all models
    # ---------------------------------------------------------------------

    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        doda_model_results.append({

            "Method": "Boruta + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


# =============================================================================
# FINAL RESULTS TABLE
# =============================================================================

boruta_doda_results_df = pd.DataFrame(
    doda_model_results
)


display(
    boruta_doda_results_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta + DODA,5,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
1,Boruta + DODA,5,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth",0.728925,0.303608,0.597094,0.402536,0.735492
2,Boruta + DODA,5,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
3,Boruta + DODA,10,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712583,0.315563,0.752244,0.444613,0.805783
4,Boruta + DODA,10,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.805622,0.338485,0.283944,0.308825,0.731153
5,Boruta + DODA,10,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.708443,0.314562,0.768770,0.446449,0.807820
6,Boruta + DODA,15,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712975,0.316255,0.754523,0.445697,0.807390
7,Boruta + DODA,15,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.829546,0.382111,0.185639,0.249880,0.760447
8,Boruta + DODA,15,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.710753,0.316303,0.767346,0.447956,0.808930
9,Boruta + DODA,20,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
10,Boruta + DODA,20,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.843098,0.459770,0.148169,0.224114,0.778220
11,Boruta + DODA,20,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [24]:
boruta_doda_results_df.to_csv(
    "../../../results/diabetes/doda/boruta_doda_results.csv",
    index=False
)

In [25]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        boruta_results_df,
        boruta_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta,5,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income",0.704347,0.308659,0.752671,0.437787,0.797671
1,Boruta,5,Random Forest,"Age, BMI, GenHlth, HighBP, Income",0.723172,0.300155,0.608349,0.401977,0.736248
2,Boruta,5,XGBoost,"Age, BMI, GenHlth, HighBP, Income",0.695784,0.304544,0.770623,0.436562,0.800745
3,Boruta,10,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.709533,0.313077,0.753099,0.442288,0.804871
4,Boruta,10,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.812136,0.340370,0.243482,0.283887,0.740769
5,Boruta,10,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.706765,0.313157,0.768770,0.445031,0.805572
6,Boruta,15,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.713150,0.316450,0.754808,0.445941,0.807144
7,Boruta,15,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.837063,0.410317,0.149594,0.219252,0.767797
8,Boruta,15,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.710056,0.315947,0.768913,0.447865,0.808701
9,Boruta,20,Logistic Regression,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.714195,0.318100,0.759652,0.448425,0.810549
10,Boruta,20,Random Forest,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.842358,0.453247,0.149167,0.224461,0.776700
11,Boruta,20,XGBoost,"Age, BMI, GenHlth, HighBP, Income, PhysHlth, H...",0.712627,0.318123,0.768770,0.450023,0.811615
12,Boruta + DODA,5,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth",0.702887,0.307388,0.752244,0.436436,0.797001
13,Boruta + DODA,5,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth",0.728925,0.303608,0.597094,0.402536,0.735492
14,Boruta + DODA,5,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth",0.694629,0.303196,0.767773,0.434719,0.800155
15,Boruta + DODA,10,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712583,0.315563,0.752244,0.444613,0.805783
16,Boruta + DODA,10,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.805622,0.338485,0.283944,0.308825,0.731153
17,Boruta + DODA,10,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.708443,0.314562,0.768770,0.446449,0.807820
18,Boruta + DODA,15,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712975,0.316255,0.754523,0.445697,0.807390
19,Boruta + DODA,15,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.829546,0.382111,0.185639,0.249880,0.760447
20,Boruta + DODA,15,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.710753,0.316303,0.767346,0.447956,0.808930
21,Boruta + DODA,20,Logistic Regression,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.714195,0.318100,0.759652,0.448425,0.810549
22,Boruta + DODA,20,Random Forest,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.843098,0.459770,0.148169,0.224114,0.778220
23,Boruta + DODA,20,XGBoost,"BMI, GenHlth, Age, HighBP, PhysHlth, HighChol,...",0.712605,0.318104,0.768770,0.450004,0.811610

In [26]:
# ============================================================
# BORUTA + DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from boruta import BorutaPy

from doda import DODASelector
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion
from doda.adapters.sklearn_adapter import SklearnAdapter


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "clinical_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should contain the ORIGINAL Heart Disease data
# before imputation/scaling.
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"BORUTA + DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0


    # ========================================================
    # 25 REPEATED CV RUNS
    # ========================================================

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()


        # ----------------------------------------------------
        # IMPUTATION
        # ----------------------------------------------------

        imputer = SimpleImputer(
            strategy="median"
        )

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )


        # ----------------------------------------------------
        # BORUTA RANDOM FOREST
        # ----------------------------------------------------

        rf_boruta = RandomForestClassifier(
            n_estimators=200,
            random_state=RANDOM_STATE,
            class_weight="balanced",
            n_jobs=-1
        )


        # ----------------------------------------------------
        # BORUTA SELECTOR
        # ----------------------------------------------------

        boruta = BorutaPy(
            estimator=rf_boruta,
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )


        # ----------------------------------------------------
        # DODA ADAPTER
        # ----------------------------------------------------

        boruta_operator = SklearnAdapter(
            boruta
        )


        # ----------------------------------------------------
        # CLINICAL KNOWLEDGE PROVIDER
        # ----------------------------------------------------

        provider = JSONProvider(
            WEIGHTS_FILE
        )


        # ----------------------------------------------------
        # DODA SELECTOR
        # ----------------------------------------------------

        doda_selector = DODASelector(

            operators=[boruta_operator],

            provider=provider,

            fusion=RankFusion(),

            top_k=TOP_K

        )


        # ----------------------------------------------------
        # FIT ONLY ON TRAINING FOLD
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )


        # ----------------------------------------------------
        # SELECTED FEATURES
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )


        selected_feature_sets.append(
            set(selected_features)
        )


        all_runs.append({

            "Top_K": TOP_K,

            "Run": run_number,

            "Selected_Features": selected_features

        })


        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []


    for i in range(
        len(selected_feature_sets)
    ):

        for j in range(
            i + 1,
            len(selected_feature_sets)
        ):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]


            intersection = len(
                set_a.intersection(set_b)
            )

            union = len(
                set_a.union(set_b)
            )


            jaccard = (
                intersection / union
            )


            jaccard_scores.append(
                jaccard
            )


            all_jaccard.append({

                "Top_K": TOP_K,

                "Run_A": i + 1,

                "Run_B": j + 1,

                "Jaccard_Similarity": jaccard

            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(
        jaccard_scores
    )

    std_jaccard = np.std(
        jaccard_scores
    )

    min_jaccard = np.min(
        jaccard_scores
    )

    max_jaccard = np.max(
        jaccard_scores
    )


    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(
        f"Number of runs:          "
        f"{len(selected_feature_sets)}"
    )

    print(
        f"Number of comparisons:   "
        f"{len(jaccard_scores)}"
    )

    print(
        f"Mean Jaccard Similarity: "
        f"{mean_jaccard:.4f}"
    )

    print(
        f"Standard Deviation:      "
        f"{std_jaccard:.4f}"
    )

    print(
        f"Minimum Jaccard:         "
        f"{min_jaccard:.4f}"
    )

    print(
        f"Maximum Jaccard:         "
        f"{max_jaccard:.4f}"
    )


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}


    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )


    for feature, count in feature_counts.items():

        all_frequency.append({

            "Top_K": TOP_K,

            "Feature": feature,

            "Selection_Count": count,

            "Selection_Frequency":
                count / len(selected_feature_sets)

        })


    frequency_df_topk = pd.DataFrame(

        [

            {

                "Feature": feature,

                "Selection_Count": count,

                "Selection_Frequency":
                    count / len(selected_feature_sets)

            }

            for feature, count
            in feature_counts.items()

        ]

    ).sort_values(

        "Selection_Frequency",

        ascending=False

    )


    print(
        "\nFEATURE SELECTION FREQUENCY"
    )

    print(
        frequency_df_topk.to_string(
            index=False
        )
    )


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(
    all_runs
)

jaccard_df = pd.DataFrame(
    all_jaccard
)

frequency_df = pd.DataFrame(
    all_frequency
)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []


for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]


    summary_rows.append({

        "Top_K": TOP_K,

        "Mean_Jaccard":
            subset.mean(),

        "Std_Jaccard":
            subset.std(),

        "Min_Jaccard":
            subset.min(),

        "Max_Jaccard":
            subset.max()

    })


summary_df = pd.DataFrame(
    summary_rows
)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("BORUTA + DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(

    summary_df.to_string(

        index=False,

        float_format=lambda x:
            f"{x:.4f}"

    )

)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/diabetes/"
    "boruta_doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/diabetes/"
    "boruta_doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/diabetes/"
    "boruta_doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/diabetes/"
    "boruta_doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")

print(
    "1. boruta_doda_stability_all_topk_runs.csv"
)

print(
    "2. boruta_doda_stability_all_topk_jaccard.csv"
)

print(
    "3. boruta_doda_stability_all_topk_frequency.csv"
)

print(
    "4. boruta_doda_stability_all_topk_summary.csv"
)

======================================================================
BORUTA + DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D1A2358910>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028991596638655463, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Run 01: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D1A235A850>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028790389395194696, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Run 02: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D1A2312C40>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.08333333333333333), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.027972027972027972, 'BMI': 0.03278688524590164, 'Smoker': 0.029910714285714284, 'Stroke': 0.02938045560996381, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.028850145288501453, 'Fruits': 0.028594771241830064, 'Veggies': 0.02821939586645469, 'HvyAlcoholConsump': 0.02803921568627451, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.02786377708978328, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Run 03: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D1A23109D0>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.1), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028790389395194696, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028991596638655463, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Run 04: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D1A23BD6D0>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.1), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.09090909090909091), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights

In [27]:
# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier
from boruta import BorutaPy

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# =============================================================================
# CONFIGURATION
# =============================================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

target_column = "Diabetes_binary"

X = df.drop(columns=[target_column])
y = df[target_column]

feature_names = X.columns.tolist()


# =============================================================================
# MODELS
# =============================================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# =============================================================================
# CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

provider = JSONProvider(
    "clinical_weights.json"
)


# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# =============================================================================
# RESULTS STORAGE
# =============================================================================

results = []


# =============================================================================
# CROSS-VALIDATION LOOP
# =============================================================================

for run_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    print("\n" + "=" * 80)
    print(f"REPEATED STRATIFIED CV RUN {run_number}")
    print("=" * 80)

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # =========================================================================
    # IMPUTATION
    # =========================================================================

    imputer = SimpleImputer(
        strategy="median"
    )

    X_train_imp_array = imputer.fit_transform(
        X_train
    )

    X_test_imp_array = imputer.transform(
        X_test
    )

    X_train_imp = pd.DataFrame(
        X_train_imp_array,
        columns=feature_names,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        X_test_imp_array,
        columns=feature_names,
        index=X_test.index
    )


    # =========================================================================
    # FEATURE SELECTION FOR EACH TOP-K VALUE
    # =========================================================================

    for top_k in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"TOP-K = {top_k}")
        print("-" * 80)


        # =====================================================================
        # BASELINE BORUTA FEATURE SELECTION
        # =====================================================================

        rf_boruta = RandomForestClassifier(
            n_estimators=200,
            random_state=RANDOM_STATE,
            class_weight="balanced",
            n_jobs=-1
        )

        boruta_selector = BorutaPy(
            estimator=rf_boruta,
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )

        boruta_selector.fit(
            X_train_imp.values,
            y_train.values
        )


        boruta_scores = pd.DataFrame({

            "Feature": feature_names,

            "Boruta Rank":
                boruta_selector.ranking_,

            "Confirmed":
                boruta_selector.support_,

            "Tentative":
                boruta_selector.support_weak_

        })


        boruta_scores = (
            boruta_scores
            .sort_values(
                by=["Boruta Rank", "Feature"]
            )
            .reset_index(drop=True)
        )


        # Create deterministic ranking
        boruta_scores["Final Rank"] = (
            np.arange(len(boruta_scores)) + 1
        )


        boruta_features = (
            boruta_scores
            .head(top_k)["Feature"]
            .tolist()
        )


        print("Boruta-selected features:")
        print(boruta_features)


        # =====================================================================
        # DODA-BORUTA FEATURE SELECTION
        # =====================================================================

        boruta = BorutaPy(
            estimator=RandomForestClassifier(
                n_estimators=200,
                random_state=RANDOM_STATE,
                class_weight="balanced",
                n_jobs=-1
            ),
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )


        boruta_operator = SklearnAdapter(
            boruta
        )


        doda_selector = DODASelector(
            operators=[boruta_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )


        doda_selector.fit(
            X_train_imp,
            y_train
        )


        doda_features = list(
            doda_selector.get_selected_features()
        )


        print("DODA-Boruta-selected features:")
        print(doda_features)


        # =====================================================================
        # PREPARE SELECTED FEATURE MATRICES
        # =====================================================================

        X_train_boruta_selected = (
            X_train_imp[boruta_features]
        )

        X_test_boruta_selected = (
            X_test_imp[boruta_features]
        )

        X_train_doda_selected = (
            X_train_imp[doda_features]
        )

        X_test_doda_selected = (
            X_test_imp[doda_features]
        )


        # =====================================================================
        # MODEL EVALUATION
        # =====================================================================

        selected_feature_sets = {

            "Boruta": (
                X_train_boruta_selected,
                X_test_boruta_selected,
                boruta_features
            ),

            "DODA": (
                X_train_doda_selected,
                X_test_doda_selected,
                doda_features
            )

        }


        for method, (
            X_train_selected,
            X_test_selected,
            selected_features
        ) in selected_feature_sets.items():

            for model_name, model_template in models.items():

                model = clone(
                    model_template
                )

                X_train_model = (
                    X_train_selected.copy()
                )

                X_test_model = (
                    X_test_selected.copy()
                )


                # -------------------------------------------------------------
                # Scale only Logistic Regression
                # -------------------------------------------------------------

                if model_name == "Logistic Regression":

                    model_scaler = StandardScaler()

                    X_train_model = (
                        model_scaler.fit_transform(
                            X_train_model
                        )
                    )

                    X_test_model = (
                        model_scaler.transform(
                            X_test_model
                        )
                    )


                # -------------------------------------------------------------
                # Train model
                # -------------------------------------------------------------

                model.fit(
                    X_train_model,
                    y_train
                )

                y_pred = model.predict(
                    X_test_model
                )

                y_prob = model.predict_proba(
                    X_test_model
                )[:, 1]


                # -------------------------------------------------------------
                # Calculate metrics
                # -------------------------------------------------------------

                accuracy = accuracy_score(
                    y_test,
                    y_pred
                )

                precision = precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                roc_auc = roc_auc_score(
                    y_test,
                    y_prob
                )


                # -------------------------------------------------------------
                # Store results
                # -------------------------------------------------------------

                results.append({

                    "Run": run_number,

                    "Method": method,

                    "Top_K": top_k,

                    "Model": model_name,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": roc_auc,

                    "Selected_Features": selected_features

                })


# =============================================================================
# RESULTS DATAFRAME
# =============================================================================

results_df = pd.DataFrame(
    results
)


# =============================================================================
# DISPLAY RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("REPEATED STRATIFIED CV RESULTS — BORUTA VS DODA-BORUTA")
print("=" * 80)

display(
    results_df.head()
)

print(
    "Total evaluation rows:",
    len(results_df)
)

================================================================================
REPEATED STRATIFIED CV RUN 1
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------
Boruta-selected features:
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D198852930>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028991596638655463, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 5 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']
DODA-Boruta-selected features:
['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------
Boruta-selected features:
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D198852930>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028991596638655463, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 10 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth']
DODA-Boruta-selected features:
['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth']

--------------------------------------------------------------------------------
TOP-K = 15
--------------------------------------------------------------------------------
Boruta-selected features:
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Fruits', 'Sex', 'Smoker', 'PhysActivity']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D198852930>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028991596638655463, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 15 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth', 'Education', 'Smoker', 'Stroke', 'PhysActivity', 'Fruits']
DODA-Boruta-selected features:
['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth', 'Education', 'Smoker', 'Stroke', 'PhysActivity', 'Fruits']

--------------------------------------------------------------------------------
TOP-K = 20
--------------------------------------------------------------------------------
Boruta-selected features:
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income', 'PhysHlth', 'HighChol', 'Education', 'MentHlth', 'DiffWalk', 'HeartDiseaseorAttack', 'Fruits', 'Sex', 'Smoker', 'PhysActivity', 'Veggies', 'HvyAlcoholConsump', 'NoDocbcCost', 'Stroke', 'CholCheck']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D198852930>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:
{'BorutaPy_1': {'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.5), 'HighChol': np.float64(0.2), 'CholCheck': np.float64(0.05555555555555555), 'BMI': np.float64(1.0), 'Smoker': np.float64(0.09090909090909091), 'Stroke': np.float64(0.058823529411764705), 'HeartDiseaseorAttack': np.float64(0.1111111111111111), 'PhysActivity': np.float64(0.07692307692307693), 'Fruits': np.float64(0.1), 'Veggies': np.float64(0.07142857142857142), 'HvyAlcoholConsump': np.float64(0.06666666666666667), 'AnyHealthcare': np.float64(0.05263157894736842), 'NoDocbcCost': np.float64(0.0625), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.14285714285714285), 'PhysHlth': np.float64(0.25), 'DiffWalk': np.float64(0.125), 'Sex': np.float64(0.09090909090909091), 'Age': np.float64(1.0), 'Education': np.float64(0.16666666666666666), 'Income': np.float64(0.3333333333333333)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.02813852813852814, 'BMI': 0.03278688524590164, 'Smoker': 0.029709507042253523, 'Stroke': 0.029551337359792925, 'HeartDiseaseorAttack': 0.030886196246139225, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.028991596638655463, 'Veggies': 0.028404512489927477, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027526395173453996, 'NoDocbcCost': 0.02803921568627451, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.030309988518943745, 'PhysHlth': 0.03149801587301587, 'DiffWalk': 0.030834914611005692, 'Sex': 0.028790389395194696, 'Age': 0.03252247488101534, 'Education': 0.03007688828584351, 'Income': 0.030798389007344232}
Top 20 Features Selected: ['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth', 'Education', 'Smoker', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'HvyAlcoholConsump', 'CholCheck', 'NoDocbcCost']
DODA-Boruta-selected features:
['BMI', 'GenHlth', 'HighBP', 'Age', 'HighChol', 'PhysHlth', 'HeartDiseaseorAttack', 'DiffWalk', 'Income', 'MentHlth', 'Education', 'Smoker', 'Stroke', 'PhysActivity', 'Fruits', 'Sex', 'Veggies', 'HvyAlcoholConsump', 'CholCheck', 'NoDocbcCost']

================================================================================
REPEATED STRATIFIED CV RUN 2
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------
Boruta-selected features:
['Age', 'BMI', 'GenHlth', 'HighBP', 'Income']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D198852930>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of rankings: 21
Operator Scores:

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,Boruta,5,Logistic Regression,0.848676,0.523537,0.117253,0.191596,0.794844,"[Age, BMI, GenHlth, HighBP, Income]"
1,1,Boruta,5,Random Forest,0.839416,0.437029,0.173529,0.248419,0.752930,"[Age, BMI, GenHlth, HighBP, Income]"
2,1,Boruta,5,XGBoost,0.851073,0.554054,0.134350,0.216260,0.803638,"[Age, BMI, GenHlth, HighBP, Income]"
3,1,DODA,5,Logistic Regression,0.850310,0.544161,0.130788,0.210889,0.801032,"[BMI, GenHlth, HighBP, Age, HighChol]"
4,1,DODA,5,Random Forest,0.847413,0.503556,0.161419,0.244471,0.783598,"[BMI, GenHlth, HighBP, Age, HighChol]"

Total evaluation rows: 600

In [28]:
# =============================================================================
# PREPARE FEATURE SETS FOR STABILITY ANALYSIS
# mRMR VS DODA-mRMR
# =============================================================================

import ast
import numpy as np
import pandas as pd


# =============================================================================
# CONVERT SELECTED FEATURES TO SET
# =============================================================================

def convert_to_set(features):
    """
    Convert Selected_Features into a Python set.
    Handles lists, tuples, NumPy arrays, and strings.
    """

    if isinstance(features, str):

        # Handle string representation of a list
        if features.startswith("[") and features.endswith("]"):

            try:
                features = ast.literal_eval(features)

            except Exception:
                features = features.split(",")

        else:
            features = features.split(",")


    return {
        str(feature).strip().strip("'").strip('"')
        for feature in features
        if str(feature).strip()
    }


# =============================================================================
# USE ONLY ONE MODEL
# =============================================================================

# Feature selection is independent of the predictive model.
# Therefore, Logistic Regression rows are sufficient.

stability_df = results_df[
    results_df["Model"] == "Logistic Regression"
].copy()


# =============================================================================
# CONVERT FEATURE LISTS TO SETS
# =============================================================================

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(convert_to_set)
)


# =============================================================================
# CHECK RESULTS
# =============================================================================

print("=" * 80)
print("FEATURE SETS PREPARED FOR STABILITY ANALYSIS")
print("=" * 80)

print(
    "Rows used for stability analysis:",
    len(stability_df)
)


# =============================================================================
# DISPLAY SAMPLE
# =============================================================================

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head(10)
)


# =============================================================================
# CHECK FEATURE COUNT
# =============================================================================

stability_df["Feature_Count"] = (
    stability_df["Feature_Set"]
    .apply(len)
)


print("\nFeature count check:")

display(
    stability_df[
        [
            "Method",
            "Top_K",
            "Feature_Count"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Method", "Top_K"]
    )
)


# =============================================================================
# VERIFY EXPECTED TOP-K
# =============================================================================

invalid_rows = stability_df[
    stability_df["Feature_Count"] != stability_df["Top_K"]
]


if len(invalid_rows) == 0:

    print(
        "\n✓ All feature sets contain the expected number of features."
    )

else:

    print(
        "\n⚠ WARNING: Some feature sets do not match their Top-K value."
    )

    display(
        invalid_rows[
            [
                "Run",
                "Method",
                "Top_K",
                "Feature_Count",
                "Feature_Set"
            ]
        ]
    )

================================================================================
FEATURE SETS PREPARED FOR STABILITY ANALYSIS
================================================================================
Rows used for stability analysis: 200

    Run  Method  Top_K                                        Feature_Set
0     1  Boruta      5                {GenHlth, Income, BMI, HighBP, Age}
3     1    DODA      5              {GenHlth, BMI, HighBP, Age, HighChol}
6     1  Boruta     10  {PhysHlth, GenHlth, MentHlth, Income, Educatio...
9     1    DODA     10  {PhysHlth, GenHlth, MentHlth, Income, HeartDis...
12    1  Boruta     15  {PhysHlth, GenHlth, Fruits, MentHlth, Income, ...
15    1    DODA     15  {PhysHlth, GenHlth, Fruits, Stroke, MentHlth, ...
18    1  Boruta     20  {Fruits, HvyAlcoholConsump, BMI, HighBP, Veggi...
21    1    DODA     20  {Fruits, HvyAlcoholConsump, BMI, HighBP, Veggi...
24    2  Boruta      5                {GenHlth, Income, BMI, HighBP, Age}
27    2    DODA      5              {GenHlth, BMI, HighBP, Age, HighChol}

Feature count check:

    Method  Top_K  Feature_Count
0   Boruta      5              5
6   Boruta     10             10
12  Boruta     15             15
18  Boruta     20             20
3     DODA      5              5
9     DODA     10             10
15    DODA     15             15
21    DODA     20             20

✓ All feature sets contain the expected number of features.

In [29]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# BORUTA VS DODA
# =============================================================================

selection_frequency = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]


        # -------------------------------------------------------------
        # Number of CV runs
        # -------------------------------------------------------------

        total_runs = len(subset)


        # -------------------------------------------------------------
        # All features appearing across the 25 runs
        # -------------------------------------------------------------

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )


        # -------------------------------------------------------------
        # Calculate selection frequency
        # -------------------------------------------------------------

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set
                in subset["Feature_Set"]
            )


            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100

            })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

selection_frequency_df = pd.DataFrame(
    selection_frequency
)


# =============================================================================
# SORT RESULTS
# =============================================================================

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


# =============================================================================
# DISPLAY
# =============================================================================

print("=" * 80)
print("FEATURE SELECTION FREQUENCY")
print("=" * 80)

display(
    selection_frequency_df
)

================================================================================
FEATURE SELECTION FREQUENCY
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,Boruta,5,Age,25,25,100.0
1,Boruta,5,BMI,25,25,100.0
2,Boruta,5,GenHlth,25,25,100.0
3,Boruta,5,HighBP,25,25,100.0
4,Boruta,5,Income,25,25,100.0
...,...,...,...,...,...,...
96,DODA,20,PhysHlth,25,25,100.0
97,DODA,20,Sex,25,25,100.0
98,DODA,20,Smoker,25,25,100.0
99,DODA,20,Stroke,25,25,100.0
100,DODA,20,Veggies,25,25,100.0

In [30]:
# =============================================================================
# TEST 2: JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Jaccard comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )

                union = len(
                    set_a.union(set_b)
                )


                if union == 0:
                    jaccard = 0.0

                else:
                    jaccard = (
                        intersection / union
                    )


                jaccard_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Union": union,

                    "Jaccard_Similarity": jaccard

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

jaccard_df = pd.DataFrame(
    jaccard_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("JACCARD SIMILARITY — PAIRWISE RESULTS")
print("=" * 80)

display(
    jaccard_df
)


# =============================================================================
# JACCARD SUMMARY
# =============================================================================

jaccard_summary = (
    jaccard_df
    .groupby(
        ["Method", "Top_K"]
    )["Jaccard_Similarity"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("JACCARD SIMILARITY SUMMARY")
print("=" * 80)

display(
    jaccard_summary
)

================================================================================
JACCARD SIMILARITY — PAIRWISE RESULTS
================================================================================

      Method  Top_K  Run_A  Run_B  Intersection  Union  Jaccard_Similarity
0     Boruta      5      1      2             5      5                 1.0
1     Boruta      5      1      3             5      5                 1.0
2     Boruta      5      1      4             5      5                 1.0
3     Boruta      5      1      5             5      5                 1.0
4     Boruta      5      1      6             5      5                 1.0
...      ...    ...    ...    ...           ...    ...                 ...
2395    DODA     20     22     24            20     20                 1.0
2396    DODA     20     22     25            20     20                 1.0
2397    DODA     20     23     24            20     20                 1.0
2398    DODA     20     23     25            20     20                 1.0
2399    DODA     20     24     25            20     20                 1.0

[2400 rows x 7 columns]

================================================================================
JACCARD SIMILARITY SUMMARY
================================================================================

   Method  Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0  Boruta      5      1.000000     0.000000        1.000          1.0
1  Boruta     10      1.000000     0.000000        1.000          1.0
2  Boruta     15      1.000000     0.000000        1.000          1.0
3  Boruta     20      1.000000     0.000000        1.000          1.0
4    DODA      5      1.000000     0.000000        1.000          1.0
5    DODA     10      1.000000     0.000000        1.000          1.0
6    DODA     15      0.935833     0.062582        0.875          1.0
7    DODA     20      1.000000     0.000000        1.000          1.0

In [31]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

Total number of features: 21
================================================================================
KUNCHEVA INDEX — PAIRWISE RESULTS
================================================================================

      Method  Top_K  Run_A  Run_B  Intersection  Kuncheva_Index
0     Boruta      5      1      2             5             1.0
1     Boruta      5      1      3             5             1.0
2     Boruta      5      1      4             5             1.0
3     Boruta      5      1      5             5             1.0
4     Boruta      5      1      6             5             1.0
...      ...    ...    ...    ...           ...             ...
2395    DODA     20     22     24            20             1.0
2396    DODA     20     22     25            20             1.0
2397    DODA     20     23     24            20             1.0
2398    DODA     20     23     25            20             1.0
2399    DODA     20     24     25            20             1.0

[2400 rows x 6 columns]

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

   Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0  Boruta      5       1.000000       0.00000      1.000000           1.0
1  Boruta     10       1.000000       0.00000      1.000000           1.0
2  Boruta     15       1.000000       0.00000      1.000000           1.0
3  Boruta     20       1.000000       0.00000      1.000000           1.0
4    DODA      5       1.000000       0.00000      1.000000           1.0
5    DODA     10       1.000000       0.00000      1.000000           1.0
6    DODA     15       0.880222       0.11682      0.766667           1.0
7    DODA     20       1.000000       0.00000      1.000000           1.0

In [32]:
# =============================================================================
# TEST 4: BORUTA VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for top_k in sorted(
    stability_df["Top_K"].unique()
):

    boruta_subset = stability_df[
        (stability_df["Method"] == "Boruta") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    doda_subset = stability_df[
        (stability_df["Method"] == "DODA") &
        (stability_df["Top_K"] == top_k)
    ].copy()


    # Match Boruta and DODA feature sets
    # from the same CV run

    merged = pd.merge(

        boruta_subset[
            ["Run", "Feature_Set"]
        ].rename(
            columns={
                "Feature_Set":
                "Boruta_Feature_Set"
            }
        ),

        doda_subset[
            ["Run", "Feature_Set"]
        ].rename(
            columns={
                "Feature_Set":
                "DODA_Feature_Set"
            }
        ),

        on="Run",

        how="inner"
    )


    for _, row in merged.iterrows():

        boruta_set = row[
            "Boruta_Feature_Set"
        ]

        doda_set = row[
            "DODA_Feature_Set"
        ]


        # ---------------------------------------------------------
        # Common features
        # ---------------------------------------------------------

        intersection = len(
            boruta_set.intersection(
                doda_set
            )
        )


        # ---------------------------------------------------------
        # Total unique features
        # ---------------------------------------------------------

        union = len(
            boruta_set.union(
                doda_set
            )
        )


        # ---------------------------------------------------------
        # Jaccard agreement
        # ---------------------------------------------------------

        if union == 0:

            jaccard_agreement = 0.0

        else:

            jaccard_agreement = (
                intersection / union
            )


        agreement_results.append({

            "Top_K":
                top_k,

            "Run":
                row["Run"],

            "Boruta_Features":
                sorted(boruta_set),

            "DODA_Features":
                sorted(doda_set),

            "Common_Features":
                sorted(
                    boruta_set.intersection(
                        doda_set
                    )
                ),

            "Common_Feature_Count":
                intersection,

            "Jaccard_Agreement":
                jaccard_agreement

        })


# =============================================================================
# CONVERT TO DATAFRAME
# =============================================================================

agreement_df = pd.DataFrame(
    agreement_results
)


# =============================================================================
# DISPLAY
# =============================================================================

display(
    agreement_df
)

,Top_K,Run,Boruta_Features,DODA_Features,Common_Features,Common_Feature_Count,Jaccard_Agreement
0,5,1,"[Age, BMI, GenHlth, HighBP, Income]","[Age, BMI, GenHlth, HighBP, HighChol]","[Age, BMI, GenHlth, HighBP]",4,0.666667
1,5,2,"[Age, BMI, GenHlth, HighBP, Income]","[Age, BMI, GenHlth, HighBP, HighChol]","[Age, BMI, GenHlth, HighBP]",4,0.666667
2,5,3,"[Age, BMI, GenHlth, HighBP, Income]","[Age, BMI, GenHlth, HighBP, HighChol]","[Age, BMI, GenHlth, HighBP]",4,0.666667
3,5,4,"[Age, BMI, GenHlth, HighBP, Income]","[Age, BMI, GenHlth, HighBP, HighChol]","[Age, BMI, GenHlth, HighBP]",4,0.666667
4,5,5,"[Age, BMI, GenHlth, HighBP, Income]","[Age, BMI, GenHlth, HighBP, HighChol]","[Age, BMI, GenHlth, HighBP]",4,0.666667
...,...,...,...,...,...,...,...
95,20,21,"[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...",20,1.000000
96,20,22,"[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...",20,1.000000
97,20,23,"[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...",20,1.000000
98,20,24,"[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...",20,1.000000
99,20,25,"[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...","[Age, BMI, CholCheck, DiffWalk, Education, Fru...",20,1.000000

In [33]:
# =============================================================================
# AGREEMENT SUMMARY
# =============================================================================

agreement_summary = (
    agreement_df
    .groupby("Top_K")["Jaccard_Agreement"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)

display(agreement_summary)

   Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0      5      0.666667          0.0     0.666667     0.666667
1     10      0.818182          0.0     0.818182     0.818182
2     15      0.875000          0.0     0.875000     0.875000
3     20      1.000000          0.0     1.000000     1.000000