In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# LASSO (L1-regularized Logistic Regression)

## 2. Baseline

In [10]:
# =============================================================================
# LASSO BASELINE FEATURE SELECTION (TOP-K = 5,10,15,20)
# =============================================================================

from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np


# Fit LASSO once with all features
# Logistic Regression with L1 penalty = LASSO-style feature selection

lasso_selector = LogisticRegression(
    penalty="l1",
    solver="liblinear",
    C=0.1,
    max_iter=2000,
    class_weight="balanced",
    random_state=42
)


lasso_selector.fit(
    X_train_scaled,
    y_train
)


# =============================================================================
# Extract LASSO coefficients
# =============================================================================

lasso_coefficients = lasso_selector.coef_[0]


# Use absolute coefficient magnitude as feature importance
lasso_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "LASSO Coefficient": lasso_coefficients,

    "LASSO Score": np.abs(lasso_coefficients)

})


# Sort by absolute coefficient magnitude
lasso_scores = lasso_scores.sort_values(
    by="LASSO Score",
    ascending=False
).reset_index(drop=True)


# =============================================================================
# Top-K values
# =============================================================================

k_values = [5, 10, 15, 20]

lasso_results = {}


for k in k_values:

    top_features = (
        lasso_scores
        .head(k)["Feature"]
        .tolist()
    )


    # Boolean mask for selecting columns
    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    lasso_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": lasso_scores.head(k)

    }


    print("=" * 70)
    print(f"TOP {k} LASSO FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nScores:")
    print(lasso_scores.head(k))

======================================================================
TOP 5 LASSO FEATURES
======================================================================
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol']

Scores:
    Feature  LASSO Coefficient  LASSO Score
0   GenHlth           0.571338     0.571338
1       BMI           0.468812     0.468812
2       Age           0.442791     0.442791
3    HighBP           0.356107     0.356107
4  HighChol           0.280930     0.280930
======================================================================
TOP 10 LASSO FEATURES
======================================================================
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack']

Scores:
                Feature  LASSO Coefficient  LASSO Score
0               GenHlth           0.571338     0.571338
1                   BMI           0.468812     0.468812
2                   Age           0.442791     0.442791
3                HighBP           0.356107     0.356107
4              HighChol           0.280930     0.280930
5             CholCheck           0.259868     0.259868
6     HvyAlcoholConsump          -0.188147     0.188147
7                   Sex           0.142205     0.142205
8                Income          -0.097900     0.097900
9  HeartDiseaseorAttack           0.070965     0.070965
======================================================================
TOP 15 LASSO FEATURES
======================================================================
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education']

Scores:
                 Feature  LASSO Coefficient  LASSO Score
0                GenHlth           0.571338     0.571338
1                    BMI           0.468812     0.468812
2                    Age           0.442791     0.442791
3                 HighBP           0.356107     0.356107
4               HighChol           0.280930     0.280930
5              CholCheck           0.259868     0.259868
6      HvyAlcoholConsump          -0.188147     0.188147
7                    Sex           0.142205     0.142205
8                 Income          -0.097900     0.097900
9   HeartDiseaseorAttack           0.070965     0.070965
10              PhysHlth          -0.057410     0.057410
11              DiffWalk           0.043891     0.043891
12              MentHlth          -0.040751     0.040751
13                Stroke           0.032361     0.032361
14             Education          -0.023610     0.023610
======================================================================
TOP 20 LASSO FEATURES
======================================================================
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education', 'AnyHealthcare', 'Fruits', 'Smoker', 'PhysActivity', 'Veggies']

Scores:
                 Feature  LASSO Coefficient  LASSO Score
0                GenHlth           0.571338     0.571338
1                    BMI           0.468812     0.468812
2                    Age           0.442791     0.442791
3                 HighBP           0.356107     0.356107
4               HighChol           0.280930     0.280930
5              CholCheck           0.259868     0.259868
6      HvyAlcoholConsump          -0.188147     0.188147
7                    Sex           0.142205     0.142205
8                 Income          -0.097900     0.097900
9   HeartDiseaseorAttack           0.070965     0.070965
10              PhysHlth          -0.057410     0.057410
11              DiffWalk           0.043891     0.043891
12              MentHlth          -0.040751     0.040751
13                Stroke           0.032361     0.032361
14             Education          -0.023610     0.023610
15         AnyHealthcare           0.020317     0.020317
16                Fruits          -0.011624     0.011624
17                Smoker          -0.009270     0.009270
18          PhysActivity          -0.005727     0.005727
19               Veggies          -0.003524     0.003524

In [11]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [12]:
# =============================================================================
# MODEL EVALUATION — LASSO
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results_lasso = []


for k in k_values:

    Xtr = lasso_results[k]["X_train"]

    Xts = lasso_results[k]["X_test"]

    features = ", ".join(
        lasso_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        results_lasso.append({

            "Method": "LASSO",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred
            ),

            "Recall": recall_score(
                y_test,
                y_pred
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


lasso_evaluation = pd.DataFrame(
    results_lasso
)

display(lasso_evaluation)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,LASSO,5,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol",0.707855,0.312342,0.757515,0.442309,0.803644
1,LASSO,5,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol",0.707419,0.304925,0.713634,0.427280,0.778408
2,LASSO,5,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol",0.696546,0.305737,0.774469,0.438405,0.806462
3,LASSO,10,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.713520,0.317904,0.762217,0.448675,0.809988
4,LASSO,10,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.773287,0.319740,0.427839,0.365974,0.719348
5,LASSO,10,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.703650,0.312628,0.782305,0.446731,0.812640
6,LASSO,15,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714283,0.318241,0.760080,0.448640,0.810505
7,LASSO,15,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.826038,0.377879,0.212708,0.272197,0.759698
8,LASSO,15,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.710382,0.316547,0.771050,0.448831,0.811581
9,LASSO,20,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714304,0.318260,0.760080,0.448659,0.810583
10,LASSO,20,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.842423,0.454194,0.150449,0.226027,0.776861
11,LASSO,20,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.712997,0.319040,0.772760,0.451624,0.811829

In [13]:
lasso_evaluation.to_csv(
    "../../../results/diabetes/baseline/lasso_baseline_results.csv",
    index=False
)

## 2. DODA

In [14]:
%pip uninstall -y doda

Found existing installation: doda 0.1.0
Uninstalling doda-0.1.0:
  Successfully uninstalled doda-0.1.0
Note: you may need to restart the kernel to use updated packages.

In [15]:
%pip install git+https://github.com/anandha-3679/DODA.git

Collecting git+https://github.com/anandha-3679/DODA.git
  Cloning https://github.com/anandha-3679/DODA.git to c:\users\anandha lakshmi\appdata\local\temp\pip-req-build-wdmy_ulp
  Resolved https://github.com/anandha-3679/DODA.git to commit ff8eb84b57e3c9c01f5028f902c0fd76be092333
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: doda
  Building wheel for doda (pyproject.toml): started
  Building wheel for doda (pyproject.toml): finished with status 'done'
  Created wheel for doda: filename=doda-0.1.0-py3-none-any.whl size=13504 sha256=ff47a080d7dc23c854ea26459f9c534a24b4868b7737d6014b6e152781af15e1
  Stored in directory: C:\Users\Anandha Lakshmi\AppData\Local\Temp\pip-ephem-wheel-cache-8q1l_6fl\wheels\42\6a\22\a51a03690cc18d3493705062872e3519eede94dc00682c19bc
Successfully built doda
Installing collected packages: doda
Successfully installed doda-0.1.0
Note: you may need to restart the kernel to use updated packages.

  Running command git clone --filter=blob:none --quiet https://github.com/anandha-3679/DODA.git 'C:\Users\Anandha Lakshmi\AppData\Local\Temp\pip-req-build-wdmy_ulp'

In [16]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--upgrade",
    "--force-reinstall",
    "--no-cache-dir",
    "git+https://github.com/anandha-3679/DODA.git"
])

0

In [20]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [21]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [22]:
# =============================================================================
# LASSO + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.linear_model import LogisticRegression


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

doda_results = {}


# =============================================================================
# RUN LASSO + DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"LASSO + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # LASSO operator
    # ---------------------------------------------------------------------

    lasso = SklearnAdapter(

        LogisticRegression(
            penalty="l1",
            solver="liblinear",
            C=0.1,
            max_iter=2000,
            class_weight="balanced",
            random_state=42
        )

    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(

        operators=[lasso],

        provider=provider,

        fusion=fusion,

        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(

        X_train_scaled,

        y_train

    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(

        X_test_scaled

    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = (
        selector.get_selected_features()
    )


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores":
            selector.raw_math_scores_,

        "math_scores":
            selector.math_scores_,

        "clinical_weights":
            selector.clinical_weights_,

        "final_scores":
            selector.final_scores_
    }


print("\n" + "=" * 70)
print("LASSO + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
LASSO + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001E313D43CB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of coefficients: 21
Operator Scores:
{'LogisticRegression_1': {'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.49170552930633166), 'CholCheck': np.float64(0.45484151873536205), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.01622500921440345), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.010023802381810953), 'Fruits': np.float64(0.020344452905173033), 'Veggies': np.float64(0.006167821079381689), 'HvyAlcoholConsump': np.float64(0.3293098197819434), 'AnyHealthcare': np.float64(0.03556050929587827), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07132573078426926), 'PhysHlth': np.float64(0.10048300417444983), 'DiffWalk': np.float64(0.07682122600913582), 'Sex': np.float64(0.24889907700551056), 'Age': np.float64(0.7750073929901105), 'Education': np.float64(0.04132418300575992), 'Income': np.float64(0.17135303204314128)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.4425349763756985), 'CholCheck': np.float64(0.18193660749414484), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.009735005528642069), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.004009520952724381), 'Fruits': np.float64(0.004068890581034607), 'Veggies': np.float64(0.001233564215876338), 'HvyAlcoholConsump': np.float64(0.06586196395638869), 'AnyHealthcare': np.float64(0.007112101859175654), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03566286539213463), 'PhysHlth': np.float64(0.08038640333955988), 'DiffWalk': np.float64(0.06913910340822224), 'Sex': np.float64(0.049779815401102115), 'Age': np.float64(0.6975066536910994), 'Education': np.float64(0.012397254901727975), 'Income': np.float64(0.051405909612942384)}
Top 5 Features Selected: ['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol']

Selected Features:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol']

======================================================================
LASSO + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001E313D43CB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of coefficients: 21
Operator Scores:
{'LogisticRegression_1': {'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.49170552930633166), 'CholCheck': np.float64(0.45484151873536205), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.01622500921440345), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.010023802381810953), 'Fruits': np.float64(0.020344452905173033), 'Veggies': np.float64(0.006167821079381689), 'HvyAlcoholConsump': np.float64(0.3293098197819434), 'AnyHealthcare': np.float64(0.03556050929587827), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07132573078426926), 'PhysHlth': np.float64(0.10048300417444983), 'DiffWalk': np.float64(0.07682122600913582), 'Sex': np.float64(0.24889907700551056), 'Age': np.float64(0.7750073929901105), 'Education': np.float64(0.04132418300575992), 'Income': np.float64(0.17135303204314128)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.4425349763756985), 'CholCheck': np.float64(0.18193660749414484), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.009735005528642069), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.004009520952724381), 'Fruits': np.float64(0.004068890581034607), 'Veggies': np.float64(0.001233564215876338), 'HvyAlcoholConsump': np.float64(0.06586196395638869), 'AnyHealthcare': np.float64(0.007112101859175654), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03566286539213463), 'PhysHlth': np.float64(0.08038640333955988), 'DiffWalk': np.float64(0.06913910340822224), 'Sex': np.float64(0.049779815401102115), 'Age': np.float64(0.6975066536910994), 'Education': np.float64(0.012397254901727975), 'Income': np.float64(0.051405909612942384)}
Top 10 Features Selected: ['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump']

Selected Features:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump']

======================================================================
LASSO + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001E313D43CB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of coefficients: 21
Operator Scores:
{'LogisticRegression_1': {'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.49170552930633166), 'CholCheck': np.float64(0.45484151873536205), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.01622500921440345), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.010023802381810953), 'Fruits': np.float64(0.020344452905173033), 'Veggies': np.float64(0.006167821079381689), 'HvyAlcoholConsump': np.float64(0.3293098197819434), 'AnyHealthcare': np.float64(0.03556050929587827), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07132573078426926), 'PhysHlth': np.float64(0.10048300417444983), 'DiffWalk': np.float64(0.07682122600913582), 'Sex': np.float64(0.24889907700551056), 'Age': np.float64(0.7750073929901105), 'Education': np.float64(0.04132418300575992), 'Income': np.float64(0.17135303204314128)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.4425349763756985), 'CholCheck': np.float64(0.18193660749414484), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.009735005528642069), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.004009520952724381), 'Fruits': np.float64(0.004068890581034607), 'Veggies': np.float64(0.001233564215876338), 'HvyAlcoholConsump': np.float64(0.06586196395638869), 'AnyHealthcare': np.float64(0.007112101859175654), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03566286539213463), 'PhysHlth': np.float64(0.08038640333955988), 'DiffWalk': np.float64(0.06913910340822224), 'Sex': np.float64(0.049779815401102115), 'Age': np.float64(0.6975066536910994), 'Education': np.float64(0.012397254901727975), 'Income': np.float64(0.051405909612942384)}
Top 15 Features Selected: ['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education']

Selected Features:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education']

======================================================================
LASSO + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001E313D43CB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of coefficients: 21
Operator Scores:
{'LogisticRegression_1': {'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(0.35610703120782017), 'HighChol': np.float64(0.2809300218171465), 'CholCheck': np.float64(0.2598682141360738), 'BMI': np.float64(0.4688119526536865), 'Smoker': np.float64(0.009269963262394149), 'Stroke': np.float64(0.032361323849658556), 'HeartDiseaseorAttack': np.float64(0.07096469729569904), 'PhysActivity': np.float64(0.005726978555204656), 'Fruits': np.float64(0.011623557714657111), 'Veggies': np.float64(0.0035239101598865054), 'HvyAlcoholConsump': np.float64(0.1881471924597913), 'AnyHealthcare': np.float64(0.02031706795409283), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(0.5713379351529065), 'MentHlth': np.float64(0.0407510957495565), 'PhysHlth': np.float64(0.057409752122991056), 'DiffWalk': np.float64(0.04389088064397442), 'Sex': np.float64(0.14220548471779268), 'Age': np.float64(0.44279112363920686), 'Education': np.float64(0.023610073390391704), 'Income': np.float64(0.09790048750971816)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.623286166203047), 'HighChol': np.float64(0.49170552930633166), 'CholCheck': np.float64(0.45484151873536205), 'BMI': np.float64(0.8205510676062826), 'Smoker': np.float64(0.01622500921440345), 'Stroke': np.float64(0.05664130081087252), 'HeartDiseaseorAttack': np.float64(0.12420792131841699), 'PhysActivity': np.float64(0.010023802381810953), 'Fruits': np.float64(0.020344452905173033), 'Veggies': np.float64(0.006167821079381689), 'HvyAlcoholConsump': np.float64(0.3293098197819434), 'AnyHealthcare': np.float64(0.03556050929587827), 'NoDocbcCost': np.float64(0.0), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.07132573078426926), 'PhysHlth': np.float64(0.10048300417444983), 'DiffWalk': np.float64(0.07682122600913582), 'Sex': np.float64(0.24889907700551056), 'Age': np.float64(0.7750073929901105), 'Education': np.float64(0.04132418300575992), 'Income': np.float64(0.17135303204314128)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores

In [23]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
13               GenHlth        0.571338               1.000000
3                    BMI        0.468812               0.820551
18                   Age        0.442791               0.775007
0                 HighBP        0.356107               0.623286
1               HighChol        0.280930               0.491706
2              CholCheck        0.259868               0.454842
10     HvyAlcoholConsump        0.188147               0.329310
17                   Sex        0.142205               0.248899
20                Income        0.097900               0.171353
6   HeartDiseaseorAttack        0.070965               0.124208
15              PhysHlth        0.057410               0.100483
16              DiffWalk        0.043891               0.076821
14              MentHlth        0.040751               0.071326
5                 Stroke        0.032361               0.056641
19             Education        0.023610               0.041324
11         AnyHealthcare        0.020317               0.035561
8                 Fruits        0.011624               0.020344
4                 Smoker        0.009270               0.016225
7           PhysActivity        0.005727               0.010024
9                Veggies        0.003524               0.006168
12           NoDocbcCost        0.000000               0.000000

In [24]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                 HighBP              1.0
3                    BMI              1.0
13               GenHlth              1.0
6   HeartDiseaseorAttack              1.0
5                 Stroke              1.0
18                   Age              0.9
16              DiffWalk              0.9
1               HighChol              0.9
15              PhysHlth              0.8
4                 Smoker              0.6
14              MentHlth              0.5
2              CholCheck              0.4
7           PhysActivity              0.4
20                Income              0.3
19             Education              0.3
12           NoDocbcCost              0.2
9                Veggies              0.2
8                 Fruits              0.2
11         AnyHealthcare              0.2
10     HvyAlcoholConsump              0.2
17                   Sex              0.2

In [25]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
13               GenHlth          1.000000
3                    BMI          0.820551
18                   Age          0.697507
0                 HighBP          0.623286
1               HighChol          0.442535
2              CholCheck          0.181937
6   HeartDiseaseorAttack          0.124208
15              PhysHlth          0.080386
16              DiffWalk          0.069139
10     HvyAlcoholConsump          0.065862
5                 Stroke          0.056641
20                Income          0.051406
17                   Sex          0.049780
14              MentHlth          0.035663
19             Education          0.012397
4                 Smoker          0.009735
11         AnyHealthcare          0.007112
8                 Fruits          0.004069
7           PhysActivity          0.004010
9                Veggies          0.001234
12           NoDocbcCost          0.000000

In [26]:
selector.get_selected_features()

['GenHlth',
 'BMI',
 'Age',
 'HighBP',
 'HighChol',
 'CholCheck',
 'HeartDiseaseorAttack',
 'PhysHlth',
 'DiffWalk',
 'HvyAlcoholConsump']

In [27]:
comparison = selector.compare_scores()

comparison

,Feature,Math Rank,Normalized Math Score,Clinical Weight,DODA Rank,Final Score,Rank Change
0,GenHlth,1,1.0000,1.0,1,1.0000,0
1,BMI,2,0.8206,1.0,2,0.8206,0
2,Age,3,0.7750,0.9,3,0.6975,0
3,HighBP,4,0.6233,1.0,4,0.6233,0
4,HighChol,5,0.4917,0.9,5,0.4425,0
5,CholCheck,6,0.4548,0.4,6,0.1819,0
6,HeartDiseaseorAttack,10,0.1242,1.0,7,0.1242,3
7,PhysHlth,11,0.1005,0.8,8,0.0804,3
8,DiffWalk,12,0.0768,0.9,9,0.0691,3
9,HvyAlcoholConsump,7,0.3293,0.2,10,0.0659,-3
10,Stroke,14,0.0566,1.0,11,0.0566,3
11,Income,9,0.1714,0.3,12,0.0514,-3
12,Sex,8,0.2489,0.2,13,0.0498,-5
13,MentHlth,13,0.0713,0.5,14,0.0357,-1
14,Education,15,0.0413,0.3,15,0.0124,0
15,Smoker,18,0.0162,0.6,16,0.0097,2
16,AnyHealthcare,16,0.0356,0.2,17,0.0071,-1
17,Fruits,17,0.0203,0.2,18,0.0041,-1
18,PhysActivity,19,0.0100,0.4,19,0.0040,0
19,Veggies,20,0.0062,0.2,20,0.0012,0
20,NoDocbcCost,21,0.0000,0.2,21,0.0000,0

In [28]:
# =============================================================================
# LASSO + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


# -------------------------------------------------------------------------
# Store results
# -------------------------------------------------------------------------

lasso_doda_model_results = []


# -------------------------------------------------------------------------
# Evaluate for each Top-K
# -------------------------------------------------------------------------

for k in k_values:

    Xtr = doda_results[k]["X_train"]

    Xts = doda_results[k]["X_test"]

    features = ", ".join(
        doda_results[k]["features"]
    )


    # ---------------------------------------------------------------------
    # Evaluate each model
    # ---------------------------------------------------------------------

    for model_name, model in models.items():

        # Train model
        model.fit(
            Xtr,
            y_train
        )


        # Predictions
        y_pred = model.predict(
            Xts
        )


        # Probability predictions
        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        # ---------------------------------------------------------------
        # Store evaluation metrics
        # ---------------------------------------------------------------

        lasso_doda_model_results.append({

            "Method": "LASSO + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


# -------------------------------------------------------------------------
# Convert results to DataFrame
# -------------------------------------------------------------------------

lasso_doda_results_df = pd.DataFrame(
    lasso_doda_model_results
)


# -------------------------------------------------------------------------
# Display results
# -------------------------------------------------------------------------

display(
    lasso_doda_results_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,LASSO + DODA,5,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol",0.707855,0.312342,0.757515,0.442309,0.803644
1,LASSO + DODA,5,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol",0.707463,0.304986,0.713777,0.427365,0.778447
2,LASSO + DODA,5,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol",0.696546,0.305737,0.774469,0.438405,0.806462
3,LASSO + DODA,10,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.713803,0.317585,0.758513,0.447715,0.808388
4,LASSO + DODA,10,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.765508,0.318636,0.468443,0.379283,0.723653
5,LASSO + DODA,10,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.707833,0.315297,0.777034,0.448575,0.810865
6,LASSO + DODA,15,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714283,0.318241,0.760080,0.448640,0.810505
7,LASSO + DODA,15,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.826212,0.377213,0.209432,0.269329,0.757992
8,LASSO + DODA,15,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.710382,0.316547,0.771050,0.448831,0.811573
9,LASSO + DODA,20,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714304,0.318260,0.760080,0.448659,0.810583
10,LASSO + DODA,20,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.842488,0.455051,0.151446,0.227258,0.775875
11,LASSO + DODA,20,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.712997,0.319040,0.772760,0.451624,0.811831

In [29]:
lasso_doda_results_df.to_csv(
    "../../../results/diabetes/baseline/lasso_doda_results.csv",
    index=False
)

In [35]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        lasso_evaluation,
        lasso_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,LASSO,5,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol",0.707855,0.312342,0.757515,0.442309,0.803644
1,LASSO,5,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol",0.707419,0.304925,0.713634,0.427280,0.778408
2,LASSO,5,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol",0.696546,0.305737,0.774469,0.438405,0.806462
3,LASSO,10,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.713520,0.317904,0.762217,0.448675,0.809988
4,LASSO,10,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.773287,0.319740,0.427839,0.365974,0.719348
5,LASSO,10,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.703650,0.312628,0.782305,0.446731,0.812640
6,LASSO,15,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714283,0.318241,0.760080,0.448640,0.810505
7,LASSO,15,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.826038,0.377879,0.212708,0.272197,0.759698
8,LASSO,15,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.710382,0.316547,0.771050,0.448831,0.811581
9,LASSO,20,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714304,0.318260,0.760080,0.448659,0.810583
10,LASSO,20,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.842423,0.454194,0.150449,0.226027,0.776861
11,LASSO,20,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.712997,0.319040,0.772760,0.451624,0.811829
12,LASSO + DODA,5,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol",0.707855,0.312342,0.757515,0.442309,0.803644
13,LASSO + DODA,5,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol",0.707463,0.304986,0.713777,0.427365,0.778447
14,LASSO + DODA,5,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol",0.696546,0.305737,0.774469,0.438405,0.806462
15,LASSO + DODA,10,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.713803,0.317585,0.758513,0.447715,0.808388
16,LASSO + DODA,10,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.765508,0.318636,0.468443,0.379283,0.723653
17,LASSO + DODA,10,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.707833,0.315297,0.777034,0.448575,0.810865
18,LASSO + DODA,15,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714283,0.318241,0.760080,0.448640,0.810505
19,LASSO + DODA,15,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.826212,0.377213,0.209432,0.269329,0.757992
20,LASSO + DODA,15,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.710382,0.316547,0.771050,0.448831,0.811573
21,LASSO + DODA,20,Logistic Regression,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.714304,0.318260,0.760080,0.448659,0.810583
22,LASSO + DODA,20,Random Forest,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.842488,0.455051,0.151446,0.227258,0.775875
23,LASSO + DODA,20,XGBoost,"GenHlth, BMI, Age, HighBP, HighChol, CholCheck...",0.712997,0.319040,0.772760,0.451624,0.811831

In [36]:
for k in k_values:

    selector = doda_results[k]["selector"]

    raw_rank = [
        x[0]
        for x in sorted(
            selector.raw_math_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    doda_rank = [
        x[0]
        for x in sorted(
            selector.final_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    print("\n" + "=" * 70)
    print(f"TOP {k}")
    print("=" * 70)

    print("Raw Math Ranking:")
    print(raw_rank)

    print("\nDODA Ranking:")
    print(doda_rank)

    print("\nTop-K Same:",
          raw_rank[:k] == doda_rank[:k])

======================================================================
TOP 5
======================================================================
Raw Math Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education', 'AnyHealthcare', 'Fruits', 'Smoker', 'PhysActivity', 'Veggies', 'NoDocbcCost']

DODA Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education', 'Smoker', 'AnyHealthcare', 'Fruits', 'PhysActivity', 'Veggies', 'NoDocbcCost']

Top-K Same: True

======================================================================
TOP 10
======================================================================
Raw Math Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education', 'AnyHealthcare', 'Fruits', 'Smoker', 'PhysActivity', 'Veggies', 'NoDocbcCost']

DODA Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education', 'Smoker', 'AnyHealthcare', 'Fruits', 'PhysActivity', 'Veggies', 'NoDocbcCost']

Top-K Same: False

======================================================================
TOP 15
======================================================================
Raw Math Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education', 'AnyHealthcare', 'Fruits', 'Smoker', 'PhysActivity', 'Veggies', 'NoDocbcCost']

DODA Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education', 'Smoker', 'AnyHealthcare', 'Fruits', 'PhysActivity', 'Veggies', 'NoDocbcCost']

Top-K Same: False

======================================================================
TOP 20
======================================================================
Raw Math Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HvyAlcoholConsump', 'Sex', 'Income', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'MentHlth', 'Stroke', 'Education', 'AnyHealthcare', 'Fruits', 'Smoker', 'PhysActivity', 'Veggies', 'NoDocbcCost']

DODA Ranking:
['GenHlth', 'BMI', 'Age', 'HighBP', 'HighChol', 'CholCheck', 'HeartDiseaseorAttack', 'PhysHlth', 'DiffWalk', 'HvyAlcoholConsump', 'Stroke', 'Income', 'Sex', 'MentHlth', 'Education', 'Smoker', 'AnyHealthcare', 'Fruits', 'PhysActivity', 'Veggies', 'NoDocbcCost']

Top-K Same: False

# Interpretation of LASSO + DODA Feature Ranking

## Overview

The LASSO feature-selection experiment was performed using two ranking approaches:

1. **Raw Mathematical Ranking** — features ranked according to the absolute LASSO coefficients.
2. **DODA Ranking** — LASSO-based mathematical importance was combined with clinically assigned feature weights.

The purpose of this experiment was to determine whether incorporating clinical knowledge through DODA changes the feature prioritization produced by LASSO.

---

## 1. Top-5 Features

For Top-5, the feature sets selected by both approaches were identical:

**LASSO:**

- GenHlth
- BMI
- Age
- HighBP
- HighChol

**LASSO + DODA:**

- GenHlth
- BMI
- Age
- HighBP
- HighChol

Therefore:

> **Top-5 Same = True**

This indicates that the five strongest statistically important features were also strongly supported by the clinical weighting scheme. Consequently, DODA did not alter the Top-5 feature selection.

---

## 2. Top-10 Features

At Top-10, DODA produced a different feature ranking.

### Raw LASSO Ranking

The raw LASSO ranking placed:

- HvyAlcoholConsump at rank 7
- Sex at rank 8
- Income at rank 9
- HeartDiseaseorAttack at rank 10

### DODA Ranking

After incorporating clinical weights:

- HeartDiseaseorAttack moved from rank 10 → rank 7
- PhysHlth moved from rank 11 → rank 8
- DiffWalk moved from rank 12 → rank 9
- HvyAlcoholConsump moved from rank 7 → rank 10

Therefore:

> **Top-10 Same = False**

This demonstrates that DODA modifies the prioritization of features that have similar or moderate statistical importance by incorporating clinical relevance.

---

## 3. Top-15 Features

The Top-15 feature sets also differed between the raw LASSO and DODA rankings.

The major ranking changes included:

- HeartDiseaseorAttack: **10 → 7**
- PhysHlth: **11 → 8**
- DiffWalk: **12 → 9**
- Stroke: **14 → 11**
- HvyAlcoholConsump: **7 → 10**
- Sex: **8 → 13**
- Income: **9 → 12**

Thus:

> **Top-15 Same = False**

The effect of clinical knowledge becomes more apparent as the number of selected features increases.

---

## 4. Top-20 Features

At Top-20, the ranking was again different between LASSO and LASSO + DODA.

However, most features remained within the Top-20. The primary effect of DODA was therefore **reordering rather than completely replacing features**.

This indicates that DODA preserves the majority of statistically relevant features while changing their relative priority according to clinical knowledge.

Therefore:

> **Top-20 Same = False**

---

## 5. Overall Pattern

The experiment demonstrates an important pattern:

| Top-K | Same Feature Set? | Effect of DODA |
|------:|:-----------------:|----------------|
| 5 | Yes | No change in selected features |
| 10 | No | Clinical re-ranking begins |
| 15 | No | Greater ranking modification |
| 20 | No | Ranking remains clinically adjusted |

The strongest statistically important features, particularly **GenHlth, BMI, Age, HighBP, and HighChol**, remained consistently ranked at the top.

However, DODA changed the ordering of several lower-ranked features, particularly features such as **HeartDiseaseorAttack, PhysHlth, DiffWalk, and Stroke**.

---

## 6. Interpretation of the DODA Effect

The results suggest that DODA does not simply replace statistically selected features with clinically selected features.

Instead, it acts primarily as a **clinical re-ranking mechanism**.

The process can be summarized as:

**LASSO statistical importance**
→ **Normalization**
→ **Clinical weighting**
→ **DODA final ranking**

Therefore, features with strong statistical importance and high clinical relevance retain high rankings, while features with lower clinical relevance may be moved downward.

For example, **HeartDiseaseorAttack** moved from rank 10 under raw LASSO to rank 7 under DODA, whereas **HvyAlcoholConsump** moved from rank 7 to rank 10.

---

## 7. Relationship With Model Evaluation

The feature-ranking results also explain the model evaluation results.

For Top-5, LASSO and LASSO + DODA selected exactly the same five features. Therefore, their downstream model performance was essentially identical.

For Top-10, Top-15, and Top-20, DODA changed the feature ranking and, in some cases, the selected feature set. However, the predictive performance remained broadly comparable to standard LASSO.

This suggests that the features introduced or prioritized by DODA contain predictive information comparable to the features selected by purely statistical ranking.

---

## 8. Key Research Finding

The most important finding from this experiment is:

> **DODA successfully incorporates clinical knowledge into LASSO-based feature prioritization while preserving the strongest statistically supported features and maintaining broadly comparable predictive performance.**

The results therefore suggest that the primary contribution of DODA may not necessarily be an increase in predictive accuracy, but rather the generation of a **clinically informed feature ranking without substantial loss of predictive capability**.

---

## 9. Research Implication

These results provide preliminary evidence supporting the proposed DODA framework.

However, this experiment alone is not sufficient to establish the overall effectiveness of DODA. Further experiments should compare:

- ANOVA vs. ANOVA + DODA
- LASSO vs. LASSO + DODA
- MRMR vs. MRMR + DODA
- Random Forest importance vs. Random Forest + DODA

Additionally, **feature-selection stability** should be evaluated using measures such as Jaccard similarity across cross-validation folds.

This will help determine whether DODA consistently produces clinically meaningful and stable feature rankings across different datasets and feature-selection methods.

---

## Conclusion

The LASSO experiment demonstrates that DODA has a measurable effect on feature prioritization.

The Top-5 features remained unchanged, indicating that DODA preserves the strongest statistical signals. From Top-10 onward, DODA re-ranked several features based on clinical relevance, particularly prioritizing features such as **HeartDiseaseorAttack, PhysHlth, DiffWalk, and Stroke**.

Although these ranking changes did not produce substantial improvements in predictive performance, they demonstrate that DODA can introduce **clinical knowledge into a statistically driven feature-selection process while maintaining comparable predictive performance**.

Therefore, the current experiment supports the role of DODA as a **clinically informed feature-ranking framework rather than simply an accuracy-improvement technique**.