In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [6]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [7]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [9]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [10]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [11]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# ANNOVA

## 1. Baseline

In [12]:
# =============================================================================
# ANOVA BASELINE FEATURE SELECTION (TOP-K = 5,10,15,20)
# =============================================================================

from sklearn.feature_selection import SelectKBest, f_classif
import pandas as pd


# Fit ANOVA once with all features
anova_selector = SelectKBest(
    score_func=f_classif,

    k="all"
)

anova_selector.fit(
    X_train_scaled,
    y_train
)


# Create score dataframe
anova_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "ANOVA Score": anova_selector.scores_

})


# Sort by ANOVA importance
anova_scores = anova_scores.sort_values(
    by="ANOVA Score",
    ascending=False
).reset_index(drop=True)



# Top-k values
k_values = [5, 10, 15, 20]

anova_results = {}


for k in k_values:

    top_features = (
        anova_scores
        .head(k)["Feature"]
        .tolist()
    )


    # Boolean mask for selecting columns
    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    anova_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": anova_scores.head(k)

    }


    print("="*70)
    print(f"TOP {k} ANOVA FEATURES")
    print("="*70)

    print(top_features)

    print("\nScores:")
    print(anova_scores.head(k))

======================================================================
TOP 5 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

Scores:
    Feature   ANOVA Score
0   GenHlth  15028.459921
1    HighBP  12696.639767
2       BMI   8028.929585
3  DiffWalk   7990.290227
4  HighChol   7172.991333
======================================================================
TOP 10 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education']

Scores:
                Feature   ANOVA Score
0               GenHlth  15028.459921
1                HighBP  12696.639767
2                   BMI   8028.929585
3              DiffWalk   7990.290227
4              HighChol   7172.991333
5                   Age   5995.341829
6  HeartDiseaseorAttack   5368.293621
7              PhysHlth   4532.827198
8                Income   3621.117911
9             Education   1906.303916
======================================================================
TOP 15 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth']

Scores:
                 Feature   ANOVA Score
0                GenHlth  15028.459921
1                 HighBP  12696.639767
2                    BMI   8028.929585
3               DiffWalk   7990.290227
4               HighChol   7172.991333
5                    Age   5995.341829
6   HeartDiseaseorAttack   5368.293621
7               PhysHlth   4532.827198
8                 Income   3621.117911
9              Education   1906.303916
10          PhysActivity   1875.211102
11                Stroke   1781.432236
12             CholCheck    963.943424
13     HvyAlcoholConsump    804.709027
14              MentHlth    500.257213
======================================================================
TOP 20 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth', 'Smoker', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

Scores:
                 Feature   ANOVA Score
0                GenHlth  15028.459921
1                 HighBP  12696.639767
2                    BMI   8028.929585
3               DiffWalk   7990.290227
4               HighChol   7172.991333
5                    Age   5995.341829
6   HeartDiseaseorAttack   5368.293621
7               PhysHlth   4532.827198
8                 Income   3621.117911
9              Education   1906.303916
10          PhysActivity   1875.211102
11                Stroke   1781.432236
12             CholCheck    963.943424
13     HvyAlcoholConsump    804.709027
14              MentHlth    500.257213
15                Smoker    386.635201
16               Veggies    302.338736
17                   Sex    193.495629
18         AnyHealthcare    133.841125
19                Fruits    101.570460

In [13]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,

        eval_metric="logloss",
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()
    )
}

In [14]:
# =============================================================================
# MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for k in k_values:

    Xtr = anova_results[k]["X_train"]
    Xts = anova_results[k]["X_test"]

    features = ", ".join(anova_results[k]["features"])

    for model_name, model in models.items():

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xts)

        y_prob = model.predict_proba(Xts)[:,1]

        results.append({

            "Method": "ANOVA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(y_test, y_pred),

            "Precision": precision_score(y_test, y_pred),

            "Recall": recall_score(y_test, y_pred),

            "F1 Score": f1_score(y_test, y_pred),

            "ROC-AUC": roc_auc_score(y_test, y_prob)

        })

In [15]:
results_df = pd.DataFrame(results)

results_df

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305606,0.738567,0.432324,0.786946
2,ANOVA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.713934,0.317044,0.754238,0.446431,0.805833
4,ANOVA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.808912,0.337419,0.258869,0.292970,0.732218
5,ANOVA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710012,0.315326,0.765066,0.446588,0.807438
6,ANOVA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714653,0.317890,0.755663,0.447519,0.809178
7,ANOVA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.824818,0.368867,0.204588,0.263196,0.754941
8,ANOVA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710470,0.316835,0.772475,0.449362,0.810981
9,ANOVA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842423,0.454194,0.150449,0.226027,0.776861
11,ANOVA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811829

In [17]:
results_df.to_csv(
    "../../../results/diabetes/baseline/anova_baseline_results.csv",
    index=False
)

## 2. DODA

In [18]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [31]:
# =============================================================================
# DODA FEATURE SELECTION - ANOVA + CLINICAL KNOWLEDGE
# =============================================================================

doda_results = {}

k_values = [5, 10, 15, 20]

provider = JSONProvider(
    "clinical_weights.json"
)

fusion = HadamardFusion()


for k in k_values:

    print("=" * 70)
    print(f"DODA FEATURE SELECTION - TOP {k}")
    print("=" * 70)

    # -------------------------------------------------------------------------
    # ANOVA selector
    # -------------------------------------------------------------------------

    anova = SklearnAdapter(
        SelectKBest(
            score_func=f_classif,
            k=k
        )
    )

    # -------------------------------------------------------------------------
    # DODA selector
    # -------------------------------------------------------------------------

    selector = DODASelector(
        operators=[anova],
        provider=provider,
        fusion=fusion,
        top_k=k
    )

    # -------------------------------------------------------------------------
    # Fit on training data
    # -------------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )

    # -------------------------------------------------------------------------
    # Transform test data
    # -------------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )

    # -------------------------------------------------------------------------
    # Selected features
    # -------------------------------------------------------------------------

    selected_features = selector.get_selected_features()

    print("\nSelected Features:")
    print(selected_features)

    # -------------------------------------------------------------------------
    # Store results
    # -------------------------------------------------------------------------

    doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features
    }

======================================================================
DODA FEATURE SELECTION - TOP 5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001A6FBA73B10>
DODA Pipeline Started
Running: SelectKBest
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(6455.6922001002795), 'CholCheck': np.float64(385.5773696429477), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(231.98112073479865), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(750.0844408250998), 'Fruits': np.float64(20.314091949190185), 'Veggies': np.float64(60.46774713092755), 'HvyAlcoholConsump': np.float64(160.94180532873236), 'AnyHealthcare': np.float64(26.768224940586283), 'NoDocbcCost': np.float64(9.695797866823455), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(250.12860642342372), 'PhysHlth': np.float64(3626.261758128957), 'DiffWalk': np.float64(7191.261204570319), 'Sex': np.float64(38.699125716395415), 'Age': np.float64(5395.807646524666), 'Education': np.float64(571.8911747448066), 'Income': np.float64(1086.3353733086883)}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
======================================================================
DODA FEATURE SELECTION - TOP 10
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001A6FBA73B10>
DODA Pipeline Started
Running: SelectKBest
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(6455.6922001002795), 'CholCheck': np.float64(385.5773696429477), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(231.98112073479865), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(750.0844408250998), 'Fruits': np.float64(20.314091949190185), 'Veggies': np.float64(60.46774713092755), 'HvyAlcoholConsump': np.float64(160.94180532873236), 'AnyHealthcare': np.float64(26.768224940586283), 'NoDocbcCost': np.float64(9.695797866823455), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(250.12860642342372), 'PhysHlth': np.float64(3626.261758128957), 'DiffWalk': np.float64(7191.261204570319), 'Sex': np.float64(38.699125716395415), 'Age': np.float64(5395.807646524666), 'Education': np.float64(571.8911747448066), 'Income': np.float64(1086.3353733086883)}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income']
======================================================================
DODA FEATURE SELECTION - TOP 15
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001A6FBA73B10>
DODA Pipeline Started
Running: SelectKBest
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(6455.6922001002795), 'CholCheck': np.float64(385.5773696429477), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(231.98112073479865), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(750.0844408250998), 'Fruits': np.float64(20.314091949190185), 'Veggies': np.float64(60.46774713092755), 'HvyAlcoholConsump': np.float64(160.94180532873236), 'AnyHealthcare': np.float64(26.768224940586283), 'NoDocbcCost': np.float64(9.695797866823455), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(250.12860642342372), 'PhysHlth': np.float64(3626.261758128957), 'DiffWalk': np.float64(7191.261204570319), 'Sex': np.float64(38.699125716395415), 'Age': np.float64(5395.807646524666), 'Education': np.float64(571.8911747448066), 'Income': np.float64(1086.3353733086883)}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker']
======================================================================
DODA FEATURE SELECTION - TOP 20
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001A6FBA73B10>
DODA Pipeline Started
Running: SelectKBest
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(6455.6922001002795), 'CholCheck': np.float64(385.5773696429477), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(231.98112073479865), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(750.0844408250998), 'Fruits': np.float64(20.314091949190185), 'Veggies': np.float64(60.46774713092755), 'HvyAlcoholConsump': np.float64(160.94180532873236), 'AnyHealthcare': np.float64(26.768224940586283), 'NoDocbcCost': np.float64(9.695797866823455), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(250.12860642342372), 'PhysHlth': np.float64(3626.261758128957), 'DiffWalk': np.float64(7191.261204570319), 'Sex': np.float64(38.699125716395415), 'Age': np.float64(5395.807646524666), 'Education': np.float64(571.8911747448066), 'Income': np.float64(1086.3353733086883)}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker', 'HvyAlcoholConsump', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker', 'HvyAlcoholConsump', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

In [33]:
X_train_selected = selector.fit_transform(

    X_train_scaled,

    y_train

)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001A6FBA73B10>
DODA Pipeline Started
Running: SelectKBest
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(6455.6922001002795), 'CholCheck': np.float64(385.5773696429477), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(231.98112073479865), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(750.0844408250998), 'Fruits': np.float64(20.314091949190185), 'Veggies': np.float64(60.46774713092755), 'HvyAlcoholConsump': np.float64(160.94180532873236), 'AnyHealthcare': np.float64(26.768224940586283), 'NoDocbcCost': np.float64(9.695797866823455), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(250.12860642342372), 'PhysHlth': np.float64(3626.261758128957), 'DiffWalk': np.float64(7191.261204570319), 'Sex': np.float64(38.699125716395415), 'Age': np.float64(5395.807646524666), 'Education': np.float64(571.8911747448066), 'Income': np.float64(1086.3353733086883)}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker', 'HvyAlcoholConsump', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

In [32]:
X_test_selected = selector.transform(
    X_test_scaled
)

In [34]:
# =============================================================================
# INSPECT DODA SCORES
# =============================================================================

k = 10

selector = doda_results[k]["selector"]


math_scores = pd.DataFrame(
    selector.get_math_scores().items(),
    columns=[
        "Feature",
        "Math Score"
    ]
)

math_scores = math_scores.sort_values(
    by="Math Score",
    ascending=False
)


print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature    Math Score
13               GenHlth  15028.459921
0                 HighBP  12696.639767
3                    BMI   8028.929585
16              DiffWalk   7990.290227
1               HighChol   7172.991333
18                   Age   5995.341829
6   HeartDiseaseorAttack   5368.293621
15              PhysHlth   4532.827198
20                Income   3621.117911
19             Education   1906.303916
7           PhysActivity   1875.211102
5                 Stroke   1781.432236
2              CholCheck    963.943424
10     HvyAlcoholConsump    804.709027
14              MentHlth    500.257213
4                 Smoker    386.635201
9                Veggies    302.338736
17                   Sex    193.495629
11         AnyHealthcare    133.841125
8                 Fruits    101.570460
12           NoDocbcCost     48.478989

In [35]:
clinical_weights = pd.DataFrame(

    selector.get_clinical_weights().items(),

    columns=[

        "Feature",

        "Clinical Weight"

    ]

)

clinical_weights

                 Feature  Clinical Weight
0                 HighBP              1.0
1               HighChol              0.9
2              CholCheck              0.4
3                    BMI              1.0
4                 Smoker              0.6
5                 Stroke              1.0
6   HeartDiseaseorAttack              1.0
7           PhysActivity              0.4
8                 Fruits              0.2
9                Veggies              0.2
10     HvyAlcoholConsump              0.2
11         AnyHealthcare              0.2
12           NoDocbcCost              0.2
13               GenHlth              1.0
14              MentHlth              0.5
15              PhysHlth              0.8
16              DiffWalk              0.9
17                   Sex              0.2
18                   Age              0.9
19             Education              0.3
20                Income              0.3

In [36]:
final_scores = pd.DataFrame(
    selector.get_final_scores().items(),
    columns=[
        "Feature",
        "Final Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final Score",
    ascending=False
)


print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature   Final Score
13               GenHlth  15028.459921
0                 HighBP  12696.639767
3                    BMI   8028.929585
16              DiffWalk   7191.261205
1               HighChol   6455.692200
18                   Age   5395.807647
6   HeartDiseaseorAttack   5368.293621
15              PhysHlth   3626.261758
5                 Stroke   1781.432236
20                Income   1086.335373
7           PhysActivity    750.084441
19             Education    571.891175
2              CholCheck    385.577370
14              MentHlth    250.128606
4                 Smoker    231.981121
10     HvyAlcoholConsump    160.941805
9                Veggies     60.467747
17                   Sex     38.699126
11         AnyHealthcare     26.768225
8                 Fruits     20.314092
12           NoDocbcCost      9.695798

In [37]:
selector.get_selected_features()

['GenHlth',
 'HighBP',
 'BMI',
 'DiffWalk',
 'HighChol',
 'Age',
 'HeartDiseaseorAttack',
 'PhysHlth',
 'Stroke',
 'Income']

In [38]:
comparison = selector.compare_scores()

comparison

,Feature,Math Rank,Math Score,Clinical Weight,DODA Rank,Final Score,Rank Change
0,GenHlth,1,15028.4599,1.0,1,15028.4599,0
1,HighBP,2,12696.6398,1.0,2,12696.6398,0
2,BMI,3,8028.9296,1.0,3,8028.9296,0
3,DiffWalk,4,7990.2902,0.9,4,7191.2612,0
4,HighChol,5,7172.9913,0.9,5,6455.6922,0
5,Age,6,5995.3418,0.9,6,5395.8076,0
6,HeartDiseaseorAttack,7,5368.2936,1.0,7,5368.2936,0
7,PhysHlth,8,4532.8272,0.8,8,3626.2618,0
8,Stroke,12,1781.4322,1.0,9,1781.4322,3
9,Income,9,3621.1179,0.3,10,1086.3354,-1
10,PhysActivity,11,1875.2111,0.4,11,750.0844,0
11,Education,10,1906.3039,0.3,12,571.8912,-2
12,CholCheck,13,963.9434,0.4,13,385.5774,0
13,MentHlth,15,500.2572,0.5,14,250.1286,1
14,Smoker,16,386.6352,0.6,15,231.9811,1
15,HvyAlcoholConsump,14,804.7090,0.2,16,160.9418,-2
16,Veggies,17,302.3387,0.2,17,60.4677,0
17,Sex,18,193.4956,0.2,18,38.6991,0
18,AnyHealthcare,19,133.8411,0.2,19,26.7682,0
19,Fruits,20,101.5705,0.2,20,20.3141,0
20,NoDocbcCost,21,48.4790,0.2,21,9.6958,0

In [39]:
# =============================================================================
# DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


doda_model_results = []


for k in k_values:

    Xtr = doda_results[k]["X_train"]

    Xts = doda_results[k]["X_test"]

    features = ", ".join(
        doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        doda_model_results.append({

            "Method": "ANOVA + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


doda_results_df = pd.DataFrame(
    doda_model_results
)


display(doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA + DODA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305629,0.738709,0.432372,0.786912
2,ANOVA + DODA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714283,0.317720,0.756660,0.447525,0.805912
4,ANOVA + DODA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.793703,0.320533,0.311583,0.315995,0.718421
5,ANOVA + DODA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.708857,0.314543,0.766348,0.446020,0.807959
6,ANOVA + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712975,0.316255,0.754523,0.445697,0.807390
7,ANOVA + DODA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.829546,0.380995,0.183359,0.247571,0.758248
8,ANOVA + DODA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710753,0.316303,0.767346,0.447956,0.808930
9,ANOVA + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA + DODA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842706,0.456859,0.150876,0.226839,0.777000
11,ANOVA + DODA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811831

In [40]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        results_df,
        doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305606,0.738567,0.432324,0.786946
2,ANOVA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.713934,0.317044,0.754238,0.446431,0.805833
4,ANOVA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.808912,0.337419,0.258869,0.292970,0.732218
5,ANOVA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710012,0.315326,0.765066,0.446588,0.807438
6,ANOVA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714653,0.317890,0.755663,0.447519,0.809178
7,ANOVA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.824818,0.368867,0.204588,0.263196,0.754941
8,ANOVA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710470,0.316835,0.772475,0.449362,0.810981
9,ANOVA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842423,0.454194,0.150449,0.226027,0.776861
11,ANOVA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811829
12,ANOVA + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
13,ANOVA + DODA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305629,0.738709,0.432372,0.786912
14,ANOVA + DODA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
15,ANOVA + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714283,0.317720,0.756660,0.447525,0.805912
16,ANOVA + DODA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.793703,0.320533,0.311583,0.315995,0.718421
17,ANOVA + DODA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.708857,0.314543,0.766348,0.446020,0.807959
18,ANOVA + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712975,0.316255,0.754523,0.445697,0.807390
19,ANOVA + DODA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.829546,0.380995,0.183359,0.247571,0.758248
20,ANOVA + DODA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710753,0.316303,0.767346,0.447956,0.808930
21,ANOVA + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
22,ANOVA + DODA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842706,0.456859,0.150876,0.226839,0.777000
23,ANOVA + DODA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811831

In [41]:
for k in [5, 10, 15, 20]:

    print("=" * 70)
    print(f"TOP {k}")
    print("=" * 70)

    print("ANOVA:")
    print(anova_results[k]["features"])

    print("\nDODA:")
    print(doda_results[k]["features"])

======================================================================
TOP 5
======================================================================
ANOVA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

DODA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
======================================================================
TOP 10
======================================================================
ANOVA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education']

DODA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income']
======================================================================
TOP 15
======================================================================
ANOVA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth']

DODA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker']
======================================================================
TOP 20
======================================================================
ANOVA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth', 'Smoker', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

DODA:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker', 'HvyAlcoholConsump', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

In [42]:
k = 20

selector = doda_results[k]["selector"]

math_scores = pd.DataFrame(
    selector.get_math_scores().items(),
    columns=["Feature", "Math Score"]
)

clinical_weights = pd.DataFrame(
    selector.get_clinical_weights().items(),
    columns=["Feature", "Clinical Weight"]
)

final_scores = pd.DataFrame(
    selector.get_final_scores().items(),
    columns=["Feature", "Final Score"]
)

doda_analysis = (
    math_scores
    .merge(clinical_weights, on="Feature")
    .merge(final_scores, on="Feature")
)

doda_analysis = doda_analysis.sort_values(
    "Final Score",
    ascending=False
)

display(doda_analysis)

                 Feature    Math Score  Clinical Weight   Final Score
13               GenHlth  15028.459921              1.0  15028.459921
0                 HighBP  12696.639767              1.0  12696.639767
3                    BMI   8028.929585              1.0   8028.929585
16              DiffWalk   7990.290227              0.9   7191.261205
1               HighChol   7172.991333              0.9   6455.692200
18                   Age   5995.341829              0.9   5395.807647
6   HeartDiseaseorAttack   5368.293621              1.0   5368.293621
15              PhysHlth   4532.827198              0.8   3626.261758
5                 Stroke   1781.432236              1.0   1781.432236
20                Income   3621.117911              0.3   1086.335373
7           PhysActivity   1875.211102              0.4    750.084441
19             Education   1906.303916              0.3    571.891175
2              CholCheck    963.943424              0.4    385.577370
14              MentHlth    500.257213              0.5    250.128606
4                 Smoker    386.635201              0.6    231.981121
10     HvyAlcoholConsump    804.709027              0.2    160.941805
9                Veggies    302.338736              0.2     60.467747
17                   Sex    193.495629              0.2     38.699126
11         AnyHealthcare    133.841125              0.2     26.768225
8                 Fruits    101.570460              0.2     20.314092
12           NoDocbcCost     48.478989              0.2      9.695798