In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/diabetes_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 229474
Columns : 22

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "Diabetes_binary"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 229474
Columns : 21

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 229474

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    194377
1.0     35097
Name: count, dtype: int64

Class Percentage

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                     Data Type
HighBP                 float64
HighChol               float64
CholCheck              float64
BMI                    float64
Smoker                 float64
Stroke                 float64
HeartDiseaseorAttack   float64
PhysActivity           float64
Fruits                 float64
Veggies                float64
HvyAlcoholConsump      float64
AnyHealthcare          float64
NoDocbcCost            float64
GenHlth                float64
MentHlth               float64
PhysHlth               float64
DiffWalk               float64
Sex                    float64
Age                    float64
Education              float64
Income                 float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (183579, 21)
y_train shape : (183579,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (45895, 21)
y_test shape  : (45895,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

Diabetes_binary
0.0    84.71
1.0    15.29
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (183579, 21)
X_test_scaled shape  : (45895, 21)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.096408,-0.889095,0.205176,-0.395435,1.072035,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,-4.187359,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,1.13290,-0.350440,0.020709,0.529942
1,1.096408,1.124739,0.205176,0.786628,-0.932805,-0.215734,-0.338755,0.601961,-1.256327,0.509271,...,0.238814,-0.3204,0.375330,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,-0.986375,-1.381726
2,-0.912069,1.124739,0.205176,-0.690951,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,0.620283,1.027793,1.007859
3,-0.912069,1.124739,0.205176,-0.986467,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,-0.563578,-0.455262,-0.517047,-0.477229,-0.88269,1.591006,0.020709,-0.425892
4,1.096408,-0.889095,0.205176,0.195596,-0.932805,-0.215734,-0.338755,0.601961,0.795971,0.509271,...,0.238814,-0.3204,1.314239,-0.455262,0.698722,2.095428,-0.88269,-0.350440,-0.986375,-0.425892

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

HighBP                  0.0
HighChol                0.0
CholCheck              -0.0
BMI                    -0.0
Smoker                 -0.0
Stroke                  0.0
HeartDiseaseorAttack    0.0
PhysActivity           -0.0
Fruits                 -0.0
Veggies                -0.0
HvyAlcoholConsump      -0.0
AnyHealthcare           0.0
NoDocbcCost             0.0
GenHlth                 0.0
MentHlth                0.0
PhysHlth                0.0
DiffWalk               -0.0
Sex                    -0.0
Age                     0.0
Education              -0.0
Income                 -0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

HighBP                  1.0
HighChol                1.0
CholCheck               1.0
BMI                     1.0
Smoker                  1.0
Stroke                  1.0
HeartDiseaseorAttack    1.0
PhysActivity            1.0
Fruits                  1.0
Veggies                 1.0
HvyAlcoholConsump       1.0
AnyHealthcare           1.0
NoDocbcCost             1.0
GenHlth                 1.0
MentHlth                1.0
PhysHlth                1.0
DiffWalk                1.0
Sex                     1.0
Age                     1.0
Education               1.0
Income                  1.0
dtype: float64

# ANNOVA

## 1. Baseline

In [10]:
# =============================================================================
# ANOVA BASELINE FEATURE SELECTION (TOP-K = 5,10,15,20)
# =============================================================================

from sklearn.feature_selection import SelectKBest, f_classif
import pandas as pd


# Fit ANOVA once with all features
anova_selector = SelectKBest(
    score_func=f_classif,

    k="all"
)

anova_selector.fit(
    X_train_scaled,
    y_train
)


# Create score dataframe
anova_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "ANOVA Score": anova_selector.scores_

})


# Sort by ANOVA importance
anova_scores = anova_scores.sort_values(
    by="ANOVA Score",
    ascending=False
).reset_index(drop=True)



# Top-k values
k_values = [5, 10, 15, 20]

anova_results = {}


for k in k_values:

    top_features = (
        anova_scores
        .head(k)["Feature"]
        .tolist()
    )


    # Boolean mask for selecting columns
    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    anova_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": anova_scores.head(k)

    }


    print("="*70)
    print(f"TOP {k} ANOVA FEATURES")
    print("="*70)

    print(top_features)

    print("\nScores:")
    print(anova_scores.head(k))

======================================================================
TOP 5 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

Scores:
    Feature   ANOVA Score
0   GenHlth  15028.459921
1    HighBP  12696.639767
2       BMI   8028.929585
3  DiffWalk   7990.290227
4  HighChol   7172.991333
======================================================================
TOP 10 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education']

Scores:
                Feature   ANOVA Score
0               GenHlth  15028.459921
1                HighBP  12696.639767
2                   BMI   8028.929585
3              DiffWalk   7990.290227
4              HighChol   7172.991333
5                   Age   5995.341829
6  HeartDiseaseorAttack   5368.293621
7              PhysHlth   4532.827198
8                Income   3621.117911
9             Education   1906.303916
======================================================================
TOP 15 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth']

Scores:
                 Feature   ANOVA Score
0                GenHlth  15028.459921
1                 HighBP  12696.639767
2                    BMI   8028.929585
3               DiffWalk   7990.290227
4               HighChol   7172.991333
5                    Age   5995.341829
6   HeartDiseaseorAttack   5368.293621
7               PhysHlth   4532.827198
8                 Income   3621.117911
9              Education   1906.303916
10          PhysActivity   1875.211102
11                Stroke   1781.432236
12             CholCheck    963.943424
13     HvyAlcoholConsump    804.709027
14              MentHlth    500.257213
======================================================================
TOP 20 ANOVA FEATURES
======================================================================
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Income', 'Education', 'PhysActivity', 'Stroke', 'CholCheck', 'HvyAlcoholConsump', 'MentHlth', 'Smoker', 'Veggies', 'Sex', 'AnyHealthcare', 'Fruits']

Scores:
                 Feature   ANOVA Score
0                GenHlth  15028.459921
1                 HighBP  12696.639767
2                    BMI   8028.929585
3               DiffWalk   7990.290227
4               HighChol   7172.991333
5                    Age   5995.341829
6   HeartDiseaseorAttack   5368.293621
7               PhysHlth   4532.827198
8                 Income   3621.117911
9              Education   1906.303916
10          PhysActivity   1875.211102
11                Stroke   1781.432236
12             CholCheck    963.943424
13     HvyAlcoholConsump    804.709027
14              MentHlth    500.257213
15                Smoker    386.635201
16               Veggies    302.338736
17                   Sex    193.495629
18         AnyHealthcare    133.841125
19                Fruits    101.570460

In [11]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,

        eval_metric="logloss",
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()
    )
}

In [12]:
# =============================================================================
# MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for k in k_values:

    Xtr = anova_results[k]["X_train"]
    Xts = anova_results[k]["X_test"]

    features = ", ".join(anova_results[k]["features"])

    for model_name, model in models.items():

        model.fit(Xtr, y_train)

        y_pred = model.predict(Xts)

        y_prob = model.predict_proba(Xts)[:,1]

        results.append({

            "Method": "ANOVA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(y_test, y_pred),

            "Precision": precision_score(y_test, y_pred),

            "Recall": recall_score(y_test, y_pred),

            "F1 Score": f1_score(y_test, y_pred),

            "ROC-AUC": roc_auc_score(y_test, y_prob)

        })

In [13]:
results_df = pd.DataFrame(results)

results_df

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305606,0.738567,0.432324,0.786946
2,ANOVA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.713934,0.317044,0.754238,0.446431,0.805833
4,ANOVA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.808912,0.337419,0.258869,0.292970,0.732218
5,ANOVA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710012,0.315326,0.765066,0.446588,0.807438
6,ANOVA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714653,0.317890,0.755663,0.447519,0.809178
7,ANOVA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.824818,0.368867,0.204588,0.263196,0.754941
8,ANOVA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710470,0.316835,0.772475,0.449362,0.810981
9,ANOVA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842423,0.454194,0.150449,0.226027,0.776861
11,ANOVA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811829

In [14]:
results_df.to_csv(
    "../../../results/diabetes/baseline/anova_baseline_results.csv",
    index=False
)

## 2. DODA

In [15]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--upgrade",
    "--force-reinstall",
    "--no-cache-dir",
    "git+https://github.com/anandha-3679/DODA.git"
])

CalledProcessError: Command '['c:\\Users\\Anandha Lakshmi\\Downloads\\Anaconda\\python.exe', '-m', 'pip', 'install', '--upgrade', '--force-reinstall', '--no-cache-dir', 'git+https://github.com/anandha-3679/DODA.git']' returned non-zero exit status 1.

In [16]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [17]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [18]:
# =============================================================================
# ANOVA + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif

# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "clinical_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

doda_results = {}


# =============================================================================
# RUN DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"ANOVA + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # ANOVA operator
    # ---------------------------------------------------------------------

    anova = SklearnAdapter(
        SelectKBest(
            score_func=f_classif,
            k=k
        )
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[anova],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
ANOVA + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CACD70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.4772938392247658), 'CholCheck': np.float64(0.06414119804418085), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.02572686777293752), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.12477732993866683), 'Fruits': np.float64(0.006758540813779002), 'Veggies': np.float64(0.020117745746343032), 'HvyAlcoholConsump': np.float64(0.05354567473053477), 'AnyHealthcare': np.float64(0.008905844338298444), 'NoDocbcCost': np.float64(0.0032258121982011614), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03328732388205549), 'PhysHlth': np.float64(0.30161621492928176), 'DiffWalk': np.float64(0.5316772489779121), 'Sex': np.float64(0.012875279941924729), 'Age': np.float64(0.3989325493690825), 'Education': np.float64(0.12684625875214597), 'Income': np.float64(0.24095069820899404)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.42956445530228926), 'CholCheck': np.float64(0.02565647921767234), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.015436120663762511), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.049910931975466734), 'Fruits': np.float64(0.0013517081627558004), 'Veggies': np.float64(0.0040235491492686066), 'HvyAlcoholConsump': np.float64(0.010709134946106955), 'AnyHealthcare': np.float64(0.001781168867659689), 'NoDocbcCost': np.float64(0.0006451624396402323), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.016643661941027746), 'PhysHlth': np.float64(0.24129297194342542), 'DiffWalk': np.float64(0.47850952408012093), 'Sex': np.float64(0.002575055988384946), 'Age': np.float64(0.35903929443217425), 'Education': np.float64(0.038053877625643794), 'Income': np.float64(0.0722852094626982)}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

======================================================================
ANOVA + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CACD70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.4772938392247658), 'CholCheck': np.float64(0.06414119804418085), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.02572686777293752), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.12477732993866683), 'Fruits': np.float64(0.006758540813779002), 'Veggies': np.float64(0.020117745746343032), 'HvyAlcoholConsump': np.float64(0.05354567473053477), 'AnyHealthcare': np.float64(0.008905844338298444), 'NoDocbcCost': np.float64(0.0032258121982011614), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03328732388205549), 'PhysHlth': np.float64(0.30161621492928176), 'DiffWalk': np.float64(0.5316772489779121), 'Sex': np.float64(0.012875279941924729), 'Age': np.float64(0.3989325493690825), 'Education': np.float64(0.12684625875214597), 'Income': np.float64(0.24095069820899404)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.42956445530228926), 'CholCheck': np.float64(0.02565647921767234), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.015436120663762511), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.049910931975466734), 'Fruits': np.float64(0.0013517081627558004), 'Veggies': np.float64(0.0040235491492686066), 'HvyAlcoholConsump': np.float64(0.010709134946106955), 'AnyHealthcare': np.float64(0.001781168867659689), 'NoDocbcCost': np.float64(0.0006451624396402323), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.016643661941027746), 'PhysHlth': np.float64(0.24129297194342542), 'DiffWalk': np.float64(0.47850952408012093), 'Sex': np.float64(0.002575055988384946), 'Age': np.float64(0.35903929443217425), 'Education': np.float64(0.038053877625643794), 'Income': np.float64(0.0722852094626982)}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income']

======================================================================
ANOVA + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CACD70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.4772938392247658), 'CholCheck': np.float64(0.06414119804418085), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.02572686777293752), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.12477732993866683), 'Fruits': np.float64(0.006758540813779002), 'Veggies': np.float64(0.020117745746343032), 'HvyAlcoholConsump': np.float64(0.05354567473053477), 'AnyHealthcare': np.float64(0.008905844338298444), 'NoDocbcCost': np.float64(0.0032258121982011614), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03328732388205549), 'PhysHlth': np.float64(0.30161621492928176), 'DiffWalk': np.float64(0.5316772489779121), 'Sex': np.float64(0.012875279941924729), 'Age': np.float64(0.3989325493690825), 'Education': np.float64(0.12684625875214597), 'Income': np.float64(0.24095069820899404)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.42956445530228926), 'CholCheck': np.float64(0.02565647921767234), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.015436120663762511), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.049910931975466734), 'Fruits': np.float64(0.0013517081627558004), 'Veggies': np.float64(0.0040235491492686066), 'HvyAlcoholConsump': np.float64(0.010709134946106955), 'AnyHealthcare': np.float64(0.001781168867659689), 'NoDocbcCost': np.float64(0.0006451624396402323), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.016643661941027746), 'PhysHlth': np.float64(0.24129297194342542), 'DiffWalk': np.float64(0.47850952408012093), 'Sex': np.float64(0.002575055988384946), 'Age': np.float64(0.35903929443217425), 'Education': np.float64(0.038053877625643794), 'Income': np.float64(0.0722852094626982)}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker']

Selected Features:
['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'Stroke', 'Income', 'PhysActivity', 'Education', 'CholCheck', 'MentHlth', 'Smoker']

======================================================================
ANOVA + DODA — TOP 20 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CACD70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12696.639766679335), 'HighChol': np.float64(7172.991333444755), 'CholCheck': np.float64(963.9434241073692), 'BMI': np.float64(8028.929584555686), 'Smoker': np.float64(386.63520122466446), 'Stroke': np.float64(1781.4322362374398), 'HeartDiseaseorAttack': np.float64(5368.293621472076), 'PhysActivity': np.float64(1875.2111020627494), 'Fruits': np.float64(101.57045974595091), 'Veggies': np.float64(302.33873565463773), 'HvyAlcoholConsump': np.float64(804.7090266436618), 'AnyHealthcare': np.float64(133.8411247029314), 'NoDocbcCost': np.float64(48.478989334117266), 'GenHlth': np.float64(15028.459921241243), 'MentHlth': np.float64(500.25721284684744), 'PhysHlth': np.float64(4532.827197661196), 'DiffWalk': np.float64(7990.290227300355), 'Sex': np.float64(193.49562858197706), 'Age': np.float64(5995.34182947185), 'Education': np.float64(1906.303915816022), 'Income': np.float64(3621.117911028961)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.4772938392247658), 'CholCheck': np.float64(0.06414119804418085), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.02572686777293752), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.12477732993866683), 'Fruits': np.float64(0.006758540813779002), 'Veggies': np.float64(0.020117745746343032), 'HvyAlcoholConsump': np.float64(0.05354567473053477), 'AnyHealthcare': np.float64(0.008905844338298444), 'NoDocbcCost': np.float64(0.0032258121982011614), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03328732388205549), 'PhysHlth': np.float64(0.30161621492928176), 'DiffWalk': np.float64(0.5316772489779121), 'Sex': np.float64(0.012875279941924729), 'Age': np.float64(0.3989325493690825), 'Education': np.float64(0.12684625875214597), 'Income': np.float64(0.24095069820899404)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': np.float64(0.8448397129990605), 'HighChol': np.float64(0.42956445530228926), 'CholCheck': np.float64(0.02565647921767234), 'BMI': np.float64(0.5342483279479349), 'Smoker': np.float64(0.015436120663762511), 'Stroke': np.float64(0.11853724503863243), 'HeartDiseaseorAttack': np.float64(0.35720849971356833), 'PhysActivity': np.float64(0.049910931975466734), 'Fruits': np.float64(0.0013517081627558004), 'Veggies': np.float64(0.0040235491492686066), 'HvyAlcoholConsump': np.float64(0.010709134946106955), 'AnyHealthcare': np.float64(0.001781168867659689), 'NoDocbcCost': np.float64(0.0006451624396402323), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.016643661941027746), 'PhysHlth': np.float64(0.24129297194342542), 'DiffWalk': np.float64(0.47850952408012093), 'Sex': np.float64(0.002575055988384946), 'Age': np.float64(0.35903929443217425), 'Education': np.float64(0.038053877625643794), 'Income': np.float64(0.0722852094626982)}

In [19]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                 Feature  Raw Math Score  Normalized Math Score
13               GenHlth    15028.459921               1.000000
0                 HighBP    12696.639767               0.844840
3                    BMI     8028.929585               0.534248
16              DiffWalk     7990.290227               0.531677
1               HighChol     7172.991333               0.477294
18                   Age     5995.341829               0.398933
6   HeartDiseaseorAttack     5368.293621               0.357208
15              PhysHlth     4532.827198               0.301616
20                Income     3621.117911               0.240951
19             Education     1906.303916               0.126846
7           PhysActivity     1875.211102               0.124777
5                 Stroke     1781.432236               0.118537
2              CholCheck      963.943424               0.064141
10     HvyAlcoholConsump      804.709027               0.053546
14              MentHlth      500.257213               0.033287
4                 Smoker      386.635201               0.025727
9                Veggies      302.338736               0.020118
17                   Sex      193.495629               0.012875
11         AnyHealthcare      133.841125               0.008906
8                 Fruits      101.570460               0.006759
12           NoDocbcCost       48.478989               0.003226

In [20]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                 Feature  Clinical Weight
0                 HighBP              1.0
3                    BMI              1.0
13               GenHlth              1.0
6   HeartDiseaseorAttack              1.0
5                 Stroke              1.0
18                   Age              0.9
16              DiffWalk              0.9
1               HighChol              0.9
15              PhysHlth              0.8
4                 Smoker              0.6
14              MentHlth              0.5
2              CholCheck              0.4
7           PhysActivity              0.4
20                Income              0.3
19             Education              0.3
12           NoDocbcCost              0.2
9                Veggies              0.2
8                 Fruits              0.2
11         AnyHealthcare              0.2
10     HvyAlcoholConsump              0.2
17                   Sex              0.2

In [21]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                 Feature  Final DODA Score
13               GenHlth          1.000000
0                 HighBP          0.844840
3                    BMI          0.534248
16              DiffWalk          0.478510
1               HighChol          0.429564
18                   Age          0.359039
6   HeartDiseaseorAttack          0.357208
15              PhysHlth          0.241293
5                 Stroke          0.118537
20                Income          0.072285
7           PhysActivity          0.049911
19             Education          0.038054
2              CholCheck          0.025656
14              MentHlth          0.016644
4                 Smoker          0.015436
10     HvyAlcoholConsump          0.010709
9                Veggies          0.004024
17                   Sex          0.002575
11         AnyHealthcare          0.001781
8                 Fruits          0.001352
12           NoDocbcCost          0.000645

In [22]:
selector.get_selected_features()

['GenHlth',
 'HighBP',
 'BMI',
 'DiffWalk',
 'HighChol',
 'Age',
 'HeartDiseaseorAttack',
 'PhysHlth',
 'Stroke',
 'Income']

In [23]:
comparison = selector.compare_scores()

comparison

======================================================================
MATHEMATICAL vs CLINICAL vs HADAMARDFUSION
======================================================================

Fusion Method: HadamardFusion

Top Features After Fusion:
                Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0               GenHlth          1              5           1            0
1                HighBP          2              1           2            0
2                   BMI          3              2           3            0
3              DiffWalk          4              7           4            0
4              HighChol          5              6           5            0
5                   Age          6              8           6            0
6  HeartDiseaseorAttack          7              4           7            0
7              PhysHlth          8              9           8            0
8                Stroke         12              3           9            3
9                Income          9             15          10           -1

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,GenHlth,1,1.0000,5,1.0,1,1.0000,0
1,HighBP,2,0.8448,1,1.0,2,0.8448,0
2,BMI,3,0.5342,2,1.0,3,0.5342,0
3,DiffWalk,4,0.5317,7,0.9,4,0.4785,0
4,HighChol,5,0.4773,6,0.9,5,0.4296,0
5,Age,6,0.3989,8,0.9,6,0.3590,0
6,HeartDiseaseorAttack,7,0.3572,4,1.0,7,0.3572,0
7,PhysHlth,8,0.3016,9,0.8,8,0.2413,0
8,Stroke,12,0.1185,3,1.0,9,0.1185,3
9,Income,9,0.2410,15,0.3,10,0.0723,-1
10,PhysActivity,11,0.1248,13,0.4,11,0.0499,0
11,Education,10,0.1268,14,0.3,12,0.0381,-2
12,CholCheck,13,0.0641,12,0.4,13,0.0257,0
13,MentHlth,15,0.0333,11,0.5,14,0.0166,1
14,Smoker,16,0.0257,10,0.6,15,0.0154,1
15,HvyAlcoholConsump,14,0.0535,18,0.2,16,0.0107,-2
16,Veggies,17,0.0201,17,0.2,17,0.0040,0
17,Sex,18,0.0129,21,0.2,18,0.0026,0
18,AnyHealthcare,19,0.0089,19,0.2,19,0.0018,0
19,Fruits,20,0.0068,16,0.2,20,0.0014,0
20,NoDocbcCost,21,0.0032,20,0.2,21,0.0006,0

In [24]:
# =============================================================================
# DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


doda_model_results = []


for k in k_values:

    Xtr = doda_results[k]["X_train"]

    Xts = doda_results[k]["X_test"]

    features = ", ".join(
        doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        doda_model_results.append({

            "Method": "ANOVA + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


doda_results_df = pd.DataFrame(
    doda_model_results
)


display(doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA + DODA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305629,0.738709,0.432372,0.786912
2,ANOVA + DODA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714283,0.317720,0.756660,0.447525,0.805912
4,ANOVA + DODA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.793703,0.320533,0.311583,0.315995,0.718421
5,ANOVA + DODA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.708857,0.314543,0.766348,0.446020,0.807959
6,ANOVA + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712975,0.316255,0.754523,0.445697,0.807390
7,ANOVA + DODA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.829546,0.380995,0.183359,0.247571,0.758248
8,ANOVA + DODA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710753,0.316303,0.767346,0.447956,0.808930
9,ANOVA + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA + DODA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842706,0.456859,0.150876,0.226839,0.777000
11,ANOVA + DODA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811831

In [25]:
doda_results_df.to_csv(
    "../../../results/diabetes/doda/anova_doda_results.csv",
    index=False
)

In [26]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        results_df,
        doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
1,ANOVA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305606,0.738567,0.432324,0.786946
2,ANOVA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
3,ANOVA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.713934,0.317044,0.754238,0.446431,0.805833
4,ANOVA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.808912,0.337419,0.258869,0.292970,0.732218
5,ANOVA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710012,0.315326,0.765066,0.446588,0.807438
6,ANOVA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714653,0.317890,0.755663,0.447519,0.809178
7,ANOVA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.824818,0.368867,0.204588,0.263196,0.754941
8,ANOVA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710470,0.316835,0.772475,0.449362,0.810981
9,ANOVA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
10,ANOVA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842423,0.454194,0.150449,0.226027,0.776861
11,ANOVA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811829
12,ANOVA + DODA,5,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.708552,0.308374,0.728736,0.433364,0.791913
13,ANOVA + DODA,5,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.703366,0.305629,0.738709,0.432372,0.786912
14,ANOVA + DODA,5,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol",0.691077,0.299927,0.764496,0.430831,0.794595
15,ANOVA + DODA,10,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714283,0.317720,0.756660,0.447525,0.805912
16,ANOVA + DODA,10,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.793703,0.320533,0.311583,0.315995,0.718421
17,ANOVA + DODA,10,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.708857,0.314543,0.766348,0.446020,0.807959
18,ANOVA + DODA,15,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712975,0.316255,0.754523,0.445697,0.807390
19,ANOVA + DODA,15,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.829546,0.380995,0.183359,0.247571,0.758248
20,ANOVA + DODA,15,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.710753,0.316303,0.767346,0.447956,0.808930
21,ANOVA + DODA,20,Logistic Regression,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.714304,0.318260,0.760080,0.448659,0.810583
22,ANOVA + DODA,20,Random Forest,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.842706,0.456859,0.150876,0.226839,0.777000
23,ANOVA + DODA,20,XGBoost,"GenHlth, HighBP, BMI, DiffWalk, HighChol, Age,...",0.712997,0.319040,0.772760,0.451624,0.811831

In [27]:
# ============================================================
# DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "clinical_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should already contain the original Heart Disease data
# BEFORE imputation/scaling.

# Example:
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0

    # --------------------------------------------------------
    # 25 repeated CV runs
    # --------------------------------------------------------

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()

        # ----------------------------------------------------
        # Imputation fitted ONLY on training data
        # ----------------------------------------------------

        imputer = SimpleImputer(strategy="median")

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )

        # ----------------------------------------------------
        # ANOVA operator
        #
        # k="all" because DODA itself performs Top-K ranking
        # ----------------------------------------------------

        anova_operator = SklearnAdapter(
            SelectKBest(
                score_func=f_classif,
                k="all"
            )
        )

        # ----------------------------------------------------
        # Clinical knowledge provider
        # ----------------------------------------------------

        provider = JSONProvider(WEIGHTS_FILE)

        # ----------------------------------------------------
        # DODA selector
        # ----------------------------------------------------

        doda_selector = DODASelector(
            operators=[anova_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=TOP_K
        )

        # ----------------------------------------------------
        # Fit ONLY on training fold
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        # ----------------------------------------------------
        # Selected features
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )

        selected_feature_sets.append(set(selected_features))

        all_runs.append({
            "Top_K": TOP_K,
            "Run": run_number,
            "Selected_Features": selected_features
        })

        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []

    for i in range(len(selected_feature_sets)):

        for j in range(i + 1, len(selected_feature_sets)):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]

            intersection = len(set_a.intersection(set_b))
            union = len(set_a.union(set_b))

            jaccard = intersection / union

            jaccard_scores.append(jaccard)

            all_jaccard.append({
                "Top_K": TOP_K,
                "Run_A": i + 1,
                "Run_B": j + 1,
                "Jaccard_Similarity": jaccard
            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(jaccard_scores)
    std_jaccard = np.std(jaccard_scores)
    min_jaccard = np.min(jaccard_scores)
    max_jaccard = np.max(jaccard_scores)

    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(f"Number of runs:          {len(selected_feature_sets)}")
    print(f"Number of comparisons:   {len(jaccard_scores)}")
    print(f"Mean Jaccard Similarity: {mean_jaccard:.4f}")
    print(f"Standard Deviation:      {std_jaccard:.4f}")
    print(f"Minimum Jaccard:         {min_jaccard:.4f}")
    print(f"Maximum Jaccard:         {max_jaccard:.4f}")


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}

    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )

    for feature, count in feature_counts.items():

        all_frequency.append({
            "Top_K": TOP_K,
            "Feature": feature,
            "Selection_Count": count,
            "Selection_Frequency": count / len(selected_feature_sets)
        })

    frequency_df = pd.DataFrame(
        [
            {
                "Feature": feature,
                "Selection_Count": count,
                "Selection_Frequency": count / len(selected_feature_sets)
            }
            for feature, count in feature_counts.items()
        ]
    ).sort_values(
        "Selection_Frequency",
        ascending=False
    )

    print("\nFEATURE SELECTION FREQUENCY")

    print(frequency_df.to_string(index=False))


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(all_runs)

jaccard_df = pd.DataFrame(all_jaccard)

frequency_df = pd.DataFrame(all_frequency)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []

for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]

    summary_rows.append({
        "Top_K": TOP_K,
        "Mean_Jaccard": subset.mean(),
        "Std_Jaccard": subset.std(),
        "Min_Jaccard": subset.min(),
        "Max_Jaccard": subset.max()
    })


summary_df = pd.DataFrame(summary_rows)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(
    summary_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/diabetes/doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/diabetes/doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/diabetes/doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/diabetes/doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")
print("1. doda_stability_all_topk_runs.csv")
print("2. doda_stability_all_topk_jaccard.csv")
print("3. doda_stability_all_topk_frequency.csv")
print("4. doda_stability_all_topk_summary.csv")

======================================================================
DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DA4910>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Run 01: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DA5450>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12628.60558516035), 'HighChol': np.float64(7224.776279830574), 'CholCheck': np.float64(960.082974802271), 'BMI': np.float64(7977.986676971004), 'Smoker': np.float64(429.17333459788546), 'Stroke': np.float64(1820.3507345577996), 'HeartDiseaseorAttack': np.float64(5387.469677335985), 'PhysActivity': np.float64(1929.2172878228441), 'Fruits': np.float64(108.19714567391037), 'Veggies': np.float64(309.5111104662035), 'HvyAlcoholConsump': np.float64(792.4367153479299), 'AnyHealthcare': np.float64(107.3566532315966), 'NoDocbcCost': np.float64(84.28727704897864), 'GenHlth': np.float64(15540.69641733264), 'MentHlth': np.float64(602.1931608890196), 'PhysHlth': np.float64(4689.110920988237), 'DiffWalk': np.float64(8223.838634883552), 'Sex': np.float64(188.4299548160389), 'Age': np.float64(6029.064632075608), 'Education': np.float64(2001.2007466536902), 'Income': np.float64(3734.345017060291)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12628.60558516035), 'HighChol': np.float64(7224.776279830574), 'CholCheck': np.float64(960.082974802271), 'BMI': np.float64(7977.986676971004), 'Smoker': np.float64(429.17333459788546), 'Stroke': np.float64(1820.3507345577996), 'HeartDiseaseorAttack': np.float64(5387.469677335985), 'PhysActivity': np.float64(1929.2172878228441), 'Fruits': np.float64(108.19714567391037), 'Veggies': np.float64(309.5111104662035), 'HvyAlcoholConsump': np.float64(792.4367153479299), 'AnyHealthcare': np.float64(107.3566532315966), 'NoDocbcCost': np.float64(84.28727704897864), 'GenHlth': np.float64(15540.69641733264), 'MentHlth': np.float64(602.1931608890196), 'PhysHlth': np.float64(4689.110920988237), 'DiffWalk': np.float64(8223.838634883552), 'Sex': np.float64(188.4299548160389), 'Age': np.float64(6029.064632075608), 'Education': np.float64(2001.2007466536902), 'Income': np.float64(3734.345017060291)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8126151651141956), 'HighChol': np.float64(0.46489398453036723), 'CholCheck': np.float64(0.0617786326313848), 'BMI': np.float64(0.5133609500326577), 'Smoker': np.float64(0.027616094097252016), 'Stroke': np.float64(0.11713443758720817), 'HeartDiseaseorAttack': np.float64(0.34666848464572697), 'PhysActivity': np.float64(0.12413969335834754), 'Fruits': np.float64(0.006962181279935266), 'Veggies': np.float64(0.019916167342475317), 'HvyAlcoholConsump': np.float64(0.050991068486745554), 'AnyHealthcare': np.float64(0.006908097960903543), 'NoDocbcCost': np.float64(0.005423648643890404), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.038749432117944835), 'PhysHlth': np.float64(0.3017310675832031), 'DiffWalk': np.float64(0.5291808303848887), 'Sex': np.float64(0.012124936344929931), 'Age': np.float64(0.3879533111110357), 'Education': np.float64(0.12877162598850705), 'Income': np.float64(0.2402945734719682)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032018442622950824, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.029236022193768675, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.03200204813108039, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Run 02: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CAA9E0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12940.799023719715), 'HighChol': np.float64(7241.286365204554), 'CholCheck': np.float64(984.2628021547791), 'BMI': np.float64(8171.8010418149415), 'Smoker': np.float64(356.62113495528985), 'Stroke': np.float64(1789.8861548370583), 'HeartDiseaseorAttack': np.float64(5302.872636123003), 'PhysActivity': np.float64(1881.2240808153595), 'Fruits': np.float64(94.12031274174613), 'Veggies': np.float64(309.0828127533907), 'HvyAlcoholConsump': np.float64(822.0327283918216), 'AnyHealthcare': np.float64(136.348087450945), 'NoDocbcCost': np.float64(69.75075183749733), 'GenHlth': np.float64(15294.418949576906), 'MentHlth': np.float64(530.3725070200052), 'PhysHlth': np.float64(4730.652028932416), 'DiffWalk': np.float64(8153.873150968674), 'Sex': np.float64(190.7914622352907), 'Age': np.float64(5903.618171418776), 'Education': np.float64(1952.1472777732286), 'Income': np.float64(3671.268009081201)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12940.799023719715), 'HighChol': np.float64(7241.286365204554), 'CholCheck': np.float64(984.2628021547791), 'BMI': np.float64(8171.8010418149415), 'Smoker': np.float64(356.62113495528985), 'Stroke': np.float64(1789.8861548370583), 'HeartDiseaseorAttack': np.float64(5302.872636123003), 'PhysActivity': np.float64(1881.2240808153595), 'Fruits': np.float64(94.12031274174613), 'Veggies': np.float64(309.0828127533907), 'HvyAlcoholConsump': np.float64(822.0327283918216), 'AnyHealthcare': np.float64(136.348087450945), 'NoDocbcCost': np.float64(69.75075183749733), 'GenHlth': np.float64(15294.418949576906), 'MentHlth': np.float64(530.3725070200052), 'PhysHlth': np.float64(4730.652028932416), 'DiffWalk': np.float64(8153.873150968674), 'Sex': np.float64(190.7914622352907), 'Age': np.float64(5903.618171418776), 'Education': np.float64(1952.1472777732286), 'Income': np.float64(3671.268009081201)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8461124980545731), 'HighChol': np.float64(0.47345939646859697), 'CholCheck': np.float64(0.06435437693970107), 'BMI': np.float64(0.5342995421242205), 'Smoker': np.float64(0.023317076387864684), 'Stroke': np.float64(0.11702871228635806), 'HeartDiseaseorAttack': np.float64(0.34671945718275865), 'PhysActivity': np.float64(0.12300068979524066), 'Fruits': np.float64(0.006153899213304197), 'Veggies': np.float64(0.020208862708180293), 'HvyAlcoholConsump': np.float64(0.053747234929415987), 'AnyHealthcare': np.float64(0.008914891628146281), 'NoDocbcCost': np.float64(0.00456053623661374), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03467751921590176), 'PhysHlth': np.float64(0.30930576993663966), 'DiffWalk': np.float64(0.5331273569692713), 'Sex': np.float64(0.012474580620832844), 'Age': np.float64(0.38599819913930694), 'Education': np.float64(0.12763788439489762), 'Income': np.float64(0.24003971783333164)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.029236022193768675, 'Fruits': 0.027205882352941177, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Run 03: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C381CAA520>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12676.978257436587), 'HighChol': np.float64(7252.01789555841), 'CholCheck': np.float64(980.1730193199547), 'BMI': np.float64(8193.213927464642), 'Smoker': np.float64(392.38159391712423), 'Stroke': np.float64(1819.5723887696186), 'HeartDiseaseorAttack': np.float64(5322.148497791766), 'PhysActivity': np.float64(1919.9818194747054), 'Fruits': np.float64(125.10134412461548), 'Veggies': np.float64(326.2804102735145), 'HvyAlcoholConsump': np.float64(787.1074864594536), 'AnyHealthcare': np.float64(113.93230426273901), 'NoDocbcCost': np.float64(76.38073587437852), 'GenHlth': np.float64(15277.164841698903), 'MentHlth': np.float64(532.8918298515193), 'PhysHlth': np.float64(4506.694207734076), 'DiffWalk': np.float64(7972.2812082724595), 'Sex': np.float64(193.2726543488749), 'Age': np.float64(5957.729000020386), 'Education': np.float64(1992.3865160051914), 'Income': np.float64(3734.227313585937)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12676.978257436587), 'HighChol': np.float64(7252.01789555841), 'CholCheck': np.float64(980.1730193199547), 'BMI': np.float64(8193.213927464642), 'Smoker': np.float64(392.38159391712423), 'Stroke': np.float64(1819.5723887696186), 'HeartDiseaseorAttack': np.float64(5322.148497791766), 'PhysActivity': np.float64(1919.9818194747054), 'Fruits': np.float64(125.10134412461548), 'Veggies': np.float64(326.2804102735145), 'HvyAlcoholConsump': np.float64(787.1074864594536), 'AnyHealthcare': np.float64(113.93230426273901), 'NoDocbcCost': np.float64(76.38073587437852), 'GenHlth': np.float64(15277.164841698903), 'MentHlth': np.float64(532.8918298515193), 'PhysHlth': np.float64(4506.694207734076), 'DiffWalk': np.float64(7972.2812082724595), 'Sex': np.float64(193.2726543488749), 'Age': np.float64(5957.729000020386), 'Education': np.float64(1992.3865160051914), 'Income': np.float64(3734.227313585937)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8297991406648224), 'HighChol': np.float64(0.4746965795488495), 'CholCheck': np.float64(0.06415935348452745), 'BMI': np.float64(0.5363046096813283), 'Smoker': np.float64(0.02568418931018678), 'Stroke': np.float64(0.11910406201830787), 'HeartDiseaseorAttack': np.float64(0.34837278729002147), 'PhysActivity': np.float64(0.12567657935025547), 'Fruits': np.float64(0.0081887801448049), 'Veggies': np.float64(0.021357392792079762), 'HvyAlcoholConsump': np.float64(0.05152182977767248), 'AnyHealthcare': np.float64(0.007457686386400811), 'NoDocbcCost': np.float64(0.004999666932040812), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.034881591929740476), 'PhysHlth': np.float64(0.2949954559260295), 'DiffWalk': np.float64(0.5218429787778541), 'Sex': np.float64(0.012651081293653303), 'Age': np.float64(0.3899760892648622), 'Education': np.float64(0.1304159859928321), 'Income': np.float64(0.24443195791102498)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.029236022193768675, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Run 04: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DEAC30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12547.088018581486), 'HighChol': np.float64(7328.932202134178), 'CholCheck': np.float64(960.6439653744151), 'BMI': np.float64(7879.806856623305), 'Smoker': np.float64(335.8062083280819), 'Stroke': np.float64(1857.7281711333217), 'HeartDiseaseorAttack': np.float64(5370.169418988393), 'PhysActivity': np.float64(1819.0575859283872), 'Fruits': np.float64(116.77662084651124), 'Veggies': np.float64(343.35166518372245), 'HvyAlcoholConsump': np.float64(789.1422895851779), 'AnyHealthcare': np.float64(115.16981064409146), 'NoDocbcCost': np.float64(76.26982506927777), 'GenHlth': np.float64(14980.335792990742), 'MentHlth': np.float64(508.4934386986871), 'PhysHlth': np.float64(4523.195598379303), 'DiffWalk': np.float64(7999.359115447618), 'Sex': np.float64(205.4068799515698), 'Age': np.float64(5960.170549565276), 'Education': np.float64(1921.4317730064556), 'Income': np.float64(3696.488430268609)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

In [28]:
# ============================================================
# CV PREDICTIVE PERFORMANCE
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from xgboost import XGBClassifier

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "clinical_weights.json"


# ============================================================
# DATA
# ============================================================

# IMPORTANT:
# X and y should be the ORIGINAL dataset before:
# - imputation
# - scaling
# - feature selection
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# CROSS-VALIDATION
# ============================================================

cv = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

results = []


# ============================================================
# MODEL DEFINITIONS
# ============================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# ============================================================
# MAIN EXPERIMENT
# ============================================================

for method in ["ANOVA", "DODA"]:

    print("\n")
    print("=" * 80)
    print(f"METHOD: {method}")
    print("=" * 80)

    for TOP_K in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"{method} | TOP-{TOP_K}")
        print("-" * 80)

        for model_name, base_model in models.items():

            print(f"\nModel: {model_name}")

            for fold, (train_idx, val_idx) in enumerate(
                cv.split(X, y),
                start=1
            ):

                # ====================================================
                # TRAIN / VALIDATION SPLIT
                # ====================================================

                X_train = X.iloc[train_idx].copy()
                X_val = X.iloc[val_idx].copy()

                y_train = y.iloc[train_idx].copy()
                y_val = y.iloc[val_idx].copy()


                # ====================================================
                # IMPUTATION
                # Fit ONLY on training data
                # ====================================================

                imputer = SimpleImputer(strategy="median")

                X_train_imp = pd.DataFrame(
                    imputer.fit_transform(X_train),
                    columns=X_train.columns,
                    index=X_train.index
                )

                X_val_imp = pd.DataFrame(
                    imputer.transform(X_val),
                    columns=X_val.columns,
                    index=X_val.index
                )


                # ====================================================
                # FEATURE SELECTION
                # ====================================================

                if method == "ANOVA":

                    selector = SelectKBest(
                        score_func=f_classif,
                        k=TOP_K
                    )

                    X_train_selected = selector.fit_transform(
                        X_train_imp,
                        y_train
                    )

                    X_val_selected = selector.transform(
                        X_val_imp
                    )

                    selected_features = (
                        X_train_imp.columns[
                            selector.get_support()
                        ].tolist()
                    )


                elif method == "DODA":

                    # ------------------------------------------------
                    # ANOVA provides mathematical feature scores
                    # DODA then incorporates clinical weights
                    # ------------------------------------------------

                    anova_operator = SklearnAdapter(
                        SelectKBest(
                            score_func=f_classif,
                            k="all"
                        )
                    )

                    provider = JSONProvider(
                        WEIGHTS_FILE
                    )

                    doda_selector = DODASelector(
                        operators=[anova_operator],
                        provider=provider,
                        fusion=RankFusion(),
                        top_k=TOP_K
                    )

                    doda_selector.fit(
                        X_train_imp,
                        y_train
                    )

                    selected_features = list(
                        doda_selector.get_selected_features()
                    )

                    X_train_selected = (
                        X_train_imp[selected_features]
                    )

                    X_val_selected = (
                        X_val_imp[selected_features]
                    )


                # ====================================================
                # MODEL
                # ====================================================

                # Create a fresh model for every fold
                model = type(base_model)(
                    **base_model.get_params()
                )


                # ====================================================
                # SCALING
                # Only Logistic Regression needs scaling
                # ====================================================

                if model_name == "Logistic Regression":

                    scaler = StandardScaler()

                    X_train_final = scaler.fit_transform(
                        X_train_selected
                    )

                    X_val_final = scaler.transform(
                        X_val_selected
                    )

                else:

                    X_train_final = X_train_selected
                    X_val_final = X_val_selected


                # ====================================================
                # TRAIN
                # ====================================================

                model.fit(
                    X_train_final,
                    y_train
                )


                # ====================================================
                # PREDICTION
                # ====================================================

                y_pred = model.predict(
                    X_val_final
                )

                y_prob = model.predict_proba(
                    X_val_final
                )[:, 1]


                # ====================================================
                # METRICS
                # ====================================================

                accuracy = accuracy_score(
                    y_val,
                    y_pred
                )

                precision = precision_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                auc = roc_auc_score(
                    y_val,
                    y_prob
                )


                # ====================================================
                # STORE RESULTS
                # ====================================================

                results.append({

                    "Method": method,

                    "Top_K": TOP_K,

                    "Model": model_name,

                    "Fold": fold,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": auc,

                    "Selected_Features":
                        ", ".join(selected_features)
                })


                print(
                    f"  Fold {fold}: "
                    f"Acc={accuracy:.4f}, "
                    f"Prec={precision:.4f}, "
                    f"Recall={recall:.4f}, "
                    f"F1={f1:.4f}, "
                    f"AUC={auc:.4f}"
                )


# ============================================================
# RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)


# ============================================================
# SAVE FOLD-LEVEL RESULTS
# ============================================================

results_df.to_csv(
    "../../../results/diabetes_cv_results.csv",
    index=False
)


# ============================================================
# SUMMARY — MEAN ± STD
# ============================================================

summary_df = (
    results_df
    .groupby(
        ["Method", "Top_K", "Model"]
    )
    .agg({

        "Accuracy": ["mean", "std"],

        "Precision": ["mean", "std"],

        "Recall": ["mean", "std"],

        "F1": ["mean", "std"],

        "ROC_AUC": ["mean", "std"]

    })
    .reset_index()
)


# ============================================================
# FLATTEN COLUMN NAMES
# ============================================================

summary_df.columns = [

    "Method",
    "Top_K",
    "Model",

    "Accuracy_Mean",
    "Accuracy_STD",

    "Precision_Mean",
    "Precision_STD",

    "Recall_Mean",
    "Recall_STD",

    "F1_Mean",
    "F1_STD",

    "ROC_AUC_Mean",
    "ROC_AUC_STD"
]


# ============================================================
# SAVE SUMMARY
# ============================================================

summary_df.to_csv(
    "../../../results/diabetes_cv_summary.csv",
    index=False
)


# ============================================================
# DISPLAY SUMMARY
# ============================================================

print("\n")
print("=" * 100)
print("FINAL CV PERFORMANCE SUMMARY")
print("=" * 100)

display(
    summary_df.round(4)
)


# ============================================================
# BEST CONFIGURATION BY ROC-AUC
# ============================================================

best_auc = summary_df.loc[
    summary_df["ROC_AUC_Mean"].idxmax()
]

print("\n")
print("=" * 80)
print("BEST CONFIGURATION — ROC-AUC")
print("=" * 80)

print(
    f"Method:     {best_auc['Method']}"
)

print(
    f"Top-K:      {int(best_auc['Top_K'])}"
)

print(
    f"Model:      {best_auc['Model']}"
)

print(
    f"ROC-AUC:    "
    f"{best_auc['ROC_AUC_Mean']:.4f} "
    f"± {best_auc['ROC_AUC_STD']:.4f}"
)


# ============================================================
# BEST CONFIGURATION BY F1
# ============================================================

best_f1 = summary_df.loc[
    summary_df["F1_Mean"].idxmax()
]

print("\n")
print("=" * 80)
print("BEST CONFIGURATION — F1")
print("=" * 80)

print(
    f"Method:     {best_f1['Method']}"
)

print(
    f"Top-K:      {int(best_f1['Top_K'])}"
)

print(
    f"Model:      {best_f1['Model']}"
)

print(
    f"F1:         "
    f"{best_f1['F1_Mean']:.4f} "
    f"± {best_f1['F1_STD']:.4f}"
)

================================================================================
METHOD: ANOVA
================================================================================

--------------------------------------------------------------------------------
ANOVA | TOP-5
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8502, Prec=0.5438, Recall=0.1272, F1=0.2062, AUC=0.7888
  Fold 2: Acc=0.8502, Prec=0.5422, Recall=0.1328, F1=0.2133, AUC=0.7860
  Fold 3: Acc=0.8499, Prec=0.5402, Recall=0.1245, F1=0.2024, AUC=0.7841
  Fold 4: Acc=0.8496, Prec=0.5341, Recall=0.1318, F1=0.2114, AUC=0.7866
  Fold 5: Acc=0.8503, Prec=0.5446, Recall=0.1278, F1=0.2070, AUC=0.7935

Model: Random Forest
  Fold 1: Acc=0.8513, Prec=0.5591, Recall=0.1314, F1=0.2127, AUC=0.7871
  Fold 2: Acc=0.8496, Prec=0.5353, Recall=0.1252, F1=0.2030, AUC=0.7846
  Fold 3: Acc=0.8506, Prec=0.5535, Recall=0.1208, F1=0.1983, AUC=0.7805
  Fold 4: Acc=0.8503, Prec=0.5455, Recall=0.1281, F1=0.2074, AUC=0.7843
  Fold 5: Acc=0.8512, Prec=0.5595, Recall=0.1259, F1=0.2056, AUC=0.7897

Model: XGBoost
  Fold 1: Acc=0.8525, Prec=0.5870, Recall=0.1207, F1=0.2002, AUC=0.7940
  Fold 2: Acc=0.8510, Prec=0.5563, Recall=0.1267, F1=0.2063, AUC=0.7911
  Fold 3: Acc=0.8507, Prec=0.5568, Recall=0.1167, F1=0.1929, AUC=0.7899
  Fold 4: Acc=0.8517, Prec=0.5671, Recall=0.1282, F1=0.2091, AUC=0.7920
  Fold 5: Acc=0.8536, Prec=0.6019, Recall=0.1258, F1=0.2081, AUC=0.7984

--------------------------------------------------------------------------------
ANOVA | TOP-10
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8502, Prec=0.5402, Recall=0.1388, F1=0.2208, AUC=0.8032
  Fold 2: Acc=0.8494, Prec=0.5283, Recall=0.1410, F1=0.2226, AUC=0.7993
  Fold 3: Acc=0.8496, Prec=0.5323, Recall=0.1383, F1=0.2196, AUC=0.7996
  Fold 4: Acc=0.8492, Prec=0.5260, Recall=0.1413, F1=0.2228, AUC=0.8007
  Fold 5: Acc=0.8500, Prec=0.5362, Recall=0.1413, F1=0.2237, AUC=0.8070

Model: Random Forest
  Fold 1: Acc=0.8334, Prec=0.4154, Recall=0.2188, F1=0.2866, AUC=0.7515
  Fold 2: Acc=0.8322, Prec=0.4110, Recall=0.2237, F1=0.2897, AUC=0.7468
  Fold 3: Acc=0.8330, Prec=0.4114, Recall=0.2125, F1=0.2803, AUC=0.7476
  Fold 4: Acc=0.8321, Prec=0.4057, Recall=0.2108, F1=0.2775, AUC=0.7509
  Fold 5: Acc=0.8336, Prec=0.4170, Recall=0.2207, F1=0.2886, AUC=0.7525

Model: XGBoost
  Fold 1: Acc=0.8543, Prec=0.5881, Recall=0.1589, F1=0.2501, AUC=0.8120
  Fold 2: Acc=0.8526, Prec=0.5679, Recall=0.1524, F1=0.2404, AUC=0.8077
  Fold 3: Acc=0.8517, Prec=0.5594, Recall=0.1436, F1=0.2285, AUC=0.8092
  Fold 4: Acc=0.8537, Prec=0.5794, Recall=0.1580, F1=0.2483, AUC=0.8097
  Fold 5: Acc=0.8543, Prec=0.5880, Recall=0.1571, F1=0.2480, AUC=0.8148

--------------------------------------------------------------------------------
ANOVA | TOP-15
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8506, Prec=0.5426, Recall=0.1453, F1=0.2292, AUC=0.8061
  Fold 2: Acc=0.8500, Prec=0.5339, Recall=0.1490, F1=0.2330, AUC=0.8034
  Fold 3: Acc=0.8495, Prec=0.5295, Recall=0.1419, F1=0.2238, AUC=0.8031
  Fold 4: Acc=0.8498, Prec=0.5322, Recall=0.1481, F1=0.2318, AUC=0.8043
  Fold 5: Acc=0.8504, Prec=0.5405, Recall=0.1473, F1=0.2315, AUC=0.8111

Model: Random Forest
  Fold 1: Acc=0.8393, Prec=0.4425, Recall=0.1946, F1=0.2703, AUC=0.7659
  Fold 2: Acc=0.8382, Prec=0.4377, Recall=0.2037, F1=0.2780, AUC=0.7605
  Fold 3: Acc=0.8386, Prec=0.4366, Recall=0.1899, F1=0.2647, AUC=0.7622
  Fold 4: Acc=0.8382, Prec=0.4356, Recall=0.1966, F1=0.2709, AUC=0.7617
  Fold 5: Acc=0.8393, Prec=0.4435, Recall=0.1979, F1=0.2737, AUC=0.7676

Model: XGBoost
  Fold 1: Acc=0.8545, Prec=0.5882, Recall=0.1630, F1=0.2552, AUC=0.8156
  Fold 2: Acc=0.8531, Prec=0.5696, Recall=0.1610, F1=0.2510, AUC=0.8121
  Fold 3: Acc=0.8514, Prec=0.5544, Recall=0.1466, F1=0.2319, AUC=0.8128
  Fold 4: Acc=0.8541, Prec=0.5819, Recall=0.1635, F1=0.2553, AUC=0.8138
  Fold 5: Acc=0.8549, Prec=0.5925, Recall=0.1651, F1=0.2583, AUC=0.8191

--------------------------------------------------------------------------------
ANOVA | TOP-20
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8512, Prec=0.5494, Recall=0.1514, F1=0.2374, AUC=0.8072
  Fold 2: Acc=0.8498, Prec=0.5313, Recall=0.1497, F1=0.2336, AUC=0.8051
  Fold 3: Acc=0.8501, Prec=0.5363, Recall=0.1464, F1=0.2301, AUC=0.8045
  Fold 4: Acc=0.8499, Prec=0.5322, Recall=0.1520, F1=0.2365, AUC=0.8059
  Fold 5: Acc=0.8511, Prec=0.5476, Recall=0.1517, F1=0.2376, AUC=0.8120

Model: Random Forest
  Fold 1: Acc=0.8453, Prec=0.4843, Recall=0.1785, F1=0.2609, AUC=0.7800
  Fold 2: Acc=0.8442, Prec=0.4744, Recall=0.1720, F1=0.2524, AUC=0.7779
  Fold 3: Acc=0.8435, Prec=0.4672, Recall=0.1645, F1=0.2434, AUC=0.7776
  Fold 4: Acc=0.8425, Prec=0.4600, Recall=0.1711, F1=0.2494, AUC=0.7751
  Fold 5: Acc=0.8438, Prec=0.4697, Recall=0.1658, F1=0.2451, AUC=0.7811

Model: XGBoost
  Fold 1: Acc=0.8550, Prec=0.5929, Recall=0.1664, F1=0.2599, AUC=0.8169
  Fold 2: Acc=0.8533, Prec=0.5716, Recall=0.1626, F1=0.2531, AUC=0.8138
  Fold 3: Acc=0.8523, Prec=0.5637, Recall=0.1531, F1=0.2408, AUC=0.8139
  Fold 4: Acc=0.8536, Prec=0.5745, Recall=0.1664, F1=0.2580, AUC=0.8152
  Fold 5: Acc=0.8547, Prec=0.5887, Recall=0.1654, F1=0.2583, AUC=0.8201


================================================================================
METHOD: DODA
================================================================================

--------------------------------------------------------------------------------
DODA | TOP-5
--------------------------------------------------------------------------------

Model: Logistic Regression
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DAA4B0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
  Fold 1: Acc=0.8502, Prec=0.5438, Recall=0.1272, F1=0.2062, AUC=0.7888
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DABD10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12628.60558516035), 'HighChol': np.float64(7224.776279830574), 'CholCheck': np.float64(960.082974802271), 'BMI': np.float64(7977.986676971004), 'Smoker': np.float64(429.17333459788546), 'Stroke': np.float64(1820.3507345577996), 'HeartDiseaseorAttack': np.float64(5387.469677335985), 'PhysActivity': np.float64(1929.2172878228441), 'Fruits': np.float64(108.19714567391037), 'Veggies': np.float64(309.5111104662035), 'HvyAlcoholConsump': np.float64(792.4367153479299), 'AnyHealthcare': np.float64(107.3566532315966), 'NoDocbcCost': np.float64(84.28727704897864), 'GenHlth': np.float64(15540.69641733264), 'MentHlth': np.float64(602.1931608890196), 'PhysHlth': np.float64(4689.110920988237), 'DiffWalk': np.float64(8223.838634883552), 'Sex': np.float64(188.4299548160389), 'Age': np.float64(6029.064632075608), 'Education': np.float64(2001.2007466536902), 'Income': np.float64(3734.345017060291)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12628.60558516035), 'HighChol': np.float64(7224.776279830574), 'CholCheck': np.float64(960.082974802271), 'BMI': np.float64(7977.986676971004), 'Smoker': np.float64(429.17333459788546), 'Stroke': np.float64(1820.3507345577996), 'HeartDiseaseorAttack': np.float64(5387.469677335985), 'PhysActivity': np.float64(1929.2172878228441), 'Fruits': np.float64(108.19714567391037), 'Veggies': np.float64(309.5111104662035), 'HvyAlcoholConsump': np.float64(792.4367153479299), 'AnyHealthcare': np.float64(107.3566532315966), 'NoDocbcCost': np.float64(84.28727704897864), 'GenHlth': np.float64(15540.69641733264), 'MentHlth': np.float64(602.1931608890196), 'PhysHlth': np.float64(4689.110920988237), 'DiffWalk': np.float64(8223.838634883552), 'Sex': np.float64(188.4299548160389), 'Age': np.float64(6029.064632075608), 'Education': np.float64(2001.2007466536902), 'Income': np.float64(3734.345017060291)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8126151651141956), 'HighChol': np.float64(0.46489398453036723), 'CholCheck': np.float64(0.0617786326313848), 'BMI': np.float64(0.5133609500326577), 'Smoker': np.float64(0.027616094097252016), 'Stroke': np.float64(0.11713443758720817), 'HeartDiseaseorAttack': np.float64(0.34666848464572697), 'PhysActivity': np.float64(0.12413969335834754), 'Fruits': np.float64(0.006962181279935266), 'Veggies': np.float64(0.019916167342475317), 'HvyAlcoholConsump': np.float64(0.050991068486745554), 'AnyHealthcare': np.float64(0.006908097960903543), 'NoDocbcCost': np.float64(0.005423648643890404), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.038749432117944835), 'PhysHlth': np.float64(0.3017310675832031), 'DiffWalk': np.float64(0.5291808303848887), 'Sex': np.float64(0.012124936344929931), 'Age': np.float64(0.3879533111110357), 'Education': np.float64(0.12877162598850705), 'Income': np.float64(0.2402945734719682)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032018442622950824, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.029236022193768675, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.03200204813108039, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
  Fold 2: Acc=0.8502, Prec=0.5422, Recall=0.1328, F1=0.2133, AUC=0.7860
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DAB8F0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12940.799023719715), 'HighChol': np.float64(7241.286365204554), 'CholCheck': np.float64(984.2628021547791), 'BMI': np.float64(8171.8010418149415), 'Smoker': np.float64(356.62113495528985), 'Stroke': np.float64(1789.8861548370583), 'HeartDiseaseorAttack': np.float64(5302.872636123003), 'PhysActivity': np.float64(1881.2240808153595), 'Fruits': np.float64(94.12031274174613), 'Veggies': np.float64(309.0828127533907), 'HvyAlcoholConsump': np.float64(822.0327283918216), 'AnyHealthcare': np.float64(136.348087450945), 'NoDocbcCost': np.float64(69.75075183749733), 'GenHlth': np.float64(15294.418949576906), 'MentHlth': np.float64(530.3725070200052), 'PhysHlth': np.float64(4730.652028932416), 'DiffWalk': np.float64(8153.873150968674), 'Sex': np.float64(190.7914622352907), 'Age': np.float64(5903.618171418776), 'Education': np.float64(1952.1472777732286), 'Income': np.float64(3671.268009081201)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12940.799023719715), 'HighChol': np.float64(7241.286365204554), 'CholCheck': np.float64(984.2628021547791), 'BMI': np.float64(8171.8010418149415), 'Smoker': np.float64(356.62113495528985), 'Stroke': np.float64(1789.8861548370583), 'HeartDiseaseorAttack': np.float64(5302.872636123003), 'PhysActivity': np.float64(1881.2240808153595), 'Fruits': np.float64(94.12031274174613), 'Veggies': np.float64(309.0828127533907), 'HvyAlcoholConsump': np.float64(822.0327283918216), 'AnyHealthcare': np.float64(136.348087450945), 'NoDocbcCost': np.float64(69.75075183749733), 'GenHlth': np.float64(15294.418949576906), 'MentHlth': np.float64(530.3725070200052), 'PhysHlth': np.float64(4730.652028932416), 'DiffWalk': np.float64(8153.873150968674), 'Sex': np.float64(190.7914622352907), 'Age': np.float64(5903.618171418776), 'Education': np.float64(1952.1472777732286), 'Income': np.float64(3671.268009081201)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8461124980545731), 'HighChol': np.float64(0.47345939646859697), 'CholCheck': np.float64(0.06435437693970107), 'BMI': np.float64(0.5342995421242205), 'Smoker': np.float64(0.023317076387864684), 'Stroke': np.float64(0.11702871228635806), 'HeartDiseaseorAttack': np.float64(0.34671945718275865), 'PhysActivity': np.float64(0.12300068979524066), 'Fruits': np.float64(0.006153899213304197), 'Veggies': np.float64(0.020208862708180293), 'HvyAlcoholConsump': np.float64(0.053747234929415987), 'AnyHealthcare': np.float64(0.008914891628146281), 'NoDocbcCost': np.float64(0.00456053623661374), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03467751921590176), 'PhysHlth': np.float64(0.30930576993663966), 'DiffWalk': np.float64(0.5331273569692713), 'Sex': np.float64(0.012474580620832844), 'Age': np.float64(0.38599819913930694), 'Education': np.float64(0.12763788439489762), 'Income': np.float64(0.24003971783333164)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03028233151183971, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.029236022193768675, 'Fruits': 0.027205882352941177, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027364110201042444, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']
  Fold 3: Acc=0.8499, Prec=0.5402, Recall=0.1245, F1=0.2024, AUC=0.7841
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C386DD97F0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,ANOVA,5,Logistic Regression,0.8500,0.0003,0.5410,0.0042,0.1288,0.0034,0.2081,0.0043,0.7878,0.0036
1,ANOVA,5,Random Forest,0.8506,0.0007,0.5506,0.0102,0.1263,0.0039,0.2054,0.0053,0.7852,0.0034
2,ANOVA,5,XGBoost,0.8519,0.0012,0.5738,0.0200,0.1236,0.0048,0.2033,0.0068,0.7931,0.0033
3,ANOVA,10,Logistic Regression,0.8497,0.0004,0.5326,0.0058,0.1402,0.0015,0.2219,0.0017,0.8020,0.0032
4,ANOVA,10,Random Forest,0.8329,0.0007,0.4121,0.0044,0.2173,0.0055,0.2845,0.0054,0.7499,0.0025
5,ANOVA,10,XGBoost,0.8533,0.0011,0.5766,0.0127,0.1540,0.0063,0.2431,0.0089,0.8107,0.0028
6,ANOVA,15,Logistic Regression,0.8500,0.0005,0.5358,0.0056,0.1463,0.0028,0.2299,0.0037,0.8056,0.0033
7,ANOVA,15,Random Forest,0.8387,0.0006,0.4392,0.0036,0.1965,0.0050,0.2715,0.0049,0.7636,0.0030
8,ANOVA,15,XGBoost,0.8536,0.0014,0.5773,0.0154,0.1598,0.0076,0.2503,0.0106,0.8147,0.0028
9,ANOVA,20,Logistic Regression,0.8504,0.0007,0.5393,0.0086,0.1503,0.0023,0.2350,0.0032,0.8070,0.0030
10,ANOVA,20,Random Forest,0.8439,0.0010,0.4711,0.0090,0.1704,0.0056,0.2502,0.0069,0.7783,0.0023
11,ANOVA,20,XGBoost,0.8538,0.0011,0.5783,0.0122,0.1628,0.0056,0.2540,0.0078,0.8160,0.0026
12,DODA,5,Logistic Regression,0.8500,0.0003,0.5410,0.0042,0.1288,0.0034,0.2081,0.0043,0.7878,0.0036
13,DODA,5,Random Forest,0.8506,0.0007,0.5507,0.0103,0.1263,0.0038,0.2054,0.0053,0.7852,0.0035
14,DODA,5,XGBoost,0.8518,0.0011,0.5706,0.0173,0.1249,0.0045,0.2049,0.0065,0.7930,0.0034
15,DODA,10,Logistic Regression,0.8499,0.0005,0.5349,0.0062,0.1410,0.0024,0.2231,0.0029,0.8020,0.0032
16,DODA,10,Random Forest,0.8328,0.0013,0.4131,0.0060,0.2213,0.0046,0.2881,0.0039,0.7476,0.0033
17,DODA,10,XGBoost,0.8533,0.0013,0.5766,0.0154,0.1543,0.0061,0.2435,0.0089,0.8108,0.0028
18,DODA,15,Logistic Regression,0.8499,0.0005,0.5348,0.0069,0.1427,0.0024,0.2253,0.0030,0.8039,0.0032
19,DODA,15,Random Forest,0.8394,0.0008,0.4412,0.0058,0.1871,0.0037,0.2627,0.0042,0.7644,0.0030
20,DODA,15,XGBoost,0.8532,0.0013,0.5726,0.0145,0.1574,0.0069,0.2469,0.0099,0.8131,0.0027
21,DODA,20,Logistic Regression,0.8504,0.0007,0.5393,0.0086,0.1503,0.0023,0.2350,0.0032,0.8070,0.0030
22,DODA,20,Random Forest,0.8432,0.0011,0.4652,0.0098,0.1698,0.0059,0.2488,0.0074,0.7782,0.0022
23,DODA,20,XGBoost,0.8539,0.0013,0.5800,0.0146,0.1632,0.0058,0.2548,0.0083,0.8161,0.0026

================================================================================
BEST CONFIGURATION — ROC-AUC
================================================================================
Method:     DODA
Top-K:      20
Model:      XGBoost
ROC-AUC:    0.8161 ± 0.0026


================================================================================
BEST CONFIGURATION — F1
================================================================================
Method:     DODA
Top-K:      10
Model:      Random Forest
F1:         0.2881 ± 0.0039

In [29]:
# ============================================================
# 5×5 REPEATED STRATIFIED CV
# ANOVA vs DODA PREDICTIVE PERFORMANCE
# ============================================================

import numpy as np
import pandas as pd

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42


# ============================================================
# MODELS
# ============================================================

models = {
    "LR": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "RF": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGB": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# ============================================================
# DODA PROVIDER
# ============================================================

provider = JSONProvider("clinical_weights.json")


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

results = []


# ============================================================
# MAIN LOOP
# ============================================================

for run_id, (train_idx, test_idx) in enumerate(
    cv.split(X, y), start=1
):

    print("=" * 70)
    print(f"RUN {run_id}/25")
    print("=" * 70)

    # --------------------------------------------------------
    # Split data
    # --------------------------------------------------------

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # --------------------------------------------------------
    # Imputation
    # Fit ONLY on training data
    # --------------------------------------------------------

    imputer = SimpleImputer(strategy="median")

    X_train_imp = pd.DataFrame(
        imputer.fit_transform(X_train),
        columns=X_train.columns,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        imputer.transform(X_test),
        columns=X_test.columns,
        index=X_test.index
    )


    # ========================================================
    # LOOP THROUGH TOP-K
    # ========================================================

    for top_k in TOP_K_VALUES:

        print(f"\nTop-{top_k}")


        # ====================================================
        # ANOVA FEATURE SELECTION
        # ====================================================

        anova_selector = SelectKBest(
            score_func=f_classif,
            k=top_k
        )

        X_train_anova = anova_selector.fit_transform(
            X_train_imp,
            y_train
        )

        X_test_anova = anova_selector.transform(
            X_test_imp
        )

        anova_features = X_train_imp.columns[
            anova_selector.get_support()
        ].tolist()


        # ====================================================
        # DODA FEATURE SELECTION
        # ====================================================

        # k="all" is important:
        # ANOVA scores ALL features first.
        # DODA performs the final Top-K ranking.

        anova_operator = SklearnAdapter(
            SelectKBest(
                score_func=f_classif,
                k="all"
            )
        )

        doda_selector = DODASelector(
            operators=[anova_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        doda_features = doda_selector.get_selected_features()


        # ----------------------------------------------------
        # Transform test/train data
        # ----------------------------------------------------

        X_train_doda = X_train_imp[doda_features]
        X_test_doda = X_test_imp[doda_features]


        # ====================================================
        # MODEL LOOP
        # ====================================================

        for model_name, model_template in models.items():

            # =================================================
            # ANOVA
            # =================================================

            model = model_template.__class__(
                **model_template.get_params()
            )

            Xtr = X_train_anova
            Xte = X_test_anova

            # -------------------------------------------------
            # Scale only for Logistic Regression
            # -------------------------------------------------

            if model_name == "LR":

                scaler = StandardScaler()

                Xtr = scaler.fit_transform(Xtr)
                Xte = scaler.transform(Xte)

            model.fit(Xtr, y_train)

            y_pred = model.predict(Xte)
            y_prob = model.predict_proba(Xte)[:, 1]


            anova_metrics = {
                "Accuracy": accuracy_score(
                    y_test, y_pred
                ),

                "Precision": precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "Recall": recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "F1": f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "ROC_AUC": roc_auc_score(
                    y_test,
                    y_prob
                )
            }


            results.append({
                "Run": run_id,
                "Method": "ANOVA",
                "Top_K": top_k,
                "Model": model_name,
                "Accuracy": anova_metrics["Accuracy"],
                "Precision": anova_metrics["Precision"],
                "Recall": anova_metrics["Recall"],
                "F1": anova_metrics["F1"],
                "ROC_AUC": anova_metrics["ROC_AUC"],
                "Selected_Features": ", ".join(anova_features)
            })


            # =================================================
            # DODA
            # =================================================

            model = model_template.__class__(
                **model_template.get_params()
            )

            Xtr = X_train_doda
            Xte = X_test_doda

            # -------------------------------------------------
            # Scale only for Logistic Regression
            # -------------------------------------------------

            if model_name == "LR":

                scaler = StandardScaler()

                Xtr = scaler.fit_transform(Xtr)
                Xte = scaler.transform(Xte)

            model.fit(Xtr, y_train)

            y_pred = model.predict(Xte)
            y_prob = model.predict_proba(Xte)[:, 1]


            doda_metrics = {
                "Accuracy": accuracy_score(
                    y_test, y_pred
                ),

                "Precision": precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "Recall": recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "F1": f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "ROC_AUC": roc_auc_score(
                    y_test,
                    y_prob
                )
            }


            results.append({
                "Run": run_id,
                "Method": "DODA",
                "Top_K": top_k,
                "Model": model_name,
                "Accuracy": doda_metrics["Accuracy"],
                "Precision": doda_metrics["Precision"],
                "Recall": doda_metrics["Recall"],
                "F1": doda_metrics["F1"],
                "ROC_AUC": doda_metrics["ROC_AUC"],
                "Selected_Features": ", ".join(doda_features)
            })


# ============================================================
# CREATE RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)

print("\nCompleted!")
print("Total runs:", len(results_df))

results_df.head()

======================================================================
RUN 1/25
======================================================================

Top-5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C3BE01C530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 5 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol']

Top-10
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C3BE01C530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 10 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'HeartDiseaseorAttack', 'Age', 'PhysHlth', 'Stroke', 'Income']

Top-15
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C3BE01C530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 15 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'HeartDiseaseorAttack', 'Age', 'PhysHlth', 'Stroke', 'Income', 'Education', 'PhysActivity', 'CholCheck', 'Smoker', 'MentHlth']

Top-20
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C3BE01C530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'HighBP': np.float64(12680.515022522148), 'HighChol': np.float64(7214.04785563188), 'CholCheck': np.float64(968.2340991382633), 'BMI': np.float64(8080.950570252485), 'Smoker': np.float64(394.03049203157457), 'Stroke': np.float64(1834.0359378221917), 'HeartDiseaseorAttack': np.float64(5346.0930342178945), 'PhysActivity': np.float64(1799.766110922192), 'Fruits': np.float64(122.37541165606639), 'Veggies': np.float64(313.8867870254641), 'HvyAlcoholConsump': np.float64(819.2731611353994), 'AnyHealthcare': np.float64(117.55480540888074), 'NoDocbcCost': np.float64(63.2147597334414), 'GenHlth': np.float64(15156.632794853043), 'MentHlth': np.float64(527.9374043101004), 'PhysHlth': np.float64(4511.205389986336), 'DiffWalk': np.float64(8042.679265057442), 'Sex': np.float64(206.45533215858242), 'Age': np.float64(5927.576367416428), 'Education': np.float64(1915.4154723775544), 'Income': np.float64(3690.7529926107045)}

Normalized Mathematical Scores
{'HighBP': np.float64(0.8366314071307615), 'HighChol': np.float64(0.47596639393953377), 'CholCheck': np.float64(0.06388187351659404), 'BMI': np.float64(0.5331626542405019), 'Smoker': np.float64(0.02599723153320579), 'Stroke': np.float64(0.12100550053868177), 'HeartDiseaseorAttack': np.float64(0.35272300296364933), 'PhysActivity': np.float64(0.11874445566388364), 'Fruits': np.float64(0.008074050042145455), 'Veggies': np.float64(0.020709532999443992), 'HvyAlcoholConsump': np.float64(0.05405377119208244), 'AnyHealthcare': np.float64(0.007755997456691074), 'NoDocbcCost': np.float64(0.004170765406080706), 'GenHlth': np.float64(1.0), 'MentHlth': np.float64(0.03483210363778027), 'PhysHlth': np.float64(0.29763902385484137), 'DiffWalk': np.float64(0.5306376009708839), 'Sex': np.float64(0.013621451080393756), 'Age': np.float64(0.39108794464093244), 'Education': np.float64(0.12637473628232251), 'Income': np.float64(0.24350744935009752)}

Clinical Weights
{'HighBP': 1.0, 'HighChol': 0.9, 'CholCheck': 0.4, 'BMI': 1.0, 'Smoker': 0.6, 'Stroke': 1.0, 'HeartDiseaseorAttack': 1.0, 'PhysActivity': 0.4, 'Fruits': 0.2, 'Veggies': 0.2, 'HvyAlcoholConsump': 0.2, 'AnyHealthcare': 0.2, 'NoDocbcCost': 0.2, 'GenHlth': 1.0, 'MentHlth': 0.5, 'PhysHlth': 0.8, 'DiffWalk': 0.9, 'Sex': 0.2, 'Age': 0.9, 'Education': 0.3, 'Income': 0.3}

Final DODA Scores
{'HighBP': 0.03252247488101534, 'HighChol': 0.0315136476426799, 'CholCheck': 0.028850145288501453, 'BMI': 0.032266458495966696, 'Smoker': 0.028782894736842105, 'Stroke': 0.03047794966520434, 'HeartDiseaseorAttack': 0.03131881575727918, 'PhysActivity': 0.02904040404040404, 'Fruits': 0.027364110201042444, 'Veggies': 0.027692895339954164, 'HvyAlcoholConsump': 0.02821939586645469, 'AnyHealthcare': 0.027205882352941177, 'NoDocbcCost': 0.027051561365286855, 'GenHlth': 0.03278688524590164, 'MentHlth': 0.02871794871794872, 'PhysHlth': 0.03057889822595705, 'DiffWalk': 0.031754032258064516, 'Sex': 0.027526395173453996, 'Age': 0.03128054740957967, 'Education': 0.029211087420042643, 'Income': 0.029418126757516764}
Top 20 Features Selected: ['GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol', 'HeartDiseaseorAttack', 'Age', 'PhysHlth', 'Stroke', 'Income', 'Education', 'PhysActivity', 'CholCheck', 'Smoker', 'MentHlth', 'HvyAlcoholConsump', 'Veggies', 'Sex', 'Fruits', 'AnyHealthcare']
======================================================================
RUN 2/25
======================================================================

Top-5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001C3BE01C530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies']
Number of features: 21
Number of scores: 21
Operator Scores:
{'SelectKBest_1': {'HighBP': np.float64(12628.60558516035), 'HighChol': np.float64(7224.776279830574), 'CholCheck': np.float64(960.082974802271), 'BMI': np.float64(7977.986676971004), 'Smoker': np.float64(429.17333459788546), 'Stroke': np.float64(1820.3507345577996), 'HeartDiseaseorAttack': np.float64(5387.469677335985), 'PhysActivity': np.float64(1929.2172878228441), 'Fruits': np.float64(108.19714567391037), 'Veggies': np.float64(309.5111104662035), 'HvyAlcoholConsump': np.float64(792.4367153479299), 'AnyHealthcare': np.float64(107.3566532315966), 'NoDocbcCost': np.float64(84.28727704897864), 'GenHlth': np.float64(15540.69641733264), 'MentHlth': np.float64(602.1931608890196), 'PhysHlth': np.float64(4689.110920988237), 'DiffWalk': np.float64(8223.838634883552), 'Sex': np.float64(188.4299548160389), 'Age': np.float64(6029.064632075608), 'Education': np.float64(2001.2007466536902), 'Income': np.float64(3734.345017060291)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,ANOVA,5,LR,0.850202,0.543849,0.127226,0.206212,0.788804,"HighBP, HighChol, BMI, GenHlth, DiffWalk"
1,1,DODA,5,LR,0.850202,0.543849,0.127226,0.206212,0.788804,"GenHlth, HighBP, BMI, DiffWalk, HighChol"
2,1,ANOVA,5,RF,0.851313,0.559127,0.131358,0.212737,0.787069,"HighBP, HighChol, BMI, GenHlth, DiffWalk"
3,1,DODA,5,RF,0.851313,0.559127,0.131358,0.212737,0.787071,"GenHlth, HighBP, BMI, DiffWalk, HighChol"
4,1,ANOVA,5,XGB,0.852533,0.586972,0.120672,0.200189,0.794029,"HighBP, HighChol, BMI, GenHlth, DiffWalk"

In [30]:
# =============================================================================
# PREPARE STABILITY DATAFRAME
# =============================================================================

stability_df = results_df[
    ["Run", "Method", "Top_K", "Selected_Features"]
].copy()

stability_df["Feature_Set"] = stability_df["Selected_Features"].apply(
    lambda x: {
        feature.strip()
        for feature in x.split(",")
        if feature.strip()
    }
)

print("Shape:", stability_df.shape)

print("\nMethods:")
print(stability_df["Method"].unique())

print("\nTop-K:")
print(sorted(stability_df["Top_K"].unique()))

display(
    stability_df[
        ["Run", "Method", "Top_K", "Feature_Set"]
    ].head()
)

Shape: (600, 5)

Methods:
['ANOVA' 'DODA']

Top-K:
[np.int64(5), np.int64(10), np.int64(15), np.int64(20)]

   Run Method  Top_K                                 Feature_Set
0    1  ANOVA      5  {DiffWalk, HighBP, BMI, GenHlth, HighChol}
1    1   DODA      5  {DiffWalk, HighBP, BMI, GenHlth, HighChol}
2    1  ANOVA      5  {DiffWalk, HighBP, BMI, GenHlth, HighChol}
3    1   DODA      5  {DiffWalk, HighBP, BMI, GenHlth, HighChol}
4    1  ANOVA      5  {DiffWalk, HighBP, BMI, GenHlth, HighChol}

In [31]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# =============================================================================

selection_frequency = []

for method in stability_df["Method"].unique():

    for top_k in sorted(stability_df["Top_K"].unique()):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]

        total_runs = len(subset)

        all_features = sorted(
            set().union(*subset["Feature_Set"])
        )

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set in subset["Feature_Set"]
            )

            selection_frequency.append({
                "Method": method,
                "Top_K": top_k,
                "Feature": feature,
                "Selected_Count": selected_count,
                "Total_Runs": total_runs,
                "Selection_Frequency_Percentage":
                    (selected_count / total_runs) * 100
            })

selection_frequency_df = pd.DataFrame(selection_frequency)

selection_frequency_df = selection_frequency_df.sort_values(
    by=[
        "Method",
        "Top_K",
        "Selection_Frequency_Percentage"
    ],
    ascending=[True, True, False]
).reset_index(drop=True)

display(selection_frequency_df)

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,ANOVA,5,BMI,75,75,100.0
1,ANOVA,5,DiffWalk,75,75,100.0
2,ANOVA,5,GenHlth,75,75,100.0
3,ANOVA,5,HighBP,75,75,100.0
4,ANOVA,5,HighChol,75,75,100.0
...,...,...,...,...,...,...
98,DODA,20,PhysHlth,75,75,100.0
99,DODA,20,Sex,75,75,100.0
100,DODA,20,Smoker,75,75,100.0
101,DODA,20,Stroke,75,75,100.0
102,DODA,20,Veggies,75,75,100.0

In [32]:
# =============================================================================
# TOP FREQUENTLY SELECTED FEATURES
# =============================================================================

top_frequency_features = (
    selection_frequency_df
    .groupby(["Method", "Top_K"], group_keys=False)
    .head(10)
    .reset_index(drop=True)
)

display(top_frequency_features)

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,ANOVA,5,BMI,75,75,100.0
1,ANOVA,5,DiffWalk,75,75,100.0
2,ANOVA,5,GenHlth,75,75,100.0
3,ANOVA,5,HighBP,75,75,100.0
4,ANOVA,5,HighChol,75,75,100.0
...,...,...,...,...,...,...
65,DODA,20,Education,75,75,100.0
66,DODA,20,Fruits,75,75,100.0
67,DODA,20,GenHlth,75,75,100.0
68,DODA,20,HeartDiseaseorAttack,75,75,100.0
69,DODA,20,HighBP,75,75,100.0

In [33]:
# =============================================================================
# TEST 2: PAIRWISE JACCARD SIMILARITY
# =============================================================================

from itertools import combinations

jaccard_results = []

for method in stability_df["Method"].unique():

    for top_k in sorted(stability_df["Top_K"].unique()):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)

        feature_sets = subset["Feature_Set"].tolist()

        pairwise_scores = []

        for set_a, set_b in combinations(feature_sets, 2):

            intersection_size = len(set_a.intersection(set_b))
            union_size = len(set_a.union(set_b))

            if union_size == 0:
                jaccard_score = 1.0
            else:
                jaccard_score = intersection_size / union_size

            pairwise_scores.append(jaccard_score)

        jaccard_results.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Jaccard": np.mean(pairwise_scores),
            "Std_Jaccard": np.std(pairwise_scores, ddof=1),
            "Minimum_Jaccard": np.min(pairwise_scores),
            "Maximum_Jaccard": np.max(pairwise_scores)
        })

jaccard_df = pd.DataFrame(jaccard_results)

display(jaccard_df)

  Method  Top_K  Mean_Jaccard  Std_Jaccard  Minimum_Jaccard  Maximum_Jaccard
0  ANOVA      5      1.000000     0.000000         1.000000              1.0
1  ANOVA     10      0.972285     0.065364         0.818182              1.0
2  ANOVA     15      1.000000     0.000000         1.000000              1.0
3  ANOVA     20      1.000000     0.000000         1.000000              1.0
4   DODA      5      1.000000     0.000000         1.000000              1.0
5   DODA     10      0.985848     0.048721         0.818182              1.0
6   DODA     15      1.000000     0.000000         1.000000              1.0
7   DODA     20      1.000000     0.000000         1.000000              1.0

In [35]:
TOTAL_FEATURES = X.shape[1]

print("Total features:", TOTAL_FEATURES)

Total features: 21

In [36]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []

for method in stability_df["Method"].unique():

    for top_k in sorted(stability_df["Top_K"].unique()):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)

        feature_sets = subset["Feature_Set"].tolist()

        pairwise_scores = []

        for set_a, set_b in combinations(feature_sets, 2):

            k = len(set_a)
            r = len(set_a.intersection(set_b))
            n = TOTAL_FEATURES

            expected_overlap = (k * k) / n

            denominator = k - expected_overlap

            if denominator == 0:
                kuncheva_score = 1.0
            else:
                kuncheva_score = (
                    r - expected_overlap
                ) / denominator

            pairwise_scores.append(kuncheva_score)

        kuncheva_results.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Kuncheva": np.mean(pairwise_scores),
            "Std_Kuncheva": np.std(pairwise_scores, ddof=1),
            "Minimum_Kuncheva": np.min(pairwise_scores),
            "Maximum_Kuncheva": np.max(pairwise_scores)
        })

kuncheva_df = pd.DataFrame(kuncheva_results)

display(kuncheva_df)

,Method,Top_K,Mean_Kuncheva,Std_Kuncheva,Minimum_Kuncheva,Maximum_Kuncheva
0,ANOVA,5,1.000000,0.000000,1.000000,1.0
1,ANOVA,10,0.970899,0.068633,0.809091,1.0
2,ANOVA,15,1.000000,0.000000,1.000000,1.0
3,ANOVA,20,1.000000,0.000000,1.000000,1.0
4,DODA,5,1.000000,0.000000,1.000000,1.0
5,DODA,10,0.985140,0.051157,0.809091,1.0
6,DODA,15,1.000000,0.000000,1.000000,1.0
7,DODA,20,1.000000,0.000000,1.000000,1.0

In [37]:
# =============================================================================
# TEST 4: ANOVA VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for run in sorted(stability_df["Run"].unique()):

    for top_k in sorted(stability_df["Top_K"].unique()):

        anova_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "ANOVA") &
            (stability_df["Top_K"] == top_k)
        ]

        doda_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "DODA") &
            (stability_df["Top_K"] == top_k)
        ]

        if anova_rows.empty or doda_rows.empty:
            continue

        anova_set = anova_rows.iloc[0]["Feature_Set"]
        doda_set = doda_rows.iloc[0]["Feature_Set"]

        intersection_size = len(
            anova_set.intersection(doda_set)
        )

        union_size = len(
            anova_set.union(doda_set)
        )

        if union_size == 0:
            jaccard_agreement = 1.0
        else:
            jaccard_agreement = (
                intersection_size / union_size
            )

        agreement_results.append({
            "Run": run,
            "Top_K": top_k,
            "ANOVA_Features": ", ".join(sorted(anova_set)),
            "DODA_Features": ", ".join(sorted(doda_set)),
            "Common_Feature_Count": intersection_size,
            "ANOVA_Feature_Count": len(anova_set),
            "DODA_Feature_Count": len(doda_set),
            "Same_Feature_Set": anova_set == doda_set,
            "Jaccard_Agreement": jaccard_agreement
        })

agreement_df = pd.DataFrame(agreement_results)

display(agreement_df)

,Run,Top_K,ANOVA_Features,DODA_Features,Common_Feature_Count,ANOVA_Feature_Count,DODA_Feature_Count,Same_Feature_Set,Jaccard_Agreement
0,1,5,"BMI, DiffWalk, GenHlth, HighBP, HighChol","BMI, DiffWalk, GenHlth, HighBP, HighChol",5,5,5,True,1.000000
1,1,10,"Age, BMI, DiffWalk, Education, GenHlth, HeartD...","Age, BMI, DiffWalk, GenHlth, HeartDiseaseorAtt...",9,10,10,False,0.818182
2,1,15,"Age, BMI, CholCheck, DiffWalk, Education, GenH...","Age, BMI, CholCheck, DiffWalk, Education, GenH...",14,15,15,False,0.875000
3,1,20,"Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...","Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...",20,20,20,True,1.000000
4,2,5,"BMI, DiffWalk, GenHlth, HighBP, HighChol","BMI, DiffWalk, GenHlth, HighBP, HighChol",5,5,5,True,1.000000
...,...,...,...,...,...,...,...,...,...
95,24,20,"Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...","Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...",20,20,20,True,1.000000
96,25,5,"BMI, DiffWalk, GenHlth, HighBP, HighChol","BMI, DiffWalk, GenHlth, HighBP, HighChol",5,5,5,True,1.000000
97,25,10,"Age, BMI, DiffWalk, Education, GenHlth, HeartD...","Age, BMI, DiffWalk, GenHlth, HeartDiseaseorAtt...",9,10,10,False,0.818182
98,25,15,"Age, BMI, CholCheck, DiffWalk, Education, GenH...","Age, BMI, CholCheck, DiffWalk, Education, GenH...",14,15,15,False,0.875000
99,25,20,"Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...","Age, AnyHealthcare, BMI, CholCheck, DiffWalk, ...",20,20,20,True,1.000000

In [38]:
# =============================================================================
# SUMMARY OF ANOVA VS DODA AGREEMENT
# =============================================================================

agreement_summary_df = (
    agreement_df
    .groupby("Top_K")
    .agg(
        Same_Feature_Set_Percentage=(
            "Same_Feature_Set",
            lambda x: x.mean() * 100
        ),
        Mean_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "mean"
        ),
        Std_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "std"
        ),
        Mean_Common_Features=(
            "Common_Feature_Count",
            "mean"
        )
    )
    .reset_index()
)

display(agreement_summary_df)

,Top_K,Same_Feature_Set_Percentage,Mean_Jaccard_Agreement,Std_Jaccard_Agreement,Mean_Common_Features
0,5,100.0,1.000000,0.000000,5.00
1,10,4.0,0.825455,0.036364,9.04
2,15,0.0,0.875000,0.000000,14.00
3,20,100.0,1.000000,0.000000,20.00