In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../data/processed/breast_cancer_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 569
Columns : 31

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================


target_column = "target"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]



print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")

display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 569
Columns : 30

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 569

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================


print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

target
1    357
0    212
Name: count, dtype: int64

Class Percentage

target
1    62.74
0    37.26
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================


print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

                        Data Type
mean radius               float64
mean texture              float64
mean perimeter            float64
mean area                 float64
mean smoothness           float64
mean compactness          float64
mean concavity            float64
mean concave points       float64
mean symmetry             float64
mean fractal dimension    float64
radius error              float64
texture error             float64
perimeter error           float64
area error                float64
smoothness error          float64
compactness error         float64
concavity error           float64
concave points error      float64
symmetry error            float64
fractal dimension error   float64
worst radius              float64
worst texture             float64
worst perimeter           float64
worst area                float64
worst smoothness          float64
worst compactness         float64
worst concavity           float64
worst concave points      float64
worst symmetry            float64
worst fractal dimension   float64

In [5]:
# =============================================================================
# STEP 3: TRAIN-TEST SPLIT
# =============================================================================


from sklearn.model_selection import train_test_split


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (455, 30)
y_train shape : (455,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (114, 30)
y_test shape  : (114,)

In [6]:
# =============================================================================
# CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================


print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True)*100)
    .round(2)
)



print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True)*100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

target
1    62.64
0    37.36
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

target
1    63.16
0    36.84
Name: proportion, dtype: float64

In [7]:
# =============================================================================
# STEP 4: FEATURE SCALING
# =============================================================================


from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


# Initialize scaler
scaler = StandardScaler()


# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)


# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)



print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (455, 30)
X_test_scaled shape  : (114, 30)

In [8]:
# =============================================================================
# CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)



print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(X_train_scaled.head())

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,-1.072001,-0.658425,-1.088080,-0.939274,-0.135940,-1.008718,-0.968359,-1.102032,0.281062,-0.113231,...,-1.034094,-0.623497,-1.070773,-0.876534,-0.169982,-1.038836,-1.078995,-1.350527,-0.352658,-0.541380
1,1.748743,0.066502,1.751157,1.745559,1.274468,0.842288,1.519852,1.994664,-0.293045,-0.320180,...,1.228342,-0.092833,1.187467,1.104386,1.517001,0.249655,1.178594,1.549916,0.191078,-0.173739
2,-0.974734,-0.931124,-0.997709,-0.867589,-0.613515,-1.138154,-1.092292,-1.243358,0.434395,-0.429247,...,-0.973231,-1.036772,-1.008044,-0.834168,-1.097823,-1.167260,-1.282241,-1.707442,-0.307734,-1.213033
3,-0.145103,-1.215186,-0.123013,-0.253192,0.664482,0.286762,-0.129729,-0.098605,0.555635,0.029395,...,-0.251266,-1.369643,-0.166633,-0.330292,0.234006,0.096874,-0.087521,-0.344838,0.242198,-0.118266
4,-0.771617,-0.081211,-0.803700,-0.732927,-0.672282,-1.006099,-0.798502,-0.684484,0.737495,-0.457213,...,-0.801135,0.079230,-0.824381,-0.741830,-0.911367,-0.984612,-0.933190,-0.777604,0.555118,-0.761639

In [9]:
# =============================================================================
# SCALING VERIFICATION
# =============================================================================


print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.mean().round(2)
)



print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)

display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

mean radius               -0.0
mean texture               0.0
mean perimeter            -0.0
mean area                 -0.0
mean smoothness            0.0
mean compactness          -0.0
mean concavity            -0.0
mean concave points        0.0
mean symmetry             -0.0
mean fractal dimension     0.0
radius error              -0.0
texture error             -0.0
perimeter error            0.0
area error                 0.0
smoothness error          -0.0
compactness error         -0.0
concavity error            0.0
concave points error      -0.0
symmetry error             0.0
fractal dimension error    0.0
worst radius               0.0
worst texture             -0.0
worst perimeter           -0.0
worst area                 0.0
worst smoothness           0.0
worst compactness         -0.0
worst concavity            0.0
worst concave points      -0.0
worst symmetry            -0.0
worst fractal dimension    0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

mean radius                1.0
mean texture               1.0
mean perimeter             1.0
mean area                  1.0
mean smoothness            1.0
mean compactness           1.0
mean concavity             1.0
mean concave points        1.0
mean symmetry              1.0
mean fractal dimension     1.0
radius error               1.0
texture error              1.0
perimeter error            1.0
area error                 1.0
smoothness error           1.0
compactness error          1.0
concavity error            1.0
concave points error       1.0
symmetry error             1.0
fractal dimension error    1.0
worst radius               1.0
worst texture              1.0
worst perimeter            1.0
worst area                 1.0
worst smoothness           1.0
worst compactness          1.0
worst concavity            1.0
worst concave points       1.0
worst symmetry             1.0
worst fractal dimension    1.0
dtype: float64

# Random Forest

# 1. Baseline

In [10]:
# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION
# TOP-K = 5, 10, 15, 20
# =============================================================================

from sklearn.ensemble import RandomForestClassifier
import pandas as pd


# =============================================================================
# FIT RANDOM FOREST ON ALL TRAINING FEATURES
# =============================================================================

rf_selector = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


rf_selector.fit(
    X_train_scaled,
    y_train
)


# =============================================================================
# CREATE FEATURE IMPORTANCE DATAFRAME
# =============================================================================

rf_scores = pd.DataFrame({

    "Feature": X_train_scaled.columns,

    "RF Importance": rf_selector.feature_importances_

})


# =============================================================================
# SORT FEATURES BY IMPORTANCE
# =============================================================================

rf_scores = rf_scores.sort_values(
    by="RF Importance",
    ascending=False
).reset_index(drop=True)


# =============================================================================
# TOP-K VALUES
# =============================================================================

k_values = [5, 10, 15, 20]

rf_results = {}


# =============================================================================
# SELECT TOP-K FEATURES
# =============================================================================

for k in k_values:

    top_features = (
        rf_scores
        .head(k)["Feature"]
        .tolist()
    )


    # -------------------------------------------------------------------------
    # Boolean mask for selecting columns
    # -------------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # -------------------------------------------------------------------------
    # Store results
    # -------------------------------------------------------------------------

    rf_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": rf_scores.head(k)

    }


    # -------------------------------------------------------------------------
    # Display results
    # -------------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} RANDOM FOREST FEATURES")
    print("=" * 70)

    print("\nSelected Features:")
    print(top_features)

    print("\nFeature Importance:")
    print(rf_scores.head(k))


# =============================================================================
# RANDOM FOREST BASELINE FEATURE SELECTION COMPLETED
# =============================================================================

======================================================================
TOP 5 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius']

Feature Importance:
                Feature  RF Importance
0            worst area       0.137862
1  worst concave points       0.131157
2   mean concave points       0.116819
3       worst perimeter       0.081788
4          worst radius       0.076800
======================================================================
TOP 10 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius']

Feature Importance:
                Feature  RF Importance
0            worst area       0.137862
1  worst concave points       0.131157
2   mean concave points       0.116819
3       worst perimeter       0.081788
4          worst radius       0.076800
5        mean concavity       0.068669
6        mean perimeter       0.065251
7             mean area       0.040521
8       worst concavity       0.040485
9           mean radius       0.037879
======================================================================
TOP 15 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness']

Feature Importance:
                 Feature  RF Importance
0             worst area       0.137862
1   worst concave points       0.131157
2    mean concave points       0.116819
3        worst perimeter       0.081788
4           worst radius       0.076800
5         mean concavity       0.068669
6         mean perimeter       0.065251
7              mean area       0.040521
8        worst concavity       0.040485
9            mean radius       0.037879
10            area error       0.035366
11         worst texture       0.021991
12          radius error       0.016400
13     worst compactness       0.016229
14      mean compactness       0.012885
======================================================================
TOP 20 RANDOM FOREST FEATURES
======================================================================

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness', 'mean texture', 'worst symmetry', 'worst smoothness', 'perimeter error', 'compactness error']

Feature Importance:
                 Feature  RF Importance
0             worst area       0.137862
1   worst concave points       0.131157
2    mean concave points       0.116819
3        worst perimeter       0.081788
4           worst radius       0.076800
5         mean concavity       0.068669
6         mean perimeter       0.065251
7              mean area       0.040521
8        worst concavity       0.040485
9            mean radius       0.037879
10            area error       0.035366
11         worst texture       0.021991
12          radius error       0.016400
13     worst compactness       0.016229
14      mean compactness       0.012885
15          mean texture       0.011584
16        worst symmetry       0.011540
17      worst smoothness       0.009623
18       perimeter error       0.009303
19     compactness error       0.008174

In [11]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [12]:
# =============================================================================
# RANDOM FOREST FEATURE SELECTION — MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_model_results = []


for k in k_values:

    Xtr = rf_results[k]["X_train"]

    Xts = rf_results[k]["X_test"]

    features = ", ".join(
        rf_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_model_results.append({

            "Method": "Random Forest",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_results_df = pd.DataFrame(
    rf_model_results
)


display(rf_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.985075,0.916667,0.949640,0.990741
1,Random Forest,5,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.971014,0.930556,0.950355,0.986772
2,Random Forest,5,XGBoost,"worst area, worst concave points, mean concave...",0.921053,0.943662,0.930556,0.937063,0.982474
3,Random Forest,10,Logistic Regression,"worst area, worst concave points, mean concave...",0.912281,0.969697,0.888889,0.927536,0.991402
4,Random Forest,10,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.990079
5,Random Forest,10,XGBoost,"worst area, worst concave points, mean concave...",0.973684,0.972603,0.986111,0.979310,0.992394
6,Random Forest,15,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.994048
7,Random Forest,15,Random Forest,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.992725
8,Random Forest,15,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.995040
9,Random Forest,20,Logistic Regression,"worst area, worst concave points, mean concave...",0.956140,0.985507,0.944444,0.964539,0.995701
10,Random Forest,20,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.993221
11,Random Forest,20,XGBoost,"worst area, worst concave points, mean concave...",0.956140,0.946667,0.986111,0.965986,0.994048

In [13]:
rf_results_df.to_csv(
    "../../../results/breast_cancer/baseline_results/rf_baseline_results.csv",
    index=False
)

## 2. DODA

In [14]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--upgrade",
    "--force-reinstall",
    "--no-cache-dir",
    "git+https://github.com/anandha-3679/DODA.git"
])

0

In [15]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\johnm\msc_research\.venv\Scripts\python.exe
DODA: c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\__init__.py
Selector: c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\selector.py

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import HadamardFusion

In [17]:
# =============================================================================
# RANDOM FOREST + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 10, 15, 20]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "../../../config/clinical_weights/breast_cancer.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = HadamardFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

rf_doda_results = {}


# =============================================================================
# RUN DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"RANDOM FOREST + DODA \u2014 TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest operator
    # ---------------------------------------------------------------------

    rf = SklearnAdapter(
        RandomForestClassifier(
            n_estimators=100,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        )
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[rf],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    rf_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores": selector.raw_math_scores_,

        "math_scores": selector.math_scores_,

        "clinical_weights": selector.clinical_weights_,

        "final_scores": selector.final_scores_
    }


print("\n" + "=" * 70)
print("RANDOM FOREST + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
RANDOM FOREST + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410914D2B0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.037878571075900605), 'mean texture': np.float64(0.011584227153273762), 'mean perimeter': np.float64(0.06525109582346444), 'mean area': np.float64(0.04052144874956467), 'mean smoothness': np.float64(0.007004956117366906), 'mean compactness': np.float64(0.012885022993264956), 'mean concavity': np.float64(0.06866896338978329), 'mean concave points': np.float64(0.1168193189507702), 'mean symmetry': np.float64(0.003998715308884734), 'mean fractal dimension': np.float64(0.003287087239608105), 'radius error': np.float64(0.016400086046875748), 'texture error': np.float64(0.00653017754723641), 'perimeter error': np.float64(0.009302648630012407), 'area error': np.float64(0.035366085258647845), 'smoothness error': np.float64(0.006037171374074463), 'compactness error': np.float64(0.0081736570964226), 'concavity error': np.float64(0.0033125790585614868), 'concave points error': np.float64(0.0036972707689099517), 'symmetry error': np.float64(0.003635883983164279), 'fractal dimension error': np.float64(0.005003147909418703), 'worst radius': np.float64(0.07679957589977142), 'worst texture': np.float64(0.02199104195301148), 'worst perimeter': np.float64(0.08178762473196294), 'worst area': np.float64(0.1378618304225077), 'worst smoothness': np.float64(0.009623200215453646), 'worst compactness': np.float64(0.016228954964113487), 'worst concavity': np.float64(0.040485194182530465), 'worst concave points': np.float64(0.13115706795265292), 'worst symmetry': np.float64(0.01154049911343507), 'worst fractal dimension': np.float64(0.007166896089355457)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.037878571075900605), 'mean texture': np.float64(0.011584227153273762), 'mean perimeter': np.float64(0.06525109582346444), 'mean area': np.float64(0.04052144874956467), 'mean smoothness': np.float64(0.007004956117366906), 'mean compactness': np.float64(0.012885022993264956), 'mean concavity': np.float64(0.06866896338978329), 'mean concave points': np.float64(0.1168193189507702), 'mean symmetry': np.float64(0.003998715308884734), 'mean fractal dimension': np.float64(0.003287087239608105), 'radius error': np.float64(0.016400086046875748), 'texture error': np.float64(0.00653017754723641), 'perimeter error': np.float64(0.009302648630012407), 'area error': np.float64(0.035366085258647845), 'smoothness error': np.float64(0.006037171374074463), 'compactness error': np.float64(0.0081736570964226), 'concavity error': np.float64(0.0033125790585614868), 'concave points error': np.float64(0.0036972707689099517), 'symmetry error': np.float64(0.003635883983164279), 'fractal dimension error': np.float64(0.005003147909418703), 'worst radius': np.float64(0.07679957589977142), 'worst texture': np.float64(0.02199104195301148), 'worst perimeter': np.float64(0.08178762473196294), 'worst area': np.float64(0.1378618304225077), 'worst smoothness': np.float64(0.009623200215453646), 'worst compactness': np.float64(0.016228954964113487), 'worst concavity': np.float64(0.040485194182530465), 'worst concave points': np.float64(0.13115706795265292), 'worst symmetry': np.float64(0.01154049911343507), 'worst fractal dimension': np.float64(0.007166896089355457)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.27475749422311785), 'mean texture': np.float64(0.084027806085059), 'mean perimeter': np.float64(0.4733079172348736), 'mean area': np.float64(0.29392797575208335), 'mean smoothness': np.float64(0.05081142543877945), 'mean compactness': np.float64(0.09346330999505802), 'mean concavity': np.float64(0.4980998959562067), 'mean concave points': np.float64(0.8473652104629098), 'mean symmetry': np.float64(0.029005238771527966), 'mean fractal dimension': np.float64(0.02384334539541589), 'radius error': np.float64(0.11896030972905337), 'texture error': np.float64(0.047367552913110574), 'perimeter error': np.float64(0.06747805829577636), 'area error': np.float64(0.2565328281966136), 'smoothness error': np.float64(0.043791463928574234), 'compactness error': np.float64(0.05928876086566269), 'concavity error': np.float64(0.024028253856846125), 'concave points error': np.float64(0.02681866879018549), 'symmetry error': np.float64(0.02637339118464711), 'fractal dimension error': np.float64(0.036291030621640984), 'worst radius': np.float64(0.5570764269152843), 'worst texture': np.float64(0.15951508757438612), 'worst perimeter': np.float64(0.5932579342759842), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.06980322389425157), 'worst compactness': np.float64(0.11771898657065781), 'worst concavity': np.float64(0.293664998197505), 'worst concave points': np.float64(0.9513660710197553), 'worst symmetry': np.float64(0.08371061865395729), 'worst fractal dimension': np.float64(0.05198607959426434)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.24728174480080606), 'mean texture': np.float64(0.0420139030425295), 'mean perimeter': np.float64(0.4259771255113862), 'mean area': np.float64(0.264535178176875), 'mean smoothness': np.float64(0.020324570175511782), 'mean compactness': np.float64(0.06542431699654061), 'mean concavity': np.float64(0.448289906360586), 'mean concave points': np.float64(0.7626286894166189), 'mean symmetry': np.float64(0.014502619385763983), 'mean fractal dimension': np.float64(0.007153003618624767), 'radius error': np.float64(0.05948015486452669), 'texture error': np.float64(0.014210265873933172), 'perimeter error': np.float64(0.03373902914788818), 'area error': np.float64(0.1282664140983068), 'smoothness error': np.float64(0.008758292785714846), 'compactness error': np.float64(0.017786628259698806), 'concavity error': np.float64(0.00961130154273845), 'concave points error': np.float64(0.010727467516074196), 'symmetry error': np.float64(0.007912017355394133), 'fractal dimension error': np.float64(0.007258206124328197), 'worst radius': np.float64(0.5570764269152843), 'worst texture': np.float64(0.09570905254463168), 'worst perimeter': np.float64(0.5932579342759842), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.03490161194712579), 'worst compactness': np.float64(0.09417518925652625), 'worst concavity': np.float64(0.293664998197505), 'worst concave points': np.float64(0.9513660710197553), 'worst symmetry': np.float64(0.05022637119237437), 'worst fractal dimension': np.float64(0.0155958238782793)}
Top 5 Features Selected: ['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius']

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius']

======================================================================
RANDOM FOREST + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410914D2B0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.037878571075900605), 'mean texture': np.float64(0.011584227153273762), 'mean perimeter': np.float64(0.06525109582346444), 'mean area': np.float64(0.04052144874956467), 'mean smoothness': np.float64(0.007004956117366906), 'mean compactness': np.float64(0.012885022993264956), 'mean concavity': np.float64(0.06866896338978329), 'mean concave points': np.float64(0.1168193189507702), 'mean symmetry': np.float64(0.003998715308884734), 'mean fractal dimension': np.float64(0.003287087239608105), 'radius error': np.float64(0.016400086046875748), 'texture error': np.float64(0.00653017754723641), 'perimeter error': np.float64(0.009302648630012407), 'area error': np.float64(0.035366085258647845), 'smoothness error': np.float64(0.006037171374074463), 'compactness error': np.float64(0.0081736570964226), 'concavity error': np.float64(0.0033125790585614868), 'concave points error': np.float64(0.0036972707689099517), 'symmetry error': np.float64(0.003635883983164279), 'fractal dimension error': np.float64(0.005003147909418703), 'worst radius': np.float64(0.07679957589977142), 'worst texture': np.float64(0.02199104195301148), 'worst perimeter': np.float64(0.08178762473196294), 'worst area': np.float64(0.1378618304225077), 'worst smoothness': np.float64(0.009623200215453646), 'worst compactness': np.float64(0.016228954964113487), 'worst concavity': np.float64(0.040485194182530465), 'worst concave points': np.float64(0.13115706795265292), 'worst symmetry': np.float64(0.01154049911343507), 'worst fractal dimension': np.float64(0.007166896089355457)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.037878571075900605), 'mean texture': np.float64(0.011584227153273762), 'mean perimeter': np.float64(0.06525109582346444), 'mean area': np.float64(0.04052144874956467), 'mean smoothness': np.float64(0.007004956117366906), 'mean compactness': np.float64(0.012885022993264956), 'mean concavity': np.float64(0.06866896338978329), 'mean concave points': np.float64(0.1168193189507702), 'mean symmetry': np.float64(0.003998715308884734), 'mean fractal dimension': np.float64(0.003287087239608105), 'radius error': np.float64(0.016400086046875748), 'texture error': np.float64(0.00653017754723641), 'perimeter error': np.float64(0.009302648630012407), 'area error': np.float64(0.035366085258647845), 'smoothness error': np.float64(0.006037171374074463), 'compactness error': np.float64(0.0081736570964226), 'concavity error': np.float64(0.0033125790585614868), 'concave points error': np.float64(0.0036972707689099517), 'symmetry error': np.float64(0.003635883983164279), 'fractal dimension error': np.float64(0.005003147909418703), 'worst radius': np.float64(0.07679957589977142), 'worst texture': np.float64(0.02199104195301148), 'worst perimeter': np.float64(0.08178762473196294), 'worst area': np.float64(0.1378618304225077), 'worst smoothness': np.float64(0.009623200215453646), 'worst compactness': np.float64(0.016228954964113487), 'worst concavity': np.float64(0.040485194182530465), 'worst concave points': np.float64(0.13115706795265292), 'worst symmetry': np.float64(0.01154049911343507), 'worst fractal dimension': np.float64(0.007166896089355457)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.27475749422311785), 'mean texture': np.float64(0.084027806085059), 'mean perimeter': np.float64(0.4733079172348736), 'mean area': np.float64(0.29392797575208335), 'mean smoothness': np.float64(0.05081142543877945), 'mean compactness': np.float64(0.09346330999505802), 'mean concavity': np.float64(0.4980998959562067), 'mean concave points': np.float64(0.8473652104629098), 'mean symmetry': np.float64(0.029005238771527966), 'mean fractal dimension': np.float64(0.02384334539541589), 'radius error': np.float64(0.11896030972905337), 'texture error': np.float64(0.047367552913110574), 'perimeter error': np.float64(0.06747805829577636), 'area error': np.float64(0.2565328281966136), 'smoothness error': np.float64(0.043791463928574234), 'compactness error': np.float64(0.05928876086566269), 'concavity error': np.float64(0.024028253856846125), 'concave points error': np.float64(0.02681866879018549), 'symmetry error': np.float64(0.02637339118464711), 'fractal dimension error': np.float64(0.036291030621640984), 'worst radius': np.float64(0.5570764269152843), 'worst texture': np.float64(0.15951508757438612), 'worst perimeter': np.float64(0.5932579342759842), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.06980322389425157), 'worst compactness': np.float64(0.11771898657065781), 'worst concavity': np.float64(0.293664998197505), 'worst concave points': np.float64(0.9513660710197553), 'worst symmetry': np.float64(0.08371061865395729), 'worst fractal dimension': np.float64(0.05198607959426434)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.24728174480080606), 'mean texture': np.float64(0.0420139030425295), 'mean perimeter': np.float64(0.4259771255113862), 'mean area': np.float64(0.264535178176875), 'mean smoothness': np.float64(0.020324570175511782), 'mean compactness': np.float64(0.06542431699654061), 'mean concavity': np.float64(0.448289906360586), 'mean concave points': np.float64(0.7626286894166189), 'mean symmetry': np.float64(0.014502619385763983), 'mean fractal dimension': np.float64(0.007153003618624767), 'radius error': np.float64(0.05948015486452669), 'texture error': np.float64(0.014210265873933172), 'perimeter error': np.float64(0.03373902914788818), 'area error': np.float64(0.1282664140983068), 'smoothness error': np.float64(0.008758292785714846), 'compactness error': np.float64(0.017786628259698806), 'concavity error': np.float64(0.00961130154273845), 'concave points error': np.float64(0.010727467516074196), 'symmetry error': np.float64(0.007912017355394133), 'fractal dimension error': np.float64(0.007258206124328197), 'worst radius': np.float64(0.5570764269152843), 'worst texture': np.float64(0.09570905254463168), 'worst perimeter': np.float64(0.5932579342759842), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.03490161194712579), 'worst compactness': np.float64(0.09417518925652625), 'worst concavity': np.float64(0.293664998197505), 'worst concave points': np.float64(0.9513660710197553), 'worst symmetry': np.float64(0.05022637119237437), 'worst fractal dimension': np.float64(0.0155958238782793)}
Top 10 Features Selected: ['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius']

Selected Features:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius']

======================================================================
RANDOM FOREST + DODA — TOP 15 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410914D2B0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.037878571075900605), 'mean texture': np.float64(0.011584227153273762), 'mean perimeter': np.float64(0.06525109582346444), 'mean area': np.float64(0.04052144874956467), 'mean smoothness': np.float64(0.007004956117366906), 'mean compactness': np.float64(0.012885022993264956), 'mean concavity': np.float64(0.06866896338978329), 'mean concave points': np.float64(0.1168193189507702), 'mean symmetry': np.float64(0.003998715308884734), 'mean fractal dimension': np.float64(0.003287087239608105), 'radius error': np.float64(0.016400086046875748), 'texture error': np.float64(0.00653017754723641), 'perimeter error': np.float64(0.009302648630012407), 'area error': np.float64(0.035366085258647845), 'smoothness error': np.float64(0.006037171374074463), 'compactness error': np.float64(0.0081736570964226), 'concavity error': np.float64(0.0033125790585614868), 'concave points error': np.float64(0.0036972707689099517), 'symmetry error': np.float64(0.003635883983164279), 'fractal dimension error': np.float64(0.005003147909418703), 'worst radius': np.float64(0.07679957589977142), 'worst texture': np.float64(0.02199104195301148), 'worst perimeter': np.float64(0.08178762473196294), 'worst area': np.float64(0.1378618304225077), 'worst smoothness': np.float64(0.009623200215453646), 'worst compactness': np.float64(0.016228954964113487), 'worst concavity': np.float64(0.040485194182530465), 'worst concave points': np.float64(0.13115706795265292), 'worst symmetry': np.float64(0.01154049911343507), 'worst fractal dimension': np.float64(0.007166896089355457)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

In [18]:
# CELL 2
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = rf_doda_results[k]["selector"]

# -----------------------------------------------------------------------------
# Raw mathematical scores
# -----------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Normalized mathematical scores
# -----------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)

# -----------------------------------------------------------------------------
# Combine both
# -----------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)

math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)

print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

                    Feature  Raw Math Score  Normalized Math Score
23               worst area        0.137862               1.000000
27     worst concave points        0.131157               0.951366
7       mean concave points        0.116819               0.847365
22          worst perimeter        0.081788               0.593258
20             worst radius        0.076800               0.557076
6            mean concavity        0.068669               0.498100
2            mean perimeter        0.065251               0.473308
3                 mean area        0.040521               0.293928
26          worst concavity        0.040485               0.293665
0               mean radius        0.037879               0.274757
13               area error        0.035366               0.256533
21            worst texture        0.021991               0.159515
10             radius error        0.016400               0.118960
25        worst compactness        0.016229               0.117719
5          mean compactness        0.012885               0.093463
1              mean texture        0.011584               0.084028
28           worst symmetry        0.011540               0.083711
24         worst smoothness        0.009623               0.069803
12          perimeter error        0.009303               0.067478
15        compactness error        0.008174               0.059289
29  worst fractal dimension        0.007167               0.051986
4           mean smoothness        0.007005               0.050811
11            texture error        0.006530               0.047368
14         smoothness error        0.006037               0.043791
19  fractal dimension error        0.005003               0.036291
8             mean symmetry        0.003999               0.029005
17     concave points error        0.003697               0.026819
18           symmetry error        0.003636               0.026373
16          concavity error        0.003313               0.024028
9    mean fractal dimension        0.003287               0.023843

In [19]:
# CELL 3
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)

clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)

print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

                    Feature  Clinical Weight
27     worst concave points              1.0
26          worst concavity              1.0
22          worst perimeter              1.0
23               worst area              1.0
20             worst radius              1.0
0               mean radius              0.9
3                 mean area              0.9
6            mean concavity              0.9
7       mean concave points              0.9
2            mean perimeter              0.9
25        worst compactness              0.8
5          mean compactness              0.7
21            worst texture              0.6
28           worst symmetry              0.6
24         worst smoothness              0.5
8             mean symmetry              0.5
1              mean texture              0.5
12          perimeter error              0.5
10             radius error              0.5
13               area error              0.5
4           mean smoothness              0.4
17     concave points error              0.4
16          concavity error              0.4
9    mean fractal dimension              0.3
11            texture error              0.3
18           symmetry error              0.3
15        compactness error              0.3
29  worst fractal dimension              0.3
19  fractal dimension error              0.2
14         smoothness error              0.2

In [20]:
# CELL 4
# =============================================================================
# INSPECT FINAL DODA SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final DODA Score"
    ]
)

final_scores = final_scores.sort_values(
    by="Final DODA Score",
    ascending=False
)

print("=" * 70)
print("FINAL DODA SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL DODA SCORES
======================================================================

                    Feature  Final DODA Score
23               worst area          1.000000
27     worst concave points          0.951366
7       mean concave points          0.762629
22          worst perimeter          0.593258
20             worst radius          0.557076
6            mean concavity          0.448290
2            mean perimeter          0.425977
26          worst concavity          0.293665
3                 mean area          0.264535
0               mean radius          0.247282
13               area error          0.128266
21            worst texture          0.095709
25        worst compactness          0.094175
5          mean compactness          0.065424
10             radius error          0.059480
28           worst symmetry          0.050226
1              mean texture          0.042014
24         worst smoothness          0.034902
12          perimeter error          0.033739
4           mean smoothness          0.020325
15        compactness error          0.017787
29  worst fractal dimension          0.015596
8             mean symmetry          0.014503
11            texture error          0.014210
17     concave points error          0.010727
16          concavity error          0.009611
14         smoothness error          0.008758
18           symmetry error          0.007912
19  fractal dimension error          0.007258
9    mean fractal dimension          0.007153

In [21]:
selector.get_selected_features()

['worst area',
 'worst concave points',
 'mean concave points',
 'worst perimeter',
 'worst radius',
 'mean concavity',
 'mean perimeter',
 'worst concavity',
 'mean area',
 'mean radius']

In [22]:
comparison = selector.compare_scores()

comparison

======================================================================
MATHEMATICAL vs CLINICAL vs HADAMARDFUSION
======================================================================

Fusion Method: HadamardFusion

Top Features After Fusion:
                Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0            worst area          1              3           1            0
1  worst concave points          2              5           2            0
2   mean concave points          3             10           3            0
3       worst perimeter          4              2           4            0
4          worst radius          5              1           5            0
5        mean concavity          6              9           6            0
6        mean perimeter          7              7           7            0
7       worst concavity          9              4           8            1
8             mean area          8              8           9           -1
9           mean radius         10              6          10            0

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,worst area,1,1.0000,3,1.0,1,1.0000,0
1,worst concave points,2,0.9514,5,1.0,2,0.9514,0
2,mean concave points,3,0.8474,10,0.9,3,0.7626,0
3,worst perimeter,4,0.5933,2,1.0,4,0.5933,0
4,worst radius,5,0.5571,1,1.0,5,0.5571,0
5,mean concavity,6,0.4981,9,0.9,6,0.4483,0
6,mean perimeter,7,0.4733,7,0.9,7,0.4260,0
7,worst concavity,9,0.2937,4,1.0,8,0.2937,1
8,mean area,8,0.2939,8,0.9,9,0.2645,-1
9,mean radius,10,0.2748,6,0.9,10,0.2473,0
10,area error,11,0.2565,19,0.5,11,0.1283,0
11,worst texture,12,0.1595,13,0.6,12,0.0957,0
12,worst compactness,14,0.1177,11,0.8,13,0.0942,1
13,mean compactness,15,0.0935,12,0.7,14,0.0654,1
14,radius error,13,0.1190,17,0.5,15,0.0595,-2
15,worst symmetry,17,0.0837,14,0.6,16,0.0502,1
16,mean texture,16,0.0840,15,0.5,17,0.0420,-1
17,worst smoothness,18,0.0698,20,0.5,18,0.0349,0
18,perimeter error,19,0.0675,18,0.5,19,0.0337,0
19,mean smoothness,22,0.0508,21,0.4,20,0.0203,2
20,compactness error,20,0.0593,26,0.3,21,0.0178,-1
21,worst fractal dimension,21,0.0520,28,0.3,22,0.0156,-1
22,mean symmetry,26,0.0290,16,0.5,23,0.0145,3
23,texture error,23,0.0474,25,0.3,24,0.0142,-1
24,concave points error,27,0.0268,23,0.4,25,0.0107,2
25,concavity error,29,0.0240,22,0.4,26,0.0096,3
26,smoothness error,24,0.0438,29,0.2,27,0.0088,-3
27,symmetry error,28,0.0264,27,0.3,28,0.0079,0
28,fractal dimension error,25,0.0363,30,0.2,29,0.0073,-4
29,mean fractal dimension,30,0.0238,24,0.3,30,0.0072,0

In [23]:
# =============================================================================
# RANDOM FOREST + DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rf_doda_model_results = []


for k in k_values:

    Xtr = rf_doda_results[k]["X_train"]

    Xts = rf_doda_results[k]["X_test"]

    features = ", ".join(
        rf_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rf_doda_model_results.append({

            "Method": "RF + DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


rf_doda_results_df = pd.DataFrame(
    rf_doda_model_results
)


display(rf_doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,RF + DODA,5,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.985075,0.916667,0.949640,0.990741
1,RF + DODA,5,Random Forest,"worst area, worst concave points, mean concave...",0.929825,0.957143,0.930556,0.943662,0.986111
2,RF + DODA,5,XGBoost,"worst area, worst concave points, mean concave...",0.921053,0.943662,0.930556,0.937063,0.982474
3,RF + DODA,10,Logistic Regression,"worst area, worst concave points, mean concave...",0.912281,0.969697,0.888889,0.927536,0.991402
4,RF + DODA,10,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.989087
5,RF + DODA,10,XGBoost,"worst area, worst concave points, mean concave...",0.964912,0.959459,0.986111,0.972603,0.991071
6,RF + DODA,15,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.994048
7,RF + DODA,15,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.994048
8,RF + DODA,15,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.994378
9,RF + DODA,20,Logistic Regression,"worst area, worst concave points, mean concave...",0.956140,0.985507,0.944444,0.964539,0.994378
10,RF + DODA,20,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.971014,0.930556,0.950355,0.994709
11,RF + DODA,20,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.945946,0.972222,0.958904,0.996693

In [24]:
rf_doda_results_df.to_csv(
    "../../../results/breast_cancer/doda_results/rf_doda_results.csv",
    index=False
)

In [25]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================

comparison_df = pd.concat(
    [
        rf_results_df,
        rf_doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Random Forest,5,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.985075,0.916667,0.949640,0.990741
1,Random Forest,5,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.971014,0.930556,0.950355,0.986772
2,Random Forest,5,XGBoost,"worst area, worst concave points, mean concave...",0.921053,0.943662,0.930556,0.937063,0.982474
3,Random Forest,10,Logistic Regression,"worst area, worst concave points, mean concave...",0.912281,0.969697,0.888889,0.927536,0.991402
4,Random Forest,10,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.990079
5,Random Forest,10,XGBoost,"worst area, worst concave points, mean concave...",0.973684,0.972603,0.986111,0.979310,0.992394
6,Random Forest,15,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.994048
7,Random Forest,15,Random Forest,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.992725
8,Random Forest,15,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.995040
9,Random Forest,20,Logistic Regression,"worst area, worst concave points, mean concave...",0.956140,0.985507,0.944444,0.964539,0.995701
10,Random Forest,20,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.993221
11,Random Forest,20,XGBoost,"worst area, worst concave points, mean concave...",0.956140,0.946667,0.986111,0.965986,0.994048
12,RF + DODA,5,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.985075,0.916667,0.949640,0.990741
13,RF + DODA,5,Random Forest,"worst area, worst concave points, mean concave...",0.929825,0.957143,0.930556,0.943662,0.986111
14,RF + DODA,5,XGBoost,"worst area, worst concave points, mean concave...",0.921053,0.943662,0.930556,0.937063,0.982474
15,RF + DODA,10,Logistic Regression,"worst area, worst concave points, mean concave...",0.912281,0.969697,0.888889,0.927536,0.991402
16,RF + DODA,10,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.989087
17,RF + DODA,10,XGBoost,"worst area, worst concave points, mean concave...",0.964912,0.959459,0.986111,0.972603,0.991071
18,RF + DODA,15,Logistic Regression,"worst area, worst concave points, mean concave...",0.938596,0.957746,0.944444,0.951049,0.994048
19,RF + DODA,15,Random Forest,"worst area, worst concave points, mean concave...",0.956140,0.958904,0.972222,0.965517,0.994048
20,RF + DODA,15,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.958333,0.958333,0.958333,0.994378
21,RF + DODA,20,Logistic Regression,"worst area, worst concave points, mean concave...",0.956140,0.985507,0.944444,0.964539,0.994378
22,RF + DODA,20,Random Forest,"worst area, worst concave points, mean concave...",0.938596,0.971014,0.930556,0.950355,0.994709
23,RF + DODA,20,XGBoost,"worst area, worst concave points, mean concave...",0.947368,0.945946,0.972222,0.958904,0.996693

In [26]:
for k in k_values:

    selector = rf_doda_results[k]["selector"]

    raw_rank = [
        x[0]
        for x in sorted(
            selector.raw_math_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    doda_rank = [
        x[0]
        for x in sorted(
            selector.final_scores_.items(),
            key=lambda x: x[1],
            reverse=True
        )
    ]

    print("\n" + "=" * 70)
    print(f"TOP {k}")
    print("=" * 70)

    print("Raw Math Ranking:")
    print(raw_rank)

    print("\nDODA Ranking:")
    print(doda_rank)

    print("\nTop-K Same:",
          raw_rank[:k] == doda_rank[:k])

======================================================================
TOP 5
======================================================================
Raw Math Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness', 'mean texture', 'worst symmetry', 'worst smoothness', 'perimeter error', 'compactness error', 'worst fractal dimension', 'mean smoothness', 'texture error', 'smoothness error', 'fractal dimension error', 'mean symmetry', 'concave points error', 'symmetry error', 'concavity error', 'mean fractal dimension']

DODA Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius', 'area error', 'worst texture', 'worst compactness', 'mean compactness', 'radius error', 'worst symmetry', 'mean texture', 'worst smoothness', 'perimeter error', 'mean smoothness', 'compactness error', 'worst fractal dimension', 'mean symmetry', 'texture error', 'concave points error', 'concavity error', 'smoothness error', 'symmetry error', 'fractal dimension error', 'mean fractal dimension']

Top-K Same: True

======================================================================
TOP 10
======================================================================
Raw Math Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness', 'mean texture', 'worst symmetry', 'worst smoothness', 'perimeter error', 'compactness error', 'worst fractal dimension', 'mean smoothness', 'texture error', 'smoothness error', 'fractal dimension error', 'mean symmetry', 'concave points error', 'symmetry error', 'concavity error', 'mean fractal dimension']

DODA Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius', 'area error', 'worst texture', 'worst compactness', 'mean compactness', 'radius error', 'worst symmetry', 'mean texture', 'worst smoothness', 'perimeter error', 'mean smoothness', 'compactness error', 'worst fractal dimension', 'mean symmetry', 'texture error', 'concave points error', 'concavity error', 'smoothness error', 'symmetry error', 'fractal dimension error', 'mean fractal dimension']

Top-K Same: False

======================================================================
TOP 15
======================================================================
Raw Math Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness', 'mean texture', 'worst symmetry', 'worst smoothness', 'perimeter error', 'compactness error', 'worst fractal dimension', 'mean smoothness', 'texture error', 'smoothness error', 'fractal dimension error', 'mean symmetry', 'concave points error', 'symmetry error', 'concavity error', 'mean fractal dimension']

DODA Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius', 'area error', 'worst texture', 'worst compactness', 'mean compactness', 'radius error', 'worst symmetry', 'mean texture', 'worst smoothness', 'perimeter error', 'mean smoothness', 'compactness error', 'worst fractal dimension', 'mean symmetry', 'texture error', 'concave points error', 'concavity error', 'smoothness error', 'symmetry error', 'fractal dimension error', 'mean fractal dimension']

Top-K Same: False

======================================================================
TOP 20
======================================================================
Raw Math Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'mean area', 'worst concavity', 'mean radius', 'area error', 'worst texture', 'radius error', 'worst compactness', 'mean compactness', 'mean texture', 'worst symmetry', 'worst smoothness', 'perimeter error', 'compactness error', 'worst fractal dimension', 'mean smoothness', 'texture error', 'smoothness error', 'fractal dimension error', 'mean symmetry', 'concave points error', 'symmetry error', 'concavity error', 'mean fractal dimension']

DODA Ranking:
['worst area', 'worst concave points', 'mean concave points', 'worst perimeter', 'worst radius', 'mean concavity', 'mean perimeter', 'worst concavity', 'mean area', 'mean radius', 'area error', 'worst texture', 'worst compactness', 'mean compactness', 'radius error', 'worst symmetry', 'mean texture', 'worst smoothness', 'perimeter error', 'mean smoothness', 'compactness error', 'worst fractal dimension', 'mean symmetry', 'texture error', 'concave points error', 'concavity error', 'smoothness error', 'symmetry error', 'fractal dimension error', 'mean fractal dimension']

Top-K Same: False

In [27]:
# =============================================================================
# STEP 21: CROSS-VALIDATION CONFIGURATION
# =============================================================================
# Random Forest vs Random Forest + DODA
#
# The fixed-split experiment above is retained unchanged.
# This section adds fold-wise and repeated-CV validation.
#
# Random Forest feature importance is refit inside every training fold.
# Scaling is also fitted separately inside every CV training fold to prevent
# data leakage.
#
# DODA continues to use the existing Hadamard fusion method exactly as
# defined in the fixed-split experiment.

import os
import numpy as np
import pandas as pd

from itertools import combinations

from sklearn.model_selection import (
    StratifiedKFold,
    RepeatedStratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters import SklearnAdapter
from doda.knowledge.providers import JSONProvider
from doda.fusion import HadamardFusion


# -------------------------------------------------------------------------
# Research design
# -------------------------------------------------------------------------

TOP_K_VALUES = [5, 10, 15, 20]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "../../../config/clinical_weights/breast_cancer.json"

print("=" * 80)
print("BREAST CANCER RANDOM FOREST CROSS-VALIDATION CONFIGURATION")
print("=" * 80)

print("Top-K values:", TOP_K_VALUES)
print("5-fold CV:", N_SPLITS)
print(
    "Repeated CV:",
    f"{N_SPLITS} folds × {N_REPEATS} repeats"
)
print(
    "Total repeated runs:",
    N_SPLITS * N_REPEATS
)
print("Random state:", RANDOM_STATE)
print("Clinical weights:", WEIGHTS_FILE)


# -------------------------------------------------------------------------
# Random Forest + DODA factory
# -------------------------------------------------------------------------

def make_doda_rf(top_k):
    """Create a fresh Random Forest + DODA selector using Hadamard fusion."""

    rf_operator = SklearnAdapter(
        RandomForestClassifier(
            n_estimators=100,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1
        )
    )

    provider = JSONProvider(
        WEIGHTS_FILE
    )

    return DODASelector(
        operators=[rf_operator],
        provider=provider,
        fusion=HadamardFusion(),
        top_k=top_k
    )


# -------------------------------------------------------------------------
# Downstream models
# -------------------------------------------------------------------------

cv_models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        random_state=RANDOM_STATE,
        eval_metric="logloss",
        scale_pos_weight=(
            (y == 0).sum() /
            (y == 1).sum()
        )
    )
}

print("\nCross-validation configuration loaded successfully.")

================================================================================
BREAST CANCER RANDOM FOREST CROSS-VALIDATION CONFIGURATION
================================================================================
Top-K values: [5, 10, 15, 20]
5-fold CV: 5
Repeated CV: 5 folds × 5 repeats
Total repeated runs: 25
Random state: 42
Clinical weights: ../../../config/clinical_weights/breast_cancer.json

Cross-validation configuration loaded successfully.

In [28]:
# =============================================================================
# STEP 22: 5-FOLD CV PREDICTIVE PERFORMANCE
# Random Forest vs Random Forest + DODA
# =============================================================================
# Feature selection is fitted inside each training fold.
# Scaling is also fitted inside each training fold.
#
# This prevents information from the validation fold from influencing
# Random Forest feature importance, DODA ranking, or downstream model fitting.

cv = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE
)

cv_results = []


for method in [
    "RF",
    "RF + DODA"
]:

    print("\n" + "=" * 80)
    print(f"METHOD: {method}")
    print("=" * 80)

    for TOP_K in TOP_K_VALUES:

        for fold, (train_idx, val_idx) in enumerate(
            cv.split(X, y),
            start=1
        ):

            X_train_cv = X.iloc[train_idx].copy()
            X_val_cv = X.iloc[val_idx].copy()

            y_train_cv = y.iloc[train_idx].copy()
            y_val_cv = y.iloc[val_idx].copy()


            # -------------------------------------------------------------
            # SCALE WITH TRAINING-FOLD STATISTICS ONLY
            # -------------------------------------------------------------

            fold_scaler = StandardScaler()

            X_train_cv_scaled = pd.DataFrame(
                fold_scaler.fit_transform(X_train_cv),
                columns=X_train_cv.columns,
                index=X_train_cv.index
            )

            X_val_cv_scaled = pd.DataFrame(
                fold_scaler.transform(X_val_cv),
                columns=X_val_cv.columns,
                index=X_val_cv.index
            )


            # -------------------------------------------------------------
            # RANDOM FOREST FEATURE IMPORTANCE
            # -------------------------------------------------------------
            # The selector is fitted using training-fold data only.

            rf_selector_cv = RandomForestClassifier(
                n_estimators=100,
                class_weight="balanced",
                random_state=RANDOM_STATE,
                n_jobs=-1
            )

            rf_selector_cv.fit(
                X_train_cv_scaled,
                y_train_cv
            )

            rf_scores_cv = pd.Series(
                rf_selector_cv.feature_importances_,
                index=X_train_cv_scaled.columns
            ).sort_values(
                ascending=False
            )

            rf_ranked_features_cv = (
                rf_scores_cv.index.tolist()
            )


            # -------------------------------------------------------------
            # FEATURE SELECTION
            # -------------------------------------------------------------

            if method == "RF":

                selected_features = (
                    rf_ranked_features_cv[
                        :TOP_K
                    ]
                )

            else:

                # DODA receives the complete scaled training matrix.
                # The Random Forest operator supplies the statistical
                # importance ranking, while DODA applies the existing
                # Hadamard fusion with the clinical weights before
                # selecting Top-K.

                doda_selector_cv = make_doda_rf(
                    TOP_K
                )

                doda_selector_cv.fit(
                    X_train_cv_scaled,
                    y_train_cv
                )

                selected_features = list(
                    doda_selector_cv.get_selected_features()
                )


            # -------------------------------------------------------------
            # Selected train/validation matrices
            # -------------------------------------------------------------

            X_train_selected = X_train_cv_scaled[
                selected_features
            ]

            X_val_selected = X_val_cv_scaled[
                selected_features
            ]


            # -------------------------------------------------------------
            # Evaluate downstream models
            # -------------------------------------------------------------

            for model_name, model_template in cv_models.items():

                model = type(model_template)(
                    **model_template.get_params()
                )

                model.fit(
                    X_train_selected,
                    y_train_cv
                )

                y_pred = model.predict(
                    X_val_selected
                )

                y_prob = model.predict_proba(
                    X_val_selected
                )[:, 1]


                cv_results.append({

                    "Fold": fold,
                    "Method": method,
                    "Top_K": TOP_K,
                    "Model": model_name,

                    "Accuracy": accuracy_score(
                        y_val_cv,
                        y_pred
                    ),

                    "Precision": precision_score(
                        y_val_cv,
                        y_pred,
                        zero_division=0
                    ),

                    "Recall": recall_score(
                        y_val_cv,
                        y_pred,
                        zero_division=0
                    ),

                    "F1": f1_score(
                        y_val_cv,
                        y_pred,
                        zero_division=0
                    ),

                    "ROC_AUC": roc_auc_score(
                        y_val_cv,
                        y_prob
                    ),

                    "Selected_Features": ", ".join(
                        selected_features
                    )
                })


cv_results_df = pd.DataFrame(
    cv_results
)

print("\nCompleted 5-fold CV.")
print("Rows:", len(cv_results_df))

display(
    cv_results_df.head()
)

================================================================================
METHOD: RF
================================================================================

================================================================================
METHOD: RF + DODA
================================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410E231090>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.3804661863289701), 'mean texture': np.float64(0.13617624432931913), 'mean perimeter': np.float64(0.45239639088412464), 'mean area': np.float64(0.3471902132252078), 'mean smoothness': np.float64(0.05297633948860021), 'mean compactness': np.float64(0.09220340316944801), 'mean concavity': np.float64(0.3234080726740471), 'mean concave points': np.float64(0.6859121290293384), 'mean symmetry': np.float64(0.03021477165340324), 'mean fractal dimension': np.float64(0.02729774628342118), 'radius error': np.float64(0.12026422504128535), 'texture error': np.float64(0.04232751472753247), 'perimeter error': np.float64(0.07247872431465362), 'area error': np.float64(0.3095400613448384), 'smoothness error': np.float64(0.03741313781980282), 'compactness error': np.float64(0.04540986685519918), 'concavity error': np.float64(0.018767830598947495), 'concave points error': np.float64(0.0180043913259337), 'symmetry error': np.float64(0.028132476664895316), 'fractal dimension error': np.float64(0.030187832303452383), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.1352729501159021), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.08476448759650382), 'worst compactness': np.float64(0.10613224717178739), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.050801783366028495), 'worst fractal dimension': np.float64(0.047792114775316044)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.3424195676960731), 'mean texture': np.float64(0.06808812216465956), 'mean perimeter': np.float64(0.4071567517957122), 'mean area': np.float64(0.3124711919026871), 'mean smoothness': np.float64(0.021190535795440085), 'mean compactness': np.float64(0.06454238221861361), 'mean concavity': np.float64(0.2910672654066424), 'mean concave points': np.float64(0.6173209161264046), 'mean symmetry': np.float64(0.01510738582670162), 'mean fractal dimension': np.float64(0.008189323885026354), 'radius error': np.float64(0.060132112520642676), 'texture error': np.float64(0.01269825441825974), 'perimeter error': np.float64(0.03623936215732681), 'area error': np.float64(0.1547700306724192), 'smoothness error': np.float64(0.007482627563960564), 'compactness error': np.float64(0.013622960056559755), 'concavity error': np.float64(0.007507132239578999), 'concave points error': np.float64(0.007201756530373481), 'symmetry error': np.float64(0.008439742999468595), 'fractal dimension error': np.float64(0.0060375664606904765), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.08116377006954126), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.04238224379825191), 'worst compactness': np.float64(0.08490579773742991), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.030481070019617095), 'worst fractal dimension': np.float64(0.014337634432594813)}
Top 5 Features Selected: ['worst area', 'worst concave points', 'worst perimeter', 'mean concave points', 'worst radius']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410E232210>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.047336345148627675), 'mean texture': np.float64(0.009194543545558938), 'mean perimeter': np.float64(0.08126255532481427), 'mean area': np.float64(0.05067598770081093), 'mean smoothness': np.float64(0.007138991267440261), 'mean compactness': np.float64(0.01331633594266391), 'mean concavity': np.float64(0.04782523614158579), 'mean concave points': np.float64(0.08653159106128595), 'mean symmetry': np.float64(0.003990827049920485), 'mean fractal dimension': np.float64(0.0030433060363224984), 'radius error': np.float64(0.014884189573590242), 'texture error': np.float64(0.003366547689189123), 'perimeter error': np.float64(0.011254638904862923), 'area error': np.float64(0.0269766742969783), 'smoothness error': np.float64(0.005186798552988446), 'compactness error': np.float64(0.0038841779201969407), 'concavity error': np.float64(0.002967136555241194), 'concave points error': np.float64(0.0031531336231766165), 'symmetry error': np.float64(0.0030331223091310472), 'fractal dimension error': np.float64(0.004713833548126605), 'worst radius': np.float64(0.04987242401644813), 'worst texture': np.float64(0.015470091872513183), 'worst perimeter': np.float64(0.10486027076079187), 'worst area': np.float64(0.1695975006783126), 'worst smoothness': np.float64(0.010648168436634258), 'worst compactness': np.float64(0.013787320650108707), 'worst concavity': np.float64(0.03818058161273058), 'worst concave points': np.float64(0.1532612198035329), 'worst symmetry': np.float64(0.0098852650375757), 'worst fractal dimension': np.float64(0.004701184938840029)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.047336345148627675), 'mean texture': np.float64(0.009194543545558938), 'mean perimeter': np.float64(0.08126255532481427), 'mean area': np.float64(0.05067598770081093), 'mean smoothness': np.float64(0.007138991267440261), 'mean compactness': np.float64(0.01331633594266391), 'mean concavity': np.float64(0.04782523614158579), 'mean concave points': np.float64(0.08653159106128595), 'mean symmetry': np.float64(0.003990827049920485), 'mean fractal dimension': np.float64(0.0030433060363224984), 'radius error': np.float64(0.014884189573590242), 'texture error': np.float64(0.003366547689189123), 'perimeter error': np.float64(0.011254638904862923), 'area error': np.float64(0.0269766742969783), 'smoothness error': np.float64(0.005186798552988446), 'compactness error': np.float64(0.0038841779201969407), 'concavity error': np.float64(0.002967136555241194), 'concave points error': np.float64(0.0031531336231766165), 'symmetry error': np.float64(0.0030331223091310472), 'fractal dimension error': np.float64(0.004713833548126605), 'worst radius': np.float64(0.04987242401644813), 'worst texture': np.float64(0.015470091872513183), 'worst perimeter': np.float64(0.10486027076079187), 'worst area': np.float64(0.1695975006783126), 'worst smoothness': np.float64(0.010648168436634258), 'worst compactness': np.float64(0.013787320650108707), 'worst concavity': np.float64(0.03818058161273058), 'worst concave points': np.float64(0.1532612198035329), 'worst symmetry': np.float64(0.0098852650375757), 'worst fractal dimension': np.float64(0.004701184938840029)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.27910992178129923), 'mean texture': np.float64(0.05421390945494455), 'mean perimeter': np.float64(0.4791494862825285), 'mean area': np.float64(0.29880150060071703), 'mean smoothness': np.float64(0.04209372920525098), 'mean compactness': np.float64(0.07851728881265728), 'mean concavity': np.float64(0.28199257624851), 'mean concave points': np.float64(0.5102173718079516), 'mean symmetry': np.float64(0.02353116663841742), 'mean fractal dimension': np.float64(0.01794428587774385), 'radius error': np.float64(0.08776184503934478), 'texture error': np.float64(0.019850219936758905), 'perimeter error': np.float64(0.06636087713468361), 'area error': np.float64(0.15906292362260005), 'smoothness error': np.float64(0.03058298932616117), 'compactness error': np.float64(0.022902329955701007), 'concavity error': np.float64(0.017495166752894364), 'concave points error': np.float64(0.018591863739533428), 'symmetry error': np.float64(0.017884239431595055), 'fractal dimension error': np.float64(0.027794239474481768), 'worst radius': np.float64(0.2940634373559822), 'worst texture': np.float64(0.09121650856079762), 'worst perimeter': np.float64(0.6182890098108677), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.06278493724286291), 'worst compactness': np.float64(0.08129436221032571), 'worst concavity': np.float64(0.2251246714133503), 'worst concave points': np.float64(0.9036761696991876), 'worst symmetry': np.float64(0.05828661977941391), 'worst fractal dimension': np.float64(0.027719659311236513)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.2511989296031693), 'mean texture': np.float64(0.027106954727472276), 'mean perimeter': np.float64(0.43123453765427566), 'mean area': np.float64(0.2689213505406453), 'mean smoothness': np.float64(0.016837491682100393), 'mean compactness': np.float64(0.05496210216886009), 'mean concavity': np.float64(0.253793318623659), 'mean concave points': np.float64(0.4591956346271564), 'mean symmetry': np.float64(0.01176558331920871), 'mean fractal dimension': np.float64(0.005383285763323155), 'radius error': np.float64(0.04388092251967239), 'texture error': np.float64(0.005955065981027671), 'perimeter error': np.float64(0.033180438567341805), 'area error': np.float64(0.07953146181130002), 'smoothness error': np.float64(0.0061165978652322345), 'compactness error': np.float64(0.006870698986710302), 'concavity error': np.float64(0.006998066701157746), 'concave points error': np.float64(0.007436745495813371), 'symmetry error': np.float64(0.005365271829478516), 'fractal dimension error': np.float64(0.005558847894896354), 'worst radius': np.float64(0.2940634373559822), 'worst texture': np.float64(0.05472990513647857), 'worst perimeter': np.float64(0.6182890098108677), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.031392468621431455), 'worst compactness': np.float64(0.06503548976826057), 'worst concavity': np.float64(0.2251246714133503), 'worst concave points': np.float64(0.9036761696991876), 'worst symmetry': np.float64(0.03497197186764835), 'worst fractal dimension': np.float64(0.008315897793370953)}
Top 5 Features Selected: ['worst area', 'worst concave points', 'worst perimeter', 'mean concave points', 'mean perimeter']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410911B100>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.033800352067554044), 'mean texture': np.float64(0.015188731123414708), 'mean perimeter': np.float64(0.07564449896248869), 'mean area': np.float64(0.04627715648086357), 'mean smoothness': np.float64(0.00523860344011446), 'mean compactness': np.float64(0.011747907041554595), 'mean concavity': np.float64(0.06787891576092947), 'mean concave points': np.float64(0.08580578009228244), 'mean symmetry': np.float64(0.004947401429381312), 'mean fractal dimension': np.float64(0.0035392993192464466), 'radius error': np.float64(0.014238112824754321), 'texture error': np.float64(0.0031728140788358345), 'perimeter error': np.float64(0.012628929745384092), 'area error': np.float64(0.034293684714467865), 'smoothness error': np.float64(0.0041765981523919195), 'compactness error': np.float64(0.007374745959315963), 'concavity error': np.float64(0.007282081334341127), 'concave points error': np.float64(0.0038240766572662115), 'symmetry error': np.float64(0.0021516260910473192), 'fractal dimension error': np.float64(0.006033752142621421), 'worst radius': np.float64(0.08028043481355203), 'worst texture': np.float64(0.015055358795563445), 'worst perimeter': np.float64(0.10150971626090934), 'worst area': np.float64(0.16972524958018106), 'worst smoothness': np.float64(0.010137909455652573), 'worst compactness': np.float64(0.014223287944138211), 'worst concavity': np.float64(0.030957034387167827), 'worst concave points': np.float64(0.11817108964448497), 'worst symmetry': np.float64(0.008327195603601947), 'worst fractal dimension': np.float64(0.006367656096492836)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.033800352067554044), 'mean texture': np.float64(0.015188731123414708), 'mean perimeter': np.float64(0.07564449896248869), 'mean area': np.float64(0.04627715648086357), 'mean smoothness': np.float64(0.00523860344011446), 'mean compactness': np.float64(0.011747907041554595), 'mean concavity': np.float64(0.06787891576092947), 'mean concave points': np.float64(0.08580578009228244), 'mean symmetry': np.float64(0.004947401429381312), 'mean fractal dimension': np.float64(0.0035392993192464466), 'radius error': np.float64(0.014238112824754321), 'texture error': np.float64(0.0031728140788358345), 'perimeter error': np.float64(0.012628929745384092), 'area error': np.float64(0.034293684714467865), 'smoothness error': np.float64(0.0041765981523919195), 'compactness error': np.float64(0.007374745959315963), 'concavity error': np.float64(0.007282081334341127), 'concave points error': np.float64(0.0038240766572662115), 'symmetry error': np.float64(0.0021516260910473192), 'fractal dimension error': np.float64(0.006033752142621421), 'worst radius': np.float64(0.08028043481355203), 'worst texture': np.float64(0.015055358795563445), 'worst perimeter': np.float64(0.10150971626090934), 'worst area': np.float64(0.16972524958018106), 'worst smoothness': np.float64(0.010137909455652573), 'worst compactness': np.float64(0.014223287944138211), 'worst concavity': np.float64(0.030957034387167827), 'worst concave points': np.float64(0.11817108964448497), 'worst symmetry': np.float64(0.008327195603601947), 'worst fractal dimension': np.float64(0.006367656096492836)}

Normalized Mathematical Scores

,Fold,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,RF,5,Logistic Regression,0.938596,1.000000,0.901408,0.948148,0.997707,"worst area, worst concave points, mean concave..."
1,1,RF,5,Random Forest,0.938596,0.984848,0.915493,0.948905,0.996397,"worst area, worst concave points, mean concave..."
2,1,RF,5,XGBoost,0.938596,0.984848,0.915493,0.948905,0.996725,"worst area, worst concave points, mean concave..."
3,2,RF,5,Logistic Regression,0.921053,0.918919,0.957746,0.937931,0.977727,"worst area, worst concave points, worst perime..."
4,2,RF,5,Random Forest,0.912281,0.906667,0.957746,0.931507,0.969538,"worst area, worst concave points, worst perime..."

In [29]:
# =============================================================================
# STEP 23: 5-FOLD CV SUMMARY — MEAN ± STD
# =============================================================================

cv_summary_df = (
    cv_results_df
    .groupby(
        ["Method", "Top_K", "Model"]
    )
    .agg(
        Accuracy_Mean=("Accuracy", "mean"),
        Accuracy_STD=("Accuracy", "std"),

        Precision_Mean=("Precision", "mean"),
        Precision_STD=("Precision", "std"),

        Recall_Mean=("Recall", "mean"),
        Recall_STD=("Recall", "std"),

        F1_Mean=("F1", "mean"),
        F1_STD=("F1", "std"),

        ROC_AUC_Mean=("ROC_AUC", "mean"),
        ROC_AUC_STD=("ROC_AUC", "std")
    )
    .reset_index()
)

print("=" * 100)
print("5-FOLD CV PERFORMANCE SUMMARY")
print("=" * 100)

display(
    cv_summary_df.round(4)
)

os.makedirs(
    "../../../results/breast_cancer/cv",
    exist_ok=True
)

cv_results_df.to_csv(
    "../../../results/breast_cancer/cv/rf_doda_5fold_results.csv",
    index=False
)

cv_summary_df.to_csv(
    "../../../results/breast_cancer/cv/rf_doda_5fold_summary.csv",
    index=False
)

====================================================================================================
5-FOLD CV PERFORMANCE SUMMARY
====================================================================================================

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,RF,5,Logistic Regression,0.9456,0.0189,0.9699,0.0337,0.9440,0.0343,0.9560,0.0152,0.9891,0.0098
1,RF,5,Random Forest,0.9403,0.0179,0.9588,0.0320,0.9468,0.0286,0.9521,0.0140,0.9823,0.0107
2,RF,5,XGBoost,0.9350,0.0201,0.9556,0.0306,0.9412,0.0286,0.9479,0.0158,0.9748,0.0201
3,RF,10,Logistic Regression,0.9438,0.0158,0.9664,0.0209,0.9441,0.0341,0.9545,0.0134,0.9899,0.0089
4,RF,10,Random Forest,0.9455,0.0190,0.9614,0.0271,0.9524,0.0319,0.9563,0.0154,0.9853,0.0098
5,RF,10,XGBoost,0.9368,0.0208,0.9554,0.0256,0.9441,0.0311,0.9493,0.0168,0.9770,0.0180
6,RF,15,Logistic Regression,0.9614,0.0159,0.9752,0.0175,0.9636,0.0379,0.9688,0.0136,0.9955,0.0051
7,RF,15,Random Forest,0.9578,0.0114,0.9754,0.0244,0.9580,0.0341,0.9660,0.0097,0.9893,0.0074
8,RF,15,XGBoost,0.9543,0.0144,0.9667,0.0225,0.9608,0.0116,0.9636,0.0112,0.9927,0.0045
9,RF,20,Logistic Regression,0.9754,0.0096,0.9836,0.0177,0.9776,0.0255,0.9803,0.0079,0.9962,0.0057
10,RF,20,Random Forest,0.9613,0.0100,0.9780,0.0207,0.9608,0.0317,0.9688,0.0086,0.9925,0.0054
11,RF,20,XGBoost,0.9596,0.0117,0.9672,0.0246,0.9692,0.0151,0.9679,0.0090,0.9936,0.0050
12,RF + DODA,5,Logistic Regression,0.9473,0.0195,0.9699,0.0337,0.9468,0.0320,0.9575,0.0156,0.9891,0.0098
13,RF + DODA,5,Random Forest,0.9438,0.0228,0.9590,0.0320,0.9524,0.0363,0.9550,0.0182,0.9811,0.0112
14,RF + DODA,5,XGBoost,0.9333,0.0201,0.9556,0.0305,0.9385,0.0321,0.9463,0.0159,0.9741,0.0196
15,RF + DODA,10,Logistic Regression,0.9438,0.0132,0.9723,0.0259,0.9384,0.0416,0.9542,0.0120,0.9895,0.0097
16,RF + DODA,10,Random Forest,0.9455,0.0143,0.9638,0.0224,0.9496,0.0287,0.9562,0.0119,0.9845,0.0114
17,RF + DODA,10,XGBoost,0.9368,0.0243,0.9530,0.0273,0.9469,0.0372,0.9493,0.0199,0.9768,0.0170
18,RF + DODA,15,Logistic Regression,0.9631,0.0156,0.9752,0.0175,0.9664,0.0353,0.9703,0.0134,0.9953,0.0056
19,RF + DODA,15,Random Forest,0.9614,0.0117,0.9752,0.0176,0.9636,0.0322,0.9689,0.0100,0.9909,0.0060
20,RF + DODA,15,XGBoost,0.9543,0.0168,0.9668,0.0224,0.9608,0.0268,0.9634,0.0135,0.9930,0.0034
21,RF + DODA,20,Logistic Regression,0.9772,0.0100,0.9837,0.0176,0.9804,0.0273,0.9817,0.0083,0.9960,0.0060
22,RF + DODA,20,Random Forest,0.9578,0.0144,0.9779,0.0230,0.9552,0.0331,0.9659,0.0121,0.9921,0.0054
23,RF + DODA,20,XGBoost,0.9613,0.0100,0.9673,0.0245,0.9720,0.0170,0.9693,0.0076,0.9939,0.0046

In [30]:
# =============================================================================
# STEP 24: 5×5 REPEATED STRATIFIED CV
# Random Forest vs Random Forest + DODA
# =============================================================================
# 5 folds × 5 repeats = 25 train/validation partitions.
# Random Forest feature importance and DODA are refit inside every
# repeated-CV partition.
# Scaling is also refit inside every partition using training data only.
#
# The repeated-CV results are stored separately from the fixed-split
# baseline and 5-fold CV results.

repeated_cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)

repeated_cv_results = []


for run_id, (train_idx, val_idx) in enumerate(
    repeated_cv.split(X, y),
    start=1
):

    X_train_rep = X.iloc[train_idx].copy()
    X_val_rep = X.iloc[val_idx].copy()

    y_train_rep = y.iloc[train_idx].copy()
    y_val_rep = y.iloc[val_idx].copy()


    # ---------------------------------------------------------------------
    # Scale within the current training partition only.
    # ---------------------------------------------------------------------

    rep_scaler = StandardScaler()

    X_train_rep_scaled = pd.DataFrame(
        rep_scaler.fit_transform(X_train_rep),
        columns=X_train_rep.columns,
        index=X_train_rep.index
    )

    X_val_rep_scaled = pd.DataFrame(
        rep_scaler.transform(X_val_rep),
        columns=X_val_rep.columns,
        index=X_val_rep.index
    )


    # ---------------------------------------------------------------------
    # Fit Random Forest feature importance once per repeated-CV partition.
    # The same ranking is reused across Top-K values.
    # ---------------------------------------------------------------------

    rf_selector_rep = RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )

    rf_selector_rep.fit(
        X_train_rep_scaled,
        y_train_rep
    )

    rf_scores_rep = pd.Series(
        rf_selector_rep.feature_importances_,
        index=X_train_rep_scaled.columns
    ).sort_values(
        ascending=False
    )

    rf_rank_rep = rf_scores_rep.index.tolist()


    for TOP_K in TOP_K_VALUES:

        # ---------------------------------------------------------------
        # Random Forest baseline
        # ---------------------------------------------------------------

        rf_features_rep = (
            rf_rank_rep[:TOP_K]
        )


        # ---------------------------------------------------------------
        # Random Forest + DODA
        # ---------------------------------------------------------------

        doda_selector_rep = make_doda_rf(
            TOP_K
        )

        doda_selector_rep.fit(
            X_train_rep_scaled,
            y_train_rep
        )

        doda_features_rep = list(
            doda_selector_rep.get_selected_features()
        )


        feature_sets = {
            "RF": rf_features_rep,
            "RF + DODA": doda_features_rep
        }


        for method, selected_features in feature_sets.items():

            X_train_selected = X_train_rep_scaled[
                selected_features
            ]

            X_val_selected = X_val_rep_scaled[
                selected_features
            ]


            for model_name, model_template in cv_models.items():

                model = type(model_template)(
                    **model_template.get_params()
                )

                model.fit(
                    X_train_selected,
                    y_train_rep
                )

                y_pred = model.predict(
                    X_val_selected
                )

                y_prob = model.predict_proba(
                    X_val_selected
                )[:, 1]


                repeated_cv_results.append({

                    "Run": run_id,
                    "Method": method,
                    "Top_K": TOP_K,
                    "Model": model_name,

                    "Accuracy": accuracy_score(
                        y_val_rep,
                        y_pred
                    ),

                    "Precision": precision_score(
                        y_val_rep,
                        y_pred,
                        zero_division=0
                    ),

                    "Recall": recall_score(
                        y_val_rep,
                        y_pred,
                        zero_division=0
                    ),

                    "F1": f1_score(
                        y_val_rep,
                        y_pred,
                        zero_division=0
                    ),

                    "ROC_AUC": roc_auc_score(
                        y_val_rep,
                        y_prob
                    ),

                    "Selected_Features": ", ".join(
                        selected_features
                    )
                })


repeated_cv_results_df = pd.DataFrame(
    repeated_cv_results
)

print("=" * 100)
print("COMPLETED 5×5 REPEATED STRATIFIED CV")
print("=" * 100)

print(
    "Total runs:",
    N_SPLITS * N_REPEATS
)

print(
    "Result rows:",
    len(repeated_cv_results_df)
)

display(
    repeated_cv_results_df.head()
)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410914ABA0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.3804661863289701), 'mean texture': np.float64(0.13617624432931913), 'mean perimeter': np.float64(0.45239639088412464), 'mean area': np.float64(0.3471902132252078), 'mean smoothness': np.float64(0.05297633948860021), 'mean compactness': np.float64(0.09220340316944801), 'mean concavity': np.float64(0.3234080726740471), 'mean concave points': np.float64(0.6859121290293384), 'mean symmetry': np.float64(0.03021477165340324), 'mean fractal dimension': np.float64(0.02729774628342118), 'radius error': np.float64(0.12026422504128535), 'texture error': np.float64(0.04232751472753247), 'perimeter error': np.float64(0.07247872431465362), 'area error': np.float64(0.3095400613448384), 'smoothness error': np.float64(0.03741313781980282), 'compactness error': np.float64(0.04540986685519918), 'concavity error': np.float64(0.018767830598947495), 'concave points error': np.float64(0.0180043913259337), 'symmetry error': np.float64(0.028132476664895316), 'fractal dimension error': np.float64(0.030187832303452383), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.1352729501159021), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.08476448759650382), 'worst compactness': np.float64(0.10613224717178739), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.050801783366028495), 'worst fractal dimension': np.float64(0.047792114775316044)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.3424195676960731), 'mean texture': np.float64(0.06808812216465956), 'mean perimeter': np.float64(0.4071567517957122), 'mean area': np.float64(0.3124711919026871), 'mean smoothness': np.float64(0.021190535795440085), 'mean compactness': np.float64(0.06454238221861361), 'mean concavity': np.float64(0.2910672654066424), 'mean concave points': np.float64(0.6173209161264046), 'mean symmetry': np.float64(0.01510738582670162), 'mean fractal dimension': np.float64(0.008189323885026354), 'radius error': np.float64(0.060132112520642676), 'texture error': np.float64(0.01269825441825974), 'perimeter error': np.float64(0.03623936215732681), 'area error': np.float64(0.1547700306724192), 'smoothness error': np.float64(0.007482627563960564), 'compactness error': np.float64(0.013622960056559755), 'concavity error': np.float64(0.007507132239578999), 'concave points error': np.float64(0.007201756530373481), 'symmetry error': np.float64(0.008439742999468595), 'fractal dimension error': np.float64(0.0060375664606904765), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.08116377006954126), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.04238224379825191), 'worst compactness': np.float64(0.08490579773742991), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.030481070019617095), 'worst fractal dimension': np.float64(0.014337634432594813)}
Top 5 Features Selected: ['worst area', 'worst concave points', 'worst perimeter', 'mean concave points', 'worst radius']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410E392550>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}

Normalized Mathematical Scores
{'mean radius': np.float64(0.3804661863289701), 'mean texture': np.float64(0.13617624432931913), 'mean perimeter': np.float64(0.45239639088412464), 'mean area': np.float64(0.3471902132252078), 'mean smoothness': np.float64(0.05297633948860021), 'mean compactness': np.float64(0.09220340316944801), 'mean concavity': np.float64(0.3234080726740471), 'mean concave points': np.float64(0.6859121290293384), 'mean symmetry': np.float64(0.03021477165340324), 'mean fractal dimension': np.float64(0.02729774628342118), 'radius error': np.float64(0.12026422504128535), 'texture error': np.float64(0.04232751472753247), 'perimeter error': np.float64(0.07247872431465362), 'area error': np.float64(0.3095400613448384), 'smoothness error': np.float64(0.03741313781980282), 'compactness error': np.float64(0.04540986685519918), 'concavity error': np.float64(0.018767830598947495), 'concave points error': np.float64(0.0180043913259337), 'symmetry error': np.float64(0.028132476664895316), 'fractal dimension error': np.float64(0.030187832303452383), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.1352729501159021), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.08476448759650382), 'worst compactness': np.float64(0.10613224717178739), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.050801783366028495), 'worst fractal dimension': np.float64(0.047792114775316044)}

Clinical Weights
{'mean radius': 0.9, 'mean texture': 0.5, 'mean perimeter': 0.9, 'mean area': 0.9, 'mean smoothness': 0.4, 'mean compactness': 0.7, 'mean concavity': 0.9, 'mean concave points': 0.9, 'mean symmetry': 0.5, 'mean fractal dimension': 0.3, 'radius error': 0.5, 'texture error': 0.3, 'perimeter error': 0.5, 'area error': 0.5, 'smoothness error': 0.2, 'compactness error': 0.3, 'concavity error': 0.4, 'concave points error': 0.4, 'symmetry error': 0.3, 'fractal dimension error': 0.2, 'worst radius': 1.0, 'worst texture': 0.6, 'worst perimeter': 1.0, 'worst area': 1.0, 'worst smoothness': 0.5, 'worst compactness': 0.8, 'worst concavity': 1.0, 'worst concave points': 1.0, 'worst symmetry': 0.6, 'worst fractal dimension': 0.3}

Final DODA Scores
{'mean radius': np.float64(0.3424195676960731), 'mean texture': np.float64(0.06808812216465956), 'mean perimeter': np.float64(0.4071567517957122), 'mean area': np.float64(0.3124711919026871), 'mean smoothness': np.float64(0.021190535795440085), 'mean compactness': np.float64(0.06454238221861361), 'mean concavity': np.float64(0.2910672654066424), 'mean concave points': np.float64(0.6173209161264046), 'mean symmetry': np.float64(0.01510738582670162), 'mean fractal dimension': np.float64(0.008189323885026354), 'radius error': np.float64(0.060132112520642676), 'texture error': np.float64(0.01269825441825974), 'perimeter error': np.float64(0.03623936215732681), 'area error': np.float64(0.1547700306724192), 'smoothness error': np.float64(0.007482627563960564), 'compactness error': np.float64(0.013622960056559755), 'concavity error': np.float64(0.007507132239578999), 'concave points error': np.float64(0.007201756530373481), 'symmetry error': np.float64(0.008439742999468595), 'fractal dimension error': np.float64(0.0060375664606904765), 'worst radius': np.float64(0.48425785070831906), 'worst texture': np.float64(0.08116377006954126), 'worst perimeter': np.float64(0.6858632141578032), 'worst area': np.float64(1.0), 'worst smoothness': np.float64(0.04238224379825191), 'worst compactness': np.float64(0.08490579773742991), 'worst concavity': np.float64(0.2965482802993088), 'worst concave points': np.float64(0.792159419068154), 'worst symmetry': np.float64(0.030481070019617095), 'worst fractal dimension': np.float64(0.014337634432594813)}
Top 10 Features Selected: ['worst area', 'worst concave points', 'worst perimeter', 'mean concave points', 'worst radius', 'mean perimeter', 'mean radius', 'mean area', 'worst concavity', 'mean concavity']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001410E391DD0>
DODA Pipeline Started
Running: RandomForestClassifier
DODA feature order:
['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness', 'mean compactness', 'mean concavity', 'mean concave points', 'mean symmetry', 'mean fractal dimension']
Number of features: 30
Number of feature importances: 30
Operator Scores:
{'RandomForestClassifier_1': {'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'mean radius': np.float64(0.054866806961806826), 'mean texture': np.float64(0.019637896819404373), 'mean perimeter': np.float64(0.06523981983354342), 'mean area': np.float64(0.050068098276636656), 'mean smoothness': np.float64(0.007639687038445365), 'mean compactness': np.float64(0.013296599026925269), 'mean concavity': np.float64(0.04663848965004807), 'mean concave points': np.float64(0.09891498831823801), 'mean symmetry': np.float64(0.004357254608347618), 'mean fractal dimension': np.float64(0.003936592080037905), 'radius error': np.float64(0.017343233792782027), 'texture error': np.float64(0.006104026226710505), 'perimeter error': np.float64(0.010452114586529067), 'area error': np.float64(0.044638591819742765), 'smoothness error': np.float64(0.005395326797371934), 'compactness error': np.float64(0.006548530430379148), 'concavity error': np.float64(0.0027064979111546764), 'concave points error': np.float64(0.002596402778591984), 'symmetry error': np.float64(0.004056968061797022), 'fractal dimension error': np.float64(0.004353369700393794), 'worst radius': np.float64(0.06983454238316814), 'worst texture': np.float64(0.01950763328740572), 'worst perimeter': np.float64(0.09890793433312574), 'worst area': np.float64(0.14420941711326282), 'worst smoothness': np.float64(0.012223837348196213), 'worst compactness': np.float64(0.015305269501564196), 'worst concavity': np.float64(0.042765054647903804), 'worst concave points': np.float64(0.11423684808459939), 'worst symmetry': np.float64(0.00732609556752922), 'worst fractal dimension': np.float64(0.006892073014358483)}

Normalized Mathematical Scores

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,RF,5,Logistic Regression,0.938596,1.000000,0.901408,0.948148,0.997707,"worst area, worst concave points, mean concave..."
1,1,RF,5,Random Forest,0.938596,0.984848,0.915493,0.948905,0.996397,"worst area, worst concave points, mean concave..."
2,1,RF,5,XGBoost,0.938596,0.984848,0.915493,0.948905,0.996725,"worst area, worst concave points, mean concave..."
3,1,RF + DODA,5,Logistic Regression,0.938596,1.000000,0.901408,0.948148,0.997707,"worst area, worst concave points, worst perime..."
4,1,RF + DODA,5,Random Forest,0.947368,0.985075,0.929577,0.956522,0.995906,"worst area, worst concave points, worst perime..."

In [31]:
# =============================================================================
# STEP 25: REPEATED CV PERFORMANCE SUMMARY — MEAN ± STD
# =============================================================================

repeated_cv_summary_df = (
    repeated_cv_results_df
    .groupby(
        ["Method", "Top_K", "Model"]
    )
    .agg(
        Accuracy_Mean=("Accuracy", "mean"),
        Accuracy_STD=("Accuracy", "std"),

        Precision_Mean=("Precision", "mean"),
        Precision_STD=("Precision", "std"),

        Recall_Mean=("Recall", "mean"),
        Recall_STD=("Recall", "std"),

        F1_Mean=("F1", "mean"),
        F1_STD=("F1", "std"),

        ROC_AUC_Mean=("ROC_AUC", "mean"),
        ROC_AUC_STD=("ROC_AUC", "std")
    )
    .reset_index()
)

print("=" * 100)
print(
    "5×5 REPEATED STRATIFIED CV PERFORMANCE SUMMARY"
)
print("=" * 100)

display(
    repeated_cv_summary_df.round(4)
)

os.makedirs(
    "../../../results/breast_cancer/cv",
    exist_ok=True
)

repeated_cv_results_df.to_csv(
    "../../../results/breast_cancer/cv/"
    "rf_doda_5x5_repeated_results.csv",
    index=False
)

repeated_cv_summary_df.to_csv(
    "../../../results/breast_cancer/cv/"
    "rf_doda_5x5_repeated_summary.csv",
    index=False
)

====================================================================================================
5×5 REPEATED STRATIFIED CV PERFORMANCE SUMMARY
====================================================================================================

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,RF,5,Logistic Regression,0.9455,0.0215,0.9692,0.0259,0.9440,0.0301,0.9559,0.0178,0.9883,0.0069
1,RF,5,Random Forest,0.9392,0.0209,0.9575,0.0289,0.9462,0.0277,0.9513,0.0168,0.9816,0.0096
2,RF,5,XGBoost,0.9417,0.0195,0.9570,0.0260,0.9507,0.0267,0.9533,0.0157,0.9784,0.0142
3,RF,10,Logistic Regression,0.9434,0.0152,0.9705,0.0186,0.9389,0.0271,0.9541,0.0128,0.9898,0.0060
4,RF,10,Random Forest,0.9473,0.0179,0.9619,0.0227,0.9546,0.0295,0.9577,0.0148,0.9858,0.0087
5,RF,10,XGBoost,0.9420,0.0152,0.9554,0.0240,0.9529,0.0232,0.9537,0.0121,0.9808,0.0127
6,RF,15,Logistic Regression,0.9624,0.0118,0.9728,0.0158,0.9675,0.0220,0.9699,0.0096,0.9946,0.0042
7,RF,15,Random Forest,0.9568,0.0212,0.9698,0.0257,0.9619,0.0276,0.9654,0.0171,0.9903,0.0077
8,RF,15,XGBoost,0.9571,0.0171,0.9695,0.0201,0.9624,0.0242,0.9656,0.0140,0.9932,0.0046
9,RF,20,Logistic Regression,0.9779,0.0114,0.9823,0.0139,0.9826,0.0158,0.9824,0.0091,0.9957,0.0044
10,RF,20,Random Forest,0.9589,0.0194,0.9714,0.0237,0.9636,0.0286,0.9670,0.0158,0.9918,0.0066
11,RF,20,XGBoost,0.9624,0.0171,0.9702,0.0197,0.9703,0.0219,0.9700,0.0139,0.9936,0.0041
12,RF + DODA,5,Logistic Regression,0.9452,0.0220,0.9686,0.0257,0.9440,0.0298,0.9557,0.0181,0.9882,0.0069
13,RF + DODA,5,Random Forest,0.9402,0.0221,0.9567,0.0299,0.9490,0.0305,0.9522,0.0177,0.9805,0.0098
14,RF + DODA,5,XGBoost,0.9392,0.0206,0.9563,0.0264,0.9473,0.0292,0.9513,0.0167,0.9775,0.0138
15,RF + DODA,10,Logistic Regression,0.9427,0.0170,0.9711,0.0204,0.9372,0.0309,0.9534,0.0145,0.9883,0.0073
16,RF + DODA,10,Random Forest,0.9490,0.0177,0.9626,0.0247,0.9568,0.0280,0.9592,0.0143,0.9850,0.0088
17,RF + DODA,10,XGBoost,0.9455,0.0156,0.9572,0.0242,0.9568,0.0255,0.9566,0.0126,0.9795,0.0118
18,RF + DODA,15,Logistic Regression,0.9624,0.0109,0.9744,0.0149,0.9658,0.0218,0.9698,0.0090,0.9950,0.0042
19,RF + DODA,15,Random Forest,0.9571,0.0201,0.9687,0.0239,0.9636,0.0277,0.9657,0.0163,0.9907,0.0070
20,RF + DODA,15,XGBoost,0.9613,0.0160,0.9719,0.0192,0.9669,0.0265,0.9690,0.0133,0.9940,0.0038
21,RF + DODA,20,Logistic Regression,0.9789,0.0105,0.9824,0.0139,0.9843,0.0153,0.9832,0.0084,0.9955,0.0047
22,RF + DODA,20,Random Forest,0.9585,0.0180,0.9715,0.0242,0.9630,0.0270,0.9668,0.0146,0.9915,0.0061
23,RF + DODA,20,XGBoost,0.9631,0.0164,0.9703,0.0193,0.9714,0.0230,0.9706,0.0134,0.9936,0.0042

## 4. Feature-Selection Stability and Random Forest–DODA Agreement

The next analyses use the **25 repeated-CV runs** to examine how consistently features are selected.

We distinguish:

- **Selection frequency:** how often a feature is selected.
- **Jaccard similarity:** overlap between feature sets.
- **Kuncheva index:** chance-adjusted agreement for fixed-size feature subsets.
- **Random Forest–DODA agreement:** whether DODA changes the selected set relative to the Random Forest statistical baseline.

These analyses evaluate **feature-selection stability and set membership**, not merely predictive performance.

In [32]:
# =============================================================================
# STEP 26: PREPARE STABILITY DATAFRAME
# =============================================================================

stability_df = repeated_cv_results_df[
    [
        "Run",
        "Method",
        "Top_K",
        "Selected_Features"
    ]
].copy()

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(
        lambda x: {
            feature.strip()
            for feature in x.split(",")
            if feature.strip()
        }
    )
)

feature_names = X.columns.tolist()
N_FEATURES = len(feature_names)

print("=" * 80)
print("STABILITY ANALYSIS PREPARATION")
print("=" * 80)

print("Rows:", stability_df.shape[0])
print(
    "Methods:",
    stability_df["Method"].unique()
)
print(
    "Top-K:",
    sorted(stability_df["Top_K"].unique())
)
print(
    "Total predictors:",
    N_FEATURES
)

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head()
)

================================================================================
STABILITY ANALYSIS PREPARATION
================================================================================
Rows: 600
Methods: <StringArray>
['RF', 'RF + DODA']
Length: 2, dtype: str
Top-K: [np.int64(5), np.int64(10), np.int64(15), np.int64(20)]
Total predictors: 30

   Run     Method  Top_K                                        Feature_Set
0    1         RF      5  {worst concave points, worst perimeter, worst ...
1    1         RF      5  {worst concave points, worst perimeter, worst ...
2    1         RF      5  {worst concave points, worst perimeter, worst ...
3    1  RF + DODA      5  {worst concave points, worst perimeter, worst ...
4    1  RF + DODA      5  {worst concave points, worst perimeter, worst ...

In [33]:
# =============================================================================
# STEP 27: TEST 1 — FEATURE SELECTION FREQUENCY
# =============================================================================

selection_frequency = []


for method in sorted(
    stability_df["Method"].unique()
):

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]

        total_runs = len(subset)

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set in subset["Feature_Set"]
            )

            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100
            })


selection_frequency_df = pd.DataFrame(
    selection_frequency
)

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)

display(
    selection_frequency_df
)

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,RF,5,mean concave points,75,75,100.0
1,RF,5,worst area,75,75,100.0
2,RF,5,worst concave points,75,75,100.0
3,RF,5,worst perimeter,69,75,92.0
4,RF,5,mean concavity,30,75,40.0
...,...,...,...,...,...,...
109,RF + DODA,20,worst smoothness,75,75,100.0
110,RF + DODA,20,worst symmetry,75,75,100.0
111,RF + DODA,20,worst texture,75,75,100.0
112,RF + DODA,20,mean smoothness,45,75,60.0
113,RF + DODA,20,concavity error,30,75,40.0

In [34]:
# =============================================================================
# STEP 28: TOP FREQUENTLY SELECTED FEATURES
# =============================================================================

top_frequency_features = (
    selection_frequency_df
    .groupby(
        ["Method", "Top_K"],
        group_keys=False
    )
    .head(10)
    .reset_index(drop=True)
)

print("=" * 80)
print("TOP FREQUENTLY SELECTED FEATURES")
print("=" * 80)

display(
    top_frequency_features
)

================================================================================
TOP FREQUENTLY SELECTED FEATURES
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,RF,5,mean concave points,75,75,100.0
1,RF,5,worst area,75,75,100.0
2,RF,5,worst concave points,75,75,100.0
3,RF,5,worst perimeter,69,75,92.0
4,RF,5,mean concavity,30,75,40.0
...,...,...,...,...,...,...
69,RF + DODA,20,mean perimeter,75,75,100.0
70,RF + DODA,20,mean radius,75,75,100.0
71,RF + DODA,20,mean texture,75,75,100.0
72,RF + DODA,20,perimeter error,75,75,100.0
73,RF + DODA,20,radius error,75,75,100.0

In [35]:
# =============================================================================
# STEP 29: TEST 2 — PAIRWISE JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


for method in sorted(
    stability_df["Method"].unique()
):

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)

        feature_sets = (
            subset["Feature_Set"]
            .tolist()
        )

        pairwise_scores = []


        for set_a, set_b in combinations(
            feature_sets,
            2
        ):

            intersection_size = len(
                set_a.intersection(set_b)
            )

            union_size = len(
                set_a.union(set_b)
            )

            jaccard_score = (
                intersection_size /
                union_size
                if union_size
                else 1.0
            )

            pairwise_scores.append(
                jaccard_score
            )


        if pairwise_scores:

            jaccard_results.append({

                "Method": method,

                "Top_K": top_k,

                "Mean_Jaccard": np.mean(
                    pairwise_scores
                ),

                "Std_Jaccard": np.std(
                    pairwise_scores,
                    ddof=1
                ),

                "Minimum_Jaccard": np.min(
                    pairwise_scores
                ),

                "Maximum_Jaccard": np.max(
                    pairwise_scores
                )
            })


jaccard_df = pd.DataFrame(
    jaccard_results
)

print("=" * 80)
print("PAIRWISE JACCARD SIMILARITY")
print("=" * 80)

display(
    jaccard_df.round(4)
)

================================================================================
PAIRWISE JACCARD SIMILARITY
================================================================================

,Method,Top_K,Mean_Jaccard,Std_Jaccard,Minimum_Jaccard,Maximum_Jaccard
0,RF,5,0.7489,0.1717,0.4286,1.0
1,RF,10,0.8939,0.0896,0.8182,1.0
2,RF,15,0.9010,0.0619,0.7647,1.0
3,RF,20,0.9162,0.0548,0.8182,1.0
4,RF + DODA,5,0.7873,0.1709,0.4286,1.0
5,RF + DODA,10,1.0000,0.0000,1.0000,1.0
6,RF + DODA,15,0.9319,0.0629,0.7647,1.0
7,RF + DODA,20,0.9537,0.0476,0.9048,1.0

In [36]:
# =============================================================================
# STEP 30: TEST 3 — KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


for method in sorted(
    stability_df["Method"].unique()
):

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)

        feature_sets = (
            subset["Feature_Set"]
            .tolist()
        )


        for i in range(
            len(feature_sets)
        ):

            for j in range(
                i + 1,
                len(feature_sets)
            ):

                set_a = feature_sets[i]
                set_b = feature_sets[j]

                intersection = len(
                    set_a.intersection(set_b)
                )

                denominator = (
                    top_k *
                    (
                        N_FEATURES -
                        top_k
                    )
                )


                if denominator == 0:

                    kuncheva_value = np.nan

                else:

                    kuncheva_value = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (
                            top_k ** 2
                        )
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i,
                        "Run"
                    ],

                    "Run_B": subset.loc[
                        j,
                        "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva_value
                })


kuncheva_df = pd.DataFrame(
    kuncheva_results
)

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary.round(4)
)

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

      Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0         RF      5         0.8147        0.1327        0.5200           1.0
1         RF     10         0.9124        0.0740        0.8500           1.0
2         RF     15         0.8936        0.0678        0.7333           1.0
3         RF     20         0.8662        0.0895        0.7000           1.0
4  RF + DODA      5         0.8451        0.1272        0.5200           1.0
5  RF + DODA     10         1.0000        0.0000        1.0000           1.0
6  RF + DODA     15         0.9274        0.0673        0.7333           1.0
7  RF + DODA     20         0.9270        0.0750        0.8500           1.0

In [37]:
# =============================================================================
# STEP 31: TEST 4 — RANDOM FOREST vs DODA FEATURE-SET AGREEMENT
# =============================================================================
# This compares feature-set membership within the SAME repeated-CV run
# and Top-K value.

agreement_results = []


for run in sorted(
    stability_df["Run"].unique()
):

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        rf_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "RF") &
            (stability_df["Top_K"] == top_k)
        ]

        doda_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "RF + DODA") &
            (stability_df["Top_K"] == top_k)
        ]


        if (
            rf_rows.empty or
            doda_rows.empty
        ):
            continue


        rf_set = (
            rf_rows.iloc[0]["Feature_Set"]
        )

        doda_set = (
            doda_rows.iloc[0]["Feature_Set"]
        )


        intersection_size = len(
            rf_set.intersection(
                doda_set
            )
        )

        union_size = len(
            rf_set.union(
                doda_set
            )
        )

        jaccard_agreement = (
            intersection_size /
            union_size
            if union_size
            else 1.0
        )


        agreement_results.append({

            "Run": run,

            "Top_K": top_k,

            "RF_Features":
                ", ".join(
                    sorted(rf_set)
                ),

            "DODA_Features":
                ", ".join(
                    sorted(doda_set)
                ),

            "Common_Feature_Count":
                intersection_size,

            "RF_Feature_Count":
                len(rf_set),

            "DODA_Feature_Count":
                len(doda_set),

            "Same_Feature_Set":
                rf_set == doda_set,

            "Jaccard_Agreement":
                jaccard_agreement,

            "Features_Added_by_DODA":
                ", ".join(
                    sorted(
                        doda_set -
                        rf_set
                    )
                ),

            "Features_Removed_by_DODA":
                ", ".join(
                    sorted(
                        rf_set -
                        doda_set
                    )
                )
        })


agreement_df = pd.DataFrame(
    agreement_results
)


print("=" * 100)
print("RANDOM FOREST vs DODA FEATURE-SET AGREEMENT")
print("=" * 100)

display(
    agreement_df
)

====================================================================================================
RANDOM FOREST vs DODA FEATURE-SET AGREEMENT
====================================================================================================

,Run,Top_K,RF_Features,DODA_Features,Common_Feature_Count,RF_Feature_Count,DODA_Feature_Count,Same_Feature_Set,Jaccard_Agreement,Features_Added_by_DODA,Features_Removed_by_DODA
0,1,5,"mean concave points, worst area, worst concave...","mean concave points, worst area, worst concave...",5,5,5,True,1.000000,,
1,1,10,"area error, mean area, mean concave points, me...","mean area, mean concave points, mean concavity...",9,10,10,False,0.818182,worst concavity,area error
2,1,15,"area error, mean area, mean concave points, me...","area error, mean area, mean compactness, mean ...",14,15,15,False,0.875000,mean compactness,radius error
3,1,20,"area error, mean area, mean compactness, mean ...","area error, mean area, mean compactness, mean ...",20,20,20,True,1.000000,,
4,2,5,"mean concave points, mean perimeter, worst are...","mean concave points, mean perimeter, worst are...",5,5,5,True,1.000000,,
...,...,...,...,...,...,...,...,...,...,...,...
95,24,20,"area error, mean area, mean compactness, mean ...","area error, mean area, mean compactness, mean ...",20,20,20,True,1.000000,,
96,25,5,"mean concave points, mean perimeter, worst are...","mean concave points, mean perimeter, worst are...",5,5,5,True,1.000000,,
97,25,10,"mean area, mean concave points, mean concavity...","mean area, mean concave points, mean concavity...",10,10,10,True,1.000000,,
98,25,15,"area error, mean area, mean concave points, me...","area error, mean area, mean concave points, me...",15,15,15,True,1.000000,,
99,25,20,"area error, concavity error, mean area, mean c...","area error, concavity error, mean area, mean c...",20,20,20,True,1.000000,,

In [38]:
# =============================================================================
# STEP 32: SUMMARY OF RANDOM FOREST vs DODA AGREEMENT
# =============================================================================

agreement_summary_df = (
    agreement_df
    .groupby("Top_K")
    .agg(
        Same_Feature_Set_Percentage=(
            "Same_Feature_Set",
            lambda x: x.mean() * 100
        ),

        Mean_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "mean"
        ),

        Std_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "std"
        ),

        Mean_Common_Features=(
            "Common_Feature_Count",
            "mean"
        )
    )
    .reset_index()
)


print("=" * 100)
print(
    "FINAL RANDOM FOREST vs DODA FEATURE-SET AGREEMENT SUMMARY"
)
print("=" * 100)

display(
    agreement_summary_df.round(4)
)


# -------------------------------------------------------------------------
# Save stability outputs
# -------------------------------------------------------------------------

os.makedirs(
    "../../../results/breast_cancer/stability",
    exist_ok=True
)

selection_frequency_df.to_csv(
    "../../../results/breast_cancer/stability/"
    "feature_selection_frequency_rf.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/breast_cancer/stability/"
    "jaccard_similarity_rf.csv",
    index=False
)

kuncheva_df.to_csv(
    "../../../results/breast_cancer/stability/"
    "kuncheva_pairwise_rf.csv",
    index=False
)

kuncheva_summary.to_csv(
    "../../../results/breast_cancer/stability/"
    "kuncheva_summary_rf.csv",
    index=False
)

agreement_df.to_csv(
    "../../../results/breast_cancer/stability/"
    "rf_doda_agreement.csv",
    index=False
)

agreement_summary_df.to_csv(
    "../../../results/breast_cancer/stability/"
    "rf_doda_agreement_summary.csv",
    index=False
)

====================================================================================================
FINAL RANDOM FOREST vs DODA FEATURE-SET AGREEMENT SUMMARY
====================================================================================================

,Top_K,Same_Feature_Set_Percentage,Mean_Jaccard_Agreement,Std_Jaccard_Agreement,Mean_Common_Features
0,5,76.0,0.9200,0.1453,4.76
1,10,56.0,0.9200,0.0921,9.56
2,15,44.0,0.9300,0.0633,14.44
3,20,64.0,0.9657,0.0467,19.64

In [39]:
# =============================================================================
# STEP 33: FINAL NOTEBOOK CONSISTENCY CHECK
# =============================================================================

print("=" * 80)
print("BREAST CANCER RANDOM FOREST + DODA NOTEBOOK SANITY CHECK")
print("=" * 80)

print(
    "Dataset shape             :",
    df.shape
)

print(
    "Predictor count           :",
    X.shape[1]
)

print(
    "Target column             :",
    target_column
)

print(
    "Missing values in X       :",
    int(X.isnull().sum().sum())
)

print(
    "Fixed-split Top-K values  :",
    k_values
)

print(
    "CV Top-K values           :",
    TOP_K_VALUES
)

print(
    "Repeated-CV runs          :",
    N_SPLITS * N_REPEATS
)

print(
    "Baseline result rows      :",
    len(rf_results_df)
)

print(
    "DODA result rows          :",
    len(rf_doda_results_df)
)

print(
    "5-fold CV result rows     :",
    len(cv_results_df)
)

print(
    "5×5 CV result rows        :",
    len(repeated_cv_results_df)
)

print(
    "Stability methods         :",
    stability_df["Method"].unique()
)


assert target_column == "target"
assert X.isnull().sum().sum() == 0
assert TOP_K_VALUES == [5, 10, 15, 20]
assert all(
    k <= X.shape[1]
    for k in TOP_K_VALUES
)
assert set(
    stability_df["Method"].unique()
) == {
    "RF",
    "RF + DODA"
}


print(
    "\nCore notebook dependencies are defined."
)

print(
    "Run this notebook from the top using Run All "
    "for a clean execution state."
)

================================================================================
BREAST CANCER RANDOM FOREST + DODA NOTEBOOK SANITY CHECK
================================================================================
Dataset shape             : (569, 31)
Predictor count           : 30
Target column             : target
Missing values in X       : 0
Fixed-split Top-K values  : [5, 10, 15, 20]
CV Top-K values           : [5, 10, 15, 20]
Repeated-CV runs          : 25
Baseline result rows      : 12
DODA result rows          : 12
5-fold CV result rows     : 120
5×5 CV result rows        : 600
Stability methods         : <StringArray>
['RF', 'RF + DODA']
Length: 2, dtype: str

Core notebook dependencies are defined.
Run this notebook from the top using Run All for a clean execution state.

# 3. Random Forest + DODA: Experiment Interpretation

## 3.1 Overall Observation

The Random Forest-based feature-selection experiment produced strong predictive performance across all three downstream classifiers. Accuracy generally ranged from 0.912 to 0.965, recall from 0.889 to 0.986, F1-score from 0.928 to 0.972, and ROC-AUC remained high across configurations.

DODA did **not** produce a uniform improvement. Its effect depended on both the downstream model and the Top-K feature subset. In this experiment, DODA mainly refined the Random Forest-derived feature ranking; performance was preserved in several configurations, improved in selected Random Forest and XGBoost settings, and reduced for Logistic Regression at Top-K = 10.

## 3.2 Change in Feature Ranking

The main ranking change was not a wholesale replacement of Random Forest-important features. Instead, DODA adjusted the ordering by multiplying normalized mathematical importance by clinical weights.

| Feature | RF Mathematical Rank | DODA Rank | Rank Change | Clinical Weight | Interpretation |
|---------|---------------------:|----------:|------------:|----------------:|----------------|
| worst area | 1 | 1 | 0 | 1.0 | Retained as the highest-ranked feature. |
| worst concave points | 2 | 2 | 0 | 1.0 | Retained as a dominant feature. |
| worst radius | 4 | 3 | +1 | 1.0 | Promoted because its clinical weight preserved its full mathematical score. |
| mean concave points | 3 | 4 | -1 | 0.9 | Slightly demoted despite high mathematical importance because its clinical weight was lower than 1.0. |
| worst perimeter | 5 | 5 | 0 | 1.0 | Retained in the Top-5. |
| mean concavity | 6 | 6 | 0 | 0.9 | Retained as a highly ranked feature. |
| mean perimeter | 7 | 7 | 0 | 0.9 | Retained as a highly ranked feature. |
| mean radius | 8 | 8 | 0 | 0.9 | Retained in the Top-10. |
| worst concavity | 11 | 9 | +2 | 1.0 | Promoted into the Top-10 due to high clinical weighting. |
| mean area | 10 | 10 | 0 | 0.9 | Retained at the Top-10 boundary. |
| area error | 9 | 11 | -2 | 0.5 | Demoted below the Top-10 after clinical weighting. |
| worst compactness | 13 | 12 | +1 | 0.8 | Mildly promoted. |
| worst texture | 12 | 13 | -1 | 0.6 | Mildly demoted. |
| mean compactness | 15 | 14 | +1 | 0.7 | Mildly promoted within the Top-15. |
| radius error | 14 | 15 | -1 | 0.5 | Mildly demoted within the Top-15. |
| worst symmetry | 19 | 17 | +2 | 0.6 | Promoted within the Top-20. |
| mean symmetry | 24 | 21 | +3 | 0.5 | Promoted, but remained outside the Top-20. |
| texture error | 23 | 26 | -3 | 0.3 | Demoted among lower-ranked features. |
| fractal dimension error | 26 | 29 | -3 | 0.2 | Demoted among lower-ranked features. |

DODA preserved the strongest Random Forest mathematical features while promoting clinically weighted features such as worst radius, worst concavity, worst compactness, mean compactness, and worst symmetry. Lower clinical weights contributed to demotions such as area error, radius error, texture error, and fractal dimension error.

## 3.3 Top-K Feature Selection

### Top-K = 5

RF baseline features: worst area, worst concave points, mean concave points, worst radius, worst perimeter.

RF + DODA features: worst area, worst concave points, worst radius, mean concave points, worst perimeter.

The same five features were retained. The main change was internal ordering: worst radius moved ahead of mean concave points.

### Top-K = 10

RF baseline features: worst area, worst concave points, mean concave points, worst radius, worst perimeter, mean concavity, mean perimeter, mean radius, area error, mean area.

RF + DODA features: worst area, worst concave points, worst radius, mean concave points, worst perimeter, mean concavity, mean perimeter, mean radius, worst concavity, mean area.

The Top-10 set changed by one feature: worst concavity entered and area error left.

### Top-K = 15

RF baseline features: worst area, worst concave points, mean concave points, worst radius, worst perimeter, mean concavity, mean perimeter, mean radius, area error, mean area, worst concavity, worst texture, worst compactness, radius error, mean compactness.

RF + DODA features: worst area, worst concave points, worst radius, mean concave points, worst perimeter, mean concavity, mean perimeter, mean radius, worst concavity, mean area, area error, worst compactness, worst texture, mean compactness, radius error.

The same 15 features were retained, but their ranking order changed.

### Top-K = 20

RF baseline features: worst area, worst concave points, mean concave points, worst radius, worst perimeter, mean concavity, mean perimeter, mean radius, area error, mean area, worst concavity, worst texture, worst compactness, radius error, mean compactness, mean texture, worst smoothness, mean smoothness, worst symmetry, perimeter error.

RF + DODA features: worst area, worst concave points, worst radius, mean concave points, worst perimeter, mean concavity, mean perimeter, mean radius, worst concavity, mean area, area error, worst compactness, worst texture, mean compactness, radius error, mean texture, worst symmetry, worst smoothness, mean smoothness, perimeter error.

The same 20 features were retained. DODA mainly refined the ordering within the selected feature set.

| Top-K | Retained Features | Entered with DODA | Left after DODA | Interpretation |
|------:|-------------------|------------------|-----------------|----------------|
| 5 | worst area; worst concave points; mean concave points; worst radius; worst perimeter | None | None | Ranking refinement only. |
| 10 | 9 of 10 features retained | worst concavity | area error | Partial feature replacement at the Top-10 boundary. |
| 15 | All 15 features retained | None | None | Feature set preserved; ranking order changed. |
| 20 | All 20 features retained | None | None | Feature set preserved; ranking order changed. |

## 3.4 Top-K Stability Between RF and RF + DODA

The printed `Top-K Same: False` result reflects exact ordered-list equality, not feature-set equality. A Top-K list can have the same features but still return `False` if their internal order changes.

| Top-K | Common Features | Overlap | Stability | Main Change |
|------:|----------------:|--------:|-----------|-------------|
| 5 | 5 / 5 | 100.0% | Highly Stable | Feature set preserved; worst radius and mean concave points changed order. |
| 10 | 9 / 10 | 90.0% | Highly Stable | worst concavity entered; area error left. |
| 15 | 15 / 15 | 100.0% | Highly Stable | Feature set preserved; internal ordering changed. |
| 20 | 20 / 20 | 100.0% | Highly Stable | Feature set preserved; internal ordering changed. |

Ranking stability refers to whether features remain in the same order. Feature-set stability refers to whether the same features are selected regardless of order. In this experiment, ranking stability changed, but feature-set stability was high.

# 4. Predictive Performance Comparison

The following tables compare Random Forest baseline feature selection with RF + DODA feature selection using the executed notebook outputs. Values are shown as `baseline -> DODA`.

## 4.1 Logistic Regression Results

| Top-K | Accuracy | Precision | Recall | F1-score | ROC-AUC | Overall Effect |
|------:|----------|-----------|--------|----------|---------|----------------|
| 5 | 0.939 -> 0.939 | 0.985 -> 0.985 | 0.917 -> 0.917 | 0.950 -> 0.950 | 0.991 -> 0.991 | Maintained / Comparable |
| 10 | 0.947 -> 0.912 | 0.985 -> 0.970 | 0.931 -> 0.889 | 0.957 -> 0.928 | 0.992 -> 0.991 | Reduced |
| 15 | 0.939 -> 0.939 | 0.958 -> 0.958 | 0.944 -> 0.944 | 0.951 -> 0.951 | 0.994 -> 0.994 | Maintained / Comparable |
| 20 | 0.956 -> 0.956 | 0.986 -> 0.986 | 0.944 -> 0.944 | 0.965 -> 0.965 | 0.994 -> 0.994 | Maintained / Comparable |

The best Logistic Regression baseline configuration was Top-K = 20, with Accuracy = 0.956, Recall = 0.944, F1-score = 0.965, and ROC-AUC = 0.994. The best DODA configuration was also Top-K = 20 with the same values. DODA maintained comparable performance at Top-K = 5, 15, and 20, but reduced performance at Top-K = 10.

## 4.2 Random Forest Results

| Top-K | Accuracy | Precision | Recall | F1-score | ROC-AUC | Overall Effect |
|------:|----------|-----------|--------|----------|---------|----------------|
| 5 | 0.921 -> 0.921 | 0.944 -> 0.944 | 0.931 -> 0.931 | 0.937 -> 0.937 | 0.986 -> 0.984 | Maintained / Comparable |
| 10 | 0.956 -> 0.956 | 0.972 -> 0.959 | 0.958 -> 0.972 | 0.965 -> 0.966 | 0.989 -> 0.987 | Improved |
| 15 | 0.956 -> 0.965 | 0.959 -> 0.972 | 0.972 -> 0.972 | 0.966 -> 0.972 | 0.993 -> 0.994 | Improved |
| 20 | 0.956 -> 0.956 | 0.959 -> 0.959 | 0.972 -> 0.972 | 0.966 -> 0.966 | 0.993 -> 0.996 | Maintained / Comparable |

The best Random Forest baseline configurations were Top-K = 15 and Top-K = 20, both with Accuracy = 0.956, Recall = 0.972, and F1-score = 0.966; Top-K = 20 had the higher ROC-AUC. The best DODA Random Forest configuration was Top-K = 15, with Accuracy = 0.965, Recall = 0.972, F1-score = 0.972, and ROC-AUC = 0.994. DODA improved Random Forest performance most clearly at Top-K = 15.

## 4.3 XGBoost Results

| Top-K | Accuracy | Precision | Recall | F1-score | ROC-AUC | Overall Effect |
|------:|----------|-----------|--------|----------|---------|----------------|
| 5 | 0.921 -> 0.921 | 0.944 -> 0.944 | 0.931 -> 0.931 | 0.937 -> 0.937 | 0.982 -> 0.982 | Maintained / Comparable |
| 10 | 0.956 -> 0.965 | 0.959 -> 0.959 | 0.972 -> 0.986 | 0.966 -> 0.973 | 0.982 -> 0.991 | Improved |
| 15 | 0.947 -> 0.956 | 0.958 -> 0.959 | 0.958 -> 0.972 | 0.958 -> 0.966 | 0.995 -> 0.996 | Improved |
| 20 | 0.947 -> 0.947 | 0.946 -> 0.946 | 0.972 -> 0.972 | 0.959 -> 0.959 | 0.995 -> 0.997 | Maintained / Comparable |

The best XGBoost baseline configuration by F1-score was Top-K = 10. The best XGBoost DODA configuration was also Top-K = 10, with Accuracy = 0.965, Recall = 0.986, F1-score = 0.973, and ROC-AUC = 0.991. XGBoost appeared sensitive to the DODA ranking at Top-K = 10 and Top-K = 15, where both recall and F1-score improved.

## 4.4 Best Performing Configurations

| Category | Configuration | Accuracy | Recall | F1-score | ROC-AUC |
|----------|---------------|---------:|-------:|---------:|--------:|
| Best RF baseline configuration | Random Forest baseline, Random Forest, Top-K = 20 | 0.956 | 0.972 | 0.966 | 0.993 |
| Best RF + DODA configuration | RF + DODA, XGBoost, Top-K = 10 | 0.965 | 0.986 | 0.973 | 0.991 |
| Highest Accuracy | RF + DODA, Random Forest, Top-K = 15; RF + DODA, XGBoost, Top-K = 10 | 0.965 | 0.972 / 0.986 | 0.972 / 0.973 | 0.994 / 0.991 |
| Highest Recall | RF + DODA, XGBoost, Top-K = 10 | 0.965 | 0.986 | 0.973 | 0.991 |
| Highest F1-score | RF + DODA, XGBoost, Top-K = 10 | 0.965 | 0.986 | 0.973 | 0.991 |
| Highest ROC-AUC | RF + DODA, XGBoost, Top-K = 20 | 0.947 | 0.972 | 0.959 | 0.997 |

## 4.5 Importance of Accuracy, Recall, and F1-score

Accuracy is important because it summarizes the overall proportion of correctly classified samples. Recall is particularly important in this breast cancer classification setting because missed positive cases can be clinically serious. F1-score is useful because it balances Precision and Recall rather than emphasizing only one of them.

The strongest balance of these metrics was observed for RF + DODA with XGBoost at Top-K = 10, which achieved Accuracy = 0.965, Recall = 0.986, and F1-score = 0.973. RF + DODA with Random Forest at Top-K = 15 also showed a strong balance, with Accuracy = 0.965, Recall = 0.972, and F1-score = 0.972.

# 5. Effect of Clinical Knowledge

Clinical weighting affected the Random Forest ranking by reducing the scores of features with lower clinical weights and preserving the scores of features with weight 1.0. This promoted features such as worst radius, worst concavity, worst compactness, mean compactness, worst symmetry, and mean symmetry. It demoted features such as mean concave points, area error, radius error, worst texture, texture error, and fractal dimension error.

DODA preserved the strongest statistically important features: worst area, worst concave points, worst radius, mean concave points, worst perimeter, mean concavity, mean perimeter, and mean radius all remained highly ranked. The only Top-10 feature-set replacement was worst concavity entering in place of area error.

The results suggest that clinical knowledge mainly refined the ranking rather than substantially replacing the Random Forest feature set. However, a higher DODA rank should not be interpreted as proof that a feature is independently more predictive. The mathematical feature importance, clinical weighting, and downstream predictive performance are related but distinct components of the experiment.

Performance changes were not consistently positive. DODA improved selected Random Forest and XGBoost configurations, preserved several configurations, and reduced Logistic Regression performance at Top-K = 10.

# 6. Main Findings

| Finding | Observation |
|---------|-------------|
| Strongest RF baseline configuration | Random Forest with Random Forest Top-K = 20 achieved a strong baseline balance: Accuracy = 0.956, Recall = 0.972, F1-score = 0.966, and ROC-AUC = 0.993. |
| Strongest RF + DODA configuration | XGBoost with RF + DODA Top-K = 10 achieved Accuracy = 0.965, Recall = 0.986, F1-score = 0.973. |
| Highest Accuracy | 0.965, achieved by RF + DODA Random Forest Top-K = 15 and RF + DODA XGBoost Top-K = 10. |
| Highest Recall | 0.986, achieved by RF + DODA XGBoost Top-K = 10. |
| Highest F1-score | 0.973, achieved by RF + DODA XGBoost Top-K = 10. |
| Strongest DODA improvement | XGBoost Top-K = 10 improved Accuracy from 0.956 to 0.965, Recall from 0.972 to 0.986, and F1-score from 0.966 to 0.973. |
| Largest performance reduction | Logistic Regression Top-K = 10 declined from Accuracy = 0.947, Recall = 0.931, F1-score = 0.957 to Accuracy = 0.912, Recall = 0.889, F1-score = 0.928. |
| Top-K stability pattern | Feature-set overlap was 100% for Top-K = 5, 15, and 20, and 90% for Top-K = 10. |
| Main feature-ranking change | worst radius moved above mean concave points; worst concavity moved into the Top-10 while area error moved out. |
| Overall effect of clinical knowledge | Clinical knowledge produced meaningful ranking refinement, but its predictive effect was model- and Top-K-dependent. |

# 7. Research Interpretation

These results do not show that incorporating clinical knowledge through DODA consistently improves predictive performance. The evidence is more nuanced. DODA preserved performance in several configurations, improved selected Random Forest and XGBoost configurations, and reduced Logistic Regression performance at Top-K = 10.

The effect depended on both Top-K and downstream model. XGBoost showed the clearest gains at Top-K = 10 and Top-K = 15, while Random Forest improved most clearly at Top-K = 15. Logistic Regression was largely unchanged except for a reduction at Top-K = 10.

From a feature-selection perspective, DODA acted mainly as a ranking refinement method. It preserved most of the Random Forest-derived feature set while adjusting the internal order according to clinical weights. The experiment therefore supports the potential usefulness of clinical weighting, but only as a cautious, dataset-specific finding rather than evidence of general superiority.

# 8. Conclusion

RF + DODA did not consistently improve predictive performance across all models and Top-K values. It preserved performance in several configurations and improved selected Random Forest and XGBoost results, especially RF + DODA with XGBoost at Top-K = 10 and RF + DODA with Random Forest at Top-K = 15.

The feature ranking changed meaningfully, but the selected Top-K feature sets remained highly stable. The Top-5, Top-15, and Top-20 sets were fully preserved, while the Top-10 set changed by one feature. Clinical weighting therefore produced ranking refinement rather than a substantial replacement of the Random Forest-derived features.

The main limitation is that this experiment is based on one breast cancer dataset and one evaluation split, so it does not establish statistical significance or broader generalization. In this experiment, incorporating clinical knowledge through DODA primarily refined the Random Forest feature ranking, with predictive effects that were dependent on the model and Top-K setting rather than uniformly beneficial.