In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/heartdisease_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 303
Columns : 14

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

target_column = "target"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]


print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")


display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 303
Columns : 13

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 303

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================

print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

target
0    164
1    139
Name: count, dtype: int64

Class Percentage

target
0    54.13
1    45.87
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================

print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

         Data Type
age        float64
sex        float64
cp         float64
trestbps   float64
chol       float64
fbs        float64
restecg    float64
thalach    float64
exang      float64
oldpeak    float64
slope      float64
ca         float64
thal       float64

In [5]:
# =============================================================================
# STEP 5: MISSING VALUE CHECK
# =============================================================================

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)


missing = pd.DataFrame({
    "Missing Count": X.isnull().sum(),
    "Missing Percentage (%)": (
        X.isnull().mean() * 100
    ).round(2)
})


display(
    missing[missing["Missing Count"] > 0]
)

======================================================================
MISSING VALUES
======================================================================

      Missing Count  Missing Percentage (%)
ca                4                    1.32
thal              2                    0.66

In [6]:
# =============================================================================
# STEP 6: MISSING VALUE IMPUTATION
# =============================================================================

from sklearn.impute import SimpleImputer


imputer = SimpleImputer(
    strategy="median"
)


X_imputed = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index=X.index
)


print("=" * 70)
print("MISSING VALUE IMPUTATION")
print("=" * 70)

print("Imputation completed successfully")


print("\nRemaining Missing Values:")
print(X_imputed.isnull().sum().sum())

======================================================================
MISSING VALUE IMPUTATION
======================================================================
Imputation completed successfully

Remaining Missing Values:
0

In [7]:
# =============================================================================
# STEP 7: TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X_imputed,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (242, 13)
y_train shape : (242,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (61, 13)
y_test shape  : (61,)

In [8]:
# =============================================================================
# STEP 8: CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================

print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True) * 100)
    .round(2)
)


print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

target
0    54.13
1    45.87
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

target
0    54.1
1    45.9
Name: proportion, dtype: float64

In [9]:
# =============================================================================
# STEP 9: FEATURE SCALING
# =============================================================================

from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


scaler = StandardScaler()


# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(
    X_train
)


# Transform test data
X_test_scaled = scaler.transform(
    X_test
)


print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(
    f"X_train_scaled shape : {X_train_scaled.shape}"
)

print(
    f"X_test_scaled shape  : {X_test_scaled.shape}"
)

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (242, 13)
X_test_scaled shape  : (61, 13)

In [10]:
# =============================================================================
# STEP 10: CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)


print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(
    X_train_scaled.head()
)

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973

In [11]:
# =============================================================================
# STEP 11: SCALING VERIFICATION
# =============================================================================

print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.mean().round(2)
)


print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

age        -0.0
sex         0.0
cp          0.0
trestbps   -0.0
chol        0.0
fbs        -0.0
restecg     0.0
thalach    -0.0
exang       0.0
oldpeak     0.0
slope      -0.0
ca          0.0
thal        0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

age         1.0
sex         1.0
cp          1.0
trestbps    1.0
chol        1.0
fbs         1.0
restecg     1.0
thalach     1.0
exang       1.0
oldpeak     1.0
slope       1.0
ca          1.0
thal        1.0
dtype: float64

In [12]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 1: IMPORTS
# =============================================================================

import numpy as np
import pandas as pd

# -----------------------------------------------------------------------------
# Scikit-learn
# -----------------------------------------------------------------------------

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# -----------------------------------------------------------------------------
# Boruta
# -----------------------------------------------------------------------------

from boruta import BorutaPy

# -----------------------------------------------------------------------------
# mRMR
# -----------------------------------------------------------------------------

from mrmr import mrmr_classif

# -----------------------------------------------------------------------------
# DODA
# -----------------------------------------------------------------------------

from doda import DODASelector
from doda.adapters import SklearnAdapter
from doda.knowledge.providers import JSONProvider
from doda.fusion import RankFusion
from doda.aggregation import MeanAggregator

In [13]:
# =============================================================================
# MRMR ADAPTER
# =============================================================================

class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # ---------------------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # ---------------------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # ---------------------------------------------------------------------
        # Store importance
        # ---------------------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"

In [14]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 2: CREATE ALL SELECTOR OPERATORS
# =============================================================================

# -----------------------------------------------------------------------------
# 1. ANOVA
# -----------------------------------------------------------------------------

anova_operator = SklearnAdapter(
    SelectKBest(
        score_func=f_classif,
        k="all"
    )
)


# -----------------------------------------------------------------------------
# 2. LASSO
# -----------------------------------------------------------------------------

lasso_model = LogisticRegression(
    penalty="l1",
    solver="liblinear",
    max_iter=5000,
    random_state=42
)

lasso_operator = SklearnAdapter(
    lasso_model
)


# -----------------------------------------------------------------------------
# 3. mRMR
# -----------------------------------------------------------------------------

mrmr_operator = MRMRAdapter()


# -----------------------------------------------------------------------------
# 4. Random Forest
# -----------------------------------------------------------------------------

rf_operator = SklearnAdapter(
    RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    )
)


# -----------------------------------------------------------------------------
# 5. Boruta
# -----------------------------------------------------------------------------

rf_boruta = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

boruta = BorutaPy(
    estimator=rf_boruta,
    n_estimators="auto",
    max_iter=100,
    perc=100,
    random_state=42,
    verbose=0
)

boruta_operator = SklearnAdapter(
    boruta
)


print("All 5 selector operators created successfully.")

All 5 selector operators created successfully.

In [15]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 3: CREATE MEAN AGGREGATOR
# =============================================================================

aggregator = MeanAggregator()

print("MeanAggregator created successfully.")

MeanAggregator created successfully.

In [16]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 4: CLINICAL KNOWLEDGE + FUSION
# =============================================================================

provider = JSONProvider("heartdisease_weights.json")

fusion = RankFusion()

print("Clinical provider and RankFusion created successfully.")

Clinical provider and RankFusion created successfully.

In [17]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 5: CREATE MULTI-SELECTOR DODA
# =============================================================================

operators = [
    anova_operator,
    lasso_operator,
    mrmr_operator,
    rf_operator,
    boruta_operator
]

selector = DODASelector(
    operators=operators,
    aggregator=aggregator,
    provider=provider,
    fusion=fusion,
    top_k=5
)

print("Multi-selector DODA created successfully.")
print("Number of operators:", len(selector.operators))

Multi-selector DODA created successfully.
Number of operators: 5

In [18]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 6: FIT DODA + SELECT TOP-5 FEATURES
# =============================================================================

X_train_selected = selector.fit_transform(
    X_train_scaled,
    y_train
)

selected_features = selector.get_selected_features()

print("Selected features:", selected_features)
print("Number of selected features:", len(selected_features))
print("Selected data shape:", X_train_selected.shape)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F94AD98C20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Running: LogisticRegression
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of coefficients: 13
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.78it/s]

Running: RandomForestClassifier
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of feature importances: 13
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}, 'LogisticRegression_2': {'age': np.float64(0.040879670492979414), 'sex': np.float64(0.6202444908214807), 'cp': np.float64(0.5265548683474585), 'trestbps': np.float64(0.2648403676587003), 'chol': np.float64(0.17260487803047), 'fbs': np.float64(0.18741924893453896), 'restecg': np.float64(0.19653776709342824), 'thalach': np.float64(0.30336053270752145), 'exang': np.float64(0.37429935034835576), 'oldpeak': np.float64(0.13229165615287652), 'slope': np.float64(0.33771002172107784), 'ca': np.float64(1.0902287388613396), 'thal': np.float64(0.6837896915622799)}, 'MRMR_3': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}, 'RandomForestClassifier_4': {'age': np.float64(0.0966735741067629), 'sex': np.float64(0.04097798577342465), 'cp': np.float64(0.1165744623287366), 'trestbps': np.float64(0.07829131674305914), 'chol': np.float64(0.08427654782893294), 'fbs': np.float64(0.01137173061045471), 'restecg': np.float64(0.022061148446768607), 'thalach': np.float64(0.1206280324818276), 'exang': np.float64(0.051814045539448746), 'oldpeak': np.float64(0.09029189464775904), 'slope': np.float64(0.04363740284934486), 'ca': np.float64(0.10506181498012705), 'thal': np.float64(0.1383400436633532)}, 'BorutaPy_5': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 5 operators

Raw Mathematical Scores
{'age': np.float64(2.4960932396995608), 'sex': np.float64(5.347109796254786), 'cp': np.float64(9.659129632748837), 'trestbps': np.float64(1.0704684252069634), 'chol': np.float64(0.46986404874498283), 'fbs': np.float64(0.18143264827131514), 'restecg': np.float64(1.4161746735326197), 'thalach': np.float64(10.07730127561296), 'exang': np.float64(10.618501916942414), 'oldpeak': np.float64(9.07521457037907), 'slope': np.float64(5.813202214435795), 'ca': np.float64(12.674151267700173), 'thal': np.float64(20.770908361595186)}

Normalized Mathematical Scores
{'age': np.float64(0.12017256040254674), 'sex': np.float64(0.2574326410366067), 'cp': np.float64(0.465031642554848), 'trestbps': np.float64(0.05153690953575381), 'chol': np.float64(0.022621256642475395), 'fbs': np.float64(0.008734940480830337), 'restecg': np.float64(0.0681806808291103), 'thalach': np.float64(0.4851642065999194), 'exang': np.float64(0.5112199106600326), 'oldpeak': np.float64(0.43691948432832534), 'slope': np.float64(0.2798723153188735), 'ca': np.float64(0.6101876262250675), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Number of selected features: 5
Selected data shape: (242, 5)

In [19]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 7: TRANSFORM TEST DATA
# =============================================================================

X_test_selected = selector.transform(X_test_scaled)

print("Test data shape:", X_test_selected.shape)
print("Selected features:", selector.get_selected_features())

Test data shape: (61, 5)
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak']

In [20]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 8: LOGISTIC REGRESSION EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

lr_model = LogisticRegression(
    max_iter=5000,
    random_state=42
)

lr_model.fit(X_train_selected, y_train)

y_pred = lr_model.predict(X_test_selected)
y_prob = lr_model.predict_proba(X_test_selected)[:, 1]

lr_results = {
    "Method": "DODA Multi-Selector",
    "Top_K": 5,
    "Model": "Logistic Regression",
    "Selected Features": ", ".join(selector.get_selected_features()),
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
}

pd.DataFrame([lr_results])

,Method,Top_K,Model,Selected Features,Accuracy,Precision,Recall,F1,ROC-AUC
0,DODA Multi-Selector,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476

In [21]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 9: RANDOM FOREST EVALUATION
# =============================================================================

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train_selected, y_train)

y_pred = rf_model.predict(X_test_selected)
y_prob = rf_model.predict_proba(X_test_selected)[:, 1]

rf_results = {
    "Method": "DODA Multi-Selector",
    "Top_K": 5,
    "Model": "Random Forest",
    "Selected Features": ", ".join(selector.get_selected_features()),
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
}

pd.DataFrame([rf_results])

,Method,Top_K,Model,Selected Features,Accuracy,Precision,Recall,F1,ROC-AUC
0,DODA Multi-Selector,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.885281

In [22]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 10: XGBOOST EVALUATION
# =============================================================================

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=3,
    learning_rate=0.05,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train_selected, y_train)

y_pred = xgb_model.predict(X_test_selected)
y_prob = xgb_model.predict_proba(X_test_selected)[:, 1]

xgb_results = {
    "Method": "DODA Multi-Selector",
    "Top_K": 5,
    "Model": "XGBoost",
    "Selected Features": ", ".join(selector.get_selected_features()),
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob)
}

pd.DataFrame([xgb_results])

,Method,Top_K,Model,Selected Features,Accuracy,Precision,Recall,F1,ROC-AUC
0,DODA Multi-Selector,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.819672,0.793103,0.821429,0.807018,0.936147

In [23]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 11: RUN DODA FOR ALL TOP-K VALUES
# =============================================================================

k_values = [5, 8, 10, 13]

multi_doda_results = {}

for k in k_values:

    print(f"\n{'='*60}")
    print(f"Running Multi-Selector DODA — Top-{k}")
    print(f"{'='*60}")

    selector_k = DODASelector(
        operators=[
            anova_operator,
            lasso_operator,
            mrmr_operator,
            rf_operator,
            boruta_operator
        ],
        aggregator=MeanAggregator(),
        provider=provider,
        fusion=RankFusion(),
        top_k=k
    )

    X_train_k = selector_k.fit_transform(
        X_train_scaled,
        y_train
    )

    X_test_k = selector_k.transform(
        X_test_scaled
    )

    multi_doda_results[k] = {
        "selector": selector_k,
        "X_train": X_train_k,
        "X_test": X_test_k,
        "features": selector_k.get_selected_features()
    }

    print("Selected features:", selector_k.get_selected_features())
    print("Train shape:", X_train_k.shape)
    print("Test shape:", X_test_k.shape)

============================================================
Running Multi-Selector DODA — Top-5
============================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F94AD98C20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Running: LogisticRegression
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of coefficients: 13
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.16it/s]

Running: RandomForestClassifier
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of feature importances: 13
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}, 'LogisticRegression_2': {'age': np.float64(0.040879670492979414), 'sex': np.float64(0.6202444908214807), 'cp': np.float64(0.5265548683474585), 'trestbps': np.float64(0.2648403676587003), 'chol': np.float64(0.17260487803047), 'fbs': np.float64(0.18741924893453896), 'restecg': np.float64(0.19653776709342824), 'thalach': np.float64(0.30336053270752145), 'exang': np.float64(0.37429935034835576), 'oldpeak': np.float64(0.13229165615287652), 'slope': np.float64(0.33771002172107784), 'ca': np.float64(1.0902287388613396), 'thal': np.float64(0.6837896915622799)}, 'MRMR_3': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}, 'RandomForestClassifier_4': {'age': np.float64(0.0966735741067629), 'sex': np.float64(0.04097798577342465), 'cp': np.float64(0.1165744623287366), 'trestbps': np.float64(0.07829131674305914), 'chol': np.float64(0.08427654782893294), 'fbs': np.float64(0.01137173061045471), 'restecg': np.float64(0.022061148446768607), 'thalach': np.float64(0.1206280324818276), 'exang': np.float64(0.051814045539448746), 'oldpeak': np.float64(0.09029189464775904), 'slope': np.float64(0.04363740284934486), 'ca': np.float64(0.10506181498012705), 'thal': np.float64(0.1383400436633532)}, 'BorutaPy_5': {'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 5 operators

Raw Mathematical Scores
{'age': np.float64(2.3960932396995607), 'sex': np.float64(5.3423478914928815), 'cp': np.float64(9.659129632748837), 'trestbps': np.float64(1.0704684252069634), 'chol': np.float64(0.4365307154116495), 'fbs': np.float64(0.17865487049353734), 'restecg': np.float64(1.4126032449611912), 'thalach': np.float64(10.07730127561296), 'exang': np.float64(10.601835250275746), 'oldpeak': np.float64(9.07521457037907), 'slope': np.float64(5.806535547769128), 'ca': np.float64(12.674151267700173), 'thal': np.float64(20.770908361595186)}

Normalized Mathematical Scores
{'age': np.float64(0.11535813446319317), 'sex': np.float64(0.25720338265854226), 'cp': np.float64(0.465031642554848), 'trestbps': np.float64(0.05153690953575381), 'chol': np.float64(0.0210164479960242), 'fbs': np.float64(0.008601206426959404), 'restecg': np.float64(0.06800873704556196), 'thalach': np.float64(0.4851642065999194), 'exang': np.float64(0.5104175063368069), 'oldpeak': np.float64(0.43691948432832534), 'slope': np.float64(0.2795513535895833), 'ca': np.float64(0.6101876262250675), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Train shape: (242, 5)
Test shape: (61, 5)

============================================================
Running Multi-Selector DODA — Top-8
============================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F94AD98C20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Running: LogisticRegression
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of coefficients: 13
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.29it/s]

Running: RandomForestClassifier
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of feature importances: 13
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}, 'LogisticRegression_2': {'age': np.float64(0.040879670492979414), 'sex': np.float64(0.6202444908214807), 'cp': np.float64(0.5265548683474585), 'trestbps': np.float64(0.2648403676587003), 'chol': np.float64(0.17260487803047), 'fbs': np.float64(0.18741924893453896), 'restecg': np.float64(0.19653776709342824), 'thalach': np.float64(0.30336053270752145), 'exang': np.float64(0.37429935034835576), 'oldpeak': np.float64(0.13229165615287652), 'slope': np.float64(0.33771002172107784), 'ca': np.float64(1.0902287388613396), 'thal': np.float64(0.6837896915622799)}, 'MRMR_3': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}, 'RandomForestClassifier_4': {'age': np.float64(0.0966735741067629), 'sex': np.float64(0.04097798577342465), 'cp': np.float64(0.1165744623287366), 'trestbps': np.float64(0.07829131674305914), 'chol': np.float64(0.08427654782893294), 'fbs': np.float64(0.01137173061045471), 'restecg': np.float64(0.022061148446768607), 'thalach': np.float64(0.1206280324818276), 'exang': np.float64(0.051814045539448746), 'oldpeak': np.float64(0.09029189464775904), 'slope': np.float64(0.04363740284934486), 'ca': np.float64(0.10506181498012705), 'thal': np.float64(0.1383400436633532)}, 'BorutaPy_5': {'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.2), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 5 operators

Raw Mathematical Scores
{'age': np.float64(2.3960932396995607), 'sex': np.float64(5.3423478914928815), 'cp': np.float64(9.659129632748837), 'trestbps': np.float64(1.0604684252069636), 'chol': np.float64(0.4365307154116495), 'fbs': np.float64(0.17865487049353734), 'restecg': np.float64(1.4126032449611912), 'thalach': np.float64(10.07730127561296), 'exang': np.float64(10.601835250275746), 'oldpeak': np.float64(9.07521457037907), 'slope': np.float64(5.806535547769128), 'ca': np.float64(12.674151267700173), 'thal': np.float64(20.770908361595186)}

Normalized Mathematical Scores
{'age': np.float64(0.11535813446319317), 'sex': np.float64(0.25720338265854226), 'cp': np.float64(0.465031642554848), 'trestbps': np.float64(0.05105546694181846), 'chol': np.float64(0.0210164479960242), 'fbs': np.float64(0.008601206426959404), 'restecg': np.float64(0.06800873704556196), 'thalach': np.float64(0.4851642065999194), 'exang': np.float64(0.5104175063368069), 'oldpeak': np.float64(0.43691948432832534), 'slope': np.float64(0.2795513535895833), 'ca': np.float64(0.6101876262250675), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age']
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age']
Train shape: (242, 8)
Test shape: (61, 8)

============================================================
Running Multi-Selector DODA — Top-10
============================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F94AD98C20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Running: LogisticRegression
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of coefficients: 13
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.19it/s]

Running: RandomForestClassifier
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of feature importances: 13
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}, 'LogisticRegression_2': {'age': np.float64(0.040879670492979414), 'sex': np.float64(0.6202444908214807), 'cp': np.float64(0.5265548683474585), 'trestbps': np.float64(0.2648403676587003), 'chol': np.float64(0.17260487803047), 'fbs': np.float64(0.18741924893453896), 'restecg': np.float64(0.19653776709342824), 'thalach': np.float64(0.30336053270752145), 'exang': np.float64(0.37429935034835576), 'oldpeak': np.float64(0.13229165615287652), 'slope': np.float64(0.33771002172107784), 'ca': np.float64(1.0902287388613396), 'thal': np.float64(0.6837896915622799)}, 'MRMR_3': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}, 'RandomForestClassifier_4': {'age': np.float64(0.0966735741067629), 'sex': np.float64(0.04097798577342465), 'cp': np.float64(0.1165744623287366), 'trestbps': np.float64(0.07829131674305914), 'chol': np.float64(0.08427654782893294), 'fbs': np.float64(0.01137173061045471), 'restecg': np.float64(0.022061148446768607), 'thalach': np.float64(0.1206280324818276), 'exang': np.float64(0.051814045539448746), 'oldpeak': np.float64(0.09029189464775904), 'slope': np.float64(0.04363740284934486), 'ca': np.float64(0.10506181498012705), 'thal': np.float64(0.1383400436633532)}, 'BorutaPy_5': {'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 5 operators

Raw Mathematical Scores
{'age': np.float64(2.3960932396995607), 'sex': np.float64(5.3423478914928815), 'cp': np.float64(9.659129632748837), 'trestbps': np.float64(1.0704684252069634), 'chol': np.float64(0.4365307154116495), 'fbs': np.float64(0.17865487049353734), 'restecg': np.float64(1.4126032449611912), 'thalach': np.float64(10.07730127561296), 'exang': np.float64(10.601835250275746), 'oldpeak': np.float64(9.07521457037907), 'slope': np.float64(5.806535547769128), 'ca': np.float64(12.674151267700173), 'thal': np.float64(20.770908361595186)}

Normalized Mathematical Scores
{'age': np.float64(0.11535813446319317), 'sex': np.float64(0.25720338265854226), 'cp': np.float64(0.465031642554848), 'trestbps': np.float64(0.05153690953575381), 'chol': np.float64(0.0210164479960242), 'fbs': np.float64(0.008601206426959404), 'restecg': np.float64(0.06800873704556196), 'thalach': np.float64(0.4851642065999194), 'exang': np.float64(0.5104175063368069), 'oldpeak': np.float64(0.43691948432832534), 'slope': np.float64(0.2795513535895833), 'ca': np.float64(0.6101876262250675), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps']
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps']
Train shape: (242, 10)
Test shape: (61, 10)

============================================================
Running Multi-Selector DODA — Top-13
============================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001F94AD98C20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Running: LogisticRegression
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of coefficients: 13
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.35it/s]

Running: RandomForestClassifier
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of feature importances: 13
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}, 'LogisticRegression_2': {'age': np.float64(0.040879670492979414), 'sex': np.float64(0.6202444908214807), 'cp': np.float64(0.5265548683474585), 'trestbps': np.float64(0.2648403676587003), 'chol': np.float64(0.17260487803047), 'fbs': np.float64(0.18741924893453896), 'restecg': np.float64(0.19653776709342824), 'thalach': np.float64(0.30336053270752145), 'exang': np.float64(0.37429935034835576), 'oldpeak': np.float64(0.13229165615287652), 'slope': np.float64(0.33771002172107784), 'ca': np.float64(1.0902287388613396), 'thal': np.float64(0.6837896915622799)}, 'MRMR_3': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}, 'RandomForestClassifier_4': {'age': np.float64(0.0966735741067629), 'sex': np.float64(0.04097798577342465), 'cp': np.float64(0.1165744623287366), 'trestbps': np.float64(0.07829131674305914), 'chol': np.float64(0.08427654782893294), 'fbs': np.float64(0.01137173061045471), 'restecg': np.float64(0.022061148446768607), 'thalach': np.float64(0.1206280324818276), 'exang': np.float64(0.051814045539448746), 'oldpeak': np.float64(0.09029189464775904), 'slope': np.float64(0.04363740284934486), 'ca': np.float64(0.10506181498012705), 'thal': np.float64(0.1383400436633532)}, 'BorutaPy_5': {'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.2), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 5 operators

Raw Mathematical Scores
{'age': np.float64(2.3960932396995607), 'sex': np.float64(5.3423478914928815), 'cp': np.float64(9.659129632748837), 'trestbps': np.float64(1.0604684252069636), 'chol': np.float64(0.4365307154116495), 'fbs': np.float64(0.17865487049353734), 'restecg': np.float64(1.4126032449611912), 'thalach': np.float64(10.07730127561296), 'exang': np.float64(10.601835250275746), 'oldpeak': np.float64(9.07521457037907), 'slope': np.float64(5.806535547769128), 'ca': np.float64(12.674151267700173), 'thal': np.float64(20.770908361595186)}

Normalized Mathematical Scores
{'age': np.float64(0.11535813446319317), 'sex': np.float64(0.25720338265854226), 'cp': np.float64(0.465031642554848), 'trestbps': np.float64(0.05105546694181846), 'chol': np.float64(0.0210164479960242), 'fbs': np.float64(0.008601206426959404), 'restecg': np.float64(0.06800873704556196), 'thalach': np.float64(0.4851642065999194), 'exang': np.float64(0.5104175063368069), 'oldpeak': np.float64(0.43691948432832534), 'slope': np.float64(0.2795513535895833), 'ca': np.float64(0.6101876262250675), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']
Selected features: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']
Train shape: (242, 13)
Test shape: (61, 13)

In [24]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 12: EVALUATE ALL TOP-K VALUES
# =============================================================================

evaluation_results = []

for k in k_values:

    X_train_k = multi_doda_results[k]["X_train"]
    X_test_k = multi_doda_results[k]["X_test"]
    features_k = multi_doda_results[k]["features"]

    models = {
        "Logistic Regression": LogisticRegression(
            max_iter=5000,
            random_state=42
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            class_weight="balanced"
        ),
        "XGBoost": XGBClassifier(
            n_estimators=200,
            max_depth=3,
            learning_rate=0.05,
            random_state=42,
            eval_metric="logloss"
        )
    }

    for model_name, model in models.items():

        model.fit(X_train_k, y_train)

        y_pred = model.predict(X_test_k)
        y_prob = model.predict_proba(X_test_k)[:, 1]

        evaluation_results.append({
            "Method": "DODA Multi-Selector",
            "Top_K": k,
            "Model": model_name,
            "Selected Features": ", ".join(features_k),
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred),
            "Recall": recall_score(y_test, y_pred),
            "F1": f1_score(y_test, y_pred),
            "ROC-AUC": roc_auc_score(y_test, y_prob)
        })

doda_multi_results_df = pd.DataFrame(evaluation_results)

doda_multi_results_df

,Method,Top_K,Model,Selected Features,Accuracy,Precision,Recall,F1,ROC-AUC
0,DODA Multi-Selector,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476
1,DODA Multi-Selector,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.885281
2,DODA Multi-Selector,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.819672,0.793103,0.821429,0.807018,0.936147
3,DODA Multi-Selector,8,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.885246,0.838710,0.928571,0.881356,0.939394
4,DODA Multi-Selector,8,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.901639,0.843750,0.964286,0.900000,0.958874
5,DODA Multi-Selector,8,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.852459,0.806452,0.892857,0.847458,0.942641
6,DODA Multi-Selector,10,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.944805
7,DODA Multi-Selector,10,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.901639,0.843750,0.964286,0.900000,0.954545
8,DODA Multi-Selector,10,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.836066,0.764706,0.928571,0.838710,0.955628
9,DODA Multi-Selector,13,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.951299
10,DODA Multi-Selector,13,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.918033,0.870968,0.964286,0.915254,0.957251
11,DODA Multi-Selector,13,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.938312

In [25]:
# =============================================================================
# MULTI-SELECTOR DODA — HEART DISEASE
# STEP 13: FINAL FEATURE RANKING
# =============================================================================

final_selector = multi_doda_results[13]["selector"]

feature_ranking_df = final_selector.compare_scores()

feature_ranking_df

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
     Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0       thal          1              5           1            0
1         ca          2              4           2            0
2      exang          3              2           3            0
3         cp          5              1           4            1
4    oldpeak          6              3           5            1
5    thalach          4             11           6           -2
6      slope          7              8           7            0
7        age          9              6           8            1
8        sex          8             12           9           -1
9   trestbps         11              7          10            1
10   restecg         10             10          11           -1
11      chol         12              9          12            0
12       fbs         13             13          13            0

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,thal,1,1.0000,5,1.0,1,0.0328,0
1,ca,2,0.6102,4,1.0,2,0.0325,0
2,exang,3,0.5104,2,1.0,3,0.0323,0
3,cp,5,0.4650,1,1.0,4,0.0318,1
4,oldpeak,6,0.4369,3,1.0,5,0.0315,1
5,thalach,4,0.4852,11,0.8,6,0.0315,-2
6,slope,7,0.2796,8,0.9,7,0.0311,0
7,age,9,0.1154,6,0.9,8,0.0306,1
8,sex,8,0.2572,12,0.6,9,0.0303,-1
9,trestbps,11,0.0511,7,0.9,10,0.0302,1
10,restecg,10,0.0680,10,0.8,11,0.0302,-1
11,chol,12,0.0210,9,0.8,12,0.0298,0
12,fbs,13,0.0086,13,0.6,13,0.0293,0