In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/heartdisease_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 303
Columns : 14

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

target_column = "target"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]


print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")


display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 303
Columns : 13

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 303

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================

print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

target
0    164
1    139
Name: count, dtype: int64

Class Percentage

target
0    54.13
1    45.87
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================

print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

         Data Type
age        float64
sex        float64
cp         float64
trestbps   float64
chol       float64
fbs        float64
restecg    float64
thalach    float64
exang      float64
oldpeak    float64
slope      float64
ca         float64
thal       float64

In [5]:
# =============================================================================
# STEP 5: MISSING VALUE CHECK
# =============================================================================

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)


missing = pd.DataFrame({
    "Missing Count": X.isnull().sum(),
    "Missing Percentage (%)": (
        X.isnull().mean() * 100
    ).round(2)
})


display(
    missing[missing["Missing Count"] > 0]
)

======================================================================
MISSING VALUES
======================================================================

      Missing Count  Missing Percentage (%)
ca                4                    1.32
thal              2                    0.66

In [6]:
# =============================================================================
# STEP 6: MISSING VALUE IMPUTATION
# =============================================================================

from sklearn.impute import SimpleImputer


imputer = SimpleImputer(
    strategy="median"
)


X_imputed = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index=X.index
)


print("=" * 70)
print("MISSING VALUE IMPUTATION")
print("=" * 70)

print("Imputation completed successfully")


print("\nRemaining Missing Values:")
print(X_imputed.isnull().sum().sum())

======================================================================
MISSING VALUE IMPUTATION
======================================================================
Imputation completed successfully

Remaining Missing Values:
0

In [7]:
# =============================================================================
# STEP 7: TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X_imputed,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (242, 13)
y_train shape : (242,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (61, 13)
y_test shape  : (61,)

In [8]:
# =============================================================================
# STEP 8: CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================

print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True) * 100)
    .round(2)
)


print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

target
0    54.13
1    45.87
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

target
0    54.1
1    45.9
Name: proportion, dtype: float64

In [9]:
# =============================================================================
# STEP 9: FEATURE SCALING
# =============================================================================

from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


scaler = StandardScaler()


# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(
    X_train
)


# Transform test data
X_test_scaled = scaler.transform(
    X_test
)


print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(
    f"X_train_scaled shape : {X_train_scaled.shape}"
)

print(
    f"X_test_scaled shape  : {X_test_scaled.shape}"
)

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (242, 13)
X_test_scaled shape  : (61, 13)

In [10]:
# =============================================================================
# STEP 10: CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)


print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(
    X_train_scaled.head()
)

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973

In [11]:
# =============================================================================
# STEP 11: SCALING VERIFICATION
# =============================================================================

print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.mean().round(2)
)


print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

age        -0.0
sex         0.0
cp          0.0
trestbps   -0.0
chol        0.0
fbs        -0.0
restecg     0.0
thalach    -0.0
exang       0.0
oldpeak     0.0
slope      -0.0
ca          0.0
thal        0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

age         1.0
sex         1.0
cp          1.0
trestbps    1.0
chol        1.0
fbs         1.0
restecg     1.0
thalach     1.0
exang       1.0
oldpeak     1.0
slope       1.0
ca          1.0
thal        1.0
dtype: float64

# BORUTA

## 1. Baseline

In [14]:
# =============================================================================
# BORUTA BASELINE FEATURE SELECTION (TOP-K = 5,8,10,13)
# =============================================================================

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy


# =============================================================================
# Prepare training data
# =============================================================================

X_train_boruta = X_train_scaled.copy()

y_train_boruta = np.asarray(y_train)


# =============================================================================
# Random Forest estimator for Boruta
# =============================================================================

rf_boruta = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)


# =============================================================================
# Initialize Boruta
# =============================================================================

boruta_selector = BorutaPy(
    estimator=rf_boruta,
    n_estimators="auto",
    max_iter=100,
    random_state=42,
    verbose=0
)


# =============================================================================
# Run Boruta
# =============================================================================

boruta_selector.fit(
    X_train_boruta.values,
    y_train_boruta
)


# =============================================================================
# Create Boruta ranking
# =============================================================================

boruta_scores = pd.DataFrame({
    "Feature": X_train_boruta.columns,
    "Boruta Rank": boruta_selector.ranking_,
    "Confirmed": boruta_selector.support_,
    "Tentative": boruta_selector.support_weak_
})


# =============================================================================
# Sort according to Boruta ranking
# =============================================================================

boruta_scores = boruta_scores.sort_values(
    by=["Boruta Rank", "Feature"],
    ascending=[True, True]
).reset_index(drop=True)


# Create sequential rank for Top-K selection
boruta_scores["Final Rank"] = (
    np.arange(len(boruta_scores)) + 1
)


# =============================================================================
# Display complete Boruta ranking
# =============================================================================

print("=" * 70)
print("BORUTA FEATURE RANKING")
print("=" * 70)

print(boruta_scores)


# =============================================================================
# Display confirmed and tentative features
# =============================================================================

confirmed_features = boruta_scores[
    boruta_scores["Confirmed"]
]["Feature"].tolist()

tentative_features = boruta_scores[
    boruta_scores["Tentative"]
]["Feature"].tolist()


print("\nConfirmed Features:")
print(confirmed_features)

print("\nTentative Features:")
print(tentative_features)


# =============================================================================
# Top-K values
# =============================================================================

k_values = [5, 8, 10, 13]

boruta_results = {}


for k in k_values:

    # -------------------------------------------------------------------------
    # Select Top-K features
    # -------------------------------------------------------------------------

    top_features = (
        boruta_scores
        .head(k)["Feature"]
        .tolist()
    )


    # -------------------------------------------------------------------------
    # Boolean mask for selecting columns
    # -------------------------------------------------------------------------

    mask = X_train_scaled.columns.isin(
        top_features
    )


    # -------------------------------------------------------------------------
    # Create selected train/test datasets
    # -------------------------------------------------------------------------

    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    # -------------------------------------------------------------------------
    # Store results
    # -------------------------------------------------------------------------

    boruta_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": boruta_scores.head(k).copy()

    }


    # -------------------------------------------------------------------------
    # Print results
    # -------------------------------------------------------------------------

    print("=" * 70)
    print(f"TOP {k} BORUTA FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nRanks:")

    print(
        boruta_scores
        .head(k)
    )

======================================================================
BORUTA FEATURE RANKING
======================================================================
     Feature  Boruta Rank  Confirmed  Tentative  Final Rank
0        age            1       True      False           1
1         ca            1       True      False           2
2         cp            1       True      False           3
3    oldpeak            1       True      False           4
4       thal            1       True      False           5
5    thalach            1       True      False           6
6       chol            2      False      False           7
7      exang            3      False      False           8
8   trestbps            4      False      False           9
9      slope            5      False      False          10
10       sex            6      False      False          11
11   restecg            7      False      False          12
12       fbs            8      False      False          13

Confirmed Features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach']

Tentative Features:
[]
======================================================================
TOP 5 BORUTA FEATURES
======================================================================
['age', 'ca', 'cp', 'oldpeak', 'thal']

Ranks:
   Feature  Boruta Rank  Confirmed  Tentative  Final Rank
0      age            1       True      False           1
1       ca            1       True      False           2
2       cp            1       True      False           3
3  oldpeak            1       True      False           4
4     thal            1       True      False           5
======================================================================
TOP 8 BORUTA FEATURES
======================================================================
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'chol', 'exang']

Ranks:
   Feature  Boruta Rank  Confirmed  Tentative  Final Rank
0      age            1       True      False           1
1       ca            1       True      False           2
2       cp            1       True      False           3
3  oldpeak            1       True      False           4
4     thal            1       True      False           5
5  thalach            1       True      False           6
6     chol            2      False      False           7
7    exang            3      False      False           8
======================================================================
TOP 10 BORUTA FEATURES
======================================================================
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'chol', 'exang', 'trestbps', 'slope']

Ranks:
    Feature  Boruta Rank  Confirmed  Tentative  Final Rank
0       age            1       True      False           1
1        ca            1       True      False           2
2        cp            1       True      False           3
3   oldpeak            1       True      False           4
4      thal            1       True      False           5
5   thalach            1       True      False           6
6      chol            2      False      False           7
7     exang            3      False      False           8
8  trestbps            4      False      False           9
9     slope            5      False      False          10
======================================================================
TOP 13 BORUTA FEATURES
======================================================================
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'chol', 'exang', 'trestbps', 'slope', 'sex', 'restecg', 'fbs']

Ranks:
     Feature  Boruta Rank  Confirmed  Tentative  Final Rank
0        age            1       True      False           1
1         ca            1       True      False           2
2         cp            1       True      False           3
3    oldpeak            1       True      False           4
4       thal            1       True      False           5
5    thalach            1       True      False           6
6       chol            2      False      False           7
7      exang            3      False      False           8
8   trestbps            4      False      False           9
9      slope            5      False      False          10
10       sex            6      False      False          11
11   restecg            7      False      False          12
12       fbs            8      False      False          13

In [15]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [16]:
# =============================================================================
# MODEL EVALUATION — BORUTA
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results_boruta = []


for k in k_values:

    Xtr = boruta_results[k]["X_train"]

    Xts = boruta_results[k]["X_test"]

    features = ", ".join(
        boruta_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        results_boruta.append({

            "Method": "Boruta",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


# =============================================================================
# Convert to DataFrame
# =============================================================================

boruta_evaluation = pd.DataFrame(
    results_boruta
)


# =============================================================================
# Display results
# =============================================================================

display(boruta_evaluation)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta,5,Logistic Regression,"age, ca, cp, oldpeak, thal",0.852459,0.787879,0.928571,0.852459,0.925866
1,Boruta,5,Random Forest,"age, ca, cp, oldpeak, thal",0.803279,0.735294,0.892857,0.806452,0.931277
2,Boruta,5,XGBoost,"age, ca, cp, oldpeak, thal",0.836066,0.764706,0.928571,0.838710,0.943182
3,Boruta,8,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.868852,0.812500,0.928571,0.866667,0.937229
4,Boruta,8,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.901639,0.892857,0.892857,0.892857,0.943182
5,Boruta,8,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.786885,0.741935,0.821429,0.779661,0.891775
6,Boruta,10,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.885246,0.818182,0.964286,0.885246,0.949134
7,Boruta,10,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.833333,0.892857,0.862069,0.932900
8,Boruta,10,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.852459,0.806452,0.892857,0.847458,0.899351
9,Boruta,13,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.812500,0.928571,0.866667,0.950216
10,Boruta,13,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.901639,0.866667,0.928571,0.896552,0.951299
11,Boruta,13,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.812500,0.928571,0.866667,0.906926

In [17]:
boruta_evaluation.to_csv(
    "../../../results/heart_disease/baseline/boruta_baseline_results.csv",
    index=False
)

## 2. Baseline

In [18]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [19]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import RankFusion

In [28]:
# =============================================================================
# BORUTA + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 8, 10, 13]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "heartdisease_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = RankFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

boruta_doda_results = {}


# =============================================================================
# RUN BORUTA + DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"BORUTA + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # Random Forest estimator used internally by Boruta
    # ---------------------------------------------------------------------

    rf_boruta = RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )


    # ---------------------------------------------------------------------
    # Boruta operator
    # ---------------------------------------------------------------------

    boruta = BorutaPy(
        estimator=rf_boruta,
        n_estimators="auto",
        max_iter=100,
        perc=100,
        random_state=42,
        verbose=0
    )


    # ---------------------------------------------------------------------
    # Wrap Boruta as a DODA operator
    # ---------------------------------------------------------------------

    boruta_operator = SklearnAdapter(
        boruta
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[boruta_operator],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for evaluation
    # ---------------------------------------------------------------------

    boruta_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores":
            selector.raw_math_scores_,

        "math_scores":
            selector.math_scores_,

        "clinical_weights":
            selector.clinical_weights_,

        "final_scores":
            selector.final_scores_
    }


print("\n" + "=" * 70)
print("BORUTA + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
BORUTA + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F10B950>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']

Selected Features:
['cp', 'oldpeak', 'ca', 'thal', 'age']

======================================================================
BORUTA + DODA — TOP 8 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F10B950>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol']

Selected Features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol']

======================================================================
BORUTA + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F10B950>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol', 'trestbps', 'slope']

Selected Features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol', 'trestbps', 'slope']

======================================================================
BORUTA + DODA — TOP 13 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F10B950>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol', 'trestbps', 'slope', 'restecg', 'sex', 'fbs']

Selected Features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'exang', 'chol', 'trestbps', 'slope', 'restecg', 'sex', 'fbs']

======================================================================
BORUTA + DODA FEATURE SELECTION COMPLETED
======================================================================

In [29]:
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = boruta_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# Raw mathematical scores
# -------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)


# -------------------------------------------------------------------------
# Normalized mathematical scores
# -------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)


# -------------------------------------------------------------------------
# Combine both
# -------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)


math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)


print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

     Feature  Raw Math Score  Normalized Math Score
0        age        1.000000               1.000000
2         cp        1.000000               1.000000
11        ca        1.000000               1.000000
12      thal        1.000000               1.000000
7    thalach        1.000000               1.000000
9    oldpeak        1.000000               1.000000
4       chol        0.500000               0.500000
8      exang        0.333333               0.333333
3   trestbps        0.250000               0.250000
10     slope        0.200000               0.200000
1        sex        0.166667               0.166667
6    restecg        0.142857               0.142857
5        fbs        0.125000               0.125000

In [30]:
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)


clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)


print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

     Feature  Clinical Weight
2         cp              1.0
9    oldpeak              1.0
11        ca              1.0
12      thal              1.0
8      exang              1.0
10     slope              0.9
0        age              0.9
3   trestbps              0.9
4       chol              0.8
7    thalach              0.8
6    restecg              0.8
1        sex              0.6
5        fbs              0.6

In [31]:
# =============================================================================
# INSPECT FINAL RANK FUSION SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final Rank Fusion Score"
    ]
)


final_scores = final_scores.sort_values(
    by="Final Rank Fusion Score",
    ascending=False
)


print("=" * 70)
print("FINAL RANK FUSION SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL RANK FUSION SCORES
======================================================================

     Feature  Final Rank Fusion Score
2         cp                 0.032787
12      thal                 0.032787
9    oldpeak                 0.032787
11        ca                 0.032787
0        age                 0.032522
7    thalach                 0.032266
8      exang                 0.032266
4       chol                 0.032002
3   trestbps                 0.031754
10     slope                 0.031514
6    restecg                 0.030798
1        sex                 0.030777
5        fbs                 0.030331

In [32]:
# =============================================================================
# SELECTED FEATURES
# =============================================================================

selector.get_selected_features()

['cp',
 'oldpeak',
 'ca',
 'thal',
 'age',
 'thalach',
 'exang',
 'chol',
 'trestbps',
 'slope']

In [33]:
# =============================================================================
# COMPARE RANKINGS
# =============================================================================

comparison = selector.compare_scores()

display(comparison)

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
    Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0        cp          2              1           1            1
1   oldpeak          4              3           2            2
2        ca          5              4           3            2
3      thal          6              5           4            2
4       age          1              6           5           -4
5   thalach          3             11           6           -3
6     exang          8              2           7            1
7      chol          7              9           8           -1
8  trestbps          9              7           9            0
9     slope         10              8          10            0

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,cp,2,1.0000,1,1.0,1,0.0328,1
1,oldpeak,4,1.0000,3,1.0,2,0.0328,2
2,ca,5,1.0000,4,1.0,3,0.0328,2
3,thal,6,1.0000,5,1.0,4,0.0328,2
4,age,1,1.0000,6,0.9,5,0.0325,-4
5,thalach,3,1.0000,11,0.8,6,0.0323,-3
6,exang,8,0.3333,2,1.0,7,0.0323,1
7,chol,7,0.5000,9,0.8,8,0.0320,-1
8,trestbps,9,0.2500,7,0.9,9,0.0318,0
9,slope,10,0.2000,8,0.9,10,0.0315,0
10,restecg,12,0.1429,10,0.8,11,0.0308,1
11,sex,11,0.1667,12,0.6,12,0.0308,-1
12,fbs,13,0.1250,13,0.6,13,0.0303,0

In [34]:
# =============================================================================
#  MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression":
        LogisticRegression(
            max_iter=1000,
            random_state=42
        ),


    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),


    "XGBoost":
        XGBClassifier(
            n_estimators=200,
            random_state=42,
            eval_metric="logloss"
        )
}

In [35]:
# =============================================================================
# RANK FUSION DODA MODEL EVALUATION — BORUTA
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

boruta_doda_results_eval = []


for k in k_values:

    Xtr = boruta_doda_results[k]["X_train"]

    Xts = boruta_doda_results[k]["X_test"]

    features = ", ".join(
        boruta_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        boruta_doda_results_eval.append({

            "Method": "Boruta + Rank Fusion DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


boruta_doda_evaluation = pd.DataFrame(
    boruta_doda_results_eval
)


display(boruta_doda_evaluation)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta + Rank Fusion DODA,5,Logistic Regression,"cp, oldpeak, ca, thal, age",0.852459,0.787879,0.928571,0.852459,0.925866
1,Boruta + Rank Fusion DODA,5,Random Forest,"cp, oldpeak, ca, thal, age",0.786885,0.714286,0.892857,0.793651,0.933442
2,Boruta + Rank Fusion DODA,5,XGBoost,"cp, oldpeak, ca, thal, age",0.836066,0.764706,0.928571,0.838710,0.931277
3,Boruta + Rank Fusion DODA,8,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.868852,0.833333,0.892857,0.862069,0.936147
4,Boruta + Rank Fusion DODA,8,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.868852,0.833333,0.892857,0.862069,0.944264
5,Boruta + Rank Fusion DODA,8,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.819672,0.774194,0.857143,0.813559,0.895022
6,Boruta + Rank Fusion DODA,10,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.948052
7,Boruta + Rank Fusion DODA,10,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.918033,0.870968,0.964286,0.915254,0.955087
8,Boruta + Rank Fusion DODA,10,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.836066,0.781250,0.892857,0.833333,0.910173
9,Boruta + Rank Fusion DODA,13,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.951299
10,Boruta + Rank Fusion DODA,13,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.901639,0.866667,0.928571,0.896552,0.951299
11,Boruta + Rank Fusion DODA,13,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.910173

In [36]:
# =============================================================================
# SAVE DODA RESULTS
# =============================================================================


boruta_doda_evaluation.to_csv(
    "../../../results/heart_disease/doda/boruta_doda_results.csv",
    index=False
)

In [38]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================


comparison_df = pd.concat(
    [
        boruta_evaluation,
        boruta_doda_evaluation
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Boruta,5,Logistic Regression,"age, ca, cp, oldpeak, thal",0.852459,0.787879,0.928571,0.852459,0.925866
1,Boruta,5,Random Forest,"age, ca, cp, oldpeak, thal",0.803279,0.735294,0.892857,0.806452,0.931277
2,Boruta,5,XGBoost,"age, ca, cp, oldpeak, thal",0.836066,0.764706,0.928571,0.838710,0.943182
3,Boruta,8,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.868852,0.812500,0.928571,0.866667,0.937229
4,Boruta,8,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.901639,0.892857,0.892857,0.892857,0.943182
5,Boruta,8,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exang",0.786885,0.741935,0.821429,0.779661,0.891775
6,Boruta,10,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.885246,0.818182,0.964286,0.885246,0.949134
7,Boruta,10,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.833333,0.892857,0.862069,0.932900
8,Boruta,10,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.852459,0.806452,0.892857,0.847458,0.899351
9,Boruta,13,Logistic Regression,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.812500,0.928571,0.866667,0.950216
10,Boruta,13,Random Forest,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.901639,0.866667,0.928571,0.896552,0.951299
11,Boruta,13,XGBoost,"age, ca, cp, oldpeak, thal, thalach, chol, exa...",0.868852,0.812500,0.928571,0.866667,0.906926
12,Boruta + Rank Fusion DODA,5,Logistic Regression,"cp, oldpeak, ca, thal, age",0.852459,0.787879,0.928571,0.852459,0.925866
13,Boruta + Rank Fusion DODA,5,Random Forest,"cp, oldpeak, ca, thal, age",0.786885,0.714286,0.892857,0.793651,0.933442
14,Boruta + Rank Fusion DODA,5,XGBoost,"cp, oldpeak, ca, thal, age",0.836066,0.764706,0.928571,0.838710,0.931277
15,Boruta + Rank Fusion DODA,8,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.868852,0.833333,0.892857,0.862069,0.936147
16,Boruta + Rank Fusion DODA,8,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.868852,0.833333,0.892857,0.862069,0.944264
17,Boruta + Rank Fusion DODA,8,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, chol",0.819672,0.774194,0.857143,0.813559,0.895022
18,Boruta + Rank Fusion DODA,10,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.948052
19,Boruta + Rank Fusion DODA,10,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.918033,0.870968,0.964286,0.915254,0.955087
20,Boruta + Rank Fusion DODA,10,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.836066,0.781250,0.892857,0.833333,0.910173
21,Boruta + Rank Fusion DODA,13,Logistic Regression,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.951299
22,Boruta + Rank Fusion DODA,13,Random Forest,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.901639,0.866667,0.928571,0.896552,0.951299
23,Boruta + Rank Fusion DODA,13,XGBoost,"cp, oldpeak, ca, thal, age, thalach, exang, ch...",0.868852,0.812500,0.928571,0.866667,0.910173

In [41]:
# ============================================================
# BORUTA + DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# Heart Disease Dataset
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from boruta import BorutaPy

from doda import DODASelector
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion
from doda.adapters.sklearn_adapter import SklearnAdapter


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "heartdisease_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should contain the ORIGINAL Heart Disease data
# before imputation/scaling.
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"BORUTA + DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0


    # ========================================================
    # 25 REPEATED CV RUNS
    # ========================================================

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()


        # ----------------------------------------------------
        # IMPUTATION
        # ----------------------------------------------------

        imputer = SimpleImputer(
            strategy="median"
        )

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )


        # ----------------------------------------------------
        # BORUTA RANDOM FOREST
        # ----------------------------------------------------

        rf_boruta = RandomForestClassifier(
            n_estimators=200,
            random_state=RANDOM_STATE,
            class_weight="balanced",
            n_jobs=-1
        )


        # ----------------------------------------------------
        # BORUTA SELECTOR
        # ----------------------------------------------------

        boruta = BorutaPy(
            estimator=rf_boruta,
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )


        # ----------------------------------------------------
        # DODA ADAPTER
        # ----------------------------------------------------

        boruta_operator = SklearnAdapter(
            boruta
        )


        # ----------------------------------------------------
        # CLINICAL KNOWLEDGE PROVIDER
        # ----------------------------------------------------

        provider = JSONProvider(
            WEIGHTS_FILE
        )


        # ----------------------------------------------------
        # DODA SELECTOR
        # ----------------------------------------------------

        doda_selector = DODASelector(

            operators=[boruta_operator],

            provider=provider,

            fusion=RankFusion(),

            top_k=TOP_K

        )


        # ----------------------------------------------------
        # FIT ONLY ON TRAINING FOLD
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )


        # ----------------------------------------------------
        # SELECTED FEATURES
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )


        selected_feature_sets.append(
            set(selected_features)
        )


        all_runs.append({

            "Top_K": TOP_K,

            "Run": run_number,

            "Selected_Features": selected_features

        })


        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []


    for i in range(
        len(selected_feature_sets)
    ):

        for j in range(
            i + 1,
            len(selected_feature_sets)
        ):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]


            intersection = len(
                set_a.intersection(set_b)
            )

            union = len(
                set_a.union(set_b)
            )


            jaccard = (
                intersection / union
            )


            jaccard_scores.append(
                jaccard
            )


            all_jaccard.append({

                "Top_K": TOP_K,

                "Run_A": i + 1,

                "Run_B": j + 1,

                "Jaccard_Similarity": jaccard

            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(
        jaccard_scores
    )

    std_jaccard = np.std(
        jaccard_scores
    )

    min_jaccard = np.min(
        jaccard_scores
    )

    max_jaccard = np.max(
        jaccard_scores
    )


    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(
        f"Number of runs:          "
        f"{len(selected_feature_sets)}"
    )

    print(
        f"Number of comparisons:   "
        f"{len(jaccard_scores)}"
    )

    print(
        f"Mean Jaccard Similarity: "
        f"{mean_jaccard:.4f}"
    )

    print(
        f"Standard Deviation:      "
        f"{std_jaccard:.4f}"
    )

    print(
        f"Minimum Jaccard:         "
        f"{min_jaccard:.4f}"
    )

    print(
        f"Maximum Jaccard:         "
        f"{max_jaccard:.4f}"
    )


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}


    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )


    for feature, count in feature_counts.items():

        all_frequency.append({

            "Top_K": TOP_K,

            "Feature": feature,

            "Selection_Count": count,

            "Selection_Frequency":
                count / len(selected_feature_sets)

        })


    frequency_df_topk = pd.DataFrame(

        [

            {

                "Feature": feature,

                "Selection_Count": count,

                "Selection_Frequency":
                    count / len(selected_feature_sets)

            }

            for feature, count
            in feature_counts.items()

        ]

    ).sort_values(

        "Selection_Frequency",

        ascending=False

    )


    print(
        "\nFEATURE SELECTION FREQUENCY"
    )

    print(
        frequency_df_topk.to_string(
            index=False
        )
    )


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(
    all_runs
)

jaccard_df = pd.DataFrame(
    all_jaccard
)

frequency_df = pd.DataFrame(
    all_frequency
)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []


for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]


    summary_rows.append({

        "Top_K": TOP_K,

        "Mean_Jaccard":
            subset.mean(),

        "Std_Jaccard":
            subset.std(),

        "Min_Jaccard":
            subset.min(),

        "Max_Jaccard":
            subset.max()

    })


summary_df = pd.DataFrame(
    summary_rows
)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("BORUTA + DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(

    summary_df.to_string(

        index=False,

        float_format=lambda x:
            f"{x:.4f}"

    )

)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/heart_disease/"
    "boruta_doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/heart_disease/"
    "boruta_doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/heart_disease/"
    "boruta_doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/heart_disease/"
    "boruta_doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")

print(
    "1. boruta_doda_stability_all_topk_runs.csv"
)

print(
    "2. boruta_doda_stability_all_topk_jaccard.csv"
)

print(
    "3. boruta_doda_stability_all_topk_frequency.csv"
)

print(
    "4. boruta_doda_stability_all_topk_summary.csv"
)

======================================================================
BORUTA + DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA720CCE90>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.03252247488101534, 'oldpeak': 0.03278688524590164, 'slope': 0.03128054740957967, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 01: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA720CFCB0>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.03225806451612903, 'chol': 0.031746031746031744, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 02: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044BD10>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 03: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044B0B0>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.2), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.3333333333333333), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.2), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.3333333333333333), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.2), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.3333333333333333), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03200204813108039, 'fbs': 0.03055037313432836, 'restecg': 0.031024531024531024, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.03200204813108039, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 04: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044BC50>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.5), 'sex': np.float64(0.14285714285714285), 'cp': np.float64(1.0), 'trestbps': np.float64(0.25), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.1111111111111111), 'restecg': np.float64(0.125), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03225806451612903, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.031754032258064516, 'chol': 0.031746031746031744, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'thalach']
Run 05: ['cp', 'oldpeak', 'ca', 'thal', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044B110>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.2), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.2), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.2), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.0315136476426799, 'chol': 0.03200204813108039, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.031754032258064516, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 06: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044B050>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.5), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.25), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03200204813108039, 'fbs': 0.03055037313432836, 'restecg': 0.031024531024531024, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.031754032258064516, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 07: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044BC50>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.03225806451612903, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032266458495966696, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Run 08: ['cp', 'oldpeak', 'ca', 'thal', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA7044BD10>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.3333333333333333), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores

In [42]:
# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# BORUTA VS DODA-BORUTA WITH RANK FUSION
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier
from boruta import BorutaPy

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# =============================================================================
# CONFIGURATION
# =============================================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

target_column = "target"

X = df.drop(columns=[target_column])
y = df[target_column]

feature_names = X.columns.tolist()


# =============================================================================
# MODELS
# =============================================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# =============================================================================
# CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

provider = JSONProvider(
    "heartdisease_weights.json"
)


# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# =============================================================================
# RESULTS STORAGE
# =============================================================================

results = []


# =============================================================================
# CROSS-VALIDATION LOOP
# =============================================================================

for run_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    print("\n" + "=" * 80)
    print(f"REPEATED STRATIFIED CV RUN {run_number}")
    print("=" * 80)

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # =========================================================================
    # IMPUTATION
    # =========================================================================

    imputer = SimpleImputer(
        strategy="median"
    )

    X_train_imp_array = imputer.fit_transform(
        X_train
    )

    X_test_imp_array = imputer.transform(
        X_test
    )

    X_train_imp = pd.DataFrame(
        X_train_imp_array,
        columns=feature_names,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        X_test_imp_array,
        columns=feature_names,
        index=X_test.index
    )


    # =========================================================================
    # FEATURE SELECTION FOR EACH TOP-K VALUE
    # =========================================================================

    for top_k in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"TOP-K = {top_k}")
        print("-" * 80)


        # =====================================================================
        # BASELINE BORUTA FEATURE SELECTION
        # =====================================================================

        rf_boruta = RandomForestClassifier(
            n_estimators=200,
            random_state=RANDOM_STATE,
            class_weight="balanced",
            n_jobs=-1
        )

        boruta_selector = BorutaPy(
            estimator=rf_boruta,
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )

        boruta_selector.fit(
            X_train_imp.values,
            y_train.values
        )


        boruta_scores = pd.DataFrame({

            "Feature": feature_names,

            "Boruta Rank":
                boruta_selector.ranking_,

            "Confirmed":
                boruta_selector.support_,

            "Tentative":
                boruta_selector.support_weak_

        })


        boruta_scores = (
            boruta_scores
            .sort_values(
                by=["Boruta Rank", "Feature"]
            )
            .reset_index(drop=True)
        )


        # Create deterministic ranking
        boruta_scores["Final Rank"] = (
            np.arange(len(boruta_scores)) + 1
        )


        boruta_features = (
            boruta_scores
            .head(top_k)["Feature"]
            .tolist()
        )


        print("Boruta-selected features:")
        print(boruta_features)


        # =====================================================================
        # DODA-BORUTA FEATURE SELECTION
        # =====================================================================

        boruta = BorutaPy(
            estimator=RandomForestClassifier(
                n_estimators=200,
                random_state=RANDOM_STATE,
                class_weight="balanced",
                n_jobs=-1
            ),
            n_estimators="auto",
            max_iter=100,
            perc=100,
            random_state=RANDOM_STATE,
            verbose=0
        )


        boruta_operator = SklearnAdapter(
            boruta
        )


        doda_selector = DODASelector(
            operators=[boruta_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )


        doda_selector.fit(
            X_train_imp,
            y_train
        )


        doda_features = list(
            doda_selector.get_selected_features()
        )


        print("DODA-Boruta-selected features:")
        print(doda_features)


        # =====================================================================
        # PREPARE SELECTED FEATURE MATRICES
        # =====================================================================

        X_train_boruta_selected = (
            X_train_imp[boruta_features]
        )

        X_test_boruta_selected = (
            X_test_imp[boruta_features]
        )

        X_train_doda_selected = (
            X_train_imp[doda_features]
        )

        X_test_doda_selected = (
            X_test_imp[doda_features]
        )


        # =====================================================================
        # MODEL EVALUATION
        # =====================================================================

        selected_feature_sets = {

            "Boruta": (
                X_train_boruta_selected,
                X_test_boruta_selected,
                boruta_features
            ),

            "DODA": (
                X_train_doda_selected,
                X_test_doda_selected,
                doda_features
            )

        }


        for method, (
            X_train_selected,
            X_test_selected,
            selected_features
        ) in selected_feature_sets.items():

            for model_name, model_template in models.items():

                model = clone(
                    model_template
                )

                X_train_model = (
                    X_train_selected.copy()
                )

                X_test_model = (
                    X_test_selected.copy()
                )


                # -------------------------------------------------------------
                # Scale only Logistic Regression
                # -------------------------------------------------------------

                if model_name == "Logistic Regression":

                    model_scaler = StandardScaler()

                    X_train_model = (
                        model_scaler.fit_transform(
                            X_train_model
                        )
                    )

                    X_test_model = (
                        model_scaler.transform(
                            X_test_model
                        )
                    )


                # -------------------------------------------------------------
                # Train model
                # -------------------------------------------------------------

                model.fit(
                    X_train_model,
                    y_train
                )

                y_pred = model.predict(
                    X_test_model
                )

                y_prob = model.predict_proba(
                    X_test_model
                )[:, 1]


                # -------------------------------------------------------------
                # Calculate metrics
                # -------------------------------------------------------------

                accuracy = accuracy_score(
                    y_test,
                    y_pred
                )

                precision = precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                roc_auc = roc_auc_score(
                    y_test,
                    y_prob
                )


                # -------------------------------------------------------------
                # Store results
                # -------------------------------------------------------------

                results.append({

                    "Run": run_number,

                    "Method": method,

                    "Top_K": top_k,

                    "Model": model_name,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": roc_auc,

                    "Selected_Features": selected_features

                })


# =============================================================================
# RESULTS DATAFRAME
# =============================================================================

results_df = pd.DataFrame(
    results
)


# =============================================================================
# DISPLAY RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("REPEATED STRATIFIED CV RESULTS — BORUTA VS DODA-BORUTA")
print("=" * 80)

display(
    results_df.head()
)

print(
    "Total evaluation rows:",
    len(results_df)
)

================================================================================
REPEATED STRATIFIED CV RUN 1
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.03252247488101534, 'oldpeak': 0.03278688524590164, 'slope': 0.03128054740957967, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'exang', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.03252247488101534, 'oldpeak': 0.03278688524590164, 'slope': 0.03128054740957967, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'exang', 'trestbps', 'chol', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.03252247488101534, 'oldpeak': 0.03278688524590164, 'slope': 0.03128054740957967, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps', 'chol', 'slope']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps', 'chol', 'slope']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'exang', 'trestbps', 'chol', 'sex', 'slope', 'restecg', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.2), 'cp': np.float64(1.0), 'trestbps': np.float64(0.3333333333333333), 'chol': np.float64(0.25), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.5), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.16666666666666666), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.031009615384615385, 'cp': 0.03278688524590164, 'trestbps': 0.03200204813108039, 'chol': 0.03149801587301587, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.03252247488101534, 'oldpeak': 0.03278688524590164, 'slope': 0.03128054740957967, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps', 'chol', 'slope', 'sex', 'restecg', 'fbs']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'exang', 'thalach', 'trestbps', 'chol', 'slope', 'sex', 'restecg', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 2
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.03225806451612903, 'chol': 0.031746031746031744, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'trestbps', 'chol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.03225806451612903, 'chol': 0.031746031746031744, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'trestbps', 'exang']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'trestbps', 'exang']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'trestbps', 'chol', 'exang', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:
{'BorutaPy_1': {'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(1.0), 'sex': np.float64(0.16666666666666666), 'cp': np.float64(1.0), 'trestbps': np.float64(0.5), 'chol': np.float64(0.3333333333333333), 'fbs': np.float64(0.125), 'restecg': np.float64(0.14285714285714285), 'thalach': np.float64(1.0), 'exang': np.float64(0.25), 'oldpeak': np.float64(1.0), 'slope': np.float64(0.2), 'ca': np.float64(1.0), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03252247488101534, 'sex': 0.030776515151515152, 'cp': 0.03278688524590164, 'trestbps': 0.03225806451612903, 'chol': 0.031746031746031744, 'fbs': 0.030330882352941176, 'restecg': 0.030798389007344232, 'thalach': 0.032266458495966696, 'exang': 0.032018442622950824, 'oldpeak': 0.03278688524590164, 'slope': 0.0315136476426799, 'ca': 0.03278688524590164, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'trestbps', 'exang', 'chol', 'slope']
DODA-Boruta-selected features:
['cp', 'oldpeak', 'ca', 'thal', 'age', 'thalach', 'trestbps', 'exang', 'chol', 'slope']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------
Boruta-selected features:
['age', 'ca', 'cp', 'oldpeak', 'thal', 'thalach', 'trestbps', 'chol', 'exang', 'slope', 'sex', 'restecg', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002BA6F013B30>
DODA Pipeline Started
Running: BorutaPy
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of rankings: 13
Operator Scores:

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,Boruta,5,Logistic Regression,0.901639,0.892857,0.892857,0.892857,0.945887,"[age, ca, cp, oldpeak, thal]"
1,1,Boruta,5,Random Forest,0.819672,0.814815,0.785714,0.800000,0.894481,"[age, ca, cp, oldpeak, thal]"
2,1,Boruta,5,XGBoost,0.819672,0.840000,0.750000,0.792453,0.901515,"[age, ca, cp, oldpeak, thal]"
3,1,DODA,5,Logistic Regression,0.901639,0.892857,0.892857,0.892857,0.945887,"[cp, oldpeak, ca, thal, age]"
4,1,DODA,5,Random Forest,0.803279,0.785714,0.785714,0.785714,0.909091,"[cp, oldpeak, ca, thal, age]"

Total evaluation rows: 600

In [43]:
# =============================================================================
# PREPARE FEATURE SETS FOR STABILITY ANALYSIS
# mRMR VS DODA-mRMR
# =============================================================================

import ast
import numpy as np
import pandas as pd


# =============================================================================
# CONVERT SELECTED FEATURES TO SET
# =============================================================================

def convert_to_set(features):
    """
    Convert Selected_Features into a Python set.
    Handles lists, tuples, NumPy arrays, and strings.
    """

    if isinstance(features, str):

        # Handle string representation of a list
        if features.startswith("[") and features.endswith("]"):

            try:
                features = ast.literal_eval(features)

            except Exception:
                features = features.split(",")

        else:
            features = features.split(",")


    return {
        str(feature).strip().strip("'").strip('"')
        for feature in features
        if str(feature).strip()
    }


# =============================================================================
# USE ONLY ONE MODEL
# =============================================================================

# Feature selection is independent of the predictive model.
# Therefore, Logistic Regression rows are sufficient.

stability_df = results_df[
    results_df["Model"] == "Logistic Regression"
].copy()


# =============================================================================
# CONVERT FEATURE LISTS TO SETS
# =============================================================================

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(convert_to_set)
)


# =============================================================================
# CHECK RESULTS
# =============================================================================

print("=" * 80)
print("FEATURE SETS PREPARED FOR STABILITY ANALYSIS")
print("=" * 80)

print(
    "Rows used for stability analysis:",
    len(stability_df)
)


# =============================================================================
# DISPLAY SAMPLE
# =============================================================================

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head(10)
)


# =============================================================================
# CHECK FEATURE COUNT
# =============================================================================

stability_df["Feature_Count"] = (
    stability_df["Feature_Set"]
    .apply(len)
)


print("\nFeature count check:")

display(
    stability_df[
        [
            "Method",
            "Top_K",
            "Feature_Count"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Method", "Top_K"]
    )
)


# =============================================================================
# VERIFY EXPECTED TOP-K
# =============================================================================

invalid_rows = stability_df[
    stability_df["Feature_Count"] != stability_df["Top_K"]
]


if len(invalid_rows) == 0:

    print(
        "\n✓ All feature sets contain the expected number of features."
    )

else:

    print(
        "\n⚠ WARNING: Some feature sets do not match their Top-K value."
    )

    display(
        invalid_rows[
            [
                "Run",
                "Method",
                "Top_K",
                "Feature_Count",
                "Feature_Set"
            ]
        ]
    )

================================================================================
FEATURE SETS PREPARED FOR STABILITY ANALYSIS
================================================================================
Rows used for stability analysis: 200

    Run  Method  Top_K                                        Feature_Set
0     1  Boruta      5                       {cp, ca, age, thal, oldpeak}
3     1    DODA      5                       {cp, ca, age, thal, oldpeak}
6     1  Boruta      8  {exang, trestbps, cp, ca, thalach, age, thal, ...
9     1    DODA      8  {exang, trestbps, cp, ca, thalach, age, thal, ...
12    1  Boruta     10  {exang, sex, trestbps, cp, ca, thalach, age, t...
15    1    DODA     10  {exang, trestbps, cp, ca, thalach, age, slope,...
18    1  Boruta     13  {exang, sex, fbs, trestbps, restecg, cp, ca, t...
21    1    DODA     13  {exang, sex, fbs, trestbps, restecg, cp, ca, t...
24    2  Boruta      5                       {cp, ca, age, thal, oldpeak}
27    2    DODA      5                       {cp, ca, age, thal, oldpeak}

Feature count check:

    Method  Top_K  Feature_Count
0   Boruta      5              5
6   Boruta      8              8
12  Boruta     10             10
18  Boruta     13             13
3     DODA      5              5
9     DODA      8              8
15    DODA     10             10
21    DODA     13             13

✓ All feature sets contain the expected number of features.

In [44]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# BORUTA VS DODA-RF
# =============================================================================

selection_frequency = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]


        # -------------------------------------------------------------
        # Number of CV runs
        # -------------------------------------------------------------

        total_runs = len(subset)


        # -------------------------------------------------------------
        # All features appearing across the 25 runs
        # -------------------------------------------------------------

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )


        # -------------------------------------------------------------
        # Calculate selection frequency
        # -------------------------------------------------------------

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set
                in subset["Feature_Set"]
            )


            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100

            })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

selection_frequency_df = pd.DataFrame(
    selection_frequency
)


# =============================================================================
# SORT RESULTS
# =============================================================================

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


# =============================================================================
# DISPLAY
# =============================================================================

print("=" * 80)
print("FEATURE SELECTION FREQUENCY")
print("=" * 80)

display(
    selection_frequency_df
)

================================================================================
FEATURE SELECTION FREQUENCY
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,Boruta,5,ca,25,25,100.0
1,Boruta,5,cp,25,25,100.0
2,Boruta,5,oldpeak,25,25,100.0
3,Boruta,5,thal,25,25,100.0
4,Boruta,5,age,20,25,80.0
...,...,...,...,...,...,...
76,DODA,13,sex,25,25,100.0
77,DODA,13,slope,25,25,100.0
78,DODA,13,thal,25,25,100.0
79,DODA,13,thalach,25,25,100.0
80,DODA,13,trestbps,25,25,100.0

In [45]:
# =============================================================================
# TEST 2: JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Jaccard comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )

                union = len(
                    set_a.union(set_b)
                )


                if union == 0:
                    jaccard = 0.0

                else:
                    jaccard = (
                        intersection / union
                    )


                jaccard_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Union": union,

                    "Jaccard_Similarity": jaccard

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

jaccard_df = pd.DataFrame(
    jaccard_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("JACCARD SIMILARITY — PAIRWISE RESULTS")
print("=" * 80)

display(
    jaccard_df
)


# =============================================================================
# JACCARD SUMMARY
# =============================================================================

jaccard_summary = (
    jaccard_df
    .groupby(
        ["Method", "Top_K"]
    )["Jaccard_Similarity"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("JACCARD SIMILARITY SUMMARY")
print("=" * 80)

display(
    jaccard_summary
)

================================================================================
JACCARD SIMILARITY — PAIRWISE RESULTS
================================================================================

      Method  Top_K  Run_A  Run_B  Intersection  Union  Jaccard_Similarity
0     Boruta      5      1      2             5      5            1.000000
1     Boruta      5      1      3             5      5            1.000000
2     Boruta      5      1      4             5      5            1.000000
3     Boruta      5      1      5             4      6            0.666667
4     Boruta      5      1      6             5      5            1.000000
...      ...    ...    ...    ...           ...    ...                 ...
2395    DODA     13     22     24            13     13            1.000000
2396    DODA     13     22     25            13     13            1.000000
2397    DODA     13     23     24            13     13            1.000000
2398    DODA     13     23     25            13     13            1.000000
2399    DODA     13     24     25            13     13            1.000000

[2400 rows x 7 columns]

================================================================================
JACCARD SIMILARITY SUMMARY
================================================================================

   Method  Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0  Boruta      5      0.884444     0.158901     0.666667          1.0
1  Boruta      8      0.797333     0.118175     0.600000          1.0
2  Boruta     10      0.960000     0.075443     0.818182          1.0
3  Boruta     13      1.000000     0.000000     1.000000          1.0
4    DODA      5      0.884444     0.158901     0.666667          1.0
5    DODA      8      0.885481     0.113362     0.600000          1.0
6    DODA     10      1.000000     0.000000     1.000000          1.0
7    DODA     13      1.000000     0.000000     1.000000          1.0

In [46]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

Total number of features: 13
================================================================================
KUNCHEVA INDEX — PAIRWISE RESULTS
================================================================================

      Method  Top_K  Run_A  Run_B  Intersection  Kuncheva_Index
0     Boruta      5      1      2             5           1.000
1     Boruta      5      1      3             5           1.000
2     Boruta      5      1      4             5           1.000
3     Boruta      5      1      5             4           0.675
4     Boruta      5      1      6             5           1.000
...      ...    ...    ...    ...           ...             ...
2395    DODA     13     22     24            13             NaN
2396    DODA     13     22     25            13             NaN
2397    DODA     13     23     24            13             NaN
2398    DODA     13     23     25            13             NaN
2399    DODA     13     24     25            13             NaN

[2400 rows x 6 columns]

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

   Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0  Boruta      5       0.887333      0.154929      0.675000           1.0
1  Boruta      8       0.694500      0.188815      0.350000           1.0
2  Boruta     10       0.904667      0.179807      0.566667           1.0
3  Boruta     13            NaN           NaN           NaN           NaN
4    DODA      5       0.887333      0.154929      0.675000           1.0
5    DODA      8       0.832083      0.166968      0.350000           1.0
6    DODA     10       1.000000      0.000000      1.000000           1.0
7    DODA     13            NaN           NaN           NaN           NaN

In [50]:
# =============================================================================
# TEST 4: BORUTA VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for top_k in sorted(
    stability_df["Top_K"].unique()
):

    boruta_subset = stability_df[
        (stability_df["Method"] == "Boruta") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    doda_subset = stability_df[
        (stability_df["Method"] == "DODA") &
        (stability_df["Top_K"] == top_k)
    ].copy()


    # Match Boruta and DODA feature sets
    # from the same CV run

    merged = pd.merge(

        boruta_subset[
            ["Run", "Feature_Set"]
        ].rename(
            columns={
                "Feature_Set":
                "Boruta_Feature_Set"
            }
        ),

        doda_subset[
            ["Run", "Feature_Set"]
        ].rename(
            columns={
                "Feature_Set":
                "DODA_Feature_Set"
            }
        ),

        on="Run",

        how="inner"
    )


    for _, row in merged.iterrows():

        boruta_set = row[
            "Boruta_Feature_Set"
        ]

        doda_set = row[
            "DODA_Feature_Set"
        ]


        # ---------------------------------------------------------
        # Common features
        # ---------------------------------------------------------

        intersection = len(
            boruta_set.intersection(
                doda_set
            )
        )


        # ---------------------------------------------------------
        # Total unique features
        # ---------------------------------------------------------

        union = len(
            boruta_set.union(
                doda_set
            )
        )


        # ---------------------------------------------------------
        # Jaccard agreement
        # ---------------------------------------------------------

        if union == 0:

            jaccard_agreement = 0.0

        else:

            jaccard_agreement = (
                intersection / union
            )


        agreement_results.append({

            "Top_K":
                top_k,

            "Run":
                row["Run"],

            "Boruta_Features":
                sorted(boruta_set),

            "DODA_Features":
                sorted(doda_set),

            "Common_Features":
                sorted(
                    boruta_set.intersection(
                        doda_set
                    )
                ),

            "Common_Feature_Count":
                intersection,

            "Jaccard_Agreement":
                jaccard_agreement

        })


# =============================================================================
# CONVERT TO DATAFRAME
# =============================================================================

agreement_df = pd.DataFrame(
    agreement_results
)


# =============================================================================
# DISPLAY
# =============================================================================

display(
    agreement_df
)

,Top_K,Run,Boruta_Features,DODA_Features,Common_Features,Common_Feature_Count,Jaccard_Agreement
0,5,1,"[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]",5,1.0
1,5,2,"[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]",5,1.0
2,5,3,"[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]",5,1.0
3,5,4,"[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]","[age, ca, cp, oldpeak, thal]",5,1.0
4,5,5,"[ca, cp, oldpeak, thal, thalach]","[ca, cp, oldpeak, thal, thalach]","[ca, cp, oldpeak, thal, thalach]",5,1.0
...,...,...,...,...,...,...,...
95,13,21,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.0
96,13,22,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.0
97,13,23,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.0
98,13,24,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.0
99,13,25,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.0

In [51]:
# =============================================================================
# AGREEMENT SUMMARY
# =============================================================================

agreement_summary = (
    agreement_df
    .groupby("Top_K")["Jaccard_Agreement"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)

display(agreement_summary)

   Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0      5      1.000000     0.000000     1.000000          1.0
1      8      0.889778     0.147473     0.600000          1.0
2     10      0.978182     0.060302     0.818182          1.0
3     13      1.000000     0.000000     1.000000          1.0