In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/heartdisease_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 303
Columns : 14

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

target_column = "target"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]


print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")


display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 303
Columns : 13

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 303

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================

print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

target
0    164
1    139
Name: count, dtype: int64

Class Percentage

target
0    54.13
1    45.87
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================

print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

         Data Type
age        float64
sex        float64
cp         float64
trestbps   float64
chol       float64
fbs        float64
restecg    float64
thalach    float64
exang      float64
oldpeak    float64
slope      float64
ca         float64
thal       float64

In [5]:
# =============================================================================
# STEP 5: MISSING VALUE CHECK
# =============================================================================

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)


missing = pd.DataFrame({
    "Missing Count": X.isnull().sum(),
    "Missing Percentage (%)": (
        X.isnull().mean() * 100
    ).round(2)
})


display(
    missing[missing["Missing Count"] > 0]
)

======================================================================
MISSING VALUES
======================================================================

      Missing Count  Missing Percentage (%)
ca                4                    1.32
thal              2                    0.66

In [6]:
# =============================================================================
# STEP 6: MISSING VALUE IMPUTATION
# =============================================================================

from sklearn.impute import SimpleImputer


imputer = SimpleImputer(
    strategy="median"
)


X_imputed = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index=X.index
)


print("=" * 70)
print("MISSING VALUE IMPUTATION")
print("=" * 70)

print("Imputation completed successfully")


print("\nRemaining Missing Values:")
print(X_imputed.isnull().sum().sum())

======================================================================
MISSING VALUE IMPUTATION
======================================================================
Imputation completed successfully

Remaining Missing Values:
0

In [7]:
# =============================================================================
# STEP 7: TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X_imputed,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (242, 13)
y_train shape : (242,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (61, 13)
y_test shape  : (61,)

In [8]:
# =============================================================================
# STEP 8: CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================

print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True) * 100)
    .round(2)
)


print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

target
0    54.13
1    45.87
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

target
0    54.1
1    45.9
Name: proportion, dtype: float64

In [9]:
# =============================================================================
# STEP 9: FEATURE SCALING
# =============================================================================

from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


scaler = StandardScaler()


# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(
    X_train
)


# Transform test data
X_test_scaled = scaler.transform(
    X_test
)


print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(
    f"X_train_scaled shape : {X_train_scaled.shape}"
)

print(
    f"X_test_scaled shape  : {X_test_scaled.shape}"
)

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (242, 13)
X_test_scaled shape  : (61, 13)

In [10]:
# =============================================================================
# STEP 10: CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)


print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(
    X_train_scaled.head()
)

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973

In [11]:
# =============================================================================
# STEP 11: SCALING VERIFICATION
# =============================================================================

print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.mean().round(2)
)


print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

age        -0.0
sex         0.0
cp          0.0
trestbps   -0.0
chol        0.0
fbs        -0.0
restecg     0.0
thalach    -0.0
exang       0.0
oldpeak     0.0
slope      -0.0
ca          0.0
thal        0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

age         1.0
sex         1.0
cp          1.0
trestbps    1.0
chol        1.0
fbs         1.0
restecg     1.0
thalach     1.0
exang       1.0
oldpeak     1.0
slope       1.0
ca          1.0
thal        1.0
dtype: float64

# MRMR

## 1. Baseline

In [12]:
# =============================================================================
# mRMR BASELINE FEATURE SELECTION (TOP-K = 5,8,10,13)
# =============================================================================

import pandas as pd
import numpy as np
from mrmr import mrmr_classif


# =============================================================================
# Prepare training data
# =============================================================================

# mRMR expects the target separately
X_train_mrmr = X_train_scaled.copy()
y_train_mrmr = pd.Series(
    y_train,
    index=X_train_mrmr.index,
    name="target"
)


# =============================================================================
# Run mRMR for maximum K
# =============================================================================

k_values = [5, 8, 10, 13]

max_k = max(k_values)

mrmr_selected = mrmr_classif(
    X=X_train_mrmr,
    y=y_train_mrmr,
    K=max_k
)


# =============================================================================
# Create mRMR ranking
# =============================================================================

mrmr_scores = pd.DataFrame({
    "Feature": mrmr_selected,
    "mRMR Rank": range(1, len(mrmr_selected) + 1)
})


# =============================================================================
# Top-K values
# =============================================================================

mrmr_results = {}


for k in k_values:

    top_features = (
        mrmr_scores
        .head(k)["Feature"]
        .tolist()
    )


    # Boolean mask for selecting columns
    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = X_train_scaled.loc[
        :, mask
    ]

    X_test_selected = X_test_scaled.loc[
        :, mask
    ]


    mrmr_results[k] = {

        "features": top_features,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "scores": mrmr_scores.head(k)

    }


    print("=" * 70)
    print(f"TOP {k} mRMR FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nRanks:")
    print(mrmr_scores.head(k))

100%|██████████| 13/13 [00:07<00:00,  1.79it/s]

======================================================================
TOP 5 mRMR FEATURES
======================================================================
['thal', 'ca', 'exang', 'cp', 'sex']

Ranks:
  Feature  mRMR Rank
0    thal          1
1      ca          2
2   exang          3
3      cp          4
4     sex          5
======================================================================
TOP 8 mRMR FEATURES
======================================================================
['thal', 'ca', 'exang', 'cp', 'sex', 'thalach', 'oldpeak', 'slope']

Ranks:
   Feature  mRMR Rank
0     thal          1
1       ca          2
2    exang          3
3       cp          4
4      sex          5
5  thalach          6
6  oldpeak          7
7    slope          8
======================================================================
TOP 10 mRMR FEATURES
======================================================================
['thal', 'ca', 'exang', 'cp', 'sex', 'thalach', 'oldpeak', 'slope', 'restecg', 'age']

Ranks:
   Feature  mRMR Rank
0     thal          1
1       ca          2
2    exang          3
3       cp          4
4      sex          5
5  thalach          6
6  oldpeak          7
7    slope          8
8  restecg          9
9      age         10
======================================================================
TOP 13 mRMR FEATURES
======================================================================
['thal', 'ca', 'exang', 'cp', 'sex', 'thalach', 'oldpeak', 'slope', 'restecg', 'age', 'trestbps', 'chol', 'fbs']

Ranks:
     Feature  mRMR Rank
0       thal          1
1         ca          2
2      exang          3
3         cp          4
4        sex          5
5    thalach          6
6    oldpeak          7
7      slope          8
8    restecg          9
9        age         10
10  trestbps         11
11      chol         12
12       fbs         13

In [13]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        scale_pos_weight=(
            (y_train == 0).sum() /
            (y_train == 1).sum()
        )
    )
}

In [14]:
# =============================================================================
# MODEL EVALUATION — mRMR
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results_mrmr = []


for k in k_values:

    Xtr = mrmr_results[k]["X_train"]

    Xts = mrmr_results[k]["X_test"]

    features = ", ".join(
        mrmr_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        results_mrmr.append({

            "Method": "mRMR",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred
            ),

            "Recall": recall_score(
                y_test,
                y_pred
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


mrmr_evaluation = pd.DataFrame(
    results_mrmr
)

display(mrmr_evaluation)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,mRMR,5,Logistic Regression,"thal, ca, exang, cp, sex",0.819672,0.774194,0.857143,0.813559,0.898268
1,mRMR,5,Random Forest,"thal, ca, exang, cp, sex",0.819672,0.793103,0.821429,0.807018,0.904762
2,mRMR,5,XGBoost,"thal, ca, exang, cp, sex",0.836066,0.800000,0.857143,0.827586,0.924242
3,mRMR,8,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.852459,0.806452,0.892857,0.847458,0.931818
4,mRMR,8,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.836066,0.800000,0.857143,0.827586,0.943182
5,mRMR,8,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.819672,0.774194,0.857143,0.813559,0.930736
6,mRMR,10,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.781250,0.892857,0.833333,0.935065
7,mRMR,10,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.764706,0.928571,0.838710,0.945887
8,mRMR,10,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.764706,0.928571,0.838710,0.925325
9,mRMR,13,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.868852,0.812500,0.928571,0.866667,0.950216
10,mRMR,13,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.901639,0.866667,0.928571,0.896552,0.951299
11,mRMR,13,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.868852,0.812500,0.928571,0.866667,0.906926

In [15]:
mrmr_evaluation.to_csv(
    "../../../results/heart_disease/baseline/mrmr_baseline_results.csv",
    index=False
)

## 2. DODA

In [16]:
import sys
import doda
from doda import DODASelector
import inspect

print("Python:", sys.executable)
print("DODA:", doda.__file__)
print("Selector:", inspect.getfile(DODASelector))

Python: c:\Users\Anandha Lakshmi\Downloads\Anaconda\python.exe
DODA: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
Selector: c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\selector.py

In [17]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from doda import DODASelector

from doda.adapters import SklearnAdapter

from doda.knowledge.providers import JSONProvider

from doda.fusion import RankFusion

In [18]:
# =============================================================================
# MRMR ADAPTER FOR DODA
# =============================================================================

import numpy as np
from mrmr import mrmr_classif


class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # -------------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # First feature = highest score
        # -------------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # -------------------------------------------------------------
        # Store importance
        # -------------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"

In [19]:
# =============================================================================
# mRMR + DODA FEATURE SELECTION
# =============================================================================

import pandas as pd


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 8, 10, 13]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "heartdisease_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------

fusion = RankFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

mrmr_doda_results = {}


# =============================================================================
# RUN mRMR + DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"mRMR + DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # mRMR operator
    # ---------------------------------------------------------------------

    mrmr_operator = MRMRAdapter()


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(

        operators=[mrmr_operator],

        provider=provider,

        fusion=fusion,

        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(

        X_train_scaled,

        y_train

    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(

        X_test_scaled

    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = (
        selector.get_selected_features()
    )


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for evaluation
    # ---------------------------------------------------------------------

    mrmr_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores":
            selector.raw_math_scores_,

        "math_scores":
            selector.math_scores_,

        "clinical_weights":
            selector.clinical_weights_,

        "final_scores":
            selector.final_scores_
    }


print("\n" + "=" * 70)
print("mRMR + DODA FEATURE SELECTION COMPLETED")
print("=" * 70)

======================================================================
mRMR + DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DB5DEBA0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  1.95it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.031009615384615385, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03131881575727918, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

======================================================================
mRMR + DODA — TOP 8 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DB5DEBA0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.53it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.031009615384615385, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03131881575727918, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope']

======================================================================
mRMR + DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DB5DEBA0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.43it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.031009615384615385, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03131881575727918, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'age', 'restecg']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'age', 'restecg']

======================================================================
mRMR + DODA — TOP 13 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DB5DEBA0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.65it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.6923076923076923), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.031009615384615385, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03131881575727918, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

======================================================================
mRMR + DODA FEATURE SELECTION COMPLETED
======================================================================

In [21]:
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = mrmr_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# Raw mathematical scores
# -------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)


# -------------------------------------------------------------------------
# Normalized mathematical scores
# -------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)


# -------------------------------------------------------------------------
# Combine both
# -------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)


math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)


print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

     Feature  Raw Math Score  Normalized Math Score
12      thal        1.000000               1.000000
11        ca        0.923077               0.923077
8      exang        0.846154               0.846154
2         cp        0.769231               0.769231
1        sex        0.692308               0.692308
7    thalach        0.615385               0.615385
9    oldpeak        0.538462               0.538462
10     slope        0.461538               0.461538
6    restecg        0.384615               0.384615
0        age        0.307692               0.307692
3   trestbps        0.230769               0.230769
4       chol        0.153846               0.153846
5        fbs        0.076923               0.076923

In [22]:
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)


clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)


print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

     Feature  Clinical Weight
2         cp              1.0
9    oldpeak              1.0
11        ca              1.0
12      thal              1.0
8      exang              1.0
10     slope              0.9
0        age              0.9
3   trestbps              0.9
4       chol              0.8
7    thalach              0.8
6    restecg              0.8
1        sex              0.6
5        fbs              0.6

In [23]:
# =============================================================================
# INSPECT FINAL RANK FUSION SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final Rank Fusion Score"
    ]
)


final_scores = final_scores.sort_values(
    by="Final Rank Fusion Score",
    ascending=False
)


print("=" * 70)
print("FINAL RANK FUSION SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL RANK FUSION SCORES
======================================================================

     Feature  Final Rank Fusion Score
12      thal                 0.032787
11        ca                 0.032522
8      exang                 0.032266
2         cp                 0.032018
9    oldpeak                 0.031319
7    thalach                 0.031025
1        sex                 0.031010
10     slope                 0.030835
0        age                 0.030415
6    restecg                 0.030366
3   trestbps                 0.030214
4       chol                 0.029762
5        fbs                 0.029324

In [24]:
# =============================================================================
# SELECTED FEATURES
# =============================================================================

selector.get_selected_features()

['thal',
 'ca',
 'exang',
 'cp',
 'oldpeak',
 'thalach',
 'sex',
 'slope',
 'age',
 'restecg']

In [25]:
# =============================================================================
# COMPARE RANKINGS
# =============================================================================

comparison = selector.compare_scores()

display(comparison)

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
   Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0     thal          1              5           1            0
1       ca          2              4           2            0
2    exang          3              2           3            0
3       cp          4              1           4            0
4  oldpeak          7              3           5            2
5  thalach          6             11           6            0
6      sex          5             12           7           -2
7    slope          8              8           8            0
8      age         10              6           9            1
9  restecg          9             10          10           -1

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,thal,1,1.0000,5,1.0,1,0.0328,0
1,ca,2,0.9231,4,1.0,2,0.0325,0
2,exang,3,0.8462,2,1.0,3,0.0323,0
3,cp,4,0.7692,1,1.0,4,0.0320,0
4,oldpeak,7,0.5385,3,1.0,5,0.0313,2
5,thalach,6,0.6154,11,0.8,6,0.0310,0
6,sex,5,0.6923,12,0.6,7,0.0310,-2
7,slope,8,0.4615,8,0.9,8,0.0308,0
8,age,10,0.3077,6,0.9,9,0.0304,1
9,restecg,9,0.3846,10,0.8,10,0.0304,-1
10,trestbps,11,0.2308,7,0.9,11,0.0302,0
11,chol,12,0.1538,9,0.8,12,0.0298,0
12,fbs,13,0.0769,13,0.6,13,0.0293,0

In [26]:
# =============================================================================
#  MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression":
        LogisticRegression(
            max_iter=1000,
            random_state=42
        ),


    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),


    "XGBoost":
        XGBClassifier(
            n_estimators=200,
            random_state=42,
            eval_metric="logloss"
        )
}

In [27]:
# =============================================================================
# RANK FUSION DODA MODEL EVALUATION — mRMR
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


mrmr_doda_results_eval = []


for k in k_values:

    Xtr = mrmr_doda_results[k]["X_train"]

    Xts = mrmr_doda_results[k]["X_test"]

    features = ", ".join(
        mrmr_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        mrmr_doda_results_eval.append({

            "Method": "mRMR + Rank Fusion DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )

        })


mrmr_doda_evaluation = pd.DataFrame(
    mrmr_doda_results_eval
)


display(mrmr_doda_evaluation)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,mRMR + Rank Fusion DODA,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476
1,mRMR + Rank Fusion DODA,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.877706
2,mRMR + Rank Fusion DODA,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.786885,0.758621,0.785714,0.771930,0.879329
3,mRMR + Rank Fusion DODA,8,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.852459,0.806452,0.892857,0.847458,0.935065
4,mRMR + Rank Fusion DODA,8,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.836066,0.764706,0.928571,0.838710,0.938312
5,mRMR + Rank Fusion DODA,8,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.852459,0.827586,0.857143,0.842105,0.925325
6,mRMR + Rank Fusion DODA,10,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.852459,0.806452,0.892857,0.847458,0.937229
7,mRMR + Rank Fusion DODA,10,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.956169
8,mRMR + Rank Fusion DODA,10,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.836066,0.764706,0.928571,0.838710,0.914502
9,mRMR + Rank Fusion DODA,13,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.951299
10,mRMR + Rank Fusion DODA,13,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.885246,0.818182,0.964286,0.885246,0.948052
11,mRMR + Rank Fusion DODA,13,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.910173

In [28]:
# =============================================================================
# SAVE DODA RESULTS
# =============================================================================


mrmr_doda_evaluation.to_csv(
    "../../../results/heart_disease/doda/mrmr_doda_results.csv",
    index=False
)

In [29]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================


comparison_df = pd.concat(
    [
        mrmr_evaluation,
        mrmr_doda_evaluation
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,mRMR,5,Logistic Regression,"thal, ca, exang, cp, sex",0.819672,0.774194,0.857143,0.813559,0.898268
1,mRMR,5,Random Forest,"thal, ca, exang, cp, sex",0.819672,0.793103,0.821429,0.807018,0.904762
2,mRMR,5,XGBoost,"thal, ca, exang, cp, sex",0.836066,0.800000,0.857143,0.827586,0.924242
3,mRMR,8,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.852459,0.806452,0.892857,0.847458,0.931818
4,mRMR,8,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.836066,0.800000,0.857143,0.827586,0.943182
5,mRMR,8,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, slope",0.819672,0.774194,0.857143,0.813559,0.930736
6,mRMR,10,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.781250,0.892857,0.833333,0.935065
7,mRMR,10,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.764706,0.928571,0.838710,0.945887
8,mRMR,10,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.836066,0.764706,0.928571,0.838710,0.925325
9,mRMR,13,Logistic Regression,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.868852,0.812500,0.928571,0.866667,0.950216
10,mRMR,13,Random Forest,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.901639,0.866667,0.928571,0.896552,0.951299
11,mRMR,13,XGBoost,"thal, ca, exang, cp, sex, thalach, oldpeak, sl...",0.868852,0.812500,0.928571,0.866667,0.906926
12,mRMR + Rank Fusion DODA,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476
13,mRMR + Rank Fusion DODA,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.877706
14,mRMR + Rank Fusion DODA,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.786885,0.758621,0.785714,0.771930,0.879329
15,mRMR + Rank Fusion DODA,8,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.852459,0.806452,0.892857,0.847458,0.935065
16,mRMR + Rank Fusion DODA,8,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.836066,0.764706,0.928571,0.838710,0.938312
17,mRMR + Rank Fusion DODA,8,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, slope",0.852459,0.827586,0.857143,0.842105,0.925325
18,mRMR + Rank Fusion DODA,10,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.852459,0.806452,0.892857,0.847458,0.937229
19,mRMR + Rank Fusion DODA,10,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.956169
20,mRMR + Rank Fusion DODA,10,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.836066,0.764706,0.928571,0.838710,0.914502
21,mRMR + Rank Fusion DODA,13,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.951299
22,mRMR + Rank Fusion DODA,13,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.885246,0.818182,0.964286,0.885246,0.948052
23,mRMR + Rank Fusion DODA,13,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, sex, sl...",0.868852,0.812500,0.928571,0.866667,0.910173

In [30]:
# ============================================================
# mRMR + DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# Heart Disease Dataset
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer

from doda import DODASelector
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# MRMR ADAPTER
# ============================================================

from mrmr import mrmr_classif


class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # --------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # --------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # --------------------------------------------------------
        # Store importance
        # --------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "heartdisease_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should contain the ORIGINAL Heart Disease data
# before imputation/scaling.
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"mRMR + DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0


    # ========================================================
    # 25 REPEATED CV RUNS
    # ========================================================

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()


        # ----------------------------------------------------
        # IMPUTATION
        # ----------------------------------------------------

        imputer = SimpleImputer(
            strategy="median"
        )

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )


        # ----------------------------------------------------
        # mRMR OPERATOR
        # ----------------------------------------------------

        mrmr_operator = MRMRAdapter()


        # ----------------------------------------------------
        # CLINICAL KNOWLEDGE PROVIDER
        # ----------------------------------------------------

        provider = JSONProvider(
            WEIGHTS_FILE
        )


        # ----------------------------------------------------
        # DODA SELECTOR
        # ----------------------------------------------------

        doda_selector = DODASelector(

            operators=[mrmr_operator],

            provider=provider,

            fusion=RankFusion(),

            top_k=TOP_K

        )


        # ----------------------------------------------------
        # FIT ONLY ON TRAINING FOLD
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )


        # ----------------------------------------------------
        # SELECTED FEATURES
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )


        selected_feature_sets.append(
            set(selected_features)
        )


        all_runs.append({

            "Top_K": TOP_K,

            "Run": run_number,

            "Selected_Features": selected_features

        })


        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []


    for i in range(
        len(selected_feature_sets)
    ):

        for j in range(
            i + 1,
            len(selected_feature_sets)
        ):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]


            intersection = len(
                set_a.intersection(set_b)
            )

            union = len(
                set_a.union(set_b)
            )


            jaccard = (
                intersection / union
            )


            jaccard_scores.append(
                jaccard
            )


            all_jaccard.append({

                "Top_K": TOP_K,

                "Run_A": i + 1,

                "Run_B": j + 1,

                "Jaccard_Similarity": jaccard

            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(
        jaccard_scores
    )

    std_jaccard = np.std(
        jaccard_scores
    )

    min_jaccard = np.min(
        jaccard_scores
    )

    max_jaccard = np.max(
        jaccard_scores
    )


    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(
        f"Number of runs:          "
        f"{len(selected_feature_sets)}"
    )

    print(
        f"Number of comparisons:   "
        f"{len(jaccard_scores)}"
    )

    print(
        f"Mean Jaccard Similarity: "
        f"{mean_jaccard:.4f}"
    )

    print(
        f"Standard Deviation:      "
        f"{std_jaccard:.4f}"
    )

    print(
        f"Minimum Jaccard:         "
        f"{min_jaccard:.4f}"
    )

    print(
        f"Maximum Jaccard:         "
        f"{max_jaccard:.4f}"
    )


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}


    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )


    for feature, count in feature_counts.items():

        all_frequency.append({

            "Top_K": TOP_K,

            "Feature": feature,

            "Selection_Count": count,

            "Selection_Frequency":
                count / len(selected_feature_sets)

        })


    frequency_df_topk = pd.DataFrame(

        [

            {

                "Feature": feature,

                "Selection_Count": count,

                "Selection_Frequency":
                    count / len(selected_feature_sets)

            }

            for feature, count
            in feature_counts.items()

        ]

    ).sort_values(

        "Selection_Frequency",

        ascending=False

    )


    print(
        "\nFEATURE SELECTION FREQUENCY"
    )

    print(
        frequency_df_topk.to_string(
            index=False
        )
    )


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(
    all_runs
)

jaccard_df = pd.DataFrame(
    all_jaccard
)

frequency_df = pd.DataFrame(
    all_frequency
)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []


for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]


    summary_rows.append({

        "Top_K": TOP_K,

        "Mean_Jaccard":
            subset.mean(),

        "Std_Jaccard":
            subset.std(),

        "Min_Jaccard":
            subset.min(),

        "Max_Jaccard":
            subset.max()

    })


summary_df = pd.DataFrame(
    summary_rows
)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("mRMR + DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(

    summary_df.to_string(

        index=False,

        float_format=lambda x:
            f"{x:.4f}"

    )

)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/heart_disease/"
    "mrmr_doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/heart_disease/"
    "mrmr_doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/heart_disease/"
    "mrmr_doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/heart_disease/"
    "mrmr_doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")

print(
    "1. mrmr_doda_stability_all_topk_runs.csv"
)

print(
    "2. mrmr_doda_stability_all_topk_jaccard.csv"
)

print(
    "3. mrmr_doda_stability_all_topk_frequency.csv"
)

print(
    "4. mrmr_doda_stability_all_topk_summary.csv"
)

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE806AD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.21it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Run 01: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE807250>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Run 02: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8DC2B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.54it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang']
Run 03: ['thal', 'cp', 'ca', 'restecg', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8DC770>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.50it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca']
Run 04: ['thal', 'cp', 'oldpeak', 'restecg', 'ca']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DD9F9370>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:10<00:00,  1.29it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
Run 05: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE920050>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:10<00:00,  1.19it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Run 06: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE920380>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.45it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang']
Run 07: ['thal', 'ca', 'cp', 'oldpeak', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE840850>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.54it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 08: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE840C50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:11<00:00,  1.17it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 09: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE931A90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:12<00:00,  1.05it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach']
Run 10: ['thal', 'ca', 'restecg', 'exang', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE914C80>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:11<00:00,  1.18it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
Run 11: ['thal', 'ca', 'exang', 'restecg', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA86B30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.12it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Run 12: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA87310>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  1.96it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 13: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8D2C30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:10<00:00,  1.23it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang']
Run 14: ['thal', 'cp', 'ca', 'restecg', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE88AA50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.85it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
Run 15: ['thal', 'ca', 'exang', 'restecg', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE88ABD0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.11it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach']
Run 16: ['thal', 'ca', 'restecg', 'cp', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE96CF70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.38it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Run 17: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE96E200>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.18it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Run 18: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE962710>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.25it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 19: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE96A990>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.78it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Run 20: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE756DE0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.60it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Run 21: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8B2950>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.81it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
Run 22: ['thal', 'ca', 'exang', 'restecg', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8B3650>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 23: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DB807460>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Run 24: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8866D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.73it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope']
Run 25: ['thal', 'ca', 'cp', 'exang', 'slope']

----------------------------------------------------------------------
TOP-5 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 0.7159
Standard Deviation:      0.1741
Minimum Jaccard:         0.4286
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
Feature  Selection_Count  Selection_Frequency
     ca               25                 1.00
   thal               25                 1.00
  exang               23                 0.92
     cp               18                 0.72
oldpeak               17                 0.68
restecg               14                 0.56
thalach                2                 0.08
  slope                1                 0.04

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-8
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94170>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.81it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex']
Run 01: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA17590>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.84it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Run 02: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AAD50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.86it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach']
Run 03: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA943B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.51it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope']
Run 04: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA5A4E90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.86it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex']
Run 05: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA163F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.80it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Run 06: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.88it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex']
Run 07: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94050>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.86it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Run 08: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856A50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.79it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
Run 09: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94170>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope']
Run 10: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94050>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.41it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
Run 11: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94290>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.75it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Run 12: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA8566F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.76it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Run 13: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.86it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope']
Run 14: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AA5D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.80it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
Run 15: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.48it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope']
Run 16: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.85it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Run 17: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AA090>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Run 18: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856930>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.38it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
Run 19: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.88it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Run 20: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AB2F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.77it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex']
Run 21: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope']
Run 22: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA17D10>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Run 23: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AA330>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Run 24: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.80it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age']
Run 25: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age']

----------------------------------------------------------------------
TOP-8 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 0.8785
Standard Deviation:      0.1106
Minimum Jaccard:         0.7778
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
Feature  Selection_Count  Selection_Frequency
     ca               25                 1.00
thalach               25                 1.00
   thal               25                 1.00
  exang               25                 1.00
oldpeak               25                 1.00
  slope               25                 1.00
     cp               25                 1.00
restecg               14                 0.56
    sex               10                 0.40
    age                1                 0.04

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-10
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8ABC50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.94it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age']
Run 01: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.73it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Run 02: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15D90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.85it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps']
Run 03: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.85it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex']
Run 04: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856B70>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.86it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Run 05: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA171D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.90it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Run 06: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.88it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Run 07: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
Run 08: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856450>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.94it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
Run 09: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA155B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.84it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex']
Run 10: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94230>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
Run 11: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.44it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
Run 12: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA940B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.39it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
Run 13: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.40it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex']
Run 14: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA155B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.81it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
Run 15: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94110>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex']
Run 16: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA943B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.77it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
Run 17: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.78it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Run 18: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.79it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
Run 19: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.85it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Run 20: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps']
Run 21: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.56it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex']
Run 22: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.38it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
Run 23: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
Run 24: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA943B0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.84it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps']
Run 25: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps']

----------------------------------------------------------------------
TOP-10 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 0.8927
Standard Deviation:      0.0894
Minimum Jaccard:         0.8182
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
 Feature  Selection_Count  Selection_Frequency
      ca               25                 1.00
 thalach               25                 1.00
    thal               25                 1.00
 oldpeak               25                 1.00
   exang               25                 1.00
      cp               25                 1.00
   slope               25                 1.00
     sex               24                 0.96
 restecg               22                 0.88
     age               19                 0.76
trestbps               10                 0.40

======================================================================
mRMR + DODA STABILITY ANALYSIS — TOP-13
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.00it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age', 'restecg', 'chol', 'fbs']
Run 01: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age', 'restecg', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94170>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.46it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Run 02: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.37it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps', 'sex', 'chol', 'fbs']
Run 03: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps', 'sex', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:09<00:00,  1.32it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 04: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA17590>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.48it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Run 05: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA163F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.56it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Run 06: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Run 07: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.58it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Run 08: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Run 09: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856A50>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:09<00:00,  1.38it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 10: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA856930>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.75it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Run 11: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94170>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:10<00:00,  1.23it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Run 12: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DA8562D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.51it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 13: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94110>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 14: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA94170>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.35it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Run 15: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15D90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.31it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 16: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15EB0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.76it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Run 17: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA14650>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.64it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Run 18: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA15D90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.83it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Run 19: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Run 20: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DDA14650>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'restecg', 'chol', 'fbs']
Run 21: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'restecg', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82C1D0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.61it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Run 22: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE60BEF0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.52it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Run 23: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE8AB2F0>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.78it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Run 24: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE82CB90>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.79it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']
Run 25: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']

----------------------------------------------------------------------
TOP-13 STABILITY SUMMARY
----------------------------------------------------------------------
Number of runs:          25
Number of comparisons:   300
Mean Jaccard Similarity: 1.0000
Standard Deviation:      0.0000
Minimum Jaccard:         1.0000
Maximum Jaccard:         1.0000

FEATURE SELECTION FREQUENCY
 Feature  Selection_Count  Selection_Frequency
      ca               25                  1.0
 thalach               25                  1.0
    thal               25                  1.0
     sex               25                  1.0
trestbps               25                  1.0
   exang               25                  1.0
 oldpeak               25                  1.0
     fbs               25                  1.0
   slope               25                  1.0
    chol               25                  1.0
      cp               25                  1.0
 restecg               25                  1.0
     age               25                  1.0

======================================================================
mRMR + DODA STABILITY — ALL TOP-K VALUES
======================================================================
 Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
     5        0.7159       0.1744       0.4286       1.0000
     8        0.8785       0.1108       0.7778       1.0000
    10        0.8927       0.0896       0.8182       1.0000
    13        1.0000       0.0000       1.0000       1.0000

Files saved:
1. mrmr_doda_stability_all_topk_runs.csv
2. mrmr_doda_stability_all_topk_jaccard.csv
3. mrmr_doda_stability_all_topk_frequency.csv
4. mrmr_doda_stability_all_topk_summary.csv

In [31]:
# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# mRMR VS DODA-mRMR WITH RANK FUSION
# =============================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from mrmr import mrmr_classif

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# =============================================================================
# MRMR ADAPTER
# =============================================================================

class MRMRAdapter:

    def __init__(self):
        self.importance = {}

    def fit(self, X, y):

        # Run mRMR for ALL features
        selected_features = mrmr_classif(
            X=X,
            y=y,
            K=X.shape[1]
        )

        # ---------------------------------------------------------------------
        # Convert mRMR ranking into normalized importance scores
        # ---------------------------------------------------------------------

        n_features = len(selected_features)

        scores = np.zeros(len(X.columns))

        feature_to_index = {
            feature: i
            for i, feature in enumerate(X.columns)
        }

        for rank, feature in enumerate(selected_features):

            index = feature_to_index[feature]

            scores[index] = (
                n_features - rank
            ) / n_features

        # ---------------------------------------------------------------------
        # Store importance
        # ---------------------------------------------------------------------

        self.importance = dict(
            zip(
                X.columns,
                scores
            )
        )

        return self

    def get_importance(self):

        return self.importance

    def get_name(self):

        return "MRMR"


# =============================================================================
# CONFIGURATION
# =============================================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

target_column = "target"

X = df.drop(columns=[target_column])
y = df[target_column]

feature_names = X.columns.tolist()


# =============================================================================
# MODELS
# =============================================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# =============================================================================
# CLINICAL KNOWLEDGE PROVIDER
# =============================================================================

provider = JSONProvider(
    "heartdisease_weights.json"
)


# =============================================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# =============================================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# =============================================================================
# RESULTS STORAGE
# =============================================================================

results = []


# =============================================================================
# CROSS-VALIDATION LOOP
# =============================================================================

for run_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    print("\n" + "=" * 80)
    print(f"REPEATED STRATIFIED CV RUN {run_number}")
    print("=" * 80)

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # =========================================================================
    # IMPUTATION
    # =========================================================================

    imputer = SimpleImputer(
        strategy="median"
    )

    X_train_imp_array = imputer.fit_transform(
        X_train
    )

    X_test_imp_array = imputer.transform(
        X_test
    )

    X_train_imp = pd.DataFrame(
        X_train_imp_array,
        columns=feature_names,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        X_test_imp_array,
        columns=feature_names,
        index=X_test.index
    )


    # =========================================================================
    # FEATURE SELECTION FOR EACH TOP-K VALUE
    # =========================================================================

    for top_k in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"TOP-K = {top_k}")
        print("-" * 80)


        # =====================================================================
        # BASELINE mRMR FEATURE SELECTION
        # =====================================================================

        mrmr_selected_features = mrmr_classif(
            X=X_train_imp,
            y=y_train,
            K=top_k
        )

        mrmr_features = list(
            mrmr_selected_features
        )

        print("mRMR-selected features:")
        print(mrmr_features)


        # =====================================================================
        # DODA-mRMR FEATURE SELECTION
        # =====================================================================

        mrmr_operator = MRMRAdapter()

        doda_selector = DODASelector(
            operators=[mrmr_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        doda_features = list(
            doda_selector.get_selected_features()
        )

        print("DODA-selected features:")
        print(doda_features)


        # =====================================================================
        # PREPARE SELECTED FEATURE MATRICES
        # =====================================================================

        X_train_mrmr_selected = (
            X_train_imp[mrmr_features]
        )

        X_test_mrmr_selected = (
            X_test_imp[mrmr_features]
        )

        X_train_doda_selected = (
            X_train_imp[doda_features]
        )

        X_test_doda_selected = (
            X_test_imp[doda_features]
        )


        # =====================================================================
        # MODEL EVALUATION
        # =====================================================================

        selected_feature_sets = {

            "mRMR": (
                X_train_mrmr_selected,
                X_test_mrmr_selected,
                mrmr_features
            ),

            "DODA": (
                X_train_doda_selected,
                X_test_doda_selected,
                doda_features
            )

        }


        for method, (
            X_train_selected,
            X_test_selected,
            selected_features
        ) in selected_feature_sets.items():

            for model_name, model_template in models.items():

                model = clone(
                    model_template
                )

                X_train_model = (
                    X_train_selected.copy()
                )

                X_test_model = (
                    X_test_selected.copy()
                )


                # -------------------------------------------------------------
                # Scale only Logistic Regression
                # -------------------------------------------------------------

                if model_name == "Logistic Regression":

                    model_scaler = StandardScaler()

                    X_train_model = (
                        model_scaler.fit_transform(
                            X_train_model
                        )
                    )

                    X_test_model = (
                        model_scaler.transform(
                            X_test_model
                        )
                    )


                # -------------------------------------------------------------
                # Train model
                # -------------------------------------------------------------

                model.fit(
                    X_train_model,
                    y_train
                )

                y_pred = model.predict(
                    X_test_model
                )

                y_prob = model.predict_proba(
                    X_test_model
                )[:, 1]


                # -------------------------------------------------------------
                # Calculate metrics
                # -------------------------------------------------------------

                accuracy = accuracy_score(
                    y_test,
                    y_pred
                )

                precision = precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                )

                roc_auc = roc_auc_score(
                    y_test,
                    y_prob
                )


                # -------------------------------------------------------------
                # Store results
                # -------------------------------------------------------------

                results.append({

                    "Run": run_number,

                    "Method": method,

                    "Top_K": top_k,

                    "Model": model_name,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": roc_auc,

                    "Selected_Features": selected_features

                })


# =============================================================================
# RESULTS DATAFRAME
# =============================================================================

results_df = pd.DataFrame(
    results
)


# =============================================================================
# DISPLAY RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("REPEATED STRATIFIED CV RESULTS — mRMR VS DODA-mRMR")
print("=" * 80)

display(
    results_df.head()
)

print(
    "Total evaluation rows:",
    len(results_df)
)

================================================================================
REPEATED STRATIFIED CV RUN 1
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 25.84it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.11it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.07it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  1.93it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.42it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'trestbps', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.29it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:06<00:00,  2.13it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.21it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.38461538461538464), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030776515151515152, 'cp': 0.03177805800756621, 'trestbps': 0.030621785881252923, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age', 'restecg', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'trestbps', 'age', 'restecg', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 2
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 33.48it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'thalach', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.35it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.09it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.05it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.82it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'restecg', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.20it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.24it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'restecg', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.45it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 3
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 24.57it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.35it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.70it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.09it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.79it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.25it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.42it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.37it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.38461538461538464), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030117753623188408, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps', 'sex', 'chol', 'fbs']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'slope', 'thalach', 'age', 'trestbps', 'sex', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 4
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 24.39it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'oldpeak', 'ca']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.29it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca']
DODA-selected features:
['thal', 'cp', 'oldpeak', 'restecg', 'ca']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.88it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'oldpeak', 'ca', 'exang', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.05it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope']
DODA-selected features:
['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.77it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'oldpeak', 'ca', 'exang', 'thalach', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.39it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.20it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'oldpeak', 'ca', 'exang', 'thalach', 'sex', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.30it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6153846153846154), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.6923076923076923), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.031544957774465976, 'oldpeak': 0.032018442622950824, 'slope': 0.030621785881252923, 'ca': 0.03177805800756621, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'cp', 'oldpeak', 'restecg', 'ca', 'exang', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 5
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 14.94it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'thalach', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:07<00:00,  1.64it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.37it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'thalach', 'exang', 'oldpeak', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:17<00:00,  1.36s/it]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.00it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'thalach', 'exang', 'oldpeak', 'sex', 'slope', 'restecg', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.52it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.47it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'thalach', 'exang', 'oldpeak', 'sex', 'slope', 'restecg', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.61it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.7692307692307693), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 6
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 21.97it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  1.97it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.42it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  1.87it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.54it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.28it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'age', 'chol', 'trestbps', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.66it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 7
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 20.97it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang']
DODA-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.29it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.45it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.95it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'sex', 'slope', 'restecg', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.75it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
DODA-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'sex', 'slope', 'restecg', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.58it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'cp', 'oldpeak', 'exang', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 8
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 22.34it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.62it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.05it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.47it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.87it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.54it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:06<00:00,  2.16it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.40it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 9
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 25.95it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.37it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.24it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.06it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.59it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 10
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 25.86it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach']
DODA-selected features:
['thal', 'ca', 'restecg', 'exang', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.79it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'exang', 'cp', 'oldpeak', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.35it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope']
DODA-selected features:
['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.87it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.55it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.61it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.5384615384615384), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.03131881575727918, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'restecg', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 11
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 33.37it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.14it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.60it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.92it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.55it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.62it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age', 'trestbps', 'fbs', 'chol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 12
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.21it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'thalach', 'cp', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.47it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.92it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'thalach', 'cp', 'sex', 'slope', 'restecg', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'thalach', 'cp', 'sex', 'slope', 'restecg', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.61it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.03125763125763126, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 13
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 25.86it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.44it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  5.70it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:08<00:00,  1.45it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:04<00:00,  2.01it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.30it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.47it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.26it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 14
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 18.50it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.76it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.29it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.49it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.93it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.56it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

mRMR-selected features:
['thal', 'restecg', 'cp', 'ca', 'exang', 'oldpeak', 'thalach', 'sex', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.73it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'cp', 'ca', 'restecg', 'exang', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 15
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 23.91it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.63it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.49it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.00it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.64it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 16
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 20.79it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach']
DODA-selected features:
['thal', 'ca', 'restecg', 'cp', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.86it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'cp', 'oldpeak', 'exang', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.45it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope']
DODA-selected features:
['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.98it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'cp', 'oldpeak', 'exang', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

mRMR-selected features:
['thal', 'restecg', 'thalach', 'ca', 'cp', 'oldpeak', 'exang', 'sex', 'slope', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.65it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.8461538461538461), 'exang': np.float64(0.5384615384615384), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.7692307692307693), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.031746031746031744, 'exang': 0.03131881575727918, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032018442622950824, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'restecg', 'cp', 'thalach', 'oldpeak', 'exang', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 17
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 18.99it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.59it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.94it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.43it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.01it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'restecg', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.44it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'restecg', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.7692307692307693), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.032018442622950824, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 18
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 25.03it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.76it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  4.85it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.01it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.51it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:05<00:00,  2.45it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'age', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.61it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 19
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 18.50it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.97it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.53it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.60it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.79it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'sex', 'thalach', 'slope', 'age', 'trestbps', 'fbs', 'chol']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.07692307692307693), 'fbs': np.float64(0.15384615384615385), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.46153846153846156), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.03055037313432836, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.029571646010002173, 'fbs': 0.029513888888888888, 'restecg': 0.03200204813108039, 'thalach': 0.03057889822595705, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 20
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 32.87it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.99it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.99it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'restecg', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.38461538461538464), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.03055037313432836, 'cp': 0.032018442622950824, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03036576949620428, 'thalach': 0.031024531024531024, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'sex', 'trestbps', 'restecg', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 21
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 21.67it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.77it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.66it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:06<00:00,  2.16it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  3.01it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

mRMR-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'sex', 'thalach', 'slope', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.18it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.6153846153846154), 'cp': np.float64(0.7692307692307693), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.8461538461538461), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.46153846153846156), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030776515151515152, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.030798389007344232, 'exang': 0.032266458495966696, 'oldpeak': 0.03177805800756621, 'slope': 0.030834914611005692, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'restecg', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'slope', 'thalach', 'sex', 'age', 'trestbps', 'restecg', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 22
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 23.91it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.72it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  6.61it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.48it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.91it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.60it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.74it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'sex', 'slope', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.64it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6923076923076923), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'cp', 'oldpeak', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 23
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 21.48it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.70it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.19it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.55it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.88it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'trestbps']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.68it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'thalach', 'oldpeak', 'cp', 'sex', 'slope', 'trestbps', 'age', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.23076923076923078), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.5384615384615384), 'trestbps': np.float64(0.3076923076923077), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.6923076923076923), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6153846153846154), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.03021353930031804, 'sex': 0.030330882352941176, 'cp': 0.03131881575727918, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.03125763125763126, 'exang': 0.032018442622950824, 'oldpeak': 0.031544957774465976, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'trestbps', 'sex', 'age', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 24
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 33.31it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.36it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.49it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.92it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:15<00:00,  1.15s/it]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

mRMR-selected features:
['thal', 'restecg', 'ca', 'exang', 'oldpeak', 'cp', 'thalach', 'sex', 'slope', 'age', 'chol', 'trestbps', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.47it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3076923076923077), 'sex': np.float64(0.46153846153846156), 'cp': np.float64(0.6153846153846154), 'trestbps': np.float64(0.15384615384615385), 'chol': np.float64(0.23076923076923078), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.9230769230769231), 'thalach': np.float64(0.5384615384615384), 'exang': np.float64(0.7692307692307693), 'oldpeak': np.float64(0.6923076923076923), 'slope': np.float64(0.38461538461538464), 'ca': np.float64(0.8461538461538461), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.0304147465437788, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.03200204813108039, 'thalach': 0.030798389007344232, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.030621785881252923, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'exang', 'restecg', 'oldpeak', 'cp', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RUN 25
================================================================================

--------------------------------------------------------------------------------
TOP-K = 5
--------------------------------------------------------------------------------

100%|██████████| 5/5 [00:00<00:00, 20.18it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'slope', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.71it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'slope']

--------------------------------------------------------------------------------
TOP-K = 8
--------------------------------------------------------------------------------

100%|██████████| 8/8 [00:01<00:00,  7.14it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'slope', 'exang', 'thalach', 'sex', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:05<00:00,  2.48it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age']

--------------------------------------------------------------------------------
TOP-K = 10
--------------------------------------------------------------------------------

100%|██████████| 10/10 [00:03<00:00,  2.71it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'slope', 'exang', 'thalach', 'sex', 'oldpeak', 'age', 'restecg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps']

--------------------------------------------------------------------------------
TOP-K = 13
--------------------------------------------------------------------------------

100%|██████████| 13/13 [00:04<00:00,  2.69it/s]

mRMR-selected features:
['thal', 'ca', 'cp', 'slope', 'exang', 'thalach', 'sex', 'oldpeak', 'age', 'restecg', 'trestbps', 'chol', 'fbs']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000002A2DE87CB30>
DODA Pipeline Started
Running: MRMR

100%|██████████| 13/13 [00:04<00:00,  2.67it/s]

Operator Scores:
{'MRMR_1': {'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Normalized Mathematical Scores
{'age': np.float64(0.38461538461538464), 'sex': np.float64(0.5384615384615384), 'cp': np.float64(0.8461538461538461), 'trestbps': np.float64(0.23076923076923078), 'chol': np.float64(0.15384615384615385), 'fbs': np.float64(0.07692307692307693), 'restecg': np.float64(0.3076923076923077), 'thalach': np.float64(0.6153846153846154), 'exang': np.float64(0.6923076923076923), 'oldpeak': np.float64(0.46153846153846156), 'slope': np.float64(0.7692307692307693), 'ca': np.float64(0.9230769230769231), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.03055037313432836, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.031099324975891997, 'slope': 0.031754032258064516, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']
DODA-selected features:
['thal', 'ca', 'cp', 'exang', 'slope', 'oldpeak', 'thalach', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']

================================================================================
REPEATED STRATIFIED CV RESULTS — mRMR VS DODA-mRMR
================================================================================

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,mRMR,5,Logistic Regression,0.885246,0.862069,0.892857,0.877193,0.931277,"[thal, ca, exang, oldpeak, cp]"
1,1,mRMR,5,Random Forest,0.786885,0.800000,0.714286,0.754717,0.908550,"[thal, ca, exang, oldpeak, cp]"
2,1,mRMR,5,XGBoost,0.819672,0.840000,0.750000,0.792453,0.905303,"[thal, ca, exang, oldpeak, cp]"
3,1,DODA,5,Logistic Regression,0.885246,0.862069,0.892857,0.877193,0.931277,"[thal, ca, exang, oldpeak, cp]"
4,1,DODA,5,Random Forest,0.786885,0.800000,0.714286,0.754717,0.908550,"[thal, ca, exang, oldpeak, cp]"

Total evaluation rows: 600

In [32]:
# =============================================================================
# PREPARE FEATURE SETS FOR STABILITY ANALYSIS
# mRMR VS DODA-mRMR
# =============================================================================

import ast
import numpy as np
import pandas as pd


# =============================================================================
# CONVERT SELECTED FEATURES TO SET
# =============================================================================

def convert_to_set(features):
    """
    Convert Selected_Features into a Python set.
    Handles lists, tuples, NumPy arrays, and strings.
    """

    if isinstance(features, str):

        # Handle string representation of a list
        if features.startswith("[") and features.endswith("]"):

            try:
                features = ast.literal_eval(features)

            except Exception:
                features = features.split(",")

        else:
            features = features.split(",")


    return {
        str(feature).strip().strip("'").strip('"')
        for feature in features
        if str(feature).strip()
    }


# =============================================================================
# USE ONLY ONE MODEL
# =============================================================================

# Feature selection is independent of the predictive model.
# Therefore, Logistic Regression rows are sufficient.

stability_df = results_df[
    results_df["Model"] == "Logistic Regression"
].copy()


# =============================================================================
# CONVERT FEATURE LISTS TO SETS
# =============================================================================

stability_df["Feature_Set"] = (
    stability_df["Selected_Features"]
    .apply(convert_to_set)
)


# =============================================================================
# CHECK RESULTS
# =============================================================================

print("=" * 80)
print("FEATURE SETS PREPARED FOR STABILITY ANALYSIS")
print("=" * 80)

print(
    "Rows used for stability analysis:",
    len(stability_df)
)


# =============================================================================
# DISPLAY SAMPLE
# =============================================================================

display(
    stability_df[
        [
            "Run",
            "Method",
            "Top_K",
            "Feature_Set"
        ]
    ].head(10)
)


# =============================================================================
# CHECK FEATURE COUNT
# =============================================================================

stability_df["Feature_Count"] = (
    stability_df["Feature_Set"]
    .apply(len)
)


print("\nFeature count check:")

display(
    stability_df[
        [
            "Method",
            "Top_K",
            "Feature_Count"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Method", "Top_K"]
    )
)


# =============================================================================
# VERIFY EXPECTED TOP-K
# =============================================================================

invalid_rows = stability_df[
    stability_df["Feature_Count"] != stability_df["Top_K"]
]


if len(invalid_rows) == 0:

    print(
        "\n✓ All feature sets contain the expected number of features."
    )

else:

    print(
        "\n⚠ WARNING: Some feature sets do not match their Top-K value."
    )

    display(
        invalid_rows[
            [
                "Run",
                "Method",
                "Top_K",
                "Feature_Count",
                "Feature_Set"
            ]
        ]
    )

================================================================================
FEATURE SETS PREPARED FOR STABILITY ANALYSIS
================================================================================
Rows used for stability analysis: 200

    Run Method  Top_K                                        Feature_Set
0     1   mRMR      5                     {ca, thal, exang, oldpeak, cp}
3     1   DODA      5                     {ca, thal, exang, oldpeak, cp}
6     1   mRMR      8  {ca, sex, thal, thalach, exang, oldpeak, slope...
9     1   DODA      8  {ca, thalach, thal, sex, exang, oldpeak, slope...
12    1   mRMR     10  {ca, sex, thal, thalach, trestbps, exang, oldp...
15    1   DODA     10  {ca, thalach, thal, sex, trestbps, exang, oldp...
18    1   mRMR     13  {ca, sex, thal, thalach, trestbps, exang, oldp...
21    1   DODA     13  {ca, thalach, thal, sex, trestbps, exang, oldp...
24    2   mRMR      5                {ca, thalach, thal, exang, oldpeak}
27    2   DODA      5                     {ca, thal, exang, oldpeak, cp}

Feature count check:

   Method  Top_K  Feature_Count
3    DODA      5              5
9    DODA      8              8
15   DODA     10             10
21   DODA     13             13
0    mRMR      5              5
6    mRMR      8              8
12   mRMR     10             10
18   mRMR     13             13

✓ All feature sets contain the expected number of features.

In [33]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# mRMR VS DODA-mRMR
# =============================================================================

selection_frequency = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]


        # -------------------------------------------------------------
        # Number of CV runs
        # -------------------------------------------------------------

        total_runs = len(subset)


        # -------------------------------------------------------------
        # All features appearing across the 25 runs
        # -------------------------------------------------------------

        all_features = sorted(
            set().union(
                *subset["Feature_Set"]
            )
        )


        # -------------------------------------------------------------
        # Calculate selection frequency
        # -------------------------------------------------------------

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set
                in subset["Feature_Set"]
            )


            selection_frequency.append({

                "Method": method,

                "Top_K": top_k,

                "Feature": feature,

                "Selected_Count": selected_count,

                "Total_Runs": total_runs,

                "Selection_Frequency_Percentage":
                    (
                        selected_count /
                        total_runs
                    ) * 100

            })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

selection_frequency_df = pd.DataFrame(
    selection_frequency
)


# =============================================================================
# SORT RESULTS
# =============================================================================

selection_frequency_df = (
    selection_frequency_df
    .sort_values(
        by=[
            "Method",
            "Top_K",
            "Selection_Frequency_Percentage"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
    .reset_index(drop=True)
)


# =============================================================================
# DISPLAY
# =============================================================================

print("=" * 80)
print("FEATURE SELECTION FREQUENCY")
print("=" * 80)

display(
    selection_frequency_df
)

================================================================================
FEATURE SELECTION FREQUENCY
================================================================================

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,DODA,5,ca,25,25,100.0
1,DODA,5,thal,25,25,100.0
2,DODA,5,exang,23,25,92.0
3,DODA,5,cp,18,25,72.0
4,DODA,5,oldpeak,17,25,68.0
...,...,...,...,...,...,...
78,mRMR,13,sex,25,25,100.0
79,mRMR,13,slope,25,25,100.0
80,mRMR,13,thal,25,25,100.0
81,mRMR,13,thalach,25,25,100.0
82,mRMR,13,trestbps,25,25,100.0

In [34]:
# =============================================================================
# TEST 2: JACCARD SIMILARITY
# =============================================================================

jaccard_results = []


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Jaccard comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )

                union = len(
                    set_a.union(set_b)
                )


                if union == 0:
                    jaccard = 0.0

                else:
                    jaccard = (
                        intersection / union
                    )


                jaccard_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Union": union,

                    "Jaccard_Similarity": jaccard

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

jaccard_df = pd.DataFrame(
    jaccard_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("JACCARD SIMILARITY — PAIRWISE RESULTS")
print("=" * 80)

display(
    jaccard_df
)


# =============================================================================
# JACCARD SUMMARY
# =============================================================================

jaccard_summary = (
    jaccard_df
    .groupby(
        ["Method", "Top_K"]
    )["Jaccard_Similarity"]
    .agg(
        Mean_Jaccard="mean",
        Std_Jaccard="std",
        Min_Jaccard="min",
        Max_Jaccard="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("JACCARD SIMILARITY SUMMARY")
print("=" * 80)

display(
    jaccard_summary
)

================================================================================
JACCARD SIMILARITY — PAIRWISE RESULTS
================================================================================

     Method  Top_K  Run_A  Run_B  Intersection  Union  Jaccard_Similarity
0      mRMR      5      1      2             4      6            0.666667
1      mRMR      5      1      3             4      6            0.666667
2      mRMR      5      1      4             4      6            0.666667
3      mRMR      5      1      5             4      6            0.666667
4      mRMR      5      1      6             5      5            1.000000
...     ...    ...    ...    ...           ...    ...                 ...
2395   DODA     13     22     24            13     13            1.000000
2396   DODA     13     22     25            13     13            1.000000
2397   DODA     13     23     24            13     13            1.000000
2398   DODA     13     23     25            13     13            1.000000
2399   DODA     13     24     25            13     13            1.000000

[2400 rows x 7 columns]

================================================================================
JACCARD SIMILARITY SUMMARY
================================================================================

  Method  Top_K  Mean_Jaccard  Std_Jaccard  Min_Jaccard  Max_Jaccard
0   DODA      5      0.715873     0.174381     0.428571          1.0
1   DODA      8      0.878519     0.110811     0.777778          1.0
2   DODA     10      0.892727     0.089574     0.818182          1.0
3   DODA     13      1.000000     0.000000     1.000000          1.0
4   mRMR      5      0.660635     0.165901     0.428571          1.0
5   mRMR      8      0.876296     0.110580     0.777778          1.0
6   mRMR     10      0.923636     0.089888     0.818182          1.0
7   mRMR     13      1.000000     0.000000     1.000000          1.0

In [35]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

Total number of features: 13
================================================================================
KUNCHEVA INDEX — PAIRWISE RESULTS
================================================================================

     Method  Top_K  Run_A  Run_B  Intersection  Kuncheva_Index
0      mRMR      5      1      2             4           0.675
1      mRMR      5      1      3             4           0.675
2      mRMR      5      1      4             4           0.675
3      mRMR      5      1      5             4           0.675
4      mRMR      5      1      6             5           1.000
...     ...    ...    ...    ...           ...             ...
2395   DODA     13     22     24            13             NaN
2396   DODA     13     22     25            13             NaN
2397   DODA     13     23     24            13             NaN
2398   DODA     13     23     25            13             NaN
2399   DODA     13     24     25            13             NaN

[2400 rows x 6 columns]

================================================================================
KUNCHEVA INDEX SUMMARY
================================================================================

  Method  Top_K  Mean_Kuncheva  Std_Kuncheva  Min_Kuncheva  Max_Kuncheva
0   DODA      5       0.711833      0.189959      0.350000           1.0
1   DODA      8       0.822333      0.162061      0.675000           1.0
2   DODA     10       0.744333      0.213484      0.566667           1.0
3   DODA     13            NaN           NaN           NaN           NaN
4   mRMR      5       0.649000      0.191748      0.350000           1.0
5   mRMR      8       0.819083      0.161723      0.675000           1.0
6   mRMR     10       0.818000      0.214233      0.566667           1.0
7   mRMR     13            NaN           NaN           NaN           NaN

In [39]:
# =============================================================================
# TEST 4: mRMR VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for top_k in sorted(stability_df["Top_K"].unique()):

    mrmr_subset = stability_df[
        (stability_df["Method"] == "mRMR") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    doda_subset = stability_df[
        (stability_df["Method"] == "DODA") &
        (stability_df["Top_K"] == top_k)
    ].copy()

    # Match mRMR and DODA feature sets from the same CV run
    merged = pd.merge(
        mrmr_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "mRMR_Feature_Set"}
        ),
        doda_subset[["Run", "Feature_Set"]].rename(
            columns={"Feature_Set": "DODA_Feature_Set"}
        ),
        on="Run",
        how="inner"
    )

    for _, row in merged.iterrows():

        mrmr_set = row["mRMR_Feature_Set"]
        doda_set = row["DODA_Feature_Set"]

        # Common features
        intersection = len(
            mrmr_set.intersection(doda_set)
        )

        # Total unique features
        union = len(
            mrmr_set.union(doda_set)
        )

        # Jaccard agreement
        if union == 0:
            jaccard_agreement = 0.0
        else:
            jaccard_agreement = intersection / union

        agreement_results.append({
            "Top_K": top_k,
            "Run": row["Run"],
            "mRMR_Features": sorted(mrmr_set),
            "DODA_Features": sorted(doda_set),
            "Common_Features": sorted(
                mrmr_set.intersection(doda_set)
            ),
            "Common_Feature_Count": intersection,
            "Jaccard_Agreement": jaccard_agreement
        })


# Convert to DataFrame
agreement_df = pd.DataFrame(agreement_results)

display(agreement_df)

,Top_K,Run,mRMR_Features,DODA_Features,Common_Features,Common_Feature_Count,Jaccard_Agreement
0,5,1,"[ca, cp, exang, oldpeak, thal]","[ca, cp, exang, oldpeak, thal]","[ca, cp, exang, oldpeak, thal]",5,1.000000
1,5,2,"[ca, exang, oldpeak, thal, thalach]","[ca, cp, exang, oldpeak, thal]","[ca, exang, oldpeak, thal]",4,0.666667
2,5,3,"[ca, cp, exang, restecg, thal]","[ca, cp, exang, restecg, thal]","[ca, cp, exang, restecg, thal]",5,1.000000
3,5,4,"[ca, cp, oldpeak, restecg, thal]","[ca, cp, oldpeak, restecg, thal]","[ca, cp, oldpeak, restecg, thal]",5,1.000000
4,5,5,"[ca, cp, exang, thal, thalach]","[ca, cp, exang, oldpeak, thal]","[ca, cp, exang, thal]",4,0.666667
...,...,...,...,...,...,...,...
95,13,21,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.000000
96,13,22,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.000000
97,13,23,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.000000
98,13,24,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.000000
99,13,25,"[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...","[age, ca, chol, cp, exang, fbs, oldpeak, reste...",13,1.000000

In [40]:
# =============================================================================
# mRMR VS DODA AGREEMENT SUMMARY
# =============================================================================

agreement_summary = (
    agreement_df
    .groupby("Top_K")["Jaccard_Agreement"]
    .agg(
        Mean_Agreement="mean",
        Std_Agreement="std",
        Min_Agreement="min",
        Max_Agreement="max"
    )
    .reset_index()
)

display(agreement_summary)

   Top_K  Mean_Agreement  Std_Agreement  Min_Agreement  Max_Agreement
0      5        0.933333       0.136083       0.666667            1.0
1      8        0.875556       0.112583       0.777778            1.0
2     10        0.970909       0.068030       0.818182            1.0
3     13        1.000000       0.000000       1.000000            1.0

# mRMR Feature Selection — Heart Disease

### Overall Interpretation

The mRMR experiment evaluated conventional **mRMR feature selection** against **mRMR + Rank Fusion DODA**, using Logistic Regression, Random Forest, and XGBoost across Top-5, Top-8, Top-10, and Top-13 feature subsets.

The current DODA implementation uses **Rank Fusion**, combining the mRMR-derived feature ranking with clinically informed feature ranking. The results show that DODA retains a substantial portion of the features identified by mRMR while modifying the feature ranking through the clinical knowledge layer.

The results demonstrate that DODA does **not uniformly improve every predictive metric or every model**. However, it maintains high agreement with mRMR and shows substantial feature-selection stability, particularly at Top-8 and Top-10.

## 1. mRMR Baseline Feature Selection

The mRMR baseline consistently prioritised a core group of heart-disease-related features.

At Top-5, the selected features were:

`thal, ca, exang, cp, oldpeak`

At Top-8, the feature set expanded to:

`thal, ca, exang, cp, oldpeak, thalach, sex, slope`

At Top-10, additional features were included as the subset size increased.

The repeated-selection results indicate that **thal and ca formed the most consistently selected core features**, with other variables such as `exang`, `cp`, and `oldpeak` also appearing frequently.

## 2. Effect of Rank Fusion DODA on Feature Selection

After applying Rank Fusion DODA, the Top-5 feature set remained:

`thal, ca, exang, cp, oldpeak`

Thus, at Top-5, DODA preserved the complete mRMR-selected feature set while incorporating the clinical ranking.

At Top-8, DODA selected:

`thal, ca, exang, cp, oldpeak, thalach, sex, slope`

Again, the selected subset remained highly consistent with the mRMR baseline.

At Top-10, DODA continued to retain the major mRMR features while incorporating additional features according to the fused ranking.

Therefore, unlike a feature-selection approach that substantially replaces the underlying statistical ranking, Rank Fusion DODA in this experiment primarily **preserved the mRMR core while using clinical information to determine the ordering and inclusion of additional features**.

This is also supported by the high mRMR–DODA feature-set agreement observed across the Top-K configurations.

## 3. Top-5 Predictive Performance

At Top-5, DODA produced mixed changes across the three models.

### Logistic Regression

The mRMR + DODA subset produced an accuracy of **85.25%**, with:

* Precision: **80.65%**
* Recall: **89.29%**
* F1-score: **84.75%**
* ROC-AUC: **0.9405**

The results indicate strong discriminative performance using only five selected features.

### Random Forest

The DODA subset produced:

* Accuracy: **72.13%**
* Precision: **66.67%**
* Recall: **78.57%**
* F1-score: **72.13%**
* ROC-AUC: **0.8777**

The tree-based model therefore showed lower predictive performance at Top-5 compared with the larger feature subsets.

### XGBoost

XGBoost produced:

* Accuracy: **78.69%**
* Precision: **75.86%**
* Recall: **78.57%**
* F1-score: **77.19%**
* ROC-AUC: **0.8793**

Thus, at Top-5, the reduced feature space was sufficient for Logistic Regression to obtain stronger performance than the tree-based models, while Random Forest and XGBoost benefited from additional features.

## 4. Top-8 Predictive Performance

At Top-8, DODA selected:

`thal, ca, exang, cp, oldpeak, thalach, sex, slope`

The DODA subset produced:

### Logistic Regression

* Accuracy: **85.25%**
* Precision: **80.65%**
* Recall: **89.29%**
* F1-score: **84.75%**
* ROC-AUC: **0.9351**

The model maintained strong performance while using only eight features.

### Random Forest

* Accuracy: **83.61%**
* Precision: **76.47%**
* Recall: **92.86%**
* F1-score: **83.87%**
* ROC-AUC: **0.9383**

Random Forest achieved substantially higher recall than at Top-5, indicating that the additional features improved identification of the positive class.

### XGBoost

* Accuracy: **85.25%**
* Precision: **82.76%**
* Recall: **85.71%**
* F1-score: **84.21%**
* ROC-AUC: **0.9253**

Overall, Top-8 provided a balanced feature subset with strong performance across all three models.

## 5. Top-10 Predictive Performance

At Top-10, DODA retained the core features:

`thal, ca, exang, cp, oldpeak, thalach, sex, slope`

while adding further features through the fused ranking.

This produced particularly strong results across the three models.

### Logistic Regression

The model achieved:

* Accuracy: **85.25%**
* Precision: **80.65%**
* Recall: **89.29%**
* F1-score: **84.75%**
* ROC-AUC: **0.9372**

The performance remained highly consistent with Top-8.

### Random Forest

Random Forest achieved:

* Accuracy: **86.89%**
* Precision: **81.25%**
* Recall: **92.86%**
* F1-score: **86.67%**
* ROC-AUC: **0.9562**

This represents the strongest ROC-AUC observed for the DODA evaluation in the reported results.

### XGBoost

XGBoost achieved:

* Accuracy: **83.61%**
* Precision: **76.47%**
* Recall: **92.86%**
* F1-score: **83.87%**
* ROC-AUC: **0.9145**

Thus, increasing the feature subset from Top-8 to Top-10 did not uniformly improve every metric, although performance remained strong.

## 6. Top-13

At Top-13, all available features are retained.

Therefore, feature selection becomes effectively inactive because the complete 13-feature space is used.

This provides a useful reference point for comparing the reduced Top-5, Top-8, and Top-10 configurations. Differences between mRMR and DODA at Top-13 are therefore not attributable to different feature subsets.

The DODA evaluation at Top-13 produced:

### Logistic Regression

* Accuracy: **86.89%**
* F1-score: **86.67%**
* ROC-AUC: **0.9513**

### Random Forest

* Accuracy: **88.52%**
* F1-score: **88.52%**
* ROC-AUC: **0.9481**

### XGBoost

* Accuracy: **86.89%**
* F1-score: **86.67%**
* ROC-AUC: **0.9102**

## 7. Cross-Validation Results

The repeated stratified cross-validation provides a more robust assessment than a single train-test evaluation.

The results show that the mRMR and mRMR-DODA approaches generally maintain **comparable predictive performance across the repeated folds**, with differences depending on the downstream model and Top-K value.

The DODA approach does not produce a consistent improvement across all models and metrics. Instead, its main effect is to preserve the strong mRMR feature-selection structure while incorporating the clinical ranking.

For example, at Top-10, the DODA configuration showed strong performance across all three classifiers, while at Top-5 the reduced feature space resulted in greater variation between Logistic Regression, Random Forest, and XGBoost.

Therefore, the repeated CV results support the interpretation that DODA provides **competitive and consistent predictive performance rather than a universal performance improvement**.

## 8. Feature-Selection Stability

Feature-selection stability is a strong finding of the mRMR-DODA experiment.

The mean Jaccard similarity values were:

| Top-K | mRMR Mean Jaccard | DODA Mean Jaccard | Interpretation             |
| ----: | ----------------: | ----------------: | -------------------------- |
|     5 |            0.6606 |        **0.7159** | Moderate-to-high stability |
|     8 |            0.8763 |        **0.8785** | High stability             |
|    10 |        **0.9236** |            0.8927 | Very high stability        |
|    13 |            1.0000 |            1.0000 | Complete stability         |

DODA therefore showed higher Jaccard stability at Top-5 and Top-8, while mRMR showed higher stability at Top-10.

The Kuncheva index showed a similar mixed pattern:

| Top-K | mRMR Mean Kuncheva | DODA Mean Kuncheva |
| ----: | -----------------: | -----------------: |
|     5 |             0.6490 |         **0.7118** |
|     8 |             0.8191 |         **0.8223** |
|    10 |         **0.8180** |             0.7443 |
|    13 |                N/A |                N/A |

The positive Kuncheva values indicate substantial overlap between feature subsets across repeated runs. Top-13 is not applicable because all 13 features are selected, leaving no feature-selection variability for the Kuncheva calculation.

Overall, both approaches demonstrated **high selection stability**, particularly as the number of selected features increased.

## 9. Overall Interpretation

The Heart Disease mRMR experiment demonstrates that **Rank Fusion DODA preserves a highly consistent core of mRMR-selected features while incorporating clinical information into the feature-ranking process**.

The most consistently retained features included:

`thal, ca, exang, cp, oldpeak, thalach, sex, slope`

The stability analysis shows that DODA achieved strong reproducibility, with mean Jaccard similarity of **0.7159 at Top-5, 0.8785 at Top-8, and 0.8927 at Top-10**. The corresponding Kuncheva values were also positive, indicating substantial agreement between repeated feature subsets.

The mRMR–DODA feature-set agreement was particularly high, with the two approaches retaining a large proportion of common features across the Top-K configurations. This indicates that the clinical knowledge layer **modifies rather than fundamentally replaces the information captured by mRMR**.

Predictively, DODA does not consistently outperform mRMR across every classifier and Top-K configuration. Instead, performance varies according to the downstream model and subset size. The Top-8 and Top-10 configurations provide a useful balance between dimensionality reduction and predictive performance, while Top-13 serves as the full-feature reference.

Overall, the mRMR experiment supports Rank Fusion DODA as a **clinically guided extension of mRMR that maintains high feature-set agreement, substantial selection stability, and competitive predictive performance**. Its contribution is therefore not simply an increase in predictive accuracy, but the integration of clinical knowledge into a reproducible feature-selection framework.