In [1]:
# =============================================================================
# STEP 1: LOAD PROCESSED DATASET
# =============================================================================

import pandas as pd
import numpy as np


# Load cleaned dataset
df = pd.read_csv(
    "../../../data/processed/heartdisease_cleaned.csv"
)


print("=" * 70)
print("PROCESSED DATASET")
print("=" * 70)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")


display(df.head())

======================================================================
PROCESSED DATASET
======================================================================
Rows    : 303
Columns : 14

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [2]:
# =============================================================================
# STEP 2: FEATURE AND TARGET SEPARATION
# =============================================================================

target_column = "target"


X = df.drop(
    target_column,
    axis=1
)


y = df[target_column]


print("=" * 70)
print("FEATURE MATRIX (X)")
print("=" * 70)

print(f"Rows    : {X.shape[0]}")
print(f"Columns : {X.shape[1]}")


print("\n" + "=" * 70)
print("TARGET VARIABLE (y)")
print("=" * 70)

print(f"Rows : {y.shape[0]}")


display(y.head())

======================================================================
FEATURE MATRIX (X)
======================================================================
Rows    : 303
Columns : 13

======================================================================
TARGET VARIABLE (y)
======================================================================
Rows : 303

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [3]:
# =============================================================================
# STEP 3: VERIFY TARGET DISTRIBUTION
# =============================================================================

print("=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)


display(
    y.value_counts()
)


print("\nClass Percentage")


display(
    (y.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TARGET DISTRIBUTION
======================================================================

target
0    164
1    139
Name: count, dtype: int64

Class Percentage

target
0    54.13
1    45.87
Name: proportion, dtype: float64

In [4]:
# =============================================================================
# STEP 4: FEATURE TYPE CHECK
# =============================================================================

print("=" * 70)
print("FEATURE DATA TYPES")
print("=" * 70)


display(
    X.dtypes.to_frame(
        name="Data Type"
    )
)

======================================================================
FEATURE DATA TYPES
======================================================================

         Data Type
age        float64
sex        float64
cp         float64
trestbps   float64
chol       float64
fbs        float64
restecg    float64
thalach    float64
exang      float64
oldpeak    float64
slope      float64
ca         float64
thal       float64

In [5]:
# =============================================================================
# STEP 5: MISSING VALUE CHECK
# =============================================================================

print("=" * 70)
print("MISSING VALUES")
print("=" * 70)


missing = pd.DataFrame({
    "Missing Count": X.isnull().sum(),
    "Missing Percentage (%)": (
        X.isnull().mean() * 100
    ).round(2)
})


display(
    missing[missing["Missing Count"] > 0]
)

======================================================================
MISSING VALUES
======================================================================

      Missing Count  Missing Percentage (%)
ca                4                    1.32
thal              2                    0.66

In [6]:
# =============================================================================
# STEP 6: MISSING VALUE IMPUTATION
# =============================================================================

from sklearn.impute import SimpleImputer


imputer = SimpleImputer(
    strategy="median"
)


X_imputed = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index=X.index
)


print("=" * 70)
print("MISSING VALUE IMPUTATION")
print("=" * 70)

print("Imputation completed successfully")


print("\nRemaining Missing Values:")
print(X_imputed.isnull().sum().sum())

======================================================================
MISSING VALUE IMPUTATION
======================================================================
Imputation completed successfully

Remaining Missing Values:
0

In [7]:
# =============================================================================
# STEP 7: TRAIN-TEST SPLIT
# =============================================================================

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X_imputed,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)


print("Training Data")
print("-" * 70)

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


print("\nTesting Data")
print("-" * 70)

print(f"X_test shape  : {X_test.shape}")
print(f"y_test shape  : {y_test.shape}")

======================================================================
TRAIN-TEST SPLIT
======================================================================
Training Data
----------------------------------------------------------------------
X_train shape : (242, 13)
y_train shape : (242,)

Testing Data
----------------------------------------------------------------------
X_test shape  : (61, 13)
y_test shape  : (61,)

In [8]:
# =============================================================================
# STEP 8: CLASS DISTRIBUTION AFTER SPLIT
# =============================================================================

print("=" * 70)
print("TRAINING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_train.value_counts(normalize=True) * 100)
    .round(2)
)


print("\n" + "=" * 70)
print("TESTING TARGET DISTRIBUTION")
print("=" * 70)


display(
    (y_test.value_counts(normalize=True) * 100)
    .round(2)
)

======================================================================
TRAINING TARGET DISTRIBUTION
======================================================================

target
0    54.13
1    45.87
Name: proportion, dtype: float64

======================================================================
TESTING TARGET DISTRIBUTION
======================================================================

target
0    54.1
1    45.9
Name: proportion, dtype: float64

In [9]:
# =============================================================================
# STEP 9: FEATURE SCALING
# =============================================================================

from sklearn.preprocessing import StandardScaler


print("=" * 70)
print("FEATURE SCALING USING STANDARD SCALER")
print("=" * 70)


scaler = StandardScaler()


# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(
    X_train
)


# Transform test data
X_test_scaled = scaler.transform(
    X_test
)


print("Scaling completed successfully")


print("\n" + "=" * 70)
print("SHAPE AFTER SCALING")
print("=" * 70)


print(
    f"X_train_scaled shape : {X_train_scaled.shape}"
)

print(
    f"X_test_scaled shape  : {X_test_scaled.shape}"
)

======================================================================
FEATURE SCALING USING STANDARD SCALER
======================================================================
Scaling completed successfully

======================================================================
SHAPE AFTER SCALING
======================================================================
X_train_scaled shape : (242, 13)
X_test_scaled shape  : (61, 13)

In [10]:
# =============================================================================
# STEP 10: CONVERT SCALED DATA BACK TO DATAFRAME
# =============================================================================


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)


X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)


print("=" * 70)
print("SCALED TRAIN DATA PREVIEW")
print("=" * 70)


display(
    X_train_scaled.head()
)

======================================================================
SCALED TRAIN DATA PREVIEW
======================================================================

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973

In [11]:
# =============================================================================
# STEP 11: SCALING VERIFICATION
# =============================================================================

print("=" * 70)
print("MEAN AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.mean().round(2)
)


print("\n" + "=" * 70)
print("STANDARD DEVIATION AFTER SCALING")
print("=" * 70)


display(
    X_train_scaled.std().round(2)
)

======================================================================
MEAN AFTER SCALING
======================================================================

age        -0.0
sex         0.0
cp          0.0
trestbps   -0.0
chol        0.0
fbs        -0.0
restecg     0.0
thalach    -0.0
exang       0.0
oldpeak     0.0
slope      -0.0
ca          0.0
thal        0.0
dtype: float64

======================================================================
STANDARD DEVIATION AFTER SCALING
======================================================================

age         1.0
sex         1.0
cp          1.0
trestbps    1.0
chol        1.0
fbs         1.0
restecg     1.0
thalach     1.0
exang       1.0
oldpeak     1.0
slope       1.0
ca          1.0
thal        1.0
dtype: float64

# ANNOVA

## 1. Baseline

In [12]:
# =============================================================================
# ANOVA BASELINE FEATURE SELECTION
# =============================================================================

from sklearn.feature_selection import (
    SelectKBest,
    f_classif
)


# Fit ANOVA once with all features

anova_selector = SelectKBest(
    score_func=f_classif,
    k="all"
)


anova_selector.fit(
    X_train_scaled,
    y_train
)


# Create score dataframe

anova_scores = pd.DataFrame({

    "Feature":
        X_train_scaled.columns,

    "ANOVA Score":
        anova_selector.scores_

})


# Sort by ANOVA score

anova_scores = (
    anova_scores
    .sort_values(
        by="ANOVA Score",
        ascending=False
    )
    .reset_index(drop=True)
)


display(anova_scores)

     Feature  ANOVA Score
0       thal   101.032412
1         ca    60.252389
2      exang    51.486909
3    thalach    48.347133
4         cp    45.883288
5    oldpeak    43.615028
6      slope    28.023125
7        sex    25.215352
8        age    11.035221
9    restecg     6.334802
10  trestbps     4.528441
11      chol     1.438593
12       fbs     0.506449

In [13]:
# =============================================================================
# TOP-K ANOVA FEATURES
# =============================================================================

k_values = [5, 8, 10, 13]


anova_results = {}


for k in k_values:

    top_features = (
        anova_scores
        .head(k)["Feature"]
        .tolist()
    )


    mask = X_train_scaled.columns.isin(
        top_features
    )


    X_train_selected = (
        X_train_scaled.loc[:, mask]
    )


    X_test_selected = (
        X_test_scaled.loc[:, mask]
    )


    anova_results[k] = {

        "features":
            top_features,

        "X_train":
            X_train_selected,

        "X_test":
            X_test_selected,

        "scores":
            anova_scores.head(k)
    }


    print("=" * 70)
    print(f"TOP {k} ANOVA FEATURES")
    print("=" * 70)

    print(top_features)

    print("\nScores:")

    display(
        anova_scores.head(k)
    )

======================================================================
TOP 5 ANOVA FEATURES
======================================================================
['thal', 'ca', 'exang', 'thalach', 'cp']

Scores:

   Feature  ANOVA Score
0     thal   101.032412
1       ca    60.252389
2    exang    51.486909
3  thalach    48.347133
4       cp    45.883288

======================================================================
TOP 8 ANOVA FEATURES
======================================================================
['thal', 'ca', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'sex']

Scores:

   Feature  ANOVA Score
0     thal   101.032412
1       ca    60.252389
2    exang    51.486909
3  thalach    48.347133
4       cp    45.883288
5  oldpeak    43.615028
6    slope    28.023125
7      sex    25.215352

======================================================================
TOP 10 ANOVA FEATURES
======================================================================
['thal', 'ca', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'sex', 'age', 'restecg']

Scores:

   Feature  ANOVA Score
0     thal   101.032412
1       ca    60.252389
2    exang    51.486909
3  thalach    48.347133
4       cp    45.883288
5  oldpeak    43.615028
6    slope    28.023125
7      sex    25.215352
8      age    11.035221
9  restecg     6.334802

======================================================================
TOP 13 ANOVA FEATURES
======================================================================
['thal', 'ca', 'exang', 'thalach', 'cp', 'oldpeak', 'slope', 'sex', 'age', 'restecg', 'trestbps', 'chol', 'fbs']

Scores:

     Feature  ANOVA Score
0       thal   101.032412
1         ca    60.252389
2      exang    51.486909
3    thalach    48.347133
4         cp    45.883288
5    oldpeak    43.615028
6      slope    28.023125
7        sex    25.215352
8        age    11.035221
9    restecg     6.334802
10  trestbps     4.528441
11      chol     1.438593
12       fbs     0.506449

In [14]:
# =============================================================================
# BASELINE MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression":
        LogisticRegression(
            max_iter=1000,
            random_state=42
        ),


    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),


    "XGBoost":
        XGBClassifier(
            n_estimators=200,
            random_state=42,
            eval_metric="logloss"
        )
}

In [15]:
# =============================================================================
# ANOVA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


results = []


for k in k_values:

    Xtr = anova_results[k]["X_train"]
    Xts = anova_results[k]["X_test"]


    features = ", ".join(
        anova_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        results.append({

            "Method":
                "ANOVA",

            "Top-K":
                k,

            "Model":
                model_name,

            "Selected Features":
                features,

            "Accuracy":
                accuracy_score(
                    y_test,
                    y_pred
                ),

            "Precision":
                precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

            "Recall":
                recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

            "F1 Score":
                f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

            "ROC-AUC":
                roc_auc_score(
                    y_test,
                    y_prob
                )
        })


results_df = pd.DataFrame(
    results
)


display(results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"thal, ca, exang, thalach, cp",0.836066,0.800000,0.857143,0.827586,0.919913
1,ANOVA,5,Random Forest,"thal, ca, exang, thalach, cp",0.868852,0.884615,0.821429,0.851852,0.933442
2,ANOVA,5,XGBoost,"thal, ca, exang, thalach, cp",0.852459,0.851852,0.821429,0.836364,0.930736
3,ANOVA,8,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.852459,0.806452,0.892857,0.847458,0.935065
4,ANOVA,8,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.852459,0.787879,0.928571,0.852459,0.939394
5,ANOVA,8,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.819672,0.793103,0.821429,0.807018,0.929654
6,ANOVA,10,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.852459,0.806452,0.892857,0.847458,0.937229
7,ANOVA,10,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.836066,0.750000,0.964286,0.843750,0.951299
8,ANOVA,10,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.933983
9,ANOVA,13,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.951299
10,ANOVA,13,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.901639,0.843750,0.964286,0.900000,0.955087
11,ANOVA,13,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.910173

In [16]:
# =============================================================================
# SAVE ANOVA BASELINE RESULTS
# =============================================================================

results_df.to_csv(
    "../../../results/heart_disease/baseline/anova_baseline_results.csv",
    index=False
)

## 2. DODA

In [17]:
#%pip uninstall -y doda

In [18]:
#%pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

In [19]:
import doda

print(doda.__file__)

from doda.knowledge import JSONProvider
from doda.fusion import RankFusion

print("JSONProvider:", JSONProvider)
print("RankFusion:", RankFusion)

c:\Users\Anandha Lakshmi\Downloads\Anaconda\Lib\site-packages\doda\__init__.py
JSONProvider: <class 'doda.knowledge.providers.json_provider.JSONProvider'>
RankFusion: <class 'doda.fusion.rank.RankFusion'>

In [20]:
# =============================================================================
# DODA IMPORTS
# =============================================================================

from sklearn.feature_selection import (
    SelectKBest,
    f_classif
)

from doda import DODASelector

from doda.adapters import (
    SklearnAdapter
)

from doda.knowledge.providers import (
    JSONProvider
)

from doda.fusion import (
    RankFusion
)

In [21]:
# =============================================================================
# ANOVA + RANK FUSION DODA FEATURE SELECTION
# =============================================================================

import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif


# -------------------------------------------------------------------------
# Top-K values
# -------------------------------------------------------------------------

k_values = [5, 8, 10, 13]


# -------------------------------------------------------------------------
# Clinical knowledge provider
# -------------------------------------------------------------------------

provider = JSONProvider(
    "heartdisease_weights.json"
)


# -------------------------------------------------------------------------
# Fusion method
# -------------------------------------------------------------------------
# Rank-based fusion instead of Hadamard multiplication

fusion = RankFusion()


# -------------------------------------------------------------------------
# Store DODA results
# -------------------------------------------------------------------------

rank_doda_results = {}


# =============================================================================
# RUN DODA FOR EACH TOP-K
# =============================================================================

for k in k_values:

    print("\n" + "=" * 70)
    print(f"ANOVA + RANK FUSION DODA — TOP {k} FEATURES")
    print("=" * 70)


    # ---------------------------------------------------------------------
    # ANOVA operator
    # ---------------------------------------------------------------------

    anova = SklearnAdapter(
        SelectKBest(
            score_func=f_classif,
            k=k
        )
    )


    # ---------------------------------------------------------------------
    # DODA selector
    # ---------------------------------------------------------------------

    selector = DODASelector(
        operators=[anova],
        provider=provider,
        fusion=fusion,
        top_k=k
    )


    # ---------------------------------------------------------------------
    # Fit DODA on TRAINING data
    # ---------------------------------------------------------------------

    X_train_selected = selector.fit_transform(
        X_train_scaled,
        y_train
    )


    # ---------------------------------------------------------------------
    # Transform TEST data
    # ---------------------------------------------------------------------

    X_test_selected = selector.transform(
        X_test_scaled
    )


    # ---------------------------------------------------------------------
    # Selected features
    # ---------------------------------------------------------------------

    selected_features = selector.get_selected_features()


    print("\nSelected Features:")
    print(selected_features)


    # ---------------------------------------------------------------------
    # Store everything needed for later evaluation
    # ---------------------------------------------------------------------

    rank_doda_results[k] = {

        "selector": selector,

        "X_train": X_train_selected,

        "X_test": X_test_selected,

        "features": selected_features,

        "raw_math_scores":
            selector.raw_math_scores_,

        "math_scores":
            selector.math_scores_,

        "clinical_weights":
            selector.clinical_weights_,

        "final_scores":
            selector.final_scores_
    }


print("\n" + "=" * 70)
print("ANOVA + RANK FUSION DODA COMPLETED")
print("=" * 70)

======================================================================
ANOVA + RANK FUSION DODA — TOP 5 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082074D0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}

Normalized Mathematical Scores
{'age': np.float64(0.10922455892926354), 'sex': np.float64(0.24957685982541794), 'cp': np.float64(0.454144240669995), 'trestbps': np.float64(0.04482166779907261), 'chol': np.float64(0.014238922287468215), 'fbs': np.float64(0.005012739718852071), 'restecg': np.float64(0.06270068975576748), 'thalach': np.float64(0.4785309209749201), 'exang': np.float64(0.5096078372578391), 'oldpeak': np.float64(0.4316934226139958), 'slope': np.float64(0.27736767450322286), 'ca': np.float64(0.5963669244895055), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak']

======================================================================
ANOVA + RANK FUSION DODA — TOP 8 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082074D0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}

Normalized Mathematical Scores
{'age': np.float64(0.10922455892926354), 'sex': np.float64(0.24957685982541794), 'cp': np.float64(0.454144240669995), 'trestbps': np.float64(0.04482166779907261), 'chol': np.float64(0.014238922287468215), 'fbs': np.float64(0.005012739718852071), 'restecg': np.float64(0.06270068975576748), 'thalach': np.float64(0.4785309209749201), 'exang': np.float64(0.5096078372578391), 'oldpeak': np.float64(0.4316934226139958), 'slope': np.float64(0.27736767450322286), 'ca': np.float64(0.5963669244895055), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age']

======================================================================
ANOVA + RANK FUSION DODA — TOP 10 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082074D0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}

Normalized Mathematical Scores
{'age': np.float64(0.10922455892926354), 'sex': np.float64(0.24957685982541794), 'cp': np.float64(0.454144240669995), 'trestbps': np.float64(0.04482166779907261), 'chol': np.float64(0.014238922287468215), 'fbs': np.float64(0.005012739718852071), 'restecg': np.float64(0.06270068975576748), 'thalach': np.float64(0.4785309209749201), 'exang': np.float64(0.5096078372578391), 'oldpeak': np.float64(0.4316934226139958), 'slope': np.float64(0.27736767450322286), 'ca': np.float64(0.5963669244895055), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps']

======================================================================
ANOVA + RANK FUSION DODA — TOP 13 FEATURES
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082074D0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.035220646205753), 'sex': np.float64(25.215352145704667), 'cp': np.float64(45.88328806383722), 'trestbps': np.float64(4.528441210863827), 'chol': np.float64(1.4385926640193571), 'fbs': np.float64(0.506449184888505), 'restecg': np.float64(6.334801924650374), 'thalach': np.float64(48.34713319749084), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(43.61502776263317), 'slope': np.float64(28.02312518607009), 'ca': np.float64(60.25238886158248), 'thal': np.float64(101.0324120727503)}

Normalized Mathematical Scores
{'age': np.float64(0.10922455892926354), 'sex': np.float64(0.24957685982541794), 'cp': np.float64(0.454144240669995), 'trestbps': np.float64(0.04482166779907261), 'chol': np.float64(0.014238922287468215), 'fbs': np.float64(0.005012739718852071), 'restecg': np.float64(0.06270068975576748), 'thalach': np.float64(0.4785309209749201), 'exang': np.float64(0.5096078372578391), 'oldpeak': np.float64(0.4316934226139958), 'slope': np.float64(0.27736767450322286), 'ca': np.float64(0.5963669244895055), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']

Selected Features:
['thal', 'ca', 'exang', 'cp', 'oldpeak', 'thalach', 'slope', 'age', 'sex', 'trestbps', 'restecg', 'chol', 'fbs']

======================================================================
ANOVA + RANK FUSION DODA COMPLETED
======================================================================

In [22]:
# =============================================================================
# INSPECT MATHEMATICAL SCORES
# =============================================================================

k = 10

selector = rank_doda_results[k]["selector"]


# -------------------------------------------------------------------------
# Raw mathematical scores
# -------------------------------------------------------------------------

raw_math_scores = pd.DataFrame(
    selector.raw_math_scores_.items(),
    columns=[
        "Feature",
        "Raw Math Score"
    ]
)


# -------------------------------------------------------------------------
# Normalized mathematical scores
# -------------------------------------------------------------------------

normalized_math_scores = pd.DataFrame(
    selector.math_scores_.items(),
    columns=[
        "Feature",
        "Normalized Math Score"
    ]
)


# -------------------------------------------------------------------------
# Combine both
# -------------------------------------------------------------------------

math_scores = raw_math_scores.merge(
    normalized_math_scores,
    on="Feature"
)


math_scores = math_scores.sort_values(
    by="Normalized Math Score",
    ascending=False
)


print("=" * 70)
print("MATHEMATICAL SCORES")
print("=" * 70)

display(math_scores)

======================================================================
MATHEMATICAL SCORES
======================================================================

     Feature  Raw Math Score  Normalized Math Score
12      thal      101.032412               1.000000
11        ca       60.252389               0.596367
8      exang       51.486909               0.509608
7    thalach       48.347133               0.478531
2         cp       45.883288               0.454144
9    oldpeak       43.615028               0.431693
10     slope       28.023125               0.277368
1        sex       25.215352               0.249577
0        age       11.035221               0.109225
6    restecg        6.334802               0.062701
3   trestbps        4.528441               0.044822
4       chol        1.438593               0.014239
5        fbs        0.506449               0.005013

In [23]:
# =============================================================================
# INSPECT CLINICAL WEIGHTS
# =============================================================================

clinical_weights = pd.DataFrame(
    selector.clinical_weights_.items(),
    columns=[
        "Feature",
        "Clinical Weight"
    ]
)


clinical_weights = clinical_weights.sort_values(
    by="Clinical Weight",
    ascending=False
)


print("=" * 70)
print("CLINICAL WEIGHTS")
print("=" * 70)

display(clinical_weights)

======================================================================
CLINICAL WEIGHTS
======================================================================

     Feature  Clinical Weight
2         cp              1.0
9    oldpeak              1.0
11        ca              1.0
12      thal              1.0
8      exang              1.0
10     slope              0.9
0        age              0.9
3   trestbps              0.9
4       chol              0.8
7    thalach              0.8
6    restecg              0.8
1        sex              0.6
5        fbs              0.6

In [24]:
# =============================================================================
# INSPECT FINAL RANK FUSION SCORES
# =============================================================================

final_scores = pd.DataFrame(
    selector.final_scores_.items(),
    columns=[
        "Feature",
        "Final Rank Fusion Score"
    ]
)


final_scores = final_scores.sort_values(
    by="Final Rank Fusion Score",
    ascending=False
)


print("=" * 70)
print("FINAL RANK FUSION SCORES")
print("=" * 70)

display(final_scores)

======================================================================
FINAL RANK FUSION SCORES
======================================================================

     Feature  Final Rank Fusion Score
12      thal                 0.032787
11        ca                 0.032522
8      exang                 0.032266
2         cp                 0.031778
9    oldpeak                 0.031545
7    thalach                 0.031498
10     slope                 0.031054
0        age                 0.030622
1        sex                 0.030331
3   trestbps                 0.030214
6    restecg                 0.030159
4       chol                 0.029762
5        fbs                 0.029324

In [25]:
# =============================================================================
# SELECTED FEATURES
# =============================================================================

selector.get_selected_features()

['thal',
 'ca',
 'exang',
 'cp',
 'oldpeak',
 'thalach',
 'slope',
 'age',
 'sex',
 'trestbps']

In [26]:
# =============================================================================
# COMPARE RANKINGS
# =============================================================================

comparison = selector.compare_scores()

display(comparison)

======================================================================
MATHEMATICAL vs CLINICAL vs RANKFUSION
======================================================================

Fusion Method: RankFusion

Top Features After Fusion:
    Feature  Math Rank  Clinical Rank  Final Rank  Rank Change
0      thal          1              5           1            0
1        ca          2              4           2            0
2     exang          3              2           3            0
3        cp          5              1           4            1
4   oldpeak          6              3           5            1
5   thalach          4             11           6           -2
6     slope          7              8           7            0
7       age          9              6           8            1
8       sex          8             12           9           -1
9  trestbps         11              7          10            1

,Feature,Math Rank,Normalized Math Score,Clinical Rank,Clinical Weight,Final Rank,Final Score,Rank Change
0,thal,1,1.0000,5,1.0,1,0.0328,0
1,ca,2,0.5964,4,1.0,2,0.0325,0
2,exang,3,0.5096,2,1.0,3,0.0323,0
3,cp,5,0.4541,1,1.0,4,0.0318,1
4,oldpeak,6,0.4317,3,1.0,5,0.0315,1
5,thalach,4,0.4785,11,0.8,6,0.0315,-2
6,slope,7,0.2774,8,0.9,7,0.0311,0
7,age,9,0.1092,6,0.9,8,0.0306,1
8,sex,8,0.2496,12,0.6,9,0.0303,-1
9,trestbps,11,0.0448,7,0.9,10,0.0302,1
10,restecg,10,0.0627,10,0.8,11,0.0302,-1
11,chol,12,0.0142,9,0.8,12,0.0298,0
12,fbs,13,0.0050,13,0.6,13,0.0293,0

In [27]:
# =============================================================================
#  MODELS
# =============================================================================

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "Logistic Regression":
        LogisticRegression(
            max_iter=1000,
            random_state=42
        ),


    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),


    "XGBoost":
        XGBClassifier(
            n_estimators=200,
            random_state=42,
            eval_metric="logloss"
        )
}

In [28]:
# =============================================================================
# RANK FUSION DODA MODEL EVALUATION
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


rank_doda_model_results = []


for k in k_values:

    Xtr = rank_doda_results[k]["X_train"]

    Xts = rank_doda_results[k]["X_test"]

    features = ", ".join(
        rank_doda_results[k]["features"]
    )


    for model_name, model in models.items():

        model.fit(
            Xtr,
            y_train
        )


        y_pred = model.predict(
            Xts
        )


        y_prob = model.predict_proba(
            Xts
        )[:, 1]


        rank_doda_model_results.append({

            "Method": "ANOVA + Rank Fusion DODA",

            "Top-K": k,

            "Model": model_name,

            "Selected Features": features,

            "Accuracy": accuracy_score(
                y_test,
                y_pred
            ),

            "Precision": precision_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "Recall": recall_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "F1 Score": f1_score(
                y_test,
                y_pred,
                zero_division=0
            ),

            "ROC-AUC": roc_auc_score(
                y_test,
                y_prob
            )
        })


doda_results_df = pd.DataFrame(
    rank_doda_model_results
)


display(doda_results_df)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA + Rank Fusion DODA,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476
1,ANOVA + Rank Fusion DODA,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.877706
2,ANOVA + Rank Fusion DODA,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.786885,0.758621,0.785714,0.771930,0.879329
3,ANOVA + Rank Fusion DODA,8,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.885246,0.838710,0.928571,0.881356,0.939394
4,ANOVA + Rank Fusion DODA,8,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.885246,0.838710,0.928571,0.881356,0.950758
5,ANOVA + Rank Fusion DODA,8,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.836066,0.764706,0.928571,0.838710,0.922078
6,ANOVA + Rank Fusion DODA,10,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.944805
7,ANOVA + Rank Fusion DODA,10,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.961039
8,ANOVA + Rank Fusion DODA,10,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.852459,0.771429,0.964286,0.857143,0.941558
9,ANOVA + Rank Fusion DODA,13,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.951299
10,ANOVA + Rank Fusion DODA,13,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.918033,0.870968,0.964286,0.915254,0.964286
11,ANOVA + Rank Fusion DODA,13,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.910173

In [29]:
# =============================================================================
# SAVE DODA RESULTS
# =============================================================================


doda_results_df.to_csv(
    "../../../results/heart_disease/doda/anova_doda_results.csv",
    index=False
)

In [30]:
# =============================================================================
# COMBINED COMPARISON
# =============================================================================


comparison_df = pd.concat(
    [
        results_df,
        doda_results_df
    ],
    ignore_index=True
)


display(
    comparison_df
)

,Method,Top-K,Model,Selected Features,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,ANOVA,5,Logistic Regression,"thal, ca, exang, thalach, cp",0.836066,0.800000,0.857143,0.827586,0.919913
1,ANOVA,5,Random Forest,"thal, ca, exang, thalach, cp",0.868852,0.884615,0.821429,0.851852,0.933442
2,ANOVA,5,XGBoost,"thal, ca, exang, thalach, cp",0.852459,0.851852,0.821429,0.836364,0.930736
3,ANOVA,8,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.852459,0.806452,0.892857,0.847458,0.935065
4,ANOVA,8,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.852459,0.787879,0.928571,0.852459,0.939394
5,ANOVA,8,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, sex",0.819672,0.793103,0.821429,0.807018,0.929654
6,ANOVA,10,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.852459,0.806452,0.892857,0.847458,0.937229
7,ANOVA,10,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.836066,0.750000,0.964286,0.843750,0.951299
8,ANOVA,10,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.933983
9,ANOVA,13,Logistic Regression,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.951299
10,ANOVA,13,Random Forest,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.901639,0.843750,0.964286,0.900000,0.955087
11,ANOVA,13,XGBoost,"thal, ca, exang, thalach, cp, oldpeak, slope, ...",0.868852,0.812500,0.928571,0.866667,0.910173
12,ANOVA + Rank Fusion DODA,5,Logistic Regression,"thal, ca, exang, cp, oldpeak",0.852459,0.806452,0.892857,0.847458,0.940476
13,ANOVA + Rank Fusion DODA,5,Random Forest,"thal, ca, exang, cp, oldpeak",0.721311,0.666667,0.785714,0.721311,0.877706
14,ANOVA + Rank Fusion DODA,5,XGBoost,"thal, ca, exang, cp, oldpeak",0.786885,0.758621,0.785714,0.771930,0.879329
15,ANOVA + Rank Fusion DODA,8,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.885246,0.838710,0.928571,0.881356,0.939394
16,ANOVA + Rank Fusion DODA,8,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.885246,0.838710,0.928571,0.881356,0.950758
17,ANOVA + Rank Fusion DODA,8,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, age",0.836066,0.764706,0.928571,0.838710,0.922078
18,ANOVA + Rank Fusion DODA,10,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.944805
19,ANOVA + Rank Fusion DODA,10,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.961039
20,ANOVA + Rank Fusion DODA,10,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.852459,0.771429,0.964286,0.857143,0.941558
21,ANOVA + Rank Fusion DODA,13,Logistic Regression,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.951299
22,ANOVA + Rank Fusion DODA,13,Random Forest,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.918033,0.870968,0.964286,0.915254,0.964286
23,ANOVA + Rank Fusion DODA,13,XGBoost,"thal, ca, exang, cp, oldpeak, thalach, slope, ...",0.868852,0.812500,0.928571,0.866667,0.910173

In [31]:
# ============================================================
# DODA STABILITY ANALYSIS — ALL TOP-K VALUES
# Heart Disease Dataset
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "heartdisease_weights.json"


# ============================================================
# DATA
# ============================================================

# X and y should already contain the original Heart Disease data
# BEFORE imputation/scaling.

# Example:
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

all_runs = []
all_jaccard = []
all_frequency = []


# ============================================================
# LOOP THROUGH ALL TOP-K VALUES
# ============================================================

for TOP_K in TOP_K_VALUES:

    print("\n" + "=" * 70)
    print(f"DODA STABILITY ANALYSIS — TOP-{TOP_K}")
    print("=" * 70)

    selected_feature_sets = []

    run_number = 0

    # --------------------------------------------------------
    # 25 repeated CV runs
    # --------------------------------------------------------

    for train_idx, val_idx in cv.split(X, y):

        run_number += 1

        X_train = X.iloc[train_idx].copy()
        y_train = y.iloc[train_idx].copy()

        X_val = X.iloc[val_idx].copy()
        y_val = y.iloc[val_idx].copy()

        # ----------------------------------------------------
        # Imputation fitted ONLY on training data
        # ----------------------------------------------------

        imputer = SimpleImputer(strategy="median")

        X_train_imp = pd.DataFrame(
            imputer.fit_transform(X_train),
            columns=X_train.columns,
            index=X_train.index
        )

        X_val_imp = pd.DataFrame(
            imputer.transform(X_val),
            columns=X_val.columns,
            index=X_val.index
        )

        # ----------------------------------------------------
        # ANOVA operator
        #
        # k="all" because DODA itself performs Top-K ranking
        # ----------------------------------------------------

        anova_operator = SklearnAdapter(
            SelectKBest(
                score_func=f_classif,
                k="all"
            )
        )

        # ----------------------------------------------------
        # Clinical knowledge provider
        # ----------------------------------------------------

        provider = JSONProvider(WEIGHTS_FILE)

        # ----------------------------------------------------
        # DODA selector
        # ----------------------------------------------------

        doda_selector = DODASelector(
            operators=[anova_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=TOP_K
        )

        # ----------------------------------------------------
        # Fit ONLY on training fold
        # ----------------------------------------------------

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        # ----------------------------------------------------
        # Selected features
        # ----------------------------------------------------

        selected_features = list(
            doda_selector.get_selected_features()
        )

        selected_feature_sets.append(set(selected_features))

        all_runs.append({
            "Top_K": TOP_K,
            "Run": run_number,
            "Selected_Features": selected_features
        })

        print(
            f"Run {run_number:02d}: "
            f"{selected_features}"
        )


    # ========================================================
    # JACCARD SIMILARITY
    # ========================================================

    jaccard_scores = []

    for i in range(len(selected_feature_sets)):

        for j in range(i + 1, len(selected_feature_sets)):

            set_a = selected_feature_sets[i]
            set_b = selected_feature_sets[j]

            intersection = len(set_a.intersection(set_b))
            union = len(set_a.union(set_b))

            jaccard = intersection / union

            jaccard_scores.append(jaccard)

            all_jaccard.append({
                "Top_K": TOP_K,
                "Run_A": i + 1,
                "Run_B": j + 1,
                "Jaccard_Similarity": jaccard
            })


    # ========================================================
    # STABILITY SUMMARY
    # ========================================================

    mean_jaccard = np.mean(jaccard_scores)
    std_jaccard = np.std(jaccard_scores)
    min_jaccard = np.min(jaccard_scores)
    max_jaccard = np.max(jaccard_scores)

    print("\n" + "-" * 70)
    print(f"TOP-{TOP_K} STABILITY SUMMARY")
    print("-" * 70)

    print(f"Number of runs:          {len(selected_feature_sets)}")
    print(f"Number of comparisons:   {len(jaccard_scores)}")
    print(f"Mean Jaccard Similarity: {mean_jaccard:.4f}")
    print(f"Standard Deviation:      {std_jaccard:.4f}")
    print(f"Minimum Jaccard:         {min_jaccard:.4f}")
    print(f"Maximum Jaccard:         {max_jaccard:.4f}")


    # ========================================================
    # FEATURE SELECTION FREQUENCY
    # ========================================================

    feature_counts = {}

    for feature_set in selected_feature_sets:

        for feature in feature_set:

            feature_counts[feature] = (
                feature_counts.get(feature, 0) + 1
            )

    for feature, count in feature_counts.items():

        all_frequency.append({
            "Top_K": TOP_K,
            "Feature": feature,
            "Selection_Count": count,
            "Selection_Frequency": count / len(selected_feature_sets)
        })

    frequency_df = pd.DataFrame(
        [
            {
                "Feature": feature,
                "Selection_Count": count,
                "Selection_Frequency": count / len(selected_feature_sets)
            }
            for feature, count in feature_counts.items()
        ]
    ).sort_values(
        "Selection_Frequency",
        ascending=False
    )

    print("\nFEATURE SELECTION FREQUENCY")

    print(frequency_df.to_string(index=False))


# ============================================================
# CREATE DATAFRAMES
# ============================================================

runs_df = pd.DataFrame(all_runs)

jaccard_df = pd.DataFrame(all_jaccard)

frequency_df = pd.DataFrame(all_frequency)


# ============================================================
# SUMMARY TABLE
# ============================================================

summary_rows = []

for TOP_K in TOP_K_VALUES:

    subset = jaccard_df[
        jaccard_df["Top_K"] == TOP_K
    ]["Jaccard_Similarity"]

    summary_rows.append({
        "Top_K": TOP_K,
        "Mean_Jaccard": subset.mean(),
        "Std_Jaccard": subset.std(),
        "Min_Jaccard": subset.min(),
        "Max_Jaccard": subset.max()
    })


summary_df = pd.DataFrame(summary_rows)


# ============================================================
# DISPLAY FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DODA STABILITY — ALL TOP-K VALUES")
print("=" * 70)

print(
    summary_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ============================================================
# SAVE RESULTS
# ============================================================

runs_df.to_csv(
    "../../../results/heart_disease/doda_stability_all_topk_runs.csv",
    index=False
)

jaccard_df.to_csv(
    "../../../results/heart_disease/doda_stability_all_topk_jaccard.csv",
    index=False
)

frequency_df.to_csv(
    "../../../results/heart_disease/doda_stability_all_topk_frequency.csv",
    index=False
)

summary_df.to_csv(
    "../../../results/heart_disease/doda_stability_all_topk_summary.csv",
    index=False
)


print("\nFiles saved:")
print("1. doda_stability_all_topk_runs.csv")
print("2. doda_stability_all_topk_jaccard.csv")
print("3. doda_stability_all_topk_frequency.csv")
print("4. doda_stability_all_topk_summary.csv")

======================================================================
DODA STABILITY ANALYSIS — TOP-5
======================================================================
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8090B9590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp']
Run 01: ['thal', 'exang', 'ca', 'oldpeak', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8090B91D0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}

Normalized Mathematical Scores
{'age': np.float64(0.12328618502430178), 'sex': np.float64(0.2707663454174306), 'cp': np.float64(0.47916514769330715), 'trestbps': np.float64(0.07913176287796957), 'chol': np.float64(0.016878694878010917), 'fbs': np.float64(0.008913816964758568), 'restecg': np.float64(0.08002249257543233), 'thalach': np.float64(0.6483605648721671), 'exang': np.float64(0.5670982596045171), 'oldpeak': np.float64(0.6095783748149011), 'slope': np.float64(0.31830069461656835), 'ca': np.float64(0.7754252510697944), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'thalach']
Run 02: ['thal', 'ca', 'oldpeak', 'exang', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D809094FC0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.200515006947251), 'sex': np.float64(12.485212224785743), 'cp': np.float64(63.21026634739328), 'trestbps': np.float64(4.9558099371161335), 'chol': np.float64(3.076917481889256), 'fbs': np.float64(0.01441419062358313), 'restecg': np.float64(7.598737742818419), 'thalach': np.float64(49.79167040571289), 'exang': np.float64(62.884021668320045), 'oldpeak': np.float64(50.371347753644606), 'slope': np.float64(35.28201631741495), 'ca': np.float64(64.2359301607097), 'thal': np.float64(82.71529043012269)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.200515006947251), 'sex': np.float64(12.485212224785743), 'cp': np.float64(63.21026634739328), 'trestbps': np.float64(4.9558099371161335), 'chol': np.float64(3.076917481889256), 'fbs': np.float64(0.01441419062358313), 'restecg': np.float64(7.598737742818419), 'thalach': np.float64(49.79167040571289), 'exang': np.float64(62.884021668320045), 'oldpeak': np.float64(50.371347753644606), 'slope': np.float64(35.28201631741495), 'ca': np.float64(64.2359301607097), 'thal': np.float64(82.71529043012269)}

Normalized Mathematical Scores
{'age': np.float64(0.13541045372269314), 'sex': np.float64(0.1509420103569988), 'cp': np.float64(0.7641908287899065), 'trestbps': np.float64(0.05991407285576501), 'chol': np.float64(0.03719889594643465), 'fbs': np.float64(0.00017426270945346118), 'restecg': np.float64(0.0918661797994626), 'thalach': np.float64(0.6019645236907746), 'exang': np.float64(0.7602466405101247), 'oldpeak': np.float64(0.608972627572383), 'slope': np.float64(0.42654769310422663), 'ca': np.float64(0.7765907588147293), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
Run 03: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D809094C30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.489019411708304), 'sex': np.float64(20.8315532721725), 'cp': np.float64(49.61539964594882), 'trestbps': np.float64(3.504310933272695), 'chol': np.float64(0.7089017091334149), 'fbs': np.float64(0.10049450470661826), 'restecg': np.float64(6.681596478699899), 'thalach': np.float64(51.41468262997414), 'exang': np.float64(50.78044450667848), 'oldpeak': np.float64(61.59908622627253), 'slope': np.float64(40.297459391421064), 'ca': np.float64(65.65842260993776), 'thal': np.float64(106.35859109340848)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.489019411708304), 'sex': np.float64(20.8315532721725), 'cp': np.float64(49.61539964594882), 'trestbps': np.float64(3.504310933272695), 'chol': np.float64(0.7089017091334149), 'fbs': np.float64(0.10049450470661826), 'restecg': np.float64(6.681596478699899), 'thalach': np.float64(51.41468262997414), 'exang': np.float64(50.78044450667848), 'oldpeak': np.float64(61.59908622627253), 'slope': np.float64(40.297459391421064), 'ca': np.float64(65.65842260993776), 'thal': np.float64(106.35859109340848)}

Normalized Mathematical Scores
{'age': np.float64(0.1362280118865382), 'sex': np.float64(0.19586150077784853), 'cp': np.float64(0.4664916969647947), 'trestbps': np.float64(0.0329480759123169), 'chol': np.float64(0.006665204022031735), 'fbs': np.float64(0.0009448649485997785), 'restecg': np.float64(0.06282140831323957), 'thalach': np.float64(0.483408835162358), 'exang': np.float64(0.4774456297759812), 'oldpeak': np.float64(0.5791641802792751), 'slope': np.float64(0.37888297482269373), 'ca': np.float64(0.6173306917188649), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.032266458495966696, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'cp']
Run 04: ['thal', 'ca', 'oldpeak', 'exang', 'cp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D809110EF0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.332269042690003), 'sex': np.float64(21.661351628628605), 'cp': np.float64(52.638194301306484), 'trestbps': np.float64(5.245715551758071), 'chol': np.float64(1.581079926160417), 'fbs': np.float64(0.2953679059427318), 'restecg': np.float64(7.039373981265975), 'thalach': np.float64(52.75764143109119), 'exang': np.float64(51.49722302358352), 'oldpeak': np.float64(44.88695499511203), 'slope': np.float64(25.931576767603055), 'ca': np.float64(65.5281769773227), 'thal': np.float64(89.60847810226801)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.332269042690003), 'sex': np.float64(21.661351628628605), 'cp': np.float64(52.638194301306484), 'trestbps': np.float64(5.245715551758071), 'chol': np.float64(1.581079926160417), 'fbs': np.float64(0.2953679059427318), 'restecg': np.float64(7.039373981265975), 'thalach': np.float64(52.75764143109119), 'exang': np.float64(51.49722302358352), 'oldpeak': np.float64(44.88695499511203), 'slope': np.float64(25.931576767603055), 'ca': np.float64(65.5281769773227), 'thal': np.float64(89.60847810226801)}

Normalized Mathematical Scores
{'age': np.float64(0.13762390907493685), 'sex': np.float64(0.2417332833608336), 'cp': np.float64(0.5874242640437635), 'trestbps': np.float64(0.05854039330710718), 'chol': np.float64(0.01764431178438237), 'fbs': np.float64(0.0032962049149594472), 'restecg': np.float64(0.07855700855930291), 'thalach': np.float64(0.5887572532018696), 'exang': np.float64(0.5746914144084779), 'oldpeak': np.float64(0.5009230816740757), 'slope': np.float64(0.2893875369472068), 'ca': np.float64(0.7312720667182514), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'thalach']
Run 05: ['thal', 'ca', 'cp', 'exang', 'thalach']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082A0E20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.708189055240988), 'sex': np.float64(13.77048848938552), 'cp': np.float64(47.70696615509223), 'trestbps': np.float64(3.2173040698818025), 'chol': np.float64(5.5151814195028415), 'fbs': np.float64(0.545612511707297), 'restecg': np.float64(9.13918702417913), 'thalach': np.float64(47.764732267537326), 'exang': np.float64(56.9612267380755), 'oldpeak': np.float64(41.69074384722524), 'slope': np.float64(29.27884476919867), 'ca': np.float64(59.886754993264134), 'thal': np.float64(87.73046518811289)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.708189055240988), 'sex': np.float64(13.77048848938552), 'cp': np.float64(47.70696615509223), 'trestbps': np.float64(3.2173040698818025), 'chol': np.float64(5.5151814195028415), 'fbs': np.float64(0.545612511707297), 'restecg': np.float64(9.13918702417913), 'thalach': np.float64(47.764732267537326), 'exang': np.float64(56.9612267380755), 'oldpeak': np.float64(41.69074384722524), 'slope': np.float64(29.27884476919867), 'ca': np.float64(59.886754993264134), 'thal': np.float64(87.73046518811289)}

Normalized Mathematical Scores
{'age': np.float64(0.13345636581472725), 'sex': np.float64(0.1569635868208227), 'cp': np.float64(0.543790187967182), 'trestbps': np.float64(0.036672597859628515), 'chol': np.float64(0.06286506526184618), 'fbs': np.float64(0.0062191909109040626), 'restecg': np.float64(0.10417347046527974), 'thalach': np.float64(0.5444486378263186), 'exang': np.float64(0.649275330022911), 'oldpeak': np.float64(0.4752139836239483), 'slope': np.float64(0.33373634468275715), 'ca': np.float64(0.6826221069824959), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.030017921146953404, 'chol': 0.029957522915269395, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.032266458495966696, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Run 06: ['thal', 'ca', 'exang', 'cp', 'oldpeak']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082A2AD0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.396129345871145), 'sex': np.float64(20.533858583223726), 'cp': np.float64(56.532878520300144), 'trestbps': np.float64(9.210934251258983), 'chol': np.float64(4.104204364898775), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(13.151118034504588), 'thalach': np.float64(47.58313557927372), 'exang': np.float64(49.48673034471284), 'oldpeak': np.float64(67.21492708185932), 'slope': np.float64(34.46730529122318), 'ca': np.float64(63.1956244683068), 'thal': np.float64(96.24825745821975)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.396129345871145), 'sex': np.float64(20.533858583223726), 'cp': np.float64(56.532878520300144), 'trestbps': np.float64(9.210934251258983), 'chol': np.float64(4.104204364898775), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(13.151118034504588), 'thalach': np.float64(47.58313557927372), 'exang': np.float64(49.48673034471284), 'oldpeak': np.float64(67.21492708185932), 'slope': np.float64(34.46730529122318), 'ca': np.float64(63.1956244683068), 'thal': np.float64(96.24825745821975)}

Normalized Mathematical Scores
{'age': np.float64(0.15996268142885003), 'sex': np.float64(0.21334265290088222), 'cp': np.float64(0.5873652158828996), 'trestbps': np.float64(0.09569975077478511), 'chol': np.float64(0.04264185631288299), 'fbs': np.float64(0.0012418607583622988), 'restecg': np.float64(0.1366374662960868), 'thalach': np.float64(0.49437919018875753), 'exang': np.float64(0.5141571562081989), 'oldpeak': np.float64(0.6983495478973896), 'slope': np.float64(0.35810835646749273), 'ca': np.float64(0.6565898036724382), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.03177805800756621, 'oldpeak': 0.03252247488101534, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'oldpeak', 'ca', 'cp', 'exang']
Run 07: ['thal', 'oldpeak', 'ca', 'cp', 'exang']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8082F6950>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:

In [32]:
# ============================================================
# CV PREDICTIVE PERFORMANCE
# Top-5, Top-8, Top-10, Top-13
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from xgboost import XGBClassifier

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
RANDOM_STATE = 42

WEIGHTS_FILE = "heartdisease_weights.json"


# ============================================================
# DATA
# ============================================================

# IMPORTANT:
# X and y should be the ORIGINAL dataset before:
# - imputation
# - scaling
# - feature selection
#
# Example:
#
# X = df.drop(columns=["target"])
# y = df["target"]


# ============================================================
# CROSS-VALIDATION
# ============================================================

cv = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

results = []


# ============================================================
# MODEL DEFINITIONS
# ============================================================

models = {

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# ============================================================
# MAIN EXPERIMENT
# ============================================================

for method in ["ANOVA", "DODA"]:

    print("\n")
    print("=" * 80)
    print(f"METHOD: {method}")
    print("=" * 80)

    for TOP_K in TOP_K_VALUES:

        print("\n" + "-" * 80)
        print(f"{method} | TOP-{TOP_K}")
        print("-" * 80)

        for model_name, base_model in models.items():

            print(f"\nModel: {model_name}")

            for fold, (train_idx, val_idx) in enumerate(
                cv.split(X, y),
                start=1
            ):

                # ====================================================
                # TRAIN / VALIDATION SPLIT
                # ====================================================

                X_train = X.iloc[train_idx].copy()
                X_val = X.iloc[val_idx].copy()

                y_train = y.iloc[train_idx].copy()
                y_val = y.iloc[val_idx].copy()


                # ====================================================
                # IMPUTATION
                # Fit ONLY on training data
                # ====================================================

                imputer = SimpleImputer(strategy="median")

                X_train_imp = pd.DataFrame(
                    imputer.fit_transform(X_train),
                    columns=X_train.columns,
                    index=X_train.index
                )

                X_val_imp = pd.DataFrame(
                    imputer.transform(X_val),
                    columns=X_val.columns,
                    index=X_val.index
                )


                # ====================================================
                # FEATURE SELECTION
                # ====================================================

                if method == "ANOVA":

                    selector = SelectKBest(
                        score_func=f_classif,
                        k=TOP_K
                    )

                    X_train_selected = selector.fit_transform(
                        X_train_imp,
                        y_train
                    )

                    X_val_selected = selector.transform(
                        X_val_imp
                    )

                    selected_features = (
                        X_train_imp.columns[
                            selector.get_support()
                        ].tolist()
                    )


                elif method == "DODA":

                    # ------------------------------------------------
                    # ANOVA provides mathematical feature scores
                    # DODA then incorporates clinical weights
                    # ------------------------------------------------

                    anova_operator = SklearnAdapter(
                        SelectKBest(
                            score_func=f_classif,
                            k="all"
                        )
                    )

                    provider = JSONProvider(
                        WEIGHTS_FILE
                    )

                    doda_selector = DODASelector(
                        operators=[anova_operator],
                        provider=provider,
                        fusion=RankFusion(),
                        top_k=TOP_K
                    )

                    doda_selector.fit(
                        X_train_imp,
                        y_train
                    )

                    selected_features = list(
                        doda_selector.get_selected_features()
                    )

                    X_train_selected = (
                        X_train_imp[selected_features]
                    )

                    X_val_selected = (
                        X_val_imp[selected_features]
                    )


                # ====================================================
                # MODEL
                # ====================================================

                # Create a fresh model for every fold
                model = type(base_model)(
                    **base_model.get_params()
                )


                # ====================================================
                # SCALING
                # Only Logistic Regression needs scaling
                # ====================================================

                if model_name == "Logistic Regression":

                    scaler = StandardScaler()

                    X_train_final = scaler.fit_transform(
                        X_train_selected
                    )

                    X_val_final = scaler.transform(
                        X_val_selected
                    )

                else:

                    X_train_final = X_train_selected
                    X_val_final = X_val_selected


                # ====================================================
                # TRAIN
                # ====================================================

                model.fit(
                    X_train_final,
                    y_train
                )


                # ====================================================
                # PREDICTION
                # ====================================================

                y_pred = model.predict(
                    X_val_final
                )

                y_prob = model.predict_proba(
                    X_val_final
                )[:, 1]


                # ====================================================
                # METRICS
                # ====================================================

                accuracy = accuracy_score(
                    y_val,
                    y_pred
                )

                precision = precision_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                recall = recall_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                f1 = f1_score(
                    y_val,
                    y_pred,
                    zero_division=0
                )

                auc = roc_auc_score(
                    y_val,
                    y_prob
                )


                # ====================================================
                # STORE RESULTS
                # ====================================================

                results.append({

                    "Method": method,

                    "Top_K": TOP_K,

                    "Model": model_name,

                    "Fold": fold,

                    "Accuracy": accuracy,

                    "Precision": precision,

                    "Recall": recall,

                    "F1": f1,

                    "ROC_AUC": auc,

                    "Selected_Features":
                        ", ".join(selected_features)
                })


                print(
                    f"  Fold {fold}: "
                    f"Acc={accuracy:.4f}, "
                    f"Prec={precision:.4f}, "
                    f"Recall={recall:.4f}, "
                    f"F1={f1:.4f}, "
                    f"AUC={auc:.4f}"
                )


# ============================================================
# RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)


# ============================================================
# SAVE FOLD-LEVEL RESULTS
# ============================================================

results_df.to_csv(
    "../../../results/heart_disease_cv_results.csv",
    index=False
)


# ============================================================
# SUMMARY — MEAN ± STD
# ============================================================

summary_df = (
    results_df
    .groupby(
        ["Method", "Top_K", "Model"]
    )
    .agg({

        "Accuracy": ["mean", "std"],

        "Precision": ["mean", "std"],

        "Recall": ["mean", "std"],

        "F1": ["mean", "std"],

        "ROC_AUC": ["mean", "std"]

    })
    .reset_index()
)


# ============================================================
# FLATTEN COLUMN NAMES
# ============================================================

summary_df.columns = [

    "Method",
    "Top_K",
    "Model",

    "Accuracy_Mean",
    "Accuracy_STD",

    "Precision_Mean",
    "Precision_STD",

    "Recall_Mean",
    "Recall_STD",

    "F1_Mean",
    "F1_STD",

    "ROC_AUC_Mean",
    "ROC_AUC_STD"
]


# ============================================================
# SAVE SUMMARY
# ============================================================

summary_df.to_csv(
    "../../../results/heart_disease_cv_summary.csv",
    index=False
)


# ============================================================
# DISPLAY SUMMARY
# ============================================================

print("\n")
print("=" * 100)
print("FINAL CV PERFORMANCE SUMMARY")
print("=" * 100)

display(
    summary_df.round(4)
)


# ============================================================
# BEST CONFIGURATION BY ROC-AUC
# ============================================================

best_auc = summary_df.loc[
    summary_df["ROC_AUC_Mean"].idxmax()
]

print("\n")
print("=" * 80)
print("BEST CONFIGURATION — ROC-AUC")
print("=" * 80)

print(
    f"Method:     {best_auc['Method']}"
)

print(
    f"Top-K:      {int(best_auc['Top_K'])}"
)

print(
    f"Model:      {best_auc['Model']}"
)

print(
    f"ROC-AUC:    "
    f"{best_auc['ROC_AUC_Mean']:.4f} "
    f"± {best_auc['ROC_AUC_STD']:.4f}"
)


# ============================================================
# BEST CONFIGURATION BY F1
# ============================================================

best_f1 = summary_df.loc[
    summary_df["F1_Mean"].idxmax()
]

print("\n")
print("=" * 80)
print("BEST CONFIGURATION — F1")
print("=" * 80)

print(
    f"Method:     {best_f1['Method']}"
)

print(
    f"Top-K:      {int(best_f1['Top_K'])}"
)

print(
    f"Model:      {best_f1['Model']}"
)

print(
    f"F1:         "
    f"{best_f1['F1_Mean']:.4f} "
    f"± {best_f1['F1_STD']:.4f}"
)

================================================================================
METHOD: ANOVA
================================================================================

--------------------------------------------------------------------------------
ANOVA | TOP-5
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8852, Prec=0.8621, Recall=0.8929, F1=0.8772, AUC=0.9313
  Fold 2: Acc=0.8197, Prec=0.8696, Recall=0.7143, F1=0.7843, AUC=0.8820

  Fold 3: Acc=0.8361, Prec=0.8462, Recall=0.7857, F1=0.8148, AUC=0.9156
  Fold 4: Acc=0.8167, Prec=0.8077, Recall=0.7778, F1=0.7925, AUC=0.8844
  Fold 5: Acc=0.8333, Prec=0.8750, Recall=0.7500, F1=0.8077, AUC=0.8571

Model: Random Forest
  Fold 1: Acc=0.7869, Prec=0.8000, Recall=0.7143, F1=0.7547, AUC=0.9129
  Fold 2: Acc=0.7705, Prec=0.7692, Recall=0.7143, F1=0.7407, AUC=0.8328
  Fold 3: Acc=0.8361, Prec=0.8000, Recall=0.8571, F1=0.8276, AUC=0.9080
  Fold 4: Acc=0.7333, Prec=0.6897, Recall=0.7407, F1=0.7143, AUC=0.8384
  Fold 5: Acc=0.7333, Prec=0.7500, Recall=0.6429, F1=0.6923, AUC=0.8432

Model: XGBoost
  Fold 1: Acc=0.8033, Prec=0.8077, Recall=0.7500, F1=0.7778, AUC=0.8999
  Fold 2: Acc=0.8197, Prec=0.8400, Recall=0.7500, F1=0.7925, AUC=0.8550
  Fold 3: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.9080
  Fold 4: Acc=0.7167, Prec=0.6923, Recall=0.6667, F1=0.6792, AUC=0.8058
  Fold 5: Acc=0.7667, Prec=0.7692, Recall=0.7143, F1=0.7407, AUC=0.8482

--------------------------------------------------------------------------------
ANOVA | TOP-8
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8852, Prec=0.8387, Recall=0.9286, F1=0.8814, AUC=0.9426
  Fold 2: Acc=0.8197, Prec=0.8696, Recall=0.7143, F1=0.7843, AUC=0.9080
  Fold 3: Acc=0.8361, Prec=0.8462, Recall=0.7857, F1=0.8148, AUC=0.9232
  Fold 4: Acc=0.8000, Prec=0.8000, Recall=0.7407, F1=0.7692, AUC=0.9035
  Fold 5: Acc=0.8500, Prec=0.9130, Recall=0.7500, F1=0.8235, AUC=0.8761

Model: Random Forest
  Fold 1: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.9253
  Fold 2: Acc=0.8197, Prec=0.8148, Recall=0.7857, F1=0.8000, AUC=0.8723
  Fold 3: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.9167
  Fold 4: Acc=0.7833, Prec=0.7692, Recall=0.7407, F1=0.7547, AUC=0.8850
  Fold 5: Acc=0.8333, Prec=0.8750, Recall=0.7500, F1=0.8077, AUC=0.9012

Model: XGBoost
  Fold 1: Acc=0.8525, Prec=0.8519, Recall=0.8214, F1=0.8364, AUC=0.9275
  Fold 2: Acc=0.7869, Prec=0.7586, Recall=0.7857, F1=0.7719, AUC=0.8571
  Fold 3: Acc=0.8197, Prec=0.7931, Recall=0.8214, F1=0.8070, AUC=0.9080
  Fold 4: Acc=0.8000, Prec=0.7778, Recall=0.7778, F1=0.7778, AUC=0.8586
  Fold 5: Acc=0.8000, Prec=0.8636, Recall=0.6786, F1=0.7600, AUC=0.8895

--------------------------------------------------------------------------------
ANOVA | TOP-10
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.8689, Prec=0.8125, Recall=0.9286, F1=0.8667, AUC=0.9416
  Fold 2: Acc=0.8197, Prec=0.8696, Recall=0.7143, F1=0.7843, AUC=0.8994
  Fold 3: Acc=0.8525, Prec=0.8519, Recall=0.8214, F1=0.8364, AUC=0.9221
  Fold 4: Acc=0.8000, Prec=0.7778, Recall=0.7778, F1=0.7778, AUC=0.9012
  Fold 5: Acc=0.8500, Prec=0.9130, Recall=0.7500, F1=0.8235, AUC=0.8850

Model: Random Forest
  Fold 1: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.9410
  Fold 2: Acc=0.8197, Prec=0.8148, Recall=0.7857, F1=0.8000, AUC=0.8923
  Fold 3: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.9177
  Fold 4: Acc=0.8000, Prec=0.7778, Recall=0.7778, F1=0.7778, AUC=0.8878
  Fold 5: Acc=0.8500, Prec=0.9130, Recall=0.7500, F1=0.8235, AUC=0.9113

Model: XGBoost
  Fold 1: Acc=0.7869, Prec=0.8000, Recall=0.7143, F1=0.7547, AUC=0.9080
  Fold 2: Acc=0.8033, Prec=0.8077, Recall=0.7500, F1=0.7778, AUC=0.8755
  Fold 3: Acc=0.8197, Prec=0.8148, Recall=0.7857, F1=0.8000, AUC=0.9058
  Fold 4: Acc=0.8000, Prec=0.8261, Recall=0.7037, F1=0.7600, AUC=0.8676
  Fold 5: Acc=0.8167, Prec=0.8400, Recall=0.7500, F1=0.7925, AUC=0.9085

--------------------------------------------------------------------------------
ANOVA | TOP-13
--------------------------------------------------------------------------------

Model: Logistic Regression
  Fold 1: Acc=0.9180, Prec=0.8966, Recall=0.9286, F1=0.9123, AUC=0.9372
  Fold 2: Acc=0.8197, Prec=0.8148, Recall=0.7857, F1=0.8000, AUC=0.8820
  Fold 3: Acc=0.7869, Prec=0.7778, Recall=0.7500, F1=0.7636, AUC=0.9123
  Fold 4: Acc=0.7833, Prec=0.7500, Recall=0.7778, F1=0.7636, AUC=0.9181
  Fold 5: Acc=0.8500, Prec=0.9130, Recall=0.7500, F1=0.8235, AUC=0.9085

Model: Random Forest
  Fold 1: Acc=0.8689, Prec=0.8846, Recall=0.8214, F1=0.8519, AUC=0.9481
  Fold 2: Acc=0.7869, Prec=0.7778, Recall=0.7500, F1=0.7636, AUC=0.8788
  Fold 3: Acc=0.8197, Prec=0.8148, Recall=0.7857, F1=0.8000, AUC=0.9075
  Fold 4: Acc=0.7833, Prec=0.7692, Recall=0.7407, F1=0.7547, AUC=0.8973
  Fold 5: Acc=0.8500, Prec=0.9130, Recall=0.7500, F1=0.8235, AUC=0.9202

Model: XGBoost
  Fold 1: Acc=0.8361, Prec=0.8462, Recall=0.7857, F1=0.8148, AUC=0.9199
  Fold 2: Acc=0.8033, Prec=0.7667, Recall=0.8214, F1=0.7931, AUC=0.8669
  Fold 3: Acc=0.8361, Prec=0.8214, Recall=0.8214, F1=0.8214, AUC=0.8972
  Fold 4: Acc=0.8333, Prec=0.8400, Recall=0.7778, F1=0.8077, AUC=0.8878
  Fold 5: Acc=0.8333, Prec=0.9091, Recall=0.7143, F1=0.8000, AUC=0.8873


================================================================================
METHOD: DODA
================================================================================

--------------------------------------------------------------------------------
DODA | TOP-5
--------------------------------------------------------------------------------

Model: Logistic Regression
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80910F650>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp']
  Fold 1: Acc=0.8852, Prec=0.8621, Recall=0.8929, F1=0.8772, AUC=0.9313
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8090CAFF0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}

Normalized Mathematical Scores
{'age': np.float64(0.12328618502430178), 'sex': np.float64(0.2707663454174306), 'cp': np.float64(0.47916514769330715), 'trestbps': np.float64(0.07913176287796957), 'chol': np.float64(0.016878694878010917), 'fbs': np.float64(0.008913816964758568), 'restecg': np.float64(0.08002249257543233), 'thalach': np.float64(0.6483605648721671), 'exang': np.float64(0.5670982596045171), 'oldpeak': np.float64(0.6095783748149011), 'slope': np.float64(0.31830069461656835), 'ca': np.float64(0.7754252510697944), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'thalach']
  Fold 2: Acc=0.8197, Prec=0.8696, Recall=0.7143, F1=0.7843, AUC=0.8820
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80910F590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.200515006947251), 'sex': np.float64(12.485212224785743), 'cp': np.float64(63.21026634739328), 'trestbps': np.float64(4.9558099371161335), 'chol': np.float64(3.076917481889256), 'fbs': np.float64(0.01441419062358313), 'restecg': np.float64(7.598737742818419), 'thalach': np.float64(49.79167040571289), 'exang': np.float64(62.884021668320045), 'oldpeak': np.float64(50.371347753644606), 'slope': np.float64(35.28201631741495), 'ca': np.float64(64.2359301607097), 'thal': np.float64(82.71529043012269)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.200515006947251), 'sex': np.float64(12.485212224785743), 'cp': np.float64(63.21026634739328), 'trestbps': np.float64(4.9558099371161335), 'chol': np.float64(3.076917481889256), 'fbs': np.float64(0.01441419062358313), 'restecg': np.float64(7.598737742818419), 'thalach': np.float64(49.79167040571289), 'exang': np.float64(62.884021668320045), 'oldpeak': np.float64(50.371347753644606), 'slope': np.float64(35.28201631741495), 'ca': np.float64(64.2359301607097), 'thal': np.float64(82.71529043012269)}

Normalized Mathematical Scores
{'age': np.float64(0.13541045372269314), 'sex': np.float64(0.1509420103569988), 'cp': np.float64(0.7641908287899065), 'trestbps': np.float64(0.05991407285576501), 'chol': np.float64(0.03719889594643465), 'fbs': np.float64(0.00017426270945346118), 'restecg': np.float64(0.0918661797994626), 'thalach': np.float64(0.6019645236907746), 'exang': np.float64(0.7602466405101247), 'oldpeak': np.float64(0.608972627572383), 'slope': np.float64(0.42654769310422663), 'ca': np.float64(0.7765907588147293), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.032266458495966696, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031024531024531024, 'exang': 0.032018442622950824, 'oldpeak': 0.03177805800756621, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'oldpeak']
  Fold 3: Acc=0.8361, Prec=0.8462, Recall=0.7857, F1=0.8148, AUC=0.9156
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80836F410>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.489019411708304), 'sex': np.float64(20.8315532721725), 'cp': np.float64(49.61539964594882), 'trestbps': np.float64(3.504310933272695), 'chol': np.float64(0.7089017091334149), 'fbs': np.float64(0.10049450470661826), 'restecg': np.float64(6.681596478699899), 'thalach': np.float64(51.41468262997414), 'exang': np.float64(50.78044450667848), 'oldpeak': np.float64(61.59908622627253), 'slope': np.float64(40.297459391421064), 'ca': np.float64(65.65842260993776), 'thal': np.float64(106.35859109340848)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.489019411708304), 'sex': np.float64(20.8315532721725), 'cp': np.float64(49.61539964594882), 'trestbps': np.float64(3.504310933272695), 'chol': np.float64(0.7089017091334149), 'fbs': np.float64(0.10049450470661826), 'restecg': np.float64(6.681596478699899), 'thalach': np.float64(51.41468262997414), 'exang': np.float64(50.78044450667848), 'oldpeak': np.float64(61.59908622627253), 'slope': np.float64(40.297459391421064), 'ca': np.float64(65.65842260993776), 'thal': np.float64(106.35859109340848)}

Normalized Mathematical Scores
{'age': np.float64(0.1362280118865382), 'sex': np.float64(0.19586150077784853), 'cp': np.float64(0.4664916969647947), 'trestbps': np.float64(0.0329480759123169), 'chol': np.float64(0.006665204022031735), 'fbs': np.float64(0.0009448649485997785), 'restecg': np.float64(0.06282140831323957), 'thalach': np.float64(0.483408835162358), 'exang': np.float64(0.4774456297759812), 'oldpeak': np.float64(0.5791641802792751), 'slope': np.float64(0.37888297482269373), 'ca': np.float64(0.6173306917188649), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.03149801587301587, 'exang': 0.03177805800756621, 'oldpeak': 0.032266458495966696, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'cp']
  Fold 4: Acc=0.7833, Prec=0.7692, Recall=0.7407, F1=0.7547, AUC=0.8911
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D8090C9730>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.332269042690003), 'sex': np.float64(21.661351628628605), 'cp': np.float64(52.638194301306484), 'trestbps': np.float64(5.245715551758071), 'chol': np.float64(1.581079926160417), 'fbs': np.float64(0.2953679059427318), 'restecg': np.float64(7.039373981265975), 'thalach': np.float64(52.75764143109119), 'exang': np.float64(51.49722302358352), 'oldpeak': np.float64(44.88695499511203), 'slope': np.float64(25.931576767603055), 'ca': np.float64(65.5281769773227), 'thal': np.float64(89.60847810226801)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.332269042690003), 'sex': np.float64(21.661351628628605), 'cp': np.float64(52.638194301306484), 'trestbps': np.float64(5.245715551758071), 'chol': np.float64(1.581079926160417), 'fbs': np.float64(0.2953679059427318), 'restecg': np.float64(7.039373981265975), 'thalach': np.float64(52.75764143109119), 'exang': np.float64(51.49722302358352), 'oldpeak': np.float64(44.88695499511203), 'slope': np.float64(25.931576767603055), 'ca': np.float64(65.5281769773227), 'thal': np.float64(89.60847810226801)}

Normalized Mathematical Scores
{'age': np.float64(0.13762390907493685), 'sex': np.float64(0.2417332833608336), 'cp': np.float64(0.5874242640437635), 'trestbps': np.float64(0.05854039330710718), 'chol': np.float64(0.01764431178438237), 'fbs': np.float64(0.0032962049149594472), 'restecg': np.float64(0.07855700855930291), 'thalach': np.float64(0.5887572532018696), 'exang': np.float64(0.5746914144084779), 'oldpeak': np.float64(0.5009230816740757), 'slope': np.float64(0.2893875369472068), 'ca': np.float64(0.7312720667182514), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.032018442622950824, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.031544957774465976, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'cp', 'exang', 'thalach']
  Fold 5: Acc=0.8333, Prec=0.8750, Recall=0.7500, F1=0.8077, AUC=0.8571

Model: Random Forest
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80836DBB0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}

,Method,Top_K,Model,Accuracy_Mean,Accuracy_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,F1_Mean,F1_STD,ROC_AUC_Mean,ROC_AUC_STD
0,ANOVA,5,Logistic Regression,0.8382,0.0276,0.8521,0.0271,0.7841,0.0669,0.8153,0.0366,0.8941,0.0294
1,ANOVA,5,Random Forest,0.7720,0.0428,0.7618,0.0456,0.7339,0.0779,0.7459,0.0516,0.8671,0.0398
2,ANOVA,5,XGBoost,0.7885,0.0477,0.7861,0.0585,0.7405,0.0567,0.7623,0.0548,0.8634,0.0416
3,ANOVA,8,Logistic Regression,0.8382,0.0322,0.8535,0.0416,0.7839,0.0848,0.8146,0.0433,0.9107,0.0247
4,ANOVA,8,Random Forest,0.8217,0.0225,0.8204,0.0375,0.7839,0.0382,0.8011,0.0275,0.9001,0.0219
5,ANOVA,8,XGBoost,0.8118,0.0256,0.8090,0.0463,0.7770,0.0586,0.7906,0.0309,0.8881,0.0307
6,ANOVA,10,Logistic Regression,0.8382,0.0278,0.8449,0.0521,0.7984,0.0826,0.8177,0.0370,0.9099,0.0221
7,ANOVA,10,Random Forest,0.8284,0.0191,0.8297,0.0500,0.7913,0.0306,0.8088,0.0198,0.9100,0.0214
8,ANOVA,10,XGBoost,0.8053,0.0133,0.8177,0.0157,0.7407,0.0327,0.7770,0.0197,0.8931,0.0199
9,ANOVA,13,Logistic Regression,0.8316,0.0554,0.8304,0.0719,0.7984,0.0745,0.8126,0.0613,0.9116,0.0199
10,ANOVA,13,Random Forest,0.8217,0.0378,0.8319,0.0642,0.7696,0.0337,0.7987,0.0406,0.9104,0.0259
11,ANOVA,13,XGBoost,0.8284,0.0141,0.8367,0.0512,0.7841,0.0439,0.8074,0.0113,0.8918,0.0192
12,DODA,5,Logistic Regression,0.8315,0.0366,0.8444,0.0434,0.7767,0.0698,0.8077,0.0454,0.8954,0.0290
13,DODA,5,Random Forest,0.7886,0.0312,0.7890,0.0480,0.7410,0.0773,0.7616,0.0411,0.8707,0.0367
14,DODA,5,XGBoost,0.7919,0.0358,0.7949,0.0580,0.7410,0.0464,0.7657,0.0377,0.8723,0.0289
15,DODA,8,Logistic Regression,0.8349,0.0376,0.8512,0.0463,0.7767,0.0698,0.8108,0.0465,0.9004,0.0259
16,DODA,8,Random Forest,0.8316,0.0303,0.8499,0.0395,0.7690,0.0644,0.8062,0.0426,0.9040,0.0204
17,DODA,8,XGBoost,0.7852,0.0439,0.7754,0.0329,0.7476,0.1032,0.7588,0.0612,0.8809,0.0200
18,DODA,10,Logistic Regression,0.8415,0.0193,0.8509,0.0442,0.7984,0.0745,0.8210,0.0279,0.9099,0.0232
19,DODA,10,Random Forest,0.8317,0.0213,0.8362,0.0468,0.7910,0.0488,0.8114,0.0254,0.9085,0.0271
20,DODA,10,XGBoost,0.8184,0.0353,0.8186,0.0358,0.7765,0.0797,0.7953,0.0472,0.8902,0.0211
21,DODA,13,Logistic Regression,0.8316,0.0554,0.8304,0.0719,0.7984,0.0745,0.8126,0.0613,0.9116,0.0199
22,DODA,13,Random Forest,0.8416,0.0298,0.8498,0.0513,0.7984,0.0416,0.8222,0.0320,0.9064,0.0275
23,DODA,13,XGBoost,0.8251,0.0214,0.8426,0.0619,0.7696,0.0421,0.8019,0.0145,0.8964,0.0198

================================================================================
BEST CONFIGURATION — ROC-AUC
================================================================================
Method:     ANOVA
Top-K:      13
Model:      Logistic Regression
ROC-AUC:    0.9116 ± 0.0199


================================================================================
BEST CONFIGURATION — F1
================================================================================
Method:     DODA
Top-K:      13
Model:      Random Forest
F1:         0.8222 ± 0.0320

In [33]:
# ============================================================
# 5×5 REPEATED STRATIFIED CV
# ANOVA vs DODA PREDICTIVE PERFORMANCE
# ============================================================

import numpy as np
import pandas as pd

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion


# ============================================================
# CONFIGURATION
# ============================================================

TOP_K_VALUES = [5, 8, 10, 13]

N_SPLITS = 5
N_REPEATS = 5
RANDOM_STATE = 42


# ============================================================
# MODELS
# ============================================================

models = {
    "LR": LogisticRegression(
        max_iter=2000,
        random_state=RANDOM_STATE
    ),

    "RF": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),

    "XGB": XGBClassifier(
        n_estimators=300,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}


# ============================================================
# DODA PROVIDER
# ============================================================

provider = JSONProvider("heartdisease_weights.json")


# ============================================================
# REPEATED STRATIFIED CV
# ============================================================

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=RANDOM_STATE
)


# ============================================================
# STORAGE
# ============================================================

results = []


# ============================================================
# MAIN LOOP
# ============================================================

for run_id, (train_idx, test_idx) in enumerate(
    cv.split(X, y), start=1
):

    print("=" * 70)
    print(f"RUN {run_id}/25")
    print("=" * 70)

    # --------------------------------------------------------
    # Split data
    # --------------------------------------------------------

    X_train = X.iloc[train_idx].copy()
    X_test = X.iloc[test_idx].copy()

    y_train = y.iloc[train_idx].copy()
    y_test = y.iloc[test_idx].copy()


    # --------------------------------------------------------
    # Imputation
    # Fit ONLY on training data
    # --------------------------------------------------------

    imputer = SimpleImputer(strategy="median")

    X_train_imp = pd.DataFrame(
        imputer.fit_transform(X_train),
        columns=X_train.columns,
        index=X_train.index
    )

    X_test_imp = pd.DataFrame(
        imputer.transform(X_test),
        columns=X_test.columns,
        index=X_test.index
    )


    # ========================================================
    # LOOP THROUGH TOP-K
    # ========================================================

    for top_k in TOP_K_VALUES:

        print(f"\nTop-{top_k}")


        # ====================================================
        # ANOVA FEATURE SELECTION
        # ====================================================

        anova_selector = SelectKBest(
            score_func=f_classif,
            k=top_k
        )

        X_train_anova = anova_selector.fit_transform(
            X_train_imp,
            y_train
        )

        X_test_anova = anova_selector.transform(
            X_test_imp
        )

        anova_features = X_train_imp.columns[
            anova_selector.get_support()
        ].tolist()


        # ====================================================
        # DODA FEATURE SELECTION
        # ====================================================

        # k="all" is important:
        # ANOVA scores ALL features first.
        # DODA performs the final Top-K ranking.

        anova_operator = SklearnAdapter(
            SelectKBest(
                score_func=f_classif,
                k="all"
            )
        )

        doda_selector = DODASelector(
            operators=[anova_operator],
            provider=provider,
            fusion=RankFusion(),
            top_k=top_k
        )

        doda_selector.fit(
            X_train_imp,
            y_train
        )

        doda_features = doda_selector.get_selected_features()


        # ----------------------------------------------------
        # Transform test/train data
        # ----------------------------------------------------

        X_train_doda = X_train_imp[doda_features]
        X_test_doda = X_test_imp[doda_features]


        # ====================================================
        # MODEL LOOP
        # ====================================================

        for model_name, model_template in models.items():

            # =================================================
            # ANOVA
            # =================================================

            model = model_template.__class__(
                **model_template.get_params()
            )

            Xtr = X_train_anova
            Xte = X_test_anova

            # -------------------------------------------------
            # Scale only for Logistic Regression
            # -------------------------------------------------

            if model_name == "LR":

                scaler = StandardScaler()

                Xtr = scaler.fit_transform(Xtr)
                Xte = scaler.transform(Xte)

            model.fit(Xtr, y_train)

            y_pred = model.predict(Xte)
            y_prob = model.predict_proba(Xte)[:, 1]


            anova_metrics = {
                "Accuracy": accuracy_score(
                    y_test, y_pred
                ),

                "Precision": precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "Recall": recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "F1": f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "ROC_AUC": roc_auc_score(
                    y_test,
                    y_prob
                )
            }


            results.append({
                "Run": run_id,
                "Method": "ANOVA",
                "Top_K": top_k,
                "Model": model_name,
                "Accuracy": anova_metrics["Accuracy"],
                "Precision": anova_metrics["Precision"],
                "Recall": anova_metrics["Recall"],
                "F1": anova_metrics["F1"],
                "ROC_AUC": anova_metrics["ROC_AUC"],
                "Selected_Features": ", ".join(anova_features)
            })


            # =================================================
            # DODA
            # =================================================

            model = model_template.__class__(
                **model_template.get_params()
            )

            Xtr = X_train_doda
            Xte = X_test_doda

            # -------------------------------------------------
            # Scale only for Logistic Regression
            # -------------------------------------------------

            if model_name == "LR":

                scaler = StandardScaler()

                Xtr = scaler.fit_transform(Xtr)
                Xte = scaler.transform(Xte)

            model.fit(Xtr, y_train)

            y_pred = model.predict(Xte)
            y_prob = model.predict_proba(Xte)[:, 1]


            doda_metrics = {
                "Accuracy": accuracy_score(
                    y_test, y_pred
                ),

                "Precision": precision_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "Recall": recall_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "F1": f1_score(
                    y_test,
                    y_pred,
                    zero_division=0
                ),

                "ROC_AUC": roc_auc_score(
                    y_test,
                    y_prob
                )
            }


            results.append({
                "Run": run_id,
                "Method": "DODA",
                "Top_K": top_k,
                "Model": model_name,
                "Accuracy": doda_metrics["Accuracy"],
                "Precision": doda_metrics["Precision"],
                "Recall": doda_metrics["Recall"],
                "F1": doda_metrics["F1"],
                "ROC_AUC": doda_metrics["ROC_AUC"],
                "Selected_Features": ", ".join(doda_features)
            })


# ============================================================
# CREATE RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)

print("\nCompleted!")
print("Total runs:", len(results_df))

results_df.head()

======================================================================
RUN 1/25
======================================================================

Top-5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp']

Top-8
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp', 'slope', 'thalach', 'age']

Top-10
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp', 'slope', 'thalach', 'age', 'trestbps', 'sex']

Top-13
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.092089497961574), 'sex': np.float64(21.564202094745454), 'cp': np.float64(42.239456661366745), 'trestbps': np.float64(7.608511654167631), 'chol': np.float64(2.288972965863027), 'fbs': np.float64(0.11952693399811455), 'restecg': np.float64(6.906150433507175), 'thalach': np.float64(42.05786643867364), 'exang': np.float64(60.11520349331092), 'oldpeak': np.float64(53.44021864765956), 'slope': np.float64(27.81521670536931), 'ca': np.float64(57.94607446107259), 'thal': np.float64(82.69642608429048)}

Normalized Mathematical Scores
{'age': np.float64(0.17040747908014606), 'sex': np.float64(0.26076341041347517), 'cp': np.float64(0.5107772930635851), 'trestbps': np.float64(0.09200532616019534), 'chol': np.float64(0.027679224777258597), 'fbs': np.float64(0.001445370007602065), 'restecg': np.float64(0.0835120785808555), 'thalach': np.float64(0.5085814276399934), 'exang': np.float64(0.7269383495731356), 'oldpeak': np.float64(0.6462216226030039), 'slope': np.float64(0.3363533108071433), 'ca': np.float64(0.7007083280964228), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.03177805800756621, 'trestbps': 0.0304147465437788, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.029957522915269395, 'thalach': 0.031024531024531024, 'exang': 0.03252247488101534, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.032266458495966696, 'thal': 0.03278688524590164}
Top 13 Features Selected: ['thal', 'exang', 'ca', 'oldpeak', 'cp', 'slope', 'thalach', 'age', 'trestbps', 'sex', 'restecg', 'chol', 'fbs']
======================================================================
RUN 2/25
======================================================================

Top-5
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}

Normalized Mathematical Scores
{'age': np.float64(0.12328618502430178), 'sex': np.float64(0.2707663454174306), 'cp': np.float64(0.47916514769330715), 'trestbps': np.float64(0.07913176287796957), 'chol': np.float64(0.016878694878010917), 'fbs': np.float64(0.008913816964758568), 'restecg': np.float64(0.08002249257543233), 'thalach': np.float64(0.6483605648721671), 'exang': np.float64(0.5670982596045171), 'oldpeak': np.float64(0.6095783748149011), 'slope': np.float64(0.31830069461656835), 'ca': np.float64(0.7754252510697944), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 5 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'thalach']

Top-8
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}

Normalized Mathematical Scores
{'age': np.float64(0.12328618502430178), 'sex': np.float64(0.2707663454174306), 'cp': np.float64(0.47916514769330715), 'trestbps': np.float64(0.07913176287796957), 'chol': np.float64(0.016878694878010917), 'fbs': np.float64(0.008913816964758568), 'restecg': np.float64(0.08002249257543233), 'thalach': np.float64(0.6483605648721671), 'exang': np.float64(0.5670982596045171), 'oldpeak': np.float64(0.6095783748149011), 'slope': np.float64(0.31830069461656835), 'ca': np.float64(0.7754252510697944), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 8 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'thalach', 'cp', 'slope', 'age']

Top-10
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.1931653517703), 'sex': np.float64(24.582904202562887), 'cp': np.float64(43.50345278247853), 'trestbps': np.float64(7.184380847664311), 'chol': np.float64(1.53241843483448), 'fbs': np.float64(0.8092863542033588), 'restecg': np.float64(7.265250288027541), 'thalach': np.float64(58.864722018536334), 'exang': np.float64(51.486909009337076), 'oldpeak': np.float64(55.34368301542992), 'slope': np.float64(28.898552629593546), 'ca': np.float64(70.40093787841145), 'thal': np.float64(90.79010231003531)}

Normalized Mathematical Scores
{'age': np.float64(0.12328618502430178), 'sex': np.float64(0.2707663454174306), 'cp': np.float64(0.47916514769330715), 'trestbps': np.float64(0.07913176287796957), 'chol': np.float64(0.016878694878010917), 'fbs': np.float64(0.008913816964758568), 'restecg': np.float64(0.08002249257543233), 'thalach': np.float64(0.6483605648721671), 'exang': np.float64(0.5670982596045171), 'oldpeak': np.float64(0.6095783748149011), 'slope': np.float64(0.31830069461656835), 'ca': np.float64(0.7754252510697944), 'thal': np.float64(1.0)}

Clinical Weights
{'age': 0.9, 'sex': 0.6, 'cp': 1.0, 'trestbps': 0.9, 'chol': 0.8, 'fbs': 0.6, 'restecg': 0.8, 'thalach': 0.8, 'exang': 1.0, 'oldpeak': 1.0, 'slope': 0.9, 'ca': 1.0, 'thal': 1.0}

Final DODA Scores
{'age': 0.030621785881252923, 'sex': 0.030330882352941176, 'cp': 0.031544957774465976, 'trestbps': 0.03021353930031804, 'chol': 0.02976190476190476, 'fbs': 0.0293236301369863, 'restecg': 0.030158730158730156, 'thalach': 0.031746031746031744, 'exang': 0.03177805800756621, 'oldpeak': 0.032018442622950824, 'slope': 0.031054405392392875, 'ca': 0.03252247488101534, 'thal': 0.03278688524590164}
Top 10 Features Selected: ['thal', 'ca', 'oldpeak', 'exang', 'thalach', 'cp', 'slope', 'age', 'sex', 'trestbps']

Top-13
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x000001D80912EA50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak']
Number of features: 13
Number of scores: 13
Operator Scores:

,Run,Method,Top_K,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Selected_Features
0,1,ANOVA,5,LR,0.885246,0.862069,0.892857,0.877193,0.931277,"cp, exang, oldpeak, ca, thal"
1,1,DODA,5,LR,0.885246,0.862069,0.892857,0.877193,0.931277,"thal, exang, ca, oldpeak, cp"
2,1,ANOVA,5,RF,0.786885,0.800000,0.714286,0.754717,0.912879,"cp, exang, oldpeak, ca, thal"
3,1,DODA,5,RF,0.819672,0.869565,0.714286,0.784314,0.912879,"thal, exang, ca, oldpeak, cp"
4,1,ANOVA,5,XGB,0.803279,0.807692,0.750000,0.777778,0.899892,"cp, exang, oldpeak, ca, thal"

In [46]:
# =============================================================================
# PREPARE STABILITY DATAFRAME
# =============================================================================

stability_df = results_df[
    ["Run", "Method", "Top_K", "Selected_Features"]
].copy()

stability_df["Feature_Set"] = stability_df["Selected_Features"].apply(
    lambda x: {
        feature.strip()
        for feature in x.split(",")
        if feature.strip()
    }
)

print("Shape:", stability_df.shape)

print("\nMethods:")
print(stability_df["Method"].unique())

print("\nTop-K:")
print(sorted(stability_df["Top_K"].unique()))

display(
    stability_df[
        ["Run", "Method", "Top_K", "Feature_Set"]
    ].head()
)

Shape: (600, 5)

Methods:
['ANOVA' 'DODA']

Top-K:
[np.int64(5), np.int64(8), np.int64(10), np.int64(13)]

   Run Method  Top_K                     Feature_Set
0    1  ANOVA      5  {oldpeak, thal, ca, cp, exang}
1    1   DODA      5  {oldpeak, ca, thal, cp, exang}
2    1  ANOVA      5  {oldpeak, thal, ca, cp, exang}
3    1   DODA      5  {oldpeak, ca, thal, cp, exang}
4    1  ANOVA      5  {oldpeak, thal, ca, cp, exang}

In [47]:
# =============================================================================
# TEST 1: FEATURE SELECTION FREQUENCY
# =============================================================================

selection_frequency = []

for method in stability_df["Method"].unique():

    for top_k in sorted(stability_df["Top_K"].unique()):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ]

        total_runs = len(subset)

        all_features = sorted(
            set().union(*subset["Feature_Set"])
        )

        for feature in all_features:

            selected_count = sum(
                feature in feature_set
                for feature_set in subset["Feature_Set"]
            )

            selection_frequency.append({
                "Method": method,
                "Top_K": top_k,
                "Feature": feature,
                "Selected_Count": selected_count,
                "Total_Runs": total_runs,
                "Selection_Frequency_Percentage":
                    (selected_count / total_runs) * 100
            })

selection_frequency_df = pd.DataFrame(selection_frequency)

selection_frequency_df = selection_frequency_df.sort_values(
    by=[
        "Method",
        "Top_K",
        "Selection_Frequency_Percentage"
    ],
    ascending=[True, True, False]
).reset_index(drop=True)

display(selection_frequency_df)

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,ANOVA,5,ca,75,75,100.0
1,ANOVA,5,thal,75,75,100.0
2,ANOVA,5,exang,72,75,96.0
3,ANOVA,5,oldpeak,54,75,72.0
4,ANOVA,5,cp,51,75,68.0
...,...,...,...,...,...,...
72,DODA,13,sex,75,75,100.0
73,DODA,13,slope,75,75,100.0
74,DODA,13,thal,75,75,100.0
75,DODA,13,thalach,75,75,100.0
76,DODA,13,trestbps,75,75,100.0

In [48]:
# =============================================================================
# TOP FREQUENTLY SELECTED FEATURES
# =============================================================================

top_frequency_features = (
    selection_frequency_df
    .groupby(["Method", "Top_K"], group_keys=False)
    .head(10)
    .reset_index(drop=True)
)

display(top_frequency_features)

,Method,Top_K,Feature,Selected_Count,Total_Runs,Selection_Frequency_Percentage
0,ANOVA,5,ca,75,75,100.0
1,ANOVA,5,thal,75,75,100.0
2,ANOVA,5,exang,72,75,96.0
3,ANOVA,5,oldpeak,54,75,72.0
4,ANOVA,5,cp,51,75,68.0
...,...,...,...,...,...,...
64,DODA,13,fbs,75,75,100.0
65,DODA,13,oldpeak,75,75,100.0
66,DODA,13,restecg,75,75,100.0
67,DODA,13,sex,75,75,100.0
68,DODA,13,slope,75,75,100.0

In [49]:
# =============================================================================
# TEST 2: PAIRWISE JACCARD SIMILARITY
# =============================================================================

jaccard_results = []

for method in stability_df["Method"].unique():

    for top_k in sorted(stability_df["Top_K"].unique()):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)

        feature_sets = subset["Feature_Set"].tolist()

        pairwise_scores = []

        for set_a, set_b in combinations(feature_sets, 2):

            intersection_size = len(set_a.intersection(set_b))
            union_size = len(set_a.union(set_b))

            if union_size == 0:
                jaccard_score = 1.0
            else:
                jaccard_score = intersection_size / union_size

            pairwise_scores.append(jaccard_score)

        jaccard_results.append({
            "Method": method,
            "Top_K": top_k,
            "Mean_Jaccard": np.mean(pairwise_scores),
            "Std_Jaccard": np.std(pairwise_scores, ddof=1),
            "Minimum_Jaccard": np.min(pairwise_scores),
            "Maximum_Jaccard": np.max(pairwise_scores)
        })

jaccard_df = pd.DataFrame(jaccard_results)

display(jaccard_df)

  Method  Top_K  Mean_Jaccard  Std_Jaccard  Minimum_Jaccard  Maximum_Jaccard
0  ANOVA      5      0.767568     0.153170         0.666667              1.0
1  ANOVA      8      0.966847     0.079186         0.777778              1.0
2  ANOVA     10      0.925700     0.089395         0.818182              1.0
3  ANOVA     13      1.000000     0.000000         1.000000              1.0
4   DODA      5      0.903784     0.151072         0.666667              1.0
5   DODA      8      1.000000     0.000000         1.000000              1.0
6   DODA     10      0.948698     0.081842         0.818182              1.0
7   DODA     13      1.000000     0.000000         1.000000              1.0

In [50]:
# =============================================================================
# TEST 3: KUNCHEVA INDEX
# =============================================================================

kuncheva_results = []


# =============================================================================
# TOTAL NUMBER OF FEATURES
# =============================================================================

N_FEATURES = len(feature_names)

print(
    "Total number of features:",
    N_FEATURES
)


# =============================================================================
# LOOP THROUGH METHODS AND TOP-K VALUES
# =============================================================================

for method in stability_df["Method"].unique():

    for top_k in sorted(
        stability_df["Top_K"].unique()
    ):

        subset = stability_df[
            (stability_df["Method"] == method) &
            (stability_df["Top_K"] == top_k)
        ].reset_index(drop=True)


        feature_sets = subset[
            "Feature_Set"
        ].tolist()


        # -------------------------------------------------------------
        # Pairwise Kuncheva comparison
        # -------------------------------------------------------------

        for i in range(len(feature_sets)):

            for j in range(i + 1, len(feature_sets)):

                set_a = feature_sets[i]
                set_b = feature_sets[j]


                intersection = len(
                    set_a.intersection(set_b)
                )


                # -----------------------------------------------------
                # Kuncheva Index
                # -----------------------------------------------------

                denominator = (
                    top_k *
                    (N_FEATURES - top_k)
                )


                if denominator == 0:

                    kuncheva = np.nan

                else:

                    kuncheva = (
                        (
                            intersection *
                            N_FEATURES
                        )
                        -
                        (top_k ** 2)
                    ) / denominator


                kuncheva_results.append({

                    "Method": method,

                    "Top_K": top_k,

                    "Run_A": subset.loc[
                        i, "Run"
                    ],

                    "Run_B": subset.loc[
                        j, "Run"
                    ],

                    "Intersection": intersection,

                    "Kuncheva_Index": kuncheva

                })


# =============================================================================
# CREATE DATAFRAME
# =============================================================================

kuncheva_df = pd.DataFrame(
    kuncheva_results
)


# =============================================================================
# DISPLAY PAIRWISE RESULTS
# =============================================================================

print("=" * 80)
print("KUNCHEVA INDEX — PAIRWISE RESULTS")
print("=" * 80)

display(
    kuncheva_df
)


# =============================================================================
# KUNCHEVA SUMMARY
# =============================================================================

kuncheva_summary = (
    kuncheva_df
    .groupby(
        ["Method", "Top_K"]
    )["Kuncheva_Index"]
    .agg(
        Mean_Kuncheva="mean",
        Std_Kuncheva="std",
        Min_Kuncheva="min",
        Max_Kuncheva="max"
    )
    .reset_index()
)


print("\n" + "=" * 80)
print("KUNCHEVA INDEX SUMMARY")
print("=" * 80)

display(
    kuncheva_summary
)

NameError: name 'feature_names' is not defined

In [51]:
# =============================================================================
# TEST 4: ANOVA VS DODA FEATURE-SET AGREEMENT
# =============================================================================

agreement_results = []

for run in sorted(stability_df["Run"].unique()):

    for top_k in sorted(stability_df["Top_K"].unique()):

        anova_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "ANOVA") &
            (stability_df["Top_K"] == top_k)
        ]

        doda_rows = stability_df[
            (stability_df["Run"] == run) &
            (stability_df["Method"] == "DODA") &
            (stability_df["Top_K"] == top_k)
        ]

        if anova_rows.empty or doda_rows.empty:
            continue

        anova_set = anova_rows.iloc[0]["Feature_Set"]
        doda_set = doda_rows.iloc[0]["Feature_Set"]

        intersection_size = len(anova_set.intersection(doda_set))
        union_size = len(anova_set.union(doda_set))

        if union_size == 0:
            jaccard_agreement = 1.0
        else:
            jaccard_agreement = intersection_size / union_size

        agreement_results.append({
            "Run": run,
            "Top_K": top_k,
            "ANOVA_Features": ", ".join(sorted(anova_set)),
            "DODA_Features": ", ".join(sorted(doda_set)),
            "Common_Feature_Count": intersection_size,
            "ANOVA_Feature_Count": len(anova_set),
            "DODA_Feature_Count": len(doda_set),
            "Same_Feature_Set": anova_set == doda_set,
            "Jaccard_Agreement": jaccard_agreement
        })

agreement_df = pd.DataFrame(agreement_results)

display(agreement_df)

,Run,Top_K,ANOVA_Features,DODA_Features,Common_Feature_Count,ANOVA_Feature_Count,DODA_Feature_Count,Same_Feature_Set,Jaccard_Agreement
0,1,5,"ca, cp, exang, oldpeak, thal","ca, cp, exang, oldpeak, thal",5,5,5,True,1.000000
1,1,8,"ca, cp, exang, oldpeak, sex, slope, thal, thalach","age, ca, cp, exang, oldpeak, slope, thal, thalach",7,8,8,False,0.777778
2,1,10,"age, ca, cp, exang, oldpeak, sex, slope, thal,...","age, ca, cp, exang, oldpeak, sex, slope, thal,...",10,10,10,True,1.000000
3,1,13,"age, ca, chol, cp, exang, fbs, oldpeak, restec...","age, ca, chol, cp, exang, fbs, oldpeak, restec...",13,13,13,True,1.000000
4,2,5,"ca, exang, oldpeak, thal, thalach","ca, exang, oldpeak, thal, thalach",5,5,5,True,1.000000
...,...,...,...,...,...,...,...,...,...
95,24,13,"age, ca, chol, cp, exang, fbs, oldpeak, restec...","age, ca, chol, cp, exang, fbs, oldpeak, restec...",13,13,13,True,1.000000
96,25,5,"ca, cp, exang, thal, thalach","ca, cp, exang, oldpeak, thal",4,5,5,False,0.666667
97,25,8,"ca, cp, exang, oldpeak, sex, slope, thal, thalach","age, ca, cp, exang, oldpeak, slope, thal, thalach",7,8,8,False,0.777778
98,25,10,"age, ca, cp, exang, oldpeak, sex, slope, thal,...","age, ca, cp, exang, oldpeak, sex, slope, thal,...",10,10,10,True,1.000000
99,25,13,"age, ca, chol, cp, exang, fbs, oldpeak, restec...","age, ca, chol, cp, exang, fbs, oldpeak, restec...",13,13,13,True,1.000000

In [52]:
# =============================================================================
# SUMMARY OF ANOVA VS DODA AGREEMENT
# =============================================================================

agreement_summary_df = (
    agreement_df
    .groupby("Top_K")
    .agg(
        Same_Feature_Set_Percentage=(
            "Same_Feature_Set",
            lambda x: x.mean() * 100
        ),
        Mean_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "mean"
        ),
        Std_Jaccard_Agreement=(
            "Jaccard_Agreement",
            "std"
        ),
        Mean_Common_Features=(
            "Common_Feature_Count",
            "mean"
        )
    )
    .reset_index()
)

display(agreement_summary_df)

,Top_K,Same_Feature_Set_Percentage,Mean_Jaccard_Agreement,Std_Jaccard_Agreement,Mean_Common_Features
0,5,52.0,0.840000,0.169967,4.52
1,8,8.0,0.795556,0.061531,7.08
2,10,40.0,0.890909,0.090909,9.40
3,13,100.0,1.000000,0.000000,13.00