# CKD — ANOVA + Rank Fusion: Primary Analysis vs. Sensitivity Analysis

This notebook runs the **same pipeline twice** on the same underlying CKD data, so the two runs can be compared directly:

- **Primary Analysis**: the full 400-row dataset, with missing values handled by median (numerical) / mode (categorical) imputation, fit on training data only within each fold.
- **Sensitivity Analysis**: only the 158 complete-case rows (zero missing values anywhere), no imputation needed at all.

**Why this comparison matters, concretely**: dropping every row with a missing value would cost 60.5% of the dataset and visibly shifts the class balance (62.5%/37.5% CKD in the full data vs. 27.2%/72.8% in the complete cases) — a strong sign the missingness isn't random. If the Primary and Sensitivity results agree, that's real evidence the imputation approach isn't distorting the conclusions. If they disagree, that's equally real evidence — and tells you exactly where to be cautious.

**Methodology upgrade from the earlier `ckd_anova.ipynb`**: this version uses `doda.fusion.RankFusion` directly from the package — it's been implemented properly since then as genuine **Reciprocal Rank Fusion (RRF)**, `RRF(f) = 1/(k + math_rank(f)) + 1/(k + clinical_rank(f))`, the same algorithm from Cormack, Clarke & Buettcher (2009). No more locally-redefined fusion class needed.

**Also new**: feature-selection stability (25-run repeated stratified CV, Jaccard similarity) and CV predictive performance, both with **paired Wilcoxon signed-rank tests, Holm correction, and Cohen's d effect sizes** comparing ANOVA vs. DODA — following the same rigor established in the Heart Disease experiment, applied here to both Primary and Sensitivity data.

**Imbalance handling**: `class_weight="balanced"` / `scale_pos_weight` used throughout (unlike the Heart Disease notebook, which didn't need this) since CKD is meaningfully imbalanced (62.5/37.5) — consistent with how breast cancer's similar imbalance was handled earlier in this project.

In [1]:
# =============================================================================
# STEP 1: LOAD AND CLEAN RAW DATA (shared by both analyses)
# =============================================================================

import pandas as pd
import numpy as np

df = pd.read_csv("../../data/raw/ckd.csv")
df = df.drop(columns=["id"])

# Known data-quality issues in this exact UCI file (see 01_ckd_eda.ipynb)
categorical_cols_raw = df.select_dtypes(include="object").columns
for col in categorical_cols_raw:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan, "?": np.nan})

for col in ["pcv", "wc", "rc"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Encode categorical features and target
target_column = "target"

binary_maps = {
    "rbc":   {"normal": 0, "abnormal": 1},
    "pc":    {"normal": 0, "abnormal": 1},
    "pcc":   {"notpresent": 0, "present": 1},
    "ba":    {"notpresent": 0, "present": 1},
    "htn":   {"no": 0, "yes": 1},
    "dm":    {"no": 0, "yes": 1},
    "cad":   {"no": 0, "yes": 1},
    "appet": {"poor": 0, "good": 1},
    "pe":    {"no": 0, "yes": 1},
    "ane":   {"no": 0, "yes": 1},
}
for col, mapping in binary_maps.items():
    df[col] = df[col].map(mapping)

df[target_column] = df["classification"].map({"ckd": 1, "notckd": 0})
df = df.drop(columns=["classification"])

numerical_features = ["age", "bp", "sg", "al", "su", "bgr", "bu", "sc",
                       "sod", "pot", "hemo", "pcv", "wc", "rc"]
categorical_features = ["rbc", "pc", "pcc", "ba", "htn", "dm", "cad",
                         "appet", "pe", "ane"]

print("=" * 70)
print("CLEANED + ENCODED DATASET")
print("=" * 70)
print(f"Shape: {df.shape}")
display(df.head())

======================================================================
CLEANED + ENCODED DATASET
======================================================================
Shape: (400, 25)

C:\Users\johnm\AppData\Local\Temp\ipykernel_19772\1346706842.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols_raw = df.select_dtypes(include="object").columns

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,target
0,48.0,80.0,1.020,1.0,0.0,NaN,0.0,0.0,0.0,121.0,...,44.0,7800.0,5.2,1.0,1.0,0.0,1.0,0.0,0.0,1
1,7.0,50.0,1.020,4.0,0.0,NaN,0.0,0.0,0.0,NaN,...,38.0,6000.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1
2,62.0,80.0,1.010,2.0,3.0,0.0,0.0,0.0,0.0,423.0,...,31.0,7500.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1
3,48.0,70.0,1.005,4.0,0.0,0.0,1.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1.0,0.0,0.0,0.0,1.0,1.0,1
4,51.0,80.0,1.010,2.0,0.0,0.0,0.0,0.0,0.0,106.0,...,35.0,7300.0,4.6,0.0,0.0,0.0,1.0,0.0,0.0,1

In [2]:
# =============================================================================
# STEP 2: DEFINE THE TWO DATASETS — PRIMARY (imputed) vs SENSITIVITY (complete-case)
# =============================================================================

# --- Primary: full dataset, missing values handled by imputation later ---
X_primary = df.drop(columns=[target_column])
y_primary = df[target_column]

# --- Sensitivity: complete cases only, no imputation needed ---
df_complete = df.dropna()
X_sensitivity = df_complete.drop(columns=[target_column])
y_sensitivity = df_complete[target_column]

print("=" * 70)
print("PRIMARY vs SENSITIVITY DATASET SIZES")
print("=" * 70)
print(f"Primary (full, to be imputed) : {X_primary.shape[0]} rows")
print(f"Sensitivity (complete-case)    : {X_sensitivity.shape[0]} rows "
      f"({X_sensitivity.shape[0]/X_primary.shape[0]*100:.1f}% of primary)")

print("\nClass balance comparison:")
print("Primary:")
display((y_primary.value_counts(normalize=True) * 100).round(2))
print("Sensitivity:")
display((y_sensitivity.value_counts(normalize=True) * 100).round(2))

======================================================================
PRIMARY vs SENSITIVITY DATASET SIZES
======================================================================
Primary (full, to be imputed) : 400 rows
Sensitivity (complete-case)    : 158 rows (39.5% of primary)

Class balance comparison:
Primary:

target
1    62.5
0    37.5
Name: proportion, dtype: float64

Sensitivity:

target
0    72.78
1    27.22
Name: proportion, dtype: float64

In [5]:
#%pip uninstall -y doda

In [6]:
#%pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

In [7]:
# =============================================================================
# STEP 3: SHARED HELPER FUNCTIONS
# Defined once, called twice (Primary and Sensitivity) — avoids duplicating
# ~150 lines of loop logic twice with only the input data differing.
# =============================================================================

from sklearn.model_selection import RepeatedStratifiedKFold, train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
)
from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion

WEIGHTS_FILE = "../../../config/clinical_weights/ckd_clinical_weights.json"


def make_models(y_train):
    """Fresh model instances, class-imbalance-aware (CKD is ~63/37)."""
    return {
        "LR": LogisticRegression(max_iter=2000, class_weight="balanced", random_state=42),
        "RF": RandomForestClassifier(n_estimators=300, class_weight="balanced",
                                      random_state=42, n_jobs=-1),
        "XGB": XGBClassifier(n_estimators=300, max_depth=3, learning_rate=0.05,
                              subsample=0.8, colsample_bytree=0.8, eval_metric="logloss",
                              scale_pos_weight=(y_train == 0).sum() / max((y_train == 1).sum(), 1),
                              random_state=42, n_jobs=-1)
    }


def impute_if_needed(X_train, X_test, do_impute):
    """Median/mode imputation fit on TRAIN only — skipped entirely for the
    complete-case (Sensitivity) dataset, since it has no missing values."""
    if not do_impute:
        return X_train.copy(), X_test.copy()

    num_cols = [c for c in numerical_features if c in X_train.columns]
    cat_cols = [c for c in categorical_features if c in X_train.columns]

    num_imp = SimpleImputer(strategy="median")
    cat_imp = SimpleImputer(strategy="most_frequent")

    X_train_i, X_test_i = X_train.copy(), X_test.copy()
    X_train_i[num_cols] = num_imp.fit_transform(X_train[num_cols])
    X_test_i[num_cols] = num_imp.transform(X_test[num_cols])
    X_train_i[cat_cols] = cat_imp.fit_transform(X_train[cat_cols])
    X_test_i[cat_cols] = cat_imp.transform(X_test[cat_cols])

    return X_train_i, X_test_i


def run_stability_analysis(X, y, k_values, do_impute, label):
    """25-run (5x5) repeated stratified CV. For each K, runs BOTH ANOVA and
    DODA, records selected feature sets, computes pairwise Jaccard similarity."""

    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=42)
    all_jaccard = []

    for k in k_values:
        print(f"\n{'='*70}\n{label} STABILITY — TOP-{k}\n{'='*70}")

        for method in ["ANOVA", "DODA"]:
            selected_sets = []

            for train_idx, _ in cv.split(X, y):
                X_train = X.iloc[train_idx]
                y_train = y.iloc[train_idx]
                X_train_imp, _ = impute_if_needed(X_train, X_train, do_impute)

                if method == "ANOVA":
                    sel = SelectKBest(score_func=f_classif, k=k)
                    sel.fit(X_train_imp, y_train)
                    features = X_train_imp.columns[sel.get_support()].tolist()
                else:
                    operator = SklearnAdapter(SelectKBest(score_func=f_classif, k="all"))
                    provider = JSONProvider(WEIGHTS_FILE)
                    selector = DODASelector(operators=[operator], provider=provider,
                                             fusion=RankFusion(), top_k=k)
                    selector.fit(X_train_imp, y_train)
                    features = list(selector.get_selected_features())

                selected_sets.append(set(features))

            jaccard_scores = []
            for i in range(len(selected_sets)):
                for j in range(i + 1, len(selected_sets)):
                    inter = len(selected_sets[i] & selected_sets[j])
                    union = len(selected_sets[i] | selected_sets[j])
                    jaccard_scores.append(inter / union)

            for score in jaccard_scores:
                all_jaccard.append({"Top_K": k, "Method": method, "Jaccard": score})

            print(f"{method}: mean Jaccard = {np.mean(jaccard_scores):.4f} "
                  f"(std {np.std(jaccard_scores):.4f})")

    return pd.DataFrame(all_jaccard)


def run_cv_performance(X, y, k_values, do_impute, label):
    """25-run (5x5) repeated stratified CV predictive performance,
    ANOVA vs DODA, across 3 models and all Top-K values."""

    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=42)
    results = []

    for run_id, (train_idx, test_idx) in enumerate(cv.split(X, y), start=1):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
        X_train_imp, X_test_imp = impute_if_needed(X_train, X_test, do_impute)

        for k in k_values:
            for method in ["ANOVA", "DODA"]:
                if method == "ANOVA":
                    sel = SelectKBest(score_func=f_classif, k=k)
                    X_train_sel = pd.DataFrame(sel.fit_transform(X_train_imp, y_train),
                                                columns=X_train_imp.columns[sel.get_support()])
                    X_test_sel = pd.DataFrame(sel.transform(X_test_imp),
                                               columns=X_train_sel.columns)
                else:
                    operator = SklearnAdapter(SelectKBest(score_func=f_classif, k="all"))
                    provider = JSONProvider(WEIGHTS_FILE)
                    selector = DODASelector(operators=[operator], provider=provider,
                                             fusion=RankFusion(), top_k=k)
                    X_train_sel = selector.fit_transform(X_train_imp, y_train)
                    X_test_sel = selector.transform(X_test_imp)

                models = make_models(y_train)
                for model_name, model in models.items():
                    if model_name == "LR":
                        scaler = StandardScaler()
                        Xtr = scaler.fit_transform(X_train_sel)
                        Xts = scaler.transform(X_test_sel)
                    else:
                        Xtr, Xts = X_train_sel, X_test_sel

                    model.fit(Xtr, y_train)
                    y_pred = model.predict(Xts)
                    y_prob = model.predict_proba(Xts)[:, 1]

                    results.append({
                        "Run": run_id, "Top_K": k, "Method": method, "Model": model_name,
                        "Accuracy": accuracy_score(y_test, y_pred),
                        "F1": f1_score(y_test, y_pred, zero_division=0),
                        "ROC_AUC": roc_auc_score(y_test, y_prob)
                    })

        if run_id % 5 == 0:
            print(f"{label}: completed {run_id}/25 CV runs")

    return pd.DataFrame(results)


def wilcoxon_holm_test(df, group_cols, value_col="Jaccard"):
    """Paired Wilcoxon signed-rank test (ANOVA vs DODA) + Cohen's d,
    with Holm correction across all comparisons in this dataframe."""
    rows = []
    for keys, group in df.groupby(group_cols):
        anova_vals = group[group.Method == "ANOVA"].sort_values(value_col)[value_col].values \
            if "Run" not in group.columns else \
            group[group.Method == "ANOVA"].sort_values("Run")[value_col].values
        doda_vals = group[group.Method == "DODA"].sort_values(value_col)[value_col].values \
            if "Run" not in group.columns else \
            group[group.Method == "DODA"].sort_values("Run")[value_col].values

        n = min(len(anova_vals), len(doda_vals))
        anova_vals, doda_vals = anova_vals[:n], doda_vals[:n]

        if np.allclose(anova_vals, doda_vals):
            stat, p = np.nan, 1.0
        else:
            try:
                stat, p = wilcoxon(anova_vals, doda_vals)
            except ValueError:
                stat, p = np.nan, 1.0

        diff = doda_vals - anova_vals
        pooled_std = np.std(np.concatenate([anova_vals, doda_vals]), ddof=1)
        cohens_d = diff.mean() / pooled_std if pooled_std > 0 else 0.0

        rows.append({
            **(dict(zip(group_cols, keys)) if isinstance(keys, tuple) else {group_cols[0]: keys}),
            "ANOVA_mean": anova_vals.mean(),
            "DODA_mean": doda_vals.mean(),
            "p_value": p,
            "cohens_d": cohens_d
        })

    result_df = pd.DataFrame(rows)
    if len(result_df) > 0:
        reject, p_adj, _, _ = multipletests(result_df["p_value"].fillna(1.0), method="holm")
        result_df["p_holm"] = p_adj
        result_df["significant"] = reject
    return result_df


print("Helper functions defined.")

ImportError: cannot import name 'RankFusion' from 'doda.fusion' (c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\fusion\__init__.py)

# PRIMARY ANALYSIS (Imputed, n=400)

## 1. Baseline (80/20 split, for direct comparison with earlier notebooks)

In [4]:
# =============================================================================
# PRIMARY: TRAIN-TEST SPLIT, IMPUTATION, SCALING
# =============================================================================

X_train, X_test, y_train, y_test = train_test_split(
    X_primary, y_primary, test_size=0.2, random_state=42, stratify=y_primary
)

X_train_imp, X_test_imp = impute_if_needed(X_train, X_test, do_impute=True)

scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train_imp), columns=X_train_imp.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test_imp), columns=X_test_imp.columns)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

print("PRIMARY split:", X_train_scaled.shape, X_test_scaled.shape)
print("Missing after imputation:", X_train_scaled.isnull().sum().sum(),
      X_test_scaled.isnull().sum().sum())

PRIMARY split: (320, 24) (80, 24)
Missing after imputation: 0 0

In [5]:
# =============================================================================
# PRIMARY: ANOVA BASELINE TOP-K
# =============================================================================

k_values = [5, 10, 15, 20]

anova_selector = SelectKBest(score_func=f_classif, k="all")
anova_selector.fit(X_train_scaled, y_train)
anova_scores = pd.DataFrame({
    "Feature": X_train_scaled.columns, "ANOVA Score": anova_selector.scores_
}).sort_values("ANOVA Score", ascending=False).reset_index(drop=True)

anova_results = {}
for k in k_values:
    top_features = anova_scores.head(k)["Feature"].tolist()
    mask = X_train_scaled.columns.isin(top_features)
    anova_results[k] = {
        "features": top_features,
        "X_train": X_train_scaled.loc[:, mask],
        "X_test": X_test_scaled.loc[:, mask]
    }
    print(f"Top-{k}:", top_features)

Top-5: ['hemo', 'pcv', 'sg', 'rc', 'htn']
Top-10: ['hemo', 'pcv', 'sg', 'rc', 'htn', 'dm', 'al', 'pc', 'appet', 'bu']
Top-15: ['hemo', 'pcv', 'sg', 'rc', 'htn', 'dm', 'al', 'pc', 'appet', 'bu', 'pe', 'bgr', 'ane', 'sod', 'bp']
Top-20: ['hemo', 'pcv', 'sg', 'rc', 'htn', 'dm', 'al', 'pc', 'appet', 'bu', 'pe', 'bgr', 'ane', 'sod', 'bp', 'pcc', 'sc', 'rbc', 'su', 'cad']

In [6]:
# =============================================================================
# PRIMARY: BASELINE MODEL EVALUATION
# =============================================================================

primary_baseline_results = []
for k in k_values:
    Xtr, Xts = anova_results[k]["X_train"], anova_results[k]["X_test"]
    models = make_models(y_train)
    for model_name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        primary_baseline_results.append({
            "Method": "ANOVA", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "F1 Score": f1_score(y_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(y_test, y_prob)
        })

primary_baseline_df = pd.DataFrame(primary_baseline_results)
display(primary_baseline_df)

   Method  Top-K Model  Accuracy  F1 Score   ROC-AUC
0   ANOVA      5    LR    0.9500  0.959184  0.986000
1   ANOVA      5    RF    0.9875  0.990099  0.998667
2   ANOVA      5   XGB    0.9875  0.990099  0.996000
3   ANOVA     10    LR    0.9750  0.979592  1.000000
4   ANOVA     10    RF    0.9875  0.989899  1.000000
5   ANOVA     10   XGB    0.9875  0.990099  1.000000
6   ANOVA     15    LR    0.9750  0.979592  1.000000
7   ANOVA     15    RF    1.0000  1.000000  1.000000
8   ANOVA     15   XGB    0.9875  0.989899  0.999333
9   ANOVA     20    LR    0.9750  0.979592  0.999333
10  ANOVA     20    RF    1.0000  1.000000  1.000000
11  ANOVA     20   XGB    1.0000  1.000000  1.000000

In [7]:
# =============================================================================
# PRIMARY: RANK FUSION DODA
# =============================================================================

provider = JSONProvider(WEIGHTS_FILE)
fusion = RankFusion()

primary_doda_results_by_k = {}
for k in k_values:
    operator = SklearnAdapter(SelectKBest(score_func=f_classif, k="all"))
    selector = DODASelector(operators=[operator], provider=provider, fusion=fusion, top_k=k)
    X_train_sel = selector.fit_transform(X_train_scaled, y_train)
    X_test_sel = selector.transform(X_test_scaled)
    features = selector.get_selected_features()
    primary_doda_results_by_k[k] = {"X_train": X_train_sel, "X_test": X_test_sel,
                                     "features": features, "selector": selector}
    print(f"Top-{k}:", features)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}

Normalized Mathematical Scores
{'age': np.float64(0.03432240549099475), 'bp': np.float64(0.08789120993828284), 'sg': np.float64(0.5961011648904558), 'al': np.float64(0.3193734560836549), 'su': np.float64(0.06548204222666795), 'rbc': np.float64(0.0689326165686331), 'pc': np.float64(0.1444062843445097), 'pcc': np.float64(0.07606849820099681), 'ba': np.float64(0.034891818263135366), 'bgr': np.float64(0.12485966719713518), 'bu': np.float64(0.14042576353426572), 'sc': np.float64(0.07331984765252175), 'sod': np.float64(0.09812477222482771), 'pot': np.float64(0.00028985378329315095), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6953650548359581), 'wc': np.float64(0.024833498085088505), 'rc': np.float64(0.47060539235604254), 'htn': np.float64(0.4426636702539963), 'dm': np.float64(0.3268437669954925), 'cad': np.float64(0.04486090919545982), 'appet': np.float64(0.14108430862919968), 'pe': np.float64(0.12826428967152598), 'ane': np.float64(0.10190259505988554)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.027809742999616416, 'rbc': 0.028949545078577336, 'pc': 0.029857397504456328, 'pcc': 0.028309409888357256, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']
Top-5: ['hemo', 'pcv', 'htn', 'al', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}

Normalized Mathematical Scores
{'age': np.float64(0.03432240549099475), 'bp': np.float64(0.08789120993828284), 'sg': np.float64(0.5961011648904558), 'al': np.float64(0.3193734560836549), 'su': np.float64(0.06548204222666795), 'rbc': np.float64(0.0689326165686331), 'pc': np.float64(0.1444062843445097), 'pcc': np.float64(0.07606849820099681), 'ba': np.float64(0.034891818263135366), 'bgr': np.float64(0.12485966719713518), 'bu': np.float64(0.14042576353426572), 'sc': np.float64(0.07331984765252175), 'sod': np.float64(0.09812477222482771), 'pot': np.float64(0.00028985378329315095), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6953650548359581), 'wc': np.float64(0.024833498085088505), 'rc': np.float64(0.47060539235604254), 'htn': np.float64(0.4426636702539963), 'dm': np.float64(0.3268437669954925), 'cad': np.float64(0.04486090919545982), 'appet': np.float64(0.14108430862919968), 'pe': np.float64(0.12826428967152598), 'ane': np.float64(0.10190259505988554)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.027809742999616416, 'rbc': 0.028949545078577336, 'pc': 0.029857397504456328, 'pcc': 0.028309409888357256, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe']
Top-10: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}

Normalized Mathematical Scores
{'age': np.float64(0.03432240549099475), 'bp': np.float64(0.08789120993828284), 'sg': np.float64(0.5961011648904558), 'al': np.float64(0.3193734560836549), 'su': np.float64(0.06548204222666795), 'rbc': np.float64(0.0689326165686331), 'pc': np.float64(0.1444062843445097), 'pcc': np.float64(0.07606849820099681), 'ba': np.float64(0.034891818263135366), 'bgr': np.float64(0.12485966719713518), 'bu': np.float64(0.14042576353426572), 'sc': np.float64(0.07331984765252175), 'sod': np.float64(0.09812477222482771), 'pot': np.float64(0.00028985378329315095), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6953650548359581), 'wc': np.float64(0.024833498085088505), 'rc': np.float64(0.47060539235604254), 'htn': np.float64(0.4426636702539963), 'dm': np.float64(0.3268437669954925), 'cad': np.float64(0.04486090919545982), 'appet': np.float64(0.14108430862919968), 'pe': np.float64(0.12826428967152598), 'ane': np.float64(0.10190259505988554)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.027809742999616416, 'rbc': 0.028949545078577336, 'pc': 0.029857397504456328, 'pcc': 0.028309409888357256, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe', 'appet', 'bgr', 'sc', 'ane', 'bp']
Top-15: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe', 'appet', 'bgr', 'sc', 'ane', 'bp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.033768241197253), 'bp': np.float64(33.37626382493944), 'sg': np.float64(226.36654745916326), 'al': np.float64(121.28053233555288), 'su': np.float64(24.866490274599517), 'rbc': np.float64(26.176829268292586), 'pc': np.float64(54.83759124087606), 'pcc': np.float64(28.88664596273283), 'ba': np.float64(13.249999999999986), 'bgr': np.float64(47.41485748565791), 'bu': np.float64(53.326007627262655), 'sc': np.float64(27.84285915023033), 'sod': np.float64(37.26240983413097), 'pot': np.float64(0.11007057871478018), 'hemo': np.float64(379.74518553534807), 'pcv': np.float64(264.0615317634784), 'wc': np.float64(9.430401337813645), 'rc': np.float64(178.71013203418065), 'htn': np.float64(168.09939759036195), 'dm': np.float64(124.11734693877537), 'cad': np.float64(17.035714285714292), 'appet': np.float64(53.57608695652174), 'pe': np.float64(48.70774647887326), 'ane': np.float64(38.69701986754968)}

Normalized Mathematical Scores
{'age': np.float64(0.03432240549099475), 'bp': np.float64(0.08789120993828284), 'sg': np.float64(0.5961011648904558), 'al': np.float64(0.3193734560836549), 'su': np.float64(0.06548204222666795), 'rbc': np.float64(0.0689326165686331), 'pc': np.float64(0.1444062843445097), 'pcc': np.float64(0.07606849820099681), 'ba': np.float64(0.034891818263135366), 'bgr': np.float64(0.12485966719713518), 'bu': np.float64(0.14042576353426572), 'sc': np.float64(0.07331984765252175), 'sod': np.float64(0.09812477222482771), 'pot': np.float64(0.00028985378329315095), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6953650548359581), 'wc': np.float64(0.024833498085088505), 'rc': np.float64(0.47060539235604254), 'htn': np.float64(0.4426636702539963), 'dm': np.float64(0.3268437669954925), 'cad': np.float64(0.04486090919545982), 'appet': np.float64(0.14108430862919968), 'pe': np.float64(0.12826428967152598), 'ane': np.float64(0.10190259505988554)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.027809742999616416, 'rbc': 0.028949545078577336, 'pc': 0.029857397504456328, 'pcc': 0.028309409888357256, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe', 'appet', 'bgr', 'sc', 'ane', 'bp', 'sod', 'rbc', 'pcc', 'cad', 'age']
Top-20: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pc', 'pe', 'appet', 'bgr', 'sc', 'ane', 'bp', 'sod', 'rbc', 'pcc', 'cad', 'age']

In [8]:
# =============================================================================
# PRIMARY: DODA MODEL EVALUATION + COMBINED BASELINE COMPARISON
# =============================================================================

primary_doda_results = []
for k in k_values:
    Xtr, Xts = primary_doda_results_by_k[k]["X_train"], primary_doda_results_by_k[k]["X_test"]
    models = make_models(y_train)
    for model_name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        primary_doda_results.append({
            "Method": "ANOVA + Rank Fusion", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "F1 Score": f1_score(y_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(y_test, y_prob)
        })

primary_doda_df = pd.DataFrame(primary_doda_results)
primary_comparison_df = pd.concat([primary_baseline_df, primary_doda_df], ignore_index=True)
display(primary_comparison_df)

import os
os.makedirs("../../../results/ckd/primary", exist_ok=True)
primary_comparison_df.to_csv("../../../results/ckd/primary/anova_rankfusion_80_20_comparison.csv", index=False)

                 Method  Top-K Model  Accuracy  F1 Score   ROC-AUC
0                 ANOVA      5    LR    0.9500  0.959184  0.986000
1                 ANOVA      5    RF    0.9875  0.990099  0.998667
2                 ANOVA      5   XGB    0.9875  0.990099  0.996000
3                 ANOVA     10    LR    0.9750  0.979592  1.000000
4                 ANOVA     10    RF    0.9875  0.989899  1.000000
5                 ANOVA     10   XGB    0.9875  0.990099  1.000000
6                 ANOVA     15    LR    0.9750  0.979592  1.000000
7                 ANOVA     15    RF    1.0000  1.000000  1.000000
8                 ANOVA     15   XGB    0.9875  0.989899  0.999333
9                 ANOVA     20    LR    0.9750  0.979592  0.999333
10                ANOVA     20    RF    1.0000  1.000000  1.000000
11                ANOVA     20   XGB    1.0000  1.000000  1.000000
12  ANOVA + Rank Fusion      5    LR    0.9375  0.948454  0.979000
13  ANOVA + Rank Fusion      5    RF    0.9625  0.969697  0.983333
14  ANOVA + Rank Fusion      5   XGB    0.9500  0.959184  0.989667
15  ANOVA + Rank Fusion     10    LR    0.9875  0.989899  1.000000
16  ANOVA + Rank Fusion     10    RF    1.0000  1.000000  1.000000
17  ANOVA + Rank Fusion     10   XGB    0.9875  0.990099  1.000000
18  ANOVA + Rank Fusion     15    LR    0.9750  0.979592  1.000000
19  ANOVA + Rank Fusion     15    RF    1.0000  1.000000  1.000000
20  ANOVA + Rank Fusion     15   XGB    1.0000  1.000000  1.000000
21  ANOVA + Rank Fusion     20    LR    0.9750  0.979592  1.000000
22  ANOVA + Rank Fusion     20    RF    1.0000  1.000000  1.000000
23  ANOVA + Rank Fusion     20   XGB    1.0000  1.000000  1.000000

## 2. Feature-Selection Stability (25-run repeated CV)

In [9]:
# =============================================================================
# PRIMARY: STABILITY ANALYSIS
# =============================================================================

primary_jaccard_df = run_stability_analysis(
    X_primary, y_primary, k_values, do_impute=True, label="PRIMARY"
)

primary_stability_summary = primary_jaccard_df.groupby(["Top_K", "Method"])["Jaccard"].agg(
    ["mean", "std"]
).reset_index()
print("\n" + "=" * 70)
print("PRIMARY STABILITY SUMMARY")
print("=" * 70)
display(primary_stability_summary)

======================================================================
PRIMARY STABILITY — TOP-5
======================================================================

ANOVA: mean Jaccard = 0.8489 (std 0.1659)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f606960>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd3c80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32b380>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3056d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3462d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e339790>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617230>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6667387890>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e347830>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34c3e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights

ANOVA: mean Jaccard = 0.8084 (std 0.1004)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f615f10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e346c30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3054c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3243e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e329580>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores

DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e1b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34d5e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg', 'dm', 'rc', 'bu', 'pe', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f6158b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34c920>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights

ANOVA: mean Jaccard = 0.8968 (std 0.0631)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3284d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc', 'bu', 'bgr', 'appet', 'bp', 'rbc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3452e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc', 'sc', 'pe', 'appet', 'sod', 'ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e346db0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet', 'bgr', 'sc', 'ane', 'sod', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34eff0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sc', 'bp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e4b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores

DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.06642260880594358), 'bp': np.float64(0.0837353477266576), 'sg': np.float64(0.7370090545195246), 'al': np.float64(0.391270587870701), 'su': np.float64(0.09536871259936801), 'rbc': np.float64(0.08980447254983023), 'pc': np.float64(0.16904371303497454), 'pcc': np.float64(0.0870155137749908), 'ba': np.float64(0.035527044085647136), 'bgr': np.float64(0.17226116099667094), 'bu': np.float64(0.1507054884261271), 'sc': np.float64(0.08605304364586153), 'sod': np.float64(0.11734480613215331), 'pot': np.float64(0.003536204247882121), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6563601133539506), 'wc': np.float64(0.02265546716759715), 'rc': np.float64(0.485064496884727), 'htn': np.float64(0.5063673873894039), 'dm': np.float64(0.4480133237317373), 'cad': np.float64(0.056062907718969164), 'appet': np.float64(0.18095938829589855), 'pe': np.float64(0.15764238346876674), 'ane': np.float64(0.11034797934227505)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'appet', 'bu', 'pe', 'pc', 'sod', 'rbc', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34f260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'ane', 'pc', 'sc', 'sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e8a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'sc', 'ane', 'bp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34f590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc', 'bu', 'appet', 'pe', 'pc', 'ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34f260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3afbf0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04632012624498299), 'bp': np.float64(0.08768748863230913), 'sg': np.float64(0.6291628689310891), 'al': np.float64(0.27570257130402037), 'su': np.float64(0.07592230621857678), 'rbc': np.float64(0.06726783842996786), 'pc': np.float64(0.1264043996870825), 'pcc': np.float64(0.0581699059288733), 'ba': np.float64(0.027575635629676264), 'bgr': np.float64(0.14787268227408162), 'bu': np.float64(0.133934818651203), 'sc': np.float64(0.07888996503724914), 'sod': np.float64(0.10139654446287828), 'pot': np.float64(0.004631292860360031), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7373359487228023), 'wc': np.float64(0.020456207282722415), 'rc': np.float64(0.4052286615934912), 'htn': np.float64(0.4470243101172216), 'dm': np.float64(0.38759087857267194), 'cad': np.float64(0.05596231936610772), 'appet': np.float64(0.1391676862893376), 'pe': np.float64(0.12952780961263433), 'ane': np.float64(0.10014309781303485)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.030158730158730156, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'sod', 'bp', 'ane']
DODA: mean Jaccard = 0.8745 (std 0.0757)

======================================================================
PRIMARY STABILITY — TOP-20
======================================================================

ANOVA: mean Jaccard = 0.9600 (std 0.0470)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34dbe0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc', 'bu', 'bgr', 'appet', 'bp', 'rbc', 'pc', 'ane', 'su', 'cad', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34fdd0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc', 'sc', 'pe', 'appet', 'sod', 'ane', 'rbc', 'bp', 'su', 'age', 'cad']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af800>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet', 'bgr', 'sc', 'ane', 'sod', 'pc', 'bp', 'rbc', 'su', 'cad', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34fc20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sc', 'bp', 'sod', 'rbc', 'su', 'cad', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af1d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34c320>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'ane', 'pc', 'sc', 'sod', 'rbc', 'bp', 'su', 'cad', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e344860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'sc', 'ane', 'bp', 'sod', 'rbc', 'su', 'cad', 'pcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e347c50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc', 'bu', 'appet', 'pe', 'pc', 'ane', 'rbc', 'bp', 'su', 'cad', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34dfd0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg', 'dm', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sod', 'rbc', 'sc', 'bp', 'su', 'age', 'pcc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ac6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores

   Top_K Method      mean       std
0      5  ANOVA  0.848889  0.166216
1      5   DODA  0.860000  0.164794
2     10  ANOVA  0.808384  0.100544
3     10   DODA  0.783784  0.127454
4     15  ANOVA  0.896814  0.063200
5     15   DODA  0.874534  0.075872
6     20  ANOVA  0.960000  0.047084
7     20   DODA  0.961270  0.046860

In [10]:
# =============================================================================
# PRIMARY: STABILITY SIGNIFICANCE TESTING (Wilcoxon + Holm + Cohen's d)
# =============================================================================

primary_stability_test = wilcoxon_holm_test(primary_jaccard_df, ["Top_K"], value_col="Jaccard")
print("=" * 70)
print("PRIMARY — ANOVA vs DODA STABILITY: SIGNIFICANCE TEST")
print("=" * 70)
display(primary_stability_test.round(4))

======================================================================
PRIMARY — ANOVA vs DODA STABILITY: SIGNIFICANCE TEST
======================================================================

   Top_K  ANOVA_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0      5      0.8489     0.8600   0.0016    0.0672  0.0031         True
1     10      0.8084     0.7838   0.0000   -0.2133  0.0000         True
2     15      0.8968     0.8745   0.0000   -0.3153  0.0000         True
3     20      0.9600     0.9613   0.0455    0.0271  0.0455         True

## 3. Predictive Performance (25-run repeated CV)

In [11]:
# =============================================================================
# PRIMARY: CV PREDICTIVE PERFORMANCE
# =============================================================================

primary_cv_results = run_cv_performance(
    X_primary, y_primary, k_values, do_impute=True, label="PRIMARY"
)

primary_cv_summary = primary_cv_results.groupby(["Top_K", "Method", "Model"]).agg(
    {"Accuracy": ["mean", "std"], "F1": ["mean", "std"], "ROC_AUC": ["mean", "std"]}
).reset_index()
primary_cv_summary.columns = ["Top_K", "Method", "Model", "Acc_Mean", "Acc_STD",
                               "F1_Mean", "F1_STD", "AUC_Mean", "AUC_STD"]

os.makedirs("../../../results/ckd/primary", exist_ok=True)
primary_cv_results.to_csv("../../../results/ckd/primary/cv_performance_runs.csv", index=False)
primary_cv_summary.to_csv("../../../results/ckd/primary/cv_performance_summary.csv", index=False)

print("=" * 70)
print("PRIMARY CV PERFORMANCE SUMMARY")
print("=" * 70)
display(primary_cv_summary.round(4))

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e306570>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e326930>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22c0e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc', 'bu', 'bgr', 'appet', 'bp', 'rbc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e307fe0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.680931940287804), 'bp': np.float64(37.305673867208945), 'sg': np.float64(223.18444977221588), 'al': np.float64(123.19658076503616), 'su': np.float64(30.789409729824396), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(44.10616438356164), 'pcc': np.float64(20.22368421052632), 'ba': np.float64(7.611702127659573), 'bgr': np.float64(52.02822635558733), 'bu': np.float64(46.60060505313), 'sc': np.float64(42.10784534352323), 'sod': np.float64(75.86032790605188), 'pot': np.float64(1.16494223458721), 'hemo': np.float64(334.76933360080085), 'pcv': np.float64(256.140163846139), 'wc': np.float64(9.409275235718171), 'rc': np.float64(130.5421947828456), 'htn': np.float64(182.6487341772152), 'dm': np.float64(145.75), 'cad': np.float64(16.261363636363633), 'appet': np.float64(60.07330827067671), 'pe': np.float64(54.83759124087591), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.0408667418641212), 'bp': np.float64(0.11143695112675547), 'sg': np.float64(0.6666812858024639), 'al': np.float64(0.36800437913450934), 'su': np.float64(0.09197201368073799), 'rbc': np.float64(0.08628820821795793), 'pc': np.float64(0.1317509101241528), 'pcc': np.float64(0.06041080284445128), 'ba': np.float64(0.022737154702276958), 'bgr': np.float64(0.15541515047381527), 'bu': np.float64(0.13920213226190956), 'sc': np.float64(0.12578166850173667), 'sod': np.float64(0.22660477018636455), 'pot': np.float64(0.0034798355693366986), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7651243352880583), 'wc': np.float64(0.028106741840751636), 'rc': np.float64(0.38994669367927226), 'htn': np.float64(0.5455957754930342), 'dm': np.float64(0.4353744067065626), 'cad': np.float64(0.04857483050031896), 'appet': np.float64(0.1794468675625819), 'pe': np.float64(0.16380709263611212), 'ane': np.float64(0.10640200966736536)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.028850145288501453, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029910714285714284, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'pe', 'sc', 'bu', 'bgr', 'appet', 'bp', 'rbc', 'pc', 'ane', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f66675cd760>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f616570>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22ec90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc', 'sc', 'pe', 'appet', 'sod', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e338ec0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.94798193690508), 'bp': np.float64(26.93377237833337), 'sg': np.float64(242.81183150298074), 'al': np.float64(118.62494876476508), 'su': np.float64(31.525657216302243), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.91502759459745), 'bu': np.float64(49.47656866372859), 'sc': np.float64(30.634056849704766), 'sod': np.float64(37.55031341469965), 'pot': np.float64(1.9535675363810006), 'hemo': np.float64(355.5538465884311), 'pcv': np.float64(257.96415801012654), 'wc': np.float64(8.78354650671208), 'rc': np.float64(148.375106307906), 'htn': np.float64(186.51923076923075), 'dm': np.float64(161.33823529411765), 'cad': np.float64(21.044117647058826), 'appet': np.float64(49.898936170212686), 'pe': np.float64(42.99489795918368), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.06454150941437671), 'bp': np.float64(0.07575159891185307), 'sg': np.float64(0.6829115584960775), 'al': np.float64(0.33363427200403367), 'su': np.float64(0.08866633709294264), 'rbc': np.float64(0.0812440822674335), 'pc': np.float64(0.15068346882079542), 'pcc': np.float64(0.07114380785967174), 'ba': np.float64(0.031156655901074047), 'bgr': np.float64(0.16007428450205755), 'bu': np.float64(0.13915351820395253), 'sc': np.float64(0.08615869900899992), 'sod': np.float64(0.10561076409381603), 'pot': np.float64(0.005494435104909269), 'hemo': np.float64(1.0), 'pcv': np.float64(0.725527681630544), 'wc': np.float64(0.024703843288410302), 'rc': np.float64(0.41730699226454043), 'htn': np.float64(0.5245878579542828), 'dm': np.float64(0.45376596777723405), 'cad': np.float64(0.059186865362247924), 'appet': np.float64(0.14034143252561362), 'pe': np.float64(0.12092373172649748), 'ane': np.float64(0.0945978104507723)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.029437229437229435, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'bu', 'pc', 'sc', 'pe', 'appet', 'sod', 'ane', 'rbc', 'bp', 'su', 'age', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f6154f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e328770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e304ad0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet', 'bgr', 'sc', 'ane', 'sod', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e347da0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.790505467606195), 'bp': np.float64(28.960073692076723), 'sg': np.float64(264.9058898160716), 'al': np.float64(133.50412166364185), 'su': np.float64(29.095939799100616), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(52.817273355771526), 'bu': np.float64(54.069722013721766), 'sc': np.float64(27.724345048719055), 'sod': np.float64(32.22340449077808), 'pot': np.float64(1.4525058049061321), 'hemo': np.float64(377.0161535932862), 'pcv': np.float64(287.1048461754883), 'wc': np.float64(13.8686940385378), 'rc': np.float64(141.87106613423947), 'htn': np.float64(175.19444444444454), 'dm': np.float64(142.83791208791212), 'cad': np.float64(20.22368421052632), 'appet': np.float64(54.83759124087599), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.0498400540361908), 'bp': np.float64(0.0768138802968055), 'sg': np.float64(0.7026380363050548), 'al': np.float64(0.35410716594298003), 'su': np.float64(0.077174252407467), 'rbc': np.float64(0.06943158540769442), 'pc': np.float64(0.13555690484359384), 'pcc': np.float64(0.06709382158925352), 'ba': np.float64(0.03710775607450335), 'bgr': np.float64(0.14009286565675705), 'bu': np.float64(0.14341486829779332), 'sc': np.float64(0.07353622592687965), 'sod': np.float64(0.0854695592845598), 'pot': np.float64(0.0038526354668427603), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7615186867701389), 'wc': np.float64(0.03678541066836869), 'rc': np.float64(0.3762997017026643), 'htn': np.float64(0.4646868384144598), 'dm': np.float64(0.3788641699474803), 'cad': np.float64(0.053641426283137526), 'appet': np.float64(0.14545156943071766), 'pe': np.float64(0.14545156943071746), 'ane': np.float64(0.10264021713322889)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bu', 'pe', 'appet', 'bgr', 'sc', 'ane', 'sod', 'pc', 'bp', 'rbc', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd3470>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32aa20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3459a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sc', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32b530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.815802601233104), 'bp': np.float64(31.452865639986182), 'sg': np.float64(247.90205701456213), 'al': np.float64(125.37277257626096), 'su': np.float64(28.896785537055745), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(57.416666666666664), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.74172001467814), 'bu': np.float64(51.49234132416434), 'sc': np.float64(26.222076675494645), 'sod': np.float64(38.31777954995364), 'pot': np.float64(0.8949974467839343), 'hemo': np.float64(380.1316433634773), 'pcv': np.float64(267.06370332312235), 'wc': np.float64(8.97985355339011), 'rc': np.float64(159.08332005958337), 'htn': np.float64(158.0755813953489), 'dm': np.float64(134.47340425531917), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(44.10616438356164)}

Normalized Mathematical Scores
{'age': np.float64(0.028452781529926894), 'bp': np.float64(0.08274203473745366), 'sg': np.float64(0.6521479107108197), 'al': np.float64(0.32981409142090556), 'su': np.float64(0.0760178376137579), 'rbc': np.float64(0.07358561885224461), 'pc': np.float64(0.15104416501250212), 'pcc': np.float64(0.06654393283767576), 'ba': np.float64(0.029142190727506716), 'bgr': np.float64(0.13085393148161492), 'bu': np.float64(0.135459234249878), 'sc': np.float64(0.06898156765765856), 'sod': np.float64(0.10080134137455808), 'pot': np.float64(0.0023544407902084293), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7025558329216999), 'wc': np.float64(0.023623009844522945), 'rc': np.float64(0.41849533664702), 'htn': np.float64(0.4158443111882663), 'dm': np.float64(0.35375482836806965), 'cad': np.float64(0.04896006949493732), 'appet': np.float64(0.16523504369835076), 'pe': np.float64(0.1409408763829033), 'ane': np.float64(0.11602865784416652)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sc', 'bp', 'sod', 'rbc', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e313200>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.0693830122106997), 'bp': np.float64(0.07961196281417365), 'sg': np.float64(0.7490815734992863), 'al': np.float64(0.38165055726281616), 'su': np.float64(0.09332360305457571), 'rbc': np.float64(0.07904187311875141), 'pc': np.float64(0.16558406996409963), 'pcc': np.float64(0.07375125242807193), 'ba': np.float64(0.04224398060536621), 'bgr': np.float64(0.1697165966640394), 'bu': np.float64(0.15353648741696974), 'sc': np.float64(0.08028530049337625), 'sod': np.float64(0.10678221202761297), 'pot': np.float64(0.003995029049520781), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7604547730432223), 'wc': np.float64(0.034671104849668725), 'rc': np.float64(0.6006590865216419), 'htn': np.float64(0.458283183537003), 'dm': np.float64(0.4227021910263661), 'cad': np.float64(0.05380500430688953), 'appet': np.float64(0.19388903918873207), 'pe': np.float64(0.16558406996409963), 'ane': np.float64(0.11061270116182566)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.029116045245077504, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029726775956284153, 'sod': 0.0293236301369863, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.029513888888888888}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e930>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.0693830122106997), 'bp': np.float64(0.07961196281417365), 'sg': np.float64(0.7490815734992863), 'al': np.float64(0.38165055726281616), 'su': np.float64(0.09332360305457571), 'rbc': np.float64(0.07904187311875141), 'pc': np.float64(0.16558406996409963), 'pcc': np.float64(0.07375125242807193), 'ba': np.float64(0.04224398060536621), 'bgr': np.float64(0.1697165966640394), 'bu': np.float64(0.15353648741696974), 'sc': np.float64(0.08028530049337625), 'sod': np.float64(0.10678221202761297), 'pot': np.float64(0.003995029049520781), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7604547730432223), 'wc': np.float64(0.034671104849668725), 'rc': np.float64(0.6006590865216419), 'htn': np.float64(0.458283183537003), 'dm': np.float64(0.4227021910263661), 'cad': np.float64(0.05380500430688953), 'appet': np.float64(0.19388903918873207), 'pe': np.float64(0.16558406996409963), 'ane': np.float64(0.11061270116182566)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.029116045245077504, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029726775956284153, 'sod': 0.0293236301369863, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.029513888888888888}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af950>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.0693830122106997), 'bp': np.float64(0.07961196281417365), 'sg': np.float64(0.7490815734992863), 'al': np.float64(0.38165055726281616), 'su': np.float64(0.09332360305457571), 'rbc': np.float64(0.07904187311875141), 'pc': np.float64(0.16558406996409963), 'pcc': np.float64(0.07375125242807193), 'ba': np.float64(0.04224398060536621), 'bgr': np.float64(0.1697165966640394), 'bu': np.float64(0.15353648741696974), 'sc': np.float64(0.08028530049337625), 'sod': np.float64(0.10678221202761297), 'pot': np.float64(0.003995029049520781), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7604547730432223), 'wc': np.float64(0.034671104849668725), 'rc': np.float64(0.6006590865216419), 'htn': np.float64(0.458283183537003), 'dm': np.float64(0.4227021910263661), 'cad': np.float64(0.05380500430688953), 'appet': np.float64(0.19388903918873207), 'pe': np.float64(0.16558406996409963), 'ane': np.float64(0.11061270116182566)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.029116045245077504, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029726775956284153, 'sod': 0.0293236301369863, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.029513888888888888}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'ane', 'pc', 'sod']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617fb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.978039273318817), 'bp': np.float64(26.36562971084117), 'sg': np.float64(248.07838786987247), 'al': np.float64(126.39378450214686), 'su': np.float64(30.906605922551247), 'rbc': np.float64(26.17682926829269), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.990223463687153), 'bgr': np.float64(56.20618793023399), 'bu': np.float64(50.84771221867614), 'sc': np.float64(26.588623483292814), 'sod': np.float64(35.36378406592105), 'pot': np.float64(1.323060666769116), 'hemo': np.float64(331.1767324765316), 'pcv': np.float64(251.84492693263678), 'wc': np.float64(11.482263215464515), 'rc': np.float64(198.92431360657562), 'htn': np.float64(151.77272727272725), 'dm': np.float64(139.9891304347826), 'cad': np.float64(17.818965517241384), 'appet': np.float64(64.21153846153847), 'pe': np.float64(54.83759124087591), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.0693830122106997), 'bp': np.float64(0.07961196281417365), 'sg': np.float64(0.7490815734992863), 'al': np.float64(0.38165055726281616), 'su': np.float64(0.09332360305457571), 'rbc': np.float64(0.07904187311875141), 'pc': np.float64(0.16558406996409963), 'pcc': np.float64(0.07375125242807193), 'ba': np.float64(0.04224398060536621), 'bgr': np.float64(0.1697165966640394), 'bu': np.float64(0.15353648741696974), 'sc': np.float64(0.08028530049337625), 'sod': np.float64(0.10678221202761297), 'pot': np.float64(0.003995029049520781), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7604547730432223), 'wc': np.float64(0.034671104849668725), 'rc': np.float64(0.6006590865216419), 'htn': np.float64(0.458283183537003), 'dm': np.float64(0.4227021910263661), 'cad': np.float64(0.05380500430688953), 'appet': np.float64(0.19388903918873207), 'pe': np.float64(0.16558406996409963), 'ane': np.float64(0.11061270116182566)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.029116045245077504, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029726775956284153, 'sod': 0.0293236301369863, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.029513888888888888}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'ane', 'pc', 'sod', 'rbc', 'bp', 'su', 'age', 'cad']

PRIMARY: completed 5/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e307cb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.056496231612452076), 'bp': np.float64(0.07160964704781828), 'sg': np.float64(0.5942447557214509), 'al': np.float64(0.33317421914589124), 'su': np.float64(0.08306825792092609), 'rbc': np.float64(0.0773641040422154), 'pc': np.float64(0.14817792925248122), 'pcc': np.float64(0.0699608404975058), 'ba': np.float64(0.026741788452714573), 'bgr': np.float64(0.15325085982089404), 'bu': np.float64(0.14966641834535677), 'sc': np.float64(0.07794358755524604), 'sod': np.float64(0.1038639160774087), 'pot': np.float64(0.003109944190580423), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7406464971551985), 'wc': np.float64(0.023717216730770506), 'rc': np.float64(0.47586418487275434), 'htn': np.float64(0.5051602822903086), 'dm': np.float64(0.4554593493613134), 'cad': np.float64(0.05147407835117892), 'appet': np.float64(0.16614760294305625), 'pe': np.float64(0.15520724278438258), 'ane': np.float64(0.10993846363893768)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22f7d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.056496231612452076), 'bp': np.float64(0.07160964704781828), 'sg': np.float64(0.5942447557214509), 'al': np.float64(0.33317421914589124), 'su': np.float64(0.08306825792092609), 'rbc': np.float64(0.0773641040422154), 'pc': np.float64(0.14817792925248122), 'pcc': np.float64(0.0699608404975058), 'ba': np.float64(0.026741788452714573), 'bgr': np.float64(0.15325085982089404), 'bu': np.float64(0.14966641834535677), 'sc': np.float64(0.07794358755524604), 'sod': np.float64(0.1038639160774087), 'pot': np.float64(0.003109944190580423), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7406464971551985), 'wc': np.float64(0.023717216730770506), 'rc': np.float64(0.47586418487275434), 'htn': np.float64(0.5051602822903086), 'dm': np.float64(0.4554593493613134), 'cad': np.float64(0.05147407835117892), 'appet': np.float64(0.16614760294305625), 'pe': np.float64(0.15520724278438258), 'ane': np.float64(0.10993846363893768)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bu', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30a0c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.056496231612452076), 'bp': np.float64(0.07160964704781828), 'sg': np.float64(0.5942447557214509), 'al': np.float64(0.33317421914589124), 'su': np.float64(0.08306825792092609), 'rbc': np.float64(0.0773641040422154), 'pc': np.float64(0.14817792925248122), 'pcc': np.float64(0.0699608404975058), 'ba': np.float64(0.026741788452714573), 'bgr': np.float64(0.15325085982089404), 'bu': np.float64(0.14966641834535677), 'sc': np.float64(0.07794358755524604), 'sod': np.float64(0.1038639160774087), 'pot': np.float64(0.003109944190580423), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7406464971551985), 'wc': np.float64(0.023717216730770506), 'rc': np.float64(0.47586418487275434), 'htn': np.float64(0.5051602822903086), 'dm': np.float64(0.4554593493613134), 'cad': np.float64(0.05147407835117892), 'appet': np.float64(0.16614760294305625), 'pe': np.float64(0.15520724278438258), 'ane': np.float64(0.10993846363893768)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bu', 'bgr', 'appet', 'sc', 'ane', 'sod', 'rbc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e325850>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.42711106069692), 'bp': np.float64(25.891606776489617), 'sg': np.float64(214.85864235382653), 'al': np.float64(120.46443776533339), 'su': np.float64(30.034649776453055), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(55.41028568388134), 'bu': np.float64(54.11427386111704), 'sc': np.float64(28.181743702517032), 'sod': np.float64(37.55365071897133), 'pot': np.float64(1.1244497829401023), 'hemo': np.float64(361.56590409110885), 'pcv': np.float64(267.7925203558322), 'wc': np.float64(8.575336909785811), 'rc': np.float64(172.05626422809598), 'htn': np.float64(182.6487341772152), 'dm': np.float64(164.67857142857147), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(56.11764705882352), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.056496231612452076), 'bp': np.float64(0.07160964704781828), 'sg': np.float64(0.5942447557214509), 'al': np.float64(0.33317421914589124), 'su': np.float64(0.08306825792092609), 'rbc': np.float64(0.0773641040422154), 'pc': np.float64(0.14817792925248122), 'pcc': np.float64(0.0699608404975058), 'ba': np.float64(0.026741788452714573), 'bgr': np.float64(0.15325085982089404), 'bu': np.float64(0.14966641834535677), 'sc': np.float64(0.07794358755524604), 'sod': np.float64(0.1038639160774087), 'pot': np.float64(0.003109944190580423), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7406464971551985), 'wc': np.float64(0.023717216730770506), 'rc': np.float64(0.47586418487275434), 'htn': np.float64(0.5051602822903086), 'dm': np.float64(0.4554593493613134), 'cad': np.float64(0.05147407835117892), 'appet': np.float64(0.16614760294305625), 'pe': np.float64(0.15520724278438258), 'ane': np.float64(0.10993846363893768)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bu', 'bgr', 'appet', 'sc', 'ane', 'sod', 'rbc', 'pc', 'bp', 'su', 'age', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3398b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.05463061853504088), 'bp': np.float64(0.0913851258105834), 'sg': np.float64(0.7320604018193563), 'al': np.float64(0.39751810886640115), 'su': np.float64(0.09540778591975999), 'rbc': np.float64(0.08745398395060824), 'pc': np.float64(0.16461926390702725), 'pcc': np.float64(0.07678886395663165), 'ba': np.float64(0.03886843731138144), 'bgr': np.float64(0.1694773499249699), 'bu': np.float64(0.15069498866061454), 'sc': np.float64(0.12420552013782471), 'sod': np.float64(0.23136963967143684), 'pot': np.float64(0.004467651807325386), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7802038049869978), 'wc': np.float64(0.03424311356516593), 'rc': np.float64(0.45557590420562866), 'htn': np.float64(0.5033936637156964), 'dm': np.float64(0.40247639925656253), 'cad': np.float64(0.06173222396513524), 'appet': np.float64(0.21899046387631962), 'pe': np.float64(0.15716368130254232), 'ane': np.float64(0.11660531193414432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029571646010002173, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3042c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.05463061853504088), 'bp': np.float64(0.0913851258105834), 'sg': np.float64(0.7320604018193563), 'al': np.float64(0.39751810886640115), 'su': np.float64(0.09540778591975999), 'rbc': np.float64(0.08745398395060824), 'pc': np.float64(0.16461926390702725), 'pcc': np.float64(0.07678886395663165), 'ba': np.float64(0.03886843731138144), 'bgr': np.float64(0.1694773499249699), 'bu': np.float64(0.15069498866061454), 'sc': np.float64(0.12420552013782471), 'sod': np.float64(0.23136963967143684), 'pot': np.float64(0.004467651807325386), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7802038049869978), 'wc': np.float64(0.03424311356516593), 'rc': np.float64(0.45557590420562866), 'htn': np.float64(0.5033936637156964), 'dm': np.float64(0.40247639925656253), 'cad': np.float64(0.06173222396513524), 'appet': np.float64(0.21899046387631962), 'pe': np.float64(0.15716368130254232), 'ane': np.float64(0.11660531193414432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029571646010002173, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'sod', 'bgr', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6667617ec0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.05463061853504088), 'bp': np.float64(0.0913851258105834), 'sg': np.float64(0.7320604018193563), 'al': np.float64(0.39751810886640115), 'su': np.float64(0.09540778591975999), 'rbc': np.float64(0.08745398395060824), 'pc': np.float64(0.16461926390702725), 'pcc': np.float64(0.07678886395663165), 'ba': np.float64(0.03886843731138144), 'bgr': np.float64(0.1694773499249699), 'bu': np.float64(0.15069498866061454), 'sc': np.float64(0.12420552013782471), 'sod': np.float64(0.23136963967143684), 'pot': np.float64(0.004467651807325386), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7802038049869978), 'wc': np.float64(0.03424311356516593), 'rc': np.float64(0.45557590420562866), 'htn': np.float64(0.5033936637156964), 'dm': np.float64(0.40247639925656253), 'cad': np.float64(0.06173222396513524), 'appet': np.float64(0.21899046387631962), 'pe': np.float64(0.15716368130254232), 'ane': np.float64(0.11660531193414432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029571646010002173, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'sod', 'bgr', 'sc', 'appet', 'bu', 'pe', 'pc', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6667325400>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.62322608419692), 'bp': np.float64(31.152600946878525), 'sg': np.float64(249.55467713815648), 'al': np.float64(135.51136363636365), 'su': np.float64(32.52389987561067), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(13.25), 'bgr': np.float64(57.7737373004266), 'bu': np.float64(51.37095128772947), 'sc': np.float64(42.340862037802516), 'sod': np.float64(78.87242034165486), 'pot': np.float64(1.5229937332656154), 'hemo': np.float64(340.89356085638514), 'pcv': np.float64(265.9664532757184), 'wc': np.float64(11.673256918038998), 'rc': np.float64(155.30289222502415), 'htn': np.float64(171.6036585365854), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(74.65243902439018), 'pe': np.float64(53.576086956521735), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.05463061853504088), 'bp': np.float64(0.0913851258105834), 'sg': np.float64(0.7320604018193563), 'al': np.float64(0.39751810886640115), 'su': np.float64(0.09540778591975999), 'rbc': np.float64(0.08745398395060824), 'pc': np.float64(0.16461926390702725), 'pcc': np.float64(0.07678886395663165), 'ba': np.float64(0.03886843731138144), 'bgr': np.float64(0.1694773499249699), 'bu': np.float64(0.15069498866061454), 'sc': np.float64(0.12420552013782471), 'sod': np.float64(0.23136963967143684), 'pot': np.float64(0.004467651807325386), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7802038049869978), 'wc': np.float64(0.03424311356516593), 'rc': np.float64(0.45557590420562866), 'htn': np.float64(0.5033936637156964), 'dm': np.float64(0.40247639925656253), 'cad': np.float64(0.06173222396513524), 'appet': np.float64(0.21899046387631962), 'pe': np.float64(0.15716368130254232), 'ane': np.float64(0.11660531193414432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029571646010002173, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'sod', 'bgr', 'sc', 'appet', 'bu', 'pe', 'pc', 'ane', 'rbc', 'bp', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e339610>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.041952468560767515), 'bp': np.float64(0.07402781093779534), 'sg': np.float64(0.7627787720374549), 'al': np.float64(0.3545791763558416), 'su': np.float64(0.08654084423942017), 'rbc': np.float64(0.0684670066861167), 'pc': np.float64(0.13987606664243366), 'pcc': np.float64(0.07841137948003342), 'ba': np.float64(0.03306066838689669), 'bgr': np.float64(0.13451252425673182), 'bu': np.float64(0.1384652422341608), 'sc': np.float64(0.07538391049241126), 'sod': np.float64(0.10016070152536205), 'pot': np.float64(0.0026367028554736974), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7534971865777158), 'wc': np.float64(0.03350032621313557), 'rc': np.float64(0.3778231955833093), 'htn': np.float64(0.42544738914046837), 'dm': np.float64(0.36946746951672255), 'cad': np.float64(0.047754298781072985), 'appet': np.float64(0.1466984574066057), 'pe': np.float64(0.1267958967635386), 'ane': np.float64(0.09984989745133444)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.028309409888357256, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e3f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.041952468560767515), 'bp': np.float64(0.07402781093779534), 'sg': np.float64(0.7627787720374549), 'al': np.float64(0.3545791763558416), 'su': np.float64(0.08654084423942017), 'rbc': np.float64(0.0684670066861167), 'pc': np.float64(0.13987606664243366), 'pcc': np.float64(0.07841137948003342), 'ba': np.float64(0.03306066838689669), 'bgr': np.float64(0.13451252425673182), 'bu': np.float64(0.1384652422341608), 'sc': np.float64(0.07538391049241126), 'sod': np.float64(0.10016070152536205), 'pot': np.float64(0.0026367028554736974), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7534971865777158), 'wc': np.float64(0.03350032621313557), 'rc': np.float64(0.3778231955833093), 'htn': np.float64(0.42544738914046837), 'dm': np.float64(0.36946746951672255), 'cad': np.float64(0.047754298781072985), 'appet': np.float64(0.1466984574066057), 'pe': np.float64(0.1267958967635386), 'ane': np.float64(0.09984989745133444)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.028309409888357256, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'appet', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f614fe0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.041952468560767515), 'bp': np.float64(0.07402781093779534), 'sg': np.float64(0.7627787720374549), 'al': np.float64(0.3545791763558416), 'su': np.float64(0.08654084423942017), 'rbc': np.float64(0.0684670066861167), 'pc': np.float64(0.13987606664243366), 'pcc': np.float64(0.07841137948003342), 'ba': np.float64(0.03306066838689669), 'bgr': np.float64(0.13451252425673182), 'bu': np.float64(0.1384652422341608), 'sc': np.float64(0.07538391049241126), 'sod': np.float64(0.10016070152536205), 'pot': np.float64(0.0026367028554736974), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7534971865777158), 'wc': np.float64(0.03350032621313557), 'rc': np.float64(0.3778231955833093), 'htn': np.float64(0.42544738914046837), 'dm': np.float64(0.36946746951672255), 'cad': np.float64(0.047754298781072985), 'appet': np.float64(0.1466984574066057), 'pe': np.float64(0.1267958967635386), 'ane': np.float64(0.09984989745133444)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.028309409888357256, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'appet', 'bgr', 'pc', 'pe', 'sc', 'sod', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e328a10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.96598811466389), 'bp': np.float64(26.40844214077308), 'sg': np.float64(272.1112351206448), 'al': np.float64(126.49142997061703), 'su': np.float64(30.87230121975083), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(47.98556338547095), 'bu': np.float64(49.39564322821329), 'sc': np.float64(26.89221271525752), 'sod': np.float64(35.73100511150331), 'pot': np.float64(0.9406088592799071), 'hemo': np.float64(356.7367696846226), 'pcv': np.float64(268.8001523061857), 'wc': np.float64(11.950798156655068), 'rc': np.float64(134.78342630431112), 'htn': np.float64(151.77272727272725), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(45.23275862068965), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.041952468560767515), 'bp': np.float64(0.07402781093779534), 'sg': np.float64(0.7627787720374549), 'al': np.float64(0.3545791763558416), 'su': np.float64(0.08654084423942017), 'rbc': np.float64(0.0684670066861167), 'pc': np.float64(0.13987606664243366), 'pcc': np.float64(0.07841137948003342), 'ba': np.float64(0.03306066838689669), 'bgr': np.float64(0.13451252425673182), 'bu': np.float64(0.1384652422341608), 'sc': np.float64(0.07538391049241126), 'sod': np.float64(0.10016070152536205), 'pot': np.float64(0.0026367028554736974), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7534971865777158), 'wc': np.float64(0.03350032621313557), 'rc': np.float64(0.3778231955833093), 'htn': np.float64(0.42544738914046837), 'dm': np.float64(0.36946746951672255), 'cad': np.float64(0.047754298781072985), 'appet': np.float64(0.1466984574066057), 'pe': np.float64(0.1267958967635386), 'ane': np.float64(0.09984989745133444)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.028309409888357256, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.02938045560996381, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'appet', 'bgr', 'pc', 'pe', 'sc', 'sod', 'ane', 'rbc', 'bp', 'su', 'pcc', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e312ed0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}

Normalized Mathematical Scores
{'age': np.float64(0.02671534271309483), 'bp': np.float64(0.07932970228486894), 'sg': np.float64(0.7493397995986926), 'al': np.float64(0.33279111930864397), 'su': np.float64(0.07654000464535245), 'rbc': np.float64(0.07646901003010413), 'pc': np.float64(0.12677756926043576), 'pcc': np.float64(0.05306968015553125), 'ba': np.float64(0.02643238895777426), 'bgr': np.float64(0.13915758360843425), 'bu': np.float64(0.14118802226254684), 'sc': np.float64(0.08085743975408945), 'sod': np.float64(0.09169240714001262), 'pot': np.float64(0.002839138019017178), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7059823743535876), 'wc': np.float64(0.02898728345576464), 'rc': np.float64(0.4315732160982903), 'htn': np.float64(0.4595414128441956), 'dm': np.float64(0.3676164166396832), 'cad': np.float64(0.04657135197322131), 'appet': np.float64(0.14306451289615488), 'pe': np.float64(0.13971405591966396), 'ane': np.float64(0.09464500562299814)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029030910609857977, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.029726775956284153, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32b590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}

Normalized Mathematical Scores
{'age': np.float64(0.02671534271309483), 'bp': np.float64(0.07932970228486894), 'sg': np.float64(0.7493397995986926), 'al': np.float64(0.33279111930864397), 'su': np.float64(0.07654000464535245), 'rbc': np.float64(0.07646901003010413), 'pc': np.float64(0.12677756926043576), 'pcc': np.float64(0.05306968015553125), 'ba': np.float64(0.02643238895777426), 'bgr': np.float64(0.13915758360843425), 'bu': np.float64(0.14118802226254684), 'sc': np.float64(0.08085743975408945), 'sod': np.float64(0.09169240714001262), 'pot': np.float64(0.002839138019017178), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7059823743535876), 'wc': np.float64(0.02898728345576464), 'rc': np.float64(0.4315732160982903), 'htn': np.float64(0.4595414128441956), 'dm': np.float64(0.3676164166396832), 'cad': np.float64(0.04657135197322131), 'appet': np.float64(0.14306451289615488), 'pe': np.float64(0.13971405591966396), 'ane': np.float64(0.09464500562299814)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029030910609857977, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.029726775956284153, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e325a90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}

Normalized Mathematical Scores
{'age': np.float64(0.02671534271309483), 'bp': np.float64(0.07932970228486894), 'sg': np.float64(0.7493397995986926), 'al': np.float64(0.33279111930864397), 'su': np.float64(0.07654000464535245), 'rbc': np.float64(0.07646901003010413), 'pc': np.float64(0.12677756926043576), 'pcc': np.float64(0.05306968015553125), 'ba': np.float64(0.02643238895777426), 'bgr': np.float64(0.13915758360843425), 'bu': np.float64(0.14118802226254684), 'sc': np.float64(0.08085743975408945), 'sod': np.float64(0.09169240714001262), 'pot': np.float64(0.002839138019017178), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7059823743535876), 'wc': np.float64(0.02898728345576464), 'rc': np.float64(0.4315732160982903), 'htn': np.float64(0.4595414128441956), 'dm': np.float64(0.3676164166396832), 'cad': np.float64(0.04657135197322131), 'appet': np.float64(0.14306451289615488), 'pe': np.float64(0.13971405591966396), 'ane': np.float64(0.09464500562299814)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029030910609857977, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.029726775956284153, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'pe', 'appet', 'sc', 'bgr', 'ane', 'sod', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310ad0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.772422878487944), 'bp': np.float64(29.01865815003362), 'sg': np.float64(274.10711065931594), 'al': np.float64(121.734375), 'su': np.float64(27.99819192097372), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(46.374999999999986), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(50.9035863164723), 'bu': np.float64(51.64631701507906), 'sc': np.float64(29.577501686381588), 'sod': np.float64(33.54091268608275), 'pot': np.float64(1.0385514283007404), 'hemo': np.float64(365.798147657596), 'pcv': np.float64(258.24704481745385), 'wc': np.float64(10.603494593744385), 'rc': np.float64(157.868683027386), 'htn': np.float64(168.09939759036135), 'dm': np.float64(134.47340425531917), 'cad': np.float64(17.035714285714285), 'appet': np.float64(52.33273381294971), 'pe': np.float64(51.10714285714286), 'ane': np.float64(34.62096774193548)}

Normalized Mathematical Scores
{'age': np.float64(0.02671534271309483), 'bp': np.float64(0.07932970228486894), 'sg': np.float64(0.7493397995986926), 'al': np.float64(0.33279111930864397), 'su': np.float64(0.07654000464535245), 'rbc': np.float64(0.07646901003010413), 'pc': np.float64(0.12677756926043576), 'pcc': np.float64(0.05306968015553125), 'ba': np.float64(0.02643238895777426), 'bgr': np.float64(0.13915758360843425), 'bu': np.float64(0.14118802226254684), 'sc': np.float64(0.08085743975408945), 'sod': np.float64(0.09169240714001262), 'pot': np.float64(0.002839138019017178), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7059823743535876), 'wc': np.float64(0.02898728345576464), 'rc': np.float64(0.4315732160982903), 'htn': np.float64(0.4595414128441956), 'dm': np.float64(0.3676164166396832), 'cad': np.float64(0.04657135197322131), 'appet': np.float64(0.14306451289615488), 'pe': np.float64(0.13971405591966396), 'ane': np.float64(0.09464500562299814)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029030910609857977, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.029726775956284153, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bu', 'pe', 'appet', 'sc', 'bgr', 'ane', 'sod', 'pc', 'bp', 'rbc', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f614c20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.07486800902870092), 'bp': np.float64(0.11407423241271406), 'sg': np.float64(0.6441668792729464), 'al': np.float64(0.3581513559442369), 'su': np.float64(0.0878267416937289), 'rbc': np.float64(0.08155404307260754), 'pc': np.float64(0.159881014905692), 'pcc': np.float64(0.06377521088611571), 'ba': np.float64(0.038630862508077256), 'bgr': np.float64(0.1639500479378303), 'bu': np.float64(0.13332468861524024), 'sc': np.float64(0.07888535668738925), 'sod': np.float64(0.10664112855839986), 'pot': np.float64(0.006080600648095142), 'hemo': np.float64(1.0), 'pcv': np.float64(0.720399510711194), 'wc': np.float64(0.02919067798878091), 'rc': np.float64(0.4491359614460918), 'htn': np.float64(0.521516643859043), 'dm': np.float64(0.4608751736428754), 'cad': np.float64(0.0589628954070653), 'appet': np.float64(0.15620305275005172), 'pe': np.float64(0.159881014905692), 'ane': np.float64(0.11282258520570908)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02844551282051282, 'bp': 0.02976190476190476, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35ffb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.07486800902870092), 'bp': np.float64(0.11407423241271406), 'sg': np.float64(0.6441668792729464), 'al': np.float64(0.3581513559442369), 'su': np.float64(0.0878267416937289), 'rbc': np.float64(0.08155404307260754), 'pc': np.float64(0.159881014905692), 'pcc': np.float64(0.06377521088611571), 'ba': np.float64(0.038630862508077256), 'bgr': np.float64(0.1639500479378303), 'bu': np.float64(0.13332468861524024), 'sc': np.float64(0.07888535668738925), 'sod': np.float64(0.10664112855839986), 'pot': np.float64(0.006080600648095142), 'hemo': np.float64(1.0), 'pcv': np.float64(0.720399510711194), 'wc': np.float64(0.02919067798878091), 'rc': np.float64(0.4491359614460918), 'htn': np.float64(0.521516643859043), 'dm': np.float64(0.4608751736428754), 'cad': np.float64(0.0589628954070653), 'appet': np.float64(0.15620305275005172), 'pe': np.float64(0.159881014905692), 'ane': np.float64(0.11282258520570908)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02844551282051282, 'bp': 0.02976190476190476, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'pe', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e328fb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.07486800902870092), 'bp': np.float64(0.11407423241271406), 'sg': np.float64(0.6441668792729464), 'al': np.float64(0.3581513559442369), 'su': np.float64(0.0878267416937289), 'rbc': np.float64(0.08155404307260754), 'pc': np.float64(0.159881014905692), 'pcc': np.float64(0.06377521088611571), 'ba': np.float64(0.038630862508077256), 'bgr': np.float64(0.1639500479378303), 'bu': np.float64(0.13332468861524024), 'sc': np.float64(0.07888535668738925), 'sod': np.float64(0.10664112855839986), 'pot': np.float64(0.006080600648095142), 'hemo': np.float64(1.0), 'pcv': np.float64(0.720399510711194), 'wc': np.float64(0.02919067798878091), 'rc': np.float64(0.4491359614460918), 'htn': np.float64(0.521516643859043), 'dm': np.float64(0.4608751736428754), 'cad': np.float64(0.0589628954070653), 'appet': np.float64(0.15620305275005172), 'pe': np.float64(0.159881014905692), 'ane': np.float64(0.11282258520570908)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02844551282051282, 'bp': 0.02976190476190476, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'pe', 'bu', 'bp', 'pc', 'appet', 'sc', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f66672fd4f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(25.67897932444225), 'bp': np.float64(39.12632235825508), 'sg': np.float64(220.94280573160714), 'al': np.float64(122.84233791748527), 'su': np.float64(30.12369519832986), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(13.25), 'bgr': np.float64(56.23322892990135), 'bu': np.float64(45.729036564549084), 'sc': np.float64(27.056889446601456), 'sod': np.float64(36.57684197714606), 'pot': np.float64(2.0855852900104113), 'hemo': np.float64(342.9900121238448), 'pcv': np.float64(247.0898369128443), 'wc': np.float64(10.012110997275213), 'rc': np.float64(154.0491488616497), 'htn': np.float64(178.875), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(53.57608695652181), 'pe': np.float64(54.83759124087591), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.07486800902870092), 'bp': np.float64(0.11407423241271406), 'sg': np.float64(0.6441668792729464), 'al': np.float64(0.3581513559442369), 'su': np.float64(0.0878267416937289), 'rbc': np.float64(0.08155404307260754), 'pc': np.float64(0.159881014905692), 'pcc': np.float64(0.06377521088611571), 'ba': np.float64(0.038630862508077256), 'bgr': np.float64(0.1639500479378303), 'bu': np.float64(0.13332468861524024), 'sc': np.float64(0.07888535668738925), 'sod': np.float64(0.10664112855839986), 'pot': np.float64(0.006080600648095142), 'hemo': np.float64(1.0), 'pcv': np.float64(0.720399510711194), 'wc': np.float64(0.02919067798878091), 'rc': np.float64(0.4491359614460918), 'htn': np.float64(0.521516643859043), 'dm': np.float64(0.4608751736428754), 'cad': np.float64(0.0589628954070653), 'appet': np.float64(0.15620305275005172), 'pe': np.float64(0.159881014905692), 'ane': np.float64(0.11282258520570908)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02844551282051282, 'bp': 0.02976190476190476, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.027271052146674038, 'bgr': 0.030330882352941176, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'bgr', 'pe', 'bu', 'bp', 'pc', 'appet', 'sc', 'ane', 'rbc', 'sod', 'su', 'age', 'cad']

PRIMARY: completed 10/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb6e70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.042199826361934915), 'bp': np.float64(0.09400192650969165), 'sg': np.float64(0.7927455571753808), 'al': np.float64(0.368455361192023), 'su': np.float64(0.08558170469610707), 'rbc': np.float64(0.0865992278162939), 'pc': np.float64(0.15079435592325754), 'pcc': np.float64(0.06515050266055548), 'ba': np.float64(0.036512919073498136), 'bgr': np.float64(0.16860765401896674), 'bu': np.float64(0.16362996987320283), 'sc': np.float64(0.08526243806763457), 'sod': np.float64(0.10746848496025915), 'pot': np.float64(0.004437935495821685), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7323291554312453), 'wc': np.float64(0.033554613305401076), 'rc': np.float64(0.4722057966894789), 'htn': np.float64(0.49948718706425865), 'dm': np.float64(0.4512275554638472), 'cad': np.float64(0.055165751294953116), 'appet': np.float64(0.1818379701122964), 'pe': np.float64(0.1777563097281822), 'ane': np.float64(0.10412943587627241)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22f320>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.042199826361934915), 'bp': np.float64(0.09400192650969165), 'sg': np.float64(0.7927455571753808), 'al': np.float64(0.368455361192023), 'su': np.float64(0.08558170469610707), 'rbc': np.float64(0.0865992278162939), 'pc': np.float64(0.15079435592325754), 'pcc': np.float64(0.06515050266055548), 'ba': np.float64(0.036512919073498136), 'bgr': np.float64(0.16860765401896674), 'bu': np.float64(0.16362996987320283), 'sc': np.float64(0.08526243806763457), 'sod': np.float64(0.10746848496025915), 'pot': np.float64(0.004437935495821685), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7323291554312453), 'wc': np.float64(0.033554613305401076), 'rc': np.float64(0.4722057966894789), 'htn': np.float64(0.49948718706425865), 'dm': np.float64(0.4512275554638472), 'cad': np.float64(0.055165751294953116), 'appet': np.float64(0.1818379701122964), 'pe': np.float64(0.1777563097281822), 'ane': np.float64(0.10412943587627241)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'pe', 'bu', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e33b260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.042199826361934915), 'bp': np.float64(0.09400192650969165), 'sg': np.float64(0.7927455571753808), 'al': np.float64(0.368455361192023), 'su': np.float64(0.08558170469610707), 'rbc': np.float64(0.0865992278162939), 'pc': np.float64(0.15079435592325754), 'pcc': np.float64(0.06515050266055548), 'ba': np.float64(0.036512919073498136), 'bgr': np.float64(0.16860765401896674), 'bu': np.float64(0.16362996987320283), 'sc': np.float64(0.08526243806763457), 'sod': np.float64(0.10746848496025915), 'pot': np.float64(0.004437935495821685), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7323291554312453), 'wc': np.float64(0.033554613305401076), 'rc': np.float64(0.4722057966894789), 'htn': np.float64(0.49948718706425865), 'dm': np.float64(0.4512275554638472), 'cad': np.float64(0.055165751294953116), 'appet': np.float64(0.1818379701122964), 'pe': np.float64(0.1777563097281822), 'ane': np.float64(0.10412943587627241)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'pe', 'bu', 'bgr', 'appet', 'sod', 'rbc', 'sc', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310fe0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.630871204063265), 'bp': np.float64(30.36335131329381), 'sg': np.float64(256.06296326370773), 'al': np.float64(119.01393929396238), 'su': np.float64(27.643554362798657), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(54.46157991836858), 'bu': np.float64(52.853749333866034), 'sc': np.float64(27.540428765666114), 'sod': np.float64(34.71315413540331), 'pot': np.float64(1.4334875844430457), 'hemo': np.float64(323.00775569916993), 'pcv': np.float64(236.54799692891515), 'wc': np.float64(10.838400337131107), 'rc': np.float64(152.5261346168071), 'htn': np.float64(161.33823529411765), 'dm': np.float64(145.75), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.042199826361934915), 'bp': np.float64(0.09400192650969165), 'sg': np.float64(0.7927455571753808), 'al': np.float64(0.368455361192023), 'su': np.float64(0.08558170469610707), 'rbc': np.float64(0.0865992278162939), 'pc': np.float64(0.15079435592325754), 'pcc': np.float64(0.06515050266055548), 'ba': np.float64(0.036512919073498136), 'bgr': np.float64(0.16860765401896674), 'bu': np.float64(0.16362996987320283), 'sc': np.float64(0.08526243806763457), 'sod': np.float64(0.10746848496025915), 'pot': np.float64(0.004437935495821685), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7323291554312453), 'wc': np.float64(0.033554613305401076), 'rc': np.float64(0.4722057966894789), 'htn': np.float64(0.49948718706425865), 'dm': np.float64(0.4512275554638472), 'cad': np.float64(0.055165751294953116), 'appet': np.float64(0.1818379701122964), 'pe': np.float64(0.1777563097281822), 'ane': np.float64(0.10412943587627241)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'pe', 'bu', 'bgr', 'appet', 'sod', 'rbc', 'sc', 'bp', 'ane', 'pc', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd1550>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.06642260880594358), 'bp': np.float64(0.0837353477266576), 'sg': np.float64(0.7370090545195246), 'al': np.float64(0.391270587870701), 'su': np.float64(0.09536871259936801), 'rbc': np.float64(0.08980447254983023), 'pc': np.float64(0.16904371303497454), 'pcc': np.float64(0.0870155137749908), 'ba': np.float64(0.035527044085647136), 'bgr': np.float64(0.17226116099667094), 'bu': np.float64(0.1507054884261271), 'sc': np.float64(0.08605304364586153), 'sod': np.float64(0.11734480613215331), 'pot': np.float64(0.003536204247882121), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6563601133539506), 'wc': np.float64(0.02265546716759715), 'rc': np.float64(0.485064496884727), 'htn': np.float64(0.5063673873894039), 'dm': np.float64(0.4480133237317373), 'cad': np.float64(0.056062907718969164), 'appet': np.float64(0.18095938829589855), 'pe': np.float64(0.15764238346876674), 'ane': np.float64(0.11034797934227505)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6682d1b3e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.06642260880594358), 'bp': np.float64(0.0837353477266576), 'sg': np.float64(0.7370090545195246), 'al': np.float64(0.391270587870701), 'su': np.float64(0.09536871259936801), 'rbc': np.float64(0.08980447254983023), 'pc': np.float64(0.16904371303497454), 'pcc': np.float64(0.0870155137749908), 'ba': np.float64(0.035527044085647136), 'bgr': np.float64(0.17226116099667094), 'bu': np.float64(0.1507054884261271), 'sc': np.float64(0.08605304364586153), 'sod': np.float64(0.11734480613215331), 'pot': np.float64(0.003536204247882121), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6563601133539506), 'wc': np.float64(0.02265546716759715), 'rc': np.float64(0.485064496884727), 'htn': np.float64(0.5063673873894039), 'dm': np.float64(0.4480133237317373), 'cad': np.float64(0.056062907718969164), 'appet': np.float64(0.18095938829589855), 'pe': np.float64(0.15764238346876674), 'ane': np.float64(0.11034797934227505)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'appet', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ae3c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.06642260880594358), 'bp': np.float64(0.0837353477266576), 'sg': np.float64(0.7370090545195246), 'al': np.float64(0.391270587870701), 'su': np.float64(0.09536871259936801), 'rbc': np.float64(0.08980447254983023), 'pc': np.float64(0.16904371303497454), 'pcc': np.float64(0.0870155137749908), 'ba': np.float64(0.035527044085647136), 'bgr': np.float64(0.17226116099667094), 'bu': np.float64(0.1507054884261271), 'sc': np.float64(0.08605304364586153), 'sod': np.float64(0.11734480613215331), 'pot': np.float64(0.003536204247882121), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6563601133539506), 'wc': np.float64(0.02265546716759715), 'rc': np.float64(0.485064496884727), 'htn': np.float64(0.5063673873894039), 'dm': np.float64(0.4480133237317373), 'cad': np.float64(0.056062907718969164), 'appet': np.float64(0.18095938829589855), 'pe': np.float64(0.15764238346876674), 'ane': np.float64(0.11034797934227505)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'appet', 'bu', 'pe', 'pc', 'sod', 'rbc', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32bcb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(22.050394248776605), 'bp': np.float64(27.797725249327783), 'sg': np.float64(244.66579240439916), 'al': np.float64(129.89057303825038), 'su': np.float64(31.65966753817356), 'rbc': np.float64(29.8125), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(28.886645962732924), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(57.185747172710954), 'bu': np.float64(50.02988432687374), 'sc': np.float64(28.567133583115695), 'sod': np.float64(38.95509804229048), 'pot': np.float64(1.1739180259812687), 'hemo': np.float64(331.9712165054786), 'pcv': np.float64(217.8926652957848), 'wc': np.float64(7.520962996127156), 'rc': np.float64(161.02745111444077), 'htn': np.float64(168.09939759036135), 'dm': np.float64(148.72752808988764), 'cad': np.float64(18.61127167630058), 'appet': np.float64(60.07330827067671), 'pe': np.float64(52.33273381294964), 'ane': np.float64(36.63235294117647)}

Normalized Mathematical Scores
{'age': np.float64(0.06642260880594358), 'bp': np.float64(0.0837353477266576), 'sg': np.float64(0.7370090545195246), 'al': np.float64(0.391270587870701), 'su': np.float64(0.09536871259936801), 'rbc': np.float64(0.08980447254983023), 'pc': np.float64(0.16904371303497454), 'pcc': np.float64(0.0870155137749908), 'ba': np.float64(0.035527044085647136), 'bgr': np.float64(0.17226116099667094), 'bu': np.float64(0.1507054884261271), 'sc': np.float64(0.08605304364586153), 'sod': np.float64(0.11734480613215331), 'pot': np.float64(0.003536204247882121), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6563601133539506), 'wc': np.float64(0.02265546716759715), 'rc': np.float64(0.485064496884727), 'htn': np.float64(0.5063673873894039), 'dm': np.float64(0.4480133237317373), 'cad': np.float64(0.056062907718969164), 'appet': np.float64(0.18095938829589855), 'pe': np.float64(0.15764238346876674), 'ane': np.float64(0.11034797934227505)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'appet', 'bu', 'pe', 'pc', 'sod', 'rbc', 'sc', 'ane', 'bp', 'su', 'pcc', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e660>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e309250>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'ane', 'pc', 'sc', 'sod']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e309ca0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.200503406752745), 'bp': np.float64(27.47020818377602), 'sg': np.float64(241.50039331167895), 'al': np.float64(121.23773701156738), 'su': np.float64(27.876623376623378), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(48.707746478873254), 'pcc': np.float64(21.044117647058826), 'ba': np.float64(9.66891891891892), 'bgr': np.float64(53.31151146370995), 'bu': np.float64(47.83904006789586), 'sc': np.float64(26.28670598808899), 'sod': np.float64(38.49591722560613), 'pot': np.float64(0.7883780481406805), 'hemo': np.float64(354.0387122455604), 'pcv': np.float64(253.2636122326403), 'wc': np.float64(14.18235543364434), 'rc': np.float64(159.62231012347294), 'htn': np.float64(182.6487341772152), 'dm': np.float64(142.83791208791212), 'cad': np.float64(18.61127167630058), 'appet': np.float64(62.81106870229006), 'pe': np.float64(53.576086956521735), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.05140822960097346), 'bp': np.float64(0.07759097305924768), 'sg': np.float64(0.6821299054555786), 'al': np.float64(0.3424420347780419), 'su': np.float64(0.07873891304092254), 'rbc': np.float64(0.07645779251996875), 'pc': np.float64(0.1375774591708764), 'pcc': np.float64(0.05944015984461799), 'ba': np.float64(0.02731034371239205), 'bgr': np.float64(0.15058102297788611), 'bu': np.float64(0.13512375458736506), 'sc': np.float64(0.07424811208175616), 'sod': np.float64(0.10873363814210647), 'pot': np.float64(0.0022268131163968963), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7153557039744773), 'wc': np.float64(0.04005877025054676), 'rc': np.float64(0.4508611759178451), 'htn': np.float64(0.51590045907333), 'dm': np.float64(0.4034528065643852), 'cad': np.float64(0.05256846506489337), 'appet': np.float64(0.17741299617744755), 'pe': np.float64(0.15132832965272308), 'ane': np.float64(0.10930166258403264)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'ane', 'pc', 'sc', 'sod', 'rbc', 'bp', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f616570>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34d9d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd15b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'sc', 'ane', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f614110>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.238582074320888), 'bp': np.float64(32.223206308274), 'sg': np.float64(241.42814152913004), 'al': np.float64(131.9976333802612), 'su': np.float64(28.80404802616907), 'rbc': np.float64(24.424698795180728), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(49.763225467006286), 'bu': np.float64(52.00828747927983), 'sc': np.float64(27.986061463592176), 'sod': np.float64(33.663215283452416), 'pot': np.float64(1.95615949837945), 'hemo': np.float64(395.13139919974367), 'pcv': np.float64(305.2140657119252), 'wc': np.float64(11.647345953010749), 'rc': np.float64(165.855157412474), 'htn': np.float64(178.875), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.0410966633054441), 'bp': np.float64(0.08155060917339242), 'sg': np.float64(0.611007229539572), 'al': np.float64(0.3340600965845663), 'su': np.float64(0.0728973908034281), 'rbc': np.float64(0.06181411764453006), 'pc': np.float64(0.14202274780611748), 'pcc': np.float64(0.06401782950351509), 'ba': np.float64(0.02803591128139888), 'bgr': np.float64(0.1259409542440599), 'bu': np.float64(0.13162276545121895), 'sc': np.float64(0.07082722739896681), 'sod': np.float64(0.08519498919000172), 'pot': np.float64(0.004950655661233816), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7724368813262441), 'wc': np.float64(0.029477146024335252), 'rc': np.float64(0.4197468430713911), 'htn': np.float64(0.4526975086319995), 'dm': np.float64(0.361494713852659), 'cad': np.float64(0.04912996217711621), 'appet': np.float64(0.14531031141274056), 'pe': np.float64(0.13559055814098533), 'ane': np.float64(0.10603725427416208)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02878726010616578, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'sc', 'ane', 'bp', 'sod', 'rbc', 'su', 'cad', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e306ea0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3104d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34d9d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc', 'bu', 'appet', 'pe', 'pc', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e338f80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.701717518883747), 'bp': np.float64(30.855854400976916), 'sg': np.float64(240.93948633092106), 'al': np.float64(125.23869521734477), 'su': np.float64(35.55946785294612), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(13.25), 'bgr': np.float64(53.044000206511164), 'bu': np.float64(49.101036197990794), 'sc': np.float64(43.200778486886946), 'sod': np.float64(70.71907470923065), 'pot': np.float64(1.4452395832652591), 'hemo': np.float64(372.65019554625604), 'pcv': np.float64(265.7841710658339), 'wc': np.float64(8.92034953945184), 'rc': np.float64(134.3081558521814), 'htn': np.float64(161.33823529411765), 'dm': np.float64(142.83791208791212), 'cad': np.float64(19.412790697674414), 'appet': np.float64(52.33273381294971), 'pe': np.float64(44.10616438356164), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04750223595867262), 'bp': np.float64(0.08280112225822478), 'sg': np.float64(0.6465567151460515), 'al': np.float64(0.3360757533851857), 'su': np.float64(0.0954231831297462), 'rbc': np.float64(0.07751678734634476), 'pc': np.float64(0.1371450853050715), 'pcc': np.float64(0.06554323353937153), 'ba': np.float64(0.03555613322724076), 'bgr': np.float64(0.14234260666026394), 'bu': np.float64(0.13176173469066654), 'sc': np.float64(0.11592850078492593), 'sod': np.float64(0.18977334657121492), 'pot': np.float64(0.003878274050404639), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7132269732912104), 'wc': np.float64(0.02393759521949474), 'rc': np.float64(0.3604134855083152), 'htn': np.float64(0.43294821047287274), 'dm': np.float64(0.38330293072443067), 'cad': np.float64(0.052093869612003886), 'appet': np.float64(0.14043393627162015), 'pe': np.float64(0.11835808731807539), 'ane': np.float64(0.10105427338268425)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.028949545078577336, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030117753623188408, 'bu': 0.02976190476190476, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029437229437229435, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bgr', 'sc', 'bu', 'appet', 'pe', 'pc', 'ane', 'rbc', 'bp', 'su', 'cad', 'age']

PRIMARY: completed 15/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3459a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg', 'dm', 'rc', 'bu', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30a0c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg', 'dm', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sod', 'rbc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35d880>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(20.220066883011448), 'bp': np.float64(30.155661459263502), 'sg': np.float64(258.6948146070787), 'al': np.float64(134.97843224556073), 'su': np.float64(30.67223446309377), 'rbc': np.float64(28.886645962732924), 'pc': np.float64(56.11764705882352), 'pcc': np.float64(27.97222222222222), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.62975345765938), 'bu': np.float64(51.21615604149457), 'sc': np.float64(26.87261343629788), 'sod': np.float64(33.277542984634344), 'pot': np.float64(1.6606259567761157), 'hemo': np.float64(366.5613656279766), 'pcv': np.float64(279.295706996176), 'wc': np.float64(15.435144040567083), 'rc': np.float64(174.39061630460674), 'htn': np.float64(182.6487341772152), 'dm': np.float64(131.80263157894737), 'cad': np.float64(17.818965517241384), 'appet': np.float64(58.735074626865604), 'pe': np.float64(52.33273381294964), 'ane': np.float64(35.62012987012987)}

Normalized Mathematical Scores
{'age': np.float64(0.05516147848361305), 'bp': np.float64(0.08226633870048515), 'sg': np.float64(0.7057339885339369), 'al': np.float64(0.36822874667744016), 'su': np.float64(0.08367557887762521), 'rbc': np.float64(0.07880439312868012), 'pc': np.float64(0.15309209404184007), 'pcc': np.float64(0.076309793789374), 'ba': np.float64(0.03414968672342151), 'bgr': np.float64(0.13812081197079443), 'bu': np.float64(0.13972055116543264), 'sc': np.float64(0.07330999924190296), 'sod': np.float64(0.09078300689878961), 'pot': np.float64(0.004530280909258414), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7619343803941232), 'wc': np.float64(0.042107940137456334), 'rc': np.float64(0.47574739909059566), 'htn': np.float64(0.4982760086140271), 'dm': np.float64(0.3595649840324797), 'cad': np.float64(0.0486111390563889), 'appet': np.float64(0.16023258350274663), 'pe': np.float64(0.14276663805880233), 'ane': np.float64(0.09717371553629786)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027972027972027972, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.029957522915269395, 'sc': 0.029051670471052088, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031054405392392875, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'sg', 'dm', 'rc', 'bu', 'pe', 'appet', 'pc', 'bgr', 'ane', 'sod', 'rbc', 'sc', 'bp', 'su', 'age', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34d5e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3123c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311ee0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'bp', 'sc', 'ane', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e339760>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(19.943770055650052), 'bp': np.float64(36.21581531233158), 'sg': np.float64(262.56213391559487), 'al': np.float64(120.65889170799213), 'su': np.float64(32.161764705882355), 'rbc': np.float64(21.044117647058826), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(50.99290813061113), 'bu': np.float64(44.98993752545684), 'sc': np.float64(26.074393018539627), 'sod': np.float64(29.038436259724335), 'pot': np.float64(1.6403687015072683), 'hemo': np.float64(342.0393435086655), 'pcv': np.float64(267.94613118376503), 'wc': np.float64(7.228962812156519), 'rc': np.float64(149.9542607070492), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(21.044117647058826), 'appet': np.float64(57.416666666666664), 'pe': np.float64(51.10714285714286), 'ane': np.float64(39.75)}

Normalized Mathematical Scores
{'age': np.float64(0.058308409351583206), 'bp': np.float64(0.10588201620558325), 'sg': np.float64(0.7676372291626238), 'al': np.float64(0.3527631952227018), 'su': np.float64(0.0940294305794314), 'rbc': np.float64(0.061525429885306966), 'pc': np.float64(0.13897002694373536), 'pcc': np.float64(0.0714090330797338), 'ba': np.float64(0.03448128488077644), 'bgr': np.float64(0.14908491990284511), 'bu': np.float64(0.13153439327752955), 'sc': np.float64(0.07623214555105423), 'sod': np.float64(0.08489794174508071), 'pot': np.float64(0.004795848000058244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7833781004113541), 'wc': np.float64(0.021134886817408986), 'rc': np.float64(0.438412315872224), 'htn': np.float64(0.4814609037056562), 'dm': np.float64(0.4011281611518757), 'cad': np.float64(0.061525429885306966), 'appet': np.float64(0.1678656790697881), 'pe': np.float64(0.1494189011500312), 'ane': np.float64(0.11621470089446871)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.029386529386529386, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.02878726010616578, 'pc': 0.029236022193768675, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02938045560996381, 'sod': 0.028782894736842105, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'bp', 'sc', 'ane', 'pc', 'rbc', 'sod', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22ca40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35f980>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bu', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22c6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bu', 'bgr', 'sc', 'appet', 'pe', 'pc', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3accb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.877048710312472), 'bp': np.float64(30.278958019087277), 'sg': np.float64(240.93178956447187), 'al': np.float64(123.66082826604229), 'su': np.float64(28.24342105263158), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(19.412790697674414), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(60.081835143772174), 'bu': np.float64(56.579498149114656), 'sc': np.float64(45.81107107921602), 'sod': np.float64(85.93753774840125), 'pot': np.float64(0.8300149759020787), 'hemo': np.float64(376.1588499600323), 'pcv': np.float64(275.31330400186846), 'wc': np.float64(17.399857937178105), 'rc': np.float64(147.83130573758083), 'htn': np.float64(182.6487341772152), 'dm': np.float64(158.0755813953489), 'cad': np.float64(20.22368421052632), 'appet': np.float64(61.4318181818183), 'pe': np.float64(49.89893617021277), 'ane': np.float64(32.6608280254777)}

Normalized Mathematical Scores
{'age': np.float64(0.047525264159575), 'bp': np.float64(0.08049513662194704), 'sg': np.float64(0.6405054396302823), 'al': np.float64(0.32874629502717145), 'su': np.float64(0.07508376063897608), 'rbc': np.float64(0.0743627917439516), 'pc': np.float64(0.1424294203425343), 'pcc': np.float64(0.051607959508960285), 'ba': np.float64(0.02944997533259171), 'bgr': np.float64(0.15972463535061318), 'bu': np.float64(0.1504138428622013), 'sc': np.float64(0.12178650345215472), 'sod': np.float64(0.22846076267388712), 'pot': np.float64(0.002206554427711244), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7319070228737703), 'wc': np.float64(0.046256675707688065), 'rc': np.float64(0.3930023333314855), 'htn': np.float64(0.48556277273982), 'dm': np.float64(0.42023624171581975), 'cad': np.float64(0.05376368045753843), 'appet': np.float64(0.16331349957164523), 'pe': np.float64(0.13265389389486554), 'ane': np.float64(0.08682722214018887)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.029957522915269395, 'sc': 0.029906956136464335, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'sod', 'bu', 'bgr', 'sc', 'appet', 'pe', 'pc', 'bp', 'ane', 'rbc', 'cad', 'su', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e345d00>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.04263765723145428), 'bp': np.float64(0.07462227220969551), 'sg': np.float64(0.586177851388137), 'al': np.float64(0.29998220071225623), 'su': np.float64(0.0751314224460796), 'rbc': np.float64(0.07780688373518169), 'pc': np.float64(0.1333832292603115), 'pcc': np.float64(0.05928143522680509), 'ba': np.float64(0.027063263907889285), 'bgr': np.float64(0.13896294245967025), 'bu': np.float64(0.13009881188446426), 'sc': np.float64(0.0744762619939371), 'sod': np.float64(0.09858779677392548), 'pot': np.float64(0.0017076505052074245), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6248678577720422), 'wc': np.float64(0.022348319128360494), 'rc': np.float64(0.3677918443835548), 'htn': np.float64(0.41255743003770773), 'dm': np.float64(0.3727890253685629), 'cad': np.float64(0.04446107642010382), 'appet': np.float64(0.14985029460109064), 'pe': np.float64(0.1431192313961006), 'ane': np.float64(0.1093502149791743)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f66678f95b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.04263765723145428), 'bp': np.float64(0.07462227220969551), 'sg': np.float64(0.586177851388137), 'al': np.float64(0.29998220071225623), 'su': np.float64(0.0751314224460796), 'rbc': np.float64(0.07780688373518169), 'pc': np.float64(0.1333832292603115), 'pcc': np.float64(0.05928143522680509), 'ba': np.float64(0.027063263907889285), 'bgr': np.float64(0.13896294245967025), 'bu': np.float64(0.13009881188446426), 'sc': np.float64(0.0744762619939371), 'sod': np.float64(0.09858779677392548), 'pot': np.float64(0.0017076505052074245), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6248678577720422), 'wc': np.float64(0.022348319128360494), 'rc': np.float64(0.3677918443835548), 'htn': np.float64(0.41255743003770773), 'dm': np.float64(0.3727890253685629), 'cad': np.float64(0.04446107642010382), 'appet': np.float64(0.14985029460109064), 'pe': np.float64(0.1431192313961006), 'ane': np.float64(0.1093502149791743)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd1760>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.04263765723145428), 'bp': np.float64(0.07462227220969551), 'sg': np.float64(0.586177851388137), 'al': np.float64(0.29998220071225623), 'su': np.float64(0.0751314224460796), 'rbc': np.float64(0.07780688373518169), 'pc': np.float64(0.1333832292603115), 'pcc': np.float64(0.05928143522680509), 'ba': np.float64(0.027063263907889285), 'bgr': np.float64(0.13896294245967025), 'bu': np.float64(0.13009881188446426), 'sc': np.float64(0.0744762619939371), 'sod': np.float64(0.09858779677392548), 'pot': np.float64(0.0017076505052074245), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6248678577720422), 'wc': np.float64(0.022348319128360494), 'rc': np.float64(0.3677918443835548), 'htn': np.float64(0.41255743003770773), 'dm': np.float64(0.3727890253685629), 'cad': np.float64(0.04446107642010382), 'appet': np.float64(0.14985029460109064), 'pe': np.float64(0.1431192313961006), 'ane': np.float64(0.1093502149791743)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'rbc', 'ane', 'pc', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd1df0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.33705265126774), 'bp': np.float64(28.592283657360035), 'sg': np.float64(224.60001423507762), 'al': np.float64(114.94123565175394), 'su': np.float64(28.787369756346628), 'rbc': np.float64(29.8125), 'pc': np.float64(51.10714285714286), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(53.245066801276714), 'bu': np.float64(49.848684886371174), 'sc': np.float64(28.536338356014806), 'sod': np.float64(37.77491849340919), 'pot': np.float64(0.6543036842314356), 'hemo': np.float64(383.1601854338214), 'pcv': np.float64(239.42448425557043), 'wc': np.float64(8.562986101356826), 'rc': np.float64(140.92319129505003), 'htn': np.float64(158.0755813953489), 'dm': np.float64(142.83791208791212), 'cad': np.float64(17.035714285714285), 'appet': np.float64(57.416666666666664), 'pe': np.float64(54.83759124087591), 'ane': np.float64(41.89864864864866)}

Normalized Mathematical Scores
{'age': np.float64(0.04263765723145428), 'bp': np.float64(0.07462227220969551), 'sg': np.float64(0.586177851388137), 'al': np.float64(0.29998220071225623), 'su': np.float64(0.0751314224460796), 'rbc': np.float64(0.07780688373518169), 'pc': np.float64(0.1333832292603115), 'pcc': np.float64(0.05928143522680509), 'ba': np.float64(0.027063263907889285), 'bgr': np.float64(0.13896294245967025), 'bu': np.float64(0.13009881188446426), 'sc': np.float64(0.0744762619939371), 'sod': np.float64(0.09858779677392548), 'pot': np.float64(0.0017076505052074245), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6248678577720422), 'wc': np.float64(0.022348319128360494), 'rc': np.float64(0.3677918443835548), 'htn': np.float64(0.41255743003770773), 'dm': np.float64(0.3727890253685629), 'cad': np.float64(0.04446107642010382), 'appet': np.float64(0.14985029460109064), 'pe': np.float64(0.1431192313961006), 'ane': np.float64(0.1093502149791743)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02886002886002886, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.029236022193768675, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.030536130536130537, 'htn': 0.031754032258064516, 'dm': 0.0315136476426799, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'rbc', 'ane', 'pc', 'sc', 'sod', 'bp', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e339c40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.041364706322207005), 'bp': np.float64(0.0800280549330416), 'sg': np.float64(0.7590401608947129), 'al': np.float64(0.42145426983901735), 'su': np.float64(0.09899577184515304), 'rbc': np.float64(0.0972477075022456), 'pc': np.float64(0.1655036875003124), 'pcc': np.float64(0.08278493125265528), 'ba': np.float64(0.037298705289657876), 'bgr': np.float64(0.16871196077632392), 'bu': np.float64(0.15843097010125062), 'sc': np.float64(0.09112719564173694), 'sod': np.float64(0.12693672414520077), 'pot': np.float64(0.005434531386323013), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7226909450975417), 'wc': np.float64(0.019419751353515594), 'rc': np.float64(0.5085616801029064), 'htn': np.float64(0.5208004405259636), 'dm': np.float64(0.4898372752152641), 'cad': np.float64(0.05635296086547288), 'appet': np.float64(0.17747357811026773), 'pe': np.float64(0.1655036875003124), 'ane': np.float64(0.1223803729849775)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.02946236559139785, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3afbc0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.041364706322207005), 'bp': np.float64(0.0800280549330416), 'sg': np.float64(0.7590401608947129), 'al': np.float64(0.42145426983901735), 'su': np.float64(0.09899577184515304), 'rbc': np.float64(0.0972477075022456), 'pc': np.float64(0.1655036875003124), 'pcc': np.float64(0.08278493125265528), 'ba': np.float64(0.037298705289657876), 'bgr': np.float64(0.16871196077632392), 'bu': np.float64(0.15843097010125062), 'sc': np.float64(0.09112719564173694), 'sod': np.float64(0.12693672414520077), 'pot': np.float64(0.005434531386323013), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7226909450975417), 'wc': np.float64(0.019419751353515594), 'rc': np.float64(0.5085616801029064), 'htn': np.float64(0.5208004405259636), 'dm': np.float64(0.4898372752152641), 'cad': np.float64(0.05635296086547288), 'appet': np.float64(0.17747357811026773), 'pe': np.float64(0.1655036875003124), 'ane': np.float64(0.1223803729849775)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.02946236559139785, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'bu', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e312b40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.041364706322207005), 'bp': np.float64(0.0800280549330416), 'sg': np.float64(0.7590401608947129), 'al': np.float64(0.42145426983901735), 'su': np.float64(0.09899577184515304), 'rbc': np.float64(0.0972477075022456), 'pc': np.float64(0.1655036875003124), 'pcc': np.float64(0.08278493125265528), 'ba': np.float64(0.037298705289657876), 'bgr': np.float64(0.16871196077632392), 'bu': np.float64(0.15843097010125062), 'sc': np.float64(0.09112719564173694), 'sod': np.float64(0.12693672414520077), 'pot': np.float64(0.005434531386323013), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7226909450975417), 'wc': np.float64(0.019419751353515594), 'rc': np.float64(0.5085616801029064), 'htn': np.float64(0.5208004405259636), 'dm': np.float64(0.4898372752152641), 'cad': np.float64(0.05635296086547288), 'appet': np.float64(0.17747357811026773), 'pe': np.float64(0.1655036875003124), 'ane': np.float64(0.1223803729849775)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.02946236559139785, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'sod', 'rbc', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666fafcb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.079637063716833), 'bp': np.float64(25.30509718323389), 'sg': np.float64(240.01064443574106), 'al': np.float64(133.26503143789296), 'su': np.float64(31.30274288643937), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(52.33273381294964), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(11.793956043956047), 'bgr': np.float64(53.347198891574514), 'bu': np.float64(50.09632057908366), 'sc': np.float64(28.814676849001337), 'sod': np.float64(40.1377509837421), 'pot': np.float64(1.7184141860164028), 'hemo': np.float64(316.202826676299), 'pcv': np.float64(228.51691965320873), 'wc': np.float64(6.140580271332515), 'rc': np.float64(160.80864078778674), 'htn': np.float64(164.67857142857147), 'dm': np.float64(154.88793103448273), 'cad': np.float64(17.818965517241384), 'appet': np.float64(56.11764705882361), 'pe': np.float64(52.33273381294964), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.041364706322207005), 'bp': np.float64(0.0800280549330416), 'sg': np.float64(0.7590401608947129), 'al': np.float64(0.42145426983901735), 'su': np.float64(0.09899577184515304), 'rbc': np.float64(0.0972477075022456), 'pc': np.float64(0.1655036875003124), 'pcc': np.float64(0.08278493125265528), 'ba': np.float64(0.037298705289657876), 'bgr': np.float64(0.16871196077632392), 'bu': np.float64(0.15843097010125062), 'sc': np.float64(0.09112719564173694), 'sod': np.float64(0.12693672414520077), 'pot': np.float64(0.005434531386323013), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7226909450975417), 'wc': np.float64(0.019419751353515594), 'rc': np.float64(0.5085616801029064), 'htn': np.float64(0.5208004405259636), 'dm': np.float64(0.4898372752152641), 'cad': np.float64(0.05635296086547288), 'appet': np.float64(0.17747357811026773), 'pe': np.float64(0.1655036875003124), 'ane': np.float64(0.1223803729849775)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.03131881575727918, 'su': 0.028665028665028666, 'rbc': 0.02946236559139785, 'pc': 0.029437229437229435, 'pcc': 0.02813852813852814, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.029551337359792925, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'htn', 'sg', 'pcv', 'al', 'dm', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'sod', 'rbc', 'pc', 'ane', 'bp', 'su', 'cad', 'pcc']

PRIMARY: completed 20/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af5f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.08513685899925653), 'bp': np.float64(0.08022924296088649), 'sg': np.float64(0.6306635571451844), 'al': np.float64(0.3673194121472562), 'su': np.float64(0.0778593317921416), 'rbc': np.float64(0.07493148147501383), 'pc': np.float64(0.15179944432174333), 'pcc': np.float64(0.06761157120392816), 'ba': np.float64(0.034651754237437334), 'bgr': np.float64(0.14035169361046315), 'bu': np.float64(0.15509268437293422), 'sc': np.float64(0.07156449179583359), 'sod': np.float64(0.11335469139422123), 'pot': np.float64(0.001250547910026839), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7174419607410025), 'wc': np.float64(0.03759090208424136), 'rc': np.float64(0.42442924141941446), 'htn': np.float64(0.5997656113342656), 'dm': np.float64(0.420131795395532), 'cad': np.float64(0.05598247398963022), 'appet': np.float64(0.17774806728272513), 'pe': np.float64(0.1414729515107404), 'ane': np.float64(0.10711969617700653)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028958333333333336, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.029437229437229435, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.029051670471052088, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34dd00>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.08513685899925653), 'bp': np.float64(0.08022924296088649), 'sg': np.float64(0.6306635571451844), 'al': np.float64(0.3673194121472562), 'su': np.float64(0.0778593317921416), 'rbc': np.float64(0.07493148147501383), 'pc': np.float64(0.15179944432174333), 'pcc': np.float64(0.06761157120392816), 'ba': np.float64(0.034651754237437334), 'bgr': np.float64(0.14035169361046315), 'bu': np.float64(0.15509268437293422), 'sc': np.float64(0.07156449179583359), 'sod': np.float64(0.11335469139422123), 'pot': np.float64(0.001250547910026839), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7174419607410025), 'wc': np.float64(0.03759090208424136), 'rc': np.float64(0.42442924141941446), 'htn': np.float64(0.5997656113342656), 'dm': np.float64(0.420131795395532), 'cad': np.float64(0.05598247398963022), 'appet': np.float64(0.17774806728272513), 'pe': np.float64(0.1414729515107404), 'ane': np.float64(0.10711969617700653)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028958333333333336, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.029437229437229435, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.029051670471052088, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'appet', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f66675cc980>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.08513685899925653), 'bp': np.float64(0.08022924296088649), 'sg': np.float64(0.6306635571451844), 'al': np.float64(0.3673194121472562), 'su': np.float64(0.0778593317921416), 'rbc': np.float64(0.07493148147501383), 'pc': np.float64(0.15179944432174333), 'pcc': np.float64(0.06761157120392816), 'ba': np.float64(0.034651754237437334), 'bgr': np.float64(0.14035169361046315), 'bu': np.float64(0.15509268437293422), 'sc': np.float64(0.07156449179583359), 'sod': np.float64(0.11335469139422123), 'pot': np.float64(0.001250547910026839), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7174419607410025), 'wc': np.float64(0.03759090208424136), 'rc': np.float64(0.42442924141941446), 'htn': np.float64(0.5997656113342656), 'dm': np.float64(0.420131795395532), 'cad': np.float64(0.05598247398963022), 'appet': np.float64(0.17774806728272513), 'pe': np.float64(0.1414729515107404), 'ane': np.float64(0.10711969617700653)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028958333333333336, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.029437229437229435, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.029051670471052088, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'appet', 'pe', 'bgr', 'pc', 'sod', 'ane', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd3560>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(30.75571385780485), 'bp': np.float64(28.982836206758304), 'sg': np.float64(227.82738442666803), 'al': np.float64(132.69423921919358), 'su': np.float64(28.126705141657933), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(24.424698795180728), 'ba': np.float64(12.517955801104971), 'bgr': np.float64(50.70208813058745), 'bu': np.float64(56.02727512010352), 'sc': np.float64(25.85269245217399), 'sod': np.float64(40.949413614036274), 'pot': np.float64(0.45176077833218176), 'hemo': np.float64(361.25027654677075), 'pcv': np.float64(259.1761067239446), 'wc': np.float64(13.579723773574772), 'rc': np.float64(153.3251808372996), 'htn': np.float64(216.6654929577465), 'dm': np.float64(151.77272727272725), 'cad': np.float64(20.22368421052632), 'appet': np.float64(64.21153846153847), 'pe': np.float64(51.10714285714286), 'ane': np.float64(38.69701986754967)}

Normalized Mathematical Scores
{'age': np.float64(0.08513685899925653), 'bp': np.float64(0.08022924296088649), 'sg': np.float64(0.6306635571451844), 'al': np.float64(0.3673194121472562), 'su': np.float64(0.0778593317921416), 'rbc': np.float64(0.07493148147501383), 'pc': np.float64(0.15179944432174333), 'pcc': np.float64(0.06761157120392816), 'ba': np.float64(0.034651754237437334), 'bgr': np.float64(0.14035169361046315), 'bu': np.float64(0.15509268437293422), 'sc': np.float64(0.07156449179583359), 'sod': np.float64(0.11335469139422123), 'pot': np.float64(0.001250547910026839), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7174419607410025), 'wc': np.float64(0.03759090208424136), 'rc': np.float64(0.42442924141941446), 'htn': np.float64(0.5997656113342656), 'dm': np.float64(0.420131795395532), 'cad': np.float64(0.05598247398963022), 'appet': np.float64(0.17774806728272513), 'pe': np.float64(0.1414729515107404), 'ane': np.float64(0.10711969617700653)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028958333333333336, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.029437229437229435, 'pcc': 0.027651515151515153, 'ba': 0.026973565905412694, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.029051670471052088, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.02712049508554787, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.029857397504456328, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bu', 'appet', 'pe', 'bgr', 'pc', 'sod', 'ane', 'sc', 'bp', 'age', 'rbc', 'su', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3afaa0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}

Normalized Mathematical Scores
{'age': np.float64(0.044360754027836374), 'bp': np.float64(0.08045449822265863), 'sg': np.float64(0.6461791693264042), 'al': np.float64(0.3561685469256983), 'su': np.float64(0.09152732620031914), 'rbc': np.float64(0.07975430815065672), 'pc': np.float64(0.15275596320846604), 'pcc': np.float64(0.07463528965574937), 'ba': np.float64(0.02956567029841279), 'bgr': np.float64(0.14124112052394686), 'bu': np.float64(0.13737518680325572), 'sc': np.float64(0.07505826517783079), 'sod': np.float64(0.09468746761631329), 'pot': np.float64(0.0038891214590193817), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6527655608132409), 'wc': np.float64(0.02108573638304291), 'rc': np.float64(0.4273935055086517), 'htn': np.float64(0.4695310021200318), 'dm': np.float64(0.3911887881956658), 'cad': np.float64(0.05766170201474074), 'appet': np.float64(0.1600024510267047), 'pe': np.float64(0.14227168296080198), 'ane': np.float64(0.11637762167798052)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3093d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}

Normalized Mathematical Scores
{'age': np.float64(0.044360754027836374), 'bp': np.float64(0.08045449822265863), 'sg': np.float64(0.6461791693264042), 'al': np.float64(0.3561685469256983), 'su': np.float64(0.09152732620031914), 'rbc': np.float64(0.07975430815065672), 'pc': np.float64(0.15275596320846604), 'pcc': np.float64(0.07463528965574937), 'ba': np.float64(0.02956567029841279), 'bgr': np.float64(0.14124112052394686), 'bu': np.float64(0.13737518680325572), 'sc': np.float64(0.07505826517783079), 'sod': np.float64(0.09468746761631329), 'pot': np.float64(0.0038891214590193817), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6527655608132409), 'wc': np.float64(0.02108573638304291), 'rc': np.float64(0.4273935055086517), 'htn': np.float64(0.4695310021200318), 'dm': np.float64(0.3911887881956658), 'cad': np.float64(0.05766170201474074), 'appet': np.float64(0.1600024510267047), 'pe': np.float64(0.14227168296080198), 'ane': np.float64(0.11637762167798052)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'appet', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3afaa0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}

Normalized Mathematical Scores
{'age': np.float64(0.044360754027836374), 'bp': np.float64(0.08045449822265863), 'sg': np.float64(0.6461791693264042), 'al': np.float64(0.3561685469256983), 'su': np.float64(0.09152732620031914), 'rbc': np.float64(0.07975430815065672), 'pc': np.float64(0.15275596320846604), 'pcc': np.float64(0.07463528965574937), 'ba': np.float64(0.02956567029841279), 'bgr': np.float64(0.14124112052394686), 'bu': np.float64(0.13737518680325572), 'sc': np.float64(0.07505826517783079), 'sod': np.float64(0.09468746761631329), 'pot': np.float64(0.0038891214590193817), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6527655608132409), 'wc': np.float64(0.02108573638304291), 'rc': np.float64(0.4273935055086517), 'htn': np.float64(0.4695310021200318), 'dm': np.float64(0.3911887881956658), 'cad': np.float64(0.05766170201474074), 'appet': np.float64(0.1600024510267047), 'pe': np.float64(0.14227168296080198), 'ane': np.float64(0.11637762167798052)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'appet', 'bu', 'bgr', 'pc', 'ane', 'sc', 'sod']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e33aa80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.558643769662755), 'bp': np.float64(28.217799831081084), 'sg': np.float64(226.63436921332388), 'al': np.float64(124.9189664381733), 'su': np.float64(32.1013719164219), 'rbc': np.float64(27.97222222222222), 'pc': np.float64(53.576086956521735), 'pcc': np.float64(26.17682926829269), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(49.53748708782425), 'bu': np.float64(48.18158845815675), 'sc': np.float64(26.32517943987053), 'sod': np.float64(33.209728066598196), 'pot': np.float64(1.3640312633068397), 'hemo': np.float64(350.729921315127), 'pcv': np.float64(228.9444137812527), 'wc': np.float64(7.3953986624961505), 'rc': np.float64(149.8996905576457), 'htn': np.float64(164.67857142857147), 'dm': np.float64(137.20161290322577), 'cad': np.float64(20.22368421052632), 'appet': np.float64(56.11764705882361), 'pe': np.float64(49.89893617021277), 'ane': np.float64(40.817114093959724)}

Normalized Mathematical Scores
{'age': np.float64(0.044360754027836374), 'bp': np.float64(0.08045449822265863), 'sg': np.float64(0.6461791693264042), 'al': np.float64(0.3561685469256983), 'su': np.float64(0.09152732620031914), 'rbc': np.float64(0.07975430815065672), 'pc': np.float64(0.15275596320846604), 'pcc': np.float64(0.07463528965574937), 'ba': np.float64(0.02956567029841279), 'bgr': np.float64(0.14124112052394686), 'bu': np.float64(0.13737518680325572), 'sc': np.float64(0.07505826517783079), 'sod': np.float64(0.09468746761631329), 'pot': np.float64(0.0038891214590193817), 'hemo': np.float64(1.0), 'pcv': np.float64(0.6527655608132409), 'wc': np.float64(0.02108573638304291), 'rc': np.float64(0.4273935055086517), 'htn': np.float64(0.4695310021200318), 'dm': np.float64(0.3911887881956658), 'cad': np.float64(0.05766170201474074), 'appet': np.float64(0.1600024510267047), 'pe': np.float64(0.14227168296080198), 'ane': np.float64(0.11637762167798052)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029030910609857977, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.028484848484848488, 'rbc': 0.029116045245077504, 'pc': 0.02964426877470356, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.029709507042253523, 'bu': 0.02976190476190476, 'sc': 0.02921395544346364, 'sod': 0.029138513513513514, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.029857397504456328, 'pe': 0.029910714285714284, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'pe', 'appet', 'bu', 'bgr', 'pc', 'ane', 'sc', 'sod', 'rbc', 'bp', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6667863290>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.044603676166630433), 'bp': np.float64(0.08808839608810028), 'sg': np.float64(0.8611751691115233), 'al': np.float64(0.4336309940268661), 'su': np.float64(0.09481408208955881), 'rbc': np.float64(0.09505447109704493), 'pc': np.float64(0.1542477068606433), 'pcc': np.float64(0.07021445251767781), 'ba': np.float64(0.03424393380985107), 'bgr': np.float64(0.1749401574554003), 'bu': np.float64(0.16596244799628268), 'sc': np.float64(0.17482021682996005), 'sod': np.float64(0.23953734120516668), 'pot': np.float64(0.0047803591330825524), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7699212149960782), 'wc': np.float64(0.03627604243399258), 'rc': np.float64(0.5270927192611757), 'htn': np.float64(0.49872912597115276), 'dm': np.float64(0.4327347236687317), 'cad': np.float64(0.05026716487061025), 'appet': np.float64(0.17748653275301893), 'pe': np.float64(0.16561452387321832), 'ane': np.float64(0.11640817127930796)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.028665028665028666, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.03047794966520434, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['hemo', 'al', 'sg', 'htn', 'pcv']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ad2b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.044603676166630433), 'bp': np.float64(0.08808839608810028), 'sg': np.float64(0.8611751691115233), 'al': np.float64(0.4336309940268661), 'su': np.float64(0.09481408208955881), 'rbc': np.float64(0.09505447109704493), 'pc': np.float64(0.1542477068606433), 'pcc': np.float64(0.07021445251767781), 'ba': np.float64(0.03424393380985107), 'bgr': np.float64(0.1749401574554003), 'bu': np.float64(0.16596244799628268), 'sc': np.float64(0.17482021682996005), 'sod': np.float64(0.23953734120516668), 'pot': np.float64(0.0047803591330825524), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7699212149960782), 'wc': np.float64(0.03627604243399258), 'rc': np.float64(0.5270927192611757), 'htn': np.float64(0.49872912597115276), 'dm': np.float64(0.4327347236687317), 'cad': np.float64(0.05026716487061025), 'appet': np.float64(0.17748653275301893), 'pe': np.float64(0.16561452387321832), 'ane': np.float64(0.11640817127930796)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.028665028665028666, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.03047794966520434, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['hemo', 'al', 'sg', 'htn', 'pcv', 'dm', 'rc', 'sc', 'sod', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ad370>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.044603676166630433), 'bp': np.float64(0.08808839608810028), 'sg': np.float64(0.8611751691115233), 'al': np.float64(0.4336309940268661), 'su': np.float64(0.09481408208955881), 'rbc': np.float64(0.09505447109704493), 'pc': np.float64(0.1542477068606433), 'pcc': np.float64(0.07021445251767781), 'ba': np.float64(0.03424393380985107), 'bgr': np.float64(0.1749401574554003), 'bu': np.float64(0.16596244799628268), 'sc': np.float64(0.17482021682996005), 'sod': np.float64(0.23953734120516668), 'pot': np.float64(0.0047803591330825524), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7699212149960782), 'wc': np.float64(0.03627604243399258), 'rc': np.float64(0.5270927192611757), 'htn': np.float64(0.49872912597115276), 'dm': np.float64(0.4327347236687317), 'cad': np.float64(0.05026716487061025), 'appet': np.float64(0.17748653275301893), 'pe': np.float64(0.16561452387321832), 'ane': np.float64(0.11640817127930796)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.028665028665028666, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.03047794966520434, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['hemo', 'al', 'sg', 'htn', 'pcv', 'dm', 'rc', 'sc', 'sod', 'bgr', 'bu', 'appet', 'pe', 'rbc', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6682d3f0b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.42923227381489), 'bp': np.float64(28.496483631407965), 'sg': np.float64(278.5890673479596), 'al': np.float64(140.27907275095723), 'su': np.float64(30.67223446309377), 'rbc': np.float64(30.74999999999999), 'pc': np.float64(49.89893617021277), 'pcc': np.float64(22.71428571428571), 'ba': np.float64(11.077868852459018), 'bgr': np.float64(56.59291751001909), 'bu': np.float64(53.68863996597782), 'sc': np.float64(56.55411687087269), 'sod': np.float64(77.49002395204386), 'pot': np.float64(1.5464400742624118), 'hemo': np.float64(323.49872283867717), 'pcv': np.float64(249.0685297376339), 'wc': np.float64(11.735253397038258), 'rc': np.float64(170.51382149855576), 'htn': np.float64(161.33823529411765), 'dm': np.float64(139.9891304347826), 'cad': np.float64(16.261363636363633), 'appet': np.float64(57.416666666666664), 'pe': np.float64(53.576086956521735), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.044603676166630433), 'bp': np.float64(0.08808839608810028), 'sg': np.float64(0.8611751691115233), 'al': np.float64(0.4336309940268661), 'su': np.float64(0.09481408208955881), 'rbc': np.float64(0.09505447109704493), 'pc': np.float64(0.1542477068606433), 'pcc': np.float64(0.07021445251767781), 'ba': np.float64(0.03424393380985107), 'bgr': np.float64(0.1749401574554003), 'bu': np.float64(0.16596244799628268), 'sc': np.float64(0.17482021682996005), 'sod': np.float64(0.23953734120516668), 'pot': np.float64(0.0047803591330825524), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7699212149960782), 'wc': np.float64(0.03627604243399258), 'rc': np.float64(0.5270927192611757), 'htn': np.float64(0.49872912597115276), 'dm': np.float64(0.4327347236687317), 'cad': np.float64(0.05026716487061025), 'appet': np.float64(0.17748653275301893), 'pe': np.float64(0.16561452387321832), 'ane': np.float64(0.11640817127930796)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028693528693528692, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.028665028665028666, 'pcc': 0.027809742999616416, 'ba': 0.026973565905412694, 'bgr': 0.029910714285714284, 'bu': 0.02976190476190476, 'sc': 0.03047794966520434, 'sod': 0.030330882352941176, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.03149801587301587, 'wc': 0.02712049508554787, 'rc': 0.031009615384615385, 'htn': 0.0315136476426799, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.0293236301369863, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['hemo', 'al', 'sg', 'htn', 'pcv', 'dm', 'rc', 'sc', 'sod', 'bgr', 'bu', 'appet', 'pe', 'rbc', 'ane', 'bp', 'pc', 'su', 'cad', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e32bc20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.032197418909080976), 'bp': np.float64(0.08577795961018425), 'sg': np.float64(0.6898570005874478), 'al': np.float64(0.34131909343342903), 'su': np.float64(0.08453747898893431), 'rbc': np.float64(0.07210251819962288), 'pc': np.float64(0.1460684078500547), 'pcc': np.float64(0.06737835648302187), 'ba': np.float64(0.03529342482444003), 'bgr': np.float64(0.14929964634832574), 'bu': np.float64(0.11905415362567813), 'sc': np.float64(0.06902301837327268), 'sod': np.float64(0.08574150381899763), 'pot': np.float64(0.00437631628820999), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7222266712825093), 'wc': np.float64(0.035421870292706874), 'rc': np.float64(0.39099324062264085), 'htn': np.float64(0.3961587797709617), 'dm': np.float64(0.3961587797709617), 'cad': np.float64(0.04331465773908548), 'appet': np.float64(0.16363315145876772), 'pe': np.float64(0.1529381742392401), 'ane': np.float64(0.08959100147742467)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029571646010002173, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031754032258064516, 'cad': 0.028283227848101264, 'appet': 0.03007688828584351, 'pe': 0.030330882352941176, 'ane': 0.029513888888888888}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22f3e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.032197418909080976), 'bp': np.float64(0.08577795961018425), 'sg': np.float64(0.6898570005874478), 'al': np.float64(0.34131909343342903), 'su': np.float64(0.08453747898893431), 'rbc': np.float64(0.07210251819962288), 'pc': np.float64(0.1460684078500547), 'pcc': np.float64(0.06737835648302187), 'ba': np.float64(0.03529342482444003), 'bgr': np.float64(0.14929964634832574), 'bu': np.float64(0.11905415362567813), 'sc': np.float64(0.06902301837327268), 'sod': np.float64(0.08574150381899763), 'pot': np.float64(0.00437631628820999), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7222266712825093), 'wc': np.float64(0.035421870292706874), 'rc': np.float64(0.39099324062264085), 'htn': np.float64(0.3961587797709617), 'dm': np.float64(0.3961587797709617), 'cad': np.float64(0.04331465773908548), 'appet': np.float64(0.16363315145876772), 'pe': np.float64(0.1529381742392401), 'ane': np.float64(0.08959100147742467)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029571646010002173, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031754032258064516, 'cad': 0.028283227848101264, 'appet': 0.03007688828584351, 'pe': 0.030330882352941176, 'ane': 0.029513888888888888}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e33abd0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.032197418909080976), 'bp': np.float64(0.08577795961018425), 'sg': np.float64(0.6898570005874478), 'al': np.float64(0.34131909343342903), 'su': np.float64(0.08453747898893431), 'rbc': np.float64(0.07210251819962288), 'pc': np.float64(0.1460684078500547), 'pcc': np.float64(0.06737835648302187), 'ba': np.float64(0.03529342482444003), 'bgr': np.float64(0.14929964634832574), 'bu': np.float64(0.11905415362567813), 'sc': np.float64(0.06902301837327268), 'sod': np.float64(0.08574150381899763), 'pot': np.float64(0.00437631628820999), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7222266712825093), 'wc': np.float64(0.035421870292706874), 'rc': np.float64(0.39099324062264085), 'htn': np.float64(0.3961587797709617), 'dm': np.float64(0.3961587797709617), 'cad': np.float64(0.04331465773908548), 'appet': np.float64(0.16363315145876772), 'pe': np.float64(0.1529381742392401), 'ane': np.float64(0.08959100147742467)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029571646010002173, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031754032258064516, 'cad': 0.028283227848101264, 'appet': 0.03007688828584351, 'pe': 0.030330882352941176, 'ane': 0.029513888888888888}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'bp', 'ane', 'pc', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34ce60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.087684963061434), 'bp': np.float64(32.20310781649891), 'sg': np.float64(258.98889958262106), 'al': np.float64(128.13939169941943), 'su': np.float64(31.73740157480315), 'rbc': np.float64(27.069018404907975), 'pc': np.float64(54.83759124087591), 'pcc': np.float64(25.295454545454547), 'ba': np.float64(13.25), 'bgr': np.float64(56.050675839921205), 'bu': np.float64(44.6957908841952), 'sc': np.float64(25.912900150527502), 'sod': np.float64(32.18942143622764), 'pot': np.float64(1.6429743247424382), 'hemo': np.float64(375.4240362308116), 'pcv': np.float64(271.14125200642326), 'wc': np.float64(13.298221516132294), 'rc': np.float64(146.78826053351676), 'htn': np.float64(148.72752808988764), 'dm': np.float64(148.72752808988764), 'cad': np.float64(16.261363636363633), 'appet': np.float64(61.4318181818183), 'pe': np.float64(57.416666666666664), 'ane': np.float64(33.63461538461538)}

Normalized Mathematical Scores
{'age': np.float64(0.032197418909080976), 'bp': np.float64(0.08577795961018425), 'sg': np.float64(0.6898570005874478), 'al': np.float64(0.34131909343342903), 'su': np.float64(0.08453747898893431), 'rbc': np.float64(0.07210251819962288), 'pc': np.float64(0.1460684078500547), 'pcc': np.float64(0.06737835648302187), 'ba': np.float64(0.03529342482444003), 'bgr': np.float64(0.14929964634832574), 'bu': np.float64(0.11905415362567813), 'sc': np.float64(0.06902301837327268), 'sod': np.float64(0.08574150381899763), 'pot': np.float64(0.00437631628820999), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7222266712825093), 'wc': np.float64(0.035421870292706874), 'rc': np.float64(0.39099324062264085), 'htn': np.float64(0.3961587797709617), 'dm': np.float64(0.3961587797709617), 'cad': np.float64(0.04331465773908548), 'appet': np.float64(0.16363315145876772), 'pe': np.float64(0.1529381742392401), 'ane': np.float64(0.08959100147742467)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.029571646010002173, 'sg': 0.03125763125763126, 'al': 0.031544957774465976, 'su': 0.028484848484848488, 'rbc': 0.02928692699490662, 'pc': 0.029437229437229435, 'pcc': 0.027972027972027972, 'ba': 0.027271052146674038, 'bgr': 0.030117753623188408, 'bu': 0.029957522915269395, 'sc': 0.02938045560996381, 'sod': 0.029138513513513514, 'pot': 0.02792120864410021, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.031754032258064516, 'cad': 0.028283227848101264, 'appet': 0.03007688828584351, 'pe': 0.030330882352941176, 'ane': 0.029513888888888888}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'dm', 'al', 'sg', 'rc', 'pe', 'bgr', 'appet', 'bu', 'bp', 'ane', 'pc', 'sc', 'rbc', 'sod', 'su', 'cad', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f616000>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04632012624498299), 'bp': np.float64(0.08768748863230913), 'sg': np.float64(0.6291628689310891), 'al': np.float64(0.27570257130402037), 'su': np.float64(0.07592230621857678), 'rbc': np.float64(0.06726783842996786), 'pc': np.float64(0.1264043996870825), 'pcc': np.float64(0.0581699059288733), 'ba': np.float64(0.027575635629676264), 'bgr': np.float64(0.14787268227408162), 'bu': np.float64(0.133934818651203), 'sc': np.float64(0.07888996503724914), 'sod': np.float64(0.10139654446287828), 'pot': np.float64(0.004631292860360031), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7373359487228023), 'wc': np.float64(0.020456207282722415), 'rc': np.float64(0.4052286615934912), 'htn': np.float64(0.4470243101172216), 'dm': np.float64(0.38759087857267194), 'cad': np.float64(0.05596231936610772), 'appet': np.float64(0.1391676862893376), 'pe': np.float64(0.12952780961263433), 'ane': np.float64(0.10014309781303485)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.030158730158730156, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35c6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04632012624498299), 'bp': np.float64(0.08768748863230913), 'sg': np.float64(0.6291628689310891), 'al': np.float64(0.27570257130402037), 'su': np.float64(0.07592230621857678), 'rbc': np.float64(0.06726783842996786), 'pc': np.float64(0.1264043996870825), 'pcc': np.float64(0.0581699059288733), 'ba': np.float64(0.027575635629676264), 'bgr': np.float64(0.14787268227408162), 'bu': np.float64(0.133934818651203), 'sc': np.float64(0.07888996503724914), 'sod': np.float64(0.10139654446287828), 'pot': np.float64(0.004631292860360031), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7373359487228023), 'wc': np.float64(0.020456207282722415), 'rc': np.float64(0.4052286615934912), 'htn': np.float64(0.4470243101172216), 'dm': np.float64(0.38759087857267194), 'cad': np.float64(0.05596231936610772), 'appet': np.float64(0.1391676862893376), 'pe': np.float64(0.12952780961263433), 'ane': np.float64(0.10014309781303485)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.030158730158730156, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34d580>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04632012624498299), 'bp': np.float64(0.08768748863230913), 'sg': np.float64(0.6291628689310891), 'al': np.float64(0.27570257130402037), 'su': np.float64(0.07592230621857678), 'rbc': np.float64(0.06726783842996786), 'pc': np.float64(0.1264043996870825), 'pcc': np.float64(0.0581699059288733), 'ba': np.float64(0.027575635629676264), 'bgr': np.float64(0.14787268227408162), 'bu': np.float64(0.133934818651203), 'sc': np.float64(0.07888996503724914), 'sod': np.float64(0.10139654446287828), 'pot': np.float64(0.004631292860360031), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7373359487228023), 'wc': np.float64(0.020456207282722415), 'rc': np.float64(0.4052286615934912), 'htn': np.float64(0.4470243101172216), 'dm': np.float64(0.38759087857267194), 'cad': np.float64(0.05596231936610772), 'appet': np.float64(0.1391676862893376), 'pe': np.float64(0.12952780961263433), 'ane': np.float64(0.10014309781303485)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.030158730158730156, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'sod', 'bp', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ad910>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(17.41825923527365), 'bp': np.float64(32.97407698350354), 'sg': np.float64(236.5909344523254), 'al': np.float64(103.67542682000106), 'su': np.float64(28.549887892376677), 'rbc': np.float64(25.295454545454547), 'pc': np.float64(47.5332167832168), 'pcc': np.float64(21.874260355029584), 'ba': np.float64(10.369565217391305), 'bgr': np.float64(55.60616782524821), 'bu': np.float64(50.36496186468619), 'sc': np.float64(29.66584881079235), 'sod': np.float64(38.129241869384146), 'pot': np.float64(1.741555262815382), 'hemo': np.float64(376.0408411486195), 'pcv': np.float64(277.26843036683795), 'wc': np.float64(7.692369393305453), 'rc': np.float64(152.3825267631457), 'htn': np.float64(168.09939759036135), 'dm': np.float64(145.75), 'cad': np.float64(21.044117647058826), 'appet': np.float64(52.33273381294971), 'pe': np.float64(48.707746478873254), 'ane': np.float64(37.6578947368421)}

Normalized Mathematical Scores
{'age': np.float64(0.04632012624498299), 'bp': np.float64(0.08768748863230913), 'sg': np.float64(0.6291628689310891), 'al': np.float64(0.27570257130402037), 'su': np.float64(0.07592230621857678), 'rbc': np.float64(0.06726783842996786), 'pc': np.float64(0.1264043996870825), 'pcc': np.float64(0.0581699059288733), 'ba': np.float64(0.027575635629676264), 'bgr': np.float64(0.14787268227408162), 'bu': np.float64(0.133934818651203), 'sc': np.float64(0.07888996503724914), 'sod': np.float64(0.10139654446287828), 'pot': np.float64(0.004631292860360031), 'hemo': np.float64(1.0), 'pcv': np.float64(0.7373359487228023), 'wc': np.float64(0.020456207282722415), 'rc': np.float64(0.4052286615934912), 'htn': np.float64(0.4470243101172216), 'dm': np.float64(0.38759087857267194), 'cad': np.float64(0.05596231936610772), 'appet': np.float64(0.1391676862893376), 'pe': np.float64(0.12952780961263433), 'ane': np.float64(0.10014309781303485)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.029206349206349208, 'sg': 0.03125763125763126, 'al': 0.03131881575727918, 'su': 0.02813852813852814, 'rbc': 0.028949545078577336, 'pc': 0.02904040404040404, 'pcc': 0.027809742999616416, 'ba': 0.02712049508554787, 'bgr': 0.030330882352941176, 'bu': 0.030158730158730156, 'sc': 0.029551337359792925, 'sod': 0.0293236301369863, 'pot': 0.027777777777777776, 'hemo': 0.032266458495966696, 'pcv': 0.031754032258064516, 'wc': 0.026973565905412694, 'rc': 0.03076923076923077, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.02964426877470356, 'pe': 0.029709507042253523, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['hemo', 'pcv', 'htn', 'al', 'dm', 'sg', 'rc', 'bgr', 'bu', 'pe', 'appet', 'sc', 'sod', 'bp', 'ane', 'pc', 'rbc', 'su', 'cad', 'age']

PRIMARY: completed 25/25 CV runs
======================================================================
PRIMARY CV PERFORMANCE SUMMARY
======================================================================

    Top_K Method Model  Acc_Mean  Acc_STD  F1_Mean  F1_STD  AUC_Mean  AUC_STD
0       5  ANOVA    LR    0.9750   0.0153   0.9797  0.0126    0.9955   0.0039
1       5  ANOVA    RF    0.9855   0.0112   0.9884  0.0091    0.9990   0.0011
2       5  ANOVA   XGB    0.9775   0.0149   0.9820  0.0119    0.9986   0.0014
3       5   DODA    LR    0.9585   0.0283   0.9651  0.0248    0.9948   0.0057
4       5   DODA    RF    0.9705   0.0219   0.9760  0.0187    0.9956   0.0062
5       5   DODA   XGB    0.9695   0.0198   0.9754  0.0162    0.9947   0.0065
6      10  ANOVA    LR    0.9890   0.0083   0.9911  0.0068    0.9999   0.0002
7      10  ANOVA    RF    0.9910   0.0092   0.9928  0.0073    0.9996   0.0007
8      10  ANOVA   XGB    0.9785   0.0147   0.9828  0.0117    0.9983   0.0017
9      10   DODA    LR    0.9860   0.0110   0.9886  0.0091    0.9999   0.0002
10     10   DODA    RF    0.9900   0.0095   0.9921  0.0076    0.9994   0.0012
11     10   DODA   XGB    0.9770   0.0179   0.9816  0.0143    0.9980   0.0023
12     15  ANOVA    LR    0.9900   0.0114   0.9919  0.0094    0.9999   0.0002
13     15  ANOVA    RF    0.9910   0.0099   0.9929  0.0078    0.9997   0.0006
14     15  ANOVA   XGB    0.9835   0.0152   0.9868  0.0121    0.9980   0.0024
15     15   DODA    LR    0.9905   0.0097   0.9923  0.0079    0.9999   0.0002
16     15   DODA    RF    0.9910   0.0099   0.9929  0.0078    0.9999   0.0002
17     15   DODA   XGB    0.9860   0.0137   0.9888  0.0109    0.9989   0.0015
18     20  ANOVA    LR    0.9905   0.0075   0.9923  0.0061    1.0000   0.0001
19     20  ANOVA    RF    0.9915   0.0094   0.9932  0.0074    0.9999   0.0003
20     20  ANOVA   XGB    0.9875   0.0114   0.9900  0.0091    0.9990   0.0015
21     20   DODA    LR    0.9905   0.0083   0.9923  0.0067    1.0000   0.0001
22     20   DODA    RF    0.9920   0.0087   0.9936  0.0070    0.9999   0.0002
23     20   DODA   XGB    0.9875   0.0125   0.9900  0.0100    0.9988   0.0018

In [12]:
# =============================================================================
# PRIMARY: PERFORMANCE SIGNIFICANCE TESTING
# =============================================================================

primary_perf_test = wilcoxon_holm_test(
    primary_cv_results, ["Top_K", "Model"], value_col="ROC_AUC"
)
print("=" * 70)
print("PRIMARY — ANOVA vs DODA ROC-AUC: SIGNIFICANCE TEST")
print("=" * 70)
display(primary_perf_test.round(4))

======================================================================
PRIMARY — ANOVA vs DODA ROC-AUC: SIGNIFICANCE TEST
======================================================================

    Top_K Model  ANOVA_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0       5    LR      0.9955     0.9948   1.0000   -0.1507  1.0000        False
1       5    RF      0.9990     0.9956   0.0105   -0.7136  0.1156        False
2       5   XGB      0.9986     0.9947   0.0043   -0.7677  0.0512        False
3      10    LR      0.9999     0.9999   0.1573   -0.2437  1.0000        False
4      10    RF      0.9996     0.9994   0.5106   -0.2338  1.0000        False
5      10   XGB      0.9983     0.9980   0.4499   -0.1674  1.0000        False
6      15    LR      0.9999     0.9999   1.0000    0.0000  1.0000        False
7      15    RF      0.9997     0.9999   0.2041    0.3535  1.0000        False
8      15   XGB      0.9980     0.9989   0.0120    0.4473  0.1196        False
9      20    LR      1.0000     1.0000   1.0000    0.0000  1.0000        False
10     20    RF      0.9999     0.9999   0.1975    0.2160  1.0000        False
11     20   XGB      0.9990     0.9988   0.2059   -0.1294  1.0000        False

# SENSITIVITY ANALYSIS (Complete-Case, n=158)

Identical pipeline, applied to the 158 rows with zero missing values — no imputation step at all. If the Primary and Sensitivity conclusions agree, the imputation choice wasn't driving the results.

## 1. Baseline (80/20 split)

In [13]:
# =============================================================================
# SENSITIVITY: TRAIN-TEST SPLIT + SCALING (no imputation needed)
# =============================================================================

Xs_train, Xs_test, ys_train, ys_test = train_test_split(
    X_sensitivity, y_sensitivity, test_size=0.2, random_state=42, stratify=y_sensitivity
)

scaler_s = StandardScaler()
Xs_train_scaled = pd.DataFrame(scaler_s.fit_transform(Xs_train), columns=Xs_train.columns)
Xs_test_scaled = pd.DataFrame(scaler_s.transform(Xs_test), columns=Xs_test.columns)
ys_train = ys_train.reset_index(drop=True)
ys_test = ys_test.reset_index(drop=True)

print("SENSITIVITY split:", Xs_train_scaled.shape, Xs_test_scaled.shape)

SENSITIVITY split: (126, 24) (32, 24)

In [14]:
# =============================================================================
# SENSITIVITY: ANOVA BASELINE TOP-K
# =============================================================================

anova_selector_s = SelectKBest(score_func=f_classif, k="all")
anova_selector_s.fit(Xs_train_scaled, ys_train)
anova_scores_s = pd.DataFrame({
    "Feature": Xs_train_scaled.columns, "ANOVA Score": anova_selector_s.scores_
}).sort_values("ANOVA Score", ascending=False).reset_index(drop=True)

anova_results_s = {}
for k in k_values:
    top_features = anova_scores_s.head(k)["Feature"].tolist()
    mask = Xs_train_scaled.columns.isin(top_features)
    anova_results_s[k] = {
        "features": top_features,
        "X_train": Xs_train_scaled.loc[:, mask],
        "X_test": Xs_test_scaled.loc[:, mask]
    }
    print(f"Top-{k}:", top_features)

Top-5: ['al', 'htn', 'pcv', 'hemo', 'sg']
Top-10: ['al', 'htn', 'pcv', 'hemo', 'sg', 'pc', 'rc', 'dm', 'sc', 'bu']
Top-15: ['al', 'htn', 'pcv', 'hemo', 'sg', 'pc', 'rc', 'dm', 'sc', 'bu', 'appet', 'sod', 'rbc', 'pe', 'bgr']
Top-20: ['al', 'htn', 'pcv', 'hemo', 'sg', 'pc', 'rc', 'dm', 'sc', 'bu', 'appet', 'sod', 'rbc', 'pe', 'bgr', 'pcc', 'ane', 'su', 'ba', 'cad']

In [15]:
# =============================================================================
# SENSITIVITY: BASELINE MODEL EVALUATION
# =============================================================================

sensitivity_baseline_results = []
for k in k_values:
    Xtr, Xts = anova_results_s[k]["X_train"], anova_results_s[k]["X_test"]
    models = make_models(ys_train)
    for model_name, model in models.items():
        model.fit(Xtr, ys_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        sensitivity_baseline_results.append({
            "Method": "ANOVA", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(ys_test, y_pred),
            "F1 Score": f1_score(ys_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(ys_test, y_prob)
        })

sensitivity_baseline_df = pd.DataFrame(sensitivity_baseline_results)
display(sensitivity_baseline_df)

   Method  Top-K Model  Accuracy  F1 Score  ROC-AUC
0   ANOVA      5    LR   1.00000  1.000000      1.0
1   ANOVA      5    RF   1.00000  1.000000      1.0
2   ANOVA      5   XGB   0.96875  0.941176      1.0
3   ANOVA     10    LR   1.00000  1.000000      1.0
4   ANOVA     10    RF   1.00000  1.000000      1.0
5   ANOVA     10   XGB   0.96875  0.941176      1.0
6   ANOVA     15    LR   1.00000  1.000000      1.0
7   ANOVA     15    RF   1.00000  1.000000      1.0
8   ANOVA     15   XGB   0.96875  0.941176      1.0
9   ANOVA     20    LR   1.00000  1.000000      1.0
10  ANOVA     20    RF   1.00000  1.000000      1.0
11  ANOVA     20   XGB   0.96875  0.941176      1.0

In [16]:
# =============================================================================
# SENSITIVITY: RANK FUSION DODA + EVALUATION
# =============================================================================

sensitivity_doda_results_by_k = {}
for k in k_values:
    operator = SklearnAdapter(SelectKBest(score_func=f_classif, k="all"))
    selector = DODASelector(operators=[operator], provider=provider, fusion=RankFusion(), top_k=k)
    X_train_sel = selector.fit_transform(Xs_train_scaled, ys_train)
    X_test_sel = selector.transform(Xs_test_scaled)
    features = selector.get_selected_features()
    sensitivity_doda_results_by_k[k] = {"X_train": X_train_sel, "X_test": X_test_sel, "features": features}
    print(f"Top-{k}:", features)

sensitivity_doda_results = []
for k in k_values:
    Xtr, Xts = sensitivity_doda_results_by_k[k]["X_train"], sensitivity_doda_results_by_k[k]["X_test"]
    models = make_models(ys_train)
    for model_name, model in models.items():
        model.fit(Xtr, ys_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        sensitivity_doda_results.append({
            "Method": "ANOVA + Rank Fusion", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(ys_test, y_pred),
            "F1 Score": f1_score(ys_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(ys_test, y_prob)
        })

sensitivity_doda_df = pd.DataFrame(sensitivity_doda_results)
sensitivity_comparison_df = pd.concat([sensitivity_baseline_df, sensitivity_doda_df], ignore_index=True)
display(sensitivity_comparison_df)

os.makedirs("../../../results/ckd/sensitivity", exist_ok=True)
sensitivity_comparison_df.to_csv("../../../results/ckd/sensitivity/anova_rankfusion_80_20_comparison.csv", index=False)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}

Normalized Mathematical Scores
{'age': np.float64(0.01604378000244671), 'bp': np.float64(0.01886825431505373), 'sg': np.float64(0.22857294994675942), 'al': np.float64(1.0), 'su': np.float64(0.05109941060903784), 'rbc': np.float64(0.08021052631579025), 'pc': np.float64(0.2124363636363658), 'pcc': np.float64(0.06289523809523871), 'ba': np.float64(0.04233333333333376), 'bgr': np.float64(0.06662498274927028), 'bu': np.float64(0.11008501165787893), 'sc': np.float64(0.13808819279726586), 'sod': np.float64(0.08858551454500865), 'pot': np.float64(0.0037765278111395956), 'hemo': np.float64(0.27754607543364185), 'pcv': np.float64(0.2781025079732088), 'wc': np.float64(0.02109368102815273), 'rc': np.float64(0.1524345358354843), 'htn': np.float64(0.47413333333333707), 'dm': np.float64(0.14514285714285882), 'cad': np.float64(0.026340740740740998), 'appet': np.float64(0.10160000000000116), 'pe': np.float64(0.07112000000000075), 'ane': np.float64(0.06289523809523867)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.029236022193768675, 'pe': 0.029138513513513514, 'ane': 0.028612012987012988}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']
Top-5: ['al', 'htn', 'hemo', 'pcv', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}

Normalized Mathematical Scores
{'age': np.float64(0.01604378000244671), 'bp': np.float64(0.01886825431505373), 'sg': np.float64(0.22857294994675942), 'al': np.float64(1.0), 'su': np.float64(0.05109941060903784), 'rbc': np.float64(0.08021052631579025), 'pc': np.float64(0.2124363636363658), 'pcc': np.float64(0.06289523809523871), 'ba': np.float64(0.04233333333333376), 'bgr': np.float64(0.06662498274927028), 'bu': np.float64(0.11008501165787893), 'sc': np.float64(0.13808819279726586), 'sod': np.float64(0.08858551454500865), 'pot': np.float64(0.0037765278111395956), 'hemo': np.float64(0.27754607543364185), 'pcv': np.float64(0.2781025079732088), 'wc': np.float64(0.02109368102815273), 'rc': np.float64(0.1524345358354843), 'htn': np.float64(0.47413333333333707), 'dm': np.float64(0.14514285714285882), 'cad': np.float64(0.026340740740740998), 'appet': np.float64(0.10160000000000116), 'pe': np.float64(0.07112000000000075), 'ane': np.float64(0.06289523809523867)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.029236022193768675, 'pe': 0.029138513513513514, 'ane': 0.028612012987012988}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu']
Top-10: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}

Normalized Mathematical Scores
{'age': np.float64(0.01604378000244671), 'bp': np.float64(0.01886825431505373), 'sg': np.float64(0.22857294994675942), 'al': np.float64(1.0), 'su': np.float64(0.05109941060903784), 'rbc': np.float64(0.08021052631579025), 'pc': np.float64(0.2124363636363658), 'pcc': np.float64(0.06289523809523871), 'ba': np.float64(0.04233333333333376), 'bgr': np.float64(0.06662498274927028), 'bu': np.float64(0.11008501165787893), 'sc': np.float64(0.13808819279726586), 'sod': np.float64(0.08858551454500865), 'pot': np.float64(0.0037765278111395956), 'hemo': np.float64(0.27754607543364185), 'pcv': np.float64(0.2781025079732088), 'wc': np.float64(0.02109368102815273), 'rc': np.float64(0.1524345358354843), 'htn': np.float64(0.47413333333333707), 'dm': np.float64(0.14514285714285882), 'cad': np.float64(0.026340740740740998), 'appet': np.float64(0.10160000000000116), 'pe': np.float64(0.07112000000000075), 'ane': np.float64(0.06289523809523867)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.029236022193768675, 'pe': 0.029138513513513514, 'ane': 0.028612012987012988}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'appet', 'pe', 'bgr']
Top-15: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'appet', 'pe', 'bgr']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bb47d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.297231773208832), 'bp': np.float64(16.81422987955652), 'sg': np.float64(203.6901803675013), 'al': np.float64(891.1386076740316), 'su': np.float64(45.53665762310162), 'rbc': np.float64(71.47869674185459), 'pc': np.float64(189.3102453102453), 'pcc': np.float64(56.04837490551773), 'ba': np.float64(37.724867724867714), 'bgr': np.float64(59.3720943634911), 'bu': np.float64(98.10100401458176), 'sc': np.float64(123.05571986557874), 'sod': np.float64(78.94197209172668), 'pot': np.float64(3.3654097354611974), 'hemo': np.float64(247.33202322732737), 'pcv': np.float64(247.82788174590155), 'wc': np.float64(18.79739354214816), 'rc': np.float64(135.84030002587076), 'htn': np.float64(422.5185185185175), 'dm': np.float64(129.3424036281181), 'cad': np.float64(23.473251028806573), 'appet': np.float64(90.53968253968264), 'pe': np.float64(63.3777777777778), 'ane': np.float64(56.048374905517704)}

Normalized Mathematical Scores
{'age': np.float64(0.01604378000244671), 'bp': np.float64(0.01886825431505373), 'sg': np.float64(0.22857294994675942), 'al': np.float64(1.0), 'su': np.float64(0.05109941060903784), 'rbc': np.float64(0.08021052631579025), 'pc': np.float64(0.2124363636363658), 'pcc': np.float64(0.06289523809523871), 'ba': np.float64(0.04233333333333376), 'bgr': np.float64(0.06662498274927028), 'bu': np.float64(0.11008501165787893), 'sc': np.float64(0.13808819279726586), 'sod': np.float64(0.08858551454500865), 'pot': np.float64(0.0037765278111395956), 'hemo': np.float64(0.27754607543364185), 'pcv': np.float64(0.2781025079732088), 'wc': np.float64(0.02109368102815273), 'rc': np.float64(0.1524345358354843), 'htn': np.float64(0.47413333333333707), 'dm': np.float64(0.14514285714285882), 'cad': np.float64(0.026340740740740998), 'appet': np.float64(0.10160000000000116), 'pe': np.float64(0.07112000000000075), 'ane': np.float64(0.06289523809523867)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.029236022193768675, 'pe': 0.029138513513513514, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'appet', 'pe', 'bgr', 'ane', 'pcc', 'cad', 'bp', 'su']
Top-20: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'appet', 'pe', 'bgr', 'ane', 'pcc', 'cad', 'bp', 'su']

                 Method  Top-K Model  Accuracy  F1 Score  ROC-AUC
0                 ANOVA      5    LR   1.00000  1.000000      1.0
1                 ANOVA      5    RF   1.00000  1.000000      1.0
2                 ANOVA      5   XGB   0.96875  0.941176      1.0
3                 ANOVA     10    LR   1.00000  1.000000      1.0
4                 ANOVA     10    RF   1.00000  1.000000      1.0
5                 ANOVA     10   XGB   0.96875  0.941176      1.0
6                 ANOVA     15    LR   1.00000  1.000000      1.0
7                 ANOVA     15    RF   1.00000  1.000000      1.0
8                 ANOVA     15   XGB   0.96875  0.941176      1.0
9                 ANOVA     20    LR   1.00000  1.000000      1.0
10                ANOVA     20    RF   1.00000  1.000000      1.0
11                ANOVA     20   XGB   0.96875  0.941176      1.0
12  ANOVA + Rank Fusion      5    LR   1.00000  1.000000      1.0
13  ANOVA + Rank Fusion      5    RF   0.96875  0.941176      1.0
14  ANOVA + Rank Fusion      5   XGB   0.96875  0.941176      1.0
15  ANOVA + Rank Fusion     10    LR   1.00000  1.000000      1.0
16  ANOVA + Rank Fusion     10    RF   0.96875  0.941176      1.0
17  ANOVA + Rank Fusion     10   XGB   0.96875  0.941176      1.0
18  ANOVA + Rank Fusion     15    LR   1.00000  1.000000      1.0
19  ANOVA + Rank Fusion     15    RF   1.00000  1.000000      1.0
20  ANOVA + Rank Fusion     15   XGB   0.96875  0.941176      1.0
21  ANOVA + Rank Fusion     20    LR   1.00000  1.000000      1.0
22  ANOVA + Rank Fusion     20    RF   1.00000  1.000000      1.0
23  ANOVA + Rank Fusion     20   XGB   0.96875  0.941176      1.0

## 2. Feature-Selection Stability (25-run repeated CV)

In [17]:
# =============================================================================
# SENSITIVITY: STABILITY ANALYSIS
# =============================================================================

sensitivity_jaccard_df = run_stability_analysis(
    X_sensitivity, y_sensitivity, k_values, do_impute=False, label="SENSITIVITY"
)

sensitivity_stability_summary = sensitivity_jaccard_df.groupby(["Top_K", "Method"])["Jaccard"].agg(
    ["mean", "std"]
).reset_index()
print("\n" + "=" * 70)
print("SENSITIVITY STABILITY SUMMARY")
print("=" * 70)
display(sensitivity_stability_summary)

======================================================================
SENSITIVITY STABILITY — TOP-5
======================================================================
ANOVA: mean Jaccard = 0.7833 (std 0.1590)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3046e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3082f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e308590>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35fec0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.018927643236864883), 'bp': np.float64(0.018018612331350305), 'sg': np.float64(0.245820557286469), 'al': np.float64(1.0), 'su': np.float64(0.057641259006446725), 'rbc': np.float64(0.07791874919902601), 'pc': np.float64(0.22401640394719968), 'pcc': np.float64(0.06906434588095484), 'ba': np.float64(0.04675124951941561), 'bgr': np.float64(0.0935534014922953), 'bu': np.float64(0.12612060112453308), 'sc': np.float64(0.1621131105806818), 'sod': np.float64(0.12848579566532084), 'pot': np.float64(0.004211214732875464), 'hemo': np.float64(0.34485420143348045), 'pcv': np.float64(0.3352509595236918), 'wc': np.float64(0.03229543670935517), 'rc': np.float64(0.25654847721334795), 'htn': np.float64(0.4675124951941558), 'dm': np.float64(0.22401640394719968), 'cad': np.float64(0.04045781208410966), 'appet': np.float64(0.08765859284890438), 'pe': np.float64(0.08765859284890423), 'ane': np.float64(0.0609798906774986)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02964254577157803, 'pc': 0.03007688828584351, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.030117753623188408, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35ede0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores

DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.011803916590412293), 'bp': np.float64(0.01451254889614622), 'sg': np.float64(0.1633156990169624), 'al': np.float64(1.0), 'su': np.float64(0.04224058769513313), 'rbc': np.float64(0.05068870523415977), 'pc': np.float64(0.21965105601469223), 'pcc': np.float64(0.03484848484848484), 'ba': np.float64(0.03484848484848484), 'bgr': np.float64(0.06477545670503661), 'bu': np.float64(0.0955613249334403), 'sc': np.float64(0.12257014080637094), 'sod': np.float64(0.06617145574790655), 'pot': np.float64(0.0034078183343879123), 'hemo': np.float64(0.2317633251347633), 'pcv': np.float64(0.22262021142870939), 'wc': np.float64(0.014922472921445515), 'rc': np.float64(0.11241800430576719), 'htn': np.float64(0.25661157024793385), 'dm': np.float64(0.12867132867132863), 'cad': np.float64(0.026319135410044495), 'appet': np.float64(0.06402783819051769), 'pe': np.float64(0.08050559066601844), 'ane': np.float64(0.04492862509391432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'rc']
DODA: mean Jaccard = 0.9108 (std 0.0954)

======================================================================
SENSITIVITY STABILITY — TOP-15
======================================================================
ANOVA: mean Jaccard = 0.9280 (std 0.0733)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327470>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'pe', 'rbc', 'sod', 'bgr', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327710>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rbc', 'bu', 'rc', 'pe', 'sod', 'bgr', 'appet']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327ef0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'ane']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3454f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310f20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.02592363812810592), 'bp': np.float64(0.019433680541504825), 'sg': np.float64(0.3338522536531136), 'al': np.float64(1.0), 'su': np.float64(0.06785258103171045), 'rbc': np.float64(0.10254412622085562), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.05412051106100715), 'ba': np.float64(0.03367498466018221), 'bgr': np.float64(0.10981639191222901), 'bu': np.float64(0.18118742746022087), 'sc': np.float64(0.21313895847733438), 'sod': np.float64(0.13811911241835761), 'pot': np.float64(0.004447608119905612), 'hemo': np.float64(0.40726794182970727), 'pcv': np.float64(0.37589428356496796), 'wc': np.float64(0.02431446188519591), 'rc': np.float64(0.18302875430826873), 'htn': np.float64(0.7533575139692192), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.03996591586043604), 'appet': np.float64(0.11545709026348179), 'pe': np.float64(0.14612537986471927), 'ane': np.float64(0.090922458582492)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02792120864410021, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'pc', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'appet', 'ane', 'cad', 'su', 'pcc', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22d280>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.02394167469674263), 'bp': np.float64(0.023435784512764235), 'sg': np.float64(0.28136628296595967), 'al': np.float64(1.0), 'su': np.float64(0.05870097953085933), 'rbc': np.float64(0.08559687027111833), 'pc': np.float64(0.25349842349523494), 'pcc': np.float64(0.07542101856056578), 'ba': np.float64(0.06613002352049607), 'bgr': np.float64(0.0810981749216549), 'bu': np.float64(0.1388484575204332), 'sc': np.float64(0.15583223673291507), 'sod': np.float64(0.12118290237580666), 'pot': np.float64(0.006359989549386573), 'hemo': np.float64(0.46408357391759525), 'pcv': np.float64(0.4732149117127621), 'wc': np.float64(0.045016399872454635), 'rc': np.float64(0.18898929683624632), 'htn': np.float64(0.6452687143515072), 'dm': np.float64(0.25349842349523494), 'cad': np.float64(0.05761327806709888), 'appet': np.float64(0.10916200054818742), 'pe': np.float64(0.10916200054818731), 'ane': np.float64(0.08559687027111833)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.029236022193768675, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'bu', 'rc', 'pc', 'sod', 'rbc', 'pe', 'ane', 'appet', 'bgr', 'pcc', 'cad', 'bp', 'su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22ed50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01005815636350061), 'bp': np.float64(0.01676348167177102), 'sg': np.float64(0.24697575555469048), 'al': np.float64(1.0), 'su': np.float64(0.05106619851671104), 'rbc': np.float64(0.09371095376926272), 'pc': np.float64(0.2481920411949564), 'pcc': np.float64(0.0567698241674664), 'ba': np.float64(0.036523243520328035), 'bgr': np.float64(0.08348959475276603), 'bu': np.float64(0.12822013656765224), 'sc': np.float64(0.14247642612635503), 'sod': np.float64(0.12786058049974805), 'pot': np.float64(0.004779033663709402), 'hemo': np.float64(0.3521382903715432), 'pcv': np.float64(0.3547335989744239), 'wc': np.float64(0.02808233655537081), 'rc': np.float64(0.2392608123981195), 'htn': np.float64(0.3857767596834649), 'dm': np.float64(0.19174702848172218), 'cad': np.float64(0.030774214447683804), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.08309037900874629), 'ane': np.float64(0.07348128755875523)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.02904040404040404, 'pe': 0.028958333333333336, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'rc', 'bu', 'rbc', 'sod', 'bgr', 'appet', 'pe', 'ane', 'pcc', 'cad', 'bp', 'su']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3268a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}

Normalized Mathematical Scores
{'age': np.float64(0.016991864206822825), 'bp': np.float64(0.024759231558358973), 'sg': np.float64(0.3918883013331342), 'al': np.float64(1.0), 'su': np.float64(0.07529471415895557), 'rbc': np.float64(0.1082361516034986), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.07529471415895556), 'ba': np.float64(0.06614431486880472), 'bgr': np.float64(0.11035689701495596), 'bu': np.float64(0.17035671988944603), 'sc': np.float64(0.18490305565527543), 'sod': np.float64(0.13467825948763948), 'pot': np.float64(0.004719867906432446), 'hemo': np.float64(0.4745620648500175), 'pcv': np.float64(0.4130373904817077), 'wc': np.float64(0.06986662070125173), 'rc': np.float64(0.18341375590811818), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.05772594752186594), 'appet': np.float64(0.0962099125364429), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.06614431486880472)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028665028665028666, 'rbc': 0.030017921146953404, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027912386121341344, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029910714285714284, 'pot': 0.02821869488536155, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.028083267871170464, 'rc': 0.030090497737556562, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'hemo', 'htn', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'rbc', 'sod', 'bgr', 'pe', 'appet', 'su', 'ane', 'bp', 'pcc', 'cad']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22cb60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores

   Top_K Method      mean       std
0      5  ANOVA  0.783333  0.159256
1      5   DODA  0.763651  0.163215
2     10  ANOVA  0.972121  0.065620
3     10   DODA  0.910808  0.095570
4     15  ANOVA  0.927966  0.073419
5     15   DODA  0.922083  0.060670
6     20  ANOVA  0.963810  0.046305
7     20   DODA  0.984791  0.035692

In [18]:
sensitivity_stability_test = wilcoxon_holm_test(sensitivity_jaccard_df, ["Top_K"], value_col="Jaccard")
print("=" * 70)
print("SENSITIVITY — ANOVA vs DODA STABILITY: SIGNIFICANCE TEST")
print("=" * 70)
display(sensitivity_stability_test.round(4))

======================================================================
SENSITIVITY — ANOVA vs DODA STABILITY: SIGNIFICANCE TEST
======================================================================

   Top_K  ANOVA_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0      5      0.7833     0.7637   0.0001   -0.1219  0.0001         True
1     10      0.9721     0.9108   0.0000   -0.7010  0.0000         True
2     15      0.9280     0.9221   0.0000   -0.0873  0.0000         True
3     20      0.9638     0.9848   0.0000    0.4923  0.0000         True

## 3. Predictive Performance (25-run repeated CV)

In [19]:
# =============================================================================
# SENSITIVITY: CV PREDICTIVE PERFORMANCE
# =============================================================================

sensitivity_cv_results = run_cv_performance(
    X_sensitivity, y_sensitivity, k_values, do_impute=False, label="SENSITIVITY"
)

sensitivity_cv_summary = sensitivity_cv_results.groupby(["Top_K", "Method", "Model"]).agg(
    {"Accuracy": ["mean", "std"], "F1": ["mean", "std"], "ROC_AUC": ["mean", "std"]}
).reset_index()
sensitivity_cv_summary.columns = ["Top_K", "Method", "Model", "Acc_Mean", "Acc_STD",
                                   "F1_Mean", "F1_STD", "AUC_Mean", "AUC_STD"]

sensitivity_cv_results.to_csv("../../../results/ckd/sensitivity/cv_performance_runs.csv", index=False)
sensitivity_cv_summary.to_csv("../../../results/ckd/sensitivity/cv_performance_summary.csv", index=False)

print("=" * 70)
print("SENSITIVITY CV PERFORMANCE SUMMARY")
print("=" * 70)
display(sensitivity_cv_summary.round(4))

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310380>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3732c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3ad2b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'pe', 'rbc', 'sod', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e347fb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.655838595793952), 'bp': np.float64(20.010236819882145), 'sg': np.float64(215.49980646808285), 'al': np.float64(896.8553459119493), 'su': np.float64(47.11007871983482), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.268438004244295), 'bu': np.float64(106.02689573659777), 'sc': np.float64(126.1858727117594), 'sod': np.float64(81.79112984436362), 'pot': np.float64(4.282811103195126), 'hemo': np.float64(265.19343917266224), 'pcv': np.float64(246.16690559453045), 'wc': np.float64(19.442229376915883), 'rc': np.float64(117.62426052073852), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01188133475968611), 'bp': np.float64(0.022311554378409978), 'sg': np.float64(0.24028379543075168), 'al': np.float64(1.0), 'su': np.float64(0.05252806813782426), 'rbc': np.float64(0.07066666666666671), 'pc': np.float64(0.18507936507936515), 'pcc': np.float64(0.04828157349896482), 'ba': np.float64(0.04828157349896482), 'bgr': np.float64(0.06273970296405924), 'bu': np.float64(0.11822073227292464), 'sc': np.float64(0.14069813296752984), 'sod': np.float64(0.09119768334680099), 'pot': np.float64(0.004775364413801019), 'hemo': np.float64(0.2956925443790555), 'pcv': np.float64(0.2744778260135369), 'wc': np.float64(0.021678222096280692), 'rc': np.float64(0.13115187533518535), 'htn': np.float64(0.389387755102041), 'dm': np.float64(0.18507936507936515), 'cad': np.float64(0.031062271062271076), 'appet': np.float64(0.08973544973544971), 'pe': np.float64(0.100952380952381), 'ane': np.float64(0.06249433106575968)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029910714285714284, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'pe', 'rbc', 'sod', 'bgr', 'appet', 'ane', 'bp', 'cad', 'su', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22c260>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666cf8c80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rbc', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e346570>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rbc', 'bu', 'rc', 'pe', 'sod', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e373ec0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.44545604641465), 'bp': np.float64(13.700947235708192), 'sg': np.float64(197.56958877642475), 'al': np.float64(835.2369237978095), 'su': np.float64(48.70931537598205), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(251.4991181657849), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(75.89714788108624), 'bu': np.float64(104.46037047809341), 'sc': np.float64(127.64961732920857), 'sod': np.float64(79.43404525261117), 'pot': np.float64(0.6472020815416297), 'hemo': np.float64(303.2352212539296), 'pcv': np.float64(321.55957557453945), 'wc': np.float64(23.76221354152163), 'rc': np.float64(132.58131538025484), 'htn': np.float64(349.2244897959184), 'dm': np.float64(189.31024531024528), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.008914184507744552), 'bp': np.float64(0.01640366564903548), 'sg': np.float64(0.23654316894669702), 'al': np.float64(1.0), 'su': np.float64(0.058317962231005716), 'rbc': np.float64(0.09635555555555554), 'pc': np.float64(0.30111111111111116), 'pcc': np.float64(0.045166666666666674), 'ba': np.float64(0.03902399999999999), 'bgr': np.float64(0.09086900461246741), 'bu': np.float64(0.12506675351840735), 'sc': np.float64(0.15283042893839954), 'sod': np.float64(0.0951036083168184), 'pot': np.float64(0.0007748724500813635), 'hemo': np.float64(0.3630529405658022), 'pcv': np.float64(0.38499205005498677), 'wc': np.float64(0.028449668428779714), 'rc': np.float64(0.15873497878591097), 'htn': np.float64(0.41811428571428566), 'dm': np.float64(0.2266545454545454), 'cad': np.float64(0.03902399999999999), 'appet': np.float64(0.09635555555555547), 'pe': np.float64(0.09635555555555554), 'ane': np.float64(0.05912727272727272)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.0293236301369863, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029709507042253523, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rbc', 'bu', 'rc', 'pe', 'sod', 'bgr', 'appet', 'ane', 'cad', 'bp', 'su', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e305a30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666f1e930>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22c380>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e345d60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.381760528995056), 'bp': np.float64(12.217218950852835), 'sg': np.float64(181.6809924399001), 'al': np.float64(673.7884803123981), 'su': np.float64(42.84967530437423), 'rbc': np.float64(49.38528138528139), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(72.13221221985654), 'bu': np.float64(109.19023337158463), 'sc': np.float64(120.36766752189868), 'sod': np.float64(92.5271320176052), 'pot': np.float64(3.967718926950147), 'hemo': np.float64(280.8257333623504), 'pcv': np.float64(260.0695612805941), 'wc': np.float64(21.292718892715065), 'rc': np.float64(133.06336608336355), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.027281203324331784), 'bp': np.float64(0.018132127971657207), 'sg': np.float64(0.26964098934381425), 'al': np.float64(1.0), 'su': np.float64(0.06359514381205691), 'rbc': np.float64(0.07329493279906506), 'pc': np.float64(0.3224977043158862), 'pcc': np.float64(0.07329493279906506), 'ba': np.float64(0.04134585952767773), 'bgr': np.float64(0.10705468307563357), 'bu': np.float64(0.16205417065153624), 'sc': np.float64(0.178643106908107), 'sod': np.float64(0.1373237072481642), 'pot': np.float64(0.005888671360351156), 'hemo': np.float64(0.41678618968396014), 'pcv': np.float64(0.3859810146353561), 'wc': np.float64(0.031601488471341664), 'rc': np.float64(0.19748536814056172), 'htn': np.float64(0.6270788695031122), 'dm': np.float64(0.24635241301907976), 'cad': np.float64(0.048374655647382934), 'appet': np.float64(0.11944359419106888), 'pe': np.float64(0.1343740434649526), 'ane': np.float64(0.09406183042546684)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02928692699490662, 'pc': 0.030536130536130537, 'pcc': 0.028309409888357256, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'ane', 'appet', 'cad', 'pcc', 'su', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e279d00>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.018927643236864883), 'bp': np.float64(0.018018612331350305), 'sg': np.float64(0.245820557286469), 'al': np.float64(1.0), 'su': np.float64(0.057641259006446725), 'rbc': np.float64(0.07791874919902601), 'pc': np.float64(0.22401640394719968), 'pcc': np.float64(0.06906434588095484), 'ba': np.float64(0.04675124951941561), 'bgr': np.float64(0.0935534014922953), 'bu': np.float64(0.12612060112453308), 'sc': np.float64(0.1621131105806818), 'sod': np.float64(0.12848579566532084), 'pot': np.float64(0.004211214732875464), 'hemo': np.float64(0.34485420143348045), 'pcv': np.float64(0.3352509595236918), 'wc': np.float64(0.03229543670935517), 'rc': np.float64(0.25654847721334795), 'htn': np.float64(0.4675124951941558), 'dm': np.float64(0.22401640394719968), 'cad': np.float64(0.04045781208410966), 'appet': np.float64(0.08765859284890438), 'pe': np.float64(0.08765859284890423), 'ane': np.float64(0.0609798906774986)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02964254577157803, 'pc': 0.03007688828584351, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.030117753623188408, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e328e90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.018927643236864883), 'bp': np.float64(0.018018612331350305), 'sg': np.float64(0.245820557286469), 'al': np.float64(1.0), 'su': np.float64(0.057641259006446725), 'rbc': np.float64(0.07791874919902601), 'pc': np.float64(0.22401640394719968), 'pcc': np.float64(0.06906434588095484), 'ba': np.float64(0.04675124951941561), 'bgr': np.float64(0.0935534014922953), 'bu': np.float64(0.12612060112453308), 'sc': np.float64(0.1621131105806818), 'sod': np.float64(0.12848579566532084), 'pot': np.float64(0.004211214732875464), 'hemo': np.float64(0.34485420143348045), 'pcv': np.float64(0.3352509595236918), 'wc': np.float64(0.03229543670935517), 'rc': np.float64(0.25654847721334795), 'htn': np.float64(0.4675124951941558), 'dm': np.float64(0.22401640394719968), 'cad': np.float64(0.04045781208410966), 'appet': np.float64(0.08765859284890438), 'pe': np.float64(0.08765859284890423), 'ane': np.float64(0.0609798906774986)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02964254577157803, 'pc': 0.03007688828584351, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.030117753623188408, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'rc', 'sg', 'bu', 'sod']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3094c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.018927643236864883), 'bp': np.float64(0.018018612331350305), 'sg': np.float64(0.245820557286469), 'al': np.float64(1.0), 'su': np.float64(0.057641259006446725), 'rbc': np.float64(0.07791874919902601), 'pc': np.float64(0.22401640394719968), 'pcc': np.float64(0.06906434588095484), 'ba': np.float64(0.04675124951941561), 'bgr': np.float64(0.0935534014922953), 'bu': np.float64(0.12612060112453308), 'sc': np.float64(0.1621131105806818), 'sod': np.float64(0.12848579566532084), 'pot': np.float64(0.004211214732875464), 'hemo': np.float64(0.34485420143348045), 'pcv': np.float64(0.3352509595236918), 'wc': np.float64(0.03229543670935517), 'rc': np.float64(0.25654847721334795), 'htn': np.float64(0.4675124951941558), 'dm': np.float64(0.22401640394719968), 'cad': np.float64(0.04045781208410966), 'appet': np.float64(0.08765859284890438), 'pe': np.float64(0.08765859284890423), 'ane': np.float64(0.0609798906774986)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02964254577157803, 'pc': 0.03007688828584351, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.030117753623188408, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'rc', 'sg', 'bu', 'sod', 'pc', 'bgr', 'rbc', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30b440>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.664168065672506), 'bp': np.float64(13.95989750179198), 'sg': np.float64(190.44917113743836), 'al': np.float64(774.7487567343558), 'su': np.float64(44.65749375184759), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(72.4803814944258), 'bu': np.float64(97.71177891982158), 'sc': np.float64(125.59693087272237), 'sod': np.float64(99.54421044973179), 'pot': np.float64(3.262633378636668), 'hemo': np.float64(267.1753638152081), 'pcv': np.float64(259.7352640849801), 'wc': np.float64(25.020849438765993), 'rc': np.float64(198.7606137631335), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.018927643236864883), 'bp': np.float64(0.018018612331350305), 'sg': np.float64(0.245820557286469), 'al': np.float64(1.0), 'su': np.float64(0.057641259006446725), 'rbc': np.float64(0.07791874919902601), 'pc': np.float64(0.22401640394719968), 'pcc': np.float64(0.06906434588095484), 'ba': np.float64(0.04675124951941561), 'bgr': np.float64(0.0935534014922953), 'bu': np.float64(0.12612060112453308), 'sc': np.float64(0.1621131105806818), 'sod': np.float64(0.12848579566532084), 'pot': np.float64(0.004211214732875464), 'hemo': np.float64(0.34485420143348045), 'pcv': np.float64(0.3352509595236918), 'wc': np.float64(0.03229543670935517), 'rc': np.float64(0.25654847721334795), 'htn': np.float64(0.4675124951941558), 'dm': np.float64(0.22401640394719968), 'cad': np.float64(0.04045781208410966), 'appet': np.float64(0.08765859284890438), 'pe': np.float64(0.08765859284890423), 'ane': np.float64(0.0609798906774986)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02964254577157803, 'pc': 0.03007688828584351, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.029709507042253523, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.030117753623188408, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.03076923076923077, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'rc', 'sg', 'bu', 'sod', 'pc', 'bgr', 'rbc', 'pe', 'appet', 'ane', 'pcc', 'cad', 'su', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e306240>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.023518692608961972), 'bp': np.float64(0.024142219353067446), 'sg': np.float64(0.41446195114472145), 'al': np.float64(1.0), 'su': np.float64(0.05957953299275153), 'rbc': np.float64(0.12152831057234931), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.05772594752186594), 'ba': np.float64(0.05772594752186594), 'bgr': np.float64(0.10064133931867617), 'bu': np.float64(0.18218901318988576), 'sc': np.float64(0.17265884709058657), 'sod': np.float64(0.13106385478532945), 'pot': np.float64(0.005047497437727378), 'hemo': np.float64(0.49839806279822385), 'pcv': np.float64(0.4474227559025183), 'wc': np.float64(0.05778070003297799), 'rc': np.float64(0.17770276900573176), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.04995514689392245), 'appet': np.float64(0.08527696793002909), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.08527696793002919)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030798389007344232, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.027912386121341344, 'rc': 0.030090497737556562, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['al', 'hemo', 'htn', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd25d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.023518692608961972), 'bp': np.float64(0.024142219353067446), 'sg': np.float64(0.41446195114472145), 'al': np.float64(1.0), 'su': np.float64(0.05957953299275153), 'rbc': np.float64(0.12152831057234931), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.05772594752186594), 'ba': np.float64(0.05772594752186594), 'bgr': np.float64(0.10064133931867617), 'bu': np.float64(0.18218901318988576), 'sc': np.float64(0.17265884709058657), 'sod': np.float64(0.13106385478532945), 'pot': np.float64(0.005047497437727378), 'hemo': np.float64(0.49839806279822385), 'pcv': np.float64(0.4474227559025183), 'wc': np.float64(0.05778070003297799), 'rc': np.float64(0.17770276900573176), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.04995514689392245), 'appet': np.float64(0.08527696793002909), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.08527696793002919)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030798389007344232, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.027912386121341344, 'rc': 0.030090497737556562, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['al', 'hemo', 'htn', 'pcv', 'dm', 'sc', 'bu', 'sg', 'pc', 'rbc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666f1e930>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.023518692608961972), 'bp': np.float64(0.024142219353067446), 'sg': np.float64(0.41446195114472145), 'al': np.float64(1.0), 'su': np.float64(0.05957953299275153), 'rbc': np.float64(0.12152831057234931), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.05772594752186594), 'ba': np.float64(0.05772594752186594), 'bgr': np.float64(0.10064133931867617), 'bu': np.float64(0.18218901318988576), 'sc': np.float64(0.17265884709058657), 'sod': np.float64(0.13106385478532945), 'pot': np.float64(0.005047497437727378), 'hemo': np.float64(0.49839806279822385), 'pcv': np.float64(0.4474227559025183), 'wc': np.float64(0.05778070003297799), 'rc': np.float64(0.17770276900573176), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.04995514689392245), 'appet': np.float64(0.08527696793002909), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.08527696793002919)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030798389007344232, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.027912386121341344, 'rc': 0.030090497737556562, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['al', 'hemo', 'htn', 'pcv', 'dm', 'sc', 'bu', 'sg', 'pc', 'rbc', 'rc', 'sod', 'pe', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310290>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.756936768639216), 'bp': np.float64(15.148172152735938), 'sg': np.float64(260.0564966659274), 'al': np.float64(627.4556589517215), 'su': np.float64(37.38351513400274), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(36.22047244094489), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(63.14797787998375), 'bu': np.float64(114.31552732482365), 'sc': np.float64(108.33577067506852), 'sod': np.float64(82.23675736908163), 'pot': np.float64(3.167080830846358), 'hemo': np.float64(312.722684913321), 'pcv': np.float64(280.73794013480983), 'wc': np.float64(36.254827213883964), 'rc': np.float64(111.50060802403696), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(53.50751610594123), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.023518692608961972), 'bp': np.float64(0.024142219353067446), 'sg': np.float64(0.41446195114472145), 'al': np.float64(1.0), 'su': np.float64(0.05957953299275153), 'rbc': np.float64(0.12152831057234931), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.05772594752186594), 'ba': np.float64(0.05772594752186594), 'bgr': np.float64(0.10064133931867617), 'bu': np.float64(0.18218901318988576), 'sc': np.float64(0.17265884709058657), 'sod': np.float64(0.13106385478532945), 'pot': np.float64(0.005047497437727378), 'hemo': np.float64(0.49839806279822385), 'pcv': np.float64(0.4474227559025183), 'wc': np.float64(0.05778070003297799), 'rc': np.float64(0.17770276900573176), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.04995514689392245), 'appet': np.float64(0.08527696793002909), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.08527696793002919)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.03021353930031804, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030798389007344232, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.027912386121341344, 'rc': 0.030090497737556562, 'htn': 0.031754032258064516, 'dm': 0.03128054740957967, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['al', 'hemo', 'htn', 'pcv', 'dm', 'sc', 'bu', 'sg', 'pc', 'rbc', 'rc', 'sod', 'pe', 'bgr', 'ane', 'appet', 'bp', 'su', 'cad', 'pot']

SENSITIVITY: completed 5/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f616990>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}

Normalized Mathematical Scores
{'age': np.float64(0.020691397872788946), 'bp': np.float64(0.01397987307106227), 'sg': np.float64(0.2848812995036987), 'al': np.float64(1.0), 'su': np.float64(0.06474574987694516), 'rbc': np.float64(0.08309037900874629), 'pc': np.float64(0.2848812994585586), 'pcc': np.float64(0.06474574987694516), 'ba': np.float64(0.04945855893377756), 'bgr': np.float64(0.09349565799027341), 'bu': np.float64(0.15536025143525914), 'sc': np.float64(0.16186378131498463), 'sod': np.float64(0.10117002128054604), 'pot': np.float64(0.004075837032849596), 'hemo': np.float64(0.3505337954578765), 'pcv': np.float64(0.34319948943611284), 'wc': np.float64(0.03300648941214772), 'rc': np.float64(0.14872189618305084), 'htn': np.float64(0.6884631403581833), 'dm': np.float64(0.2481920411949564), 'cad': np.float64(0.04945855893377756), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.11870054144106612), 'ane': np.float64(0.04945855893377756)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02821869488536155, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027745885954841176, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30a270>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}

Normalized Mathematical Scores
{'age': np.float64(0.020691397872788946), 'bp': np.float64(0.01397987307106227), 'sg': np.float64(0.2848812995036987), 'al': np.float64(1.0), 'su': np.float64(0.06474574987694516), 'rbc': np.float64(0.08309037900874629), 'pc': np.float64(0.2848812994585586), 'pcc': np.float64(0.06474574987694516), 'ba': np.float64(0.04945855893377756), 'bgr': np.float64(0.09349565799027341), 'bu': np.float64(0.15536025143525914), 'sc': np.float64(0.16186378131498463), 'sod': np.float64(0.10117002128054604), 'pot': np.float64(0.004075837032849596), 'hemo': np.float64(0.3505337954578765), 'pcv': np.float64(0.34319948943611284), 'wc': np.float64(0.03300648941214772), 'rc': np.float64(0.14872189618305084), 'htn': np.float64(0.6884631403581833), 'dm': np.float64(0.2481920411949564), 'cad': np.float64(0.04945855893377756), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.11870054144106612), 'ane': np.float64(0.04945855893377756)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02821869488536155, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027745885954841176, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22e780>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}

Normalized Mathematical Scores
{'age': np.float64(0.020691397872788946), 'bp': np.float64(0.01397987307106227), 'sg': np.float64(0.2848812995036987), 'al': np.float64(1.0), 'su': np.float64(0.06474574987694516), 'rbc': np.float64(0.08309037900874629), 'pc': np.float64(0.2848812994585586), 'pcc': np.float64(0.06474574987694516), 'ba': np.float64(0.04945855893377756), 'bgr': np.float64(0.09349565799027341), 'bu': np.float64(0.15536025143525914), 'sc': np.float64(0.16186378131498463), 'sod': np.float64(0.10117002128054604), 'pot': np.float64(0.004075837032849596), 'hemo': np.float64(0.3505337954578765), 'pcv': np.float64(0.34319948943611284), 'wc': np.float64(0.03300648941214772), 'rc': np.float64(0.14872189618305084), 'htn': np.float64(0.6884631403581833), 'dm': np.float64(0.2481920411949564), 'cad': np.float64(0.04945855893377756), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.11870054144106612), 'ane': np.float64(0.04945855893377756)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02821869488536155, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027745885954841176, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'pe', 'rc', 'sod', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311a00>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.782510946967319), 'bp': np.float64(10.663247651885913), 'sg': np.float64(217.29523812966897), 'al': np.float64(762.7571150097473), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(71.31447835459898), 'bu': np.float64(118.50213717194721), 'sc': np.float64(123.46275086038632), 'sod': np.float64(77.16815355742403), 'pot': np.float64(3.1088736964262464), 'hemo': np.float64(267.37214653686675), 'pcv': np.float64(261.77785243510766), 'wc': np.float64(25.17593464060956), 'rc': np.float64(113.43868447136302), 'htn': np.float64(525.1301587301587), 'dm': np.float64(189.31024531024528), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(37.724867724867735)}

Normalized Mathematical Scores
{'age': np.float64(0.020691397872788946), 'bp': np.float64(0.01397987307106227), 'sg': np.float64(0.2848812995036987), 'al': np.float64(1.0), 'su': np.float64(0.06474574987694516), 'rbc': np.float64(0.08309037900874629), 'pc': np.float64(0.2848812994585586), 'pcc': np.float64(0.06474574987694516), 'ba': np.float64(0.04945855893377756), 'bgr': np.float64(0.09349565799027341), 'bu': np.float64(0.15536025143525914), 'sc': np.float64(0.16186378131498463), 'sod': np.float64(0.10117002128054604), 'pot': np.float64(0.004075837032849596), 'hemo': np.float64(0.3505337954578765), 'pcv': np.float64(0.34319948943611284), 'wc': np.float64(0.03300648941214772), 'rc': np.float64(0.14872189618305084), 'htn': np.float64(0.6884631403581833), 'dm': np.float64(0.2481920411949564), 'cad': np.float64(0.04945855893377756), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.11870054144106612), 'ane': np.float64(0.04945855893377756)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028283227848101264, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027912386121341344, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02821869488536155, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027745885954841176, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'pe', 'rc', 'sod', 'rbc', 'bgr', 'appet', 'cad', 'ane', 'bp', 'su', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e373a70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}

Normalized Mathematical Scores
{'age': np.float64(0.01286241139573121), 'bp': np.float64(0.019765970018092497), 'sg': np.float64(0.30474511447178065), 'al': np.float64(1.0), 'su': np.float64(0.05363408259278618), 'rbc': np.float64(0.08539999999999999), 'pc': np.float64(0.2236666666666666), 'pcc': np.float64(0.0583478260869565), 'ba': np.float64(0.0583478260869565), 'bgr': np.float64(0.07578703521227395), 'bu': np.float64(0.12977339548809597), 'sc': np.float64(0.15907424045001198), 'sod': np.float64(0.14193767582000064), 'pot': np.float64(0.00465861400858149), 'hemo': np.float64(0.39184439503794544), 'pcv': np.float64(0.34148823159742026), 'wc': np.float64(0.03755477726742931), 'rc': np.float64(0.1657864762179995), 'htn': np.float64(0.39649999999999996), 'dm': np.float64(0.1742857142857143), 'cad': np.float64(0.03753846153846153), 'appet': np.float64(0.10844444444444433), 'pe': np.float64(0.1084444444444444), 'ane': np.float64(0.09631578947368419)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.028782894736842105, 'bu': 0.029957522915269395, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3268d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}

Normalized Mathematical Scores
{'age': np.float64(0.01286241139573121), 'bp': np.float64(0.019765970018092497), 'sg': np.float64(0.30474511447178065), 'al': np.float64(1.0), 'su': np.float64(0.05363408259278618), 'rbc': np.float64(0.08539999999999999), 'pc': np.float64(0.2236666666666666), 'pcc': np.float64(0.0583478260869565), 'ba': np.float64(0.0583478260869565), 'bgr': np.float64(0.07578703521227395), 'bu': np.float64(0.12977339548809597), 'sc': np.float64(0.15907424045001198), 'sod': np.float64(0.14193767582000064), 'pot': np.float64(0.00465861400858149), 'hemo': np.float64(0.39184439503794544), 'pcv': np.float64(0.34148823159742026), 'wc': np.float64(0.03755477726742931), 'rc': np.float64(0.1657864762179995), 'htn': np.float64(0.39649999999999996), 'dm': np.float64(0.1742857142857143), 'cad': np.float64(0.03753846153846153), 'appet': np.float64(0.10844444444444433), 'pe': np.float64(0.1084444444444444), 'ane': np.float64(0.09631578947368419)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.028782894736842105, 'bu': 0.029957522915269395, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rc', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35cd40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}

Normalized Mathematical Scores
{'age': np.float64(0.01286241139573121), 'bp': np.float64(0.019765970018092497), 'sg': np.float64(0.30474511447178065), 'al': np.float64(1.0), 'su': np.float64(0.05363408259278618), 'rbc': np.float64(0.08539999999999999), 'pc': np.float64(0.2236666666666666), 'pcc': np.float64(0.0583478260869565), 'ba': np.float64(0.0583478260869565), 'bgr': np.float64(0.07578703521227395), 'bu': np.float64(0.12977339548809597), 'sc': np.float64(0.15907424045001198), 'sod': np.float64(0.14193767582000064), 'pot': np.float64(0.00465861400858149), 'hemo': np.float64(0.39184439503794544), 'pcv': np.float64(0.34148823159742026), 'wc': np.float64(0.03755477726742931), 'rc': np.float64(0.1657864762179995), 'htn': np.float64(0.39649999999999996), 'dm': np.float64(0.1742857142857143), 'cad': np.float64(0.03753846153846153), 'appet': np.float64(0.10844444444444433), 'pe': np.float64(0.1084444444444444), 'ane': np.float64(0.09631578947368419)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.028782894736842105, 'bu': 0.029957522915269395, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rc', 'bu', 'sod', 'pe', 'rbc', 'ane', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e279640>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.545562659543435), 'bp': np.float64(14.668890578089986), 'sg': np.float64(226.16004852290362), 'al': np.float64(742.1285454072341), 'su': np.float64(39.803383698835866), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(56.243722202811696), 'bu': np.float64(96.30854122613837), 'sc': np.float64(118.053534676928), 'sod': np.float64(105.33600089478061), 'pot': np.float64(3.4572904378023455), 'hemo': np.float64(290.7989109154881), 'pcv': np.float64(253.42816458908217), 'wc': np.float64(27.87047222656998), 'rc': np.float64(123.03487644385497), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(80.47971781305114), 'ane': np.float64(71.47869674185463)}

Normalized Mathematical Scores
{'age': np.float64(0.01286241139573121), 'bp': np.float64(0.019765970018092497), 'sg': np.float64(0.30474511447178065), 'al': np.float64(1.0), 'su': np.float64(0.05363408259278618), 'rbc': np.float64(0.08539999999999999), 'pc': np.float64(0.2236666666666666), 'pcc': np.float64(0.0583478260869565), 'ba': np.float64(0.0583478260869565), 'bgr': np.float64(0.07578703521227395), 'bu': np.float64(0.12977339548809597), 'sc': np.float64(0.15907424045001198), 'sod': np.float64(0.14193767582000064), 'pot': np.float64(0.00465861400858149), 'hemo': np.float64(0.39184439503794544), 'pcv': np.float64(0.34148823159742026), 'wc': np.float64(0.03755477726742931), 'rc': np.float64(0.1657864762179995), 'htn': np.float64(0.39649999999999996), 'dm': np.float64(0.1742857142857143), 'cad': np.float64(0.03753846153846153), 'appet': np.float64(0.10844444444444433), 'pe': np.float64(0.1084444444444444), 'ane': np.float64(0.09631578947368419)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027912386121341344, 'bgr': 0.028782894736842105, 'bu': 0.029957522915269395, 'sc': 0.030886196246139225, 'sod': 0.029910714285714284, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'rc', 'bu', 'sod', 'pe', 'rbc', 'ane', 'appet', 'bgr', 'bp', 'pcc', 'cad', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd1880>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.01700183312208167), 'bp': np.float64(0.017898845596323827), 'sg': np.float64(0.27652198577834214), 'al': np.float64(1.0), 'su': np.float64(0.05887999999999999), 'rbc': np.float64(0.11448888888888883), 'pc': np.float64(0.23613333333333322), 'pcc': np.float64(0.04636799999999998), 'ba': np.float64(0.03963076923076922), 'bgr': np.float64(0.105262062883385), 'bu': np.float64(0.14349540092768323), 'sc': np.float64(0.14911172379234516), 'sod': np.float64(0.1185775135873297), 'pot': np.float64(0.005075972209557585), 'hemo': np.float64(0.38843011432072533), 'pcv': np.float64(0.35853131339820826), 'wc': np.float64(0.03629536750220751), 'rc': np.float64(0.16853690056265508), 'htn': np.float64(0.4185999999999999), 'dm': np.float64(0.30911999999999984), 'cad': np.float64(0.04636799999999998), 'appet': np.float64(0.09015999999999996), 'pe': np.float64(0.09015999999999998), 'ane': np.float64(0.061599999999999974)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.030017921146953404, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02844551282051282, 'appet': 0.028484848484848488, 'pe': 0.029138513513513514, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e371a60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.01700183312208167), 'bp': np.float64(0.017898845596323827), 'sg': np.float64(0.27652198577834214), 'al': np.float64(1.0), 'su': np.float64(0.05887999999999999), 'rbc': np.float64(0.11448888888888883), 'pc': np.float64(0.23613333333333322), 'pcc': np.float64(0.04636799999999998), 'ba': np.float64(0.03963076923076922), 'bgr': np.float64(0.105262062883385), 'bu': np.float64(0.14349540092768323), 'sc': np.float64(0.14911172379234516), 'sod': np.float64(0.1185775135873297), 'pot': np.float64(0.005075972209557585), 'hemo': np.float64(0.38843011432072533), 'pcv': np.float64(0.35853131339820826), 'wc': np.float64(0.03629536750220751), 'rc': np.float64(0.16853690056265508), 'htn': np.float64(0.4185999999999999), 'dm': np.float64(0.30911999999999984), 'cad': np.float64(0.04636799999999998), 'appet': np.float64(0.09015999999999996), 'pe': np.float64(0.09015999999999998), 'ane': np.float64(0.061599999999999974)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.030017921146953404, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02844551282051282, 'appet': 0.028484848484848488, 'pe': 0.029138513513513514, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'rc', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e326510>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.01700183312208167), 'bp': np.float64(0.017898845596323827), 'sg': np.float64(0.27652198577834214), 'al': np.float64(1.0), 'su': np.float64(0.05887999999999999), 'rbc': np.float64(0.11448888888888883), 'pc': np.float64(0.23613333333333322), 'pcc': np.float64(0.04636799999999998), 'ba': np.float64(0.03963076923076922), 'bgr': np.float64(0.105262062883385), 'bu': np.float64(0.14349540092768323), 'sc': np.float64(0.14911172379234516), 'sod': np.float64(0.1185775135873297), 'pot': np.float64(0.005075972209557585), 'hemo': np.float64(0.38843011432072533), 'pcv': np.float64(0.35853131339820826), 'wc': np.float64(0.03629536750220751), 'rc': np.float64(0.16853690056265508), 'htn': np.float64(0.4185999999999999), 'dm': np.float64(0.30911999999999984), 'cad': np.float64(0.04636799999999998), 'appet': np.float64(0.09015999999999996), 'pe': np.float64(0.09015999999999998), 'ane': np.float64(0.061599999999999974)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.030017921146953404, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02844551282051282, 'appet': 0.028484848484848488, 'pe': 0.029138513513513514, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'rc', 'pc', 'rbc', 'sod', 'bgr', 'pe', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e35fb30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.951401967903218), 'bp': np.float64(12.581954954331946), 'sg': np.float64(194.38053422060338), 'al': np.float64(702.9478458049889), 'su': np.float64(41.38956916099774), 'rbc': np.float64(80.47971781305114), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(32.59428571428571), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(73.99374034886476), 'bu': np.float64(100.86978296503814), 'sc': np.float64(104.81776502409754), 'sod': np.float64(83.35380773712521), 'pot': np.float64(3.568143730074494), 'hemo': np.float64(273.04611210753944), 'pcv': np.float64(252.02881440690385), 'wc': np.float64(25.51375039837717), 'rc': np.float64(118.472651189168), 'htn': np.float64(294.2539682539683), 'dm': np.float64(217.29523809523806), 'cad': np.float64(32.59428571428571), 'appet': np.float64(63.37777777777777), 'pe': np.float64(63.37777777777779), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.01700183312208167), 'bp': np.float64(0.017898845596323827), 'sg': np.float64(0.27652198577834214), 'al': np.float64(1.0), 'su': np.float64(0.05887999999999999), 'rbc': np.float64(0.11448888888888883), 'pc': np.float64(0.23613333333333322), 'pcc': np.float64(0.04636799999999998), 'ba': np.float64(0.03963076923076922), 'bgr': np.float64(0.105262062883385), 'bu': np.float64(0.14349540092768323), 'sc': np.float64(0.14911172379234516), 'sod': np.float64(0.1185775135873297), 'pot': np.float64(0.005075972209557585), 'hemo': np.float64(0.38843011432072533), 'pcv': np.float64(0.35853131339820826), 'wc': np.float64(0.03629536750220751), 'rc': np.float64(0.16853690056265508), 'htn': np.float64(0.4185999999999999), 'dm': np.float64(0.30911999999999984), 'cad': np.float64(0.04636799999999998), 'appet': np.float64(0.09015999999999996), 'pe': np.float64(0.09015999999999998), 'ane': np.float64(0.061599999999999974)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.030017921146953404, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02844551282051282, 'appet': 0.028484848484848488, 'pe': 0.029138513513513514, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'rc', 'pc', 'rbc', 'sod', 'bgr', 'pe', 'ane', 'appet', 'cad', 'bp', 'su', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310560>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.01118861617528689), 'bp': np.float64(0.018826482494280393), 'sg': np.float64(0.19735855145554365), 'al': np.float64(1.0), 'su': np.float64(0.03981425250769587), 'rbc': np.float64(0.06768422926308298), 'pc': np.float64(0.22561409754360998), 'pcc': np.float64(0.0533269685103078), 'ba': np.float64(0.04136258454966183), 'bgr': np.float64(0.06393978294360912), 'bu': np.float64(0.10802271674475736), 'sc': np.float64(0.12654568740333882), 'sod': np.float64(0.08884710118084913), 'pot': np.float64(0.0034325199631616427), 'hemo': np.float64(0.3342667708428517), 'pcv': np.float64(0.34391606376578243), 'wc': np.float64(0.02064256450214813), 'rc': np.float64(0.2138607811399343), 'htn': np.float64(0.3609825560697758), 'dm': np.float64(0.1527233891064437), 'cad': np.float64(0.02673944859776118), 'appet': np.float64(0.07599632759363717), 'pe': np.float64(0.06768422926308298), 'ane': np.float64(0.06768422926308298)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f66675cc770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.01118861617528689), 'bp': np.float64(0.018826482494280393), 'sg': np.float64(0.19735855145554365), 'al': np.float64(1.0), 'su': np.float64(0.03981425250769587), 'rbc': np.float64(0.06768422926308298), 'pc': np.float64(0.22561409754360998), 'pcc': np.float64(0.0533269685103078), 'ba': np.float64(0.04136258454966183), 'bgr': np.float64(0.06393978294360912), 'bu': np.float64(0.10802271674475736), 'sc': np.float64(0.12654568740333882), 'sod': np.float64(0.08884710118084913), 'pot': np.float64(0.0034325199631616427), 'hemo': np.float64(0.3342667708428517), 'pcv': np.float64(0.34391606376578243), 'wc': np.float64(0.02064256450214813), 'rc': np.float64(0.2138607811399343), 'htn': np.float64(0.3609825560697758), 'dm': np.float64(0.1527233891064437), 'cad': np.float64(0.02673944859776118), 'appet': np.float64(0.07599632759363717), 'pe': np.float64(0.06768422926308298), 'ane': np.float64(0.06768422926308298)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'pc', 'rc', 'sg', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3735c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.01118861617528689), 'bp': np.float64(0.018826482494280393), 'sg': np.float64(0.19735855145554365), 'al': np.float64(1.0), 'su': np.float64(0.03981425250769587), 'rbc': np.float64(0.06768422926308298), 'pc': np.float64(0.22561409754360998), 'pcc': np.float64(0.0533269685103078), 'ba': np.float64(0.04136258454966183), 'bgr': np.float64(0.06393978294360912), 'bu': np.float64(0.10802271674475736), 'sc': np.float64(0.12654568740333882), 'sod': np.float64(0.08884710118084913), 'pot': np.float64(0.0034325199631616427), 'hemo': np.float64(0.3342667708428517), 'pcv': np.float64(0.34391606376578243), 'wc': np.float64(0.02064256450214813), 'rc': np.float64(0.2138607811399343), 'htn': np.float64(0.3609825560697758), 'dm': np.float64(0.1527233891064437), 'cad': np.float64(0.02673944859776118), 'appet': np.float64(0.07599632759363717), 'pe': np.float64(0.06768422926308298), 'ane': np.float64(0.06768422926308298)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'pc', 'rc', 'sg', 'bu', 'rbc', 'sod', 'pe', 'ane', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3262d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(11.226497153811358), 'bp': np.float64(18.890222778859314), 'sg': np.float64(198.02674267170323), 'al': np.float64(1003.3856714656223), 'su': np.float64(39.94905048633626), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(226.3779527559055), 'pcc': np.float64(53.507516105941285), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(64.15626204223938), 'bu': np.float64(108.38844617447909), 'sc': np.float64(126.97412952627786), 'sod': np.float64(89.14790827612039), 'pot': np.float64(3.444141348056098), 'hemo': np.float64(335.3984883108001), 'pcv': np.float64(345.08045056944337), 'wc': np.float64(20.71245344376032), 'rc': np.float64(214.58484348425546), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(67.91338582677164), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.01118861617528689), 'bp': np.float64(0.018826482494280393), 'sg': np.float64(0.19735855145554365), 'al': np.float64(1.0), 'su': np.float64(0.03981425250769587), 'rbc': np.float64(0.06768422926308298), 'pc': np.float64(0.22561409754360998), 'pcc': np.float64(0.0533269685103078), 'ba': np.float64(0.04136258454966183), 'bgr': np.float64(0.06393978294360912), 'bu': np.float64(0.10802271674475736), 'sc': np.float64(0.12654568740333882), 'sod': np.float64(0.08884710118084913), 'pot': np.float64(0.0034325199631616427), 'hemo': np.float64(0.3342667708428517), 'pcv': np.float64(0.34391606376578243), 'wc': np.float64(0.02064256450214813), 'rc': np.float64(0.2138607811399343), 'htn': np.float64(0.3609825560697758), 'dm': np.float64(0.1527233891064437), 'cad': np.float64(0.02673944859776118), 'appet': np.float64(0.07599632759363717), 'pe': np.float64(0.06768422926308298), 'ane': np.float64(0.06768422926308298)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.0293236301369863, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'pc', 'rc', 'sg', 'bu', 'rbc', 'sod', 'pe', 'ane', 'bgr', 'appet', 'pcc', 'cad', 'bp', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30b8f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.026445471765629128), 'bp': np.float64(0.0312997242237943), 'sg': np.float64(0.3309534687273464), 'al': np.float64(1.0), 'su': np.float64(0.08239877300613496), 'rbc': np.float64(0.08745454545454541), 'pc': np.float64(0.28366666666666657), 'pcc': np.float64(0.06783333333333333), 'ba': np.float64(0.04385185185185184), 'bgr': np.float64(0.1162544640549625), 'bu': np.float64(0.18312692533356406), 'sc': np.float64(0.22680104318672326), 'sod': np.float64(0.13558117603381975), 'pot': np.float64(0.006009387482638607), 'hemo': np.float64(0.4311572890732788), 'pcv': np.float64(0.42747200216754316), 'wc': np.float64(0.04197343703968556), 'rc': np.float64(0.20761340881279058), 'htn': np.float64(0.4995000000000001), 'dm': np.float64(0.28366666666666657), 'cad': np.float64(0.05123076923076923), 'appet': np.float64(0.11100000000000015), 'pe': np.float64(0.15670588235294117), 'ane': np.float64(0.08745454545454541)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028484848484848488, 'rbc': 0.02964254577157803, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029910714285714284, 'ane': 0.029138513513513514}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e313b90>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.026445471765629128), 'bp': np.float64(0.0312997242237943), 'sg': np.float64(0.3309534687273464), 'al': np.float64(1.0), 'su': np.float64(0.08239877300613496), 'rbc': np.float64(0.08745454545454541), 'pc': np.float64(0.28366666666666657), 'pcc': np.float64(0.06783333333333333), 'ba': np.float64(0.04385185185185184), 'bgr': np.float64(0.1162544640549625), 'bu': np.float64(0.18312692533356406), 'sc': np.float64(0.22680104318672326), 'sod': np.float64(0.13558117603381975), 'pot': np.float64(0.006009387482638607), 'hemo': np.float64(0.4311572890732788), 'pcv': np.float64(0.42747200216754316), 'wc': np.float64(0.04197343703968556), 'rc': np.float64(0.20761340881279058), 'htn': np.float64(0.4995000000000001), 'dm': np.float64(0.28366666666666657), 'cad': np.float64(0.05123076923076923), 'appet': np.float64(0.11100000000000015), 'pe': np.float64(0.15670588235294117), 'ane': np.float64(0.08745454545454541)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028484848484848488, 'rbc': 0.02964254577157803, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029910714285714284, 'ane': 0.029138513513513514}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311d30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.026445471765629128), 'bp': np.float64(0.0312997242237943), 'sg': np.float64(0.3309534687273464), 'al': np.float64(1.0), 'su': np.float64(0.08239877300613496), 'rbc': np.float64(0.08745454545454541), 'pc': np.float64(0.28366666666666657), 'pcc': np.float64(0.06783333333333333), 'ba': np.float64(0.04385185185185184), 'bgr': np.float64(0.1162544640549625), 'bu': np.float64(0.18312692533356406), 'sc': np.float64(0.22680104318672326), 'sod': np.float64(0.13558117603381975), 'pot': np.float64(0.006009387482638607), 'hemo': np.float64(0.4311572890732788), 'pcv': np.float64(0.42747200216754316), 'wc': np.float64(0.04197343703968556), 'rc': np.float64(0.20761340881279058), 'htn': np.float64(0.4995000000000001), 'dm': np.float64(0.28366666666666657), 'cad': np.float64(0.05123076923076923), 'appet': np.float64(0.11100000000000015), 'pe': np.float64(0.15670588235294117), 'ane': np.float64(0.08745454545454541)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028484848484848488, 'rbc': 0.02964254577157803, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029910714285714284, 'ane': 0.029138513513513514}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e373f80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.180193940451957), 'bp': np.float64(19.150182409748588), 'sg': np.float64(202.4880235350332), 'al': np.float64(611.8323047456906), 'su': np.float64(50.41423119656055), 'rbc': np.float64(53.507516105941285), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(71.12823667972275), 'bu': np.float64(112.0429687878265), 'sc': np.float64(138.7642049716598), 'sod': np.float64(82.95294341290314), 'pot': np.float64(3.6767373936126826), 'hemo': np.float64(263.79595788160816), 'pcv': np.float64(261.5411803004228), 'wc': np.float64(25.680704722088958), 'rc': np.float64(127.02459041003894), 'htn': np.float64(305.61023622047253), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.026445471765629128), 'bp': np.float64(0.0312997242237943), 'sg': np.float64(0.3309534687273464), 'al': np.float64(1.0), 'su': np.float64(0.08239877300613496), 'rbc': np.float64(0.08745454545454541), 'pc': np.float64(0.28366666666666657), 'pcc': np.float64(0.06783333333333333), 'ba': np.float64(0.04385185185185184), 'bgr': np.float64(0.1162544640549625), 'bu': np.float64(0.18312692533356406), 'sc': np.float64(0.22680104318672326), 'sod': np.float64(0.13558117603381975), 'pot': np.float64(0.006009387482638607), 'hemo': np.float64(0.4311572890732788), 'pcv': np.float64(0.42747200216754316), 'wc': np.float64(0.04197343703968556), 'rc': np.float64(0.20761340881279058), 'htn': np.float64(0.4995000000000001), 'dm': np.float64(0.28366666666666657), 'cad': np.float64(0.05123076923076923), 'appet': np.float64(0.11100000000000015), 'pe': np.float64(0.15670588235294117), 'ane': np.float64(0.08745454545454541)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028484848484848488, 'rbc': 0.02964254577157803, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028612012987012988, 'appet': 0.028850145288501453, 'pe': 0.029910714285714284, 'ane': 0.029138513513513514}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'ane', 'appet', 'cad', 'su', 'bp', 'pcc']

SENSITIVITY: completed 10/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666ab9fc20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.015210248581651518), 'bp': np.float64(0.0069818030900298455), 'sg': np.float64(0.2577552541417599), 'al': np.float64(1.0), 'su': np.float64(0.047188650972593775), 'rbc': np.float64(0.06390129819205408), 'pc': np.float64(0.16674835800411741), 'pcc': np.float64(0.04936856147947989), 'ba': np.float64(0.04301048916772871), 'bgr': np.float64(0.08792251492740358), 'bu': np.float64(0.12441594868862489), 'sc': np.float64(0.1330012415351675), 'sod': np.float64(0.09401205789111923), 'pot': np.float64(0.006591417128261563), 'hemo': np.float64(0.2760615363555578), 'pcv': np.float64(0.2695824905174491), 'wc': np.float64(0.025887148156493893), 'rc': np.float64(0.120576670815883), 'htn': np.float64(0.33548181550828393), 'dm': np.float64(0.14746453428935558), 'cad': np.float64(0.04301048916772871), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.09175571022448788), 'ane': np.float64(0.04936856147947989)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30bbf0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.015210248581651518), 'bp': np.float64(0.0069818030900298455), 'sg': np.float64(0.2577552541417599), 'al': np.float64(1.0), 'su': np.float64(0.047188650972593775), 'rbc': np.float64(0.06390129819205408), 'pc': np.float64(0.16674835800411741), 'pcc': np.float64(0.04936856147947989), 'ba': np.float64(0.04301048916772871), 'bgr': np.float64(0.08792251492740358), 'bu': np.float64(0.12441594868862489), 'sc': np.float64(0.1330012415351675), 'sod': np.float64(0.09401205789111923), 'pot': np.float64(0.006591417128261563), 'hemo': np.float64(0.2760615363555578), 'pcv': np.float64(0.2695824905174491), 'wc': np.float64(0.025887148156493893), 'rc': np.float64(0.120576670815883), 'htn': np.float64(0.33548181550828393), 'dm': np.float64(0.14746453428935558), 'cad': np.float64(0.04301048916772871), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.09175571022448788), 'ane': np.float64(0.04936856147947989)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'sod']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311370>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.015210248581651518), 'bp': np.float64(0.0069818030900298455), 'sg': np.float64(0.2577552541417599), 'al': np.float64(1.0), 'su': np.float64(0.047188650972593775), 'rbc': np.float64(0.06390129819205408), 'pc': np.float64(0.16674835800411741), 'pcc': np.float64(0.04936856147947989), 'ba': np.float64(0.04301048916772871), 'bgr': np.float64(0.08792251492740358), 'bu': np.float64(0.12441594868862489), 'sc': np.float64(0.1330012415351675), 'sod': np.float64(0.09401205789111923), 'pot': np.float64(0.006591417128261563), 'hemo': np.float64(0.2760615363555578), 'pcv': np.float64(0.2695824905174491), 'wc': np.float64(0.025887148156493893), 'rc': np.float64(0.120576670815883), 'htn': np.float64(0.33548181550828393), 'dm': np.float64(0.14746453428935558), 'cad': np.float64(0.04301048916772871), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.09175571022448788), 'ane': np.float64(0.04936856147947989)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'sod', 'rc', 'pe', 'rbc', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310dd0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.341039056019227), 'bp': np.float64(6.123799174320287), 'sg': np.float64(226.07933683264014), 'al': np.float64(877.108548515955), 'su': np.float64(41.38956916099774), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(146.25641025641025), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(77.11758944984734), 'bu': np.float64(109.12629216651531), 'sc': np.float64(116.65652591373072), 'sod': np.float64(82.45877963987752), 'pot': np.float64(5.781388310032704), 'hemo': np.float64(242.13593345390785), 'pcv': np.float64(236.45310696307598), 'wc': np.float64(22.70583894475984), 'rc': np.float64(105.75882872420524), 'htn': np.float64(294.2539682539683), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(43.3015873015873)}

Normalized Mathematical Scores
{'age': np.float64(0.015210248581651518), 'bp': np.float64(0.0069818030900298455), 'sg': np.float64(0.2577552541417599), 'al': np.float64(1.0), 'su': np.float64(0.047188650972593775), 'rbc': np.float64(0.06390129819205408), 'pc': np.float64(0.16674835800411741), 'pcc': np.float64(0.04936856147947989), 'ba': np.float64(0.04301048916772871), 'bgr': np.float64(0.08792251492740358), 'bu': np.float64(0.12441594868862489), 'sc': np.float64(0.1330012415351675), 'sod': np.float64(0.09401205789111923), 'pot': np.float64(0.006591417128261563), 'hemo': np.float64(0.2760615363555578), 'pcv': np.float64(0.2695824905174491), 'wc': np.float64(0.025887148156493893), 'rc': np.float64(0.120576670815883), 'htn': np.float64(0.33548181550828393), 'dm': np.float64(0.14746453428935558), 'cad': np.float64(0.04301048916772871), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.09175571022448788), 'ane': np.float64(0.04936856147947989)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'bu', 'pc', 'sod', 'rc', 'pe', 'rbc', 'bgr', 'ane', 'appet', 'cad', 'pcc', 'bp', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e33a750>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011783649392687844), 'bp': np.float64(0.022654386779836302), 'sg': np.float64(0.2598334341947192), 'al': np.float64(1.0), 'su': np.float64(0.07084866902531844), 'rbc': np.float64(0.090922458582492), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.06212093443524296), 'ba': np.float64(0.04676012155671016), 'bgr': np.float64(0.08738136382103608), 'bu': np.float64(0.15565871722319924), 'sc': np.float64(0.17289132568375312), 'sod': np.float64(0.13283987275831954), 'pot': np.float64(0.005127814366353282), 'hemo': np.float64(0.3843777977736662), 'pcv': np.float64(0.37777084265959404), 'wc': np.float64(0.03970668654518961), 'rc': np.float64(0.2536789251993525), 'htn': np.float64(0.42213998627585575), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.04676012155671016), 'appet': np.float64(0.0804076164334964), 'pe': np.float64(0.11545709026348187), 'ane': np.float64(0.07084866902531843)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e33a390>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011783649392687844), 'bp': np.float64(0.022654386779836302), 'sg': np.float64(0.2598334341947192), 'al': np.float64(1.0), 'su': np.float64(0.07084866902531844), 'rbc': np.float64(0.090922458582492), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.06212093443524296), 'ba': np.float64(0.04676012155671016), 'bgr': np.float64(0.08738136382103608), 'bu': np.float64(0.15565871722319924), 'sc': np.float64(0.17289132568375312), 'sod': np.float64(0.13283987275831954), 'pot': np.float64(0.005127814366353282), 'hemo': np.float64(0.3843777977736662), 'pcv': np.float64(0.37777084265959404), 'wc': np.float64(0.03970668654518961), 'rc': np.float64(0.2536789251993525), 'htn': np.float64(0.42213998627585575), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.04676012155671016), 'appet': np.float64(0.0804076164334964), 'pe': np.float64(0.11545709026348187), 'ane': np.float64(0.07084866902531843)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'pc', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666bd1c70>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011783649392687844), 'bp': np.float64(0.022654386779836302), 'sg': np.float64(0.2598334341947192), 'al': np.float64(1.0), 'su': np.float64(0.07084866902531844), 'rbc': np.float64(0.090922458582492), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.06212093443524296), 'ba': np.float64(0.04676012155671016), 'bgr': np.float64(0.08738136382103608), 'bu': np.float64(0.15565871722319924), 'sc': np.float64(0.17289132568375312), 'sod': np.float64(0.13283987275831954), 'pot': np.float64(0.005127814366353282), 'hemo': np.float64(0.3843777977736662), 'pcv': np.float64(0.37777084265959404), 'wc': np.float64(0.03970668654518961), 'rc': np.float64(0.2536789251993525), 'htn': np.float64(0.42213998627585575), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.04676012155671016), 'appet': np.float64(0.0804076164334964), 'pe': np.float64(0.11545709026348187), 'ane': np.float64(0.07084866902531843)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'pc', 'bu', 'rc', 'rbc', 'sod', 'pe', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617fb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(8.213828841236637), 'bp': np.float64(15.791309577508128), 'sg': np.float64(181.1176898245553), 'al': np.float64(697.0530578017365), 'su': np.float64(49.385281385281395), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(32.59428571428571), 'bgr': np.float64(60.90944684633923), 'bu': np.float64(108.50238481392685), 'sc': np.float64(120.51442723525601), 'sod': np.float64(92.59643950418022), 'pot': np.float64(3.5743586839062296), 'hemo': np.float64(267.9317192892315), 'pcv': np.float64(263.3263210242087), 'wc': np.float64(27.677667271499484), 'rc': np.float64(176.82767051006664), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(32.59428571428571), 'appet': np.float64(56.048374905517825), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011783649392687844), 'bp': np.float64(0.022654386779836302), 'sg': np.float64(0.2598334341947192), 'al': np.float64(1.0), 'su': np.float64(0.07084866902531844), 'rbc': np.float64(0.090922458582492), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.06212093443524296), 'ba': np.float64(0.04676012155671016), 'bgr': np.float64(0.08738136382103608), 'bu': np.float64(0.15565871722319924), 'sc': np.float64(0.17289132568375312), 'sod': np.float64(0.13283987275831954), 'pot': np.float64(0.005127814366353282), 'hemo': np.float64(0.3843777977736662), 'pcv': np.float64(0.37777084265959404), 'wc': np.float64(0.03970668654518961), 'rc': np.float64(0.2536789251993525), 'htn': np.float64(0.42213998627585575), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.04676012155671016), 'appet': np.float64(0.0804076164334964), 'pe': np.float64(0.11545709026348187), 'ane': np.float64(0.07084866902531843)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028484848484848488, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'pc', 'bu', 'rc', 'rbc', 'sod', 'pe', 'bgr', 'ane', 'appet', 'su', 'cad', 'bp', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e27a960>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01580490874876666), 'bp': np.float64(0.01588847237951871), 'sg': np.float64(0.2157207756736986), 'al': np.float64(1.0), 'su': np.float64(0.057697913852953094), 'rbc': np.float64(0.07225762180178423), 'pc': np.float64(0.33548181550828393), 'pcc': np.float64(0.056304640365026665), 'ba': np.float64(0.04936856147947989), 'bgr': np.float64(0.07611385330064098), 'bu': np.float64(0.13253445663870778), 'sc': np.float64(0.1405615106625508), 'sod': np.float64(0.09591538817923087), 'pot': np.float64(0.0038226035720431476), 'hemo': np.float64(0.3333124618871249), 'pcv': np.float64(0.31690567073247683), 'wc': np.float64(0.027683809379521432), 'rc': np.float64(0.1633847621082228), 'htn': np.float64(0.39815424258126), 'dm': np.float64(0.16674835800411741), 'cad': np.float64(0.03716106264091759), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.10322517400254888), 'ane': np.float64(0.06390129819205408)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.031024531024531024, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.027271052146674038, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e325580>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01580490874876666), 'bp': np.float64(0.01588847237951871), 'sg': np.float64(0.2157207756736986), 'al': np.float64(1.0), 'su': np.float64(0.057697913852953094), 'rbc': np.float64(0.07225762180178423), 'pc': np.float64(0.33548181550828393), 'pcc': np.float64(0.056304640365026665), 'ba': np.float64(0.04936856147947989), 'bgr': np.float64(0.07611385330064098), 'bu': np.float64(0.13253445663870778), 'sc': np.float64(0.1405615106625508), 'sod': np.float64(0.09591538817923087), 'pot': np.float64(0.0038226035720431476), 'hemo': np.float64(0.3333124618871249), 'pcv': np.float64(0.31690567073247683), 'wc': np.float64(0.027683809379521432), 'rc': np.float64(0.1633847621082228), 'htn': np.float64(0.39815424258126), 'dm': np.float64(0.16674835800411741), 'cad': np.float64(0.03716106264091759), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.10322517400254888), 'ane': np.float64(0.06390129819205408)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.031024531024531024, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.027271052146674038, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pc', 'pcv', 'sc', 'sg', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666d191f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01580490874876666), 'bp': np.float64(0.01588847237951871), 'sg': np.float64(0.2157207756736986), 'al': np.float64(1.0), 'su': np.float64(0.057697913852953094), 'rbc': np.float64(0.07225762180178423), 'pc': np.float64(0.33548181550828393), 'pcc': np.float64(0.056304640365026665), 'ba': np.float64(0.04936856147947989), 'bgr': np.float64(0.07611385330064098), 'bu': np.float64(0.13253445663870778), 'sc': np.float64(0.1405615106625508), 'sod': np.float64(0.09591538817923087), 'pot': np.float64(0.0038226035720431476), 'hemo': np.float64(0.3333124618871249), 'pcv': np.float64(0.31690567073247683), 'wc': np.float64(0.027683809379521432), 'rc': np.float64(0.1633847621082228), 'htn': np.float64(0.39815424258126), 'dm': np.float64(0.16674835800411741), 'cad': np.float64(0.03716106264091759), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.10322517400254888), 'ane': np.float64(0.06390129819205408)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.031024531024531024, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.027271052146674038, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pc', 'pcv', 'sc', 'sg', 'bu', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617fb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.862620572057844), 'bp': np.float64(13.935914946935496), 'sg': np.float64(189.21053643589372), 'al': np.float64(877.108548515955), 'su': np.float64(50.6073334719623), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(294.2539682539683), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(66.76011139048154), 'bu': np.float64(116.24710489072775), 'sc': np.float64(123.28770259443985), 'sod': np.float64(84.12820690622958), 'pot': np.float64(3.35283827062667), 'hemo': np.float64(292.3512096480957), 'pcv': np.float64(277.96067287263793), 'wc': np.float64(24.281705862264424), 'rc': np.float64(143.3061715423679), 'htn': np.float64(349.2244897959184), 'dm': np.float64(146.25641025641025), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01580490874876666), 'bp': np.float64(0.01588847237951871), 'sg': np.float64(0.2157207756736986), 'al': np.float64(1.0), 'su': np.float64(0.057697913852953094), 'rbc': np.float64(0.07225762180178423), 'pc': np.float64(0.33548181550828393), 'pcc': np.float64(0.056304640365026665), 'ba': np.float64(0.04936856147947989), 'bgr': np.float64(0.07611385330064098), 'bu': np.float64(0.13253445663870778), 'sc': np.float64(0.1405615106625508), 'sod': np.float64(0.09591538817923087), 'pot': np.float64(0.0038226035720431476), 'hemo': np.float64(0.3333124618871249), 'pcv': np.float64(0.31690567073247683), 'wc': np.float64(0.027683809379521432), 'rc': np.float64(0.1633847621082228), 'htn': np.float64(0.39815424258126), 'dm': np.float64(0.16674835800411741), 'cad': np.float64(0.03716106264091759), 'appet': np.float64(0.08149355842306498), 'pe': np.float64(0.10322517400254888), 'ane': np.float64(0.06390129819205408)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.031024531024531024, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.027271052146674038, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pc', 'pcv', 'sc', 'sg', 'bu', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'appet', 'ane', 'su', 'cad', 'bp', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666cfa3c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.02639117874385328), 'bp': np.float64(0.034497660145964615), 'sg': np.float64(0.40280529956921374), 'al': np.float64(1.0), 'su': np.float64(0.0790660274527501), 'rbc': np.float64(0.12002951207054002), 'pc': np.float64(0.2731921707022187), 'pcc': np.float64(0.06532856255922621), 'ba': np.float64(0.05701401823350653), 'bgr': np.float64(0.12485595501847524), 'bu': np.float64(0.1412921340304362), 'sc': np.float64(0.20740689994507552), 'sod': np.float64(0.13995521345340653), 'pot': np.float64(0.004682913390882651), 'hemo': np.float64(0.4579513202763242), 'pcv': np.float64(0.38866245300772617), 'wc': np.float64(0.04528594289508035), 'rc': np.float64(0.19181311588601757), 'htn': np.float64(0.5701401823350649), 'dm': np.float64(0.35633761395941577), 'cad': np.float64(0.04223260609889371), 'appet': np.float64(0.12002951207054023), 'pe': np.float64(0.13461643194022377), 'ane': np.float64(0.08422525420858915)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.031009615384615385, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.031009615384615385, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e309b80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.02639117874385328), 'bp': np.float64(0.034497660145964615), 'sg': np.float64(0.40280529956921374), 'al': np.float64(1.0), 'su': np.float64(0.0790660274527501), 'rbc': np.float64(0.12002951207054002), 'pc': np.float64(0.2731921707022187), 'pcc': np.float64(0.06532856255922621), 'ba': np.float64(0.05701401823350653), 'bgr': np.float64(0.12485595501847524), 'bu': np.float64(0.1412921340304362), 'sc': np.float64(0.20740689994507552), 'sod': np.float64(0.13995521345340653), 'pot': np.float64(0.004682913390882651), 'hemo': np.float64(0.4579513202763242), 'pcv': np.float64(0.38866245300772617), 'wc': np.float64(0.04528594289508035), 'rc': np.float64(0.19181311588601757), 'htn': np.float64(0.5701401823350649), 'dm': np.float64(0.35633761395941577), 'cad': np.float64(0.04223260609889371), 'appet': np.float64(0.12002951207054023), 'pe': np.float64(0.13461643194022377), 'ane': np.float64(0.08422525420858915)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.031009615384615385, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.031009615384615385, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'sc', 'sg', 'pcv', 'bu', 'pc', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e30a360>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.02639117874385328), 'bp': np.float64(0.034497660145964615), 'sg': np.float64(0.40280529956921374), 'al': np.float64(1.0), 'su': np.float64(0.0790660274527501), 'rbc': np.float64(0.12002951207054002), 'pc': np.float64(0.2731921707022187), 'pcc': np.float64(0.06532856255922621), 'ba': np.float64(0.05701401823350653), 'bgr': np.float64(0.12485595501847524), 'bu': np.float64(0.1412921340304362), 'sc': np.float64(0.20740689994507552), 'sod': np.float64(0.13995521345340653), 'pot': np.float64(0.004682913390882651), 'hemo': np.float64(0.4579513202763242), 'pcv': np.float64(0.38866245300772617), 'wc': np.float64(0.04528594289508035), 'rc': np.float64(0.19181311588601757), 'htn': np.float64(0.5701401823350649), 'dm': np.float64(0.35633761395941577), 'cad': np.float64(0.04223260609889371), 'appet': np.float64(0.12002951207054023), 'pe': np.float64(0.13461643194022377), 'ane': np.float64(0.08422525420858915)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.031009615384615385, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.031009615384615385, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'sc', 'sg', 'pcv', 'bu', 'pc', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e27ab40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(16.766068977296104), 'bp': np.float64(21.916040779242316), 'sg': np.float64(255.89843873763292), 'al': np.float64(635.2906454093513), 'su': np.float64(50.2299076104111), 'rbc': np.float64(76.2536261914629), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(79.31982024688807), 'bu': np.float64(89.76157101946039), 'sc': np.float64(131.76366332845978), 'sod': np.float64(88.91223788321817), 'pot': np.float64(2.9750110704899333), 'hemo': np.float64(290.93218982441056), 'pcv': np.float64(246.91362061766003), 'wc': np.float64(28.769735889786624), 'rc': np.float64(121.8570781892068), 'htn': np.float64(362.20472440944866), 'dm': np.float64(226.3779527559055), 'cad': np.float64(26.829979585885095), 'appet': np.float64(76.25362619146303), 'pe': np.float64(85.52055993000877), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.02639117874385328), 'bp': np.float64(0.034497660145964615), 'sg': np.float64(0.40280529956921374), 'al': np.float64(1.0), 'su': np.float64(0.0790660274527501), 'rbc': np.float64(0.12002951207054002), 'pc': np.float64(0.2731921707022187), 'pcc': np.float64(0.06532856255922621), 'ba': np.float64(0.05701401823350653), 'bgr': np.float64(0.12485595501847524), 'bu': np.float64(0.1412921340304362), 'sc': np.float64(0.20740689994507552), 'sod': np.float64(0.13995521345340653), 'pot': np.float64(0.004682913390882651), 'hemo': np.float64(0.4579513202763242), 'pcv': np.float64(0.38866245300772617), 'wc': np.float64(0.04528594289508035), 'rc': np.float64(0.19181311588601757), 'htn': np.float64(0.5701401823350649), 'dm': np.float64(0.35633761395941577), 'cad': np.float64(0.04223260609889371), 'appet': np.float64(0.12002951207054023), 'pe': np.float64(0.13461643194022377), 'ane': np.float64(0.08422525420858915)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.031009615384615385, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.031009615384615385, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02797067901234568, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'sc', 'sg', 'pcv', 'bu', 'pc', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'ane', 'appet', 'su', 'bp', 'pcc', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34e180>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.017842376409068682), 'bp': np.float64(0.02753369317412335), 'sg': np.float64(0.2727904724846976), 'al': np.float64(1.0), 'su': np.float64(0.04472955974842766), 'rbc': np.float64(0.09524999999999996), 'pc': np.float64(0.24341666666666653), 'pcc': np.float64(0.05820833333333331), 'ba': np.float64(0.03762962962962962), 'bgr': np.float64(0.07567877089329354), 'bu': np.float64(0.15219063200814228), 'sc': np.float64(0.16679486836928556), 'sod': np.float64(0.12105888183400994), 'pot': np.float64(0.004911094003043878), 'hemo': np.float64(0.47659177224015353), 'pcv': np.float64(0.49411452164569863), 'wc': np.float64(0.029824291521684344), 'rc': np.float64(0.19222590294030711), 'htn': np.float64(0.6138333333333331), 'dm': np.float64(0.19049999999999984), 'cad': np.float64(0.03762962962962962), 'appet': np.float64(0.11994444444444437), 'pe': np.float64(0.08466666666666665), 'ane': np.float64(0.09524999999999996)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029138513513513514, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e34c6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.017842376409068682), 'bp': np.float64(0.02753369317412335), 'sg': np.float64(0.2727904724846976), 'al': np.float64(1.0), 'su': np.float64(0.04472955974842766), 'rbc': np.float64(0.09524999999999996), 'pc': np.float64(0.24341666666666653), 'pcc': np.float64(0.05820833333333331), 'ba': np.float64(0.03762962962962962), 'bgr': np.float64(0.07567877089329354), 'bu': np.float64(0.15219063200814228), 'sc': np.float64(0.16679486836928556), 'sod': np.float64(0.12105888183400994), 'pot': np.float64(0.004911094003043878), 'hemo': np.float64(0.47659177224015353), 'pcv': np.float64(0.49411452164569863), 'wc': np.float64(0.029824291521684344), 'rc': np.float64(0.19222590294030711), 'htn': np.float64(0.6138333333333331), 'dm': np.float64(0.19049999999999984), 'cad': np.float64(0.03762962962962962), 'appet': np.float64(0.11994444444444437), 'pe': np.float64(0.08466666666666665), 'ane': np.float64(0.09524999999999996)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029138513513513514, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22f770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.017842376409068682), 'bp': np.float64(0.02753369317412335), 'sg': np.float64(0.2727904724846976), 'al': np.float64(1.0), 'su': np.float64(0.04472955974842766), 'rbc': np.float64(0.09524999999999996), 'pc': np.float64(0.24341666666666653), 'pcc': np.float64(0.05820833333333331), 'ba': np.float64(0.03762962962962962), 'bgr': np.float64(0.07567877089329354), 'bu': np.float64(0.15219063200814228), 'sc': np.float64(0.16679486836928556), 'sod': np.float64(0.12105888183400994), 'pot': np.float64(0.004911094003043878), 'hemo': np.float64(0.47659177224015353), 'pcv': np.float64(0.49411452164569863), 'wc': np.float64(0.029824291521684344), 'rc': np.float64(0.19222590294030711), 'htn': np.float64(0.6138333333333331), 'dm': np.float64(0.19049999999999984), 'cad': np.float64(0.03762962962962962), 'appet': np.float64(0.11994444444444437), 'pe': np.float64(0.08466666666666665), 'ane': np.float64(0.09524999999999996)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029138513513513514, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'ane', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e27a600>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.72163982294562), 'bp': np.float64(19.631562496274945), 'sg': np.float64(194.49999588158124), 'al': np.float64(713.0014260028522), 'su': np.float64(31.892239885108705), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(26.829979585885095), 'bgr': np.float64(53.95907156506144), 'bu': np.float64(108.51213764608077), 'sc': np.float64(118.92497899725863), 'sod': np.float64(86.31515537795987), 'pot': np.float64(3.501617027404341), 'hemo': np.float64(339.810613228456), 'pcv': np.float64(352.3043585421003), 'wc': np.float64(21.264762384485714), 'rc': np.float64(137.05734291112483), 'htn': np.float64(437.6640419947506), 'dm': np.float64(135.82677165354323), 'cad': np.float64(26.829979585885095), 'appet': np.float64(85.52055993000872), 'pe': np.float64(60.36745406824148), 'ane': np.float64(67.91338582677164)}

Normalized Mathematical Scores
{'age': np.float64(0.017842376409068682), 'bp': np.float64(0.02753369317412335), 'sg': np.float64(0.2727904724846976), 'al': np.float64(1.0), 'su': np.float64(0.04472955974842766), 'rbc': np.float64(0.09524999999999996), 'pc': np.float64(0.24341666666666653), 'pcc': np.float64(0.05820833333333331), 'ba': np.float64(0.03762962962962962), 'bgr': np.float64(0.07567877089329354), 'bu': np.float64(0.15219063200814228), 'sc': np.float64(0.16679486836928556), 'sod': np.float64(0.12105888183400994), 'pot': np.float64(0.004911094003043878), 'hemo': np.float64(0.47659177224015353), 'pcv': np.float64(0.49411452164569863), 'wc': np.float64(0.029824291521684344), 'rc': np.float64(0.19222590294030711), 'htn': np.float64(0.6138333333333331), 'dm': np.float64(0.19049999999999984), 'cad': np.float64(0.03762962962962962), 'appet': np.float64(0.11994444444444437), 'pe': np.float64(0.08466666666666665), 'ane': np.float64(0.09524999999999996)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028309409888357256, 'ba': 0.027745885954841176, 'bgr': 0.028958333333333336, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.02844551282051282, 'appet': 0.02904040404040404, 'pe': 0.029138513513513514, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'rc', 'pc', 'bu', 'rbc', 'sod', 'ane', 'pe', 'appet', 'bgr', 'cad', 'bp', 'pcc', 'su']

SENSITIVITY: completed 15/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f6171d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011609023535999801), 'bp': np.float64(0.01885516962104032), 'sg': np.float64(0.15858942366625187), 'al': np.float64(1.0), 'su': np.float64(0.04413411078717204), 'rbc': np.float64(0.053396825396825436), 'pc': np.float64(0.1594970109255824), 'pcc': np.float64(0.036482303066154013), 'ba': np.float64(0.031783824640967524), 'bgr': np.float64(0.061966211420994295), 'bu': np.float64(0.10538135115905628), 'sc': np.float64(0.12782497983286603), 'sod': np.float64(0.06486280368719795), 'pot': np.float64(0.003201188315494682), 'hemo': np.float64(0.2142572902437448), 'pcv': np.float64(0.210904556321917), 'wc': np.float64(0.017928707710052595), 'rc': np.float64(0.10082516906490682), 'htn': np.float64(0.2942274052478136), 'dm': np.float64(0.13984882842025706), 'cad': np.float64(0.027461224489795932), 'appet': np.float64(0.0602219835302543), 'pe': np.float64(0.06780549256739736), 'ane': np.float64(0.04160791589363021)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e373c50>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011609023535999801), 'bp': np.float64(0.01885516962104032), 'sg': np.float64(0.15858942366625187), 'al': np.float64(1.0), 'su': np.float64(0.04413411078717204), 'rbc': np.float64(0.053396825396825436), 'pc': np.float64(0.1594970109255824), 'pcc': np.float64(0.036482303066154013), 'ba': np.float64(0.031783824640967524), 'bgr': np.float64(0.061966211420994295), 'bu': np.float64(0.10538135115905628), 'sc': np.float64(0.12782497983286603), 'sod': np.float64(0.06486280368719795), 'pot': np.float64(0.003201188315494682), 'hemo': np.float64(0.2142572902437448), 'pcv': np.float64(0.210904556321917), 'wc': np.float64(0.017928707710052595), 'rc': np.float64(0.10082516906490682), 'htn': np.float64(0.2942274052478136), 'dm': np.float64(0.13984882842025706), 'cad': np.float64(0.027461224489795932), 'appet': np.float64(0.0602219835302543), 'pe': np.float64(0.06780549256739736), 'ane': np.float64(0.04160791589363021)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e2f2030>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011609023535999801), 'bp': np.float64(0.01885516962104032), 'sg': np.float64(0.15858942366625187), 'al': np.float64(1.0), 'su': np.float64(0.04413411078717204), 'rbc': np.float64(0.053396825396825436), 'pc': np.float64(0.1594970109255824), 'pcc': np.float64(0.036482303066154013), 'ba': np.float64(0.031783824640967524), 'bgr': np.float64(0.061966211420994295), 'bu': np.float64(0.10538135115905628), 'sc': np.float64(0.12782497983286603), 'sod': np.float64(0.06486280368719795), 'pot': np.float64(0.003201188315494682), 'hemo': np.float64(0.2142572902437448), 'pcv': np.float64(0.210904556321917), 'wc': np.float64(0.017928707710052595), 'rc': np.float64(0.10082516906490682), 'htn': np.float64(0.2942274052478136), 'dm': np.float64(0.13984882842025706), 'cad': np.float64(0.027461224489795932), 'appet': np.float64(0.0602219835302543), 'pe': np.float64(0.06780549256739736), 'ane': np.float64(0.04160791589363021)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'pe', 'rc', 'sod', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e373530>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(13.77898608042211), 'bp': np.float64(22.37958420418839), 'sg': np.float64(188.2330115382313), 'al': np.float64(1186.920332936979), 'su': np.float64(52.38367346938776), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(73.54895629064978), 'bu': np.float64(125.07926840305579), 'sc': np.float64(151.71806762088798), 'sod': np.float64(76.9869805476349), 'pot': np.float64(3.799555501220915), 'hemo': np.float64(254.30633427028053), 'pcv': np.float64(250.3269062075356), 'wc': np.float64(21.279947724345412), 'rc': np.float64(119.67144323494641), 'htn': np.float64(349.2244897959184), 'dm': np.float64(165.98941798941797), 'cad': np.float64(32.59428571428571), 'appet': np.float64(71.4786967418547), 'pe': np.float64(80.47971781305114), 'ane': np.float64(49.38528138528139)}

Normalized Mathematical Scores
{'age': np.float64(0.011609023535999801), 'bp': np.float64(0.01885516962104032), 'sg': np.float64(0.15858942366625187), 'al': np.float64(1.0), 'su': np.float64(0.04413411078717204), 'rbc': np.float64(0.053396825396825436), 'pc': np.float64(0.1594970109255824), 'pcc': np.float64(0.036482303066154013), 'ba': np.float64(0.031783824640967524), 'bgr': np.float64(0.061966211420994295), 'bu': np.float64(0.10538135115905628), 'sc': np.float64(0.12782497983286603), 'sod': np.float64(0.06486280368719795), 'pot': np.float64(0.003201188315494682), 'hemo': np.float64(0.2142572902437448), 'pcv': np.float64(0.210904556321917), 'wc': np.float64(0.017928707710052595), 'rc': np.float64(0.10082516906490682), 'htn': np.float64(0.2942274052478136), 'dm': np.float64(0.13984882842025706), 'cad': np.float64(0.027461224489795932), 'appet': np.float64(0.0602219835302543), 'pe': np.float64(0.06780549256739736), 'ane': np.float64(0.04160791589363021)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027583600982429624, 'bgr': 0.0293236301369863, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.02967032967032967, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028125, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'pe', 'rc', 'sod', 'rbc', 'bgr', 'appet', 'ane', 'su', 'bp', 'cad', 'pcc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3affb0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01839283687836374), 'bp': np.float64(0.017431421674021817), 'sg': np.float64(0.27871848336214294), 'al': np.float64(1.0), 'su': np.float64(0.06549839935789539), 'rbc': np.float64(0.09300291545189499), 'pc': np.float64(0.277800916284881), 'pcc': np.float64(0.055358878245175595), 'ba': np.float64(0.04088040239643735), 'bgr': np.float64(0.10334132114414772), 'bu': np.float64(0.14432409135792643), 'sc': np.float64(0.17198570400339347), 'sod': np.float64(0.12695750984064194), 'pot': np.float64(0.004800923725218728), 'hemo': np.float64(0.4177807108736354), 'pcv': np.float64(0.3743567845855554), 'wc': np.float64(0.04357919903775753), 'rc': np.float64(0.29452650822993115), 'htn': np.float64(0.4317992503123696), 'dm': np.float64(0.3690591883011706), 'cad': np.float64(0.02847028024037601), 'appet': np.float64(0.11809894025637446), 'pe': np.float64(0.1328613077884214), 'ane': np.float64(0.08224747624997517)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02792120864410021, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.029857397504456328, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3723c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01839283687836374), 'bp': np.float64(0.017431421674021817), 'sg': np.float64(0.27871848336214294), 'al': np.float64(1.0), 'su': np.float64(0.06549839935789539), 'rbc': np.float64(0.09300291545189499), 'pc': np.float64(0.277800916284881), 'pcc': np.float64(0.055358878245175595), 'ba': np.float64(0.04088040239643735), 'bgr': np.float64(0.10334132114414772), 'bu': np.float64(0.14432409135792643), 'sc': np.float64(0.17198570400339347), 'sod': np.float64(0.12695750984064194), 'pot': np.float64(0.004800923725218728), 'hemo': np.float64(0.4177807108736354), 'pcv': np.float64(0.3743567845855554), 'wc': np.float64(0.04357919903775753), 'rc': np.float64(0.29452650822993115), 'htn': np.float64(0.4317992503123696), 'dm': np.float64(0.3690591883011706), 'cad': np.float64(0.02847028024037601), 'appet': np.float64(0.11809894025637446), 'pe': np.float64(0.1328613077884214), 'ane': np.float64(0.08224747624997517)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02792120864410021, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.029857397504456328, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'rc', 'sg', 'bu', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3063f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01839283687836374), 'bp': np.float64(0.017431421674021817), 'sg': np.float64(0.27871848336214294), 'al': np.float64(1.0), 'su': np.float64(0.06549839935789539), 'rbc': np.float64(0.09300291545189499), 'pc': np.float64(0.277800916284881), 'pcc': np.float64(0.055358878245175595), 'ba': np.float64(0.04088040239643735), 'bgr': np.float64(0.10334132114414772), 'bu': np.float64(0.14432409135792643), 'sc': np.float64(0.17198570400339347), 'sod': np.float64(0.12695750984064194), 'pot': np.float64(0.004800923725218728), 'hemo': np.float64(0.4177807108736354), 'pcv': np.float64(0.3743567845855554), 'wc': np.float64(0.04357919903775753), 'rc': np.float64(0.29452650822993115), 'htn': np.float64(0.4317992503123696), 'dm': np.float64(0.3690591883011706), 'cad': np.float64(0.02847028024037601), 'appet': np.float64(0.11809894025637446), 'pe': np.float64(0.1328613077884214), 'ane': np.float64(0.08224747624997517)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02792120864410021, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.029857397504456328, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'rc', 'sg', 'bu', 'pc', 'pe', 'sod', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327620>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.533984797313163), 'bp': np.float64(11.878818678306109), 'sg': np.float64(189.93553067937964), 'al': np.float64(681.4601184256362), 'su': np.float64(44.634546983121005), 'rbc': np.float64(63.37777777777779), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(70.42298894515261), 'bu': np.float64(98.35111238844489), 'sc': np.float64(117.20139821766894), 'sod': np.float64(86.51647969102774), 'pot': np.float64(3.271638050340001), 'hemo': np.float64(284.70089270789407), 'pcv': np.float64(255.10921875711296), 'wc': np.float64(29.69748613716462), 'rc': np.float64(200.708069177858), 'htn': np.float64(294.2539682539683), 'dm': np.float64(251.4991181657849), 'cad': np.float64(19.401360544217688), 'appet': np.float64(80.47971781305108), 'pe': np.float64(90.53968253968254), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01839283687836374), 'bp': np.float64(0.017431421674021817), 'sg': np.float64(0.27871848336214294), 'al': np.float64(1.0), 'su': np.float64(0.06549839935789539), 'rbc': np.float64(0.09300291545189499), 'pc': np.float64(0.277800916284881), 'pcc': np.float64(0.055358878245175595), 'ba': np.float64(0.04088040239643735), 'bgr': np.float64(0.10334132114414772), 'bu': np.float64(0.14432409135792643), 'sc': np.float64(0.17198570400339347), 'sod': np.float64(0.12695750984064194), 'pot': np.float64(0.004800923725218728), 'hemo': np.float64(0.4177807108736354), 'pcv': np.float64(0.3743567845855554), 'wc': np.float64(0.04357919903775753), 'rc': np.float64(0.29452650822993115), 'htn': np.float64(0.4317992503123696), 'dm': np.float64(0.3690591883011706), 'cad': np.float64(0.02847028024037601), 'appet': np.float64(0.11809894025637446), 'pe': np.float64(0.1328613077884214), 'ane': np.float64(0.08224747624997517)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02792120864410021, 'sg': 0.030309988518943745, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.029857397504456328, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030536130536130537, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.02797067901234568, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'rc', 'sg', 'bu', 'pc', 'pe', 'sod', 'rbc', 'bgr', 'appet', 'ane', 'su', 'pcc', 'cad', 'bp']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e309fa0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.017921554456675308), 'bp': np.float64(0.025152860398481046), 'sg': np.float64(0.30275107426571707), 'al': np.float64(1.0), 'su': np.float64(0.05733428596260135), 'rbc': np.float64(0.0778643819043652), 'pc': np.float64(0.301874219075385), 'pcc': np.float64(0.0778643819043652), 'ba': np.float64(0.05240871858947658), 'bgr': np.float64(0.0778255391360728), 'bu': np.float64(0.13783730092751648), 'sc': np.float64(0.15791408532703122), 'sod': np.float64(0.12936466905498983), 'pot': np.float64(0.006049408769959829), 'hemo': np.float64(0.3788958169974014), 'pcv': np.float64(0.38425863187949816), 'wc': np.float64(0.02724331691217639), 'rc': np.float64(0.17744744524666436), 'htn': np.float64(0.4851549949425831), 'dm': np.float64(0.1796870351639197), 'cad': np.float64(0.05240871858947658), 'appet': np.float64(0.07786438190436527), 'pe': np.float64(0.09930072995900822), 'ane': np.float64(0.08804664723032064)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.028782894736842105, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e371a60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.017921554456675308), 'bp': np.float64(0.025152860398481046), 'sg': np.float64(0.30275107426571707), 'al': np.float64(1.0), 'su': np.float64(0.05733428596260135), 'rbc': np.float64(0.0778643819043652), 'pc': np.float64(0.301874219075385), 'pcc': np.float64(0.0778643819043652), 'ba': np.float64(0.05240871858947658), 'bgr': np.float64(0.0778255391360728), 'bu': np.float64(0.13783730092751648), 'sc': np.float64(0.15791408532703122), 'sod': np.float64(0.12936466905498983), 'pot': np.float64(0.006049408769959829), 'hemo': np.float64(0.3788958169974014), 'pcv': np.float64(0.38425863187949816), 'wc': np.float64(0.02724331691217639), 'rc': np.float64(0.17744744524666436), 'htn': np.float64(0.4851549949425831), 'dm': np.float64(0.1796870351639197), 'cad': np.float64(0.05240871858947658), 'appet': np.float64(0.07786438190436527), 'pe': np.float64(0.09930072995900822), 'ane': np.float64(0.08804664723032064)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.028782894736842105, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e305a30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.017921554456675308), 'bp': np.float64(0.025152860398481046), 'sg': np.float64(0.30275107426571707), 'al': np.float64(1.0), 'su': np.float64(0.05733428596260135), 'rbc': np.float64(0.0778643819043652), 'pc': np.float64(0.301874219075385), 'pcc': np.float64(0.0778643819043652), 'ba': np.float64(0.05240871858947658), 'bgr': np.float64(0.0778255391360728), 'bu': np.float64(0.13783730092751648), 'sc': np.float64(0.15791408532703122), 'sod': np.float64(0.12936466905498983), 'pot': np.float64(0.006049408769959829), 'hemo': np.float64(0.3788958169974014), 'pcv': np.float64(0.38425863187949816), 'wc': np.float64(0.02724331691217639), 'rc': np.float64(0.17744744524666436), 'htn': np.float64(0.4851549949425831), 'dm': np.float64(0.1796870351639197), 'cad': np.float64(0.05240871858947658), 'appet': np.float64(0.07786438190436527), 'pe': np.float64(0.09930072995900822), 'ane': np.float64(0.08804664723032064)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.028782894736842105, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'ane', 'bgr']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22c6e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(12.900301505136307), 'bp': np.float64(18.105543447217457), 'sg': np.float64(217.92641639837984), 'al': np.float64(719.8204562178078), 'su': np.float64(41.270391878521956), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(217.29523809523806), 'pcc': np.float64(56.048374905517775), 'ba': np.float64(37.724867724867735), 'bgr': np.float64(56.02041508632478), 'bu': np.float64(99.21810883747617), 'sc': np.float64(113.66978894332144), 'sod': np.float64(93.11933509762851), 'pot': np.float64(4.354488180640491), 'hemo': np.float64(272.73695985008845), 'pcv': np.float64(276.597223705131), 'wc': np.float64(19.610296808609128), 'rc': np.float64(127.73030099213841), 'htn': np.float64(349.2244897959184), 'dm': np.float64(129.34240362811795), 'cad': np.float64(37.724867724867735), 'appet': np.float64(56.048374905517825), 'pe': np.float64(71.47869674185463), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.017921554456675308), 'bp': np.float64(0.025152860398481046), 'sg': np.float64(0.30275107426571707), 'al': np.float64(1.0), 'su': np.float64(0.05733428596260135), 'rbc': np.float64(0.0778643819043652), 'pc': np.float64(0.301874219075385), 'pcc': np.float64(0.0778643819043652), 'ba': np.float64(0.05240871858947658), 'bgr': np.float64(0.0778255391360728), 'bu': np.float64(0.13783730092751648), 'sc': np.float64(0.15791408532703122), 'sod': np.float64(0.12936466905498983), 'pot': np.float64(0.006049408769959829), 'hemo': np.float64(0.3788958169974014), 'pcv': np.float64(0.38425863187949816), 'wc': np.float64(0.02724331691217639), 'rc': np.float64(0.17744744524666436), 'htn': np.float64(0.4851549949425831), 'dm': np.float64(0.1796870351639197), 'cad': np.float64(0.05240871858947658), 'appet': np.float64(0.07786438190436527), 'pe': np.float64(0.09930072995900822), 'ane': np.float64(0.08804664723032064)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028373015873015873, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027745885954841176, 'bgr': 0.028782894736842105, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.02844551282051282, 'appet': 0.028665028665028666, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'ane', 'bgr', 'appet', 'pcc', 'cad', 'bp', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f6666d6fc80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.015171709341515448), 'bp': np.float64(0.022138833893878995), 'sg': np.float64(0.30249537481163835), 'al': np.float64(1.0), 'su': np.float64(0.07086198635439013), 'rbc': np.float64(0.130507640263508), 'pc': np.float64(0.26485374053476607), 'pcc': np.float64(0.06333459012787886), 'ba': np.float64(0.05527382411160338), 'bgr': np.float64(0.10803591170557679), 'bu': np.float64(0.16784136632787075), 'sc': np.float64(0.18519946504044563), 'sod': np.float64(0.12703240716170627), 'pot': np.float64(0.00384499441099777), 'hemo': np.float64(0.47901942146760607), 'pcv': np.float64(0.4272094177071331), 'wc': np.float64(0.048339442074078004), 'rc': np.float64(0.17397616937265273), 'htn': np.float64(0.5527382411160334), 'dm': np.float64(0.26485374053476607), 'cad': np.float64(0.04783311701965677), 'appet': np.float64(0.10363842020925647), 'pe': np.float64(0.1036384202092563), 'ane': np.float64(0.08165451289214132)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.0304147465437788, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029138513513513514, 'ane': 0.028958333333333336}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e346930>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.015171709341515448), 'bp': np.float64(0.022138833893878995), 'sg': np.float64(0.30249537481163835), 'al': np.float64(1.0), 'su': np.float64(0.07086198635439013), 'rbc': np.float64(0.130507640263508), 'pc': np.float64(0.26485374053476607), 'pcc': np.float64(0.06333459012787886), 'ba': np.float64(0.05527382411160338), 'bgr': np.float64(0.10803591170557679), 'bu': np.float64(0.16784136632787075), 'sc': np.float64(0.18519946504044563), 'sod': np.float64(0.12703240716170627), 'pot': np.float64(0.00384499441099777), 'hemo': np.float64(0.47901942146760607), 'pcv': np.float64(0.4272094177071331), 'wc': np.float64(0.048339442074078004), 'rc': np.float64(0.17397616937265273), 'htn': np.float64(0.5527382411160334), 'dm': np.float64(0.26485374053476607), 'cad': np.float64(0.04783311701965677), 'appet': np.float64(0.10363842020925647), 'pe': np.float64(0.1036384202092563), 'ane': np.float64(0.08165451289214132)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.0304147465437788, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029138513513513514, 'ane': 0.028958333333333336}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'rbc', 'bu', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311a60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.015171709341515448), 'bp': np.float64(0.022138833893878995), 'sg': np.float64(0.30249537481163835), 'al': np.float64(1.0), 'su': np.float64(0.07086198635439013), 'rbc': np.float64(0.130507640263508), 'pc': np.float64(0.26485374053476607), 'pcc': np.float64(0.06333459012787886), 'ba': np.float64(0.05527382411160338), 'bgr': np.float64(0.10803591170557679), 'bu': np.float64(0.16784136632787075), 'sc': np.float64(0.18519946504044563), 'sod': np.float64(0.12703240716170627), 'pot': np.float64(0.00384499441099777), 'hemo': np.float64(0.47901942146760607), 'pcv': np.float64(0.4272094177071331), 'wc': np.float64(0.048339442074078004), 'rc': np.float64(0.17397616937265273), 'htn': np.float64(0.5527382411160334), 'dm': np.float64(0.26485374053476607), 'cad': np.float64(0.04783311701965677), 'appet': np.float64(0.10363842020925647), 'pe': np.float64(0.1036384202092563), 'ane': np.float64(0.08165451289214132)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.0304147465437788, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029138513513513514, 'ane': 0.028958333333333336}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'rbc', 'bu', 'pc', 'rc', 'sod', 'bgr', 'pe', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22f7d0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(9.941893634441458), 'bp': np.float64(14.507391804642046), 'sg': np.float64(198.22267706239975), 'al': np.float64(655.2915963949253), 'su': np.float64(46.435264161883715), 'rbc': np.float64(85.52055993000877), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(70.7950250495286), 'bu': np.float64(109.98503688209587), 'sc': np.float64(121.35965309783977), 'sod': np.float64(83.24326888288464), 'pot': np.float64(2.519592525712294), 'hemo': np.float64(313.8974013976811), 'pcv': np.float64(279.9467413242537), 'wc': np.float64(31.676430165562593), 'rc': np.float64(114.00512176287951), 'htn': np.float64(362.20472440944866), 'dm': np.float64(173.55643044619418), 'cad': np.float64(31.344639612356154), 'appet': np.float64(67.91338582677176), 'pe': np.float64(67.91338582677164), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.015171709341515448), 'bp': np.float64(0.022138833893878995), 'sg': np.float64(0.30249537481163835), 'al': np.float64(1.0), 'su': np.float64(0.07086198635439013), 'rbc': np.float64(0.130507640263508), 'pc': np.float64(0.26485374053476607), 'pcc': np.float64(0.06333459012787886), 'ba': np.float64(0.05527382411160338), 'bgr': np.float64(0.10803591170557679), 'bu': np.float64(0.16784136632787075), 'sc': np.float64(0.18519946504044563), 'sod': np.float64(0.12703240716170627), 'pot': np.float64(0.00384499441099777), 'hemo': np.float64(0.47901942146760607), 'pcv': np.float64(0.4272094177071331), 'wc': np.float64(0.048339442074078004), 'rc': np.float64(0.17397616937265273), 'htn': np.float64(0.5527382411160334), 'dm': np.float64(0.26485374053476607), 'cad': np.float64(0.04783311701965677), 'appet': np.float64(0.10363842020925647), 'pe': np.float64(0.1036384202092563), 'ane': np.float64(0.08165451289214132)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028309409888357256, 'rbc': 0.0304147465437788, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027745885954841176, 'bgr': 0.029513888888888888, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027583600982429624, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.028125, 'appet': 0.028850145288501453, 'pe': 0.029138513513513514, 'ane': 0.028958333333333336}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'sc', 'dm', 'pcv', 'sg', 'rbc', 'bu', 'pc', 'rc', 'sod', 'bgr', 'pe', 'ane', 'appet', 'su', 'bp', 'pcc', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e339a60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.022208875237780486), 'bp': np.float64(0.014001545990330327), 'sg': np.float64(0.3660092465399996), 'al': np.float64(1.0), 'su': np.float64(0.05447292724196276), 'rbc': np.float64(0.08933333333333332), 'pc': np.float64(0.2568333333333332), 'pcc': np.float64(0.06141666666666665), 'ba': np.float64(0.053599999999999995), 'bgr': np.float64(0.09989394811749593), 'bu': np.float64(0.1517862795737709), 'sc': np.float64(0.16181644227921502), 'sod': np.float64(0.14205547977101546), 'pot': np.float64(0.0056190809298163205), 'hemo': np.float64(0.4464463321529234), 'pcv': np.float64(0.44881307986920355), 'wc': np.float64(0.03373371847866787), 'rc': np.float64(0.19174027234874197), 'htn': np.float64(0.5359999999999996), 'dm': np.float64(0.22676923076923072), 'cad': np.float64(0.053599999999999995), 'appet': np.float64(0.12655555555555548), 'pe': np.float64(0.12655555555555556), 'ane': np.float64(0.06991304347826084)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e344c20>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.022208875237780486), 'bp': np.float64(0.014001545990330327), 'sg': np.float64(0.3660092465399996), 'al': np.float64(1.0), 'su': np.float64(0.05447292724196276), 'rbc': np.float64(0.08933333333333332), 'pc': np.float64(0.2568333333333332), 'pcc': np.float64(0.06141666666666665), 'ba': np.float64(0.053599999999999995), 'bgr': np.float64(0.09989394811749593), 'bu': np.float64(0.1517862795737709), 'sc': np.float64(0.16181644227921502), 'sod': np.float64(0.14205547977101546), 'pot': np.float64(0.0056190809298163205), 'hemo': np.float64(0.4464463321529234), 'pcv': np.float64(0.44881307986920355), 'wc': np.float64(0.03373371847866787), 'rc': np.float64(0.19174027234874197), 'htn': np.float64(0.5359999999999996), 'dm': np.float64(0.22676923076923072), 'cad': np.float64(0.053599999999999995), 'appet': np.float64(0.12655555555555548), 'pe': np.float64(0.12655555555555556), 'ane': np.float64(0.06991304347826084)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e372060>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.022208875237780486), 'bp': np.float64(0.014001545990330327), 'sg': np.float64(0.3660092465399996), 'al': np.float64(1.0), 'su': np.float64(0.05447292724196276), 'rbc': np.float64(0.08933333333333332), 'pc': np.float64(0.2568333333333332), 'pcc': np.float64(0.06141666666666665), 'ba': np.float64(0.053599999999999995), 'bgr': np.float64(0.09989394811749593), 'bu': np.float64(0.1517862795737709), 'sc': np.float64(0.16181644227921502), 'sod': np.float64(0.14205547977101546), 'pot': np.float64(0.0056190809298163205), 'hemo': np.float64(0.4464463321529234), 'pcv': np.float64(0.44881307986920355), 'wc': np.float64(0.03373371847866787), 'rc': np.float64(0.19174027234874197), 'htn': np.float64(0.5359999999999996), 'dm': np.float64(0.22676923076923072), 'cad': np.float64(0.053599999999999995), 'appet': np.float64(0.12655555555555548), 'pe': np.float64(0.12655555555555556), 'ane': np.float64(0.06991304347826084)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e2f1f40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.007760326388276), 'bp': np.float64(9.461615870772054), 'sg': np.float64(247.33260872076605), 'al': np.float64(675.7550828534495), 'su': np.float64(36.81035746166247), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(173.55643044619418), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(36.22047244094489), 'bgr': np.float64(67.50384318669664), 'bu': np.float64(102.5703499293904), 'sc': np.float64(109.34828335944137), 'sod': np.float64(95.99471250244908), 'pot': np.float64(3.7971224992882657), 'hemo': np.float64(301.68837817361737), 'pcv': np.float64(303.2877199727255), 'wc': np.float64(22.79573172550715), 'rc': np.float64(129.5694636273671), 'htn': np.float64(362.20472440944866), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(85.52055993000872), 'pe': np.float64(85.52055993000877), 'ane': np.float64(47.24409448818897)}

Normalized Mathematical Scores
{'age': np.float64(0.022208875237780486), 'bp': np.float64(0.014001545990330327), 'sg': np.float64(0.3660092465399996), 'al': np.float64(1.0), 'su': np.float64(0.05447292724196276), 'rbc': np.float64(0.08933333333333332), 'pc': np.float64(0.2568333333333332), 'pcc': np.float64(0.06141666666666665), 'ba': np.float64(0.053599999999999995), 'bgr': np.float64(0.09989394811749593), 'bu': np.float64(0.1517862795737709), 'sc': np.float64(0.16181644227921502), 'sod': np.float64(0.14205547977101546), 'pot': np.float64(0.0056190809298163205), 'hemo': np.float64(0.4464463321529234), 'pcv': np.float64(0.44881307986920355), 'wc': np.float64(0.03373371847866787), 'rc': np.float64(0.19174027234874197), 'htn': np.float64(0.5359999999999996), 'dm': np.float64(0.22676923076923072), 'cad': np.float64(0.053599999999999995), 'appet': np.float64(0.12655555555555548), 'pe': np.float64(0.12655555555555556), 'ane': np.float64(0.06991304347826084)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.028068137824235385, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.02946236559139785, 'pc': 0.030303030303030304, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.02792120864410021, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027425373134328357, 'rc': 0.030090497737556562, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'pc', 'bu', 'rc', 'sod', 'pe', 'rbc', 'bgr', 'appet', 'ane', 'cad', 'pcc', 'bp', 'su']

SENSITIVITY: completed 20/25 CV runs

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3117f0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.02592363812810592), 'bp': np.float64(0.019433680541504825), 'sg': np.float64(0.3338522536531136), 'al': np.float64(1.0), 'su': np.float64(0.06785258103171045), 'rbc': np.float64(0.10254412622085562), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.05412051106100715), 'ba': np.float64(0.03367498466018221), 'bgr': np.float64(0.10981639191222901), 'bu': np.float64(0.18118742746022087), 'sc': np.float64(0.21313895847733438), 'sod': np.float64(0.13811911241835761), 'pot': np.float64(0.004447608119905612), 'hemo': np.float64(0.40726794182970727), 'pcv': np.float64(0.37589428356496796), 'wc': np.float64(0.02431446188519591), 'rc': np.float64(0.18302875430826873), 'htn': np.float64(0.7533575139692192), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.03996591586043604), 'appet': np.float64(0.11545709026348179), 'pe': np.float64(0.14612537986471927), 'ane': np.float64(0.090922458582492)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02792120864410021, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3af860>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.02592363812810592), 'bp': np.float64(0.019433680541504825), 'sg': np.float64(0.3338522536531136), 'al': np.float64(1.0), 'su': np.float64(0.06785258103171045), 'rbc': np.float64(0.10254412622085562), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.05412051106100715), 'ba': np.float64(0.03367498466018221), 'bgr': np.float64(0.10981639191222901), 'bu': np.float64(0.18118742746022087), 'sc': np.float64(0.21313895847733438), 'sod': np.float64(0.13811911241835761), 'pot': np.float64(0.004447608119905612), 'hemo': np.float64(0.40726794182970727), 'pcv': np.float64(0.37589428356496796), 'wc': np.float64(0.02431446188519591), 'rc': np.float64(0.18302875430826873), 'htn': np.float64(0.7533575139692192), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.03996591586043604), 'appet': np.float64(0.11545709026348179), 'pe': np.float64(0.14612537986471927), 'ane': np.float64(0.090922458582492)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02792120864410021, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'pc', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e327320>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.02592363812810592), 'bp': np.float64(0.019433680541504825), 'sg': np.float64(0.3338522536531136), 'al': np.float64(1.0), 'su': np.float64(0.06785258103171045), 'rbc': np.float64(0.10254412622085562), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.05412051106100715), 'ba': np.float64(0.03367498466018221), 'bgr': np.float64(0.10981639191222901), 'bu': np.float64(0.18118742746022087), 'sc': np.float64(0.21313895847733438), 'sod': np.float64(0.13811911241835761), 'pot': np.float64(0.004447608119905612), 'hemo': np.float64(0.40726794182970727), 'pcv': np.float64(0.37589428356496796), 'wc': np.float64(0.02431446188519591), 'rc': np.float64(0.18302875430826873), 'htn': np.float64(0.7533575139692192), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.03996591586043604), 'appet': np.float64(0.11545709026348179), 'pe': np.float64(0.14612537986471927), 'ane': np.float64(0.090922458582492)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02792120864410021, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'pc', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f614d40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(18.070151226541917), 'bp': np.float64(13.546306445798045), 'sg': np.float64(232.7127342629038), 'al': np.float64(697.0530578017365), 'su': np.float64(47.296849087893875), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(37.724867724867735), 'ba': np.float64(23.473251028806583), 'bgr': np.float64(76.54785177917312), 'bu': np.float64(126.29725034637727), 'sc': np.float64(148.56916274330328), 'sod': np.float64(96.27634965207797), 'pot': np.float64(3.100218839884039), 'hemo': np.float64(283.8873641970172), 'pcv': np.float64(262.01825976915393), 'wc': np.float64(16.94847000587958), 'rc': np.float64(127.58075285622148), 'htn': np.float64(525.1301587301587), 'dm': np.float64(251.4991181657849), 'cad': np.float64(27.85836385836386), 'appet': np.float64(80.47971781305108), 'pe': np.float64(101.85714285714286), 'ane': np.float64(63.37777777777779)}

Normalized Mathematical Scores
{'age': np.float64(0.02592363812810592), 'bp': np.float64(0.019433680541504825), 'sg': np.float64(0.3338522536531136), 'al': np.float64(1.0), 'su': np.float64(0.06785258103171045), 'rbc': np.float64(0.10254412622085562), 'pc': np.float64(0.27158656459705394), 'pcc': np.float64(0.05412051106100715), 'ba': np.float64(0.03367498466018221), 'bgr': np.float64(0.10981639191222901), 'bu': np.float64(0.18118742746022087), 'sc': np.float64(0.21313895847733438), 'sod': np.float64(0.13811911241835761), 'pot': np.float64(0.004447608119905612), 'hemo': np.float64(0.40726794182970727), 'pcv': np.float64(0.37589428356496796), 'wc': np.float64(0.02431446188519591), 'rc': np.float64(0.18302875430826873), 'htn': np.float64(0.7533575139692192), 'dm': np.float64(0.360803407073381), 'cad': np.float64(0.03996591586043604), 'appet': np.float64(0.11545709026348179), 'pe': np.float64(0.14612537986471927), 'ane': np.float64(0.090922458582492)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.02797067901234568, 'bp': 0.02792120864410021, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.03007688828584351, 'pcc': 0.027972027972027972, 'ba': 0.027425373134328357, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.027777777777777776, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.02712049508554787, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.0315136476426799, 'cad': 0.028283227848101264, 'appet': 0.028850145288501453, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'dm', 'pcv', 'sc', 'sg', 'bu', 'pc', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'appet', 'ane', 'cad', 'su', 'pcc', 'age']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3735c0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.02394167469674263), 'bp': np.float64(0.023435784512764235), 'sg': np.float64(0.28136628296595967), 'al': np.float64(1.0), 'su': np.float64(0.05870097953085933), 'rbc': np.float64(0.08559687027111833), 'pc': np.float64(0.25349842349523494), 'pcc': np.float64(0.07542101856056578), 'ba': np.float64(0.06613002352049607), 'bgr': np.float64(0.0810981749216549), 'bu': np.float64(0.1388484575204332), 'sc': np.float64(0.15583223673291507), 'sod': np.float64(0.12118290237580666), 'pot': np.float64(0.006359989549386573), 'hemo': np.float64(0.46408357391759525), 'pcv': np.float64(0.4732149117127621), 'wc': np.float64(0.045016399872454635), 'rc': np.float64(0.18898929683624632), 'htn': np.float64(0.6452687143515072), 'dm': np.float64(0.25349842349523494), 'cad': np.float64(0.05761327806709888), 'appet': np.float64(0.10916200054818742), 'pe': np.float64(0.10916200054818731), 'ane': np.float64(0.08559687027111833)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.029236022193768675, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617f80>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.02394167469674263), 'bp': np.float64(0.023435784512764235), 'sg': np.float64(0.28136628296595967), 'al': np.float64(1.0), 'su': np.float64(0.05870097953085933), 'rbc': np.float64(0.08559687027111833), 'pc': np.float64(0.25349842349523494), 'pcc': np.float64(0.07542101856056578), 'ba': np.float64(0.06613002352049607), 'bgr': np.float64(0.0810981749216549), 'bu': np.float64(0.1388484575204332), 'sc': np.float64(0.15583223673291507), 'sod': np.float64(0.12118290237580666), 'pot': np.float64(0.006359989549386573), 'hemo': np.float64(0.46408357391759525), 'pcv': np.float64(0.4732149117127621), 'wc': np.float64(0.045016399872454635), 'rc': np.float64(0.18898929683624632), 'htn': np.float64(0.6452687143515072), 'dm': np.float64(0.25349842349523494), 'cad': np.float64(0.05761327806709888), 'appet': np.float64(0.10916200054818742), 'pe': np.float64(0.10916200054818731), 'ane': np.float64(0.08559687027111833)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.029236022193768675, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'bu', 'rc', 'pc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311d30>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.02394167469674263), 'bp': np.float64(0.023435784512764235), 'sg': np.float64(0.28136628296595967), 'al': np.float64(1.0), 'su': np.float64(0.05870097953085933), 'rbc': np.float64(0.08559687027111833), 'pc': np.float64(0.25349842349523494), 'pcc': np.float64(0.07542101856056578), 'ba': np.float64(0.06613002352049607), 'bgr': np.float64(0.0810981749216549), 'bu': np.float64(0.1388484575204332), 'sc': np.float64(0.15583223673291507), 'sod': np.float64(0.12118290237580666), 'pot': np.float64(0.006359989549386573), 'hemo': np.float64(0.46408357391759525), 'pcv': np.float64(0.4732149117127621), 'wc': np.float64(0.045016399872454635), 'rc': np.float64(0.18898929683624632), 'htn': np.float64(0.6452687143515072), 'dm': np.float64(0.25349842349523494), 'cad': np.float64(0.05761327806709888), 'appet': np.float64(0.10916200054818742), 'pe': np.float64(0.10916200054818731), 'ane': np.float64(0.08559687027111833)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.029236022193768675, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'bu', 'rc', 'pc', 'sod', 'rbc', 'pe', 'ane', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e2f3770>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(15.676881117483497), 'bp': np.float64(15.345626918552703), 'sg': np.float64(184.2371439925086), 'al': np.float64(654.7946756463284), 'su': np.float64(38.4370888520308), 'rbc': np.float64(56.048374905517775), 'pc': np.float64(165.98941798941797), 'pcc': np.float64(49.38528138528139), 'ba': np.float64(43.3015873015873), 'bgr': np.float64(53.10265314333423), 'bu': np.float64(90.91723070608506), 'sc': np.float64(102.03811890677099), 'sod': np.float64(79.349919255047), 'pot': np.float64(4.164487294104619), 'hemo': np.float64(303.8794532561607), 'pcv': np.float64(309.858604625964), 'wc': np.float64(29.47649895324935), 'rc': np.float64(123.74918532251759), 'htn': np.float64(422.51851851851853), 'dm': np.float64(165.98941798941797), 'cad': np.float64(37.724867724867735), 'appet': np.float64(71.4786967418547), 'pe': np.float64(71.47869674185463), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.02394167469674263), 'bp': np.float64(0.023435784512764235), 'sg': np.float64(0.28136628296595967), 'al': np.float64(1.0), 'su': np.float64(0.05870097953085933), 'rbc': np.float64(0.08559687027111833), 'pc': np.float64(0.25349842349523494), 'pcc': np.float64(0.07542101856056578), 'ba': np.float64(0.06613002352049607), 'bgr': np.float64(0.0810981749216549), 'bu': np.float64(0.1388484575204332), 'sc': np.float64(0.15583223673291507), 'sod': np.float64(0.12118290237580666), 'pot': np.float64(0.006359989549386573), 'hemo': np.float64(0.46408357391759525), 'pcv': np.float64(0.4732149117127621), 'wc': np.float64(0.045016399872454635), 'rc': np.float64(0.18898929683624632), 'htn': np.float64(0.6452687143515072), 'dm': np.float64(0.25349842349523494), 'cad': np.float64(0.05761327806709888), 'appet': np.float64(0.10916200054818742), 'pe': np.float64(0.10916200054818731), 'ane': np.float64(0.08559687027111833)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.02821869488536155, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.029827662395050816, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.028083267871170464, 'bgr': 0.029138513513513514, 'bu': 0.03036576949620428, 'sc': 0.031099324975891997, 'sod': 0.029910714285714284, 'pot': 0.028068137824235385, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027583600982429624, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.029236022193768675, 'pe': 0.029513888888888888, 'ane': 0.0293236301369863}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'dm', 'sc', 'sg', 'bu', 'rc', 'pc', 'sod', 'rbc', 'pe', 'ane', 'appet', 'bgr', 'pcc', 'cad', 'bp', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e371a60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01005815636350061), 'bp': np.float64(0.01676348167177102), 'sg': np.float64(0.24697575555469048), 'al': np.float64(1.0), 'su': np.float64(0.05106619851671104), 'rbc': np.float64(0.09371095376926272), 'pc': np.float64(0.2481920411949564), 'pcc': np.float64(0.0567698241674664), 'ba': np.float64(0.036523243520328035), 'bgr': np.float64(0.08348959475276603), 'bu': np.float64(0.12822013656765224), 'sc': np.float64(0.14247642612635503), 'sod': np.float64(0.12786058049974805), 'pot': np.float64(0.004779033663709402), 'hemo': np.float64(0.3521382903715432), 'pcv': np.float64(0.3547335989744239), 'wc': np.float64(0.02808233655537081), 'rc': np.float64(0.2392608123981195), 'htn': np.float64(0.3857767596834649), 'dm': np.float64(0.19174702848172218), 'cad': np.float64(0.030774214447683804), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.08309037900874629), 'ane': np.float64(0.07348128755875523)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.02904040404040404, 'pe': 0.028958333333333336, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e311970>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01005815636350061), 'bp': np.float64(0.01676348167177102), 'sg': np.float64(0.24697575555469048), 'al': np.float64(1.0), 'su': np.float64(0.05106619851671104), 'rbc': np.float64(0.09371095376926272), 'pc': np.float64(0.2481920411949564), 'pcc': np.float64(0.0567698241674664), 'ba': np.float64(0.036523243520328035), 'bgr': np.float64(0.08348959475276603), 'bu': np.float64(0.12822013656765224), 'sc': np.float64(0.14247642612635503), 'sod': np.float64(0.12786058049974805), 'pot': np.float64(0.004779033663709402), 'hemo': np.float64(0.3521382903715432), 'pcv': np.float64(0.3547335989744239), 'wc': np.float64(0.02808233655537081), 'rc': np.float64(0.2392608123981195), 'htn': np.float64(0.3857767596834649), 'dm': np.float64(0.19174702848172218), 'cad': np.float64(0.030774214447683804), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.08309037900874629), 'ane': np.float64(0.07348128755875523)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.02904040404040404, 'pe': 0.028958333333333336, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'rc', 'bu']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f617ad0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01005815636350061), 'bp': np.float64(0.01676348167177102), 'sg': np.float64(0.24697575555469048), 'al': np.float64(1.0), 'su': np.float64(0.05106619851671104), 'rbc': np.float64(0.09371095376926272), 'pc': np.float64(0.2481920411949564), 'pcc': np.float64(0.0567698241674664), 'ba': np.float64(0.036523243520328035), 'bgr': np.float64(0.08348959475276603), 'bu': np.float64(0.12822013656765224), 'sc': np.float64(0.14247642612635503), 'sod': np.float64(0.12786058049974805), 'pot': np.float64(0.004779033663709402), 'hemo': np.float64(0.3521382903715432), 'pcv': np.float64(0.3547335989744239), 'wc': np.float64(0.02808233655537081), 'rc': np.float64(0.2392608123981195), 'htn': np.float64(0.3857767596834649), 'dm': np.float64(0.19174702848172218), 'cad': np.float64(0.030774214447683804), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.08309037900874629), 'ane': np.float64(0.07348128755875523)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.02904040404040404, 'pe': 0.028958333333333336, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'rc', 'bu', 'rbc', 'sod', 'bgr', 'appet', 'pe']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e310d10>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(7.671930330140657), 'bp': np.float64(12.786464917478838), 'sg': np.float64(188.3825147842483), 'al': np.float64(762.7571150097473), 'su': np.float64(38.95110625512155), 'rbc': np.float64(71.47869674185463), 'pc': np.float64(189.31024531024528), 'pcc': np.float64(43.3015873015873), 'ba': np.float64(27.85836385836386), 'bgr': np.float64(63.68228242695275), 'bu': np.float64(97.80082145449822), 'sc': np.float64(108.67490774903794), 'sod': np.float64(97.52656750545938), 'pot': np.float64(3.6452419298654464), 'hemo': np.float64(268.595986448263), 'pcv': np.float64(270.57557655075624), 'wc': np.float64(21.420002013707403), 'rc': np.float64(182.497886999678), 'htn': np.float64(294.2539682539683), 'dm': np.float64(146.25641025641025), 'cad': np.float64(23.473251028806583), 'appet': np.float64(71.4786967418547), 'pe': np.float64(63.37777777777779), 'ane': np.float64(56.048374905517775)}

Normalized Mathematical Scores
{'age': np.float64(0.01005815636350061), 'bp': np.float64(0.01676348167177102), 'sg': np.float64(0.24697575555469048), 'al': np.float64(1.0), 'su': np.float64(0.05106619851671104), 'rbc': np.float64(0.09371095376926272), 'pc': np.float64(0.2481920411949564), 'pcc': np.float64(0.0567698241674664), 'ba': np.float64(0.036523243520328035), 'bgr': np.float64(0.08348959475276603), 'bu': np.float64(0.12822013656765224), 'sc': np.float64(0.14247642612635503), 'sod': np.float64(0.12786058049974805), 'pot': np.float64(0.004779033663709402), 'hemo': np.float64(0.3521382903715432), 'pcv': np.float64(0.3547335989744239), 'wc': np.float64(0.02808233655537081), 'rc': np.float64(0.2392608123981195), 'htn': np.float64(0.3857767596834649), 'dm': np.float64(0.19174702848172218), 'cad': np.float64(0.030774214447683804), 'appet': np.float64(0.0937109537692628), 'pe': np.float64(0.08309037900874629), 'ane': np.float64(0.07348128755875523)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027673192771084338, 'bp': 0.028068137824235385, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.027972027972027972, 'rbc': 0.029827662395050816, 'pc': 0.030536130536130537, 'pcc': 0.02813852813852814, 'ba': 0.027583600982429624, 'bgr': 0.029138513513513514, 'bu': 0.030158730158730156, 'sc': 0.030886196246139225, 'sod': 0.029709507042253523, 'pot': 0.027777777777777776, 'hemo': 0.03149801587301587, 'pcv': 0.03149801587301587, 'wc': 0.027271052146674038, 'rc': 0.030309988518943745, 'htn': 0.03225806451612903, 'dm': 0.030834914611005692, 'cad': 0.028125, 'appet': 0.02904040404040404, 'pe': 0.028958333333333336, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'rc', 'bu', 'rbc', 'sod', 'bgr', 'appet', 'pe', 'ane', 'pcc', 'cad', 'bp', 'su']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3730b0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}

Normalized Mathematical Scores
{'age': np.float64(0.016991864206822825), 'bp': np.float64(0.024759231558358973), 'sg': np.float64(0.3918883013331342), 'al': np.float64(1.0), 'su': np.float64(0.07529471415895557), 'rbc': np.float64(0.1082361516034986), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.07529471415895556), 'ba': np.float64(0.06614431486880472), 'bgr': np.float64(0.11035689701495596), 'bu': np.float64(0.17035671988944603), 'sc': np.float64(0.18490305565527543), 'sod': np.float64(0.13467825948763948), 'pot': np.float64(0.004719867906432446), 'hemo': np.float64(0.4745620648500175), 'pcv': np.float64(0.4130373904817077), 'wc': np.float64(0.06986662070125173), 'rc': np.float64(0.18341375590811818), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.05772594752186594), 'appet': np.float64(0.0962099125364429), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.06614431486880472)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028665028665028666, 'rbc': 0.030017921146953404, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027912386121341344, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029910714285714284, 'pot': 0.02821869488536155, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.028083267871170464, 'rc': 0.030090497737556562, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 5 Features Selected: ['al', 'hemo', 'htn', 'sc', 'dm']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e304e60>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}

Normalized Mathematical Scores
{'age': np.float64(0.016991864206822825), 'bp': np.float64(0.024759231558358973), 'sg': np.float64(0.3918883013331342), 'al': np.float64(1.0), 'su': np.float64(0.07529471415895557), 'rbc': np.float64(0.1082361516034986), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.07529471415895556), 'ba': np.float64(0.06614431486880472), 'bgr': np.float64(0.11035689701495596), 'bu': np.float64(0.17035671988944603), 'sc': np.float64(0.18490305565527543), 'sod': np.float64(0.13467825948763948), 'pot': np.float64(0.004719867906432446), 'hemo': np.float64(0.4745620648500175), 'pcv': np.float64(0.4130373904817077), 'wc': np.float64(0.06986662070125173), 'rc': np.float64(0.18341375590811818), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.05772594752186594), 'appet': np.float64(0.0962099125364429), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.06614431486880472)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028665028665028666, 'rbc': 0.030017921146953404, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027912386121341344, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029910714285714284, 'pot': 0.02821869488536155, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.028083267871170464, 'rc': 0.030090497737556562, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 10 Features Selected: ['al', 'hemo', 'htn', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e372210>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}

Normalized Mathematical Scores
{'age': np.float64(0.016991864206822825), 'bp': np.float64(0.024759231558358973), 'sg': np.float64(0.3918883013331342), 'al': np.float64(1.0), 'su': np.float64(0.07529471415895557), 'rbc': np.float64(0.1082361516034986), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.07529471415895556), 'ba': np.float64(0.06614431486880472), 'bgr': np.float64(0.11035689701495596), 'bu': np.float64(0.17035671988944603), 'sc': np.float64(0.18490305565527543), 'sod': np.float64(0.13467825948763948), 'pot': np.float64(0.004719867906432446), 'hemo': np.float64(0.4745620648500175), 'pcv': np.float64(0.4130373904817077), 'wc': np.float64(0.06986662070125173), 'rc': np.float64(0.18341375590811818), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.05772594752186594), 'appet': np.float64(0.0962099125364429), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.06614431486880472)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028665028665028666, 'rbc': 0.030017921146953404, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027912386121341344, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029910714285714284, 'pot': 0.02821869488536155, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.028083267871170464, 'rc': 0.030090497737556562, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 15 Features Selected: ['al', 'hemo', 'htn', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'rbc', 'sod', 'bgr', 'pe', 'appet']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e345670>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(10.661641352710186), 'bp': np.float64(15.535319952588388), 'sg': np.float64(245.8925323484525), 'al': np.float64(627.4556589517215), 'su': np.float64(47.24409448818898), 'rbc': np.float64(67.91338582677164), 'pc': np.float64(153.24046032707452), 'pcc': np.float64(47.24409448818897), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(69.24405953638646), 'bu': np.float64(106.8912879350862), 'sc': np.float64(116.01846862836767), 'sod': np.float64(84.50463605328777), 'pot': np.float64(2.9615078273956525), 'hemo': np.float64(297.7666531139573), 'pcv': np.float64(259.1626480163994), 'wc': np.float64(43.83820653083389), 'rc': np.float64(115.08399907413849), 'htn': np.float64(261.5923009623796), 'dm': np.float64(153.24046032707452), 'cad': np.float64(36.22047244094489), 'appet': np.float64(60.36745406824127), 'pe': np.float64(67.91338582677164), 'ane': np.float64(41.50262467191601)}

Normalized Mathematical Scores
{'age': np.float64(0.016991864206822825), 'bp': np.float64(0.024759231558358973), 'sg': np.float64(0.3918883013331342), 'al': np.float64(1.0), 'su': np.float64(0.07529471415895557), 'rbc': np.float64(0.1082361516034986), 'pc': np.float64(0.24422516259250973), 'pcc': np.float64(0.07529471415895556), 'ba': np.float64(0.06614431486880472), 'bgr': np.float64(0.11035689701495596), 'bu': np.float64(0.17035671988944603), 'sc': np.float64(0.18490305565527543), 'sod': np.float64(0.13467825948763948), 'pot': np.float64(0.004719867906432446), 'hemo': np.float64(0.4745620648500175), 'pcv': np.float64(0.4130373904817077), 'wc': np.float64(0.06986662070125173), 'rc': np.float64(0.18341375590811818), 'htn': np.float64(0.41690962099125384), 'dm': np.float64(0.24422516259250973), 'cad': np.float64(0.05772594752186594), 'appet': np.float64(0.0962099125364429), 'pe': np.float64(0.1082361516034986), 'ane': np.float64(0.06614431486880472)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.028125, 'bp': 0.028531243721117136, 'sg': 0.03076923076923077, 'al': 0.03278688524590164, 'su': 0.028665028665028666, 'rbc': 0.030017921146953404, 'pc': 0.030303030303030304, 'pcc': 0.028484848484848488, 'ba': 0.027912386121341344, 'bgr': 0.029709507042253523, 'bu': 0.03036576949620428, 'sc': 0.03131881575727918, 'sod': 0.029910714285714284, 'pot': 0.02821869488536155, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.028083267871170464, 'rc': 0.030090497737556562, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.02844551282051282, 'appet': 0.028850145288501453, 'pe': 0.029513888888888888, 'ane': 0.028612012987012988}
Top 20 Features Selected: ['al', 'hemo', 'htn', 'sc', 'dm', 'pcv', 'sg', 'bu', 'pc', 'rc', 'rbc', 'sod', 'bgr', 'pe', 'appet', 'su', 'ane', 'bp', 'pcc', 'cad']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e3049e0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.011803916590412293), 'bp': np.float64(0.01451254889614622), 'sg': np.float64(0.1633156990169624), 'al': np.float64(1.0), 'su': np.float64(0.04224058769513313), 'rbc': np.float64(0.05068870523415977), 'pc': np.float64(0.21965105601469223), 'pcc': np.float64(0.03484848484848484), 'ba': np.float64(0.03484848484848484), 'bgr': np.float64(0.06477545670503661), 'bu': np.float64(0.0955613249334403), 'sc': np.float64(0.12257014080637094), 'sod': np.float64(0.06617145574790655), 'pot': np.float64(0.0034078183343879123), 'hemo': np.float64(0.2317633251347633), 'pcv': np.float64(0.22262021142870939), 'wc': np.float64(0.014922472921445515), 'rc': np.float64(0.11241800430576719), 'htn': np.float64(0.25661157024793385), 'dm': np.float64(0.12867132867132863), 'cad': np.float64(0.026319135410044495), 'appet': np.float64(0.06402783819051769), 'pe': np.float64(0.08050559066601844), 'ane': np.float64(0.04492862509391432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 5 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f666f6162a0>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.011803916590412293), 'bp': np.float64(0.01451254889614622), 'sg': np.float64(0.1633156990169624), 'al': np.float64(1.0), 'su': np.float64(0.04224058769513313), 'rbc': np.float64(0.05068870523415977), 'pc': np.float64(0.21965105601469223), 'pcc': np.float64(0.03484848484848484), 'ba': np.float64(0.03484848484848484), 'bgr': np.float64(0.06477545670503661), 'bu': np.float64(0.0955613249334403), 'sc': np.float64(0.12257014080637094), 'sod': np.float64(0.06617145574790655), 'pot': np.float64(0.0034078183343879123), 'hemo': np.float64(0.2317633251347633), 'pcv': np.float64(0.22262021142870939), 'wc': np.float64(0.014922472921445515), 'rc': np.float64(0.11241800430576719), 'htn': np.float64(0.25661157024793385), 'dm': np.float64(0.12867132867132863), 'cad': np.float64(0.026319135410044495), 'appet': np.float64(0.06402783819051769), 'pe': np.float64(0.08050559066601844), 'ane': np.float64(0.04492862509391432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 10 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'rc']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665e22e780>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.011803916590412293), 'bp': np.float64(0.01451254889614622), 'sg': np.float64(0.1633156990169624), 'al': np.float64(1.0), 'su': np.float64(0.04224058769513313), 'rbc': np.float64(0.05068870523415977), 'pc': np.float64(0.21965105601469223), 'pcc': np.float64(0.03484848484848484), 'ba': np.float64(0.03484848484848484), 'bgr': np.float64(0.06477545670503661), 'bu': np.float64(0.0955613249334403), 'sc': np.float64(0.12257014080637094), 'sod': np.float64(0.06617145574790655), 'pot': np.float64(0.0034078183343879123), 'hemo': np.float64(0.2317633251347633), 'pcv': np.float64(0.22262021142870939), 'wc': np.float64(0.014922472921445515), 'rc': np.float64(0.11241800430576719), 'htn': np.float64(0.25661157024793385), 'dm': np.float64(0.12867132867132863), 'cad': np.float64(0.026319135410044495), 'appet': np.float64(0.06402783819051769), 'pe': np.float64(0.08050559066601844), 'ane': np.float64(0.04492862509391432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 15 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'ane']

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x7f665c90ca40>
DODA Pipeline Started
Running: SelectKBest
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of scores: 24
Operator Scores:
{'SelectKBest_1': {'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(14.057814049605197), 'bp': np.float64(17.28364583104029), 'sg': np.float64(194.49999587650058), 'al': np.float64(1190.9448818897642), 'su': np.float64(50.30621172353455), 'rbc': np.float64(60.36745406824148), 'pc': np.float64(261.5923009623796), 'pcc': np.float64(41.50262467191601), 'ba': np.float64(41.50262467191601), 'bgr': np.float64(77.14399863493536), 'bu': np.float64(113.80827083608544), 'sc': np.float64(145.9742818658552), 'sod': np.float64(78.80655655016432), 'pot': np.float64(4.058523803749385), 'hemo': np.float64(276.0173458789997), 'pcv': np.float64(265.12840140623865), 'wc': np.float64(17.771842750934134), 'rc': np.float64(133.88364686021492), 'htn': np.float64(305.61023622047253), 'dm': np.float64(153.24046032707452), 'cad': np.float64(31.344639612356154), 'appet': np.float64(76.25362619146303), 'pe': np.float64(95.87772116720704), 'ane': np.float64(53.507516105941285)}

Normalized Mathematical Scores
{'age': np.float64(0.011803916590412293), 'bp': np.float64(0.01451254889614622), 'sg': np.float64(0.1633156990169624), 'al': np.float64(1.0), 'su': np.float64(0.04224058769513313), 'rbc': np.float64(0.05068870523415977), 'pc': np.float64(0.21965105601469223), 'pcc': np.float64(0.03484848484848484), 'ba': np.float64(0.03484848484848484), 'bgr': np.float64(0.06477545670503661), 'bu': np.float64(0.0955613249334403), 'sc': np.float64(0.12257014080637094), 'sod': np.float64(0.06617145574790655), 'pot': np.float64(0.0034078183343879123), 'hemo': np.float64(0.2317633251347633), 'pcv': np.float64(0.22262021142870939), 'wc': np.float64(0.014922472921445515), 'rc': np.float64(0.11241800430576719), 'htn': np.float64(0.25661157024793385), 'dm': np.float64(0.12867132867132863), 'cad': np.float64(0.026319135410044495), 'appet': np.float64(0.06402783819051769), 'pe': np.float64(0.08050559066601844), 'ane': np.float64(0.04492862509391432)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.027820121951219513, 'bp': 0.02821869488536155, 'sg': 0.030536130536130537, 'al': 0.03278688524590164, 'su': 0.02813852813852814, 'rbc': 0.02946236559139785, 'pc': 0.030536130536130537, 'pcc': 0.027972027972027972, 'ba': 0.027745885954841176, 'bgr': 0.0293236301369863, 'bu': 0.030158730158730156, 'sc': 0.031099324975891997, 'sod': 0.029513888888888888, 'pot': 0.02792120864410021, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.027425373134328357, 'rc': 0.029877369007803793, 'htn': 0.03225806451612903, 'dm': 0.031054405392392875, 'cad': 0.028283227848101264, 'appet': 0.028665028665028666, 'pe': 0.029709507042253523, 'ane': 0.028782894736842105}
Top 20 Features Selected: ['al', 'htn', 'hemo', 'pcv', 'sc', 'dm', 'sg', 'pc', 'bu', 'rc', 'pe', 'sod', 'rbc', 'bgr', 'ane', 'appet', 'cad', 'bp', 'su', 'pcc']

SENSITIVITY: completed 25/25 CV runs
======================================================================
SENSITIVITY CV PERFORMANCE SUMMARY
======================================================================

    Top_K Method Model  Acc_Mean  Acc_STD  F1_Mean  F1_STD  AUC_Mean  AUC_STD
0       5  ANOVA    LR    0.9898   0.0151   0.9799  0.0300       1.0      0.0
1       5  ANOVA    RF    0.9874   0.0158   0.9755  0.0307       1.0      0.0
2       5  ANOVA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
3       5   DODA    LR    0.9924   0.0138   0.9849  0.0274       1.0      0.0
4       5   DODA    RF    0.9836   0.0161   0.9682  0.0313       1.0      0.0
5       5   DODA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
6      10  ANOVA    LR    0.9936   0.0130   0.9873  0.0260       1.0      0.0
7      10  ANOVA    RF    0.9949   0.0120   0.9896  0.0243       1.0      0.0
8      10  ANOVA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
9      10   DODA    LR    0.9949   0.0120   0.9896  0.0243       1.0      0.0
10     10   DODA    RF    0.9924   0.0138   0.9853  0.0268       1.0      0.0
11     10   DODA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
12     15  ANOVA    LR    0.9949   0.0119   0.9900  0.0235       1.0      0.0
13     15  ANOVA    RF    0.9988   0.0062   0.9976  0.0118       1.0      0.0
14     15  ANOVA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
15     15   DODA    LR    0.9962   0.0105   0.9926  0.0204       1.0      0.0
16     15   DODA    RF    0.9987   0.0065   0.9973  0.0133       1.0      0.0
17     15   DODA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
18     20  ANOVA    LR    0.9975   0.0088   0.9950  0.0174       1.0      0.0
19     20  ANOVA    RF    0.9962   0.0106   0.9923  0.0213       1.0      0.0
20     20  ANOVA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0
21     20   DODA    LR    0.9949   0.0119   0.9900  0.0235       1.0      0.0
22     20   DODA    RF    0.9987   0.0065   0.9973  0.0133       1.0      0.0
23     20   DODA   XGB    0.9898   0.0151   0.9799  0.0300       1.0      0.0

In [20]:
sensitivity_perf_test = wilcoxon_holm_test(
    sensitivity_cv_results, ["Top_K", "Model"], value_col="ROC_AUC"
)
print("=" * 70)
print("SENSITIVITY — ANOVA vs DODA ROC-AUC: SIGNIFICANCE TEST")
print("=" * 70)
display(sensitivity_perf_test.round(4))

======================================================================
SENSITIVITY — ANOVA vs DODA ROC-AUC: SIGNIFICANCE TEST
======================================================================

    Top_K Model  ANOVA_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0       5    LR         1.0        1.0      1.0      0.00     1.0        False
1       5    RF         1.0        1.0      1.0      0.00     1.0        False
2       5   XGB         1.0        1.0      1.0     -0.28     1.0        False
3      10    LR         1.0        1.0      1.0      0.00     1.0        False
4      10    RF         1.0        1.0      1.0      0.00     1.0        False
5      10   XGB         1.0        1.0      1.0      0.28     1.0        False
6      15    LR         1.0        1.0      1.0      0.00     1.0        False
7      15    RF         1.0        1.0      1.0     -0.28     1.0        False
8      15   XGB         1.0        1.0      1.0      0.00     1.0        False
9      20    LR         1.0        1.0      1.0      0.00     1.0        False
10     20    RF         1.0        1.0      1.0      0.00     1.0        False
11     20   XGB         1.0        1.0      1.0      0.00     1.0        False

# Primary vs. Sensitivity — Head-to-Head Comparison

In [21]:
# =============================================================================
# SIDE-BY-SIDE: STABILITY SUMMARY
# =============================================================================

primary_stability_summary["Analysis"] = "Primary (imputed, n=400)"
sensitivity_stability_summary["Analysis"] = "Sensitivity (complete-case, n=158)"

stability_side_by_side = pd.concat(
    [primary_stability_summary, sensitivity_stability_summary], ignore_index=True
).pivot_table(index=["Top_K", "Method"], columns="Analysis", values="mean").round(4)

print("=" * 70)
print("MEAN JACCARD STABILITY — PRIMARY vs SENSITIVITY")
print("=" * 70)
display(stability_side_by_side)

======================================================================
MEAN JACCARD STABILITY — PRIMARY vs SENSITIVITY
======================================================================

Analysis      Primary (imputed, n=400)  Sensitivity (complete-case, n=158)
Top_K Method
5     ANOVA                     0.8489                              0.7833
      DODA                      0.8600                              0.7637
10    ANOVA                     0.8084                              0.9721
      DODA                      0.7838                              0.9108
15    ANOVA                     0.8968                              0.9280
      DODA                      0.8745                              0.9221
20    ANOVA                     0.9600                              0.9638
      DODA                      0.9613                              0.9848

In [22]:
# =============================================================================
# SIDE-BY-SIDE: PREDICTIVE PERFORMANCE (ROC-AUC) SUMMARY
# =============================================================================

primary_auc = primary_cv_summary[["Top_K", "Method", "Model", "AUC_Mean"]].copy()
primary_auc["Analysis"] = "Primary"
sensitivity_auc = sensitivity_cv_summary[["Top_K", "Method", "Model", "AUC_Mean"]].copy()
sensitivity_auc["Analysis"] = "Sensitivity"

auc_side_by_side = pd.concat([primary_auc, sensitivity_auc], ignore_index=True).pivot_table(
    index=["Top_K", "Method", "Model"], columns="Analysis", values="AUC_Mean"
).round(4)

print("=" * 70)
print("MEAN ROC-AUC — PRIMARY vs SENSITIVITY")
print("=" * 70)
display(auc_side_by_side)

auc_side_by_side.to_csv("../../../results/ckd/primary_vs_sensitivity_auc_comparison.csv")
stability_side_by_side.to_csv("../../../results/ckd/primary_vs_sensitivity_stability_comparison.csv")

======================================================================
MEAN ROC-AUC — PRIMARY vs SENSITIVITY
======================================================================

Analysis            Primary  Sensitivity
Top_K Method Model
5     ANOVA  LR      0.9955          1.0
             RF      0.9990          1.0
             XGB     0.9986          1.0
      DODA   LR      0.9948          1.0
             RF      0.9956          1.0
             XGB     0.9947          1.0
10    ANOVA  LR      0.9999          1.0
             RF      0.9996          1.0
             XGB     0.9983          1.0
      DODA   LR      0.9999          1.0
             RF      0.9994          1.0
             XGB     0.9980          1.0
15    ANOVA  LR      0.9999          1.0
             RF      0.9997          1.0
             XGB     0.9980          1.0
      DODA   LR      0.9999          1.0
             RF      0.9999          1.0
             XGB     0.9989          1.0
20    ANOVA  LR      1.0000          1.0
             RF      0.9999          1.0
             XGB     0.9990          1.0
      DODA   LR      1.0000          1.0
             RF      0.9999          1.0
             XGB     0.9988          1.0