# CKD — LASSO + Rank Fusion: Primary Analysis vs. Sensitivity Analysis

This notebook runs the **same pipeline twice** on the same underlying CKD data, so the two runs can be compared directly:

- **Primary Analysis**: the full 400-row dataset, with missing values handled by median (numerical) / mode (categorical) imputation, fit on training data only within each fold.
- **Sensitivity Analysis**: only the 158 complete-case rows (zero missing values anywhere), no imputation needed at all.

**Why this comparison matters, concretely**: dropping every row with a missing value would cost 60.5% of the dataset and visibly shifts the class balance (62.5%/37.5% CKD in the full data vs. 27.2%/72.8% in the complete cases) — a strong sign the missingness isn't random. If the Primary and Sensitivity results agree, that's real evidence the imputation approach isn't distorting the conclusions. If they disagree, that's equally real evidence — and tells you exactly where to be cautious.

**What differs from `ckd_anova.ipynb`**: the mathematical operator is **LASSO** (L1-penalized Logistic Regression, absolute coefficient magnitude as the importance score) instead of ANOVA's F-statistic. `SklearnAdapter` has an explicit branch for this (`elif hasattr(self.estimator, "coef_"): values = np.abs(self.estimator.coef_)`, labelled "Linear models / LASSO" in the package source), so no adapter changes are needed — only swapping which estimator gets wrapped. Everything else — the Primary/Sensitivity split, the imputation logic, the 25-run repeated-CV stability and performance analyses, and the Wilcoxon + Holm + Cohen's d significance testing — is identical, so the two notebooks are directly comparable.

**Fusion**: `doda.fusion.RankFusion` — genuine Reciprocal Rank Fusion, `RRF(f) = 1/(k + math_rank(f)) + 1/(k + clinical_rank(f))` (Cormack, Clarke & Buettcher, 2009).

**Imbalance handling**: `class_weight="balanced"` / `scale_pos_weight` throughout, since CKD is ~63/37.

In [1]:
# =============================================================================
# STEP 1: LOAD AND CLEAN RAW DATA (shared by both analyses)
# =============================================================================

import pandas as pd
import numpy as np

df = pd.read_csv("../../data/raw/ckd.csv")
df = df.drop(columns=["id"])

# Known data-quality issues in this exact UCI file (see 01_ckd_eda.ipynb)
categorical_cols_raw = df.select_dtypes(include="object").columns
for col in categorical_cols_raw:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan, "?": np.nan})

for col in ["pcv", "wc", "rc"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Encode categorical features and target
target_column = "target"

binary_maps = {
    "rbc":   {"normal": 0, "abnormal": 1},
    "pc":    {"normal": 0, "abnormal": 1},
    "pcc":   {"notpresent": 0, "present": 1},
    "ba":    {"notpresent": 0, "present": 1},
    "htn":   {"no": 0, "yes": 1},
    "dm":    {"no": 0, "yes": 1},
    "cad":   {"no": 0, "yes": 1},
    "appet": {"poor": 0, "good": 1},
    "pe":    {"no": 0, "yes": 1},
    "ane":   {"no": 0, "yes": 1},
}
for col, mapping in binary_maps.items():
    df[col] = df[col].map(mapping)

df[target_column] = df["classification"].map({"ckd": 1, "notckd": 0})
df = df.drop(columns=["classification"])

numerical_features = ["age", "bp", "sg", "al", "su", "bgr", "bu", "sc",
                       "sod", "pot", "hemo", "pcv", "wc", "rc"]
categorical_features = ["rbc", "pc", "pcc", "ba", "htn", "dm", "cad",
                         "appet", "pe", "ane"]

print("=" * 70)
print("CLEANED + ENCODED DATASET")
print("=" * 70)
print(f"Shape: {df.shape}")
display(df.head())

======================================================================
CLEANED + ENCODED DATASET
======================================================================
Shape: (400, 25)

C:\Users\johnm\AppData\Local\Temp\ipykernel_5852\1346706842.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols_raw = df.select_dtypes(include="object").columns

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,target
0,48.0,80.0,1.020,1.0,0.0,NaN,0.0,0.0,0.0,121.0,...,44.0,7800.0,5.2,1.0,1.0,0.0,1.0,0.0,0.0,1
1,7.0,50.0,1.020,4.0,0.0,NaN,0.0,0.0,0.0,NaN,...,38.0,6000.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1
2,62.0,80.0,1.010,2.0,3.0,0.0,0.0,0.0,0.0,423.0,...,31.0,7500.0,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1
3,48.0,70.0,1.005,4.0,0.0,0.0,1.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1.0,0.0,0.0,0.0,1.0,1.0,1
4,51.0,80.0,1.010,2.0,0.0,0.0,0.0,0.0,0.0,106.0,...,35.0,7300.0,4.6,0.0,0.0,0.0,1.0,0.0,0.0,1

In [2]:
# =============================================================================
# STEP 2: DEFINE THE TWO DATASETS — PRIMARY (imputed) vs SENSITIVITY (complete-case)
# =============================================================================

# --- Primary: full dataset, missing values handled by imputation later ---
X_primary = df.drop(columns=[target_column])
y_primary = df[target_column]

# --- Sensitivity: complete cases only, no imputation needed ---
df_complete = df.dropna()
X_sensitivity = df_complete.drop(columns=[target_column])
y_sensitivity = df_complete[target_column]

print("=" * 70)
print("PRIMARY vs SENSITIVITY DATASET SIZES")
print("=" * 70)
print(f"Primary (full, to be imputed) : {X_primary.shape[0]} rows")
print(f"Sensitivity (complete-case)    : {X_sensitivity.shape[0]} rows "
      f"({X_sensitivity.shape[0]/X_primary.shape[0]*100:.1f}% of primary)")

print("\nClass balance comparison:")
print("Primary:")
display((y_primary.value_counts(normalize=True) * 100).round(2))
print("Sensitivity:")
display((y_sensitivity.value_counts(normalize=True) * 100).round(2))

======================================================================
PRIMARY vs SENSITIVITY DATASET SIZES
======================================================================
Primary (full, to be imputed) : 400 rows
Sensitivity (complete-case)    : 158 rows (39.5% of primary)

Class balance comparison:
Primary:

target
1    62.5
0    37.5
Name: proportion, dtype: float64

Sensitivity:

target
0    72.78
1    27.22
Name: proportion, dtype: float64

In [3]:
#%pip uninstall -y doda

In [4]:
#%pip install --no-cache-dir git+https://github.com/anandha-3679/DODA.git

In [5]:
import doda

print(doda.__file__)

from doda.knowledge import JSONProvider
from doda.fusion import RankFusion

print("JSONProvider:", JSONProvider)
print("RankFusion:", RankFusion)

c:\Users\johnm\msc_research\.venv\Lib\site-packages\doda\__init__.py
JSONProvider: <class 'doda.knowledge.providers.json_provider.JSONProvider'>
RankFusion: <class 'doda.fusion.rank.RankFusion'>

In [6]:
# =============================================================================
# DODA IMPORTS
# =============================================================================

from sklearn.feature_selection import (
    SelectKBest,
    f_classif
)

from doda import DODASelector

from doda.adapters import (
    SklearnAdapter
)

from doda.knowledge.providers import (
    JSONProvider
)

from doda.fusion import (
    RankFusion
)

In [7]:
# =============================================================================
# STEP 3: SHARED HELPER FUNCTIONS
# Defined once, called twice (Primary and Sensitivity) — avoids duplicating
# ~150 lines of loop logic twice with only the input data differing.
# =============================================================================

from sklearn.model_selection import RepeatedStratifiedKFold, train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
)
from scipy.stats import wilcoxon
from statsmodels.stats.multitest import multipletests

from doda import DODASelector
from doda.adapters.sklearn_adapter import SklearnAdapter
from doda.knowledge import JSONProvider
from doda.fusion import RankFusion

WEIGHTS_FILE = "../../../config/clinical_weights/ckd_clinical_weights.json"


def make_models(y_train):
    """Fresh model instances, class-imbalance-aware (CKD is ~63/37)."""
    return {
        "LR": LogisticRegression(max_iter=2000, class_weight="balanced", random_state=42),
        "RF": RandomForestClassifier(n_estimators=300, class_weight="balanced",
                                      random_state=42, n_jobs=-1),
        "XGB": XGBClassifier(n_estimators=300, max_depth=3, learning_rate=0.05,
                              subsample=0.8, colsample_bytree=0.8, eval_metric="logloss",
                              scale_pos_weight=(y_train == 0).sum() / max((y_train == 1).sum(), 1),
                              random_state=42, n_jobs=-1)
    }


def impute_if_needed(X_train, X_test, do_impute):
    """Median/mode imputation fit on TRAIN only — skipped entirely for the
    complete-case (Sensitivity) dataset, since it has no missing values."""
    if not do_impute:
        return X_train.copy(), X_test.copy()

    num_cols = [c for c in numerical_features if c in X_train.columns]
    cat_cols = [c for c in categorical_features if c in X_train.columns]

    num_imp = SimpleImputer(strategy="median")
    cat_imp = SimpleImputer(strategy="most_frequent")

    X_train_i, X_test_i = X_train.copy(), X_test.copy()
    X_train_i[num_cols] = num_imp.fit_transform(X_train[num_cols])
    X_test_i[num_cols] = num_imp.transform(X_test[num_cols])
    X_train_i[cat_cols] = cat_imp.fit_transform(X_train[cat_cols])
    X_test_i[cat_cols] = cat_imp.transform(X_test[cat_cols])

    return X_train_i, X_test_i


def run_stability_analysis(X, y, k_values, do_impute, label):
    """25-run (5x5) repeated stratified CV. For each K, runs BOTH LASSO and
    DODA, records selected feature sets, computes pairwise Jaccard similarity."""

    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=42)
    all_jaccard = []

    for k in k_values:
        print(f"\n{'='*70}\n{label} STABILITY — TOP-{k}\n{'='*70}")

        for method in ["LASSO", "DODA"]:
            selected_sets = []

            for train_idx, _ in cv.split(X, y):
                X_train = X.iloc[train_idx]
                y_train = y.iloc[train_idx]
                X_train_imp, _ = impute_if_needed(X_train, X_train, do_impute)

                if method == "LASSO":
                    lasso = LogisticRegression(
                        penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
                        class_weight="balanced", random_state=42
                    )
                    lasso.fit(X_train_imp, y_train)
                    coefs = pd.Series(np.abs(lasso.coef_[0]), index=X_train_imp.columns)
                    features = coefs.sort_values(ascending=False).head(k).index.tolist()
                else:
                    operator = SklearnAdapter(
                        LogisticRegression(
                            penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
                            class_weight="balanced", random_state=42
                        )
                    )
                    provider = JSONProvider(WEIGHTS_FILE)
                    selector = DODASelector(operators=[operator], provider=provider,
                                             fusion=RankFusion(), top_k=k)
                    selector.fit(X_train_imp, y_train)
                    features = list(selector.get_selected_features())

                selected_sets.append(set(features))

            jaccard_scores = []
            for i in range(len(selected_sets)):
                for j in range(i + 1, len(selected_sets)):
                    inter = len(selected_sets[i] & selected_sets[j])
                    union = len(selected_sets[i] | selected_sets[j])
                    jaccard_scores.append(inter / union)

            for score in jaccard_scores:
                all_jaccard.append({"Top_K": k, "Method": method, "Jaccard": score})

            print(f"{method}: mean Jaccard = {np.mean(jaccard_scores):.4f} "
                  f"(std {np.std(jaccard_scores):.4f})")

    return pd.DataFrame(all_jaccard)


def run_cv_performance(X, y, k_values, do_impute, label):
    """25-run (5x5) repeated stratified CV predictive performance,
    LASSO vs DODA, across 3 models and all Top-K values."""

    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=42)
    results = []

    for run_id, (train_idx, test_idx) in enumerate(cv.split(X, y), start=1):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
        X_train_imp, X_test_imp = impute_if_needed(X_train, X_test, do_impute)

        for k in k_values:
            for method in ["LASSO", "DODA"]:
                if method == "LASSO":
                    lasso = LogisticRegression(
                        penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
                        class_weight="balanced", random_state=42
                    )
                    lasso.fit(X_train_imp, y_train)
                    coefs = pd.Series(np.abs(lasso.coef_[0]), index=X_train_imp.columns)
                    sel_features = coefs.sort_values(ascending=False).head(k).index.tolist()
                    X_train_sel = X_train_imp[sel_features]
                    X_test_sel = X_test_imp[sel_features]
                else:
                    operator = SklearnAdapter(
                        LogisticRegression(
                            penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
                            class_weight="balanced", random_state=42
                        )
                    )
                    provider = JSONProvider(WEIGHTS_FILE)
                    selector = DODASelector(operators=[operator], provider=provider,
                                             fusion=RankFusion(), top_k=k)
                    X_train_sel = selector.fit_transform(X_train_imp, y_train)
                    X_test_sel = selector.transform(X_test_imp)

                models = make_models(y_train)
                for model_name, model in models.items():
                    if model_name == "LR":
                        scaler = StandardScaler()
                        Xtr = scaler.fit_transform(X_train_sel)
                        Xts = scaler.transform(X_test_sel)
                    else:
                        Xtr, Xts = X_train_sel, X_test_sel

                    model.fit(Xtr, y_train)
                    y_pred = model.predict(Xts)
                    y_prob = model.predict_proba(Xts)[:, 1]

                    results.append({
                        "Run": run_id, "Top_K": k, "Method": method, "Model": model_name,
                        "Accuracy": accuracy_score(y_test, y_pred),
                        "F1": f1_score(y_test, y_pred, zero_division=0),
                        "ROC_AUC": roc_auc_score(y_test, y_prob)
                    })

        if run_id % 5 == 0:
            print(f"{label}: completed {run_id}/25 CV runs")

    return pd.DataFrame(results)


def wilcoxon_holm_test(df, group_cols, value_col="Jaccard"):
    """Paired Wilcoxon signed-rank test (LASSO vs DODA) + Cohen's d,
    with Holm correction across all comparisons in this dataframe."""
    rows = []
    for keys, group in df.groupby(group_cols):
        lasso_vals = group[group.Method == "LASSO"].sort_values(value_col)[value_col].values \
            if "Run" not in group.columns else \
            group[group.Method == "LASSO"].sort_values("Run")[value_col].values
        doda_vals = group[group.Method == "DODA"].sort_values(value_col)[value_col].values \
            if "Run" not in group.columns else \
            group[group.Method == "DODA"].sort_values("Run")[value_col].values

        n = min(len(lasso_vals), len(doda_vals))
        lasso_vals, doda_vals = lasso_vals[:n], doda_vals[:n]

        if np.allclose(lasso_vals, doda_vals):
            stat, p = np.nan, 1.0
        else:
            try:
                stat, p = wilcoxon(lasso_vals, doda_vals)
            except ValueError:
                stat, p = np.nan, 1.0

        diff = doda_vals - lasso_vals
        pooled_std = np.std(np.concatenate([lasso_vals, doda_vals]), ddof=1)
        cohens_d = diff.mean() / pooled_std if pooled_std > 0 else 0.0

        rows.append({
            **(dict(zip(group_cols, keys)) if isinstance(keys, tuple) else {group_cols[0]: keys}),
            "LASSO_mean": lasso_vals.mean(),
            "DODA_mean": doda_vals.mean(),
            "p_value": p,
            "cohens_d": cohens_d
        })

    result_df = pd.DataFrame(rows)
    if len(result_df) > 0:
        reject, p_adj, _, _ = multipletests(result_df["p_value"].fillna(1.0), method="holm")
        result_df["p_holm"] = p_adj
        result_df["significant"] = reject
    return result_df


print("Helper functions defined.")

Helper functions defined.

# PRIMARY ANALYSIS (Imputed, n=400)

## 1. Baseline (80/20 split, for direct comparison with earlier notebooks)

In [8]:
# =============================================================================
# PRIMARY: TRAIN-TEST SPLIT, IMPUTATION, SCALING
# =============================================================================

X_train, X_test, y_train, y_test = train_test_split(
    X_primary, y_primary, test_size=0.2, random_state=42, stratify=y_primary
)

X_train_imp, X_test_imp = impute_if_needed(X_train, X_test, do_impute=True)

scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train_imp), columns=X_train_imp.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test_imp), columns=X_test_imp.columns)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

print("PRIMARY split:", X_train_scaled.shape, X_test_scaled.shape)
print("Missing after imputation:", X_train_scaled.isnull().sum().sum(),
      X_test_scaled.isnull().sum().sum())

PRIMARY split: (320, 24) (80, 24)
Missing after imputation: 0 0

In [9]:
# =============================================================================
# PRIMARY: LASSO BASELINE TOP-K
# =============================================================================

k_values = [5, 10, 15, 20]

lasso_selector = LogisticRegression(
    penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
    class_weight="balanced", random_state=42
)
lasso_selector.fit(X_train_scaled, y_train)

lasso_scores = pd.DataFrame({
    "Feature": X_train_scaled.columns,
    "LASSO Coefficient": lasso_selector.coef_[0],
    "LASSO Score": np.abs(lasso_selector.coef_[0])
}).sort_values("LASSO Score", ascending=False).reset_index(drop=True)

display(lasso_scores)

lasso_results = {}
for k in k_values:
    top_features = lasso_scores.head(k)["Feature"].tolist()
    mask = X_train_scaled.columns.isin(top_features)
    lasso_results[k] = {
        "features": top_features,
        "X_train": X_train_scaled.loc[:, mask],
        "X_test": X_test_scaled.loc[:, mask]
    }
    print(f"Top-{k}:", top_features)

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

   Feature  LASSO Coefficient  LASSO Score
0     hemo          -1.423788     1.423788
1       sg          -1.016467     1.016467
2      htn           0.427144     0.427144
3       dm           0.398986     0.398986
4      pcv          -0.255307     0.255307
5       al           0.251402     0.251402
6       rc          -0.145765     0.145765
7    appet          -0.107240     0.107240
8      pcc           0.000000     0.000000
9       pc           0.000000     0.000000
10     rbc           0.000000     0.000000
11      su           0.000000     0.000000
12     age           0.000000     0.000000
13      bp           0.000000     0.000000
14      ba           0.000000     0.000000
15     bgr           0.000000     0.000000
16     sod           0.000000     0.000000
17     pot           0.000000     0.000000
18      bu           0.000000     0.000000
19      sc           0.000000     0.000000
20      wc           0.000000     0.000000
21     cad           0.000000     0.000000
22      pe           0.000000     0.000000
23     ane           0.000000     0.000000

Top-5: ['hemo', 'sg', 'htn', 'dm', 'pcv']
Top-10: ['hemo', 'sg', 'htn', 'dm', 'pcv', 'al', 'rc', 'appet', 'pcc', 'pc']
Top-15: ['hemo', 'sg', 'htn', 'dm', 'pcv', 'al', 'rc', 'appet', 'pcc', 'pc', 'rbc', 'su', 'age', 'bp', 'ba']
Top-20: ['hemo', 'sg', 'htn', 'dm', 'pcv', 'al', 'rc', 'appet', 'pcc', 'pc', 'rbc', 'su', 'age', 'bp', 'ba', 'bgr', 'sod', 'pot', 'bu', 'sc']

In [10]:
# =============================================================================
# PRIMARY: LASSO BASELINE MODEL EVALUATION
# =============================================================================

primary_baseline_results = []
for k in k_values:
    Xtr, Xts = lasso_results[k]["X_train"], lasso_results[k]["X_test"]
    models = make_models(y_train)
    for model_name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        primary_baseline_results.append({
            "Method": "LASSO", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "F1 Score": f1_score(y_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(y_test, y_prob)
        })

primary_baseline_df = pd.DataFrame(primary_baseline_results)
display(primary_baseline_df)

   Method  Top-K Model  Accuracy  F1 Score   ROC-AUC
0   LASSO      5    LR    0.9500  0.958333  0.992667
1   LASSO      5    RF    0.9750  0.979592  0.999333
2   LASSO      5   XGB    0.9875  0.990099  0.998000
3   LASSO     10    LR    0.9750  0.979592  0.999667
4   LASSO     10    RF    0.9875  0.989899  0.999667
5   LASSO     10   XGB    0.9875  0.990099  0.999667
6   LASSO     15    LR    0.9750  0.979592  0.998667
7   LASSO     15    RF    0.9875  0.989899  1.000000
8   LASSO     15   XGB    0.9875  0.990099  1.000000
9   LASSO     20    LR    0.9750  0.979592  1.000000
10  LASSO     20    RF    1.0000  1.000000  1.000000
11  LASSO     20   XGB    1.0000  1.000000  1.000000

In [11]:
# =============================================================================
# PRIMARY: RANK FUSION DODA
# =============================================================================

provider = JSONProvider(WEIGHTS_FILE)
fusion = RankFusion()

primary_doda_results_by_k = {}
for k in k_values:
    operator = SklearnAdapter(
        LogisticRegression(
            penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
            class_weight="balanced", random_state=42
        )
    )
    selector = DODASelector(operators=[operator], provider=provider, fusion=fusion, top_k=k)
    X_train_sel = selector.fit_transform(X_train_scaled, y_train)
    X_test_sel = selector.transform(X_test_scaled)
    features = selector.get_selected_features()
    primary_doda_results_by_k[k] = {"X_train": X_train_sel, "X_test": X_test_sel,
                                     "features": features, "selector": selector}
    print(f"Top-{k}:", features)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.7139171813517396), 'al': np.float64(0.17657296234976505), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.1793153325480432), 'wc': np.float64(0.0), 'rc': np.float64(0.10237796222138641), 'htn': np.float64(0.3000049599951287), 'dm': np.float64(0.28022846793235867), 'cad': np.float64(0.0), 'appet': np.float64(0.07532018458724313), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03036576949620428, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02964426877470356, 'rbc': 0.030621785881252923, 'pc': 0.02964426877470356, 'pcc': 0.02964426877470356, 'ba': 0.029418126757516764, 'bgr': 0.030117753623188408, 'bu': 0.03036576949620428, 'sc': 0.030886196246139225, 'sod': 0.030117753623188408, 'pot': 0.03036576949620428, 'hemo': 0.032266458495966696, 'pcv': 0.031009615384615385, 'wc': 0.029418126757516764, 'rc': 0.030309988518943745, 'htn': 0.03200204813108039, 'dm': 0.031754032258064516, 'cad': 0.030117753623188408, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.030117753623188408}
Top 5 Features Selected: ['hemo', 'htn', 'dm', 'al', 'sg']
Top-5: ['hemo', 'htn', 'dm', 'al', 'sg']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.7139171813517396), 'al': np.float64(0.17657296234976505), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.1793153325480432), 'wc': np.float64(0.0), 'rc': np.float64(0.10237796222138641), 'htn': np.float64(0.3000049599951287), 'dm': np.float64(0.28022846793235867), 'cad': np.float64(0.0), 'appet': np.float64(0.07532018458724313), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03036576949620428, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02964426877470356, 'rbc': 0.030621785881252923, 'pc': 0.02964426877470356, 'pcc': 0.02964426877470356, 'ba': 0.029418126757516764, 'bgr': 0.030117753623188408, 'bu': 0.03036576949620428, 'sc': 0.030886196246139225, 'sod': 0.030117753623188408, 'pot': 0.03036576949620428, 'hemo': 0.032266458495966696, 'pcv': 0.031009615384615385, 'wc': 0.029418126757516764, 'rc': 0.030309988518943745, 'htn': 0.03200204813108039, 'dm': 0.031754032258064516, 'cad': 0.030117753623188408, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.030117753623188408}
Top 10 Features Selected: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu']
Top-10: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.7139171813517396), 'al': np.float64(0.17657296234976505), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.1793153325480432), 'wc': np.float64(0.0), 'rc': np.float64(0.10237796222138641), 'htn': np.float64(0.3000049599951287), 'dm': np.float64(0.28022846793235867), 'cad': np.float64(0.0), 'appet': np.float64(0.07532018458724313), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03036576949620428, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02964426877470356, 'rbc': 0.030621785881252923, 'pc': 0.02964426877470356, 'pcc': 0.02964426877470356, 'ba': 0.029418126757516764, 'bgr': 0.030117753623188408, 'bu': 0.03036576949620428, 'sc': 0.030886196246139225, 'sod': 0.030117753623188408, 'pot': 0.03036576949620428, 'hemo': 0.032266458495966696, 'pcv': 0.031009615384615385, 'wc': 0.029418126757516764, 'rc': 0.030309988518943745, 'htn': 0.03200204813108039, 'dm': 0.031754032258064516, 'cad': 0.030117753623188408, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.030117753623188408}
Top 15 Features Selected: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu', 'pot', 'rc', 'age', 'bgr', 'sod']
Top-15: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu', 'pot', 'rc', 'age', 'bgr', 'sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(1.0164668375534045), 'al': np.float64(0.25140249503068596), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.4237881705393525), 'pcv': np.float64(0.255307049278234), 'wc': np.float64(0.0), 'rc': np.float64(0.1457645315347347), 'htn': np.float64(0.4271435131441959), 'dm': np.float64(0.39898597769045857), 'cad': np.float64(0.0), 'appet': np.float64(0.10723998781815723), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.7139171813517396), 'al': np.float64(0.17657296234976505), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.1793153325480432), 'wc': np.float64(0.0), 'rc': np.float64(0.10237796222138641), 'htn': np.float64(0.3000049599951287), 'dm': np.float64(0.28022846793235867), 'cad': np.float64(0.0), 'appet': np.float64(0.07532018458724313), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03036576949620428, 'sg': 0.0315136476426799, 'al': 0.031544957774465976, 'su': 0.02964426877470356, 'rbc': 0.030621785881252923, 'pc': 0.02964426877470356, 'pcc': 0.02964426877470356, 'ba': 0.029418126757516764, 'bgr': 0.030117753623188408, 'bu': 0.03036576949620428, 'sc': 0.030886196246139225, 'sod': 0.030117753623188408, 'pot': 0.03036576949620428, 'hemo': 0.032266458495966696, 'pcv': 0.031009615384615385, 'wc': 0.029418126757516764, 'rc': 0.030309988518943745, 'htn': 0.03200204813108039, 'dm': 0.031754032258064516, 'cad': 0.030117753623188408, 'appet': 0.029857397504456328, 'pe': 0.030117753623188408, 'ane': 0.030117753623188408}
Top 20 Features Selected: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu', 'pot', 'rc', 'age', 'bgr', 'sod', 'cad', 'pe', 'ane', 'appet', 'su']
Top-20: ['hemo', 'htn', 'dm', 'al', 'sg', 'pcv', 'sc', 'rbc', 'bp', 'bu', 'pot', 'rc', 'age', 'bgr', 'sod', 'cad', 'pe', 'ane', 'appet', 'su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

In [12]:
# =============================================================================
# PRIMARY: DODA MODEL EVALUATION + COMBINED BASELINE COMPARISON
# =============================================================================

primary_doda_results = []
for k in k_values:
    Xtr, Xts = primary_doda_results_by_k[k]["X_train"], primary_doda_results_by_k[k]["X_test"]
    models = make_models(y_train)
    for model_name, model in models.items():
        model.fit(Xtr, y_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        primary_doda_results.append({
            "Method": "LASSO + Rank Fusion", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "F1 Score": f1_score(y_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(y_test, y_prob)
        })

primary_doda_df = pd.DataFrame(primary_doda_results)
primary_comparison_df = pd.concat([primary_baseline_df, primary_doda_df], ignore_index=True)
display(primary_comparison_df)

import os
os.makedirs("../../../results/ckd/primary", exist_ok=True)
primary_comparison_df.to_csv("../../../results/ckd/primary/lasso_rankfusion_80_20_comparison.csv", index=False)

                 Method  Top-K Model  Accuracy  F1 Score   ROC-AUC
0                 LASSO      5    LR    0.9500  0.958333  0.992667
1                 LASSO      5    RF    0.9750  0.979592  0.999333
2                 LASSO      5   XGB    0.9875  0.990099  0.998000
3                 LASSO     10    LR    0.9750  0.979592  0.999667
4                 LASSO     10    RF    0.9875  0.989899  0.999667
5                 LASSO     10   XGB    0.9875  0.990099  0.999667
6                 LASSO     15    LR    0.9750  0.979592  0.998667
7                 LASSO     15    RF    0.9875  0.989899  1.000000
8                 LASSO     15   XGB    0.9875  0.990099  1.000000
9                 LASSO     20    LR    0.9750  0.979592  1.000000
10                LASSO     20    RF    1.0000  1.000000  1.000000
11                LASSO     20   XGB    1.0000  1.000000  1.000000
12  LASSO + Rank Fusion      5    LR    0.9875  0.989899  0.999667
13  LASSO + Rank Fusion      5    RF    0.9875  0.989899  0.999667
14  LASSO + Rank Fusion      5   XGB    0.9875  0.990099  0.999667
15  LASSO + Rank Fusion     10    LR    0.9750  0.979592  0.998667
16  LASSO + Rank Fusion     10    RF    1.0000  1.000000  1.000000
17  LASSO + Rank Fusion     10   XGB    0.9875  0.990099  1.000000
18  LASSO + Rank Fusion     15    LR    0.9750  0.979592  1.000000
19  LASSO + Rank Fusion     15    RF    1.0000  1.000000  1.000000
20  LASSO + Rank Fusion     15   XGB    1.0000  1.000000  1.000000
21  LASSO + Rank Fusion     20    LR    0.9750  0.979592  1.000000
22  LASSO + Rank Fusion     20    RF    1.0000  1.000000  1.000000
23  LASSO + Rank Fusion     20   XGB    1.0000  1.000000  1.000000

## 2. Feature-Selection Stability (25-run repeated CV)

In [13]:
# =============================================================================
# PRIMARY: STABILITY ANALYSIS
# =============================================================================

primary_jaccard_df = run_stability_analysis(
    X_primary, y_primary, k_values, do_impute=True, label="PRIMARY"
)

primary_stability_summary = primary_jaccard_df.groupby(["Top_K", "Method"])["Jaccard"].agg(
    ["mean", "std"]
).reset_index()
print("\n" + "=" * 70)
print("PRIMARY STABILITY SUMMARY")
print("=" * 70)
display(primary_stability_summary)

======================================================================
PRIMARY STABILITY — TOP-5
======================================================================

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B5BD90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B5AE90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B92780>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B92520>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C3F770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CCDD00>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B6B890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000240FA9F4320>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BD33F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BD27B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094B4EA90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07026889626309528), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04226759967793602), 'bu': np.float64(0.03911786098283301), 'sc': np.float64(0.2161687986218055), 'sod': np.float64(0.03290790840197277), 'pot': np.float64(0.0), 'hemo': np.float64(0.7081037735878919), 'pcv': np.float64(0.23378190899319135), 'wc': np.float64(0.00022941631770969145), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032018442622950824, 'sod': 0.030330882352941176, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C931D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C1AF10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000240E3A2D3B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BB3C50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BFD250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099CDE8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099CDD5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 0.9394 (std 0.0857)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3830>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3D10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA25D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1C10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1670>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA0AD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA0C50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3DD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3B90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA2990>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1C70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA23F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA36B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1A90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA2870>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3830>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA2ED0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009041941120717354), 'bp': np.float64(0.0698678956980507), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05346706919135869), 'bu': np.float64(0.02665018224373051), 'sc': np.float64(0.4332862994312083), 'sod': np.float64(0.045648674746017824), 'pot': np.float64(0.0), 'hemo': np.float64(0.7979879465987304), 'pcv': np.float64(0.2384509915308636), 'wc': np.float64(0.00010240846833461283), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBE5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005711873891163141), 'bp': np.float64(0.0938023539231203), 'sg': np.float64(0.0), 'al': np.float64(0.4858104597266678), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05389205106659081), 'bu': np.float64(0.02354631921428538), 'sc': np.float64(1.0), 'sod': np.float64(0.03914508757576098), 'pot': np.float64(0.0), 'hemo': np.float64(0.8441202679754073), 'pcv': np.float64(0.25509793302802586), 'wc': np.float64(8.610062700555763e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.032266458495966696, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03278688524590164, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']
DODA: mean Jaccard = 0.9855 (std 0.0493)

======================================================================
PRIMARY STABILITY — TOP-15
======================================================================

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA450>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBC6B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9790>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB8C50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBFB90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBABD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3B30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB83B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9C10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBBDD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA36B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAA50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9610>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA2ED0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA24B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3BF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA2E70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA3F50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA0A70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA33B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CA1910>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA810>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9A30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB470>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB85F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB410>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAF30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

   Top_K Method      mean       std
0      5   DODA  1.000000  0.000000
1      5  LASSO  1.000000  0.000000
2     10   DODA  0.985455  0.049408
3     10  LASSO  0.939394  0.085853
4     15   DODA  1.000000  0.000000
5     15  LASSO  1.000000  0.000000
6     20   DODA  1.000000  0.000000
7     20  LASSO  1.000000  0.000000

In [14]:
# =============================================================================
# PRIMARY: STABILITY SIGNIFICANCE TESTING (Wilcoxon + Holm + Cohen's d)
# =============================================================================

primary_stability_test = wilcoxon_holm_test(primary_jaccard_df, ["Top_K"], value_col="Jaccard")
print("=" * 70)
print("PRIMARY — LASSO vs DODA STABILITY: SIGNIFICANCE TEST")
print("=" * 70)
display(primary_stability_test.round(4))

======================================================================
PRIMARY — LASSO vs DODA STABILITY: SIGNIFICANCE TEST
======================================================================

   Top_K  LASSO_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0      5      1.0000     1.0000      1.0    0.0000     1.0        False
1     10      0.9394     0.9855      0.0    0.6251     0.0         True
2     15      1.0000     1.0000      1.0    0.0000     1.0        False
3     20      1.0000     1.0000      1.0    0.0000     1.0        False

## 3. Predictive Performance (25-run repeated CV)

In [15]:
# =============================================================================
# PRIMARY: CV PREDICTIVE PERFORMANCE
# =============================================================================

primary_cv_results = run_cv_performance(
    X_primary, y_primary, k_values, do_impute=True, label="PRIMARY"
)

primary_cv_summary = primary_cv_results.groupby(["Top_K", "Method", "Model"]).agg(
    {"Accuracy": ["mean", "std"], "F1": ["mean", "std"], "ROC_AUC": ["mean", "std"]}
).reset_index()
primary_cv_summary.columns = ["Top_K", "Method", "Model", "Acc_Mean", "Acc_STD",
                               "F1_Mean", "F1_STD", "AUC_Mean", "AUC_STD"]

os.makedirs("../../../results/ckd/primary", exist_ok=True)
primary_cv_results.to_csv("../../../results/ckd/primary/cv_performance_runs.csv", index=False)
primary_cv_summary.to_csv("../../../results/ckd/primary/cv_performance_summary.csv", index=False)

print("=" * 70)
print("PRIMARY CV PERFORMANCE SUMMARY")
print("=" * 70)
display(primary_cv_summary.round(4))

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5F290>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5F1D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD7D10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB8650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007067988547346615), 'bp': np.float64(0.07005529207613247), 'sg': np.float64(0.0), 'al': np.float64(0.8334280024922338), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03898959967616611), 'bu': np.float64(0.0175814233577056), 'sc': np.float64(0.5561575341139979), 'sod': np.float64(0.017603009549310957), 'pot': np.float64(0.0), 'hemo': np.float64(0.5218637312486231), 'pcv': np.float64(0.187297075467749), 'wc': np.float64(0.00011666575812822751), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.008480622832699309), 'bp': np.float64(0.08405680138733432), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04678220501299922), 'bu': np.float64(0.02109531153876658), 'sc': np.float64(0.6673132321579036), 'sod': np.float64(0.02112121202632016), 'pot': np.float64(0.0), 'hemo': np.float64(0.6261653432426948), 'pcv': np.float64(0.22473096045209295), 'wc': np.float64(0.00013998300726560318), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCAA50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCBFB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCB890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB8650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0024066746689654158), 'bp': np.float64(0.05833958256316776), 'sg': np.float64(0.0), 'al': np.float64(0.7208225985979881), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03759365862127554), 'bu': np.float64(0.01270644399254112), 'sc': np.float64(0.716708054133204), 'sod': np.float64(0.026377456497405857), 'pot': np.float64(0.0), 'hemo': np.float64(0.5510711727643575), 'pcv': np.float64(0.18573382569606825), 'wc': np.float64(7.290260808428345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.003338789146797614), 'bp': np.float64(0.08093473023270804), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0521538291035767), 'bu': np.float64(0.01762769926644276), 'sc': np.float64(0.9942918764300857), 'sod': np.float64(0.036593548188847635), 'pot': np.float64(0.0), 'hemo': np.float64(0.7645031854386919), 'pcv': np.float64(0.25766926017209174), 'wc': np.float64(0.00010113807228863277), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x00000240FBB562D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095BEF530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095BEF230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C25550>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0031072491260507756), 'bp': np.float64(0.07159041318781663), 'sg': np.float64(0.0), 'al': np.float64(0.8600180449510871), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036740769263662536), 'bu': np.float64(0.021342548967224248), 'sc': np.float64(0.5486184352585247), 'sod': np.float64(0.022997693461116516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6243123472769746), 'pcv': np.float64(0.19904413772656845), 'wc': np.float64(0.00022197680648527882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0036130045692558672), 'bp': np.float64(0.08324291985279016), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04272092833325624), 'bu': np.float64(0.02481639669367413), 'sc': np.float64(0.6379150280384256), 'sod': np.float64(0.0267409429326852), 'pot': np.float64(0.0), 'hemo': np.float64(0.7259293580432744), 'pcv': np.float64(0.2314418155468923), 'wc': np.float64(0.00025810714994695675), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBFF50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBC050>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095BEF710>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAB70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.005086356747865055), 'bp': np.float64(0.06888912204458209), 'sg': np.float64(0.0), 'al': np.float64(0.7034248172495389), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03612869657112075), 'bu': np.float64(0.011658761511980151), 'sc': np.float64(0.6255541034771989), 'sod': np.float64(0.04050236531521802), 'pot': np.float64(0.0), 'hemo': np.float64(0.7212044590439799), 'pcv': np.float64(0.1715620425091385), 'wc': np.float64(3.9307181318114794e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007052586383904876), 'bp': np.float64(0.09551954536706649), 'sg': np.float64(0.0), 'al': np.float64(0.9753472935843887), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05009494342147097), 'bu': np.float64(0.016165681403904335), 'sc': np.float64(0.867374148388414), 'sod': np.float64(0.056159338461256154), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.2378826702438295), 'wc': np.float64(5.45021329599375e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03252247488101534, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBB590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB80B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.05369963512904516), 'sg': np.float64(0.0), 'al': np.float64(0.9042936809261033), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036724261205674076), 'bu': np.float64(0.030066007778714297), 'sc': np.float64(0.33372416024923396), 'sod': np.float64(0.03069648277201783), 'pot': np.float64(0.0), 'hemo': np.float64(0.5711465636295389), 'pcv': np.float64(0.18309587261958607), 'wc': np.float64(6.11356437081272e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.059382959608929704), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040610989527278464), 'bu': np.float64(0.03324805692319243), 'sc': np.float64(0.369044003389984), 'sod': np.float64(0.03394525851444744), 'pot': np.float64(0.0), 'hemo': np.float64(0.6315941111571381), 'pcv': np.float64(0.20247390475191016), 'wc': np.float64(6.760596142341401e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

PRIMARY: completed 5/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB050>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06647774923969976), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04216637264929467), 'bu': np.float64(0.0199780487904666), 'sc': np.float64(0.7471967408754032), 'sod': np.float64(0.032087899795664565), 'pot': np.float64(0.0), 'hemo': np.float64(0.6409570368279527), 'pcv': np.float64(0.22610798568957455), 'wc': np.float64(0.0001581903527052474), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E00B90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06647774923969976), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04216637264929467), 'bu': np.float64(0.0199780487904666), 'sc': np.float64(0.7471967408754032), 'sod': np.float64(0.032087899795664565), 'pot': np.float64(0.0), 'hemo': np.float64(0.6409570368279527), 'pcv': np.float64(0.22610798568957455), 'wc': np.float64(0.0001581903527052474), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBDB50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06647774923969976), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04216637264929467), 'bu': np.float64(0.0199780487904666), 'sc': np.float64(0.7471967408754032), 'sod': np.float64(0.032087899795664565), 'pot': np.float64(0.0), 'hemo': np.float64(0.6409570368279527), 'pcv': np.float64(0.22610798568957455), 'wc': np.float64(0.0001581903527052474), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E01BB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.056315579336629014), 'sg': np.float64(0.0), 'al': np.float64(0.8471342664381), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0357205791626158), 'bu': np.float64(0.016924089706976495), 'sc': np.float64(0.6329759629664238), 'sod': np.float64(0.02718275945493956), 'pot': np.float64(0.0), 'hemo': np.float64(0.5429766692115859), 'pcv': np.float64(0.19154382259293415), 'wc': np.float64(0.00013400846839654404), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06647774923969976), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04216637264929467), 'bu': np.float64(0.0199780487904666), 'sc': np.float64(0.7471967408754032), 'sod': np.float64(0.032087899795664565), 'pot': np.float64(0.0), 'hemo': np.float64(0.6409570368279527), 'pcv': np.float64(0.22610798568957455), 'wc': np.float64(0.0001581903527052474), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5F050>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.004427283174504777), 'bp': np.float64(0.0938449402378741), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05169391489424759), 'bu': np.float64(0.03351944462277235), 'sc': np.float64(0.6966477754451825), 'sod': np.float64(0.02772097554749944), 'pot': np.float64(0.0), 'hemo': np.float64(0.7300312069110736), 'pcv': np.float64(0.26221211528309285), 'wc': np.float64(0.00015729304052792637), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5EDB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.004427283174504777), 'bp': np.float64(0.0938449402378741), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05169391489424759), 'bu': np.float64(0.03351944462277235), 'sc': np.float64(0.6966477754451825), 'sod': np.float64(0.02772097554749944), 'pot': np.float64(0.0), 'hemo': np.float64(0.7300312069110736), 'pcv': np.float64(0.26221211528309285), 'wc': np.float64(0.00015729304052792637), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5DF70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.004427283174504777), 'bp': np.float64(0.0938449402378741), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05169391489424759), 'bu': np.float64(0.03351944462277235), 'sc': np.float64(0.6966477754451825), 'sod': np.float64(0.02772097554749944), 'pot': np.float64(0.0), 'hemo': np.float64(0.7300312069110736), 'pcv': np.float64(0.26221211528309285), 'wc': np.float64(0.00015729304052792637), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5E090>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0035078990462133084), 'bp': np.float64(0.07435679250157895), 'sg': np.float64(0.0), 'al': np.float64(0.7923367238883905), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04095898717227341), 'bu': np.float64(0.02655868693896577), 'sc': np.float64(0.551979616100371), 'sod': np.float64(0.02196434694829589), 'pot': np.float64(0.0), 'hemo': np.float64(0.5784305348202078), 'pcv': np.float64(0.20776028838725075), 'wc': np.float64(0.000124629052422341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.004427283174504777), 'bp': np.float64(0.0938449402378741), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05169391489424759), 'bu': np.float64(0.03351944462277235), 'sc': np.float64(0.6966477754451825), 'sod': np.float64(0.02772097554749944), 'pot': np.float64(0.0), 'hemo': np.float64(0.7300312069110736), 'pcv': np.float64(0.26221211528309285), 'wc': np.float64(0.00015729304052792637), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBE930>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005230016332046231), 'bp': np.float64(0.08399848549450768), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04841796793892626), 'bu': np.float64(0.021779243287129168), 'sc': np.float64(0.9263756001023423), 'sod': np.float64(0.02556883060938116), 'pot': np.float64(0.0), 'hemo': np.float64(0.7885179319189696), 'pcv': np.float64(0.20940921879204577), 'wc': np.float64(0.00015262050239288824), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBABD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005230016332046231), 'bp': np.float64(0.08399848549450768), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04841796793892626), 'bu': np.float64(0.021779243287129168), 'sc': np.float64(0.9263756001023423), 'sod': np.float64(0.02556883060938116), 'pot': np.float64(0.0), 'hemo': np.float64(0.7885179319189696), 'pcv': np.float64(0.20940921879204577), 'wc': np.float64(0.00015262050239288824), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBF3B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005230016332046231), 'bp': np.float64(0.08399848549450768), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04841796793892626), 'bu': np.float64(0.021779243287129168), 'sc': np.float64(0.9263756001023423), 'sod': np.float64(0.02556883060938116), 'pot': np.float64(0.0), 'hemo': np.float64(0.7885179319189696), 'pcv': np.float64(0.20940921879204577), 'wc': np.float64(0.00015262050239288824), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBB230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.003949749950744433), 'bp': np.float64(0.0634363246461858), 'sg': np.float64(0.0), 'al': np.float64(0.7552079572950592), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03656563466353417), 'bu': np.float64(0.016447857834304948), 'sc': np.float64(0.6996062246412745), 'sod': np.float64(0.01930978433493413), 'pot': np.float64(0.0), 'hemo': np.float64(0.5954950166550496), 'pcv': np.float64(0.158147508362695), 'wc': np.float64(0.00011526021785347882), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005230016332046231), 'bp': np.float64(0.08399848549450768), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04841796793892626), 'bu': np.float64(0.021779243287129168), 'sc': np.float64(0.9263756001023423), 'sod': np.float64(0.02556883060938116), 'pot': np.float64(0.0), 'hemo': np.float64(0.7885179319189696), 'pcv': np.float64(0.20940921879204577), 'wc': np.float64(0.00015262050239288824), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E026F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCBEF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBB650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.008934502214940705), 'bp': np.float64(0.05732491972934189), 'sg': np.float64(0.0), 'al': np.float64(0.7147867254184851), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.033938799785652576), 'bu': np.float64(0.01964464876872973), 'sc': np.float64(0.6608910693991428), 'sod': np.float64(0.04025013702543571), 'pot': np.float64(0.0), 'hemo': np.float64(0.6356681947626699), 'pcv': np.float64(0.18171225408295574), 'wc': np.float64(6.414803898744735e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.012499535731738492), 'bp': np.float64(0.0801986350484894), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04748101577541536), 'bu': np.float64(0.02748323110957105), 'sc': np.float64(0.9245989690312336), 'sod': np.float64(0.0563106946367401), 'pot': np.float64(0.0), 'hemo': np.float64(0.8893116955837508), 'pcv': np.float64(0.2542188426576738), 'wc': np.float64(8.974430652708429e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB82F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAD50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB8DD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0042395312724732145), 'bp': np.float64(0.0827669593822689), 'sg': np.float64(0.0), 'al': np.float64(0.9242762553548725), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03955904344351791), 'bu': np.float64(0.021895832013337325), 'sc': np.float64(0.1640345267405518), 'sod': np.float64(0.024044410498073456), 'pot': np.float64(0.0), 'hemo': np.float64(0.6489160210545746), 'pcv': np.float64(0.1860257873733112), 'wc': np.float64(4.378375163978738e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0045868659374414655), 'bp': np.float64(0.08954785855717004), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04280002132947726), 'bu': np.float64(0.023689705200671308), 'sc': np.float64(0.17747348348527178), 'sod': np.float64(0.026014311585708425), 'pot': np.float64(0.0), 'hemo': np.float64(0.7020801597953262), 'pcv': np.float64(0.20126643554408666), 'wc': np.float64(4.7370849771507733e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032018442622950824, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

PRIMARY: completed 10/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBE030>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBF1D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9AF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAD50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007830315168853746), 'bp': np.float64(0.06790491469519352), 'sg': np.float64(0.0), 'al': np.float64(0.8579071586810835), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03756256677115064), 'bu': np.float64(0.013558496190445232), 'sc': np.float64(0.6564004579921074), 'sod': np.float64(0.02588424552767912), 'pot': np.float64(0.0), 'hemo': np.float64(0.5560028892937491), 'pcv': np.float64(0.18892743777504933), 'wc': np.float64(8.991942033845215e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009127229082563899), 'bp': np.float64(0.07915182197522186), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04378395306655095), 'bu': np.float64(0.01580415322712727), 'sc': np.float64(0.7651182897240706), 'sod': np.float64(0.030171383075381555), 'pot': np.float64(0.0), 'hemo': np.float64(0.64809214338359), 'pcv': np.float64(0.22021897808324595), 'wc': np.float64(0.00010481253062008612), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA3F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E00890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB86B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB85F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0010478632350914485), 'bp': np.float64(0.06112779846513972), 'sg': np.float64(0.0), 'al': np.float64(0.8068677790049218), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03907962522391999), 'bu': np.float64(0.01680830829703476), 'sc': np.float64(0.7603074527546817), 'sod': np.float64(0.012805128014100215), 'pot': np.float64(0.0), 'hemo': np.float64(0.6448619878210218), 'pcv': np.float64(0.12237143408881537), 'wc': np.float64(9.234073190342185e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0012986802328179927), 'bp': np.float64(0.07575937477702509), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.048433741240870166), 'bu': np.float64(0.02083155224981692), 'sc': np.float64(0.9422949738956473), 'sod': np.float64(0.015870169000790035), 'pot': np.float64(0.0), 'hemo': np.float64(0.7992164324820414), 'pcv': np.float64(0.1516623135450163), 'wc': np.float64(0.00011444344947979213), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.03252247488101534, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB87D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5FCB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBB530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0632843779770715), 'sg': np.float64(0.0), 'al': np.float64(0.8277908966606974), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.035748299841891464), 'bu': np.float64(0.01282289756328185), 'sc': np.float64(0.6281737613169497), 'sod': np.float64(0.027561772630074307), 'pot': np.float64(0.0), 'hemo': np.float64(0.614240177069764), 'pcv': np.float64(0.16435410675713694), 'wc': np.float64(6.202671599909345e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07644971481609696), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04318518116845674), 'bu': np.float64(0.015490503235792189), 'sc': np.float64(0.7588556045385353), 'sod': np.float64(0.033295573485113576), 'pot': np.float64(0.0), 'hemo': np.float64(0.7420233534188458), 'pcv': np.float64(0.19854543873355002), 'wc': np.float64(7.493041569955502e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.030158730158730156, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07026889626309528), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04226759967793602), 'bu': np.float64(0.03911786098283301), 'sc': np.float64(0.2161687986218055), 'sod': np.float64(0.03290790840197277), 'pot': np.float64(0.0), 'hemo': np.float64(0.7081037735878919), 'pcv': np.float64(0.23378190899319135), 'wc': np.float64(0.00022941631770969145), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032018442622950824, 'sod': 0.030330882352941176, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAA50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07026889626309528), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04226759967793602), 'bu': np.float64(0.03911786098283301), 'sc': np.float64(0.2161687986218055), 'sod': np.float64(0.03290790840197277), 'pot': np.float64(0.0), 'hemo': np.float64(0.7081037735878919), 'pcv': np.float64(0.23378190899319135), 'wc': np.float64(0.00022941631770969145), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032018442622950824, 'sod': 0.030330882352941176, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bu', 'bgr', 'rbc', 'htn', 'dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07026889626309528), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04226759967793602), 'bu': np.float64(0.03911786098283301), 'sc': np.float64(0.2161687986218055), 'sod': np.float64(0.03290790840197277), 'pot': np.float64(0.0), 'hemo': np.float64(0.7081037735878919), 'pcv': np.float64(0.23378190899319135), 'wc': np.float64(0.00022941631770969145), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032018442622950824, 'sod': 0.030330882352941176, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'sod', 'pot', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E020F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06548827996694422), 'sg': np.float64(0.0), 'al': np.float64(0.9319668224437189), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03939200056416919), 'bu': np.float64(0.036456548600966004), 'sc': np.float64(0.20146214836304022), 'sod': np.float64(0.030669078826655517), 'pot': np.float64(0.0), 'hemo': np.float64(0.6599292238311142), 'pcv': np.float64(0.2178769828692112), 'wc': np.float64(0.0002138083966326398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.07026889626309528), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04226759967793602), 'bu': np.float64(0.03911786098283301), 'sc': np.float64(0.2161687986218055), 'sod': np.float64(0.03290790840197277), 'pot': np.float64(0.0), 'hemo': np.float64(0.7081037735878919), 'pcv': np.float64(0.23378190899319135), 'wc': np.float64(0.00022941631770969145), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.03278688524590164, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032018442622950824, 'sod': 0.030330882352941176, 'pot': 0.030158730158730156, 'hemo': 0.03200204813108039, 'pcv': 0.03149801587301587, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'pcv', 'bp', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'sod', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB9430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.1052422279398648), 'sg': np.float64(0.0), 'al': np.float64(0.9597806441919973), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05607607126838534), 'bu': np.float64(0.030485737978216413), 'sc': np.float64(0.9797451434939232), 'sod': np.float64(0.06433418637178208), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.33258137242145686), 'wc': np.float64(8.905288925716106e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.032266458495966696, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.030158730158730156, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 5 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBAAB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.1052422279398648), 'sg': np.float64(0.0), 'al': np.float64(0.9597806441919973), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05607607126838534), 'bu': np.float64(0.030485737978216413), 'sc': np.float64(0.9797451434939232), 'sod': np.float64(0.06433418637178208), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.33258137242145686), 'wc': np.float64(8.905288925716106e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.032266458495966696, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.030158730158730156, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 10 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB89B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.1052422279398648), 'sg': np.float64(0.0), 'al': np.float64(0.9597806441919973), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05607607126838534), 'bu': np.float64(0.030485737978216413), 'sc': np.float64(0.9797451434939232), 'sod': np.float64(0.06433418637178208), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.33258137242145686), 'wc': np.float64(8.905288925716106e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.032266458495966696, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.030158730158730156, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 15 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA7B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.06550574383649156), 'sg': np.float64(0.0), 'al': np.float64(0.5973946603789904), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.034903335208397654), 'bu': np.float64(0.018975186878488766), 'sc': np.float64(0.6098211302732142), 'sod': np.float64(0.0400434199740344), 'pot': np.float64(0.0), 'hemo': np.float64(0.6224283267161677), 'pcv': np.float64(0.20700806713325398), 'wc': np.float64(5.5429040849574944e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.1052422279398648), 'sg': np.float64(0.0), 'al': np.float64(0.9597806441919973), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05607607126838534), 'bu': np.float64(0.030485737978216413), 'sc': np.float64(0.9797451434939232), 'sod': np.float64(0.06433418637178208), 'pot': np.float64(0.0), 'hemo': np.float64(1.0), 'pcv': np.float64(0.33258137242145686), 'wc': np.float64(8.905288925716106e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.029910714285714284, 'bp': 0.03125763125763126, 'sg': 0.02967032967032967, 'al': 0.032266458495966696, 'su': 0.029437229437229435, 'rbc': 0.0304147465437788, 'pc': 0.029437229437229435, 'pcc': 0.029437229437229435, 'ba': 0.029211087420042643, 'bgr': 0.03055037313432836, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.030776515151515152, 'pot': 0.030158730158730156, 'hemo': 0.032266458495966696, 'pcv': 0.03125, 'wc': 0.029418126757516764, 'rc': 0.02967032967032967, 'htn': 0.0304147465437788, 'dm': 0.0304147465437788, 'cad': 0.029910714285714284, 'appet': 0.029437229437229435, 'pe': 0.029910714285714284, 'ane': 0.029910714285714284}
Top 20 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'sod', 'bu', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

PRIMARY: completed 15/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CB8EF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009299379424419888), 'bp': np.float64(0.1437137754168779), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0522723229695084), 'bu': np.float64(0.03895712661637961), 'sc': np.float64(0.7816643880777353), 'sod': np.float64(0.04436648684594182), 'pot': np.float64(0.0), 'hemo': np.float64(0.9711745664829647), 'pcv': np.float64(0.35688507966633015), 'wc': np.float64(0.00027973022245681963), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5D370>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009299379424419888), 'bp': np.float64(0.1437137754168779), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0522723229695084), 'bu': np.float64(0.03895712661637961), 'sc': np.float64(0.7816643880777353), 'sod': np.float64(0.04436648684594182), 'pot': np.float64(0.0), 'hemo': np.float64(0.9711745664829647), 'pcv': np.float64(0.35688507966633015), 'wc': np.float64(0.00027973022245681963), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBA1B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009299379424419888), 'bp': np.float64(0.1437137754168779), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0522723229695084), 'bu': np.float64(0.03895712661637961), 'sc': np.float64(0.7816643880777353), 'sod': np.float64(0.04436648684594182), 'pot': np.float64(0.0), 'hemo': np.float64(0.9711745664829647), 'pcv': np.float64(0.35688507966633015), 'wc': np.float64(0.00027973022245681963), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DC8470>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0059073978620217335), 'bp': np.float64(0.09129366712485727), 'sg': np.float64(0.0), 'al': np.float64(0.6352464602647663), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03320580813619685), 'bu': np.float64(0.024747376785141457), 'sc': np.float64(0.4965495356414059), 'sod': np.float64(0.028183653723267855), 'pot': np.float64(0.0), 'hemo': np.float64(0.6169352056574723), 'pcv': np.float64(0.22670998357934535), 'wc': np.float64(0.0001776976336447703), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009299379424419888), 'bp': np.float64(0.1437137754168779), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0522723229695084), 'bu': np.float64(0.03895712661637961), 'sc': np.float64(0.7816643880777353), 'sod': np.float64(0.04436648684594182), 'pot': np.float64(0.0), 'hemo': np.float64(0.9711745664829647), 'pcv': np.float64(0.35688507966633015), 'wc': np.float64(0.00027973022245681963), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD5CD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBC230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBEC90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBCEF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002530512176439522), 'bp': np.float64(0.06737520318116055), 'sg': np.float64(0.0), 'al': np.float64(0.8996493957148928), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03807795765943031), 'bu': np.float64(0.026606218787505114), 'sc': np.float64(0.28923305128954474), 'sod': np.float64(0.029878079373101107), 'pot': np.float64(0.0), 'hemo': np.float64(0.5683528652981609), 'pcv': np.float64(0.19916176916852948), 'wc': np.float64(5.707604817441487e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002812775941930899), 'bp': np.float64(0.07489051123923877), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04232533011281827), 'bu': np.float64(0.02957398617087147), 'sc': np.float64(0.32149529879882827), 'sod': np.float64(0.03321080358127618), 'pot': np.float64(0.0), 'hemo': np.float64(0.6317492881174315), 'pcv': np.float64(0.2213770943627085), 'wc': np.float64(6.344254600322413e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9C70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA0F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCAED0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5F590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0007222545591661139), 'bp': np.float64(0.056093955281117866), 'sg': np.float64(0.0), 'al': np.float64(0.7171881819835465), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03900842282447291), 'bu': np.float64(0.022194701985728017), 'sc': np.float64(0.5189723713514856), 'sod': np.float64(0.016932249470457666), 'pot': np.float64(0.0), 'hemo': np.float64(0.5332847443960281), 'pcv': np.float64(0.197404495983871), 'wc': np.float64(0.00025128711642476826), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0010070642229052843), 'bp': np.float64(0.07821371948151365), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05439077748964891), 'bu': np.float64(0.0309468317287989), 'sc': np.float64(0.7236209190120085), 'sod': np.float64(0.023609214284077702), 'pot': np.float64(0.0), 'hemo': np.float64(0.7435771500320993), 'pcv': np.float64(0.27524783723834395), 'wc': np.float64(0.0003503782169552443), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.030798389007344232, 'sc': 0.032266458495966696, 'sod': 0.030330882352941176, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bu', 'bgr', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DC92B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5E4B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9550>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBB170>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0006232626051134012), 'bp': np.float64(0.05233330702247657), 'sg': np.float64(0.0), 'al': np.float64(0.8115298487004667), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03865156190744363), 'bu': np.float64(0.012126247327628134), 'sc': np.float64(0.6995025360126592), 'sod': np.float64(0.037019321409051606), 'pot': np.float64(0.0), 'hemo': np.float64(0.7368718788044091), 'pcv': np.float64(0.14115616194169664), 'wc': np.float64(2.484417468755853e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.000768009465223559), 'bp': np.float64(0.06448722386031748), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.04762802251739456), 'bu': np.float64(0.014942453869129213), 'sc': np.float64(0.861955400818342), 'sod': np.float64(0.04561670956198597), 'pot': np.float64(0.0), 'hemo': np.float64(0.9080034209270179), 'pcv': np.float64(0.17393834887002038), 'wc': np.float64(3.06139998760889e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA270>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB8710>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DC81D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E03410>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0067904724873102396), 'bp': np.float64(0.06544792657012953), 'sg': np.float64(0.0), 'al': np.float64(0.9006654490094549), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03592016545965666), 'bu': np.float64(0.012732383773751408), 'sc': np.float64(0.6936113527032), 'sod': np.float64(0.024984159709304277), 'pot': np.float64(0.0), 'hemo': np.float64(0.614596190847226), 'pcv': np.float64(0.15341254188159312), 'wc': np.float64(4.504025267693003e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.007539394893829168), 'bp': np.float64(0.07266618991780874), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.039881806834226166), 'bu': np.float64(0.014136640622502382), 'sc': np.float64(0.7701098709471186), 'sod': np.float64(0.027739667083689808), 'pot': np.float64(0.0), 'hemo': np.float64(0.6823801129744173), 'pcv': np.float64(0.1703324381437248), 'wc': np.float64(5.000775007686257e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

PRIMARY: completed 20/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBDFD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD4770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD6450>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBA0F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.002423035620402879), 'bp': np.float64(0.06911943435372526), 'sg': np.float64(0.0), 'al': np.float64(0.8656004150412385), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03074941318197295), 'bu': np.float64(0.018618595497045375), 'sc': np.float64(0.4960485131576613), 'sod': np.float64(0.028140553549128134), 'pot': np.float64(0.0), 'hemo': np.float64(0.5749927309717062), 'pcv': np.float64(0.19084083471498337), 'wc': np.float64(0.0001173980517617121), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.002799254226660048), 'bp': np.float64(0.07985143393263312), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0355237967168812), 'bu': np.float64(0.021509457682224373), 'sc': np.float64(0.5730687099243463), 'sod': np.float64(0.032509866053827476), 'pot': np.float64(0.0), 'hemo': np.float64(0.6642703965712778), 'pcv': np.float64(0.22047220795971015), 'wc': np.float64(0.00013562615003612154), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9730>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB88F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBF350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095CBE1B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0005381255531994244), 'bp': np.float64(0.06427054495774441), 'sg': np.float64(0.0), 'al': np.float64(0.9348368858424773), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03557969603612039), 'bu': np.float64(0.021561193526391013), 'sc': np.float64(0.5509972714467994), 'sod': np.float64(0.026974092904775798), 'pot': np.float64(0.0), 'hemo': np.float64(0.6336901064481155), 'pcv': np.float64(0.178065288298606), 'wc': np.float64(0.00013874966909400795), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005756357727738399), 'bp': np.float64(0.06875054453999602), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038059790509930386), 'bu': np.float64(0.023064123648651298), 'sc': np.float64(0.5894047183966638), 'sod': np.float64(0.028854330967553424), 'pot': np.float64(0.0), 'hemo': np.float64(0.6778616847975917), 'pcv': np.float64(0.19047738808266335), 'wc': np.float64(0.00014842126064480907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5FCB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005076271991282865), 'bp': np.float64(0.07112716153447728), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03741392274497845), 'bu': np.float64(0.01811445881815552), 'sc': np.float64(0.7131483401616853), 'sod': np.float64(0.022634535614807178), 'pot': np.float64(0.0), 'hemo': np.float64(0.630692947338831), 'pcv': np.float64(0.17248319562790757), 'wc': np.float64(7.157986869402226e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099D5E390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005076271991282865), 'bp': np.float64(0.07112716153447728), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03741392274497845), 'bu': np.float64(0.01811445881815552), 'sc': np.float64(0.7131483401616853), 'sod': np.float64(0.022634535614807178), 'pot': np.float64(0.0), 'hemo': np.float64(0.630692947338831), 'pcv': np.float64(0.17248319562790757), 'wc': np.float64(7.157986869402226e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCB9B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005076271991282865), 'bp': np.float64(0.07112716153447728), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03741392274497845), 'bu': np.float64(0.01811445881815552), 'sc': np.float64(0.7131483401616853), 'sod': np.float64(0.022634535614807178), 'pot': np.float64(0.0), 'hemo': np.float64(0.630692947338831), 'pcv': np.float64(0.17248319562790757), 'wc': np.float64(7.157986869402226e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB8A70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.00046553176389978966), 'bp': np.float64(0.06522887864793567), 'sg': np.float64(0.0), 'al': np.float64(0.9170741140333212), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03431134005386224), 'bu': np.float64(0.016612301271853053), 'sc': np.float64(0.6540098822281111), 'sod': np.float64(0.020757546695504947), 'pot': np.float64(0.0), 'hemo': np.float64(0.5783921759078225), 'pcv': np.float64(0.15817987381609935), 'wc': np.float64(6.564404466519193e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0005076271991282865), 'bp': np.float64(0.07112716153447728), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03741392274497845), 'bu': np.float64(0.01811445881815552), 'sc': np.float64(0.7131483401616853), 'sod': np.float64(0.022634535614807178), 'pot': np.float64(0.0), 'hemo': np.float64(0.630692947338831), 'pcv': np.float64(0.17248319562790757), 'wc': np.float64(7.157986869402226e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03252247488101534, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.031746031746031744, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFABD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009041941120717354), 'bp': np.float64(0.0698678956980507), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05346706919135869), 'bu': np.float64(0.02665018224373051), 'sc': np.float64(0.4332862994312083), 'sod': np.float64(0.045648674746017824), 'pot': np.float64(0.0), 'hemo': np.float64(0.7979879465987304), 'pcv': np.float64(0.2384509915308636), 'wc': np.float64(0.00010240846833461283), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB8AD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009041941120717354), 'bp': np.float64(0.0698678956980507), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05346706919135869), 'bu': np.float64(0.02665018224373051), 'sc': np.float64(0.4332862994312083), 'sod': np.float64(0.045648674746017824), 'pot': np.float64(0.0), 'hemo': np.float64(0.7979879465987304), 'pcv': np.float64(0.2384509915308636), 'wc': np.float64(0.00010240846833461283), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9970>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009041941120717354), 'bp': np.float64(0.0698678956980507), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05346706919135869), 'bu': np.float64(0.02665018224373051), 'sc': np.float64(0.4332862994312083), 'sod': np.float64(0.045648674746017824), 'pot': np.float64(0.0), 'hemo': np.float64(0.7979879465987304), 'pcv': np.float64(0.2384509915308636), 'wc': np.float64(0.00010240846833461283), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9610>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.007480788814938894), 'bp': np.float64(0.057804730829725696), 'sg': np.float64(0.0), 'al': np.float64(0.827343234717436), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.044235617975639664), 'bu': np.float64(0.022048847983337175), 'sc': np.float64(0.3584764885301634), 'sod': np.float64(0.037767122224934516), 'pot': np.float64(0.0), 'hemo': np.float64(0.6602099290045181), 'pcv': np.float64(0.19728081465472463), 'wc': np.float64(8.47269534544167e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.009041941120717354), 'bp': np.float64(0.0698678956980507), 'sg': np.float64(0.0), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05346706919135869), 'bu': np.float64(0.02665018224373051), 'sc': np.float64(0.4332862994312083), 'sod': np.float64(0.045648674746017824), 'pot': np.float64(0.0), 'hemo': np.float64(0.7979879465987304), 'pcv': np.float64(0.2384509915308636), 'wc': np.float64(0.00010240846833461283), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.03278688524590164, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.032266458495966696, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['al', 'sc', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E00470>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005711873891163141), 'bp': np.float64(0.0938023539231203), 'sg': np.float64(0.0), 'al': np.float64(0.4858104597266678), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05389205106659081), 'bu': np.float64(0.02354631921428538), 'sc': np.float64(1.0), 'sod': np.float64(0.03914508757576098), 'pot': np.float64(0.0), 'hemo': np.float64(0.8441202679754073), 'pcv': np.float64(0.25509793302802586), 'wc': np.float64(8.610062700555763e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.032266458495966696, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03278688524590164, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 5 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBAC90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005711873891163141), 'bp': np.float64(0.0938023539231203), 'sg': np.float64(0.0), 'al': np.float64(0.4858104597266678), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05389205106659081), 'bu': np.float64(0.02354631921428538), 'sc': np.float64(1.0), 'sod': np.float64(0.03914508757576098), 'pot': np.float64(0.0), 'hemo': np.float64(0.8441202679754073), 'pcv': np.float64(0.25509793302802586), 'wc': np.float64(8.610062700555763e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.032266458495966696, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03278688524590164, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 10 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DB9E50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005711873891163141), 'bp': np.float64(0.0938023539231203), 'sg': np.float64(0.0), 'al': np.float64(0.4858104597266678), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05389205106659081), 'bu': np.float64(0.02354631921428538), 'sc': np.float64(1.0), 'sod': np.float64(0.03914508757576098), 'pot': np.float64(0.0), 'hemo': np.float64(0.8441202679754073), 'pcv': np.float64(0.25509793302802586), 'wc': np.float64(8.610062700555763e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.032266458495966696, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03278688524590164, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 15 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DBAE70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.004250014798138015), 'bp': np.float64(0.06979520204222489), 'sg': np.float64(0.0), 'al': np.float64(0.36147535507092987), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.040099277207322835), 'bu': np.float64(0.017520030555509353), 'sc': np.float64(0.7440666371701985), 'sod': np.float64(0.02912655367422939), 'pot': np.float64(0.0), 'hemo': np.float64(0.6280817291596681), 'pcv': np.float64(0.18980986117723173), 'wc': np.float64(6.406460399427085e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.005711873891163141), 'bp': np.float64(0.0938023539231203), 'sg': np.float64(0.0), 'al': np.float64(0.4858104597266678), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05389205106659081), 'bu': np.float64(0.02354631921428538), 'sc': np.float64(1.0), 'sod': np.float64(0.03914508757576098), 'pot': np.float64(0.0), 'hemo': np.float64(0.8441202679754073), 'pcv': np.float64(0.25509793302802586), 'wc': np.float64(8.610062700555763e-05), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030117753623188408, 'bp': 0.03125763125763126, 'sg': 0.02946912242686891, 'al': 0.032266458495966696, 'su': 0.029236022193768675, 'rbc': 0.03021353930031804, 'pc': 0.029236022193768675, 'pcc': 0.029236022193768675, 'ba': 0.02900988017658188, 'bgr': 0.030776515151515152, 'bu': 0.03057889822595705, 'sc': 0.03278688524590164, 'sod': 0.03055037313432836, 'pot': 0.029957522915269395, 'hemo': 0.03200204813108039, 'pcv': 0.03125, 'wc': 0.029211087420042643, 'rc': 0.02946912242686891, 'htn': 0.03021353930031804, 'dm': 0.03021353930031804, 'cad': 0.029709507042253523, 'appet': 0.029236022193768675, 'pe': 0.029709507042253523, 'ane': 0.029709507042253523}
Top 20 Features Selected: ['sc', 'al', 'hemo', 'bp', 'pcv', 'bgr', 'bu', 'sod', 'rbc', 'htn', 'dm', 'age', 'pot', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

PRIMARY: completed 25/25 CV runs
======================================================================
PRIMARY CV PERFORMANCE SUMMARY
======================================================================

    Top_K Method Model  Acc_Mean  Acc_STD  F1_Mean  F1_STD  AUC_Mean  AUC_STD
0       5   DODA    LR    0.9555   0.0242   0.9636  0.0204    0.9892   0.0115
1       5   DODA    RF    0.9690   0.0211   0.9746  0.0178    0.9911   0.0085
2       5   DODA   XGB    0.9590   0.0230   0.9666  0.0192    0.9895   0.0101
3       5  LASSO    LR    0.9555   0.0242   0.9636  0.0204    0.9892   0.0115
4       5  LASSO    RF    0.9690   0.0220   0.9746  0.0185    0.9910   0.0090
5       5  LASSO   XGB    0.9600   0.0228   0.9675  0.0191    0.9896   0.0097
6      10   DODA    LR    0.9665   0.0168   0.9727  0.0139    0.9943   0.0068
7      10   DODA    RF    0.9805   0.0145   0.9843  0.0117    0.9989   0.0012
8      10   DODA   XGB    0.9765   0.0178   0.9811  0.0145    0.9979   0.0024
9      10  LASSO    LR    0.9575   0.0260   0.9651  0.0220    0.9929   0.0089
10     10  LASSO    RF    0.9790   0.0160   0.9831  0.0130    0.9986   0.0015
11     10  LASSO   XGB    0.9775   0.0169   0.9819  0.0136    0.9978   0.0025
12     15   DODA    LR    0.9755   0.0146   0.9800  0.0122    0.9959   0.0059
13     15   DODA    RF    0.9860   0.0121   0.9888  0.0098    0.9995   0.0007
14     15   DODA   XGB    0.9805   0.0173   0.9843  0.0142    0.9978   0.0026
15     15  LASSO    LR    0.9805   0.0140   0.9841  0.0116    0.9991   0.0011
16     15  LASSO    RF    0.9905   0.0110   0.9924  0.0088    0.9998   0.0003
17     15  LASSO   XGB    0.9865   0.0130   0.9891  0.0105    0.9989   0.0015
18     20   DODA    LR    0.9915   0.0113   0.9931  0.0092    0.9999   0.0003
19     20   DODA    RF    0.9920   0.0087   0.9936  0.0070    0.9998   0.0003
20     20   DODA   XGB    0.9875   0.0125   0.9900  0.0100    0.9989   0.0016
21     20  LASSO    LR    0.9840   0.0128   0.9869  0.0105    0.9997   0.0005
22     20  LASSO    RF    0.9915   0.0094   0.9932  0.0074    0.9998   0.0003
23     20  LASSO   XGB    0.9870   0.0127   0.9896  0.0102    0.9989   0.0016

In [16]:
# =============================================================================
# PRIMARY: PERFORMANCE SIGNIFICANCE TESTING
# =============================================================================

primary_perf_test = wilcoxon_holm_test(
    primary_cv_results, ["Top_K", "Model"], value_col="ROC_AUC"
)
print("=" * 70)
print("PRIMARY — LASSO vs DODA ROC-AUC: SIGNIFICANCE TEST")
print("=" * 70)
display(primary_perf_test.round(4))

======================================================================
PRIMARY — LASSO vs DODA ROC-AUC: SIGNIFICANCE TEST
======================================================================

    Top_K Model  LASSO_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0       5    LR      0.9892     0.9892   1.0000    0.0000  1.0000        False
1       5    RF      0.9910     0.9911   0.8127    0.0077  1.0000        False
2       5   XGB      0.9896     0.9895   0.5922   -0.0163  1.0000        False
3      10    LR      0.9929     0.9943   0.0130    0.1764  0.1166        False
4      10    RF      0.9986     0.9989   0.0632    0.2195  0.5055        False
5      10   XGB      0.9978     0.9979   0.7515    0.0442  1.0000        False
6      15    LR      0.9991     0.9959   0.0013   -0.7028  0.0161         True
7      15    RF      0.9998     0.9995   0.0061   -0.5735  0.0611        False
8      15   XGB      0.9989     0.9978   0.0031   -0.5329  0.0337         True
9      20    LR      0.9997     0.9999   0.0702    0.4255  0.5055        False
10     20    RF      0.9998     0.9998   0.9153    0.0903  1.0000        False
11     20   XGB      0.9989     0.9989   0.7825   -0.0166  1.0000        False

# SENSITIVITY ANALYSIS (Complete-Case, n=158)

Identical pipeline, applied to the 158 rows with zero missing values — no imputation step at all. If the Primary and Sensitivity conclusions agree, the imputation choice wasn't driving the results.

## 1. Baseline (80/20 split)

In [17]:

# =============================================================================
# SENSITIVITY: TRAIN-TEST SPLIT + SCALING (no imputation needed)
# =============================================================================

Xs_train, Xs_test, ys_train, ys_test = train_test_split(
    X_sensitivity, y_sensitivity, test_size=0.2, random_state=42, stratify=y_sensitivity
)

scaler_s = StandardScaler()
Xs_train_scaled = pd.DataFrame(scaler_s.fit_transform(Xs_train), columns=Xs_train.columns)
Xs_test_scaled = pd.DataFrame(scaler_s.transform(Xs_test), columns=Xs_test.columns)
ys_train = ys_train.reset_index(drop=True)
ys_test = ys_test.reset_index(drop=True)

print("SENSITIVITY split:", Xs_train_scaled.shape, Xs_test_scaled.shape)

SENSITIVITY split: (126, 24) (32, 24)

In [18]:
# =============================================================================
# SENSITIVITY: LASSO BASELINE TOP-K
# =============================================================================

lasso_selector_s = LogisticRegression(
    penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
    class_weight="balanced", random_state=42
)
lasso_selector_s.fit(Xs_train_scaled, ys_train)

lasso_scores_s = pd.DataFrame({
    "Feature": Xs_train_scaled.columns,
    "LASSO Coefficient": lasso_selector_s.coef_[0],
    "LASSO Score": np.abs(lasso_selector_s.coef_[0])
}).sort_values("LASSO Score", ascending=False).reset_index(drop=True)

display(lasso_scores_s)

lasso_results_s = {}
for k in k_values:
    top_features = lasso_scores_s.head(k)["Feature"].tolist()
    mask = Xs_train_scaled.columns.isin(top_features)
    lasso_results_s[k] = {
        "features": top_features,
        "X_train": Xs_train_scaled.loc[:, mask],
        "X_test": Xs_test_scaled.loc[:, mask]
    }
    print(f"Top-{k}:", top_features)

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

   Feature  LASSO Coefficient  LASSO Score
0       al           1.750828     1.750828
1       sg          -0.229718     0.229718
2      htn           0.226350     0.226350
3     hemo          -0.116927     0.116927
4      pcv          -0.112393     0.112393
5       su           0.000000     0.000000
6       bp           0.000000     0.000000
7      age           0.000000     0.000000
8      pcc           0.000000     0.000000
9       pc           0.000000     0.000000
10     rbc           0.000000     0.000000
11      ba           0.000000     0.000000
12      sc           0.000000     0.000000
13      bu           0.000000     0.000000
14     pot           0.000000     0.000000
15     bgr           0.000000     0.000000
16     sod           0.000000     0.000000
17      wc           0.000000     0.000000
18      rc           0.000000     0.000000
19      dm           0.000000     0.000000
20     cad           0.000000     0.000000
21   appet           0.000000     0.000000
22      pe           0.000000     0.000000
23     ane           0.000000     0.000000

Top-5: ['al', 'sg', 'htn', 'hemo', 'pcv']
Top-10: ['al', 'sg', 'htn', 'hemo', 'pcv', 'su', 'bp', 'age', 'pcc', 'pc']
Top-15: ['al', 'sg', 'htn', 'hemo', 'pcv', 'su', 'bp', 'age', 'pcc', 'pc', 'rbc', 'ba', 'sc', 'bu', 'pot']
Top-20: ['al', 'sg', 'htn', 'hemo', 'pcv', 'su', 'bp', 'age', 'pcc', 'pc', 'rbc', 'ba', 'sc', 'bu', 'pot', 'bgr', 'sod', 'wc', 'rc', 'dm']

In [19]:
# =============================================================================
# SENSITIVITY: LASSO BASELINE MODEL EVALUATION
# =============================================================================

sensitivity_baseline_results = []
for k in k_values:
    Xtr, Xts = lasso_results_s[k]["X_train"], lasso_results_s[k]["X_test"]
    models = make_models(ys_train)
    for model_name, model in models.items():
        model.fit(Xtr, ys_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        sensitivity_baseline_results.append({
            "Method": "LASSO", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(ys_test, y_pred),
            "F1 Score": f1_score(ys_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(ys_test, y_prob)
        })

sensitivity_baseline_df = pd.DataFrame(sensitivity_baseline_results)
display(sensitivity_baseline_df)

   Method  Top-K Model  Accuracy  F1 Score  ROC-AUC
0   LASSO      5    LR   1.00000  1.000000      1.0
1   LASSO      5    RF   1.00000  1.000000      1.0
2   LASSO      5   XGB   0.96875  0.941176      1.0
3   LASSO     10    LR   1.00000  1.000000      1.0
4   LASSO     10    RF   1.00000  1.000000      1.0
5   LASSO     10   XGB   0.96875  0.941176      1.0
6   LASSO     15    LR   1.00000  1.000000      1.0
7   LASSO     15    RF   1.00000  1.000000      1.0
8   LASSO     15   XGB   0.96875  0.941176      1.0
9   LASSO     20    LR   1.00000  1.000000      1.0
10  LASSO     20    RF   1.00000  1.000000      1.0
11  LASSO     20   XGB   0.96875  0.941176      1.0

In [20]:
# =============================================================================
# SENSITIVITY: RANK FUSION DODA + EVALUATION
# =============================================================================

sensitivity_doda_results_by_k = {}
for k in k_values:
    operator = SklearnAdapter(
        LogisticRegression(
            penalty="l1", solver="liblinear", C=0.1, max_iter=2000,
            class_weight="balanced", random_state=42
        )
    )
    selector = DODASelector(operators=[operator], provider=provider, fusion=RankFusion(), top_k=k)
    X_train_sel = selector.fit_transform(Xs_train_scaled, ys_train)
    X_test_sel = selector.transform(Xs_test_scaled)
    features = selector.get_selected_features()
    sensitivity_doda_results_by_k[k] = {"X_train": X_train_sel, "X_test": X_test_sel, "features": features}
    print(f"Top-{k}:", features)

sensitivity_doda_results = []
for k in k_values:
    Xtr, Xts = sensitivity_doda_results_by_k[k]["X_train"], sensitivity_doda_results_by_k[k]["X_test"]
    models = make_models(ys_train)
    for model_name, model in models.items():
        model.fit(Xtr, ys_train)
        y_pred, y_prob = model.predict(Xts), model.predict_proba(Xts)[:, 1]
        sensitivity_doda_results.append({
            "Method": "LASSO + Rank Fusion", "Top-K": k, "Model": model_name,
            "Accuracy": accuracy_score(ys_test, y_pred),
            "F1 Score": f1_score(ys_test, y_pred, zero_division=0),
            "ROC-AUC": roc_auc_score(ys_test, y_prob)
        })

sensitivity_doda_df = pd.DataFrame(sensitivity_doda_results)
sensitivity_comparison_df = pd.concat([sensitivity_baseline_df, sensitivity_doda_df], ignore_index=True)
display(sensitivity_comparison_df)

os.makedirs("../../../results/ckd/sensitivity", exist_ok=True)
sensitivity_comparison_df.to_csv("../../../results/ckd/sensitivity/lasso_rankfusion_80_20_comparison.csv", index=False)

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.13120538804984533), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.06678364150888742), 'pcv': np.float64(0.06419443534788975), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.1292815936327504), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.0315136476426799, 'al': 0.03278688524590164, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.030776515151515152, 'bu': 0.031024531024531024, 'sc': 0.031544957774465976, 'sod': 0.030776515151515152, 'pot': 0.031024531024531024, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.03007688828584351, 'rc': 0.030536130536130537, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 5 Features Selected: ['al', 'htn', 'sc', 'sg', 'hemo']
Top-5: ['al', 'htn', 'sc', 'sg', 'hemo']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.13120538804984533), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.06678364150888742), 'pcv': np.float64(0.06419443534788975), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.1292815936327504), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.0315136476426799, 'al': 0.03278688524590164, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.030776515151515152, 'bu': 0.031024531024531024, 'sc': 0.031544957774465976, 'sod': 0.030776515151515152, 'pot': 0.031024531024531024, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.03007688828584351, 'rc': 0.030536130536130537, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 10 Features Selected: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot']
Top-10: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.13120538804984533), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.06678364150888742), 'pcv': np.float64(0.06419443534788975), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.1292815936327504), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.0315136476426799, 'al': 0.03278688524590164, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.030776515151515152, 'bu': 0.031024531024531024, 'sc': 0.031544957774465976, 'sod': 0.030776515151515152, 'pot': 0.031024531024531024, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.03007688828584351, 'rc': 0.030536130536130537, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 15 Features Selected: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot', 'pcv', 'age', 'bgr', 'sod', 'cad']
Top-15: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot', 'pcv', 'age', 'bgr', 'sod', 'cad']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024094BA8590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.2297180924640198), 'al': np.float64(1.7508281929454697), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.11692668238132342), 'pcv': np.float64(0.11239342723730059), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.22634985896113893), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.13120538804984533), 'al': np.float64(1.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0), 'bu': np.float64(0.0), 'sc': np.float64(0.0), 'sod': np.float64(0.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.06678364150888742), 'pcv': np.float64(0.06419443534788975), 'wc': np.float64(0.0), 'rc': np.float64(0.0), 'htn': np.float64(0.1292815936327504), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.0315136476426799, 'al': 0.03278688524590164, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.030776515151515152, 'bu': 0.031024531024531024, 'sc': 0.031544957774465976, 'sod': 0.030776515151515152, 'pot': 0.031024531024531024, 'hemo': 0.03149801587301587, 'pcv': 0.031009615384615385, 'wc': 0.03007688828584351, 'rc': 0.030536130536130537, 'htn': 0.03200204813108039, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 20 Features Selected: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot', 'pcv', 'age', 'bgr', 'sod', 'cad', 'pe', 'ane', 'rc', 'su', 'pc']
Top-20: ['al', 'htn', 'sc', 'sg', 'hemo', 'rbc', 'dm', 'bp', 'bu', 'pot', 'pcv', 'age', 'bgr', 'sod', 'cad', 'pe', 'ane', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

                 Method  Top-K Model  Accuracy  F1 Score  ROC-AUC
0                 LASSO      5    LR   1.00000  1.000000      1.0
1                 LASSO      5    RF   1.00000  1.000000      1.0
2                 LASSO      5   XGB   0.96875  0.941176      1.0
3                 LASSO     10    LR   1.00000  1.000000      1.0
4                 LASSO     10    RF   1.00000  1.000000      1.0
5                 LASSO     10   XGB   0.96875  0.941176      1.0
6                 LASSO     15    LR   1.00000  1.000000      1.0
7                 LASSO     15    RF   1.00000  1.000000      1.0
8                 LASSO     15   XGB   0.96875  0.941176      1.0
9                 LASSO     20    LR   1.00000  1.000000      1.0
10                LASSO     20    RF   1.00000  1.000000      1.0
11                LASSO     20   XGB   0.96875  0.941176      1.0
12  LASSO + Rank Fusion      5    LR   1.00000  1.000000      1.0
13  LASSO + Rank Fusion      5    RF   0.96875  0.941176      1.0
14  LASSO + Rank Fusion      5   XGB   0.96875  0.941176      1.0
15  LASSO + Rank Fusion     10    LR   1.00000  1.000000      1.0
16  LASSO + Rank Fusion     10    RF   0.96875  0.941176      1.0
17  LASSO + Rank Fusion     10   XGB   0.96875  0.941176      1.0
18  LASSO + Rank Fusion     15    LR   1.00000  1.000000      1.0
19  LASSO + Rank Fusion     15    RF   1.00000  1.000000      1.0
20  LASSO + Rank Fusion     15   XGB   0.96875  0.941176      1.0
21  LASSO + Rank Fusion     20    LR   1.00000  1.000000      1.0
22  LASSO + Rank Fusion     20    RF   1.00000  1.000000      1.0
23  LASSO + Rank Fusion     20   XGB   0.96875  0.941176      1.0

## 2. Feature-Selection Stability (25-run repeated CV)

In [21]:
# =============================================================================
# SENSITIVITY: STABILITY ANALYSIS
# =============================================================================

sensitivity_jaccard_df = run_stability_analysis(
    X_sensitivity, y_sensitivity, k_values, do_impute=False, label="SENSITIVITY"
)

sensitivity_stability_summary = sensitivity_jaccard_df.groupby(["Top_K", "Method"])["Jaccard"].agg(
    ["mean", "std"]
).reset_index()
print("\n" + "=" * 70)
print("SENSITIVITY STABILITY SUMMARY")
print("=" * 70)
display(sensitivity_stability_summary)

======================================================================
SENSITIVITY STABILITY — TOP-5
======================================================================
LASSO: mean Jaccard = 0.8844 (std 0.1586)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C4BEF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCA9F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DC8770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCBA10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E01F10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E028D0>
DODA Pipeline Started
Running: LogisticRegression

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E01970>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13228988141288872), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25828391645266763), 'bu': np.float64(0.287856830980005), 'sc': np.float64(0.0), 'sod': np.float64(0.23727834248982116), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020937672545559964), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C25D30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1286970412121136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24279605415319014), 'bu': np.float64(0.2734093522083297), 'sc': np.float64(0.0), 'sod': np.float64(0.2461388333068622), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023546010025447843), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C247D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1039471182166854), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.16405066170035731), 'bu': np.float64(0.40070896519133564), 'sc': np.float64(0.0), 'sod': np.float64(0.1571598527129387), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0016473321915155955), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCAB70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2463805619297823), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.36424924236615785), 'bu': np.float64(0.6635467843607106), 'sc': np.float64(0.0), 'sod': np.float64(0.853533376102596), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0059428661205443096), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DCA9F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.023319361316268876), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34143885277580244), 'bu': np.float64(0.88646900045944), 'sc': np.float64(0.0), 'sod': np.float64(1.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.6320916106007236), 'wc': np.float64(0.007475057551387546), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E037D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFAF90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFA150>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF9C10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFB590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFB110>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DFADB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD4530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD5190>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD6750>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD68D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD7B30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

LASSO: mean Jaccard = 1.0000 (std 0.0000)
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD5CD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD5850>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD4350>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD6C30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD52B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']
Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DD7050>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

   Top_K Method      mean       std
0      5   DODA  0.813333  0.165739
1      5  LASSO  0.884444  0.158901
2     10   DODA  0.939394  0.085853
3     10  LASSO  1.000000  0.000000
4     15   DODA  1.000000  0.000000
5     15  LASSO  1.000000  0.000000
6     20   DODA  0.992381  0.025881
7     20  LASSO  1.000000  0.000000

In [22]:
sensitivity_stability_test = wilcoxon_holm_test(sensitivity_jaccard_df, ["Top_K"], value_col="Jaccard")
print("=" * 70)
print("SENSITIVITY — LASSO vs DODA STABILITY: SIGNIFICANCE TEST")
print("=" * 70)
display(sensitivity_stability_test.round(4))

======================================================================
SENSITIVITY — LASSO vs DODA STABILITY: SIGNIFICANCE TEST
======================================================================

   Top_K  LASSO_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0      5      0.8844     0.8133      0.0   -0.4282     0.0         True
1     10      1.0000     0.9394      0.0   -0.8937     0.0         True
2     15      1.0000     1.0000      1.0    0.0000     1.0        False
3     20      1.0000     0.9924      0.0   -0.4079     0.0         True

## 3. Predictive Performance (25-run repeated CV)

In [23]:
# =============================================================================
# SENSITIVITY: CV PREDICTIVE PERFORMANCE
# =============================================================================

sensitivity_cv_results = run_cv_performance(
    X_sensitivity, y_sensitivity, k_values, do_impute=False, label="SENSITIVITY"
)

sensitivity_cv_summary = sensitivity_cv_results.groupby(["Top_K", "Method", "Model"]).agg(
    {"Accuracy": ["mean", "std"], "F1": ["mean", "std"], "ROC_AUC": ["mean", "std"]}
).reset_index()
sensitivity_cv_summary.columns = ["Top_K", "Method", "Model", "Acc_Mean", "Acc_STD",
                                   "F1_Mean", "F1_STD", "AUC_Mean", "AUC_STD"]

sensitivity_cv_results.to_csv("../../../results/ckd/sensitivity/cv_performance_runs.csv", index=False)
sensitivity_cv_summary.to_csv("../../../results/ckd/sensitivity/cv_performance_summary.csv", index=False)

print("=" * 70)
print("SENSITIVITY CV PERFORMANCE SUMMARY")
print("=" * 70)
display(sensitivity_cv_summary.round(4))

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC2E70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3BF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3DD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01978992550233362), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06327604596869596), 'bu': np.float64(0.07898341148757178), 'sc': np.float64(0.0), 'sod': np.float64(0.05456414802826558), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24904010277258648), 'wc': np.float64(0.0005038247590906257), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.07946481422875493), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25407974564834296), 'bu': np.float64(0.3171513768595586), 'sc': np.float64(0.0), 'sod': np.float64(0.21909783774098177), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020230667811388533), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C26E10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3830>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C27650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC32F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.022784081226257906), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03740821539100214), 'bu': np.float64(0.08605498336044488), 'sc': np.float64(0.0), 'sod': np.float64(0.02130089699847802), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.270530553466584), 'wc': np.float64(0.0003571151012039907), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.08421999265629049), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.1382772293615361), 'bu': np.float64(0.3180970957170441), 'sc': np.float64(0.0), 'sod': np.float64(0.07873749092488036), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0013200545987427687), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C26870>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C26E70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD5B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8C890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03641017148849459), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06034960551689444), 'bu': np.float64(0.07433474363333772), 'sc': np.float64(0.0), 'sod': np.float64(0.08034683528021216), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.17660580425729275), 'wc': np.float64(0.0005101293588671355), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.20616633548153088), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34171926438483613), 'bu': np.float64(0.42090770428496915), 'sc': np.float64(0.0), 'sod': np.float64(0.45495013948214746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002888519780040413), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C26750>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8CA70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC1430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029444920184473877), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06226785352398292), 'bu': np.float64(0.07818311103371624), 'sc': np.float64(0.0), 'sod': np.float64(0.06767488965113254), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2170548287335448), 'wc': np.float64(0.0005111860588809432), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13565660048328287), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.28687614962218855), 'bu': np.float64(0.360199823656968), 'sc': np.float64(0.0), 'sod': np.float64(0.3117870726304358), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023551010676130684), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3B90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAF890>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC1F70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.018563374535763802), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05046243792152644), 'bu': np.float64(0.07596314854491666), 'sc': np.float64(0.0), 'sod': np.float64(0.09654202436718778), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18340908405379755), 'wc': np.float64(0.0008883601694733878), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.10121295044643913), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.27513597912481147), 'bu': np.float64(0.41417331609722857), 'sc': np.float64(0.0), 'sod': np.float64(0.52637536938394), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.004843599618069158), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

SENSITIVITY: completed 5/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024095C4A5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8F6B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099FC9850>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8F530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02079326460773257), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06270570507809431), 'bu': np.float64(0.07217517758504267), 'sc': np.float64(0.0), 'sod': np.float64(0.07018117508761655), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.18963164810799923), 'wc': np.float64(0.0004803117672688844), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.10965081417153727), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.33067109685394963), 'bu': np.float64(0.3806072367410812), 'sc': np.float64(0.0), 'sod': np.float64(0.37009210112252405), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002532867124560014), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8D7F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13228988141288872), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25828391645266763), 'bu': np.float64(0.287856830980005), 'sc': np.float64(0.0), 'sod': np.float64(0.23727834248982116), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020937672545559964), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8D430>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13228988141288872), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25828391645266763), 'bu': np.float64(0.287856830980005), 'sc': np.float64(0.0), 'sod': np.float64(0.23727834248982116), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020937672545559964), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8DD30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13228988141288872), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25828391645266763), 'bu': np.float64(0.287856830980005), 'sc': np.float64(0.0), 'sod': np.float64(0.23727834248982116), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020937672545559964), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8F590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.033292908697381544), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06500136485588384), 'bu': np.float64(0.0724438716656162), 'sc': np.float64(0.0), 'sod': np.float64(0.059714969187431695), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2516663280804626), 'wc': np.float64(0.0005269307168092188), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13228988141288872), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25828391645266763), 'bu': np.float64(0.287856830980005), 'sc': np.float64(0.0), 'sod': np.float64(0.23727834248982116), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020937672545559964), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099FCBF50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1286970412121136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24279605415319014), 'bu': np.float64(0.2734093522083297), 'sc': np.float64(0.0), 'sod': np.float64(0.2461388333068622), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023546010025447843), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC12B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1286970412121136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24279605415319014), 'bu': np.float64(0.2734093522083297), 'sc': np.float64(0.0), 'sod': np.float64(0.2461388333068622), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023546010025447843), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC3770>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1286970412121136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24279605415319014), 'bu': np.float64(0.2734093522083297), 'sc': np.float64(0.0), 'sod': np.float64(0.2461388333068622), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023546010025447843), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFB90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.030108391364066844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05680160593627808), 'bu': np.float64(0.06396352007282632), 'sc': np.float64(0.0), 'sod': np.float64(0.05758364180947677), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2339478132558101), 'wc': np.float64(0.0005508537556352905), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1286970412121136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24279605415319014), 'bu': np.float64(0.2734093522083297), 'sc': np.float64(0.0), 'sod': np.float64(0.2461388333068622), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0023546010025447843), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2CF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1039471182166854), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.16405066170035731), 'bu': np.float64(0.40070896519133564), 'sc': np.float64(0.0), 'sod': np.float64(0.1571598527129387), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0016473321915155955), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8D3D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1039471182166854), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.16405066170035731), 'bu': np.float64(0.40070896519133564), 'sc': np.float64(0.0), 'sod': np.float64(0.1571598527129387), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0016473321915155955), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8DEB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1039471182166854), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.16405066170035731), 'bu': np.float64(0.40070896519133564), 'sc': np.float64(0.0), 'sod': np.float64(0.1571598527129387), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0016473321915155955), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8FD70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.024293447105247588), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.038340226655353055), 'bu': np.float64(0.09364956159902112), 'sc': np.float64(0.0), 'sod': np.float64(0.03672977793373233), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23370967393830114), 'wc': np.float64(0.0003849974693471769), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1039471182166854), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.16405066170035731), 'bu': np.float64(0.40070896519133564), 'sc': np.float64(0.0), 'sod': np.float64(0.1571598527129387), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0016473321915155955), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EADAF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2463805619297823), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.36424924236615785), 'bu': np.float64(0.6635467843607106), 'sc': np.float64(0.0), 'sod': np.float64(0.853533376102596), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0059428661205443096), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF23F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2463805619297823), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.36424924236615785), 'bu': np.float64(0.6635467843607106), 'sc': np.float64(0.0), 'sod': np.float64(0.853533376102596), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0059428661205443096), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFBF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2463805619297823), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.36424924236615785), 'bu': np.float64(0.6635467843607106), 'sc': np.float64(0.0), 'sod': np.float64(0.853533376102596), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0059428661205443096), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD610>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.034980320055200485), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05171493634901197), 'bu': np.float64(0.09420823910269285), 'sc': np.float64(0.0), 'sod': np.float64(0.12118192458045345), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14197678494283883), 'wc': np.float64(0.0008437490251406024), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2463805619297823), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.36424924236615785), 'bu': np.float64(0.6635467843607106), 'sc': np.float64(0.0), 'sod': np.float64(0.853533376102596), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0059428661205443096), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

SENSITIVITY: completed 10/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8DCD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.023319361316268876), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34143885277580244), 'bu': np.float64(0.88646900045944), 'sc': np.float64(0.0), 'sod': np.float64(1.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.6320916106007236), 'wc': np.float64(0.007475057551387546), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.032018442622950824, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.03149801587301587, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['sod', 'bu', 'pcv', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E5D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.023319361316268876), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34143885277580244), 'bu': np.float64(0.88646900045944), 'sc': np.float64(0.0), 'sod': np.float64(1.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.6320916106007236), 'wc': np.float64(0.007475057551387546), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.032018442622950824, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.03149801587301587, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['sod', 'bu', 'pcv', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E6F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.023319361316268876), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34143885277580244), 'bu': np.float64(0.88646900045944), 'sc': np.float64(0.0), 'sod': np.float64(1.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.6320916106007236), 'wc': np.float64(0.007475057551387546), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.032018442622950824, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.03149801587301587, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['sod', 'bu', 'pcv', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8ED50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0032568689945688444), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.047686623920135396), 'bu': np.float64(0.12380756758670637), 'sc': np.float64(0.0), 'sod': np.float64(0.13966373051120712), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.08828027236133433), 'wc': np.float64(0.001043994423412754), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.023319361316268876), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.34143885277580244), 'bu': np.float64(0.88646900045944), 'sc': np.float64(0.0), 'sod': np.float64(1.0), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.6320916106007236), 'wc': np.float64(0.007475057551387546), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.032018442622950824, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.03149801587301587, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['sod', 'bu', 'pcv', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD490>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14034482735374235), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2454571369959144), 'bu': np.float64(0.2720701516715029), 'sc': np.float64(0.0), 'sod': np.float64(0.22316984882385815), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002034158496194697), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8DFD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14034482735374235), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2454571369959144), 'bu': np.float64(0.2720701516715029), 'sc': np.float64(0.0), 'sod': np.float64(0.22316984882385815), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002034158496194697), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14034482735374235), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2454571369959144), 'bu': np.float64(0.2720701516715029), 'sc': np.float64(0.0), 'sod': np.float64(0.22316984882385815), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002034158496194697), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8C8F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03566456688193166), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.062375811379020665), 'bu': np.float64(0.0691387370936608), 'sc': np.float64(0.0), 'sod': np.float64(0.05671214357866985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2541209929457415), 'wc': np.float64(0.0005169223768620127), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14034482735374235), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2454571369959144), 'bu': np.float64(0.2720701516715029), 'sc': np.float64(0.0), 'sod': np.float64(0.22316984882385815), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002034158496194697), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8EE70>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.09595210688750792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.30669423301354054), 'bu': np.float64(0.33740332374391535), 'sc': np.float64(0.0), 'sod': np.float64(0.3354390175325718), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0026530191661340284), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8C230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.09595210688750792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.30669423301354054), 'bu': np.float64(0.33740332374391535), 'sc': np.float64(0.0), 'sod': np.float64(0.3354390175325718), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0026530191661340284), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8FBF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.09595210688750792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.30669423301354054), 'bu': np.float64(0.33740332374391535), 'sc': np.float64(0.0), 'sod': np.float64(0.3354390175325718), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0026530191661340284), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8ED50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.01842913303316492), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.05890552072334819), 'bu': np.float64(0.06480369155831596), 'sc': np.float64(0.0), 'sod': np.float64(0.06442641521013569), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.19206595489112935), 'wc': np.float64(0.0005095546594879999), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.09595210688750792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.30669423301354054), 'bu': np.float64(0.33740332374391535), 'sc': np.float64(0.0), 'sod': np.float64(0.3354390175325718), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0026530191661340284), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8C290>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1392401675593961), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25845223079656165), 'bu': np.float64(0.30933946144755387), 'sc': np.float64(0.0), 'sod': np.float64(0.2526508442089678), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020682968213115837), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAEE10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1392401675593961), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25845223079656165), 'bu': np.float64(0.30933946144755387), 'sc': np.float64(0.0), 'sod': np.float64(0.2526508442089678), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020682968213115837), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E630>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1392401675593961), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25845223079656165), 'bu': np.float64(0.30933946144755387), 'sc': np.float64(0.0), 'sod': np.float64(0.2526508442089678), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020682968213115837), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8D970>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03362993325446423), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06242258554772346), 'bu': np.float64(0.07471310630975418), 'sc': np.float64(0.0), 'sod': np.float64(0.06102140766102706), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24152465372550347), 'wc': np.float64(0.0004995446735688398), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.1392401675593961), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.25845223079656165), 'bu': np.float64(0.30933946144755387), 'sc': np.float64(0.0), 'sod': np.float64(0.2526508442089678), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020682968213115837), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF33B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.132657841063882), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14112964199590422), 'bu': np.float64(0.3351267017858002), 'sc': np.float64(0.0), 'sod': np.float64(0.1167512551930827), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001530174528182592), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC0530>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.132657841063882), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14112964199590422), 'bu': np.float64(0.3351267017858002), 'sc': np.float64(0.0), 'sod': np.float64(0.1167512551930827), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001530174528182592), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2CF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.132657841063882), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14112964199590422), 'bu': np.float64(0.3351267017858002), 'sc': np.float64(0.0), 'sod': np.float64(0.1167512551930827), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001530174528182592), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3BF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03532821810591819), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03758435033810397), 'bu': np.float64(0.08924786592979769), 'sc': np.float64(0.0), 'sod': np.float64(0.03109212221850281), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.26631081753324876), 'wc': np.float64(0.0004075020295688593), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.132657841063882), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14112964199590422), 'bu': np.float64(0.3351267017858002), 'sc': np.float64(0.0), 'sod': np.float64(0.1167512551930827), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001530174528182592), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03125, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'age', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

SENSITIVITY: completed 15/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8F0B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.12691674048298326), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2620221865668203), 'bu': np.float64(0.30485150478795603), 'sc': np.float64(0.0), 'sod': np.float64(0.24335231735895746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001992019328247341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099FD51F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.12691674048298326), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2620221865668203), 'bu': np.float64(0.30485150478795603), 'sc': np.float64(0.0), 'sod': np.float64(0.24335231735895746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001992019328247341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF1AF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.12691674048298326), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2620221865668203), 'bu': np.float64(0.30485150478795603), 'sc': np.float64(0.0), 'sod': np.float64(0.24335231735895746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001992019328247341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF1CD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.02985842507937617), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06164332456827236), 'bu': np.float64(0.07171934751402398), 'sc': np.float64(0.0), 'sod': np.float64(0.05725105221032076), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.23525994258716035), 'wc': np.float64(0.0004686423527959832), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.12691674048298326), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2620221865668203), 'bu': np.float64(0.30485150478795603), 'sc': np.float64(0.0), 'sod': np.float64(0.24335231735895746), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.001992019328247341), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC2CF0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14122504051315526), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24954504367370225), 'bu': np.float64(0.2764116871152206), 'sc': np.float64(0.0), 'sod': np.float64(0.2561741488335373), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002349418833415814), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099E8E9F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14122504051315526), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24954504367370225), 'bu': np.float64(0.2764116871152206), 'sc': np.float64(0.0), 'sod': np.float64(0.2561741488335373), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002349418833415814), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099FCB650>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14122504051315526), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24954504367370225), 'bu': np.float64(0.2764116871152206), 'sc': np.float64(0.0), 'sod': np.float64(0.2561741488335373), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002349418833415814), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC3AD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03261239944571358), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.057626201517900995), 'bu': np.float64(0.06383038247969536), 'sc': np.float64(0.0), 'sod': np.float64(0.0591570279538831), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2309250493199589), 'wc': np.float64(0.0005425396599797872), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.14122504051315526), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24954504367370225), 'bu': np.float64(0.2764116871152206), 'sc': np.float64(0.0), 'sod': np.float64(0.2561741488335373), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.002349418833415814), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03149801587301587, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'sod', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD4F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.16947859463419251), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24264763462265435), 'bu': np.float64(0.29232036170625436), 'sc': np.float64(0.0), 'sod': np.float64(0.22778875789292644), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019472606954711667), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD7F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.16947859463419251), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24264763462265435), 'bu': np.float64(0.29232036170625436), 'sc': np.float64(0.0), 'sod': np.float64(0.22778875789292644), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019472606954711667), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAF230>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.16947859463419251), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24264763462265435), 'bu': np.float64(0.29232036170625436), 'sc': np.float64(0.0), 'sod': np.float64(0.22778875789292644), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019472606954711667), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAE8D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.04333661380661281), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06204634193142254), 'bu': np.float64(0.07474793291988682), 'sc': np.float64(0.0), 'sod': np.float64(0.05824684498712602), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2557055296579005), 'wc': np.float64(0.0004979253275174664), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.16947859463419251), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.24264763462265435), 'bu': np.float64(0.29232036170625436), 'sc': np.float64(0.0), 'sod': np.float64(0.22778875789292644), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019472606954711667), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2C90>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.450353765696873), 'bu': np.float64(0.6348893665637597), 'sc': np.float64(0.0), 'sod': np.float64(0.7307950641692249), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.00489913890798742), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.030536130536130537, 'al': 0.031544957774465976, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.031544957774465976, 'sod': 0.031754032258064516, 'pot': 0.031024531024531024, 'hemo': 0.031024531024531024, 'pcv': 0.032018442622950824, 'wc': 0.030309988518943745, 'rc': 0.030536130536130537, 'htn': 0.03128054740957967, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC27B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.450353765696873), 'bu': np.float64(0.6348893665637597), 'sc': np.float64(0.0), 'sod': np.float64(0.7307950641692249), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.00489913890798742), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.030536130536130537, 'al': 0.031544957774465976, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.031544957774465976, 'sod': 0.031754032258064516, 'pot': 0.031024531024531024, 'hemo': 0.031024531024531024, 'pcv': 0.032018442622950824, 'wc': 0.030309988518943745, 'rc': 0.030536130536130537, 'htn': 0.03128054740957967, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'rbc', 'htn', 'dm', 'bgr', 'bp']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099FD6DB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.450353765696873), 'bu': np.float64(0.6348893665637597), 'sc': np.float64(0.0), 'sod': np.float64(0.7307950641692249), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.00489913890798742), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.030536130536130537, 'al': 0.031544957774465976, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.031544957774465976, 'sod': 0.031754032258064516, 'pot': 0.031024531024531024, 'hemo': 0.031024531024531024, 'pcv': 0.032018442622950824, 'wc': 0.030309988518943745, 'rc': 0.030536130536130537, 'htn': 0.03128054740957967, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'rbc', 'htn', 'dm', 'bgr', 'bp', 'pot', 'hemo', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF3290>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06548473563163554), 'bu': np.float64(0.0923175634169079), 'sc': np.float64(0.0), 'sod': np.float64(0.10626295419995886), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14540732335235412), 'wc': np.float64(0.0007123706753418259), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.450353765696873), 'bu': np.float64(0.6348893665637597), 'sc': np.float64(0.0), 'sod': np.float64(0.7307950641692249), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.00489913890798742), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.030776515151515152, 'bp': 0.031024531024531024, 'sg': 0.030536130536130537, 'al': 0.031544957774465976, 'su': 0.030303030303030304, 'rbc': 0.03128054740957967, 'pc': 0.030303030303030304, 'pcc': 0.030303030303030304, 'ba': 0.03007688828584351, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.031544957774465976, 'sod': 0.031754032258064516, 'pot': 0.031024531024531024, 'hemo': 0.031024531024531024, 'pcv': 0.032018442622950824, 'wc': 0.030309988518943745, 'rc': 0.030536130536130537, 'htn': 0.03128054740957967, 'dm': 0.03128054740957967, 'cad': 0.030776515151515152, 'appet': 0.030303030303030304, 'pe': 0.030776515151515152, 'ane': 0.030776515151515152}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'rbc', 'htn', 'dm', 'bgr', 'bp', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'wc', 'su']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF0590>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.11836939361195786), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14814232469028643), 'bu': np.float64(0.358874177858525), 'sc': np.float64(0.0), 'sod': np.float64(0.14048134252149236), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017010091171520752), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF0FB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.11836939361195786), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14814232469028643), 'bu': np.float64(0.358874177858525), 'sc': np.float64(0.0), 'sod': np.float64(0.14048134252149236), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017010091171520752), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF1EB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.11836939361195786), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14814232469028643), 'bu': np.float64(0.358874177858525), 'sc': np.float64(0.0), 'sod': np.float64(0.14048134252149236), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017010091171520752), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EC3A10>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.029331583621838176), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.036709227377064765), 'bu': np.float64(0.0889279537249599), 'sc': np.float64(0.0), 'sod': np.float64(0.034810858784875796), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24779702528504846), 'wc': np.float64(0.00042150499921303074), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.11836939361195786), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.14814232469028643), 'bu': np.float64(0.358874177858525), 'sc': np.float64(0.0), 'sod': np.float64(0.14048134252149236), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017010091171520752), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

SENSITIVITY: completed 20/25 CV runs

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFE30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3982863344021144), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.4526479288174817), 'bu': np.float64(0.5283502228207919), 'sc': np.float64(0.0), 'sod': np.float64(0.6923279413131215), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.003049359744365867), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFAD0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3982863344021144), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.4526479288174817), 'bu': np.float64(0.5283502228207919), 'sc': np.float64(0.0), 'sod': np.float64(0.6923279413131215), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.003049359744365867), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFB30>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3982863344021144), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.4526479288174817), 'bu': np.float64(0.5283502228207919), 'sc': np.float64(0.0), 'sod': np.float64(0.6923279413131215), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.003049359744365867), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAF9B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.05499602012926074), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0625023568586245), 'bu': np.float64(0.07295545184388684), 'sc': np.float64(0.0), 'sod': np.float64(0.09559775997251474), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.13808161460477358), 'wc': np.float64(0.00042106051701283853), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.3982863344021144), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.4526479288174817), 'bu': np.float64(0.5283502228207919), 'sc': np.float64(0.0), 'sod': np.float64(0.6923279413131215), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.003049359744365867), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2930>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13224219400520792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.12828395528789077), 'bu': np.float64(0.264225309781843), 'sc': np.float64(0.0), 'sod': np.float64(0.1034527798742981), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017497057343210066), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03149801587301587, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'age', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2450>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13224219400520792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.12828395528789077), 'bu': np.float64(0.264225309781843), 'sc': np.float64(0.0), 'sod': np.float64(0.1034527798742981), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017497057343210066), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03149801587301587, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'age', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'sod']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF24B0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13224219400520792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.12828395528789077), 'bu': np.float64(0.264225309781843), 'sc': np.float64(0.0), 'sod': np.float64(0.1034527798742981), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017497057343210066), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03149801587301587, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'age', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF14F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03377715148136425), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.03276614262931089), 'bu': np.float64(0.067488129494889), 'sc': np.float64(0.0), 'sod': np.float64(0.026423791916555656), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.2554188678995605), 'wc': np.float64(0.0004469078578176406), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13224219400520792), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.12828395528789077), 'bu': np.float64(0.264225309781843), 'sc': np.float64(0.0), 'sod': np.float64(0.1034527798742981), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0017497057343210066), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03149801587301587, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.031009615384615385, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'age', 'al', 'sc', 'bgr', 'rbc', 'htn', 'dm', 'sod', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAE090>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.058141247947454136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2612820375123657), 'bu': np.float64(0.32261931337359434), 'sc': np.float64(0.0), 'sod': np.float64(0.2182610335989195), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020999599537646417), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAC110>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.058141247947454136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2612820375123657), 'bu': np.float64(0.32261931337359434), 'sc': np.float64(0.0), 'sod': np.float64(0.2182610335989195), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020999599537646417), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAE030>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.058141247947454136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2612820375123657), 'bu': np.float64(0.32261931337359434), 'sc': np.float64(0.0), 'sod': np.float64(0.2182610335989195), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020999599537646417), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAE930>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.014748272075124143), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.0662775346868676), 'bu': np.float64(0.08183652016935854), 'sc': np.float64(0.0), 'sod': np.float64(0.05536470613468536), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.25366280559462834), 'wc': np.float64(0.000532681733508305), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.058141247947454136), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2612820375123657), 'bu': np.float64(0.32261931337359434), 'sc': np.float64(0.0), 'sod': np.float64(0.2182610335989195), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0020999599537646417), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAC7D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2574532083600719), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.3733523585138804), 'bu': np.float64(0.6674420725544686), 'sc': np.float64(0.0), 'sod': np.float64(0.8782175418914223), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.006042577365520526), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF1E50>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2574532083600719), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.3733523585138804), 'bu': np.float64(0.6674420725544686), 'sc': np.float64(0.0), 'sod': np.float64(0.8782175418914223), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.006042577365520526), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF34D0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2574532083600719), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.3733523585138804), 'bu': np.float64(0.6674420725544686), 'sc': np.float64(0.0), 'sod': np.float64(0.8782175418914223), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.006042577365520526), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099DF2390>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.03653672682690065), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.052984669408828775), 'bu': np.float64(0.09472070219298553), 'sc': np.float64(0.0), 'sod': np.float64(0.12463311149652559), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.14191598954867438), 'wc': np.float64(0.0008575383462522672), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.0), 'bp': np.float64(0.2574532083600719), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.3733523585138804), 'bu': np.float64(0.6674420725544686), 'sc': np.float64(0.0), 'sod': np.float64(0.8782175418914223), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.006042577365520526), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.03055037313432836, 'bp': 0.03125763125763126, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03125, 'bu': 0.031746031746031744, 'sc': 0.03131881575727918, 'sod': 0.031754032258064516, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'sod', 'bu', 'al', 'sc', 'bp', 'bgr', 'rbc', 'htn', 'dm', 'pot', 'hemo', 'age', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAC470>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13856574224916965), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2494618492251671), 'bu': np.float64(0.3058086732745601), 'sc': np.float64(0.0), 'sod': np.float64(0.22992284878441985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019073290327672608), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 5 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAFFB0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13856574224916965), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2494618492251671), 'bu': np.float64(0.3058086732745601), 'sc': np.float64(0.0), 'sod': np.float64(0.22992284878441985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019073290327672608), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 10 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAD250>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13856574224916965), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2494618492251671), 'bu': np.float64(0.3058086732745601), 'sc': np.float64(0.0), 'sod': np.float64(0.22992284878441985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019073290327672608), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 15 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Provider inside knowledge engine: <doda.knowledge.providers.json_provider.JSONProvider object at 0x0000024099EAF8F0>
DODA Pipeline Started
Running: LogisticRegression
DODA feature order:
['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr']
Number of features: 24
Number of coefficients: 24
Operator Scores:
{'LogisticRegression_1': {'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}}
Resolving scores from: 1 operators

Raw Mathematical Scores
{'age': np.float64(0.03427300210165844), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.06170216637964849), 'bu': np.float64(0.07563905141140459), 'sc': np.float64(0.0), 'sod': np.float64(0.05686936865995058), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(0.24734109272137805), 'wc': np.float64(0.00047176084714386336), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Normalized Mathematical Scores
{'age': np.float64(0.13856574224916965), 'bp': np.float64(0.0), 'sg': np.float64(0.0), 'al': np.float64(0.0), 'su': np.float64(0.0), 'rbc': np.float64(0.0), 'pc': np.float64(0.0), 'pcc': np.float64(0.0), 'ba': np.float64(0.0), 'bgr': np.float64(0.2494618492251671), 'bu': np.float64(0.3058086732745601), 'sc': np.float64(0.0), 'sod': np.float64(0.22992284878441985), 'pot': np.float64(0.0), 'hemo': np.float64(0.0), 'pcv': np.float64(1.0), 'wc': np.float64(0.0019073290327672608), 'rc': np.float64(0.0), 'htn': np.float64(0.0), 'dm': np.float64(0.0), 'cad': np.float64(0.0), 'appet': np.float64(0.0), 'pe': np.float64(0.0), 'ane': np.float64(0.0)}

Clinical Weights
{'age': 0.6, 'bp': 0.7, 'sg': 0.5, 'al': 1.0, 'su': 0.4, 'rbc': 0.8, 'pc': 0.4, 'pcc': 0.4, 'ba': 0.3, 'bgr': 0.6, 'bu': 0.7, 'sc': 1.0, 'sod': 0.6, 'pot': 0.7, 'hemo': 0.7, 'pcv': 0.6, 'wc': 0.3, 'rc': 0.5, 'htn': 0.8, 'dm': 0.8, 'cad': 0.6, 'appet': 0.4, 'pe': 0.6, 'ane': 0.6}

Final DODA Scores
{'age': 0.031009615384615385, 'bp': 0.030798389007344232, 'sg': 0.030309988518943745, 'al': 0.03131881575727918, 'su': 0.03007688828584351, 'rbc': 0.031054405392392875, 'pc': 0.03007688828584351, 'pcc': 0.03007688828584351, 'ba': 0.029850746268656716, 'bgr': 0.03149801587301587, 'bu': 0.03200204813108039, 'sc': 0.03131881575727918, 'sod': 0.03125, 'pot': 0.030798389007344232, 'hemo': 0.030798389007344232, 'pcv': 0.032018442622950824, 'wc': 0.03007688828584351, 'rc': 0.030309988518943745, 'htn': 0.031054405392392875, 'dm': 0.031054405392392875, 'cad': 0.03055037313432836, 'appet': 0.03007688828584351, 'pe': 0.03055037313432836, 'ane': 0.03055037313432836}
Top 20 Features Selected: ['pcv', 'bu', 'bgr', 'al', 'sc', 'sod', 'rbc', 'htn', 'dm', 'age', 'bp', 'pot', 'hemo', 'cad', 'pe', 'ane', 'sg', 'rc', 'su', 'pc']

c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\johnm\msc_research\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

SENSITIVITY: completed 25/25 CV runs
======================================================================
SENSITIVITY CV PERFORMANCE SUMMARY
======================================================================

    Top_K Method Model  Acc_Mean  Acc_STD  F1_Mean  F1_STD  AUC_Mean  AUC_STD
0       5   DODA    LR    0.9949   0.0119   0.9900  0.0235    1.0000   0.0000
1       5   DODA    RF    0.9937   0.0129   0.9876  0.0254    1.0000   0.0000
2       5   DODA   XGB    0.9924   0.0138   0.9853  0.0268    1.0000   0.0000
3       5  LASSO    LR    0.9822   0.0161   0.9645  0.0322    0.9925   0.0141
4       5  LASSO    RF    0.9860   0.0162   0.9719  0.0324    1.0000   0.0000
5       5  LASSO   XGB    0.9936   0.0130   0.9873  0.0260    1.0000   0.0000
6      10   DODA    LR    0.9950   0.0118   0.9903  0.0228    1.0000   0.0000
7      10   DODA    RF    0.9937   0.0129   0.9876  0.0254    1.0000   0.0000
8      10   DODA   XGB    0.9898   0.0151   0.9799  0.0300    1.0000   0.0000
9      10  LASSO    LR    0.9872   0.0160   0.9743  0.0322    1.0000   0.0000
10     10  LASSO    RF    0.9936   0.0131   0.9870  0.0266    1.0000   0.0000
11     10  LASSO   XGB    0.9899   0.0151   0.9802  0.0295    1.0000   0.0000
12     15   DODA    LR    0.9962   0.0104   0.9929  0.0195    0.9983   0.0087
13     15   DODA    RF    0.9962   0.0106   0.9923  0.0213    1.0000   0.0000
14     15   DODA   XGB    0.9898   0.0151   0.9799  0.0300    0.9998   0.0011
15     15  LASSO    LR    0.9936   0.0131   0.9870  0.0266    1.0000   0.0000
16     15  LASSO    RF    0.9962   0.0105   0.9926  0.0204    1.0000   0.0000
17     15  LASSO   XGB    0.9937   0.0129   0.9876  0.0254    1.0000   0.0000
18     20   DODA    LR    0.9937   0.0129   0.9876  0.0254    1.0000   0.0000
19     20   DODA    RF    1.0000   0.0000   1.0000  0.0000    1.0000   0.0000
20     20   DODA   XGB    0.9898   0.0151   0.9799  0.0300    1.0000   0.0000
21     20  LASSO    LR    1.0000   0.0000   1.0000  0.0000    1.0000   0.0000
22     20  LASSO    RF    0.9974   0.0089   0.9947  0.0185    1.0000   0.0000
23     20  LASSO   XGB    0.9898   0.0151   0.9799  0.0300    1.0000   0.0000

In [24]:
sensitivity_perf_test = wilcoxon_holm_test(
    sensitivity_cv_results, ["Top_K", "Model"], value_col="ROC_AUC"
)
print("=" * 70)
print("SENSITIVITY — LASSO vs DODA ROC-AUC: SIGNIFICANCE TEST")
print("=" * 70)
display(sensitivity_perf_test.round(4))

======================================================================
SENSITIVITY — LASSO vs DODA ROC-AUC: SIGNIFICANCE TEST
======================================================================

    Top_K Model  LASSO_mean  DODA_mean  p_value  cohens_d  p_holm  significant
0       5    LR      0.9925     1.0000   0.0277    0.7044  0.3325        False
1       5    RF      1.0000     1.0000   1.0000    0.0000  1.0000        False
2       5   XGB      1.0000     1.0000   1.0000    0.0000  1.0000        False
3      10    LR      1.0000     1.0000   1.0000    0.0000  1.0000        False
4      10    RF      1.0000     1.0000   1.0000    0.0000  1.0000        False
5      10   XGB      1.0000     1.0000   1.0000   -0.2800  1.0000        False
6      15    LR      1.0000     0.9983   0.3173   -0.2828  1.0000        False
7      15    RF      1.0000     1.0000   1.0000   -0.2800  1.0000        False
8      15   XGB      1.0000     0.9998   0.3173   -0.2828  1.0000        False
9      20    LR      1.0000     1.0000   1.0000    0.0000  1.0000        False
10     20    RF      1.0000     1.0000   1.0000   -0.2800  1.0000        False
11     20   XGB      1.0000     1.0000   1.0000    0.0000  1.0000        False

# Primary vs. Sensitivity — Head-to-Head Comparison

In [25]:
# =============================================================================
# SIDE-BY-SIDE: STABILITY SUMMARY
# =============================================================================

primary_stability_summary["Analysis"] = "Primary (imputed, n=400)"
sensitivity_stability_summary["Analysis"] = "Sensitivity (complete-case, n=158)"

stability_side_by_side = pd.concat(
    [primary_stability_summary, sensitivity_stability_summary], ignore_index=True
).pivot_table(index=["Top_K", "Method"], columns="Analysis", values="mean").round(4)

print("=" * 70)
print("MEAN JACCARD STABILITY — PRIMARY vs SENSITIVITY")
print("=" * 70)
display(stability_side_by_side)

======================================================================
MEAN JACCARD STABILITY — PRIMARY vs SENSITIVITY
======================================================================

Analysis      Primary (imputed, n=400)  Sensitivity (complete-case, n=158)
Top_K Method
5     DODA                      1.0000                              0.8133
      LASSO                     1.0000                              0.8844
10    DODA                      0.9855                              0.9394
      LASSO                     0.9394                              1.0000
15    DODA                      1.0000                              1.0000
      LASSO                     1.0000                              1.0000
20    DODA                      1.0000                              0.9924
      LASSO                     1.0000                              1.0000

In [26]:
# =============================================================================
# SIDE-BY-SIDE: PREDICTIVE PERFORMANCE (ROC-AUC) SUMMARY
# =============================================================================

primary_auc = primary_cv_summary[["Top_K", "Method", "Model", "AUC_Mean"]].copy()
primary_auc["Analysis"] = "Primary"
sensitivity_auc = sensitivity_cv_summary[["Top_K", "Method", "Model", "AUC_Mean"]].copy()
sensitivity_auc["Analysis"] = "Sensitivity"

auc_side_by_side = pd.concat([primary_auc, sensitivity_auc], ignore_index=True).pivot_table(
    index=["Top_K", "Method", "Model"], columns="Analysis", values="AUC_Mean"
).round(4)

print("=" * 70)
print("MEAN ROC-AUC — PRIMARY vs SENSITIVITY")
print("=" * 70)
display(auc_side_by_side)

auc_side_by_side.to_csv("../../../results/ckd/lasso_primary_vs_sensitivity_auc_comparison.csv")
stability_side_by_side.to_csv("../../../results/ckd/lasso_primary_vs_sensitivity_stability_comparison.csv")

======================================================================
MEAN ROC-AUC — PRIMARY vs SENSITIVITY
======================================================================

Analysis            Primary  Sensitivity
Top_K Method Model
5     DODA   LR      0.9892       1.0000
             RF      0.9911       1.0000
             XGB     0.9895       1.0000
      LASSO  LR      0.9892       0.9925
             RF      0.9910       1.0000
             XGB     0.9896       1.0000
10    DODA   LR      0.9943       1.0000
             RF      0.9989       1.0000
             XGB     0.9979       1.0000
      LASSO  LR      0.9929       1.0000
             RF      0.9986       1.0000
             XGB     0.9978       1.0000
15    DODA   LR      0.9959       0.9983
             RF      0.9995       1.0000
             XGB     0.9978       0.9998
      LASSO  LR      0.9991       1.0000
             RF      0.9998       1.0000
             XGB     0.9989       1.0000
20    DODA   LR      0.9999       1.0000
             RF      0.9998       1.0000
             XGB     0.9989       1.0000
      LASSO  LR      0.9997       1.0000
             RF      0.9998       1.0000
             XGB     0.9989       1.0000